### PR TITLE
Rename paramSetByUser() to isParamSetByUser()

### LINKED ISSUE #6174: Naming of InputParameters::paramSetByUser()
Every other method to query things about the parameter in InputParameters starts with "is", but this one doesn't.  For consistency with function names like isParamValid(), isParamSetByAddParam(), etc, it should be renamed to isParamSetByUser().

### PR DESCRIPTION
**Pull request by bwspenc**
closes #6174

I'm submitting a merge request to trigger the tests on the apps to see if there are any apps that use this.

### CODE REVIEW

**Comment by bwspenc** [comment]
OK, looks like Yak and Rattlesnake both use this.  I'll add a deprecated version of the function with the old name.

**Comment by friedmud** [comment]
Seems like an odd thing to change.  Why do it?

**Comment by friedmud** [comment]
Ok - I looked at the ticket.

Glad you're adding a deprecated version now.  Anything that changes public API needs to go through deprecation now.

There are over 230 Stork forks now... we can't just look at what's used at INL to decide whether or not something is used!

**Comment by bwspenc** [comment]
I think this version is ready to go.  It includes the old parameter as deprecated.  The first merge request was just to see which of our apps we need to fix.

**Pull request merged**
