### PR TITLE
Adding Bayesian UQ Tutorial

### PR DESCRIPTION
**Pull request by yfche**
Adding the tutorial page under the stochastic tools module to demonstrate the Bayesian inverse UQ capabilities.

## Reason
Upon merging #23839 which adds the parallel MCMC samplers, it will be good to have a tutorial page to demonstrate how to use these parallel MCMC samplers for the purpose of inverse UQ. 

## Design
Adding markdown files under stochastic tools for the tutorial page.

## Impact
Providing tutorial for newly added code features.

### CODE REVIEW

**Comment by somu15** [comment]
I'd suggest to open this PR after https://github.com/idaholab/moose/pull/23839 is merged upon rebasing. Right, a lot of the files are duplicated from the https://github.com/idaholab/moose/pull/23839 PR.

**Comment by yfche** [comment]
> I'd suggest to open this PR after #23839 is merged upon rebasing. Right now, a lot of the files are duplicated from the #23839 PR.

Yep I'll wait for #23839 to be merged first, then update this PR and merge it. Currently just submitting it as a draft for record.

**Comment by somu15** [comment]
@yfche #23839 is merged into next. Once merged into devel (in about 1-2 days), you may rebase your local branch with devel. Then push changes. Alternatively, you may close this PR, create a fresh moose branch that is current with the new devel with your new changes, and submit a new PR.

**Comment by somu15** [comment]
Also, upon rebasing with the new devel, do you mind running the calculations again as a verification step? This should be pretty quick since the model is fast. The new results should be consistent with what you have, statistically.

**Comment by yfche** [comment]
Submitted a new PR which is an equivalent to this one.

**Pull request closed without merging**
