### PR TITLE
Properly scope console timed print

### LINKED ISSUE #15376: Properly scope "Computing max dofs per elem/node"
## Reason
The scope for the console timed print "Computing max dofs per elem/node" is poor and encompasses much more. It can collide with other timed prints.

## Design
Scope said timed print.

## Impact
Minimal.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #15376

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
Nice. I had been recently doing some stuff in debug mode where it appeared as if computing this was basically the whole simulation :-) thanks to you I didn’t even have to look into it! Just move that local variable out of the scope block...

**Comment by loganharbour** [comment]
Whoops. What is trying to compile before pushing anyway?

Hah - yeah. The same thing happened to me and is what lead to this. Should be good now.

**Comment by lindsayad** [comment]
The functor constructor needs to be moved out too. Third time the charm?

**Comment by loganharbour** [comment]
Damn.

Cleaner this time. I even compiled.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
