### PR TITLE
Test solution time adaptive dt deterministically

### LINKED ISSUE #18863: Add deterministic test for switching direction in SolutionTimeAdaptiveDT
## Reason
The code branch [here](https://github.com/idaholab/moose/blob/b9a47a04f1981f6c931ea4ae97a940025724adb5/framework/src/timesteppers/SolutionTimeAdaptiveDT.C#L86) is not always hit because it is based off of walltime, which leads to coverage for this branch flipping depending on if the machine that ran it is under load or not.

## Design
Develop a test that intentionally slows down/speeds up execution (using a sleep statement) that forces this branch to be hit.

## Impact
Enhanced testing, consistent coverage for this branch.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #18863

### CODE REVIEW

**Comment by dschwen** [comment]
Deterministically my _behind_...

**Comment by dschwen** [comment]
Ok, design flaw in `SlowKernel` because `timestepSetup` is outside the section that is timed by `SolutionTimeAdaptiveDT` :-D

**Comment by friedmud** [comment]
I was just talking to @loganharbour about this - we should have done this ages ago.

Alternative design: create a `Problem` and slow down `solve()` deterministically.  For instance, check out the `SlowProblem` I recently added that could probably be extended.

**Comment by dschwen** [comment]
Yeah, I saw `SlowProblem` I can move the functionality of `SlowKernel` into that class.

**Comment by loganharbour** [comment]
Wouldn't you believe it - you even added coverage

**Comment by dschwen** [comment]
> Wouldn't you believe it - you even added coverage

Yay me!

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
