### PR TITLE
Added MaskedBodyForce for #4620

### LINKED ISSUE #4620: Create MaskedBodyForce kernel
I am creating a kernel that will apply a body force multiplied by a material that defines some mask. This will provide a flexible interface for having a body force change as a function of location, time, or other variables. It will live in the phase field module.

### PR DESCRIPTION
**Pull request by tonkmr**
I added MaskedBodyForce to create a body force that is modified by a mask defined by a material property. Closes #4620.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Who was that masked body force?

But seriously, it looks like you added the letter "b" to some random input files in this patch...

**Comment by tonkmr** [comment]
Yeah, that is really weird. I didn't even open any files in any module except the phase_field module. 

The masked body force strikes again!

**Comment by dschwen** [comment]
He didn't add the ```b```, he just added a newline to the end of the files. Does the delete whitespace script do that maybe?

**Comment by jwpeterson** [comment]
> He didn't add the b, he just added a newline to the end of the files. Does the delete whitespace script do that maybe?

Are you guys running the whitespace removal script manually?

In any event, the b should definitely be removed.  @tonkmr would you mind doing that since you were the lucky contestant who found it?

**Comment by tonkmr** [comment]
I can do it, as long as we are sure it isn't supposed to be there. It looks like those input files were for a presentation. @aeslaughter the b's aren't needed for the presentation generation script are they?

**Comment by aeslaughter** [comment]
The 'b' should NOT be there.

**Pull request merged**
