### PR TITLE
Add profiling to moose-dev container

### LINKED ISSUE #28583: Add profiler to moose containers
### Motivation

To get a better picture on the bottlenecks in moose, we should be able to easily profile the code.

### Design

Add gperftools and pprof to the default moose containers.

### Impact

Easier development.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #28583

### CODE REVIEW

**Comment by loganharbour** [comment]
FYI @YaqiWang, will have a profiling container up this evening. 

I'll share information on how to use it once it's up.

**Comment by lindsayad** [comment]
FWIW PETSc will release 3.22 at the end of September

**Comment by loganharbour** [comment]
> FWIW PETSc will release 3.22 at the end of September, at which time I will definitely want to update to it ASAP

We only added this while were rebuilding petsc anyway. No preference if it's here or not. And also no preference updating again after.

**Comment by lindsayad** [comment]
Yea I think it's fine to or even good to update here to 3.21.5, assuming this PR goes in before 3.22 is released

**Comment by grmnptr** [comment]
Got merged into https://github.com/idaholab/moose/pull/28656
I think

**Pull request closed without merging**
