### PR TITLE
Fix unused parameter warning

### PR DESCRIPTION
**Pull request by brianmoose**
Only happens with gcc
refs #1777

### CODE REVIEW

**Comment by permcody** [comment]
Brian, this shouldn't be GCC related, it's debug vs opt. Are you seeing something to contradict this?

**Comment by brianmoose** [comment]
It doesn't happen on the clang target but happens on all the gcc targets.

**Comment by brianmoose** [comment]
Nevermind, you are right, it is a debug vs opt issue

**Review by jwpeterson — APPROVED** [review]
We need to turn on unused parameter/variable/etc warnings in opt mode in clang.  Currently trying to figure out if `-Wunused` is a real flag still, it's not even listed on [this site...](http://fuckingclangwarnings.com/).

**Pull request merged**
