### PR TITLE
Nearest node caching fix

### PR DESCRIPTION
**Pull request by GiudGiud**
Refs #20962 which was misdiagnosed initially

### CODE REVIEW

**Comment by GiudGiud** [comment]
Test failures are unrelated

**Comment by lindsayad** [comment]
This doesn't close the issue? Can you say why the PR here refs/closes the issue? It's not clear to me just from reviewing the PR

**Comment by GiudGiud** [comment]
Well I would have Cole try it with Sabertooth before we can close the issue. It s safe to say from the test I am adding that I am fixing a bug here though

**Comment by lindsayad** [comment]
but what is *this* bug?

**Review by lindsayad — APPROVED** [review]
I pulled the changes and I can see that previously we just always used the zeroth sub-app for the "nearest"? Anyway yes clearly there is a good bug-fix here :smile:

**Comment by GiudGiud** [comment]
Indeed. The multiple subapp case was just not supported by the caching in the to_multiapp direction. 
I ll examine other transfers when I have time to make sure this is an isolated issue.

**Pull request merged**
