### PR TITLE
Update PETSc to 3.14.2

### LINKED ISSUE #16066: Update PETSc to 3.14.2
## Reason

The version has a better way to print out converged reason.
It will only print out reasons when the algorithm diverged.

Also want to use new features in PETSc.
## Design

Update  PETSc-3.14.1
## Impact

Better performance

### PR DESCRIPTION
**Pull request by fdkong**
Closes #16066

### CODE REVIEW

**Comment by fdkong** [comment]
We need https://github.com/idaholab/moose/pull/15791 go in first

**Comment by loganharbour** [comment]
@fdkong Just rebased and force pushed this to see how it plays with the new testing.

**Comment by fdkong** [comment]
I am waiting on @milljm 's new-build-farm

https://github.com/idaholab/moose/pull/15946


Somehow conda can not create libmesh package

**Comment by loganharbour** [comment]
I just want to see what is failing that doesn't use conda.

**Comment by milljm** [comment]
Conda package updates will not work until our Firewall rules get fixed. I am trying everything I know to get in touch with them...

**Comment by cticenhour** [comment]
@lindsayad @fdkong Is this ready to go? I'd like to get the libmesh fix for my testing issues in so I can finish out #16295

**Review by milljm — APPROVED** [review]
I approve. If simply for the PETSc update, and the libMesh update to follow (LLVM 10!)

**Comment by fdkong** [comment]
I think it is ready.

**Comment by lindsayad** [comment]
Two for one: PETSc and libmesh update!

**Comment by fdkong** [comment]
Nothing can be wrong if we update all at once

**Comment by cticenhour** [comment]
Just double the beautiful code!

**Pull request merged**
