### PR TITLE
Suppress warning

### LINKED ISSUE #19528: Suppress warning in `ADRealMonolithic.h` build
## Reason
The `ADRealMonolithic.h` file is built using the C++ preprocessor. As it contains a `#pragma once` in the main file passed to the preprocessor a warning is issued.

## Design
Add `-Wno-pragma-once-outside-header` to the appropriate Makefile rule.

## Impact
No more unproductive warning. @loganharbour

### PR DESCRIPTION
**Pull request by dschwen**
Closes #19528

### CODE REVIEW

**Review by loganharbour — DISMISSED** [review]

**Comment by loganharbour** [comment]
Still there?

**Comment by dschwen** [comment]
Yeah

**Comment by dschwen** [comment]
Massive improvement. We now got _two_ warnings.

```
/ramdisk/civet/build_0/moose/framework/include/utils/ADReal.h:10:9: warning: #pragma once in main file
   10 | #pragma once
      |         ^~~~
cc1plus: warning: unrecognized command line option '-Wno-pragma-once-outside-header'
```

**Comment by dschwen** [comment]
Yeah, unfortunately that flag is only supported by clang. Bringing it to GCC has now been almost a three year effort that didn bear fruit yet: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89808

**Pull request closed without merging**
