### PR TITLE
Allow skipping the bounding box check in MultiAppUserObjectTransfer

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by permcody** [comment]
Does this improve speed significantly?

**Comment by snschune** [comment]
> Does this improve speed significantly?

not significantly. It's for ensuring the transfer is executed and not skipped if you're outside the bbox of the `from_app`. There a legitimate cases where you want that, e.g. when transferring from 1D channels that don't cover the whole `to_domain`.

**Review by permcody — CHANGES_REQUESTED** [review]
Any chance you could provide a small test case to demonstrate?

**Comment by snschune** [comment]
> Any chance you could provide a small test case to demonstrate?

Two pipes represented by THM sub-app. The 3D master represents the pipe as
explicitly meshed region of block 1. Transfer to variable in block 1 is the problem.
Screen Shot 2019-07-10 at 3 10 04 PM

This is the result. 
Screen Shot 2019-07-10 at 3 14 01 PM

I saw that you can add padding to your subapp bounding box in transient multiapp.
That would solve this problem. I think it should be set on the transfer level though.

**Comment by permcody** [comment]
Looks good but you forgot the test spec.

**Pull request closed without merging**
