### PR TITLE
Bayesian UQ PR causing valgrind failure in STM

### LINKED ISSUE #25078: Bayesian UQ PR causing valgrind failure in STM
## Bug Description
Bayesian UQ PR causing valgrind failure in STM

## Steps to Reproduce
Run tests with valgrind turned on

## Impact
next cannot be integrated with devel

### PR DESCRIPTION
**Pull request by somu15**
closes #25078

### CODE REVIEW

**Review by loganharbour — CHANGES_REQUESTED** [review]
I don't think the solution to memory issues should be only a processor count change... we need some code change here. Either an error for an invalid configuration or a memory fix

**Comment by somu15** [comment]
> I don't think the solution to memory issues should be only a processor count change... we need some code change here. Either an error for an invalid configuration or a memory fix

I guess, I found the issue. Give me a few mins, I will push some changes. A gather operation is required, I believe; the vectors are not of the correct size.

**Comment by somu15** [comment]
@loganharbour @zachmprince valgrind stm is now passing. I'll just have to get rid of a duplicate test. Pushing a new change. But are you okay with this now?

**Comment by somu15** [comment]
The two failures are unrelated to this PR: Grizzly docs and geochemistry.

**Review by loganharbour — APPROVED** [review]
Unrelated failures

**Comment by loganharbour** [comment]
Thanks for getting to this quickly @somu15

**Pull request merged**
