### PR TITLE
Fixes uninitialized coupled variables in initQpStatefulProperties

### LINKED ISSUE #6760: Investigate use of couple variables for initializing material properties.
### Description of the enhancement or error report
@WilkAndy reports that you cannot use the reference from `coupledValue` to in `initQpStatefulProperties`.

### Rationale for the enhancement or information for reproducing the error
IC objects can not use Material objects, so it seems like the IC could/should be set prior to initializing materials.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This should help @WilkAndy do something.

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #6760)

### CODE REVIEW

**Comment by WilkAndy** [comment]
Thaks @aeslaughter - i can confirm that this works for me,

a

**Comment by YaqiWang** [comment]
The only caveat about this is that if the variable is changed by an aux kernel on initial, the material property will not see it. It will not work if the material property depends on another non-stateful material property. But I am glad this works for @WilkAndy 's case.

**Comment by WilkAndy** [comment]
OK, thanks @YaqiWang .  This is really important to fix.  It is just pure luck that currently our code+tests don't fall into Yaqi's caveats, as i foresee that we'll encounter them soon.  These things are quite difficult to debug, so it's quite important for us to be assured that "everything just works", or that moose throws a descriptive error in the "corner cases".

**Comment by permcody** [comment]
Ah I knew there was another case that we'd seen before. At least we'll be able to detect the pathological case that Yaqi mentions here when I get around to finishing up all of the MOOSE depend work I started a few weeks back.

**Pull request merged**
