### PR TITLE
Improve assignment of processor_id for new XFEM nodes

### LINKED ISSUE #11500: Fix assignment of processor_id in newly created XFEM nodes
## Rationale

Recent changes to libMesh broke the XFEM `init_solution_propagation` test. 
Libmesh Issue https://github.com/libMesh/libmesh/issues/1688
It appears that this issue is because XFEM is creating new nodes that are not attached to any on-processor elements in some cases.

## Description

This is what we do in XFEM: if an element is cut, we delete it, and replace it with two new overlapping elements. Those elements are connected to both the original nodes and new nodes that are created at the same locations as the original nodes. The new elements are set to have the same processor id as the original one that we deleted, and the new nodes are set to have the same processor id as the ones that they are duplicated from. There are scenarios where the newly-created nodes may not be connected to any elements on-processor. 

## Impact

Minor changes to XFEM.C

### PR DESCRIPTION
**Pull request by bwspenc**
closes #11500

### CODE REVIEW

**Comment by bwspenc** [comment]
@roystgnr @jwpeterson This will hopefully address the issue in #11469.

**Comment by roystgnr** [comment]
This isn't yet working for me, but I think the problem is now on my end and not yours.

**Comment by roystgnr** [comment]
Wait, no it's not.  There still *is* at least one problem on my end (a failed assumption which could have been caught by a simple assertion but which instead gets ignored until the implications spiral out of control), but there's also a bug to be fixed in XFEM.C:

```
roystgnr@zappa:(xfem_parallel) ~/git/moose/modules                                                                                                   |
$ git diff xfem/                                                                                                                                     |
diff --git a/modules/xfem/src/base/XFEM.C b/modules/xfem/src/base/XFEM.C
index a9c755a..c57da6c 100644
--- a/modules/xfem/src/base/XFEM.C
+++ b/modules/xfem/src/base/XFEM.C
@@ -300,6 +300,8 @@ XFEM::update(Real time, NonlinearSystemBase & nl, AuxiliarySystem & aux)
 
     if (_displaced_mesh)
     {
+      Partitioner::set_node_processor_ids(*_displaced_mesh);
+
       _displaced_mesh->update_parallel_id_counts();
       MeshCommunication().make_elems_parallel_consistent(*_displaced_mesh);
       MeshCommunication().make_nodes_parallel_consistent(*_displaced_mesh);
```

This PR got the processor ids set properly on the mesh but not the displaced mesh.

I'll start testing some more to see if there's any other issues.

**Comment by roystgnr** [comment]
With the above change, the broken XFEM test works for me on up to 14 processors.

On 15 processors I get a segfault, but it looks like a completely unrelated problem, of the common "code assuming n_local_elem() != 0 dies on too many processors" variety.

**Comment by bwspenc** [comment]
@roystgnr Oh yeah, the displaced mesh... thanks for pointing that out! I just pushed an update with your fix.

**Review by roystgnr — APPROVED** [review]

**Comment by roystgnr** [comment]
Unless someone screams first I'd like to merge this as soon as the CI is done.  I'm very glad that the modules tests are now part of the regular libMesh CI, but at the moment that means we have a probably-false-positive test failure that's blocking multiple PRs there.  And even if it's 99% likely that there's no real underlying regression, I already feel guilty enough about regressing your XFEM code and I'd rather not take even a small risk of accidentally doing so twice in a row.

**Comment by bwspenc** [comment]
@roystgnr I'm good with that -- as far as I'm concerned, this is ready to go.

**Comment by jwpeterson** [comment]
So @roystgnr there's no changes required on the libmesh side in order for this to go in?

**Comment by roystgnr** [comment]
Well, this PR works with the current libMesh checkout in MOOSE CI, and it works on my systems with libMesh master, and with it XFEM is now using the libMesh methods exactly the way they're meant to be used while meeting each of their preconditions for use.

I can't swear there won't be any more surprises, but there's at least good evidence that this PR is adding compatibility with newer libMesh without breaking any compatibility with older.

I am a little annoyed that the related "simple assertion" I was planning to put into libMesh turns out to be impossible to do simply after all.  But that wasn't anything we required for this PR, that was just a belt-and-suspenders idea I had to make this problem easier to diagnose if it ever crops up in other code.

**Comment by jwpeterson** [comment]
I've been informed the cool new "Auto Merge" label might not work in this particular case since we have some failed-but-allowed app tests this morning. I'll merge by hand regardless when the other testing is done.

**Comment by jwpeterson** [comment]
Closes libMesh/libmesh#1688

**Pull request merged**
