### PR TITLE
Updating SQA script(s) for improved CIVET testing and website dashboard

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #12049)

This is just a first step, I also need to:

- [x] Re-work our CIVET recipes to put all SQA related tests in a single target 
- [x] Create a testable means for linking pages: RTM, theory, etc...
- [x] Build a MooseDocs dashboard for showing all this information

### CODE REVIEW

**Comment by aeslaughter** [comment]
@permcody I have the "dashboard" working on the command-line, which is all I am planning for now. You can check it out here: https://civet.inl.gov/job/550778/ in the "Check SQA" tab. 

I still have a few things to iron out, mainly why this isn't returning a failing exit code.

**Comment by aeslaughter** [comment]
We have some work to do. Somewhere along the python3/conda updates our SQA checking started to be skipped without us noticing and we accumulated some missing documentation. These checks are also more complete than before so I think it found some other problems as well.

```bash
$ ./scripts/sqa_check.py
Collecting SQA document reports...done
Collecting SQA requirement reports...done
Collecting SQA application reports...done

--------------------------------------------------------------------------------
MOOSEAPP REPORT(S):
--------------------------------------------------------------------------------
framework FAIL
  MooseObject Report:
               Count: 901
             Removed: 154
              Hidden: 232
               Stubs: 277
       Syntax Report:
               Count: 16
             Removed: 0
              Hidden: 7
               Stubs: 7

MooseObject(s) without documentation: 2
/ModifyMesh/AppendMeshGeneratorAction actions/AppendMeshGeneratorAction.md /test/src/actions/AppendMeshGeneratorAction.C
/VectorPostprocessors/TestFaceInfo vectorpostprocessors/TestFaceInfo.md /test/src/vectorpostprocessors/TestFaceInfo.C

MooseObject(s) removed and hidden: 18
/Bounds/AddBoundsVectorsAction actions/AddBoundsVectorsAction.md /framework/src/actions/AddBoundsVectorsAction.C
/Bounds/AddKernelAction actions/AddKernelAction.md /framework/src/actions/AddKernelAction.C
/AuxVariables/InitialCondition/AddICAction actions/AddICAction.md /framework/src/actions/AddICAction.C
/AuxVariables/InitialCondition/BoundingBoxIC ics/BoundingBoxIC.md /framework/src/ics/BoundingBoxIC.C
/AuxVariables/InitialCondition/ConstantIC ics/ConstantIC.md /framework/src/ics/ConstantIC.C
/AuxVariables/InitialCondition/FunctionIC ics/FunctionIC.md /framework/src/ics/FunctionIC.C
/AuxVariables/InitialCondition/FunctionScalarIC ics/FunctionScalarIC.md /framework/src/ics/FunctionScalarIC.C
/AuxVariables/InitialCondition/RandomIC ics/RandomIC.md /framework/src/ics/RandomIC.C
/AuxVariables/InitialCondition/ScalarComponentIC ics/ScalarComponentIC.md /framework/src/ics/ScalarComponentIC.C
/AuxVariables/InitialCondition/ScalarConstantIC ics/ScalarConstantIC.md /framework/src/ics/ScalarConstantIC.C
/Variables/InitialCondition/AddICAction actions/AddICAction.md /framework/src/actions/AddICAction.C
/Variables/InitialCondition/BoundingBoxIC ics/BoundingBoxIC.md /framework/src/ics/BoundingBoxIC.C
/Variables/InitialCondition/ConstantIC ics/ConstantIC.md /framework/src/ics/ConstantIC.C
/Variables/InitialCondition/FunctionIC ics/FunctionIC.md /framework/src/ics/FunctionIC.C
/Variables/InitialCondition/FunctionScalarIC ics/FunctionScalarIC.md /framework/src/ics/FunctionScalarIC.C
/Variables/InitialCondition/RandomIC ics/RandomIC.md /framework/src/ics/RandomIC.C
/Variables/InitialCondition/ScalarComponentIC ics/ScalarComponentIC.md /framework/src/ics/ScalarComponentIC.C
/Variables/InitialCondition/ScalarConstantIC ics/ScalarConstantIC.md /framework/src/ics/ScalarConstantIC.C

MooseObject(s) without description and not hidden: 2
/ModifyMesh/AppendMeshGeneratorAction actions/AppendMeshGeneratorAction.md /test/src/actions/AppendMeshGeneratorAction.C
/MoreAuxVariables/AddAuxVariableAction actions/AddAuxVariableAction.md /framework/src/actions/AddAuxVariableAction.C

Syntax without documentation: 1
/MoreAuxVariables MoreAuxVariables/index.md 

chemical_reactions WARNING
  MooseObject Report:
               Count: 33
             Removed: 7
              Hidden: 10
               Stubs: 10
       Syntax Report:
               Count: 0
             Removed: 0
              Hidden: 0
               Stubs: 0 

contact FAIL
  MooseObject Report:
               Count: 16
             Removed: 2
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 1
             Removed: 0
              Hidden: 0
               Stubs: 0

MooseObject(s) without documentation: 2
/DiracKernels/ContactMaster dirackernels/ContactMaster.md /modules/contact/src/dirackernels/ContactMaster.C
/DiracKernels/SlaveConstraint dirackernels/SlaveConstraint.md /modules/contact/src/dirackernels/SlaveConstraint.C

MooseObject(s) without description and not hidden: 2
/DiracKernels/ContactMaster dirackernels/ContactMaster.md /modules/contact/src/dirackernels/ContactMaster.C
/DiracKernels/SlaveConstraint dirackernels/SlaveConstraint.md /modules/contact/src/dirackernels/SlaveConstraint.C 

geochemistry OK
  MooseObject Report:
               Count: 5
             Removed: 0
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 2
             Removed: 0
              Hidden: 0
               Stubs: 0 

fluid_properties WARNING
  MooseObject Report:
               Count: 40
             Removed: 6
              Hidden: 6
               Stubs: 9
       Syntax Report:
               Count: 1
             Removed: 0
              Hidden: 0
               Stubs: 0 

functional_expansion_tools OK
  MooseObject Report:
               Count: 10
             Removed: 1
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 0
             Removed: 0
              Hidden: 0
               Stubs: 0 

heat_conduction FAIL
  MooseObject Report:
               Count: 53
             Removed: 6
              Hidden: 0
               Stubs: 10
       Syntax Report:
               Count: 2
             Removed: 0
              Hidden: 0
               Stubs: 1

MooseObject(s) without description and not hidden: 6
/BCs/CoupledConvectiveFlux bcs/CoupledConvectiveFlux.md /modules/heat_conduction/src/bcs/CoupledConvectiveFlux.C
/BCs/HeatConductionBC bcs/HeatConductionBC.md /modules/heat_conduction/src/bcs/HeatConductionBC.C
/DiracKernels/GapHeatPointSourceMaster dirackernels/GapHeatPointSourceMaster.md /modules/heat_conduction/src/dirackernels/GapHeatPointSourceMaster.C
/Kernels/AnisoHeatConduction kernels/AnisoHeatConduction.md /modules/heat_conduction/src/kernels/AnisoHeatConduction.C
/Materials/AnisoHeatConductionMaterial materials/AnisoHeatConductionMaterial.md /modules/heat_conduction/src/materials/AnisoHeatConductionMaterial.C
/Materials/GapConductance materials/GapConductance.md /modules/heat_conduction/src/materials/GapConductance.C 

level_set OK
  MooseObject Report:
               Count: 17
             Removed: 2
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 0
             Removed: 0
              Hidden: 0
               Stubs: 0 

misc FAIL
  MooseObject Report:
               Count: 10
             Removed: 2
              Hidden: 0
               Stubs: 5
       Syntax Report:
               Count: 0
             Removed: 0
              Hidden: 0
               Stubs: 0

MooseObject(s) without description and not hidden: 2
/AuxKernels/CoupledDirectionalMeshHeightInterpolation auxkernels/CoupledDirectionalMeshHeightInterpolation.md /modules/misc/src/auxkernels/CoupledDirectionalMeshHeightInterpolation.C
/UserObjects/RigidBodyModes3D userobjects/RigidBodyModes3D.md /modules/misc/src/userobjects/RigidBodyModes3D.C 

navier_stokes FAIL
  MooseObject Report:
               Count: 123
             Removed: 16
              Hidden: 0
               Stubs: 19
       Syntax Report:
               Count: 2
             Removed: 0
              Hidden: 0
               Stubs: 0

MooseObject(s) without description and not hidden: 14
/AuxKernels/EnthalpyAux auxkernels/EnthalpyAux.md /modules/navier_stokes/src/auxkernels/EnthalpyAux.C
/AuxKernels/InternalEnergyAux auxkernels/InternalEnergyAux.md /modules/navier_stokes/src/auxkernels/InternalEnergyAux.C
/AuxKernels/SpecificInternalEnergyAux auxkernels/SpecificInternalEnergyAux.md /modules/navier_stokes/src/auxkernels/SpecificInternalEnergyAux.C
/AuxKernels/SpecificVolumeAux auxkernels/SpecificVolumeAux.md /modules/navier_stokes/src/auxkernels/SpecificVolumeAux.C
/BCs/EnergyFreeBC bcs/EnergyFreeBC.md /modules/navier_stokes/src/bcs/EnergyFreeBC.C
/BCs/MassFreeBC bcs/MassFreeBC.md /modules/navier_stokes/src/bcs/MassFreeBC.C
/BCs/MomentumFreeBC bcs/MomentumFreeBC.md /modules/navier_stokes/src/bcs/MomentumFreeBC.C
/BCs/MomentumFreeSlipBC bcs/MomentumFreeSlipBC.md /modules/navier_stokes/src/bcs/MomentumFreeSlipBC.C
/Kernels/DistributedForce kernels/DistributedForce.md /modules/navier_stokes/src/kernels/DistributedForce.C
/Kernels/DistributedPower kernels/DistributedPower.md /modules/navier_stokes/src/kernels/DistributedPower.C
/Kernels/MassConvectiveFlux kernels/MassConvectiveFlux.md /modules/navier_stokes/src/kernels/MassConvectiveFlux.C
/Kernels/MomentumConvectiveFlux kernels/MomentumConvectiveFlux.md /modules/navier_stokes/src/kernels/MomentumConvectiveFlux.C
/Kernels/PressureGradient kernels/PressureGradient.md /modules/navier_stokes/src/kernels/PressureGradient.C
/Kernels/TotalEnergyConvectiveFlux kernels/TotalEnergyConvectiveFlux.md /modules/navier_stokes/src/kernels/TotalEnergyConvectiveFlux.C 

peridynamics FAIL
  MooseObject Report:
               Count: 51
             Removed: 8
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 4
             Removed: 0
              Hidden: 0
               Stubs: 1 

phase_field FAIL
  MooseObject Report:
               Count: 325
             Removed: 31
              Hidden: 0
               Stubs: 177
       Syntax Report:
               Count: 30
             Removed: 0
              Hidden: 0
               Stubs: 29

MooseObject(s) without documentation: 1
/Materials/EBCoupledVarTest materials/EBCoupledVarTest.md /modules/phase_field/test/src/materials/EBCoupledVarTest.C

MooseObject(s) without description and not hidden: 25
/AuxKernels/EBSDReaderAvgDataAux auxkernels/EBSDReaderAvgDataAux.md /modules/phase_field/src/auxkernels/EBSDReaderAvgDataAux.C
/AuxKernels/EBSDReaderPointDataAux auxkernels/EBSDReaderPointDataAux.md /modules/phase_field/src/auxkernels/EBSDReaderPointDataAux.C
/AuxKernels/EulerAngleVariables2RGBAux auxkernels/EulerAngleVariables2RGBAux.md /modules/phase_field/src/auxkernels/EulerAngleVariables2RGBAux.C
/AuxKernels/PFCEnergyDensity auxkernels/PFCEnergyDensity.md /modules/phase_field/src/auxkernels/PFCEnergyDensity.C
/AuxKernels/PFCRFFEnergyDensity auxkernels/PFCRFFEnergyDensity.md /modules/phase_field/src/auxkernels/PFCRFFEnergyDensity.C
/ICs/ReconPhaseVarIC ics/ReconPhaseVarIC.md /modules/phase_field/src/ics/ReconPhaseVarIC.C
/Materials/DeformedGrainMaterial materials/DeformedGrainMaterial.md /modules/phase_field/src/materials/DeformedGrainMaterial.C
/Materials/GBAnisotropy materials/GBAnisotropy.md /modules/phase_field/src/materials/GBAnisotropy.C
/Materials/GBWidthAnisotropy materials/GBWidthAnisotropy.md /modules/phase_field/src/materials/GBWidthAnisotropy.C
/Materials/InterfaceOrientationMaterial materials/InterfaceOrientationMaterial.md /modules/phase_field/src/materials/InterfaceOrientationMaterial.C
/Materials/PFCRFFMaterial materials/PFCRFFMaterial.md /modules/phase_field/src/materials/PFCRFFMaterial.C
/Postprocessors/FeatureVolumeFraction postprocessors/FeatureVolumeFraction.md /modules/phase_field/src/postprocessors/FeatureVolumeFraction.C
/Postprocessors/PFCElementEnergyIntegral postprocessors/PFCElementEnergyIntegral.md /modules/phase_field/src/postprocessors/PFCElementEnergyIntegral.C
/AuxKernels/MatVecRealGradAuxKernel/MatVecRealGradAuxKernelAction action/MatVecRealGradAuxKernelAction.md /modules/phase_field/src/action/MatVecRealGradAuxKernelAction.C
/AuxKernels/MaterialVectorAuxKernel/MaterialVectorAuxKernelAction action/MaterialVectorAuxKernelAction.md /modules/phase_field/src/action/MaterialVectorAuxKernelAction.C
/AuxKernels/MaterialVectorGradAuxKernel/MaterialVectorGradAuxKernelAction action/MaterialVectorGradAuxKernelAction.md /modules/phase_field/src/action/MaterialVectorGradAuxKernelAction.C
/AuxVariables/InitialCondition/ReconPhaseVarIC ics/ReconPhaseVarIC.md /modules/phase_field/src/ics/ReconPhaseVarIC.C
/Kernels/CHPFCRFFSplitKernel/CHPFCRFFSplitKernelAction action/CHPFCRFFSplitKernelAction.md /modules/phase_field/src/action/CHPFCRFFSplitKernelAction.C
/Variables/InitialCondition/ReconPhaseVarIC ics/ReconPhaseVarIC.md /modules/phase_field/src/ics/ReconPhaseVarIC.C
/Variables/CHPFCRFFSplitVariables/CHPFCRFFSplitVariablesAction action/CHPFCRFFSplitVariablesAction.md /modules/phase_field/src/action/CHPFCRFFSplitVariablesAction.C
/Variables/HHPFCRFFSplitVariables/HHPFCRFFSplitVariablesAction action/HHPFCRFFSplitVariablesAction.md /modules/phase_field/src/action/HHPFCRFFSplitVariablesAction.C
/Variables/PFCRFFVariables/PFCRFFVariablesAction action/PFCRFFVariablesAction.md /modules/phase_field/src/action/PFCRFFVariablesAction.C
/ICs/PolycrystalICs/PolycrystalRandomIC/PolycrystalRandomICAction action/PolycrystalRandomICAction.md /modules/phase_field/src/action/PolycrystalRandomICAction.C
/ICs/PolycrystalICs/PolycrystalVoronoiVoidIC/PolycrystalVoronoiVoidICAction action/PolycrystalVoronoiVoidICAction.md /modules/phase_field/src/action/PolycrystalVoronoiVoidICAction.C
/ICs/PolycrystalICs/Tricrystal2CircleGrainsIC/Tricrystal2CircleGrainsICAction action/Tricrystal2CircleGrainsICAction.md /modules/phase_field/src/action/Tricrystal2CircleGrainsICAction.C 

porous_flow FAIL
  MooseObject Report:
               Count: 121
             Removed: 6
              Hidden: 0
               Stubs: 1
       Syntax Report:
               Count: 3
             Removed: 0
              Hidden: 0
               Stubs: 3 

rdg OK
  MooseObject Report:
               Count: 8
             Removed: 1
              Hidden: 0
               Stubs: 0
       Syntax Report:
               Count: 0
             Removed: 0
              Hidden: 0
               Stubs: 0 

stochastic_tools FAIL
  MooseObject Report:
               Count: 53
             Removed: 9
              Hidden: 0
               Stubs: 1
       Syntax Report:
               Count: 3
             Removed: 0
              Hidden: 0
               Stubs: 0 

tensor_mechanics FAIL
  MooseObject Report:
               Count: 319
             Removed: 31
              Hidden: 0
               Stubs: 70
       Syntax Report:
               Count: 15
             Removed: 0
              Hidden: 0
               Stubs: 4

MooseObject(s) without description and not hidden: 5
/AuxKernels/AccumulateAux auxkernels/AccumulateAux.md /modules/tensor_mechanics/src/auxkernels/AccumulateAux.C
/BCs/DashpotBC bcs/DashpotBC.md /modules/tensor_mechanics/src/bcs/DashpotBC.C
/BCs/PresetVelocity bcs/PresetVelocity.md /modules/tensor_mechanics/src/bcs/PresetVelocity.C
/Kernels/MomentBalancing kernels/MomentBalancing.md /modules/tensor_mechanics/src/kernels/MomentBalancing.C
/Materials/InclusionProperties materials/InclusionProperties.md /modules/tensor_mechanics/src/materials/InclusionProperties.C 

xfem FAIL
  MooseObject Report:
               Count: 28
             Removed: 3
              Hidden: 0
               Stubs: 1
       Syntax Report:
               Count: 1
             Removed: 0
              Hidden: 0
               Stubs: 0

MooseObject(s) without description and not hidden: 1
/UserObjects/XFEMMaterialTensorMarkerUserObject userobjects/XFEMMaterialTensorMarkerUserObject.md /modules/xfem/src/userobjects/XFEMMaterialTensorMarkerUserObject.C 


--------------------------------------------------------------------------------
DOCUMENT REPORT(S):
--------------------------------------------------------------------------------
Initiation: WARNING
  safety_software_determination: None WARNING
    REASON: Not provided
  quality_level_determination: None WARNING
    REASON: Not provided
  enterprise_architecture_entry: None WARNING
    REASON: Not provided 

Planning: WARNING
  project_management_plan: None WARNING
    REASON: Not provided
  software_quality_plan: None WARNING
    REASON: Not provided
  configuration_management_plan: None WARNING
    REASON: Not provided 

Requirements: OK
  software_requirements_specification: sqa/moose_srs.md OK 

Design: OK
  software_design_description: sqa/moose_sdd.md OK 

Testing: WARNING
  software_test_plan: sqa/moose_stp.md OK
  requirements_traceablity_matrix: sqa/moose_rtm.md OK
  asset_management_plan: None WARNING
    REASON: Not provided
  verification_validation_plan: sqa/moose_vvr.md OK 

Other: WARNING
  user_manual: None WARNING
    REASON: Not provided
  theory_manual: None WARNING
    REASON: Not provided 


--------------------------------------------------------------------------------
REQUIREMENT REPORT(S):
--------------------------------------------------------------------------------
Complete MOOSE repository information WARNING
      Requirements Complete: 78.1%
      Total Number of Files: 1577
    Files with Requirements: 1288
      Total Number of Tests: 5831
    Tests with Requirements: 4487
           Deprecated Tests: 89
  Missing Test Requirements: 1255
     Duplicate Requirements: 325 

test/tests FAIL
      Requirements Complete: 99.5%
      Total Number of Files: 780
    Files with Requirements: 754
      Total Number of Tests: 1987
    Tests with Requirements: 1888
           Deprecated Tests: 89
  Missing Test Requirements: 10
     Duplicate Requirements: 45

MISSING REQUIREMENTS: 10
/Users/slauae/projects/moose/test/tests/mesh_modifiers/sidesets_between_subdomains/tests:2 test
/Users/slauae/projects/moose/test/tests/relationship_managers/evaluable/tests:41 all_systems_evaluable
/Users/slauae/projects/moose/test/tests/fvkernels/fv_coupled_var/tests:10 jac
/Users/slauae/projects/moose/test/tests/vectorpostprocessors/csv_reader/tests:4 issue9167
/Users/slauae/projects/moose/test/tests/mesh/abaqus_input/tests:2 testcube_elem_id
/Users/slauae/projects/moose/test/tests/mesh_modifiers/sidesets_between_subdomains/tests:18 between_created_subdomain
/Users/slauae/projects/moose/test/tests/mesh/abaqus_input/tests:9 testcube_elset_name
/Users/slauae/projects/moose/test/tests/vectorpostprocessors/csv_reader/tests:38 issue14785
/Users/slauae/projects/moose/test/tests/mesh/abaqus_input/tests:16 testcube_elset_name_ws
/Users/slauae/projects/moose/test/tests/mesh_modifiers/sidesets_between_subdomains/tests:10 vector_test 

stork WARNING
      Requirements Complete: 0.0%
      Total Number of Files: 1
    Files with Requirements: 0
      Total Number of Tests: 1
    Tests with Requirements: 0
           Deprecated Tests: 0
  Missing Test Requirements: 1
     Duplicate Requirements: 0 

tutorials WARNING
      Requirements Complete: 100.0%
      Total Number of Files: 64
    Files with Requirements: 64
      Total Number of Tests: 83
    Tests with Requirements: 83
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 54 

scripts OK
      Requirements Complete: 100.0%
      Total Number of Files: 1
    Files with Requirements: 1
      Total Number of Tests: 3
    Tests with Requirements: 3
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 0 

python WARNING
      Requirements Complete: 41.5%
      Total Number of Files: 104
    Files with Requirements: 19
      Total Number of Tests: 311
    Tests with Requirements: 129
           Deprecated Tests: 0
  Missing Test Requirements: 182
     Duplicate Requirements: 1 

modules/combined WARNING
      Requirements Complete: 83.7%
      Total Number of Files: 116
    Files with Requirements: 91
      Total Number of Tests: 479
    Tests with Requirements: 401
           Deprecated Tests: 0
  Missing Test Requirements: 78
     Duplicate Requirements: 23 

modules/chemical_reactions WARNING
      Requirements Complete: 0.0%
      Total Number of Files: 10
    Files with Requirements: 0
      Total Number of Tests: 49
    Tests with Requirements: 0
           Deprecated Tests: 0
  Missing Test Requirements: 49
     Duplicate Requirements: 0 

modules/contact WARNING
      Requirements Complete: 97.3%
      Total Number of Files: 60
    Files with Requirements: 56
      Total Number of Tests: 259
    Tests with Requirements: 252
           Deprecated Tests: 0
  Missing Test Requirements: 7
     Duplicate Requirements: 5 

modules/external_petsc_solver WARNING
      Requirements Complete: 100.0%
      Total Number of Files: 1
    Files with Requirements: 1
      Total Number of Tests: 10
    Tests with Requirements: 10
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 1 

modules/fluid_properties WARNING
      Requirements Complete: 73.3%
      Total Number of Files: 16
    Files with Requirements: 8
      Total Number of Tests: 45
    Tests with Requirements: 33
           Deprecated Tests: 0
  Missing Test Requirements: 12
     Duplicate Requirements: 0 

modules/functional_expansion_tools WARNING
      Requirements Complete: 28.6%
      Total Number of Files: 2
    Files with Requirements: 1
      Total Number of Tests: 21
    Tests with Requirements: 6
           Deprecated Tests: 0
  Missing Test Requirements: 15
     Duplicate Requirements: 0 

modules/heat_conduction WARNING
      Requirements Complete: 100.0%
      Total Number of Files: 29
    Files with Requirements: 29
      Total Number of Tests: 84
    Tests with Requirements: 84
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 14 

modules/geochemistry WARNING
      Requirements Complete: 100.0%
      Total Number of Files: 6
    Files with Requirements: 6
      Total Number of Tests: 26
    Tests with Requirements: 26
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 3 

modules/level_set WARNING
      Requirements Complete: 85.7%
      Total Number of Files: 14
    Files with Requirements: 12
      Total Number of Tests: 28
    Tests with Requirements: 24
           Deprecated Tests: 0
  Missing Test Requirements: 4
     Duplicate Requirements: 0 

modules/misc WARNING
      Requirements Complete: 31.2%
      Total Number of Files: 5
    Files with Requirements: 3
      Total Number of Tests: 16
    Tests with Requirements: 5
           Deprecated Tests: 0
  Missing Test Requirements: 11
     Duplicate Requirements: 0 

modules/navier_stokes WARNING
      Requirements Complete: 79.5%
      Total Number of Files: 14
    Files with Requirements: 7
      Total Number of Tests: 73
    Tests with Requirements: 58
           Deprecated Tests: 0
  Missing Test Requirements: 15
     Duplicate Requirements: 0 

modules/phase_field WARNING
      Requirements Complete: 69.8%
      Total Number of Files: 56
    Files with Requirements: 28
      Total Number of Tests: 281
    Tests with Requirements: 196
           Deprecated Tests: 0
  Missing Test Requirements: 85
     Duplicate Requirements: 12 

modules/porous_flow WARNING
      Requirements Complete: 84.1%
      Total Number of Files: 46
    Files with Requirements: 34
      Total Number of Tests: 484
    Tests with Requirements: 407
           Deprecated Tests: 0
  Missing Test Requirements: 77
     Duplicate Requirements: 132 

modules/peridynamics WARNING
      Requirements Complete: 100.0%
      Total Number of Files: 10
    Files with Requirements: 10
      Total Number of Tests: 51
    Tests with Requirements: 51
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 1 

modules/rdg OK
      Requirements Complete: 100.0%
      Total Number of Files: 2
    Files with Requirements: 2
      Total Number of Tests: 7
    Tests with Requirements: 7
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 0 

modules/richards WARNING
      Requirements Complete: 0.0%
      Total Number of Files: 20
    Files with Requirements: 0
      Total Number of Tests: 242
    Tests with Requirements: 0
           Deprecated Tests: 0
  Missing Test Requirements: 242
     Duplicate Requirements: 0 

modules/solid_mechanics WARNING
      Requirements Complete: 5.3%
      Total Number of Files: 31
    Files with Requirements: 2
      Total Number of Tests: 94
    Tests with Requirements: 5
           Deprecated Tests: 0
  Missing Test Requirements: 89
     Duplicate Requirements: 0 

modules/stochastic_tools WARNING
      Requirements Complete: 87.5%
      Total Number of Files: 41
    Files with Requirements: 37
      Total Number of Tests: 80
    Tests with Requirements: 70
           Deprecated Tests: 0
  Missing Test Requirements: 10
     Duplicate Requirements: 0 

modules/tensor_mechanics WARNING
      Requirements Complete: 63.9%
      Total Number of Files: 127
    Files with Requirements: 102
      Total Number of Tests: 1018
    Tests with Requirements: 650
           Deprecated Tests: 0
  Missing Test Requirements: 368
     Duplicate Requirements: 32 

modules/xfem OK
      Requirements Complete: 100.0%
      Total Number of Files: 21
    Files with Requirements: 21
      Total Number of Tests: 99
    Tests with Requirements: 99
           Deprecated Tests: 0
  Missing Test Requirements: 0
     Duplicate Requirements: 0 

```

**Comment by aeslaughter** [comment]
This is now getting very close, I just need to integrate the reporting into an improved MooseDocs check command, which will be how each app can have a full SQA status report. The new system is much more rigorous and found all sorts of fun little problems. 

All but a few of these are actual errors that shouldn't be happening!
```
CRITICAL:0 ERROR:0 WARNING:3179
```

**Comment by aeslaughter** [comment]
I finally have this done! I ended up spending a lot of time breaking the status checks out into a separate python package that is easily tested, maintained and extended. My first attempt was a total hack job that would of just made MooseDocs worst.

Anyway, the status of the entire MOOSE repository can be viewed here: https://mooseframework.inl.gov/docs/PRs/15458/site/sqa/index.html

Individual modules also have a status page, which look similar to what can be expected in an app: https://mooseframework.inl.gov/docs/PRs/15458/site/modules/tensor_mechanics/sqa/

There are three things that remain that need attention. However, in my opinion we need to get some application specific funding for the work. I have already put way more time into this than intended on the current funding, but the effort was worth it in my opinion.

1. Automatically create document links from the SQADocumentReport object.
1. Add documentation for the new modules, in particular how to use the config YAML files for the reports
1. Add documentation outline the entire SQA setup process, from initialize documents with INL, to setting up CIVET, and finally MooseDocs.

@permcody @zachmprince

**Comment by aeslaughter** [comment]
There is also a command-line report here: https://civet.inl.gov/job/572800/ in "Check SQA"

**Comment by aeslaughter** [comment]
@dschwen I don't think @permcody is going to have time to get to this soon. I included restoration of the --generate behavior you desired to motivate your review. Take a look at this comment to get a bit of context: https://github.com/idaholab/moose/pull/15458#issuecomment-663765104

**Comment by aeslaughter** [comment]
Not stale

**Comment by aeslaughter** [comment]
@permcody This is finally ready. The result is this page: https://mooseframework.inl.gov/docs/PRs/15458/site/sqa/index.html
There is also a command-line version of this information: `./moosedocs.py check`

**Comment by aeslaughter** [comment]
@dschwen Can you review/merge this beast?

The reason for the changes is for this page: https://mooseframework.inl.gov/docs/PRs/15458/site/sqa/index.html
There is also a command-line version of this information: ./moosedocs.py check
This also brings back the stubs you are longing for...

**Review by permcody — APPROVED** [review]

**Pull request merged**
