### PR TITLE
Disallow addDeprecatedParam and deprecateParam on same param

### LINKED ISSUE #27577: deprecateParam after addDeprecatedParam with the same param leads to nonsensical deprecation messages
### Bug Description

@gambka reported this deprecation message and I can reproduce it:
```
 The parameter 'use_pre_SMO_residual' is deprecated.
 This parameter is deprecated in favor of 'use_pre_SMO_residual' and is recommended to stay false.
```

### Steps to Reproduce

Run any input with `Executioner/compute_initial_residual_before_preset_bcs=<value>`

### Impact

confusing message to users

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #27577

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]
pending app and/or modules having the same issue

**Comment by lindsayad** [comment]
@roystgnr it looks like you potentially added some new assertions for the sanity of FE calculations? Just FYI that I'm fixing up failures related to those here since I don't care to downgrade my libMesh locally in my quest to see `run_tests` totally green

**Comment by lindsayad** [comment]
No, but I do

**Comment by loganharbour** [comment]
> I'm kind of confused about how you hit those assertions here, though. None of the MOOSE CI uses a `--disable-deprecated` libMesh, does it?

Every next merge https://civet.inl.gov/job/2230858/

**Pull request merged**
