### PR TITLE
Cleanup extra node set generator

### LINKED ISSUE #14936: ExtraNodesetGenerator coord parameter is confusing
## Reason
`ExtraNodesetGenerator` has a coordinate parameter `coords` that is mighty confusing. In most MOOSE objects we expect coordinates to be passed in with three components. `coords` however expects a list of coordinates, where each point is supposed to have *dim* components, where *dim* is the mesh dimension. That means `1.0 0.0 0.0` selects the one point (1,0,0) in a 3D mesh, but the three points (1,0,0), (0,0,0) (0,0,0) in a 1D mesh.

## Design
We have support for lists of lists (with the top level being semicolon separated). I suggest we disambiguate the syntax by making `coords` a `std::vector<std::vector>>` parameter. Ideally we'd make it `std::vector<Point>` and improve how MOOSE handles that type, but that would likely be an app breaking change.

## Impact
Clearer interface

### PR DESCRIPTION
**Pull request by dschwen**
This does not look like it's being tested thoroughly, so I should probably add a test. I do expect app breakage though.

Closes #14936

### CODE REVIEW

**Comment by dschwen** [comment]
Looks like none of the app tests are actually related to this PR.

**Review by permcody — CHANGES_REQUESTED** [review]
This looks like a good change. However, I'm bothered that we don't already have a test in the framework, or the existing test isn't utilizing the capability of accepting multiple nodes. Can we add or expand the current test before this goes in? That will protect us from having somebody refactor this again in the future.

**Comment by dschwen** [comment]
Tests added

**Review by permcody — APPROVED** [review]
Excellent thanks!

**Pull request merged**
