### PR TITLE
Add contact examples 

### PR DESCRIPTION
**Pull request by recuero**
Adding contact examples to showcase MOOSE capabilities:

- 2D frictionless mortar-based spherical indenter
- 2D frictional node-face spherical indenter
- 3D frictional node-face Berkovich indenter

Refs. #14813

### CODE REVIEW

**Comment by recuero** [comment]
Ping @dschwen @jiangwen84

**Review by dschwen — DISMISSED** [review]

**Review by dschwen — APPROVED** [review]

**Review by dschwen — DISMISSED** [review]

**Review by dschwen — COMMENTED** [review]
Actually, this increases repos size by over 6Mb due to checked in large meshes. I wonder if checking in the .jou files is enough.

**Comment by recuero** [comment]
`This PR changes repo size by 6.98 MiB` I don't think that's quite right. I removed the 3D mesh, which was less than 2 MB.

Maybe the best place for this kind of assessment-like problems is a separate repo where we can run the tests from time to time.

**Comment by dschwen** [comment]
Keep in mind that files in older commits affect repo size.

**Comment by recuero** [comment]
That's precisely what I mean (they are not directly included in this PR):

```
1.07 MiB	modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e3.e
1.07 MiB	modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e4.e
1.07 MiB	modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e5.e
1.07 MiB	modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e6.e

**Comment by dschwen** [comment]
Oh, weird, sorry, I'm on my phone. I'll check it out.

**Review by dschwen — DISMISSED** [review]

**Review by dschwen — APPROVED** [review]

**Pull request merged**
