### PR TITLE
Add alternative stress units in LAROMANCE

### LINKED ISSUE #17287: add a few alternative units in LAROMANCE
## Reason

We don't always use units that happen to be consistent with what's required in the ROM.

## Design

Add some additional options in the ROM to handle unit conversion.

## Impact

Unit conversion support for LAROMANCE.

### PR DESCRIPTION
**Pull request by hugary1995**
Use MooseUnits to do the conversion

closes #17287

### CODE REVIEW

**Comment by hugary1995** [comment]
@lynnmunday here it is. I removed the `RealU` stuff as I don't have time to work on it. I also doubt if anyone will come to this PR anytime soon, so feel free to just cherry-pick this commit onto your branch.

**Comment by dschwen** [comment]
Add a test with `stress_unit = MPa` and the stiffness tensor units changed to MPa as well. This should compare against an existing gold file. Ping @lynnmunday

**Comment by hugary1995** [comment]
BTW, right now this only does unit conversion for stress. If you need unit conversion for other input features let me know.

**Comment by hugary1995** [comment]
For the input file named `3D.i`, the postprocessor outputs are

```
+----------------+-------------------+----------------------+----------------+-------------------+
| time           | cell_dislocations | effective_strain_avg | temperature    | wall_disloactions |
+----------------+-------------------+----------------------+----------------+-------------------+
|   0.000000e+00 |      0.000000e+00 |         0.000000e+00 |   0.000000e+00 |      0.000000e+00 |
|   1.000000e+00 |      6.000000e+12 |         0.000000e+00 |   9.000000e+02 |      4.400000e+11 |
|   2.000000e+00 |      6.000000e+12 |         0.000000e+00 |   9.000000e+02 |      4.400000e+11 |
|   3.000000e+00 |      6.000000e+12 |         0.000000e+00 |   9.000000e+02 |      4.400000e+11 |
|   4.000000e+00 |      6.000000e+12 |         0.000000e+00 |   9.000000e+02 |      4.400000e+11 |
|   5.000000e+00 |      6.000000e+12 |         0.000000e+00 |   9.000000e+02 |      4.400000e+11 |
+----------------+-------------------+----------------------+----------------+-------------------+
```

and if I change the unit to `kPa` (not even `MPa`), the outputs become

```
+----------------+-------------------+----------------------+----------------+-------------------+
| time           | cell_dislocations | effective_strain_avg | temperature    | wall_disloactions |
+----------------+-------------------+----------------------+----------------+-------------------+
|   0.000000e+00 |      0.000000e+00 |         0.000000e+00 |   0.000000e+00 |      0.000000e+00 |
|   1.000000e+00 |      5.989511e+12 |         1.483769e-06 |   9.000000e+02 |      4.400000e+11 |
|   2.000000e+00 |      5.978860e+12 |         2.940074e-06 |   9.000000e+02 |      4.400000e+11 |
|   3.000000e+00 |      5.968068e+12 |         4.371130e-06 |   9.000000e+02 |      4.400000e+11 |
|   4.000000e+00 |      5.957158e+12 |         5.778851e-06 |   9.000000e+02 |      4.400000e+11 |
|   5.000000e+00 |      5.946149e+12 |         7.164902e-06 |   9.000000e+02 |      4.400000e+11 |
+----------------+-------------------+----------------------+----------------+-------------------+
```

Once I change it to `MPa`, it errors with negative cell dislocation density.

This ROM is inherently sensitive to feature units. Even if we come up with a test that gives us consistent results with different units, IMHO that's still pointless.

If we want to test the conversion utility provided MooseUnit, well, that's already been tested in unit tests.

**Comment by hugary1995** [comment]
Well, I guess "the ROM gives different results with different input units" is the very reason why @lynnmunday wanted this PR.

**Comment by dschwen** [comment]
I don't quite understand this. I thought the whole point here is to have LAROMANCE work with the units it was fitted on, regardless what the stress units in the stress units in MOOSE are. Why can't you decouple the MOSOE units from the LAROMANCE units?

**Comment by dschwen** [comment]
Have you adjusted both elasticity tensor and pressure bcs?

**Comment by hugary1995** [comment]
Yeah I shouldn't say it is sensitive to units, I wanted to say it is sensitive to 

> Have you adjusted both elasticity tensor and pressure bcs?

Oh yeah, you are right. I take back everything I just said. This is what happens when I wake up coding at 7 am with a bad mood.

**Review by dschwen — APPROVED** [review]
Looks good to me!

**Comment by hugary1995** [comment]
Thanks for your `moose-hit-format` package -- it bumps up my contribution statistics everytime I touch an old input file.

**Comment by lynnmunday** [comment]
@hugary1995 I just repeated everything you have here.  I want to use this with your phase field fracture input file.

**Pull request merged**
