### PR TITLE
Gallery: Simulation result of flow through digital rock

### LINKED ISSUE #17364: Gallery: simulation result of flow through digital rock
Adding video of flow through rock to MOOSE gallery

### PR DESCRIPTION
**Pull request by mlesueur**
closes #17364
I have added the video and its caption in gallery.md and updated the large_media submodule.
@fdkong @lindsayad, please have a look.

### CODE REVIEW

**Comment by hugary1995** [comment]
Nice movie!

**Comment by lindsayad** [comment]
@mlesueur ive invited you to the moose org. After you’ve accepted please do something like git commit —amend and then force push to initiate automatic testing of your PR. That will allow us to see the site build which is what I’m interested to see :-)

**Comment by mlesueur** [comment]
@lindsayad You can check out the updated gallery here: https://mooseframework.inl.gov/docs/PRs/17365/site/gallery.html
I don't know why a computational test is failing...

**Comment by fdkong** [comment]
The video is really cool!!!

**Review by lindsayad — APPROVED** [review]
Awesome! Seems like the `large_media` hash was pointing to something off the master branch before...weird

**Comment by mlesueur** [comment]
Thank you @lindsayad @fdkong @hugary1995 :)

**Pull request merged**
