### PR TITLE
FluidProperties: tabulated version of CO2 properties

### PR DESCRIPTION
**Pull request by cpgr**
The `CO2FluidProperties` formulation in `fluid_properties` requires iterations to calculate properties as a function of pressure and temperature. To speed up calculation, interpolation is used on tabulated data.

This adds a base class in utils to read and write tabulated data files, and a tabulated version of `CO2FluidProperties`.

Refs #9016

### CODE REVIEW

**Comment by andrsd** [comment]
Unless I missed something, I think your `CO2TabulatedFluidProperties` class can be generalized. If you passed a `UserObjectName` into it instead of building the user object by yourself. Your syntax would be then:
```
[FluidProperties]
  [./co2]
    type = CO2FluitProperties
  [../]
  [./co2tabulated]
    type = TabulatedFluidProperties
    file = <file name>
    fp = co2
  [../]
[]
```
This way you can do any properties with one class as long as you have the data file and the fp object.

**Comment by cpgr** [comment]
I started with that design (hence the 2 in the branch name), but couldn't decide on the best way to make the implementation general. My thought was to read in whatever properties are provided in tabulated form and use the `fp` user object for all of the remaining properties. Something like

```
TabulatedFluidProperties::rho(Real pressure, Real temperature)
{
  if (is_rho_tabulated)
    return interpolated_density
  else
    return fp->rho(pressure, temperature)
}
```

Do you think this would be better? I didn't know so spun the file reading out to another class and just made a CO2 tabulated properties.

**Comment by andrsd** [comment]
I understood that `rho`, `e`, `h` is always provided, therefore you would always only have:
```
TabulatedFluidProperties::rho(Real pressure, Real temperature)
{
  return interpolated_density;
}
```
and for quantities like `beta`, you would always call the `fp` object:
```
return fp->beta(...);
```
So, if somebody gives you a data file without `rho`, you tell them "it is not a correct data file".

If your data file can provide different quantities, i.e. sometimes it would have `rho`, sometimes it would not, you could do something like:
```
readFile()
{
  if have `rho`
    use the values from file;
  else
    generate the interpolation for `rho` using fp object;
}
```
then your `rho()` et al. would always call the interpolated value. And there would be the initial cost of generating the interpolation. Which would work if it is not expensive. If it is expensive, then yes, you would need that:
```
if (provided)
  return interpolated_value;
else
  return fp->XYZ();
```

**Comment by permcody** [comment]
My general take on this is that I don't like all of the "file readers" that we are accumulating in MOOSE. We have several at this point, all slightly different, almost none of them scalable to thousands of processors. 

I know it's a problem that the framework doesn't supply a general CSV reader yet, but it's on our list FWIW. What are the chances that when we supply one, people will use it over existing ones that have been committed?

**Comment by cpgr** [comment]
The file reading is the bit I dislike most about this! I promise to use the framework one when it is available! I just couldn't get the one I found (griddeddata) to work for multiple properties.

**Review by andrsd — APPROVED** [review]

**Comment by andrsd** [comment]
Sorry for the delay @cpgr

**Comment by cpgr** [comment]
No worries

**Comment by cpgr** [comment]
Hi @permcody 

I just noticed on the mailing list that there is a csv reader in utils now. Looking at it, I could use it in this tabulated properties reader like so

    pressure, temperature, density, enthalpy, internal_energy
    p1, t1, rho11, h11, e11
    p1, t2, rho12, h12, e12
    p1, t3, rho13, h13, e13
    p2, t1, rho21, h21, e21
    p2, t2, rho22, h22, e22

etc.

It does mean that there is duplication in the pressure and temperature values, but i guess it doesn't really matter as it is only read at the start.

**Comment by permcody** [comment]
Yeah, I wouldn't worry too much about the duplicate values.

**Pull request merged**
