### PR TITLE
Exodiff Map disable

### LINKED ISSUE #6011: Ability to turn off "map" option for Exodiff
A test might want to disable to `map` option for Exodiff.

An example is that the `map` option fails if two elements are perfectly on top of each other (which you might be trying to do on purpose....

### PR DESCRIPTION
**Pull request by friedmud**
Just putting this here for now... I'll come back around and add a test for it later...

I also see that I need a rebase on the branch... I'll fix it later... no time... but I didn't want to forget this....

closes #6011

### CODE REVIEW

**Comment by permcody** [comment]
Just noticed that we already support "exodiff_opts" in the TestHarness. You don't need a new "map" option.

**Comment by friedmud** [comment]
No: we do.  We currently ALWAYS have mapping turned on... there is no way to turn it off by passing options

**Comment by permcody** [comment]
ping @friedmud

**Comment by friedmud** [comment]
I'm on it.

**Comment by friedmud** [comment]
This can be merged when you like.

**Pull request merged**
