### PR TITLE
Adding ICEUpdater Output for Real-time MOOSE updates to ICE. Refs #5663

### PR DESCRIPTION
**Pull request by amccaskey**
This will enable the use of a new Output subclass called ICEUpdater that lets users post Postprocessor data to a running ICE instance for real-time plotting as the MOOSE simulation is running. This issue for this request is #5663

### CODE REVIEW

**Comment by dschwen** [comment]
Uhm, did you rebase against master? That might explain the 250+ commits in this PR.

**Comment by amccaskey** [comment]
Not sure about the commits. Everything is up to date with idaholab/devel.

**Comment by amccaskey** [comment]
Build failing because it can't include curl/curl.h. Is libcurl installed on the build server?

**Comment by dschwen** [comment]
Yes, it may be up to date with devel, but it also contains the merge commits from master. I'd make a new branch from current devel and cherry pick your commits onto that and push. You should also squash some of those commits.

**Comment by jwpeterson** [comment]
There are a number of issues here, the main one is that you merged master into devel:
```
Merge branch 'master' of https://github.com/amccaskey/moose into devel
```
which should never happen in MOOSE (merges always go the other direction).  I'll take a crack at cleaning this up and will make a new PR.

**Comment by amccaskey** [comment]
My bad, I accidentally did that merge and thought I had reversed it. Thanks for the help on this.

**Comment by jwpeterson** [comment]
Replaced by #5717.

**Pull request closed without merging**
