### PR TITLE
Add longer running examples to the contact module 

### LINKED ISSUE #18648: Add set of practical contact regression tests
## Reason
We need to avoid regression in practical contact models which require to run for longer than a few minutes.

## Design
Create a new test file (e.g. `examples`) that will run according to its particular CIVET recipe (longer running, on more processors). 

## Impact
 - Quality assurance on models for which we have an analytical solution (e.g. Hertzian setups)
 - Avoid regression in contact models used for validation
 - More practical examples will be available to users

@dschwen @jiangwen84

### PR DESCRIPTION
**Pull request by recuero**
Tests added:

 - Berkovich indenter with displacement control
 - Berkovich indenter with force control
 - Spherical indenter with displacement control
 - Quarter symmetric sphere on a plane (Hex27)
 - Two dimensional spherical indenters on plastic material 
 - Axisymmetric frictionless sphere on plane (first and second order)
 - Frictional 2d cylinder, NTS and mortar

Closes #18648

### CODE REVIEW

**Comment by lindsayad** [comment]
I think we want to limit growth of the repository and this grows it by 10 MB. Is this from input meshes or output files or both?

**Comment by recuero** [comment]
It's from input meshes. Any way they can be placed in large_media?

**Comment by lindsayad** [comment]
Generated by cubit? Or another meshing software?

**Comment by recuero** [comment]
Cubit

**Comment by dschwen** [comment]
It'd be great if we could create those meshes on the fly. Any chance you
could mesh those with gmsh and just upload the geo?

**Comment by recuero** [comment]
Like potentially using https://github.com/idaholab/moose/issues/18567? I'd need to figure out how to create those meshes with Gmsh but I guess it'd be doable.

**Comment by lindsayad** [comment]
We won’t be able to do gmsh based mesh generators but you could write a standalone python or c++ program that links libgmsh or you could go the geo script route. @dschwen i thought we discussed that if we were going to support processing gmsh inputs for the test harness that we should also consider processing cubit inputs?

**Comment by recuero** [comment]
>we should also consider processing cubit inputs

We already have a good number of cubit scripts for these meshes, so that'd be my preferred option to check in these examples.

**Comment by dschwen** [comment]
Yeah, that's fine. I'm just worried that Cubit scripts are less accessible
for users as Cubit is not as easily available as gmsh.

**Comment by lindsayad** [comment]
@recuero sorry for the hold-up here. @bwspenc @dschwen @milljm and I are exploring the feasibility of getting "on-the-fly-meshing" going. Were you hoping to get this PR in quickly?

**Comment by recuero** [comment]
I am happy to wait to see if we can use that capability to do on-the-fly meshing. It'd be great to test practical examples with fine meshes without adding unnecessary repo size.

**Pull request closed without merging**
