### PR TITLE
Op interface 6279

### LINKED ISSUE #6279: Multiphase Order Parameter Barrier
A material class should be created which prevents multiple order parameters from increasing above 0 on an interface between two order parameters for the multiphase phase field module. Only the two order parameters present on either side of the interface should see any change. Adding a term to the free energy similar to the following should work:

`Constant * eta_i^2 * eta_j^2 * eta_k^2`

I propose we add another barrier function material option with that equation and name it something like OPInterfaceBarrierMaterial.

### PR DESCRIPTION
**Pull request by jbair34**
Closes #6279 . Should be approved by @dschwen. Height of barrier can be controlled by modifying the W in the DerivativeMultiphaseMaterial.

### CODE REVIEW

**Comment by jwpeterson** [comment]
img_0199

**Comment by permcody** [comment]
This might be a new record for number of merge commits in a PR!

**Comment by jbair34** [comment]
Sorry I have no idea how all of those showed up... I tried to squash my 4 commits into 1 and I thought it had worked but now I have no idea how these all showed up...

**Comment by jwpeterson** [comment]
You rebased on master, you need to rebase on devel.

**Comment by jbair34** [comment]
Crap. Sorry about that... Is there an easy way to fix that?

**Comment by jwpeterson** [comment]
You have 1 patch, right?  Start fresh:
```
git fetch upstream
git checkout -b fresh_branch upstream/devel
git cherry-pick 61935ce
```

You also apparently have some tab characters in your commit that you need to get rid of.

**Comment by jbair34** [comment]
I am sure this is an incredibly dumb question but what is a tab character?

**Comment by jbair34** [comment]
Also I tried the git fetch upstream command and it says:
error cannot open .git/FETCH_HEAD: Permission Denied

**Comment by jwpeterson** [comment]
> I am sure this is an incredibly dumb question but what is a tab character?

It's a whitespace character which is not a regular space, newline, carriage return, etc. etc.

Add this to your .gitconfig file, and `git log -p` will highlight tab characters in red:
```
[core]
  whitespace = trailing-space,space-before-tab,tab-in-indent
```

**Comment by permcody** [comment]
They look like this:

**Comment by jbair34** [comment]
So I think the reason that i can't do the git fetch head thing may be because the university installed MOOSE on this desktop and they did it in a place where in order to change any files I have to use the sudo command. But I can't use the sudo command for git things (except git pull) because it says Permission denied (publickey). And without the sudo command it tells me what I put above which I think is from the lack of a sudo there... Any ideas? Sorry for being a pain.

**Comment by permcody** [comment]
Your University help desk is doing it wrong! Send them to moose-users so we can chastise them

**Comment by jwpeterson** [comment]
> So I think the reason that i can't do the git fetch head thing may be because the university installed MOOSE on this desktop and they did it in a place where in order to change any files I have to use the sudo command.

I think you need to start over --  you should not be using sudo and you should not be working in a repository owned by root.

If you have a home directory on this system you are on, you need to start by cloning MOOSE there, not in a directory owned by root.

**Comment by jbair34** [comment]
So do we just delete this pull request and open a new one? I got those issues fixed so I don't have to sudo anymore and have recommitted stuff to the new branch which I believe should be on devel not master.

**Comment by jwpeterson** [comment]
Yes, let's close this and forget it ever happened.

**Pull request closed without merging**
