### PR TITLE
Dont duplicate NodalKernel computation on interfaces

### LINKED ISSUE #16265: NodalKernel computation duplicated on nodes shared between subdomains
## Bug Description
This is reported at https://github.com/idaholab/moose/discussions/16227#discussioncomment-134829. 

## Steps to Reproduce
You can just look at the current code:
```c++
  const std::set<SubdomainID> & block_ids = _aux_sys.mesh().getNodeBlockIds(*node);
  for (const auto & block : block_ids)
    if (_nkernel_warehouse->hasActiveBlockObjects(block, _tid))
    {
      std::set<TagID> needed_fe_var_vector_tags;
      _nkernel_warehouse->updateBlockFEVariableCoupledVectorTagDependency(
          block, needed_fe_var_vector_tags, _tid);
      _fe_problem.setActiveFEVariableCoupleableVectorTags(needed_fe_var_vector_tags, _tid);

      const auto & objects = _nkernel_warehouse->getActiveBlockObjects(block, _tid);
      for (const auto & nodal_kernel : objects)
        nodal_kernel->computeResidual();
    }
```

## Impact
This produces fundamentally wrong results. I guess you could work around this by restricting every `NodalKernel` to a single subdomain, but a user will not intuitively think to do that, and will most likely silently get wrong results.

### PR DESCRIPTION
**Pull request by lindsayad**
Previously we would duplicate `NodalKernel` computation if a node sat on
the interface between two subdomains on which the `NodalKernel` was
active.

Closes #16265

Refs #16227

### CODE REVIEW

**Comment by GiudGiud** [comment]
Does the test return different results when the NodalKernel computation is duplicated?

**Comment by lindsayad** [comment]
Yes it does. When nodal kernel computation is duplicated, the solution has a uniform value of 4, corresponding to 4 nodal impulses: two from the nodes at the domain boundaries, and two from the center node. Without the duplication the solution is (close to) 3 across the domain. (It's actually interesting to me that the solution is not exactly uniformly 3, but I suppose that the `Diffusion` kernel slightly messes with the balance between the nodal sources and the reaction sink)

**Comment by loganharbour** [comment]
Any chance that you want to use emplace here in the set so that you don't do two searches in the map?

**Review by loganharbour — COMMENTED** [review]
Any chance that you want to use emplace here in the set so that you don't do two searches in the set?

```
if (nks_executed.emplace(nodal_kernel.get).second)
```

**Comment by lindsayad** [comment]
> Any chance that you want to use emplace here in the set so that you don't do two searches in the set?

Yea I suppose I don't care much about the argument forwarding of `insert` vs `emplace` but checking the return value to avoid the two searches as you say is a stellar idea

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
