### PR TITLE
Fixing the revert

### LINKED ISSUE #6845: Initial contribution to PorousFlow module
This will be a major commit from our code sprint.  The work is still unpolished, but the functionality is there and it is becoming increasingly difficult to work in this "mega branch" that we have.  It'll be easier once this is merged and we can follow the standard incremental approach with issues+PRs on idaholab/moose.

### LINKED ISSUE #6939: PorousFlow rename internal parameter _dicatator_UO to _dictator
Suggested by @dschwen.  This will be easier to do when the backlog of PRs is merged.

### LINKED ISSUE #6986: Change component_index to fluid_component_index in PorousFlow
### Description of the enhancement or error report

Some Kernels etc have input "component_index".  This can actually lead to subtle bugs because "component_index" is used elsewhere to mean "spatial component index", and we inherit from stuff that has "component_index" already.  We should change to "fluid_component_index".  

Tagging @cpgr

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #6986
Fixes #6939
Fixes #6845

### CODE REVIEW

**Comment by WilkAndy** [comment]
Wow, that git stuff took about 1.5 hours to do !   @permcody - hopefully this does the trick.  it must have been difficult for you to figure out which commit broke the tests

**Comment by cpgr** [comment]
Hooley dooley!

**Comment by WilkAndy** [comment]
Heheheh, all because of 6 lines in your Dirac tests that conflicted with a PR of mine, and both got merged at the same time.

**Comment by cpgr** [comment]
Lucky I got in first then he he he

**Comment by WilkAndy** [comment]
:-)

**Comment by dschwen** [comment]
👍  This just renames a few members and input parameters.

**Comment by permcody** [comment]
👍

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Pull request merged**
