### PR TITLE
Added PostprocessorInterface to InitialConditionBase

### LINKED ISSUE #17692: Add `PostprocessorInterface` to initial conditions
## Reason
Sometimes initial conditions depend on post-processor values. One example is this: a user provides a distribution function, but it needs to be normalized first, which requires an integral of that function, and thus `ElementIntegralPostprocessor` can be used for this.

## Design
This would have `InitialConditionBase` inherit from `PostprocessorInterface`.

## Impact
This allows initial conditions to inherit the APIs provided by `PostprocessorInterface`.

### PR DESCRIPTION
**Pull request by joshuahansel**
- Added PostprocessorInterface to InitialConditionBase
- Added overloads for InitialConditionBase::getPostprocessorValue
  and InitialConditionBase::getPostprocessorValueByName that add
  the post-processor name to the user object dependency list
- Tested correct dependency resolution of both new overloads
- Added news entry

Closes #17692

### CODE REVIEW

**Comment by joshuahansel** [comment]
@rwcarlsen You were complaining about getting PRs that were too big, so I figured I'd be doing you a favor by asking you to review 😛

**Comment by loganharbour** [comment]
Sorry @joshuahansel - I'm here to ruin your day with #17527

**Comment by joshuahansel** [comment]
@loganharbour The one time I try and make a contribution to MOOSE, and now the last! It was your birthday, so I'll allow it 😄 

I'll see if I can figure out what to do now.

**Comment by joshuahansel** [comment]
@loganharbour I'm offering you the honor of reviewing this. It took me a whole 2 minutes to clean up this disaster!

**Review by loganharbour — APPROVED** [review]
Even fewer lines! @rwcarlsen would be proud.

**Pull request merged**
