### PR TITLE
Ad grad u dot

### LINKED ISSUE #16167: Add gradient of u_dot for AD
## Reason
I want to be able to include a Laplacian of a time rate of change variable in my phase-field model, using AD. Getting the gradient of `u_dot` is implemented for non-AD variables, this would add that functionality for AD varaibles

## Design
Some swinging of the copy-paste wand so `_ad_grad_u_dot` is computed in `MooseVariableData`, and provide the interface in `MooseVariableFE`

## Impact
Adds possibility of gradient-rate dependent kernels

### PR DESCRIPTION
**Pull request by hugary1995**
This is a copy of PR #16168 . I rebased it, and all merge conflicts were trivial. So all reviews in the original PR should still be valid. Let's see if there is still an SQA failure, if so I'll fix it.

The following description is copied from the original PR:

> Using the same methodology as other variables computed using MooseVariableData, adds functionality to compute _ad_grad_u_dot. Also provides necessary interfaces in Coupleable and MooseVariableFE.
> Includes a new kernel ADDiffusionRate, which implements the Laplacian rate of a variable, to show how this functionality may be used. Kernel has accompanying documentation and a test in the phase-field module.
> @hugary1995 @lindsayad
> 
> closes #16167

### CODE REVIEW

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
ADDiffusionRate doesn't appear to have an analog non-AD class in the framework.  Are we sure this class is general enough to belong in the framework - or should it be a test object or in a module?

**Comment by hugary1995** [comment]
How do we determine if this is general enough? I think it is.

**Review by rwcarlsen — DISMISSED** [review]

**Review by rwcarlsen — DISMISSED** [review]

**Review by GiudGiud — APPROVED** [review]
I m totally fine with the plethora of (mat / vectormat / coef / function) Diffusion/Reaction/BodyForce in the framework.
They come in handy for hacking small simulations together, which is a goal for pure (no apps) framework use

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
completely forgot I had reviewed this already lol

**Pull request merged**
