### PR TITLE
WIP: Mesh meta store

### PR DESCRIPTION
**Pull request by permcody**
Tag @rwcarlsen, @friedmud  - here's the dataLoad, dataStore routines I added for making libMesh::Parameters restartable (for POD types).

### CODE REVIEW

**Comment by permcody** [comment]
@gambka - Can you point me to one of your test cases where MeshModifiers _can't_ be converted to MeshGenerators, or alternatively can you give me a good explanation of your specific difficulty that you are overcoming. I've started a restartable datastore here but I need a problem to solve now.

**Comment by gambka** [comment]
> alternatively can you give me a good explanation of your specific difficulty that you are overcoming. I've started a restartable datastore here but I need a problem to solve now.

It is not a case of a MeshModifier but more of a case of moving a MeshObject over to a MeshGenerator (if I recall correctly this is also desired so you can use them with the new MeshGenerator versions of MeshModifiers).  The issue is we have Actions that query the Mesh to see if the correct MeshObject is being used (i.e, the action is only valid for that particular type of mesh).  Upon restart the actions are re-executed and since the MeshObject is created upon restart we can perform the proper check on the Mesh.  However, because MeshGenerators are not executed upon restart we are unable to check whether or not the correct mesh generator has been supplied.  

In addition, the MeshObject/MeshGenerator contains a methods to store information about the mesh that is read by a UserObject which passes information to material models to avoid user input error.  The UserObject also performs a check that the supplied Mesh is the correct type.  Therefore, we encounter the same error upon restart if it is in a MeshGenerator. I have figured out how to check if a certain MeshGenerator exists but upon restart that check fails because no MeshGenerators exist.  There is not an example in MOOSE, but if you want to see code that shows what is being done you can look in Bison at:

```
Layered1DFuelPinGeometry (the UserObject)
Layered1DMesh
Layered1DAction
``` 

OR

```
Layered2DFuelPinGeometry (the UserObject)
Layered2DAction
Layered2DMesh (I did create a Layered2DMeshGenerator originally and it still exists it is just not currently coupled to the Action or UserObject because it doesn't work on restart)
```
I think if we can store off the information related to the methods that is used by the UserObject we can avoid the check on the MeshObject/MeshGenerator type on restart or recover by encapsulating it in an if statement like:

```
if (!_app.isRecovering())
{
   Check the type
}
```

**Comment by permcody** [comment]
@gambka - So I can't see the holdup here. There are two phases to this work.

1) MeshModifiers -> MeshGenerators: This is the immediate task and the holdup is BISON but I don't see anything that you wrote above that would prevent this from working now. 

2) MooseMesh derived objects -> MeshGenerators: Now this is where things get a little more complicated, however we aren't enforcing this right now and probably not for awhile. This will require storing data on the Mesh meta-data store, which is what I'm trying to design. 

If MeshModifiers went away tomorrow, how would that break you?

**Comment by YaqiWang** [comment]
I know it will break Rattlesnake because we have several mesh modifiers...

**Comment by permcody** [comment]
@YaqiWang - Yes, but assuming we convert your MeshModifiers to Generators, is there a specific hangup? I need a few problems so that I can design a solution.

**Comment by gambka** [comment]
@permcody 
I think the problem is we have a few tests that have apply a MeshModifier to one of those MooseMesh derived objects.  Now that the format is to have MeshGenerators nested into [Mesh] what do you use for the input into the MeshGenerator version of the MeshModifier? 

```
[Mesh]
  type = MyAwesomeMesh
  [./BoundingBoxNodeSet]
    type = BoundingBoxNodeSet
    bottom_left = '-1 -1 0'
    top_right = '2 2 0'
    new_boundary = 1000
    input = ????? <--- needs to be a MeshGenerator (even if the MeshGenerators are not nested here you can't supply anything but a MeshGenerator)
  [../]
[]
```
 
Now, to be able to apply the modification  I must convert MyAwesomeMesh to MyAwesomeMeshGenerator, but now if I do that I will fail the recover testing target for the reasons described previously. And I don't think the solution is to create the MeshGenerator and add `recover =false` to the tests.  It should behave exactly as before.

**Comment by permcody** [comment]
@gambka - Now that makes sense!

**Comment by YaqiWang** [comment]
No, should be quite strait-forward to convert them. We have actions automatically adding mesh modifiers after all modifiers in the input. To make these actions work properly we will need to have MooseApp returns the current final mesh generator.

**Comment by friedmud** [comment]
@permcody I don't understand how people are supposed to use this.

There needs to be a `MeshMetaDataInterface` that `MeshGenerator`s inherit from.  It should have a `declareMeshMetaData()` on it that adds to the `_mesh._meta_data` and returns a reference to the data.

Then, when the Generator runs it can set the value of that meta data.

When a restart file gets written the final mesh will be written out (like usual) and the meta-data that was declared will get written out (because of what you've done here).

When restart occurs the mesh file that was written out will be read back in (like normal) and the meta-data will be restored (which are the values that were set by Generators).

In this way @gambka can make `MyAwesomeMeshGenerator` which will declare mesh-meta data and set their values during generation.  The `BoundingBoxNodesetGenerator` will also get run... creating the final mesh.  The mesh, as it is in memory, will get written out as a restart file... and the meta-data created in `MyAwesomeMeshGenerator` will also get written out.  On restart: no generators run.  The final mesh (with the added nodesets) is read back in - and so is the meta-data... perfectly recreating the end-result of the original generators.

**Comment by permcody** [comment]
Basically yes. This was more or less the discussion we had and the
direction I’m heading. I’ve been working on it a bit since late last week
but the interruptions have been constant.

**Comment by permcody** [comment]
superseded by #14190.

**Pull request closed without merging**
