### PR TITLE
PorousFlow uses saturation not effective saturation

### LINKED ISSUE #13131: Change effective saturation to saturation in PorousFlow
## Reason

I believe that it is correct for PorousFlow to return **saturation** rather than **effective saturation** when using capillary pressure to compute saturation.

## Design

Currently the saturation calculators set the saturation equal to the effective saturation returned by the capillary-pressure user object.  Change this to plain-old saturation.

## Impact

This is potentially a significant change for users who employ a nonzero  ```sat_lr```.  I'm not aware of users doing this, however.  The saturation enters the relative permeability - so potentially a big change here - and also the fluid mass calculation, which is probably a smaller impact because we're computing time derivatives of saturation.

Before this change gets merged, i need @cpgr to agree it's the right thing to do.

### PR DESCRIPTION
**Pull request by WilkAndy**
**BEFORE MERGING** @cpgr has to "OK" this change.

Includes minor changes to tests that were not necessary for this PR, but which i thought would make them more useful to users.

Fixes #13131

### CODE REVIEW

**Comment by cpgr** [comment]
Hi Andy,

I think this is the correct thing to do, and what you have done looks fine.

Can you also update the documentation for capillary pressure to note that we can now return true saturation as well? And maybe a note on the documentation for PorousFlow1PhaseP and PorousFlow2PhasePP that saturation is now true saturation?

**Comment by WilkAndy** [comment]
Thanks Chris.  Yep, i'll do those things you recommend.

**Comment by cpgr** [comment]
I've been poking around the code a bit more and the actions don't have a `sat_lr` param, so the VG capillary pressure function always used `sat_lr = 0`, so this change shouldn't affect anyone using them.

We should probably add a `sat_lr` in the input parameters for these actions though to allow one to be set.

**Comment by WilkAndy** [comment]
I've done the doco - have a look to see if you approve.

Yea, i agree about the Actions.   Shall we do it in a separate issue?

**Comment by cpgr** [comment]
Looks good Andy. Thanks for doing that.

Let's leave the sat_lr thing for the actions for another PR

**Review by cpgr — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks @cpgr

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Fantastic - thanks for the review and merge, @permcody

**Pull request merged**
