### PR TITLE
Fixing tutorial steps 9 and 10

### PR DESCRIPTION
**Pull request by andrsd**
1. The RZ symmetry is about x axis
2. Temperature is coupled in mechanics so that we get non-zero displacements

### CODE REVIEW

**Comment by andrsd** [comment]
No idea if 76285e8 is correct. I copied it from another test. We do get non-zero displacement now. I also changed the preconditioner to LU, because the convergence was pretty bad.  It runs better now, but may be a different setup should be used (I do not know what would be a better one though). Free free to make suggestions...

**Comment by sapitts** [comment]
The B matrix in the stress divergence rz kernel for tensor mechanics assumes that the y-axis is the axis of symmetry; to use the x-axis as the axis of symmetry the rz kernel should be expanded to check for the axis of symmetry and switch the components used in the residual and jacobian calculations

**Comment by andrsd** [comment]
Ok, so that's probably the __real__ reason why the RZ symmetry is about Y-axis. Thanks @sapitts, I will fix this PR accordingly.

**Comment by sapitts** [comment]
Thanks @andrsd; I'll update the documentation for the stress divergence RZ kernel to make that distinction clearer

**Review by friedmud — APPROVED** [review]
This is kind of a bummer - but I guess there's no way around it.  I would really rather the `TensorMechanics` system was able to setup a simple thermal strain automatically with just a couple of input parameters... but I can also see that it's really problem dependent.

**Pull request merged**
