### PR TITLE
Handled deleted files correctly in clang-format hook script

### LINKED ISSUE #11762: Clang-format hook from script does not handle deleted files
## Rationale
The clang-format hook installation script tries to add all staged changes, including deleted files, which results in an error.

## Description
The fix to this would exclude deleted files from `git add`.

## Impact
No API change.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #11762.

### CODE REVIEW

**Comment by joshuahansel** [comment]
@jwpeterson Would you review this? I have no idea how I haven't run into this issue before today... Could you verify the issue with the old script and that the new script solves it?

**Comment by jwpeterson** [comment]
> Could you verify the issue with the old script and that the new script solves it?

So to verify the issue I just have to `git rm` some files and then run `git clang-format`?

**Comment by joshuahansel** [comment]
> So to verify the issue I just have to git rm some files and then run git clang-format?
`git rm file` and then try to commit (with the old hook installed).

**Comment by joshuahansel** [comment]
Basically I think it just boils down to `git rm file` and then `git add file`...

**Comment by jwpeterson** [comment]
While looking at this, @joshuahansel and I also figured out that the 
```
git rev-parse --show-superproject-working-tree
```
command that is used in the script does not work for git version <= 2.7.4, but does work in 2.15.x, so we will also need to fix that up.

**Comment by jwpeterson** [comment]
According to @permcody's computer, the flag is also supported in git 2.13

**Comment by jwpeterson** [comment]
According to [this](https://git-scm.com/docs/git-rev-parse/2.13.2), it was present in 2.13.2 release but not in 2.12.0.

**Review by jwpeterson — APPROVED** [review]
I did not test the old version of the script but the new version seems to work fine so 👍

**Pull request merged**
