### PR TITLE
Start checking for failure when opening output streams

### PR DESCRIPTION
**Pull request by permcody**
refs #11171

### CODE REVIEW

**Comment by permcody** [comment]
@stimpsonsg, I put in this PR in an attempt to track down a user-reported bug earlier this week. This PR is probably a good idea and we did find the other problem (turned out it was unrelated), but this PR fails only one test in Tiamat, which actually indicate a more serious issue:
https://civet.inl.gov/job/173180/

The failure looked a little bit like this ticket (https://github.com/idaholab/moose/issues/6270), so I started wondering if we need to think about this issue a bit more. Take a look at that ticket and failure and lets see if this is affecting you and what you would like to do about it.

Thanks!

**Comment by mangerij** [comment]
By the way Cody, what is the procedure for me? Is there a way to drop the default tolerance on that absolutelyFuzzy function? Or is there still a debate? Anything break on CIVET when the default is dropped?

To be honest, if you don't have convergence problems, I see no problem with having a small time step. Plenty of codes seem to have no problems with this. 

I'm still testing my implementation -- so we can debate this for a while. I'll use the hack in the mean time.

**Comment by stimpsonsg** [comment]
Okay, so it's not writing an output CSV file and your new check is flagging that as a failure, correct?

We've seen some flakiness in actual Tiamat with respect to CSV files (especially vector post-processor CSV files), but there always seems to be a typical output CSV (just the timesteps reported to it are sparse).

Are you thinkin we need to make a change in Tiamat to guarantee this output?

**Comment by stimpsonsg** [comment]
Hmmm, okay.  It's not clear to me that we're doing anything that would impact MOOSE/Bison writing files, but I can understand why you'd think that.

**Comment by permcody** [comment]
@stimpsonsg - It turns out that there is a bug somewhere in Tiamat that this PR exposes. I was trying to help @gardnerru troubleshoot a few issues with a coupled solve yesterday and he noted that the Exodus file contained the correct number of time steps for a particular run while the corresponding CSV file only had three steps written to it. 

I've looked through the framework and can't see any issues on our side. This PR passed around 30 apps and Tiamat was the only one that failed. Something is definitely wrong there.

**Comment by permcody** [comment]
UPDATE: Turns out the Tiamat failure is real. We have no test coverage for when a subapp fails, where we are also writing CSV files from the subapp.

**Comment by friedmud** [comment]
Fascinating - and also a bummer!  What’s the problem here?  If the step fails nothing should get output - but the next time through it should keep adding to the file.  I don’t get it.

**Comment by permcody** [comment]
FormattedTable keeps it's stream open for efficiency. This helps for 1D calcs and probably explicit (although I haven't timed it) since you aren't opening and closing the file all the time. This problem was triggered when a class level Boolean got out of sync with the actual filehandle state (happens during a restore operation). The logic was trying to open an already open filehandle due to this discrepancy. 

The right solution here is to just query the filehandle for it's state where appropriate instead of using a separate Boolean.

**Comment by jwpeterson** [comment]
@permcody Checking `if (stream.fail())` misses `stream.bad()` cases, which I think you probably also want to error out on. (I don't remember the exact distinction between `failbit` and `badbit`, but neither are "good". Instead `if (!stream.good())` should be used.

https://stackoverflow.com/questions/41926303/difference-between-ifstream-good-and-boolifstream

**Comment by jwpeterson** [comment]
Oh, wait, [this](http://en.cppreference.com/w/cpp/io/basic_ios/fail) says `fail()` returns true if either `failbit` or `badbit` is set, LOL. So, this is probably fine then?

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
