### PR TITLE
Tutorial 1: Step 8

### LINKED ISSUE #15707: Improve MPI Instructions (I mean create them)
## Reason
Apparently we are not explaining how to use MOOSE with MPI.

## Design
Add some MPI instructions to our Getting Started instructions

## Impact
Show how to use MOOSE based apps with MPI

### PR DESCRIPTION
**Pull request by crswong888**
... and a bunch of other minor stuff.

Step 8 introduces the testing system in MOOSE. The exercise is to create a regression test for the `DarcyPressure` kernel that is similar to the simple diffusion test. The user shall also enforce the requirement that the viscosity not be zero-valued by invoking `paramError()` and test it with `type = RunException`.

(refs #15232 #15730 #16214 idaholab/babbler#3 idaholab/babbler#4) (closes #15707)

### CODE REVIEW

**Comment by crswong888** [comment]
@aeslaughter can I be authorized to see results of Internal App tests?

**Comment by aeslaughter** [comment]
The failures are not related to this PR, we are working on a fix.

**Comment by crswong888** [comment]
Okay, I was concerned it was caused by Babbler.

**Comment by crswong888** [comment]
@aeslaughter this is ready for review

**Comment by aeslaughter** [comment]
@crswong888 I will take a look next week. Thanks for the work.

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
