### PR TITLE
Fix more execute on flags and add a simple test

### LINKED ISSUE #8610: FEProblemBase:: _current_execute_on_flag is not set for EXEC_LINEAR
### Description of the enhancement or error report
This flag is currently set by `FEProblemBase::execute()`, which is not called by `FEProblem::computeResidualType()`. Thus this flag is not set for EXEC_LINEAR.

### Rationale for the enhancement or information for reproducing the error
This is in consistent what this flag is supposed to be doing.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None. But I will be using this feature soon to check where the material property evaluation is happening.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #8610.

### CODE REVIEW

**Review by andrsd — CHANGES_REQUESTED** [review]
Let's move the test into `test/tests/misc/execute_on`. We are testing the execute-on flag not the auxkernel. The auxkernel is just a vehicle for making sure the flag is set.

**Comment by YaqiWang** [comment]
Yes, test is moved to misc folder.

**Comment by andrsd** [comment]
You still have that `_aux` suffix in the directory name, the input file and the gold file

**Comment by YaqiWang** [comment]
Thanks @andrsd Names are changed. I was just lazy.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
