### PR TITLE
Add strongly-imposed H(div) Dirichlet BCs

### PR DESCRIPTION
**Pull request by nmnobre**
Hi Alex,

The idea here is to try to strongly impose Dirichlet boundary conditions on problems in H(div) because nobody likes penalties that much.

It's our understanding the only support for strong boundary conditions is via the nodal boundary conditions infrastructure which cycles through boundary nodes, and therefore never has any concept of elements, or their sides, and thus no means for integration. So, here, we instead tried to use the integrated boundary conditions infrastructure to recover the ability to integrate but, of course, this poses some difficulties when the time comes to override the required Jacobian and residual entries.

The approach we took applies a boolean mask on the current element's Jacobian and residual, thereby erasing any entries we wish to override while preserving the entries we wish to keep corresponding to dofs in the bulk of the domain. This all assumes the assembly will go through `ThreadedElementLoopBase<RangeType>::operator()` and thus that any boundary contributions are computed after the bulk element contributions.

Number of (linear) iterations for the tests prescribed by `coupled_electrostatics.i`:

| Element type  | Weak (penalty) BCs | Strong BCs |
| ------------- | ------------- | ------------- |
| HEX27 | 83 | 20 |
| TET14 | 1509 | 1177 |
| TRI6/7 | 328 | 328 |
| QUAD8/9 | 22 | 9 |

Missing:
- documentation
- an implementation for H(curl)/Nédélec one

Possible improvements:
- element-wise multiplication for libMesh's `DenseMatrix` and `DenseVector` to hide it from MOOSE's code
- ~can I omit some postprocessors/variables from a CSVDiff (or a .csv output) to avoid unnecessary redundancy in the gold files?~ Done, thanks @GiudGiud!

Cheers,
-Nuno

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
What you have here is an elegant idea. However, there are APIs in the tagging interface that allow bypassing the local residual and Jacobian data structures so that a residual object can pass its residuals/Jacobians directly to `Assembly`; these APIs are used most commonly by AD objects. 

Sadly, in a case where an `ADKernel` is active, your multiplication by the masking objects won't do anything since that `ADKernel`'s data has already gotten into `Assembly`. A more bullet-proof solution would be to think about how we can generalize what we do for "nodal" boundary conditions for non-nodal boundary dofs. I'm sure @roystgnr would like that.

I was thinking that maybe we could pursue eliminating the APIs that allow circumventing `_local_re` and `_local_ke` ... but the AD objects form their Jacobians entirely based on the global dof indices ... you would have to reverse map into the local indices in order to use `_local_ke`, and that's not something we want to do

**Review by lindsayad — CHANGES_REQUESTED** [review]
above concerns need to be addressed

**Comment by nmnobre** [comment]
> What you have here is an elegant idea. However, there are APIs in the tagging interface that allow bypassing the local residual and Jacobian data structures so that a residual object can pass its residuals/Jacobians directly to `Assembly`;

Yeah, we noticed those. We had a solution intercepting cached entries, but it was so ugly we gave up.

> A more bullet-proof solution would be to think about how we can generalize what we do for "nodal" boundary conditions for non-nodal boundary dofs.

Funny you mention it, because we actually tried that too: https://github.com/idaholab/moose/compare/next...farscape-project:moose:dirichlet_nodal. Ignore the print statements. The important bit is that by skipping all the is-this-a-nodal-variable checks on the example RT0 problem, MOOSE actually overrides the Jacobian and residual entries that you expect (those on the faces at the boundary). The problem is once you're there, you have no way of integrating. As far as I know there's no way of getting an edge/face from a node, is there?

**Comment by lindsayad** [comment]
You don't necessarily need JxW right? That will only influence scaling of the constraint. But you definitely need the `_normals`. So yes we wouldn't be able to use the nodal loop to apply these constraints

**Comment by lindsayad** [comment]
should we keep this open @nmnobre?

**Comment by nmnobre** [comment]
I think I'd very much like to come back to this yes. I'm guessing the bot will shut up if I force push?

**Comment by GiudGiud** [comment]
you just need to comment to fend the bot away

**Pull request closed without merging**
