### PR TITLE
libMesh submodule update

### LINKED ISSUE #26605: Incorrect results for general field transfer test
## Bug Description
The test `transfers/general_field/user_object/subdomain.2d_overlay/projection_needed_receiving` is producing the following solution:
Screenshot 2024-01-19 at 8 10 07 AM
Here, the right side corresponds to the current gold results. The large 5x5 domain is the main application, and the 3 small 5x5 domains correspond to 3 sub-applications. These are supposed to have the solution transferred from a certain block of the main application - the lower left corner (3 horizontal by 2 vertical), with a -1 value being used as an extrapolation constant outside of the domain.

The left side of the image corresponds to the same test run but moving the `to_main` block to the top of the `AuxVariables` block in `sub.i`. This input file ordering should have no effect on the solution, so this is a second red flag for the test. This was discovered in https://github.com/idaholab/moose/issues/26164.

## Steps to Reproduce
Run the above test and observe the results.

## Impact
This is a significant bug that may be producing incorrect results in user models.

### PR DESCRIPTION
**Pull request by roystgnr**
Summary of changes:

- Improved TriangulatorInterface compatibility with quadratic elements
  in boundary and hole meshes, including adjusting triangulation
  elements to match curved boundaries.  This feature is not yet
  compatible with mid-triangulation boundary refinement.
- Added scaling options to Empirical Interpolation Method in
  Reduced-Basis code, handling for cases with linearly dependent
  data, and update plotting.
- Fixed bugs in visualization output of Lagrange data on Tri7, in
  `DirichletBoundary` application on nodesets generated from sidesets,
  and in FEMContext quadrature selection for cases where the first
  variable of a system is higher-order than any of the variables being
  queried by the context.  This last fix prevents excessive numbers of
  quadrature points from being used in some MOOSE GeneralField
  transfer operations.
  
  This should fix #26605

### CODE REVIEW

**Comment by roystgnr** [comment]
(I've cherry-picked from #27226 here so we don't get conflicts with the April news update)

**Review by milljm — APPROVED** [review]
The Conda stuff looks good to me!

**Comment by roystgnr** [comment]
Whoa - did I get it right on the first try?  I'm surprisingly kind of disappointed.  It feels like getting to the end of a Rube Goldberg machine, and sure the cube of sugar I wanted in my tea is now in there, but was there really no room to squeeze in another ravenous toucan or something first?

**Comment by roystgnr** [comment]
Jason seems to have traced the TMAP8 install failure down to a recent PR there, and it's affecting far more than this PR, so we should be good to merge.

**Pull request merged**
