### PR TITLE
Strengthen PETSc options in PorousFlow tests

### LINKED ISSUE #7737: strengthen KSP+PC in porous flow
### Description of the enhancement or error report

A few PorousFlow tests fail on my local computer due to weak preconditioning.  These can be strengthened to make the tests more robust.

### PR DESCRIPTION
**Pull request by WilkAndy**
These are @cpgr 's tests, so i give him the right to veto this PR.

Chris - these tests fail on one of my local computers, unless i include "stronger" PETSc options such as the ones i've used here.

Fixes #7737

### CODE REVIEW

**Comment by cpgr** [comment]
No worries Andy. Do you think it might indicate a small problem with the Jacobian of the dispersion kernel, or that the tests are poorly constructed?

**Comment by cpgr** [comment]
And how did you get all these extra tests to run?

**Comment by WilkAndy** [comment]
You might not be able to do this, Chris, as i think the moose guys had to put me on some list or something.  But what i do is:

 - click "Details" on one of the tests.  That takes you to CIVET
 - Up the top of that page you'll see "Pull request | Event | Job".  Click on Pull request.
 - In the next page you can see "Additional Recipes to run", and you can select the ones you want.

**Comment by WilkAndy** [comment]
Re these tests: i think it's just a fact of life for multiphase/component flow that the Jacobian has a lot of zeroes on (or near) the diagonal, so you need a stronger preconditioner than just bjacobi.

**Review by permcody — APPROVED** [review]
👍

**Comment by WilkAndy** [comment]
I agree, the contact test is unrelated to this PR.

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Pull request merged**
