### PR TITLE
Add LDFLAGS in app.mk

### LINKED ISSUE #14490: Include LDFLAGS variable in makefiles
## Reason
Adding `$(LDFLAGS)` in app.mk, similar to the addition of `$(CXXFLAGS)` in #12969 would allow users more flexibility in specifying linker options (and additional libraries) to accommodate non-standard (or explicitly standard - because of the use of distribution packages rather than the moose environment) environments.

I stumbled across this while trying to enable building with google-perftools. The makefile code

```
ifneq ($(GPERF_DIR), )
    libmesh_CXXFLAGS += -DHAVE_GPERFTOOLS -I$(GPERF_DIR)/include
    libmesh_LDFLAGS += -L$(GPERF_DIR)/lib -ltcmalloc_and_profiler
endif
```

assumes a non-standard install of google-perftools. When using a (Debian) system package the library is located at `/usr/lib/x86_64-linux-gnu/libprofiler.so` and the include at `/usr/include/google/profiler.h`. There is *no* common "GPERF_DIR", and the lib and include paths are *already* in the path list of the compiler.

My workaround here is to add the appropriate options in my bash profile as

```
export CXXFLAGS='-DHAVE_GPERFTOOLS'
export LDFLAGS='-ltcmalloc_and_profiler'
```

Except that `LDFLAGS` is ignored...

## Design
Add `$(LDFLAGS)` to app.mk

## Impact
Added flexibility in the build process.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #14490

### CODE REVIEW

**Review by permcody — COMMENTED** [review]
You'll want to check moose.mk too. It also has it's own build commands.

**Comment by dschwen** [comment]
I also ran into [this issue](https://github.com/gperftools/gperftools/issues/1066) when trying to link tcmalloc. I wonder how you avoid this?! The gist is that must only supply `-ltcmalloc` (or `-ltcmalloc_and_profiler`) when you link the final executable, and _not_ when linking any libraries.

**Comment by dschwen** [comment]
The workaround could be a specific `executable_LDFLAGS` variable that only is added in the `$(app_EXEC):` rule...

**Comment by dschwen** [comment]
Looks like the gperftools issue can be solved by configuring the environment with

```
export CXXFLAGS='-DHAVE_GPERFTOOLS'
export ADDITIONAL_LIBS='-ltcmalloc_and_profiler'
```

...which of course avoids `LDFLAGS` entirely and already works without this PR.

**Comment by permcody** [comment]
So do you want to close this for now?

**Comment by dschwen** [comment]
Yeah

**Pull request closed without merging**
