### PR TITLE
Disable logging for some run modes

### LINKED ISSUE #6300: Refactor Performance Logging in MOOSE
Yes, once and for all. Let's do this. The current log is getting more and more useless since it logs only pieces of a real simulation.

### PR DESCRIPTION
**Pull request by permcody**
closes #6300

### CODE REVIEW

**Comment by permcody** [comment]
How about this @andrsd?

**Comment by permcody** [comment]
Alternative to #6492

**Comment by andrsd** [comment]
I would start with logging disabled and enable it for running input files ;-) But tomayto, tomahto. :+1: and I am going to close my #6492

**Comment by permcody** [comment]
Was dang close to doing it that way.

**Pull request merged**
