### PR TITLE
Fix name emitted by new deprecation APIs

### PR DESCRIPTION
**Pull request by lindsayad**
Refs #23260

### CODE REVIEW

**Review by bwspenc — APPROVED** [review]

**Review by bwspenc — CHANGES_REQUESTED** [review]
I like the change. Can we add a test? That would also be helpful for referring to as a static example of how to deprecate a parameter.

**Comment by YaqiWang** [comment]
It does produce this:
```
*** Warning, This code is deprecated and will be removed in future versions:
The parameter 'vol' is deprecated.
'vol' has been deprecated and will be removed on 10/1/2023. Please use 'volume' instead
```
Can we add a period sign at the end?

**Comment by YaqiWang** [comment]
Now the warning becomes:
```
/Users/wangy2/projects/gitlib/griffin/radiation_transport/test/tests/materials/neutron/AConstantNM2.i:315: (UserObjects/UO1/vol):
'vol' has been deprecated and will be removed on 10/1/2023. Please use 'volume' instead.
```
without the backtrace. Looks great!

**Review by YaqiWang — DISMISSED** [review]

**Comment by lindsayad** [comment]
I'm glad you like it @YaqiWang! Yea I think it is much improved. It gives much more helpful detail to the user without repeating itself over and over and giving the unhelpful backtrace.

I will add a test shortly, and then hopefully we can get this merged

**Comment by lindsayad** [comment]
@bwspenc I think this is ready for re-review

**Review by YaqiWang — APPROVED** [review]

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
