### PR TITLE
Added getElementalValueOld interface

### PR DESCRIPTION
**Pull request by joshuahansel**

### CODE REVIEW

**Comment by joshuahansel** [comment]
@andrsd Could you review this?

**Review by andrsd — APPROVED** [review]

**Comment by permcody** [comment]
Let’s get a regression test in for this. Please don’t add or merge capability without one.

**Comment by joshuahansel** [comment]
I see that it's merged, but I'll create another PR for a test. I guess I could create a test VPP to get current, old, or older elemental values.

**Comment by joshuahansel** [comment]
Yeah, I ended up making an AuxKernel after looking around. Just finishing up.

**Comment by andrsd** [comment]
@permcody  The `getElementalValueOld` is tested. Are you talking about `getElementalValueOlder`?

**Comment by permcody** [comment]
Yes, Test what was just added.

**Pull request merged**
