### PR TITLE
BoundaryElemIntegrityCheckThread Bug Fix for Boundary Integrity Check on SideUserObject Using Lower-d Variable

### LINKED ISSUE #21566: BoundaryElemIntegrityCheckThread Bug for Boundary Integrity Check on SideUserObject using Lower-d Variable
## Bug Description

`BoundaryElemIntegrityCheckThread` errors out for a `side user object` using lower-d variable.

## Steps to Reproduce

This bug can be reproduced by defining a `side user object` using lower-d variable and the error message will be spit out something like this (even though a variable are properly defined for specified boundaries.

```
*** ERROR ***.
'avg' of type 'SideAverageValue' depends on variable(s) 'lambdab'. However, that variable does not appear to be defined on (all of) boundary 'bottom'.
```
Above error can be reproduced using the attached input: 
[test.txt](https://github.com/idaholab/moose/files/9096386/test.txt)

## Impact

A `side user object` can not be used when a variable defined on the lower-D side.

### PR DESCRIPTION
**Pull request by yjung-anl**
closes #21566

### CODE REVIEW

**Comment by YaqiWang** [comment]
@lindsayad This seems a proper small/quick fix for a bug. @yjung-anl needs this for a capability in Griffin. Please review/merge this. Thanks!

**Review by lindsayad — CHANGES_REQUESTED** [review]
Could we add a test for this to make sure we don't regress in the future?

**Comment by yjung-anl** [comment]
@lindsayad 
Test cases were added.

**Review by lindsayad — APPROVED** [review]
Failure unrelated. Thanks for the bug fix @yjung-anl !

**Pull request merged**
