### PR TITLE
Add aux kernels for outputting array material properties

### LINKED ISSUE #19639: Add aux kernels for outputting array materials
## Reason
Aux kernels that output array materials do not currently exist.

## Design
Add `VectorMaterialRealEigenVectorAux` and `MaterialRealEigenVectorAux`.

## Impact
Added capability.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #19639

### CODE REVIEW

**Review by GiudGiud — CHANGES_REQUESTED** [review]
The two docs could refer to each other since they are related 

I think we can come up with a better name. RealEigenVector is not mentioned much in the docs. 

I’ll review further later

**Comment by loganharbour** [comment]
We have `{Vector}MaterialRealVectorValueAux`. This goes with previous implementation.

I would prefer not to rename objects, but `{Vector}ArrayMaterialAux` is okay I guess.

**Comment by loganharbour** [comment]
@YaqiWang any thoughts?

**Comment by YaqiWang** [comment]
Ideally, the name should be `ArrayMaterialArrayAux` or `ArrayMaterialRealAux` or `VectorMaterialRealAux` or `VectorMaterialArrayAux`, i.e. with material property type and aux var type in it. Note that `vector` is often used for vector variables. Or we can have two ultimate aux like `MaterialPropertyRealAux` and `MaterialPropertyArrayAux` which can take any material properties.

**Comment by loganharbour** [comment]
The problem is we also need to distinguish between getting a single component (outputting to a non-array aux var) or all components (outputting to an array aux var)

**Comment by tophmatthews** [comment]
This is great! I'm hoping it'll be agnostic of the size of the array/vector? I have a similar capability in internal apps that I'd love to get rid of.

**Comment by GiudGiud** [comment]
@YaqiWang s proposal works for me
ArrayMaterialArrayAux : array mat prop to array variable
ArrayMaterialComponentAux or ArrayMaterialRealAux : array mat prop to regular variable

**Comment by loganharbour** [comment]
Do we want to rename the vector getters then too? I would assume so

**Comment by GiudGiud** [comment]
which ones?
RealVectorValue is more implementation-focused than I would like (why not just call it vector) for sure

**Pull request closed without merging**
