### PR TITLE
added dof_id_type  

### LINKED ISSUE #20467: add dof_id_type to constantReporter
## Reason
I want to pass node ids from a subapp to the main app using the reporter transfer

## Design
I'll copy the pattern used for the other types.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #20467

### CODE REVIEW

**Comment by lynnmunday** [comment]
@zachmprince   I used -1 as the dofid to show it gives the max unsigned long int of 18446744073709551615. Is that a bad test?  I wanted to show that it is unsigned long int

**Comment by lynnmunday** [comment]
@zachmprince or @loganharbour would some systems have different dof_id_types.  On my machine it is long long but I think its only a long on the Test install.

**Comment by loganharbour** [comment]
> @zachmprince or @loganharbour would some systems have different dof_id_types. On my machine it is long long but I think its only a long on the Test install.

It’s unsigned long when petsc is configured with 64 bit dof indices (our default). Otherwise, it’s unsigned. The latter is tested on the 32bit test and the petsc alt tests. All other recipes should have 64 bit dof indices (unsigned long)

**Comment by loganharbour** [comment]
You'll probably need to create a test for each option, where you limit them with the test spec `dof_id_bytes = 32` or `dof_id_bytes = 64`.

**Comment by zachmprince** [comment]
I don't think it is necessary to test that the size of the variable is good. The implementation is straightforward enough.

**Comment by loganharbour** [comment]
> I don't think it is necessary to test that the size of the variable is good. The implementation is straightforward enough.

You have to restrict it otherwise it’ll fail tests because of the variable type in the output

**Comment by zachmprince** [comment]
> You have to restrict it otherwise it’ll fail tests because the variable type in the output will diff

That's true. We can also change that type to "dof_id_type" by specializing [this function](https://github.com/idaholab/moose/blob/ee847348c22a77dd707b527a3b0fcca7b2432c19/framework/include/reporters/ReporterContext.h#L376)

**Comment by lynnmunday** [comment]
Thanks, I added the dof_id_type.  @zachmprince helped sort out the difference between bits and bytes!

**Comment by lynnmunday** [comment]
Test install is failing because it is outputting 32 bit dof_ids into the json file even though it is running the dof_id_type=8 test and skipping the dof_id_type=4 test.

**Comment by lynnmunday** [comment]
@zachmprince will you review this.  All the tests are passing and all the builds!

**Review by zachmprince — APPROVED** [review]

**Pull request merged**
