### PR TITLE
Refactoring common functionality in unit tests

### LINKED ISSUE #11401: Provide common base class for testing single MOOSE objects
## Rationale

There is a lot of duplicated code in unit tests for testing user objects. These unit tests would benefit from a common base class, so that developers can focus on testing without needing to know about the minimal underlying setup.

## Description

Provide a base class for unit testing some MOOSE object (the ones that can live stand alone).

## Impact

Easier unit test development. Reduce maintenance burden.

### PR DESCRIPTION
**Pull request by andrsd**
To test a single MOOSE object, we provide a common base class that
builds the necessary stuff. Then, the user class just builds the stuff
it needs and plug it in MOOSE and test it.

Closes #11401

### CODE REVIEW

**Review by friedmud — DISMISSED** [review]
👍

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
This is a great idea and a clean implementation.  But it could use some docs so people know to (and how to) use this unit test helper.

**Comment by andrsd** [comment]
Doco is in place...

**Review by rwcarlsen — APPROVED** [review]

**Comment by WilkAndy** [comment]
Oh yea, this is good.

By the way: big news!   I found a pub in Brisbane that had 4 old bottles of Ola Dubh stored in their fridge.  I bought one ($20) and it tasted excellent.  Yum!

a

**Comment by andrsd** [comment]
:+1: You should have bought all of them :-)

**Pull request merged**
