### PR TITLE
Speedup MooseMesh::getBoundaryName

### LINKED ISSUE #22298: Change MooseMesh::getBoundaryName
## Reason
It's really slow

## Design
Just query `_mesh_sideset_ids` data member instead of looping over the entire elem-side-bc data

## Impact
Improve user's experience. Make boundary integrity checks much faster

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #22298

### Previous

vincent

### Now

change

### CODE REVIEW

**Comment by GiudGiud** [comment]
Seems SAM is relying on this mesh triggering an update.
Should be solvable though, just needs the a prepare call or something similar?

**Comment by lindsayad** [comment]
I've got an MR into SAM [here](https://git-nse.egs.anl.gov/SAM/SAM/-/merge_requests/650)

**Review by GiudGiud — COMMENTED** [review]
why remove all the setBoundaryName code?

Is it going to error here now? (and wasnt before?)

**Comment by joshuahansel** [comment]
> why remove all the setBoundaryName code?

Same question for me.

**Comment by YaqiWang** [comment]
> > why remove all the setBoundaryName code?
> 
> Same question for me.

I guess with the code change in that function, calling it can cause errors. Maybe we should add an assertion in the function like `mooseAssertion(_moose_mesh_prepared, "")`. I think the changes in thm are good because it is unnecessary to call `setBoundaryName` which contains more codes.

**Comment by lindsayad** [comment]
`setBoundaryName` will be way faster if we use the data on `MooseMesh` ... but that data is not available until `MooseMesh::prepare` has been called. Within the era of mesh generators, users generating a mesh are using APIs from the `libMesh::MeshBase` ... I think `Components` should behave similarly.

One the mesh has been generated and `MooseMesh::prepare` has been called, then `setBoundaryName` (and `getBoundaryName`) are safe to use. In that vein I think I should error in those methods if `!_moose_mesh_prepared`

**Comment by lindsayad** [comment]
Alternatively, I could make `setBoundaryName` not use `MooseMesh` data

**Comment by GiudGiud** [comment]
> `setBoundaryName` will be way faster if we use the data on `MooseMesh` ... but that data is not available until `MooseMesh::prepare` has been called. Within the era of mesh generators, users generating a mesh are using APIs from the `libMesh::MeshBase` ... I think `Components` should behave similarly.
> 
> Once the mesh has been generated and `MooseMesh::prepare` has been called, then `setBoundaryName` (and `getBoundaryName`) are safe to use. In that vein I think I should error in those methods if `!_moose_mesh_prepared`

ok seems like the way forward, eg add an error in those routines telling the devs to use the other API as the mesh is not currently prepared. You could also just forward the call to the other API when it s not prepared

**Comment by lindsayad** [comment]
> You could also just forward the call to the other API when it s not prepared

I think this seems like a good middle ground ... e.g. things just work. And I think that if the moose mesh is not prepared we can forward to a better libMesh API than we were before

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
