### PR TITLE
Read command-line arguments from files for multiapp

### LINKED ISSUE #18596: Read command-line arguments from files for multiapp
## Reason

Assume there are one thousand sub-apps. These sub-apps will use the same input file, but each sub-app will have a few unique parameter values.  It would be convenient to read these unique parameter values from files.

## Design

Read command-line arguments from files

## Impact
New beautiful capability

### PR DESCRIPTION
**Pull request by fdkong**
Closes #18596

### CODE REVIEW

**Comment by fdkong** [comment]
Do you have time to review this PR? @lindsayad

**Review by aeslaughter — APPROVED** [review]

**Comment by aeslaughter** [comment]
Beautiful command-line args

**Comment by tophmatthews** [comment]
Pretty cool @fdkong . I'm trying to understand how each line is applied...but can't see any doco additions 😅 
Is each new cli-arg just passed to each new subapp?

**Comment by fdkong** [comment]
>Pretty cool @fdkong . I'm trying to understand how each line is applied...but can't see any doco additions 😅


It is the same as the cli-args you put into an input file.

>  Is each new cli-arg just passed to each new subapp?

We support multiple modes. It will be consistent with "positions"

**Comment by fdkong** [comment]
> but can't see any doco additions

It is straightforward for me.....

 Just let me know what you want me add to make this easy for you

**Pull request merged**
