### PR TITLE
Coloring is back on

### LINKED ISSUE #4895: Convergence colors are hosed in the Console output
Norms are always green even when they increase. The problem is that the old nonlinear and linear norms are not updated now that they are in the Console class.

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #4895)

### CODE REVIEW

**Comment by permcody** [comment]
I don't like this fix. You have member variables call `_old_nonlinear_norm` and `_old_linear_norm` which are updated as a side effect of screen output. If you turn off write to screen those variables won't get updated anymore. I suggest updating the variables regardless of whether they are output or naming them differently.

**Comment by aeslaughter** [comment]
_old_nonlinear_norm and _old_linear_norm do not mean anything to unless you are outputting to the screen, their only role is to compute the change in norm for coloring. Updating them always is not necessary and I would say wasteful, but I also don't care that much. So, if you want them updated, so be it.

**Comment by andrsd** [comment]
I think what @permcody is trying to say is:
* `outputNorm()` is being called only within `Console` class and you pass member variables into it.
* thus, `outputNorm()` does not have pass anything by reference. It should be either by const ref or by value
* and the update to `old_norm` inside `outputNorm()` should happen in `output()` on the member variable

That would be a cleaner solution IMO...

**Comment by permcody** [comment]
Only updating the variables on output can be ok, but you might want to name them more appropriately. If I'm an outside user looking at this class and I see a variable called `_old_nonlinear_norm` I might assume that it contains the old nonlinear norm. There is a case where it does not. I suggest either updating it all the time or naming it something more descriptive to indicate that it may not be always update to date: `_last_printed_nonlinear_norm`

**Pull request merged**
