### PR TITLE
Avoid expensive warehouse calls

### PR DESCRIPTION
**Pull request by loganharbour**
refs #24601

### CODE REVIEW

**Comment by loganharbour** [comment]
@lindsayad this seems to have sped up a NS problem that Sebastian profiled by a factor of 2... from ~200s to 100s. I'll have him post the profile.

**Comment by snschune** [comment]
```
Showing nodes accounting for 137.38s, 86.77% of 158.32s total
Dropped 427 nodes (cum <= 0.79s)
      flat  flat%   sum%        cum   cum%
    59.26s 37.43% 37.43%    158.32s   100%  [libresolv.9.dylib]
     7.65s  4.83% 42.26%      9.46s  5.98%  MetaPhysicL::DynamicSparseNumberBase::sparsity_union
     6.80s  4.30% 46.56%     10.85s  6.85%  std::__1::__hash_table::find
        5s  3.16% 49.72%     10.59s  6.69%  MetaPhysicL::derivative_multiply_helper
     4.91s  3.10% 52.82%      4.96s  3.13%  MetaPhysicL::DynamicStdArrayWrapper::resize
     4.58s  2.89% 55.71%      5.46s  3.45%  [libtcmalloc_and_profiler.4.dylib]
     3.81s  2.41% 58.12%     20.80s 13.14%  CNSFVHLLCBase::waveSpeed
     3.45s  2.18% 60.30%     62.83s 39.69%  MooseVariableDataFV::computeAD
     2.92s  1.84% 62.14%     21.53s 13.60%  TheWarehouse::queryInto
     2.89s  1.83% 63.97%      4.86s  3.07%  MetaPhysicL::derivative_division_helper
     2.77s  1.75% 65.72%     10.04s  6.34%  ConservedVarValuesMaterial::computeQpProperties
     2.36s  1.49% 67.21%      4.37s  2.76%  Assembly::prepareNeighbor
     1.89s  1.19% 68.40%      1.89s  1.19%  MooseObject::enabled
     1.83s  1.16% 69.56%      2.94s  1.86%  libMesh::DofMap::_dof_indices
     1.46s  0.92% 70.48%      2.38s  1.50%  Assembly::prepareJacobianBlock
     1.31s  0.83% 71.30%      2.87s  1.81%  MooseVariableFV::dofIndices
     1.27s   0.8% 72.11%      5.07s  3.20%  libMesh::TypeVector::operator*
     1.19s  0.75% 72.86%      1.38s  0.87%  MooseVariableDataFV::initializeSolnVars
     1.10s  0.69% 73.55%      2.77s  1.75%  (anonymous namespace)::mz_size
     1.06s  0.67% 74.22%      1.06s  0.67%  TCMallocImplementation::GetAllocatedSize
     1.01s  0.64% 74.86%      1.77s  1.12%  MooseVariableFV::dofIndicesNeighbor
        1s  0.63% 75.49%      1.02s  0.64%  TCMallocImplementation::GetOwnership
     0.93s  0.59% 76.08%     29.51s 18.64%  CNSFVHLLC::computeQpResidual
     0.92s  0.58% 76.66%      4.13s  2.61%  libMesh::DofMap::dof_indices
     0.90s  0.57% 77.23%      1.80s  1.14%  AttribSystem::isMatch
     0.86s  0.54% 77.77%     42.20s 26.65%  TheWarehouse::QueryCache::queryIntoHelper
```

to

```
Showing nodes accounting for 96.09s, 87.75% of 109.51s total
Dropped 392 nodes (cum <= 0.55s)
      flat  flat%   sum%        cum   cum%
    15.08s 13.77% 13.77%     15.58s 14.23%  [libsystem_kernel.dylib]
    10.80s  9.86% 23.63%     11.57s 10.57%  [libsystem_platform.dylib]
     7.37s  6.73% 30.36%      8.96s  8.18%  MetaPhysicL::DynamicSparseNumberBase::sparsity_union
     6.87s  6.27% 36.64%      7.60s  6.94%  [libc++abi.dylib]
     5.21s  4.76% 41.39%     10.82s  9.88%  MetaPhysicL::derivative_multiply_helper
     4.39s  4.01% 45.40%      4.41s  4.03%  MetaPhysicL::DynamicStdArrayWrapper::resize
     3.77s  3.44% 48.84%     20.85s 19.04%  CNSFVHLLCBase::waveSpeed
     2.82s  2.58% 51.42%      4.48s  4.09%  MetaPhysicL::derivative_division_helper
     2.72s  2.48% 53.90%      9.04s  8.25%  ConservedVarValuesMaterial::computeQpProperties
     2.37s  2.16% 56.07%      2.81s  2.57%  [libsystem_pthread.dylib]
     2.28s  2.08% 58.15%      4.34s  3.96%  Assembly::prepareNeighbor
     1.94s  1.77% 59.92%     17.41s 15.90%  MooseVariableDataFV::computeAD
     1.89s  1.73% 61.65%      3.04s  2.78%  libMesh::DofMap::_dof_indices
     1.70s  1.55% 63.20%     10.18s  9.30%  TheWarehouse::queryInto
     1.64s  1.50% 64.70%      3.22s  2.94%  MooseVariableFV::dofIndices
     1.34s  1.22% 65.92%      2.37s  2.16%  Assembly::prepareJacobianBlock
     1.24s  1.13% 67.05%      1.36s  1.24%  MooseVariableDataFV::initializeSolnVars
     1.24s  1.13% 68.19%      2.69s  2.46%  [libsystem_malloc.dylib]
     1.04s  0.95% 69.14%      1.76s  1.61%  MooseVariableFV::dofIndicesNeighbor
     1.01s  0.92% 70.06%     29.28s 26.74%  CNSFVHLLC::computeQpResidual
     0.92s  0.84% 70.90%      4.80s  4.38%  libMesh::TypeVector::operator*
     0.87s  0.79% 71.69%      3.94s  3.60%  libMesh::DofMap::dof_indices
     0.81s  0.74% 72.43%      2.76s  2.52%  Assembly::cacheResidualBlock
     0.76s  0.69% 73.13%      1.88s  1.72%  MooseVariableDataBase::fetchDoFValues
     0.72s  0.66% 73.78%      1.28s  1.17%  [libtcmalloc_and_profiler.4.dylib]
     0.71s  0.65% 74.43%      0.72s  0.66%  Assembly::processLocalResidual
```

**Review by lindsayad — APPROVED** [review]
Yea we don't hit this code for incompressible/weakly-compressible FV so probably why we have not optimized this code-path before. Thanks for the improvement!

**Comment by lindsayad** [comment]
This made me feel a little better
```
(base) lindad@inl610212:~/projects/moose/framework/src/variables(next)$ git blame -L500,530 MooseVariableDataFV.C
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 500) {
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 501)   // This query and if check prevent running this code when we have FV
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 502)   // variables, but no kernels.  When this happens, maxVarNDofsPerElem is
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 503)   // not computed (because no kernels) and is zero giving nonsense offsets for
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 504)   // AD stuff.  So we just skip all this when that is the case.  Maybe there
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 505)   // is a better way to do this - like just checking if getMaxVarNDofsPerElem
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 506)   // returns zero?
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 507)   std::vector<FVKernel *> ks1;
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 508)   std::vector<FVKernel *> ks2;
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 509)   _subproblem.getMooseApp()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 510)       .theWarehouse()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 511)       .query()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 512)       .template condition<AttribSystem>("FVElementalKernel")
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 513)       .queryInto(ks1);
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 514)   _subproblem.getMooseApp()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 515)       .theWarehouse()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 516)       .query()
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 517)       .template condition<AttribSystem>("FVFluxKernel")
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 518)       .queryInto(ks2);
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 519)   if (ks1.size() == 0 && ks2.size() == 0)
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 520)     return;
8aa10e49e98 (Robert Carlsen 2020-04-20 09:44:36 -0600 521) 
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 522)   _ad_dof_values.resize(num_dofs);
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 523)   if (_need_ad_u)
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 524)     _ad_u.resize(nqp);
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 525) 
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 526)   if (_need_ad_grad_u)
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 527)     _ad_grad_u.resize(nqp);
b474d9301d7 (Robert Carlsen 2020-04-07 11:43:32 -0600 528) 
2a3b426396a (Alex Lindsay   2020-05-01 11:31:31 -0700 529)   if (_need_ad_second_u)
2a3b426396a (Alex Lindsay   2020-05-01 11:31:31 -0700 530)     _ad_second_u.resize(nqp);
```

**Comment by GiudGiud** [comment]
Still quite a bit of computational time concentrated in a few routines, and a lot pointing to AD. Would be nice to try the segregated solver there too
waveSpeed performance will depend on the fluid properties you are using quite a bit. What are you using?

**Comment by lindsayad** [comment]
After https://github.com/idaholab/moose/pull/24617 the cost of AD on the same problem is reduced by greater than 10x

**Pull request merged**
