### PR TITLE
Add a virtual function to check the Picard convergence

### LINKED ISSUE #10518: Need a virtual function in Transient to check the convergence of Picard iteration
## Rationale
We have a derived executioner from `Transient`, which needs to check the convergence of Picard iteration slightly differently. Make the check as a virtual function in `Transient` will allow this executioner to add more logic in the function.

## Description
Make derived executioners able to override the Picard iteration convergence check.

## Impact
New capability.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #10518.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Any comments?

**Review by permcody — COMMENTED** [review]
This looks fine to me. I'm going to assign to @friedmud though to make sure this isn't short-sighted in any way. We have to be diligent about extending the interface of any Executioner.

**Comment by YaqiWang** [comment]
I thought hard and concluded that I have to extend the interface unfortunately to have the desired capability. I am basically checking the convergence on a scalar value which is directly related with the method in the derived class. We can let `Transient` check convergence of a postprocessor with something `picard_check_pp` and `picard_pp_tol` and I then convert that scalar value into a postprocessor. But that will require more changes and I am not sure if it is worthwhile.

**Comment by YaqiWang** [comment]
Is the decision so hard to make? I am waiting on this...

**Comment by permcody** [comment]
@friedmud - Please get to this at your earliest convenience. Thanks!

**Review by friedmud — APPROVED** [review]
Looks fine.  Should probably move this function to `Problem` eventually like the other convergence checks

**Pull request merged**
