### PR TITLE
Tests involving DiracKernels with off-diagonal Jacobians

### LINKED ISSUE #5314: richards: offdiag dirac test
I think i can add this test to the suite now:

dirac.bh27............................... skipped (Needs DiracKernel::computeOffDiagQpJacobian - ticket #668)

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #5314 .

### CODE REVIEW

**Comment by jwpeterson** [comment]
So it looks like this works, but @permcody thinks we should be able to support this better at the framework level, possibly by inherting from the beautifully-named `NeighborCoupleableMooseVariableDependencyIntermediateInterface.h`

**Comment by WilkAndy** [comment]
So do you want me to change the code?  If so, how?

a

**Comment by permcody** [comment]
We don't want you to change the code just yet. One of us needs to look at this and see if we can get the coupling correct automagically. If you don't need this right away we should be able to get to this later this week or sometime next week.

**Comment by WilkAndy** [comment]
I don't think i need this until next week.

a

**Comment by permcody** [comment]
I looked a little more at your PR and understand what you are doing now. It appears that we aren't missing some variable dependency interface in MOOSE. It's just that you are doing something slightly unusual here (telling the Dirac system about the coupled variables in a dependent UserObject). I'm not sure that I want to hack anything into the framework to make this work automatically since it is non-trivial although this is a valid problem...

@friedmud what do you think?

**Comment by friedmud** [comment]
What he's doing now is the right way to handle it.

I've been thinking that we could make this a bit easier with a function on `MooseVariableDependencyInterface` that is like `MooseVariableDependencyInterface::addDependencies(MooseVariableDependencyInterface &)`... to make it easy to add the dependencies for another object to be dependencies of this object (essentially, take this loop that he's doing here and move it down).

**Comment by permcody** [comment]
OK - at least they don't have to duplicate code that way. That's a reasonable way to move forward. I'll merge this PR and open a ticket to create that interface method.

**Pull request merged**
