### PR TITLE
fix script now only renames macros with << operator

### PR DESCRIPTION
**Pull request by rwcarlsen**
Thanks @dschwen for your brilliant mind and your willingness to share your sage wisdom! (i.e. good idea).

### CODE REVIEW

**Comment by permcody** [comment]
Are we planning to revert your original commit and replace it with the renames resulting from this script?

**Comment by rwcarlsen** [comment]
Don't know how feasible that is for the framework - there might be considerable conflicts by now.  But there is more hope for BISON.

**Comment by rwcarlsen** [comment]
Git blame doesn't return ownership of lines after a revert - so no point changing already done renames.

**Comment by dschwen** [comment]
Do I detect a hint of sarcasm here?

**Comment by dschwen** [comment]
> Git blame doesn't return ownership of lines after a revert

Yes it absolutely does!

**Review by permcody — APPROVED** [review]

**Pull request merged**
