### PR TITLE
Adds geometry postprocessor tests 

### LINKED ISSUE #15542: Add tests showing AreaPostprocessor and VolumePostprocessor behavior in 2D and 3D
## Reason
Having an easy test that shows how `AreaPostprocessor` and `VolumePostprocessor` would help clear up inconsistancies

## Design
Add tests with meshes

## Impact
Adds double check to geometry postprocessors.

### PR DESCRIPTION
**Pull request by tophmatthews**
This provides a couple tests for `AreaPostprocessor` and `VolumePostprocessor` in 2D and 3D. In 3D, `AreaPostprocessor` should return the area of a sideset, and `VolumePostprocessor` should return the volume of a block.  In 2D, `AreaPostprocessor` should return the perimeter of a sideset, and `VolumePostprocessor` should return the area of a block.

There are two complications that result in non-exact solutions. The first is changes in geometry due to polygonization, and goes:
For perimeter calculations ->`R_eff = R * alpha / 2 / (sin(alpha / 2))`
For area calculations -> `R_eff = R * sqrt(alpha / sin(alpha))`
where `alpha = 2 * pi / num_sides`
(credit to @vincentlaboure for clarifying these).
Okay easy enough!

The next problem comes with the 2D perimeter calculation: If a sideset is shared by two surfaces, the perimeter calculation in `AreaPostprocessor` is double that of the exact value. 

Included are journal files for the 3D and 2D meshes, and input files for 3D and 2D.

`3D_geometry.i` using the mesh from `3d_mesh.jou` works great, and matches exactly.

The `2D_geometry.i` using the mesh from `2d_mesh.jou` works great once a x2 factor is applied to the all "shared" sidesets (see `2d_correction = 2` in the input file).

I'm not sure how to handle this x2. f I messed up the mesh, if this is a bigger issue, or if it's an expected behavior. This feels like a _very_ easy gotcha to miss.

closes #15542

### CODE REVIEW

**Comment by tophmatthews** [comment]
The geometry looks like:
image

**Comment by tophmatthews** [comment]
ping @vincentlaboure @harterj

**Comment by vincentlaboure** [comment]
One way to determine if the problem comes from MOOSE or Cubit would be to create a cylinder with a mesh generator and see if the `AreaPostprocessor`s are correct. I think the problem comes from Cubit since @harterj was able to generate a mesh full of circles (with Cubit) that was reporting a correct value for `AreaPostprocessor`.

**Comment by tophmatthews** [comment]
> One way to determine if the problem comes from MOOSE or Cubit would be to create a cylinder with a mesh generator and see if the `AreaPostprocessor`s are correct. I think the problem comes from Cubit since @harterj was able to generate a mesh full of circles (with Cubit) that was reporting a correct value for `AreaPostprocessor`.

I started down that path, but it was a pain to make sidesets...I'll try it again...

**Comment by tophmatthews** [comment]
> but it was a pain to make sidesets

AGGGG it's such a pain to make sidesets on anything but straight lines in MESHGENERATORS!

**Comment by tophmatthews** [comment]
Okay @YaqiWang is on to something, in paraview there is 2x the number of expected cells:
image

**Comment by tophmatthews** [comment]
Cubit has 16....
image

**Comment by YaqiWang** [comment]
This is hard for the code to detect. I wish users can get a meaningful error or warning in such a case.

**Comment by tophmatthews** [comment]
Well I can't even figure out how this occurs? It's somewhere in the cubit exporting...I think?! It would almost be easy to check with a number of cells = number of points?

**Comment by tophmatthews** [comment]
Wait scratch that...it's in the sideset generation still...
image

**Comment by tophmatthews** [comment]
Found it! `sideset 10 add curve 1 wrt surface 1 `

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
