### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ffarha**
adding stand-in numerical sensors

## Reason

This feature will enable the users to realistically model sensors in a system.

## Design

GeneralSensorPostprocessor added. Adds drift, delay, noise, efficiency to the sensor to show realistic outputs.

## Impact

add something new

### CODE REVIEW

**Comment by lindsayad** [comment]
Hi @ffarha you will need to close this pull request and open a new one against the `next` branch instead of the `master` branch. You should make sure you're rebased onto `next` or `devel` before you make the new PR and remove the merge commit

**Comment by GiudGiud** [comment]
I would do this:
```
git checkout origin/next
git cherry-pick 467fec0
git cherry-pick c50daa6
git push <name of your remote> HEAD:master
```

**Comment by ffarha** [comment]
I added the new PR.

**Comment by GiudGiud** [comment]
Closing this PR as duplicate of #26870

**Pull request closed without merging**
