### PR TITLE
Fixing phase field tests in parallel

### PR DESCRIPTION
**Pull request by dschwen**
Fix a few more phase field tests in parallel. 

Refs #2975

### CODE REVIEW

**Comment by permcody** [comment]
Do you have a marmot patch ready?

**Review by permcody — DISMISSED** [review]

**Comment by dschwen** [comment]
> Do you have a marmot patch ready?

Ugh, I guess I'll do that now...

**Comment by permcody** [comment]
I'm also attaching the module parallel targets to this PR just so you can see your progress before we merge.

**Comment by dschwen** [comment]
Ok, I have the marmot changes ready.

**Comment by dschwen** [comment]
Cool, just two tests left

**Comment by dschwen** [comment]
I think I can fix the last tests as well. Working on SQA now. Let's hold this for now.

**Comment by dschwen** [comment]
Phase Field Parallel is all green now 🍾 🎉

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
This is merged, let me know when marmot patch is up.

**Pull request merged**
