### PR TITLE
JOSS paper.md, paper.bib, README.md and LICENSE added.  Fixes #14719

### LINKED ISSUE #14719: PorousFlow: Journal of Open Source Software additions
## Reason

PorousFlow has been used in quite a few studies, and yet we haven't published a paper that people can cite.  @cpgr and I feel that the [Journal of Open Source Software](https://joss.theoj.org/) is a good fit.  This journal likes the paper to be part of the repository, so we intend to add it to the porous_flow module.  There are other things we need to add, such as build instructions, etc.  We intend to follow a similar style to [Moltres](https://github.com/arfc/moltres) which is also [published](https://joss.theoj.org/papers/10.21105/joss.00298) in the same journal.

Perhaps the only sticking point for publication will be that PorousFlow is part of MOOSE, so the journal might question authorship - we'll have to see, but the moose-devs might have to vouch for us.

## Design

At the least, we have to add a `paper.md` and `paper.bib`, but i'm sure there are other files we need to add.

## Impact

People can cite our work!

### PR DESCRIPTION
**Pull request by WilkAndy**

### CODE REVIEW

**Comment by WilkAndy** [comment]
How about this PR @permcody

**Comment by permcody** [comment]
Sorry - I've been busy and I saw license stuff in this PR which I wanted to
make sure we get right. I'll discuss this with my team and will let you
know if we need changes before this can go in.

**Comment by WilkAndy** [comment]
Cool, you guys are awesome,

a

**Comment by permcody** [comment]
Andy, We don't believe a separate copy of the license at the porous flow level is necessary. The LGPL license at the top level should be sufficient and covers you for all use that you should require. Can we drop that? Everything else here looks fine.

**Comment by WilkAndy** [comment]
I included it just to ease the JOSS review.  Reviewers have a checklist, and one of them is "does a LICENSE file exist".  I think what i'll do is keep the file, but its contents will just be a plaintext explanation that the MOOSE LICENSE file that is two directories up.   Is that OK?

**Comment by permcody** [comment]
Yeah, or you could put in a soft link.

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for discussing this and helping, @permcody and team

**Pull request merged**
