### PR TITLE
Add user-requested partitioners to MeshGenerators

### LINKED ISSUE #16776: Add [Partitioner] capability with MeshGenerators
## Reason
Currently, the [Partitioner] block has no effect with MeshGenerators.

## Design
Get it working?

## Impact
Expanded capability.

### PR DESCRIPTION
**Pull request by lindsayad**
Previously user-requested partitioners would go completely ignored by
`MeshGenerators`, e.g. any simulation that used `MeshGenerators` to
construct its mesh probably wasn't getting the partition it wanted. We
solve this by moving the `add_partitioner` task earlier and attaching
the partitioner every time we use the `MooseMesh` to build a `MeshBase`
object.

Closes #16776

### CODE REVIEW

**Comment by lindsayad** [comment]
@loganharbour do you have a test already sitting in your brain that you can add? If not, I will think of one

**Comment by loganharbour** [comment]
The partitioner tests that currently use `GeneratedMesh` should be able to be switched to a `GeneratedMeshGenerator` if this works

**Comment by lindsayad** [comment]
Cool. I'll try that out

**Comment by loganharbour** [comment]
@lindsayad I'll see if I can add some tests to this as it's a priority for me

**Comment by lindsayad** [comment]
Ok I grepped for MOOSE tests that ask for `partitioner = `, and I converted those to use `MeshGenerators` so we should be getting coverage in MOOSE test now

**Comment by lindsayad** [comment]
Oh yea beautiful pass

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
