### PR TITLE
Modify bootstrap at libMesh level for macOS ARM64

### LINKED ISSUE #25456: Fix libMesh bootstrap applying a re-patch
## Reason
With latest `moose-dev` or rather, with updated Autotools (automake 1.16.5), we seem to run into a snag while attempting to build libMesh using our `update_and_rebuild_libmesh.sh`.

## Design
Remove the needed bootstrapping portion that is applying a patch.

```pre
Reversed (or previously applied) patch detected!  Assume -R? [y] n
Apply anyway? [n]
```

## Impact
No halts during the use of `update_and_rebuild_libmesh.sh`

### PR DESCRIPTION
**Pull request by cticenhour**
With newer autotools, the bootstrap script at the libMesh level is not technically required and duplicative work (the patch mentioned in the issue) was being performed. A simple autoreconf is all that is required at that level.

Closes #25456

CC: @milljm @roystgnr

### CODE REVIEW

**Review by roystgnr — DISMISSED** [review]
I can't swear to the conda changes but this should be the right thing to do in the configure script.

**Comment by cticenhour** [comment]
Still getting

```
Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
```

On `conda-build` when I am not getting that failure locally with this change....more tinkering required.

**Comment by cticenhour** [comment]
@loganharbour any manual builds required here?

**Comment by loganharbour** [comment]
> @loganharbour any manual builds required here on your end? 


All of the libmesh builds will need to take place. If you're done, I'll start building them in a little bit.

**Comment by cticenhour** [comment]
Should be good to go when you have time. Failures I see seem to be un-related.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
