### PR TITLE
Prepare mesh when needed in SidesetsBetweenSubdomainsGenerator

### LINKED ISSUE #21861: SideSetsBetweenSubdomainsGenerator should prepare_for_use()
## Bug Description

I am creating a mesh and need to use `SideSetsBetweenSubdomainsGenerator`. Unfortunately, as pointed out by @miaoyinb, many of the generators I am using beforehand do not prepare the mesh for use.

The best way to resolve this (suggested by @miaoyinb) would be to add `mesh->prepare_for_use();` at the beginning of `SideSetsBetweenSubdomainsGenerator::generate()`

## Steps to Reproduce

An input with `FancyExtruderGenerator` followed by `SideSetsBetweenSubdomainsGenerator` should be able to reproduce this behavior.

## Impact

I can't assign the sidesets I need.

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #21861

### CODE REVIEW

**Comment by miaoyinb** [comment]
`SidesetsBetweenSubdomainsGenerator` does not work without a prepared mesh. I guess this is a quick one.

@GiudGiud

**Comment by roystgnr** [comment]
> does not work without a prepared mesh.

Is this entirely accurate?  It needs parallel id counts to be updated, and it needs neighbor pointers and interior_parent pointers to be correct, and it needs any orphaned nodes removed, and it needs mesh dimensions to be up to date, and it needs to be repartitioned for load balancing and renumbered for contiguity, and it needs any no-longer-necessary ghost elements to be deleted?

If the answer is "yes, yes and yes, yes, yes, yes and yes, and yes", then this is a great patch.  If we can get that down to one or two out of eight yeses, though, then it would be better to just update what little needs updating (call just `find_neighbors()` and/or `update_parallel_id_counts()`, maybe) but skip most of the rest of the expensive stuff.  Even if the answer was as expansive as "yes, yes and yes, yes, yes, no and no, no", there are things we could do like temporarily disabling repartitioning/renumbering to reduce the expense.

Let me look at SidesetsBetweenSubdomainsGenerator myself and see if the requirements are obvious or subtle.

**Comment by roystgnr** [comment]
> Let me look at SidesetsBetweenSubdomainsGenerator myself 

I can see why it's tempting to just do a full prepare and not dig into this.  That is some old code, huh?  It's still using manual non-blocking-send-to-every-processor rather than the new push/pull APIs, even.

**Comment by roystgnr** [comment]
Could you see if calling just `find_neighbors()` instead of `prepare_for_use()` is adequate here?  I might be missing something else, but that's the one requirement that jumps out at me.

**Comment by miaoyinb** [comment]
> Could you see if calling just `find_neighbors()` instead of `prepare_for_use()` is adequate here? I might be missing something else, but that's the one requirement that jumps out at me.

Thanks @roystgnr. I think just `find_neighbors()` works. But `prepare_for_use()` has `is_prepared()`, while `find_neighbors()` does not have something similar. Should I use `is_prepared()` with `find_neighbors()`, or just do `find_neighbors()` anyway without checking?

**Comment by miaoyinb** [comment]
> > I think just find_neighbors() works.
> 
> Wonderful!
> 
> > prepare_for_use() has is_prepared(), while find_neighbors() does not have something similar
> 
> I'm afraid it doesn't, you're right. And even after we add a more fine-grained breakdown at the libMesh level, it'll take a while before it's being used reliably at the MOOSE level; this is a long-term solution not an immediate fix.
> 
> > Should I use is_prepared() with find_neighbors()
> 
> Definitely. `is_prepared() => neighbors_found()` (or whatever we name it eventually), so testing `!is_prepared()` will sometimes have you running `find_neighbors()` redundantly, but at least it won't be as much redundant work.
> 
> > or just do find_neighbors() anyway without checking?
> 
> No, I'm afraid it's too expensive for that.

Will do, thanks.

**Review by roystgnr — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
