### PR TITLE
Add a getter for a writeable reference to Transient::_num_steps

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by friedmud** [comment]
This isn't really a great idea... especially not to give a writeable reference out like that.  There could be decisions that are made inside Transient based on num_steps that won't get updated/modified with a writeable reference (for instance, sync times and stopping times).

Why do you want to do this?  A there are other ways to stop a simulation early: https://github.com/idaholab/moose/blob/5270d0cda43a579339ef4f82b84d19dc32b412ab/framework/src/userobject/Terminator.C

**Comment by snschune** [comment]
I have a TimeStepper that mimics the behavior of the Depletion executioner. 
It takes in a vector of time points and the length gives the number of timesteps - 1.

**Comment by permcody** [comment]
I don't like exposing writable references to important members like this
either. I'd entertain adding an accessor (setNumSteps()) or something
similar where we could do checking inside of the class to avoid bugs such
as the ones Derek is pointing out.

**Comment by snschune** [comment]
So maybe changing num_steps isn't such a good idea. 

What do you think of having another condition in ```Transient::keepGoing``` 
based on a callback to a ```Timestepper::keepGoing``` function. Something like:

```
if (!time_stepper->keepGoing())
  keep_going = false;
```

**Comment by permcody** [comment]
Hmm, Well that might work but then the user might be confused when they run
a simulation with 5 steps and end up getting 500.

I'm not fully against changing num_steps as long as it's done in the class
and not externally through a writable reference. I guess in either case
it'll be important to output information on the console about what your
timestepper is doing. I know that the iterative adaptive timestepper is
quite verbose.

**Comment by andrsd** [comment]
> I have a TimeStepper that mimics the behavior of the Depletion executioner.

If you know the time points, you know dt for each step. Then use `end_time` to stop the simulation. 'num_steps' and 'end_time' can be used mutual-exclusively (:smile:).

**Comment by snschune** [comment]
@andrsd That works thanks. I don't need to mess with num_steps.

**Pull request closed without merging**
