### PR TITLE
Exploring more robust version of MooseDocs

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
This is getting real close, I still need to the following.

- [ ] We need to write new content for the front page and include the R&D100 image again.
- [ ] The !buildstatus markdown syntax (i.e., BuildStatus.py) needs to be cleaned up to use the new Civet API (@brianmoose can you help with this?)
- [ ] The carousel needs to be update to work better for Materialize version (@brianmoose can you help with this?)
- [ ] The side navigation needs some love (@schwen could you look into improving it)

**Comment by aeslaughter** [comment]
@brianmoose The build step completed with errors, but I still think that a site was actually created. Could you let me know if there is anything in the "site" directory, is the 'index.html' just missing? I am not sure why this didn't work.

**Comment by brianmoose** [comment]
Looks like a lot got generated under `framework`, `modules`, and others. No `site/index.html` though which is what we check for.

**Comment by aeslaughter** [comment]
@brianmoose @dschwen This site is now displaying correctly.

@permcody If we get this merged you will have a nicer experience with the documentation system then you will have now.

**Comment by dschwen** [comment]
Looks awesome! But for some reason the side menu is really slow/laggy on my laptop. That can be fixed that later though.

**Comment by permcody** [comment]
Are we still loading the whole world into the menu? That's probably why
it's slow. That's really not a great idea.

**Comment by aeslaughter** [comment]
The menu is complete, if someone want to figure out how to make it dynamic
then great, that is far beyond my skills. It is not slow on my system.

**Comment by permcody** [comment]
It may not be slow on your system but you are using a high power
workstation. What will it look like on some of those old machines that
people bring to training? Will it get worse as we continue to expand the
documentation? It should be possible to use asynchronous communication to
populate menus dynamically.

**Comment by dschwen** [comment]
My guess is that asynchronous communication is not really necessary here (the full menu structure data is probably not nearly as heavy as the big image in the background). This would only help the initial load time anyways. My guess is (and I can do profiling on this) that building the full underlying DOM structure is what kills performance. It would be better to append and delete HTML elements when necessary (i.e. when a submenu level is opened).

**Comment by permcody** [comment]
You're probably right... Well that's worth investing time in.

**Comment by aeslaughter** [comment]
I would like to get this merged for @permcody and @rwcarlsen to start using for writing documentation, we can further improve the menu later.

**Review by permcody — APPROVED** [review]

**Pull request merged**
