### PR TITLE
Fix a bug in building eigen variable indices

### LINKED ISSUE #7211: A bug in Eigensystem::buildSystemDoFIndices()
### Description of the enhancement or error report
The line `sys().local_dof_indices(i, _eigen_var_indices)` is assuming that the dof index set is accumulating, i.e. `_eigen_var_indices` is not cleared by `local_dof_indices` before its action, which is not true. MOOSE test is not detecting this bug because the number of eigen variables in those tests is one.

### Rationale for the enhancement or information for reproducing the error
We found this bug in one of our calculations. It took me quite a while to figure this out.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact because no test is covering this.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #7211.

### CODE REVIEW

**Comment by YaqiWang** [comment]
A patch in Yak will be needed although the exodiff is tiny.

**Comment by YaqiWang** [comment]
@permcody Yak patch is ready for merging this.

**Comment by permcody** [comment]
👍

**Comment by permcody** [comment]
This is merged - please post your MR for yak and I will merge.

**Comment by YaqiWang** [comment]
Yak patch is under testing currently. @permcody

**Pull request merged**
