### PR TITLE
Added ADComputeMeanThermalExpansionPolynomialEigenstrain

### LINKED ISSUE #18308: Add derivative information to AD thermal expansion materials
## Reason
Often mean thermal expansion coefficients are only dependent on temperature. These coefficients are defined and passed around as Functions with temperature passed in to the `t` (time) parameter. The method `timeDerivative` in functions can optionally be defined to give the derivative of the function, and provide derivative information to the AD methods.

## Design
Add `timeDerivative` to compute thermal expansion coefficient derivatives.

## Impact
Better usability.

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #18308

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
I don't know what the longest class name in MOOSE is, but this has got to be up there.

**Comment by dschwen** [comment]
```
ADComputeMeanThermalExpansionPolynomialEigenstrain
NeighborCoupleableMooseVariableDependencyIntermediateInterface
```

**Comment by dschwen** [comment]
Just to understand the motivation a bit better, you need an AD capable class that can handle a polynomial function? Is that why you are not simply using a MooseFunction (e.g. ParsedFunction) class? I'd much rather see this in conjunction with a `PolynomialFunction` class, to keep things modular.

Yes, I know, the Function system does not directly support dual numbers, but you could always inject the evaluation of the ``Function::timeDerivative(...)` and `Function::gradient(...)` methods. We've done that before.

**Comment by dschwen** [comment]
in fact

https://github.com/idaholab/moose/blob/0a66a2da952806af56222ecd483faaa7709c3575/modules/tensor_mechanics/src/materials/ADComputeMeanThermalExpansionFunctionEigenstrain.C#L50

should just be changed to

```
  ADReal alpha = _thermal_expansion_function.value(MetaPhysicL::raw_value(temperature), Point());
  alpha.derivatives() = _thermal_expansion_function.timeDerivative(MetaPhysicL::raw_value(temperature), Point()) *
    temperature.derivatives();
  return alpha;
```

**Comment by tophmatthews** [comment]
Lots facts...

**Comment by tophmatthews** [comment]
Yes, that should work just fine, and I agree modular would be better. Are you sure that fills out the appropriate AD derivatives with just `.timeDerivative`? That is just a number, no? `alpha.derivatives` is the jacobian pieces, more than just temperature, no?

**Comment by tophmatthews** [comment]
Using variables as the `time` in functions seems so hacky still...

**Comment by dschwen** [comment]
yeah, `timeDerivative` would do it, assuming we fill in T for t... And that's what we're doing else where in MOSOE already. It seems odd to add a completely new class to implement a specific type of function where we already have a modular function system. And we're adding only an AD version of that class while leaving an equivalent (AD/non-AD) class broken instead of fixing it.

**Comment by tophmatthews** [comment]
Well, the non-AD class isn't required since it doesn't need the ADReal. The right way to do that is to combine them all into joined nonAD/AD classes, but that's neither here nor there. timeDerivative should work great.

**Pull request closed without merging**
