### PR TITLE
Add MaterialCoupledForce

### LINKED ISSUE #14665: A generalization to CoupledForce
## Reason

The need for coupling expressions like `m1 * v1 + m2 * v2` where `m<>` are material props and `v<>` are variables often comes up.

## Design

Either `CoupledForce` will be generalized or a derived class `MaterialCoupledForce`
is created. 

## Impact

Current tests won't need changes. API will be more general but still accept old inputs.

### PR DESCRIPTION
**Pull request by snschune**
closes #14665 

The changes to `CoupledForce` would be too significant and the class would 
be harder to understand. Therefore, `MaterialCoupledForce` was added instead.

### CODE REVIEW

**Comment by snschune** [comment]
@jortensi once this is merged, it'd make your life easier.

**Comment by dschwen** [comment]
MatDiffusion, MatConvection, MatDivergenceBC, MatCoefDiffusion, MatReaction... there is apattern here...

**Comment by snschune** [comment]
> MatDiffusion, MatConvection, MatDivergenceBC, MatCoefDiffusion, MatReaction... there is apattern here...

People being too lazy to write `Material<>`?

**Comment by dschwen** [comment]
If you want to be really correct all this classes should start with MaterialProperty

**Comment by snschune** [comment]
@permcody @milljm  this shows up as tests are not complete but they are.

**Comment by permcody** [comment]
Odd - must have been a network hiccup.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Testing is complete.

**Comment by permcody** [comment]
@snschune - Looks like this requires a mammoth patch.

**Pull request merged**
