### PR TITLE
Change Json namespace to moosecontrib::Json to avoid symbol conflicts

### LINKED ISSUE #8590: JSONCPP Duplicate Symbol Conflict in CASL VERA Builds
### Description of the enhancement or error report
CASL VERA continuously integrates both MOOSE and SCALE. The recent addition of JSONCPP has caused duplicate symbol link errors. Proposed enhancement : scope the JSONCPP usage with an unambiguous namespace. 

### Rationale for the enhancement or information for reproducing the error
Facilitate CI with VERA and SCALE code systems.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted) TBD

`[100%] Linking CXX executable tiamat
[100%] Linking CXX executable tiamatInline
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Writer::~Writer()':
jsoncpp.C:(.text+0x10): multiple definition of `Json::Writer::~Writer()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_writer.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_writer.cpp:200: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Writer::~Writer()':
jsoncpp.C:(.text+0x10): multiple definition of `Json::Writer::~Writer()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_writer.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_writer.cpp:200: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Writer::~Writer()':
jsoncpp.C:(.text+0x40): multiple definition of `Json::Writer::~Writer()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_writer.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_writer.cpp:200: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Features::Features()':
jsoncpp.C:(.text+0x620): multiple definition of `Json::Features::Features()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_reader.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_reader.cpp:31: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Features::Features()':
jsoncpp.C:(.text+0x620): multiple definition of `Json::Features::Features()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_reader.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_reader.cpp:31: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Features::all()':
jsoncpp.C:(.text+0x630): multiple definition of `Json::Features::all()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_reader.cpp.o):/projects/vera/VERA_builds/VERA/SCALE/packages/Standard/Json/jsoncpp/json_reader.cpp:40: first defined here
../../../../MOOSEExt/MOOSE/moose/framework/libmoose-opt.a(jsoncpp.x86_64-unknown-linux-gnu.opt.o): In function `Json::Features::strictMode()':
jsoncpp.C:(.text+0x640): multiple definition of `Json::Features::strictMode()'
../../../../SCALE/packages/Standard/Json/libStandard_Json.a(json_reader.cpp.o):/pro
....`

### PR DESCRIPTION
**Pull request by brianmoose**
closes #8590

### CODE REVIEW

**Comment by rwcarlsen** [comment]
I would rather see us moving toward standardizing on putting all moose stuff in a ``moose`` namespace - like:

```c++
namespace moose
{
namespace Json
{
...
```

**Comment by brianmoose** [comment]
How about a `MooseContrib` namespace?

**Comment by rwcarlsen** [comment]
How about a lower-case version ``moosecontrib`` or ``moose_contrib``?  CamelCase in namespacing makes it easier to mistake the namespace for a class/struct name.

**Comment by permcody** [comment]
I'm supportive of the lower case naming of namespaces. This is a small departure from what we've done but I agree with Robert on this.

**Comment by brianmoose** [comment]
Fine with me. Which one do you want? `moose`, `moosecontrib`, or `moose_contrib`?

**Comment by rwcarlsen** [comment]
I'd prefer ``moosecontrib`` just because I hate typing underscores.

**Comment by rwcarlsen** [comment]
Could you split this into 2 commits - one with the namespace additions and the other with the renames.  And maybe throw in a short comment at the top of the file for how to do an jsoncpp update.

**Review by permcody — APPROVED** [review]

**Pull request merged**
