### PR TITLE
Run contact at initialization.

### LINKED ISSUE #8451: Run contact at initialization
### Description of the enhancement or error report
Currently variables like penetration do not necessarily get computed and written to output at initialization.  Change this so that they do.

### Rationale for the enhancement or information for reproducing the error
Consistency in results.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None.

### PR DESCRIPTION
**Pull request by jasondhales**
### Complete each of the following items before creating a PR
Closes #8451

### CODE REVIEW

**Comment by permcody** [comment]
These changes aren't quite correct. The problem is that by assigning the desired values like this, you unintentionally clobber the other valid options. This is just the shortcomings of trying to create a better enum type. There's just not a better way that I know of. 

Instead, we routinely use these lines of code to change the default `execute_on`:
```
  MultiMooseEnum execute_options(SetupInterface::getExecuteOptions());
  execute_options = "initial timestep_end";
  params.set<MultiMooseEnum>("execute_on") = execute_options;
```

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
I am guessing that this change is causing the heavy test `combined:sliding_block/sliding/constraint.frictional_mu02_penalty` to exodiff. https://www.moosebuild.org/job/66025/

**Comment by permcody** [comment]
@gambka We can merge this without regolding or invalidating. Heavy tests don't prevent that. I'll view and merge as appropriate. I know you didn't break that test but it would be very helpful to get it fixed soon! Thanks

**Comment by jasondhales** [comment]
This test shows a single diff at time zero in the civet results, but it shows a whole bunch of diffs on my machine.  If that weren't the case, I would have re-golded it already, but I need to understand where the other diffs are coming from.

**Pull request merged**
