### PR TITLE
This removes the need for mkdocs:

### PR DESCRIPTION
**Pull request by aeslaughter**
# Purpose:
1. Allows site to build with threads, which saves a ton of time
2. The live server is smarter and rebuilds individual pages or the entire site depending on the file touched
3. Allows us to have complete control over the style, so we can implement an arbitrarily deep navigation tree

# Help, please!
@idaholab/moose-team I have got this site fairly close, but I need assistance finishing the style of the site. I do not know css or javascript well enough to be effective at styling the site. If someone out there is, I would like some help please. 

(refs #6699)

### CODE REVIEW

**Comment by dschwen** [comment]
Why is the [preview site](http://mooseframework.org/docs/PRs/7983/site/) so broken?

**Comment by aeslaughter** [comment]
@idaholab/moose-team I finally fixed the css/js relative path errors so the site should be better. But, I still need help to really make it nice.

**Comment by aeslaughter** [comment]
@idaholab/moose-team@sapitts 

This is getting close, but the following still needs to be addressed any volunteers would be appreciated:

1. The fonts (color and sizes) probably need some work
1. The menu items need to be tighter vertically
1. The Carousel needs some help
1. I need opinions on the parameter lists (do you like the collapsible items or would you just like a table): http://mooseframework.org/docs/PRs/7983/site/framework/systems/functions/imagefunction/index.html

**Comment by aeslaughter** [comment]
@idaholab/moose-team And most importantly, we need to write some proper content for the first page, including adding back in the build status and the R&D100 logo.

**Pull request closed without merging**
