### PR TITLE
Documentation fixups

### PR DESCRIPTION
**Pull request by friedmud**
Resize and restyle several things to do with fonts, add some more text to main documentation index pages

refs #9638

### CODE REVIEW

**Comment by friedmud** [comment]
@aeslaughter ping!

**Comment by dschwen** [comment]
Can we get a comparison how this interacts with the changes from Ben's PR?

**Comment by dschwen** [comment]
I'll work up a comparison that shows the interaction with Ben's PR.

**Comment by dschwen** [comment]
Before:
screen shot 2018-04-19 at 9 56 48 am

After:
screen shot 2018-04-19 at 9 59 51 am

👎

**Comment by friedmud** [comment]
@dschwen Even looking at your screenshots on your huge monitor I prefer mine (once you click it to zoom it to normal size.  You can see so much more and read so much more.

We can tweak what I have here... but it's closer to what it should be than yours.

**Review by aeslaughter — APPROVED** [review]

**Comment by aeslaughter** [comment]
@dschwen For standard displays, these changes work well.

**Comment by dschwen** [comment]
And @friedmud, you were asking about a google website that has prose text on it. Here is one that even has _documentation_ on it:

https://developers.google.com/maps/documentation/distance-matrix/intro

**Comment by bwspenc** [comment]
I have to say I _much_ prefer the changes after Derek's updates. The information density was way too low, which made it so you had to scroll through pages and pages to see stuff that should fit on one screen.

**Comment by dschwen** [comment]
https://www.sciencedirect.com/science/article/pii/S1071581901904586

http://journals.sagepub.com/doi/abs/10.1177/154193120304701112

https://www.sciencedirect.com/science/article/pii/S0141938207000133

**Comment by friedmud** [comment]
@dschwen no one changed the line length.  That can be a separate change independent of the font size and line spacing.

I added a new PR to increase the line spacing slightly (agreed upon by @permcody @aeslaughter and myself): #11321

**Comment by bwspenc** [comment]
After looking at pages I'm working on a bit, I think 16 point is a little hard to look at, and I'm leaning toward 18 point being better.  Part of the problem is the Roboto fonts that are being used are pretty spindly.

**Comment by friedmud** [comment]
Wait until the line-spacing goes through and see what you think.

Also: make sure you look at it on a regular laptop first.  Most people
don't have the huge-high resolution screens we do.

**Comment by sapitts** [comment]
I agree firmly with @dschwen; these changes make the documentation much harder to read. Even when I zoom in on my browser to increase the font size (yes, on my laptop), the letters are skinny and difficult to read. Could we swing the pendulum on the font size (and thanks for the extra spacing pr) back a bit towards what it used to be please?

**Comment by friedmud** [comment]
@sapitts maybe we should try a different font...

**Comment by permcody** [comment]
The pendulum is swinging the other way. Part of the problem is that we are addressing font-size, line-spacing and line-length all simultaneously. @friedmud's current PR goes back to 1.5 line spacing, which we all _now_ agree is better. I'm more than happy to listen to concerns about line-length for readability.

I'm slightly less interested in messing with font-size since that is often reader dependent and can be changed in every browser. Let's see if we can get these other two parameters fixed independently, then we can talk about font size if it's still necessary. Derek's suggestion of another font maybe be an option we consider as well.

**Comment by dschwen** [comment]
btw. line length is meassured in characters per line. We are not talking about pixels... unless you want to make the content column narrower. So yes, Derek's PR was absolutely changing the line length (as I mentioned above from 120 cpl to 160 cpl). 

I agree that it is worth checking out different fonts. Maybe we could even go crazy and take a look at a serif font for the prose text...

**Comment by bwspenc** [comment]
I think the Roboto font that we're using is very spindly and hard on the eyes.  Almost as bad as the default LaTeX fonts, but that's getting into holy war territory.  I'd prefer to just use Helvetica.  I tried it out yesterday, and IMO, it looks a lot better.  I can submit a PR so you guys can see what it looks like.  Also, FWIW, I think 18 pt rather than 16 pt is better.

**Pull request merged**
