### PR TITLE
Optionally allow uniform refinements when using a pre-split mesh

### LINKED ISSUE #18575: Allow uniform refinements when using a pre-split mesh
## Reason

 A uniform refinement is helpful for some instances when using a pre-split mesh.
 For example, a 'coarse' mesh might completely resolve geometry (also is large)
 but does not have enough resolution for the interior. For this scenario,
 we pre-split the coarse mesh (since it is large), and load the pre-split mesh in parallel,
 and then do a few levels of uniform refinements to have a fine mesh that
 potentially resolves physics features of the interior.

## Design

Add an optional parameter to control whether or not allow uniform refinements when using a pre-split mesh.

## Impact

Enable large-scale simulations

### PR DESCRIPTION
**Pull request by fdkong**
Closes #18575

### CODE REVIEW

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
I think maybe "skip_refine_when_use_split" defaulting to true would be a bit better naming/semantic.  It's more clear what is going on.  Other than that, this looks good.

**Comment by GiudGiud** [comment]
This seems to allow mesh generators to be ran as well, not just uniform refinement?

**Comment by rwcarlsen** [comment]
@GiudGiud - this should only affect the mesh complete action for the uniform_refine task - so nothing outside the uniform refine behavior should be changing.  If I missed something, could you point to the line that you think causes mesh generators to run that normally was being skipped before?

**Comment by GiudGiud** [comment]
ah nevermind wrong action.

**Comment by GiudGiud** [comment]
I'm adding a similar boolean
Is this going in as a skip or as an allow?

**Comment by fdkong** [comment]
@rwcarlsen It is ready for review again

**Review by rwcarlsen — APPROVED** [review]

**Pull request merged**
