### PR TITLE
enhance piecewise functions to allow more data contained in CSV file

### LINKED ISSUE #6303: Need to enhance piecewise functions a little
so that it can read csv files which contains data more than just abscissa and ordinate. Backward compatible will be maintained.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #6303.

### CODE REVIEW

**Comment by permcody** [comment]
@YaqiWang - This looks good except can I trouble you to put in a couple of small ExpectError test cases to test some (or all) of the error cases you put in there. I'd be nice to know that if you specify an index too big, or maybe accidentally duplicate the index it'll do the right thing.

**Comment by andrsd** [comment]
Should not this be in `PiecewiseLinear` rather than `Piecewise'? There are `PiecewiseBilinear | MultiLinear | Constant` that inherit from `Piecewise` and would get this behavior that would not do much...

**Comment by YaqiWang** [comment]
@andrsd by looking at the class inheritance graph, I see `Piecewise` is used by `PiecewiseConstant` and `PiecewiseLinear`. `PiecewiseMultilinear` is using `GriddedData` for parsing. `PiecewiseBilinear` has its own parsing. So I will not do any change for them in this PR.

**Comment by andrsd** [comment]
@YaqiWang Oh, my bad. Never mind then.

**Comment by YaqiWang** [comment]
@permcody per your request, bunch of ExpectError test are added.

**Comment by permcody** [comment]
Thanks!

**Pull request merged**
