### PR TITLE
Update PETSc to fix containerized herd code building using Docker

### LINKED ISSUE #14258: PETSc Build System Broken for Containers
## Bug Description
@permcody, I recently uncovered some odd behavior with the PETSc build system that broke my CI/CD for MOOSE and the general ability to build PETSc in a container.  

Satish Balay at ANL has been very helpful, and it looks like [the fix is in](https://gitlab.com/petsc/petsc/commit/53a5e9c0558560048914cf899e06b52f068f9586).  There isn't a clear timeline for how that commit will make its way to a tag, so I'll keep an eye on it.  If they make a v3.12.2 tag with the fix in it, I will try submitting an update PR referencing this.  If, however, ANL doesn't make a tag in short order, I will reach out to see how this might proceed.

## Steps to Reproduce
Attempt to run PETSc (revision addfb3b) configuration on Ubuntu, Debian, Amazon Linux, or OpenSUSE in a Docker container.  CentOS works for unknown reasons, and behavior using Singularity has not been tested.  Essentially, the build system successfully downloads, makes, and installs HYPRE, but it gets confused about the version number shortly after.

## Impact
Impact is pretty severe.  KP is effectively ham-strung on updating herd codes and building the latest from MOOSE.  Falling behind on this front has its own perils, of course.

### PR DESCRIPTION
**Pull request by herter4171**
In short, the PETSc submodule needs to be updated to incorporate [this fix](https://gitlab.com/petsc/petsc/commit/53a5e9c0558560048914cf899e06b52f068f9586) to address the broken state of containerized herd code building using Docker.  The update points to the latest on the PETSc master branch, which contains the fix.  I've built everything and ran tests, but I'm not sure which are allowed to fail and still pass CI.  

Closes #14258.

### CODE REVIEW

**Comment by dschwen** [comment]
We link to the issue to fix in the body of PR not in the title.

**Comment by herter4171** [comment]
@dschwen, got it.  CIVET was unhappy, because my commit message didn't have a pound symbol before the issue number, I believe.

**Comment by dschwen** [comment]
Yeah, your top commit needs to have `#14258` in the commit message. Note the `#`! You also seem to have a merge commit in your PR.

**Comment by herter4171** [comment]
Haha, yeah I've relearned that detail.  I tried to amend the initial commit to have the right message format.  Since I'd already pushed to the feature branch, Git had me do a merge commit.  Theres a bit of urgency on our end that's got me in a rush, so sorry for the sloppiness.

**Comment by dschwen** [comment]
You can amend your commit locally and force push it to your feature branch. We try not to have merge commits at this stage of our workflow.

**Comment by herter4171** [comment]
My attempt to revert yielded another commit and no deletion, so I'm just going to start over with a new branch.

**Pull request closed without merging**
