### PR TITLE
Use dnsDomainIs() for .hpc.inl.gov wildcard matching

### LINKED ISSUE #17347: Use dnsDomainIs for *.hpc.inl.gov wildcard in HPC proxy
## Reason
@tophmatthews came across an issue with the current match for `.hpc.inl.gov` domains in the HPC proxy, `shExpMatch(host, "*.hpc.inl.gov")`, doesn't work when layered with another proxy. I'm not sure as to _why_ it doesn't work, but we found something that does!

## Design
Use `dnsDomainIs(host, ".hpc.inl.gov")` instead for the wildcard match for `*.hpc.inl.gov`.

## Impact
Better HPC connectivity for everyone!

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #17347

### CODE REVIEW

**Comment by loganharbour** [comment]
@milljm can you see if this works for you as well? This fixes the problem @tophmatthews was having.

Add this guy instead: https://raw.githubusercontent.com/idaholab/moose/f74bc9f1d23e98bc3cf42d2100ab073fec03f282/scripts/hpc_proxy.pac

**Comment by milljm** [comment]
Yeah that seems to work for me...

**Review by milljm — APPROVED** [review]
Works for me...

**Comment by loganharbour** [comment]
Thanks. Will merge some time late tonight so that we don't get file changed comments on all PRs (file changed script checks against devel and not PR head).

**Pull request merged**
