### PR TITLE
Fix thread-sanity of some phase field ICs

### PR DESCRIPTION
**Pull request by dschwen**
Static `MooseRandom` functions are _bad_!

Refs #5560

### CODE REVIEW

**Comment by dschwen** [comment]
This requires 5 marmot tests to be regolded. I have a patch ready for that.

**Comment by friedmud** [comment]
@permcody you should take a look at this.  Is this the reason why the threaded random test fails... randomly?

I thought `MooseRandom` was supposed to handle threading already.

I really don't like this fix at all... we should fix the problem at a lower level... random numbers should work with threading without the users needing to do stuff like this.

**Comment by dschwen** [comment]
The static MooseRandom routines are _unfixable_! They are just not thread safe. If you do not care about parallel reproducibility **and** use them in a per-element/qp/node computation it is usually fine. The problem arises when they are used in the constructor or initialSetup to assemble a table of values, which _should_ be consistent across threads.
Each MPI process has its own random number stream which gets initialized with the same seed. **But** threads in one MPI rank share a single stream. This a) changes the numbers that are pulled, b) introduces _race conditions_ where sometime one thread will pull a number first, sometimes another one will. This led to Matthew's problem, where the initial adaptivity called the IC multiple times and the race made it set up a completely different configuration! So the mesh was not adapted to the final form of the IC.
If you want a better solution make ```RandomInterface``` work with ICs. I tried to add it, but ran into null pointer dereferences because ```current_element``` and ```current_node``` were not set when and where they were needed.

**Comment by dschwen** [comment]
I am really confused about what is not to like about this fix. MooseRandom is designed to be instantiated (as well as used statically). In the cases I address we need to use the instantiated version. There is no way we can make the static version threadsafe.

From my end this is ready to merge.

**Comment by friedmud** [comment]
@dschwen quit focusing on the fact that the calls are static.  I'm not saying that they should be static!

I'm just saying that there has to be a better solution than users needing to instantiate MooseRandom.

**Comment by dschwen** [comment]
If they are not static you have to instantiate :-)...  or have it be an interface (like RandomInterface, which has issues with ICs).

**Comment by friedmud** [comment]
@dschwen "If you do not care about parallel reproducibility" is also a non-starter.  That's the whole reason for MooseRandom to exist.  We want the exact same random numbers whether we're running with threads, MPI or in serial.  It's not only about reproducibility... it's also about debug-ability.  What happens when a run you have going on 1,000 processors gets into a weird situation because of a particular pattern of random numbers and fails.... now you can only debug on 1000 processors because that's the only way to reproduce the streams.

Again... we need to find a _proper_ fix.

**Comment by friedmud** [comment]
Yes, there has to be an instance somewhere... and it should be in a level below what the users see.  Whether that's RandomInterface or something else... I don't know.

Let's wait and see what @permcody has to say about all of this.  He's the man with the plan when it comes to random numbers.

**Comment by dschwen** [comment]
> "If you do not care about parallel reproducibility" is also a non-starter. That's the whole reason for MooseRandom to exist.
No, @friedmud, it isn't! That is the whole reason ```RandomInterface``` exists! ```MooseRandom``` is the old _crappy_ way that does _not_ ensure all those things.

**Comment by friedmud** [comment]
@dschwen MooseRandom is _used_ by RandomInterface.  MooseRandom has two interfaces: the static methods and then the stuff used by RandomInterface.  That second interface (with saving and restoring of state) is there to make reproducibility possible.

We're on the same side here.  I am not at all arguing for keeping MooseRandom the way it is (static is the devil!).

I want a solution for ICs (I don't care what... we need to think about it) that ensures parallel reproducibility, is thread safe AND is user friendly.

I completely agree that `RandomInterface` is the way we do this everywhere else.  We need to figure out how to either use that... or something like it in the IC system.

**Comment by dschwen** [comment]
Ok, @permcody and @friedmud I think I may have a partial solution to get ```RandomInterface``` working with ICs. The issue was that ```InitialCondition``` kept its own variables for the current node and element and did not update the ones from random interface (sightly different naming). I'm working on changing this. If it works users could just call ```getRandomReal``` and would obtain consistent results (in stuff like RandomIC).
**However**, this does not address the issue of getting reproducible values in the constructors. But we may be able to fix this by dealing with the special case of ```_curr_element == 0 && _curr_node == 0```.

**Comment by permcody** [comment]
I know I'm late to the discussion here and it's always good to understand history and why these things exist. Derek's last comment captures the current state correctly. Also just so we all understand MooseRandom was created a LONG time ago to deal with bad random number generation on Macs (circa 2008). It was widely used which is why it still existed after we introduced the parallel consistent PRNG interface. Also as you know, I never created a solution for ICs because it was more involved and Mike didn't care at the time to solve those issues. History aside, time to move forward...

@dschwen - I like your partial solution and yes people that still try to use MooseRandom in constructors or almost anywhere is asking for problems with threaded code let alone parallel reproducibility. Does that mean it should die? Probably not because there is always some weird need from random numbers outside of the controlled interfaces we've created. The only thing we can do is turn on threaded testing (a really good idea) and manage the code base that we care about. We could even go so far as to throw warnings when people use threads and MooseRandom together (also not a bad idea).

The biggest problem with the current state of things is the random failures that we still see with threaded use of MooseRandom that SHOULD work. I've looked at that code several times and do not see why/how it can or should fail but it occasionally does. Perhaps there's a bug in the PRNG library we are using. @andrsd found and fixed one threaded bug in there already but it didn't fix the failure that we still see. I really want to move libraries at some point in the future and I have my eye on one in particular but it requires C++11.

**Comment by dschwen** [comment]
Soooo... Do we have to leave the phase field ICs broken? Because then I'll make a different PR to add

```
if (_tid > 0)
  mooseError("This IC does not work in threaded mode because Derek refuses to merge #5562.");
```

;-)

**Comment by permcody** [comment]
No, Is this ready for me to look at again? I'll work with you to get it
merged.

**Comment by dschwen** [comment]
This has been ready from the start, or did I miss points to address? This does _not_ add RandomInterface to InitialCondition (that is a separate branch that is not ready at all).

**Comment by andrsd** [comment]
Is there a problem with adding `RandomInterface` to `InitialCondition`?

**Comment by permcody** [comment]
After having a more in-depth discussion about PRNG in MOOSE with @dschwen, I think we need to move away from those static routines as well. Yes this is definitely less convenient than what we are used to but if we ever want this thing to work with threads, we have little choice. This PR is fine for now since I know there is another coming. We'll document how to properly use random numbers in MOOSE once this is through that should always work. It won't be as convenient as using static methods but it will be thread-safe. I'm thinking about even disallowing the use of the library random numbers in our pre-checks in the near future.

**Comment by permcody** [comment]
Ultimately I would like to add `RandomInterface` to `InitialCondition`. A little more work is needed though since `InitialCondition` has it's own node and element loops. Also, we'll have to set up the MooseRandom data even earlier (also doable) before it'll be ready to go. We are working in the direction.

**Comment by andrsd** [comment]
Ok, then.

**Pull request merged**
