### PR TITLE
Move Statistics VPP to stochastic tools

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
@loganharbour 

The StatisticsVectorPostprocessor is used by a few tests in moose_test to compute some partitioner stuff, so I moved those tests to combined. But, those tests used other moose_test objects, so I had to at MooseTestApp to CombinedTestApp. Also, the SVPP tests rely on moose_test objects as well, so MooseTestApp was added to StochasticToolsApp as well.

I am sad, this all seems way too complicated. Is the real solution is to just create StochasticToolsStatistics -> SVPP?

**Comment by loganharbour** [comment]
> I am sad, this all seems way too complicated. Is the real solution is to just create StochasticToolsStatistics -> SVPP?

Yes.

**Comment by aeslaughter** [comment]
@loganharbour This moves StatisticsVectorPostprocessor to stochast_tools and just removes the need for it in moose_test. This is the right way.

**Comment by aeslaughter** [comment]
@fdkong Can you verify that it is alright to skip comparing the 'num_partition_sides' column in one of the partitioner tests.

https://github.com/idaholab/moose/pull/14749/commits/49097befdc83a8af3c8dc8b1deec318dc2933889

**Review by loganharbour — COMMENTED** [review]
The non-partitioner stuff looks good (looks like it hasn't changed from yesterday).

@fdkong can do the rest

**Review by fdkong — DISMISSED** [review]

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
