### PR TITLE
Remove legacy `InputParameters` construction

### LINKED ISSUE #19439: Remove legacy `InputParameters` construction
## Reason
`InputParameters validParams<T>` is done.

## Design
Remove all use of legacy `InputParameters` construction

## Impact
Removes legacy code. Will probably break apps that still use the legacy construction methods.

### PR DESCRIPTION
**Pull request by loganharbour**
refs #19439

### CODE REVIEW

**Comment by loganharbour** [comment]
Sorry for everyone subscribed to this... looks like CIVET is going crazy with posting comments.

**Review by dschwen — DISMISSED** [review]
this is probably fine, but my browser/computer cannot handle a 1380 file changeset

**Comment by loganharbour** [comment]
> this is probably fine

I'm gonna wait a few months for deprecation, shooting for beginning of march

> my browser/computer cannot handle a 1380 file changeset

Sorry I'm gonna need a thorough review; fix your stuff

**Review by GiudGiud — DISMISSED** [review]
browser died but git diff does fine

**Comment by loganharbour** [comment]
We'll get this in around the beginning of march. Only failure I found was RHEA. There's a PR up for it (has been since nov) and if it's not addressed it'll be removed from our testing

**Comment by GiudGiud** [comment]
any reason we're waiting?
My interest in this is that it's triggering unrelated deprecation warnings here:
https://github.com/idaholab/moose/pull/19676
in tests which dont allow deprecation

**Review by fdkong — DISMISSED** [review]
Nice cleanup

**Comment by loganharbour** [comment]
> any reason we're waiting? 

Deprecation is set for [March 1st](https://mooseframework.org/newsletter/2021_11.html#legacy-input-parameter-deprecation).

> My interest in this is that it's triggering unrelated deprecation warnings here

It's not unrelated if it's passing now; you should go remove the offending params

**Comment by GiudGiud** [comment]
It's triggering on inputs that do not use the deprecated parameters (direction, multiapp), as they dont have a multiapp. In that sense it's unrelated. 
I ll rebase on your branch see if it can be fixed then

**Comment by loganharbour** [comment]
So as to not completely leave users in the dark with something that doesn't even compile, I opted to just throw an error. We can leave this error in for a few months and then remove it. I've set a calendar reminder. Users will end up with something like this:

```
*** ERROR ***
The following object(s) are constructed using the legacy input parameter construction:

  AB2PredictorCorrector (MooseApp)
  AStableDirk4 (MooseApp)
  ActuallyExplicitEuler (MooseApp)
  <cut>

Legacy input parameter construction is no longer supported.

Convert InputParameters validParams<T>() for each object into a static
member function InputParameters T::validParams() and remove the old function.

See mooseframework.org/newsletter/2021_11.html#legacy-input-parameter-deprecation
for more information.
```

**Review by GiudGiud — APPROVED** [review]

**Comment by loganharbour** [comment]
Planning on merging this this evening

**Pull request merged**
