### PR TITLE
Update initial old value of Postprocessors

### LINKED ISSUE #5019: Old values of Postprocessors aren't right in first timestep
If you execute a Postprocessor on `initial` you would expect that the _old_ value of that Postprocessor during the first timestep would be the value you got during `initial`... but that's currently not the case.

I have a fix for this.

### PR DESCRIPTION
**Pull request by friedmud**
Simply copies back the value of Postprocessors after they have been executed on initial

closes #5019

### CODE REVIEW

**Comment by permcody** [comment]
Thanks, any chance you have a simple test for this to avoid a future regression. You know how much we all like messing around `FEProblem::initialSetup()`!

**Comment by friedmud** [comment]
Ah yes - I should have included a test.

Let me do that.

**Comment by friedmud** [comment]
Well... I'm glad you told me to make a test out of it... because it turns out that the problem was somewhat different from what I thought.

This code change _did_ fix the issue I was seeing... but kind of for the wrong reason.

The problem only occurs when using the Steady Executioner... if you use Transient it's fixed.  The reason why is that Transient calls `_problem.advanceState()` toward the top of `execute()` which copies back the Postprocessor values.

So... now the proper fix is to call `_problem.advanceState()` in the Steady Executioner.  I have that fix ready to go (it does work) and I'll put in a test to make sure it stays that way...

**Comment by permcody** [comment]
Will that impact material props too? Maybe that's a desired effect.

**Comment by friedmud** [comment]
I don't think so.  I mean it will copy the old state of them back... but I can't see that doing any harm.  Let's see what the testing system says.

**Comment by friedmud** [comment]
BTW: This is still in line with my believe that the Steady executioner should get gutted... and should really just inherit from Transient and set `num_steps=1` ;-)

**Pull request merged**
