### PR TITLE
add a master rand generator to each app/problem

### PR DESCRIPTION
**Pull request by rwcarlsen**
This is just a quick cut at the idea - basically anybody who needs random numbers can create their own c++11 generator and seed it with a number from the app master generator (and reset/reseed whenever they want).  This way we get reproducibility while enabling unique random number sequences to be generated in multiple places (e.g. subapps) all from a single master app seed.  Details of the PR include:

* Added load/store functions for mersenne twister generator for
  restart/recover.

* Each app (re)seeds subapps' master generators by pulling values from
  its master generator.

* If an apps generator is reseeded, then a transfer reseeding
  to subapps occurs.

* a reset_rand_on param was added to FEProblem params - that takes an
  ExecFlagType. This is used to auto-reset the app's generator when that
  flag phase fires.

* multiapp subapps are seeded immediately upon creation

ref #8101 (fixes maybe), #8111 (provides alternate soln)

### CODE REVIEW

**Comment by rwcarlsen** [comment]
If we decide to go this route, tests will need to be added to this PR.

**Comment by dschwen** [comment]
It does not look like there is any integration into the current RandomInterface stuff. If that is so, this is of very limited use. We have a lot of existing objects that would need to be converted over to maintain their own C++11 RNGs. We also need the RandomInterface infrastructure to ensure parallel random number reproducibility.

**Comment by permcody** [comment]
I agree with Daniel. The transfers themselves look fine, but you've introduced new members into FEProblem for this function. I'd prefer them to be part of the existing MooseRandom object even if they are using the new generator. I should be possible to wrap the C++11 generation pieces into MooseRandom and turn them on/off with parameters. Over time we can then migrate existing code to using newer generators without having to change the interface.

**Comment by permcody** [comment]
Closing due to inactivity.

**Pull request closed without merging**
