### PR TITLE
Use override keyword in tensor mechanics userobjects

### LINKED ISSUE #7956: remove some repeated doco from tensor mechanics user objects
### Description of the enhancement or error report

The TensorMechanicsPlastic* and TensorMechanicsHardening* should employ the "override" keyword so that doxygen comments don't have to be repeated

### Rationale for the enhancement or information for reproducing the error

Reduce size of files

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by WilkAndy**
This allows removal of lots of repeated doxygen comments and makes the code slightly more readable.

Fixes #7956

### CODE REVIEW

**Comment by cpgr** [comment]
Hi @WilkAndy - can't see these here but I get two compiler warnings for `TensorMechanicsPlasticWeakPlaneTensileN.h` and `TensorMechanicsPlasticWeakPlaneShear.h` because `modelName()` isn't marked override

**Comment by WilkAndy** [comment]
Aha, i see, thanks @cpgr

**Comment by WilkAndy** [comment]
Cool beans, thanks @cpgr .   How did you get the compiler to tell you about those mistakes?

**Comment by cpgr** [comment]
The clang flag that gave the warning is `-Winconsistent-missing-override`. I just ran `make` in `opt` mode after I updated everything this morning.

**Comment by WilkAndy** [comment]
Thanks.  And how did you tell "make" (moose) to use that flag?

**Comment by cpgr** [comment]
I don't think I did anything?

**Comment by WilkAndy** [comment]
Oh, ok.  I'll try it at home with my mac.  Thanks.

**Review by permcody — APPROVED** [review]
Wow! ~1000 lines of redundant documentation removed.

**Comment by permcody** [comment]
Try it in devel or debug mode. I think that flag gets turned on so you'll
see that message. I haven't found a way to enforce the override flag in all
files though....

**Comment by WilkAndy** [comment]
Thanks @permcody .

**Pull request merged**
