### PR TITLE
Adding x_offset to piecewise functions

### LINKED ISSUE #4534: Allow Piecewise functions to specify an offset for x values
Most functions are given in a way they start at t=0. When one wants to restart from a steady-state at t=t_ss, we have a need to shift these function in time so that t_start=t_ss. Instead of changing all the values, one parameter that shifts the whole function would be convenient.

### PR DESCRIPTION
**Pull request by andrsd**
Adding the ability to shift piecewise functions along the x-axis. Good for restarts.

Closes #4534

### CODE REVIEW

**Comment by WilkAndy** [comment]
I'm not sure what this is for exactly.  Is it worth me or you adding this to PiecewiseMultilinear with x, y, z and t offsets?

**Comment by andrsd** [comment]
Let's say you have a piecewise linear function that is a function of time, has about 100 data points, the first data point is at t=0. Now, you want to run a simulation, but you want this function to kick in at t=t_0+ofst. So you can (a) go and shift all the points by `ofst` in time by hand, or (b) you have this convenience to shift it by specifying a value. Which one do you pick? If you said (b) then this is what this PR is about ;-)

The more I am looking at the code now, the more I think it needs more work. I am not sure I understand the `Piecewise` business exactly. Marking under construction...

**Comment by WilkAndy** [comment]
OK, so for PiecwiseMultilinear, you probably only want the offset on the "t" values.  I don't think i would ever use it, as i would set my start_time appropriately.  However, it's a pretty easy addition that might be useful to other people.

If you would like to refactor my PiecewiseMultilinear stuff then I'd be delighted.  I use it occasionally in real models, so don't remove it entirely!

a

**Comment by andrsd** [comment]
> i would set my start_time appropriately

In our use case, we have to run some other simulation that will take you to t=t_restart and then our start time is non-zero, but our function starts at t=0, so we want an easy way to shift the values.

**Comment by permcody** [comment]
@andrsd - One month no activity ping :smile:

**Comment by andrsd** [comment]
I know, I do not really have time to work on this right now because of other things ;-(

**Comment by bwspenc** [comment]
Don't close this! -- I was needing this just the other day and hoping it would get done.  Maybe I can get to it...

**Comment by permcody** [comment]
The PR may be closed but that doesn't mean the branch is gone. I have an
unofficial policy of keeping PRs from getting stale. Branches however don't
have this policy. Feel free to pick this up and thanks!

**Comment by andrsd** [comment]
@bwspenc The branch is still in my fork. I do not have time to go and properly implement this in all `Piecewise-` classes. I just hacked it for `PiecewiseLinear` because I needed it there. Feel free to grab my branch and build on top of it.

**Comment by bwspenc** [comment]
@andrsd, yes, I'll take a look.

**Pull request closed without merging**
