### PR TITLE
Change sign on thermal eigenstrains

### LINKED ISSUE #9903: Sign wrong on thermal eigenstrain temperature derivative
### Description of the enhancement or error report
The sign is wrong for the derivative of thermal expansion eigenstrains with respect to temperature in tensor_mechanics.

### Rationale for the enhancement or information for reproducing the error
It's negative when it should be positive.  I'm writing some code that actually uses that now, which is how I found the problem. It was apparently not tested.

### Identified impact
Remove a negative sign in ComputeThermalExpansionEigenstrainBase.C

### PR DESCRIPTION
**Pull request by bwspenc**
closes #9903

### CODE REVIEW

**Comment by bwspenc** [comment]
@dschwen We need to talk about testing this. I'm writing some code that uses this, and will have a test shortly, but maybe we should use your derivative testing system.

**Review by dschwen — APPROVED** [review]
I'd be fine with adding the test with your upcoming changes.

**Comment by dschwen** [comment]
Oh, wait, the derivative is not hooked in anywhere, right. Maybe we should add a test. Let me make a commit...

**Comment by bwspenc** [comment]
The derivative will be used in my upcoming commit, but it would be even better to have a dedicated test of the derivative as well.

**Comment by bwspenc** [comment]
I'm closing this PR because I'm including this commit in PR #9912, which also adds tests that depend on this.

**Pull request closed without merging**
