### PR TITLE
SQA pages for navier stokes

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
What does this all do?

**Comment by aeslaughter** [comment]
It adds this: https://mooseframework.inl.gov/docs/PRs/16651/site/modules/navier_stokes/sqa/

**Comment by lindsayad** [comment]
I take it those warnings and error will need to go away at some point

**Comment by aeslaughter** [comment]
Yes, those and a few 100 more. We track all the modules here already: https://mooseframework.inl.gov/sqa/index.html

**Comment by lindsayad** [comment]
Is there going to be training for module developers on how to fill these things out?

**Comment by aeslaughter** [comment]
Yes, eventually we will have training for INL and potentially non-INL people. We also need to improve the instructions on the website. The training that will be created will be available as slides and/or regular website pages. I am envisioning this content will be in the "contributing" section of the website.

There is some information now for adding requirements: https://mooseframework.inl.gov/python/MooseDocs/generate.html

There is more about the SQA process in https://github.com/idaholab/moose/pull/16472

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
