### PR TITLE
Add INSFVScalarFieldAdvection

### LINKED ISSUE #16732: NSFV scalar outflow boundary condition
## Reason
@smharper needs it for his models and in general it's pretty dopey not to have this

## Design
This will inherit from `INSFVFullyDevelopedFlowBC` because we want to apply a zero normal gradient condition

## Impact
Nice outflow conditions for transported scalars

### PR DESCRIPTION
**Pull request by lindsayad**
I know I said boundary condition in #16732, but the implementation here
is more consistent with current practice. With the implementation here,
we simply execute the `INSFVScalarFieldAdvection` object on the outflow
boundary. This object also adds `INSFVScalarFieldVariable` which
currently does nothing different from `MooseVariableFVReal` other than
it sets `two_term_boundary_expansion = true` by default. Moreover,
`INSFVScalarField*` and `INSFVEnergy*` are currently equivalent, but
I've created them anyways in case in the future it can allow us to
reduce code duplication by having them separate. E.g. I'm imagining that
maybe we can reuse code between CNSFV and INSFV implementations, but
perhaps that reuse will be different between energy and non-energy
arbitrary scalars. Morevoer, if we do end up adding real code to
`*NSFVEnergy*` and `*NSFVScalarField*` that is similar, we can insert a
base class that implements common code, something like
`*NSScalarFieldBase*` or something. Others can feel free to disagree
with my thoughts though.

Closes #16732

### CODE REVIEW

**Comment by smharper** [comment]
I think we should add some source term to the test problem so the scalar distribution isn't totally flat, e.g.
```
  [scalar_src]
    type = FVBodyForce
    variable = scalar
    value = 0.1
  []
```

The code/docs look good. I'm still doing some testing with reactor geometries/properties, but so far so good.

**Comment by lindsayad** [comment]
With a uniform body force, we shouldn't have a zero normal gradient at the outlet right? Which is fine because I didn't actually implement this with a zero normal gradient condition...we just extrapolate the outflow boundary face value from the boundary element centroid value and gradient

**Comment by smharper** [comment]
Yeah, zero gradient would be a bit of a fiction for that case, but I'd still find it acceptable for the test. We could also use a block restriction or a parsed function to get zero source next to the boundary if you prefer.

**Comment by lindsayad** [comment]
Mmm, pretty! This is with the uniform body force. I really like that the extrapolation is keeping the correct shape for the scalar as you move along the flow channel all the way to the outflow.
Screenshot from 2021-01-20 08-59-32
Screenshot from 2021-01-20 08-59-08

**Review by smharper — APPROVED** [review]
Looks good. Thanks for the fast turnaround on this PR! Happy to merge once we get the green check mark.

**Pull request merged**
