### PR TITLE
Delete CahnHilliardFluxBC and use NeumannBC instead

### PR DESCRIPTION
**Pull request by jiangwen84**
In Cahn-Hilliard equation, the flux is defined as the gradient of chemical potential. The flux bc will be Neumann type bc for both split and non-split form and can standard NeumannBC.  

closes Ref #10865

### CODE REVIEW

**Comment by jiangwen84** [comment]
Failed due to timeout 

[300.0s]     FAIL navier_stokes/test:ins/mms/supg.32x32_alpha_1e0 FAILED (TIMEOUT)
[300.0s]     FAIL level_set/test:reinitialization.full FAILED (TIMEOUT)
[300.0s]     FAIL phase_field/test:MultiSmoothCircleIC.specified_test FAILED (TIMEOUT)
[300.0s]     FAIL phase_field/test:grain_tracker_test.test_ebsd_adapt FAILED (TIMEOUT)
[300.0s]     FAIL phase_field/test:rigidbodymotion.euler_angles_updater_check FAILED (TIMEOUT)

**Comment by jiangwen84** [comment]
@brianmoose what should I do for those time-out failed tests? Thanks.

**Comment by brianmoose** [comment]
I have seen those level_set and phase_field tests timeout randomly. Not sure I have seen the navier_stokes one timeout. I will invalidate...

**Comment by jiangwen84** [comment]
@dschwen Can you review the codes? Thanks!

**Review by dschwen — APPROVED** [review]
Looks good to me!

**Pull request merged**
