### PR TITLE
Allow e_from_p_rho in TabulatedFluidProperties

### PR DESCRIPTION
**Pull request by snschune**
I want to use `TabulatedFluidProperties` in RELAP-7. However, I need to
have `e_from_p_rho` available which is not the case in `TabulatedFluidProperties`.

I add this in this PR by setting up an interpolation `T(p, rho)` from the existing table
and then do:

```
e_from_p_T(p, T(p, rho))
```

Test resides in combined so I can use the `InternalEnergyAux`.

### CODE REVIEW

**Comment by andrsd** [comment]
The test should be a unit test and it should go into `TabulatedFluidPropertiesTest.C`.

**Comment by andrsd** [comment]
I don't know how exactly you are using this class, but for RELAP-7 you need at least these calls implemented:

* `p_from_v_e`
* `T_from_v_e`
* `c_from_v_e`
* `e_from_v_h`
* `c_from_v_e`
* `cp_from_v_e`
* `cv_from_v_e`
* `k_from_v_e`

They are used in the Riemann solver and the fluid property material. There might be even more depending on what BCs you are using...

**Comment by snschune** [comment]
> I don't know how exactly you are using this class, but for RELAP-7 you need at least these calls implemented:

I just realized that. It's much more complicated than I thought.

**Comment by snschune** [comment]
If I implement additionally `p(v, e)` then I think I can convert whatever I want.

```
p = p(v, e);
T = T(p, 1/v);
Call the pT version of the function.

**Comment by snschune** [comment]
@andrsd what do you think? Is this worthwhile or should I just wait for Matthias to implement hydrogen properties and just adjust cp in my problem for now?

**Comment by andrsd** [comment]
I would wait for Matthias, he can build the hydrogen properties in a few weeks if not faster. Use `IdealGas` meanwhile - it won't be great, but good enough for your needs. Swapping the fluid properties is a trivial task...

**Comment by snschune** [comment]
Closed by recommendation of @andrsd

**Pull request closed without merging**
