### PR TITLE
Moving parameters and fixing Faux GT Bug

### PR DESCRIPTION
**Pull request by permcody**
refs #6115 

This addresses your immediate issues. I think I'll hold off on the interface cleanup until the new grain tracker class is pushed.

### CODE REVIEW

**Comment by dschwen** [comment]
:+1: Thanks Cody!

**Comment by dschwen** [comment]
FauxGrainTracker does not have a test if I'm not mistaken, but I will add a test using it in an upcoming PR. So it would be great if this could be merged.

**Comment by permcody** [comment]
You're right, who merged my :hankey:?

**Comment by dschwen** [comment]
Ok, @permcody, my brain is a bit mushy from the sun here. How the heck to I look up the unique grain ID for a given OP index on a specific element?!

**Comment by permcody** [comment]
Well that depends on if you are using the GrainTracker or FauxGrainTracker. If it's the later (which I assume it is in this case) the assumption that n_grains == n_op_vars is important. 

For a given element, only one coupled var will be non_zero (or more accurately, above an appropriate threshold). That coupled variable index will be the unique grain id. That's the essence of the loop inside of the `execute` routine. I look at all the variables until it finds one above the threshold, then caches that information for retrieval by an AuxKernel, or other objects in the system.

**Comment by dschwen** [comment]
Ugh, this is not at all what I need. You are too focussed on the AuxKernel that outputs unique grain identities. That is nice, but it is only a secondary goal. The _primary_ goal is to fetch _grain_ parameters for kernels operation on an _OP_. For that I need a vector (or map) from OP to grain number (for _every_ OP!) at every element. I thought this existed sometime in the past!

In FauxGrainTrackr this will be an _identity_ map, that can be built once. In the current FauxGrainTracker this seems to be in a WTF state. It may be `_faux_data`, but that is only resized and never properly initialzed. What?

**Comment by permcody** [comment]
Right `getElementalValues()` (plural) is the intended API for that information and it does appear that I didn't build that data structure in FauxGrainTracker. It does exist in the real grain tracker...

BTW, it's more than the identity map, at least by the way Mike was using it. He wanted the active grains at each element. That would only be one grain within a grain but would be multiple grains in a grain boundary. If that's the information you need here, I can fix that up for you in a jiffy!

**Comment by dschwen** [comment]
Yeah, sure. That sounds about right. I would prefer if the grain tracker
did NOT make that decision of which op is "active" though and let kernels
decide. Otherwise GT needs to apply thresholding (which I guess it does
anyways... So never mind?)

**Comment by permcody** [comment]
That's a schizophrenic answer...  

You tell me what works best for you. These are floating point values so somebody needs to decide what thresholds to use. If you'd rather have a list of ops and their values, we could build that data structure instead. With the current design you pick the threshold when you active the `GrainTracker` (or Faux).

**Comment by dschwen** [comment]
Haha, yes it is. You are right. Thresholds have to be picked anyways (to enable grain tracking). So let's do it like you suggested. Just return a list of the active OPs.

My desired interface would be one that fetches the grain ID for a given variable number. So if the OP is not active for a given element what could such an interface return? A grain ID of -1?

**Comment by permcody** [comment]
The current interface (which may be clunky) returns all the active order parameters at once as a vector of pairs. The vector is not necessarily ordered, it's just the "list" of active grains and their corresponding ops. I'm open for adding a different API though if you wish.

**Comment by permcody** [comment]
So to answer your question more clearly, if a grain ID is not in the vector, it's not active. Yeah... We probably need a different data structure.

**Comment by dschwen** [comment]
So... there is `variable_idx` (which seems to be the order parameter number as in 0 ... numop-1, and NOT libmesh variable number) and there is `var_idx` which seems to be something else entirely(?)

**Comment by permcody** [comment]
Those should be the same thing (i.e. the coupled index, NOT the libmesh variable number). If they are not, I f---ed up.

**Comment by dschwen** [comment]
Either way, I think it would be _good enough_ to initialize the `_faux_data` with an identitiy map. Otherwise this part of FauxGT is just broken.

**Comment by dschwen** [comment]
Either way, I think it would be _good enough_ to initialize the `_faux_data` with an identity map. Otherwise this part of FauxGT is just broken.

**Comment by dschwen** [comment]
And var_idx is not that. Look at FeatureFloodCountAux:
```
  params.addParam<unsigned int>("map_index", 0, "The index of which map to retrieve values from when using FeatureFloodCount with multiple maps.");
```
This is passed in a _var_idx...

**Comment by permcody** [comment]
No, same thing...

I used `map_index` because it's possible to collapse all of the grain tracker data into a single map (always index 0) if you just need to make an image or need the "most active" grain at any location in the domain. Most of the time (and in all grain tracker simulations), map_index IS the same thing as variable index.

**Comment by permcody** [comment]
I'm a Computer Scientist, I built an a$$load of extra knobs into this thing...

**Comment by dschwen** [comment]
Yeah, I don't get that. If I pass in the var_idx of an OP into that function I do _not_ get the grain ID back. This is not intuitive. It is completely unclear to me what the purpose of var_idx really is.

**Comment by permcody** [comment]
Mostly debugging... I sometimes use it to create n_op fields to display instead of just one. That way I can look at the sizes of the grains to some specific threshold (usually a small number like 0.1 or 0.05) which is very different than where the BndCalc Aux usually puts the grain boundaries. So in a nutshell, I pass in var_idx and I get a one or zero back of that coupled variable (based on threshold comparison) at the given location to indicate whether it's in a grain or not.

**Comment by permcody** [comment]
In other words, I get back something that looks a lot like the original OP field but much more sharp instead of smooth.

**Comment by dschwen** [comment]
Anyhow, I'm adding this for now https://github.com/dschwen/moose/commit/af52af90c775a559a31f1501a39f3b7395717a4a and try to make due with the existing interface. This should make the behavior more similar to the real GT.

**Comment by permcody** [comment]
I don't see how that will help, that will just give you all of the
identities at every element? I agree the current implementation is
incomplete but your fix isn't the same as what's in GrainTracker.

When do you get back? Clearly this discussion is too complicated for email
or Github. Also, I have to go to an SQA meeting in a few mins... ugh

**Comment by dschwen** [comment]
It helps because for my application it makes it possible to exchange FauxGrainTracker with GrainTracker. I do not care about the _active_ status at all. I just need an answer for the question which Grain does that OP represent on the current element.

**Pull request merged**
