### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by permcody**
Static Analysis fixes in MOOSE and modules. More on the way in the #7865.

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]
The only thing we didn't really understand was the `fn_names` thing, but whatever.

**Comment by permcody** [comment]
Freakin' Effin' Names

**Comment by YaqiWang** [comment]
how to do this? I'd like to do this analysis for rattlesnake.

**Comment by permcody** [comment]
make sa

**Pull request merged**
