### PR TITLE
Experimental Material Profiling

### PR DESCRIPTION
**Pull request by permcody**
refs #000

DO NOT MERGE

### CODE REVIEW

**Comment by permcody** [comment]
@aeslaughter, @YaqiWang, @snschune 

Here's a branch that will allow you to profile your material evaluation. Note that Material evaluation is intertwined in everything so there's not a good way to profile it. The profiler gets called per element (per side), etc so it DOES have an adverse impact on performance if we were to leave it in here. 

However, I'm willing to open up the utility of having this in the framework as a debate. Several of us think that material profiling is best left to profiling utilities such as Instruments or OpenSpeedShop, if however there's enough demand for having a simple utility like this that people could use developmentally maybe we'll leave it in.

**Comment by permcody** [comment]
Oh and @WilkAndy 

Tagging @idaholab/moose-team - Clearly something like this would have to be easy to use, say through the definition of an environment variable.

**Comment by YaqiWang** [comment]
Can we bypass the fancy `PerfLog::push` and `Perflog::log` by calling the system timer and later add the entries into `PerfLog`? Then the penalty would be negligible.

**Comment by permcody** [comment]
Well we can look at building a better logger altogether which is a separate issue. The current logger is actually pretty poor and slow indeed. I'd prefer to not try to outsmart the logger in just one case.

Even with a negligible logger we are talking about adding quite a bit more code to perhaps the very hottest loop in MOOSE so I don't know if we'd want it on in production runs all the time anyway.

**Comment by jwpeterson** [comment]
> The current logger is actually pretty poor and slow indeed.

I woudn't say it's poor.  It's designed to one very simple thing, i.e. coarse-grained/big picture logging, and it does that well.  If you need fine-grained profiling information, there are real tools like Instruments and Open Speedshop for this.  We should not try to reinvent those sophisticated tools in the humble `PerfLog`.

**Comment by permcody** [comment]
Ok poor might be a poor choice of words 😉 

We could probably change the string comparisons or underlying map lookup to make it more optimal without significantly altering the API.

**Comment by jwpeterson** [comment]
> We could probably change the string comparisons or underlying map lookup to make it more optimal without significantly altering the API.

Yes, I've had a long term plan to at least change it to use an `unordered_map` as the underlying data structure.  That would probably speed it up only slightly though, since I don't think the map ever really gets that big...

**Comment by dschwen** [comment]
You could use a "get handle approach". To get the strings out of the picture (except for setup time)

**Comment by friedmud** [comment]
I'm against this. Any syscall this deep will have an adverse effect on
performance.

Use a profiler. OpenSpeedShop is awesome.

**Comment by friedmud** [comment]
Or - if you're on a mac use Instruments...

**Comment by permcody** [comment]
Yeah - we aren't merging this. However, if somebody really wants to dig it out, they can search for it in the history and run it on a toy problem.

**Pull request closed without merging**
