### PR TITLE
Update links to slides

### LINKED ISSUE #18427: Tutorial 2: MultiApps has an invalid link
### Discussed in https://github.com/idaholab/moose/discussions/18425

<div type='discussions-op-text'>

<sup>Originally posted by **doquang** July 24, 2021</sup>
The page (https://mooseframework.inl.gov/moose/getting_started/examples_and_tutorials/tutorial02_multiapps/index.html) has an invalid link:
https://mooseframework.org/getting_started/examples_and_tutorials/tutorial02_multiapps/slides</div>

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #18276)

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]
we need to change something about civet here. It doesn't need to run the full test suite

**Comment by aeslaughter** [comment]
@GiudGiud You can probably wait to review this until the end of today. I am going through things in preparation for giving this presentation, so will probably find more problems.

**Comment by aeslaughter** [comment]
OK, I think I am done with this?

**Comment by aeslaughter** [comment]
@GiudGiud Documentation target is fixed up, so this is now actually ready.

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
