### PR TITLE
Allow functions for temperature and pressure in NS Initial condition

### PR DESCRIPTION
**Pull request by GiudGiud**
Functions are needed for the HTGR blowdown simulation to have a T stratification at the beginning of the simulation

Would make sense to initialize pressure the same way as well, for other systems with denser fluids

### CODE REVIEW

**Comment by lindsayad** [comment]
@loganharbour I haven't seen this "No coverage report found for base commit" before

**Comment by GiudGiud** [comment]
It's because I rebased on next. But this is all covered trust me ^^

**Comment by loganharbour** [comment]
> @loganharbour I haven't seen this "No coverage report found for base commit" before

When you rebase on devel, you are guaranteed to have a base for coverage because running coverage tests is a dependency for next -> devel merge.

If you rebase on next (like @GiudGiud did here), and the test for that next merge never had coverage ran on it (it failed, or it was cancelled because of the candle), you may not have coverage ran for the base. In this case of this PR, here's the base merge on next https://civet.inl.gov/event/79425/. Cancelled.

Solutions:

- Checkout devel and cherry-pick your PR commits (which you may not be able to do if you need contents on next)
- Invalidate the coverage tests on the next PR (which I just did), wait for them to finish, and then invalidate the coverage target

**Comment by GiudGiud** [comment]
@lindsayad coverage is up for this PR now!
only 1 line missed

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
