### PR TITLE
Make ExpressionBuilder more MOOSEy and improve error checking

### LINKED ISSUE #5417: ExpressionBuilder dereferences null pointers for empty EBTerms
```EBTerm``` objects should never have an empty (null) ```root``` node pointer. I need to change the default constructor to generate a unique node (of a new type) as a placeholder for term substitution.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #5417

### CODE REVIEW

**Comment by permcody** [comment]
What are the chances this is Valgrind clean? Any bets?

**Comment by dschwen** [comment]
My bet would be the chances are pretty good. I've run this through valgrind extensively before this change to make sure it is not leaking memory. This changeset should only add additional asserts and protections against potential null pointer dereferencing (which is furthermore avoided by adding the TempID term nodes to EBTerms by default).

**Comment by dschwen** [comment]
If you want to make your "bet" interesting we'd have to establish some quotes...

**Comment by dschwen** [comment]
Hm, I'd love to actually test this but on rod moose-unit-dbg segfaults somewhere in ```FuzzyComparisonsTest::fuzzyFunctions()```...

**Comment by dschwen** [comment]
Nothing appears in the valgrind -v and --leak-check=full reports that is caused by ExpressionBuilder (ImageLoader seems to be a problem child though).

**Comment by permcody** [comment]
I'd say this conversation is officially interesting enough. We'll merge and see!

**Pull request merged**
