### PR TITLE
Convert docs/media to submodule.

### PR DESCRIPTION
**Pull request by aeslaughter**
Converts the media directory to submodule.

### CODE REVIEW

**Comment by dschwen** [comment]
Why?

**Comment by aeslaughter** [comment]
People don't like LFS.

**Comment by dschwen** [comment]
LFS is the right thing to use here.

**Comment by dschwen** [comment]
I didn't like it either until I very recently upgraded my lfs client.

**Comment by aeslaughter** [comment]
We are going to wait on this and see if git lfs is 2 works better.

**Comment by permcody** [comment]
I know this thread is a few hours old but I wanted to capture what it is about LFS that people "don't like":

1) It's slow for small files, at least with version 1.0. Each small file gets checked out serially and it can take a few fractions of a second for each one regardless of connection speed.
2) The smudge filter thing keeps screwing us. This might be user-error but it's problematic.

**Comment by dschwen** [comment]
File checkout only happens once per file, doesn't it? The initial git clone is slow, too. LFS 2.0 does some stuff (transfer queue) in parallel now (https://github.com/blog/2328-git-lfs-2-0-0-released) and the changelog mentions better resiliency against errors. For me it definitely made a difference. I had repos on two machines stuck to where a git pull would just hang (waiting for an LFS task). This just went away with the upgrade to 2.0.1

**Comment by permcody** [comment]
Yeah, 2.x series may fix our problems. We are always evaluating.

**Pull request closed without merging**
