### PR TITLE
Use more specific SubdomainID/BoundaryID types 

### PR DESCRIPTION
**Pull request by dschwen**
I might chose to reduce some more code duplication using templating. Opinions on this first?
A next step could be to use `MaterialPropertyName` more thoroughly.

Refs #6574

### CODE REVIEW

**Comment by permcody** [comment]
@aeslaughter - please review

**Comment by aeslaughter** [comment]
I really don't think it is worth doubling the number of lines of code and adding 6 new methods, some of which have two specializations, just to save the use of a few if statements and using unsigned int.

**Comment by jwpeterson** [comment]
One other thing to keep in mind, `boundary_id_type` is a *signed* type in libmesh... So it's technically possible to have negative boundary IDs, although no one ever does this in practice.  Anyway, using unsigned int for that could introduce a subtle bug is all I'm saying.

**Comment by permcody** [comment]
@jwpeterson is right - The MOOSE type is typedef'd to the libMesh type so it's better to use it. We already do it in several other places in the framework. Down the road a ways we might find a need to change the type again. It happened before which is why we introduced this type in the first place.

**Comment by dschwen** [comment]
@aeslaughter, point taken, but most of the new lines of code are now trivial, and they enforce a more stringent type checking. I have not taken this all the way. There are a whole bunch of places where we have code duplication for boundary and block stuff, with separate methods (not just some ifs).

**Pull request merged**
