### PR TITLE
Make detection of AMR-created meshes for robust to disjoint meshes

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #25278

was crashing on a user mesh

### CODE REVIEW

**Comment by roystgnr** [comment]
What did (the critical section of) the failing mesh look like?

**Comment by GiudGiud** [comment]
clad and fuel are not touching. gap is not meshed
it's somewhere along that surface though I didnt zoom on the  exact spot

Screenshot 2024-04-14 at 4 14 04 PM

**Comment by lindsayad** [comment]
I'm trying to understand the `checkNonconformalMeshFromAdaptivity` routine better. My first concern is on line 523-524 where you insert into the `coarse_elements` container. AFAICT you could be inserting a fine element into that container if you're looking at a mid-edge node belonging to a fine element. This is because of your `is_vertex` check on line 516

**Comment by lindsayad** [comment]
IMG_0459

I think as the code is now you would misclassify this element as a coarse element. Even if this doesn't impact the functionality of later code it's misleading for a developer reading it

**Comment by GiudGiud** [comment]
> I think as the code is now you would misclassify this element as a coarse element. Even if this doesn't impact the functionality of later code it's misleading for a developer reading it

it will get rejected later on when we try to form a coarse element with 4 fine elements
We dont need to classify elements right on every node, we just need to classify them right when examining that center node

**Comment by GiudGiud** [comment]
ultimately AI should look at the mesh and tell me what's wrong

**Comment by lindsayad** [comment]
could you just not classify it? For somebody trying to understand this method I don't think it's helpful to put a fine element in a coarse element container

**Comment by GiudGiud** [comment]
ok fixed! That was not bad.
You're right it s better to have the logic correct the entire way. It probably simplified the cases to deal later on too

**Review by lindsayad — APPROVED** [review]
are there similar issues for disjoint meshes for elements other than hexes?

**Comment by GiudGiud** [comment]
Not that I know and the tet code is very different

**Comment by GiudGiud** [comment]
Thanks for the PR

**Comment by lindsayad** [comment]
Yes I agree, thank you for the PR 😄

**Comment by GiudGiud** [comment]
Lol what happened I don't remember writing this

**Pull request merged**
