### PR TITLE
Make adaptivity work with INSFV variables as markers

### LINKED ISSUE #26244: INSFVVariable cannot be used within markers for adaptivity currently
## Bug Description
INSFVVariable do not compute on Qp unless requested. The request is done by the coupleable interface

however, the markers were made without the coupleable interface. Probably for a historic reason that markers predate coupleable.

## Steps to Reproduce
Run adaptivity, use INSFVEnergyVariable for the variable in a marker
See nothing happen

## Impact
An hour of debugging, going into the depths of the Qp computation before realizing the value was never computed in the first place.

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #26244

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
Instead of this change, my idea would be to do in the constructor:
```c++
if (mooseVariableFV())
  mooseVariableFV()->requireQpComputations();
```
Or perhaps even better would be to move the `requireQpComputations()` base class implementation down to `MooseVariableField` and then in the constructor you could just do
```c++
mooseVariableField().requireQpComputations();
```

**Comment by GiudGiud** [comment]
That works for me too.

**Comment by GiudGiud** [comment]
Umm but how do we know we dont need it? Should I make a test object to retrieve that status?

**Comment by lindsayad** [comment]
Yea, my thought was a derived class of `INSFVVelocityVariable` that errors if it gets into the compute qp values routines for a standard lid/channel-flow problem

**Comment by GiudGiud** [comment]
Alright did that. I do think it's a lot safer now. 

Did I overdo it on the number of routines that request Qp computations? We dont do second anything, nor XXXtest/Phi` in FV anywhere afaik but then it s future proof?

**Review by lindsayad — COMMENTED** [review]
Yes this is definitely an improvement. However, what I was thinking was doing what you are doing in `MooseVariableInterface.C` in all those kinds of interfaces in `MooseVariableFV.h/C`. That would be even safer in case someone is making calls to variable APIs not through `Coupleable` nor `MooseVariableInterface`

**Comment by GiudGiud** [comment]
Ok that works. I guess this is only an optimization of FV variables. I ll change it up

**Comment by GiudGiud** [comment]
prefer that? I dont see another way than the const_cast requireQpComputation in a few routines

**Review by lindsayad — COMMENTED** [review]
that is kind of ugly isn't it, but I think it's tolerable for the added safety.

Perhaps my preference would be to mark `requireQpComputations()` as semantically `const` and then make `_qp_calculations` `mutable` in `INSFVVariable`.  The other suggestion I have would be to to move the `_var.requireQpCompuations()` call to `MooseVariableDataFV`. And then you would get elem/neighbor (and in the future maybe lower) protection all-at-once/in fewer lines.

**Comment by GiudGiud** [comment]
both of these combined actually improve the picture quite a bit imo.

**Comment by GiudGiud** [comment]
alright it should be fixed now

**Review by lindsayad — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thanks for the review! I ll update the discussions

**Pull request merged**
