### PR TITLE
Fixing stateful material property seg. fault

### LINKED ISSUE #4602: Stateful materials and Indicators causes seg. fault

### PR DESCRIPTION
**Pull request by aeslaughter**
- closes #4602 
- Thanks @andrsd for helping with this.
- See #4599 for a bit more info.

### CODE REVIEW

**Comment by aeslaughter** [comment]
@friedmud You can take a look now, there is still some problems. It asserts in debug and seg. faults in parallel. I am taking a break from this for a bit.

**Comment by aeslaughter** [comment]
@friedmud Any chance you could take a look at this patch and resulting failures, I have been messing with this for days and just keep getting nowhere. There is still something wrong with the cache of internal side stateful material data. I just don't know anything about the system, so I am having trouble seeing where to go next with this.

**Comment by friedmud** [comment]
There is a good chance.  This stuff is complicated...

On Monday, February 2, 2015, MOOSE Build <notifications@github.com> wrote:

> Results of testing 49e7e32
> <https://github.com/idaholab/moose/commit/49e7e3251cabbe3d3634fac51e11a598af7e5321>
> using moose_PR_test recipe:
>
> Failed on: linux-gnu
>
> View the results here: https://www.moosebuild.com/view_job/11291
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/4603#issuecomment-72544660>.
>


-- 
Sent from my iPhone

**Comment by permcody** [comment]
Wow this PR really is quite straight forward - that gives us two new seg faults in the stateful adaptivity system. Did you run this through the debugger to get a stack trace?

**Comment by aeslaughter** [comment]
I know where it comes from, I don't know how to fix it. The material
property maps are all out of whack.

**Comment by permcody** [comment]
I couldn't help but notice an asymmetry in prolong and restrict material properties. Near the bottom of those two functions where the properties are actually copied. One of those functions indexes into an external data structure while one of them doesn't. That may be fine - just looking for things that might be incorrect.

**Comment by friedmud** [comment]
Damn - the tough thing here is that it works _once_ .   This is going to be a bitch to track down...

I'm looking at it...

**Comment by friedmud** [comment]
Update: I looked at it for a few hours yesterday... and couldn't figure it out.

Still searching....

**Comment by permcody** [comment]
Thanks - this system is really complicated. At some point I'd like to clean it up refactor it and get it documented. Long term goal

**Comment by permcody** [comment]
@friedmud it doesn't work once. We compute the indicators on the original mesh first. After the first timestep we have run through the prolong routine then attempt to compute them again where the problem is triggered. There's definitely something going on with the projection logic on internal sides that has probably never worked. I'm not sure how often we use stateful material properties on internal sides.

**Comment by permcody** [comment]
@friedmud - per our conversation yesterday do we just need to put in the proper error check and close this PR? 
(i.e. Don't allow Indicators to use stateful properties?)

**Comment by friedmud** [comment]
Not exactly - we also have to turn off the computation of stateful material properties when doing Indicators.

More correctly: we should really turn off Material property computation ALL TOGETHER when we don't need them for the current Indicators.  That would speed up the Indicator/Marker system tremendously

**Comment by permcody** [comment]
Closing this PR per our discussion. We need to restrict this capability instead of trying to make it work as is.

**Pull request closed without merging**
