### PR TITLE
TMA effective creep and plasticity strain output

### LINKED ISSUE #16121: TensorMechanicsAction Effective Creep and Plasticity
## Bug Description
The TensorMechanicsAction helps in the construction of Material and AuxKernel classes to reduce the input file length behind the scene.  `effective_creep_strain` and `effective_plastic_strain` are two material outputs that are created by individual creep and plasticity classes respectively, and the TensorMechanicsAction should not create a Material and AuxKernel for these two specific outputs.

## Steps to Reproduce
When using the TensorMechanicsAction to create outputs, the Material classes for `effective_creep_strain` are not created, as should be expected, however the AuxKernel classes are.  This will produce the error `A 'AuxKernel' object already exists with the name 'effective_creep_strain_clad'`.

## Impact
This issue should be resolved allowing material outputs to be correctly created.

### PR DESCRIPTION
**Pull request by vanwdani**
Closes #16121

Allows the TMA to allow `effective_creep_strain` and `effective_plastic_strain` as material outputs, without creating AuxKernels.

### CODE REVIEW

**Review by dschwen — CHANGES_REQUESTED** [review]
Just remove line 30 in `modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C` instead!

**Comment by vanwdani** [comment]
> Just remove line 30 in `modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C` instead!

I initially thought about this first, but if in the future it was decided that something like `effective_strain` or some other such output wanted to be calculated, we'd have to add this line back in.

**Comment by dschwen** [comment]
> > Just remove line 30 in `modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C` instead!
> 
> I initially thought about this first, but if in the future it was decided that something like `effective_strain` or some other such output wanted to be calculated, we'd have to add this line back in.

Yeah, but without the `"plastic_strain", "creep_strain"` entries. If you want, you can make that line 

```
        {"effective", {"EffectiveStrain", {}}},
```

and leave it as a placeholder

**Comment by vanwdani** [comment]
Fair enough!

**Pull request closed without merging**
