### PR TITLE
Treat invalid_id of element integers differently when converting it to a real number

### LINKED ISSUE #18665: Need to treat DofObject::invalid_id differently in ElemExtraIDAux
## Reason
The aux kernel `ElemExtraIDAux` evaluates element integers in `dof_id_type` as a `Real` into auxiliary solution vectors. The `DofObject::invalid_id` has different values in 32-bits and 64-bits `dof_id_type`. The loader might be confused when loading the solution in double and converting it back to `dof_id_type`.

## Design
`dof_id_type` is unsigned, i.e. the converted IDs are always positive, so we can use `-1.0` for an invalid ID, which works for both 32-bits and 64-bits.

Because we do not have a dedicated issue to track `ElemExtraIDAux`, this issue will be an indicator of that aux kernel for visualizing element integers in aux variables.

## Impact
More robust writing/loading of element integers.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #18665.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@roystgnr with this, you should be able to come up with the exodus file by yourself. Note that we will need to change this line
```
if (v == (Real) DofObject::invalid_id)
```
to
```
if (v == -1)
```
in the PR https://github.com/libMesh/libmesh/pull/2977.

**Comment by YaqiWang** [comment]
What is that Civet post?

**Comment by YaqiWang** [comment]
@roystgnr you will hit the issue #18622. So I will send you the updated two files again.

**Comment by YaqiWang** [comment]
Three meshes:

## bad_64bit_elem_integer.e
#    material_id = '0 -1 (invalid_id) -2 (2^64-2, bad)
#                   1  3              4503599627370496 (2^32)
#                   2  3              4503599627370497 (2^32+1)'
## good_64bit_elem_integer.e
#    material_id = '0 -1 (invalid_id) 2
#                   1  3              4503599627370496 (2^32)
#                   2  3              4503599627370497 (2^32+1)'
#
## good_32bit_elem_integer.e
#    material_id = '0 -1 (invalid_id) 2
#                   1  3              4503599627370495 (2^32-1)
#                   2  3              4503599627370494 (2^32-2)'

[a.zip](https://github.com/idaholab/moose/files/7024376/a.zip)

**Comment by YaqiWang** [comment]
This is ready for review. Should be a quick one.

**Review by loganharbour — COMMENTED** [review]
Would it not make more sense to block restrict the AuxKernel, and if `_id` is invalid throw an error?

**Comment by roystgnr** [comment]
I sometimes use invalid_id the same way that a C programmer might use NULL (or a C++ programmer nullptr or std::optional...) - not as an error case, but as a "no element is associated with this" case.  I assumed @YaqiWang was doing the same, in which case this PR (combined with https://github.com/libMesh/libmesh/pull/2977 in libMesh for the reading) would be the best way to handle that ... but indeed it might be wise to double-check first.  I swear, if the *one* time I forget to annoy someone with the phrase "XY Problem" turns out to be an XY problem, I'm going to get *so* much more annoying in the future...

**Comment by YaqiWang** [comment]
An element integer is for all elements. So we should support outputting invalid ids as well. If we are not converting to real for exodus, we possibly do not need this aux kernel. This aux kernel will possibly just for visualizing in the future, in that case, outputting `-1` than a huge number with other valid ids of small values can still be a better idea. So throwing an error may not be a better option. We can always do block restriction, and the exodus reader will not read those out side of the block and have invalid ids for those elements properly.

**Review by loganharbour — CHANGES_REQUESTED** [review]
Okay, I think this is fair. I was going to suggest adding a parameter to setting the Real to associate with invalid_id, but because the IDs are unsigned integers anyway I think that -1 is appropriate. 

Can you please make a change to the ElemExtraIDAux documentation to note that -1 implies invalid_id?

**Comment by YaqiWang** [comment]
Sure.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
