### PR TITLE
Fix the user object design with threads

### LINKED ISSUE #6723: Design issue in UserObject
### Description of the enhancement or error report
The `UserObject` constructor currently construct `_tid`, `_assembly` and `_coord_sys`, which should not belong to `GeneralUserObject`. Although there will be code duplication, but they should be moved to next level of inheritance.

### Rationale for the enhancement or information for reproducing the error
GeneralUserObject is only on master thread, and those member variables are valid only for threaded user objects.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
There should not be impact unless somebody is screwing up his general user object.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #6723.

On the other hand, I think mesh should be moved to the base class.

### CODE REVIEW

**Comment by YaqiWang** [comment]
I know this will break Yak. I will patch Yak very soon.

**Comment by YaqiWang** [comment]
Removing _tid in GeneralUserObject creates more impact than I thought...

**Comment by permcody** [comment]
You might let Andrew take a swipe at that. We might be able to handle it
differently.

**Comment by YaqiWang** [comment]
OK, I will hand this over to you guys. I will fix Yak to stay away from this member variables not belonging to general user object.

**Comment by friedmud** [comment]
This is not a good idea.

Interface consistency is a good idea.

Nothing wrong with having `_tid = 0` for GeneralUserObjects.

**Comment by friedmud** [comment]
I vote to close this

**Comment by YaqiWang** [comment]
While `_tid` can be kept, the other two `_assembly` and `_coord_sys` to me should be moved. And `_mesh` can be moved to `UserObject` too.

BTW, nothing prevents people from having their own thread loop in their general user object. Although I am overruled, I think we should reconsider this from user's perspective but not only from framework developers' view.

**Comment by permcody** [comment]
Yaqi,

A threaded loop would be fine. In that case you'd be doing a thread in ONE
copy. Maybe you can elaborate more on what object messed up your case?

**Comment by friedmud** [comment]
GeneralUserObjects definitely need `_coord_sys` (they may be doing their own loop and integrations - in which case they'll need that).

I don't know about `_assembly`... but it's not bothering me that it's there.

I do threaded loops in my GeneralUserObjects now... it works fine.

**Comment by YaqiWang** [comment]
Then they get `_coord_sys` on their own. They should be aware there are multiple copies of it in the system and they are getting the first one. My point is that `_tid` is a valid variable if you do the threading on your own.

**Comment by friedmud** [comment]
It is a meaningful variable within a GeneralUserObject too... It means THAT OBJECT is on thread 0.  Which it is.

If I'm doing threading within a GeneralUserObject I have a `tid` (note... NO underscore... like a local variable) that I'm using inside my threaded loop that I pass down into calls into MOOSE for that thread.

The GeneralUserObject is still on `_tid=0`... because it really is.  But within the loop it will have many different `tid`'s in order to access the correct data / objects in MOOSE.

**Comment by YaqiWang** [comment]
That is what I am doing: threaded kernels calling a function provided by general user object and pass the thread ID to it to retrieve the correct threaded assembly. Before I was using `_assembly` in the general user object, which is wrong. That is the reason why I raised this issue.

**Comment by andrsd** [comment]
That does not seem like the right way how to do it.You should use the `Assembly` of the caller, not callee.

**Comment by YaqiWang** [comment]
Right. The argument is that we are living in MOOSE (general UO can obtain those assemblies on its own) and `Assembly` is kind of heavy as a function argument. Even I pass it as an argument, I do not know what exactly I need to pass into the function.

**Pull request closed without merging**
