### PR TITLE
New Mutex to avoid race conditions in MooseException

### LINKED ISSUE #6191: Threading problems with MOOSE Exception
It appears that MOOSE exception is not thread-safe. If multiple threads throw at the same time there are thread errors that pop up in copying strings in the propagation of the error up the stack.

The most reliable way to replicate this is to use a LINUX system running three or more threads on this test:

```
tests/misc/exception/parallel_exception_initial_condition.i
```

### PR DESCRIPTION
**Pull request by permcody**
closes #6191

I just noticed that I left an "Impossible" mooseError in there. I actually don't think it's possible to hit that case. I guess we'll see what CIVET says about it. It can be removed if there are objections.

### CODE REVIEW

**Comment by friedmud** [comment]
@permcody I think a better idea is to make FEProblem::setException() thread safe by adding this mutex there instead.

We need to think about this kind of thing anytime we expose a function for use in a threaded region.

**Comment by permcody** [comment]
That's not good enough. Even the creation of the string in the threaded
element loop is not thread safe. It crashes right where I put the mutex

**Comment by friedmud** [comment]
That's not possible.  I suspect that you were seeing something odd because of inclining or something.  Creation of std::string is definitely thread safe!

**Comment by friedmud** [comment]
Ok - reading a bit more about this it sounds like old compilers might have a non-thread safe copy constructor for std::string!  Who new!

Any C++11 capable compiler shouldn't have that.  Maybe this becomes our reason to move to C++11?  We can't require that users don't use std::string in their threaded sections.  Hell... I bet we have thousands of those spread through moose!

What compiler were you testing with?  It sounds like this got fixed around GCC 4.3

**Comment by friedmud** [comment]
Nope: looks like it wasn't truly fixed until GCC 5! 9But i

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=21334

I'm not really sure what to make of this.  This bug (and it has been an actual compiler bug since C++11) means that strings can't be used at all in threaded sections.  Even just passing them by value into a function is not thread safe.

**Comment by permcody** [comment]
We don't really use them in threaded sections. Our objects are always
copied per thread so each thread can do whatever it wants. We only need to
worry about them in the library in places like this. Still this kind of
stuff is insane!

**Comment by friedmud** [comment]
I'm going to go ahead and merge this since it fixes the immediate issue.  We'll definitely need to keep in mind these kinds of problems with std::string in the future!

Hopefully this will all be solved by using newer compilers though...

**Comment by lindsayad** [comment]
Looking back on this because of some recent CIVET failures with nodal damping code (@bwspenc), this stuff really is wild. I have to say that I don't really like how we're handling this right now. As it stands if we get multiple exceptions, then the message we'll get is whatever message accompanied the last thread to report an exception.

Also, I'm curious why we put the mutexes in threaded element loop but not in threaded node loops...hence perhaps the threading errors we're seeing with the nodal damping code

**Pull request merged**
