### PR TITLE
Running clang-format on FeatureFloodCount and GrainTracker

### PR DESCRIPTION
**Pull request by permcody**
Manually reformatting several comments and lambdas
refs #7289

### CODE REVIEW

**Comment by dschwen** [comment]
This touches _a lot_ of lines. Which I still find off-putting about the whole reformat stuff.

**Comment by permcody** [comment]
It certainly does, but we starting to collectively think that this is the right thing to do. This code in particular with all it's really long lines and complicated branching structures was particularly hard hit by the formatter. 

However, most of the changes are fine and I really like the idea of a completely automated tool for style. Now, *how* we go about implementing this on a more widespread scale, I don't know. That's up for debate.

**Comment by permcody** [comment]
BTW - I think the current thinking is that the general formatting commit should be owned by the bot. This will indicate that it was a "maintenance" commit and not something logical.

**Comment by rwcarlsen** [comment]
... but something illogical.

**Comment by friedmud** [comment]
Is there any way to preserve ownership of the lines at all?

**Comment by friedmud** [comment]
You know - it touches a lot of lines... but I'm really happy with the way it looks in the end....

**Comment by rwcarlsen** [comment]
@friedmud - the problem with trying to preserve line authorship is that it splits and combines many lines.  So tracking and dealing with ownership (especially in the line-merge cases) would be infeasible.  I think the best option is to reformat with a bot persona (i.e.``clang-format-bot``) - so at least people know they have to look further back for real authorship info.

**Comment by permcody** [comment]
@jwpeterson - You can merge this. It's the clang formatted version of FeatureFloodCount and GrainTracker with a little bit of manual formatting and comment reflowing. It produces no diffs against @rwcarlsen's most recently merged .clang-format PR.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
