### PR TITLE
Use non-hdf5-exodus for new contact tests

### PR DESCRIPTION
**Pull request by lindsayad**
Refs failures on libmesh/libmesh#3229

### CODE REVIEW

**Review by roystgnr — APPROVED** [review]
This was just done with the standard "dump hdf5, reencode netcdf3" CLI?

**Comment by loganharbour** [comment]
Just added the disable HDF5 recipe; this should have it now pass

**Review by recuero — APPROVED** [review]

**Comment by lindsayad** [comment]
@roystgnr i have libmesh configured without hdf5 (for now until your MOOSE PR is in)

**Comment by lindsayad** [comment]
Lol I must have somehow clicked close on my phone. Thanks for reopening

**Pull request merged**
