### PR TITLE
Dof value accessors should be const

### PR DESCRIPTION
**Pull request by lindsayad**
These methods return const references so there's absolutely no reason
why they shouldn't be labeled const

Refs #15259

### CODE REVIEW

**Comment by lindsayad** [comment]
@recuero testing of the coupledValueLower APIs will be really easy to do with your changes in #15259 so when that is ready I can either add this content and corresponding tests directly to #15259 or wait until it's merged. (although these changes are necessary for your BISON MR, so you probably don't want #15259 merged without the material here)

**Comment by recuero** [comment]
@lindsayad I did some testing on these commits and, as far as I can see, all looks good. `AuxKernel`s and `ADMortarConstraint`s can exchange `AuxVariable` and lower-d Mortar variable values successfully. 

Yeah, I think it makes sense to put this together with #15259.

**Comment by lindsayad** [comment]
That's good to hear!

**Comment by lindsayad** [comment]
This was incorporated into #15259

**Pull request closed without merging**
