### PR TITLE
Allow boundary ID overlap when stitching in preparedness test

### LINKED ISSUE #24597: mesh/preparedness.test is catching desynchronized BCIDs
## Bug Description
As in https://civet.inl.gov/job/1565736/ from https://github.com/libMesh/libmesh/pull/3575 - when running `mesh/preparedness.test` in parallel with `METHOD=dbg` we occasionally fail an internal libMesh check for correctly-synchronized boundary id data.

## Steps to Reproduce
`METHOD=dbg ./run_tests --re preparedness -p 2` fails for me nearly 25% of the time.

## Impact
It's hitting unrelated libMesh PRs, which is only mildly annoying, but if we could be getting BCID data out of sync on non-ghosted (or even just on ghosted, depending on the app) elements, we could be getting bad results, in theory.  I'm not too worried in practice, since we'd have expected any problems that made it that far to have shown up in other tests long ago.

### PR DESCRIPTION
**Pull request by lindsayad**
I believe this was Paolo's original implicit desire. He knows what he's doing when he makes meshes.

Change the test to an exodiff as that would have caught the implicit regression of this test when #24526 was created/merged

Closes #24597

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Review by roystgnr — APPROVED** [review]
This doesn't fix the underlying problem; with that flag off maybe we should be getting different behavior but we shouldn't be getting stochastic behavior or synchronization-corrupting behavior.

But I'm okay getting CI to stop screaming by no longer triggering the problem until we've got a fix for it.

**Comment by roystgnr** [comment]
Synchronization-corrupting behavior, once we've got slit meshes and we try to acquire a boundary on the slit via a point, is really hard to prevent.  I guess I can try changing `SideSetsFromPointsGenerator` to request *every* match from the point locator rather than just the first match, then scream and die if we get multiple matches?

**Comment by lindsayad** [comment]
> We might be getting stochastic behavior via just the boundary id reassignments?

Why would that be stochastic though? A common creator of stochasticity is, for example, iterating over a set of pointers, but I don't think we have anything like that here.

**Comment by lindsayad** [comment]
> Basically it looks like the problem is that all the `stitch_boundaries_pairs` were specified numerically, then we started automatically juggling those numbers and so _naturally_ the stitching didn't always succeed afterward

@GiudGiud catches the modification of `second`, but I suppose for multiple pairs that `first` *also* could also have been renumbered and we need to handle that

**Comment by lindsayad** [comment]
There it is, the set of pointers!

**Comment by roystgnr** [comment]
I'm counting about 120 lines of code with a `std::set` of `Elem`/`Node` pointers in libMesh, and about 60 in MOOSE.  I wonder if it would be worthwhile to add some of our own containers for those, syntactic sugar to make it easier to sort by id rather than by pointer value.

But then I wonder how many should also be turned into `unordered_set`, or something like `boost::flat_set`, and I wonder whether we'd just be hiding bugs rather than eliminating them... and I wonder how high this belongs on the todo-list...

**Comment by lindsayad** [comment]
Yea I don't think changing should be a priority. There may be some algorithms that require iterating in sync across processes for which you do have to have a deterministic ordering and I think we have those in the places we need them. But yea in a lot of places `unordered` makes the most sense where you don't have parallel iterating concerns (or actually from what I remember iterating over an unordered container might actually be parallel consistent) and it's easy to hash and so it can be much faster than an ordered associative container.

Essentially we just shouldn't run into these stochastic issues if we've written our code correctly ... but obviously that doesn't always happen haha ... at which time these sets of pointers become a pain because of how they impede efficient debugging

**Comment by roystgnr** [comment]
> or actually from what I remember iterating over an unordered container might actually be parallel consistent

Iterating over an unordered container isn't even serial consistent; you can carefully make sure that your hash is of an id instead of a pointer and still end up with an unpredictable ordering because one system's headers use hash function A and another's use hash function B.

**Comment by lindsayad** [comment]
Hmm yea that makes obvious sense. I just thought I had read somewhere that the the std hash map preserved insertion ordering for iteration. But it makes sense for that not be the case/not guaranteed. https://github.com/Tessil/ordered-map guarantees it 😆

**Pull request merged**
