### PR TITLE
Fix shouldExecute = False

### LINKED ISSUE #9932: should_execute in TestHarness not doing the right thing
## Rationale
It looks like the `should_execute` option for tests in the test harness is not doing the right thing.  It looks like it's skipping execution of the _entire_ test.  It should only skip execution of the executable.

My suspicion is that this got lost in the latest refactor.

## Description
The idea behind this option is that you can run once and output multiple things then have several downstream tests that Exodiff and CSVDiff those outputs.  What it's doing right now is just silently passing any test that has `should_execute = false`.

## Impact
Currently a bug in the TestHarness... but it's not used too much.

### PR DESCRIPTION
**Pull request by milljm**
Fix an issue when shouldExecute() is false, we
still run processResults.

Closes #9932

### CODE REVIEW

**Review by permcody — CHANGES_REQUESTED** [review]
We really need to put in test cases for all these little fixes so we don't trip up again. Can you do that? See my latest PR since I just did this: https://github.com/idaholab/moose/pull/9936

**Comment by milljm** [comment]
The only thing I can think of how to create a unit test for this, is to go and grab a gold file from simple diffusion or something, copy it as though we generated results after running moose.

Then create a test, which would run a different test thus creating different results _had that test actually ran (should_execute=True), thus producing an error... because this new output will diff...?

**Comment by permcody** [comment]
Yeah, that would be one way to test it. We could make it even simpler, how about a syntax error in the input file, or an ignored parameter? That way if you tried to execute it, it would just crash.

**Comment by permcody** [comment]
Umm, you probably didn't expect a BISON failure here right? Will have to look into that.

**Review by permcody — APPROVED** [review]

**Pull request merged**
