### PR TITLE
Cleanup tensor mechanics deprecated tests 

### PR DESCRIPTION
**Pull request by gambka**
Cleans up deprecated tests fails associated with new addVariable API and MeshGenerators.
 
Refs #13909.

### CODE REVIEW

**Comment by gambka** [comment]
@lindsayad

**Review by lindsayad — APPROVED** [review]
@gambka Thanks a ton for this hefty PR! Nice sleuthing on the failing test. Can you open a ticket for the MeshGenerator behavior you want changed or is that already done?

**Comment by permcody** [comment]
Definitely a bug that names are lost. I'll take a look.

**Comment by gambka** [comment]
> Definitely a bug that names are lost. I'll take a look.

I've made an issue here: #14037

**Pull request merged**
