### PR TITLE
Only one residual calculation if solve_type=Linear

### LINKED ISSUE #11760: perform only 1 residual calculation if solve_type=Linear
## Rationale

Only 1 residual calculation per timestep is needed if solve_type=Linear.

## Description

At the moment two residual calculations are performed every timestep.  One for the first nonlinear residual (this is required), then PETSc does its linear solve, and then another, redundant, nonlinear residual calculation.  I do not know if it is PETSc, libmesh or MOOSE that is requesting this second residual calculation.  

## Impact

Computational efficiency.  In the simple physics i happen to be modelling right now, just doing 1 residual calculation would speed up MOOSE by two times!

### PR DESCRIPTION
**Pull request by WilkAndy**
I have no idea if this is the best way of addressing this issue, eg, this PR might have lots of side effects!

Fixes #11760

### CODE REVIEW

**Comment by permcody** [comment]
This is interesting. I see that you've heavily restricted it down to a very specific case but it works for you (assuming you have at least a one test case that fits all of these restrictions). Perhaps there is something that we can do here but I suspect we need to be dialing this up through PETSc or libMesh and not MOOSE. We can entertain putting something like this in though if this turns out to be a longer term project.

**Comment by fdkong** [comment]
I think `-snes_monitor_cancel` is a better solution than this PR.

**Comment by WilkAndy** [comment]
Oh, #11768 doesn't do what i want, so don't close this PR

**Comment by fdkong** [comment]
Upgrading PETSc should resolve this issue.

**Pull request closed without merging**
