### PR TITLE
Find mesh element neighbors in the fancy extruder

### LINKED ISSUE #15936: Empty neighbor lists from `FancyExtruderGenerator`
The mesh output by the `FancyExtruderGenerator` does not have the neighbors specified for each element. In other words, `elem->neighbor_ptr` returns `nullptr` for each side of the new elements.

This information is needed for the sideset generators like `SideSetsBetweenSubdomainsGenerator` so currently those generators will not work when their input is created by `FancyExtruderGenerator`.

This needs to be fixed by calling `find_neighbors` (or `prepare_for_use` which in turn calls `find_neighbors`) somewhere along the mesh generation train.

### PR DESCRIPTION
**Pull request by smharper**
Closes #15936

### CODE REVIEW

**Comment by loganharbour** [comment]
Ping @friedmud and @lindsayad 

If I recall correctly, we were generally against this kind of thing because if you have multiple `MeshGenerator`s that need neighbor links, they may all end up calling `find_neighbors()` over and over unnecessarily on the same input mesh.

I thought there was an idea for a `MeshGenerator` to pass some metadata on what exactly it needs, and the system can determine if it's available and otherwise call it.

**Comment by lindsayad** [comment]
> If I recall correctly, we were generally against this kind of thing because if you have multiple `MeshGenerator`s that need neighbor links, they may all end up calling `find_neighbors()` over and over unnecessarily on the same input mesh.

The danger to this thinking is that it may result in no calls to `find_neighbors`. For instance I believe that unless @smharper calls `find_neighbors` here, it will never get called. `MooseMesh::prepare` gets called during `SetupMeshCompleteAction` and if you look at the code, `prepare_for_use` is not going to get called unless `force || _needs_prepare_for_use`. We initialize `_needs_prepare_for_use` to `false` and the default value for `force` is `false`.

Do we have any tests leveraging `FancyExtruderGenerator` that involve mesh adaptivity or things like `DGKernels`? I'm really worried that those things wouldn't work right now without @smharper's change here.

> I thought there was an idea for a `MeshGenerator` to pass some metadata on what exactly it needs, and the system can determine if it's available and otherwise call it.

After #15338 `MeshGenerators` will be able to advertise ghosting that they need, but we don't yet have a way to advertise things like "I need neighbors", at least not to my knowledge.

**Review by lindsayad — CHANGES_REQUESTED** [review]
I would like to see a test involving something like mesh adaptivity because my hypothesis is that adaptivity would not have worked before this, and if it didn't, then it would great to make sure we don't regress in the future.

**Comment by loganharbour** [comment]
> After #15338 MeshGenerators will be able to advertise ghosting that they need, but we don't yet have a way to advertise things like "I need neighbors", at least not to my knowledge.

We definitely don't, but I think it's worth discussing unless we can think of a better idea.

**Comment by lindsayad** [comment]
> I would like to see a test involving something like mesh adaptivity because my hypothesis is that adaptivity would not have worked before this, and if it didn't, then it would great to make sure we don't regress in the future.

Adaptivity may actually only fail in debug mode since we only do `test_level_one` in debugging modes.

**Comment by lindsayad** [comment]
> We definitely don't, but I think it's worth discussing unless we can think of a better idea.

So long as we guarantee that `prepare_for_use` gets called at the end of mesh generation when we have objects that depend on it being called (e.g. `DGKernels`). We certainly don't have that guarantee now.

**Comment by loganharbour** [comment]
BTW there's an issue for this: #15823. If we absolutely need something like this in the short term, I would prefer that it be in the object that needs it. Not in objects that might come before the objects that need it. It's still not a good solution, unfortunately.

**Comment by lindsayad** [comment]
> If we absolutely need something like this in the short term, I would prefer that it be in the object that needs it.

What if the thing that needs it is algebraic? I think that if we don't want to `find_neighbors` in `FancyExtruderGenerator`, that's fine, but we should at least call `_mesh->needsPrepareForUse()`. We need to guarantee that `find_neighbors` has been called at some point, or else we're in for another time-sink of tracking down a bug when somebody tries to do something algebraic that requires neighbors to be correctly populated.

**Comment by smharper** [comment]
Looks like there are deeper issues here. If you add an `Executioner` to the `FancyExtruderGenerator` test input and run it without `--mesh-only` it will segfault. I'll keep digging.

**Review by friedmud — CHANGES_REQUESTED** [review]
Can't call `find_neighbors()` like this... it will be hella slow if you're doing something complicated.

@smharper and I talked about this, we need a way to keep track of the state of "preparedness" as meshes move through the mesh generation system.  I proposed a system where we utilize InputParameters to specify the state of the mesh after a mesh generator runs... and the state a mesh needs to be in before the mesh generator runs.

For now, that could just be `generates_prepared_mesh` and `requires_prepared_mesh`... then the MeshGenerator system itself can take care of making sure the mesh is in the right state.

**Comment by lindsayad** [comment]
> Can't call `find_neighbors()` like this... it will be hella slow if you're doing something complicated.

Will there be a later point where it will be less slow?

**Comment by loganharbour** [comment]
> > Can't call `find_neighbors()` like this... it will be hella slow if you're doing something complicated.
> 
> Will there be a later point where it will be less slow?

I think the point is to minimize calls to it, not to avoid calling it

**Comment by friedmud** [comment]
@loganharbour has this right.  This will be fixed by #15945

**Pull request closed without merging**
