### PR TITLE
Update PorousFlow landing page

### PR DESCRIPTION
**Pull request by cpgr**
Shamelessly stolen from tensor mechanics. @WilkAndy let me know what you think

Refs #13239

### CODE REVIEW

**Comment by WilkAndy** [comment]
Cool - i can't wait till the doco builds.

**Comment by WilkAndy** [comment]
It looks 1E6 times better than the previous version!  I hope it wasn't too hard to do, but i think it's worth it.  My only suggestion is to add a picture or a few pictures.  I really like that Numbat "lava lamp" simulation that you did.  Is it possible to do that in PorousFlow now?  Or, do you think we should put in some more practical applications, like my groundwater models, or models of coal mines, or CO2 injection, or @hsheldon 's mineralisation models?

**Comment by hsheldon** [comment]
Nice! I can provide some pretty pictures if you want. No numbats though.

**Comment by cpgr** [comment]
Yeah, pictures are missing, but I am working remotely today and didn't have any good ones handy.

I do have a convection example with PorousFlow - two-phase, two-component with dissolution of the gas phase that I am working into an example to add in.

**Comment by WilkAndy** [comment]
OK, cool.  So the picture(s) can be in this PR or later.  Shall we leave it to you, and you can call on us to provide pics if needed?

**Review by permcody — APPROVED** [review]

**Pull request merged**
