### PR TITLE
More exodiff robustness

### PR DESCRIPTION
**Pull request by roystgnr**
A swath of #9414 case fixes.  These are intended to correct some of the regressions @brianmoose is uncovering in his tests on #9430.  Since we're getting different FP behavior from system to system, I can't swear that all of these are sufficient, but they fix some errors at higher processor counts for me so they're a good start.

### CODE REVIEW

**Review by jwpeterson — DISMISSED** [review]

**Comment by jwpeterson** [comment]
@roystgnr Are you still working on this...?

**Comment by roystgnr** [comment]
One last commit coming up shortly.

**Comment by roystgnr** [comment]
Sorry, should have tagged it as "do not merge" in the meantime.

The material.throw_material failure was quite a rabbit hole: not a fluke of FP error, but an honest failure to work in parallel.  Since the failing ThrowMaterial code is in test/ and is only used once, I've changed it's official behavior in a way that works in parallel but keeps its nominal behavior unchanged, because I've come up short trying to think up ways to preserve the current official behavior.  Is there any callback method that a Material can override that MOOSE calls before each timestep or before each residual evaluation?  If not then I don't see how a Material can keep a needs-to-be-globally-synchronized variable like ThrowMaterial::_has_thrown in sync (except by cheating and redefining the variable like my last commit does).

**Comment by YaqiWang** [comment]
`SetupInterface::timestepSetup()`  and `SetupInterface::residualSetup()`?

**Comment by roystgnr** [comment]
@YaqiWang - that looks like what I was missing; thanks!

Let me replace that last commit with something that does it right, then.

**Comment by roystgnr** [comment]
Okay, now I think I'm done.  But since the point of the exercise was to make that Parallel Test target more robust, we should wait (I guess until a 16 core node is free?) so we can take a look at it before merging.

**Comment by roystgnr** [comment]
There's still low-hanging fruit to fix, but it can wait for a later PR.  We've got success through -np 10; let's merge this.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
