### PR TITLE
Adapt and modify still fails

### PR DESCRIPTION
**Pull request by permcody**
The looser diff tolerance in 193d67c8 didn't work. I'm
going to tighten the solve tolerance instead.

refs #6959

### CODE REVIEW

**Comment by jwpeterson** [comment]
Was it another really small diff like the last time?

I wonder if there is something fundamentally wrong with this test...

**Comment by permcody** [comment]
It was a small diff just below the last threshold you set.

This test needs to be revamped. It has always been problematic which is why it is heavily restricted. It uses a custom Executioner which has fallen behind the changes in Transient by a long ways so it'll continue to "rot". This super tight solve tolerance should take care of the immediate problem.

**Comment by friedmud** [comment]
Honestly, the test can probably be removed.  I added it essentially as an "example" for @amjokisaari on a way that pre-adaptivity could be done for nucleation events.  I suspect we have better ways of doing that now.

That said, this test has caught a LOT of issues over the years :-)

**Comment by amjokisaari** [comment]
Give it a Viking funeral?!

**Comment by friedmud** [comment]
>Give it a Viking funeral?!

lol - I'm sure @permcody would be up for that!

**Comment by jessecarterMOOSE** [comment]
> I added it essentially as an "example" for @amjokisaari on a way that pre-adaptivity could be done for nucleation events. I suspect we have better ways of doing that now.

May I ask what they are? 'Cause this is essentially what I'm doing. Hopefully my implementation isn't terrible. I should try to push some of that code and get some feedback.

**Comment by permcody** [comment]
I guess he's going to leave you hangin'

Let's see, Daniel might be doing modification post solution in some of his
newer nucleation work. Let's see if he'll chime in here.

I've been doing solution modification for a long time in the GrainTracker:
https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/postprocessors/GrainTracker.C#L773

Today we have a lot more control on when objects get executed: beginning of
time step, during linear and nonlinear iterations, and at the end of the
time step, to name several. Depending on your needs you can usually pick
one of these areas to modify the solution and everything else will work
fine even with adaptivity going on elsewhere.

This wasn't always the case. You used to get one shot at where you wanted
objects executed circa 2010-2011 when this was written. Because we had so
few options, Derek inherited from Executioner (which we highly discourage)
and made it work by forcing a specific ordering. The reason we highly
discourage inheriting from Executioner is because of how complex that class
is. People need to be able to augment that class but replacing parts of it
can be very error prone which is why it's not the "best" way anymore. That
piece in that executioner has continued to diverge from the main Transient
Executioner in MOOSE.

Cody

**Comment by dschwen** [comment]
I don't do solution modification. The free energy modulation that I apply is acting over multiple time steps to make a nucleus appear. That is enough time for adaptivity to kick in automatically and refine the location of the emerging nucleus.

**Comment by friedmud** [comment]
A combination of what @dschwen said and @permcody said is what I would have said.  I was waiting to see what other people were going to say.

I think @dschwen really nailed this one though: the right answer is NOT to modify the solution directly at all...

**Comment by jessecarterMOOSE** [comment]
A good discussion, though I was interested in the _adapt_ part, not the _modify_ part :smile: but I do need both. Don't want to hijack this thread though...

**Pull request merged**
