### PR TITLE
PorousFlowCapillaryPressure inherits from DiscreteElementUserObject

### LINKED ISSUE #12057: PorousFlowCapillary UserObjects should inherit from DiscreteElementUserObject
## Rationale

Currently these UserObjects inherit from GeneralUserObject, and they compute things like capillary pressure, saturation, etc.  However, now we have a user who wants to include user-defined Functions in their derived PorousFlowCapillary class.  So the PorousFlowCapillary must know something about the (x,y,z,t) point where the various functions (capillary pressure, saturation, etc) are being evaluated.  This will be possible if they inherit from DiscreteElementUserObject, and no other changes to PorousFlow are needed.

Later, the user thinks they might also want to use coupledVariables in their derived PorousFlowCapillary class.  This will mean some changes are needed to some PorousFlow Material classes, as the Materials will need to pass the quadpoint to the PorousFlowCapillary, so that it knows at which quadpoint to evaluate those coupledVariables.  This extension will *not* be made in this Issue, but i wanted to mention it in case it's pertinent to the above paragraph.

## Description

```PorousFlowCapillaryPressure``` inherits from ```DiscreteElementUserObject``` instead of ```GeneralUserObject```

## Impact

No impact on tests or other users, except it allows more flexibility in writing custom PorousFlowCapillary classes

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #12057

### CODE REVIEW

**Comment by WilkAndy** [comment]
I'm a bit stuck here, not knowing much about meshes and unit tests.  Could a MOOSE devel help?  There are failing unit tests that employ the ```PorousFlowCapillaryPressure``` class.  Due to this PR I presume those tests need some sort of mesh to work, and i see that ```MooseObjectUnitTest``` says: "Testing mesh-bound objects like Kernels, BCs, etc. is not possible with this class".  Does this statement include the ```DiscreteElementUserObject```?  If so, how should i modify the unit tests?  Derive from ```::testing::Test```, or hopefully some other simple change?

Tagging @cpgr in case he has some helpful advice.

**Comment by cpgr** [comment]
Sorry Andy, no good ideas here.

**Comment by WilkAndy** [comment]
By the way, i just tried to include ```MooseObjectUnitTest::buildObjects()``` in ```PorousFlowBrineCO2Test::buildObjects()``` and i get an assertion error `_ghosting_functors.count(&ghosting_functor)` failed - looks like it's calling the destructors: MooseUnitApp, MooseApp, FEProblem, FEProblemBase, etc.  Yea, i don't know what i'm doing!

**Comment by WilkAndy** [comment]
Thanks anyway, @cpgr

**Comment by cpgr** [comment]
Looks like a case for @andrsd

**Comment by WilkAndy** [comment]
Any ideas on this one, @andrsd ?

**Comment by WilkAndy** [comment]
Tagging @MarinaGrimm

**Comment by WilkAndy** [comment]
Sounds good, thanks @andrsd .  i think (hope) that you'll see the solution very quickly.

**Comment by WilkAndy** [comment]
Reminder to @andrsd  :-)

**Comment by andrsd** [comment]
I am looking into this now... Monday was a holiday here, that's why nothing happened yet.

**Comment by andrsd** [comment]
The fail in RattleSnake is unrelated

**Comment by WilkAndy** [comment]
We've realised that more is needed for @MarinaGrimm to be able to implement her requirements.  We need to have _qp passed through to the public capillaryPressure (etc) methods.  I've decided to implement this using a default argument value, such as

```
Real capillaryPressureCurve(Real saturation, unsigned qp = 0)
```

I toyed with the idea of overloading just the capillaryPressure method: one version would have just the ```Real saturation``` argument, while the other version would have ```Real saturation, unsigned qp```.  This requires less code changes, but it would require more regression tests to be created, and would always "sit off the side of PorousFlow".

**Comment by WilkAndy** [comment]
As part of this PR, I've also changed PorousFlowBrineCO2 and PorousFlowFluidStateBrineCO2IC and PorousFlowFluidStateBrineCO2 (as that's what @MarinaGrimm is interested in) to allow for quadpoint-dependent capillarity.  I hope i'm not opening the scope of #12057 too much.

**Comment by cpgr** [comment]
Thanks Andy

**Review by andrsd — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for your help with this, @andrsd 

a

**Pull request merged**
