### PR TITLE
Move tests using contact (and tensor mechanics) from combined module …

### PR DESCRIPTION
**Pull request by dewenyushu**
Move tests from combined to contact. Leave solid mechanics tests in combined. Address part of the issue #14684

### CODE REVIEW

**Comment by bwspenc** [comment]
It looks like there are a bunch of changes unrelated to your changes.  Can you rebase against devel?

**Comment by dewenyushu** [comment]
It should look good this time. @bwspenc please review the updated changes :)

**Review by bwspenc — APPROVED** [review]
Looks good, thanks!

**Comment by permcody** [comment]
@dewenyushu - One of your new tests is diffing when run in parallel. You can see this on the "next" branch. Can you please take a look?

**Pull request merged**
