### PR TITLE
Add syntax check tests for module examples

### LINKED ISSUE #7319: Run module examples with --check-input
### Description of the enhancement or error report

We are not testing our example files currently and this leads to frequently broken examples. Many of our examples are quite heavy, _but_ it might be feasible to test them with the `--check-input` switch. We could even do that on PRs!
### Rationale for the enhancement or information for reproducing the error

Our examples should always run. Those may be the first runs a new MOOSE user launches (and thus the _first impression_ a user gets of MOOSE).
### Identified impact

More testing, may require a bit more resources on the test boxes.

### PR DESCRIPTION
**Pull request by dschwen**
Wrote a small script to generate `tests` files for all modules examples. This uses `RunApp` with `--check-input`. Unsurprisingly quite a few tests fail, and the GrainTracker stuff is super heavy even for just construction and initialSetup!

Opening a PR to test this on moosebuild.

Closes #7319

### CODE REVIEW

**Comment by permcody** [comment]
What do you mean by super heavy? Why would it be expensive to set up?

**Comment by dschwen** [comment]
You tell me.

**Comment by permcody** [comment]
Those meshes are bigger and some of them have refinement turned on which does running during initialSetup. That's probably what's going on.

**Comment by dschwen** [comment]
Ok, I'll add options to modify the mesh size!

**Comment by dschwen** [comment]
This contains the commit from #7336 (which is needed to make two examples work again)

**Comment by tonkmr** [comment]
Is this still in the works? I think it would really help keep the examples operational.

**Comment by jwpeterson** [comment]
@dschwen this seems like something useful that could be fixed up relatively easily.  May I also suggest that we run the examples only in optimized mode?  That would probably take care of the rest of the timeout failures seen before.  Since there is a conflict I will rebase the branch and create a new PR unless you prefer to do something different...

**Comment by dschwen** [comment]
Go for it!

**Comment by jwpeterson** [comment]
Superseded by #8002.

**Pull request closed without merging**
