### PR TITLE
Adds ability to output latex/pdf from MOOSE markdown

### PR DESCRIPTION
**Pull request by aeslaughter**
This allows MOOSE style markdown to be used in creation of latex/pdf files as well as cleans up documentation and code around the docs system.

I ended up writing my own latex conversion tool, which mimics very closely the design of the markdown package being used. I spend a few days playing around with existing markdown/html to latex conversion tools and couldn't find anything that was suited for what we need.
(refs #6699)

### CODE REVIEW

**Comment by aeslaughter** [comment]
Here is an example pdf: [report.pdf](https://github.com/idaholab/moose/files/512836/report.pdf)

**Comment by brianmoose** [comment]
I see you are missing the bs4 module, anything else you need the recipe to pip install?

**Comment by aeslaughter** [comment]
That should be the only extra dependency. Once people agree to having this I will want to have an extra target to build the example presentation and pdf so we can make sure they continue to work.

**Comment by brianmoose** [comment]
FYI, some links are broken, like all of the documentation links.
This is probably due to the IOError that occurs in `Build docs`.
Looks like it was introduced in #7779.
Maybe we should use a link checker...

**Comment by permcody** [comment]
Holy crap this is big! Wow - lots of new python.

**Comment by aeslaughter** [comment]
It is not as big as you think, I added less than 1000 lines to do the converting. The reset is mainly concerned with streamlining the function calls to generate the various forms (web, presentation, or pdf) as well as adding more markdown content explaining things.

```
git diff upstream/devel --shortstat -- html2latex/
 8 files changed, 812 insertions(+)
```

**Comment by aeslaughter** [comment]
@idaholab/moose-team This is ready to go as far as I am concerned, I need someone to take a look. The BISON teams is hounding me to get documentation started for them and this is part of what they are wanting.

**Comment by aeslaughter** [comment]
@permcody I assigned you since your the boss, not sure who else to assign.

**Comment by jwpeterson** [comment]
The linked PDF looks good.  Is this also going to be able to make slides for presentations, or is that something else?  Who is the intended audience of the PDFs this generates?

**Comment by aeslaughter** [comment]
> Is this also going to be able to make slides for presentations, or is that something else?

There is another, very similar tool, for building presentations. That builds an html based slideshow similar to what we have now, but works from a single markdown file (which can include others).

> Who is the intended audience of the PDFs this generates?

Both BISON and Mastodon want to be able to create reports and theory manuals that exist on the website and in pdf format.

**Comment by permcody** [comment]
This doesn't follow the python standards. I could be convinced to switch to 4 spaces but right now our standard is 2 and I believe all of our existing python follows that convention.

http://mooseframework.org/wiki/CodeStandards/

**Comment by aeslaughter** [comment]
It certainly does not follow the standard, we need to update the standard.
The documentation system does not follow the standard, I am using 4 spaces
and it is already in the repository.

**Comment by aeslaughter** [comment]
I fixed the standard.

**Comment by permcody** [comment]
You can't just fix the standard. It's the standard for a reason.

**Comment by friedmud** [comment]
> You can't just fix the standard. It's the standard for a reason.

What he said.

It's the standard because we use two spaces everywhere else.  We don't want two different rules.

Not too mention that this has been the standard since the beginning with no reason to change it.

**Comment by aeslaughter** [comment]
I really want this changed, if I am going to be maintaining documentation
tools and visualization tools written in python I want 4 spaces. It makes
reading/writing the code significantly easier.

**Comment by friedmud** [comment]
No.

The standard has been set for 8 years.  It's worked well... and there is
consistency between the two languages (C++/Python).

**Comment by permcody** [comment]
Thanks for fixing up that Python spacing.

**Review by permcody — APPROVED** [review]

**Pull request merged**
