### PR TITLE
Basic Google chart support 

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #8329)

@rwcarlsen This might be useful for benchmark results.

### CODE REVIEW

**Comment by aeslaughter** [comment]
I think the build box needs a new package, we have included pandas for some time if I recall.

```
E: 19, 0: Unable to import 'pandas' (import-error)
```

**Comment by brianmoose** [comment]
pandas is in miniconda-dev module but apparently not in miniconda

**Comment by aeslaughter** [comment]
Oh, what do we do about that then?

**Comment by aeslaughter** [comment]
I will re-visit this in the future.

**Pull request closed without merging**
