### PR TITLE
Make python in MOOSE use 4-spaces

### PR DESCRIPTION
**Pull request by aeslaughter**
Let's see how many people this makes angry.

### CODE REVIEW

**Comment by friedmud** [comment]
No

**Comment by aeslaughter** [comment]
Find me another major python package, which MOOSE is becoming in some respects, that uses two spaces.

**Comment by permcody** [comment]
This isn't about what everyone else is doing. We received a lot of pressure
during the audits and in particular the python part because 1) we have a
lot of python in the MOOSE directory and 2) RAVEN was under the microscope
for style standards as well. Without a full style guide it was much more
defensible to say that all "formatting" between C++ and python was the same
(which is exactly what our guide says).

Most of python code in MOOSE has been 2 spaces since the beginning. You can
easily verify that by looking at old versions, we have this standard now
and it's been that way for a long time including through the audit.

I'm willing to look at updating the standard but if we do that we might as
well address everything else if we go down that path. As you probably
noticed the current python standards are very brief and don't address a lot
of things that need to be addressed. Let's not just change it over night
and not as part of another change request. Let's talk it out as a team and
make the decision for a full Python style guide. Then we can apply all the
changes at once to all of the code in the repository. I don't take these
style changes lightly, not with the scrutiny we are under.

**Comment by aeslaughter** [comment]
I can get on board with this answer. The Python standard is lacking, but
using pylint we could make this strictly enforceable.

We will have more problems with this in the future if/when we ever merge in
new Peacock. Chigger uses VTK style since it is build on VTK and users can
call VTK methods directly within chigger, I didn't want two styles of
function names. Similarly with peacock itself, we used a style that is
mostly compatible but has some quirks to make it look like Qt.

**Comment by friedmud** [comment]
Why?  The only style you should be using is _MOOSE_ style.  Anything else
is wrong.

We didn't just blindly use "libMesh" style because MOOSE uses libMesh.  We
chose a particular style because it gave us the consistency and readability
we wanted.  We evolved it over time (many years) and I think what we have
is really great.

I want _one_ way to format code in MOOSE.  Whether that's in C++ or
Python.  Function names, variable naming, indentation... EVERYTHNG should
be the same between the two.  Even beyond formatting... the way the code
_works_ should be similar (i.e. using inheritance for extension, plugin
systems, factories, etc.).  Uniformity in such a large project is
absolutely paramount... and definitely trumps "Well, other projects are
using 4 spaces".

What in the hell are we even doing having a conversation about this?  While
we fight about this the ticket count is closing in on _700_.  There are
better things to be doing!

The standard is set.  It has been set for MANY years.  All of our users are
used to our style.  Changing it at this point is completely ridiculous.
Just USE it!

**Pull request closed without merging**
