### PR TITLE
Assign correct boundary names in TransfiniteMG.

### PR DESCRIPTION
**Pull request by grmnptr**
Refs #28049

### CODE REVIEW

**Comment by roystgnr** [comment]
This isn't actually changing the boundary names, is it?  Just the integers corresponding to them?

**Comment by GiudGiud** [comment]
It s doing both
- changing the side id assignment to be more like the GMG and CMG
- fixing left <-> right switch 

It'd be good to regold all the tests and turn on `exodiff_opts = -pedantic` to make sure sidesets dont change in the future

**Review by oanaoana — COMMENTED** [review]
I am good with the modifications if the tests pass. It seems to be only a change of ordering from pairwise to counterclockwise, and it's still consistent with the documentation.  Did you check if the meshes look similar to the figures in the doc? Still curious how this popped up. @roystgnr any idea why both of these orderings worked for the given cases, or was there an update in  libmesh and the old ones failed?

**Comment by grmnptr** [comment]
This possped up when I tried to stittch two mesh generators: a square from a generated mesh generator and a transfinite mesh. After checking the boundaries in the gold files I saw that the left boundary was called right and vice versa. There was another issue: 
when the two meshes have the same boundary id but have different names for the boundaries the stitches will merge the boundaries with the same ids but will use the name from the first mesh. So the top and right boundaries got flipped because of the ID ordering. 
I am adding another PR which will warn for cases like this at the MOOSE level.

**Comment by roystgnr** [comment]
> @roystgnr any idea why both of these orderings worked for the given cases, or was there an update in libmesh and the old ones failed?

At the libMesh level we don't really care about what user code picks for ids and names, we just care about preserving them.  You can call a left boundary "right" and a right boundary "left" and we'll happily go along with it, because to libMesh a name is just a string that you assign to the true first-class-object id number, and you *also* get to pick your ids, and we'll happily go along with your choices; you can call id 12 "right" and also call id 14 "right" and that's your call.  Only if you try to combine different choices while assuming they're consistent do you run into issues.

At the MOOSE level, names were made the first-class-objects, except that for some reason **nobody at the time thought to add libMesh support for this** and we have bugs come up because of that.

> the stitcher will merge the boundaries with the same ids but will use the name from the first mesh.

Before adding another band-aid, please look at my first attempt to fix some of it, https://github.com/libMesh/libmesh/pull/3613 - but note the final commit there, where we default to fix to *false*, because there was already a MOOSE test I couldn't fix that was depending on the broken behavior in a way I couldn't diagnose.  I'm embarrassed to say that my next step here, to switch the default in MOOSE to *true* except for the failing case, is something I never got around to...

**Comment by grmnptr** [comment]
I don't think there is anything wrong in libmesh. I think there are a few different things that come in play here:
1. When we stitch the two meshes we already have an option to remap boundary IDs in MOOSE and it is the default right now
2. When the user remaps boundary ids we can end up with a boundary with the same name but two different ids, which will result in a screamfest with paraview

So here is my plan:
When the remapping is enabled and we detect two boundaries with the same name but different IDs in the meshgenerator we throw a warning with instructions to use the RepairMeshGenerator on top of the stitching.
When we disable mapping and we detect the same boundary ID with different names, we scream at the user saying that the stitching might result in unexpected boundary name changes and to fix that use the remapping together with the RepairMeshGenerator.

**Comment by grmnptr** [comment]
This PR is just to make the behavior of this MG similar to GMG in terms of boundary assignment. The warnings are coming in a different PR.

**Review by GiudGiud — APPROVED** [review]
good fix

**Pull request merged**
