### PR TITLE
Add more flexibility for hiding source files on MooseDocs

### LINKED ISSUE #19540: Add more flexibility for hiding source files on MooseDocs
## Reason

The `--hide-source` option for the MooseDocs build command simply hides _all_ source files. This feature is certainly useful for hiding C++ or other types of sensitive source code. However, some hidden source applications may still want to display other file types like MOOSE inputs, python codes, or data files, especially for the important purpose of demonstrating usage.

## Design

First off, it might be appropriate to ditch the `--hide-source` command line argument. All it does is disable the `'show_source'` option in the [ModalExtension](../blob/master/python/MooseDocs/extensions/modal.py). While this may seem convenient, anyone who uses this option probably wants to consistently, so they should be setting it in the `config.yml` anyways. We also seek to expand the feature to accept a list of shell-style patterns to match files that are safe to reveal, which would make the command line interface even more cumbersome. Ultimately, the YAML may end up looking something like the following:

```
Extensions:
    MooseDocs.extensions.modal:
        hide_source:
        exceptions:
            - *.i
            - *.py
```

## Impact

This enhancement will allow users to safely hide the contents of all source files from their public documentation and yet specify certain exceptions in the `config.yml` file. The ModalExtension will be modified to support this capability.

(refs #19019)

### PR DESCRIPTION
**Pull request by crswong888**
(closes #19540)

### CODE REVIEW

**Review by joshuahansel — CHANGES_REQUESTED** [review]
Looks good! The only thing I think is needed is a brief documentation page on it and a newsletter entry.

**Comment by crswong888** [comment]
@joshuahansel Yeah, the thing is the modal extension is kind of an internal one. We actually don't have any published documentation on the site: https://mooseframework.inl.gov/python/MooseDocs/specification.html

I figured adding the demos in some [`python/MooseDocs/test`](../blob/master/python/MooseDocs/test) files was sufficient for now, but let me know if it's not and I create an official docs page for the Modal extension.

**Comment by joshuahansel** [comment]
I see, and yeah, I saw that the extension was missing from the table on that page. What makes the extension an "internal" one? What I care about is that others would be able to find this information about the new option when they look for it, since there will be (and already are) other application developers that run into this issue.

**Comment by crswong888** [comment]
@joshuahansel "internal" might not be the best word, but used for lack of a better word. It's just something that people will never see at the MOOSE-flavored markdown level. And, until now, you would hardly even see it in the `config.yml` either.

But we'll leave this discussion here. It's not a huge deal, I'll add an official Modal extension page.

**Comment by crswong888** [comment]
@joshuahansel Also, while I was working on this I noticed that there's one other vulnerability here. This feature only prevents generating in-line links to pop-up windows that show the source code. However, you could still accidentally reveal code through the listing extension like:

```
!listing framework/src/kernels/Diffusion.C
```

The above would show the full source code right on the page, even if the `hide_source` option is enabled. Do you think we should have some way to block this feature as well?

**Comment by joshuahansel** [comment]
> you could still accidentally reveal code through the listing extension

@permcody Do we need to protect against this?

**Comment by joshuahansel** [comment]
@crswong888 Unless @permcody disagrees, I don't think you need to solve this in your PR - I think that is a separate issue. I don't think there are any concrete requirements on this "executable-only" documentation yet.

**Comment by crswong888** [comment]
Okay @joshuahansel this should be all set. Let me know if there's anything else you want.

**Review by joshuahansel — APPROVED** [review]

**Comment by joshuahansel** [comment]
@crswong888 Thanks for putting that together - A lot of executable-only users are going to appreciate it!

**Pull request merged**
