### PR TITLE
Variable values from previous nonlinear step

### PR DESCRIPTION
**Pull request by andrsd**
This allows users to access variable values from previous nonlinear step.

The design is (as usual) simple (and stupid). If the user code asks for variable values from previous NL iterate an extra solution vector is allocated. This solution vector is filled inside a PETSc callback (post_check). Auxiliary variables are evaluated at this point as well so that their values are consistent with the NL ones.

### CODE REVIEW

**Comment by andrsd** [comment]
I am not hung up on the function names in `Coupleable`, so if somebody has better names, I can change them.

**Comment by permcody** [comment]
Looks fine, I hope this doesn't continue to slow normal problems down. There's probably not any better way though without significant redesign of MOOSE.

**Comment by permcody** [comment]
@friedmud - any comments on this PR?

**Comment by YaqiWang** [comment]
I like this. It can be used for refactoring the current inverse power iteration. @fdkong could be interested in. Just wondering if we could let PETSc take over some of the code to avoid memory allocation or solution vector copying. I remembered MOOSE has a CPU time monitor, if this PR does not increase time in MOOSE tests, it is probably fine.

**Comment by fdkong** [comment]
> I like this. It can be used for refactoring the current inverse power iteration. @fdkong could be interested in. Just wondering if we could let PETSc take over some of the code to avoid memory allocation or solution vector copying. I remembered MOOSE has a CPU time monitor, if this PR does not increase time in MOOSE tests, it is probably fine. A small issue is to handle postprocessors and stateful material properties. To make things robust, we need to store all the states besides the primal and aux solutions.

As far as I know, PETSc nonlinear solvers do not store the solution history.  I want to refactor the inverse power iteration by rewriting the whole code based on PETSc and SLEPc.

**Comment by andrsd** [comment]
Postprocessors from the previous NL iteration cannot be retrieved right now, because they are not computed at all, but it should not be difficult to add in future. I think it could be done similarly like I treat aux variables...

Also, theoretically, using `solve_type = NEWTON` with the combination of this approach might improve run time (less residual evaluations and possibly having exact jacobians). We plan to use this in RELAP, but I do not have any hard numbers ATM.

**Comment by YaqiWang** [comment]
We can do the same thing as you did on aux variables. Evaluate pps and stateful properties at the end of a newton iteration and save them and provide a way to retrieve them like the variables.

**Comment by friedmud** [comment]
@permcody why does this slow things down?

Other than that: 👍

**Comment by permcody** [comment]
I have no evidence that it does slow anything down. I'm just noting that this adds more branching to MooseVariable which is a relatively hot spot already. If you're fine with this, I am.

**Review by permcody — APPROVED** [review]

**Comment by friedmud** [comment]
True about the branching... but there's so much there already I can't see it making a material difference.

Eventually we'll get around to implementing a few versions of that function that we can select from at runtime so there is no branching for the most common cases.... eventually.

**Pull request merged**
