### PR TITLE
Speed up grain growth tests

### PR DESCRIPTION
**Pull request by smharper**
The debug modules test is getting painfully slow to run.  This PR is one small step towards cutting down that test time.  I've simplified two of the grain growth tests (explicit because it is one of the most time consuming tests, and the basic one just because it is so similar to the explicit solve one).  I did this by shrinking the mesh down to only cover one small part of the grain boundary.  This cut the explicit runtime by ~70% and the GrGr_test runtime by ~40%.  Here are what the old test results look like:

Old GrGr
Old Explicit

And here are the new ones:

New GrGr
New Explicit

### CODE REVIEW

**Comment by friedmud** [comment]
@tonkmr @dschwen You guys should probably sign off on something like this...

**Comment by dschwen** [comment]
Using the symmetry is fine. Why can't we just take one quadrant of the circle. It would be clearer IMO. We need to make sure that we keep the curvature. The new tests don't look great to me.

**Comment by smharper** [comment]
I made them quarter circles now.  The images above reflect the changes.  Still seeing similar speedups.

**Comment by dschwen** [comment]
:+1:

**Pull request merged**
