### PR TITLE
Patch for new and old Nanoflann API 

### LINKED ISSUE #25904: API changes for potential Nanoflann update
## Reason
There have been several updates to Nanoflann since it was last updated in LibMesh and I want to try the concurrent tree building feature. I have opened https://github.com/libMesh/libmesh/pull/3684 to update Nanoflann to v1.5.0.  `nanoflann::SearchParams()` has been replaced by `nanoflann::SearchParameters()`, and, if the PR gets merged, we'll have to fix those calls for when libmesh update makes its way into MOOSE.

## Design
- [ ] Update `std::vector<std::pair<std::size_t, Real>>` instances to `std::vector<nanoflann::ResultItem<std::size_t, Real>>`
- [ ] Replace removed `nanoflann::SearchParams` with `nanoflann::SearchParameters`

## Impact
Prepare code for Nanoflann update

### PR DESCRIPTION
**Pull request by parikshitbajpai**
Closes #25904 
Requires https://github.com/libMesh/libmesh/pull/3689

### CODE REVIEW

**Comment by parikshitbajpai** [comment]
This will need Nanoflann update in LibMesh to go through and the submodule updated before changes here work. Opened this since I had the changes ready but will mark it as draft for now.

**Review by roystgnr — APPROVED** [review]
Fingers crossed...

**Comment by parikshitbajpai** [comment]
Argh, the python tests are failing and I've no idea how to fix those.

**Comment by loganharbour** [comment]
You guys don't need to invalidate for the civet results failures. We can merge despite their failure. Tests are simply a recommendation for the reviewer. But... now that we can't see that that was the failure, we need to wait for them again.

**Comment by roystgnr** [comment]
Those are due to network issues with the INL firewall.  Nothing to do but hit "invalidate" and cry while waiting for the next try.

**Comment by roystgnr** [comment]
> Well, if you didn't invalidate them for us to look at them we could tell you

If it had been more than a python failure I wouldn't have hit "invalidate".  I'm fine (modulo losing a *tiny* piece of my soul) hitting merge on a red X that was only a civet_results failure; I didn't realize SQA was fine with that.  I've done it at the libMesh level, but just because I know there's the submodule update CI stage beyond that before anything gets into MOOSE.

**Comment by loganharbour** [comment]
The SQA requirement is only that we need an independent review. Tests are only a recommendation. If they weren't only a recommendation, we wouldn't be able to merge things that break next and require an app patch.

**Comment by roystgnr** [comment]
Makes sense.

**Comment by loganharbour** [comment]
For clarity, though, you should comment to the failures and as to why it's appropriate to ignore them.

**Pull request merged**
