### PR TITLE
Adding UserObject interface for global strain  

### PR DESCRIPTION
**Pull request by SudiptaBiswas**
Adding UserObject interface for `GlobalStrainUserObject` so that different global strain calculations can be incorporated easily. 

Refs #11314

### CODE REVIEW

**Review by dschwen — DISMISSED** [review]
I'd prefer `GlobalStrainUserObjectInterface` instead of `GlobalStrainUOInterface`, but that is just a matter of taste. Can be merged as is.

**Comment by dschwen** [comment]
> `GlobalStrainUserObjectInterface` seemed a bit longer to me

Probably because it has 8 more letters :-D

**Comment by sapitts** [comment]
Would you use the full `GlobalStrainUserObjectInterface` please?  It's still nowhere near our current record holder: `ComputeMeanThermalExpansionFunctionEigenstrain`

**Comment by SudiptaBiswas** [comment]
Alright, done.

**Comment by mangerij** [comment]
I don't like UO.

**Comment by permcody** [comment]
Looks like this is ready for another review. @dschwen

**Review by dschwen — APPROVED** [review]

**Pull request merged**
