### PR TITLE
PorousFlow small changes to JOSS paper

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #15906

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hey @cpgr,

Further to my email - i can't reproduce the floating-point error on my system.

```
cd modules/porous_flow/examples/co2_intercomparison/1Dradial
../../../porous_flow-dbg -i properties.i Variables/zi/initial_condition=0.5 AuxVariables/xnacl/initial_condition=0.15 Outputs/file_base=properties_brine_co2 --error --error-unused --error-override --timing Outputs/perf_graph=true --no-gdb-backtrace    
```

works fine.   Hmmmm

**Comment by cpgr** [comment]
I've seen some of these randomly crashing on the petsc alt modules debug target before, but have never been able to reproduce it which makes it hard to debug.

**Comment by WilkAndy** [comment]
> I've seen some of these randomly crashing on the petsc alt modules debug target before, but have never been able to reproduce it which makes it hard to debug.

OK, thanks @cpgr.  I've just added a "skip if petsc < 3.12" for this test

**Comment by WilkAndy** [comment]
Hey @cpgr - a quick review would be good if you have time.  The PR has only 12 lines of changes, but i might have made a typo in the markdown.

**Comment by cpgr** [comment]
Looks ok to me.

**Comment by WilkAndy** [comment]
> Looks ok to me.

Thanks @cpgr .

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
