### PR TITLE
PorousFlowNodalValueMaterial.

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #8046

### CODE REVIEW

**Comment by WilkAndy** [comment]
@aeslaughter and @permcody , i'm going to need a lot of help with this.  This is the start of the Material-that-holds-nodal-info-at-its-quadpoints, that can be used by DiracKernels, as we discussed on the phone recently.

I have lots of problems, even after bashing away at this for a few hours.  If you look at PorousFlowNodalValueMaterial you'll see a few questions:

 - I don't know how to resize all my Material Properties, in a general way without having to specify their types (Real, RankTwoTensor, etc).  At the moment only the "PorousFlow_nodal_number" is resized (at least, i hope it is - i'm not sure i'm even doing things correctly), and i know it is an unsigned, but i want to do the same thing for all the declared Properties, somehow without specifying their Types.

 - I also think that even if i get this working, i'm pretty sure DiracKernels can't work with Stateful variables in any useful way.

Can you help me?

**Comment by permcody** [comment]
Glad you are up for an adventure. This definitely isn't a simple piece of code! Take a look at MaterialProperty.h:
https://github.com/idaholab/moose/blob/devel/framework/include/materials/MaterialProperty.h#L300-L306

It is possible to do things to "Properties" without knowing their types. This is because we hold onto the base class pointers which are **not** templated on type yet. 

As far as which material names you are going to deal with, I'm a little foggy on what we were doing there. This is going to be your base class for all DiracKernel material types right? So you want to figure out which properties have been declared by all material that are derived from this intermediate base class?

**Comment by WilkAndy** [comment]
Yep, i see the resizeItems in MaterialProperty.h, thanks @permcody.  I couldn't figure out how to get hold of that pointer to PropertyValues, but will keep trying today.

The material names problem: this is not really a problem.  i just have to know what the names actually are because there are a few Material properties that i don't want to resize.  My scheme is: all PorousFlow Materials derive from this base class.  If there are no Dirac Kernels in my simulation then everything (except the few that i don't want to resize) gets resized every time computeProperties gets called and it makes no difference because they're correctly sized anyway.  If there are DiracKernels then the resizing is necessary.  OK?

**Comment by WilkAndy** [comment]
OK @permcody and @aeslaughter , what do you think of this PorousFlowNodalValueMaterial ?   I *think* it does what i want.

**Comment by WilkAndy** [comment]
I hope to keep adding to this branch next week.  If one of you could look over the few lines in PorousFlowNodalValueMaterial i'd appreciate it, but it's not incredibly urgent.

**Comment by WilkAndy** [comment]
Design has changed.  @permcody @aeslaughter , i'd appreciate any comments you have on the following design:

    Current design:
     - PorousFlowNodalValueMaterial is base class for all other PorousFlow Materials
     - it allows derived Materials to distinguish between standard "qp" material properties, and new "nodal" material properties.
     - the latter are equipped with some new methods:
         + sizeNodalStatefulProperties, which derived classes override to correctly size nodal stateful properties to _current_elem->n_nodes()
         + initNodalStatefulProperties, which derived classes override to initialize nodal stateful properties (using subscript _nodenum instead of _qp used by initQpStatefulProperties)
         + sizeNodalProperties, which derived classes override to size non-stateful properties
         + computeNodalProperties, which derived classes override to compute nodal properties (using subscript _nodenum instead of _qp used by computeQpStatefulProperties)

**Comment by WilkAndy** [comment]
@permcody, this is going to turn into a mega PR soon.  The way it is going, almost all PorousFlow classes will be changed, and all of the test files too.  Before that happens, do you think you could look at

porous_flow/src/materials/PorousFlowMaterial

to see if you can identify any problems.  It is only short.  The idea is that PorousFlow will have two types of Materials: one is standard, the other has all its properties sized by the number of nodes in the element.

**Comment by WilkAndy** [comment]
Closing this for now.  All the tests are failing and it's a waste of computer resources to repeatedly run them.

**Pull request closed without merging**
