### PR TITLE
Percent change postprocessor feature added 

### LINKED ISSUE #5297: Percent change postprocessor feature
Adding a postprocessor that computes the change between time steps. Useful if user wants to terminate the simulation if the percent change of postprocessor is a certain value(ie 1% or so).

### PR DESCRIPTION
**Pull request by permcody**
Squashed for @mangerij
closes #5297

### CODE REVIEW

**Comment by permcody** [comment]
Good point, that option should be controlled via a parameter but it's probably ok for a first cut.

**Comment by dschwen** [comment]
Well, it is unexpected to say the least and a bit unusual to have an option for. If we get postprocessor old value support in parsed functions per #5284 users could implement whatever norm they want (together with ```FunctionValuePostprocessor```). That would be a more general solution, which I would prefer to making this class more complicated.

**Comment by permcody** [comment]
I suggest we merge this contribution from John. We can modify it in a
subsequent PR to support the "old parsed postprocessor" capability and user
defined norm. In general it's good to keep the barrier low for external
contributions.

**Comment by dschwen** [comment]
Yeah, I was not suggesting to put all that in this PR. I was just wondering if the norm could be fixed. But I agree that we should keep the bar low. Maybe that can be @mangerij's second PR :-)

**Pull request merged**
