### PR TITLE
Better Nemesis repartitioning test

### PR DESCRIPTION
**Pull request by roystgnr**
This should provide better coverage of the new capabilities discussed in #5563.

It's already been invaluable in bug hunting; it turned out that there were a whole class of bugs related to repartitioning a Nemesis file which just didn't get triggered by repartitioning a from-scratch ParallelMesh.

This PR ought to _fail_ with the first MooseBuild, then work after we merge https://github.com/libMesh/libmesh/pull/625 and update the libMesh module in a subsequent commit here.

### CODE REVIEW

**Comment by roystgnr** [comment]
Gah; accidentally referenced the previous PR rather than the underlying issue...

**Comment by roystgnr** [comment]
Editing the initial PR message to make the ticket reference is too late, huh?

**Comment by friedmud** [comment]
It's not too late.  You can reopen this PR.

You need to add the ticket number to your COMMIT MESSAGE.  Do it with rebase and force push it back on this branch and it will update this PR (reopen the PR first)

**Comment by friedmud** [comment]
Nevermind - I see you already opened another one...

**Pull request closed without merging**
