### PR TITLE
Add postprocessor to scale variables in PointSamplerBase

### LINKED ISSUE #12314: Scale LineValueSampler with a postprocessor
## Rationale

In our application, the fluxes are typically scaled way down (or else the solvers do not perform correctly). Yet, most users desire to scale them back when using postprocessors to be able to compare more easily with other codes. In particular, we recently received the request to be able to add a postprocessor as an input parameter in `LineValueSampler`.

## Description

Unless I am being oblivious to some technical difficulties, it seems that it would be fairly straightforward to add a `PostprocessorName` to `LineValueSampler`.

## Impact

This would be a lot more convenient for users than creating auxvariables to hold the unscaled variables.

### PR DESCRIPTION
**Pull request by vincentlaboure**
Closes #12314

### CODE REVIEW

**Review by permcody — CHANGES_REQUESTED** [review]
This looks mostly ok. The one problem with this scaling factor is a mismatch in execution. If you execute the line_value_sampler at a different time than the Postprocessor you our coupling in, the value could be lagged. The bigger issue is if you execute at a initial but fail to make the dependent Postprocessor execute there. This is nothing new, just pointing it out.

I'd prefer if you leave the original test alone though and create a different test for the scaling parameter. It might be unclear to somebody looking at the test that this one test is demonstrating the usage and the scaling all in one.

**Comment by vincentlaboure** [comment]
Sounds good, will do!

**Comment by vincentlaboure** [comment]
Based on the CIVET error, it looks like I need to add the `requirement`, `design` and `issues` entries for the `tests` file. While this is easy enough for the newly created test, I am not sure what to put for the already existing ones (in particular for the issue number). Is there an easy way to figure these out?

In addition, what does `group='requirements'` mean?

**Comment by permcody** [comment]
The issue number is typically something relevant to the test or the
capability so that we can trace back. If it's old enough, there may not be
anything at all in which case, I think it can either be left blank or left
out? Unsure about that.

Ignore the group='requirements' - That will go away.

**Comment by vincentlaboure** [comment]
It looks like it can be left blank. Looking at the history, I was able to find some issue numbers that seem relevant.

**Review by permcody — APPROVED** [review]
Thanks for jumping through all of those hoops.

**Pull request merged**
