### PR TITLE
Avoiding race conditions

### PR DESCRIPTION
**Pull request by permcody**
refs #13535

### CODE REVIEW

**Comment by permcody** [comment]
@lindsayad - I'm starting this. I'll hopefully get back to it in the morning. We can always revert the checks if we need to. It looks like we have lots of potential issues so it really would be nice to get this in.

**Comment by lindsayad** [comment]
Lol I just submitted #14733. So you can do command line arguments for subapps with `:`?

**Comment by lindsayad** [comment]
yea that XFEM failure is wack

**Comment by lindsayad** [comment]
Is this going to be our strategy moving forward, invalidating until they pass? 🤣

**Comment by permcody** [comment]
@lindsayad - I believe that Kyle correctly identified the issue here in #14732.

**Comment by permcody** [comment]
Sporadic failures should be fixed by #14737

**Comment by permcody** [comment]
OK - so the XFEM failure is indeed explained by #14732.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
