### PR TITLE
Update to libMesh master

### PR DESCRIPTION
**Pull request by roystgnr**
This includes fixes for compilation failures on Windows and leaked file
descriptors in fparser JIT, reduced_basis I/O tweaks, support for
disabling ImplicitSystem matrix construction via
set_basic_system_only()...

But most pressing, it includes fixes for CheckpointIO on refined
distributed meshes, which is blocking resolution of #8410 and merging
of #9631.

### CODE REVIEW

**Comment by roystgnr** [comment]
One failure starting at -p 5, but that's a huge improvement over [50 failures starting at -p 2](https://www.moosebuild.org/job/106309/) so I'd say this is good to merge.

**Comment by permcody** [comment]
Both @jwpeterson and @aeslaughter are in Cubit training (yesterday and today). @friedmud just arrived. We're going to talk over whether we want a libMesh update going in right now since we'll likely have more early next week during the tiger team. Thanks for all this work - it's looking really good!

**Comment by jessecarterMOOSE** [comment]
Sounds good. I can roll with the latest libmesh master manually for now. Good luck with the tiger team. Sounds like a blast.

**Comment by mangerij** [comment]
Any list of things you are planning on tackling during the tiger team? Is ghosting or strain periodic BCs on that list?

**Comment by dschwen** [comment]
I have a better approach for strain periodicity in the works. May work on
it next week.

**Comment by permcody** [comment]
@jessecarterMOOSE - Do you want to be a part of the Tiger team next year?

**Comment by jessecarterMOOSE** [comment]
Sure! Though I'm not sure how much good I'll be!

**Comment by roystgnr** [comment]
> we'll likely have more early next week during the tiger team

Yup.  One more commit incoming; doing a quick+efficient fix for #9626 required another mesh_base.h method.

**Comment by roystgnr** [comment]
Wait, *what*?  How do two commits, each of which only includes a submodule update, end up triggering a complaint about tutorials/darcy_thermo_mech/ files?

**Comment by roystgnr** [comment]
Trying a rebase on origin/devel

**Comment by roystgnr** [comment]
Let's hold off until https://github.com/libMesh/libmesh/pull/1405 makes into libMesh, then bring that in here, then review and merge.

That libMesh PR, plus an upcoming MOOSE PR which will use it, plus my other outstanding MOOSE PR which depends on the libMesh update, should be the last changes necessary before we get clean test suite sweeps up to at least 16 processors with or without --distributed-mesh, --recover, or both.

**Comment by roystgnr** [comment]
Last update added, and rebased for clarity.

**Comment by jwpeterson** [comment]
@roystgnr please include this summary of changes in your commit message before it goes in.
```
Summary of changes in this update:
* Avoid redundant init of old(er) Transient vectors
* Clean up system vector and matrix initialization
* Fparser/JIT: Close file descriptors returned by mkstemp
* Add support for compiling on Windows with MSys2
* More robust extra_ghost_elem/remote_elem link handling
* Minor fixes for XDR-disabled builds (Mira)
* Fix --enable-all-static builds (Mira)
* Add MeshBase::is_serial_on_zero()
* Fix bug in Exodus writer when LIBMESH_ENABLE_INFINITE_ELEMENTS 
* Add DofMap::dof_owner() search and unit tests
* Fix -fsanitize builds.
```

**Comment by roystgnr** [comment]
There's four separate commits now.  Should I split that summary into the appropriate entries for each?  I could squash them all into one, but there really is a unique moose-relevant reason for each separate stage of the update.

**Comment by jwpeterson** [comment]
I'd just amend the commit message of the most recent one. It's useful for quickly perusing the history of the libmesh submodule; doesn't have to be completely perfect.

**Comment by roystgnr** [comment]
Got it.  I added a couple line breaks in between the lines corresponding to each commit.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
