### PR TITLE
Remove deprecated Moab adapters

### LINKED ISSUE #3525: Remove MOAB Stuff From MOOSE
@sslattery informed me that DTK no longer needs MOAB linkages and that we can remove any of that kind of thing from MOOSE.

Considering that no one has used the MOAB transfer capabilities in MOOSE I'm just going to go ahead and remove them for now.  We can always resurrect them later if needed.

### PR DESCRIPTION
**Pull request by rppawlo**
Remove deprecated moab adapters.  The removed code relied on the fact that DTK had a required dependence on moab.  This dependency has been removed for DTK2 and the moab adapters no longer compile with updated DTK2 library. This comit removes the deprecated code so that MOOSE can build against DTK2.

Closes  #3525

### CODE REVIEW

**Comment by andrsd** [comment]
@rppawlo Is there a simple way to detect the older version of DTK? If so, we could tell people "hey, go use DTK2...".

**Comment by permcody** [comment]
@rppawlo - Thanks for the PR. Jason is working on getting DTK up and running on the test machines so we can test this PR against that machine.

**Comment by rppawlo** [comment]
@andrsd - DTK2 is backwards compatible with original DTK so users should be able to use either one. DTK 2 was broken into subpackages so the directory structure has changed and you can key off of that.  libmesh accepted a pull request from me earlier this week that updated the trilinos.m4 file to search for the new directory structure if the files were not found in the old directory structure. You can use that code for a search to let users know which version is being used.  Below is the code in trilinos.m4.  The first three paths checked are the old DTK paths and the last two paths look for separate files in the new dtk.

       AC_CHECK_HEADER([$withtrilinosdir/include/DataTransferKit_config.hpp],
                       [enabledtk=yes],
                       [AC_CHECK_HEADER([$withtrilinosdir/DataTransferKit_config.hpp],
                                        [enabledtk=yes],
                                        [AC_CHECK_HEADER([$withtrilinosdir/DataTransferKit/src/DataTransferKit_config.hpp],
                                                         [enabledtk=yes],
                                                         [AC_CHECK_HEADER([$withtrilinosdir/DataTransferKit/packages/Utils/src/DataTransferKitUtils_config.hpp],
                                                                          [enabledtk=yes],
                                                         		  [AC_CHECK_HEADER([$withtrilinosdir/include/DataTransferKitUtils_config.hpp],
										[enabledtk=yes],
                                                                          	[enabledtk=no])])])])])

**Comment by rppawlo** [comment]
@permcody - Thanks Cody!  Note that the current DTKInterpolationAdapter is broke as we discussed yesterday, so this request won't compile until the call to Transfer::find_sys() in DTKIntrepolationAdapter is updated.

**Comment by jwpeterson** [comment]
Once we get the build boxes updated with the new DTK (@rppawlo DTK does require Trilinos as well, correct?) this branch will need to be augmented with a libmesh submodule update to bring in these latest changes to trilinos.m4.  We can probably handle this on our end.

**Comment by rppawlo** [comment]
@jwpeterson - yes.  This pull request should work with old DTK/Trilinos - all it does is remove the deprecated moab code.  If you want to move to new DTK, then you will need the latest Trilinos release as well.  The new DTK is in a new github repo:

git clone git@github.com:ORNL-CEES/DataTransferKit.git

The new DTK is divided into subpackages, so you will need to enable the ClassicDTKAdapters subpackage (and I believe the IntrepidAdapters as well) in DTK to get the backwards compatible interfaces.  You will also need to update libmesh to get the changes to the trilinos.m4 macro to account for the new directory structure so that libmesh finds Trilinos/Tpetra and DTK correctly (Tpetra directories were changed as well for subpackages and had to be updated).

**Comment by rppawlo** [comment]
Another possible complication to updating - with the release of Trilinos 12.0, Trilinos now requires c++11.  So you will have to enable that for libmesh builds with DTK2. The update_and rebuild_libmesh.sh script in moose is hard coded to disable c++11.

**Comment by jwpeterson** [comment]
> with the release of Trilinos 12.0, Trilinos now requires c++11.

Thanks for letting us know.  We might need to handle this by making a separate CI target for Trilinos that enables C++11 in libmesh, etc.

**Comment by jwpeterson** [comment]
@rppawlo, it looks like DTK master (I tried commit 60986480914fda in the https://github.com/ORNL-CEES/DataTransferKit.git repo) requires C++11:

The file packages/Utils/src/DTK_PredicateComposition.hpp has an alias declaration:
```
using Predicate = std::function<bool(T)>;
```

Is there an older version of DTK we can use with Trilinos 11.14.3 that *doesn't* require C++11?

**Comment by rppawlo** [comment]
@jwpeterson, I don't think that is possible without falling back on the original DTK that you are already using.  To get the backwards compatibility capability working, commits as recently as last week are needed. Adding @sslattery to the conversation. I've noticed that the update_and_rebuild_libmesh.sh script turns off c++11 in libmesh.  Is there an issue with enabling it for moose builds?

**Comment by permcody** [comment]
The reason we disable it is because we don't want people to unintentionally sneak c++11 standards into the code. We can catch these things if we explicitly disable it on our test systems.

Since the new standard is required for DTK we'll set up a separate test system just for those builds. That's a reasonable intermediate step until we decide to move to c++11 in our framework.

**Comment by jwpeterson** [comment]
> I've noticed that the update_and_rebuild_libmesh.sh script turns off c++11 in libmesh. Is there an issue with enabling it for moose builds?

We certainly *can* flip the switch, however when we do so it's got to be a decision that's coordinated with our users and is well-documented, etc.

**Comment by rppawlo** [comment]
Ah.  I see.  The reason I asked is that in casl we moved to c++11 about 6 months ago, so internally we started building both libmesh and moose with c++11 enabled, but I was worried there might be an issue.

**Comment by bartlettroscoe** [comment]
Just my two cents but projects using C++ libraries are not going to be able to hold off turning on C++11 for too much longer.  We pushed back as long as we could in CASL.

**Comment by permcody** [comment]
I've confirmed that this works with the latest (necessary) software stack with DTK enabled in MOOSE. We still need to get this all out on our Linux test machine so we can maintain the DTK enabled stack without regressions. Merging...

**Comment by friedmud** [comment]
To be clear: we need to test both with and without DTK... to make sure DTK
dependencies are properly safeguarded

**Comment by bartlettroscoe** [comment]
And so starts the combinatorial explosion of testing with optional dependencies turned on and off :-)

**Comment by friedmud** [comment]
The only combinatorial dependencies are DTK.  We can remove that if you like... or we can do what we have been doing... just not testing DTK at all ;-)

**Comment by bartlettroscoe** [comment]
DTK can't be MOOSE's only optional dependency.  ParMETIS must also be an optional dependency.  Otherwise, we could not ship VERA with MOOSE + ParMETIS out to industrial customers.  For a complex project involved in research, I don't see how you can get away from optional dependencies.

**Comment by permcody** [comment]
Most of the other optional dependencies are distributed and maintained with
libMesh so they are easy to handle and are generally always on. The only
other exception I can think of is VTK.

**Comment by friedmud** [comment]
Yep - we work really hard to keep down external dependencies.

Currently... our only dependency that doesn't come with MOOSE (like in the repository) is PETSc... and it's not optional ;-)

Like Cody says the only optional dependencies I can think of are VTK and DTK.

I guess now that #5717 is merged we can technically say TBB as well.  But I hope that's only temporary until we remove the TBB specific code from there and use our generic threading interfaces.

**Comment by bartlettroscoe** [comment]
But PETSc itself has a bunch of optional dependencies, like ParMETIS and some people are running MOOSE-based applications with problems that require (or at least they are using) ParMETIS.  So the issue is not really direct optional dependencies but all optional dependencies which include direct and indirect dependencies.  So just with just the optional (direct or indirect) dependencies DTK, VTK, and ParMETIS, that gives 8 different permutations of MOOSE and MOOSE APPS that could be built.  So if you tested just these three optional enables, you would have to test 8 times the number of builds to be safe.

As soon as you allow dependencies to be optional (direct or indirect), you open yourself up for a testing problem.  That is the only point I was trying to make.

For Trilinos, there are hundreds of thousands of possible permutations of possible enables/disables of optional packages and TPLs (we have not computed all of the possible permutation but we could given the graph info we have but it would be a complex graph-based calculation).  Our policy is that we only test with everything turned on by default on all platforms and then people can always get things working by enabling everything.  Then, some customers that want/require less we or they have specific targeted testing for just the permutations of enables/disables used by that application.  CASL VERA uses a small part of Trilinos for a targeted permutation of enables/disables so we provide that testing for ourselves.  Of course TriBITS also helps in this quite a bit but does not magically test things and this gets very complex quickly.

The application to MOOSE is that if in doubt, test with everything enabled first and people can always just enable more to get it working.  Then, with extra testing resources, you can test other important permutations of enables/disables (e.g. DTK off).

**Pull request merged**
