### PR TITLE
ZeroInterface refactoring

### LINKED ISSUE #10630: Refactor ZeroInterface
## Rationale

`ZeroInterface` provides zeroes into our systems. There is a problem, though. The interface contains quantities that are indexed into with q-point index and quantities that are not indexed into at all (like zero_real). Most of the time these quantities are used in coupling values, which with the default coupling is less used.  Bringing the former quantities into systems that do not have q-points is not logical and could be misused (it did not happen, yet, so this is theoretical, but possible).

## Description

The refactor would split the ZeroInterface and move the q-point based quantities into `Coupleable` interface - this is the interface for q-point quantities. And the scalar quantities would reside in `ScalarCoupleable`.

## Impact

Increasing consistency, no impact on any apps, fixing design.

### PR DESCRIPTION
**Pull request by andrsd**
Refactoring ZeroInterface
    
  1. The interface is removed.
  2. q-point based quantities are moved into `Coupleable`
  3. scalar quantities are moved into `ScalarCoupleable`
    
Closes #10630

### CODE REVIEW

**Review by permcody — APPROVED** [review]
Looks like it's only failing Relap-7 and downstream dependencies. Merge when you are prepared to patch those applications.

**Comment by dschwen** [comment]
@andrsd, this break a WIP scalar kernel that couples optionally to other scalar variables. I assign `_zero` to the `const VariableValue &` if the parameter is not provided. `_zero` is now only available through `Coupleable` which my class does not inherit form (and conceptually should not need to inherit from).

**Comment by andrsd** [comment]
Yes, so that was exactly the purpose of this PR. The problem with using `_zero` is that it would have a wrong size (number of q-points), while it needs to have number of components.

**Comment by andrsd** [comment]
In case somebody finds this later, #10649 is introducing `_scalar_zero` in `ScalarCoupleable` which should be used instead of `_zero` when optionally coupling a scalar variable and one needs to set it to zero.

**Pull request merged**
