### PR TITLE
Increase the sync time tolerance in Transient executioner

### PR DESCRIPTION
**Pull request by YaqiWang**
This will hopefully reduce the chance of getting tiny time step size due to floating point arithmetic.

Refs #5590.

### CODE REVIEW

**Comment by YaqiWang** [comment]
... Apparently people are not careful on considering a gold file. @permcody I will have to wait you say yes before I send in patches.

**Comment by YaqiWang** [comment]
I will fix those failing tests. They need regolding anyway. Tag @permcody

**Comment by YaqiWang** [comment]
BISON can probably just regolded to fix those exodiff.

**Comment by YaqiWang** [comment]
@permcody I think this is ready for review and merge. BISON patch has been sent in. Thanks.

**Comment by YaqiWang** [comment]
@permcody any comments on this?

**Comment by permcody** [comment]
I'm fine with it, like I already said, but BISON needs to be fixed up and that can happen *before* this gets merged.

**Comment by permcody** [comment]
@YaqiWang - Have you had a chance to take any further action on working with BISON to fix up the tests?

**Comment by YaqiWang** [comment]
No. I will need help to patch BISON. I guess I cannot fix one of the tests because I am using my own PETSc which is very recent. This is good fix overall. Maybe I should let you guys take over.

**Comment by permcody** [comment]
Our team is heavily overloaded right now. I'm not sure anyone can get to this soon.

**Comment by YaqiWang** [comment]
Feel free to close it then. It is not critical to us because we know we need to set this parameter carefully.

**Comment by permcody** [comment]
Closing due to inactivity (>30 days).

**Pull request closed without merging**
