### PR TITLE
August news

### PR DESCRIPTION
**Pull request by aeslaughter**
@idaholab/moose-team, please add July work

### CODE REVIEW

**Comment by YaqiWang** [comment]
Will @lindsayad fix the addVariable deprecation in applications?

**Comment by lindsayad** [comment]
Yes in time I will fix the deprecation as it is ever the MOOSE developer's job to work all the way up and down the stack 😄 (@fdkong )

**Comment by lindsayad** [comment]
Next time I probably won't add deprecation messages and maintain backwards compatability since I'll just have to go fix the apps anyway

**Comment by lindsayad** [comment]
> Will @lindsayad fix the addVariable deprecation in applications?

Yes, unless you get to it first.

**Comment by permcody** [comment]
Pretty sad letter... Oh well!

**Review by permcody — APPROVED** [review]

**Pull request merged**
