### PR TITLE
Refactoring performance logging

### PR DESCRIPTION
**Pull request by permcody**
refs #6300 

This first cut at this does several things. First, it does away with the setup log. I really don't think it's useful to use two logs. If we really want the ability to print the perf_log early we can simply print the contents of the regular log early. In fact this might be a useful feature. I often run long simulations that I kill before they reach the end so I don't get a perf_log. It would be handy to have a feature for printing the perf_log every <n> iterations. I'll open a ticket for that but the setup log should be killed.

Next I try to categorize the events into fewer main categories: "Setup and Execution". Almost every operation should fit into one of those two general categories. There's also an "Application" category which currently has a single entry called "Full Runtime". This should basically capture nearly all of the runtime of the simulation as it completely wraps the main entry call `MooseApp::run()`. There will be other categories like "Utility" and maybe even named objects "GrainTracker" for breaking down the runtime of heavy objects. The former "solve" event is still there and you can see that even for simple diffusion it doesn't even capture the full runtime. It's time to be honest with ourselves about the full cost of running MOOSE. It's how we'll get better.

Here is a sample log from running simple diffusion with four refinements:

```
 -------------------------------------------------------------------------------------------------------------------------
| Moose Test Performance: Alive time=21.6534, Active time=21.5612                                                         |
 -------------------------------------------------------------------------------------------------------------------------
| Event                                      nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                                       w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|-------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                         |
|                                                                                                                         |
| Application                                                                                                             |
|   Full Runtime                             1          0.2820      0.282008    21.5612     21.561228   1.31     100.00   |
|                                                                                                                         |
| Execution                                                                                                               |
|   computeAuxiliaryKernels()                2          0.0000      0.000002    0.0000      0.000002    0.00     0.00     |
|   computeControls()                        2          0.0000      0.000004    0.0000      0.000004    0.00     0.00     |
|   computeDiracContributions()              18         0.0007      0.000037    0.0007      0.000037    0.00     0.00     |
|   computeUserObjects()                     4          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|   compute_jacobian()                       2          2.3852      1.192620    2.3853      1.192627    11.06    11.06    |
|   compute_residual()                       16         14.9632     0.935203    14.9639     0.935245    69.40    69.40    |
|   solve()                                  1          0.0907      0.090683    17.4399     17.439857   0.42     80.89    |
|                                                                                                                         |
| Output                                                                                                                  |
|   Exodus::output()                         2          0.6537      0.326832    0.6537      0.326832    3.03     3.03     |
|                                                                                                                         |
| Setup                                                                                                                   |
|   Application Setup                        1          1.0670      1.066983    2.3424      2.342363    4.95     10.86    |
|   FEProblem::init::meshChanged()           1          0.0983      0.098294    0.0983      0.098294    0.46     0.46     |
|   Initial updateActiveSemiLocalNodeRange() 1          0.0270      0.027044    0.0270      0.027044    0.13     0.13     |
|   Initial updateGeomSearch()               2          0.0000      0.000005    0.0000      0.000005    0.00     0.00     |
|   NonlinearSystem::update()                1          0.0001      0.000085    0.0001      0.000085    0.00     0.00     |
|   eq.init()                                1          1.1770      1.177001    1.1770      1.177001    5.46     5.46     |
|   execMultiApps()                          1          0.0000      0.000013    0.0000      0.000013    0.00     0.00     |
|   execTransfers()                          1          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|   initial adaptivity                       1          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|   initialSetup()                           1          0.1354      0.135360    0.8433      0.843308    0.63     3.91     |
|   reinit() after updateGeomSearch()        1          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|                                                                                                                         |
| Utility                                                                                                                 |
|   projectSolution()                        1          0.6809      0.680868    0.6809      0.680868    3.16     3.16     |
 -------------------------------------------------------------------------------------------------------------------------
| Totals:                                    61         21.5612                                         100.00            |
 -------------------------------------------------------------------------------------------------------------------------
```

@idaholab/moose-developers, I'd like some feed back on this.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Is it possible to have a row for computeMaterials?  I suspect that the bulk of my calculations (over and above PETSc) are Material calculations rather than Kernel calculations, and it would be nice to see that.

**Comment by permcody** [comment]
Yes, that can be easily added

**Comment by friedmud** [comment]
Actually - it can't. Materials are executed inside of threaded regions and
the perf log is not thread safe.

**Comment by friedmud** [comment]
As for being "honest" I don't know what you're talking about.  simple_diffusion is actually a worst case scenario... it's tiny and the solve is instantaneous.  Even with it the solve is still 80% of the total time which is great.  Any real solve will be nearly all solve().

What exactly are you referring to?

**Comment by roystgnr** [comment]
Hmmm... should we make the perf log thread-safe?  Perhaps at least as an option?  The trouble is that the necessary locking would make the Heisenberg problem even worse, but I'm not sure a priori how much worse it would be.

**Comment by permcody** [comment]
Haha! Right and the current perf logs reflect that but they can miss big pieces. I'd like to capture all of the time spent in a simulation. So there are several big pieces that we miss right now: First anything that happens outside of solve which includes several explicit calculations such as post processing, aux kernels, indicators, markers, mesh refinement and solution projection (this last one can get very expensive). Those pieces can easily add up to a substantial cost of the total runtime for several reasons. For one thing these between solve pieces are often serial, (just normal logic flow) that simply cannot be accelerated as we really grow the problem size. This is where my "honest" comment comes from. It's easy to show that the solve in MOOSE is scalable but other pieces may not be. 

We also miss the application of the preconditioner completely in the active time of our log. Right now I don't have a good plan for capturing that in our log directly but at least it'll be timed as part of the whole. At least this refactor will show us where some of time is being spent.

Finally I do have some greedy reasons for this. I need a better baseline for the grain tracker work which as you know falls into one of these between solves categories. While we do have logs for "compute user objects" now, I need a better understand of what else is happening in-between solves. I've already learned just how expensive the mesh refinement pieces are by adding these new logs which is making me think about tradeoffs in refinement strategies.

Just so I have some hard evidence to support this. I want you to see how worthless the current logs are for a real grain growth simulation. I can't do anything with this log as it captures only ~20% of the runtime. 

```
 ------------------------------------------------------------------------------------------------------------
| PhaseField Performance: Alive time=634.662, Active time=136.082                                            |
 ------------------------------------------------------------------------------------------------------------
| Event                         nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                          w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|------------------------------------------------------------------------------------------------------------|
|                                                                                                            |
|                                                                                                            |
| Exodus                                                                                                     |
|   output()                    2          9.0521      4.526067    9.0521      4.526067    6.65     6.65     |
|                                                                                                            |
| FeatureFloodCount                                                                                          |
|   communicate ghost elements  2          0.3331      0.166527    0.3331      0.166527    0.24     0.24     |
|   iterate ghost elements      2          53.6604     26.830215   53.6604     26.830215   39.43    39.43    |
|   mergeSets()                 2          0.0740      0.036981    0.0740      0.036981    0.05     0.05     |
|                                                                                                            |
| GrainTracker                                                                                               |
|   calculateBubbleVolumes()    2          0.1992      0.099594    0.1992      0.099594    0.15     0.15     |
|   finalize()                  2          1.0919      0.545971    1.4547      0.727351    0.80     1.07     |
|   initialize()                2          2.4027      1.201335    56.3962     28.198077   1.77     41.44    |
|   remapGrains()               2          0.0838      0.041887    0.0838      0.041887    0.06     0.06     |
|   trackGrains()               2          0.0058      0.002917    0.0058      0.002917    0.00     0.00     |
|                                                                                                            |
| Setup                                                                                                      |
|   computeAuxiliaryKernels()   2          0.3687      0.184351    0.5001      0.250034    0.27     0.37     |
|   computeControls()           2          0.0000      0.000002    0.0000      0.000002    0.00     0.00     |
|   computeUserObjects()        4          3.9167      0.979178    32.6122     8.153054    2.88     23.97    |
|                                                                                                            |
| Solve                                                                                                      |
|   ComputeResidualThread       57         23.6244     0.414464    23.6244     0.414464    17.36    17.36    |
|   computeDiracContributions() 62         0.0001      0.000002    0.0001      0.000002    0.00     0.00     |
|   compute_jacobian()          5          8.0277      1.605545    8.0277      1.605546    5.90     5.90     |
|   compute_residual()          57         6.2498      0.109645    31.5092     0.552793    4.59     23.15    |
|   residual.close3()           57         1.6059      0.028174    1.6059      0.028174    1.18     1.18     |
|   residual.close4()           57         0.0289      0.000507    0.0289      0.000507    0.02     0.02     |
|   solve()                     1          24.8195     24.819539   64.7071     64.707136   18.24    47.55    |
|   update_aux_vars_elemental() 65         0.2283      0.003512    0.2283      0.003512    0.17     0.17     |
|   update_aux_vars_nodal()     65         0.1749      0.002690    0.1749      0.002690    0.13     0.13     |
|   update_aux_vars_nodal_bcs() 65         0.1338      0.002058    0.1338      0.002058    0.10     0.10     |
 ------------------------------------------------------------------------------------------------------------
| Totals:                       517        136.0817                                        100.00            |
 ------------------------------------------------------------------------------------------------------------
```

**Comment by permcody** [comment]
@roystgnr - If not thread-safe, how about a compile time option where we can enable additional perf-log timers when all thread models are disabled:

```
#ifdef LIBMESH_NO_THREADS 
perflog.push("Some threaded Region", "Solve");
#endif
```

By thread-safe you aren't talking about locking right? Maybe using the IDs we have to accumulate times in a non-overlapping way? We'd still need some sort of concurrent structure, I suppose a simple presized vector should work.

**Comment by roystgnr** [comment]
Right, it would certainly be worse than just locking, because of the way we handle nested logging.  We'd need to create a new PerfLog map at thread split time (or lazily, at the first new log event while in threads) and then merge it into the real PerfLog when the threads merge.

**Comment by permcody** [comment]
That would be cool but I'd be happy with the compile time define for now. It would give us a handle on some of our more time sensitive sections without a lot of fuss to make it happen.

**Comment by jwpeterson** [comment]
This looks fine to me and honestly better than it looked before.

**Comment by aeslaughter** [comment]
:+1: for more accurate log

**Comment by permcody** [comment]
For those following this thread I finally got a chance to run another 2D grain-growth simulation with the new logging and there's still a lot of interesting observations here:

```
Framework Information:
MOOSE version:           git commit 3744a9a on 2016-02-09
PETSc Version:           3.6.0
Current Time:            Wed Feb 10 07:23:34 2016
Executable Timestamp:    Tue Feb  9 14:19:30 2016

Parallelism:
  Num Processors:          120
  Num Threads:             1

Mesh: 
  Distribution:            serial
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   
    Total:                 519841
    Local:                 4479
  Elems:                   
    Total:                 680400
    Local:                 5729
  Num Subdomains:          1
  Num Partitions:          120
  Partitioner:             metis

Nonlinear System:
  Num DOFs:                10396820
  Num Local DOFs:          89580
  Variables:               { "gr0" "gr1" "gr2" "gr3" "gr4" "gr5" "gr6" "gr7" "gr8" "gr9" "gr10" "gr11" 
                             "gr12" "gr13" "gr14" "gr15" "gr16" "gr17" "gr18" "gr19" } 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 

Auxiliary System:
  Num DOFs:                2075041
  Num Local DOFs:          17415
  Variables:               "bnds" { "unique_grains" "var_indices" "T" } 
  Finite Element Types:    "LAGRANGE" "MONOMIAL" 
  Approximation Orders:    "FIRST" "CONSTANT" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             IterationAdaptiveDT
  Solver Mode:             Preconditioned JFNK
  Preconditioner:          hypre boomeramg 
```



 -------------------------------------------------------------------------------------------------------------------------
| PhaseField Performance: Alive time=3595.19, Active time=3592.51                                                         |
 -------------------------------------------------------------------------------------------------------------------------
| Event                                      nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                                       w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|-------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                         |
|                                                                                                                         |
| Application                                                                                                             |
|   Full Runtime                             1          2378.0180   2378.017967 3592.5083   3592.508285 66.19    100.00   |
|                                                                                                                         |
| Execution                                                                                                               |
|   computeAuxiliaryKernels()                28         1.0301      0.036789    5.2671      0.188111    0.03     0.15     |
|   computeControls()                        28         0.0000      0.000001    0.0000      0.000001    0.00     0.00     |
|   computeDiracContributions()              1272       23.5690     0.018529    23.5690     0.018529    0.66     0.66     |
|   computeUserObjects()                     56         119.5626    2.135047    157.7652    2.817235    3.33     4.39     |
|   compute_jacobian()                       77         43.0888     0.559595    43.0889     0.559596    1.20     1.20     |
|   compute_residual()                       1195       187.8019    0.157156    211.3712    0.176880    5.23     5.88     |
|   solve()                                  14         299.4584    21.389889   558.6242    39.901729   8.34     15.55    |
|   update_aux_vars_elemental()              1301       3.2813      0.002522    3.2813      0.002522    0.09     0.09     |
|   update_aux_vars_nodal()                  1301       5.3892      0.004142    5.3892      0.004142    0.15     0.15     |
|   update_aux_vars_nodal_bcs()              1301       0.3255      0.000250    0.3255      0.000250    0.01     0.01     |
|                                                                                                                         |
| FeatureFloodCount                                                                                                       |
|   mergeSets()                              15         0.4710      0.031401    0.4710      0.031401    0.01     0.01     |
|                                                                                                                         |
| GrainTracker                                                                                                            |
|   calculateBubbleVolumes()                 15         4.7120      0.314133    4.7120      0.314133    0.13     0.13     |
|   finalize()                               15         27.7370     1.849135    34.1140     2.274264    0.77     0.95     |
|   remapGrains()                            15         5.0978      0.339850    5.0978      0.339850    0.14     0.14     |
|   trackGrains()                            15         0.8081      0.053876    0.8081      0.053876    0.02     0.02     |
|                                                                                                                         |
| Output                                                                                                                  |
|   CSV::output()                            30         0.0066      0.000220    0.0066      0.000220    0.00     0.00     |
|   Exodus::output()                         15         61.9319     4.128795    61.9319     4.128795    1.72     1.72     |
|                                                                                                                         |
| Setup                                                                                                                   |
|   Application Setup                        1          10.4897     10.489655   23.4712     23.471196   0.29     0.65     |
|   FEProblem::init::meshChanged()           1          0.8842      0.884198    0.8842      0.884198    0.02     0.02     |
|   Initial updateActiveSemiLocalNodeRange() 1          0.0058      0.005780    0.0058      0.005780    0.00     0.00     |
|   Initial updateGeomSearch()               2          0.0000      0.000001    0.0000      0.000001    0.00     0.00     |
|   NonlinearSystem::update()                1          0.0412      0.041231    0.0412      0.041231    0.00     0.00     |
|   eq.init()                                1          12.0561     12.056111   12.0561     12.056111   0.34     0.34     |
|   execMultiApps()                          1          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|   execTransfers()                          1          0.0000      0.000009    0.0000      0.000009    0.00     0.00     |
|   initial adaptivity                       1          345.4366    345.436558  392.0952    392.095231  9.62     10.91    |
|   initialSetup()                           1          5.2772      5.277198    407.4240    407.424019  0.15     11.34    |
|   reinit() after updateGeomSearch()        1          0.0020      0.001987    0.0020      0.001987    0.00     0.00     |
|                                                                                                                         |
| Utility                                                                                                                 |
|   projectSolution()                        5          56.0247     11.204937   56.0247     11.204937   1.56     1.56     |
 -------------------------------------------------------------------------------------------------------------------------
| Totals:                                    6711       3592.5067                                       100.00            |
 -------------------------------------------------------------------------------------------------------------------------
```

As you can see this is a good medium sized run. It has adaptivity and hovers between 100K-200K active elements throughout the life of the simulation. With 20 order parameters that gives us a few million degrees of freedom spread out among 120 procs. First thing to notice is that the top line is capturing essentially all of the runtime which is good. However if you look at the "with" versus "without sub" calls we are only instrumenting 66% of the code even after the refactor. Only 15% of the runtime is in `solve()` with 5% of that in `compute_residual()` - wow!  I'm not sure right now where all of the remaining time is going but we are missing a few very large pieces.

**Comment by permcody** [comment]
Wait a minute - I don't see enough projection calls. We are missing all of the adaptivity work between steps! That's probably most of it, and boy it's expensive!

**Pull request merged**
