### PR TITLE
Replace deprecated Tensor Mechanics materials

### PR DESCRIPTION
**Pull request by dschwen**
Replaces use of `LinearElasticMaterial` and `SimpleEigenStrainMaterial`.

Refs #6125

### CODE REVIEW

**Comment by dschwen** [comment]
@aeslaughter check out how 3932873 fails the test and 558bfb9 passes. It looks like your changes to block restriction now make specifying the `block = 0` (see #6697) largely unnecessary if 0 tis the only block in your simulation. **However**, there seem to be odd exceptions.

**Comment by aeslaughter** [comment]
Good timing, I just attempted to show the class what error message you get when your forget "block=0", but it now works. I will add this to the list of Material related changes that I need to work on.

**Comment by permcody** [comment]
Umm, I'm not so sure this is ready to merge. We really should figure out an understand why this isn't a 100% universal. Also the fact that this has turned into an unintentional feature makes me a little uneasy. Let's have @aeslaughter take a closer look at this before we merge.

**Comment by dschwen** [comment]
I can take b988cde and 558bfb9 out again. Then the `block = 0` issue would have nothing to do with this PR.

**Comment by permcody** [comment]
OK - let's do that for now until we understand what's going on here.

**Comment by dschwen** [comment]
One test failed with a timeout. This seems unrelated.

**Pull request merged**
