### PR TITLE
Re-factor restart test to be what it is (a recover test)

### LINKED ISSUE #10079: heat_condution/test/tests/restart is actually a recover test
## Rationale

The "restart" test in heat_conduction module is a recover test and it is generating the gold.

## Description

The tests should be renamed and the gold should be a proper gold.

## Impact

None, just making the test more consistent.

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #10079)

### CODE REVIEW

**Comment by aeslaughter** [comment]
In the previous version of this test, step one would compute the gold for steps 2/3. I tried to re-factor this so that step 1 would compare to the same gold as 2/3. However, the test isn't robust enough to give the same results across systems.

**Comment by aeslaughter** [comment]
I don't know or care enough about this test to figure out why it is so terrible.

**Comment by permcody** [comment]
Tag @milljm - Was this the test giving you grief?

**Comment by aeslaughter** [comment]
No, it is just not a good test. Currently, step 1 creates the gold file that the other steps checks against. 

I tried to make it a proper gold file, but the problem doesn't remain consistent across architectures and processors. Therefore, currently the test is checking that the same garbage solution is achieved with recover.

**Pull request closed without merging**
