### PR TITLE
Factor Matrix inversion out of RankFourTensor

### LINKED ISSUE #5291: Factor matrixInversion out of RankFourTensor.C
Hi @dschwen and @tonkmr  (and any other interested parties),

Currently RankFourTensor has a method matrixInversion that uses petsc/lapack/blas to invert a general real nxn matrix.  That is useful ability that's not necessarily related to RankFourTensor.  I think we should either make it a static function in RankFourTensor, or take it out of RankFourTensor entirely.

Thoughts?

a

### PR DESCRIPTION
**Pull request by WilkAndy**
Matrix inversion factored out of RankFourTensor

Help needed:
(1) if someone sees this is a dumb idea, please tell me!
(2) I want MatrixInversion.h to include only the minimal things, but i don't know what they are because i only have petsc3.4.4 here at work.
(3) i can't understand the compiler errors from the "#if" directives.  For some reason, I need to '#include "DerivativeMaterialInterface.h"' otherwise i get errors:
MatrixInversion.h:18:28: error: missing binary operator before token "("

If all goes to plan, i'll move the matrix-inversion things out of unit/src/RankFourTensorTest.C into a new file.
Also i want to have a method in MatrixInversion that accepts an actual nxn matrix, not the stupid n^2 vector.

Fixes #5291

### CODE REVIEW

**Comment by dschwen** [comment]
Hey @WilkAndy, what is the motivation to factor out the matrix inversion? Do you need to invert things that are not r4t?

**Comment by WilkAndy** [comment]
yes, @dschwen .

**Comment by dschwen** [comment]
Try including `PetscSupport.h`

**Comment by WilkAndy** [comment]
OK, i'll work on this next week,

a

**Comment by WilkAndy** [comment]
Thanks @dschwen for the PetscSupport.h include.  How did you know?

**Comment by WilkAndy** [comment]
Currently the code does what i want.  Please don't merge until the "PR test debug: linux-gnu" has passed - it stopped short of doing my unit tests because of problems (presumably) unrelated to this PR.

My recent PRs have been experiencing lots of failures in unrelated tests.  This didn't used to happen as frequently a few months ago.  I wonder what's happened.  Are there lots of new "fragile" tests, or something else?

**Comment by WilkAndy** [comment]
Oh, i just found that "invalidate" button.  Cool

**Comment by dschwen** [comment]
How about we name the namespace `MatrixTools` instead (`MatrixInversion::invert` sounds redundant and does not lend itself to host further methods).

**Comment by WilkAndy** [comment]
Yea, ok @dschwen , i'll do that today.

a

**Comment by dschwen** [comment]
Adds in compile warnings:

```
/Users/schwd/Programs/moose/framework/src/utils/MatrixTools.C:23:9: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
```

**Pull request merged**
