### PR TITLE
Update libmesh.

### PR DESCRIPTION
**Pull request by jwpeterson**
Brief summary of changes included in this update:
- Fix missing rehash call in Fparser.
- Many fixes for --enable-singleprecision builds.
- Add support for TRISHELL3, QUADSHELL4 element types.
- Add BoundaryInfo support for new shell element types.
- Add support for writing shell elements in XdrIO.
- Add optimized contains_point() implementations for Tri3 and Tet4.
- Add TypeTensor::solve().
- Minor optimizations to 2D/3D Elem::volume() optimizations.
- Add TypeVector::cross_norm().
- Clean up misc_ex7.
- Add libmesh_noexcept wrapping C++11 noexcept specification.
- Add const-correct Elem interfaces neighbor_ptr(), child_ptr(), side_ptr(), etc.
- Handle NULL elements in EquationSystems::get_solution().
- Add MeshBase::active_semilocal_elements_begin() interface.
- Add C++11 std::make_unique workaround.
- Optimize stitch_meshes() by avoiding unnecessary PointLocator calls.
- Speed up "make check" by modifying examples slightly.
- All all_first_order option to meshtool app.
- Add BoundaryInfo::copy_boundary_ids() interface.
- Add --enable-cxx11-required configure flag.
- Avoid writing trailing whitespace in XDA files.
- Fix a few unsigned -> dof_id_type type mismatches.
- Add configure test for C++11 std::condition_variable.
- Use non-deprecated PETSc-3.7 interfaces.
- Nonblocking send/receive of packed ranges.

Refs #000.

### CODE REVIEW

**Comment by jwpeterson** [comment]
The failures are: 

* timeout in `combined:contact_verification/patch_tests/brick_3.glued_pen`
* One test diffs slightly in BISON 
`displ_x                rel diff:  1.0000002e-05 ~  9.9999895e-06 = 1.22936e-06 (node 8)`

I don't think either of these is due to the libmesh update (I believe the former is one that times out all the time).

**Comment by permcody** [comment]
The former does timeout all the time and I asked Al to look at it today.

The later though has failed twice, I also invalidated it. I don't think
it's a big deal but maybe we need to change the tolerance on that test?

**Comment by jwpeterson** [comment]
> I don't think it's a big deal but maybe we need to change the tolerance on that test?

I'm looking into making it a bit more robust...

**Comment by friedmud** [comment]
@jwpeterson please hold off on this until @roystgnr merges https://github.com/libMesh/libmesh/pull/879

**Comment by friedmud** [comment]
Ok - libMesh/libmesh#879 has been merged.

Thanks for holding off!

**Comment by jwpeterson** [comment]
No problem.  I am also waiting on a small Bison PR to be merged, then I will restart this one.

**Comment by jwpeterson** [comment]
@permcody what do you want to do about the debug-mode test that keeps timing out?  It would be good to get the libmesh update merged now that BISON is passing.

**Pull request merged**
