### PR TITLE
Account for Hit in Submodule Moosetools.

### LINKED ISSUE #17406: Need to Account for new Submodule in Docker Builds
## Bug Description

The submodule `moosetools` has been recently added and caused our image build/test to tank.  

## Steps to Reproduce

Try to build and test a MOOSE image.

## Impact

This needs to get fixed ASAP to avoid gaps in our image history, so I will furnish a PR soon.

### PR DESCRIPTION
**Pull request by herter4171**
In `docker_ci`, the files `Dockerfile` and `Jenkinsfile` have been updated to account for `hit` being in the submodule `moosetools` and needing to get built before MOOSE.  I've verified working images on both of our distros, and this obviously doesn't touch any source.

The other minor item was updating the version numbers for the distros where applicable, but the versions were incremented months ago on our end.

Closes #17406.

### CODE REVIEW

**Comment by loganharbour** [comment]
#17413 should satisfy the immediate problem - we should be able to use the framework hit for now (not requiring the submodule yet). This was the original intention while we transition, we just goofed a bit.

Once that gets in, please test your changes here to make sure all is well.

**Comment by herter4171** [comment]
@loganharbour, everything looks good on my end.  Not sure why all of those commits popped up from the rebase.

**Comment by loganharbour** [comment]
You're probably going to need to reset on devel and cherry-pick your commits in (or something of the sort)

**Comment by loganharbour** [comment]
@herter4171 just to make sure - your workflow is good right now without this, right? I've got it on my list to discuss with you first before we make the transition to using hit from the submodule.

**Comment by herter4171** [comment]
This is stale and has stuff not from me lumped into it.  Closing

**Pull request closed without merging**
