### PR TITLE
Piecewise multi-constant interpolation

### PR DESCRIPTION
**Pull request by snschune**
Very few changes are necessary to enable multi-constant interpolation. I am looking for suggestions either to rename `PiecewiseMultilinear` or split into two different classes.

### CODE REVIEW

**Comment by permcody** [comment]
I'm fine with this, thoughts @andrsd?

**Comment by snschune** [comment]
With the same argument `MultiLinear` should be part of `PiecewiseLinear` and/or `PiecewiseBilinear`. While the common characteristic of interpolation order implies grouping as @andrsd suggests, multi-dimensional 
vs. one-dimensional intergration (the `Multi...`) is another common characteristics that would justify grouping as I did. 

Would it make sense to have `PiecewiseMultiDimensionalInterpolation` and have `PiecewiseMultiLinear` and  `PiecewiseMultiConstant` inherit from it?

**Comment by snschune** [comment]
Actually, the `Multi` aspect of interpolation distinguishes the classes more than the order aspect `Constant`/`Linear`, so enhancement of `PiecewiseConstant` is much more difficult.

**Comment by andrsd** [comment]
> Would it make sense to have `PiecewiseMultiDimensionalInterpolation` and have `PiecewiseMultiLinear` and `PiecewiseMultiConstant` inherit from it?

This would be much better :+1:

**Comment by snschune** [comment]
Any objections to this implementation?

**Review by andrsd — APPROVED** [review]

**Pull request merged**
