### PR TITLE
Threaded the generalizedplanesstrainuserobject

### LINKED ISSUE #7826: GeneralizePlaneStrainUO won't work with threads
### Description of the enhancement or error report

It appears that the `threadJoin` method is not implemented on this object. Since this is an elemental user object, that means this object will not work with threads.

### Rationale for the enhancement or information for reproducing the error

Object is incomplete

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Simulation using this object cannot run threaded.

@hchen139 - Please implement this method. Feel free to stop by the MOOSE cube if you have questions on how or what you need to do in that method. Thanks

### PR DESCRIPTION
**Pull request by hchen139**
- closes #7826

### CODE REVIEW

**Comment by hchen139** [comment]
@permcody @dschwen

**Review by dschwen — APPROVED** [review]
Looks fine to me.

**Comment by dschwen** [comment]
One more thing though, @hchen139 please review your test critically and try to figure out why it did not fail when run in parallel and or with threads!

**Comment by permcody** [comment]
I'm pretty sure we still aren't testing modules with threads or in parallel... That really needs to change.

**Comment by dschwen** [comment]
Right. OMG. We only test them in debug. Might as well add an opt build, opt MPI, and opt threads step.

**Review by permcody — APPROVED** [review]

**Comment by YaqiWang** [comment]
Do not worry to much, I know BISON has all these tests, ;-)

**Pull request merged**
