### PR TITLE
Move P and TAux from NS to FP module 

### LINKED ISSUE #13008: Move some AuxKernels from Navier Stokes to FluidProp
## Rationale

`PressureAux` and `TemperatureAux` belong into `FluidProperties` module. 
This is ultimately necessary to allow Pronghorn and RELAP-7 to be used to together.

## Description

Move source code and renaming parameters. I will stick to Relap's naming because fewer
inputs to fix.

## Impact

No additional capabilities or loss of capabilities. Expect some app's tests to be broken.

### PR DESCRIPTION
**Pull request by snschune**
closes #13008

### CODE REVIEW

**Comment by andrsd** [comment]
You will need to add this to `moose/modules/fluid_properties/doc/hidden.yml`:
```
- /AuxKernels/PressureAux
- /AuxKernels/TemperatureAux
```

That should fix the doco target.

**Comment by andrsd** [comment]
Also, all failing apps will need a MOOSE update and some THM update. I will take care of bighorn, RELAP-7, sockeye, THM and sabertooth.

**Comment by snschune** [comment]
I got a PR up for THM.

**Comment by dschwen** [comment]
A lot of acronyms here...

**Comment by snschune** [comment]
> A lot of acronyms here...

If you deal with sabertooth just naming all the apps by their full name would take about an hour.

**Comment by snschune** [comment]
> You will need to add this to moose/modules/fluid_properties/doc/hidden.yml:

Let's see if I can document the classes.

**Comment by snschune** [comment]
@andrsd not done here, need to do the same for `SpecificVolumeAux` and `SpecificInternalEnergyAux`.

**Comment by snschune** [comment]
Actually, these are different. What about renaming NS to `NSSpecificInternalEnergyAux` and equivalently?

**Review by andrsd — APPROVED** [review]

**Pull request merged**
