### PR TITLE
PenaltyLimitBC

### LINKED ISSUE #20560: Add PenaltyLimitBC
## Reason
Sometimes preventing a variable value beyond a certain value is preferable, such as a soft spring that prevents the mesh from going below a specified value.

## Design
Conditionally apply the BC computed by `PenaltyDirichletBC` based on if the variable value is above or below the specified value, but zero otherwise.

## Impact
More flexible BCs.

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #20560

### CODE REVIEW

**Comment by tophmatthews** [comment]
@bwspenc what is your feel on something like this? I am looking for a soft spring type action for a Bison simulation that doesn't allow the mesh into certain locations. I was a bit surprised that something like this doesn't already exist, so I'm concerned there is a reason it's not used...

**Comment by bwspenc** [comment]
@tophmatthews I guess we discussed this on Slack. Like I said, the VI solver kind of does this already, so maybe this isn't necessary. It's been a while since I used that solver, so I don't remember the details of how you use it. Maybe try using that and see if that works for you, and if it doesn't, then we could consider something like this.

Also, I'm curious -- does it need to be a penalty BC for your purposes?

**Comment by tophmatthews** [comment]
Oh, you were talking about the vi solver...No, I don't think that will work there as it adds in way more complexity on the solver side of things. There were other reasons I don't fully remember...but it's non trivial I remember that.

I'm still testing this, but the simplicity of this makes it easy to use. I want it to be a penalty because it just needs to be a soft nudge in the right direction, not explicitly set.

**Comment by bwspenc** [comment]
I get that about the complexity with VI. Is it actually bad if it's more than a "soft nudge"? My inclination would be for this not to be a penalty BC unless it really needed to be.

**Comment by tophmatthews** [comment]
No, I suppose it doesn't have to a be a soft nudge, I assumed it would be more numerically allowable. So you think like a wall?

**Comment by bwspenc** [comment]
I guess if you set the penalty really low, it might be less of an abrupt transition between enforcing and not enforcing the constraint. My guess is that this would work fine with a non-penalty form of the BC.

Before going further with developing this, though, I really think you should see whether VI does what you want. Look at this regression test: moose/test/tests/auxkernels/bounds, but note that the base .i file doesn't actually run (it's testing an error condition). You need to add a couple more parameters that are passed in via cli_args in that test.

**Comment by GiudGiud** [comment]
You are picking a very generic name "PenaltyLimitBC" but only handling two cases (greater and lower than for variable).
If you could extend this to "greater/lower than" for a parsed expression of variables
OR
Extend this to parsed conditions for a single variable
Then I would be happy with this. You could also change the name to something specific but that's not my favorite outcome. 

PR looks good to me otherwise

**Comment by tophmatthews** [comment]
I dunno...I'm not sure this is what I need anyways, so I'll close for now until I do more testing...unless someone else want this?

**Pull request closed without merging**
