### PR TITLE
Reset subapp during transient runs of main app

### LINKED ISSUE #16476: ignore_solve_not_converge may need modification for sequential sampling
## Bug Description
The option `ignore_solve_not_converge` in `MultiApps` is supposed to ignore non-converged solves and move on to the next sample. However, this behavior is not true when performing sequential sampling (e.g., MCMC sampling) where the `Executioner` block controls the number of samples.

## Steps to Reproduce
The main input file (MC_ignore.i) and the subapp input file (sub_ignore.i) are attached. Please note that `--allow-test-objects` should be used for running the main input file.

MC_ignore.i

`[StochasticTools]
  auto_create_executioner = false
[]

[Distributions]
  [mu1]
    type = Normal
    mean = -100
    standard_deviation = 0.045
  []
  [mu2]
    type = Normal
    mean = 9
    standard_deviation = 1.35
  []
[]

[Samplers]
  [sample]
    type = MonteCarlo
    num_rows = 1
    distributions = 'mu1 mu2'
    execute_on = INITIAL
  []
[]

[MultiApps]
  [sub]
    type = SamplerFullSolveMultiApp
    input_files = sub_ignore.i
    sampler = sample
    ignore_solve_not_converge = true
  []
[]

[Transfers]
  [sub]
    type = SamplerParameterTransfer
    multi_app = sub
    sampler = sample
    parameters = 'Kernels/nonlin_function/mu1 Kernels/nonlin_function/mu2'
    to_control = 'stochastic'
    execute_on = INITIAL
    check_multiapp_execute_on = false
  []
  [average]
    type = SamplerPostprocessorTransfer
    multi_app = sub
    sampler = sample
    to_vector_postprocessor = average
    from_postprocessor = average
  []
[]

[VectorPostprocessors]
  [sampler_data]
    type = SamplerData
    sampler = sample
    execute_on = 'TIMESTEP_END'
  []
  [average]
    type = StochasticResults
    execute_on = 'TIMESTEP_END'
  []
[]

[Executioner]
  type = Transient
  num_steps = 2
[]

[Outputs]
  csv = true
  execute_on = 'INITIAL TIMESTEP_END'
[]
`

sub_ignore.i

`[Functions]
  [source]
    type = ParsedFunction
    value = "100 * sin(2 * pi * x) * sin(2 * pi * y)"
  []
[]

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 20
    xmin = 0
    xmax = 1
    ny = 20
    ymin = 0
    ymax = 1
  []
[]

[Variables]
  [U]
    family = lagrange
    order = first
  []
[]

[Kernels]
  [diffusion]
    type = Diffusion
    variable = U
  []
  [nonlin_function]
    type = ExponentialReaction
    variable = U
    mu1 = 0.418358
    mu2 = 13.4539
  []
  [source]
    type = BodyForce
    variable = U
    function = source
  []
[]

[BCs]
  [dirichlet_all]
    type = DirichletBC
    variable = U
    boundary = 'left right top bottom'
    value = 0
  []
[]

[Executioner]
  type = Transient
  num_steps = 2
  solve_type = PJFNK
  petsc_options_iname = '-pc_type -pc_hypre_type'
  petsc_options_value = 'hypre boomeramg'
  nl_abs_tol = 1e-13
  nl_rel_tol = 1e-13
  l_tol = 1e-13
  l_abs_tol = 1e-13
  l_max_its = 1
  nl_max_its = 5
  error_on_dtmin = false
  dt_min = 1
[]

[Postprocessors]
  [average]
    type = ElementAverageValue
    variable = U
  []
[]

[Controls]
  [stochastic]
    type = SamplerReceiver
  []
[]

[Outputs]
[]
`

## Impact
This issue is preventing us to run enough number of samples to test our sequential sampling algorithm implementations in MOOSE.

### PR DESCRIPTION
**Pull request by somu15**
## Reason
Currently, there is no option to reset the subapp for each transient step of the main app. One of the implications: state of the subapp is carried forward to the next transient step of the main app and we cannot perform sequential Monte Carlo simulations.

## Design
A bool variable called 'reset_subapp_transient' will be implemented in 'SamplerFullSolveMultiapp' to reset the subapp after each transient step of the main app.

## Impact
With the bool 'reset_subapp_transient' defaulted to false, this PR would not have any impacts on other objects.

## Other info
There will be two commits: 'Problem demo' to demonstrate the problem and 'Solution' to solve the above problem.

closes #16476

### CODE REVIEW

**Comment by somu15** [comment]
@aeslaughter Per our conversation, I created two commits. Now the subapp is being reset after every time step of the transient main app in SamplerFullSolveMultiApp.

**Comment by zachmprince** [comment]
So `initialSetup` is all you need? I believe we need this for `mode = normal` as well. As such, I would put this in the `preTransfer` function. We also don't need to do it on the first time step. So I would add a member variable `bool _solved_once = false` and have `_solved_once = true` in `solveStep`, then in `preTransfer` have:
```
if (_reset_subapp_transient && _solved_once)
   initialSetup();
```

I also think `reset_subapp_transient` should default to true since this is supposed to be the expected behavior.

**Comment by somu15** [comment]
> So `initialSetup` is all you need? I believe we need this for `mode = normal` as well. As such, I would put this in the `preTransfer` function. We also don't need to do it on the first time step. So I would add a member variable `bool _solved_once = false` and have `_solved_once = true` in `solveStep`, then in `preTransfer` have:
> 
> ```
> if (_reset_subapp_transient && _solved_once)
>    initialSetup();
> ```
> 
> I also think `reset_subapp_transient` should default to true since this is supposed to be the expected behavior.

Right now, I implemented it for both normal and batch modes. Does putting this in `preTransfer` make it apply for both? Also, do you think we should default the `_reset_subapp_transient` to false in case users are expecting it to work the way it previously was (carry the subapp state to next main app step)?

**Comment by somu15** [comment]
@zachmprince I included the `_solve_once` variable and set it to true in the bottom of `SolveStep`. 

Also, I defaulted the `_reset_subapp_transient` to true and included additional two tests for cases when it is false.

Finally, I implemented this for both `batch-reset` and `normal` modes. The `preTransfer` function is located in `MultiApp.C` in the framework and not in `SamplerFullSolveMultiApp.C`.

**Comment by aeslaughter** [comment]
@somu15 I am going to take a look at this and getting it working in general; I need it #16842.

**Comment by aeslaughter** [comment]
Closing in favor of #16855. @somu15 Thank you for your work on this, it helped. I ended up just making this resetting the default (and only) behavior. I also simplified the tests and made a test for each of the modes. The only major difference is that it was necessary to perform the reset prior to the transfers to make sure the transferred data was not clobbered. For the normal operation this required the use of the preTransfer method. Thanks again.

**Comment by somu15** [comment]
> Closing in favor of #16855. @somu15 Thank you for your work on this, it helped. I ended up just making this resetting the default (and only) behavior. I also simplified the tests and made a test for each of the modes. The only major difference is that it was necessary to perform the reset prior to the transfers to make sure the transferred data was not clobbered. For the normal operation this required the use of the preTransfer method. Thanks again.

Sure, sounds good. Thanks, @aeslaughter

**Pull request closed without merging**
