### PR TITLE
Change VTKWindow for change that occured in VTK 8

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #8807)

@dschwen Can you give this a try?

### CODE REVIEW

**Comment by dschwen** [comment]
Checking it now. Took me a while to set up a non HiDPI machine :-D

**Comment by dschwen** [comment]
idaholab/devel
Original MOOSE

aeslaughter/peacock
This branch

**Comment by dschwen** [comment]
idaholab/devel
Original MOOSE

aeslaughter/peacock
This branch

**Comment by aeslaughter** [comment]
What does your branch with DPI stuff look like?

**Comment by aeslaughter** [comment]
Also, can you check on your laptop and make sure it is no longer cropped. Mine works. Thanks.

**Comment by dschwen** [comment]
Working on it now

**Comment by dschwen** [comment]
Still cut off, and it will be until a scroll bar is added to the left panel.

**Comment by aeslaughter** [comment]
What about the fixes you created on your branch that did a fraction of the screen size. If that helps we can add it to this.

**Comment by dschwen** [comment]
We should go with your PR. I didn't address the UI cut-off either. This will require a `QScrollArea` to be added to the `LeftLayout`. I looked at your code, but the whole plugin based system is to opaque for me (I don't even see where the widgets get added to the left side panel).

**Comment by aeslaughter** [comment]
I will add the scroll.

**Review by dschwen — APPROVED** [review]
thx

**Pull request merged**
