### PR TITLE
Clear mesh subdomains before its initialization

### LINKED ISSUE #7989: MooseMesh::prepare() is not clearing _mesh_subdomains before initializing it
### Description of the enhancement or error report
This is not typically an issue. But when we have a `BlockDeleter` mesh modifier, `prepare()` will be called twice and `_mesh_subdomains` will still contain the subdomain just erased when the second time it is called.

### Rationale for the enhancement or information for reproducing the error
Later `MooseMesh::meshSubdomains()` will returns wrong list of subdomains.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Seems nobody is complaining on this at this moment.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #7989.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Looks like a reasonable fix to me.  I'll invalidate the Rattlesnake app test failure (TIMEOUT) unless you think it's related to this PR?

**Comment by jwpeterson** [comment]
Oh, there was a timeout in Mammoth too if you could see whether you think it's related.

**Comment by YaqiWang** [comment]
Just random timeout. I should reduce the size of those test sometime later.

**Comment by YaqiWang** [comment]
It used to be ok. Let us see if we just had bad luck.

**Comment by YaqiWang** [comment]
@jwpeterson this is ready.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
