### PR TITLE
Transfer existing tests and examples to new IC system

### LINKED ISSUE #8810: PolycrystalICs need to be more efficient
### Description of the enhancement or error report

With the necessity of running graph coloring algorithms to setup a reduced order parameter model, we need to be smarter about how we set up polycrystal ICs for multiple variables. Right now each IC performs the same logic for each variable including building a full graph and coloring it. This is really expensive (`PolycrystalReducedIC`, `ReconVarIC`).

### Rationale for the enhancement or information for reproducing the error

Some of the graph coloring algorithms may take several seconds to run per variable under certain conditions and we have to do this for each variable even though the graph doesn't change. The problem is that in order to accomplish this, we'll need to share data across ICs somehow. I'm not really coming up with an elegant solution right now. We could have the ICs access the ICs warehouse looking for the zeroth version of a similar variable and harvesting it's data structures. Since we use these ICs through Actions in all cases. We could have the Action create a shared object that gets used by everyone. I like this except it really means we wouldn't be able to use those ICs without the Action.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

More efficient ICs

### PR DESCRIPTION
**Pull request by permcody**
Remove old IC objects and actions
closes #8810

### CODE REVIEW

**Comment by permcody** [comment]
Note to reviewer: I'm not exactly sure how to reverify the grain_texture tests (the CSV files). The reason they changed is because of the slight differences in the random center assignments (random number stuff). I believe they are OK. I have opened up all of the other tests in peacock to inspect the results.

**Comment by permcody** [comment]
This seems like a scary amount of code that's being deleted but I assure you all that the functionality of the new system is much more compact. We don't need separate Actions for each IC because all polycrystal sims are handled by a single IC now (only the UserObject changes).

**Comment by permcody** [comment]
Oh yeah... Marmot...

**Comment by dschwen** [comment]
Branch has conflicts now. Do you have Marmot fixes ready?

**Review by dschwen — DISMISSED** [review]

**Comment by permcody** [comment]
I'm working on the Marmot fixes now (theoretically). I'll get those patched up then I should be able to get back to this PR. Thanks!

**Comment by permcody** [comment]
@dschwen - you already approved yesterday. This was just rebased and passes against Marmot now.

**Review by dschwen — APPROVED** [review]

**Pull request merged**
