### PR TITLE
DOCO improvements for shouldApply

### PR DESCRIPTION
**Pull request by andrsd**
This implements what we talked about in #4446. Plus, I found some formatting inconsistency in `BoundaryCondition` class which I fixed in a separate patch.

### CODE REVIEW

**Comment by friedmud** [comment]
Man.  This is definitely bad for speed.  Did you happen to run some benchmarks to see if this slows anything down?

**Comment by andrsd** [comment]
> This is definitely bad for speed.

That's what you suggested in #4446. I thought it was obvious that it was going to have performance impact and you were fine with it when you suggested it... Also, I am not insisting on this particular solution to the problem I described there.

> Did you happen to run some benchmarks to see if this slows anything down?

No.

**Comment by friedmud** [comment]
I know I suggested it!

But thinking about it and actually seeing it are two different things!

I don't think this will have any (much?) impact - but someone should do some quick tests on a few problems before we commit this...

**Comment by permcody** [comment]
:+1:

**Pull request merged**
