### PR TITLE
prevent negative porosity

### LINKED ISSUE #15861: Protect against negative porosity
## Reason
Sometimes a negative porosity can formulate in `ADComputeMultiplePorousInelasticStress.C` due to a non-perfect deviatoric. Run a check to prevent this.

## Design
```
if (_porosity[_qp] < _initial_porosity)
  _porosity[_qp] = _initial_porosity;
```

## Impact
More robust `ADComputeMultiplePorousInelasticStress.C`

### PR DESCRIPTION
**Pull request by tophmatthews**
closes #15861

### CODE REVIEW

**Comment by tophmatthews** [comment]
ping @dschwen

**Comment by dschwen** [comment]
I'm not too familiar with the physics here, but why would you prevent porosity from closing entirely?

**Comment by tophmatthews** [comment]
It should really be zero...it's a consequence of #15667 which was too unfavorable to pursue

**Comment by tophmatthews** [comment]
I need to wrap up some work that requires this, can @dschwen or @bwspenc take a look and get this in? Thanks!

**Review by dschwen — APPROVED** [review]

**Pull request merged**
