### PR TITLE
Add a little slack for the signal handler test

### LINKED ISSUE #24252: Signal handler test brittleness
## Bug Description
see https://civet.inl.gov/job/1500879/
seems the signal is sent too early

## Steps to Reproduce
Run test suite enough times

## Impact
Unexpected test failures

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #24252

### CODE REVIEW

**Comment by loganharbour** [comment]
Please bother @permcody and I with this one - a lot went into tuning these

**Comment by loganharbour** [comment]
This removes some capability of the testing, will need to be redone

**Comment by GiudGiud** [comment]
so the short and easy fix I am offering here is simply:
- make the test longer (70 steps)
- wait a little more to be sure to not be on time step 0 when creating the checkpoint (the failure I've observed)

**Comment by GiudGiud** [comment]
the complex fix would be to rework the signal handling code to wait for time step 1 to output the checkpoint instead

**Comment by GiudGiud** [comment]
> This removes some capability of the testing, will need to be redone

please elaborate

**Comment by GiudGiud** [comment]
Why wait for a signal to finish a solve?

**Comment by loganharbour** [comment]
> We could change this to "checkpoint at the next possible AND workable (eg not timestep 0) time. But that s the complex fix, I did not do the complex fix

I'm with you now - I think that the solution here is just to set a min number of steps that must have passed for the signal to trigger a checkpoint. and that implementation is very easy. I'll get to it

**Comment by lindsayad** [comment]
Solving this problem can't happen soon enough!

**Review by lindsayad — APPROVED** [review]

**Comment by GiudGiud** [comment]
🥷

**Comment by loganharbour** [comment]
sigh

**Pull request merged**
