### PR TITLE
If no Console objects exist don't do any screen output

### LINKED ISSUE #5178: "Solve Converged" Printing When It Shouldn't
If you run https://github.com/idaholab/moose/blob/devel/test/tests/multiapps/picard/picard.i

You will see that "Solve Converged" gets printed a bunch when it shouldn't be.

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #5178)

### CODE REVIEW

**Review by friedmud — CHANGES_REQUESTED** [review]
👎

**Comment by aeslaughter** [comment]
🐴 💩

**Review by friedmud — APPROVED** [review]

**Comment by YaqiWang** [comment]
The fix here is wrong. It defeats the who purpose of `_buffer_action_console_outputs `.

**Comment by friedmud** [comment]
@YaqiWang open a new ticket for it.

**Comment by YaqiWang** [comment]
I am puzzled by this, looks like the only printout on "Solve Converged" is in `Transient::solveStep`, which is in executioner execute and should be handled by Console properly. I think the change in the code needs to be reverted. By default, all the message outputted to Console will flush to screen  before its construction. I think the correct fix would be changing the this behavior by initializing `OutputWarehouse::_buffer_action_console_outputs` to true in `OutputWarehouse` constructor. Application can choose to call `OutputWarehouse::bufferConsoleOutputsBeforeConstruction(false)` if it wants a different default behavior. Thanks.

**Comment by YaqiWang** [comment]
Wait, looks like @permcody intentionally changed the behavior in 2c8e3fd135865eae0dbbdbd6b9e1451231926d3b. My memory is correct: I set it to true. We may have to work out with something else.

**Comment by YaqiWang** [comment]
I suggest to revert this change because the new behavior is quite annoying See #11435. Currently when I check out MOOSE I have to do the reversion immediately to see the outputs by actions in a sane manner. @permcody @aeslaughter @friedmud

**Pull request merged**
