### PR TITLE
TensorMechanicsMaterial and all children removed

### LINKED ISSUE #6973: Remove disp_x, disp_y, disp_z from TensorMechanicsMaterial
### Description of the enhancement or error report

TensorMechanicsMaterial still has disp_x, disp_y and disp_z in it.  Quite a long time ago we purged the rest of TensorMechanics in favour of the vector "displacements".  I'd like to do this for TensorMechanicsMaterial too.

### Rationale for the enhancement or information for reproducing the error

Makes TensorMechanics tidier.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This is what concerns me.  Within the tensor_mechanics module there are only a few classes that inherit from TensorMechanicsMaterial, but what about external apps?  I don't really want to bother doing this only to find an external app fails.

### PR DESCRIPTION
**Pull request by WilkAndy**
At least the following people need to approve this PR (assuming it even passes all the tests!): @dschwen , @sapitts , @jiangwen84 , @cpritam .

Fixes #6973

### CODE REVIEW

**Comment by dschwen** [comment]
Some of these did not have deprecation messages! We really need to make sure that we are not screwing third party apps here.

**Comment by WilkAndy** [comment]
Yes, you're right @dschwen .  I had hoped the "App tests" would pick up any problems, but that's probably too naive.  Would it be better to shove in deprecation messages for a few months first?

**Comment by mangerij** [comment]
I'm confused. The issue you reference is for getting rid of disp_x disp_y but you are going to remove the whole class? Ferret will likely fail here.

**Comment by WilkAndy** [comment]
Yep, you're right, @mangerij .   That issue soon got broader due to Daniel's comment: "Tensor mechanics should be even tidier if we just removed TensorMechanicsMaterial".  I made the current PR mostly to see what happened, and you're right, the App tests are failing (Marmot only so far - haven't got to Ferret).

This looks like an unpopular PR and i'm happy to just include deprecation messages instead - no worries.

**Comment by mangerij** [comment]
All good. I just was confused how we made the jump from the title of that issue to this PR. I didn't read the thread. Carry on :)

**Comment by WilkAndy** [comment]
For future reference, Marmot and Ferret failed.

Closing this PR in favour of #7391, in which Deprecated warning messages are used instead of "rm".

**Comment by dschwen** [comment]
I'll fix Marmot. I already have an open issue to remove the material that depends on the TM material stuff.

**Comment by dschwen** [comment]
@mangerij why is an auxkernel including a a header from a material?

```
/home/moosetest/civet/client_root_0/ferret/include/auxkernels/BandGapAuxTiO2.h:5:57: fatal error: TensorMechanicsMaterial.h: No such file or directory
```

**Comment by mangerij** [comment]
Because I wrote that AuxKernel like 1 month after I started using MOOSE
haha.

Will fix that as well as the tests in the other issue.

**Pull request closed without merging**
