### PR TITLE
Fix Tests for  petsc-3.9.4

### LINKED ISSUE #12527: Smooth tests with PETSc-3.9.4
## Rationale
There are still some tests which do not work well with PETSc-3.9.4

## Description
Smooth tests

## Impact
Won't impact anyone

### PR DESCRIPTION
**Pull request by fdkong**
Closes  #12527

### CODE REVIEW

**Comment by fdkong** [comment]
This should fix 64-bit issues

**Review by milljm — DISMISSED** [review]
re-gold tests and allow partitioner to only run on petsc less than 3.9.4... is my understanding. Looks good to me.

**Review by milljm — COMMENTED** [review]
Opps. My web browser did not have the updated status of the failing SQA requirements.

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
@fdkong says he's tested with 64 bits, valgrind, valgrind heavy, and modules heavy with PETSc 3.9.4 and things are passing.

**Pull request merged**
