### PR TITLE
Add computeQpOffDiagJacobian to example 3. Closes #9214

### LINKED ISSUE #9214: Add more off-diagonal jacobian documentation
### Description of the enhancement or error report

Need more documentation about writing off-diagonal Jacobian contributions

### Rationale for the enhancement or information for reproducing the error

This can be referenced for teaching new users.

### Identified impact

Help new users

### PR DESCRIPTION
**Pull request by lindsayad**
I think the coupling example should show Jacobian coupling. Also going to add documentation on the wiki that points to this.

Closes #9214

### CODE REVIEW

**Comment by permcody** [comment]
Hmm, maybe. I know @friedmud has opinions about how fast we should throw all this at the user. The off-diag Jacobian stuff is intentionally omitted until Example 11 or 12 on purpose. This example is the first exposure to coupling and we want to keep it simple.

**Comment by lindsayad** [comment]
I think there's some valid arguments there. But I also think it can be problematic to introduce coupling without Jacobian coupling in an early example. We show them how to couple in a variable, but then maybe they try it and their simulation doesn't converge because they've never even heard of computeQpOffDiagJacobian. (This PR was motivated by this thread https://groups.google.com/forum/#!topic/moose-users/SUYIMpFm8NI). Maybe a new user never even makes it to example 11. By the way example 11 doesn't actually introduce any kernels with computeQpOffDiagJacobian. That method doesn't appear until example 18 for scalar kernels. When I think of teaching preconditioning, I think more about teaching the application of the preconditioner, e.g. asm, block Jacobi, multi-grid, etc. I understand there can be differing views. But I thought it was problematic that when Chris Lee asked for an example of off-diagonal coupling, I really couldn't find a simple one quickly.

**Comment by friedmud** [comment]
Example 12 uses the off-diagonals:
http://mooseframework.org/wiki/MooseExamples/Example_12/

I agree that we need more documentation about computeQpOffDiagJacobian()...
but I disagree about adding it to example 3.

During the training this is usually where I point out that we're
intentionally leaving some information out of the preconditioner and we're
going to see if we can get away with it.  MOOSE was, first and foremost,
designed to do PJFNK with inexact preconditioning matrices.  Leaving out
off-diagonals is a very normal thing to do.

So: we DO need more computeQpOffDiagJacobian() documentation... and maybe a
stronger example early on.  But I don't think this is the right way to do
it.

As for talking about preconditioning... our view is somewhat different
because our research area was in "physics-based-preconditioning" for so
long.  We were really focused on what to fill the preconditioning matrix
_with_ more than we were worried about how to apply it's approximate
inverse.

**Comment by lindsayad** [comment]
Ok, I'm convinced enough

**Comment by friedmud** [comment]
If you're motivated though - feel free to add some to example 11 or example
12 documentation...

**Comment by lindsayad** [comment]
Ok, updated wiki page here: http://mooseframework.org/wiki/MooseExamples/Example_11/

**Comment by friedmud** [comment]
Thanks!  The only issue I see there is that it shows the use of FDP before
SMP.  FDP should always be relegated to use for debugging only.  We don't
want people actually relying on it for real runs.

**Comment by lindsayad** [comment]
K, swapped

**Comment by friedmud** [comment]
Looks great!  Thanks!

**Pull request closed without merging**
