### PR TITLE
Header refactor phases 2, 3, and 4.

### PR DESCRIPTION
**Pull request by roystgnr**
In discussion over IM of #8743, I warned @jwpeterson that I might have 3 more waves of refactoring to some at some future date, and he suggested "maybe you can combine 2-4 into a single PR later".  I assume he was holding a monkey's paw at the time.

This is the last of the dependency-reducing refactoring I intend to do for the foreseeable future.  At this point IMHO any more progress on #8730 either requires significant movements of actual code, work at the libMesh level, or both; and now that my obsessiveness is satiated I should probably get back to actual "fixing the light bulb" work.

### CODE REVIEW

**Comment by andrsd** [comment]
These apps need to be fixed:

[ ] BISON
[ ] marmot
[ ] bighorn (by @andrsd)
[ ] Rattlesnake
[ ] RELAP-7 (by @andrsd)
[ ] wolverine (by @andrsd)
[ ] mammoth
[ ] Mastodon
[ ] magpie

**Comment by rwcarlsen** [comment]
Conflicts are from the recent merge of clang-formatted everything.  This will need to be rebased by following the directions at http://mooseframework.org/blog/using-our-new-clang-format-style/ in the *Updating In-flight Changes* section.

**Comment by roystgnr** [comment]
Doesn't look hard; I'll fix up the conflicts now.

**Comment by rwcarlsen** [comment]
Looks like the modules need a couple of include mods too.

**Comment by andrsd** [comment]
It looks like this needs another rebase...

**Comment by rwcarlsen** [comment]
@roystgnr - This needs another rebase; we (unfortunately) had to do another clang-format commit.  Apparently MOOSE had several instances of corner-case code that required clang-format to be run again :-/

**Comment by roystgnr** [comment]
We're rebased and reformatted again; looks like there's some remaining (or some new) incompatibilities in Badger + Mammoth.

**Comment by andrsd** [comment]
We just patched mammoth devel, but it is not in master yet.

**Comment by YaqiWang** [comment]
@roystgnr which tool are you using to detect unnecessary includes? I'd like to use it to clean up Rattlesnake as well. Thanks.

**Comment by roystgnr** [comment]
@YaqiWang I only wish there was a way to automate this little obsession, but I'm afraid my whole procedure was manual.  Look at every header file, look at every file it includes.  If the header file doesn't use the included file's class at all, remove the include.  If the header file only refers to the included file's class with a pointer (including smart pointers, for classes with no inline destructors) or reference and if it doesn't use any of the class's methods, remove the include and put a forward declaration in its place.  If those first two steps broke your compilation (because the removed include itself included some class header that you needed), fix it by adding the previously-indirectly-included file in every place where its class gets used (which may not be the header you just edited; it may instead be something that included that header).

In libMesh we have an automatic way to check for missing header inclusions, and at one point I tried to come up with a counterpart way of checking for unnecessary header inclusions, but that's just a much harder problem.  For missing inclusions you can just compile one header at a time inside a small shim, but you can't just remove an inclusion and assume that a successful recompile means you did okay, because you might have simply been inappropriately getting the same inclusion indirectly instead and saving your compile that way.

**Comment by roystgnr** [comment]
This is neither a brag nor a complaint, just an observation: I'm pretty sure I've never rebased a single branch as many times as I've rebased this one.  :smile:

**Comment by permcody** [comment]
Unfortunately this comes down to training. There are a large number of people that don't understand C++ well enough to know when you need to include something and we you don't (i.e. forward declaration). So we end up with extra includes and missing includes all over the place. I have no doubt that there are developers out there that figure this out through an informed Monte Carlo method. The rules are even more challenging with C++11 `unique_ptrs` and most developers just give up. I'm glad we are doing this. It's just going to be a fact of life as we move forward. We'll have to do this again a year or two down the road.

**Comment by roystgnr** [comment]
It doesn't even take a lack of understanding to end up with redundant includes!  You write code, you add the includes the code needs... but later you refactor and remove some code, so what do you do then?  Do you go through all the remainder of the code and every header in the includes to see if there was anything which you previously needed but you no longer need?  I certainly don't.  It still compiles, it still works, who cares if it's a little inefficient to compile?  Nobody cares, until the inefficiencies add up.  

There's tradeoffs, too, when you start playing with forward declaration possibilities.  When I was doing the "free" refactoring, I noticed something like a dozen places where we could break up dependencies even further at the cost of moving a few inline functions into a .C file.  I didn't touch any of those; it's not clear a priori at what point big improvements in compile time outweigh tiny improvements in run time.

**Comment by dschwen** [comment]
@YaqiWang, @roystgnr : https://include-what-you-use.org/

**Comment by roystgnr** [comment]
@dschwen Nice, thanks!

**Comment by roystgnr** [comment]
"apt-get install iwyu" on Ubuntu, even.  And it seems to work astonishingly well after a little fiddling with options:

```
roystgnr@minerva:(master) ~/libmesh/git/clang
$ iwyu $(contrib/bin/libmesh-config --cxxflags --include) -I/usr/lib/llvm-3.5/lib/clang/3.5.2/include/ -Iinclude ../src/base/dirichlet_boundary.C 

../src/base/dirichlet_boundary.C should add these lines:
#include <memory>                            // for unique_ptr
#include <set>                               // for set
#include <vector>                            // for vector
#include "libmesh/fem_function_base.h"       // for FEMFunctionBase
#include "libmesh/function_base.h"           // for FunctionBase
#include "libmesh/id_types.h"                // for boundary_id_type
#include "libmesh/libmesh_common.h"          // for Number, libmesh_assert
#include "libmesh/libmesh_config.h"          // for LIBMESH_ENABLE_DIRICHLET
#include "libmesh/libmesh_nullptr.h"         // for libmesh_nullptr
namespace libMesh { class System; }

../src/base/dirichlet_boundary.C should remove these lines:

The full include-list for ../src/base/dirichlet_boundary.C:
#include <memory>                            // for unique_ptr
#include <set>                               // for set
#include <vector>                            // for vector
#include "libmesh/composite_fem_function.h"  // for CompositeFEMFunction
#include "libmesh/composite_function.h"      // for CompositeFunction
#include "libmesh/dirichlet_boundaries.h"    // for DirichletBoundary, Varia...
#include "libmesh/fem_function_base.h"       // for FEMFunctionBase
#include "libmesh/function_base.h"           // for FunctionBase
#include "libmesh/id_types.h"                // for boundary_id_type
#include "libmesh/libmesh_common.h"          // for Number, libmesh_assert
#include "libmesh/libmesh_config.h"          // for LIBMESH_ENABLE_DIRICHLET
#include "libmesh/libmesh_nullptr.h"         // for libmesh_nullptr
#include "libmesh/vector_value.h"            // for Gradient, VectorValue
namespace libMesh { class System; }
---
```

**Comment by YaqiWang** [comment]
Thanks @roystgnr and @dschwen! Will give that a try.

**Comment by roystgnr** [comment]
Anyone have time to dig into Badger and Mammoth again?  @andrsd ?  This PR ought to be either merged or rejected; nobody benefits from the limbo in-between where incompatibilities still have to be fixed but only get caught after-the-fact by Civet rather than immediately by developers' compilers.

**Comment by jwpeterson** [comment]
Oops, @andrsd went on vacation. Let me see if I can shepherd this the rest of the way through the build system...

**Comment by jwpeterson** [comment]
Badger should be fixed. Mammoth was failing because of Pronghorn, Pronghorn is now fixed. I discovered a (possibly new?) failure in Rattlesnake since the last time the App tests ran, that is also fixed now.

**Comment by roystgnr** [comment]
Ah, whoops, the implications of your "just waiting" just clicked.  Sorry for jumping the gun.

**Comment by jwpeterson** [comment]
There's an additional wrinkle which may make Mammoth not pass... it will need to have it Yak, Bison, etc. submodules manually updated first. This might take until tomorrow before everything actually goes green...

**Comment by jwpeterson** [comment]
Looks like someone has also merged something in the XFEM module in the meantime that breaks with this PR? I'm taking a closer look.

**Comment by jwpeterson** [comment]
Yeah... modules/xfem/include/base/XFEM.h:231:29: error: unknown type name 'SystemBase'

**Comment by jwpeterson** [comment]
Just need to `#include "SystemBase.h"` in XFEM.h to fix it, if you want to push another commit doing that here...

**Comment by roystgnr** [comment]
Let me just do another rebase and local test while I'm at it.

**Comment by jwpeterson** [comment]
Wow, BISON, MARMOT, and Grizzly also rebroke themselves in the interim apparently...

**Comment by jwpeterson** [comment]
y-u-no-y-u-do-dis

**Comment by jwpeterson** [comment]
@idaholab/moose-team Let's hold off on merging other PRs until we get this one in. We've merged several things in the last week that have broken this apparently!

**Comment by jwpeterson** [comment]
> Wow, BISON, MARMOT, and Grizzly also rebroke themselves in the interim apparently...

n/m they were just failing due to the modules changes I think. Otherwise, those apps all seem fine.

**Comment by jwpeterson** [comment]
OK, the only remaining app test failure is mammoth (it needs app submodule updates) so I'll focus on that this morning...

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
