### PR TITLE
Check for nonexistent variables in SolutionUserObject earlier 

### LINKED ISSUE #6702: Check for nonexistent variables earlier in SolutionUserObject
### Description of the enhancement or error report
SolutionUserObject now throws an error if a value is requested for a nonexistent variable,
but that check should be done earlier per the discussion in #6694.

### Rationale for the enhancement or information for reproducing the error
This error may be hit late in the analysis, but it can be checked at initialization.

### Identified impact
Interface changes in SolutionUserObject

### PR DESCRIPTION
**Pull request by bwspenc**
closes #6702

### CODE REVIEW

**Comment by bwspenc** [comment]
@permcody This addresses the issue you brought up in the discussion of #6695.

**Comment by permcody** [comment]
Odd failure. @YaqiWang - This PR looks pretty good but failed one test in Rattlesnake and not with the expected error. Can you see anything wrong with it?

**Comment by YaqiWang** [comment]
No idea, that test is not using `SolutionUserObject` at all. Let me invalidate the test see if it is reproduceable.

**Comment by brianmoose** [comment]
This same error happened on a recent Yak "App Tests", so I doubt it is related to this PR.

**Comment by YaqiWang** [comment]
Could possibly a race condition on file writing? Let me check the test list in that folder really quick.

**Comment by YaqiWang** [comment]
Actually it does. I recently added a test, which uses one existing file as a multiapp of the test. But this newly added test is not adding the test with the same input file as prereq. Let me fix it really quick. Sorry about it.

**Comment by YaqiWang** [comment]
FYI, that tests dependency issue has been fixed in Rattlesnake. Thanks for let us aware of it.

**Pull request merged**
