### PR TITLE
Augmented EquationSystems reinit

### PR DESCRIPTION
**Pull request by roystgnr**
As of https://github.com/libMesh/libmesh/pull/478 (and as requested in https://github.com/libMesh/libmesh/issues/437 ), libMesh now supports the use of EquationSystems::add_system() after EquationSystems::init().  However, to make that code simple and O(N) instead of O(N^2), we do still require a call to EquationSystems::reinit() afterwards before the newly-added systems can be used.

### CODE REVIEW

**Comment by permcody** [comment]
@andrsd - will you review and merge or work with Roy to complete?

**Comment by andrsd** [comment]
I thought there had to be a libMesh update involved for this to work. Or are we already using the right version?

**Comment by roystgnr** [comment]
Ah, no.  https://github.com/libMesh/libmesh/pull/478 is in master now, but since I use a separate libMesh build I forgot to update the submodule in Moose.

**Comment by permcody** [comment]
How did this pass the tests then?

**Comment by roystgnr** [comment]
It doesn't reenable the test it modifies.  This is an incomplete PR - it handles the post-ES::init add_system, but not the post-Sys::init add_variable.

**Comment by permcody** [comment]
Well that makes sense.

**Comment by andrsd** [comment]
> it handles the post-ES::init add_system, but not the post-Sys::init add_variable.

Based on our discussion yesterday @roystgnr I think we do not need post_sys::init add_variable. Variables are expected to be in input files, not added by our projection transfer. The transfer only needs to add a system to already existing ES.

I cannot work on the projection transfer now, but I should be able to get to it in March, unless someone else wants to finish the work...

So, let's mark this `Under development`?

**Comment by permcody** [comment]
@andrsd and @roystgnr maybe we can deal with this PR can get it merged?

**Comment by permcody** [comment]
@smharper if it's going to be awhile before you get to this, we should probably merge. I assume this PR didn't cause any issues for you in current MOOSE HEAD?

**Pull request merged**
