### PR TITLE
Q2p refactored Kernels and added an Action

### PR DESCRIPTION
**Pull request by WilkAndy**

### CODE REVIEW

**Comment by WilkAndy** [comment]
Wow, Bison is failing.  I wonder how that got through?!   .... Tagging the omnipresent @permcody ,

a

**Comment by permcody** [comment]
It means we are in the middle of an integration branch (planned test
failure). Rest assured neither MOOSE or BISON is broken for users.

Disregard that notice, we'll invalidate and rerun your test when the
integration is complete (later this evening on our side of the planet)

**Comment by permcody** [comment]
Nice work. I really like seeing developers using the multiple task Actions!

**Comment by WilkAndy** [comment]
Thanks @permcody 

a

**Pull request merged**
