### PR TITLE
Modify FeatureVolumeVectorPostprocessor to calculate coverage of a supplied boundary

### LINKED ISSUE #13202: Modify FeatureVolumeVectorPostprocessor so it can calculate areal coverage of a boundary
## Reason
Need to calculate what fraction of a grain boundary is covered by features that are connected to a simulation domain boundary.

## Design
FeatureFloodCount already detects which features are connected to a domain boundary and outputs that via FeatureVolumeVectorPostprocessor. We will add the capability to calculate how much of a specified SideSet is covered by each feature. For 3D simulations the sideset (2D) will be the grain boundary plane. The capability to supply boundaries will be added by making FeatureVolumeVectorPostprocessor inherit from BoundaryRestrictable. If a boundary is not specified, the default behavior will be that the volume of each feature will be calculated, as before.

## Impact
None

### PR DESCRIPTION
**Pull request by laagesen**
Closes #13202

### CODE REVIEW

**Comment by permcody** [comment]
I just pushed a commit to your feature branch that should fix this. It's testing now. It appears that the FeatureFloodCount has never worked on a mesh containing multiple subdomains where a feature spans those subdomains? I guess that's feasible...

**Comment by laagesen** [comment]
Thanks @permcody !

**Comment by permcody** [comment]
Looks like your 3D tests are a bit too heavy. They are timing out repeatably in debug mode. Note that debug mode on Linux is several times (an order of magnitude?) slower than on the Mac. You probably don't need ~20K elements for a test. I'd recommend making one of the dimensions really thin and running your test along the remaining wider faces.

**Comment by permcody** [comment]
Oh, make sure you don't force-push over my commit when you push your test. It's actually on _your_ feature branch so pull (which is unusual) before you push.

**Comment by laagesen** [comment]
Ah yes. As a phase-field person I have in mind that I need to make the domain large enough to fully resolve the entire particle. But there is no reason for that for the purposes of a test. Will fix shortly.

**Review by permcody — APPROVED** [review]
Nice work!

**Pull request merged**
