### PR TITLE
Fix FVElementalKernel query for residual loops. 

### LINKED ISSUE #24214: Residuals from FVElementalKernels are evaluated on every nonlinear system.
## Bug Description
Residuals from `FVElementalKernels` are evaluated on every nonlinear system

## Steps to Reproduce
Add print statements to the `FVCoupledForce` residual evaluation. And try to execute the following file:
```
moose/test/tests/misc/multiple-nl-systems/test-fv.i
```
The print statements will appear in the residual evaluation of both systems.

## Impact
Results in incorrect results when someone uses multiple nonlinear systems with finite volume kernels.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #24214

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]

**Review by GiudGiud — DISMISSED** [review]

**Comment by grmnptr** [comment]
Even though this fixed the issue on the framework test, I am still seeing the pressure gradient kernel evaluated during the assembly of the pressure equation so I'll poke around a bit more. Sorry for the premature ready-for-review.

**Comment by grmnptr** [comment]
Oh never mind, I am doing a residual evaluation on the pressure system before setting the current nonlinear system number. This works fine.

**Review by lindsayad — CHANGES_REQUESTED** [review]
You need this in `ComputeResidualAndJacobianThread` as well. Thanks for this catch

**Review by GiudGiud — APPROVED** [review]

**Review by lindsayad — APPROVED** [review]

**Comment by grmnptr** [comment]
This probably broke next:
https://civet.inl.gov/job/1512627/

**Comment by GiudGiud** [comment]
havent checked, could also be tied to the prepared for use thing

**Comment by grmnptr** [comment]
Ahh this is the wrong PR page. Sorry about that.

**Pull request merged**
