### PR TITLE
Tagging

### PR DESCRIPTION
**Pull request by friedmud**
Putting this up to spur some discussion about matrix/vector "tagging" ( #9669 ).

Definitely not ready to go yet... but the basic design idea is there: you can add matrices and vectors and "tag" them.  You can then assign the tags to Kernels... which will then fill in all applicable vectors/matrices all in one sweep.

### CODE REVIEW

**Comment by friedmud** [comment]
(I am also interested to see what (if anything) this breaks - so I'm going to let it do the testing for now)

**Comment by permcody** [comment]
LOL

**Comment by friedmud** [comment]
LOL?

**Comment by friedmud** [comment]
If you're referring to the print statements left in - I realized after I submitted this that the tests weren't going to run because of them... but I'm still working on this so I'm not taking them out yet.  It's still up here for people to comment on for now.

**Comment by fdkong** [comment]
It is very interesting for me, and I will be able to speed up the eigen simulation with this capability.  It will be also very helpful for users who want to construct different algorithms (explicit, explicit-implicit, ..)in moose.

**Comment by permcody** [comment]
Yeah, failing the precheck is what made me laugh. It spawned a whole conversation about whether we should be able to by-pass parts of the pre-check during development.

**Comment by friedmud** [comment]
Gotcha - yeah... being able to bypass "precheck" would be nice during development... but it's not critical.

For now, I'll just add a commit to this branch that cleans up the print statements

**Comment by friedmud** [comment]
@fdkong I'm glad that you will find this useful.  I think it's a great new foundational capability in MOOSE.

However: it is fairly invasive.  It will take a while before we have every system in MOOSE working this way (which is why I put this up for discussion early: no need to put more time/effort in with a bad design).

**Comment by permcody** [comment]
@friedmud - @lindsayad is here and chomping at the bit to start working on something exciting. I have a feeling that you probably won't be getting back to this anytime soon, so if there's something that Alex could help with, that'd be something we can have him work on. What do you think? Want to setup a time to have a conference call?

**Comment by friedmud** [comment]
I think this is at a point where it could be handed off.  The basic idea is
there... it just needs to be percolated through the various systems and
integrated with everything.  It's going to be quite a job though!

Unfortunately, I won't have any time for a conference call until late next
week.  Let me know if that works for you and we can set it up.

**Comment by lindsayad** [comment]
I could do Wednesday the 20th. I'll be in Berlin for Thursday and Friday

**Comment by permcody** [comment]
We never connected on this last week. @friedmud - what is your availability this week?

**Comment by friedmud** [comment]
I'm open on Wednesday and Thursday during the day.  What works for you guys?

**Comment by permcody** [comment]
Let's plan on Wednesday.

**Comment by friedmud** [comment]
Ugh - last week was a mess for me.  Can we get together this week?

**Comment by permcody** [comment]
This week works. I think we are all here and available most times. I'm
pretty busy on Thursday.

**Comment by friedmud** [comment]
Wednesday afternoon is looking good.

**Comment by permcody** [comment]
Sound like a plan.

**Comment by fdkong** [comment]
I am still interested in this. I will take this PR.

**Comment by permcody** [comment]
Superseded by #10111.

**Pull request closed without merging**
