### PR TITLE
Support  strumpack (a sparse direct solver)

### LINKED ISSUE #16501: Support strumpack (a sparse direct solver)
## Reason

For certain problems, I found `strumpack` beat all other direct solvers. I think it is a good idea to support this.

It might be interesting for @lindsayad @bwspenc as well 

## Design

"`--download-strumpack`". Also need to add something into libmesh configuration so that we have `strumpack=true` ready for use in `tests` 

## Impact
Better direct solver

### PR DESCRIPTION
**Pull request by fdkong**
Closes #16501 

Summary of libmesh changes (oh there are so many):

  - Check if PETSc has strumpack
  - Initialize next_unpartitioned_unique_id

### CODE REVIEW

**Comment by fdkong** [comment]
Waiting for https://github.com/libMesh/libmesh/pull/2822

**Comment by fdkong** [comment]
Test the whole world because it is a libmesh update

**Comment by fdkong** [comment]
It is ready for review @lindsayad

**Comment by lindsayad** [comment]
Hahaha you are sneaking in another libmesh update?

**Review by lindsayad — APPROVED** [review]
This looks good. I am going to add a summary of libmesh changes to the PR title post

**Comment by bwspenc** [comment]
Nice, thanks!

**Pull request merged**
