### PR TITLE
Add array body force kernel

### LINKED ISSUE #17583: Need a new kernel for array body force
## Reason
This array kernel applies body force and can be useful for testing.

## Design
A simple new array kernel in framework that applications can use as well.

## Impact
New capability.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #17583.

### CODE REVIEW

**Review by friedmud — DISMISSED** [review]
This looks good - but it does highlight an issue: we need to move the ArrayKernels tests to their own directory so that they can be more organized.  I don't want to have one directory with a hundred tests of different kernels in it.

**Review by GiudGiud — APPROVED** [review]

**Comment by YaqiWang** [comment]
We can merge this first and then do the organization.

**Comment by GiudGiud** [comment]
If organization doesn't happen today I ll merge this, no need to keep this waiting.

**Comment by GiudGiud** [comment]
@friedmud please let us know if you are fixing up the organization PR today or later on

**Pull request merged**
