### PR TITLE
Make August 2023 news public

### PR DESCRIPTION
**Pull request by cticenhour**
Add September 2023 news template

Refs #11447

@idaholab/moose-ccb Please add any entries to the August newsletter that may have been missed!

### CODE REVIEW

**Comment by lindsayad** [comment]
I've got nothing MOOSE level this month

**Comment by joshuahansel** [comment]
@cticenhour Conflict is my fault. Question on our policy: should we avoid putting newsletter updates in our PRs once this PR goes up each month?

Also when we do have a conflict, do people just resolve it with the web editor and do the merge commit? Or do we rebase and fix it like that?

**Comment by cticenhour** [comment]
I don't mind resolving these - they're small. If the PR is going to go in before the end of month, I'd rather you get it in the right newsletter and don't worry about my merge conflicts 😄

**Comment by cticenhour** [comment]
Also happy to accept commits directly here if you'd rather. Coordinate with your PR reviewer in that case.

**Comment by cticenhour** [comment]
>Also when we do have a conflict, do people just resolve it with the web editor and do the merge commit? Or do we rebase and fix it like that?

Completely skipped over this....I rebase and fix usually. I don't have any experience using the web editor for it.

**Comment by GiudGiud** [comment]
wed editor does a merge commit iirc. Not what we want?

**Comment by cticenhour** [comment]
Yeah, I'd rather not have a merge commit.

**Review by grmnptr — APPROVED** [review]
Looks good to me!

**Pull request merged**
