### PR TITLE
allow subapps query master app mesh information

### LINKED ISSUE #15235: Make master mesh accessible from subapp
## Reason

xolotl (https://github.com/ORNL-Fusion/xolotl) wants to partition its mesh based the master partition to optimize the transfer performance.

## Design

Expose an API to `subapp` so that it can access to the master mesh if they need to.

## Impact
None, if we are doing things right

### PR DESCRIPTION
**Pull request by fdkong**
Closes #15235

### CODE REVIEW

**Comment by YaqiWang** [comment]
What is going on here? `clone_master_mesh` parameter in `MultiApp` is already doing this.

**Comment by YaqiWang** [comment]
Check this out: https://github.com/idaholab/moose/pull/13837

**Comment by fdkong** [comment]
> What is going on here? `clone_master_mesh` parameter in `MultiApp` is already doing this.

Nope. I do not want to clone a mesh. I just want to see master mesh.

**Comment by YaqiWang** [comment]
I think by design, that is not allowed. I forgot why exactly we choose to clone the mesh instead let multapp to access the master mesh. Better to consult @permcody or @friedmud on this.

**Comment by YaqiWang** [comment]
Looks like you are cloning the mesh based on the changes in `SetupMeshAction.C`, did I miss anything?

**Comment by fdkong** [comment]
> I think by design, that is not allowed. I forgot why exactly we choose to clone the mesh instead let multapp to access the master mesh. Better to consult @permcody or @friedmud on this.

`Clone` is the right solution for NDA because you are building a system using that mesh. For my cause, I just want to query master mesh information, and I do not do any manipulation. Here is the context #15235

**Comment by permcody** [comment]
I have no issue with this. I think @friedmud wanted to make subapps unaware that they were special and keep them disconnected from master apps. The referenced ticket here though seems like a pretty good reason to relax this restriction.

**Comment by fdkong** [comment]
> I have no issue with this. I think @friedmud wanted to make subapps unaware that they were special and keep them disconnected from master apps. The referenced ticket here though seems like a pretty good reason to relax this restriction.

There is a middle point:

I could implement an input parameter `query_master_mesh`, and API `masterMesh()` is useful only when `query_master_mesh=true`, otherwise it returns `nullpr` .

We did this for `clone_master_mesh=true`. We try to have a similar strategy.

In this way, we do not expose mater mesh for most of the users.  I agree that `restriction` is till a good idea for most of the users

**Comment by friedmud** [comment]
I am not for these changes.  As @YaqiWang says: the sub-apps should not know about the master (as much as possible).

I suggest that the master drives this instead - injecting a mesh into the sub-app.  The sub-app can have an api that detects that it has been given a mesh and triggers a boolean that you can then use.

These things should come from the top - not get pulled from below.

**Comment by YaqiWang** [comment]
You may consider having a direct parameter in `MultiApp` like `partition_mesh_based_on_master`. When this parameter is on, we add a particular partitioner for the subapp and push the master mesh into the particular partitioner. I am not familiar with how we did the mesh partitioning, so it is possible that we do not need a partitioner but pushing the master mesh into MooseMesh and let MooseMesh to do the partitioning directly. We do not have to complicate the logic in the mesh cloning. This serves the direct need in the issue and the subapp do not need to anything special on its own. This actually can simplify what we had in Griffin (Search `EmbeddedMeshFullSolveMultiApp`, you will see). @friedmud comments made me think this a little more.

**Comment by friedmud** [comment]
@YaqiWang exactly right: this should be fed _down_ from the master app - overriding whatever mesh/partitioner are in the sub-app.

**Comment by YaqiWang** [comment]
@fdkong do you have plan to add `partition_mesh_based_on_master` and finish this PR? If this is available, I can use it to fix a test in Griffin. Best.

**Comment by fdkong** [comment]
> @fdkong do you have plan to add `partition_mesh_based_on_master` and finish this PR? If this is available, I can use it to fix a test in Griffin. Best.

`partition_mesh_based_on_master` is overdesigned for my original use case, and it is actually wrong for the original use case.

In my original use case: the mesh is generated in an external application (sub-app is an external application).  We normally have no idea how external application will generate a mesh. Sometimes it is not a mesh and could be a particular representation of the computational domain.  Therefore, we have no way to partition the sub-app mesh for external applications. What I wanted originally is to add an interface via which external application can query the master mesh.  Sub-app will query the mesh information and do not modify mesh master at all.  It is safe to do so. Once sub-app knows the master mesh, it should be able to partition its mesh during the mesh generation.  I am not sure if I need to do `partition_mesh_based_on_master` for my original use case.

`partition_mesh_based_on_master` could use useful in Griffin when the NDA mesh is different from the master mesh. But most of the time, the NDA mesh is the same as the master mesh.  What is your use case here?

**Pull request closed without merging**
