### PR TITLE
Added EXEC_INITIAL to execute_on for MaterialOutputAction auxes

### LINKED ISSUE #15412: Include EXEC_INITIAL for auxes created using MaterialOutputAction
## Reason
Currently, using `show_material_properties` in `Exodus` creates auxes that do not execute on `INITIAL`, thus not allowing material properties to not be viewed at this time with this capability.

## Design
This would add `EXEC_INITIAL` to `execute_on` for the aux kernel parameters created in `MaterialOutputAction`.

## Impact
There are a lot of tests that will yield Exodiffs with this change, since those tests saved zero values for material properties on `INITIAL`. The ideal solution is to re-gold those tests, since those gold files have incorrect (zero) solutions.

### PR DESCRIPTION
**Pull request by joshuahansel**
This allows materials to be output on INITIAL when using
"show_material_properties" with Exodus, for example.

Closes #15412

### CODE REVIEW

**Comment by joshuahansel** [comment]
This will surely fail application testing with Exodiffs because of the gold files that have been created with zero material property values on INITIAL. The solution to this will likely be determined from the extent of the failures.

**Comment by joshuahansel** [comment]
@aeslaughter Can you review this? MOOSE tests should all be re-golded for the new behavior. I think I used the legacy parameter idea you suggested - see the 2nd commit.

**Review by aeslaughter — DISMISSED** [review]
Looks correct to me.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
@joshuahansel - both! We put something out there that's not quite right, then we go and fix it making everybody have to regold all the things.

**Comment by YaqiWang** [comment]
It is quite embarrassing that when we do an application training, a legacy message shows up even the application is not affected by the changes in framework ;-)

**Comment by joshuahansel** [comment]
@YaqiWang Sorry, did the message at least make it clear how to remove it? I guess that was just poor timing; otherwise, you'd have probably noticed it before the training.

**Pull request merged**
