### PR TITLE
Add override keyword throughout tutorial

### PR DESCRIPTION
**Pull request by permcody**
Also use universal initialization for vectors in the Material class throughout
refs #7171

Tag @idaholab/moose-team for comments

### CODE REVIEW

**Comment by friedmud** [comment]
I'm just not sure of the utility here.  It seems like one more thing "normal" humans won't understand about C++ with MOOSE...

**Comment by permcody** [comment]
1. It prevents errors. We've had at least two really nasty cases where somebody mistyped a name and banged their head for a long time trying to figure out why their method wasn't called.

2. I really think the documentation thing is big. When I look in a class and see a ton of virtual methods (just about everything in MOOSE and the modules, I don't really know which ones are "new" and which ones are coming from a base class. Currently we just document every method. Most of the time with really lame strings like "computes a residual at the quadrature point". If we started using the override keyword throughout, we'd know that that method was already documented and there would be no reason to document it again.

**Comment by permcody** [comment]
Oh yeah - take a look at this one. Wouldn't have happened with `override`!
https://github.com/idaholab/moose/issues/4056

**Comment by friedmud** [comment]
I can understand (1)... it's just going to take some re-educating.  Is there a compiler switch we can turn on that makes it an error if you don't specify `override`?

However, I don't understand (2)... just because it says `override` doesn't mean that the method is documented properly in the base class.  Ideally, a method that is overridden should have its own documentation saying what it specifically does.

**Comment by friedmud** [comment]
To be clear - I'm not standing in the way of this change... just talking about it.

**Comment by permcody** [comment]
1. If you add it once in a file the compiler will fail to compile if any
others are missing. This appears to be the default.

2. Ideally the base class method should be documented ;). Do you really
need a description of the override? It still does the same thing, it just
does it differently. If you look through our classes you'll see a bunch of
similar descriptions for things like computeQpResidual but not exactly the
same. I don't think people are specific about the implementation very often
in practice. Id rather see it go in 90% of the cases.

**Comment by friedmud** [comment]
1. Only for that file?  Or does it happen even if that file is included
(i.e. as long as override is somewhere in the inheritance tree it will be
enforced)

2.  Well... _ideally_ every computeQpResidual() would have a longform
comment with Latex starting from the strong form and showing how the weak
form was derived and ultimately culminating in an explanation of what was
actually written.

**Comment by dschwen** [comment]
:+1: on 2)

**Comment by permcody** [comment]
I'm not sure how widespread the effect is with the override keyword downstream. I already added it to the GraintTracker and FeatureFloodCount objects but I think I tried it in the wrong order. I bet there are also compiler flags that enforce it everywhere if we really want to go nuts (maybe eventually). 

Well we're going to start documenting kernels better with @aeslaughter's new system. We _can_ put LaTeX in those associated .md files and they'll be rendered properly with normal mark down syntax. Our Doxygen comments should probably stick to method descriptions, parameter definitions and return values like libMesh does. Perhaps I picked a bad example so let's try another one. How about the UserObject system:

```
virtual void intialize();
virtual void execute();
virtual void finalize();
virtual void threadJoin(...);
```

How creative are you at explaining what `initialize()` and `execute()` do for every derived UserObject? Personally I think a nice description in the base class is good enough. Maybe I'll go poke through a few of the ones that are out there and see how useful those comments are... 😉 

This just in, comments on all UserObject virtual overrides are ... TERRIBLE.

**Comment by permcody** [comment]
It looks like there are new flags for both Clang and GCC for dealing with missing or inconsistent `override` usage. We'll have to first agree that this is something we want to do, add it everywhere, then start using this flag:
http://stackoverflow.com/questions/29145476/requiring-virtual-function-overrides-to-use-override-keyword

**Comment by friedmud** [comment]
If we're going to do it... Then I like the idea enforcing it everywhere...

**Comment by permcody** [comment]
That would be the plan. I think we'll do this after we get it everywhere
and get people trained.

**Comment by jwpeterson** [comment]
I like `override`, and I definitely think this should be merged.

> We've had at least two really nasty cases where somebody mistyped a name and banged their head for a long time trying to figure out why their method wasn't called.

I think the other example was someone implementing `computeQpOffDiagonalJacobian()` and wondering why it was never called.

>  If you add it once in a file the compiler will fail to compile if any
others are missing. This appears to be the default.

This isn't exactly right... If you put `override` and the function does not actually override anything from the base class, that's an error.  Putting `override` is always optional, however I've noticed that Clang warns about forgetting to put the `override` keyword when some other members of the class have it.  This is just a warning, though, not a compiler error.  GCC doesn't warn about this.
```
./include/libmesh/petsc_matrix.h:352:16: warning: 'get_transpose' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void get_transpose (SparseMatrix<T> & dest) const;
```

**Pull request merged**
