### PR TITLE
Revert "Merge pull request #14856 from dschwen/rapid_dev_paper_inputs"

### PR DESCRIPTION
**Pull request by milljm**
This reverts commit d2dbdbaad1035cecc5015b2b071ead5b5f637c60, reversing
changes made to 40f90ce91bf51610248c7eb14506bafedb448f06.

### CODE REVIEW

**Comment by dschwen** [comment]
The original PR requires a marmot patch.

**Comment by loganharbour** [comment]
> The original PR requires a marmot patch.

Are you able to get that in today?

**Comment by dschwen** [comment]
Yes. It already passed most Marmot tests. Should be in in abt. 20mins

**Comment by loganharbour** [comment]
I think you may be missing something, see https://civet.inl.gov/event/52130/. This requires a MOOSE patch.

**Comment by dschwen** [comment]
```
 __          _________ ______ ___  _ 
 \ \        / /__   __|  ____|__ \| |
  \ \  /\  / /   | |  | |__     ) | |
   \ \/  \/ /    | |  |  __|   / /| |
    \  /\  /     | |  | |     |_| |_|
     \/  \/      |_|  |_|     (_) (_)
                                                                      
```

**Comment by dschwen** [comment]
```
kernels/materialpropertyvalue.test: exodiff: WARNING .. The local element 14 with global id 14 in file1 has the global id 157 in file2.
```

How is that an issue only for that super simple kernel?!

**Comment by loganharbour** [comment]
```
  , ; ,   .-'"""'-.   , ; ,
  \\|/  .'         '.  \|//
   \-;-/   ()   ()   \-;-/
   // ;               ; \\
  //__; :.         .; ;__\\
 `-----\'.'-.....-'.'/-----'
        '.'.-.-,_.'.'
          '(  (..-'
            '-'
```

**Comment by permcody** [comment]
Closing since we have a fix for the breakage.

**Comment by dschwen** [comment]
FYI, marmot fix is in

**Pull request closed without merging**
