### PR TITLE
Creates offline support for MooseDocs

### LINKED ISSUE #9656: Doco must be buildable offline for SQA purposes
### Description of the enhancement or error report

Make sure that all documentation and rendering resources are available offline for rendering documents. These should be checked into the repository so that we meet all requirements to be able to reproduce documents in past checkouts.

### Rationale for the enhancement or information for reproducing the error

New enhancement to assist in meeting NQA-1 requirements.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Documentation robustness.

### PR DESCRIPTION
**Pull request by aeslaughter**
closes #9656

### CODE REVIEW

**Comment by aeslaughter** [comment]
This simply just adds all the needed fonts/js/css dependencies to the repository, with one exception MathJax. MathJax is not contained in a single file and contains a lot of baggage, so I made it a submodule.

**Comment by rwcarlsen** [comment]
This looks pretty reasonable.  I think we should probably have a README somewhere that documents urls for the respective js/css assets and a blurb about what they are used for.  A bonus would be a script to run that auto-updates them that we could manually run on occasion.

**Comment by aeslaughter** [comment]
I think this is ready to go, I needs someone else to test this out.

**Comment by rwcarlsen** [comment]
In my browser console, it still seems like the local mathjax isn't being picked up and the cloudflare fallback is kicking in (and this is after I initialized the mathjax submodule).

Also:

screen shot 2017-09-11 at 2 53 58 pm

**Comment by gardnerru** [comment]
Runs on my machine but I confirm the same thing that Robert is seeing in the AuxKernels and other systems.

**Comment by aeslaughter** [comment]
@permcody @rwcarlsen I

**Review by gardnerru — COMMENTED** [review]
Docs build on my box, tested without internet. There is still the same formatting issues that were noted before where BurnupMetalAux shows as B...  (for example) When you click it the full name appears then you go to the page. What is interesting is that you can search for it. The spacing on the descriptions is also off.

**Comment by aeslaughter** [comment]
I am working on a new solution that will hopefully avoid the MathJax submodule stuff.

**Comment by aeslaughter** [comment]
@rwcarlsen Can you try this again?

**Comment by rwcarlsen** [comment]
screen shot 2017-09-25 at 12 42 16 pm

...but otherwise looks good - all assets are being picked up and served locally.

**Comment by rwcarlsen** [comment]
screen shot 2017-09-26 at 2 47 24 pm

**Comment by rwcarlsen** [comment]
I think the missing icons probably has to do with my proxy tunneling in firefox - so feel free to disregard it.

**Comment by aeslaughter** [comment]
@permcody @brianmoose @rwcarlsen Who wants to pull the trigger, I think everything is working.

**Comment by permcody** [comment]
I'll pull this branch and try it. I haven't for awhile.

**Comment by permcody** [comment]
The MooseDocs site is appears to be functioning properly. However there is still some work to do. The input files and code links take you to Github. The Doxygen links take you mooseframework.org. These links should be pulling up the local files as a start. We may have to figure out what we plan to do about Doxygen.

So, I'm fine with merging this since it gets us most of the way there. Would you prefer to keep working on this issue or having me open up new issues for what remains to be completed for this capability?

**Comment by aeslaughter** [comment]
Don't merge yet, I am going to move the dependencies to be easier to find (i.e., a contrib directory).

**Comment by aeslaughter** [comment]
@permcody I will used #9930 for the remaining offline items.

**Review by permcody — APPROVED** [review]

**Comment by aeslaughter** [comment]
I am good for this to get merged.

**Pull request merged**
