### PR TITLE
speed up test

### PR DESCRIPTION
**Pull request by hchen139**
refs #15532

### CODE REVIEW

**Comment by hchen139** [comment]
@lindsayad This should fix the slow test.

**Review by lindsayad — COMMENTED** [review]
I appreciate it. Is there a reason to skip the old test instead of just removing it?

**Comment by hchen139** [comment]
> I appreciate it. Is there a reason to skip the old test instead of just removing it?

I would like to have that test but now there is another problem if I pure trim down the mesh size. The skipped test will be revisited in future PR.

**Comment by lindsayad** [comment]
> I would like to have that test but now there is another problem if I purely trim down the mesh size. The skipped test will be revisited in future PR.

:+1:

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
