### PR TITLE
Fix warnings in geochemistry

### LINKED ISSUE #16135: Resolve warnings in geochemistry
## Reason
The following warnings are treated as errors in the new infrastructure target:
```
Compiling C++ (in opt mode) /opt/civet/build_0/moose/modules/heat_conduction/build/unity_src/bcs_Unity.C...
In file included from /opt/civet/build_0/moose/modules/geochemistry/build/unity_src/utils_Unity.C:14:
/opt/civet/build_0/moose/modules/geochemistry/src/utils/PertinentGeochemicalSystem.C: In member function 'unsigned int PertinentGeochemicalSystem::getIndexOfOriginalBasisSpecies(const string&) const':
/opt/civet/build_0/moose/modules/geochemistry/src/utils/PertinentGeochemicalSystem.C:75:15: error: catching polymorphic type 'class std::out_of_range' by value [-Werror=catch-value=]
   75 |   catch (std::out_of_range)
      |               ^~~~~~~~~~~~
Compiling C++ (in opt mode) /opt/civet/build_0/moose/modules/heat_conduction/build/unity_src/actions_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/moose/modules/heat_conduction/build/unity_src/meshgenerators_Unity.C...
In file included from /opt/civet/build_0/moose/modules/geochemistry/build/unity_src/outputs_Unity.C:3:
/opt/civet/build_0/moose/modules/geochemistry/src/outputs/GeochemistryConsoleOutput.C: In member function 'void GeochemistryConsoleOutput::outputNernstInfo(const GeochemicalSystem&) const':
/opt/civet/build_0/moose/modules/geochemistry/src/outputs/GeochemistryConsoleOutput.C:286:27: error: implicitly-declared 'GeochemicalSystem::GeochemicalSystem(const GeochemicalSystem&)' is deprecated [-Werror=deprecated-copy]
  286 |   GeochemicalSystem egs = egs_ref;
      |                           ^~~~~~~
In file included from /opt/civet/build_0/moose/modules/geochemistry/build/header_symlinks/GeochemistryReactorBase.h:13,
                 from /opt/civet/build_0/moose/modules/geochemistry/build/header_symlinks/GeochemistryConsoleOutput.h:12,
                 from /opt/civet/build_0/moose/modules/geochemistry/src/outputs/GeochemistryConsoleOutput.C:10,
                 from /opt/civet/build_0/moose/modules/geochemistry/build/unity_src/outputs_Unity.C:3:
/opt/civet/build_0/moose/modules/geochemistry/build/header_symlinks/GeochemicalSystem.h:128:23: note: because 'GeochemicalSystem' has user-provided 'GeochemicalSystem& GeochemicalSystem::operator=(const GeochemicalSystem&)'
  128 |   GeochemicalSystem & operator=(const GeochemicalSystem & src)
```

## Design
Fix the warnings.

## Impact
Minimum. Passing tests.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #16135

Still need to add a meowbuild spack test to next.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Thanks @loganharbour - really nice of you to fix my code like this!   Could you please check that the geochemistry unit tests still pass with these changes?   There are a lot of them!

**Comment by loganharbour** [comment]
Good call. Unfortunately, it looks like this fails in opt but not in debug (before and after my changes):
```
[----------] 7 tests from GeochemistryIonicStrengthTest
[ RUN      ] GeochemistryIonicStrengthTest.sizeExceptions
```

This whole issue came about by my trying to get unit tests ran on coverage checks. That testing recipe is in and is good to go, but it looks like I'm going to have to revert it until we fix these issues.

**Comment by WilkAndy** [comment]
> Good call. Unfortunately, it looks like this fails in opt but not in debug (before and after my changes):
> 
> ```
> [----------] 7 tests from GeochemistryIonicStrengthTest
> [ RUN      ] GeochemistryIonicStrengthTest.sizeExceptions
> ```
> 
> This whole issue came about by my trying to get unit tests ran on coverage checks. That testing recipe is in and is good to go, but it looks like I'm going to have to revert it until we fix these issues.

Hang on, so the geochem unit tests fail for you?!  That's a disaster.   Which ones are failing?

**Comment by loganharbour** [comment]
I get a segfault on the listed test above in opt and they don't continue. Interestingly, like I said, they pass in dbg.

**Comment by WilkAndy** [comment]
> I get a segfault on the listed test above in opt and they don't continue. Interestingly, like I said, they pass in dbg.

Recently i've had to clobberall, recompile and then run the unit tests.  Otherwise i get a segfault (this occurs for all modules, not just geochem).  Could that be the problem?    Perhaps the heavy-handed clobberall is not actually necessary, but that's the only thing i've tried - perhaps `make clean` is enough, i don't know.

**Comment by loganharbour** [comment]
Yeah, I tried the same (clobber). Luckily, most of the infrastructure is ready to get the unit tests in the module coverage - but as to not stop general development, I just reverted it and will look into it tomorrow (or today, actually!). Will keep you updated.

**Comment by WilkAndy** [comment]
> Yeah, I tried the same (clobber). Luckily, most of the infrastructure is ready to get the unit tests in the module coverage - but as to not stop general development, I just reverted it and will look into it tomorrow (or today, actually!). Will keep you updated.

OK, that's really excellent.  I feel quite uncomfortable with geochem and PorousFlow if their unit tests aren't running.

**Review by milljm — APPROVED** [review]

**Pull request merged**
