### PR TITLE
new text formatting/logging idea...

### PR DESCRIPTION
**Pull request by rwcarlsen**
This is just meant mostly for discussion to see if people are interested in this kind of thing.

I added a ``logMsg`` function to MooseObject that can be used to log information conveniently.  It is variadic and in the printf style (uses the fmt library added to contrib).  The fmt library lives at http://github.com/fmtlib/fmt and is BSD licensed and trivial/quick to compile - just one h and one cc file.  All you have to do is overload the ``<< ostream`` operator for any arbitrary type and the log functions just do the right thing.

Usage looks like this:

```c++
logMsg("hello {} from {:<12} with cool formatting {:010.3f}\n", "world", "c++", 1.1);
logMsg("hello {} from {:^12} with cool formatting {:>10.3f}\n", "world", "c++", 1.1);
logMsg("hello {} from {:>12} with cool formatting {:^10.3e}\n", "world", "c++", 1.1);
logMsg("hello {} from {:12} with cool formatting {:.2g}\n", "world", "c++", 123.123456);
logMsg("hello {} from {:12} with cool formatting {:.8g}\n", "world", "c++", 123.123456);
```

with this output:

```
hello world from c++          with cool formatting 000001.100
hello world from     c++      with cool formatting      1.100
hello world from          c++ with cool formatting 1.100e+00
hello world from c++          with cool formatting 1.2e+02
hello world from c++          with cool formatting 123.12346
```

There is also a ``logTags({"tag1", "tag2", ...}, "format-string", args...)`` variant that allows tagging the log entry with certain labels.  We can then adjust MooseApp settings to control which log messages are printed or not (i.e. log levels - but more flexible).  Here is a sample of what a change to IterationAdaptiveDT logging might look like:

```diff
-    if (_verbose)
-    {
-      _console << "Limiting dt to sync with dt function time: "
-               << std::setw(9) << *_tfunc_times.begin()
-               << " dt: "
-               << std::setw(9) << dt
-               << '\n';
-    }
+    logTags({"lev-info", "verbose"}, "Limiting dt to sync with dt function time: {:9} dt: {:9}\n", *_tfunc_times.begin(), dt);
```

I think the tagging/levels could help simplify a lot of logic we have for printing/omitting output from the screen.  As sample usage, the changes in this PR convert a lot of the console logging as well as IterationAdaptiveDT to use these new functions with a significant net reduction of code (~100 lines) - not counting the fmt library added to contrib obviously.

@idaholab/moose-team Thoughts?

[EDIT] - related to #3808

### CODE REVIEW

**Comment by rwcarlsen** [comment]
ping @idaholab/moose-team - this is more fleshed out now and I am interested in thoughts.

**Comment by permcody** [comment]
Yeah it looks nice but I'm not super motivated to move to it. I'm comfortable with the ugly io manipulators even though engineers probably aren't.

**Comment by rwcarlsen** [comment]
No comment on the tagging?

**Comment by permcody** [comment]
Tagging or "log level" is cool! I think we should separate that idea from formatting.

**Comment by rwcarlsen** [comment]
It is difficult to separate the need to call a function for logging (vs bare streaming) from tagging.  We could separate the fmt library and just use a simple variadic function.  But then you still have lots of wonky formatting to deal with - which actually can become even more cumbersome than in the bare streaming case - causing users to create stringstreams as a workaround anyway.  Another way around this would be to take the tags as function args, but then the function returns an object that can be streamed into (perhaps in addition to taking variadic args):

```c++
log({"tag1", "tag2"}, "my log message", var1, var2) << "additional message to append";
```

**Comment by permcody** [comment]
I'm going to close this PR for now. Nobody is jumping on it. File it away in "potential MOOSE 3.0 features".

**Pull request closed without merging**
