### PR TITLE
Update libmesh

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:
  - We need to free what ExodusII malloc()'ed.
  - Use latest poly2tri master
  - EIM fix for meshes with multiple dimensions
  - Add MeshBase::all_second_order_range()
  - Unit perflog

@roystgnr is there anything in here worth adding to the newsletter about?

### CODE REVIEW

**Comment by lindsayad** [comment]
doing this quick follow-on update for @YaqiWang and Griffin valgrind targets

**Comment by dschwen** [comment]
Mark's preconditioner reuse?

**Comment by lindsayad** [comment]
I think that PR is going to take a little bit of time

**Review by loganharbour — DISMISSED** [review]
Please update `LIBMESH_REV=` in `docker_ci/Dockerfile` to reference the libmesh commit.

This is a temp fix... should be able to get rid of this in time.

**Review by milljm — DISMISSED** [review]
👍 

Keep an eye on this one while it enters Next. This will be the first push to update the Apple Silicon channel via CI.

**Comment by lindsayad** [comment]
still getting valgrind errors

**Comment by lindsayad** [comment]
will need to wait on https://github.com/libMesh/libmesh/pull/3210

**Review by cticenhour — CHANGES_REQUESTED** [review]
Seeing some thread failures in heat conduction and BISON on the newest package with Monterey and Xcode 13.3 that might be related to the recent `scoped_lock` changes in libmesh/libmesh#3176. Fell through the cracks due to the OS differences in some of the newer and older Mac build boxes. Still investigating @lindsayad and will reach out with you when I know more, but I just wanted to put a hold here until I can confirm we don't need a libmesh change.

**Comment by lindsayad** [comment]
I would be surprised if it has anything to with the lock-type change. I can run with `ThreadSanitizer` if you tell me the tests

**Comment by cticenhour** [comment]
I am surprised too, just seeing a lot of it in the stack trace. Will send you some notes on Slack.

**Comment by YaqiWang** [comment]
Any news? I really want the valgrind error on Griffin devel gets fixed.

**Comment by lindsayad** [comment]
Just updated the hash to include https://github.com/libMesh/libmesh/pull/3210. So if this passes, then I think we're good to go

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
