### PR TITLE
Modify thermal BCs to allow use of other variable sets for CNSFV

### PR DESCRIPTION
**Pull request by GiudGiud**
See #18626 

Adds tests for the these BCs

### CODE REVIEW

**Comment by GiudGiud** [comment]
not even wrecked by precheck. I m getting better

**Review by lindsayad — COMMENTED** [review]
These tests make the BC blocks look kind of silly with the repeat of variable = u and T = u. Perhaps the "temperature" variable could be non-required and if not provided, then `_T` would be initialized as a const-reference to `_u`?

**Comment by GiudGiud** [comment]
sounds good. Will do then I ll ping you

**Comment by GiudGiud** [comment]
@lindsayad should be good now

**Comment by GiudGiud** [comment]
jk what did I do

**Comment by GiudGiud** [comment]
now, maybe

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
