### PR TITLE
Modify mesh for pressure-dep thermal mortar contact test

### PR DESCRIPTION
**Pull request by sapitts**
Modification to the MOOSE generated mesh to avoid alignment of nodes in the primary and secondary surfaces which had been sporadically giving this error: 

> Nodes on primary and secondary surfaces are aligned. This is causing trouble when identifying projections from secondary nodes when performing primary node projections.

Minor changes to the gold file with the updated mesh size are included in this PR

Refs #20658

### CODE REVIEW

**Comment by dschwen** [comment]
YES! That fixes my issue.

**Review by dschwen — APPROVED** [review]
Thank you!

**Comment by sapitts** [comment]
I'm glad this solves the issues. Thanks for the merge -- I had thought you were just going to cherry-pick this commit :-)

**Comment by dschwen** [comment]
I did cherry-pick to check if it works. And it did. So in she goes!

**Pull request merged**
