### PR TITLE
PorousFlow FluidFlower example

### LINKED ISSUE #24590: PorousFlow: add FluidFlower example
## Reason
@WilkAndy and I were involved in an international modelling benchmark study on CO2 storage (The FluidFlower - https://fluidflower.w.uib.no/fluidflower-international-benchmark-study/)  where we used MOOSE to get really good results compared to the experiments. These results are now available in publications, so we can add an example to the PorousFlow module.

## Design
A simplified example of our model that won't take as long to run. 

## Impact
Users will be able to reproduce our published results

### PR DESCRIPTION
**Pull request by cpgr**
No code - just an example and updated documentation

Closes #24590

### CODE REVIEW

**Comment by cpgr** [comment]
I'm really failing with this one...

I made a PR to large_media which is in, so I have done the following
```
cd moose/large_media
git checkout master
git pull
```
and then I think everything is ok:
```
git log
commit 169ee0ce6031bcb04902948faff2cea0b40b28bd (HEAD -> master, origin/master, origin/HEAD)
Author: Chris Green <cpgr@users.noreply.github.com>
Date:   Thu Oct 12 23:12:33 2023 +1100

    FluidFlower examples added (#50)
    
    Refs #24590
```

So I step out of large_media, git add, git commit, git push to this PR but something obviously has gone wrong?
```
cd ..
git add large_media
git commit
git push origin ffex
```

**Comment by cpgr** [comment]
Hi @WilkAndy - could take a read of this when you get a chance?

https://mooseframework.inl.gov/docs/PRs/25709/site/modules/porous_flow/fluidflower.html

**Comment by GiudGiud** [comment]
If your changes have made it into large media and we 've updated large_media you dont need a submodule update now

**Comment by MengnanLi91** [comment]
There are some conflicts with next, please rebase the PR. Besides that, all look good

**Review by GiudGiud — APPROVED** [review]
did the rebase, looks good

**Comment by cpgr** [comment]
Thanks @MengnanLi91 and @GiudGiud - I'd forgotten about this one!

**Pull request merged**
