### PR TITLE
Setup SQA documents for python

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #18910)

F-07 from 2020 MOOSE/BISON Assessment

### CODE REVIEW

**Comment by aeslaughter** [comment]
@permcody @cticenhour @loganharbour This sets up the documents for moose/python. If you run "./moosedocs.py check" in python/doc it will give you a list of things that need to change. Also, you might want to go through some of the templates to make sure the default framework content makes sense. That should probably be done for all the modules and applications.

This same kind of things can be done for CIVET, the exception is that the sqa directory you should load the basic template (e.g., https://github.com/idaholab/moose/blob/next/framework/doc/content/templates/sqa/far.md.template). Those are the recreations of the INL templates.

Then you just need to add documentation for CIVET and figure out how you want to capture requirement/design/issue content. I would recommend creating a new MooseDocs extension, like the appsyntax, that reads the information from somewhere in CIVET. You should then be able to create all the same linkage that we have MOOSE. I don't think it will be a huge lift and will get someone comfortable working in the system.

**Comment by cticenhour** [comment]
- Griffin patch is [here](https://github.inl.gov/ncrc/griffin/pull/988)
- Mastodon patch is [here](https://github.com/idaholab/mastodon/pull/396)
- RELAP-7 patch is [here](https://github.inl.gov/ncrc/relap-7), though I now see the repository as a private archive (along with a few others, like marmot)? 

@loganharbour how do we want to approach getting all of this in? 

Also tagging @zachmprince, @cbolisetti, @bwspenc, and @joshuahansel for awareness.

**Comment by loganharbour** [comment]
I'm dragged down with the GHE transition. Won't be in a good place to facilitate until this afternoon at the earliest

**Comment by aeslaughter** [comment]
@cticenhour I feel sorry for you, but not enough to help you, please don't hurt me.

**Comment by cticenhour** [comment]
@aeslaughter Ha! No promises. 😄 Hope you're doing well!

**Review by permcody — APPROVED** [review]

**Comment by cticenhour** [comment]
Failed apps have patched ready.

**Pull request merged**
