### PR TITLE
Avoid redundancy and use libMesh::Elem::build() for shorter code

### PR DESCRIPTION
**Pull request by nmnobre**
## Motivation
The list of element types is duplicated in every file where it is an option for users to chose. This can become obsolete as not every instance may be modified when a new element type is added

## Design
A single enum for all elem types, used in the relevant source files, especially the validParams elem_type parameter

## Impact
Code cleanup

Hi @roystgnr, @GiudGiud,

I believe this addresses the issues raised in #25685 that don't really belong there.
I couldn't decide where to place `LIST_GEOM_ELEM` so please just let me know where you'd like it to be (and what you'd like it to be named).

Cheers,
-N

### CODE REVIEW

**Review by roystgnr — DISMISSED** [review]
I love this; let's give others time to chime in before merging though.

**Review by lindsayad — DISMISSED** [review]
very nice code line reduction!

**Review by GiudGiud — DISMISSED** [review]
love it too

**Comment by GiudGiud** [comment]
When the non-unity build fails it means you are missing a header. Here elemGenerator needs the right utility header

in the unity build, it got that header from another file in the same folder (unity means making all the moose files be compiled together on a per-folder basis)

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Thanks @nmnobre !

**Pull request merged**
