### PR TITLE
Add MooseServer autocompletion for partial inputs and snippets

### PR DESCRIPTION
**Pull request by brandonlangley**
refs #22766

### CODE REVIEW

**Comment by brandonlangley** [comment]
@dschwen -

This MooseServer update to handle autocompletion for all of the partial input cases is finished.

I have been testing it using the `wasp_server_experimental` branch of your VS Code extension.

Testing for the partial input autocomplete scenarios has been added to `MooseServerTest` also.

I do not have the ability to assign pull requests to people but could you review this for merging?

**Comment by brandonlangley** [comment]
@dschwen -

This is finished again from my side and ready for your review and any testing that you want to do.

This PR was originally only going to add autocomplete support for all the partial input cases, e.g.,

 - parameter missing value after equal sign case
 - missing blocks and subblocks terminator case
 - partial parameter name case filtering on prefix
 - partial block name case also filtering on prefix
 - unclosed block start brace without name case

However after we briefly chatted in Oak Ridge last week, I have added two other updates of note:

 - the sever can now handle multiple documents instead of the previous limitation of one input per process
 - the server now checks for the client snippet capability and formats completion snippets when supported

And some other smaller changes are included like only adding autocomplete values with defaults.

Let me know if you have any issues, I have been using your VS Code extension to test integration.

**Review by dschwen — APPROVED** [review]
This looks fine to me. I'll build this and give it a go myself.

**Comment by dschwen** [comment]
Ok, this feels great now! I'll prepare an extension release.

**Comment by loganharbour** [comment]
Please reach out to the conda folks whenever updating these; we failed to update the current `moose-dev` version in documentation in this PR

**Pull request merged**
