### PR TITLE
Compute only materials that are needed

### LINKED ISSUE #21792: Execute only materials that provide required properties
## Reason
Materials are executed in multiple MOOSE stages,: Output, UserObjects, Kernels, AuxKernels.
Not all Material objects need to be run in every stage.

## Design
Use a design similar to the on demand material property computation in the Mortar constraint system.

## Impact
Better performance and less surprising behavior.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #21792

### CODE REVIEW

**Comment by dschwen** [comment]
This is not quite there yet (I still have two locally failing modules tests), but let's see what CIVET says.

**Comment by joshuahansel** [comment]
THM changes: 👍

**Comment by YaqiWang** [comment]
Impact to Griffin is not very big. We can help fix that once this is passing moose tests.

**Comment by dschwen** [comment]
No

**Comment by dschwen** [comment]
no

**Pull request closed without merging**
