### PR TITLE
Use dim 1 for creating the default empty mesh

### LINKED ISSUE #8327: Doc string for MooseMesh/dim is not accurate
### Description of the enhancement or error report
It says that `This is completely ignored for ExodusII meshes!`, but actually not.
https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L191 causes the default spatial dimension of the mesh is 3 regardless of the actual dimension of the mesh. I discovered this with our custom mesh extruder with a 2D exodus mesh file where we check if the mesh dimension and the mesh spatial dimension are the same. Once we specify `Mesh/dim=2 or 1` in the input, the extruder will work fine.

### Rationale for the enhancement or information for reproducing the error
Something is not very right. I suspect we should use dim=1 to construct the default empty mesh.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact except my particular mesh extruder.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #8327.

Also try to see if changing the default dimension will affect anything.

### CODE REVIEW

**Comment by YaqiWang** [comment]
We do have something depending on this although moose framework, modules and most of apps do not...

**Comment by YaqiWang** [comment]
We do have R7 and Maggie depending on this although moose framework, modules and most of apps do not... @andrsd @dschwen any thoughts? To me this change is the right thing, but I am willing to be persuaded.

**Comment by andrsd** [comment]
The current code looks at the dimension specified by an input parameter and uses that to construct the objects. Why is this incorrect?

In my opinion, the applications should have a chance to say what dimension their meshes are. If people agree that 1D is better than the current default (which is 3D), than you need to change that input parameters...

If you decided to change this because extruder did not work, than may be you need to fix that instead of `MooseMesh`. However, I cannot help here. I do not know how that system works...

**Comment by YaqiWang** [comment]
I am not sure too. But the doc side `dim` should not be valid for `FileMesh`, which make perfect sense because the mesh file already contains the dimension information like in Exodus. My understanding is that the spatial dimension can increase during mesh construction but cannot reduce. So changing the default spatial dimension for the empty mesh, which we start with, to one should be the right thing to do. I am guessing it is failing R7 because although R7 mesh is 1D, but its spatial dimension is 3D and the correct spatial dimension is never set during the mesh creation, which only adding 1D elements. Maybe somewhere in R7, calling `set_spatial_dimension(3)` will fix the issue. My mesh extruder only works for exact 2D or 1D mesh, but it will have no idea if a mesh is truly 1D or 2D if spatial dimension is set to 3 unless to check the coordinates of all nodes. I guess we will need a libMesh expert to comment on this either @jwpeterson or @roystgnr ?

**Comment by andrsd** [comment]
RELAP-7 have its own MooseMesh-derived object. I can try this PR with it and using `set_spatial_dimension` and see if that works...

**Comment by roystgnr** [comment]
At the libMesh level, MeshBase::mesh_dimension() ought to be deprecated soon, IMHO.  Ever since we started supporting multiple element dimensions in the same mesh, the only sane way to query what's going on in your mesh has been MeshBase::elem_dimensions().

We probably could make elem_dimensions() work even better, though... right now there's a delay between add_elem() and cache_elem_dims() (via prepare_for_use() typically) during which the cached dimension info isn't consistent.  It wouldn't be hard to just have add_elem() update _elem_dims on the fly.

**Comment by roystgnr** [comment]
spatial_dimension() should still have a sane meaning... but in theory we're also increasing it automatically via cache_elem_dims() via prepare_for_use(); the only time user code should need to futz with it is when you want to decrease it for some reason.

**Comment by andrsd** [comment]
Ok, `set_spatial_dimension()` did the trick for RELAP-7. And it is probably what we needed to use anyway. I can even update RELAP-7 with the patch upfront, so your PR will not fail with it...

**Comment by YaqiWang** [comment]
Thanks @andrsd . Replying @roystgnr maybe we just need to rename `mesh_dimension()` to `max_elem_dimension()`? We can also add another one `min_elem_dimension()`.

**Comment by permcody** [comment]
No - it's perfectly fine to have lower dimensional elements in higher dimensional space. Think 2D quads in the xz plane for instance.

**Review by permcody — CHANGES_REQUESTED** [review]
Please modify the default dim parameter instead.

**Comment by friedmud** [comment]
Let me just say that we need to remember that 99.99999% of users only use a single dimension.  Their mesh dimension and element dimensions always match.

Let's be sure to not make life complicated for the vast majority of users by making something unintuitive.

This is just your everyday public service announcement about not screwing up normal users when creating advanced capability.  Feel free to ignore :-)

**Comment by permcody** [comment]
@friedmud - see my comments on the ticket #8327. I don't think this will screw anything up with normal users but I also don't think the current change is correct either. I think @YaqiWang's check is overzealous.

**Review by permcody — APPROVED** [review]

**Comment by friedmud** [comment]
@permcody sure - My comment was really more general... when we're discussing things like removing `mesh_dimension()`, etc. (which I'm not saying are necessarily _bad_ ideas) we need to be careful that we don't alienate people who just need to get simple stuff done...

Just a comment - nothing more 😄

**Pull request merged**
