### PR TITLE
Add postprocessor that calculates effective K from KI, KII, KIII

### LINKED ISSUE #5261: Postprocessor to calculate mixed-mode effective K
I will add a postprocessor that combines mixed-mode stress intensity factors KI, KII, KIII into an effective K assuming self-similar crack growth. See Anderson chapter 2 for reference.

### PR DESCRIPTION
**Pull request by backmari**
closes #5261

@bwspenc

### CODE REVIEW

**Comment by permcody** [comment]
@backmari - no worries here. Marmot was in the middle of an incompatible update with MOOSE. I invalidated the failure, should pass now.

**Comment by bwspenc** [comment]
This looks good.  I have a couple of questions:
1) It looks like this does not set up the vector postprocessor for the effective Ks.  Is that right?  We should add that.
2) What's the reference for the formula?  I found something kind of like it in equation 2.63 in Anderson's book for computing G as a function of the 3 Ks. I'm wondering if K effective is the standard name for this quantity.

**Comment by backmari** [comment]
Thanks @bwspenc!
1) Oh yes, you are right, I need to fix that.
2) Yes it's the same one, but I have converted the energy release rate G to a stress intensity factor. I don't know if there is any established term. I think we also called it "equivalent KI" at some point, maybe that's better.

**Comment by backmari** [comment]
@bwspenc I found that "equivalent K" is used in the literature and changed the name to that.

**Pull request merged**
