### PR TITLE
Add test for vector periodic BC

### LINKED ISSUE #17823: Periodic BC on vector variables fails
## Bug Description
If you try to apply a periodic BC to a vector variable, MOOSE chokes. Libmesh actually supports this though for the most part; it just needs a small code change to let them work properly. This issue will be fixed once a PR is in to libmesh that fixes this, and the MOOSE submodule is updated to include it.

## Steps to Reproduce
Run, for instance, this input.

```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 10
  ny = 10
  nz = 0
  xmax = 40
  ymax = 40
  zmax = 0
  elem_type = QUAD4
[]

[Variables]
  [./u]
    order = FIRST
    family = LAGRANGE_VEC
  [../]
[]

[Kernels]
  [./diff]
    type = VectorDiffusion
    variable = u
  [../]

  [./forcing]
    type = VectorBodyForce
    variable = u
    function_x = 'exp(-((x-5)^2+(y-5)^2))'
    function_y = 'exp(-((x-35)^2+(y-35)^2))'
  [../]

  [./dot]
    type = VectorTimeDerivative
    variable = u
  [../]
[]

[BCs]
  [./Periodic]
    [./x]
      variable = u
      primary = 3
      secondary = 1
      translation = '40 0 0'
    [../]

    [./y]
      variable = u
      primary = 0
      secondary = 2
      translation = '0 40 0'
    [../]
  [../]
[]

[Executioner]
  type = Transient
  dt = 1
  num_steps = 6
  solve_type = NEWTON
[]

[Outputs]
  execute_on = 'timestep_end'
  file_base = vector_out
  exodus = true
[]

```

## Impact
Got a class project depending on this, but already fixed it in the libmesh side. Just need to submit a PR.

### PR DESCRIPTION
**Pull request by gridley**
closes #17823 

**This will only work after the libmesh submodule is updated to include [this PR](https://github.com/libMesh/libmesh/pull/2927)**

## Reason
Who wouldn't want periodic BCs on vector variables? They're awesome.

## Design
Adds a test.

## Impact

My class project won't get an F. And this will probably help others out at some point as this is a pretty common functionality to want.

### CODE REVIEW

**Review by loganharbour — DISMISSED** [review]

**Comment by loganharbour** [comment]
Reminder for myself to re-test once https://civet.inl.gov/event/68303/ gets in.

**Comment by loganharbour** [comment]
@gridley wanna add a ticket reference to your commit so we can get this in?

**Comment by gridley** [comment]
> @gridley wanna add a ticket reference to your commit so we can get this in?

ah ya, silly me

**Comment by gridley** [comment]
should be good now

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
