### PR TITLE
Add SimpleACInterface Kernel and test file

### PR DESCRIPTION
**Pull request by Biyss**
### Complete each of the following items before creating a PR
- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

### CODE REVIEW

**Comment by dschwen** [comment]
What do you think @amjokisaari? I think it looks good!

**Comment by amjokisaari** [comment]
Yeah, I think this is great :)  Is there a companion one for CH?

**Comment by dschwen** [comment]
There will be.

**Comment by amjokisaari** [comment]
Fabulous :)

Why are you on github!? Take your vacation!

**Comment by permcody** [comment]
👍

**Comment by Biyss** [comment]
Happy with my first contribution:)

Get Outlook for iOS




On Fri, Jun 10, 2016 at 7:31 AM -0600, "Cody Permann" <notifications@github.com> wrote:












👍

**Pull request merged**
