### PR TITLE
Addition of Uniform, Normal, Beta, Weibull and Triangular distributions in the stochastic_tools module

### PR DESCRIPTION
**Pull request by alfoa**
This PR introduces a new contrib library and the support in the stochastic_tools modules of 5 probability distributions. Additional distributions can be added in case needed by specific users.
Test cases have been added.

### CODE REVIEW

**Comment by alfoa** [comment]
@joshua-cogliati-inl

**Comment by dschwen** [comment]
That commit history could use some cleaning up...

**Comment by permcody** [comment]
A couple of things to get started here. This looks like the whole history of CROW? That's already been open-sourced but I guess this is different enough that we don't have copyright issues here? Also, we have a plan to deal with BOOST. We would like to distribute it within the MOOSE redistributable package and/or pick it up in Linux package managers. Once we do that, I'd like to see all the classes that call BOOST use the libMesh configuration variable to determine whether BOOST has been linked in or not and print error messages in the latter case. This will allow us to use BOOST without requiring it for everyone.

@alfoa - when you are available - let's chat over the details.

**Comment by alfoa** [comment]
yes we realized the problem with the history. We are removing it since it was not supposed to be there. Please keep this on hold. I will tag you in another post when we fixed this.

Regarding the chat, I will be back at work on Friday. I will stop by as first thing in the morning.

Thanks

Andrea

**Comment by joshua-cogliati-inl** [comment]
Hm, the git foo required to clean up the history will be a bit challenging.  https://stackoverflow.com/questions/12858199/how-to-rebase-after-git-subtree-add and https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

Alternatively, we could just flatten it to one commit:
https://github.com/alfoa/moose/tree/crow_contrib_flat

We'll have to figure out what to do about boost.

**Comment by permcody** [comment]
Can you guys just delete boost from this PR? Yes I realize it won't compile but we'll get a chance to at least review the code in the mean time. We are working on making BOOST available so we'll be able to test this out soon. It's virtually impossible to review or make suggestions with the way it sits. 

Let's not worry about the history just yet, we'll deal with that later.

**Comment by joshua-cogliati-inl** [comment]
Since it removes history, I created a separate pull request with no boost and a single commit: https://github.com/idaholab/moose/pull/9292

**Comment by dschwen** [comment]
Replaced by #9292

**Pull request closed without merging**
