### PR TITLE
Misc fracture_flow test now passes in parallel

### LINKED ISSUE #13318: misc fracture_flow test to work in parallel
## Reason

We want to be able to use "-p 2" in the test receipe for the misc module.

## Design

I want the misc/test/tests/fracture_flow/single.i test to work in parallel.  I had forgotten about this test.  It's actually quite nice, so i'd like to leave it.  I'll also add a pointer to the latex documentation from the PorousFlow fracture-flow example documentation, because the latex documentation is actually pretty good, but i haven't time to markdown it all and merge it with the PorousFlow stuff

## Impact

Better test coverage

### PR DESCRIPTION
**Pull request by WilkAndy**
Just a nonzero abs_zero was needed, but i cleaned the input file a little and added a pointer to the documentation from the PorousFlow doco.

Fixes #13318

### CODE REVIEW

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for the merge, @permcody.   @tophmatthews  - the misc tests now pass in parallel, according to my computer.

**Comment by permcody** [comment]
OK - good - need to get a new target up there.

**Comment by WilkAndy** [comment]
That's up to you guys, right?

**Comment by permcody** [comment]
yes

**Comment by milljm** [comment]
Creating a target now: https://github.com/idaholab/civet_recipes/pull/1278
Not sure how many here can even go to that link.

**Pull request merged**
