### PR TITLE
Update PolycrystalVoronoiVoidIC to use PolycrystalVoronoi user object

### PR DESCRIPTION
**Pull request by SudiptaBiswas**
Updates the grain structure from the PolycrystalVoronoi UserObject in PolycrystalVoronoiVoidIC. 
This is a preliminary version and I am open for design discussion for further improvement.
Expecting a bunch of test failures, will address them once the design is finalized. 

Refs #13267  

Ping @permcody @dschwen

### CODE REVIEW

**Comment by dschwen** [comment]
My design suggestion was to create a separate IC object to put down the voids. That way you could avoid changing the interface in `PolycrystalUserObjectBase`. The get grain centers method does not necessarily make sense for things like the EBSD reader.

**Comment by milljm** [comment]
@SudiptaBiswas [WIP] tells civet not to perform any operations :)

**Comment by SudiptaBiswas** [comment]
If we move the void creation and associated value assignment into the UserObject, we miss out the diffuse interface creation from the base classes of PolycrystalVoronoiVoidIC.

**Comment by dschwen** [comment]
> If we move the void creation and associated value assignment into the UserObject, we miss out the diffuse interface creation from the base classes of PolycrystalVoronoiVoidIC.

Then this may need to be moved up to a common parent class.

**Comment by SudiptaBiswas** [comment]
This would mean migrating `SmoothCircleBaseIC` into an UserObject class. Is that what you are suggesting?

**Comment by dschwen** [comment]
Oh, I see what you are saying. How about making `PolycrystalVoronoiVoidIC` dynamic cast the user object to your specific class. Then you don't have to add the interface to the OU base class.

**Comment by SudiptaBiswas** [comment]
I am not sure if dynamic cast is necessary, directly coupling `PolycrystalVoronoi` works.

**Comment by dschwen** [comment]
My suggestion was to have a `PolycrystalVoronoiVoid` UO inherit from `PolycrystalVoronoi`, and only add the bubble center interface to `PolycrystalVoronoiVoid`. You will need a dynamic cast in your IC top `PolycrystalVoronoiVoid` in order to access that interface.

**Comment by SudiptaBiswas** [comment]
Moving VoidCenter calculation to UO complicates things. We are again either missing out information from base class ICs or duplicating things (example: void radius calculation). I have given it a try earlier and passing the grain center information from the PolycrystalVoronoi to the IC seems cleaner to me.

**Comment by permcody** [comment]
This looks good to me. @dschwen - I had a lot of the same design discussion that you pointed out too. I talked to Sudipta about all of this and I think the design she's proposing here is actually the best in terms of minimizing code duplication, while still getting the important information she needs to make this IC correctly. Let me know if you have any other concerns, otherwise I think this is good to go!

**Review by permcody — APPROVED** [review]

**Review by dschwen — APPROVED** [review]

**Pull request merged**
