### PR TITLE
Add SLEPc support through PETSc submodule

### PR DESCRIPTION
**Pull request by fdkong**

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
If we're adding this support, then is there any reason not to set `SLEPC_DIR` in the `update_and_rebuild_libmesh.sh` script when the user is falling back on the petsc submodule?

<pre>
if [ -z "$PETSC_DIR" ]; then
  echo "We could not find an installed PETSc (no PETSC_DIR environment variable set), so the"
  echo "PETSc submodule will be used. You may see some test failures until we officially support the"
  echo "PETSc maint branch."
  echo "IMPORTANT: If you did not run the update_and_rebuild_petsc.sh script yet, please run it before building libMesh"
  export PETSC_DIR=$SCRIPT_DIR/../petsc
  export PETSC_ARCH=arch-moose
  <b>export SLEPC_DIR=$PETSC_DIR/$PETSC_ARCH/externalpackages/git.slepc</b>
</pre>

**Comment by fdkong** [comment]
> If we're adding this support, then is there any reason not to set `SLEPC_DIR` in the `update_and_rebuild_libmesh.sh` script when the user is falling back on the petsc submodule?
> 
> if [ -z "$PETSC_DIR" ]; then
>   echo "We could not find an installed PETSc (no PETSC_DIR environment variable set), so the"
>   echo "PETSc submodule will be used. You may see some test failures until we officially support the"
>   echo "PETSc maint branch."
>   echo "IMPORTANT: If you did not run the update_and_rebuild_petsc.sh script yet, please run it before building libMesh"
>   export PETSC_DIR=$SCRIPT_DIR/../petsc
>   export PETSC_ARCH=arch-moose
>   export SLEPC_DIR=$PETSC_DIR/$PETSC_ARCH/externalpackages/git.slepc

We do not need this. I have changed libmesh configuration so that it can automatically detect SLEPc from where PETSc lives. 

BTW, SLEPc does not live in $PETSC_DIR/$PETSC_ARCH/externalpackages/git.slepc

It lives in the same place as PETSc. We could just think about we do not set hyper_dir or super_dist_dir, and we should pick them up automatically

**Comment by fdkong** [comment]
```
fn604208:lib kongf$ pwd
/Users/kongf/projects/petsc/arch-darwin-c-dbg-option-data-base/lib
```

```
fn604208:lib kongf$ ls
libHYPRE-2.16.0.dylib		libfblas.a			libparmetis.dylib		libpetsc.3.011.dylib		libptscotch.a			libptscotchparmetis.a		libscotcherrexit.a		libslepc.3.011.dylib		libsuperlu_dist.6.dylib		petsc
libHYPRE.dylib			libflapack.a			libpetsc.3.011.3.dylib		libpetsc.dylib			libptscotcherr.a		libscotch.a			libscotchmetis.a		libslepc.dylib			libsuperlu_dist.a		pkgconfig
libesmumps.a			libmetis.dylib			libpetsc.3.011.3.dylib.dSYM	libptesmumps.a			libptscotcherrexit.a		libscotcherr.a			libslepc.3.011.2.dylib		libsuperlu_dist.6.1.1.dylib	libsuperlu_dist.dylib		slepc
```

We see` libslepc.xxx` here.

**Comment by fdkong** [comment]
We should pick up everything that is installed through "--download-xxxx"

**Comment by lindsayad** [comment]
> We see` libslepc.xxx` here.

Yes of the course the libraries are there.

> BTW, SLEPc does not live in $PETSC_DIR/$PETSC_ARCH/externalpackages/git.slepc

You're telling me that that directory does not exist? Whenever I build SLEPc, I have PETSC_DIR pointing to my PETSc git root, PETSC_ARCH corresponding to the name I want to give, and SLEPC_DIR pointing to my SLEPc git root.

> I have changed libmesh configuration so that it can automatically detect SLEPc from where PETSc lives.

That's great

**Review by lindsayad — APPROVED** [review]

**Comment by fdkong** [comment]
> You're telling me that that directory does not exist? Whenever I build SLEPc, I have PETSC_DIR pointing to my PETSc git root, PETSC_ARCH corresponding to the name I want to give, and SLEPC_DIR pointing to my SLEPc git root.

Directory does exist, but the built lib does not present there. In other words, you should not point your `SLEPC_DIR` to `$PETSC_DIR/$PETSC_ARCH/externalpackages/git.slepc`

**Comment by lindsayad** [comment]
I see. Yea, I've usually had my SLEPc cloned outside of the PETSc tree, so I look like this with `SLEPC_DIR=$HOME/slepc` and `PETSC_ARCH=arch-moose`:
```
lindad@localhost:~/slepc/arch-moose((HEAD detached at v3.11.1))$ ls
include lib     obj     tests
```

**Comment by fdkong** [comment]
> I see. Yea, I've usually had my SLEPc cloned outside of the PETSc tree, so I look like this with `SLEPC_DIR=$HOME/slepc` and `PETSC_ARCH=arch-moose`:
> 
> ```
> lindad@localhost:~/slepc/arch-moose((HEAD detached at v3.11.1))$ ls
> include lib     obj     tests
> ```

Yes. You do not need to clone slepc any more, and PETSc will help you out with "--download-slepc"

**Comment by lindsayad** [comment]
When will we have `--download-moose` or `--download-libmesh`?

**Comment by YaqiWang** [comment]
You cannot be serious cause either moose, libmesh can do the similar thing ;-) Actually moose is doing with the two scripts.

**Comment by lindsayad** [comment]
> You cannot be serious cause either moose

No it's a fun joke. @fdkong used to always say he wanted `--download-moose`. It's interesting that there's the `--download-slepc` option since PETSc is a dependency of SLEPc and not the reverse.

**Comment by lindsayad** [comment]
Oh I guess PETSc already does have those download options 😆

**Comment by fdkong** [comment]
> No it's a fun joke. @fdkong used to always say he wanted `--download-moose`. It's interesting that there's the `--download-slepc` option since PETSc is a dependency of SLEPc and not the reverse.

We do have `--download-moose` or `--download-libmesh`?

**Comment by YaqiWang** [comment]
Really! Good to know.

**Pull request merged**
