### PR TITLE
Add integer stringify overloads 

### LINKED ISSUE #14593: Use std:to_string in Moose::stringify for integer types
## Reason
Having specific overloads for integer types that use `std:to_string` in `Moose::stringify` would avoid the slightly more expensive stream creation ([benchmarks]()) and help dissuade people from using to_string directly in the code (direct use should be discouraged as it might spill into floating point conversion which behaves differently than our stringify).
 
## Design
Add six overloads for signed and unsigned integers.

## Impact
Encourage more uniform code by dissuading the developers from making microoptimizations (.. by making a microoptimization at the framework level :-D).

### PR DESCRIPTION
**Pull request by dschwen**
Closes #14593

### CODE REVIEW

**Comment by dschwen** [comment]
@milljm what is going on here? Style changes requested in a file that this PR does not touch. Did you update clang-format on the CIVET boxes?

**Comment by milljm** [comment]
If it was me updating the machines, that was done about a month ago.

**Comment by permcody** [comment]
If you look at the commit it's talking about here (45e9739), that's from early December. We get that hash from running a "git merge-base" command between the devel branch and your branch. I don't see anything special about those commits that would have returned such an old commit from a month ago though. No, the git merge-base command didn't fail either because we check the return code after that command. So how did we end up with that commit? That's the question here and I don't see how that could have happened.

**Comment by dschwen** [comment]
Well, I have rebased and pushed and the check passed. I must have branched off of a very out dated devel branch...

**Review by permcody — APPROVED** [review]

**Pull request merged**
