### PR TITLE
Sept. 2018 MOOSEletter

### PR DESCRIPTION
**Pull request by aeslaughter**
@idaholab/moose-team
(refs #11447)

### CODE REVIEW

**Comment by permcody** [comment]
@idaholab/moose-team, @dschwen, @bwspenc 

Newsletter is pretty slim this month. Does anyone else have anything to add? Maybe run this command on your repo and see?

`git log --since=08/1/2018 --until=09/1/2018 --author="Your Name" --no-merges`

**Comment by lindsayad** [comment]
I don't have anything...

**Comment by YaqiWang** [comment]
@permcody feel free to add the custom problem support. Your guys made significant contributions anyway.

**Comment by permcody** [comment]
The custom problem stuff should be covered in the next newsletter. It was just merged.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
