### PR TITLE
Update FunctionSideAverage.md

### PR DESCRIPTION
**Pull request by MendesMichael**
Correct the documentation for FunctionSideAverage
Issue: #27328

### CODE REVIEW

**Comment by GiudGiud** [comment]
hello

you ll want to add the issue to the commit message to pass the automated CI
so 
```
git commit --amend
< add 'refs #27328' to the end of the commit message >
git push <name of your fork> -f
```

**Comment by GiudGiud** [comment]
no merge commits please. There are no merge conflicts here, you do not need to add a merge commit

**Comment by MendesMichael** [comment]
> no merge commits please. There are no merge conflicts here, you do not need to add a merge commit

Sorry, I am new to git, so I am still learning how to use it.

**Comment by GiudGiud** [comment]
no worries. If you `git reset --hard 05049ce` next you can try again the commands I wrote down

**Review by GiudGiud — APPROVED** [review]
thanks for the fix!

**Pull request merged**
