### PR TITLE
Fix broken civet next tests

### LINKED ISSUE #27628: Fix Broken CIVET Tests
### Bug Description

Merge of #27434 broke some next CIVET tests

### Steps to Reproduce

https://civet.inl.gov/event/180188/

### Impact

Broken tests need to be fixed.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #27628

### CODE REVIEW

**Comment by miaoyinb** [comment]
The broken tests are caused by randomness in triangulation. When using different numbers of cores, the generated TRI elements are slightly different. I tried to use average elem quality and size with a reasonable custom tolerances to cover all the cases (using `-p 1` as the gold). I did not try `-p 5` or `-p 7`, which failed in this case. 

To fix this, I did a comprehensive test using different `-p` numbers and adopt the mean values instead of the `-p 1` values as the gold.

**Comment by miaoyinb** [comment]
@GiudGiud @loganharbour FYI.

**Comment by miaoyinb** [comment]
You meant just using the same number in `max_parallel` and `min_parallel` to limit this? (and maybe have multiple tests with different parallel numbers?)

**Comment by GiudGiud** [comment]
> You meant just using the same number in max_parallel and min_parallel to limit this? (and maybe have multiple tests with different parallel numbers?)

this can be done.
Or simply a max_parallel = 3 if for example the results for p = 1, 2, 3 are consistent enough to pass the gold

**Comment by GiudGiud** [comment]
I m fine with this averaging.

**Comment by miaoyinb** [comment]
I think the motivation of fixing `p` is to remove the randomness so that Exodiff can be used instead. In that case, p = 1,2,3.. would all give different exo files.

I think the current average solution is better than a series of Exodiff tests.

**Comment by miaoyinb** [comment]
Also, my observation is once p>9, things are converged for this specific case and area/quality pp values not longer change.

**Comment by loganharbour** [comment]
> I think the current average solution is better than a series of Exodiff tests.

If this works, I agree.

**Comment by GiudGiud** [comment]
Test failures are unrelated

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
