### PR TITLE
Add option "skip_after_failed_timestep" to Predictor

### LINKED ISSUE #16796: Add option in Predictor to skip prediction after a failed time step
## Reason
Predictors like `SimplePredictor` are a great tools for increasing the simulation speed.
However, in certain situations it should be possible to omit a prediction.

For instance, if a time step is reduced according to a request by a material model (e.g., plasticity requires a smaller time step),
no prediction should be made in the new, reduced time step. Currently, the prediction is also applied in the new, reduced time step. If the direction of the prediction is not reasonable, this can be the death of a simulation since it may result in an (infinite) request of smaller time steps by the material. See also https://github.com/idaholab/moose/discussions/16628#discussioncomment-283595

Predictors should have an option to skip a prediction in a repeated time step after a failed time step.

## Design
`Predictor` parent class needs to track repeated time steps and should offer a possibility to skip a prediction via `shouldApply()`. 

## Impact
Improved capabilities in particular for solid mechanics; No breaking of any backward compatibility.

### PR DESCRIPTION
**Pull request by matthiasneuner**
- Added option "skip_after_failed_timestep" in Predictor
- Moved tracking of repeated timesteps from AdamsPredictor to Predictor
- Invoke shouldApply() and timestepSetup() of parent class (Predictor) in AdamsPredictor to consider correctly option "skip_after_failed_timestep"

Closes #16796

### CODE REVIEW

**Comment by loganharbour** [comment]
First - thanks for the contribution! Can you please add a test that utilizes this functionality?

**Comment by matthiasneuner** [comment]
> First - thanks for the contribution! Can you please add a test that utilizes this functionality?

Of course. Sorry for this split commit due to the trailing whitespace.

**Comment by matthiasneuner** [comment]
So, the last test was obviously too fragile. I recently discovered the `FailingProblem` functionality. I hope that it passes all the checks this time.

**Review by loganharbour — APPROVED** [review]
Great! 👍🏼 thanks for the contribution!

> Sorry for this split commit due to the trailing whitespace.

No worries! Feel free to squash commits on your next contribution!

**Pull request merged**
