### PR TITLE
Adds the ability to call python functions using system Python (Preview)

### PR DESCRIPTION
**Pull request by aeslaughter**
This is just a sneak preview for interested parties regarding the Python interface for control logic. We still need to add the correct configure options to libMesh (--enable-python) that will include and link the necessary python bindings. I have this running just using the OSX system python.

(refs #5680)

### CODE REVIEW

**Comment by permcody** [comment]
I see that you committed temporary files again. I'm sure David will love
that!

**Comment by friedmud** [comment]
WTF.

I vote 100000000000000000000000000000000x No to all of this.

No to linking Python into MOOSE.

Freaking no.

If they want to do this in Raven... then whatever.  That's their deal.

Not in MOOSE.

If you put this in MOOSE people will use it... and we'll have to support it... and it's going to be a goddamned nightmare:

```
I just tried to run my CL on a Cray and it doesn't work
```

```
I just installed my own python 3.2 into /junk/stuff and now my CL doesn't work.
```

```
I upgraded my Ubuntu installation and now CL doesn't work
```

```
I looked at my computer wrong and now CL doesn't work
```

And why the hell would we add --enable-python to libMesh?  It doesn't make any sense.  libMesh doesn't link python and has no business having tons of configure and everything for it.

**Comment by friedmud** [comment]
After calming down a bit I decided to temper my reaction and edit my comment :-)

I looked at the code and it's obvious that @aeslaughter has done a lot of work here... no reason for me to fly off the handle like that.

That said, I am still against this idea.  We should have a conference call tomorrow (Friday) morning to discuss the situation more.

I promise to be well behaved ;-)

**Comment by andrsd** [comment]
IIRC, even the RAVEN team said that Python brought them more grief then they expected. We do use some of it in RELAP-7, but we do not have tons of it (so we can change our files easily). I'd personally went with some other scripting language. I prefer one that does not assign meaning to whitespace characters and is more C-style. After all, people using MOOSE write C++, so C-like language would be a nicer option.
Also, I have some issues with the Python layer in RELAP-7 and I do not mind to rewrite it, so it is using something else...
However this might serve as a guideline to somebody who wanted to use Python with control logic in their app. Could we do something like this in an example maybe? I agree with @friedmud that it should not be an integral part of MOOSE....

**Comment by joshua-cogliati-inl** [comment]
First of all, @aeslaughter  thank you for working on this example.

Secondly, I personally love python (even google autocomplete knows this), but using it with C++ does not go as smoothly as I would like.  A certain system vendor doesn't seem to care much if the output of python-config is something that can actually be used to build a python module.  Python themselves don't worry too much about C++ compatibility (Python issue 8027 is still not fixed and was reported in 2010.)

I don't think making this an integral part of MOOSE is needed, but I do think that being able to use Python for MOOSE applications control logic is very useful.  So I agree with @andrsd that this could make a useful example.

**Pull request closed without merging**
