### PR TITLE
Make the pressure action require displacements,

### PR DESCRIPTION
**Pull request by GiudGiud**
Came up in #22567
Tying in issue #5624 for the pressure action

### CODE REVIEW

**Comment by GiudGiud** [comment]
@dschwen

**Comment by recuero** [comment]
According to the testing, it appears we are doing well in the apps when it comes to always defining displacements when using the pressure action. That makes sense I suppose since it's typically included in the `GlobalParams` block.

**Comment by recuero** [comment]
Will the examples run with this modification (now actually applying the pressure BC)?

**Comment by GiudGiud** [comment]
The examples are being ran as RunApp. So we know they run, the result may have been affected (for the better?)

**Comment by GiudGiud** [comment]
I've run the one in the framework and did not notice anything

**Review by recuero — APPROVED** [review]

**Pull request merged**
