### PR TITLE
Adds python based scripting tool for visualization

### PR DESCRIPTION
**Pull request by aeslaughter**
This adds chigger to the MOOSE python directory, this is the first step of getting new Peacock merged.
(refs #7451)

### CODE REVIEW

**Comment by aeslaughter** [comment]
I think this is ready to go, I am not sure where 8,256 comes from, perhaps the images. Cloc is giving me:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         173           1216           1426           4211
XML                              1              0              0             56
Markdown                         1              1              0              3
-------------------------------------------------------------------------------
SUM:                           175           1217           1426           4270
```

**Comment by aeslaughter** [comment]
Don't merge yet, I am tweaking something with colormaps.

**Review by permcody — APPROVED** [review]
This is huge commit. I don't see anything that really stands out with the exception of the missing headers. We can merge this now, or after the headers either way. How will the two peacocks coincide?

**Comment by aeslaughter** [comment]
I am putting in headers now and this doesn't contain any gui stuff, just the VTK visualization tools that will be underneath peacock.

**Comment by friedmud** [comment]
Are people actually going to want to use/run "chigger"?  If not, then the
name should probably be renamed to "scriptable_viz" or something a little
more descriptive.  If it's truly meant to be its own standalone thing, and
not just a support library then that's fine... let's just make sure we have
documentation for it.

**Comment by aeslaughter** [comment]
It is a stand-along thing, others are already using it. The name has
meaning: "A nasty, little mite to replace EnSight"

**Comment by friedmud** [comment]
No problem: I was just double checking.

**Review by permcody — APPROVED** [review]

**Pull request merged**
