### PR TITLE
Correct error running moose tests (python re.search pattern, support petsc 3.6.1 )

### PR DESCRIPTION
**Pull request by garvct**
I get the following error running the moose tests.

kernels/coupled_kernel_value.test_coupled_kernel_value_test............................................... OK
Traceback (most recent call last):
  File "./run_tests", line 24, in <module>
    TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/TestHarness.py", line 34, in buildAndRun
    harness.findAndRunTests()
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/TestHarness.py", line 195, in findAndRunTests
    self.runner.run(tester, command)
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/RunParallel.py", line 69, in run
    self.spinwait()
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/RunParallel.py", line 159, in spinwait
    self.returnToTestHarness(job_index)
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/RunParallel.py", line 135, in returnToTestHarness
    if not self.harness.testOutputAndFinish(tester, p.returncode, output, time, clock()):
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/TestHarness.py", line 340, in testOutputAndFinish
    (reason, output) = tester.processResults(self.moose_dir, retcode, self.options, output)
  File "/home/garvct/trunk/falcon-moose-dev-5.7.0-gmvolf-5.5.7/moose/python/TestHarness/testers/PetscJacobianTester.py", line 28, in processResults
    if float(m.group(1)) < float(self.specs['ratio_tol']) and float(m.group(2)) < float(self.specs['difference_tol']):
ValueError: invalid literal for float(): 1.00423e-16,

The problem is

   f = float('1.00423e-16,')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for float(): 1.00423e-16,

The output has the line

Norm of matrix ratio 1.00423e-16, difference 4.29988e-16 (user-defined state)

See line 26 (moose/python/TestHarness/testers/PetscJacobianTester.py)

Currently is

m = re.search("Norm of matrix ratio (\S+) difference (\S+) (user-defined state)", output, re.MULTILINE | re.DOTALL);

Should it be?

m = re.search("Norm of matrix ratio (\S+), difference (\S+) (user-defined state)", output, re.MULTILINE | re.DOTALL);

Thanks,
Cormac.

### CODE REVIEW

**Comment by jwpeterson** [comment]
What version of PETSc are you using?  This is their printout, it's conceivable that it changed recently...

**Comment by garvct** [comment]
Petsc 3.6.1

Thanks,
Cormac.

On Tue, Jul 28, 2015 at 1:38 PM, John W. Peterson <notifications@github.com>
wrote:

> What version of PETSc are you using? This is their printout, it's
> conceivable that it changed recently...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5458#issuecomment-125731812>.
>



-- 
Cormac Garvey
HPC Software Consultant
Scientific Computing
Idaho National Laboratory
Ph: 208-526-6294

**Comment by jwpeterson** [comment]
Yep, that changed [recently](https://bitbucket.org/petsc/petsc/commits/ca5d9af2d6be687272a3f5b7d6f17a55ce2023e0) in 3.6.1, and unfortunately MOOSE does not yet support 3.6.1.  We can't merge your fix as-is since it would break 3.6.0 builds.  Now if you know how to do a regex for "comma or no comma" that would be cool...

**Comment by jwpeterson** [comment]
Also, you just need to add a relevant ticket number (say #5162) to your git commit message in order to pass the "pre check" step of the CI.

**Comment by permcody** [comment]
Just add a question mark right after the comma (i.e. ",?")

**Comment by capitalaslash** [comment]
This solution does not work for me since `\S+` is greedy, the comma will be included anyway. The first group should be changed to `(\S+?),?`, see https://regex101.com/r/hI4eH4/1
Should I open a new bug report for this?

**Comment by permcody** [comment]
@capitalaslash you're right. So are you using PETSc 3.6.1? We still haven't advanced since we are awaiting another bugfix in PETSc. Your proposed solution should solve both cases. Go ahead and open an issue and if you'd like, put in a Pull Request as well.

**Comment by capitalaslash** [comment]
@permcody yes, I recently updated to 3.6.1. what bugfix are you referring to?
issue and pull request coming in a few.

**Comment by permcody** [comment]
We have been unable to get SuperLU working since PETSc 3.6. The PETSc team is working on fixing that regression and should have it in their main branch soon.  Thanks for catching this!

**Pull request merged**
