### PR TITLE
Solution user object can be constructed independently with replicated mesh

### LINKED ISSUE #10794: SolutionUserObject does not work with distributed mesh
## Rationale
We do not have to distribute the mesh used by the SolutionUserObject. Actually it may not even be a good idea. If desired, we could just issue a warning like what we did in exodus file output with distributed mesh.

## Description
While the simulation can still use the distributed mesh, we just construct the SolutionUserObject with the replicated mesh.

## Impact
Small tests using SolutionUserObject can be tested with distributed mesh.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #10794.

### CODE REVIEW

**Comment by YaqiWang** [comment]
This is the solution I am thinking. Making the mesh used by a solution user object also distributed will be extremely hard but most of times we do not have to.

**Comment by permcody** [comment]
Well this is really in the wrong direction. We really shouldn't be creating a separate copy of the Mesh to get around a design issue. For one thing this might just crash your machine if you tried to run it on a big distributed mesh. It would probably fail for pre-split meshes. What the motivation behind this? Are you trying to use it on a distributed mesh problem right now?

**Comment by YaqiWang** [comment]
The mesh used by solution user object can definitely be independent on the mesh used by calculation. They can be completely irrelevant. Are you talking about each processor keeping a copy of entire mesh used by solution user object? If the solution mesh is too big, the user will realize and probably find other solutions. The motivation of doing this is that, I have bunch of tests using solution user object for testing the convergence. Without solution user object, they are fine with the distributed mesh and I do want to make sure they are fine with future code changes.

**Comment by YaqiWang** [comment]
This is similar as using the pre-split mesh or non-split mesh for distributed mesh calculations. Most of times, users do not have to pre-split the mesh. If the solution mesh is small, user can afford to keep a copy on all processors. I donot think this is bad solution unless you have a better solution for solving my issue...

**Comment by permcody** [comment]
Hmm, OK - I see your point.

**Comment by YaqiWang** [comment]
I see yours too. I am thinking to have a control parameter `error_on_distributed_mesh` with default value to true. I can set it to false in my tests. What do you think?

**Comment by permcody** [comment]
I'm going to pass this off to @friedmud for a decision.

**Review by friedmud — APPROVED** [review]
This is good.  SolutionUserObject shouldn't care what the FEProblem is doing

**Comment by YaqiWang** [comment]
Thanks!

**Pull request merged**
