### PR TITLE
Trying to clean up scripts

### PR DESCRIPTION
**Pull request by aeslaughter**
Refs #5434

### CODE REVIEW

**Comment by permcody** [comment]
@gardnerru - @aeslaughter wants to clean up the scripts directory. This will impact your daily BISON testing so I want to make sure we coordinate with you.

**Comment by gardnerru** [comment]
when are you looking to do this? I am on PL until Aug 5. Currently the
nightly testing is down anyway. Jason H. has a ticket in for a fix. I guess
the test harness doesnt see use.moose.

On Thu, Jul 23, 2015 at 11:29 AM, Cody Permann <notifications@github.com>
wrote:

> @gardnerru <https://github.com/gardnerru> - @aeslaughter
> <https://github.com/aeslaughter> wants to clean up the scripts directory.
> This will impact your daily BISON testing so I want to make sure we
> coordinate with you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5435#issuecomment-124175079>.
>



-- 
Russell Gardner
Fuels Modeling and Simulation
Idaho National Laboratory
PO Box 1625
Idaho Falls, ID 83415-3840
208-526-2970

**Comment by aeslaughter** [comment]
There is a PR in MOOSE now to make the move.

**Comment by gardnerru** [comment]
I saw that right after I asked. Whatever you are doing isnt going to make
the nightly work any less. Bring the noise.

On Thu, Jul 23, 2015 at 11:36 AM, Andrew E Slaughter <
notifications@github.com> wrote:

> There is a PR in MOOSE now to make the move.
>
> On Thu, Jul 23, 2015 at 11:33 AM, Russell Gardner <
> notifications@github.com>
> wrote:
>
> > when are you looking to do this? I am on PL until Aug 5. Currently the
> > nightly testing is down anyway. Jason H. has a ticket in for a fix. I
> guess
> > the test harness doesnt see use.moose.
> >
> > On Thu, Jul 23, 2015 at 11:29 AM, Cody Permann <notifications@github.com
> >
> > wrote:
> >
> > > @gardnerru <https://github.com/gardnerru> - @aeslaughter
> > > <https://github.com/aeslaughter> wants to clean up the scripts
> > directory.
> > > This will impact your daily BISON testing so I want to make sure we
> > > coordinate with you.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/idaholab/moose/pull/5435#issuecomment-124175079>.
> > >
> >
> >
> >
> > --
> > Russell Gardner
> > Fuels Modeling and Simulation
> > Idaho National Laboratory
> > PO Box 1625
> > Idaho Falls, ID 83415-3840
> > 208-526-2970
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/idaholab/moose/pull/5435#issuecomment-124175897>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5435#issuecomment-124176658>.
>



-- 
Russell Gardner
Fuels Modeling and Simulation
Idaho National Laboratory
PO Box 1625
Idaho Falls, ID 83415-3840
208-526-2970

**Comment by jwpeterson** [comment]
If something breaks, I think @gardnerru promises to fix it... :smiley:

**Comment by gardnerru** [comment]
Sure, wait until Im on vacation to run the bus over me :)

On Tue, Jul 28, 2015 at 8:26 AM, John W. Peterson <notifications@github.com>
wrote:

> If something breaks, I think @gardnerru <https://github.com/gardnerru>
> promises to fix it... [image: :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5435#issuecomment-125626803>.
>



-- 
Russell Gardner
Fuels Modeling and Simulation
Idaho National Laboratory
PO Box 1625
Idaho Falls, ID 83415-3840
208-526-2970

**Pull request merged**
