### PR TITLE
Two tests demonstrating the dependency issues

### PR DESCRIPTION
**Pull request by YaqiWang**
tag @permcody ref. #6369.

### CODE REVIEW

**Comment by YaqiWang** [comment]
I added one more duplicating postprocessor called `*_another` in each test to illustrate the problem clearer.

**Comment by YaqiWang** [comment]
@permcody anybody is working on this?

**Comment by permcody** [comment]
I was and I made some progress with the interface changes that were merged
in a month or so ago. I've been trying to get back to it but I keep getting
sidetracked with other things. Will try to work on this.

**Comment by YaqiWang** [comment]
@permcody to be clear, I do not need these two dependency issues fully resolved by MOOSE because users can probably easily change their input to avoid the issue. On the other hand, I do want MOOSE error out when the issues are detected to make users aware so that they can fix their inputs. Hopefully this can reduce the burden from this task.

**Comment by permcody** [comment]
Right - I know that. I just haven't had much time to work on this.

**Comment by dschwen** [comment]
One year and one day since the last activity...

**Comment by dschwen** [comment]
Closing this. If this is still an _issue_, let's open an actual Issue and just link to 428b141

**Comment by YaqiWang** [comment]
I do not think this issue has been fixed. I hope MOOSE can error out for unresolved dependencies. It is still critical to us.

**Pull request closed without merging**
