### PR TITLE
Remove unnecessary test outputs

### PR DESCRIPTION
**Pull request by GiudGiud**
this probably wont pass test suite straight away

### CODE REVIEW

**Comment by GiudGiud** [comment]
umm doesnt look like it made the tests faster like I expected by reducing IO. 
oh well

**Comment by GiudGiud** [comment]
this ends up being a pretty dumb PR but still down for a merge
@cticenhour @loganharbour

**Review by loganharbour — APPROVED** [review]
Letting this run with the full test suite before merging

**Comment by GiudGiud** [comment]
that's a good idea. I ll wait

**Pull request merged**
