### PR TITLE
Fixed an issue for periodic boundary regarding displaced system

### LINKED ISSUE #7946: Make DisplacedSystem and NonlinearSystem consistent for periodic boundary condition
`DisplacedSystem` has a shorter ghosted vector than `NonlinearSystem` if its `DofMap` is not updated accordingly when creating a periodic boundary condition.

### PR DESCRIPTION
**Pull request by mangerij**
From @fdkong : Make `DisplacedSystem` and `NonlinearSystem` consistent for periodic boundary condition.

`DisplacedSystem` has a shorter ghosted vector than `NonlinearSystem` if its `DofMap` is not updated accordingly when creating a periodic boundary condition.

This commit fixed this issue by updating `DofMap` accordingly. Closes #7946 

also should close PR  #7947

Also adjusted input file for test to remove nullspace that caused exodiff and regolded.

### CODE REVIEW

**Comment by mangerij** [comment]
Oh this diffed again? Very odd! The difference is e-05... 

I'll just add abs_tol = 1e-04 or something to the test.

**Comment by fdkong** [comment]
@mangerij, please squash your two commits into one. I would remove `Merge branch 'fix_different_vector_length' of https://github.com/fdko`, because it will confuse people in the future.

**Comment by permcody** [comment]
That's not the problem here. The values being compared are below 3e-10.
This is just barely shy of our normal abs_zero (not to be confused with
abs_tol). Adjust that abs_zero parameter instead.

**Comment by mangerij** [comment]
@fdkong it passed

**Comment by fdkong** [comment]
@permcody, I am fine with PR.

**Review by permcody — APPROVED** [review]

**Pull request merged**
