### PR TITLE
Add interstitial velocity functor to PINSFVSpeedFunctorMaterial

### PR DESCRIPTION
**Pull request by snschune**
## Reason

It is convenient to have the interstitial velocity as `RealVectorValue` functor for 
some correlations.

## Design

Add a functor in `PINSFVSpeedFunctorMaterial`.

## Impact

None.

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]

**Comment by lindsayad** [comment]
The action uses the same gold file (via symlink) as the non-action, which is why you're getting an exodiff

**Comment by snschune** [comment]
The diffing test uses the wrong gold file. See this:
```
navier_stokes/test:finite_volume/pins/materials.check_material-action: Reading first file ... 
navier_stokes/test:finite_volume/pins/materials.check_material-action: Reading second file ... 
navier_stokes/test:finite_volume/pins/materials.check_material-action:   FILE 1: /data/civet2/moose/modules/navier_stokes/test/tests/finite_volume/pins/materials/gold/2d-rc_out.e
navier_stokes/test:finite_volume/pins/materials.check_material-action:    Title: 2d-rc_out.e
navier_stokes/test:finite_volume/pins/materials.check_material-action:           Dim = 2, Blocks = 1, Nodes = 77, Elements = 60, Nodesets = 4, Sidesets = 4
navier_stokes/test:finite_volume/pins/materials.check_material-action:           Vars: Global = 2, Nodal = 0, Element = 7, Nodeset = 0, Sideset = 0, Times = 2
navier_stokes/test:finite_volume/pins/materials.check_material-action: 
navier_stokes/test:finite_volume/pins/materials.check_material-action:   FILE 2: /data/civet2/moose/modules/navier_stokes/test/tests/finite_volume/pins/materials/2d-rc-action_out.e
navier_stokes/test:finite_volume/pins/materials.check_material-action:    Title: 2d-rc-action_out.e
navier_stokes/test:finite_volume/pins/materials.check_material-action:           Dim = 2, Blocks = 1, Nodes = 77, Elements = 60, Nodesets = 4, Sidesets = 4
navier_stokes/test:finite_volume/pins/materials.check_material-action:           Vars: Global = 2, Nodal = 0, Element = 5, Nodeset = 0, Sideset = 0, Times = 2
```

bit the test harness file looks fine and this shouldn't happen.
```
[Tests]
  issues = '#16756 #19472'
  design = 'PINSFVSpeedFunctorMaterial.md NSFVAction.md'
  [check_material]
    type = 'Exodiff'
    input = 2d-rc.i
    exodiff = 2d-rc_out.e
    requirement = 'The system shall be able to compute the speed, eg the norm of the interstitial velocity, in a porous media incompressible flow problem.'
    ad_indexing_type = 'global'
  []
  [check_material-action]
    type = 'Exodiff'
    input = 2d-rc-action.i
    exodiff = 2d-rc-action_out.e
    requirement = 'The system shall be able to compute the speed in a porous media incompressible flow problem from within the NSFVAction.'
    ad_indexing_type = 'global'
  []
[]
```

Any ideas how that could happen?

**Comment by GiudGiud** [comment]
they are symlinked, they are the same file. 
You need to change both input files so that both input files have the same output. 

Or break the symlink and regold one but that s less desirable

**Review by GiudGiud — APPROVED** [review]

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Thanks @snschune !

**Pull request merged**
