### PR TITLE
Pbs errors

### PR DESCRIPTION
**Pull request by vanwdani**
refs #22710
## Reason
PBS run tests don't exit cleanly sometimes and more information is needed.

## Design
A header file of the PBS exit codes and reworking of the `are_queued_jobs_finished.py`

## Impact
Allows for better understanding of failures of nightly tests due to PBS exits

### CODE REVIEW

**Comment by vanwdani** [comment]
@milljm

**Comment by vanwdani** [comment]
This probably needs a method to retrieve the PBS error number, then perform the modulo to determine the correct associated error if necessary.

**Comment by milljm** [comment]
> This probably needs a method to retrieve the PBS error number, then perform the modulo to determine the correct associated error if necessary.

Yeah I am not sure folks will care? I am still trying to figure out why we might need modulo. Considering that we have a `.previous_test_results.json` file, we will be able to print the exact post processing error/success/skip message (instead of an integer):

```pre
LWR/validation/HbepR1/analysis/H8364.HbepR1_H8364 .................................. [FINISHED,min_cpus=36] OK
LWR/validation/IFA_519/analysis/rod_DH.IFA_519_rod_DH ........................................... [HEAVY] SKIP
nitride/MTR/SNAP50/analysis.SNAP-50-57-669-BTS .............. [FINISHED,min_cpus=2] FAILED (MISSING GOLD FILE)
LWR/validation/IFA_677/analysis/Rod5.ifa677r1 ................................... [min_cpus=8] FAILED (ERRMSG)
TRISO/validation/AGR-1.AGR_1_Failed_CsSr_action .................................. [FINISHED] FAILED (CSVDIFF)
```

For jobs being killed due to PBS errors, I am certain we won't have a `.previous_test_results.json` anyway. So the only thing we can print is the PBS Schedulers reason for killing the job:

```pre
LWR/validation/HbepR1/analysis/A364.HbepR1_A364 ...................... [FINISHED,min_cpus=36] FAILED (JOB_EXEC_KILL_WALLTIME:Job exec failed due to exceeding walltime)
```

(this use to simply say `FAILED (TIMEOUT)` ). We have little room here for such a lengthy explanation. So we need to discus how to print these types of errors. I also don't like seeing the word FINISHED everywhere... I need to take a look at removing that when using --pbs options.

If I am not understanding your concern, can you reply with how and when you would want to see something like this printed:

```pre
simple_diffusion .............. [SIGKILL:terminate process - kill program] FAILED (9)
```
(or something similar)

**Comment by vanwdani** [comment]
Yeah, the problem with our end on Bison is that sometimes tests won't complete within the overall wall time for the day's run.  If we can get the reason, then it might be possible to restart that job.  Specifically, instead of just passing a 
`simple_diffusion .............. [SIGKILL:terminate process - kill program] FAILED (9)]` for walltime, I'm thinking about something like `simple_diffusion ..............[SIGCONT:discard signal - continue after stop  (19)]`.  I'm trying to think of what this could allow in future expansion of the `test_harness` abilities to help maximize our results.  This would probably involve some extra coding that I'm not ready to invest in at this time, but I want to keep the method assessable for when I can if that makes sense?

**Comment by milljm** [comment]
This might be possible. But we treat each test spec file as a single PBS 'Job' which may contain many individual tests.

(I erased a whole bunch as to why, I'll re post if curious!)

With that said, when we do want to relaunch an entire Job containing 3 tests because one test in that Job failed, you will be erasing the results for the previously 2 passing tests. Where "This might be possible" comes in, is if we allow the top level results file to 'grow' by ignoring to update the 2 'going to be skipped' tests with 'SKIP' (because skipped _is_ a valid test result).

I don't know how difficult this will be. I am sure there are unforeseen ./run_tests options I am not considering (--re, --failed-tests, --heavy, --opt, --dbg, etc) that can change the outcome of how tests are skipped.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
