### PR TITLE
Third set of contact tests. 

### PR DESCRIPTION
**Pull request by acasagran**
Adding plane strain and ring configuration versions. Issue #5865.

### CODE REVIEW

**Comment by permcody** [comment]
Thanks @acasagran. When you get a chance take a look at the Intel Target and see if you can resolve the issue with one of the tests from the previous batch. Only one is failing on Intel which might be a new record so you are doing well, but it should be looked at or skipped.

**Comment by andrsd** [comment]
If you are using `CVSDiff` what do you need those `*.e` files in the `gold/`?

**Comment by acasagran** [comment]
@andrsd. I need the *.e files for my post processing script (post_plot.sh) which uses blot to extract data from the exodus files.

**Comment by andrsd** [comment]
@acasagran Do you run that script by hand or is it run automatically? I am sorry if that is in your diff, but I do not see it, because the patch is huge...

**Comment by acasagran** [comment]
@andrsd The post processing script is run by hand and only when I'm checking the results to track down the source of a diff.

**Comment by andrsd** [comment]
Would it not be better to use `Exodiff` on those `.e` files rather then `CSVDiff`? It would guard a lot more than the CSV files do. If the .e files are checked by hand, they might go out of sync when something changes, because the test system would not use them and the problem would not manifest...

**Comment by acasagran** [comment]
Eventually we'll probably switch these over to using Exodiff, but for now we're only comparing certain quantities like contact pressure and displacements of specific nodes. Since these are contact tests and we're going to be modifying the code to better handle frictional contact, small diffs in the outputs are expected and we don't want to constantly track those down during development.

**Comment by andrsd** [comment]
Ok, got you.

**Pull request merged**
