### PR TITLE
Add int and vector<int> support to WebServerControl

### LINKED ISSUE #28097: Add `int` support to `WebServerControl`
### Motivation

We have a need for controlling `int` and `vector<int>` parameters in the `WebServerControl`.

### Design

Register `int` and `vector<int>` as valid types in the `WebServerControl`.

### Impact

New capability.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #28097

FYI @pshriwise

### CODE REVIEW

**Review by dschwen — APPROVED** [review]
We don't care about unsigned int?

**Comment by loganharbour** [comment]
> We don't care about unsigned int?

For another day...

**Comment by lindsayad** [comment]
Adding this to the frontend improvement project. Let me know if that's wrong. Let's try to use that project where appropriate

**Comment by loganharbour** [comment]
> Adding this to the frontend improvement project. Let me know if that's wrong. Let's try to use that project where appropriate

Yeah, it's wrong. This is funded by a GAIN voucher. Removed

**Pull request merged**
