### PR TITLE
Rename classes and functions related to eigenstrain calculation

### PR DESCRIPTION
**Pull request by bwspenc**
ref #7815

### CODE REVIEW

**Comment by bwspenc** [comment]
This is the commit that got reverted because it was merged due to issues with Yak. I'm resubmitting for when that has been resolved.  This breaks a test in MARMOT and a build and test and BISON due to API incompatibilities.  I have those patches ready to go as soon as this is merged.

**Comment by bwspenc** [comment]
Since @dschwen is not available can someone else review and merge this?  This was reviewed by him the first time around when it got merged and then reverted because of Yak issues, and no code has changed in this version. I have MARMOT and BISON PRs ready to go to fix the failed builds/tests due API incompatibilities.

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
Moosebuild looks pretty green... I'll give this merge another try.

**Comment by dschwen** [comment]
@bwspenc are you on this?

**Comment by bwspenc** [comment]
I'm ready to go if you click the button.

**Comment by bwspenc** [comment]
Oh, I guess you clicked the button already... I'm on it.

**Comment by brianmoose** [comment]
Once the BISON fix gets through you will also have to update MAMMOTH with the new BISON and MOOSE.

**Pull request merged**
