### PR TITLE
Remove LaTeX syntax not supported by KaTeX

### LINKED ISSUE #10414: Unbreak equations in Phase Field docs
## Rationale
Transition from MathJAX to KaTeX broke a whole bunch of equations.

## Description
KaTeX lacks a bunch of features, like `\begin{eqnarray}`, `\dots`, `\label`

## Impact
Unbreak stuff

### PR DESCRIPTION
**Pull request by dschwen**
This is disappointing but a necessary compromise, I guess.

Closes #10414

### CODE REVIEW

**Comment by cpgr** [comment]
I went through this earlier this year - you can still get aligned equations using the `aligned` environment, e.g. replace
````
\begin{eqnarray}
...
\end{eqnarray}
````
with
````
\begin{equation}
\begin{aligned}
...
\end{aligned}
\end{equation}
````
There is list of supported environments at https://khan.github.io/KaTeX/function-support.html

**Comment by dschwen** [comment]
Oh, great! Thanks @cpgr

**Comment by dschwen** [comment]
By the way, for Atom users, this is awesome:

**Comment by YaqiWang** [comment]
I always use aligned and cdots.

**Comment by permcody** [comment]
closing due to inactivity (>30 days).

**Pull request closed without merging**
