### PR TITLE
Moved tests 

### PR DESCRIPTION
**Pull request by tophmatthews**
ref #13069

### CODE REVIEW

**Comment by tophmatthews** [comment]
Well this is ready for review, but I can't figure out what's going on with the modules test errors?

```
Unable to find extern "C" method "TensorMechanicsApp__registerApps" in library: /opt/moose/gcc-8.3.0/lib/../lib64/libstdc++.so.6.
```
```
Unable to locate library for "TensorMechanicsApp".
```

**Comment by tophmatthews** [comment]
I can get these to work locally in opt, or debug, but for some reason can't pick up the TensorMechanicsApp on the test machines.

**Comment by tophmatthews** [comment]
Ohhhhh, it's because Civet builds combined, not each app individually...whoops...

**Comment by tophmatthews** [comment]
This is ready for review

**Review by permcody — APPROVED** [review]

**Pull request merged**
