### PR TITLE
Fix quoting handling on evaluated brace expressions.

### LINKED ISSUE #15638: Hit: chained fparse expressions don't work when the dependency is quoted
## Bug Description

Chained fparse brace expressions die with an error when the one depended on by another is quoted.

## Steps to Reproduce
Put:

```
foo = '${fparse 42}'
bar = ${fparse foo}'
```

in an input file.  It will error out on `bar`'s line saying that foo has the wrong type (not float).

## Impact
Fix it.  It won't break anything.  It will only make people happier.

### PR DESCRIPTION
**Pull request by rwcarlsen**
Brace expressions must be treated like strings - because they can be
nested inside strings for field values.  However, once they are
evaluated/expanded, it is possible that we might want the brace evaluation to resolve
to some particular type other than string (e.g. with fparse).
Currently, brace evalers can modify the field type, however, they
were being reverted to string type from logic that was checking if there
was stuff in the field value other than the brace expression (in which
case, the result has to represent a string type).  For all brace
expression evaluation, we instead now strip off the quotes (if any)
before evaluating the brace expression.  The revert-kind-to-string logic
now doesn't bite us.  Then we return quotes (if any existed) to the
evaluated result text.  This allows quoted (singular) fparse expressions
to be referenced by other fparse expressions.

Fixes #15638.

### CODE REVIEW

**Comment by tophmatthews** [comment]
Worth having a regular moose test?

**Review by dschwen — APPROVED** [review]
thx

**Comment by rwcarlsen** [comment]
Unit tests are better - they require less text/code, are easier to debug, faster, easier to diagnose when they fail (more focused), etc.

**Comment by rwcarlsen** [comment]
Better when the thing is amenable to unit testing that is.

**Review by tophmatthews — APPROVED** [review]

**Pull request merged**
