### PR TITLE
Add `skip_coordinate_collapsing` param to all MultiAppTransfers

### PR DESCRIPTION
**Pull request by lindsayad**
@GiudGiud was right in his review that we should add this for all transfers. I ran into a need for it for `MultiAppInterpolationTransfer` when debugging a failing Sabertooth test. Might as well just add it for everyone

Refs #21788

### CODE REVIEW

**Comment by lindsayad** [comment]
@loganharbour once we have this in, we can update the Sabertooth submodule update MR and everything should pass

**Review by GiudGiud — DISMISSED** [review]
well I may have been right but for the wrong reasons so this doesnt count

thanks for fixing sabertooth!

**Comment by GiudGiud** [comment]
there's a transfer in THM that needs attention on this

**Review by GiudGiud — COMMENTED** [review]
I redid the commit and force-pushed

I dont think we want to remove the function to add params because there are other instances like this THM action that will come up.
One would be the pebble action in Griffin, if they decide to automate the transfers. Another could be subchannel (custom coordinates) to pins (pins can be modeled in many many ways, 1D (cylindrical) , 2D Rtheta-1D, 2D RZ, 3D)

@loganharbour for an independent review

**Comment by GiudGiud** [comment]
well maybe I shouldnt try to predict the future. 
I still have the old commit with the fix for THM if you prefer to delete the function. please let me know @lindsayad

**Comment by lindsayad** [comment]
I think this is good. I forgot that I needed to add that parameter to the action and indiscriminately removed that line without realizing I was not in a transfer class!

**Comment by lindsayad** [comment]
As I now have zero commits on this PR I think I can consider my review independent ... but sadly I cannot approve my own PR ... even though I have no commits on it hahaha

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
