### PR TITLE
Add test of stagnation point (2D and RZ) incompressible flow.

### PR DESCRIPTION
**Pull request by jwpeterson**
These tests provide further verification of the incompressible Navier-Stokes RZ kernels originally added with @lindsayad, and also led to new insights for me on the question of setting outflow boundary conditions.  I plan to revisit some of our other open BCs tests in the near future.

Refs #3036.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Velocity and pressure fields from the new tests.

RZ:
axisymmetric_final

2D:
2d_final

**Comment by jwpeterson** [comment]
Huh, I never ran the test in debug mode on my system, so I never saw the `NodalValueSampler` assert... it may be an overzealous one, since it never caused a crash for me.  I'll take a closer look.

**Comment by jwpeterson** [comment]
> I'll take a closer look.

The error was due to the `NodalValueSampler` being used on a variable that was not defined at every node in the Mesh (linear Lagrange variable on a mesh with quadratic elements).  This isn't actually an error (we just need to skip those nodes where the variable in question is not defined when doing the sampling) so I added a fix for that.

**Review by andrsd — APPROVED** [review]

**Comment by jwpeterson** [comment]
Thanks @andrsd!

**Pull request merged**
