### PR TITLE
Make AdvectionBC more versatile

### PR DESCRIPTION
**Pull request by lindsayad**
We had a user complain that he couldn't set a velocity vector of size 3 for a mesh of dimension 2. This commit makes the AdvectionBC object more flexible.

### CODE REVIEW

**Comment by lindsayad** [comment]
References the moose discussion here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/7DKtCT0p298/3PKykWHkCAAJ

**Review by snschune — DISMISSED** [review]

**Comment by snschune** [comment]
The only issue I have with this BC is that `outflow = false` makes no sense.
Let's say you have `nabla * (v * T)` where v is a vector. Then integration by parts
gives you a term `v * normal * T` on the boundary. On outflow BCs that makes total sense, but on inflow
you would not use `_u` for T but you would set it to a function or a constant value,
because on inflow BCs you determine what is going on. 

Should the `outflow` parameter be removed?

**Comment by lindsayad** [comment]
> The only issue I have with this BC is that `outflow = false` makes no sense.

@snschune Didn't you make this object? Yea I have no qualms about removing that parameter.

**Comment by snschune** [comment]
I copied it over from Moose tests, I think.

**Comment by snschune** [comment]
:+1:

**Comment by lindsayad** [comment]
Ah I see

**Review by permcody — APPROVED** [review]

**Pull request merged**
