### PR TITLE
Make displaced mesh an actual copy of the undisplaced

### PR DESCRIPTION
**Pull request by lindsayad**
We make use of the enhanced copy construction capability in libmesh. Using copy construction ensures that the partitioning is the same between undisplaced and displaced meshes regardless of whether we are using `DistributedMesh` or `ReplicatedMesh`

### CODE REVIEW

**Comment by lindsayad** [comment]
Don't worry about that libmesh update

**Comment by friedmud** [comment]
This looks awesome!  Will also make the startup time for problems with displaced mesh quite a lot faster!

**Comment by bwspenc** [comment]
@lindsayad Would this have any impact on how we work with the mesh in XFEM? In XFEM, we add nodes and add/delete elements during the analysis, and do the same operations on the displaced and undisplaced mesh.

**Comment by lindsayad** [comment]
This only improves your starting point, so if anything it should only make
things better...

**Review by permcody — APPROVED** [review]

**Pull request merged**
