### PR TITLE
Skip contact  tests affected by the Intel compiler

### PR DESCRIPTION
**Pull request by fdkong**
There are three contact tests that are still failing on the intel. SuperLU_dist may still have some unknown issues on the intel compiler. But let us skip these three tests before we find the root of the cause.

Refs #10084

Closes #10085

### CODE REVIEW

**Comment by brianmoose** [comment]
I invalidated the Intel target on this PR and it should reproduce the failed tests below.
I also ran it manually on the initial build box that created the Intel part of the package, here are the failed tests:
```
combined/test:internal_volume.hex20......................................................... FAILED (TIMEOUT)
combined/test:contact_verification/patch_tests/cyl_3.mu_0_2_kin.............................. FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/ring_3.glued_kin_sm........................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/ring_3.frictionless_kin_sm.................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/ring_3.mu_0_2_kin_sm.......................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/plane_3.glued_kin_sm.......................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.glued_kin....................... FAILED (ERRMSG)
combined/test:grain_texture.3D.............................................................. FAILED (CSVDIFF)
```

**Comment by brianmoose** [comment]
I am not sure what this `ignore_compiler` option is.
Looking at the #10085 intel target at https://www.moosebuild.org/job/124170/ shows that there are warnings when this is used:
```
Warning detected when parsing file "/opt/civet/build_0/moose/modules/combined/test/tests/contact_verification/patch_tests/cyl_3/tests"
       Ignored Parameter(s):  set(['ignore_compiler'])
```

**Comment by WilkAndy** [comment]
When this PR is merged, could you invalidate my current PRs, please?

**Comment by brianmoose** [comment]
Once it is fixed, I will invalidate all the failed Intel targets

**Comment by fdkong** [comment]
> I am not sure what this ignore_compiler option is.
> Looking at the #10085 intel target at https://www.moosebuild.org/job/124170/ shows that there are warnings when this is used:
> 
> Warning detected when parsing file "/opt/civet/build_0/moose/modules/combined/test/tests/contact_verification/patch_tests/cyl_3/tests"
>        Ignored Parameter(s):  set(['ignore_compiler'])

@bwspenc 

I did not use this option before. Do you have any thought ?

**Comment by bwspenc** [comment]
This was my first time trying to use it.  I was just using it because @permcody said we should be using it, but I didn't see any other usage of it, so it doesn't really surprise me that it's broken.  I'd do as you did and just do it the old way.

**Review by bwspenc — DISMISSED** [review]
I'm good with these changes, but since I have a commit in this history, I'm not sure if I'm allowed to merge this per our QA practices.  Maybe somebody else should once this passes.

**Comment by bwspenc** [comment]
@fdkong Since you overwrite my commits anyway, why don't you just remove my commit from the history?  Then I can merge it.

**Comment by fdkong** [comment]
> @fdkong Since you overwrite my changes anyway, why don't you just remove my commit from the history? Then I can merge it.

I was worrying you were getting angry on me  if I deleted your commit.  :)

I will delete it

**Comment by bwspenc** [comment]
It's just fine with me if I don't get any credit for this one! 😆

**Review by brianmoose — APPROVED** [review]

**Pull request merged**
