### PR TITLE
Slightly loosen tolerance on test affected by tangent operator change

### PR DESCRIPTION
**Pull request by bwspenc**
ref #11219

### CODE REVIEW

**Comment by bwspenc** [comment]
@tophmatthews This should fix that test, in case you started on it already.

**Comment by bwspenc** [comment]
@permcody @brianmoose

**Comment by tophmatthews** [comment]
Oh! I already did #11420. If you like this way better, I can close that one.

**Comment by bwspenc** [comment]
I think your fix is better. I just copied the tolerances from the other variant of this test. I'm closing mine in favor of yours.

**Pull request closed without merging**
