### PR TITLE
Make multiapp positions parameter optional for position irrelevant multiapp

### LINKED ISSUE #6325: Can we provide the `positions` parameter in MultiApp a default value?
Currently it does not have one, which makes lots of our simulations have to have something like `positions = '0 0 0'`, which looks really awkward because the number of subapps is one and the subapp is position irrelevant.

I looked the code, this will just require turning off a moose Error in `MultiApp::fillPositions()`. I will send in a small PR to see if there is any damage on applications.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #6325.

### CODE REVIEW

**Comment by friedmud** [comment]
I'm not really for this, but am willing to be overruled.  I think that it makes it all too easy for someone to screw up.

What I might be willing to go for is an extra parameter like `positions_irrelevant = true` that turns off the checking for positions.  I just want to keep an extra step between a new person and making a critical mistake.

**Comment by YaqiWang** [comment]
@friedmud I was expecting you would have comments.

`positions_irrelevant = true` will definitely look better than `positions = '0 0 0'` in my input files. If @friedmud  has strong opinion on this, I am willing to make compromise although I do not want my users to keep saying their multiapps are position irrelevant in their inputs.

Anybody else really want me to change this PR as @friedmud suggested or do not want this change at all?

**Comment by YaqiWang** [comment]
My ultimate goal is actually to completely get rid of the input for creating multiapps, instead applying bunch of modifications rules on the master input file and build multiapps on the fly. This makes me easier to accept @friedmud 's suggestion. So I will make the change and redo this PR.

**Comment by friedmud** [comment]
Let's see if anyone else has an opinion on this.  If it's just me then what you had before might be fine...

**Comment by andrsd** [comment]
What is wrong with having the default position set to `0 0 0`?

**Comment by friedmud** [comment]
Just that it takes no thought... and therefore we'll get lots of questions about why Transfers aren't going to the correct positions...

**Comment by permcody** [comment]
I see your point @friedmud but I think the default position is probably fine. It might not take any thought but it is a surprising common case since people who run Multiapps often set up the correct coordinates in their mesh files so they don't need any translation. This is especially true when they have only a single entity as their Multiapp. 

Given the two choices I think I'd rather have a default instead of one of these awkward logic parameters (irrelevant == true) which means "irrelevant == false" is the default.

**Comment by friedmud** [comment]
Gotcha

**Comment by aeslaughter** [comment]
I think the default position to '0 0 0' is the correct method as well.

**Comment by friedmud** [comment]
I've been overruled! :smile: That's why I wanted some others to chime in...

**Comment by YaqiWang** [comment]
;-) either way is fine to me. Let me pick up the old ci and redo the push.

**Pull request merged**
