### PR TITLE
Add Getting Started Page for Use of Docker Image (Issue #13952)

### LINKED ISSUE #13952: Need Getting Started Page for Using Docker Image
## Reason
A page on "Getting Started" has been requested for using Docker images of MOOSE.

## Design
An additional bullet titled "Docker" with a link to a brief page on using MOOSE images is needed.  More specifically, it will be shown how to go from no local copy of MOOSE to running the tests in a single command.  

After this, the page will convey how one can extend the image to containerize a MOOSE application using BLACKBEAR as a working example.  The submodule neml in BLACKBEAR seems to require Libmesh (or some other upstream dependency) to be configured with Boost installed, so a single line will be added to docker_ci/Dockerfile to have apt install libboost-all-dev as part of the build.

I don't think the intended audience will have much interest in building/pushing MOOSE images using Jenkins to drive Docker, so that will not be covered, unless I'm mistaken.

## Impact
Impact will be on the markdown for the "Getting Started" page, along with additional md files for the page on Docker.  For BLACKBEAR to serve as a working example, docker_ci/Dockerfile will include libboost-all-dev in the list of apt packages to install.

### PR DESCRIPTION
**Pull request by herter4171**
Adds a linked bullet "Docker" to the page Getting Started.  The Docker page itself covers how to obtain the framework, run tests in a container, and extend the image to contain a MOOSE app with BLACKBEAR as the working example.  For BLACKBEAR to compile with neml, Boost has to be installed from the get-go, so libboost-all-dev has been added to the Dockerfile.  This closes #13952.

I've tried to emulate existing markdown, and I've made sure everything looks alright in a markdown renderer.  Although I've built the docs, I'm not seeing any HTML files, so I'm not sure if I did it right or how the page looks in a browser.  Clarification on that would be helpful.

### CODE REVIEW

**Comment by herter4171** [comment]
I don't get why CIVET is unhappy.  The ticket number's in the body of the PR and the title with a pound symbol in front.

**Comment by loganharbour** [comment]
Precheck checks the individual commit messages for the issue, not the PR title

**Review by permcody — DISMISSED** [review]
Nice! Thanks for the contribution.

**Comment by herter4171** [comment]
Happy to help.  I hadn't realized that putting text directly under headings would render them in the same font, so I think I've fixed that now.

**Review by permcody — APPROVED** [review]

**Pull request merged**
