### PR TITLE
Create OutputEulerAngle auxkernel

### LINKED ISSUE #5446: Create AuxKernel to output the Euler angles
This auxkernel will extract the Euler angles from a user object and the current grain number from a GrainTracker user object and save it in an AuxVariable. This will primarily be used for visualization.

### PR DESCRIPTION
**Pull request by tonkmr**
I created OutputEulerAngle auxkernel that uses a grain tracker user object and a Euler angle user object and outputs one of the Euler angles as an auxvariable. I also use it in a test and the two example problems that couple grain growth with mechanics. Closes #5446.

### CODE REVIEW

**Comment by jwpeterson** [comment]
```
Results of testing ca1b547 using moose_PR_pre_check recipe:
Failed on: linux-gnu
View the results here: https://www.moosebuild.org/view_job/20366
```
Did you merge something that fails the pre-check?

**Comment by dschwen** [comment]
The PR passed all the tests and I asked @tonkmr to remove *one* empty line. He needed this merged asap so I pushed the button thinking that a trivial change will not trip up the tests. The pre test complained about a missing ticket reference, which is odd, because the reference is obviously there. My theory is that the test failed out of spite because I merged early.

**Comment by jwpeterson** [comment]
Yeah, the pre-test failure made no sense to me either because there definitely was a ticket number...

**Comment by smharper** [comment]
I think @dschwen is not far off with his theory.  Check it out:
```
error: branch 'tonkmr/moose/euler_angles_aux_5446' not found.
Switched to a new branch 'tonkmr/moose/euler_angles_aux_5446'
From github.com:tonkmr/moose
 * branch            euler_angles_aux_5446 -> FETCH_HEAD
Already up-to-date.
```
I think @moosebuild actually checked out these commits when it grabbed devel, then there was no patch to look through for ticket numbers.

**Comment by jwpeterson** [comment]
I guess the pre-check should just stop (instead of failing) if everything is already up-to-date.

**Pull request merged**
