### PR TITLE
Remove now unnecessary flag removal in libmesh script

### LINKED ISSUE #15123: Remove temporary fix introduced in #15122
## Reason
The fix is just temporary and can be removed when libMesh properly handles the extraneous flags and the libMesh submodule is updated.

## Design
Remove the additions made in #15122

## Impact
None if done correctly

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #15123

### CODE REVIEW

**Comment by loganharbour** [comment]
This should fail "Test debug PETSc alt" until the libMesh update makes it to devel, assuming that the flags are handled properly now in libMesh.

**Comment by loganharbour** [comment]
Damn. Looks like we're still not cleaning properly.

@roystgnr

**Comment by loganharbour** [comment]
```
----------------------------------- SUMMARY -----------------------------------

Package version............... : metaphysicl-1.0.2

C++ compiler.................. : mpicxx -std=c++14
C++ compiler flags............ : -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/civet/conda_builds/conda_envs/pr-15303/include -Wall
Install dir................... : /opt/civet/build_0/moose/scripts/../libmesh/installed
Build user.................... : moosetest
Build host.................... : mobuild10
Configure date................ : 2020-05-16 13:00
Build architecture............ : x86_64-pc-linux-gnu
Git revision number........... : external

Optional Packages for Testing:
  MASA........................ : no
  VEXCL....................... : no
  TIMPI....................... : no
```

```----------------------------------- SUMMARY -----------------------------------

Package version............... : timpi-1.1.2

C++ compiler.................. : mpicxx
Build Methods...................... : dbg
CPPFLAGS...(dbg)................... : -DDEBUG -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/civet/conda_builds/conda_envs/pr-15303/include
CXXFLAGS...(dbg)................... :  -O0 -felide-constructors -g -pedantic -W -Wall -Wextra -Wno-long-long -Wunused -Wpointer-arith -Wformat -Wparentheses -Woverloaded-virtual   -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/civet/conda_builds/conda_envs/pr-15303/include

Install dir................... : /opt/civet/build_0/moose/scripts/../libmesh/installed
Build user.................... : moosetest
Build host.................... : mobuild10
Configure date................ : 2020-05-16 13:00
Build architecture............ : x86_64-pc-linux-gnu
Git revision number........... : c2091c9106889f2deb083751a81304f8cb9fe7e3

-------------------------------------------------------------------------------
Optional Packages for Testing:
  MPI......................... : yes
  MPI_IMPL.................... : mpi
  timpi_optional_INCLUDES..... : -I/opt/civet/conda_builds/conda_envs/pr-15303/include 
  timpi_optional_LIBS......... : -L/opt/civet/conda_builds/conda_envs/pr-15303/lib -lmpi  

Configure complete, now type \'make\' and then \'make install\'.


----------------------------------- SUMMARY -----------------------------------

Package version.................... : libmesh-1.6.0-pre

C++ compiler type.................. : gcc7
C++ compiler....................... : mpicxx
C compiler......................... : mpicc
Fortran compiler................... : mpif90
Build Methods...................... : dbg

CPPFLAGS...(dbg)................... : -DDEBUG -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC 
CXXFLAGS...(dbg)................... :  -O0 -felide-constructors -g -pedantic -W -Wall -Wextra -Wno-long-long -Wunused -Wpointer-arith -Wformat -Wparentheses -Woverloaded-virtual    -fopenmp
CFLAGS.....(dbg)................... : -g -Wimplicit    -fopenmp

Any warnings-to-errors flags....... : 
Any extra paranoid warning flags... : 
Install dir........................ : /opt/civet/build_0/moose/scripts/../libmesh/installed
Build user......................... : moosetest
Build host......................... : mobuild10
Build architecture................. : x86_64-pc-linux-gnu
Git revision....................... : 30d38fc9b5bc608655d033117a8d5cb59c57ae4c

Library Features:
  library warnings................. : no
  library deprecated code support.. : yes
  adaptive mesh refinement......... : yes
  blocked matrix/vector storage.... : no
  complex variables................ : no
  example suite.................... : yes
  ghosted vectors.................. : yes
  high-order shape functions....... : yes
  unique-id support................ : yes
  id size (boundaries)............. : 2 bytes
  id size (dofs)................... : 4 bytes
  id size (unique)................. : 8 bytes
  id size (processors)............. : 4 bytes
  id size (subdomains)............. : 2 bytes
  infinite elements................ : no
  Dirichlet constraints............ : yes
  node constraints................. : no
  parallel mesh.................... : no
  performance logging.............. : no
  periodic boundary conditions..... : yes
  reference counting............... : yes
  shape function 2nd derivatives... : yes
  stack trace files................ : no
  track node valence............... : yes
  variational smoother............. : yes
  xdr binary I/O................... : yes

Optional Packages:
  boost............................ : yes
  capnproto........................ : no
  cppunit.......................... : no
  curl............................. : no
  eigen............................ : yes
  exodus........................... : yes
     version....................... : v5.22
  fparser.......................... : yes
     build from version............ : release
  glpk............................. : no
  gmv.............................. : yes
  gzstream......................... : yes
  hdf5............................. : no
  laspack.......................... : no
  libhilbert....................... : yes
  metaphysicl...................... : yes
  metis............................ : yes
  mpi.............................. : yes
  nanoflann........................ : yes
  nemesis.......................... : yes
     version....................... : v5.22
  netcdf........................... : yes
     version....................... : 4
  nlopt............................ : no
  parmetis......................... : yes
  petsc............................ : yes
     version....................... : 3.11.4
  qhull............................ : yes
  sfcurves......................... : no
  slepc............................ : yes
     version....................... : 3.11.0
  thread model..................... : pthread
  c++ rtti ........................ : yes
  tecio............................ : no
  tecplot...(vendor binaries)...... : no
  tetgen........................... : no
  triangle......................... : no
  trilinos......................... : no
  vtk.............................. : yes
     version....................... : 6.3.0

  libmesh_optional_INCLUDES........ : -I/opt/civet/conda_builds/conda_envs/pr-15303/libmesh-vtk/include/vtk-6.3 -pthread -I/opt/civet/conda_builds/conda_envs/pr-15303/include -I/opt/civet/conda_builds/conda_envs/pr-15303//include

  libmesh_optional_LIBS............ : -Wl,-rpath,/opt/civet/conda_builds/conda_envs/pr-15303/libmesh-vtk/lib -L/opt/civet/conda_builds/conda_envs/pr-15303/libmesh-vtk/lib -lvtkIOCore-6.3 -lvtkCommonCore-6.3 -lvtkCommonDataModel-6.3 -lvtkFiltersCore-6.3 -lvtkIOXML-6.3 -lvtkImagingCore-6.3 -lvtkIOImage-6.3 -lvtkImagingMath-6.3 -lvtkIOParallelXML-6.3 -lvtkParallelMPI-6.3 -lvtkParallelCore-6.3 -L/opt/civet/conda_builds/conda_envs/pr-15303/lib -lslepc -Wl,-rpath,/opt/civet/conda_builds/conda_envs/pr-15303/lib -lpetsc -lHYPRE -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lsuperlu_dist -lflapack -lfblas -lparmetis -lmetis -lptesmumps -lptscotchparmetis -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr -lrt -lm -lpthread -lz -ldl -lmpifort -lgfortran -lmpi
```

TIMPI `CPPFLAGS` have `-DDEBUG`, `-DNDEBUG`, and `-O2`. `CXXFLAGS` have `-O2`.

**Comment by lindsayad** [comment]
```bash
$ mpicxx -show
x86_64-conda_cos6-linux-gnu-c++ -march=nocona -mtune=haswell -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/lindad/miniconda3/envs/moose-boost/lib -Wl,-rpath-link,/home/lindad/miniconda3/envs/moose-boost/lib -L/home/lindad/miniconda3/envs/moose-boost/lib -I/home/lindad/miniconda3/envs/moose-boost/include -L/home/lindad/miniconda3/envs/moose-boost/lib -lmpicxx -Wl,-rpath -Wl,/home/lindad/miniconda3/envs/moose-boost/lib -Wl,--enable-new-dtags -lmpi
```

**Comment by lindsayad** [comment]
@loganharbour where is that configure information from?

**Comment by loganharbour** [comment]
It's straight from the CIVET libMesh build output:
https://civet.inl.gov/job/527655/

**Comment by lindsayad** [comment]
This is failing because the conda compilers have all that garbage in `CPPFLAGS,CXXFLAGS,etc.`. In order for this recipe to work we need to get those unset. @milljm is there a non-hacky way to do that from the CIVET recipe?

**Comment by roystgnr** [comment]
> This is failing because the conda compilers have all that garbage in CPPFLAGS,CXXFLAGS,etc.

Yeah, but libMesh and TIMPI aren't supposed to be listening to that garbage in the first place, for exactly this reason.  We had a regression in that behavior, but https://github.com/libMesh/libmesh/pull/2515 was supposed to fix it, and I could have sworn I tested the fix.

But I can replicate this - libMesh is behaving as expected, but TIMPI is still picking up the generic settings...

**Comment by roystgnr** [comment]
What I don't see is how that particular test is failing, though.  TIMPI flags should only be affecting error throwing in TIMPI .C files; but in the failing test that's a libMesh error...

**Comment by lindsayad** [comment]
Could it be coming in through `AM_CPPFLAGS`?

**Comment by lindsayad** [comment]
No it's as simple as the fact that we still use `CPPFLAGS` when we're compiling. This is straight out of the generated `Makefile`:
```
src/base/libmesh_dbg_la-default_coupling.lo: src/base/default_coupling.C
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libmesh_dbg_la_CPPFLAGS) $(CPPFLAGS) $(libmesh_dbg_la_CXXFLAGS) $(CXXFLAGS) -MT src/base/libmesh_dbg_la-default_coupling.lo -MD -MP -MF src/base/$(DEPDIR)/libmesh_dbg_la-default_coupling.Tpo -c -o src/base/libmesh_dbg_la-default_coupling.lo `test -f 'src/base/default_coupling.C' || echo '$(srcdir)/'`src/base/default_coupling.C
```

**Comment by lindsayad** [comment]
> Yeah, but libMesh and TIMPI aren't supposed to be listening to that garbage in the first place, for exactly this reason.

Wait, so we really want to take the approach of ignoring flags in the environment? If we're going to do that, I think we should emit a clear message saying that the flags are going to be ignored. Moreover `configure --help` lists all the flags variables as being "influential" environment variables, so if we decide to go down a route where we're going to ignore those flags (which we're *not* doing now) then we should clean up our help. I personally think that we should use the environment flags unless there's a direct conflict (like in the `DDEBUG NDEBUG` case)

**Comment by loganharbour** [comment]
Has any progress been made on this?

**Comment by lindsayad** [comment]
My stance on this is that we either try to do something in the CIVET recipe to unset the flags or we should close this PR and keep what you added before.

I think it would be a bad precedent to start ignoring/filtering user environment variables, especially ones that we label as important in our libmesh configure help.

**Pull request closed without merging**
