### PR TITLE
improve AD eigenvalue decomposition

### PR DESCRIPTION
**Pull request by hugary1995**
ref #14237

### CODE REVIEW

**Comment by dschwen** [comment]
@hugary1995 as a side note, we've been looking at using Eigen to compute the eigenvalue decomposition of symmetric matrices using dual numbers. Eigen types are templated. In our case we needed the eigenvalue decomposition of a 6x6 matrix.

**Comment by hugary1995** [comment]
I would be surprised if Eigen works with dual numbers out of the box, but I am happy to help if you think minor changes in the Eigen source code could get it to work with AD.

**Comment by dschwen** [comment]
Well, color yourself surprised. I have tried it and it does work: https://github.com/idaholab/moose/issues/16016#issuecomment-731343792

**Comment by hugary1995** [comment]
@dschwen are the derivatives correct?

**Comment by tophmatthews** [comment]
This would enable `decomposition_method = EigenSolution` right? Is this almost ready? Looks great!

**Comment by tophmatthews** [comment]
Would love to start testing this...

**Comment by dschwen** [comment]
I'll make an Eigen based PR this week

**Comment by tophmatthews** [comment]
I'm hoping this is being closed because you have some awesome new way of computing this? :)

**Comment by hugary1995** [comment]
When next libMesh update comes, we can use Eigen to compute eigenvalues and eigenvectors. If that doesn't work I can reopen this PR.

**Pull request closed without merging**
