### PR TITLE
Fix Memory Leak in new Picard Iteration, Restart logic

### PR DESCRIPTION
**Pull request by permcody**
- Mem leak fix (scroll to bottom)
- Debug statements cleanup

### CODE REVIEW

**Comment by jwpeterson** [comment]
:+1:

**Comment by friedmud** [comment]
Damnit guys... I use those print statements....

**Comment by permcody** [comment]
Well that individual commit is revertable, it's separate from the fix.

**Comment by friedmud** [comment]
Hehe... It's ok... I'll put em back if I need em. :-)

Good catch on the memory leak! It's obvious... Sorry I missed it.

**Pull request merged**
