### PR TITLE
Update package versions on website

### PR DESCRIPTION
**Pull request by milljm**
Updating package versions on mooseframework.org (new) site

Refs #9062

### CODE REVIEW

**Comment by dschwen** [comment]
Thanks for updating this. Do we have any public link to the new site yet? (besides the PR builds for testing)

**Comment by brianmoose** [comment]
We update the documentation on master: http://mooseframework.org/docs/moose_docs/site/
Don't know if there is an actual link to it anywhere.

**Comment by dschwen** [comment]
Btw. what happened to the yuuuge eye-candy images on the frontpage of the new site?

**Comment by aeslaughter** [comment]
@dschwen I took down the eye candy for some reason I can't recall, I plan on putting them back soon.

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
