### PR TITLE
Added print_nonlinear_residuals option for output

### LINKED ISSUE #22056: Add print_nonlinear_residuals option, to turn it off, in Outputs
## Reason
For some tough problems there can be a lot of nonlinear iterations. if this is expected, then it s not helpful to clobber the screen with hundreds of lines

## Design
New boolean in Outputs

## Impact
Less verbose simulations, slicker screens, happier users

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #22056

### CODE REVIEW

**Comment by socratesgorilla** [comment]
@GiudGiud

**Comment by GiudGiud** [comment]
I'd be worried this hides more things than expected.
Can you try a couple input files in the repo to see what gets removed. Let s look for inputs with 
- adaptivity
- grid cycling
- postprocessors
- mesh refinement
- automatic scaling
and see if the relevant output gets removed or not

**Comment by socratesgorilla** [comment]
> I'd be worried this hides more things than expected. Can you try a couple input files in the repo to see what gets removed. Let s look for inputs with
> 
>     * adaptivity
> 
>     * grid cycling
> 
>     * postprocessors
> 
>     * mesh refinement
> 
>     * automatic scaling
>       and see if the relevant output gets removed or not


Here's the output log of relevant tests with and without the option on:
```
./moose_test-opt -i tests/postprocessors/side_integral/side_integral_functor.i
Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:21:56 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   221
  Elems:                   192
  Num Subdomains:          2

Nonlinear System:
  Num DOFs:                132
  Num Local DOFs:          132
  Variables:               "u" 
  Finite Element Types:    "MONOMIAL" 
  Approximation Orders:    "CONSTANT" 

Auxiliary System:
  Num DOFs:                192
  Num Local DOFs:          192
  Variables:               "v1" "v2" 
  Finite Element Types:    "MONOMIAL" "MONOMIAL" 
  Approximation Orders:    "CONSTANT" "CONSTANT" 

Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK


Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | ext_f1         | ext_m1         | ext_m2         | ext_u          | ext_v1         | ext_v2         | int_s1_f1      | int_s1_m1      | int_s1_m2      | int_s1_u       | int_s1_v1      | int_s2_f1      | int_s2_m1      | int_s2_m2      | int_s2_v2      |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+

 0 Nonlinear |R| = 6.000000e+00
      0 Linear |R| = 6.000000e+00
      1 Linear |R| = 4.774439e-01
      2 Linear |R| = 1.400321e-01
      3 Linear |R| = 7.291075e-02
      4 Linear |R| = 1.244780e-02
      5 Linear |R| = 1.908332e-03
      6 Linear |R| = 2.574164e-04
      7 Linear |R| = 3.318088e-05
 1 Nonlinear |R| = 3.317691e-05
      0 Linear |R| = 3.317691e-05
      1 Linear |R| = 7.211955e-06
      2 Linear |R| = 1.285352e-06
      3 Linear |R| = 5.288903e-07
      4 Linear |R| = 1.875626e-07
      5 Linear |R| = 2.283189e-08
      6 Linear |R| = 3.341271e-09
      7 Linear |R| = 4.508092e-10
      8 Linear |R| = 3.426538e-11
 2 Nonlinear |R| = 3.443895e-11
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | ext_f1         | ext_m1         | ext_m2         | ext_u          | ext_v1         | ext_v2         | int_s1_f1      | int_s1_m1      | int_s1_m2      | int_s1_u       | int_s1_v1      | int_s2_f1      | int_s2_m1      | int_s2_m2      | int_s2_v2      |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.001225e+02 |   2.099380e+01 |   1.320000e+02 |   5.498923e+00 |   2.800000e+01 |   0.000000e+00 |   9.811315e+00 |   9.811315e+00 |   8.400000e+01 |   3.494803e+00 |   2.250000e+01 |   9.811315e+00 |   9.811315e+00 |   2.800000e+01 |   2.230000e+01 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+

❯ ./moose_test-opt -i tests/postprocessors/side_integral/side_integral_functor.i
Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:22:13 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   221
  Elems:                   192
  Num Subdomains:          2

Nonlinear System:
  Num DOFs:                132
  Num Local DOFs:          132
  Variables:               "u" 
  Finite Element Types:    "MONOMIAL" 
  Approximation Orders:    "CONSTANT" 

Auxiliary System:
  Num DOFs:                192
  Num Local DOFs:          192
  Variables:               "v1" "v2" 
  Finite Element Types:    "MONOMIAL" "MONOMIAL" 
  Approximation Orders:    "CONSTANT" "CONSTANT" 

Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK


Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | ext_f1         | ext_m1         | ext_m2         | ext_u          | ext_v1         | ext_v2         | int_s1_f1      | int_s1_m1      | int_s1_m2      | int_s1_u       | int_s1_v1      | int_s2_f1      | int_s2_m1      | int_s2_m2      | int_s2_v2      |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+

      0 Linear |R| = 6.000000e+00
      1 Linear |R| = 4.774439e-01
      2 Linear |R| = 1.400321e-01
      3 Linear |R| = 7.291075e-02
      4 Linear |R| = 1.244780e-02
      5 Linear |R| = 1.908332e-03
      6 Linear |R| = 2.574164e-04
      7 Linear |R| = 3.318088e-05
      0 Linear |R| = 3.317691e-05
      1 Linear |R| = 7.211955e-06
      2 Linear |R| = 1.285352e-06
      3 Linear |R| = 5.288903e-07
      4 Linear |R| = 1.875626e-07
      5 Linear |R| = 2.283189e-08
      6 Linear |R| = 3.341271e-09
      7 Linear |R| = 4.508092e-10
      8 Linear |R| = 3.426538e-11
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | ext_f1         | ext_m1         | ext_m2         | ext_u          | ext_v1         | ext_v2         | int_s1_f1      | int_s1_m1      | int_s1_m2      | int_s1_u       | int_s1_v1      | int_s2_f1      | int_s2_m1      | int_s2_m2      | int_s2_v2      |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.001225e+02 |   2.099380e+01 |   1.320000e+02 |   5.498923e+00 |   2.800000e+01 |   0.000000e+00 |   9.811315e+00 |   9.811315e+00 |   8.400000e+01 |   3.494803e+00 |   2.250000e+01 |   9.811315e+00 |   9.811315e+00 |   2.800000e+01 |   2.230000e+01 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+

./moose_test-opt -i "/Users/peatna/moose/5moose/moose/test/tests/geomsearch/patch_update_strategy/always-grid-sequence.i"
Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:24:50 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   106
  Elems:                   51
  Num Subdomains:          2

Nonlinear System:
  Num DOFs:                106
  Num Local DOFs:          106
  Variables:               "u" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 

Auxiliary System:
  Num DOFs:                475
  Num Local DOFs:          475
  Variables:               { "linear_field" "receiver" "disp_x" "disp_y" } "elemental_reciever" 
  Finite Element Types:    "LAGRANGE" "MONOMIAL" 
  Approximation Orders:    "FIRST" "CONSTANT" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    hypre boomeramg 


Time Step 0, time = 0

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 1, time = 1, dt = 1


Updating geometric search patches

 0 Nonlinear |R| = 7.071068e-01
   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 1.41421
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131926e-02
      2 Linear |R| = 3.983447e-04
      3 Linear |R| = 5.866306e-06
 1 Nonlinear |R| = 5.865892e-06
   Solution, reference convergence variable norms:
   u: 5.86589e-06  u_ref: 1.0002
      0 Linear |R| = 5.865892e-06
      1 Linear |R| = 1.280280e-07
      2 Linear |R| = 2.130741e-09
      3 Linear |R| = 4.463634e-11
 2 Nonlinear |R| = 4.459365e-11
   Solution, reference convergence variable norms:
   u: 4.45936e-11  u_ref: 1.0002
 Solve Converged!


Updating geometric search patches

 0 Nonlinear |R| = 3.825963e-11
   Solution, reference convergence variable norms:
   u: 3.82596e-11  u_ref: 0.866199
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 2, time = 2, dt = 1


Updating geometric search patches

 0 Nonlinear |R| = 7.071068e-01
   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 2.24062
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131927e-02
      2 Linear |R| = 3.983444e-04
      3 Linear |R| = 5.866310e-06
 1 Nonlinear |R| = 5.878150e-06
   Solution, reference convergence variable norms:
   u: 5.87815e-06  u_ref: 2.0004
      0 Linear |R| = 5.878150e-06
      1 Linear |R| = 1.282394e-07
      2 Linear |R| = 2.125735e-09
      3 Linear |R| = 4.466799e-11
 2 Nonlinear |R| = 4.474556e-11
   Solution, reference convergence variable norms:
   u: 4.47456e-11  u_ref: 2.0004
 Solve Converged!


Updating geometric search patches

 0 Nonlinear |R| = 3.839659e-11
   Solution, reference convergence variable norms:
   u: 3.83966e-11  u_ref: 1.7324
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 3, time = 3, dt = 1


Updating geometric search patches

 0 Nonlinear |R| = 7.071068e-01
   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 3.16885
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131925e-02
      2 Linear |R| = 3.983439e-04
      3 Linear |R| = 5.866314e-06
 1 Nonlinear |R| = 5.855390e-06
   Solution, reference convergence variable norms:
   u: 5.85539e-06  u_ref: 3.0006
      0 Linear |R| = 5.855390e-06
      1 Linear |R| = 1.282118e-07
      2 Linear |R| = 2.131556e-09
      3 Linear |R| = 4.447813e-11
 2 Nonlinear |R| = 4.456060e-11
   Solution, reference convergence variable norms:
   u: 4.45606e-11  u_ref: 3.0006
 Solve Converged!


Updating geometric search patches

 0 Nonlinear |R| = 3.822507e-11
   Solution, reference convergence variable norms:
   u: 3.82251e-11  u_ref: 2.5986
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   3.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

./moose_test-opt -i "/Users/peatna/moose/5moose/moose/test/tests/geomsearch/patch_update_strategy/always-grid-sequence.i"


*** Warning, This code is deprecated and will be removed in future versions:
The `solution_variables` parameter is deprecated, has no effect when the tagging system is used, and will be removed on January 1, 2020. Please simply delete this parameter from your input file.
Stack frames: 14
0: 0   libmesh_opt.0.dylib                 0x0000000105da5e43 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1091
1: 1   libmoose-opt.0.dylib                0x0000000104946c5a void moose::internal::mooseDeprecatedStream<ConsoleStream const, char const (&) [195]>(ConsoleStream const&, bool, char const (&) [195]) + 842
2: 2   libmoose-opt.0.dylib                0x0000000104944fe4 ReferenceResidualProblem::ReferenceResidualProblem(InputParameters const&) + 660
3: 3   libmoose-opt.0.dylib                0x0000000104943255 std::__1::shared_ptr<MooseObject> Registry::build<ReferenceResidualProblem, MooseObject>(InputParameters const&) + 69
4: 4   libmoose-opt.0.dylib                0x00000001051a8faa Factory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, InputParameters const&, unsigned int, bool) + 394
5: 5   libmoose-opt.0.dylib                0x0000000104ca0f04 std::__1::shared_ptr<FEProblemBase> Factory::create<FEProblemBase>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, InputParameters const&, unsigned int) + 52
6: 6   libmoose-opt.0.dylib                0x0000000104c71520 CreateProblemAction::act() + 416
7: 7   libmoose-opt.0.dylib                0x0000000104c5882f ActionWarehouse::executeActionsWithAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1359
8: 8   libmoose-opt.0.dylib                0x0000000104c876c8 ActionWarehouse::executeAllActions() + 280
9: 9   libmoose-opt.0.dylib                0x0000000105217372 MooseApp::runInputFile() + 98
10: 10  libmoose-opt.0.dylib                0x00000001052128e0 MooseApp::run() + 960
11: 11  moose_test-opt                      0x0000000103c1abd4 main + 132
12: 12  libdyld.dylib                       0x00007fff6ef59cc9 start + 1
13: 13  ???                                 0x0000000000000003 0x0 + 3

Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:25:06 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   106
  Elems:                   51
  Num Subdomains:          2

Nonlinear System:
  Num DOFs:                106
  Num Local DOFs:          106
  Variables:               "u" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 

Auxiliary System:
  Num DOFs:                475
  Num Local DOFs:          475
  Variables:               { "linear_field" "receiver" "disp_x" "disp_y" } "elemental_reciever" 
  Finite Element Types:    "LAGRANGE" "MONOMIAL" 
  Approximation Orders:    "FIRST" "CONSTANT" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    hypre boomeramg 


Time Step 0, time = 0

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 1, time = 1, dt = 1


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 1.41421
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131926e-02
      2 Linear |R| = 3.983447e-04
      3 Linear |R| = 5.866306e-06
   Solution, reference convergence variable norms:
   u: 5.86589e-06  u_ref: 1.0002
      0 Linear |R| = 5.865892e-06
      1 Linear |R| = 1.280280e-07
      2 Linear |R| = 2.130741e-09
      3 Linear |R| = 4.463634e-11
   Solution, reference convergence variable norms:
   u: 4.45936e-11  u_ref: 1.0002
 Solve Converged!


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 3.82596e-11  u_ref: 0.866199
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 2, time = 2, dt = 1


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 2.24062
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131927e-02
      2 Linear |R| = 3.983444e-04
      3 Linear |R| = 5.866310e-06
   Solution, reference convergence variable norms:
   u: 5.87815e-06  u_ref: 2.0004
      0 Linear |R| = 5.878150e-06
      1 Linear |R| = 1.282394e-07
      2 Linear |R| = 2.125735e-09
      3 Linear |R| = 4.466799e-11
   Solution, reference convergence variable norms:
   u: 4.47456e-11  u_ref: 2.0004
 Solve Converged!


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 3.83966e-11  u_ref: 1.7324
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

Warning, Exodus files cannot have titles longer than 80 characters.  Your title will be truncated.

Time Step 3, time = 3, dt = 1


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 0.707107  u_ref: 3.16885
      0 Linear |R| = 7.071068e-01
      1 Linear |R| = 2.131925e-02
      2 Linear |R| = 3.983439e-04
      3 Linear |R| = 5.866314e-06
   Solution, reference convergence variable norms:
   u: 5.85539e-06  u_ref: 3.0006
      0 Linear |R| = 5.855390e-06
      1 Linear |R| = 1.282118e-07
      2 Linear |R| = 2.131556e-09
      3 Linear |R| = 4.447813e-11
   Solution, reference convergence variable norms:
   u: 4.45606e-11  u_ref: 3.0006
 Solve Converged!


Updating geometric search patches

   Solution, reference convergence variable norms:
   u: 3.82251e-11  u_ref: 2.5986
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+
| time           | num_nl         | total_nl       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   3.000000e+00 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+

./moose_test-opt -i "/Users/peatna/moose/5moose/moose/test/tests/executioners/executioner/steady.i"
Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:28:47 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   121
  Elems:                   25
  Num Subdomains:          1

Nonlinear System:
  Num DOFs:                121
  Num Local DOFs:          121
  Variables:               "u" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "SECOND" 

Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK


Postprocessor Values:
+----------------+----------------+
| time           | l2_err         |
+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+

 0 Nonlinear |R| = 1.209941e+01
      0 Linear |R| = 1.209941e+01
      1 Linear |R| = 2.420214e+00
      2 Linear |R| = 8.497278e-01
      3 Linear |R| = 5.805302e-01
      4 Linear |R| = 3.214650e-01
      5 Linear |R| = 3.661012e-02
      6 Linear |R| = 5.671226e-03
      7 Linear |R| = 1.147977e-03
      8 Linear |R| = 1.487645e-04
      9 Linear |R| = 4.363960e-05
 1 Nonlinear |R| = 4.361781e-05
      0 Linear |R| = 4.361781e-05
      1 Linear |R| = 1.697511e-05
      2 Linear |R| = 4.131871e-06
      3 Linear |R| = 1.514798e-06
      4 Linear |R| = 3.641608e-07
      5 Linear |R| = 1.209615e-07
      6 Linear |R| = 6.886546e-08
      7 Linear |R| = 3.793717e-08
      8 Linear |R| = 9.949784e-09
      9 Linear |R| = 1.918224e-09
     10 Linear |R| = 4.435765e-10
     11 Linear |R| = 1.770547e-10
 2 Nonlinear |R| = 1.772090e-10
 Solve Converged!

Postprocessor Values:
+----------------+----------------+
| time           | l2_err         |
+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   3.577613e-11 |
+----------------+----------------+

❯ ./moose_test-opt -i "/Users/peatna/moose/5moose/moose/test/tests/executioners/executioner/steady.i"
Framework Information:
MOOSE Version:           git commit a9629f41ab on 2022-09-16
LibMesh Version:         
PETSc Version:           3.16.6
SLEPc Version:           3.16.2
Current Time:            Mon Sep 19 13:29:21 2022
Executable Timestamp:    Fri Sep 16 12:30:15 2022

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   121
  Elems:                   25
  Num Subdomains:          1

Nonlinear System:
  Num DOFs:                121
  Num Local DOFs:          121
  Variables:               "u" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "SECOND" 

Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK


Postprocessor Values:
+----------------+----------------+
| time           | l2_err         |
+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+

      0 Linear |R| = 1.209941e+01
      1 Linear |R| = 2.420214e+00
      2 Linear |R| = 8.497278e-01
      3 Linear |R| = 5.805302e-01
      4 Linear |R| = 3.214650e-01
      5 Linear |R| = 3.661012e-02
      6 Linear |R| = 5.671226e-03
      7 Linear |R| = 1.147977e-03
      8 Linear |R| = 1.487645e-04
      9 Linear |R| = 4.363960e-05
      0 Linear |R| = 4.361781e-05
      1 Linear |R| = 1.697511e-05
      2 Linear |R| = 4.131871e-06
      3 Linear |R| = 1.514798e-06
      4 Linear |R| = 3.641608e-07
      5 Linear |R| = 1.209615e-07
      6 Linear |R| = 6.886546e-08
      7 Linear |R| = 3.793717e-08
      8 Linear |R| = 9.949784e-09
      9 Linear |R| = 1.918224e-09
     10 Linear |R| = 4.435765e-10
     11 Linear |R| = 1.770547e-10
 Solve Converged!

Postprocessor Values:
+----------------+----------------+
| time           | l2_err         |
+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   3.577613e-11 |
+----------------+----------------+

**Comment by GiudGiud** [comment]
squash the commits pls then let s merge

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
test failures unrelated

**Pull request merged**
