### PR TITLE
GeochemistryConstants.h added

### LINKED ISSUE #15117: create GeochemistryConstants
## Reason

Create a file that includes all the constants for geochemistry, such as MOLES_PER_KG_WATER

## Design

Something like
```
constexpr Real MOLES_PER_KG_WATER = 55.51;
```

## Impact

These can be used by all Geochemistry classes, instead of defining them separately for each class

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #15117

### CODE REVIEW

**Comment by WilkAndy** [comment]
Another super easy one for you, @loganharbour

**Comment by loganharbour** [comment]
Shouldn't there be something along side this? At this point, you're adding unused code

**Comment by WilkAndy** [comment]
Yea, it's used in the stuff i haven't yet pushed.  i just wanted to feed it to you in smaller gulps.

**Comment by cpgr** [comment]
Hey Andy, I'm not sure if this is necessary but should the mols_per_kg_h2o have more precision to match the molar mass of H2O? Or is it good enough rounded to two decimal places?

**Comment by WilkAndy** [comment]
Yea, i'm not sure about this either.  Let's leave it as is for now.  I've seen 55, 55.5 and 55.51 used in codes.  I have no idea why they don't use higher precision....

**Comment by loganharbour** [comment]
While I understand the desire to make stuff easier to review, it's generally not a good idea to add code in without it being used. (1) we don't test it and (2) if it's not used now it may not be used later. 

I like that you're ahead of the game, but it's a better idea to just include it in the bigger PR where it's used!

**Comment by WilkAndy** [comment]
OK, no probs @loganharbour - be prepared for a bigger PR soon

**Pull request closed without merging**
