### PR TITLE
Intermediate multi-D slope limiter base for rDG

### PR DESCRIPTION
**Pull request by joshuahansel**

### CODE REVIEW

**Comment by joshuahansel** [comment]
@andrsd Would you review this? @yidongxiainl This is the rDG module change I mentioned.

**Comment by joshuahansel** [comment]
Note: Bighorn breakage is expected. I am currently preparing the fix.

**Review by andrsd — DISMISSED** [review]

**Comment by joshuahansel** [comment]
There's always some problem with my clang-format git hook...

**Review by andrsd — DISMISSED** [review]

**Comment by andrsd** [comment]
bighorn and pronghorn are expected to fail

**Review by andrsd — APPROVED** [review]

**Comment by brianmoose** [comment]
Don't forget blue_crab which has bighorn as a submodule

**Comment by andrsd** [comment]
I am working on that...

**Pull request merged**
