### PR TITLE
Fix INSTemperature jacobian

### PR DESCRIPTION
**Pull request by lindsayad**
- Add `_rho` and `_cp`
- Expand jacobian test to cover `INSTemperature` kernels

### CODE REVIEW

**Comment by lindsayad** [comment]
I don't really think those failing tests are my fault...

**Comment by brianmoose** [comment]
You are probably right. BISON was recently broken but should be fixed now. And those phase_field tests timeout every once in a while.
I invalidated both of "App tests" and "Modules debug".

**Review by jwpeterson — APPROVED** [review]
Thanks for adding the test!

**Comment by brianmoose** [comment]
@lindsayad  It looks like this PR might have caused `laminar_flow.boussinesqSquare` in moltres to start exodiffing https://www.moosebuild.org/job/104611/ 
Don't know why it wasn't caught on the PR, maybe it wasn't in moltres when this PR originally ran.

**Comment by lindsayad** [comment]
Thanks for the heads up. That's a problem on our end if it's exodiffing. We'll fix it

**Pull request merged**
