### PR TITLE
Clean up IterationAdaptiveDT

### LINKED ISSUE #5535: IterationAdaptiveDT cleanup
I'm reading ```IterationAdaptiveDT``` (which does way more than its name suggests - can we make time steppers more modular somehow?!) and had the compulsion to adjust a few style details...
Courtesey ping @bwspenc

### PR DESCRIPTION
**Pull request by dschwen**
And add a few comments.

Closes #5535

### CODE REVIEW

**Comment by dschwen** [comment]
Right. All stream manipulators modify the stream permanently... _except_ ```std::setw``` so I have to put those back in, if you insist on having such elaborate debug output. The combination of setw and setfill('0') seems oddly fortranny to me ;-). Is that really improving legibility of the output?

**Comment by bwspenc** [comment]
Fortranny?  Now this is getting personal...

**Comment by dschwen** [comment]
Haha. Sorry :-( I guess I crossed s line here. I take that back!

**Comment by dschwen** [comment]
It occurred to me that applying the permanent stream modifiers directly to ```_console``` may have unintended side effects.

**Comment by dschwen** [comment]
a4ddea4 is a suggestion to trim a lot of formatting off the debug output.

Old:
```
Shrinking dt: nl its = 6 > 5 || lin its = 21 > 125 old dt: 0.0500000 new dt: 0.0250000
```

New:
```
Shrinking dt: nl its = 6 > 5 || lin its = 21 > 125 old dt:      0.05 new dt:     0.025
```

I would argue that the simplification is actually an improvement. The string of zeroes to lengthen the numbers does not help IMO. One further change could be removing the ```std::setw``` entirely, as it creates a confusing association to the wrong label.

**Comment by dschwen** [comment]
And b2fa610 changes the output to
```
Shrinking dt: nl its = 6 > 5 || lin its = 21 > 125
old dt = 0.05
new dt = 0.025
```

**Comment by andrsd** [comment]
Why use 3 lines? ;-)
```
Shrinking dt: nl its = 6 > 5 || lin its = 21 > 125 (old dt = 0.05, new dt = 0.025)
```

**Comment by bwspenc** [comment]
@dschwen I think the c66b2fb version is the most readable.  As to why it's padded with a bunch of zeroes?  I can't remember.  I think I was fiddling with it on a problem I was working on and liked how the numbers from the various outputs lined up. It's a finely engineered masterpiece of clarity.

**Comment by dschwen** [comment]
Ok, I'll push that commit with a few tiny changes.

**Pull request merged**
