### PR TITLE
Removed redundant Jacobian calculation in ExplicitRK2

### PR DESCRIPTION
**Pull request by yidongxiainl**
Refs #5591

### CODE REVIEW

**Comment by permcody** [comment]
Thanks @yidongxiainl. I assume we already have tests for this case? I just want to make sure so we don't have regressions in the future. In fact it may be worthwhile to add a test where we verify the number of computations.

**Comment by yidongxiainl** [comment]
Yes, there are existing test cases. So no new test case is needed.


Yidong Xia, PhD
Energy, Environment Science & Technology Directorate
Idaho National Laboratory
1955 N. Fremont Ave., PO Box 3560
Idaho Falls, ID 83415-2025
Tel: (208) 526-7490

**Comment by permcody** [comment]
Well @yidongxiainl - that's where you'd be wrong :smile: Without a test that verifies the desired number of Jacobian contributions, it could regress at any time in the future. It happens around here almost daily. I can show you how to make that sort of test.

**Comment by permcody** [comment]
:+1:

**Pull request merged**
