### PR TITLE
Update petsc submodule to 3.21.0

### LINKED ISSUE #27227: Update PETSc submodule
### Motivation

PETSc has recently updated to version 3.21.1. MOOSE should be kept up-to-date with this release.

EDIT (May 10 2023): Changed to 3.21.1

### Design

Update the PETSc submodule and corresponding packages to 3.21.1.

### Impact

New features and bugfixes from PETSc.

### PR DESCRIPTION
**Pull request by cticenhour**
@lindsayad - Leaving #27228 open for now, but wanted to kick testing off for this to see if we can just jump to it instead. 

Closes #27227

### CODE REVIEW

**Comment by lindsayad** [comment]
I've experienced some module failures when working with the `main` branch head. Hopefully this won't be too difficult to resolve but IIRC some of the failures are diffs ☠️

**Comment by milljm** [comment]
I vote we no longer do `make check`.  I feel the paces we put PETSc through with our testing is sufficient.
Besides, with my OpenMPI PR, I am having to disable `make check` due to hangs (again, sigh).

**Comment by lindsayad** [comment]
on what architectures does it hang?

**Comment by lindsayad** [comment]
3.21.1 was released today. It contains a bugfix required for https://github.com/idaholab/moose/pull/27276

**Comment by lindsayad** [comment]
Let me know if you want any help at any point

**Comment by cticenhour** [comment]
Just saw this release. Will reach out. Time constraints have kept me from this PR this week, but I can see the current set of failures in CI and will work toward fixing them up.

**Comment by cticenhour** [comment]
Closing in favor of #27605.

**Pull request closed without merging**
