### PR TITLE
Additional libs

### PR DESCRIPTION
**Pull request by permcody**

### CODE REVIEW

**Comment by snschune** [comment]
This fixes the issue I'm experiencing.

**Comment by permcody** [comment]
Wow - this really doesn't work... Trying to fixup Make is going to be difficult.

**Comment by YaqiWang** [comment]
I am puzzled by the fact that I do not have this linking issue on my mac laptop, same on our test boxes. But bunch of people are having this issue and also with the new package. Any explanation of this?

**Comment by permcody** [comment]
It has to do with dependencies being introduced earlier. I'm not entirely
sure what to do about it.

**Comment by permcody** [comment]
Not sure what to do with this - more work is needed.

**Pull request closed without merging**
