### PR TITLE
Move viscosity derivative calculation from PorousFlow to FluidProperties

### LINKED ISSUE #11011: Move viscosity derivative calculation from PorousFlow to FluidProperties
## Rationale
PorousFlow uses pressure and temperature to calculate fluid properties, but at the moment, the FluidProperties module provides viscosity and its derivatives wrt density and temperature, where PorousFlow really wants derivatives wrt pressure and temperature. 

FluidProperties should provide PorousFlow with the derivative of viscosity wrt pressure (rather than wrt density) so that we don't have to add some additional chain rule derivatives in PorousFlow.

All of the fluid property related derivatives required should be provided by FluidProperties.

## Description
This was initially done this way as the fluid EOS's that we were using had viscosity as a function of density and temperature. To avoid calculating density twice (once to get density, and once to get viscosity), we simply provided viscosity as a function of density and temperature. We definitely didn't want to have to calculate density inside the `mu(p, T)` functions, as it can be expensive.

Fortunately, PorousFlow always calculates density whenever it needs viscosity, so we can provide a new public method `rho_mu(p, T)` in FluidProperties, where we can implement the most efficient calculation of both density and viscosity (e.g., if we need density to calculate viscosity, then we only need to calculate it once).

For example: if `rho = rho(p, T)` and `mu = mu(p, T)`, then
```
rho_mu(p, T)
{ 
  rho = rho(p, T)
  mu = mu(p, T)
}
```
while if `mu = mu(rho, T)`, then
```
rho_mu(p, T)
{ 
  rho = rho(p, T)
  mu = mu(rho, T)
}
```

In this way, each FluidProperties user object can implement the most efficient calculation of both density and viscosity (and similarly, provide the most efficient calculation of derivatives wrt pressure and temperature as well).

This means that the chain rule derivatives like `dmu_dp = dmu_drho * drho_dp` in PorousFlow can be removed, as all derivative calculations are provided by the FluidProperties user objects. 

## Impact
New API for FluidProperties, and an internal change in PorousFlow

### PR DESCRIPTION
**Pull request by cpgr**
Add new methods to calculate density and viscosity (and derivatives wrt pressure and temperature) that can be used by PorousFlow. Viscosity derivative calculations are now handled by FluidProperties, rather than in PorousFlow.

The new methods enable each fluid to provide the most efficient calculation of both density and viscosity to PorousFlow.

Closes #11011

### CODE REVIEW

**Comment by cpgr** [comment]
Hmm, I don't think that I did anything that should break a python test

**Comment by cpgr** [comment]
Thanks Andy

**Comment by andrsd** [comment]
The apps that failed are using the (p,T) interface and we just need to implement the new pure virtuals there. I will do so...

**Review by andrsd — APPROVED** [review]

**Comment by YaqiWang** [comment]
Does this break blue_crab?
```
 class LiFBeF2 : public SinglePhaseFluidPropertiesPT
       ^~~~~~~
In file included from pronghorn/build/header_symlinks/FluidDensityAux.h:5:0,
                 from pronghorn/src/base/PronghornApp.C:47:
../rattlesnake/moose/modules/fluid_properties/build/header_symlinks/SinglePhaseFluidPropertiesPT.h:181:16: note: 	virtual void SinglePhaseFluidPropertiesPT::rho_mu(libMesh::Real, libMesh::Real, libMesh::Real&, libMesh::Real&) const
   virtual void rho_mu(Real pressure, Real temperature, Real & rho, Real & mu) const = 0;
                ^~~~~~
In file included from pronghorn/build/header_symlinks/FluidDensityAux.h:5:0,
                 from pronghorn/src/base/PronghornApp.C:47:
../rattlesnake/moose/modules/fluid_properties/build/header_symlinks/SinglePhaseFluidPropertiesPT.h:194:16: note: 	virtual void SinglePhaseFluidPropertiesPT::rho_mu_dpT(libMesh::Real, libMesh::Real, libMesh::Real&, libMesh::Real&, libMesh::Real&, libMesh::Real&, libMesh::Real&, libMesh::Real&) const
   virtual void rho_mu_dpT(Real pressure,
                ^~~~~~~~~~
```
It current prevents merging from rattlesnake devel to master.

**Comment by andrsd** [comment]
blue_crab should be patched now

**Comment by cpgr** [comment]
Thanks @andrsd

**Pull request merged**
