### PR TITLE
Transition tests from solid mechanics to tensor mechanics

### PR DESCRIPTION
**Pull request by gambka**
This PR includes the tests in the axisymmetric_2d3d_solution_function directory.

Refs #8642

### CODE REVIEW

**Comment by gambka** [comment]
@bwspenc

**Comment by gambka** [comment]
The failing test in debug due to a timeout is not related to this PR.

**Comment by brianmoose** [comment]
There was a problem with the civet server talking to github a little earlier. This is probably due to that. Unfortunately there isn't an easy way for the server to update the github status after the job is done.

**Comment by bwspenc** [comment]
OK.  Since the tests all passed, I'm going to consider them passed then, and will merge this after I review it even though it shows the test in progress.

**Review by bwspenc — COMMENTED** [review]
Just a couple of little things to change:
1) Get rid of the soft links for the _sm gold files.  Output to the same file name as the tm files, and use prereq to prevent them runing at the same time.
2) We can get rid of a few of these files by using cli_args to pass in additional scaling arguments.  Let's clean that up while we're in here.

**Review by bwspenc — APPROVED** [review]
Looks great!  We'll merge when the tests pass.

**Pull request merged**
