### PR TITLE
Add capability to place voids along triple junctions in polycryrstal voronoi

### PR DESCRIPTION
**Pull request by sourabhkadambi**
Addresses  #25182

Creating a new class `PolycrystalVoronoiTJVoidIC` that inherits from `PolycrystalVoronoiVoidIC`. Also adding the required action system.

## Design

- [x] Create new class `PolycrystalVoronoiTJVoidIC` with `computeCircleCenters()` method to place void centers at triple junctions (TJs)
- [x] Add capability to place voids for 2D/ 3D columnar hex (in addition to random voronoi) and distinguish periodic/ non-periodic BCs 
- [x] Use `value` and `gradient` methods of `PolycrystalVoronoiVoidIC` to compute void OP field
- [x] Create a new class and action for `PolycrystalVoronoiCoupledVoidIC` that takes grain OP fields from a polycrystal UO and re-contours the fields around the void OP field, which is passed in as a coupled variable.
(Any void IC, like MultiSmoothCircleIC,  can be used to generate void structure within polycrystal)
(Avoids calling `computeCircleCenters()` method for every grain OP contrary to how it's done ? in current  `PolycrystalVoronoiVoidIC` in Moose)
- [x] Might be useful to restructure `PolycrystalVoronoiVoidIC` by removing `structure_type` option and have `computeCircleCenters()`, `value()` and `gradient()` method only for voids. The `PolycrystalVoronoiCoupledVoidIC` can have the `value()` and `gradient()` methods for grains moved from `PolycrystalVoronoiVoidIC`
- [x] Add tests for 2D hex and 3D voronoi with TJ voids 
- [x] Add a test for 3D columnar hex once PR #25179 is merged
- [x] Fix existing test input files that use `PolycrystalVoronoiVoidIC` for both voids and grains to only for voids and `PolycrystalVoronoiCoupledVoidIC` for grains. Regold if exodiff
- [ ] Similar restructuring will be needed for the `SinteredSurfaceIC` class and the tests via a Marmot PR
- [ ] Create/ update documentation

### CODE REVIEW

**Comment by sourabhkadambi** [comment]
@GiudGiud Precheck failed due to clang style format? But I'm not seeing the post with the patch

**Comment by GiudGiud** [comment]
Seems like clang crashed. Probably a pipeline fluke.

**Comment by GiudGiud** [comment]
Ah it repeated.
Run it locally to try to find why
git-clang-format
https://ortogonal.github.io/cpp/git-clang-format/#:~:text=git%2Dclang%2Dformat%20is%20a,on%20the%20changes%20you%20made.

**Comment by sourabhkadambi** [comment]
> Ah it repeated. Run it locally to try to find why git-clang-format https://ortogonal.github.io/cpp/git-clang-format/#:~:text=git%2Dclang%2Dformat%20is%20a,on%20the%20changes%20you%20made.

Ran git-clang-format on `PolycrystalVoronoiCoupledVoidIC.C`, which is what Precheck shows changed during Clang format. I see the format changes reflected in latest push, but looks like Clang precheck still failed on the same file

**Comment by GiudGiud** [comment]
run it on all your commits
git-clang-format HEAD~1 .... however many commits you have

**Comment by dschwen** [comment]
We still want this

**Pull request closed without merging**
