### PR TITLE
Adding headers to all of MOOSE

### LINKED ISSUE #4729: Header update
As @tonkmr pointed out yesterday we don't have headers in any of the modules. I think we probably should have headers in all project files. @idaholab/moose-developers comments?

### PR DESCRIPTION
**Pull request by permcody**
closes #4729 

This is a massive commit...

### CODE REVIEW

**Comment by friedmud** [comment]
We need to be careful about this.  We can't apply our copyright to anything someone else wrote...

**Comment by permcody** [comment]
That's fine. I'll take a stab at creating some sort of header to apply to
the modules just to designate them as part of the project

**Comment by friedmud** [comment]
Yeah - just something that says it's part of the project and subject to the LGPL license will be good.

**Comment by permcody** [comment]
I changed the header for the modules.
Also honored @WilkAndy's small header.

**Comment by WilkAndy** [comment]
Hi guys,
You are very accommodating to leave my header there, but it's not at all necessary.  I won't be devastated to see it go, and perhaps it'll make moose a bit more uniform.  I'll leave the final decision up to you.  Thanks,

a

**Comment by permcody** [comment]
Well I will say that we can always trade the lineage of any file through
its history without the use of a header. Try out "git blame <filename>".

**Pull request merged**
