### PR TITLE
Consolidate XFEM tests on high order elements

### PR DESCRIPTION
**Pull request by nmnobre**
## Motivation
Tests are sorted in a second order folder. We are now supporting higher orders more and more

## Design
Consolidate tests, rename "second_order" folder to more general "higher order"

## Impact
Easier organization of tests to work with. Matters when adding a new element type

Hi,

Again, no actual changes, just removing some copy and paste cruft so no re-golding shall be necessary.

Cheers,
-N

### CODE REVIEW

**Review by jiangwen84 — DISMISSED** [review]

**Comment by nmnobre** [comment]
I've rerun the tests a couple of times but they keep failing, don't know why? :/

**Review by GiudGiud — APPROVED** [review]
good call

**Comment by cticenhour** [comment]
The `high_order_elements.square_branch_tri7_2d` test here (orig. introduced in #25685, but I'm making this post in the PR with the most-recent changes) has been intermittently failing in the next branch. A recent example of this stopped the build of one of our Apple Silicon binary packages (See results output in https://civet.inl.gov/job/1919812/). @nmnobre do you have time/willingness to take a look at this?

**Comment by nmnobre** [comment]
> The `high_order_elements.square_branch_tri7_2d` test here (orig. introduced in #25685, but I'm making this post in the PR with the most-recent changes) has been intermittently failing in the next branch. A recent example of this stopped the build of one of our Apple Silicon binary packages (See results output in https://civet.inl.gov/job/1919812/). @nmnobre do you have time/willingness to take a look at this?

See #26110. I can try and have a look, though I don't have an Apple Silicon machine.

**Comment by jiangwen84** [comment]
@cticenhour @nmnobre  I will take a look.

**Pull request merged**
