### PR TITLE
Illustrates bug in compute=false Materials

### LINKED ISSUE #9165: cycle through models in ComputeMultipleInelasticStress
### Description of the enhancement or error report

Give the user an option to allow cycling through models in ComputeMultipleInelasticStress: one model per timestep.  Eg
timestep = 0, use model = 0 only
timestep = 1, use model = 1 only
timestep = 2, use model = 2 only
timestep = 3, use model = 0 only
timestep = 4, use model = 1 only
timestep = N, use model N % num_models only

### Rationale for the enhancement or information for reproducing the error

When multiple plastic models are used in the current implementation the returned stress can end up on a "corner" in stress space, where the Jacobian (consistent tangent operator) is not defined, the nonlinear convergence is pretty crappy.  Using the above strategy is obviously incorrect physically, but convergence can be much improved.  Then using lots of timesteps is practically possible and the unphysicalness of the above strategy is reduced.

This won't be a commonly-used flag, but i think it's an easy and worth addition to ComputeMultipleInelasticStress.

@sapitts , @bwspenc 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by WilkAndy**
Tagging @sapitts and @bwspenc 

**See the third commit only!** 

This PR enhances ComputeMultipleInelasticStress by adding a 'cycle_models' flag.  When set true this flag mea ns ComputeMultipleInelasticStress will use only inelastic model (_t_step - 1) % num_models to compute the stress.
The remainder of the compute=false models are ignored for that timestep.
    
Here's the bug.  The compute=false Materials set all of their internally-declared stateful MaterialProperties to zero during any timestep in which they are not called.  This is undesirable behaviour.  Instead, if not called, they should set their stateful MaterialProperties from the corresponding Old values.
    
This PR contains a test that will fail because of this bug.  The test computes a Postprocessor called i_cdp, derived from a stateful MaterialProperty, which is zero for the second timestep, because its corresponding compute=false Material is not called during that timestep.  The correct value is 540, which is the value of i_cdp at the end of the first timestep.
    
This PR won't pass (even if the above bug is fixed), and will probably conflict, until #9148 has been merged.
    
Fixes #9165

### CODE REVIEW

**Comment by bwspenc** [comment]
@WilkAndy The issue of what the behavior should be when a `compute=false` material doesn't get called is probably a question for someone on the MOOSE team like @permcody or @aeslaughter.  It seems like there are two reasonable options in that case: zero it out or copy the old state.  Since it should behave consistently for stateful and non-stateful properties, I can see why zeroing it out would make sense to do.  Maybe that's something that's negotiable -- I'm not sure.

In any event, we could easily work around this by adding a method to `StressUpdateBase` that copies the property from the old state into the new state, and just call that for the models that are skipped in the current step.

**Comment by aeslaughter** [comment]
The "resetQpProperties()" method is called on all materials with "compute=false" by MOOSE. You can do what you need in here.

**Comment by sapitts** [comment]
We'd overwritten that method as an empty method and marked it as `final` in `StressUpdateBase`; can we make the change Ben suggested in `StressUpdateBase` and still retain the 'final`?

**Comment by bwspenc** [comment]
I vaguely remember the whole conversation about `resetQpProperties()`.  It seems like we didn't think we would ever need to do anything with it, so we defined a version of it that would do nothing and made it final so that people wouldn't think they needed to overwrite it.

It sounds like we could copy the old state for some properties in that function in the base class, but we wouldn't know anything about properties that only the derived class knows about.

Since we don't need the old properties copied in most of the time, I don't really think that we should do this all of the time in `resetQpProperties()`.  I still think my original proposal is better for this case.  Define something like `copyOldStateProperties()` in `StressUpdateBase.h`, make every model that derives from that class define their own version of it that copies its properties, and then call that for all of the models that get skipped.

**Comment by WilkAndy** [comment]
We can certainly do as you suggest @bwspenc , with copying the Old properties.

However, i would like to see this functionality be part of the MOOSE framework, not some add-on that we build for our custom situation.  The stateful MaterialProperties really have physical meaning, in every situation that i can think of (not just plasticity, but other solid mechanics and porous flow too) so suddenly making them zero makes no physical sense.

It's easy to imagine someone being caught by this in the future.   Other quantities in MOOSE don't get zeroed just because they don't enter a computation.  Eg, we have shouldApply() for BCs, but when shouldApply()=false for some nodes we don't suddenly make the Variable=0 at those nodes - it just doesn't make physical sense!  It's exactly the same for stateful Material Properties.

**Comment by bwspenc** [comment]
@WilkAndy Yeah, but what are non-stateful material properties supposed to do if they don't get computed?  There is no state to copy into them.  We need to be consistent with that.

**Comment by WilkAndy** [comment]
I'm closing this and replacing with #9170 .  That has cleaner git history and i'm not good enough with git to re-jig this current PR now that #9148 has been merged.

**Pull request closed without merging**
