### PR TITLE
remove calls to MooseRandom::rand() from Point arguments

### LINKED ISSUE #7255: MooseRandom::rand() in function arguments not compatible across compilers
### Description of the enhancement or error report
In RandomHitUserObject, calls are made to MooseRandom::rand() in the arguments when assigning a Point. 

This is bad because some compilers execute arguments left-to-right and some right-to-left. A call to rand() advances the random number sequence. See discussion here:
http://stackoverflow.com/questions/621542/compilers-and-argument-order-of-evaluation-in-c
http://stackoverflow.com/questions/376278/parameter-evaluation-order-before-a-function-calling-in-c

Could this be a reason that executioners/adapt_and_modify test is troublesome?? Couldn't find other examples of this in the framework, which is not surprising. Got a PR ready for this, if anybody cares.

### Rationale for the enhancement or information for reproducing the error

Compare results between compilers and it's pretty easy to see. Only tested gcc and intel, but clang will be like one or the other.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Better consistency across compilers.

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
Removed calls to MooseRandom::rand() here: https://github.com/idaholab/moose/blob/devel/test/src/userobjects/RandomHitUserObject.C#L52

Figured I'd remove the compiler restriction in the test file and see what happens! If this fails miserably then just ignore it...

Closes #7255

### CODE REVIEW

**Comment by friedmud** [comment]
Ummmm... what's this for?  This does the same thing as the old code, but in more lines of code and with possibly more type conversion.

But maybe I don't understand...

**Comment by friedmud** [comment]
Ok - just read your ticket... interesting!

**Comment by friedmud** [comment]
Wow!  Never too old to learn something new (or get a piece of knowledge refreshed) about C++!

This is a really good catch!

**Comment by jessecarterMOOSE** [comment]
Yeah I spent half the day yesterday trying to get to the bottom of why my App gave different answers on Intel and GCC. I grep-ed through the framework and tests and found a similar case as well as associated struggles with that test. I thought I might help.

**Pull request merged**
