### PR TITLE
rename [Modules/TensorMechanics] in tests and examples

### LINKED ISSUE #28696: [Modules/TensorMechanics/Master] in tests and examples
### Motivation

[Modules/TensorMechanics/...] should/has been renamed to [Physics/SolidMechanics/...]. In some of the examples and tests the old [Modules/TensorMechanics/...] is still showing up and should be renamed [Physics/SolidMechanics/...]. 

### Design

In examples and tests rename [Modules/TensorMechanics/...] to [Physics/SolidMechanics/...]

### Impact

Tests and examples use the new [Physics/SolidMechanics/...]

### PR DESCRIPTION
**Pull request by jmeier**
Probably not the most sophisticated PR: Just renaming Modules\TensorMechanis to Physics\SolidMechanics in some tests and examples. 

closes #28696

### CODE REVIEW

**Comment by jmeier** [comment]
> is the large_media change on purpose?

No, sorry!

**Review by GiudGiud — DISMISSED** [review]
all changes as expected

will merge when it passes tests.

**Comment by jmeier** [comment]
> is the large_media change on purpose?

Should be gone now.

**Comment by GiudGiud** [comment]
looks like the inputs there have a "Master" they dont need
contact/test/tests/mortar_dynamics/frictional-mortar-3d-dynamics-light-function * i

**Comment by jmeier** [comment]
> looks like the inputs there have a "Master" they dont need contact/test/tests/mortar_dynamics/frictional-mortar-3d-dynamics-light-function * i

My local AD size is too small so the tests had been skipped on my local machine. Hopefully I've got them all now.

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
