### PR TITLE
Add Graintracker

### LINKED ISSUE #4759: Add Grain Tracker
Move some files around. Vague commit message on purpose, because HEY LOOK OVER THERE! SHINY!

### PR DESCRIPTION
**Pull request by dschwen**
Add Graintracker and EBSDReade, EBSDMesh, and its unit tests. Graintracker tests are skipped for now until we redo a test that does not depend on closed source components.

Closes #4759.

### CODE REVIEW

**Comment by permcody** [comment]
This is pretty cool. Thanks for preserving the history across repos. There's also a "problems" directory that I worked on that I thought I wanted to move but now that I think about it a bit, it's probably ok to leave those problems behind. I'll work on creating a few "examples" instead inside of it's new home in the phase_field module.

@tonkmr or @dschwen I'd like to create adapt one or two examples for this capability. Maybe get  `marmot/problems/GrainMapper/more_grains_than_op(?:_adapt)?.i` working with just the phase field module. I think the only thing that needs to change is the material.

**Comment by dschwen** [comment]
@permcody the ```CuGrGr``` matwerial can be trivially replaced by ```GBEvolution``` with the right parameters```. I did this in 247694dfce

**Comment by permcody** [comment]
Excellent - Thanks! @jwpeterson can merge when you are ready to patch Marmot

**Comment by jwpeterson** [comment]
Do not merge this, we are doing an integration branch thingy along with the GrainTracker PR.

**Comment by jwpeterson** [comment]
Merged to devel in 6fe75fe.

**Pull request closed without merging**
