### PR TITLE
Module test fixups for Big Sur

### PR DESCRIPTION
**Pull request by cticenhour**
Refs #16291

### CODE REVIEW

**Comment by loganharbour** [comment]
@WilkAndy This was one of the reasons I was concerned with console output: ef64633d795cd8bec7333c7190ea42812a22977b

**Comment by cticenhour** [comment]
It's definitely going to be a tricky problem to fixup, if console output is still desired. Since Big Sur dropped that single stoichiometric coefficient down by 1e-4, I thought that tightening the tolerance of that test on all platforms would help bring that number down (not knowing the platform, I wasn't sure what else to try). It doesn't seem to do so in my testing on moosebuild.

**Comment by WilkAndy** [comment]
This failure is not a big problem.  It comes from rounding 0.96875 to either 0.9687 or 0.9688 depending on the `precision`, as set by lines like
```
  std::stringstream ss;
  ss << std::setprecision(precision);
```

In the test at hand, i believe you can just increase the precision, by including `precision = 5` in the `[TimeIndependentReactionSolver]` of the test `combined/examples/geochem-porous_flow/geotes_weber_tensleep/eqm_model_25degC_no_precip.i`.  Viz, the final lines of that file should look like:
```
  temperature = 25
  stoichiometric_ionic_str_using_Cl_only = true
  precision = 5
[]
```

Then use the following in the `expect_out` of the `tests` file
```
Minerals:
Illite = 5*H2O - 8*H+ + 3.5*SiO2(aq) + 2.3*Al+++ + 0.25*Mg++ + 0.6*K+;  log10K = 9.7964;  SI = 9.7925
Kaolinite = 5*H2O - 6*H+ + 2*SiO2(aq) + 2*Al+++;  log10K = 7.4341;  SI = 7.734
K-feldspar = 2*H2O - 4*H+ + 3*SiO2(aq) + 1*Al+++ + 1*K+;  log10K = 0.065455;  SI = 7.1657
Albite = 2*H2O - 4*H+ + 3*SiO2(aq) + 1*Al+++ + 1*Na+;  log10K = 3.0808;  SI = 5.7026
Pyrrhotite = -0.125*H2O - 0.71875*H+ + 0.03125*SO4-- + 0.875*Fe++ + 0.96875*HS-;  log10K = -5.5573;  SI = 3.5197
Barite = 1*SO4-- + 1*Ba++;  log10K = -9.9729;  SI = 2.6139
Quartz = 1*SiO2(aq);  log10K = -4.0098;  SI = 1.3755
Chalcedony = 1*SiO2(aq);  log10K = -3.7384;  SI = 1.1042
Siderite = -1*H+ + 1*HCO3- + 1*Fe++;  log10K = -0.22246;  SI = 0.81967
Dolomite = -2*H+ + 2*HCO3- + 1*Ca++ + 1*Mg++;  log10K = 2.5162;  SI = 0.3875
Calcite = -1*H+ + 1*HCO3- + 1*Ca++;  log10K = 1.7105;  SI = 0.018304
Fluorite = 1*Ca++ + 2*F-;  log10K = -10.968;  SI = -0.11047
Celestite = 1*SO4-- + 1*Sr++;  log10K = -6.4427;  SI = -0.62617
Anhydrite = 1*SO4-- + 1*Ca++;  log10K = -4.2739;  SI = -1.1179
Goethite = 1.5*H2O - 1.875*H+ + 0.125*SO4-- + 1*Fe++ - 0.125*HS-;  log10K = 9.3083;  SI = -1.2487
```

**NOTE: you should also run the heavy tests - there might be problems in those too!**

**Comment by cticenhour** [comment]
Thanks @WilkAndy. I was looking through the other components of the `TimeIndependentReactionSolver` Action, and somehow missed the precision parameter in your `GeochemistryConsoleOutput` object. Too focused on the algebraic system! 

Heavy tests looked good in geochemistry and combined with no modifications.

**Review by loganharbour — DISMISSED** [review]
👍🏼 

FYI next is broken right now and will be probably for most of the day until a bison update makes its way through

**Comment by cticenhour** [comment]
Sounds good - no rush on this.

**Comment by cticenhour** [comment]
Actually, I found a couple heavy tests in contact and tensor mechanics that need to be fixed up. Passing on Linux, but I didn't realize we didn't do a heavy mac test. One more commit coming down the pipe later today.

**Comment by cticenhour** [comment]
@loganharbour can you re-approve this? I've rebased to ensure nothing changed in the meantime while this PR has sat. Still a couple heavy tests to fix up on Mac, but I want to put that in a part 2 since this PR has stagnated for some time without me being able to really get to it.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
