### PR TITLE
Help occasional conda users use moose environment by default

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #26972

### CODE REVIEW

**Comment by loganharbour** [comment]
I don't know if I'm the biggest fan of this... I don't like telling people to add things to their profiles.

I foresee people adding things to their `moose` environment when they intend to add it to another environment if we suggest this.

**Comment by GiudGiud** [comment]
> I foresee people adding things to their moose environment when they intend to add it to another environment if we suggest this.

If conda works properly, this should not be a problem
The text already told them to do this. We just didnt give them something to copy paste so they did not do it

**Comment by milljm** [comment]
I think I am okay with this, in the fact a power user will see that and say "NO WAY." And not do it, and that is okay. But someone not understanding what this code block even does... maybe this is perfect.

We all hated when cars told us our doors were ajar, but what do people think about adding a message that we are activating the moose environment? Personally, I don't like my own suggesting. And the prompt changing from `(base)` to `(moose)` should be enough.

**Comment by GiudGiud** [comment]
Over the last week we have had 3 users on discussions that forgot to activate moose. 
This week was crazy, this is not our steady-state stream of users. But still would be nice to smooth out the peaks

**Comment by milljm** [comment]
> Over the last week we have had 3 users on discussions that forgot to activate moose.
This week was crazy, this is not our steady-state stream of users. But still would be nice to smooth out the peaks

Indeed, this week saw a lot of new comers.

I was hoping to get @dschwen opinion. I respect this power-users opinion. And has voiced my troublesome Conda recipes in the past!

**Review by milljm — APPROVED** [review]
I am okay with this. But I would like other's opinion as well!

**Review by dschwen — APPROVED** [review]

**Pull request merged**
