### PR TITLE
Small AD Creep fix

### PR DESCRIPTION
**Pull request by tophmatthews**

### CODE REVIEW

**Comment by tophmatthews** [comment]
ping @dschwen ... super small bug

**Review by dschwen — APPROVED** [review]
Yep, that change is definitely required as both variables are used by the solution bracketing and contribute to the final result!

**Comment by dschwen** [comment]
Ok, lesson learned here is to be more careful with `MetaPhysicL::raw_value`...

**Comment by tophmatthews** [comment]
Yeah...its a bit tricky to know when to use it...maybe a best practices guide would be helpful for all

**Comment by tophmatthews** [comment]
This made its way to master, try the ad assessments again @acasagran

**Pull request merged**
