### PR TITLE
Remove unused class

### PR DESCRIPTION
**Pull request by permcody**
refs #920

### CODE REVIEW

**Comment by rwcarlsen** [comment]
This seems to break Magpie with exodiffs maybe?

**Comment by dschwen** [comment]
Hm, we're getting ye olde `exodiff: ERROR: .. Dimension doesn't agree.` Thought we fixed that with idaholab/magpie#374

**Comment by dschwen** [comment]
Looks like nowadays we're not merging to master anymore courtesy of mammoth...

**Comment by permcody** [comment]
No - we are getting merges to master. This PR was independent though of that fix. Should be fine to merge.

**Comment by dschwen** [comment]
Oh, I see now. It is just the magpie master branch that fails its test. Yeah, looks like invalidating the 1 day old test helped. When that test ran the mesh fix was not yet in magpie master.

**Review by rwcarlsen — APPROVED** [review]

**Pull request merged**
