### PR TITLE
Add missing tasks for DynamicTensorMechanicsAction

### LINKED ISSUE #8182: DynamicTensorMechanicsAction is missing a task registration
### Description of the enhancement or error report
The coordinate systems do not get checked and an internal member not initialized.

### Rationale for the enhancement or information for reproducing the error
Fails Valgrind. Is not valid.

### Identified impact
Fixes a breakage.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #8182

### CODE REVIEW

**Comment by permcody** [comment]
Looks like you fixed most of the errors. There are still two tests failing with uninitialized memory.

**Comment by dschwen** [comment]
Ahh, same deal `PoroMechanicsAction` is derived from `TensorMechanicsAction`. I'll need to register that one to the additional tasks as well.

**Comment by dschwen** [comment]
@permcody this is ready for another review. Valgrind passed this time.

**Comment by permcody** [comment]
Cool, thanks

**Review by permcody — APPROVED** [review]

**Pull request merged**
