### PR TITLE
Update libmesh

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:

  - Add sanity check to System::init_data() 
  - Continue petsc_unique_ptr refactor
  - Drop SHA1 and use C++11 std::hash
  - Add/use petsc_unique_ptr template alias
  - SparsityPattern refactoring
  - Add EDGE4 case to get_refspace_nodes
  - RB: Fix an issue where nodes in multiple nodesets were assembled twice
  - Use unique_ptrs to clean up PETSc objects
  - Fix CompareTypes typos in type_vector
  - Default/delete special functions for System classes.
  - Exodus copy fixes
  - Add API to tell mesh it is not prepared
  - Don't potentially throw from 'exceptionless' error macros
  - Make ReferenceCounter::increment_{de,con}structor_count() noexcept
  - Re-enable check_dirichlet_bcid_consistency()
  - Mention "make uninstall" in README.md
  - Deprecate public MeshBase::boundary_info member
  - Updates to InfFEBase::build_elem()
  - Ubuntu 20.10 clang 11 warning fixes
  - Ubuntu 20.10 (gcc 10.2) fixes
  - Move LinearSolver to ImplicitSystem
  - UnsteadySolver: old_local_nonlinear_solution should be a std::shared_ptr
  - Simplify unique_ptr return statements
  - Fix incorrect use of unique_ptrs in TransientSystem
  - PeriodicBoundaries should store unique_ptrs instead of dumb ptrs
  - Simplify DiagonalMatrix::zero_clone() slightly
  - Add ExodusII_IO::write_nodeset_data() API
  - Rebase #2506 and some minor clean-up
  - TypeVector overloads for std::norm and friends for Eigen::Matrix
  - Unsteady Adjoint Error Estimation Implementation (Model Error)
  - Submodule updates
  - Avoid manual memory management in System class
  - More IGA tests
  - Use "-f" when using mv to overwrite our own files

### CODE REVIEW

**Comment by gambka** [comment]
Does an email still go out with changes to libmesh or when users should update using `conda update --all`? Previously, there would be emails when it was updated telling users to run the `./update_and_rebuild_libmesh` script. I have noticed the only time I've been updating using `conda update --all` is when I have a failure  when compiling due to needed libmesh changes. An email or notification like before would be helpful.

**Comment by lindsayad** [comment]
Yes you're right Kyle. I've been lax recently. My apologies. I'll stop
being so lazy!

**Review by zachmprince — DISMISSED** [review]

**Comment by zachmprince** [comment]
@lindsayad looks like that change to the meta.yaml file was removed. Is that still needed?

**Comment by lindsayad** [comment]
> @lindsayad looks like that change to the meta.yaml file was removed. Is that still needed?

Yep! Thanks!

**Review by zachmprince — APPROVED** [review]

**Pull request merged**
