### PR TITLE
Update PETSc to 3.15.1

### LINKED ISSUE #18125: Update PETSc to 3.15.1
## Reason

Use new PETSc features

## Design

Update to 3.15.1

## Impact
None

### PR DESCRIPTION
**Pull request by fdkong**
Close #18125

### CODE REVIEW

**Review by milljm — DISMISSED** [review]
looks good to me.

**Review by loganharbour — DISMISSED** [review]

**Comment by milljm** [comment]
It looks as though the End User Experience tests, pulled down PETSc 3.14.2 by mistake. Need to investigate...

**Comment by milljm** [comment]
LOL... we always forget. Even I. You have to modify libMesh's `conda_build_config.yaml`, to point towards the new version of PETSc you want _libmesh_ to depend on.

```diff
diff --git a/conda/libmesh/conda_build_config.yaml b/conda/libmesh/conda_build_config.yaml
index 57712316b0..dc5910b539 100644
--- a/conda/libmesh/conda_build_config.yaml
+++ b/conda/libmesh/conda_build_config.yaml
@@ -24,7 +24,7 @@ libpng:
   - 1.6.37 hed695b0_0 # [linux]
 
 moose_petsc:
- - 3.14.2 build_4
+ - 3.15.1 build_0
 
 moose_libmesh_vtk:
  - 6.3.0 build_5
```

**Comment by tophmatthews** [comment]
Is there somewhere the new features that pertain to moose are listed?

**Review by loganharbour — APPROVED** [review]

**Comment by fdkong** [comment]
Here is a complete list of PETSc updates https://www.mcs.anl.gov/petsc/documentation/changes/315.html

There are several things that may be interesting for the moose community 

1. Communication optimization for parallel computation (we do not need to do anything)

2. Add the option MAT_FORCE_DIAGONAL_ENTRIES for MatSetOption(). It forces allocation of all diagonal entries. We often miss diag for ILU/LU in MOOSE. This is the right way to fix the issue 

3.  KSP/SNESConvergedReasonViewSet allows to have fine-control on convergence messages in moose

**Review by milljm — APPROVED** [review]
👍 looks good to me. But I think I was the last one to make changes, so I probably shouldn't be allowed to review my own changes :)

**Pull request merged**
