### PR TITLE
Small cleanup, add tests to phase field examples

### LINKED ISSUE #10307: Update phase field examples
## Rationale
Phase field examples in phase_field and combined are using out of date syntax

## Description
Update to use new actions, remove unnecessary block params etc.

## Impact
More modern examples for new users to start from

### PR DESCRIPTION
**Pull request by dschwen**
Most of what the issue refers to had already been done. This adds a few syntax tests and cleanups so that we can 

Close #10307

### CODE REVIEW

**Comment by dschwen** [comment]
No, @aeslaughter and @permcody . We do not need SQA tags for examples!

**Comment by permcody** [comment]
Fair enough, we'll have to agree on what makes a test versus an example before this can be implemented. The directory path?

**Comment by dschwen** [comment]
A simple top level parameter 

```
[Tests]
  example = true
  ...
[]
```

could be added to satisfy the SQA check

**Comment by permcody** [comment]
As long as people don't abuse that. I worry that we'll start seeing that syntax pop up in the normal tests directory. I'm think I'm more inclined to have a key in the testroot file that says what the "example" directories are (e.g. not under NQA control because they aren't part of the RTM) versus tests. This would give us the flexibility to use something besides "examples" for a given application (i.e. tutorials, or problems).

**Comment by dschwen** [comment]
People can already abuse the system by putting in bogus or empty strings to satisfy the automatic SQA tester. At some point human review has to take the responsibility.

**Pull request closed without merging**
