### PR TITLE
Examples added to PorousFlow

### LINKED ISSUE #10683: Add fracture flow example to PorousFlow
## Rationale

Fracture flow using PorousFlow is often asked about.  With this example we can simply point to an explicit worked example with documentation.

## Description

Philipp Schaedle has worked up a simple and detailed example that demonstrates the correctness of using embedded 2D fractures in a 3D matrix.

## Impact

Something for people to follow when they want to model fracture flow.

### LINKED ISSUE #10710: Add underground mining example to PorousFlow
## Rationale

Another example of use of PorousFlow - this time a fluid-solid coupled one.

## Description

Similar to the tesnro mechanics example, but with a single-phase unsaturated fluid (water)

## Impact

Examples = good for users

### PR DESCRIPTION
**Pull request by WilkAndy**
Fracture flow example.  Fixes #10683
Underground mining example.  Fixes #10710

### CODE REVIEW

**Comment by WilkAndy** [comment]
Yep, this is a larger commit - two examples, each with quite complicated input meshes and pictures.  Also some large gold files.

**Comment by WilkAndy** [comment]
Tagging @philippschaedle .  Lots of this is your work.  I haven't included the "finite-fracture-width" example yet, but will do when you send it.  It can either be added to this PR or put in a separate PR later.

**Comment by WilkAndy** [comment]
heat_conduction, recover.recover_3 is hosed.  nothing to do with this PR.

**Comment by permcody** [comment]
This doesn't seem right. +26MB in MOOSE? Why not use the media submodule?

**Comment by WilkAndy** [comment]
I am using the large_media for some movies (not counted in the 26MB).  i can certainly use large_media for some pictures, which would amount to maybe 2MB.  About half the 26MB is input exodus files for the examples, and about half are exodus gold files.  One way of getting rid of them would be to not (heavy) test the examples, and to put the input exodus files in large_media.  I toyed with not having those input exodus files at all, but i think examples should not be "hey, here's the input file, but you've got to generate the mesh yourself".  I don't want to simplify the examples - i want them to be fully-fledged reasonably realistic things.  Any ideas?

**Comment by WilkAndy** [comment]
Being more specific:

| Type | Size | Comment
| - | - | - |
| documentation (.md) | 44K |  |
| figures for documentation (.png) | 756K | |
| input files + tests files | 104K | | 
| "flow" example input exodus | 2.7M | Don't want to reduce |
| "mining" example input exodus | 7.2M | Could reduce by 7M if i provide doco on how to create the mesh instead of providing the mesh itself, or put this mesh into large_media |
| "flow" example gold exodus | 13M | Could reduce by 13M if i don't do heavy testing |
| "mining" example gold exodus | 3.7M | Could reduce by 3M if i test final timestep only |


What do you think?

**Comment by permcody** [comment]
We've been chatting about this and are brainstorming ideas for supporting these really large exodus files. We are thinking about generalizing the large_media repo to be more than just images and movies. One could argue that large examples could/should go there as well. What if we moved the large media repository to the root of MOOSE and allowed you to create example directories and inputs inside of the media repo?

**Comment by WilkAndy** [comment]
Yea, i don't see any disadvantages in that idea, from the point of PorousFlow.  We'd still have the markdown doco and it'd refer to large_media instead.  Many users wouldn't even realise that the files weren't in modules.

**Comment by WilkAndy** [comment]
So do i have to do anything now (like moving stuff inside large_media) or are you planning to re-organise things first and then i do my stuff?

**Comment by permcody** [comment]
We need to figure this out first.

@friedmud, @aeslaughter, @milljm: Any suggestions on how we go about moving this submodule? What's it going to break, etc?

**Comment by WilkAndy** [comment]
Can we try to get this merged this week?  I've got a deadline coming up and it'd be great if i could demonstrate this work was complete.

**Comment by permcody** [comment]
@WilkAndy - Please base your changes on #10812. We are promoting the location of the large_media submodule and expanding it's purpose to accommodate more large file types.

**Comment by WilkAndy** [comment]
Yep, great, thanks for your help here,

a

**Comment by WilkAndy** [comment]
Python doco tests failed, unrelated to this PR.  Could someone please invalidate those tests when the python stuff is fixed?

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for your help with my latest batch of PRs,

a

**Pull request merged**
