### PR TITLE
Exposing the ability to read TetGen meshes in MOOSE.

### LINKED ISSUE #20694: FileMeshGenerator does not load *.ele files from Tetgen
## Reason
Even though libMesh has `TetGenIO`, `FileMeshGenerator` treats currently `*.ele` files as exodus files.

## Design
Something about checking the file types is not very right in `FileMeshGenerator` thus not dispatch the file to the correct loaders in libMesh. This capability is needed because we have tetrahedra mess generated with TetGen.

## Impact
To be able to load meshes from TetGen.

### PR DESCRIPTION
**Pull request by permcody**
closes #20694

The issue here was that the use of `rfind` has issues in that it'll return true for matches in the middle of the string. LibMesh's NameBasedIO handles this by making sure that more specific matches (`*.ele`) always occur before less specific matches (`*.e`). Since we defer to NameBasedIO for everything but Exodus (which unfortunantely uses the `*.e` match, we were incorrectly matching TetGen's extension to Exodus.

### CODE REVIEW

**Comment by permcody** [comment]
This is literally a one-line change!

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — CHANGES_REQUESTED** [review]
Need to clear up exodus/hdf5 issue

**Comment by loganharbour** [comment]
@permcody you need to rebase on devel and regold your new file

**Comment by permcody** [comment]
Yep, will do. Not my highest priority but will get to it.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
