### PR TITLE
Reorganizing misc module

### LINKED ISSUE #9787: Organize Misc Module
### Description of the enhancement or error report

There is no directory structure in the misc module. It's just two folders, a `src` and `include` directory. This is inconsistent with other modules and applications and makes it difficult to find what one is looking for in the pile of objects.

### Rationale for the enhancement or information for reproducing the error

Misc should be consistent with framework and modules.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None

### PR DESCRIPTION
**Pull request by permcody**
Moving existing objects into folder structure
Deleting a few untested/unused objects
Moving a few combined tests into the phase_field module after moving
test code into the phase_field/test application

closes #9787, #5282

### CODE REVIEW

**Comment by dschwen** [comment]
How about you rename `test/tests/flood_counter_aux_test/tests` to `test/tests/flood_counter_aux/tests` (I'm not a fan of having tests named ...test, they are already in a two layers of test directories).

**Comment by permcody** [comment]
Sure I can make that change.

**Comment by permcody** [comment]
Hmm, I ran `./moosedocs.py check` - No Errors! Liar...
@aeslaughter

**Comment by aeslaughter** [comment]
The check didn't error, but the build did. These are two different things.

**Review by jwpeterson — APPROVED** [review]
Seems fine to me, although I would like to go on record as saying this will probably break someone's app that we aren't testing...

**Pull request merged**
