### PR TITLE
Fixes access to block/boundary names given material property

### LINKED ISSUE #4420: FEProblem::getMaterialPropertyBoundaryNames() problem
Currently this function can return a string vector containing "-1". This probably should be either expanded with the list of side set names or something more meaningful like "ALL_BOUNDARY".

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #4420)

### CODE REVIEW

**Comment by jwpeterson** [comment]
@aeslaughter is still going to do a bit more work on here, making something return the string "ANY_BOUNDARY_ID"

**Comment by aeslaughter** [comment]
This is ready to go, see #4489 to discuss @permcody test object ideas.

**Comment by friedmud** [comment]
As for the debate about testing objects... I actually prefer to have a bunch of small testing objects that test individual features.  That way when something fails it's easy to track down.

This is actually what MooseTest is for... I don't consider it bloat because it doesn't get compiled unless you specifically go do it.

So far we've done a really good job of using objects from MOOSE itself to do the testing with... but sometimes there is no way around it (I recently had to add an object to test solution vector serialization - nothing in MOOSE was using it).

Also: I would MUCH rather add to MooseTest than add to MOOSE itself...

Finally: If you think of these testing objects like Unit tests then having one object per feature makes sense.... that's what we do in MooseUnit for instance...

**Comment by friedmud** [comment]
Specifically I don't want to see this:

```
TestAux::execute()
{
  switch(test_type)
  {
    case 0:
      // Test SomeObject
    case 1:
      // Test AnotherObject
    case 2:
      // Test a feature
    case 3:
      // more testing
    case 4:
      // yet another test
  }
}
```

Yuck!

MOOSE is designed for lots of small objects... and that's the way we should do our testing as well.

**Comment by aeslaughter** [comment]
@friedmud Just to be clear, I don't think we should TestObjects would be in MOOSE, it would still be in tests/src.

However, I generally side with you. Lets see what @permcody says, he was the one that really doesn't like all the objects.

**Comment by friedmud** [comment]
Seriously... the more I think about this... the more it makes me sick to think of monolithic testing objects.  Thousands of parameters... hundreds of class member variabes... spaghetti of if statements and case statements.

Just straight up NO.

That said - we should be judicious in creating new testing code... try to reuse what we already have when possible.  BUT: Like I said, I think we've been really good about doing this up to now and I don't see any reason to make a policy change.

Derek

**Comment by YaqiWang** [comment]
Test codes can currently indicate what is going wrong for us, which is really nice. The size of test codes should not be a big issue due to the duplication in them IMO. Most of these duplication are really stable in MOOSE and will possibly not cause any painful refactoring. We do not need to make test codes fancy. ;-)

**Comment by friedmud** [comment]
@aeslaughter Right: I was just saying that if we start to make rules about what kinds of objects we can put in MooseTest people might prefer to put "testing code" over into MOOSE (there are lots of objects in MooseTest that aren't "testing" code... but also necessarily aren't useful enough to be in MOOSE either)

Things like:
https://github.com/idaholab/moose/blob/devel/test/include/bcs/DGMDDBC.h
https://github.com/idaholab/moose/blob/devel/test/include/bcs/OnOffNeumannBC.h
https://github.com/idaholab/moose/blob/devel/test/include/bcs/PolyCoupledDirichletBC.h
https://github.com/idaholab/moose/blob/devel/test/include/bcs/ScalarVarBC.h

And many more.

Each of those "could" be in MOOSE (arguably it's possible that _someone_ might find them useful)... but we were using them to exercise a bit of code.  If we start restricting what goes in MooseTest then that might lead to a few more of these types of objects actually ending up in MOOSE itself...

**Comment by friedmud** [comment]
Let's move over to #4489 for discussion

**Pull request merged**
