### PR TITLE
Make SinglePhaseFluidPropertiesPT interface consistent

### PR DESCRIPTION
**Pull request by andrsd**
This adds 2 functions:

1. k(p, T)
2. mu(p, T)

The interface already has computation of k and mu, but in terms for density and temperature.  This stays, but  under different names: `k_from_rho_T` and `mu_from_rho_T`.

### CODE REVIEW

**Comment by andrsd** [comment]
Tagging @cpgr @aprilnovak and @lingzou 

These are the changes I proposed in #10142

**Comment by andrsd** [comment]
Fixed the unit tests

**Comment by cpgr** [comment]
Looks good @andrsd.

Is it worth implementing `mu(p,T)` as
````
mu(p, T)
{
  return mu_from_rho(rho(p, T), T);
}
````
rather than have an error? It is inefficient because density has to be calculated first, but it would give viscosity for all of the fluids.

**Comment by andrsd** [comment]
Yeah, I can do that. And let's hope people won't copy this into their `(p, T)` formulations :-)

**Comment by andrsd** [comment]
Implemented `mu` and `k` and added bunch of unit tests for it.

**Review by cpgr — APPROVED** [review]
Thanks @andrsd

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
This PR and https://hpcgitlab.inl.gov/idaholab/pronghorn/merge_requests/68 cause pronghorn to be broken: https://www.moosebuild.org/job/128874/ . They got merged in similar time frames which is why testing didn't catch it.

**Comment by andrsd** [comment]
ok, I will make a MR to fix it.

**Pull request merged**
