### PR TITLE
Do not give cryptic error in FEProblemBase::addTransfer

### PR DESCRIPTION
**Pull request by lindsayad**
Also fix typos: 'directions' to 'direction' towards bottom of `MultiAppTransfer` constructor

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]

**Comment by lindsayad** [comment]
I'm all turned around. The parameter names here are right. I don't know what's going on in this input yet

**Comment by lindsayad** [comment]
Ok so the deprecated `direction` parameter used `to_multiapp` and the new blessed parameter is `to_multi_app` ...

**Comment by GiudGiud** [comment]
yes

**Comment by lindsayad** [comment]
Ok the user specified the `direction` parameter but none of `multi_app`, `to_multi_app`, `from_multi_app` ... that's the problem. And that's why we got the "we should never get here error"

**Comment by lindsayad** [comment]
> Ok the user specified the `direction` parameter but none of `multi_app`, `to_multi_app`, `from_multi_app` ... that's the problem. And that's why we got the "we should never get here" error

Ok that's not it either 😆 . Because I see there is proper error handling for this in the bottom of the`MultiAppTransfer` constructor ... this just must not be a `MultiAppTransfer`?

**Comment by lindsayad** [comment]
I'm an idiot ... the `addTransfer` error happens before construction for the `EXEC_SAME_AS_MULTIAPP` case hence why we don't get the opportunity to get to the nice error checking in the constructor

**Comment by lindsayad** [comment]
Ok, now this should be ready

**Comment by lindsayad** [comment]
I suppose that the coverage report will show me what we're not hitting in the test harness

**Review by fdkong — DISMISSED** [review]

**Comment by lindsayad** [comment]
@GiudGiud does this look good?

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
