### PR TITLE
Change default line search

### LINKED ISSUE #12388: Change default line search
## Rationale

We have received several examples on the mailing list where non-linear solves perform much better with no line search. A specific example is in mechanical contact and I have also observed it in NavierStokes, Moltres, and Zapdos.

## Description

Cubic back-tracking can be much too strict in requiring a certain residual reduction in each non-linear step. This can be particularly problematic when the current solution/residual is close to a local minimum.

## Impact

Hopefully by changing to no line search as the default, users solves will generally perform better.

### PR DESCRIPTION
**Pull request by lindsayad**
Changes default line search from cubic bracktracking to none.

Closes #12388.

### CODE REVIEW

**Comment by fdkong** [comment]
Looks good for me

**Comment by mangerij** [comment]
Ferret should be fine now. thanks

**Comment by lindsayad** [comment]
I'm going to reopen this, motivated by the ORNL BISON training where for a simple mechanics problem we go from 17 nonlinears to 3-4 just by going to `line_search = none`

**Comment by lindsayad** [comment]
I’m not gonna let it die this time!

**Comment by lindsayad** [comment]
Boo you stale bot

**Comment by permcody** [comment]
Oct 2019? Stale bot is just doing its job.

**Comment by fdkong** [comment]
Any way to disable Stale bot for a particular PR? Sometimes a PR could be large, and could not get done any soon while the PR author was distracted by other tasks. 

In this situation, Stale bot should not close the PR.

**Comment by lindsayad** [comment]
> Oct 2019? Stale bot is just doing its job.

Haha, I am a big supporter of stale bot in general, but I had to tell it something in order to stop its nefarious plan to close this.

**Comment by permcody** [comment]
I doubt there’s a way to disable it. Any action in 30 days will reset it.
That usually is enough.

**Comment by lindsayad** [comment]
boo

**Comment by lindsayad** [comment]
foo

**Comment by permcody** [comment]
foo? Seriously? 😂

**Comment by lindsayad** [comment]
I don’t care enough about this to keep fighting you stale bot!

**Pull request closed without merging**
