### PR TITLE
Modified crystal plasticity, plasticity code and tests to plug and play

### PR DESCRIPTION
**Pull request by cpritam**
### Complete each of the following items before creating a PR
- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)
  #6973

### CODE REVIEW

**Comment by dschwen** [comment]
Looks good to me. Do you have a fix for Grizzly?

**Comment by cpritam** [comment]
Yes.

**Comment by jwpeterson** [comment]
Guys, what is going on here?  You are holding up master merges because grizzly is broken.  We need to coordinate better than this.

**Comment by jwpeterson** [comment]
@cpritam @dschwen let's get this fixed

**Pull request merged**
