### PR TITLE
Correcting heavy test and failing PBS test due to contact patch updat…

### LINKED ISSUE #10439: Correcting heavy test and test that failed in PBS mode due to contact patch update
## Rationale
Correcting tests that failed due to #9832. 
1 contact heavy test failed because a warning was being converted into an error. 
2 PBS tests failed because two tests were writing to the same file and one of them and the final output file did not match the gold file.

### PR DESCRIPTION
**Pull request by sveerara**
…e #10439

corrects tests that failed due to PR #9832 using comments from @milljm.  

@brianmoose, can you please start the heavy test and PBS test on this PR? Thanks!

closes #10439

### CODE REVIEW

**Comment by brianmoose** [comment]
Added "PBS Test" and "Test Heavy"

**Review by bwspenc — DISMISSED** [review]

**Comment by sveerara** [comment]
The intel test that is failing (combined/test/tests/normalized_penalty/normalized_penalty_kin.i) is most probably not failing because of the changes I made in #9832. 

@bwspenc, do you know why that contact test is failing on intel processor?

**Comment by permcody** [comment]
Don't know about that contact test just yet. We merged a lot of PRs yesterday but we can confirm that it started yesterday so maybe it's related to the nanoflann stuff. We really need to fix or disable that test as it's already causing havoc. It's very random and when it fails, the result looks WAY different so something is definitely wrong with that test.

**Comment by permcody** [comment]
Oh - to be specific, this test fails randomly!

**Comment by bwspenc** [comment]
It looks like that test just has an unreasonably tight tolerance, so it's not quite converging, even though the residual is low. @sveerara, since you're in the middle of fixing things, could you just try loosening up nl_abs_tol to 1e-9 on that test? It looks to me like that will do the trick. The results are way off because it's comparing different time steps.

**Comment by sveerara** [comment]
Sure, I will loosen up the tolerance and update the PR

**Review by permcody — APPROVED** [review]

**Pull request merged**
