### PR TITLE
Physical test for 2d steady state heat equation

### PR DESCRIPTION
**Pull request by twh5306**
this is in ref to issue #6181 and is a steady state heat conduction example in which a plat 2 units by two units is has its left, right, and bottom edges held at 0 deg C, while the top is exposed to 10sin(pi_x/2) degrees.  This is compared to the analytical solution of (10/sinh(pi))_sin(pi_x/2)_sinh(pi*y/2) using the error calculators already in moose.  Note that the thermal conductivity, specific heat, and density in this problem are set to 1, and need to be changed to the constants of the material being analyzed.

### CODE REVIEW

**Comment by twh5306** [comment]
I can't figure out why this is failing, any thoughts?

**Comment by brianmoose** [comment]
If you go to the "Details" link and look at the output it says you are missing a ticket reference (ie contains #<number> ). The ticket reference needs to be in a commit message.

**Comment by twh5306** [comment]
@brianmoose how should I go about correcting this?

**Comment by brianmoose** [comment]
You can read https://help.github.com/articles/changing-a-commit-message/
On your local repo:
git commit --amend
Add your reference, which for you looks like "refs #6181" or if it closes
the issue "Closes #6181"
Then do a force push:
git push --force

**Comment by twh5306** [comment]
Thanks @brianmoose

**Comment by jwpeterson** [comment]
Still waiting for a log-log plot of the error under refinement confirming the correct rate before merging.

**Comment by twh5306** [comment]
picture1

**Comment by jwpeterson** [comment]
The slope of this line is approximately 0.5.

Did you by chance put log(error) on the x-axis instead of the y-axis?  Flipping the axes would probably make the slope = 2.

**Comment by twh5306** [comment]
yes error is on the x axis in that plot

**Comment by twh5306** [comment]
2d other log log
This is a plot with error on the y axis

**Comment by jwpeterson** [comment]
Looks better.  One last thing: using the actual data points, compute the actual slope of this line and let us know what it is.

**Comment by dschwen** [comment]
The graph looks like a lightsaber.

**Comment by twh5306** [comment]
slope is 1.999937.  Also @dschwen i thought it looked like a lightsaber too, its why i picked it :)

**Pull request merged**
