### PR TITLE
Cache subdomain changes

### LINKED ISSUE #23371: ElementSubdomainModifier should not modify SubdomainIDs during the element loop
## Reason
`ElementSubdomainModifier` is currently changing `element->subdomain_id()` in `execute()`. This will cause UOs in the same execution stage operating on the same element (or face of the same element), see a subdomain ID that is inconsistent with the current subdomain set in `onSubdomainChange`. This will trip [this assertion](https://github.com/idaholab/moose/blob/198b8ca429115454bf7e56c78ec5004492136d1a/framework/src/base/Assembly.C#L1895-L1896) for example.

## Design
Store all subdomain id reassignments in a list first and only apply them to the elements in finalize.

## Impact
More robust capability. Ping @dewenyushu

### PR DESCRIPTION
**Pull request by dschwen**
Closes #23371

### CODE REVIEW

**Review by hugary1995 — DISMISSED** [review]
Looks good. Can we add a regression test for this?

**Comment by dschwen** [comment]
Test added. I confirmed that the new test fails with the current MOOSE in dbg mode, but passes with this PR.

**Comment by dschwen** [comment]
The tests didn't cover displaced meshes. New test added.

**Review by hugary1995 — APPROVED** [review]
Looks good to me. This PR can fix the referenced issue.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
