### PR TITLE
Updated HHT time integration scheme in solid mechanics module 

### LINKED ISSUE #5537: Rayleigh_HHT
Rayleigh damping and HHT time integration capabilities added in Solid Mechanics kernels StressDivergence.C and SolidMechInertialForce.C

### PR DESCRIPTION
**Pull request by sveerara**
Closes #5537

### CODE REVIEW

**Comment by dschwen** [comment]
Could you please add a description to this issue. I would make reviewing the code easier.

**Comment by sveerara** [comment]
Equation of motion with both HHT and Rayleigh damping:
M*accel + (eta*M+ zeta*K)*[(1+alpha)*vel - alpha*vel_old] +
(1+alpha)*K*disp - alpha*K*disp_old = Fext(t+alpha*dt)

Here, eta and zeta are Rayleigh damping parameters and alpha is HHT time
integration parameter.

This is same as:
M*accel + eta*M*[(1+alpha)*vel - alpha*vel_old] + zeta*K*[(1+alpha)*vel-
alpha*vel_old] + (1+alpha)*K*disp - alpha*K*disp = Fext(t+alpha*dt)

1. The first two terms in the left are solved using Inertial_force.h

2. The next three terms in the left are solved using StressDivergence.C.
The -zeta*K*alpha*vel_old term requires stress_older.

3. To get stress_older, a boolean flag store_stress_older is added to
SolidModel.C. Material property Stress_older is declared if the boolean
flag is set to true in the input file.

4. For the external forces (Pressure and Gravity), the time at which the
function is calculated is changed from t to t+ alpha*dt

5. Added wave propagation tests in 1-D

**Comment by jwpeterson** [comment]
In the future, please make two separate commits (one for code, one for test updates) to make reviewing online easier.  I'll split this one up for you and merge by hand.

**Comment by sveerara** [comment]
Thanks. I will put the code and tests in different commits from next time.

**Comment by jwpeterson** [comment]
Merged in a3814c7.

**Pull request closed without merging**
