### PR TITLE
Adds basic control logic system

### PR DESCRIPTION
**Pull request by aeslaughter**
This adds the basic structure for control logic, let the discussion begin.

Note, I did not implement the requirement that a parameter be defined as controllable (e.g., addControllableParam) but this will be easy if we go that route, I want more discussion from the people who plan on using this.

Consider a graduate student whos advisor says "I want to understand how sensitive BISION is to a parameter." The student now needs to modify BISON before they can even start, which doesn't seem right.

@permcody @friedmud @andrsd 
(refs #4604)

### CODE REVIEW

**Comment by permcody** [comment]
Indeed, this is an implementation of the original design but I was pretty sold on Derek's idea of the `declareControlable()` route. While this is certainly more flexible, it'll be difficult managing the ability of object to write to nearly any parameter in the system.

**Comment by aeslaughter** [comment]
I thought we had talked about `addControllableParam`, just like `addPararm` in the `validParams` functions, this will be easy to add with this formulation. @permcody How do you want `declareControllable` to work?

Will I agree managing a system that can change anything may be difficult, but equally difficult is adding `addControllableParam` function calls everytime a parameter might be wanted to be controlled by some in the future.

**Comment by permcody** [comment]
While everything you are saying is true, ultimately it would allow object
developers to publish a list of params that could be controlled. There
would certainly be work to get our applications up to par so that you could
control the bulk of parameters but ultimately it would give us a little
more safety on what could be changed and what is off-limits. When we had
this discussion we determined this whole InputParameters warehouse would be
unnecessary. I'm just bringing up the discussion we had.

**Comment by aeslaughter** [comment]
What about making a method in InputParameters like `addParamNamesToGroup`, but called `declareControllable`, so validParams would look like this:

```
InputParameters validParam<MyObject>()
{
  InputParameters params = validParams<Kernel>();
  params.addParam<Real>("param", "doc");
  params.addParam<std::string>("param2", "doc");

  params.declareControllable("param param2");
  return params;
}
```

**Comment by mangerij** [comment]
Just so I'm following along; is this regarding the future ability to change/control input file parameters during the simulation ie after a certain time step or when a certain criterion is satisfied?

**Comment by permcody** [comment]
Yes, that's what we're after.

**Comment by mangerij** [comment]
Will some of the PETSc flags be able to be controlled during the solve as well?

**Comment by permcody** [comment]
Well it'll be a plug-able system like everything else so it should be
possible.

**Comment by friedmud** [comment]
Well... "You allow it" pretty much dooms the current design.  That's all I'm going to say about that.

The question is... what should a safer design look like.

I like `declareControllable()`... but the one thing that bothers me about it is that there is no way for Peacock / external person to know what's controllable and what's not.

What bothers me about `addControllableParam()` is... what if you want to control something that's not an "input parameter"?  What if you want to declare some datastructure as "controllable"?

That could be a corner case though... that might not be worth worrying about for now.

I'm not 100% against the idea of adding parameters to a "controllable" group... that's really up to @permcody .  It's either do that or incur the combinatorial issue of `addRequiredControllableParam()` etc.  I'm probably fine either way although... I do think `addControllableParam()` does seem to roll of the tongue nicely...

@mangerij brings up a good point about PETSc options.  To allow them to be controllable we would need to do a whole hell of a lot more than just set the value of `petsc_options_iname` and `petsc_options_value` in the `Executioner` object.  We would actually need to parse those things up and call the PETSc function to set the new parameters.

That kind of means there needs to be a callback associated with these things.  In general... it might be important to not just be able to change a value... but also to notify an object that a value has changed so that it can take some action.

I could see an interface similar to `computeQpOffDiagJacobian()` where you call `controlled("name")` and it gives you back a unique identifier for a controlled parameter.  Then you override `controllableChanged(unsigned int identifier)` and use `if` statements to figure out what changed and take appropriate action.

**Comment by joshua-cogliati-inl** [comment]
"there is no way for Peacock / external person to know what's controllable and what's not."  For what it is worth, in relap-7 and raven there is a "--dump-ctrl" command line argument.  The "--dump-ctrl"  is used with an input file to output what controllable parameters there are in the input file.  We parse the dump-ctrl and the yaml to figure out what can go into the control portion of an input file.

**Comment by dschwen** [comment]
Well, the point here is that the application developers will have to _declare_ controllable parameters as controllable. If an input parameter is only used in the constructor to set an independent variable, that variable will not get updated when the input parameter gets changed.

**Comment by aeslaughter** [comment]
On Thu, Aug 27, 2015 at 10:13 PM, Derek Gaston <notifications@github.com>
wrote:

> Well... "You allow it" pretty much dooms the current design. That's all
> I'm going to say about that.
>
> The question is... what should a safer design look like.
>
> I like declareControllable()... but the one thing that bothers me about
> it is that there is no way for Peacock / external person to know what's
> controllable and what's not.
>
I still don't understand what this means, does this replace `getParam` or
what? Give me an example of how this is used.

> What bothers me about addControllableParam() is... what if you want to
> control something that's not an "input parameter"? What if you want to
> declare some datastructure as "controllable"?
>
> That could be a corner case though... that might not be worth worrying
> about for now.
>
This was never in the original design I will need to think about this...but
it seems like controllable parameters are just becoming an arbitrarily
typed Postprocessor, which is maybe what we need.

I'm not 100% against the idea of adding parameters to a "controllable"
> group... that's really up to @permcody <https://github.com/permcody> .
> It's either do that or incur the combinatorial issue of
> addRequiredControllableParam() etc. I'm probably fine either way
> although... I do thin addControllableParam() does seem to roll of the
> tongue nicely...
>
<https://github.com/mangerij>
>
I can go either way on this as well, the group idea was just to reduce the
explosion of add methods, but I agree that a function seems more correct.

> @mangerij <https://github.com/mangerij> brings up a good point about
> PETSc options. To allow them to be controllable we would need to do a whole
> hell of a lot more than just set the value of petsc_options_iname and
> petsc_options_value in the Executioner object. We would actually need to
> parse those things up and call the PETSc function to set the new parameters.
>
This type of handling the change can occur in the "execute" method,  you
can do what ever you want in there. As of now the Control base is a general
user object, by I am thinking there will be a whole suite of these deals
(Nodal, Elemental,...) just like Postprocessors.


> That kind of means there needs to be a callback associated with these
> things. In general... it might be important to not just be able to change a
> value... but also to notify an object that a value has changed so that it
> can take some action.
>
This seems to be too much, after every command in MOOSE we would need to
inspect the set of controllable items and check if they changed, then call
a function if they have. If you just limit the check to certain times
(e.g., timestep_end, residual, etc.) then the "execute" method is doing
this already.

> I could see an interface similar to computeQpOffDiagJacobian() where you
> call controlled("name") and it gives you back a unique identifier for a
> controlled parameter. Then you override controllableChanged(unsigned int
> identifier) and use if statements to figure out what changed and take
> appropriate action.
>
This is just adding complexity in my opinion. In a Control object you have
a writeable reference to the value and a method to determine when it is
checked or updated. Inside the "execute" method the user can check the
value and do something if it changed and call whatever function they
want...why add an identifier system on top and extra methods?

**Comment by aeslaughter** [comment]
If we go with a special method for adding parameters to be controlled
(i.e., addControllable...) we can absolutely dump the syntax and have
peacock understand it.

**Comment by aeslaughter** [comment]
Correct. But making the developers declare something as controllable will
hopefully make them think about the type, i.e., I need to get and use a
reference to this controllable thingy so something else can change it.

**Comment by friedmud** [comment]
> The "--dump-ctrl" is used with an input file to output what controllable parameters there are in the input file.

Yep... what I was saying is that that's only possible when "controllable" parameters are added via the InputParameters object... otherwise there is no way to dump them without constructing the object... which is hard.

> I still don't understand what this means, does this replace `getParam` or
what? Give me an example of how this is used.

Basically... the two systems I am talking about are:

1.  InputParameter based.  Somehow the parameter is "flagged" in `validParams()` as being "controllable".

2.  Declaration based.  This would make it similar to the way `declareProperty<T>()` works in the `Material` system.  Any object could declare any type of data using `declareControllable<T>()`.  MOOSE will set aside the memory and make it available via a `getControllable<T>()` or whatever in other objects.

System (1) has advantages in being able to dump out the available controllable paramters for every object just like we can dump out syntax.

System (2) is more flexible... allowing for any type of data to be "controlled".  With the large downside that you can't know what data is controllable for an object using any sort of `--dump` type thing.

> This type of handling the change can occur in the "execute" method,  you
can do what ever you want in there.

That's not good enough.  Think about the PETSc options example.

We don't want to have to infer state... it would be better to be notified.

> This seems to be too much, after every command in MOOSE we would need to
inspect the set of controllable items and check if they changed, then call
a function if they have.

Nope.  You're still thinking too rigidly of these things being a piece of memory that someone else is going to modify without MOOSE knowing.  It doesn't have to work that way.  It could work out that what you need to do is call `setControllable<T>("name", value)` in order to set a value... that would automatically call this "callback" function for the object that declared that Controllable.

This gives MOOSE a full view of what's going on... I REALLY, REALLY don't like the idea of just giving the control logic (or anything, anywhere) a _writeable reference_ to memory that they can just abuse.  MOOSE needs to be the gatekeeper here... even if we don't want / need to do this callback mechanism.

**Comment by aeslaughter** [comment]
I am still not quite following the declare methodology, but I understand the concept. But, when you start going down this route it seems like you should just write a custom whatever (Material, UserObject, Postprocessor, etc.) to do what you need. Why have a complete other system to customize the behavior of MOOSE stuff, when the purpose of MOOSE is just that to customize objects?

**Comment by friedmud** [comment]
Well... you would think so (about creating custom objects) until you go look at a BISON Material that has several hundred lines of code in it... and all you want to do is change one parameter... AND you're not a BISON developer (you're working on coupling Relap-7 and BISON).

I agree that inheritance is the best way to do large-scale customization... but sometimes you just need to change a small value inside an otherwise large routine.  Creating a virtual function you can override and committing that to BISON and then creating an inherited class to modify that one value in your one use case is a bit heavy-handed.  Especially when you might need to do the same to dozens of objects.

I mean: are you now arguing against the idea of control-logic all together?  Everything done in control logic can definitely be done by inheriting and creating custom classes that just does the correct control logic thing inside those classes at the right time.  But talk about a PITA...

**Comment by aeslaughter** [comment]
I am working on implementing some of the stuff in the comments here, I will re-open later.

**Pull request closed without merging**
