### PR TITLE
Topological optimization in stochastic tools module

### PR DESCRIPTION
**Pull request by snschune**
@Ramzy1990 @lynnmunday 

## Reason

A topological optimization capability in the stochastic tools module.

## Design

The sampler proposes configuration. A reporter makes decisions to accept or reject
them. We use simulated annealing as algorithm.

## Impact

New capability.

### CODE REVIEW

**Comment by snschune** [comment]
Keep open.

**Comment by lynnmunday** [comment]
@snschune  Me and Ramzy will start working on this in two weeks!

**Comment by Ramzy1990** [comment]
Thank you! Okay, rebasing or resetting to before the merge will need a force push and I am not allowed to do it. Apologies @snschune for the trouble!

**Comment by GiudGiud** [comment]
@lynnmunday @Ramzy1990 any update on this?

**Pull request closed without merging**
