### PR TITLE
PorousFlow tests use consistent HIT formatting

### LINKED ISSUE #17024: Uniformize PorousFlow test-file syntax
## Reason

As mentioned by @cpgr  in #16995, some PorousFlow test/example files have

```
[blah]
  blah
  blah
[]
```

while others have

```
[./blah]
  blah
  blah
[../]
```

## Design

Use the former syntax everywhere

## Impact

Uniform look-and-feel will help new users

### PR DESCRIPTION
**Pull request by WilkAndy**
Oh my goodness, this looks like a huge set of changes, but they're all trivial.

Fixes #17024

### CODE REVIEW

**Review by loganharbour — APPROVED** [review]
You really wanna make sure you stay up top on that file changed count in MOOSE, eh @WilkAndy? 😄

**Comment by WilkAndy** [comment]
Yea, crazy amounts of lines changed.  Thanks for the merge, @loganharbour

**Comment by cpgr** [comment]
Hopefully you could do this with a script and not by hand!

**Comment by WilkAndy** [comment]
What?   It took me ages, even with my quite high typing speed.   But at least it wasn't boring.

**Pull request merged**
