### PR TITLE
Clear command line prefix before adding a multiapp

### LINKED ISSUE #9446: A strange issue on passing command line parameter to MultiApp
### Description of the enhancement or error report
I have a case where 5 MultiApp are added. When I add `--distributed-mesh` in command line, I noticed only the master and the first added MultiApp is using the distributed mesh. The rest of MultiApps are still using the replicated mesh.

### Rationale for the enhancement or information for reproducing the error
Supposedly the command line argument should be passed into the multi-apps.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
MultiApp system reliability.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #9446.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody welcome back? This should be an easy PR for you to review.

**Comment by permcody** [comment]
Yeah I started to look at this before I left but couldn't understand why it hasn't plagued us until now. Can you explain why you ran into this?

**Comment by YaqiWang** [comment]
Sure. All multiapps and master are sharing the same command line. The command line prefix will be changed by parsing multiapp at
https://github.com/idaholab/moose/blob/devel/framework/src/parser/Parser.C#L175-L187,
which happens later than
https://github.com/idaholab/moose/blob/devel/framework/src/multiapps/MultiApp.C#L541,
which will be calling
https://github.com/idaholab/moose/blob/devel/framework/src/base/AppFactory.C#L86
to set command line arguments.

If we do not clear prefix and when we have more than 1 multiapp, the second multiapp will be seeing the command line prefix set by parsing of the first multiapp. Consequently, arguments like `--distributed-mesh` will be see by the master and the first multiapp, but not the rest of multiapps. I think it is the right thing to clear the prefix before adding the multiapp and then later let the multiapp parser to set the proper prefix. Hopefully this is clear.

**Comment by permcody** [comment]
Yeah, that helps. Thanks for the explanation.

**Review by permcody — APPROVED** [review]

**Pull request merged**
