### PR TITLE
Moving nodal_patch_recovery to tensor_mechanics docs

### LINKED ISSUE #19644: Test design page in tensor_mechanics is not picked up by downstream apps
## Bug Description
The test `modules/tensor_mechanics/test/tests/nodal_patch_recovery/tests` includes a design page (`nodal_patch_recovery.md`) that is located in the `modules/doc/content/help/finite_element_concepts/` directory, which most apps do not include in their moosedocs config file. So when building SQA with tensor_mechanics as a dependency, there will be error saying the file can't be found.

## Steps to Reproduce
Example of error in Griffin

```
MooseDocs.extensions.sqa (ForkProcess-7): 
SQA ERROR: Failed to locate the design page 'nodal_patch_recovery.md'
/ramdisk/civet/build_0/griffin/moose/modules/tensor_mechanics/test/tests/nodal_patch_recovery/tests:9
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 9│nodal_patch_recovery.md                                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/ramdisk/civet/build_0/griffin/moose/python/MooseDocs/extensions/sqa.py", line 448, in createToken
    node = self.translator.findPage(d)
  File "/ramdisk/civet/build_0/griffin/moose/python/MooseDocs/base/Translator.py", line 209, in findPage
    raise exceptions.MooseDocsException(msg)
MooseDocs.common.exceptions.MooseDocsException: Unable to locate a page that ends with the name 'nodal_patch_recovery.md'. Did you mean one of the following:
     NodalPatchRecoveryAux.md
     restart_recover.md
     patch_to_code.md
     MathFreeEnergy.md
     TotalFreeEnergy.md



MooseDocs.Executioner (MainProcess): Translating complete [192.16862297058105 sec.]
MooseDocs.Executioner (MainProcess): Translating (rendering and writing) using 4 threads...
MooseDocs.base.renderers (ForkProcess-12): 
RENDER ERROR: Unable to locate the design page: nodal_patch_recovery.md
    /ramdisk/civet/build_0/griffin/moose/modules/tensor_mechanics/test/tests/nodal_patch_recovery/tests:9
/ramdisk/civet/build_0/griffin/moose/modules/tensor_mechanics/doc/content/modules/tensor_mechanics/sqa/tensor_mechanics_rtm.md:14
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
14│                                                                                                │
15│                                                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/ramdisk/civet/build_0/griffin/moose/python/MooseDocs/base/renderers.py", line 77, in render
    el = func(parent, token, page) if func else parent
  File "/ramdisk/civet/build_0/griffin/moose/python/MooseDocs/extensions/sqa.py", line 774, in createHTML
    node = self.findDesign(token['filename'], design, token['line'])
  File "/ramdisk/civet/build_0/griffin/moose/python/MooseDocs/extensions/sqa.py", line 768, in findDesign
    raise exceptions.MooseDocsException(msg, design, filename, line)
MooseDocs.common.exceptions.MooseDocsException: Unable to locate the design page: nodal_patch_recovery.md
    /ramdisk/civet/build_0/griffin/moose/modules/tensor_mechanics/test/tests/nodal_patch_recovery/tests:9
```

## Impact
Preventing merges.

### PR DESCRIPTION
**Pull request by zachmprince**
Closes #19644

### CODE REVIEW

**Review by bwspenc — DISMISSED** [review]

**Comment by bwspenc** [comment]
As I noted in the slack discussion, I think we'll need to make a symlink in the framework that points to the .md file that was moved in this commit. That will allow the apps that point to this file to pass their doc builds. Once this gets merged in and we remove the line in the config files for those apps that point to this file, we can do a separate commit that removes that symlink.

**Comment by zachmprince** [comment]
Okay, I created a symlink so hopefully the documentation tests won't fail now.

**Comment by zachmprince** [comment]
@bwspenc any idea what the errors in Blackbear and Grizzly are? They seem to have been built fine, but exited with an error code.

**Comment by bwspenc** [comment]
@zachmprince This is the error. It's there, but doesn't really stand out from the other output:
```
MooseDocs.common.get_content (MainProcess): Unknown file provided in content (it is being removed):
/ramdisk/civet/build_0/moose/modules/doc/content/help/finite_element_concepts/nodal_patch_recovery.md
```
I don't get why it's complaining because I think that file exists as a symlink, doesn't it?

**Comment by loganharbour** [comment]
Do we not follow symlinks in docs?

**Comment by bwspenc** [comment]
@loganharbour That seems like the most likely explanation. Maybe we just need to copy that file over temporarily, and then delete it once we stop referring to it from the app doc pages.

**Comment by zachmprince** [comment]
This is becoming painful. I recommend reverting the last two commits and let Grizzly, blackbear, and Griffin break temporarily.

**Comment by bwspenc** [comment]
@zachmprince Should we still do this, or is it not worth the trouble?

**Pull request closed without merging**
