### PR TITLE
AD MOOSE

### PR DESCRIPTION
**Pull request by friedmud**
The code fairy has left you a package :wink: 

I probably should have done this a few years ago... but better late than never.

This adds proper Automatic Differentiation support to MOOSE!

It's using @roystgnr 's https://github.com/roystgnr/MetaPhysicL , but of course it's all wrapped up nice and tidy so our users don't even see any templating!

Here's how it works:
1.  There is a new type called `ADReal`.  Use it anywhere you would normally use a `Real` and it will keep track of derivative information.  (other new types: ADRealVectorValue, ADRealTensor, ADVariableValue, ADVariableGradient, ADVariableSecond)
2.  There is a new `Kernel` called `ADKernel` that implements `computeJacobian()` and `computeOffDiagJacobian()` automatically.  All a user needs to do is inherit from `ADKernel` and fill out `computeQpResidual()` like normal and all the Jacobian stuff is taken care of!
3.  To enable this `MooseVariable` can now be asked for AD versions of value, gradient and second derivative (note that "old" and "older" are unnecessary as they don't need to carry derivative information).  Currently these values are only computed for Element quadrature points (just the point that I'm at currently... nothing stopping the rest).
4.  ADReal also works as a material property!  That means, for the first time, we can get _perfect_ derivatives of residuals... even if they couple to highly nonlinear material properties (including off-diagonal Jacobians!)
5.  MetaPhysicL tracks derivatives in a big long vector that hangs off of a regular Real value.  I'm using each entry in that vector to represent the derivative of the quantity with respect to a particular coefficient on the current element.  To do that, I compute an offset into that vector for each variable (using the maximum number of DoFs by any variable on any element.. the new `MaxVarNDofsPerElem` object).
6.  There is currently a bug in MetaPhysicL so we cannot use dynamically sized derivative vectors... the current limit is 100 DoFs per element... set arbitrarily by me to just get up and running.  Once @roystgnr gives me the green light I'll switch over to dynamically sized stuff and the 100 DoF per element restriction will go away.
7.  This all requires C++11... I guess it's time to thrown that switch (we're going to want it for that scripting language that @aeslaughter found anyway)

I've implemented all of this _along side_ the current way of doing things.  This means that we can merge this in, even if it's not complete.  I would like to do that so that I can start to get some feedback and find bugs.

Note: I know it won't pass the tests right now... mainly because of C++11 support.  I've added a crap-ton of tests on my own too... trying to cover most corners, but, as with any new tests I'm sure I'll need to shake them out a bit.

All-in-all this is not bad at all.  It all went a little more smoothly than I thought.  There is still a lot left to do (look at my list over here: https://github.com/idaholab/moose/issues/5658 ) but this is a REALLY good start!

### CODE REVIEW

**Comment by roystgnr** [comment]
I'm totally in favor of requiring C++11 (or 14... the drafts of 17 are looking good...) but if DualNumber or NumberArray are failing with C++03 then that's a bug I need to fix; I tried my best to keep those compatible.

**Comment by permcody** [comment]
What kind of code fairy? 

Hopefully not this one: https://www.youtube.com/watch?v=mEB7WbTTlu4

**Comment by dschwen** [comment]
OK, this is pretty cool, especially in light of the discussion about the grad_u derivatives. What I need now are higher order derivatives not w.r.t. the DOFs but w.r.t. the variables themselves. We could go the route that @roystgnr suggested a year or so ago, which is templating FParser on dual number types. With the current setup this does not seem possible though - the metaphysics package would have to be moved to libmesh for that. It would make the whole JIT business a bit messier, too (although I could make JIT a no-op for ADReal-type FParser objects for now). 
This way the two systems could be complementary.

**Comment by friedmud** [comment]
@dschwen I think they are complimentary.

I know how to get this new stuff to compute per-variable derivatives simultaneously with the per-dof derivatives (cool!).  I'll implement that this afternoon.

Then, I say, let your FParser still compute derivatives if people are using that system... then we can just take the derivatives from FParser and _set_ the derivative directly on an `ADReal`... like this:

```
  ADReal some_val = value_from_f_parser;
  som_val.derivatives()[var_number] = derivative_from_f_parser
```

That will set the value and derivative of an `ADReal`... and then the rest of the system can act on an `ADReal` without knowing that derivative was actually computed by FParser.

I think it's pretty slick and it should work perfectly.

**Comment by jwpeterson** [comment]
Should we add MetaPhysicL as a git submodule for https://github.com/roystgnr/MetaPhysicL instead of just copying it into contrib.  Seems like it's under active development...

**Comment by dschwen** [comment]
What about adding it at libMesh level (to make it usable in FParser!)?

**Comment by permcody** [comment]
I like the way in debug that this compiles for hours then crashes the compiler and possibly moose_build too!  Yay let's merge it!.  Perhaps my earlier video share was accurate...

**Comment by roystgnr** [comment]
"Under active development" is such a polite way to say "still fixing all the bugs".

Not sure I want to add a git submodule to libMesh, but the "try to remember to manually copy changes to and from upstream" alternative isn't any better.

**Comment by roystgnr** [comment]
Compile time shouldn't be nearly so bad with just DualNumber and NumberArray.

Or maybe I've become inured to the DualExpression + NamedIndexArray + VexCL compile times and now anything less no longer registers...

**Comment by permcody** [comment]
I could dig into it. The log shows an unbelieve number of warnings, but I don't know if it's related to your stuff or Derek's.

**Comment by roystgnr** [comment]
Speaking of synching up subprojects: there's going to be a bunch of commits coming into MetaPhysicL shortly, but no need to bother examining or copying them.  When I get the dynamic sparse stuff fully working I'll comment about it here.

**Comment by friedmud** [comment]
This compiles fine in debug with Clang... no extra slowdown or anything that I can detect. Might actually be a bug in that version of GCC.

So: about a submodule: I didn't go down that path for two reasons:

1.  Because I wanted to replace the build system with our simple stuff anyway. I don't want this to have to have yet another script (update_and_rebuild_metaphysicl.py ?) when it's really pretty straightforward headers.

2.  I didn't think that it was large enough to warrant a submodule.

3.  (I guess I have 3 reasons) after we get this working well and shake most of the issues out - I don't see us syncing with Metaphysicl _that_ often.

BUT: I would like to contribute back patches... and the best way to do that is to have a full repo.

I'm up for whatever :-)

**Comment by friedmud** [comment]
So: let's talk a little bit about the design here.  I need some input before I continue.

I was actually saved a little bit by the fact that `KernelBase` existed.  It means that I could create new virtual functions of `ADReal computeQpResidual()` without the typical issue of clashing return type.

However, `IntegratedBC` (for instance) doesn't have the same thing (`computeQpResidual()` is already taken).  To follow my design for Kernels I would need to create `IntegratedBCBase` that _doesn't_ have `computeQpResidual()` so that I could have both `Real` and `ADReal` versions of that in `IntegratedBC` and `ADIntegratedBC`.

Following on from that... I'll need to do the same thing for `NodalBC`, `DiracKernel` and `DGKernel`.  Does that sound reasonable?

**Comment by permcody** [comment]
I expect that any C++11 stuff will be slightly more picky on GCC than Clang. I already invalidated your modules_dbg once and it failed to compile on a different box in the same way.

**Comment by roystgnr** [comment]
DynamicSparseNumberVector ought to be in useable shape (for your purposes; I've still got two tests disabled until I implement transpose()...) as of https://github.com/roystgnr/MetaPhysicL/commit/2259c22e6c20a2044c782858cf4c40dd51e45171

**Comment by friedmud** [comment]
I've identified some performance "issues" with this approach to AD.  Namely... residual computation is ~10x slower with the current ADReal choice and ~100x slower if we switch to @roystgnr 's new sparse derivative storage.

You guys know that I never rush optimization... but 10-100x slower is hard to ignore and might mean rearchitecting this whole thing.

SO: To make it easier to work on optimization I've created a new MOOSE-based application called "Meta": https://github.com/friedmud/meta

Meta uses MetaPhysicL as a submodule (it wasn't _that_ hard to enable... so we might go this route for MOOSE too) and I shoe-horned all of the important bits from this PR into a Kernel called `ADTestKernel`.

Meta will allow us to modify MetaPhysicL and recompile without having to recompile all of MOOSE (I spent a lot of time doing that yesterday and last night.. ugh)... shortening the modify->compile->run cycle for optimization.

If you go into meta/problems there are two input files to compare the solve speed on.  They are set to pure JFNK so that the timing basically represents residual computation time.  On my laptop `simple_diffusion.i` has `compute_residual()` taking 3.6566 seconds while `ad_simple_diffusion.i` compute residual takes 28.7045 seconds.  If you edit `ADTestKernel.h/C` and swap over to the sparse storage compute residual takes 185.9074 seconds.

I have some optimization ideas and so does @roystgnr (you can see some of his over here: https://github.com/roystgnr/MetaPhysicL/issues/1 ).  Hopefully we can get this ironed out quickly...

**Comment by friedmud** [comment]
I should make it clear that the new "Meta" application works with the current MOOSE HEAD.... NOT with this PR.

**Comment by permcody** [comment]
Thanks for the work on this. Clearly there is more work to do and also we have to resolve our C++11 discussion before this can become a reality. I'll close this PR, now that we've all seen this. Hold onto this branch.

**Comment by friedmud** [comment]
This is actually closer than you think... I just need a little bit of time.
I'll reopen it then.

**Comment by permcody** [comment]
Just remember that each time you push it actually crashes our test
system... no kidding.

**Comment by friedmud** [comment]
Lol - can we install slightly newer compilers on the test system. The code
works without C++11... there is no reason the compiler should be choking on
this...

**Comment by permcody** [comment]
Yes, it should... If you want to push again, just give me a heads up and
I'll pull your branch down and test interactively to see what's going on

**Comment by lindsayad** [comment]
@friedmud Do you think we should use this as the starting point for new AD work? I'm probably going to check this out and play with it a bit

**Comment by friedmud** [comment]
@lindsayad  Yes - at least I would like you to understand it so we can have a discussion about what it does right / wrong before we move on.  It gets a lot of things right... and the ideas may carry over well to what we ultimately decide to do.

**Comment by friedmud** [comment]
@lindsayad Also, check out my todo list over here: https://github.com/idaholab/moose/issues/5658

**Comment by lindsayad** [comment]
I'm curious what success you would have building this branch right now with our existing environments...it's been a fun battle this afternoon, and so far I've lost. Might be more successful trying to rebase onto a more modern MOOSE/libmesh. Currently this branch requires a downgrade to PETSc 3.6.4 to build out of the box (because of some changes in TAO). Then PETSc 3.6.4 appears to be unable to build with llvm-5 (although it can with earlier llvm and with current gcc). However, with current gcc, there are build errors from `isnan` declarations in `exodiff.C`. That should be easy to fix, but I'm heading home for the day.

**Comment by friedmud** [comment]
Bummer - let’s talk about it today. I would think we would want to rebase
it - but I’m not sure how practical that is with the MooseVariable
splitting and reorganization...

**Pull request closed without merging**
