### PR TITLE
Create input file exploder

### PR DESCRIPTION
**Pull request by aeslaughter**
Refs #8875

### CODE REVIEW

**Comment by aeslaughter** [comment]
@rwcarlsen I spent a good part of today seeing what it would take to get the input file exploder working. I made some real progress, but it will take some time to finish it off. It would be useful for the DAG if we can get a clear view of the objects created by actions, but I am worried this will be a time sink. What do you think, should I keep going or be done with this little experiment?

**Comment by WilkAndy** [comment]
If this takes an input file with a bunch of Actions and "explodes" it to Kernels, etc, then it's a great idea for MOOSE usability.

**Comment by dschwen** [comment]
Cool, so this is a better implementation of what `DumpObjectsProblem` does. I'm all for it. Preferably if it also supports selective explosion of given action paths! Then I can easily switch the [`atom-explode-moose`](https://atom.io/packages/action-explode-moose) plugin over to this. Plus it will be on the framework team to ensure it keeps working :-D

**Comment by aeslaughter** [comment]
It is a different implementation, it has its own set of limitations. I feel that it has the potential to be move complete in outputting a working input file. This PR includes the ability to run the test harness with --explode and test if you get the same answer with the exploded version.

**Comment by aeslaughter** [comment]
This was a resurrection of what I started back in 2017, about the time you put in the DumpObjectsProblem. https://github.com/idaholab/moose/issues/8875

**Comment by dschwen** [comment]
> a great idea for MOOSE usability.

Yeah... a great idea that was a PR that went unmerged for one year from April 2017 through April 2018:

https://github.com/idaholab/moose/pull/8876

No, I'm totally not salty about that...

**Comment by YaqiWang** [comment]
This won't be exactly right about actions because we could have meta actions and have actions set parameters of existing actions, etc. Everything about action is to make the input more intuitive to users but not just to shorten the input file. This PR is only for developers and will have limited usage IMO.

**Comment by aeslaughter** [comment]
> This won't be exactly right about actions because we could have meta actions and have actions set parameters of existing actions, etc. Everything about action is to make the input more intuitive to users but not just to shorten the input file. This PR is only for developers and will have limited usage IMO.

It works for one of the meta actions tests already. A test that has an action that creates the action for nodal normals.

**Comment by dschwen** [comment]
Just a heads up, we are extending the action system in Bison to have actions browse through the action warehouse and fetch parameters of other actions, to make it easier to resolve interdependencies between actions rather than adding _another_ action layer on top of our existing action layer. This allows us to retain some modularity and reduce redundancies in input files. This should work fine as long as you are expanding all actions in an input file, but expanding just one action might have side effects (as that action won't be seen by other actions that make decisions based on its existence). I guess we'll have to have some internal discussions about this approach.

**Comment by aeslaughter** [comment]
The point of this is to dump all the MooseObjects as if the Action(s) don't exist. As long as the Action(s) create MooseObjects in the end it should work. If the Actions are messing with non-MooseObject parameters, then it will have problems. I have always recommended that any Action created should be optional, if you keep that in mind then this will work.

Seems like there is a lot of interest, but not sure this will be pursued, depending on funding. I would like to see if we can get moose_test working with --explode, that would give us an idea of what needs to be done for this to work in general.

**Comment by rwcarlsen** [comment]
I don't think this will really impact the dag stuff much beyond being a tool for helping to _start_ building a dep graph of e.g. a bison simulation.  For future dag partitioning implementation(s), all the dep graph building will come directly from the objects themselves - not from the process of creating them.

**Comment by aeslaughter** [comment]
> I don't think this will really impact the dag stuff much beyond being a tool for helping to _start_ building a dep graph of e.g. a bison simulation.

Correct. How much time did/do you expect me to spend on that task?

**Comment by rwcarlsen** [comment]
Ideally, I'd like to try to hammer out a bison run in ideally no more than a person-week.

**Comment by aeslaughter** [comment]
I don't think I will pursue this any further. If we get some funding in the future this would be a place to start up the idea again.

**Comment by dschwen** [comment]
What's (up) DAG?

**Comment by aeslaughter** [comment]
I will just make some input file diagrams by hand. This tool will work well enough as is to dump all the MooseObject syntax for a given simulation to aid me in the process.

**Comment by dschwen** [comment]
No seriously, is DAG referring to "directed acyclic graph"? Is there any discussion about why this is done and for what?

**Comment by rwcarlsen** [comment]
We have a seed ldrd to look at automatic mesh loop generation.

**Comment by dschwen** [comment]
mesh loop?

**Comment by rwcarlsen** [comment]
like all the code in the "loops" dir. to auto-generate the minimum number of necessary loops based on all the inter-obj deps.

**Pull request closed without merging**
