### PR TITLE
Add an interface function to return the names of mesh modifiers

### LINKED ISSUE #10056: Need a function in MooseApp to return the names of mesh modfiers
## Rationale
Need this function to programmatically set the `depends_on` parameter for later added mesh modifiers in an action system.

## Description
The mesh modifiers added by the action system are executed always after all mesh modifiers in the input. Thus it is not very user friendly to ask users to pass the mesh modifiers in the input file to the action. With this function, the action can obtain those mesh modifiers and set the `depends_on` parameter background.

## Impact
Trivial interface function. None.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #10056.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Any comments?

**Comment by dschwen** [comment]
See my comment on the issue. This is likely to introduce another construction-order pitfall.

**Comment by YaqiWang** [comment]
@dschwen I added a note in the header file. Hopefully people using this function will pay attention. I believe lots of functions in MOOSE should be called at the right time, so I am not too concerned.

**Comment by YaqiWang** [comment]
This is ready.

**Comment by YaqiWang** [comment]
Ping @permcody or @jwpeterson, can any of you review and merge this? I have a commit in Rattlesnake relying on this. Thanks.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
