### PR TITLE
Remove legacy params specializations

### PR DESCRIPTION
**Pull request by dschwen**
Using Civet for testing.
Refs #14135

### CODE REVIEW

**Comment by dschwen** [comment]
no-more-test-aspqvb

**Comment by bwspenc** [comment]
So, I assume when this is all finalized we won't need those forward declarations of the current class, which you have left in here. I guess we still need those for the time being for it to work if someone calls the old-style templated version of `validParams()`, though.  Is that right?

**Comment by dschwen** [comment]
@bwspenc I think we already do not need to forward declarations. I just haven't implemented removing those in my python script yet :-)

**Comment by dschwen** [comment]
So @milljm, why is this not getting any love from Civet?

**Comment by bwspenc** [comment]
I was thinking you would need them if a derived class called the templated version, but I guess they would have the class declared anyway since they're including its header.

**Comment by milljm** [comment]
Looks like Github didn't send, or Civet didn't receive the webhook generated by this PR. The simplest thing to do is 'try again'.

**Comment by dschwen** [comment]
Close this PR then? Or just push again.

**Comment by milljm** [comment]
I think push would suffice. If not, I can try and hunt down the webhook that failed. I see a bunch though.

**Comment by bwspenc** [comment]
@lynnmunday This is basically what we need to do for the apps (but also remove the forward declarations of the classes as well).

**Comment by dschwen** [comment]
Nope, push didn't help @milljm

**Comment by milljm** [comment]
being that this was the only event to happen in the last few minutes, I can see the webhook. There is failure (Timeout delivering payload).

Back in the day, my package_builder PRs would timeout like this. Let me just re-deliver and see if that works.

**Comment by bwspenc** [comment]
The system just can't handle the amount of code you're throwing at it, @dschwen.

**Comment by rwcarlsen** [comment]
Did you test this locally? - just curious to see how it compiled/ran.

**Comment by milljm** [comment]
lol ben!

Okay, I got it. But huh. I had to re-submit the web hook several times before it took. I hit the button 6 times in all. That is odd.

**Comment by milljm** [comment]
man... and then I had to invalidate all the targets to get them to trigger. That's new.

**Comment by rwcarlsen** [comment]
Framework doesn't even compile!  Not surprised.

**Comment by dschwen** [comment]
I didn't have my development machine at hand when I made the replacements. I just wanted Civet to test this for me over the weekend. That's moot now. I'm building locally now.

**Comment by dschwen** [comment]
Not surprising to see this fail if some classes in framework aren't even converted over to the new way. https://github.com/idaholab/moose/blob/next/framework/src/meshmodifiers/BreakMeshByBlockBase.C#L13-L15

**Comment by rwcarlsen** [comment]
We had originally decided to ignore mesh modifiers since they will be going away.  Maybe that was a sub-optimal choice in retrospect.

**Comment by rwcarlsen** [comment]
The legacy params macro was originally made to help us incrementally update all of moose and modules to the new validParams.  But that understanding was apparently lost in the fallout of all the changes and nobody remembered that we didn't need them after we got all of moose updated.  I vaguely also recall there being some issues related to possible deprecation warnings/errors that the macro could help with, but I don't remember exactly what or why :(

**Comment by dschwen** [comment]
TEST. MY. S%^&T!!!!

**Comment by dschwen** [comment]
image

**Comment by dschwen** [comment]
I can build and run bison with this branch. Good sign.

**Comment by dschwen** [comment]
pinging @milljm again

**Comment by milljm** [comment]
working on it... hit the button 4 times now...

**Comment by lynnmunday** [comment]
Hi Daniel, Can I get your script to edit validparams in files.  It is taking me too long to write my own.
Thanks
Lynn

**Comment by dschwen** [comment]
> working on it... hit the button 4 times now...

Hit it a fifth time!

**Comment by permcody** [comment]
Closing in favor of #15043

**Pull request closed without merging**
