### PR TITLE
Fix the failed test on Mac for subdomain partitioner interface

### PR DESCRIPTION
**Pull request by fdkong**
There was a mistake when rebased the code by taking head  changes. We need to add `subdomain_partitioner `  into `MooseEnum` .

Refs #8672

### CODE REVIEW

**Comment by jwpeterson** [comment]
> There was a mistake when rebased the code by taking head changes.

I still don't see how this passed all the testing on devel and master.

**Comment by jwpeterson** [comment]
> I still don't see how this passed all the testing on devel and master.

Oh I see now, the test is restricted to Mac because of architecture-dependent partitioning differences...

**Review by jwpeterson — APPROVED** [review]

**Comment by fdkong** [comment]
I am going to add a linux test as well.

**Comment by permcody** [comment]
#8948 will repair the broken test you are currently seeing on the Mac side.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Failed test is unrelated to the PR.

**Pull request merged**
