### PR TITLE
Do not attempt to apply PBCs to SCALAR vars 

### LINKED ISSUE #11417: AddPeriodicBCAction on all variables fails if scalar variables are in the system
## Rationale
If no `variable` argument id provided to this action it defaults to a list of _all_ non-linear variables:
```
    var_names_ptr = &nl.getVariableNames();
```
However, this apparently includes ScalarVariables, causing the setup of the periodic BCs to fail with the error

```
*** ERROR ***
Variable 'myscalar' does not exist in this system
```

where `myscalar` is a ScalarVariable.

## Description
`AddPeriodicBCAction` should default only to field variables as periodic boundary conditions (PBCs) do not make sense for ScalarVariables. This would allow users to keep using the compact default form when applying PBCs to all field variables.

## Impact
Set a more sensible default behavior.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #11417

### CODE REVIEW

**Review by jwpeterson — COMMENTED** [review]
Should we add a misc/check_error test for this?

**Review by jwpeterson — DISMISSED** [review]

**Comment by dschwen** [comment]
@permcody, would you mind elaborating why you put the big fat label on this PR? Do you have a better design in mind? This is bugging me with grain growth models (with lots of order parameters) combined with the upcoming strain periodicity 2.0 (which uses a scalar variable).

**Comment by permcody** [comment]
I'm adding design, issues, requirements to your new test and documenting the PBCs system. I'm going to push up a commit to your branch in a bit.

**Comment by permcody** [comment]
We are on the cusp or requiring these for new tests anyway, I figured I may as well clean this up.

**Comment by dschwen** [comment]
Thanks 👍

**Review by permcody — APPROVED** [review]

**Pull request merged**
