### PR TITLE
Sept 2019 news

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #11446)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@idaholab/moose-team Please add your work from August.

**Comment by lindsayad** [comment]
I've got nothing meaningful for August 😄

**Comment by rwcarlsen** [comment]
I didn't do anything.

**Comment by rwcarlsen** [comment]
And neither did Fande.

**Comment by fdkong** [comment]
> And neither did Fande.

Not right. I did at least one line of code.

**Review by permcody — APPROVED** [review]

**Pull request merged**
