### PR TITLE
Remove master slave 

### LINKED ISSUE #15457: Rename master/slave to primary/secondary in contact
## Reason
Historic connotation of the master/slave relationship is more than problematic. It seems like we are trivializing this by continuing to use these terms in the context of a mechanical contact simulation. 
 
## Design
Rename to `primary` and `secondary`. These terms do not convey any less meaning and do not have the same baggage.

## Impact
Everyone should be proud and comfortable working in the MOOSE developer and user space. Our environment should be as inclusive and inviting as possible. Using terms fraught with historical atrocity does not accomplish that goal

### PR DESCRIPTION
**Pull request by dschwen**
It's been deprecated since the beginning of September. Which should have been long enough to remove it from the applications (spoiler alert, it hasn't, Mastodon and Pronghorn need to be updated). Let's put the pressure on and remove the old nomenclature.

Closes #15457

### CODE REVIEW

**Comment by dschwen** [comment]
Pinging @cbolisetti

**Comment by cbolisetti** [comment]
@dschwen I removed master/slave and I have a PR open for this. I think it's all fine, but CIVET is probably broken right now. 

https://github.com/idaholab/mastodon/pull/347

**Comment by dschwen** [comment]
Ping @snschune for Pronghorn(?)

**Comment by snschune** [comment]
I'll have a PR open shortly.

**Comment by pbalest** [comment]
Is merged! Pronghorn is compliant again to the new rules, thanks @snschune

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
