### PR TITLE
Add stationary ray output

### LINKED ISSUE #26604: Add stationary ray output
## Reason
With the addition of stationary rays in #26597, it would be useful for diffing and visualization to output these with the `RayTracingMeshOutput`.

## Design
Add stationary capability to `RayTracingMeshOutput`.

## Impact
New capability

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #26604

### CODE REVIEW

**Comment by loganharbour** [comment]
Requires https://github.com/libMesh/libmesh/pull/3770

**Comment by loganharbour** [comment]
@roystgnr if you wouldn't mind taking a look at this. You're probably the best candidate for a review

**Review by roystgnr — APPROVED** [review]
Using the vectorized NumericVector::insert() might be faster than the repeated set() calls, but I doubt it's a hotspot so I wouldn't bother.

Otherwise I couldn't find any substantive issues.

**Comment by loganharbour** [comment]
> Using the vectorized NumericVector::insert() might be faster than the repeated set() calls, but I doubt it's a hotspot so I wouldn't bother.

Yeah, there's a lot in here that's not particularly optimized but I made the decision to prioritize readability here because it's already pretty complex as is figuring out all of the numbering 😬

**Comment by roystgnr** [comment]
> I made the decision to prioritize readability here

My biggest vague misgiving with this area of code is that it feels like the Doxygen (in the existing pre-PR code) and the comments would benefit from being elaborated on, to about twice their current verbosity ... but I couldn't really find any *specific* bits to complain about, so I didn't bother; it's impossible to productively criticize a "vibe".

**Comment by loganharbour** [comment]
Don't close. @gsgall still needs and can pester me about it

**Pull request merged**
