### PR TITLE
A test demonstrate the issue of restarting a transient from a steady

### PR DESCRIPTION
**Pull request by YaqiWang**
Refer to #9130.

### CODE REVIEW

**Comment by permcody** [comment]
I guess since you didn't add this to the tests file, this passes?

**Comment by YaqiWang** [comment]
Yes, I am going to add a FEProblem parameter to optionally load the additional vectors and add this into tests.

**Comment by YaqiWang** [comment]
I will run the two MAMMOTH tests to see if we can skip loading additional data for more complicated cases.

**Comment by YaqiWang** [comment]
@permcody those MAMMOTH tests pass with this fix. This is ready for your review.

**Review by permcody — APPROVED** [review]

**Pull request merged**
