### PR TITLE
Add option to turn off flow equations to NSFV action

### PR DESCRIPTION
**Pull request by GiudGiud**
This will be useful to advect quantities on there own

Still needs a test

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
Is there a way to reduce the amount of nesting? If not, that's fine

**Comment by lindsayad** [comment]
Also, up to you if you want to cover the PINSFV no-flow as well in this PR

**Comment by GiudGiud** [comment]
ok I ll try for nesting.

nah there are no precursors in porous flow. 
let s disallow that actually

**Comment by GiudGiud** [comment]
ok should be good now

**Comment by GiudGiud** [comment]
Test failure is unrelated

**Review by lindsayad — APPROVED** [review]
It's weird that the diff coverage report doesn't seem to have updated the removed PINSFV coeff setting lines

**Comment by lindsayad** [comment]
Oh duh, because coverage didn't run

**Comment by GiudGiud** [comment]
Refs #16853 #19472

**Pull request merged**
