### PR TITLE
Start cleaning up Console

### PR DESCRIPTION
**Pull request by permcody**
refs #11600

Removing a few unneeded `std::endl` calls in the Timestep output. 
Also removing unneeded width logic. Note: That the width is sized to the field size with a minimum of 2. This is just unecessary and is almost always a no-op and sometimes provides one character of whitespace. Just get rid of it!

### CODE REVIEW

**Review by aeslaughter — DISMISSED** [review]

**Review by aeslaughter — DISMISSED** [review]

**Comment by permcody** [comment]
Finally ready to merge for reals....

**Comment by permcody** [comment]
Ping @aeslaughter.

**Comment by permcody** [comment]
Since slaughter is MIA on this, I'm reassigning. 😄

**Review by jwpeterson — APPROVED** [review]
`std::endl` is dead, long live `std::endl`!

**Pull request merged**
