### PR TITLE
DARK MODE

### PR DESCRIPTION
**Pull request by milljm**
I can't work on the website without it blinding me. So... this first.

Refs #15299

### CODE REVIEW

**Comment by dschwen** [comment]
Looks great!

**Comment by milljm** [comment]
The links need to be a bit brighter me thinks...

**Comment by loganharbour** [comment]
Yeah, I think just a _little_ brighter would be good. Same for the header bar.

**Comment by loganharbour** [comment]
Is Doxygen next @milljm? 😬

**Comment by milljm** [comment]
@aeslaughter I can't seem to modify all of the GoogleSearch frame. Might need some help on that one. It seems like this is configured elsewhere (like in your account?).

**Review by permcody — APPROVED** [review]

**Pull request merged**
