### PR TITLE
Fix exodus viewer save state.

### LINKED ISSUE #8916: Saved State on Exodus viewer doesn't appear to work
### Description of the enhancement or error report

If you switch between different open files, the state of the check boxes and other controls on the Exodus tab doesn't reflect what's actually shown. It appears that state is saved when you switch between variables, just not files.

### Rationale for the enhancement or information for reproducing the error

Try opening a second file and checking various boxes. Then switch back and forth between the two output files.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock robustness

### PR DESCRIPTION
**Pull request by brianmoose**
The primary problem seemed to be that the way state was restored was by doing a "set" method, ie "setText()".  This would not trigger the signals that the various plugins were connected to. The solution here was for the plugins to listen to the "stateChanged" signal.
I also changed the key that is used to store the widget state to try to make it a bit more unique.

@aeslaughter and @permcody You should probably try it out to see if I missed something and that it works for you.

closes #8916

### CODE REVIEW

**Comment by aeslaughter** [comment]
@brianmoose Is this ready?

**Review by aeslaughter — DISMISSED** [review]

**Comment by brianmoose** [comment]
No, there are still some issues with this that @permcody found. Namely, saving the state correctly when the exodus file changes but has the same filename (ie switching input files). Also an issue where the whole Mesh widget can get disabled (the same can happen with the clip widget).

**Comment by brianmoose** [comment]
@permcody When you get a chance, could you try this out again?

**Comment by permcody** [comment]
This looks good. I can merge this as is.

**Review by permcody — APPROVED** [review]

**Pull request merged**
