### PR TITLE
Implement fixes suggested by cppclean.

### PR DESCRIPTION
**Pull request by jwpeterson**
This needs to be squashed down before merge, I am keeping it split up to possibly help bisect any #include errors uncovered by the apps.

### CODE REVIEW

**Comment by friedmud** [comment]
This is cool. Can you tell any difference in compile time?

**Comment by jwpeterson** [comment]
> Can you tell any difference in compile time?

I haven't really timed it yet, but it still feels like changing header files triggers lots of stuff to recompile.  I'll report the number of files recompiled due to "touch FEProblem.h" both before and after the branch is prepared...

**Comment by permcody** [comment]
So now that this passed you can squash

**Comment by jwpeterson** [comment]
I can, yes, but it's not done.  I've only made it up through "dampers" and I'm working through the include directories in alphabetical order...  Do you want to merge what has been done thus far?

**Comment by permcody** [comment]
I'm in no rush, 

keep firing...

**Comment by jwpeterson** [comment]
Looks like the last commit worked with all the apps except Yak, I'll make a patch for that tomorrow.

I think this branch is almost done.  I have gotten a few bugfixes from cppclean upstream that has improved the output of the script, so I'm going back and fixing things I missed in the first round.

**Comment by jwpeterson** [comment]
It takes a while to test this, but here are some stats for the number of files recompiled before/after the cppclean patch when touching a given header:
```
touch include/base/Assembly.h
before patch: 485
after patch: 61
```

```
touch include/base/FEProblem.h
before patch: 460
after patch: 450
```

As you can see, the savings for some files is dramatic while it is a little disappointing for others.  It just means that FEProblem.h really is included by a ton of C files.  Also note that this branch did not try to clean up C files yet -- cppclean doesn't really support this just yet -- so doing that might also help.

The number of files recompiled was counted with: `make -n | grep -c "echo \"MOOSE Compiling C++"`

**Comment by friedmud** [comment]
Nice work @jwpeterson !  That will definitely help...

**Pull request merged**
