### PR TITLE
Remove incremental_form option from tensor_mechanics eigenstrain models

### PR DESCRIPTION
**Pull request by bwspenc**
This option was used in the early development of these models, but now the last model that depended on that has been modified, so this is no longer necessary.  There is still one model in tensor_mechanics that needs the old eigenstrain tensor, but I changed that to just manage that within the model.

### CODE REVIEW

**Comment by bwspenc** [comment]
@dschwen Do you know what's up with those failing Marmot tests?  At first glance, they don't seem to have anything to do with this change.

**Comment by dschwen** [comment]
Fallout from @jiangwen84's PR

**Review by dschwen — APPROVED** [review]
Looks good to me

**Comment by brianmoose** [comment]
This breaks sabertooth, maybe just a bison submodule update is needed?

**Pull request merged**
