### PR TITLE
Transient reentering

### LINKED ISSUE #12772: Issue of reentering Transient::execute
## Rationale

`Steady::execute` can be reentered without changing the final solution even the solution before entering (or initial guess) changes. `Transient::execute` is different. If the solution before entering changes, it means the initial condition is different, thus all the sequential solution changes. However, if we only care the solution reaching the steady-state during transient like in pseudo-transient calculations, we are in a kind of situation like `Steady::execute`. But the current code does not allow reentering correctly. For example, time integrator init is in `Transient::init`, which will be skipped. Time or time step counter may not be setting correctly.

## Description

I propose to move some of the code in `Transient::init` into `Transient::preExecute` to make the reentering more solid. This will make the calculation where mater steady-state calculation drives a Picard iteration involve a pseudo-transient multiapp calculation correctly.

## Impact
A better design enables more functionality without impact.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #12772.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody @friedmud This is ready for review. The two major changes in this PR is:
1. separate output time and system time;
2. move some of the codes in `Transient::init` to `Transient::preExecute` to allow reentering.

This is important to us because it allows evaluate eigenvalues at different time (before and after control-rod movement) by simply change the system time and allows doing steady-state Picard iteration where subapp is a pseudo transient problem.

**Comment by permcody** [comment]
Looks like it's failing a few recover tests as it stands?

**Comment by YaqiWang** [comment]
Yes, looking into it. It is caused by my first commit. Looks like I cannot completely turn off backup/restore for full-solve multiapp at least for now.

**Comment by YaqiWang** [comment]
Few of the failing test is trying to recover a `FullSolveMultiApp` executed on `initial`. I think it is wrong, but I do not want to make my change too intrusive. The two exodiff failing tests I have not looked into.

**Comment by YaqiWang** [comment]
The failure involves the mess in `TransientMultiApp`... I cannot put `incrementStepOrReject();` inside `preExecute` before cleanup of `TransientMultiApp`. I will append one commit so that we can easily revert it later.

**Comment by YaqiWang** [comment]
Ready for review. I will give you a ready-to-go signal after I figured how the affecting apps should be patched.

**Comment by YaqiWang** [comment]
Looked all apps, they can easily patched. Interestingly, Pika has one test evaluate an aux variable with a function having time dependency. Fixing the time in Steady causes it exodiff because the time it is used to be is 3 the output time but now 0 the real system time. This is ready for reviewing and merging.

**Comment by YaqiWang** [comment]
@friedmud could you let me know when you will be available for reviewing this?

**Comment by friedmud** [comment]
@YaqiWang can you come talk about this?  We have some questions...

**Comment by YaqiWang** [comment]
Superseded by #12901.

**Pull request closed without merging**
