### PR TITLE
Added SmoothMultiBoundingBoxBaseIC and two new ICs that inherit from …

### PR DESCRIPTION
**Pull request by xueyang94**
…the base: IsolatedBoundingBoxIC and NestedBoundingBoxIC. closes#14050

Added IsolatedBoundingBoxIC and NestedBoundingBoxIC that allow the interfaces of initial bounding boxes to diffuse. The new ICs inheriting from SmoothMultiBoundingBoxBaseIC can reduce duplicated code. 

closes#14050

### CODE REVIEW

**Comment by xueyang94** [comment]
I think the error in the test is due to MPI. When I use 8 cores to run, it prints out the error message sometimes multiple times (IsolatedBoundingBoxIC_2D_Overlapping.i is to test the error condition in IC and is supposed to print the error message). But when running with 1 core, on my computer it gives the error message and also the stack frames thing. Could you give some advice on how to go about this? @permcody

**Comment by xueyang94** [comment]
@permcody The error I got in test modules is: failed to create Tester: Either "expect_err" or "expect_assert" must be supplied in RunException. What should be in the "expect_err" parameter?

**Comment by permcody** [comment]
expect_err = 'Some error message or pattern that should appear in the output'

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Nice work and thanks for the contribution.

**Pull request merged**
