### PR TITLE
Fix nodal bug in PorousFlowPropertyAux

### LINKED ISSUE #8726: PorousFlow: select either nodal or qp properties in PorousFlowPropertyAux
### Description of the enhancement or error report
PorousFlowPropertyAux uses `_nodal` as the flag to choose between nodal or qp properties, but it should use `_nodal_material` like the materials do, with a corresponding `at_nodes` input parameter.

### Rationale for the enhancement or information for reproducing the error
Some properties only exist at nodes in some cases. Using `_nodal` (which I think comes from MooseVariableInterface) is always 0 in this aux kernel as only elemental aux variables can be used, and therefore there is no way to output them using this AuxKernel.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Fixes a small bug.

### PR DESCRIPTION
**Pull request by cpgr**
Add `at_nodes` to PorousFlowPropertyAux to select nodal values, and update test.

Closes #8726

### CODE REVIEW

**Comment by cpgr** [comment]
Actually, the aux variables have to be elemental (like constant monomial) because the nodal aux variables (like Lagrange) can't access material properties at all. So `_nodal` was always false.

I'm not sure about the number of nodes thing - I haven't really considered that.

**Comment by WilkAndy** [comment]
OK, i didn't realise _nodal = false.  I see that AuxKernel.C does a loop

```
      for (_qp=0; _qp<_qrule->n_points(); _qp++)
        value += _JxW[_qp]*_coord[_qp]*computeValue();
```

This is obviously fine for _nodal_material = False, but isn't going to be correct otherwise.  I think it's dangerous to allow users to use their nodal Materials here (because of the potential segFault when we do the above loop, and that it'll potentially give the "wrong" answer), but it's also a massive pain in the bum to force them to create a QP Material just to make a AuxVariable that's probably just used for visualisation anyway.

Perhaps in your params.addParam("at_nodes") doco you could say: "If you set at_nodes = true then you must ensure the number of quadpoints equals the number of nodes in every element considered by this AuxKernel, and understand that a interpolation from nodes to element centroids will occur."  or something similar.

Sorry to be a pain in this PR!

**Comment by cpgr** [comment]
Yeah, this aux kernel was originally just so I could visualise mass fraction that was in a `std::vector<std::vector<>>` that I couldn't get at any other way. I don't even remember adding the choice between qp and nodal properties. 

Perhaps it would be best to have it access qp materials only (even if it means adding an extra material just for computing these at the qps)?

**Comment by WilkAndy** [comment]
I guess I'm in favour of having it access QP materials only, but i also understand (now) the point of this PR - it generally makes life easier for the user.   I'm happy to go with what you decide, but if you leave it as is then i do think the above doco string will be useful for sorting out future problems.

**Comment by cpgr** [comment]
I'm leaning towards making it qp only

**Comment by WilkAndy** [comment]
OK

**Comment by cpgr** [comment]
OK, I've removed the `_nodal` flag as it was always false. Now only qp material properties can be accessed. If these don't exist, MOOSE throws an informative error saying that the required material property doesn't exist.

**Comment by WilkAndy** [comment]
Why isn't this going through the test suite?  Did you do something strange?

**Comment by cpgr** [comment]
Hmm, no idea. It looks like the latest commit was pushed successfully.

**Comment by WilkAndy** [comment]
OK, i just manually activated App tests.  Can you do the rest, or aren't you a "Developer"?

**Comment by cpgr** [comment]
I can't see anything that I can press to activate them

**Comment by WilkAndy** [comment]
OK, i'll do it, no worried.  Perhaps you should ask the MOOSE guys to add you as a developer.  It also means you can activate other tests, eg heavy tests, or tests with PETSc-alt, which is quite useful sometimes.

**Review by permcody — APPROVED** [review]

**Comment by cpgr** [comment]
Thanks @permcody. Any ideas why the testing didn't start automatically? Andy had to manually activate them all.

**Comment by permcody** [comment]
I'm not sure. I think there may have been a problem or perhaps you aren't in the developers group. @brianmoose will you check and see if @cpgr is in the development group and add him if he's missing?

**Comment by brianmoose** [comment]
@cpgr was not a collaborator on MOOSE. An invitation has been sent, and once accepted, manual activation will no longer be required.
FYI, we always run the "Precheck" because that is quick, and more importantly, doesn't actually run any of the code in the PR (ie doesn't do "make" so if somebody put something malicious in there it doesn't run in the precheck).

**Comment by cpgr** [comment]
Thanks @brianmoose

**Pull request merged**
