### PR TITLE
Augmented Lagrangian Multiplier

### LINKED ISSUE #9677: Augmented Lagrangian Multiplier Method for Contact Problem
@bwspenc 

### Description of the enhancement or error report
This work implemented an augmented lagrangian multiplier (ALM) method to enforce the contact constraint. Compared to the penalty method, there are a couple of strengths for ALM method. ALM method is variational consistent and therefore can hold the optimal convergence rate. Moreover, ALM method is 

### Identified impact
The following classes are changed
Transient (Only add two lines)
Constraint (Add three virtual functions)
MechanicalContactConstraint (Add three functions, modify computecontactforce, residual, jacobian)
FEProblemBase(Add three functions)
NonlinearSystemBase (Add three functions)

Add one class 
ContactAugLagMulProblem

Add three tests
modules/combined/tests/contact_verification/hertz_cyl/half_symm_q4/hertz_cyl_half_1deg_template2_sm_alm.i
modules/combined/tests/sliding_block/sliding/constraint/frictional_02_alm.i
modules/combined/tests/sliding_block/sliding/constraint/frictionless_alm.i

### PR DESCRIPTION
**Pull request by yingjie1989**
@bwspenc 

### Complete each of the following items before creating a PR

- After nonlinear solve converged, check the convergence criterion. If satisfied, accept the solution and go to the next step. If not, update the lagrangian multiplier and repeat the nonlinear solve

- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- test
  
 modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q4/hertz_cyl_half_1deg_template2_sm_alm.i
	modules/combined/test/tests/sliding_block/sliding/constraint/frictional_02_alm.i
	modules/combined/test/tests/sliding_block/sliding/constraint/frictionless_alm.i

- Close #9677

### CODE REVIEW

**Comment by dschwen** [comment]
I'm not a big fan of the `AugLagMul` abbreviation

**Comment by dschwen** [comment]
@yingjie1989 you need to rebase you branch using

```
git pull --rebase upstream devel
```

and 

```
git push -f
```

again

**Comment by dschwen** [comment]
You messed that up. My comment came too late. Your PR should **not** contain changes to the Darcy tutorial!

**Comment by dschwen** [comment]
Also while you are fixing this PR it would be helpful to add your changes as _separate_ commits!

**Comment by yingjie1989** [comment]
Daniel, Thank you. But what should I do now? Can I still do the rebase and then push the code? @dschwen

**Comment by dschwen** [comment]
Yes, still rebase. You might get some conflicts now that you need to fix.

**Review by brianmoose — DISMISSED** [review]
combined tests now live in `modules/combined/test/tests` rather than `modules/combined/tests`

**Comment by yingjie1989** [comment]
Looks like I should modify the input file of some internal tests to make it work with the new code. Will do that asap

**Comment by permcody** [comment]
Closing due to inactivity. Notifying @bwspenc and @dschwen.

**Pull request closed without merging**
