### PR TITLE
Fix failures from #16767 merge

### PR DESCRIPTION
**Pull request by GiudGiud**
Use LU preconditioner in tests to improve repeatability on different platforms,
Test failures from merging #16767
refs #16099

### CODE REVIEW

**Comment by loganharbour** [comment]
Why all of them?

**Comment by GiudGiud** [comment]
They are very similar tests. There's no reason one would have the issue more than the other. 
They should also be quite cheap, not a lot of elements.

**Comment by loganharbour** [comment]
I prefer to not change things unless necessary. If you really want to do all, you should just put it in the input and leave a comment.

**Comment by GiudGiud** [comment]
Ok I've put it in the input instead with a comment.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
