### PR TITLE
Have cylinder_friction use Eisenstat-Walker

### PR DESCRIPTION
**Pull request by lindsayad**
Had a recent [CIVET failure](https://civet.inl.gov/job/941839/) so making the test more robust with the Eisentstat-Walker option. This test passed with the old gold files but I'm choosing to re-gold here since I also changed (tightened) the solver tolerances

Refs #20143

### CODE REVIEW

**Review by recuero — APPROVED** [review]
Passing this option avoids having to choose a linear tolerance/max its: Is this strategy extensible to other physics?

**Comment by lindsayad** [comment]
Yes it is, but I think where it really shines is for non-smooth problems

**Comment by lindsayad** [comment]
NS failure unrelated.

**Comment by srinath-chakravarthy** [comment]
Was this not done before ranfs implementation ??

**Comment by lindsayad** [comment]
@srinath-chakravarthy what are you referring to?

**Pull request merged**
