### PR TITLE
Start of Cosserat plasticity

### PR DESCRIPTION
**Pull request by WilkAndy**
I am not happy with any of this.

I'd appreciate it if someone could look briefly at the changes in ComputeMultiPlasticityStress.

This is the problem i'm trying to address: ComputeMultiPlasticityStress is super complicated, so i want to use as much of it as possible in the Cosserat generalisation.  At the moment this means i have some pointers that are NULL in the non-Cosserat case.  If I continued down this path, most methods in ComputeMultiPlasticityStress and all the parent classes (there are a LOT of these) would have arguments involving these pointers.  Those methods would do slightly different things depending on whether the pointers were NULL.  This seems really inelegant and error-prone to me.  But i'm finding it difficult to think of a better alternative, apart from a major refactor of ComputeMultiPlasticityStress and all the related classes, which is a major piece of work (I'm not totally against this, i'm just lazy).

The ComputeMultiPlasticityStress in this PR just does Cosserat elasticity, so it is not very functional, and it may be hard for you to understand the problem of the previous paragraph, i'm sorry.

If you have any ideas, please let me know!

Refs #7243

### CODE REVIEW

**Comment by WilkAndy** [comment]
After some more thought... i'm currently leaning towards introducing optional arguments to all of the methods.  The optional arguments are

couple_stress = RankTwoTensor()
curvature_increment = RankTwoTensor()

and similar.  Although i've never used optional arguments in MOOSE before, i'm thinking it might be good here.  Otherwise i have to define a zillion more overloaded functions: the Cosserat versions of the current functions, but with more arguments.  That seems much uglier than having optional arguments and a few statements like "if optional argument is passed then..."

**Comment by WilkAndy** [comment]
Can someone tell me how to activate the heavy tests?

**Comment by permcody** [comment]
Just click on your job in CIVET and it'll take you to the details page. There you can check boxes of all the additional configurations you wish to run.

**Comment by WilkAndy** [comment]
Aha, i activated the heavy tests, thanks @permcody 

a

**Comment by jwpeterson** [comment]
> This is the problem i'm trying to address: ComputeMultiPlasticityStress is super complicated, so i want to use as much of it as possible in the Cosserat generalisation. At the moment this means i have some pointers that are NULL in the non-Cosserat case. If I continued down this path, most methods in ComputeMultiPlasticityStress and all the parent classes (there are a LOT of these) would have arguments involving these pointers. Those methods would do slightly different things depending on whether the pointers were NULL. This seems really inelegant and error-prone to me. But i'm finding it difficult to think of a better alternative, apart from a major refactor of ComputeMultiPlasticityStress and all the related classes, which is a major piece of work (I'm not totally against this, i'm just lazy).

I don't fully understand the problem, but would it be possible to not pass anything (just work with class variables?)

**Comment by WilkAndy** [comment]
Not really, @jwpeterson .  I'm sorry this almost impossible for you to understand before i've actually tried to implement something real.

The problem starts with tensor_mechanics/include/userobjects/TensorMechanicsPlasticModel.h  .  You'll see that has lots of functions that take "stress" as an argument.  Now i have to either write another bunch of functions with "stress, couple_stress" as the argument, or have an optional argument "const RankTwoTensor & couple_stress = RankTwoTensor()" in all of the existing functions.

There are a whole heap of TensorMechanicsPlasticXXX that derive from that class.  And the problem then continues with all of the Materials and utils that actually use these TensorMechanicsPlasticXXX classes.

Are such optional arguments bad for performance, by the way?  Eg, if i don't supply "couple_stress", does the program have to create a RankTwoTensor() each time i call one of these functions?

**Comment by jwpeterson** [comment]
> Are such optional arguments bad for performance, by the way? Eg, if i don't supply "couple_stress", does the program have to create a RankTwoTensor() each time i call one of these functions?

As I understand it, yes, that is what would happen, but it  would not necessarily be bad for performance... you would have to try it and see.


Could you derive a new class from `RankTwoTensor` which actually stores a second tensor (the couple_stress tensor) inside and then still use those existing interfaces?

**Comment by WilkAndy** [comment]
Deriving from RankTwoTensor - that's sneaky and i hadn't thought of it.   Physically it's somehow the right thing to do: a "couple_stress" always appears with a "stress" and they interact.  While it's sensible to have "stress" alone, it doesn't really make any sense to have "couple_stress" alone.  I'll have to think further on this.

**Comment by jwpeterson** [comment]
@WilkAndy I interpreted your PR description as you not wanting this to be merged, but I realized you might have wanted this to be merged despite not being happy with the design... let me know what you want to do...

**Comment by WilkAndy** [comment]
Yes, don't merge.  i hope to do something this week...

**Comment by WilkAndy** [comment]
Closing this PR in favour of a more incremental approach.

First i'll add the relatively boring ComputeIncrementalCosseratSmallStrain, as per #7388 , and later i'll start the refactoring of TensorMechanics plasticity to include Cosserat.  An initial (failed) try at the latter was in PR #7324.

**Pull request closed without merging**
