### PR TITLE
Complement boundary

### LINKED ISSUE #21383: Allow ElementSubdomainModifer to create complement to moving boundary
## Reason
We're using the ElementSubdomainModifier to move "deleted" material into an inactive subdomain. We need to apply a BC to the exposed surface of the original subdomain. This class currently has an option to specify `moving_boundary_name`, which creates a boundary on the side of the block that the elements are moved into. That is useful for problems in which the destination subdomain contains physical material (such as additive manufacturing), but we need the opposite of that for the deletion case.

## Design
Add an option similar to the current `moving_boundary_name` option to specify the name of a boundary that is on the newly-exposed surface of the original block that elements are moved from. I propose naming this option `complement_moving_boundary_name`, because `complement` is used in a similar way in `complement_subdomain_id` in `ThresholdSubdomainModifier`, but I'm open to suggestions. Both of these options would only create the boundary if the option is provided.

## Impact
This would only add a new feature.

### PR DESCRIPTION
**Pull request by dschwen**
Replaces #21549
Closes #21383

### CODE REVIEW

**Comment by recuero** [comment]
Can you preserve the corresponding authorship from https://github.com/idaholab/moose/pull/21549? It seems there is common code/input file.

**Comment by dschwen** [comment]
> Can you preserve the corresponding authorship from #21549? It seems there is common code/input file.

It is preserved "jain651 authored and dschwen committed 8 hours ago". Not sure why GitHub is only showing my face here.

**Comment by recuero** [comment]
I can only see your face. Maybe GitHub updated that.

**Comment by dschwen** [comment]
> I can only see your face. Maybe GitHub updated that.

Doesn't matter, the correct authorship is preserved in the commit data.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
