### PR TITLE
Update object naming convention

### PR DESCRIPTION
**Pull request by aeslaughter**
The first patch updates the naming of MooseObject-based objects to be: `ObjectBase/user_given_object_name`, where ObjectBase is the name given to InputParameters::registerBase.

Thus, when accessing Control Logic parameters the syntax becomes: `ObjectBase/user_given_object_name/param_name`, where ObjectBase and user_given_object_name are optional.

When using control logic you can:
1. specify the complete name, with all three parts, and set a specific parameter
2. specify `ObjectBase/*/param_name` to set all parameters of an object group (e.g., Kernel)
3. specify `user_given_object_name/param_name` to set all objects sharing a name and parameter to the same name (see /tests/controls/name_components/group_param.i)
4. specify only the `param_name` to set all parameters with a name regardless of object 

However, parsing this becomes problematic when the `user_given_object_name` contains additional slashes (e.g., user/given/object/name). Thus, if the ObjectBase (as in 3 above) is not given `user` will be mistaken as the ObjectBase.

With this, I think that the naming convention should be as follows (second patch, in progress), or something similar:

`ObjectBase:my/crazy/object/name:param_name`

What do others think?

(refs #4604)

### CODE REVIEW

**Comment by dschwen** [comment]
What if the object name contains colons? ;-)

**Comment by aeslaughter** [comment]
@permcody @andrsd @friedmud Can you take a look at the proposed naming scheme for this PR? I need some feedback before I implement something that people hate

**Comment by aeslaughter** [comment]
@dschwen I am open for other ideas, I haven't implemented the new scheme.

**Comment by dschwen** [comment]
How about not using s string to hold the full name? Use a container that keeps the components separate. That should be easier to parse, too. Why lump stuff into a string if you have to peel it apart again?

**Comment by aeslaughter** [comment]
@dschwen For storing the objects that is possible, but not desirable. The object names are used to store the object InputParameters in a warehouse that can be looped over (std::map<std::string, InputParaemters*>). Breaking up the name would create a tree structure that would need to be navigated.

Additionally, when using the control logic system the user needs a way to specify a parameter to be controlled in the input file and I don't want multiple input file parameters to be required.

For example:
```
[Control]
  [./my_control]
    parameter = Kernel:this/thing:some_param
```

**Comment by aeslaughter** [comment]
@dschwen Ok, I see what your are saying with the storing thing. I think that is a good idea, in the InputWarehouse the storage container could be: `std::map<std::pair<std::string, std::string>, InputParameters*>`, where the pair is the SystemBase and object name.

**Comment by dschwen** [comment]
Yeah, if std::pair works that's great.

**Comment by friedmud** [comment]
Other stuff is already stored is a map of full name->data: namely the
restart stuff. No reason to have two different systems.

In regards to why this is a string: it's because it will often come from
the input file... and the easiest way to specify it is Kernels/diff/value
(or some variation on that).

Personally I would vote for all slashes so that it matches the command-line
override syntax:

./mooseapp-opt -i stuff.i Kernels/diff/value=4.2

As for the issue of the name having a slash in it: I'm pretty sure that's
not possible. GetPot will actually make it a sub block if you do that! We
can just pu checks into MOOSE that disallow it programmatically as well...

Derek

**Comment by andrsd** [comment]
I am with @friedmud on this. Slash is a separator, while colon is a valid name character (we use colons in component names in RELAP-7 a lot).

**Comment by aeslaughter** [comment]
So no slashes in the name then:

```
[Kernels]
  [./dont/do/this]
  ...
```

**Comment by aeslaughter** [comment]
Also, I don't think we should use 'Kernels', 'BCs', etc. as the prefix.
This is input file syntax, which when using actions may not exist. I want
to use the base object name to distinguish (Kernel, BoundaryCondition, etc.)

**Comment by dschwen** [comment]
How would that work anyways? Slashes in input files have special meaning.
How about nested blocks in actions for example?

**Comment by dschwen** [comment]
If you overload a bunch of operators for the name container class you can
make it behave like a string for most purposes. Except that you have a well
defined safe component separation.

**Comment by permcody** [comment]
I know I'm really late to the conversation but I'm a little concerned about having two different base names especially since they aren't consistent. When controlling a Kernel you have to remember to drop the 's', but when you want to control a boundary condition you have to go from BCs -> BoundaryCondition. The registerBase thing is not something most users are exposed to in the current system, are we sure we really want to expose users to that now?

As far as colon versus slash, I've already taken over the colon (perhaps prematurely) for the multiapp overrides: https://github.com/idaholab/moose/pull/5136

**Comment by aeslaughter** [comment]
Well, BCs should really be BoundaryConditions in the input file, same for ICs. My reason for wanting the base name is for actions. If an action calls `FEProblem::addKernel("MyKernel", "some_custom_name", ...)` then the stored name becomes "Kernel/some_custom_name". We can't rely on input file syntax, because it doesn't exist.

**Comment by friedmud** [comment]
On Wed, Sep 2, 2015 at 11:41 AM Andrew E Slaughter <notifications@github.com>
wrote:

>
> [Kernels]
> [./dont/do/this]
>

That's valid syntax but it doesn't mean what you think it means.

It actually creates this structure:

[Kernels]
  [./dont]
    [./do]
      [./this]
      [../]
    [../]
  [../]
[]

You can actually do this in an input file...

[Kernels/diff]
  type = Diffusion
  ....
[]

And it will actually add a Kernel just like normal.

Slashes are valid _syntax_... but they are NOT part of names.

As for whether or not to change the names from what it is in the input
file... I say no.

Again: the syntax should match what's used in the command-line override.
That's what users understand (GetPot structure) and you have to remember
that many of these parameter names are going to be passed in through the
input file... where it makes most sense to use the input file names.

Derek

**Comment by friedmud** [comment]
I will once again advocate not using the base name to build the full path.  Just follow what is already being done in the Restart system.

For instance, for Kernels: https://github.com/idaholab/moose/blob/devel/framework/src/kernels/KernelBase.C#L58

Note that the name matches the block in the input file... so it makes sense....

**Comment by permcody** [comment]
@friedmud - I'm with you but I have to chuckle just a bit. @aeslaughter is right that there is a disconnect between input file syntax and MOOSE (i.e. FEProblem). This was by design since you didn't want the parser infringing on MOOSE. :) 

However, it's not really that disconnected, it is stored somewhere... in the `Syntax` object which is a member of `MooseApp` so it can be retrieved. Basically we just need to make sure we have a good way of retrieving the mapping from the syntax so that everything works seamlessly together without additionally mapping. That way we can build the full input file syntax even when objects are added through the `Action` system.

**Comment by aeslaughter** [comment]
While I like the idea that the name matches input file syntax, again this breaks down for actions, because this is valid:

```
addKernel("MyObject", "this/is/a/valid/name", ...)
```

**Comment by friedmud** [comment]
Yes - I said we could disallow that with a simple check.

**Comment by friedmud** [comment]
From up above (including typo!):

>As for the issue of the name having a slash in it: I'm pretty sure that's
not possible. GetPot will actually make it a sub block if you do that! We
can just pu checks into MOOSE that disallow it programmatically as well...

**Comment by permcody** [comment]
I'm with @friedmud, my only suggested change is that we should retrieve the syntax from the `Syntax` object instead of supplying it directly as shown in the restart example.

**Comment by aeslaughter** [comment]
Ok, I will disallow the "/" in the name. Now what about nested syntax (Markers and Indicators) or custom syntax where the user has created a new base object. To do all this correctly, we need to inspect the parser.

```
[Adaptivity]
  [./Indicators]
     [./error]  # What is my complete name?
....
```

or

```
[SomeNewObjects]
  [./my_new_object] # The name should be SomeNewObjects/my_new_object, but how do we know? Do we inspect the parser?
```

**Pull request closed without merging**
