### PR TITLE
Add missing documentation for postprocessors & rename two of them

### PR DESCRIPTION
**Pull request by GiudGiud**
long drive to the sawtooths
6 more pps to do, later

### CODE REVIEW

**Comment by GiudGiud** [comment]
looks like github chose a reviewer @joshuahansel

**Review by joshuahansel — CHANGES_REQUESTED** [review]
Good stuff!

**Comment by joshuahansel** [comment]
@GiudGiud Looks like you just need to resolve a conflict.

**Review by joshuahansel — DISMISSED** [review]

**Comment by GiudGiud** [comment]
one minute it fails tests

**Comment by cticenhour** [comment]
I am not seeing the error I expect to see with `--error-deprecated`, so I don't think our normal deprecation procedure works with derived classes. A good feature for the future, but I can throw together a patch for Marmot and Freya this time so we don't have to leave stopgap header typedef around.

**Comment by GiudGiud** [comment]
Thanks a lot for fixing this up!
I ll try removing the phantom header in a future PR.

**Review by joshuahansel — APPROVED** [review]

**Pull request merged**
