### PR TITLE
Master

### PR DESCRIPTION
**Pull request by jain651**

### CODE REVIEW

**Comment by cticenhour** [comment]
Thanks for submitting to MOOSE! This is failing precheck because the target branch must be set to `next`, but we also have a few other issues that should be addressed, since you've branched off of the `master` branch here. 

Note that current best practice for MOOSE development is creating a new branch based off `devel` and then submitting a PR to `next`. See https://www.mooseframework.org/framework_development/contributing.html for more information on this. 

To get this PR fixed up, You will need to do the following in your Terminal while in your copy of MOOSE. (Note that I gave your new branch the name `trussModel` - you can name it whatever you like)

```
git checkout devel
git checkout -b trussModel
git cherry-pick 117c5a7^..dc5534d
```
Once this completes, confirm that you have all 9 commits above in the new branch `trussModel`. Then you can push that work up to your copy of MOOSE on github by doing the following:

```
git push origin trussModel
```

Finally, because you cannot change the source branch of a submitted PR, please create a new one (with a description and preferably also referencing a MOOSE issue) and set the target branch to be `idaholab:next`. We also require at least one commit message in your commit history to mention a MOOSE issue number in order to pass Precheck. 

If you have any questions regarding this, please let me know! 😄

**Comment by dschwen** [comment]
Amit, is this you?

**Comment by jain651** [comment]
Yes, Daniel.

**Comment by cticenhour** [comment]
Closing in favor of #15826

**Pull request closed without merging**
