### PR TITLE
Explicit MooseDocs auto linking

### PR DESCRIPTION
**Pull request by loganharbour**
refs #24406

### CODE REVIEW

**Comment by loganharbour** [comment]
@zachmprince and @cticenhour - I could benefit from a review of just the python content (`python/MooseDocs/*`). The rest is making everything explicit. Almost everything is tested, spare for two of the errors within autolink.

**Comment by GiudGiud** [comment]
It would be a shame to loose the ability to do that quick [Object.md] just so people can do [source:index.md]

Objects have to have unique names anyway so we should be able to rely on that

**Comment by GiudGiud** [comment]
btw you have some commits towards the end that reference https://github.com/idaholab/moose/issues/24412 instead of https://github.com/idaholab/moose/issues/24406

**Comment by loganharbour** [comment]
> It would be a shame to loose the ability to do that quick [Object.md] just so people can do (major page)[source:index.md] safely
> 
> Objects have to have unique names anyway so we should be able to rely on that
> 
> can we have an exception on the [] shorthand syntax?

I agree with you and have had this same thought. I'm trying to think of the best way to do this. Right now, we don't know if a page is syntax or not so it's hard to make an exception there. I could parse the pages ahead of time for the appsyntax extension. Working on it.

**Comment by GiudGiud** [comment]
While it s not forbidden I don't think very many links, if any, use the short syntax for syntax pages. 
It could just be [ ] is the short but unsafe syntax and [ ] ( ) has the explicit linking.

**Comment by loganharbour** [comment]
Please don't

**Comment by loganharbour** [comment]
Thanks @cticenhour

**Pull request closed without merging**
