### PR TITLE
Adds the TwoCircleMarker tests

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
This are the tests that gave @roystgnr all that trouble. It seemed best to get it in the test suite.

It looks like CIVET will test this with parallel and recovery and distributed mesh, but is there any combination of the above that we should explicitly test for?

ref #8890 and #8891

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Hmmm, I can squash all these commits if necessary...

**Comment by jessecarterMOOSE** [comment]
Still crashes with distributed mesh on Intel...

**Comment by jessecarterMOOSE** [comment]
Still has distributed mesh failures, but that might be fixed with libMesh/libmesh#1390

**Comment by roystgnr** [comment]
Shoot; yes, I wouldn't expect this to work with --distributed-mesh until after that patch is in.  I've kicked the tests there now, and as soon as that's green I'll merge there and I'll prepare a libMesh update PR for MOOSE.

**Comment by jessecarterMOOSE** [comment]
@roystgnr Just to clarify, the problem with --distributed-mesh here is NOT with recovery, but just simply running as-is. Does libMesh/libmesh#1390 address this or is that PR only for Checkpoint files, i.e. recovery?

**Comment by jessecarterMOOSE** [comment]
Ah, if I would bother to scroll all the way to the bottom, I see that you made a change to src/mesh/mesh_communication.C. Perhaps that does the trick for the non-recovery case?

**Comment by jessecarterMOOSE** [comment]
I checked out the latest libmesh master branch and can confirm these tests pass with recover, AND with distributed mesh, AND in parallel! I started getting some diffs at 7-10 cpu range with distributed mesh, so I'll just have to keep that in mind.  Thanks @roystgnr !

**Review by roystgnr — APPROVED** [review]

**Pull request merged**
