### PR TITLE
Update PETSc submodule to 3.20.5

### LINKED ISSUE #27227: Update PETSc submodule
### Motivation

PETSc has recently updated to version 3.21.1. MOOSE should be kept up-to-date with this release.

EDIT (May 10 2023): Changed to 3.21.1

### Design

Update the PETSc submodule and corresponding packages to 3.21.1.

### Impact

New features and bugfixes from PETSc.

### PR DESCRIPTION
**Pull request by cticenhour**
Closes #27227

### CODE REVIEW

**Comment by loganharbour** [comment]
It's worth checking if @roystgnr is ready for a libmesh update. I believe he is.

**Comment by lindsayad** [comment]
FWIW PETSc is planning to spin out the 3.21 release sometime today

**Comment by cticenhour** [comment]
Happy to move to that - this was just what was available when I checked 😄

**Comment by roystgnr** [comment]
Ha.  I was *so* ready for a libMesh update that I was postponing less urgent things for afterwards, like sorting through all my github notifications...

**Comment by cticenhour** [comment]
Closing this one as it is long out of date now.

**Pull request closed without merging**
