### PR TITLE
Fix neighbor Material coupling

### LINKED ISSUE #5046: Material not getting correct coupled neighbor values
TLDR: Neighbor material properties are messed up!

This is a straight up real bug that could have been affecting applications.

Material inherits from Coupleable.

When using DGKernels (or anything else that invokes the "neighbor" system: like Face Constraints and more) a Material will get created for "this" side of the interface and the "neighbor" side of the interface.

The Material that is created to represent the Material properties on the neighbor element is still inheriting from Coupleable... but that Coupleable interface doesn't know that it's supposed to be providing values from the neighbor element.  This means that _any_ coupled values in a neighbor material are actually the values from "this" element... NOT the neighbor!

I have a fix coming for this....

### PR DESCRIPTION
**Pull request by friedmud**
Modified Coupleable to couple to the correct values if this object is a "neighbor" object.  This also necessitated adding missing "neighbor" stuff to MooseVariable.

Unfortunately, I don't have a great test for this yet... I'm still thinking about it.  This came up because it was actually causing an error in my new application... but to reproduce it I would have to come up with a nonlinear DG test with complicated Material properties.

I'll continue to think on that - but for now I wanted to post this and let it go through the testing regimen...

closes #5046

### CODE REVIEW

**Comment by jwpeterson** [comment]
@YaqiWang Have you tried out this PR in Yak?

**Comment by YaqiWang** [comment]
@jwpeterson No, Yak does not contain a test coupling variables when evaluating material properties on sides.

**Comment by permcody** [comment]
I believe we are waiting for a test. I'm marking this as "under development"

**Comment by permcody** [comment]
@friedmud and I discussed that this capability is rather difficult to test. We are merging this without a test for now with the knowledge that we may cause a regression later. @YaqiWang if you come up with a good test for this capability, I'd be interested in adding it to MOOSE.

**Pull request merged**
