### PR TITLE
Minor and rather trivial cleanup of tests.

### PR DESCRIPTION
**Pull request by WilkAndy**
The Peacock bug that Heather found seems to be activated by an expression like
   E = 0.3  # Young's = 234
It appears to need a valid input (E=0.3) followed by a hash, followed by a single quote followed by an equals sign.

I removed all such things from the TensorMechanics and Richards tests, and took the opportunity to clean up some doco in some tests, and remove a number of unnecessary things from quite a few tests.

I'm not sure if this really closes this issue.  Possibly someone wants to fix Peacock so that it correctly parses Heather's problematic line.
#5270

### CODE REVIEW

**Comment by jwpeterson** [comment]
> The Peacock bug that Heather found seems to be activated by an expression like
> E = 0.3 # Young's = 234
> It appears to need a valid input (E=0.3) followed by a hash, followed by a single quote followed by an equals sign.

Holy dooley!  And expressions like this work fine in MOOSE, eh?

**Comment by WilkAndy** [comment]
@jwpeterson, that PR_app_tests often seems to fail, grump grump.  How can it fail if i just changed some test input files?!

**Comment by permcody** [comment]
It's not your problem - we're doing some massive integration today. Just
hang on and we'll invalidate that part of the recipe when we are finished.

Cody

**Comment by WilkAndy** [comment]
OK, great, thanks @permcody ,

a

**Comment by jwpeterson** [comment]
I'm looking to see what the conflicts are about here...

**Comment by jwpeterson** [comment]
Hmm... there weren't any conflicts when I merged by hand so good onya mate.

**Comment by WilkAndy** [comment]
Thanks @jwpeterson 

a

**Pull request merged**
