### PR TITLE
Add mechanical_strain output

### LINKED ISSUE #17624: Add mechanical_strain data to tensor mechanics action output
## Reason
`mechanical_strain`, the extrinsic deformation (excluding eigenstrains) is a useful measure to gauge the deformation of materials with mixed stiffness under thermal expansion. We should be able to output it.

## Design
Add `mechanical_strain` in the action base class list of outputtable properties.

## Impact
Added capability.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #17624

(note that this PR adds not a single untested line of code)

### CODE REVIEW

**Comment by sapitts** [comment]
>(note that this PR adds not a single untested line of code)

So this was always untested code? Should that perhaps be corrected here?

**Review by sapitts — COMMENTED** [review]
Naming consistency with the code base itself looks good

**Review by cticenhour — APPROVED** [review]
LGTM!

**Comment by cticenhour** [comment]
Also @dschwen, nice editing of someone else's comment with your response 😆

**Comment by dschwen** [comment]
Oh, oops, I thought I clicked "Quote reply" but apparently hit "Edit"! Sorry @sapitts !!

**Comment by dschwen** [comment]
>>(note that this PR adds not a single untested line of code)

> So this was always untested code? Should that perhaps be corrected here?

That's not what this means. It means that I'm adding data table entries that get processed during map initialization, and all the code that uses the data tables is executed already in tests.

**Pull request merged**
