### PR TITLE
recompute indicators and markers on refined grid

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
refs #6663 

My first PR so go easy :)

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Probably needs a test case.

**Comment by friedmud** [comment]
Looks ok so far... but `use_refined_mesh` isn't really the right name for this.  How about: `recompute_marker_during_cycles` or `mark_during_cycles` or `mark_while_cycling`

**Comment by jessecarterMOOSE** [comment]
Makes sense, but since it's calling computeIndicatorsAndMarkers(), should the parameter be recompute_indicators_and_markers_during_cycles? I know, that sounds a bit ridiculous, but I want it to be clear.

**Comment by permcody** [comment]
I think the point is that we shouldn't recompute the indicators in this loop with this new option. That means you need to pass a Boolean into `computeIndicatorsAndMarkers(just_kidding=true)`. Ugh... Breaking this into two methods might be even worse but cleaner in the long run.

**Comment by jessecarterMOOSE** [comment]
@permcody I could take a crack at it.

**Comment by jessecarterMOOSE** [comment]
Alright, I'm a git noob. What's the path forward?
```
> git pull --rebase upstream devel
From https://github.com/idaholab/moose
 * branch            devel      -> FETCH_HEAD
Current branch devel is up to date.
> git commit -am "fix a typo"
On branch devel
Your branch and 'origin/devel' have diverged,
and have 19 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
```

**Comment by friedmud** [comment]
Do a "git stat".  All it's telling you is that you haven't made any
changes.  So whatever "typo" you think you fixed... you didn't (maybe you
didn't save the file yet?).

Derek

**Comment by jessecarterMOOSE** [comment]
Yep, I definitely missed a `)` on my last commit, which I suppose is why the tests failed. I definitely fixed it on my local copy.

**Comment by jessecarterMOOSE** [comment]
I made a superficial change to the file and committed it, then tried to push it back and I got this (even though when I did `git pull --rebase upstream devel` it says the branch is up to date.
```
To https://github.com/jessecarterMOOSE/moose.git
 ! [rejected]        devel -> devel (non-fast-forward)
error: failed to push some refs to 'https://github.com/jessecarterMOOSE/moose.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details
```

**Comment by permcody** [comment]
It looks like you are trying to push to your devel branch. When you fork you have two devel branches. One in upstream (the main repository) and one in origin (your fork). You are rebasing on upstream/devel which is correct, but then pushing to origin/devel. Right now the two aren't in sync. You can avoid this problem by using a feature branch to make your changes.

$ git co -b issue_6663

Push that branch up to your origin and make the PR.

**Comment by jessecarterMOOSE** [comment]
Ah, dang, the instructions did say to do that. Whoops.

**Comment by jessecarterMOOSE** [comment]
going to try this again...

**Pull request closed without merging**
