### PR TITLE
Nemesis recover

### LINKED ISSUE #28547: Nemesis output being overwritten after recover
### Bug Description

I have been running some large models and was using nemesis for the output. I noticed that when recovering a simulation, that the previous nemesis results were overwritten, which was unexpected! I was expecting the new time steps to be appended to the output, which is what happens using exodus.

### Steps to Reproduce

I couldn't find any tests of this, but this simple input file demonstrates the issue
```
[Mesh]
  [mesh]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 10
    ny = 10
  []
  parallel_type = distributed
[]

[Variables]
  [u]
  []
[]

[Kernels]
  [diff]
    type = CoefDiffusion
    variable = u
    coef = 0.1
  []
  [time]
    type = TimeDerivative
    variable = u
  []
[]

[BCs]
  [left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  []
  [right]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1
  []
[]

[Executioner]
  type = Transient
  num_steps = 20
  dt = 0.1
  solve_type = PJFNK
[]

[Outputs]
  nemesis = true
  [recover]
    type = Checkpoint
    file_base = test_nemesis_recover_dir
  []
[]
```

If you run
```
 mpirun -n 2 ../../../moose_test-devel -i recover_nemesis.i Executioner/num_steps=10   
```
then
```
 mpirun -n 2 ../../../moose_test-devel -i recover_nemesis.i --recover test_nemesis_recover_dir_cp/0010
```
then the nemesis output after the recover only contains the time steps from 1.1 to 2.

### Impact

I had to re-run some models to save off the original output that had been overridden. 

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by cpgr**
Fixes #28547 (hopefully)

I had a go at this, and then found the code referenced in #13415 which was similar to what I had but probably better 😄, so I adapted what I had to match that.

### CODE REVIEW

**Comment by GiudGiud** [comment]
sounds good please ping me when you want a review
looks like the test failure is just a missing file

**Comment by cpgr** [comment]
Hey @GiudGiud - I think the disable HDF5 failure is real unfortunately, but I'm not certain why? It seems to not like the gold nemesis files

**Comment by GiudGiud** [comment]
@roystgnr does Nemesis rely on HDF5 in the back end by any chance?

For exodus we have set `write_hdf5` to false by default so that systems without hdf5 could read the outputs

**Comment by cpgr** [comment]
Following this hint, I have copied what was in Exodus to set using HDF5 to false by default in the Nemesis output class also

**Comment by roystgnr** [comment]
Yup, that was it; ExodusII *and* Nemesis default to HDF5 output unless we tell them not to.  My apologies for not thinking to write something like 7ff5fe8cea813cd8c5b93229772d67573cd805e3 myself in the first place when I was changing the ExodusII default.

**Review by GiudGiud — APPROVED** [review]
this is good to go for me. pls just undraft the PR when you want it merged.

**Comment by cpgr** [comment]
Thanks again @GiudGiud

**Pull request merged**
