### PR TITLE
Hold stringstream in unique pointer

### LINKED ISSUE #14067: New without delete in ADSingleVariableReturnMapping
## Reason
Copy paste error that leads to leaking memory in certain error conditions.

## Design
Use a smart pointer instead.

## Impact
Clean up

### PR DESCRIPTION
**Pull request by dschwen**
Closes #14067

### CODE REVIEW

**Review by permcody — DISMISSED** [review]

**Comment by tophmatthews** [comment]
Also `SingleVariableReturnMappingSolution`

**Comment by dschwen** [comment]
Ok, I'll fix that up and make the change to the non-AD version as well

**Review by permcody — APPROVED** [review]

**Comment by tophmatthews** [comment]
Still needs similar treatment in `SingleVariableReturnMappingSolution`

**Comment by dschwen** [comment]
No

**Comment by tophmatthews** [comment]
Wait, no I just missed it whoops!

**Pull request merged**
