### PR TITLE
Line Function Sampler

### LINKED ISSUE #6438: LineFunctionSampler
### Description of the enhancement or error report
Add the ability to Sample a Function along a line

### Rationale for the enhancement or information for reproducing the error
Need to be able to sample a Function along a line in a VectorPostprocessor for work being completed by @mellis13

### Identified impact
Possibly some refactoring of the whole tree of "Sampling" objects.  Most likely not.

### PR DESCRIPTION
**Pull request by friedmud**
Just a simple VectorPostprocessor that could be useful for many people but that @mellis13 definitely needs currently.

Simply samples Functions along a given line.

closes #6438

### CODE REVIEW

**Comment by permcody** [comment]
Looks good except you need to follow the code standards for spacing around binary operators in each of your for loops and index adjustments. We are starting to really push this on new code committed.

**Comment by permcody** [comment]
Well crap, I accidentally merged this...  Geez... :-1:

**Comment by permcody** [comment]
Feel free to submit another PR with the binary operator fixes, else one of us will take care of it later.

**Comment by friedmud** [comment]
The operator spacing stuff needs to get put into the pre-check.  Are you saying that:

```C++
for (unsigned int p=0; p<_num_points; p++)
```

Needs to be:

```C++
for (unsigned int p = 0; p < _num_points; p++)
```

Seems pretty arbitrary to me... the first one is just as easy (if not easier since each statement is all together) to parse.  But ok ;-)

**Comment by friedmud** [comment]
Maybe I should just make  it:

```C++
f o r ( u n s i g n e d i n t p = 0 ; p < _ n u m _ p o i n t s ; p + + )
```

Just to make sure it conforms to future standards ;-)

**Comment by permcody** [comment]
I wasn't the one who made this standard. It's also controversial with only
about half devs really buying in.

It's not possible to check for binary operator spacing with simple Regexes.
We need to use a language parser to enforce these standards and that is in
the plans but not a top priority for right now.

**Pull request merged**
