### PR TITLE
A 'moose' command for users/developers

### PR DESCRIPTION
**Pull request by rwcarlsen**
After attending the moose workshop, I decided it would be worth a bit of time to create a helper tool for users (and developers) to make it easier for people to learn and work with MOOSE.

usage:
```
[user@hose MyApp] $ moose -h
usage: moose [-h] {help,appinfo,newobj,libmesh,build} ...

positional arguments:
  {help,appinfo,newobj,libmesh,build}
    help                display help for subcomands
    appinfo             display local project info
    newobj              add and register a new moose object
    libmesh             perform libmesh-related tasks
    build               (re)build moose apps, libraries, modules, and tests

optional arguments:
  -h, --help            show this help message and exit
```

Add a new kernel to your project (files created, renamed, registered, etc.) starting from any directory within your project - it goes in the right place:
```
[user@hose MyApp/src] $ moose newobj Kernel MyFooKernel
[user@hose MyApp/src] $ git status
On branch master
Your branch is ahead of 'up/master' by 13 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/base/StorkApp.C

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	include/kernels/MyFooKernel.h
	src/kernels/MyFooKernel.C
	unit/include/base/

[user@hose MyApp/src] $ git diff
diff --git a/src/base/MyApp.C b/src/base/MyApp.C
index 51b46c5..d47dc38 100644
--- a/src/base/MyApp.C
+++ b/src/base/MyApp.C
@@ -1,3 +1,4 @@
+#include "MyFooKernel.h"
 #include "MyApp.h"
 #include "Moose.h"
 #include "AppFactory.h"
@@ -40,6 +41,7 @@ extern "C" void StorkApp__registerObjects(Factory & fact
 void
 StorkApp::registerObjects(Factory & factory)
 {
+  registerObject(MyFooKernel);
 }
```

Build your app (or moose framework) from anywhere within the project directory:

```
[user@hose MyApp/src] $ moose build # build the project binary
MOOSE Compiling C++ (in opt mode) /Users/user/MyApp/src/base/StorkApp.C...
MOOSE Compiling C++ (in opt mode) /Users/user/MyApp/src/kernels/MyFooKernel.C...
...
[user@hose MyApp] $ moose build --unit #or build your unit tests
...
```

Update libmesh:

```
[user@hose MyApp] $ moose libmesh update --clean # do a clean/full rebuild of libmesh
...
```

@aeslaughter's docs commands could easily be plumbed in as a ``moose docs`` subcommand.  I also think it would be valuable to have a ``moose init [appname]`` or ``moose newapp [appname]`` subcommand that automatically populates a directory full of makefiles, c++ files, etc. for a new moose app with the given name.  We would also need to add a test compile for the template files used for creating new object stubs.

Thoughts?

### CODE REVIEW

**Comment by aeslaughter** [comment]
👍

**Comment by WilkAndy** [comment]
I don't know if the "moose" command is the right place for the following idea...

One thing i find difficult is compile flags.  Someone on moose-users says "compile libmesh with such-and-such flag".  Then i have to figure out how to do that, which paths to specify, and so on.

Eg, how do i compile libmesh/moose with vtk enabled?

It's totally unclear to me.  I end up having to look through make files or config files, etc, and "reverse engineer" what i have to do.

Eg, how do i activate "superLU" in moose?

i think i have to compile petsc differently, maybe, and then maybe something different with moose/libmesh?  OK, that'll probably take me 1/2 a day to figure out.

Eg, how do i clean up my moose compilation?

I can remember "make clean", then i remember there's other alternatives.  oh yes, i find some makefile somewhere that has a "make clobberall" command, and then i have to figure out if that's what i really want by decoding the shell "find | rm" shell command.  There goes 30 mins of development time.

I wonder whether you could somehow build some helpful hints into your "moose" command.

a

**Comment by dschwen** [comment]
@rwcarlsen you might be interested in looking at these: https://github.com/dschwen/language-moose/tree/master/snippets

**Comment by friedmud** [comment]
I'm not for these types of "meta tools".

I have seen these types of tools before.  In fact, the team I was first hired into at Sandia National Lab was precisely this: creating and maintaining "meta tools" that surrounded the large, parallel multiphysics framework...

Let me say a few things:

1.  These tools are always hailed as being developed to "improve efficiency"... but almost always end up being an efficiency drain through their continued upkeep, maintenance and breakage.
2.  These tools are always thought to help new users: but what they actually do is hamstring them.  The users never learn how to do anything without the tools so when they break/change/don't work on a platform the users are completely stuck.
3.  The intention is always to try to reduce the support load by introducing tools like this... however: it tends to just _move_ the support load.  Users will still have the same number of problems (or more) they will just be with the tools.
4.  These tools are usually intended to be small... but they quickly get out of control.  At Sandia we required a whole _team_ of people just to maintain and develop the meta tools.  Just from the comments here you can already start to see the very beginning of scope creep.  It will only get worse with time.
5.  We are a small team with small funding.  We cannot continue to spin off tools we need to maintain.  We need to stay focused and deliver results for our core funding sources.  We have over 700 Issues on this project, none of which mention this capability.  Unless something is a very obvious win we should not do it.
6.  I believe that MOOSE training provides a skewed perspective on the world.  When you're in training it feels like all anyone ever does is build MOOSE, add objects, register them, etc.  That's not actually true.  Most of the time when people are using MOOSE they build it once (or once in a while) and they _edit_ existing objects in their apps and they _run_... they run over and over again (hence why we do maintain a tool for running MOOSE-based applications: Peacock).  Adding objects and rebuilding MOOSE is actually a _rare_ occurrence.  It only feels like the opposite to us because we don't work on/use actual physics codes...

Let me address the specific pieces of what these scripts do:

```
    appinfo             display local project info
```

Ok.

```
    newobj              add and register a new moose object
```

It's better to copy an existing object that is close to what you want to do than it is to start with a blank template.  At best this is less efficient than using `cp` and find/replace (good transferrable skills).  At worst this teaches bad habits and adds to the maintenance load of modifying the framework (you have to make sure to modify the templates: and keep up with any new/removed code systems in the meta tools).  That said, this is probably the most useful part of this PR.

```
    libmesh             perform libmesh-related tasks
```

This is just a proxy for the script we already have that's working fine.  This isn't adding anything.  I still wish the `libMesh` script didn't even have to exist... but the `libMesh` developers forced our hand when they moved to automake a few years ago... but that's a completely soap box...

```
    build               (re)build moose apps, libraries, modules, and tests
```

There is nothing wrong with `make`.  We have worked tirelessly for many years to ensure that simply typing `make` does the right thing.  It's the right interface... and it teaches users good habits that are transferrable to every other project in the world.

There is no reason to wrap `make`.  This comes from someone who has done that (or helped do that) multiple times... starting with a tool called `bake` I made 10 years ago... up through `dmake` @aeslaughter and I (and everyone else after it sprawled) built a couple of years ago (which no longer exists).

**Comment by friedmud** [comment]
Oh: I forgot one:

We always maintain that MOOSE is _not_ something you run.  It's a library.  Users develop _their_ applications to run.  It gives them ownership... and helps create their own identity.  Both of those are good for developing their own teams and their own funding sources.

  Instead of getting funding to "add something to MOOSE", they are getting funding to develop GRASSHOPPER (or whatever their code is).  In addition, their users are using GRASSHOPPER... not MOOSE.  Sure, MOOSE needs to get installed first... but it's normal to install supporting libraries when trying to compile an application.

  Having a `moose` command undermines a lot of this.  It changes the dynamic.  You now run `moose` to do anything... even users of GRASSHOPPER will need to interact with the `moose` command to build, etc.

**Comment by aeslaughter** [comment]
@friedmud The idea behind this spawned from difficulties people had with "forking stork" at the latest training, people were really lost and had no concept of what they were doing and why. We (me, @jwpeterson, and @rwcarlsen) thought that we should have a script in MOOSE for birthing baby animals rather than the separate repository, from there the idea of a single point to access all of these meta scripts was born, which I am still not against but I understand your arguments.

So, perhaps we should focus on the idea of coming up something a bit more streamlined for stork at the moment, as I am almost certain that you will disagree about removing "fork the stork." 

Conceptually, I like the idea of tracking peoples apps via GitHub, but that doesn't work in practice for many reasons:
1. There 419 forks currently, only a handful of which are actually being developed. Figuring out which ones are being developed requires investigating the graphs, etc. which is not practical and we just don't do it.
2. You can only have one fork, so if you want two apps that are "tracked" then you are out of luck.
3. People just don't understand the concept, they are confused by after downloading and running MOOSE that they now need to download something else, if the app comes from MOOSE it might make more sense to them. So, many people think that they need to copy and paste stuff (like Diffusion.C/h) into there app in order to use it. (A reason why having a Kernel generator would be nice, the fact that we copy/paste Diffusion.C to create a Kernel helps fuel this desire, I feel).

With respect to tracking apps, I would like us to come up with some way to register an app with MOOSE somehow. If you meet our criteria (e.g., 80% of code coverage) then we will start testing and tracking your app with Civet (if you have a test box to run).

After saying all that I think we probably just need to leave this all alone and not do any of it, just keeping working on all the other issues we have and maybe come back to this in the future.

**Comment by rwcarlsen** [comment]
> These tools are always hailed as being developed to "improve efficiency"... but almost always end up being an efficiency drain through their continued upkeep, maintenance and breakage.

It is not a black/white issue.  Our makefiles, test harness, etc. *are* exactly these kinds of tools.  So we clearly all believe that these kinds of tools can add net value to the project.

> These tools are always thought to help new users: but what they actually do is hamstring them. The users never learn how to do anything without the tools so when they break/change/don't work on a platform the users are completely stuck.

We can test these tools to make sure they don't break.

> The intention is always to try to reduce the support load by introducing tools like this... however: it tends to just move the support load. Users will still have the same number of problems (or more) they will just be with the tools.

I disagree.  It definitely adds some support load to developers in the tool maintenance, but that doesn't de-facto mean that we have more net work to do.  It also reduces work in other areas.  Tradeoffs.

> These tools are usually intended to be small... but they quickly get out of control. At Sandia we required a whole team of people just to maintain and develop the meta tools. Just from the comments here you can already start to see the very beginning of scope creep. It will only get worse with time.

Sure, but that is project growth.  You could argue the same thing about the entire moose project.  Automatic-differentiation, threading, input file custom coupleable time-steppers, etc.  Projects grow and that is okay.

> We are a small team with small funding. We cannot continue to spin off tools we need to maintain. We need to stay focused and deliver results for our core funding sources. We have over 700 Issues on this project, none of which mention this capability. Unless something is a very obvious win we should not do it.

Part of the purpose of this tool is to collect things together that we are already doing - ``run_tests``, creating new apps, code-formatting, etc.

> I believe that MOOSE training provides a skewed perspective on the world. When you're in training it feels like all anyone ever does is build MOOSE, add objects, register them, etc. That's not actually true. Most of the time when people are using MOOSE they build it once (or once in a while) and they edit existing objects in their apps and they run... they run over and over again (hence why we do maintain a tool for running MOOSE-based applications: Peacock). Adding objects and rebuilding MOOSE is actually a rare occurrence. It only feels like the opposite to us because we don't work on/use actual physics codes...

There is huge value in lowering the barrier to entry in a project.  New users need to be able to accomplish enough to be hooked before they are willing to dedicate significant effort to MOOSE.  I think it is very valuable to lower that initial barrier - or many will give up before they make it and never become users.

You have some valid concerns.  It's probably best to pick this discussion back up after the break when people are more available/present.

**Comment by friedmud** [comment]
@aeslaughter I gotcha.

I can definitely agree that tracking via forking has not worked out.  That said, it is still interesting to be able to look at the network graph and see the latest activity.  But: that's of dubious value ;-)

I'll also add a couple more downsides of Forking:

1.  Forks can't have their own Issues!
2.  Forks can't have their own wiki!
3.  We've never been able to deploy "patches" to Stork forks by having users rebase on Stork (which was part of my original idea... but it doesn't work because of all of the naming conflicts).

As for understanding Forking: that's just a training / documentation thing.  Firstly, Forking is still a fairly new thing, especially for scientists... but it's something everyone should be getting up to speed with.

I had a whole class (NOT a computer science class: in civil engineering in fact!) this semester where all of the homework was done by Forking prototype code/documents... modifying them and then you turned in your homework by putting up a PR.  In the beginning of the class there was quite a bit of training the professors had to do because most of the class had no idea what they were talking about... but the professors were adamant that this is something _every_ engineer needs to learn how to do now because it's how all code development will be done in the future.  On that last part: I happen to agree.

As for our particular issue: I truly believe that more/better documentation would help out a lot.  There isn't anywhere that we really write down with _verbose_ words just what this whole Forking thing is about.  I'm optimistic that with the new documentation system we will be able to 

That said: I'm definitely willing to give up on the idea of forking Stork.  It was just an idea... just something to try out.  We've tried it out... if the consensus is that it's not working out let's brainstorm other ideas.

**Comment by dschwen** [comment]
If the entry barrier is the main issue here, there are other approaches. We could offer a single cut and paste line on our homepage that pulls and runs a script from a webserver (a bunch of projects do that: http://brew.sh/ https://rvm.io/rvm/install).

Yeah, opinions on how good of a practice it is to cut and paste commands from websites can differ widely :-). But we are asking people to trust our binary installers already.

The curl-bash-install script could be customizable (i.e. with a small webform to pick an application name and a some checkboxes to select the modules that are needed). Of course the downside is that we are not teaching people the guts of git with this...

**Comment by friedmud** [comment]
> It is not a black/white issue. Our makefiles, test harness, etc. are exactly these kinds of tools. So we clearly all believe that these kinds of tools can add net value to the project.

Yes, MOOSE does need some amount of supporting software.  The trick to find the right place to draw the line.

Makefiles are obviously necessary... but we have worked hard to keep them at a minimum.  @permcody and @jwpeterson have done amazing work on them to keep upkeep to a minimum... both for us and for our users.

Our test harness is actually, possibly, one step too far.  If I could rip it out and replace it with something else I would.  We really have no business writing a test harness.

We actually started by using a different test harness: [Nose](http://nose.readthedocs.io/en/latest/).  But, we quickly outgrew it.  When we went looking for alternatives there was really nothing that satisfied our needs.  So we made one... and then we remade it... and remade it.  At this point, what we have is really good... but even so: I would use something else if I could.  We have (and will) put a TON of time into the testing system that could have gone towards other activities.

This new set of scripts is not that way.  It's not something that anyone is asking for... it's not necessary.  It's just a veneer over the top of already working UNIX paradigms.

We don't need to get into the business of creating an operating system (MOOSEOS?).  The operating system and its tools already work well.  Let's just educate our users on the right way to use them.

> We can test these tools to make sure they don't break.

Yes and no.  You _can_ test them... but you'll never be able to test all of the whacky combinations out there.  Look at all of the testing we do now... but someone still comes along with a Cray machine with a weird environment and we spend days figuring out what's up.  These scripts will not help with that... and will just add another layer of indirection... another layer that can go wrong.

> I disagree. It definitely adds some support load to developers in the tool maintenance, but that doesn't de-facto mean that we have more net work to do. It also reduces work in other areas. Tradeoffs.

Yes, and I'm saying that I've seen this tradeoff before and it doesn't end up being a net win.

Smaller: targeted efforts at _just_ the things we need work out better in the long run.

> Sure, but that is project growth. You could argue the same thing about the entire moose project. Automatic-differentiation, threading, input file custom coupleable time-steppers, etc. Projects grow and that is okay.

All growth should be looked at with a critical eye.  Growth is the death of any software project.  It is not "okay".  Every single new thing we add to MOOSE is one step closer to killing the project.  The best we can do is hope to delay the inevitable by making really smart decisions about what goes in.  Only pieces that add significantly to the value of MOOSE without adding too much baggage should be allowed.

This set of scripts, even though they are not currently large, is a HUGE amount of baggage.  It's tying our entire way of working... the entire way that users use and perceive MOOSE into this one command.  Once added, we can never go back.

As for some of the specific technical things you called out... all three of those are _perfect_ examples of things that are questionable... and possibly shouldn't be allowed!  In fact, 2 of those three are still NOT in the framework for just that reason... and I had to write huge essays about how your implementation of one of them wasn't right for exactly this same reason: it added too much baggage and not enough upside.

Specifically:

  - Auto-diff: This isn't in yet because I haven't found a way to do it without destroying MOOSE (either technically or spiritually).  BUT: If we can do it it will be amazing.  The upside is _huge_... just need to work on the downside.
  - Threading: This is possibly the biggest mistake I ever made in MOOSE.  To this day I still wonder if we should rip it all out.  The upside has been minimal... only a small percentage of users have ever even tried it.  The downside has been enormous: it adds a crazy amount of complication to the internals of MOOSE.  We have spent WAY too much time tracking down bugs in threading for how much we've gained from the capability.  I really think it's just unnecessary.  However, we keep it because it is (mostly) working... and we would never get it back if we let it go.
  - Custom coupled TimeSteppers: This was never put in before now because the upside is dubious... and it adds baggage.  However, I do think that the new `Steppers` is good... it's better than what was there and adds value without adding huge overhead.  We'll see though...

> Part of the purpose of this tool is to collect things together that we are already doing - run_tests, creating new apps, code-formatting, etc.

“Collection” is not a goal.  In fact: the UNIX paradigms “code should do one thing and do it well” and “small tools should feed each other” goes directly against the idea of “collection”.

> There is huge value in lowering the barrier to entry in a project. New users need to be able to accomplish enough to be hooked before they are willing to dedicate significant effort to MOOSE. I think it is very valuable to lower that initial barrier - or many will give up before they make it and never become users.

I actually don’t think we have a large initial barrier… especially compared to other computational science projects.  Most other projects are incredibly complicated to compile / install.  We provide awesome prebuilt packages that do most of the work… and scripts where necessary (like update_and_rebuild_libmesh.sh).  And then a prebuilt template App that gets people running quickly (Stork).

All-in-all MOOSE is not hard to “get started” with.

The problem actually comes _after_ that point.  After you’ve set up your Stork fork… or after you compiled and run the MOOSE tests.

Our documentation for what to do next is _completely_ missing.  We don’t have any guided examples (just an `examples` directory and a few loosely tied Wiki pages that don’t do any explanation).  We don’t have any verbose prose on what to actually _do_ with MOOSE.  We just expect users to figure it out by looking at examples and tests.

I hope to really change all of that once the new documentation system is deployed.

We need to QUIT writing scripts/software… and START writing documentation!

**Comment by aeslaughter** [comment]
I don't think we are doing this, at least not now.

**Pull request closed without merging**
