### PR TITLE
Revert "Guarantee for isotropic elasticity tensor"

### PR DESCRIPTION
**Pull request by bwspenc**
Reverts idaholab/moose#8884

### CODE REVIEW

**Comment by bwspenc** [comment]
@dschwen When I try to build on my Mac, I get errors like this after your PR:

/Users/spenbw/gitproj/githerd/moose/modules/tensor_mechanics/include/materials/ComputeStressBase.h:57:5: error: expected identifier
    0 = 0,
    ^
/Users/spenbw/gitproj/githerd/moose/modules/tensor_mechanics/include/materials/ComputeStressBase.h:58:5: error: expected identifier
    1 = 1

I'm using clang.  I'm surprised you didn't hit this on your machine.  It looks like it's translating the TRUE/FALSE in the enums to 1/0's or something.

**Comment by bwspenc** [comment]
Maybe this isn't necessary because the other PR I just submitted fixes the build for me.

**Comment by dschwen** [comment]
Ben, I wonder if there is a `TRUE` and a `FALSE` macro declared somewhere in the source tree.

**Comment by dschwen** [comment]
Yeah, for sure there is. This is soooo dumb!!!!!

**Pull request closed without merging**
