### PR TITLE
Allow per-element calculation during jacobian computations

### LINKED ISSUE #7829: Allow per-element calculation during jacobian computations
### Description of the enhancement or error report
Introduce methods for executing per-element calculation during computeJacobian methods.

### Rationale for the enhancement or information for reproducing the error
Will reduce computational time when kernel needs information from GrainTracker for jacobian calculations. GrainTracker communication can be done once per-element instead of at each quadrature point.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New methods to be added in kernel. No impact on existing tests.

### PR DESCRIPTION
**Pull request by SudiptaBiswas**
- Adds new methods in kernel allowing per-element calculation during execution of computeJacobian methods
  - Closes #7829

### CODE REVIEW

**Review by friedmud — APPROVED** [review]
This looks fine to me.

**Comment by permcody** [comment]
Pedantic, but you are missing a space on the second new method declaration before the curly braces

**Comment by friedmud** [comment]
Wow - _super_ pedantic!  😄

**Comment by SudiptaBiswas** [comment]
Updated

**Comment by dschwen** [comment]
You could add those where you actually need them by overwriting the computeResidual etc. methods. Like in NonlocalKernel.

**Comment by SudiptaBiswas** [comment]
I was actually trying to avoid that. And these methods might be useful for any other kernels that uses GrainTracker.

**Comment by dschwen** [comment]
Ok. That's fine, if there are broader applications the kernel class is the
right place. We just had a question about this on the mailing list a few
days ago (by Jesse Carter I think).

**Comment by jessecarterMOOSE** [comment]
yep, I could definitely make use of this.

**Pull request merged**
