### PR TITLE
Add option to declare sidesets that do not exist on mesh at the beginning of the simulation

### PR DESCRIPTION
**Pull request by GiudGiud**
From #27857 
copy-pasta from subdomain early adding

### CODE REVIEW

**Comment by GiudGiud** [comment]
Ready for review

**Comment by GiudGiud** [comment]
I'll fix the merge conflict once the PR is reviewed

**Review by lindsayad — APPROVED** [review]
will there be another option coming for nodesets?

**Comment by GiudGiud** [comment]
only if requested

**Comment by GiudGiud** [comment]
sneaky commit with a parenthesis in doco. Hope you wont mind

**Review by lindsayad — APPROVED** [review]
double approve nice catch

**Comment by GiudGiud** [comment]
Failure unrelated since this is a new parameter

**Pull request merged**
