### PR TITLE
Rename SerialMesh, ParallelMesh

### PR DESCRIPTION
**Pull request by jwpeterson**
to ReplicatedMesh and DistributedMesh, respectively.  Summary of changes include:
- Rename/deprecate various APIs that referred directly to `ParallelMesh`, e.g. `MooseMesh::isParallelMesh(), errorIfParallelDistribution(), getParallelMeshOnCommandLine()`, etc.
- Change the TestHarness to respect the command line option `--distributed-mesh` in addition to `--parallel-mesh`.
- Also changed the `[Mesh]` block `distribution` flag to `parallel_type`, so that instead of:

```
distribution = distributed
```

which is kind of awkward, one can say:

```
parallel_type = distributed
```

and 

```
parallel_type = replicated
```

as necessary.

Refs libMesh/libmesh#929.

### CODE REVIEW

**Comment by friedmud** [comment]
This is a user-facing API change... is the old syntax going to work for a while but be deprecated?

**Comment by jwpeterson** [comment]
> This is a user-facing API change... is the old syntax going to work for a while but be deprecated?

Yes.  If it's not, I will fix it...

**Comment by jwpeterson** [comment]
BISON requires an update in order for this PR to pass.  They cast a libMesh mesh to a `SerialMesh`, this needs to change to a `ReplicatedMesh`, since that is the actual underlying type now.

I have made the fix (BISON 377) but I don't think it will pass (?) until this is PR merged and there's a MOOSE submodule update in BISON.

**Comment by jwpeterson** [comment]
Actually, nevermind, looks like the BISON PR passed on its own.  As soon as its merged, I will invalidate the app tests here.

**Comment by permcody** [comment]
👍

**Pull request merged**
