### PR TITLE
Update remote access, make more prominent

### PR DESCRIPTION
**Pull request by permcody**
refs #14767

### CODE REVIEW

**Review by aeslaughter — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]
👍

**Comment by loganharbour** [comment]
Side note that I found out from Jack earlier today after setting him up with a similar profile, some internal submodules still point to `hpcgitlab.inl.gov` instead of `hpcgitlab.hpc.inl.gov`.

**Comment by permcody** [comment]
We should be fixing those as we find them. Better yet, we should be changing those to relative locations as much as possible.

**Comment by loganharbour** [comment]
On that note, @andrsd see my message above

**Pull request merged**
