### PR TITLE
Fix destruction order in MooseApp

### LINKED ISSUE #21019: Destructor order issue in MooseApp
## Bug Description
Valgrind backtrace
```
==75434== Invalid read of size 8
==75434==    at 0x512E32D: data (basic_string.h:2317)
==75434==    by 0x512E32D: compare (basic_string.h:2863)
==75434==    by 0x512E32D: operator< <char, std::char_traits<char>, std::allocator<char> > (basic_string.h:6232)
==75434==    by 0x512E32D: operator() (stl_function.h:386)
==75434==    by 0x512E32D: _M_lower_bound (stl_tree.h:1950)
==75434==    by 0x512E32D: std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (stl_tree.h:2575)
==75434==    by 0x12DF54B9: count (stl_set.h:749)
==75434==    by 0x12DF54B9: isRegisteredTask (ActionFactory.h:121)
==75434==    by 0x12DF54B9: ActionWarehouse::isTaskComplete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (ActionWarehouse.C:453)
==75434==    by 0x12D13B16: OutputWarehouse::mooseConsole(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&) (OutputWarehouse.C:210)
==75434==    by 0x12D15EB7: OutputWarehouse::~OutputWarehouse() (OutputWarehouse.C:45)
==75434==    by 0x138B9355: MooseApp::~MooseApp() (MooseApp.C:584)
==75434==    by 0x6A8317D: _M_release (shared_ptr_base.h:155)
==75434==    by 0x6A8317D: _M_release (shared_ptr_base.h:148)
==75434==    by 0x6A8317D: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x6A8317D: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x6A8317D: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp> > (stl_construct.h:98)
==75434==    by 0x6A8317D: __destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:108)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:137)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp>*, std::shared_ptr<MooseApp> > (stl_construct.h:206)
==75434==    by 0x6A8317D: ~vector (stl_vector.h:677)
==75434==    by 0x6A8317D: MultiApp::~MultiApp() (MultiApp.h:104)
==75434==    by 0x132179B0: _M_release (shared_ptr_base.h:155)
==75434==    by 0x132179B0: _M_release (shared_ptr_base.h:148)
==75434==    by 0x132179B0: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x132179B0: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x132179B0: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp> > (stl_construct.h:98)
==75434==    by 0x132179B0: __destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:108)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:137)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp>*, std::shared_ptr<MultiApp> > (stl_construct.h:206)
==75434==    by 0x132179B0: ~vector (stl_vector.h:677)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:98)
==75434==    by 0x132179B0: __destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:108)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:137)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*, std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:206)
==75434==    by 0x132179B0: ~vector (stl_vector.h:677)
==75434==    by 0x132179B0: MooseObjectWarehouseBase<MultiApp>::~MooseObjectWarehouseBase() (MooseObjectWarehouseBase.h:250)
==75434==    by 0x13186C01: FEProblemBase::~FEProblemBase() (FEProblemBase.C:493)
==75434==    by 0x404447: _M_release (shared_ptr_base.h:155)
==75434==    by 0x404447: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (shared_ptr_base.h:148)
==75434==    by 0x12DF3676: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x12DF3676: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x12DF3676: reset (shared_ptr_base.h:1287)
==75434==    by 0x12DF3676: ActionWarehouse::clear() (ActionWarehouse.C:71)
==75434==    by 0x138B8292: MooseApp::~MooseApp() (MooseApp.C:594)
==75434==    by 0x6A82C39: _M_release (shared_ptr_base.h:155)
==75434==    by 0x6A82C39: _M_release (shared_ptr_base.h:148)
==75434==    by 0x6A82C39: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x6A82C39: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x6A82C39: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp> > (stl_construct.h:98)
==75434==    by 0x6A82C39: __destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:108)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:137)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp>*, std::shared_ptr<MooseApp> > (stl_construct.h:206)
==75434==    by 0x6A82C39: ~vector (stl_vector.h:677)
==75434==    by 0x6A82C39: MultiApp::~MultiApp() (MultiApp.h:104)
==75434==  Address 0x166eddf98 is 40 bytes inside a block of size 64 free'd
==75434==    at 0x4C38F91: operator delete(void*) (vg_replace_malloc.c:802)
==75434==    by 0x4E4E4C6: deallocate (new_allocator.h:128)
==75434==    by 0x4E4E4C6: deallocate (alloc_traits.h:469)
==75434==    by 0x4E4E4C6: _M_put_node (stl_tree.h:584)
==75434==    by 0x4E4E4C6: _M_drop_node (stl_tree.h:651)
==75434==    by 0x4E4E4C6: std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase(std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*) (stl_tree.h:1920)
==75434==    by 0x12DF2CDD: ~_Rb_tree (stl_tree.h:1000)
==75434==    by 0x12DF2CDD: ~set (stl_set.h:281)
==75434==    by 0x12DF2CDD: ActionFactory::~ActionFactory() (ActionFactory.C:16)
==75434==    by 0x138B9349: MooseApp::~MooseApp() (MooseApp.C:584)
==75434==    by 0x6A8317D: _M_release (shared_ptr_base.h:155)
==75434==    by 0x6A8317D: _M_release (shared_ptr_base.h:148)
==75434==    by 0x6A8317D: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x6A8317D: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x6A8317D: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp> > (stl_construct.h:98)
==75434==    by 0x6A8317D: __destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:108)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:137)
==75434==    by 0x6A8317D: _Destroy<std::shared_ptr<MooseApp>*, std::shared_ptr<MooseApp> > (stl_construct.h:206)
==75434==    by 0x6A8317D: ~vector (stl_vector.h:677)
==75434==    by 0x6A8317D: MultiApp::~MultiApp() (MultiApp.h:104)
==75434==    by 0x132179B0: _M_release (shared_ptr_base.h:155)
==75434==    by 0x132179B0: _M_release (shared_ptr_base.h:148)
==75434==    by 0x132179B0: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x132179B0: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x132179B0: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp> > (stl_construct.h:98)
==75434==    by 0x132179B0: __destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:108)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:137)
==75434==    by 0x132179B0: _Destroy<std::shared_ptr<MultiApp>*, std::shared_ptr<MultiApp> > (stl_construct.h:206)
==75434==    by 0x132179B0: ~vector (stl_vector.h:677)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:98)
==75434==    by 0x132179B0: __destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:108)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:137)
==75434==    by 0x132179B0: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*, std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:206)
==75434==    by 0x132179B0: ~vector (stl_vector.h:677)
==75434==    by 0x132179B0: MooseObjectWarehouseBase<MultiApp>::~MooseObjectWarehouseBase() (MooseObjectWarehouseBase.h:250)
==75434==    by 0x13186C01: FEProblemBase::~FEProblemBase() (FEProblemBase.C:493)
==75434==    by 0x404447: _M_release (shared_ptr_base.h:155)
==75434==    by 0x404447: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (shared_ptr_base.h:148)
==75434==    by 0x12DF3676: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x12DF3676: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x12DF3676: reset (shared_ptr_base.h:1287)
==75434==    by 0x12DF3676: ActionWarehouse::clear() (ActionWarehouse.C:71)
==75434==    by 0x138B8292: MooseApp::~MooseApp() (MooseApp.C:594)
==75434==    by 0x6A82C39: _M_release (shared_ptr_base.h:155)
==75434==    by 0x6A82C39: _M_release (shared_ptr_base.h:148)
==75434==    by 0x6A82C39: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x6A82C39: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x6A82C39: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp> > (stl_construct.h:98)
==75434==    by 0x6A82C39: __destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:108)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp>*> (stl_construct.h:137)
==75434==    by 0x6A82C39: _Destroy<std::shared_ptr<MooseApp>*, std::shared_ptr<MooseApp> > (stl_construct.h:206)
==75434==    by 0x6A82C39: ~vector (stl_vector.h:677)
==75434==    by 0x6A82C39: MultiApp::~MultiApp() (MultiApp.h:104)
==75434==    by 0x13217AFF: _M_release (shared_ptr_base.h:155)
==75434==    by 0x13217AFF: _M_release (shared_ptr_base.h:148)
==75434==    by 0x13217AFF: ~__shared_count (shared_ptr_base.h:730)
==75434==    by 0x13217AFF: ~__shared_ptr (shared_ptr_base.h:1169)
==75434==    by 0x13217AFF: ~shared_ptr (shared_ptr.h:103)
==75434==    by 0x13217AFF: _Destroy<std::shared_ptr<MultiApp> > (stl_construct.h:98)
==75434==    by 0x13217AFF: __destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:108)
==75434==    by 0x13217AFF: _Destroy<std::shared_ptr<MultiApp>*> (stl_construct.h:137)
==75434==    by 0x13217AFF: _Destroy<std::shared_ptr<MultiApp>*, std::shared_ptr<MultiApp> > (stl_construct.h:206)
==75434==    by 0x13217AFF: ~vector (stl_vector.h:677)
==75434==    by 0x13217AFF: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:98)
==75434==    by 0x13217AFF: __destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:108)
==75434==    by 0x13217AFF: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*> (stl_construct.h:137)
==75434==    by 0x13217AFF: _Destroy<std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > >*, std::vector<std::shared_ptr<MultiApp>, std::allocator<std::shared_ptr<MultiApp> > > > (stl_construct.h:206)
==75434==    by 0x13217AFF: ~vector (stl_vector.h:677)
==75434==    by 0x13217AFF: MooseObjectWarehouseBase<MultiApp>::~MooseObjectWarehouseBase() (MooseObjectWarehouseBase.h:250)
==75434==  Block was alloc'd at
==75434==    at 0x4C36833: operator new(unsigned long) (vg_replace_malloc.c:417)
==75434==    by 0x5562BB2: allocate (new_allocator.h:114)
==75434==    by 0x5562BB2: allocate (alloc_traits.h:443)
==75434==    by 0x5562BB2: _M_get_node (stl_tree.h:580)
==75434==    by 0x5562BB2: _M_create_node<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (stl_tree.h:630)
==75434==    by 0x5562BB2: operator()<const std::__cxx11::basic_string<char>&> (stl_tree.h:548)
==75434==    by 0x5562BB2: _M_insert_<const std::__cxx11::basic_string<char>&, std::_Rb_tree<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, std::_Identity<std::__cxx11::basic_string<char> >, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::__cxx11::basic_string<char> > >::_Alloc_node> (stl_tree.h:1815)
==75434==    by 0x5562BB2: std::pair<std::_Rb_tree_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, bool> std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_insert_unique<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (stl_tree.h:2158)
==75434==    by 0x12DF4932: insert (stl_set.h:511)
==75434==    by 0x12DF4932: ActionFactory::reg(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Action> (*)(InputParameters const&), InputParameters (*)(), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (ActionFactory.C:37)
==75434==    by 0x138DAA4D: Registry::registerActionsTo(ActionFactory&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (Registry.C:100)
==75434==    by 0x138E5042: Moose::registerActions(Syntax&, ActionFactory&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (Moose.C:380)
==75434==    by 0x138E955D: Moose::registerAll(Factory&, ActionFactory&, Syntax&) (Moose.C:59)
==75434==    by 0x138B5DEB: MooseApp::MooseApp(InputParameters) (MooseApp.C:469)
==75434==    by 0x517BE4E: BlueCrabApp::BlueCrabApp(InputParameters) (BlueCrabApp.C:91)
==75434==    by 0x4E4D8E0: BlueCrabTestApp::BlueCrabTestApp(InputParameters) (BlueCrabTestApp.C:27)
==75434==    by 0x4E51B7C: void __gnu_cxx::new_allocator<BlueCrabTestApp>::construct<BlueCrabTestApp, InputParameters const&>(BlueCrabTestApp*, InputParameters const&) [clone .isra.0] (new_allocator.h:146)
==75434==    by 0x4E5210B: construct<BlueCrabTestApp, const InputParameters&> (alloc_traits.h:483)
==75434==    by 0x4E5210B: _Sp_counted_ptr_inplace<const InputParameters&> (shared_ptr_base.h:548)
==75434==    by 0x4E5210B: __shared_count<BlueCrabTestApp, std::allocator<BlueCrabTestApp>, const InputParameters&> (shared_ptr_base.h:679)
==75434==    by 0x4E5210B: __shared_ptr<std::allocator<BlueCrabTestApp>, const InputParameters&> (shared_ptr_base.h:1344)
==75434==    by 0x4E5210B: shared_ptr<std::allocator<BlueCrabTestApp>, const InputParameters&> (shared_ptr.h:359)
==75434==    by 0x4E5210B: allocate_shared<BlueCrabTestApp, std::allocator<BlueCrabTestApp>, const InputParameters&> (shared_ptr.h:702)
==75434==    by 0x4E5210B: make_shared<BlueCrabTestApp, const InputParameters&> (shared_ptr.h:718)
==75434==    by 0x4E5210B: std::shared_ptr<MooseApp> AppFactory::buildApp<BlueCrabTestApp>(InputParameters const&) (AppFactory.h:132)
==75434==    by 0x1384138A: AppFactory::createShared(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, InputParameters, int) (AppFactory.C:87)
```

## Steps to Reproduce
A complex model from @jortensi 

## Impact
segmentation fault or erroneous error at the end of a MOOSE simulation

### PR DESCRIPTION
**Pull request by lindsayad**
The OutputWarehouse relies on being able to make calls to the
action warehouse so we must make sure that the latter is destructed
after the output warehouse

Closes #21019

### CODE REVIEW

**Review by permcody — APPROVED** [review]

**Comment by YaqiWang** [comment]
Why did not we notice this before or how the error can be triggered?

**Comment by lindsayad** [comment]
You have to hit the `else if` branch here, and I think we virtually always hit the first `if` branch
```c++
  // Loop through all Console Output objects and pass the current output buffer                                                                                                                                                               
  std::vector<Console *> objects = getOutputs<Console>();                                                                                                                                                                                     
  if (!objects.empty())                                                                                                                                                                                                                       
  {                                                                                                                                                                                                                                           
    for (const auto & obj : objects)                                                                                                                                                                                                          
      obj->mooseConsole(message);                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
    // Reset                                                                                                                                                                                                                                  
    buffer.clear();                                                                                                                                                                                                                           
    buffer.str("");                                                                                                                                                                                                                           
  }                                                                                                                                                                                                                                           
  else if (!_app.actionWarehouse().isTaskComplete("add_output"))
```

**Comment by loganharbour** [comment]
As all of the current failures are as a result of the non-next rebase and with it being a priority: merge with the breaks

**Review by loganharbour — APPROVED** [review]

**Comment by lindsayad** [comment]
Failures unrelated and we want this to get in as soon as a devel to next fast forward is possible

**Pull request merged**
