### PR TITLE
Fix a bug in clone_master_mesh plus uniform refinement

### LINKED ISSUE #14493: When using cloned mesh in multiapp, we should not do uniform refinement
## Bug Description
I added `clone_master_mesh` parameter in `MultiApp`, but forgot to turn uniform refinement off when multapp is using the cloned mesh from master.

## Steps to Reproduce
Following change in a test file using this feature will reveal the bug:
```
diff --git a/test/tests/multiapps/picard/picard_master.i b/test/tests/multiapps/picard/picard_master.i
index e4488a8686..01d0f3d6a3 100644
--- a/test/tests/multiapps/picard/picard_master.i
+++ b/test/tests/multiapps/picard/picard_master.i
@@ -1,9 +1,10 @@
 [Mesh]
   type = GeneratedMesh
   dim = 2
-  nx = 10
-  ny = 10
+  nx = 5
+  ny = 5
   parallel_type = replicated
+  uniform_refine = 1
 []
```

## Impact
Users using this feature. Since no one has complained yet, possibly none. This bug needs to be fixed asap. I will send in a PR shortly.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #14493.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody This is the bug fix. Please consider merging it asap. Best.

**Review by permcody — DISMISSED** [review]

**Comment by YaqiWang** [comment]
The failure is real! So painful. The `GapConductance` material is using that flag...

**Comment by YaqiWang** [comment]
This will be an interesting case that we can discuss for the new mesh generation system. I think the fix is legislately correct although I really do not want that flag hanging around after mesh setup.

**Comment by YaqiWang** [comment]
@permcody Guess we have to merge this manually?

**Comment by permcody** [comment]
What about the THM failure?

**Comment by permcody** [comment]
> What about the THM failure?

Nevermind, I think the THM failure was caused by something else.

**Comment by andrsd** [comment]
Most likely by #14461, I have not seen a MR that would fix THM...

**Comment by YaqiWang** [comment]
It is by the file base change. Thought @permcody was working on a fix. I fixed mammoth and tagged Cody for fixing thm.

**Comment by permcody** [comment]
Yeah, I can't always fix everyone else's PRs. THM isn't my module, it's David's so he can tell you a little more quickly if the diff is significant or not or might be able to tell you if it's a big change or not (I suspect not). I probably missed that you tagged me earlier.

**Review by permcody — APPROVED** [review]

**Pull request merged**
