### PR TITLE
Revert "Revert "AMR for ElementSubdomainModifier ""

### PR DESCRIPTION
**Pull request by loganharbour**
Reverts idaholab/moose#24311, which reverted #23078.

### CODE REVIEW

**Comment by loganharbour** [comment]
FYI @dewenyushu

**Comment by dewenyushu** [comment]
> FYI @dewenyushu

Thanks @loganharbour !!

**Comment by grmnptr** [comment]
May I have a review on this, @lindsayad , @loganharbour ?

**Comment by loganharbour** [comment]
I approve Peter's additions; he will approve the remainder of the content that is not his. I cannot approve because the UI will not let me ✅  my own PR.

**Review by grmnptr — APPROVED** [review]

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
