### PR TITLE
Use previous unconstrained dt after sync in IterationAdaptiveDT

### LINKED ISSUE #25374: Have `IterationAdaptiveDT` use previous unconstrained time step size after sync
## Reason
After a sync point, `IterationAdaptiveDT` currently uses the old old (two olds) time step size. For example, suppose there is a sync points every 10 seconds (including 90, 100, 110, etc.) and a growth factor of 1.2.
```
step 50: dt=5, t_new=90
step 51: dt=6, t_new=96
step 52: unconstrained_dt=7.2, constrained_dt=4, t_new=100
step 53: dt=6, t_new=106
step 54: unconstrained_dt=7.2, constrained_dt=4, t_new=110
step 55: dt=6, t_new=116
...
```
So it gets into a rut where it can no longer increase the time step size, resulting in twice as many time steps as necessary.

## Design
I propose we change it to use the previous unconstrained time step size after a sync point, for example:
```
step 50: dt=5, t_new=90
step 51: dt=6, t_new=96
step 52: unconstrained_dt=7.2, constrained_dt=4, t_new=100
step 53: dt=7.2, t_new=107.2
step 54: unconstrained_dt=8.64, constrained_dt=2.8, t_new=110
step 55: dt=8.64, t_new=118.64
...
```
We can get the previous unconstrained dt with ` _executioner.unconstrainedDT()`.

## Impact
Modified behavior for users using `IterationAdaptiveDT` with time syncs.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #25374

### CODE REVIEW

**Comment by joshuahansel** [comment]
Appears to be 2 failing Bison tests (which I could fix). The other failures seem unrelated.

Objections @dschwen @bwspenc ?

**Comment by GiudGiud** [comment]
Josh is on streak fixing everything rn

**Comment by joshuahansel** [comment]
Bison fix: https://github.inl.gov/ncrc/bison/pull/5588. This is ready for review.

**Comment by lindsayad** [comment]
I want to know that this is a desirable change to the BISON team before moving forward

**Comment by joshuahansel** [comment]
Btw it was really one Bison test affected, not two (AD and non-AD versions of the same test). It would be nice to get some confirmation of it being a desirable change though. I'll try @gambka now.

**Comment by gambka** [comment]
@simopier can you check the new results in this test? You recently were working in this area.

**Comment by simopier** [comment]
@joshuahansel @lindsayad @gambka 
The change looks good to me. On the affected bison test, I don't see any major effects except for the expected impact on the number of time steps (decrease).

**Review by lindsayad — DISMISSED** [review]

**Comment by simopier** [comment]
What is the status on this?

**Comment by joshuahansel** [comment]
> What is the status on this?

It was waiting because I think maybe there was some reason we were waiting to break next. I'm gonna rebase this and then update the Bison PR.

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
