### PR TITLE
Exodiff-like summary output

### LINKED ISSUE #12682: Exodiff like summary report for CSV Differ tool
## Rationale
Request for a similar output style like Exodiff.

## Description
The csvdiff tool should output a summary report more similar to an exodiff report. Even though some of the output may not make sense if you had no idea what an Exodiff summary was.

But, because we are already printing information relating to what an Exodiff summary outputs, we might was well bring them closer together.

## Impact
None

### PR DESCRIPTION
**Pull request by milljm**
Certain key words are now printed for summary reports.

Closes #12682

### CODE REVIEW

**Comment by milljm** [comment]
Tagging @gardnerru 
He may have an additional change request to this PR. A recent failure as follows:

```
ERROR: In file TSQ022_1pt5_chkfile.csv: The values in column "FCT" don't match @ t0

        relative diff:   300.015890 ~ 300.016044 = 0.000001 (5.117e-07)
```

I don't think there is such a thing as Time Step 0.

**Comment by milljm** [comment]
Russell discovered an issue with the current csvdiff tool. Going to include the fix into this PR.

**Review by bwspenc — APPROVED** [review]

**Comment by milljm** [comment]
@bwspenc @permcody 
Ya'll merged when I asked you not to!

**Comment by bwspenc** [comment]
I didn't mean to merge anything that wasn't ready.  Where did you say it wasn't ready?

**Comment by milljm** [comment]
On Jan 11, 2.39 PM I added the "Do Not Merge" label, and then immediately following, added a message as to why. Its listed right here, within the messages above _this_ message... Are you not seeing that for some reason?

Go to this link to see this exact thread: https://github.com/idaholab/moose/pull/12683

Its not a breaking issue... I have created a new issue to pick up where I left off.

**Comment by bwspenc** [comment]
I see -- I missed the Do Not Merge flag.  Sorry about that.

**Pull request merged**
