### PR TITLE
Clean up parameter names

### PR DESCRIPTION
**Pull request by dschwen**
Refs #7488 

This contains PR #7484 due to some overlap

### CODE REVIEW

**Comment by dschwen** [comment]
This will need another Marmot fix and a Bison fix (for an input I wrote).

**Comment by dschwen** [comment]
I have a marmot and a bison fix ready.

**Comment by permcody** [comment]
I can merge this whenever. Let me know if you are still ready

**Comment by dschwen** [comment]
Yep, I'm still ready.

**Comment by permcody** [comment]
Merged

**Pull request merged**
