### PR TITLE
speed up dependency resolver

### LINKED ISSUE #11396: Warehouse sorting algorithm is slow on Falcon
## Rationale

I am experiencing a very very slow initial setup with one of my example problems on Falcon.
After adding bunch of print-outs, I finally located the line causing the problem: https://github.com/idaholab/moose/blob/devel/framework/src/problems/FEProblemBase.C#L554
which calls https://github.com/idaholab/moose/blob/devel/framework/include/interfaces/DependencyResolverInterface.h#L90.
The number of materials I have is only 352.

## Description

I can try reducing the number of materials, but looks to me that something is not properly implemented (352 is not big at all).

## Impact
Make users happy and simulations faster.

### PR DESCRIPTION
**Pull request by rwcarlsen**
Fixes an n^2 algorithm into an n*log(n) algo.  Addresses shared pointer thrashing.

Fixes #11396.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Thanks. I am trying this out.

**Comment by YaqiWang** [comment]
Yes, it is fixed. Much better with this PR on Falcon.

**Review by permcody — APPROVED** [review]
Good changes. I know there are more, but this is fine to go in as-is.

**Comment by permcody** [comment]
@rwcarlsen - My fix yesterday did not impact the timing. I think this may still be worth looking today. Can we run the benchmarks on a PR? It might be worth trying a few other things here.

**Comment by rwcarlsen** [comment]
After profiling, it looks like alignment issues - the dependency resolver doesn't even show up in the profiles anymore.  I've found some articles on the nets that explain how +/- 5-10% performance changes easily occur due to shifts in code alignment.  I'm looking in to potential mitigations for benchmarking.

**Pull request merged**
