### PR TITLE
Add call-back functions for DGKernel

### LINKED ISSUE #17004: Missing some call-backs in DGKernel
## Reason
`DGKernel` is not calling `precalculateResidual`, `precalculateJacobian` and `precalculateOffDiagJacobian`. Also it does not provide `initQpResidual` and few others to allow derived classes to optimize certain calculations.

## Design
Add them in `DGKernel`. Their default will be no-op.

## Impact
New feature.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #17004.

### CODE REVIEW

**Review by loganharbour — COMMENTED** [review]
Why "init<>"? With this, we now have precompute<>, precalculate, and init<>

I'd prefer some consistency if possible

**Comment by YaqiWang** [comment]
`init*` is for qp-wise operations different from `precalculate*`. `init*` has been used in `ArrayKernel`.

**Comment by YaqiWang** [comment]
`precalculate*` is provided by `ResidualObject`.  @loganharbour are you ok with this or having other suggestions? I need this call-backs to refactor some of DG kernels in Griffin.

**Comment by loganharbour** [comment]
Even though we have `init` within ArrayKernel, I think I would still prefer prefixing with precalculate. That way, in the future if we wish to shift it to ResidualObject it'll be consistent.

What are your thoughts?

**Comment by YaqiWang** [comment]
So rename `initQpResidual` with `precalculateQpResidual`? I am ok to do this. Note that we possibly cannot move `precalculateQpResidual` into `ResidualObject` because it may need extra arguments like in `DGKernel`.

**Comment by loganharbour** [comment]
> So rename initQpResidual with precalculateQpResidual? I am ok to do this. 

Yep, that's what I'm thinking. init -> precalculate.

> Note that we possibly cannot move precalculateQpResidual into ResidualObject because it may need extra arguments like in DGKernel.

That's fine if that's the case. I'm just shooting for consistency in general, here.

**Comment by YaqiWang** [comment]
Ok, name chaged.

**Review by loganharbour — APPROVED** [review]

**Comment by YaqiWang** [comment]
Thanks Logan.

**Pull request merged**
