### PR TITLE
Allow convergence on zeroth nl iteration for ReferenceResidualProblem

### PR DESCRIPTION
**Pull request by lindsayad**
I don't understand why the original author made it so that
convergence could not be achieved on the zeroth nl iteration.
This removes once of the principal advantages that I see of
ReferenceResidualProblem in that it can recognize essentially
that we've achieved a steady-state condition and/or that it
doesn't make any sense to keep iterating because the variables
are converged with respect to reference quantities.

### CODE REVIEW

**Comment by lindsayad** [comment]
@bwspenc Do you this why this was the way it was?

**Comment by tophmatthews** [comment]
@bwspenc FYI the command we talked about previously for forcing `N` iterations is `-snes_force_iteration N` (thanks to @fdkong for pointing it out)

@lindsayad there are advantages to force at least one iteration I've found...but I can't reproduce now, and I don't see why this shouldn't be default

**Comment by lindsayad** [comment]
Ah the old beautiful nonlinear iteration count in testing! Terrible! @fdkong

**Comment by fdkong** [comment]
> @bwspenc FYI the command we talked about previously for forcing `N` iterations is `-snes_force_iteration N` (thanks to @fdkong for pointing it out)
> 
> @lindsayad there are advantages to force at least one iteration I've found...but I can't reproduce now, and I don't see why this shouldn't be default

@tophmatthews Maybe some user objects, postprocessors or other things are not evaluated without one iteration? If so, we should actually fix these issues. 

I agree with @lindsayad, we should not let the solver do more work if already converged.

**Review by fdkong — DISMISSED** [review]

**Comment by tophmatthews** [comment]
> @tophmatthews Maybe some user objects, postprocessors or other things are not evaluated without one iteration? If so, we should actually fix these issues.

Yeah, I think you're right...I just need to find where that was happening again so we can test.

**Comment by lindsayad** [comment]
@fdkong can you re-review this?

**Review by fdkong — APPROVED** [review]

**Comment by bwspenc** [comment]
@lindsayad I agree that this is a good change. My guess about why I forced it to take at least one iteration originally was that it was a carry-over from the standard checks that this was based on.

**Pull request merged**
