### PR TITLE
References added to paper

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #14831

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hi moose team, @milljm , could you let my PRs request to merge into the joss_porous_flow branch (Precheck failure):
```
Requests MUST not be direct to the joss_porous_flow branch!
```

**Comment by cpgr** [comment]
Hey Andy, I noticed Permann et al is now published, see #14851

**Comment by permcody** [comment]
@WilkAndy - So unfortunately this whole "check for branch" check is non-trivial to mess with. In the past, the logic was simple, we basically just had CIVET check for a branch that was forbidden so that we as developers wouldn't accidentally merge into the master branch without going through our "devel" branch first. About a year ago we created this "next" branch, which complicated things a bit. We hacked CIVET to allow things to work out for the "next/devel" branches (and also master). 

Now with the current logic, we don't have a good way to allow PRs on arbitrary branches because CIVET is going to use the override logic we put in there and try to merge it against the wrong branch. This is due to our short-sighted hack we put in. You are 100% correct that we are going to need to fix this as when MOOSE is deployed for real end-use, we'll be maintaining releases, which means PRs to release branches for back-ported patches. So I guess thanks for pointing out the current weakness in our software 😉.

Is it safe to assume that you are only going to have a few minor changes to check into this branch? if so, we could just merge your PR even though nothing runs? I'm trying to figure out the best way to move forward without trying to come up with a proper solution in CIVET first.

**Comment by WilkAndy** [comment]
Yea, i think (hope!) that we'll only have small changes to make in paper.md and paper.bib as it is reviewed for JOSS.  What a pain - i'm sorry about all this mucking around - it all sounded so easy in principal!   i'll leave it to you guys to figure out what's best.  We can always just go back to using 'next' for this JOSS stuff, with the caveats that no one else can create a paper.md and paper.bib at the same time as us.

**Pull request merged**
