### PR TITLE
Changed default value of 'normal_tol' in SideSetsFromNormalsGenerator

### PR DESCRIPTION
**Pull request by pbehne**
This PR patches a bug reported by @aprilnovak. When capabilities from several sideset generators were refactored into a base class in #26869, the default value of the parameter controlling the tolerance for comparing normals changed from 1e-5 to 0.1 for the `SideSetsFromNormalsGenerator`. This PR sets the default value of the `normal_tol` parameter to 1e-5 for this generator, preserving the old behavior.

Closes Ref #26252 (for the third time)

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
this looks like a real failure in porous flow, since it s using this mesh generator

**Comment by pbehne** [comment]
Yup, I've verified that the failure is real. The tighter tolerance doesn't capture most of the intended surface. I'll look at the history just before we refactored and see what's going on.

**Comment by pbehne** [comment]
I believe I've found the source of the test failure. Comparing the old and refactored versions of `SideSetsFromNormalsGenerator`, calls to the recursive `flood` method are started from all the same elements.

Look at the changes to `SideSetsGeneratorBase` and `SideSetsFromNormalsGenerator` in #26869. In addition to `normal_tol` (used to be called 'tolerance' in the child class), the base class used to have a parameter called `variance` with default value 0.1. I got rid of that and replaced it with `normal_tol`. However, the old version of NormalsGenerator used `normal_tol` as the comparison tolerance to initiate a flood and `flood` itself used the looser `variance` parameter as a comparison tolerance for recursive calls to `flood`. Is this a behavior we want to revert back to (seems confusing to me), or do we want to update the broken test?

**Comment by GiudGiud** [comment]
can we simply adapt the tolerance in the test and fall back on the same answer?
I doubt we will want to re-gold the test, as this is changing the mesh. Unless you think the current mesh in the gold file is wrong

**Comment by pbehne** [comment]
Yeah, I was thinking of just tweaking the tolerance to get the same result as the old gold file. I just brought up the 2 tolerances in case you could think of a reason to have 2 that I don't know of. Thanks!

**Review by GiudGiud — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
