### PR TITLE
Test imp

### PR DESCRIPTION
**Pull request by andrsd**

### CODE REVIEW

**Comment by friedmud** [comment]
These definitely look like positive changes...

**Comment by friedmud** [comment]
Crap - I'm working on that test now... still no idea why it fails intermittently....

**Comment by permcody** [comment]
Intermittently? It looks like it fails most of the time!

**Comment by friedmud** [comment]
But no one can reproduce it!  I wasn't even able to reproduce it on the damn testing system yesterday!

I'm trying again right now...

**Comment by andrsd** [comment]
I invalidated the result and now it passed :-) Yay to deterministic behavior!

**Comment by permcody** [comment]
Even if MOOSE was always deterministic, invalidating a recipe would NOT be. We always merge into the current devel when running the recipe so the whole thing is sort of loosey goosey.

**Comment by permcody** [comment]
:+1:  - Will merge when Marmot is fixed up. We have a few backlogged in devel already.

**Comment by andrsd** [comment]
> We always merge into the current devel when running the recipe so the whole thing is sort of loosey goosey.

I thought that the branch was tested by itself __before__ it was merged into devel. Thus, invalidating the result and rebuilding the branch should always produce the same result (which in this case did not happen :wink: )

**Comment by permcody** [comment]
This is how it was a long time ago but then we had a failure where the
branch passed during PR testing but failed after it was merged. We decided
after that point to merge it into a new branch to make sure that it would
pass as merged.

**Comment by andrsd** [comment]
Ok, I see.

**Pull request merged**
