### PR TITLE
Fix checking array variables

### LINKED ISSUE #20537: Few places in MOOSE are checking for array variables incorrectly
## Bug Description
We have few places in MOOSE remaining using `var.count() > 1` to check if the variable is an array variable. This used to be fine but not anymore because the number of component can now be one for array variables. This causes one test in Griffin not outputting an array variable with one component properly.

## Steps to Reproduce
Apparent logic error. I will push a fix.

## Impact
A bug can potentially have impact on capabilities using `var.count() > 1`.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #20537.

This PR is expecting to break Griffin because a gold file for a test is wrong due to the bug.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@lindsayad can you review this? It is a small bug fix.

**Review by loganharbour — COMMENTED** [review]
Do we really not have any tests for the one component case in the framework that would diff on this?

**Comment by YaqiWang** [comment]
Based on #19567, we do. Let me check why that test is not diffing...

**Comment by YaqiWang** [comment]
ok, looks like that test has constant monomial array variable, which has a special logic in libMesh `ExodusII_IO::write_element_data` that happened to bypassed this bug. If we change the order to FIRST, we will see the issue. I think the logic in ExodusII_IO possibly needs some work, but here I will just replace the order of that test to first and regold. Note that without this fix, that test will fail with the new gold file.

**Review by loganharbour — APPROVED** [review]
👍🏼 thanks for getting coverage. Zach and I discussed this - unfortunate bug 😆

**Comment by loganharbour** [comment]
@YaqiWang Do you mind making a libmesh issue for this?

**Comment by YaqiWang** [comment]
ok, an issue created here https://github.com/libMesh/libmesh/issues/3189. Once this is merged, I will send in a small patch in Griffin immediately.

**Comment by loganharbour** [comment]
We can coordinate tomorrow for the griffin patch.

**Comment by YaqiWang** [comment]
Can this bug fix be merged?

**Comment by lindsayad** [comment]
@loganharbour may be waiting on https://github.com/idaholab/moose/pull/20558

**Comment by cticenhour** [comment]
Is this ready to go?

**Comment by loganharbour** [comment]
Where's the patch?

**Comment by YaqiWang** [comment]
I was out just got back. The patch will be pushed in a few minutes. Need to compile and verify it.

**Comment by YaqiWang** [comment]
BTW, I have been waiting for a merge for hours. If you did that earlier, I can respond immediately...

**Comment by loganharbour** [comment]
Or if you have it ready we can push the correct submodule hash to your MR. In the future, please just have the MR ready. Thanks

**Comment by YaqiWang** [comment]
Patch is up. Please merge it asap.

**Comment by YaqiWang** [comment]
Note that this is a bug fix, it should take the highest priority (I should have pushed it harder). I do not understand why I have to wait for days on merge such a small bug fix.

**Comment by loganharbour** [comment]
The wait was one business day.

**Pull request merged**
