### PR TITLE
Make solid_mechanics moosedocs check clean

### PR DESCRIPTION
**Pull request by hugary1995**
- Fix all duplicate requirements
- Add all missing issues
- Suppress warnings on stub files
- Suppress warnings on missing design+issue+req

ref #28733

### CODE REVIEW

**Comment by hugary1995** [comment]
This PR also turns warnings into errors for future `log_empty_issues` and `log_duplicate_requirement`. So we are highering, not lowering, the bar for future PRs.

**Review by GiudGiud — DISMISSED** [review]
There is already a module SQA PR open with some of these changes.
I dont think we need to suppress warnings, we just need to fix the underlying problems.

**Comment by hugary1995** [comment]
> I dont think we need to suppress warnings, we just need to fix the underlying problems.

In principle I agree with you. But in this case, many of the test requirements and docs are "non-fixable" any time soon.

**Comment by hugary1995** [comment]
> I dont think we need to suppress warnings, we just need to fix the underlying problems.

I fixed a discrepancy in the default value of `show_warning` for `SQAReport`. I can unsuppress warnings now.

**Comment by hugary1995** [comment]
Sounds like @cticenhour should review the moosedocs related changes: https://github.com/idaholab/moose/pull/28734/commits/5d8ce5367d9d2809556f81c91df05c1c13a83284

**Comment by cticenhour** [comment]
Sorry for the delay here - I honestly forgot about the ping on this PR. 

I am not opposed to the MooseDocs changes. @hugary1995 can you rebase this on devel and restart testing?

**Comment by GiudGiud** [comment]
no my PR has not been reviewed. I can deal with conflicts I'm not worried if your PR gets merged first

**Review by GiudGiud — APPROVED** [review]
FENIX and BC build failures are unrelated and are tied to when the test suite was last run. 
I rebased this PR and accepted the new object descriptions in all but 2 cases thus only contributing trivially

**Pull request merged**
