### PR TITLE
Cleanup PhaseFieldApp.C

### LINKED ISSUE #4771: PhasefieldApp.C needs prettyfication
The includes and register calls should be ordered by type and comments need to be added.

Assign to me.

### PR DESCRIPTION
**Pull request by dschwen**
Delete SPPARKS classes (unused commented out entirely). 
There are VTK tests in `ImageFunction` that give a better error message if the object is build without libmesh VTK support. Removing ifdef from `PhaseFieldApp.C` exposes that message to the user (adapted the test for it).

Closes #4771

P.S.: I have an editor plugin to sort lines alphabetically (I don't have _that_ much spare time to burn on aesthetics).

### CODE REVIEW

**Comment by permcody** [comment]
I like this commit :+1:

**Comment by dschwen** [comment]
What's keeping you from merging it then? ;-)

**Comment by permcody** [comment]
What does Yongfeng have to say about this?

**Comment by dschwen** [comment]
Since when are we asking him? ;-)
Well I talked to him, the SPPARKS stuff he uses its elsewhere.

**Comment by permcody** [comment]
OK

**Pull request merged**
