### PR TITLE
Exterminate FiniteStrainElasticMaterial in TM cleanup

### PR DESCRIPTION
**Pull request by sapitts**
### Design Information

As part of the tensor mechanics clean-up, this commit removes `FiniteStrainElasticMaterial` and the inheriting class `ElementPropertyReadFileTest`.  The functionality offered by these classes was already duplicated by `ComputeFinitStrain`-`ComputeFiniteStrainElasticStress`-`ComputeElasticityTensor` and `ComputeElasticityTensorCP`.
### Test Cases Modified

Within the tensor mechanics folder, the test for the `FiniteStrainElasticMaterial` was removed; the test for the plug-and-play capability retains the functionality testing.  Several other tests were migrated to use the plug-and-play code, including `tensor_mechanics/tests/elem_prop_read_user_object` and `combined/tests/finite_strain_tensor_mechanics_test`.  In migrating the `elem_prop_read_user_object` tests, a stateful variable to verify the input file reader was removed from the test and the gold files.

 Refs #6973

### CODE REVIEW

**Comment by dschwen** [comment]
Woot! 👍

**Comment by dschwen** [comment]
Ok, lets wait until #7083 is merged. Then I'll invalidate this again and merge if it passes.

**Comment by sapitts** [comment]
Oh shoot, I thought #7085 would fix this problem and just rebased.  I'll cancel these tests and wait for #7083

**Comment by sapitts** [comment]
Thanks for 'kicking the tires' by invalidating the tests for this PR

**Pull request merged**
