### PR TITLE
Limit caching in INSFV / FV

### PR DESCRIPTION
**Pull request by GiudGiud**
Refs #18009 

Most INSFV tests will fail rn as face value caching isnt working with two_term_boundary_expansion

### CODE REVIEW

**Comment by GiudGiud** [comment]
This is ready for merge once we understand why it s necessary to cache face gradients when there are 2 extrapolated boundary faces (cylinder tests for example)
Imo the solve should get the same result both times (done twice when not caching)

**Comment by lindsayad** [comment]
Probably also closer to merging when more than 1 test passes 😄

**Comment by lindsayad** [comment]
> This is ready for merge once we understand why it s necessary to cache face gradients when there are 2 extrapolated boundary faces (cylinder tests for example)
> Imo the solve should get the same result both times (done twice when not caching)

Can you give some more detail here? You get exodiffs if you remove the caching?

**Comment by GiudGiud** [comment]
I get exodiffs when I remove the caching of face gradients on the cases with the symmetry BC yeah. It s all variables too

**Comment by GiudGiud** [comment]
precheck's just a hater

**Comment by GiudGiud** [comment]
Test failures are unrelated

**Comment by GiudGiud** [comment]
wat no

**Review by lindsayad — CHANGES_REQUESTED** [review]
So this will completely remove framework level cache coverage, so I think we should add an additional test where we just toggle the caching on and make a symlink in the gold directory to make sure we're getting the same results with and without caching (although I know that since all pre-existing tests are still passing without regolding that that is already the case)

**Comment by lindsayad** [comment]
So if I look at the coverage diff, I see that we never have a cache hit for the face gradient. And that makes sense since we only have one kernel for a given variable that uses a face gradient. Is @grmnptr's input the same situation? Just perusing it, I think it is. So perhaps that explains why not caching the face gradient is faster ... you never re-use the computation and now you're just doing fruitless map `finds`

**Comment by GiudGiud** [comment]
Yeah it s only FVDiffusion using face gradients in my test.
In INSFV we have the pressure face gradient calls (Rhie Chow) that are being cached.

**Comment by lindsayad** [comment]
Top profile is with face gradient caching and the bottom profile without face gradient caching (face value are cached in both profiles). Caching the face gradients overall runtime is 67.59 seconds vs. not caching is 54.48 seconds. The smoking gun to me is the difference in time spent in `std::unordered_map::emplace` with the former spending 13.86 seconds there and the latter spending 4.41 seconds there. 

all-cache
no-fc

**Comment by lindsayad** [comment]
Not face caching
```
(pprof) peek unordered_map::emplace
Showing nodes accounting for 54.48s, 100% of 54.48s total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                             2.46s 55.78% |   MooseVariableFV::getInternalFaceValue (inline)
                                             1.37s 31.07% |   MooseVariableFV::adGradSln (inline)
                                             0.40s  9.07% |   libMesh::DefaultCoupling::operator() (inline)
                                             0.12s  2.72% |   MooseMesh::buildFaceInfo (inline)
                                             0.04s  0.91% |   MooseVariableFV::getDirichletBoundaryFaceValue (inline)
                                             0.02s  0.45% |   libMesh::TopologyMap::add_node (inline)
         0     0%     0%      4.41s  8.09%                | std::unordered_map::emplace
                                             4.41s   100% |   std::_Hashtable::emplace (inline)
----------------------------------------------------------+-------------
```
Face caching
```
(pprof) peek unordered_map::emplace
Showing nodes accounting for 67.59s, 100% of 67.59s total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                             6.48s 46.75% |   MooseVariableFV::adGradSln (inline)
                                             4.40s 31.75% |   MooseVariableFV::uncorrectedAdGradSln (inline)
                                             2.55s 18.40% |   MooseVariableFV::getInternalFaceValue (inline)
                                             0.26s  1.88% |   libMesh::DefaultCoupling::operator() (inline)
                                             0.14s  1.01% |   MooseMesh::buildFaceInfo (inline)
                                             0.02s  0.14% |   libMesh::TopologyMap::add_node (inline)
                                             0.01s 0.072% |   MooseVariableFV::getDirichletBoundaryFaceValue (inline)
         0     0%     0%     13.86s 20.51%                | std::unordered_map::emplace
                                            13.86s   100% |   std::_Hashtable::emplace (inline)
----------------------------------------------------------+-------------
```

**Comment by GiudGiud** [comment]
note that if you want to go further in this analysis, the caching can done differently for pressure and velocity so maybe there s some optimization there. I suspect we just want to turn off caching

**Comment by lindsayad** [comment]
Slower even with INSFV RC. Given these results I would vote to delete the face gradient caching code. @GiudGiud do you want to do that or I can push to this?

### cache face gradients
insfv-all-cache

### don't cache face gradients
insfv-no-fc

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
