### PR TITLE
Set MooseApp type

### LINKED ISSUE #6411: MooseApp _type is not set
### Description of the enhancement or error report
It appears that `MooseApp::_type` is not set anywhere. In turn `MooseApp::type()` returns empty string.

### Rationale for the enhancement or information for reproducing the error
Adding `_type(getParam<std::string>("_type"),` in the constructor header seems fixing the problem, but I am not sure if it is the correct fix.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
We need this to add multiapp in the same app type of the master through actions, which could be invoked by different applications.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #6411.

The second CI could be controversial. But I think it is good.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody the second CI demonstrated what I said.

**Comment by permcody** [comment]
The bigger reason I don't like this is it's inconsistent in the Input file. Almost every block (besides meta-actions) require a "type". Unless you have a compelling reason to change it, I'd rather leave that as a required type.

**Comment by YaqiWang** [comment]
app_type is not type though, for example of a multiapp
```
type = FullSolveMultiApp
app_type = MooseTestApp
```

**Comment by YaqiWang** [comment]
@permcody Any further comments?

**Comment by permcody** [comment]
No, just didn't feel like clicking merge yet. Too many other PRs going
through at the moment.

**Pull request merged**
