### PR TITLE
Friedmud multiapp restart

### PR DESCRIPTION
**Pull request by permcody**
Hopefully this will pass all tests for all applications.

### CODE REVIEW

**Comment by permcody** [comment]
@friedmud and @andrsd, It looks like we finally have a PR working with the fix in BISON and also the adjustment I added to the module restart tests. I'm happy with this. @andrsd, you may want to take one more look and merge.

**Comment by andrsd** [comment]
As far as I can tell, this is good ;-)

**Comment by friedmud** [comment]
Thanks for finishing this off. Feels good to have this in.

Derek

**Comment by permcody** [comment]
Yes, now we can have the physics guys really start using this.

**Pull request merged**
