### PR TITLE
Add scaling vector if we are doing automatic scaling in MooseVariableBase::initialSetup

### LINKED ISSUE #17078: Automatic scaling, multiapp and checkpoint restart issue
## Bug Description
When restarting a simulation with a subapp with autoscaling on both, from a checkpoint ran with autoscaling as well, I m getting 
```*** ERROR ***
Trying to load vector name scaling_factors but that vector doesn't exist in the system.
```

I didn't consistently get this message, as I got on other cases, but hopefully the fix is the same,
```Additional vectors in file do not match system
Stack frames: 14
0: 0   libmesh_opt.0.dylib                 0x0000000104519cdb libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1067
1: 1   libmesh_opt.0.dylib                 0x000000010451689f libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 255
2: 2   libmesh_opt.0.dylib                 0x0000000104b7cd79 void libMesh::System::read_parallel_data<double>(libMesh::Xdr&, bool) + 4825
3: 3   libmesh_opt.0.dylib                 0x0000000104b4d39b void libMesh::EquationSystems::_read_impl<double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool) + 1451
4: 4   libmesh_opt.0.dylib                 0x0000000104b4caf8 void libMesh::EquationSystems::read<double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool) + 40
5: 5   libmesh_opt.0.dylib                 0x0000000104b4ca7b void libMesh::EquationSystems::read<double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, bool) + 171
6: 6   libmoose-opt.0.dylib                0x00000001036c4d33 RestartableDataIO::restartEquationSystemsObject() + 227
7: 7   libmoose-opt.0.dylib                0x0000000103567dfc FEProblemBase::initialSetup() + 2284
8: 8   libmoose-opt.0.dylib                0x00000001032af333 Transient::init() + 1619
9: 9   libmoose-opt.0.dylib                0x0000000103c675bb MooseApp::executeExecutioner() + 75
10: 10  libmoose-opt.0.dylib                0x0000000103c63574 MooseApp::run() + 244
11: 11  sam-opt                             0x0000000102026c5c main + 124
12: 12  libdyld.dylib                       0x00007fff6be09cc9 start + 1
13: 13  ???                                 0x0000000000000003 0x0 + 3
[0] ../src/systems/system_io.C, line 630, compiled Feb 16 2021 at 17:10:48

*********************************************************************
READING THE FILE "/Users/giudgl-mac/projects/FHR_2D_1D_nomods/step2/../step1/FHR-master_out_cp/0010.xdr" FAILED.
It is possible this file contains infinite element information,
but the version string does not contain " with infinite elements"
Let's try this again, but looking for infinite element information...
*********************************************************************
```

## Steps to Reproduce
This requires using a multiapp with automatic scaling
Without a multiapp, the following 4 restart cases work fine:
no scaling -> autoscaling
no scaling -> no scaling
autoscaling -> no scaling
autoscaling -> autoscaling

## Impact
Computational time

### PR DESCRIPTION
**Pull request by lindsayad**
If we have automatic scaling with AD, we need to make sure that we create the `scaling_factors` vector or else we end up trying to read a `scaling_factors` vector that does not yet exist when reading our restartable data.

This maybe closes #17078

### CODE REVIEW

**Comment by loganharbour** [comment]
Hm... I think I recall a WIP parallel module test that failed before because of this. Let me see if I can find it.

**Review by GiudGiud — DISMISSED** [review]
Looks good to me, thanks for fixing this!
One comment would be that the tests are using a single variable so I dont think scaling is doing much for them. Regardless, it still scales the residual, and I checked that those tests fail prior to this PR

We should try to add more documentation for automatic scaling. I could only find two newsletters about it. 
Would it qualify as an executioner subsystem and appear here [https://mooseframework.inl.gov/syntax/Executioner/](https://mooseframework.inl.gov/syntax/Executioner/ ) ?

**Comment by lindsayad** [comment]
I believe I've put most of my automatic scaling documentation thus far here: https://mooseframework.inl.gov/source/systems/NonlinearSystemBase.html

**Comment by lindsayad** [comment]
Lol

**Comment by lindsayad** [comment]
Unfortunately this PR is going to have to wait on https://github.com/libMesh/libmesh/pull/2888

**Comment by lindsayad** [comment]
@GiudGiud it looks like this is finally ready to go

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
