### PR TITLE
Split initial setup Concept

### PR DESCRIPTION
**Pull request by permcody**
refs #5733 

Here's the concept I was going after. This PR doesn't do much except create and call the new Method in the right place. Once we start incorporating #5733 and fixing up the Multiapp initialization this new split may help keep things clean.

### CODE REVIEW

**Comment by permcody** [comment]
@idaholab/moose-developers, what do you think about this change? I'm usually an advocate for avoiding unnecessarily changing long-standing APIs but I think that this change may be warranted. I really think we need to get to a point where we handle the simulation setup (whatever that means) separately from starting the initial execution of parts of the system. The problem is that it may not be possible to have a clean split. For instance, is an initial condition part of setup or initial execution?

The real benefit may come from Multiapp initialization. Right now we basically have to call `initialSetup()` on Multiapps at some point during the master call to `initialSetup()` however that routine recursively calls itself for all Multiapps which executes several objects as each routine completes popping back up to the parent. That means we have a really big mix of initialization at different levels intermixed with execution. Does that really matter? Perhaps not as these applications are more or less independent. However in practice we already see that they are not. Yak is already using Transfer data produced during `initialSetup()` in other objects at the parent level.

If others agree that this is a good change, I'll introduce the split in a non-intrusive way by adding a new empty virtual in MOOSE. I'll then update applications (Yak) to call this new empty virtual. Finally, I'll go back in and introduce another PR to move parts of `initialSetup()` into the newly added method.

**Comment by friedmud** [comment]
Well - I'm all for cleaner code... and we all know how painful it can be to modify `initialSetup()` so it's definitely ripe for a refactor.

However, I suspect that you're going to run into issues.  Some of the issues are non-technical... and just need decisions made...

For instance: Do we want to allow the execution of a Sub-app to get information for setting the initial condition of a Master app?  If so... then MultiApps need to run _before_ initial condition projection!

OR: do we want to allow a Master app to set the initial condition of a sub-app?

We actually have use cases for each of these right now... and they are mutually exclusive.  We could add more `execute_on` options (`before_initial`?) but holy hell...

BUT: I'm all for you doing whatever you can to make it better!

**Comment by andrsd** [comment]
Time for a DAG? :smiling_imp:

**Comment by permcody** [comment]
Yuck, Yak is a total failure with this concept. I really don't want to fight with it right now as much as I'd like to see it cleaned up.

**Comment by friedmud** [comment]
Yep

To do this right would take cross-system dependency resolution... AKA DAG
;-)

**Pull request closed without merging**
