### PR TITLE
Geochemistry: use static to fix threading problem

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #16100

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hi @loganharbour .   I'm hoping you can carefully consider these changes and see whether you think they're an appropriate solution to the threading problem

**Comment by loganharbour** [comment]
Are you ever going to have multiple `GeochemistrySpatialReactor` objects?

**Comment by WilkAndy** [comment]
> Are you ever going to have multiple `GeochemistrySpatialReactor` objects?

Yea, good question.  I think it is unlikely, or maybe impossible, that a GeochemistrySpatialReactor will appear more than once in an input file.   If you can think of a better design, that would allow GSR to be block restricted, etc, please tell me.  Cody mentioned the use of a map, but i didn't understand what he meant.

I think it's unlikely, but not impossible, that an input file containing a GSR called another input file containing another GSR via a MultiApp.  Would this fail due to the `static` thing?

**Comment by loganharbour** [comment]
> I think it's unlikely, but not impossible, that an input file containing a GSR called another input file containing another GSR via a MultiApp. Would this fail due to the static thing?

Yes - this could definitely be an issue. If you're available and working right now, I'm available to discuss this over voice/video chat, which may be a bit easier. Shoot me an e-mail if you're available, or if not we can find another time to chat.

**Comment by WilkAndy** [comment]
> > I think it's unlikely, but not impossible, that an input file containing a GSR called another input file containing another GSR via a MultiApp. Would this fail due to the static thing?
> 
> Yes - this could definitely be an issue. If you're available and working right now, I'm available to discuss this over voice/video chat, which may be a bit easier. Shoot me an e-mail if you're available, or if not we can find another time to chat.

yep, i'm around

**Comment by loganharbour** [comment]
```
    std::vector<GeochemistrySpatialReactor *> objects;
    theWarehouse()
        .query()
        .condition<AttribSystem>("UserObject")
        .condition<AttribThread>(0)
        .condition<AttribName>(name())
        .queryInto(objects);
```

You will probably need to `#include "TheWarehouse.h` for this. This will get a UserObject, on thread 0, with the same name as the current UserObject that is calling it (this is why we use `name()`).

I would make sure that `objects.size() == 1`, which means that you found one and exactly one object with the requested attributes. Your thread 0 user object will then be located at objects[0]

**Comment by WilkAndy** [comment]
> ```
>     std::vector<GeochemistrySpatialReactor *> objects;
>     _fe_problem.theWarehouse()
>         .query()
>         .condition<AttribSystem>("UserObject")
>         .condition<AttribThread>(0)
>         .condition<AttribName>(name())
>         .queryInto(objects);
> ```
> 
> You will probably need to `#include "TheWarehouse.h` for this. This will get a UserObject, on thread 0, with the same name as the current UserObject that is calling it (this is why we use `name()`).
> 
> I would make sure that `objects.size() == 1`, which means that you found one and exactly one object with the requested attributes. Your thread 0 user object will then be located at objects[0]

Great, thanks @loganharbour .    I'll give that a bash today/tomorrow.

**Comment by WilkAndy** [comment]
> std::vector<GeochemistrySpatialReactor *> objects;
>     _fe_problem.theWarehouse()
>         .query()
>         .condition<AttribSystem>("UserObject")
>         .condition<AttribThread>(0)
>         .condition<AttribName>(name())
>         .queryInto(objects);

Bummer, this doesn't work because `finalize()` only gets called for thread 0.

**Comment by WilkAndy** [comment]
```
BUILD_ROOT/moose/: git pull git@github.com:WilkAndy/moose.git explore_threading_problem_16100
ssh: connect to host github.com port 22: Connection timed out
```

**Comment by loganharbour** [comment]
@WilkAndy CIVET is down for the night, unfortunately.

I'll work on other ideas for this issue tomorrow.

**Comment by WilkAndy** [comment]
Thanks.  I'm quite thrilled that we've got a fix, even if it does involve lots of copying.

**Comment by WilkAndy** [comment]
Cool, this code seems to work!

**Comment by WilkAndy** [comment]
Hey, @loganharbour , just in case you were going to merge this - just let me "squash" the two commits together and remove the
```
/// Copy of ModelGeochemicalDatabase without any user-defined swaps
  const ModelGeochemicalDatabase _mgd_no_swaps;
```
member, since it was only needed for the static stuff.

**Comment by WilkAndy** [comment]
Reminding you about this threading thing, @loganharbour

**Review by loganharbour — DISMISSED** [review]

**Comment by loganharbour** [comment]
Wasn't there another failing test that isn't in the default tests for PRs? If so, I'd like to run that here before merging

**Comment by WilkAndy** [comment]
> Wasn't there another failing test that isn't in the default tests for PRs? If so, I'd like to run that here before merging

No, this PR activates all tests.  Let me squash the commits before merging - will do that in an hour or so.

**Comment by loganharbour** [comment]
Sounds good! Just ping me when ready.

**Comment by WilkAndy** [comment]
Thanks @loganharbour  - this is all green and ready for merge, i believe

**Review by loganharbour — APPROVED** [review]

**Comment by WilkAndy** [comment]
I'm so pleased this is fixed.  Thanks for your help, @loganharbour .

**Pull request merged**
