### PR TITLE
report number active elements to console instead of total

### LINKED ISSUE #8384: Report active elements instead of total elements in framework info
### Description of the enhancement or error report

We are reporting total elements instead of active elements which is not the best measure.

### Rationale for the enhancement or information for reproducing the error

This came up in an email thread:
https://groups.google.com/d/msgid/moose-users/CABk6%3D%2BaUGhrRae2n7qzE%3DhBbvGNJj1H3_Ni_%2BwP2HGHUBZEg0w%40mail.gmail.com

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

The number of elements reported can be misleading.

### PR DESCRIPTION
**Pull request by rwcarlsen**
fixes #8384

### CODE REVIEW

**Comment by permcody** [comment]
Will you do a quick search of these methods in the framework and see if we are using the "wrong" one anywhere else? Perhaps in the `meshChanged()` printout?

**Comment by rwcarlsen** [comment]
``grep --recursive -C20 '<<' . | grep 'n_\(local_\)*elem('`` only turned up those two lines.

**Comment by YaqiWang** [comment]
Also active nodes!

**Comment by YaqiWang** [comment]
Well, sorry, mesh refinement does not make existing nodes inactive, so we are fine on reporting the number of nodes.

**Comment by jessecarterMOOSE** [comment]
Looks good to me!

**Review by permcody — APPROVED** [review]

**Pull request merged**
