### PR TITLE
Remove deprecated legacy_return_mapping option

### LINKED ISSUE #11693: Remove `legacy_return_mapping` option for return mapping iterations
## Rationale

During the process of overhauling the return mapping iterations used by radial return material models, an option called `legacy_return_mapping` was added to preserve the old behavior to aid in the migration process. Deprecate and then remove that option.

## Description

All use of this option has now been removed from Bison. With a few refinements of the new return mapping procedure that have occurred since its original commit (see issue #6873), the cases that previously needed that option no longer need it.

## Impact

We will need to remove the use of this option from a few remaining tests in the MOOSE modules tests, deprecate the option, and remove it from `SingleVariableReturnMappingSolution.C'. There is also a small amount of code in some classes that derive from that class.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #11693

### CODE REVIEW

**Review by dschwen — DISMISSED** [review]
Looks good to me :+1:

**Comment by bwspenc** [comment]
Rather than going through the incompatible API process, I just submitted a Bison PR that once merged will allow Bison to build cleanly against this code.

**Comment by bwspenc** [comment]
@dschwen Now that the Bison PR has gone in, this passes all the tests, so it should be good to merge.

**Comment by permcody** [comment]
I think we'd better hold of merging this for right now since we currently have a pretty broken devel branch. We'll get this in once everything else gets cleared through.

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Just a friendly reminder that sabertooth and blue_crab need to get updated

**Pull request merged**
