### PR TITLE
Add a python clobber script

### LINKED ISSUE #8952: make clean/clobber is unreliable
### Description of the enhancement or error report

The clean and clobber targets are both partially broken in MOOSE.
`clean` currently doesn't remove contrib object files or libraries.
`clobber` still uses find with `-depth` and `-prune` which isn't portable.
This means that there are several situations which require the use of `git clean` to solve a particular build problem.

Solution:
`clean` should also delete contrib files
`clobber` should be replaced by a python script using `os.walk()` which we use extensively in the TestHarness and also in scripts like this one:
https://github.com/idaholab/moose/blob/devel/framework/scripts/fixup_headers.py

### Rationale for the enhancement or information for reproducing the error

Run the clean and clobber "make" targets, especially after a system upgrade.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Low: Improved ability to clean up object files.

### PR DESCRIPTION
**Pull request by brianmoose**
Call a python script when doing `make clobber` instead of the non portable find command.
Also added some contrib objects and libraries to the `make clean`

closes #8952

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]
I'll pull your branch and give this a try...

**Comment by jwpeterson** [comment]
I tested this by running "make clobber" followed by "git clean -nfxd" to see if there was anything the clobber script might have missed that "git clean" would try to delete. I got:

In framework:
```
Would remove contrib/exodiff/exodiff
Would remove include/base/MooseRevision.h
```

In modules:
```
Would remove contact/include/base/ContactRevision.h
Would remove contact/lib/
Would remove heat_conduction/include/base/HeatConductionRevision.h
Would remove heat_conduction/lib/
Would remove misc/include/base/MiscRevision.h
Would remove misc/lib/
Would remove phase_field/include/base/PhaseFieldRevision.h
Would remove phase_field/lib/
Would remove solid_mechanics/include/base/SolidMechanicsRevision.h
Would remove solid_mechanics/lib/
Would remove solid_mechanics/plugins/creep-opt.plugin.dSYM/
Would remove solid_mechanics/plugins/creep_usr_creep-opt.plugin.dSYM/
Would remove solid_mechanics/plugins/elastic-opt.plugin.dSYM/
Would remove solid_mechanics/plugins/linear_strain_hardening-opt.plugin.dSYM/
Would remove solid_mechanics/plugins/swelling-opt.plugin.dSYM/
Would remove tensor_mechanics/include/base/TensorMechanicsRevision.h
Would remove tensor_mechanics/lib/
Would remove water_steam_eos/include/base/WaterSteamEosRevision.h
Would remove water_steam_eos/lib/
Would remove xfem/include/base/XfemRevision.h
Would remove xfem/lib/
```

So I think we should definitely add "*.dSYM" and possibly "lib/" to the list of stuff being clobbered. Not sure about the various "FooRevision.h" as that might be tough to do correctly/safely?

**Comment by brianmoose** [comment]
I will add the `*.dSYM`. I am a little worried about `lib/` though as that is a rather common directory name.

**Comment by jwpeterson** [comment]
:+1: Thanks for adding `-n` option.

**Pull request merged**
