### PR TITLE
Restore libmesh logic for normal computation.

### PR DESCRIPTION
**Pull request by grmnptr**
Refs #20991 and #24652 

For meshes coming from Cubit the changed version was not accurate enough which lead to weird conservation-related issues.

### CODE REVIEW

**Review by lindsayad — APPROVED** [review]

**Comment by GiudGiud** [comment]
> For meshes coming from Cubit the changed version was not accurate enough which lead to weird conservation-related issues.

Can you add more about this?
What exactly is different? Are the side sets not consistently oriented? Should we fixing that instead?

**Comment by loganharbour** [comment]
> > For meshes coming from Cubit the changed version was not accurate enough which lead to weird conservation-related issues.
> 
> Can you add more about this? What exactly is different? Are the side sets not consistently oriented? Should we fixing that instead?

Has nothing to do with Cubit. The 2D sides that uncovered this issue are likely slightly non planar, in which case this normal computation is not valid.

IMO - as I've told Peter - we should just rely on libmesh here anyway. This isn't expensive as it's cached up front, so doing it like this should be fine.

**Comment by loganharbour** [comment]
We should definitely have a test case with non-planar sides though, which I think @grmnptr plans on working on in the morn (once he confirms our suspicion).

**Comment by lindsayad** [comment]
since this has been labeled as Do Not Merge I am going to convert this to draft

**Comment by grmnptr** [comment]
Based on my short investigation, we indeed have non-planar surfaces in the 3D mesh coming from cubit.

```
Assertion `face->has_affine_map()' failed
Non-planar face detected at: (x,y,z)=(  1.3193, 0.610252, -0.00919595)
at /Users/germp/projects/moose/framework/src/mesh/FaceInfo.C, line 42
```

In 3D I relied on the cross product of the face edge vectors to compute the normal which is not consistent if the face is not planar. Also, following libmesh for mesh operations feel much safer after this. I don't remember exactly why I switched a year ago, maybe it was because of my lack of understanding of libmesh.

**Comment by grmnptr** [comment]
Added a new issue for this bug: #24652 for future reference

**Pull request merged**
