### PR TITLE
Discontinuous exodus

### PR DESCRIPTION
**Pull request by kevindugan**
This pull request introduces the ability to output discontinuous data to Exodus. References #2716.

### CODE REVIEW

**Comment by kevindugan** [comment]
So it looks like the failed tests from the last commit (7f003ba) are failing due to the implementation in Libmesh. I'm putting together some changes that will fix the discontinuous output in Libmesh. However, this pull request will need to be delayed until the Libmesh submodule is updated in MOOSE.

**Comment by permcody** [comment]
If you need this sooner we can leave the ticket open and restrict the test to run only in replicated mode. However, it's been over a month since the last libMesh update so perhaps we can get your fix in, tested and perform an update this week. Thanks for all your effort on this, nice enhancement!

**Comment by kevindugan** [comment]
@permcody I don't currently depend on this functionality in my app yet. I've connected directly to the Libmesh interface instead and was planning to refactor my app once this was incorporated in MOOSE. I'm fine with waiting to merge these changes until the next Libmesh update since I already have this functionality through another route.

I'm testing the necessary changes to Libmesh currently and hope to have a pull request open by the end of today or tomorrow.

**Comment by permcody** [comment]
Past the 30-day limit, but am keeping open. We will do a libMesh update next week.

**Comment by kevindugan** [comment]
> We will do a libMesh update next week.

Sounds Great. I'll be looking for it.

**Comment by jwpeterson** [comment]
@permcody I thought you said this PR was failing some test? Looks like it is all passing to me... I will merge unless there is still something not working.

**Review by jwpeterson — APPROVED** [review]

**Comment by jwpeterson** [comment]
Just tested locally as well and it seems to be working fine.

**Pull request merged**
