### PR TITLE
Add missing elements of SQA templates for  level set

### PR DESCRIPTION
**Pull request by jiangwen84**
#15968

### CODE REVIEW

**Comment by cticenhour** [comment]
Thanks @jiangwen84 - will get a review in for this tomorrow. Had to invalidate testing since a lot of the failures seemed to be due to the GitHub issues earlier.

**Review by cticenhour — CHANGES_REQUESTED** [review]
Minor changes here. Thanks for doing this! The only real thing I think we'll need to address in Level Set moving forward are the wording of the requirements, but unless you want to tackle those as part of this PR, we can move forward with what we have here.

**Comment by cticenhour** [comment]
@jiangwen84 Friendly reminder to look over my review for this. Hopefully we can get this merged in this week!

**Comment by jiangwen84** [comment]
@cticenhour thanks for your suggestions. They all look good to me. Is there anything we need to improve for this PR?

**Comment by cticenhour** [comment]
No, this looks ready to merge. Thank you for your help with this!

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
