### PR TITLE
Add a 2D test for block restricted DG kernels and some code cleanups

### LINKED ISSUE #8357: Allow block restriction of user objects used in RDG module
### Description of the enhancement or error report

I'm currently simulating molten salt reactors with multiple regions; only one region contains advecting material and consequently the RDG user_objects should be restricted to that block (otherwise I'll get issues like the following):

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff543fe11 in MooseVariable::getElementalValue (this=0x9818f0, elem=0x8bd010, idx=0)
    at /home/lindsayad/projects/moose/framework/src/base/MooseVariable.C:1716
1716	  return (*_sys.currentSolution())(dof_indices[idx]);
(gdb) up
#1  0x00007ffff6ffa342 in AEFVSlopeLimitingOneD::limitElementSlope (this=0x9a92d0)
    at /home/lindsayad/projects/moose/modules/rdg/src/userobjects/AEFVSlopeLimitingOneD.C:103
103	      ucell[in][0] = _u->getElementalValue(neig);
(gdb) p neig->centroid()
$1 = {<libMesh::TypeVector<double>> = {**_coords = {2.1053472222221346, 5.7499999999949196, 0}**}, <No data fields>}
(gdb) bt
#0  0x00007ffff543fe11 in MooseVariable::getElementalValue (this=0x9818f0, elem=0x8bd010, idx=0)
    at /home/lindsayad/projects/moose/framework/src/base/MooseVariable.C:1716
#1  0x00007ffff6ffa342 in AEFVSlopeLimitingOneD::limitElementSlope (this=0x9a92d0)
    at /home/lindsayad/projects/moose/modules/rdg/src/userobjects/AEFVSlopeLimitingOneD.C:103
#2  0x00007ffff700e1b3 in SlopeLimitingBase::computeElement (this=0x9a92d0)
    at /home/lindsayad/projects/moose/modules/rdg/src/userobjects/SlopeLimitingBase.C:82
#3  0x00007ffff6feefc6 in ElementLoopUserObject::onElement (this=0x9a92d0, elem=0x8d0120)
    at /home/lindsayad/projects/moose/modules/rdg/src/userobjects/ElementLoopUserObject.C:145
#4  0x00007ffff6feebfd in ElementLoopUserObject::execute (this=0x9a92d0)
    at /home/lindsayad/projects/moose/modules/rdg/src/userobjects/ElementLoopUserObject.C:94
#5  0x00007ffff549cff9 in FEProblemBase::computeUserObjects (this=0x941660, type=@0x7fffffffc464: EXEC_LINEAR, 
    group=@0x7fffffffc460: Moose::POST_AUX) at /home/lindsayad/projects/moose/framework/src/base/FEProblemBase.C:2590
```
where the element which causes the error is outside the region where my advecting variable exists.

### Identified impact
Would allow users to perform coupled simulations in which the advection physics modeled by RDG are limited to a sub-set of the problem's blocks.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #8357.

### CODE REVIEW

**Comment by YaqiWang** [comment]
I think Convection is more accepted terminology. If not, the third commit can be removed.

**Comment by lindsayad** [comment]
@YaqiWang I think you have the wrong issue referenced here. #8357 is for user objects in the RDG module, not dg_kernels. Maybe you just want to refer to your original issue #7603 and perhaps rename that issue to "Add 2D test of DGKernel block restriction" or something like that?

**Comment by YaqiWang** [comment]
Ah, right! Let me change it.

**Comment by YaqiWang** [comment]
I also better change my branch name, so have to close this one.

**Pull request closed without merging**
