### PR TITLE
Cosserat version of capped weak-plane plasticity

### LINKED ISSUE #8431: Add ComputeCappedWeakPlaneCosseratStress to tensor_mechanics
### Description of the enhancement or error report

This extends ComputeCappedWeakPlaneStress to the Cosserat case.  It is a fairly trivial extension because the Cosserat moment stress tensor does not enter the plasticity model, so the Cosserat part is purely elastic.   All that is required is to use the stress_02 and stress_12 components in the computation of "q", rather than the symmetric 0.5*(stress_02 + stress_20), and only let those components return, and enter the consistent tangent operator.

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #8431

### CODE REVIEW

**Comment by WilkAndy** [comment]
Unrelated heavy-test failure (pinging @gambka )

combined:sliding_block/sliding/constraint.frictional_mu02_penalty

**Comment by gambka** [comment]
@WilkAndy I think I've tracked down what is going on here.  There was a change to ensure contact is run on initialization here: #8452. 

In the exodiff showing on Civet for this test the penetration variable is differing on initialization otherwise everything else is the same.  Thus, in my opinion the test just needs to be regolded based on the update to contact being run on initialization.

**Comment by WilkAndy** [comment]
OK, cool, thanks @gambka .  Do you think you could put in a PR that does this regolding.  I can't because that particular test fails quite badly on my system (with different compiler, different petsc, etc).  Eg:

 --------- Time step 12, 1.0950000e+01 ~ 1.0875000e+01, rel diff:  6.84932e-03 (FAILED)
 Global variables:
    contact_pressure  rel diff:  1.0075000e+04 ~  1.0541589e+04 = 4.42617e-02 (FAILED)
    nonlinear_its     rel diff:  4.0000000e+00 ~  3.0000000e+00 = 2.50000e-01 (FAILED)
    penetration       rel diff:  1.9798586e-04 ~ -6.1110394e-04 = 1.32398e+00 (FAILED)

and similarly for the other timesteps

**Comment by gambka** [comment]
@WilkAndy I'm trying to get my machine up to date with the latest that the build system has. I was noticing similar differences that you are observing locally. Once I get that I can regold the system.  Perhaps one of the MOOSE guys can invalidate the test while I do that so your stuff can be merged.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Heavy test failure is due to unrelated PR #8452.

**Comment by WilkAndy** [comment]
OK, thanks @permcody, and good luck @gambka !

a

**Pull request merged**
