### PR TITLE
Update fluid properties method names

### LINKED ISSUE #12862: Standardise remaining method names in Fluid Properties
## Rationale

The method name convention in the fluid properties app is 
```
rho_from_p_T(p,  T)
rho_from_p_T(p, T, rho, drho_dp, drho_dT)
```
etc. But there are some older methods still around named like `rho_mu_dpT` etc that should be renamed to match the current convention.

## Description

Deprecate the old method names and replace them in the code with updated method names.

## Impact

I think that these old names are mainly being used in the porous flow module, so it shouldn't break anything else

### PR DESCRIPTION
**Pull request by cpgr**
Deprecate the old names and update code to use new method names

Closes #12862

### CODE REVIEW

**Review by andrsd — APPROVED** [review]
Thanks for helping with this @cpgr :+1:

**Comment by cpgr** [comment]
No worries!

I did notice a couple of things when I was doing this:

- SodiumProperties: this should probably be SodiumFluidProperties to follow the usual name convention, and it doesn't inherit from SinglePhaseFluidProperties, so can't be used in the normal way
- HEMFluidProperties still has some methods like `dp_duv` instead of `p_from_u_v` etc

I didn't change these as I assume that this would break some of the private apps that I can't see.

**Comment by andrsd** [comment]
> SodiumProperties:

This is kind of one off thing that is used in one of our internal apps. Any changes will break it and you won't be able to fix it.  We recently developed sodium properties that are using `SinglePhaseFluidProperties` as a base class. So maybe we need to use the internal stuff together and drop this one. As you noticed, the methods are functions of only one variable, rather than 2 as we have it in `SinglePhaseFluidProperties`.

> HEMFluidProperties

If you change it, keep the old API in, so it won't break our internal apps. We can remove the old API after the apps are patched.


Just FYI.

**Comment by cpgr** [comment]
I won't change these, just wanted to bring them to your attention in case you didn't know (but I should have know that you would know already! )

**Pull request merged**
