### PR TITLE
MOOSE documentation system

### PR DESCRIPTION
**Pull request by aeslaughter**
This moves custom mkdocs stuff into MOOSE thus we can rely on the current version (soon) of mkdocs to build the documentation.

I have one PR in mkdocs that this requires, but it looks like it will be merged soon: https://github.com/mkdocs/mkdocs/pull/997

(refs #6699)

### CODE REVIEW

**Comment by aeslaughter** [comment]
My PR was merged into [mkdocs](mkdocs/mkdocs#997), so this is now ready to go.

**Comment by dschwen** [comment]
So, do we need to wait for an mkdocs release (so it gets updated in pip)?

**Comment by aeslaughter** [comment]
@dschwen No, you can just install the development version, I have instructions for doing that. They will be available after this is merged and I get civet building it, hopefully today.

**Comment by aeslaughter** [comment]
Sorry if anyone was looking at this, I just noticed that I forgot to push the rebased version and just did.

**Comment by dschwen** [comment]
When building the docs I see stuff like `moose/modules/phase_field/docs/details/XFEM/EBSDReader.md`

I do not understand what the `XFEM` is doing in the path.

**Comment by dschwen** [comment]
`./moosedocs.py generate` craps out with 

```
ERROR: file not found: /Users/schwd/Programs/moose/docs/None
ERROR: Error building page None
```

**Comment by aeslaughter** [comment]
Line 94:
https://github.com/idaholab/moose/blob/devel/modules/xfem/src/base/XFEMApp.C#94

**Comment by aeslaughter** [comment]
You will need to hide this syntax with the "hide" option in the phase_field
section in the moosedocs.yml configuration.

**Comment by aeslaughter** [comment]
@dschwen Try this now, I think I fixed the bug you found. If I did you can mark this as ready-to-merge.

**Comment by dschwen** [comment]
Thanks, looks much better now!

**Comment by dschwen** [comment]
I'd really like to see this merged and the next few weeks declared as a test period where breaking changes may be made. But we need to start doing some actual documentation work with this to discover the rough edges.

**Comment by aeslaughter** [comment]
@dschwen That is my intent as well.

**Comment by tonkmr** [comment]
I would like to see this merged as well. I will start using it right away during the test period.

**Pull request merged**
