### PR TITLE
Coal mining example added to TensorMechanics 

### LINKED ISSUE #9308: Add mining example to TensorMechanics
### Description of the enhancement or error report

Add an example to TensorMechanics that shows how it can be used for simulation of mining.  Just a simple 2D example.

### Rationale for the enhancement or information for reproducing the error

This will help my colleagues who are following in my MOOSE footsteps and it will demonstrate some aspects of TensorMechanics that are useful for modelling geomaterials.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Example only

### PR DESCRIPTION
**Pull request by dschwen**
Closes #9308
Replaces #9309

### CODE REVIEW

**Comment by WilkAndy** [comment]
Any idea why Bison is failing because of this "coal mining example", @dschwen ?

**Comment by dschwen** [comment]
Unrelated

**Comment by WilkAndy** [comment]
OK, strange that no other PR has this failure (that i could see) and that it continued to fail even after i invalidated it.

**Comment by WilkAndy** [comment]
I'll leave it to you to fix, ok?

**Comment by dschwen** [comment]
Bison was broken two days ago. We'll fix it on Monday.

**Review by permcody — APPROVED** [review]

**Pull request merged**
