### PR TITLE
Updated 2/3D-RZ_finiteStrain_test.i, issue #5584.

### LINKED ISSUE #5584: Modify tensor mechanics 2/3D-RZ_finiteStrain_test
Changing dt and application of PressureTM BC for:
2D-RZ_finiteStrain_test.i
3D-RZ_finiteStrain_test.i
located in modules/tensor_mechanics/tests/2D_geometries

### PR DESCRIPTION
**Pull request by waxmanr**
Reduced dt to correct for errors with large dt.
For PressureTM BC, changed 'factor' to 'function'.
Copied new output to /gold folder.
[done for both 2D-RZ and 3D-RZ_finiteStrain_test.i
Closes #5584

### CODE REVIEW

**Comment by andrsd** [comment]
You need to say `Refs #5584` in your commit message, or `Closes #5584` if this closes the issue.

Use `git commit --amend` to fix your commit message and then force-push your branch (by adding `-f` to the push command you did before) to re-trigger the build system.

**Comment by dschwen** [comment]
Actually she just has to add a ```#``` in front of the issue number. The Closes #5584 goes in the description test for the issue (the first comment).

**Comment by permcody** [comment]
:+1: - @dschwen please reveiw and merge

**Comment by dschwen** [comment]
@sveerara please not that the inputs in this PR use the PressureTM BC which you will rename and move into misc/mechanics_transition. Make sure you rebase your branch and fix all merge conflicts.

**Pull request merged**
