### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### idaholab/moose now has a Chat Room on Gitter

@friedmud has just created a chat room. You can visit it here: [https://gitter.im/idaholab/moose](https://gitter.im/idaholab/moose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/idaholab/moose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by permcody** [comment]
I don't think I want this badge in our Readme. I'd rather keep user conversations on the list.

**Comment by dschwen** [comment]
But it would make us look Web 2.0 cool...

**Comment by mangerij** [comment]
That's pretty cool. I like how it supports TeX. Is it possible to have a separate chat room for users and separate one for devel?

**Comment by permcody** [comment]
It certainly is possible to have separate rooms. I'm just not sure if we can support a chat room for support with any expectation of it being "interactive". There are already internal users that contact me on chat for support it's its incredibly disruptive. I wish we had a full-time support guy for MOOSE. We actually technically don't have _any_ funding for support for MOOSE. Odd huh?

**Comment by dschwen** [comment]
> There are already internal users that contact me on chat for support it's its incredibly disruptive.

Not to name any names...

**Comment by friedmud** [comment]
I agree about doing chat support: no time for that.  Gitter should be for MOOSE developers (i.e., people submitting PRs to MOOSE).  The public channel should be for anyone submitting PRs... private for internal discussions about the framework.

I also agree that we need a full-time support person at this point.  The problem is: anyone qualified to do that job is MUCH more valuable coding!

**Comment by permcody** [comment]
OK - closing this for now.

**Comment by friedmud** [comment]
Yeah - I didn't submit this on purpose.  It was just part of the "process" of creating a new channel.

**Pull request closed without merging**
