### PR TITLE
Libmesh update 20241120

### PR DESCRIPTION
**Pull request by roystgnr**
The first commit here is cherry-picked from #28954 to try to avoid conflicts there later.

Update libMesh submodule:
    
- Added `MeshBase::elem_orders()`, `MeshBase::max_nodal_order()`, etc. APIs.  This will soon allow middleware code to do additional sanity checking of user variable order choices, or to automatically choose an isoparametric variable order when appropriate.
- Added triangularization and tetrahedralization support to `meshtool` app.
- Added the ability to condense out "element-internal" degrees of freedom when building algebraic systems.  This gives smaller algebraic systems to solve, without "bubble function" coefficients in continuous FEM methods or internal degrees of freedom in HDG methods.
- Added `NonManifoldGhostingFunctor` class, which can be used to give reliable distributed-mesh connectivity on meshes where multiple edge elements meet at the same point and/or multiple face elements meet along the same edge.
- Added `SidesToElemMap` class, for caching that "reverse connectivity" in classes like the `NonManifoldGhostingFunctor` that use it.
- Generalized `MeshFunction::find_element()` allowing evaluation of a `MeshFunction` on algebraically-ghosted elements when a `GHOSTED` vector is in use.
- Added `SimplexRefiner` class, which currently supports refinement of simplicial (edge, triangle, and/or tetrahedral) meshes via edge bisection.
- Exit with error when asked to evaluate `L2_HIERARCHIC` bases of polynomial degree `p=0`.  Previously this case was returning an incomplete basis that would deliver suboptimal convergence.
- Use more accurate projections when decimating solutions on `H_DIV` finite elements for visualization output.
- Added `--with-xdr-libdir` option to `configure`, making it possible to build libMesh with XDR support using more types of third-party library installations.
- Better `configure --help` entries for NetCDF options
- Fixes for `make check` NetCDF tests when combining older NetCDF with newer HDF5
- Support for distributed-and-unprepared meshes in `all_tri()`
- Compatibility fixes for PETSc 3.23
- Support for adding a prefix when querying a `PetscNonlinearSolver::snes()` that might have yet to be initialized
- Fixes in Reduced Basis EIM code

### CODE REVIEW

**Comment by roystgnr** [comment]
Force-pushed on top of the current devel; apparently the pull I did previously was *right* before #28817 made it in.

**Comment by loganharbour** [comment]
Added the extra recipes for you ;)

**Comment by roystgnr** [comment]
Yeah, I noticed; right after I rebased and force-pushed I remembered to add them myself but discovered they were already added.

I was a bit confused at that discovery, though.  "Logan's the one who's always on top of that, but surely he wouldn't do it without poking fun at me about it again, right?", I thought.  I worried you had simply given up and started taking cues from dementia-care pamphlets.  "Don't actually *argue* with Grandpa about how he forgot to take his pills again this morning, just crush them up and put them in his applesauce and distract him while he eats."

**Comment by roystgnr** [comment]
Did I mess up something in the conda updates?

```
The following package could not be installed
└─ moose-petsc 3.22.1.193.g72c1e49ee3d mpich_0 does not exist (perhaps a typo or a missing channel)
```

**Comment by loganharbour** [comment]
> Don't actually argue with Grandpa about how he forgot to take his pills again this morning, just crush them up and put them in his applesauce and distract him while he eats."

Damn, I shouldn't have said anything.

> Did I mess up something in the conda updates?

This is just because you rebased on next and the conda package hadn't made it through master. Good now.

Another conflict though, unfortunately.

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
Wait to see if @milljm wants to do any conda testing before merging please

**Pull request merged**
