### PR TITLE
Only load vectors that exist after restart

### LINKED ISSUE #17444: Do not load vectors in restart that do not exist in the restarting app
## Reason
The error [here](https://github.com/idaholab/moose/blob/bd1b9a8df489d1009329899fe8f01c2b51b21164/framework/src/systems/SystemBase.C) is overzealous and I think unneeded. Say the vector A exists in the problem that is storing there start, but said vector does not exist in the problem that is being restarted. If we don't need A in the problem that is being restarted - that's fine, just ignore it.

@pbalest came across this issue. The problem storing the checkpoint obtains a steady state, and in the process stores an older solution (which by default, is not allocated as of #16363). The problem that uses this checkpoint does not need an older solution, therefore it does not have the state 2 (older) solution in its system. This will trigger the error linked in the first sentence.

## Design
Remove the error.

## Impact
Should enhance restart capability.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #17444 

@lindsayad you're the one that put this error in - read the associated issue for more info.

### CODE REVIEW

**Comment by lindsayad** [comment]
It's fine to discard the unnecessary vector instead of erroring, but you will need to load it somehow or else you are going to risk data corruption which was the issue that prompted me installing the error: see https://github.com/idaholab/moose/issues/15333#issuecomment-657754985. For example if you just "skip" this unnecessary vector, then you're not really skipping it all are you? The next time you actually do read a vector, you're actually going to read the vector entries corresponding to the vector you "skipped."

**Comment by lindsayad** [comment]
I also think we should remove the error, but discarding the vector may or may not be the right thing to do. See my comment here https://github.com/idaholab/moose/pull/17399#issuecomment-806089173

**Comment by loganharbour** [comment]
Hmm. So would you prefer to create it?

**Comment by lindsayad** [comment]
I think I would prefer to create it and potentially provide some option in `FEProblemBase` for turning off the behavior for our application developers/users who are very sensitive about memory usage. Essentially the default would prevent you from ever erroring, but could lead to unnecessary vectors existing in the `System`

**Comment by lindsayad** [comment]
Although with the option suggestion...unclear to me at first thought how you would properly propagate that down to sub-applications

**Review by lindsayad — CHANGES_REQUESTED** [review]
I believe this current approach would lead to unexpected data being loaded

**Comment by loganharbour** [comment]
> I believe this current approach would lead to unexpected data being loaded

Don't you mean data _not_ being loaded?

**Comment by lindsayad** [comment]
No I mean this: https://github.com/idaholab/moose/pull/17445#issuecomment-809476215

**Comment by loganharbour** [comment]
My plan (I think we discussed this earlier) is to by default add the vector (correct parallel_type, etc) if it doesn't exist. Do you agree?

**Comment by lindsayad** [comment]
Love that plan

**Comment by friedmud** [comment]
We should be able to "skip" a vector... all the information that is needed for skipping it is in the binary package.  We just need a new `skipVector()` that forwards the input iterator the correct amount.

**Comment by lindsayad** [comment]
I think there should be a way to skip vectors if you want to but I’ve created vectors during initialSetup for holding scaling factors for AD and depending on where this falls during initialSetup it could be before or after data is restarted. Other users may also find it logical to create vectors during initialSetup as well. So I think there are reasons to read in vectors even if said vector has yet to be added to the libMesh system at the time of restarting data. Users shouldn’t have to worry about ordering in initialSetup IMO. I don’t care what the default is...skip or read...but I think it’s essential to allow read.

**Comment by GiudGiud** [comment]
Still needed

**Review by lindsayad — CHANGES_REQUESTED** [review]
Need to make sure we move over the vector-to-be-skipped's bytes such that we load the correct data into the vectors we *do* need

**Pull request closed without merging**
