### PR TITLE
Update .gitignore to include .jitcache directories

### LINKED ISSUE #7273: ignore .jitcache directories
### Description of the enhancement or error report
I started seeing directories named `.jitcache` when I run `git status` after running the tests in the `combined` module.

### Rationale for the enhancement or information for reproducing the error
These are the directories I'm seeing:
```	CHSplitFlux/.jitcache/
	DiffuseCreep/.jitcache/
	GBDependentTensors/.jitcache/
	eigenstrain/.jitcache/
	elasticitytensor/.jitcache/
	multiphase_mechanics/.jitcache/
```
I assume this has something to do with use of parsed functions.  

### Identified impact
The fix here is probably to just add `.jitcache` to a `.gitignore` file.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #7273

### CODE REVIEW

**Comment by dschwen** [comment]
I'd rather make a PR to libmesh to get rid of that dir

**Comment by friedmud** [comment]
@dschwen we can do both, right?  Might as well merge this for now...

**Comment by dschwen** [comment]
Sure

**Comment by dschwen** [comment]
Ha! I already consolidated the two directories by moving everything into `.jitcache`!

**Comment by bwspenc** [comment]
So should we remove `.jitdir` from `.gitignore`? I'll leave that to you if you think so, @dschwen.

**Comment by dschwen** [comment]
Yes @bwspenc , that is what I opened #7275 for about three hours ago :-)

**Comment by bwspenc** [comment]
OK, some of us are a little slow.

**Pull request merged**
