### PR TITLE
Use unique_ptr as Ray storage in ray_tracing

### PR DESCRIPTION
**Pull request by loganharbour**
Refs #17208

This is a WIP - curious to see if it works out as intended.

### CODE REVIEW

**Comment by friedmud** [comment]
This seems so unnecessary (especially right now)... and I am not a fan of what's going on with the banks...

**Comment by loganharbour** [comment]
> This seems so unnecessary (especially right now)... and I am not a fan of what's going on with the banks...

The bank situation affects only our application. I’m not a fan of throwing around shared ptrs everywhere

**Comment by friedmud** [comment]
It's about anticipating what's going to be needed in the future though... unique_ptrs are VERY limiting for this.  The shared_ptrs were already being passed efficiently everywhere... other than construction being slightly slower I don't see why not.

**Comment by rwcarlsen** [comment]
I think this is a good change.  In general I don't anticipate lifetime and ownership being complicated at all.  That would be the only reason for sticking with shared pointers.  Ownership and lifetime is clear and changes very little, if at all.  unique pointers seem appropriate to me.

**Comment by loganharbour** [comment]
The banking is still very reasonable. Users have access to rvalued unique_ptr in virtual methods that they can do with as they please. I think that using a unique_ptr everywhere and forcing std::move() calls on the rays makes the code explain itself MUCH more.

**Pull request closed without merging**
