### PR TITLE
No dlopen fix

### LINKED ISSUE #25911: Unused variables in !LIBMESH_HAVE_DLOPEN case
## Bug Description
In some configurations, MOOSE framework compilation fails with e.g.
```
/opt/civet0/build/moose/framework/src/base/MooseApp.C:1900:54: error: unused parameter 'app_name' [-Werror,-Wunused-parameter]
MooseApp::dynamicAppRegistration(const std::string & app_name,
```

See https://civet.inl.gov/job/1853109/ for a libMesh Civet recipe (Test MOOSE Mac) that this is killing.

## Steps to Reproduce
Configure without dlopen support, but with -Werror and with unused-parameter warnings.

## Impact
It's breaking libMesh testing, but the fix should be trivial.

### PR DESCRIPTION
**Pull request by roystgnr**
This gets builds with `!LIBMESH_HAVE_DLOPEN` working for me.  I have yet to figure out what changed in https://civet.inl.gov/job/1853109/ to cause such builds to *need* to be working, though.

Fixes #25911

### CODE REVIEW

**Review by lindsayad — APPROVED** [review]

**Comment by roystgnr** [comment]
We have got to just start ignoring `http.client.RemoteDisconnected: Remote end closed connection without response` from `mooseutils/tests.civet_results`...

**Comment by loganharbour** [comment]
> We have got to just start ignoring `http.client.RemoteDisconnected: Remote end closed connection without response` from `mooseutils/tests.civet_results`...

Trying to work on a solution to this one

This one was actually me restarting the server... and is less common than the timeout

**Comment by roystgnr** [comment]
Kicking the timeouts again, but I'm not actually sure what to do about Blackbear docs...

**Comment by lindsayad** [comment]
I would say not your circus, not your monkeys

**Pull request merged**
