### PR TITLE
Fix bad interaction between volumetric locking correction and xfem

### LINKED ISSUE #8636: Bad interaction between volumetric locking and XFEM
### Description of the enhancement or error report
We are getting very wrong results for fracture domain integrals with XFEM when `volumetric_locking_correction=true`.

### Rationale for the enhancement or information for reproducing the error
Simple 2D fracture problems give very erratic results for J Integrals, including with the wrong sign.  The problems go away if you set `volumetric_locking_correction=true`.  I have tracked this down to the fact that the volumetric locking code in the kernel uses `_current_element->volume()`, when it should be using `_current_element_volume`.  The latter has the xfem weights taken into account.

### Identified impact
Change the use of `_current_element->volume()` to `_current_element_volume` in the stress divergence kernels in solid_mechanics and tensor_mechanics.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #8636 

Note that this commit makes a few minor code changes: replacing calls to _current_elem->volume() with _current_elem_volume to correctly account for partial element volumes when used with XFEM.  It made a number of tests diff, and I went through the tests and verified that there were only extremely small differences between these two volumes in all cases. These tests were all either ill-posed or overly sensitive, so hopefully the changes I made to these tests will make them more robust in the future.

### CODE REVIEW

**Review by jasondhales — APPROVED** [review]
Looks good to me.

**Comment by bwspenc** [comment]
...yeah, looks good except that I apparently broke more tests than I thought I did!  I'll sort these tests out.

**Comment by permcody** [comment]
@bwspenc - This commit is causing regular random failures on the Intel target now.

**Comment by bwspenc** [comment]
@permcody Is causing failures in contact tests that fail on PETSc 3.7.4? Daniel mentioned that he had a commit that failed once due to that.  I know that this commit did make some of those issues pop up in new places, but it's just new manifestations of the known issue that the SuperLU in PETSc 3.7.4 is broken.

**Comment by permcody** [comment]
I don't know but it sometimes says that it can't find a contact node and other times it works. It only started with this commit. I'd say it fails 60-70% of the time.

**Comment by bwspenc** [comment]
Yes, that's the PETSC 3.7.4 issue.  We need to change that error message to say that the solution vector is full of nans rather than that it can't find the contact node.

The tests pass on the machines that have the older, non-broken version of PETSc, so if you're lucky and get one of those machines, they'll go through. 

I can add more of those tests to be skipped, but we have a real problem with this version of PETSc.  It sounds like we're having better success with 3.7.5 plus another option that Fande is passing in to SuperLU, but it's still not a 100% solution.

**Pull request merged**
