### PR TITLE
Move getInflatedProcessorBoundingBox to MooseMesh

### LINKED ISSUE #5982: Generalize PointSamplerBase::getInflatedProcessorBoundingBox()
PointSamplerBase has a really handy `getInflatedProcessorBoundingBox()` method.  I want to move it to MooseMesh so that it can be used in other places.

### PR DESCRIPTION
**Pull request by friedmud**
Simple and effective

closes #5982

### CODE REVIEW

**Comment by friedmud** [comment]
Wait - small change coming for this...

**Comment by friedmud** [comment]
Ok - should be good to go...

**Comment by permcody** [comment]
Why not just have add a `MooseUtils::InflatedBoundingBox()` routine instead? I personally could use a general capability of inflating any kind of bounding box. This routine as it stands doesn't use any instance members.

**Comment by permcody** [comment]
Also, you probably should allow the user to override the inflation amount.

**Comment by friedmud** [comment]
It does use instance members... the mesh.

I agree that it could use a parameter to override the inflation amount.

**Comment by permcody** [comment]
> It does use instance members... the mesh.

DERP! Nevermind, move along, nothing to see here...

**Comment by permcody** [comment]
Want to toss that tolerance parameter in there then I'll merge?

**Comment by friedmud** [comment]
Will do.  Sorry I didn't get to it last night.

**Comment by friedmud** [comment]
Ok - I added the parameter

**Pull request merged**
