### PR TITLE
Undo intializer list for Teuchos object

### PR DESCRIPTION
**Pull request by permcody**
refs #7174

This doesn't compile due to some odd interaction with a Teuchos constructor.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Reverting @dschwen code?  Any time!

**Comment by dschwen** [comment]
I'd be interested why and on which compiler this failed.

**Comment by jwpeterson** [comment]
> I'd be interested why and on which compiler this failed.

https://www.moosebuild.org/job/27694

```
src/transfers/DTKInterpolationAdapter.C: In constructor ‘DTKInterpolationAdapter::DTKInterpolationAdapter(Teuchos::RCP<const Teuchos::MpiComm<int> >, libMesh::EquationSystems&, const libMesh::Point&, unsigned int)’:
src/transfers/DTKInterpolationAdapter.C:165:84: error: could not convert ‘{mesh_container}’ from ‘<brace-enclosed initializer list>’ to ‘Teuchos::ArrayRCP<Teuchos::RCP<DataTransferKit::MeshContainer<long unsigned int> > >’
   Teuchos::ArrayRCP<Teuchos::RCP<MeshContainerType> > mesh_blocks = {mesh_container};
                                                                                    ^
MOOSE Compiling C++ (in opt mode) /home/moosetest/civet/client_root_0/moose/framework/src/outputs/ConsoleUtils.C...
make: *** [/home/moosetest/civet/client_root_0/moose/framework/src/transfers/DTKInterpolationAdapter.x86_64-unknown-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
ERROR: exiting with code 2
```

**Comment by dschwen** [comment]
Oh, I guess the issue is just that this container does not support
initializer lists.

**Pull request merged**
