### PR TITLE
Add SDD template.

### PR DESCRIPTION
**Pull request by lmpeterson**
Refs #9553.

### CODE REVIEW

**Comment by lmpeterson** [comment]
@aeslaughter

**Comment by aeslaughter** [comment]
Thanks for this, there are a few things that I will need to change to get it plugged into the system, but I can do that. It might be a few days before I get to it.

**Comment by aeslaughter** [comment]
@lmpeterson Sorry I didn't get to this yet, but I haven't forgot. I am in the middle of updating the template system to be more flexible, when that is done I will merge in all your changes here. It will be sometime after Labor Day before I get back on this.

**Comment by permcody** [comment]
@aeslaughter - This has been sitting for more than a month. Can we get this imported soon?

**Comment by aeslaughter** [comment]
I will re-open this when I get back around to it, not sure when that will happen.

**Pull request closed without merging**
