### PR TITLE
Add and emit moose enum docs

### LINKED ISSUE #23004: Add MooseEnum option documentation
## Reason
To enrich auto completion and documentation page generation, MooseEnum items should have individual documentation strings.

## Design
Add a map to `MooseEnumBase` that holds a doc string for each item. Add `myenum.addDocumentation("ITEM", "Doc string.");` and `myenum.addDocumentation({{"ITEM1", "Doc string1."}, {"ITEM1", "Doc string1."}});` methods.

Emit the doc strings in the JSON dump.

## Impact
Better self documentation.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #23004

The  JSON for the `error_level` parameter in `Terminator`  now looks like this:

```
              "error_level": {
                "basic_type": "String",
                "controllable": false,
                "cpp_type": "MooseEnum",
                "default": "INFO",
                "deprecated": false,
                "description": "The error level for the message. A level of ERROR will always lead to a hard termination of the entire simulation.",
                "group_name": "",
                "name": "error_level",
                "option_docs": {
                  "ERROR": "Throw a MOOSE error, resulting in the termination of the run.",
                  "INFO": "Output an information message once.",
                  "NONE": "No message will be printed.",
                  "WARNING": "Output a warning message once."
                },
                "options": "INFO WARNING ERROR NONE",
                "out_of_range_allowed": false,
                "required": false
              },
```

### CODE REVIEW

**Review by GiudGiud — CHANGES_REQUESTED** [review]
is there a doc page that describes the --dump output, the yaml and the json outputs?

since this is only adding it to JSON it should be documented

I like the idea. I've been documenting each option in the parameter description, this is a tad cleaner. I think a user will in the future be able to click on the current setting for the enum and see the description you added

**Comment by dschwen** [comment]
> is there a doc page that describes the --dump output, the yaml and the json outputs?
> 
> since this is only adding it to JSON it should be documented

What we really should do is deprecate the YAML output. The dump output is not relevant in this context (it does not even contain a list of enum options).

**Comment by dschwen** [comment]
Added YAML output (and fixed ExecFlagEnums in YAML):

```
    - name: error_level
      required: No
      default: !!str INFO
      cpp_type: MooseEnum
      group_name: 
      options: INFO WARNING ERROR NONE
      option_docs:
      - name: INFO
        description: |
          Output an information message once.
      - name: WARNING
        description: |
          Output a warning message once.
      - name: ERROR
        description: |
          Throw a MOOSE error, resulting in the termination of the run.
      - name: NONE
        description: |
          No message will be printed.
      description: |
        The error level for the message. A level of ERROR will always lead to a hard termination of the entire simulation.
```

**Comment by dschwen** [comment]
> I think a user will in the future be able to click on the current setting for the enum and see the description you added

One this is merged I'll had doco on mouse hover for enum options and will add the doco to enum item autocompletion. I'm assuming @brandonlangley will do the same for the Workbench stuff.

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
