### PR TITLE
Adding UserObjects for summing forces and pinning grains

### LINKED ISSUE #5521: Adding External Force Density to grains
Adds external force density to grains in addition to reaction forces due to interaction between grains. This force will be used in grain motion kernels as well as by mechanics modules for stress calculation. This should be equivalent to applying pressure boundary conditions for cases combining PhaseField and TensorMechanics. Helpful for grains in porous media.

### PR DESCRIPTION
**Pull request by SudiptaBiswas**
Added UserObject for summing forces calculated in different userobjects. Also Added UserObject for making the forces and torques acting on a grain zero restraining grain movement. 
closes #5521

### CODE REVIEW

**Comment by SudiptaBiswas** [comment]
'time_steppers/time_adaptive.test' is failing due to time-out.

**Comment by jwpeterson** [comment]
I fixed the conflict and tried your branch.  Both the new tests have errors for me...

```
phase_field:rigidbodymotion.grain_forcemasked: *** ERROR ***
phase_field:rigidbodymotion.grain_forcemasked: Trying to get a non-existent variable 'c'
```

```
phase_field:rigidbodymotion.grain_forcesum: *** ERROR ***
phase_field:rigidbodymotion.grain_forcesum: Trying to get a non-existent variable 'c'
```

**Comment by jwpeterson** [comment]
Those errors were easily-resolved, though, see jwpeterson/moose@523ba00.  I can merge my fixed version by hand, what do you say @dschwen?

**Comment by dschwen** [comment]
Yeah, the ```c = c``` needs to be there. Looks good now. :+1:

**Comment by SudiptaBiswas** [comment]
Yeah these tests were built before PR #5524 was merged to devel. That's why this error was coming. Thanks for getting it resolved  @jwpeterson. Let me know if anything is required from my side.

**Pull request merged**
