### PR TITLE
Aug 2020 news

### PR DESCRIPTION
**Pull request by aeslaughter**
@idaholab/moose-ccb 

(refs #11446)

### CODE REVIEW

**Comment by zachmprince** [comment]
Oh shoot I thought we merged onto next. Should I remove the POD stuff?

**Comment by lindsayad** [comment]
> Oh shoot I thought we merged onto next. Should I remove the POD stuff?

Is that Plain Old Data or [P.O.D.](https://www.youtube.com/watch?v=EDKwCvD56kw)?

**Comment by lindsayad** [comment]
I'll add my contribs today

**Comment by lindsayad** [comment]
We’ll merge this when we can!!

**Comment by loganharbour** [comment]
@aeslaughter trigger a change to get 'er in

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
