### PR TITLE
Add MooseServer completion of parameters required in blocks

### LINKED ISSUE #27510: VSCode plugin could output fill-in template
### Motivation

Some objects, like actions and physics, have a longer list of parameters. It would be much easier if a template to be filled could be spawned by the VSCode plugin, rather than relying on auto-complete to fetch the required parameters one by one

### Design

Some command (maybe ctrl T?) could spawn all the required parameters of an object, with an empty field to fill.

(another idea: Alternatively, we could spawn these templates by parameter groups)

The parameters should be sorted by parameter group for readability, and parameter groups would be separated by a line break. Maybe the name of the parameter group would be included as a header for the group of parameters. Maybe users could decide how 'verbose' the templates should be

Achieving something like this:

```
    # General control parameters
    compressibility =
    add_energy_equation =

    # Material property parameters
    density = 
    dynamic_viscosity =
    thermal_conductivity = 
    specific_heat = 

    # Initial condition parameters
    initial_velocity = 
    initial_pressure = 
    initial_temperature = 

    # Boundary condition parameters
    inlet_boundaries = 
    momentum_inlet_types = 
    momentum_inlet_function = 
    energy_inlet_types = 'heatflux'
    energy_inlet_function = 
    wall_boundaries = 
    momentum_wall_types = 
    energy_wall_types = 
    energy_wall_function = 
    outlet_boundaries = 
    momentum_outlet_types =
    pressure_function = 

    # Ambient convection parameters
    ambient_convection_alpha =
    ambient_temperature =

    # Numerical scheme
    mass_advection_interpolation =
    momentum_advection_interpolation = 
    energy_advection_interpolation =
```

NB: the action being what it is, most of these parameters are actually not required. But the physics have more required parameters due to not turning off equations with booleans

One question: do we include parameters with a default already?
I think it could be confusing. For example for the NSFVAction, if 'add_scalar_equation' is kept to false, then spawning the ten parameters for the scalar equation in the input would not be great. 
If we spawn parameters-to-fill by parameter groups rather than all-the-required-ones-at-once, then I could see us adding the pre-filled parameters with defaults

### Impact

Better usability.
Easier time using these large actions

@brandonlangley @dschwen @loganharbour

### PR DESCRIPTION
**Pull request by brandonlangley**
closes #27510, refs #22766

https://github.com/user-attachments/assets/226dc149-4d9e-4671-a20f-52e3d0539124

### CODE REVIEW

**Comment by brandonlangley** [comment]
@loganharbour @dschwen @GiudGiud -

This adds all required parameters in a block automatically when autocompleting either:

 - a completely new block, e.g., `[Mesh]` adds `file =` while `[Executioner]` adds `type =`

 - a block type value, e.g., `type = NonlinearEigen` under `[Executioner]` adds `bx_norm =`

These cases are also added to the unit test, but only for syntax very unlikely to change.

Could one of you review this update when are are able and merge it if you approve?

**Review by loganharbour — COMMENTED** [review]
This only handles complete matches, right? For param paths

**Comment by brandonlangley** [comment]
@loganharbour -

> This only handles complete matches, right? For param paths

It only inserts the required parameters when the user actually selects the block name or type value with return or click.

So it is not live updating the input by adding and removing params as the user types partial block names or type values.

I believe this is what you are asking, but I also just made this quick video showing how it is working in practice.

https://github.com/user-attachments/assets/be78fed1-0fc2-4b0d-ad13-71d808ad71f6

**Review by loganharbour — APPROVED** [review]
Looks great to me. Easier than I would have expected.

**Comment by brandonlangley** [comment]
@loganharbour 

> Looks great to me. Easier than I would have expected.

Awesome, thanks for giving it a look. Any reservations against going ahead and merging this?

**Comment by GiudGiud** [comment]
next is broken rn (a PR was merged passing the tests on PRs, but not passing the tests for next->devel merge), once we have visibility on the fix we can merge.

**Comment by brandonlangley** [comment]
@GiudGiud - Okay, thanks.

**Comment by brandonlangley** [comment]
@loganharbour @GiudGiud -

Should I rebase this on devel again or anything in order to merge?

**Comment by GiudGiud** [comment]
This is awesome thank you for adding it.
I ll try this very soon

**Comment by GiudGiud** [comment]
once it's installable I can see posting on #moose about it, it's that big a deal imo

**Pull request merged**
