### PR TITLE
Header refactor

### PR DESCRIPTION
**Pull request by roystgnr**
A swath of refactoring as discussed in #8730 

The final commit turned out to break compilation of quite a few .C files until their previously-indirectly-included dependencies were directly included, so I don't expect this to pass Civet without similar app updates.

### CODE REVIEW

**Comment by permcody** [comment]
I like these changes. It'll take someone on the inside to get it through though. Maybe @jwpeterson?

**Comment by roystgnr** [comment]
Yeah, I'm actually pretty impressed that a third of the tested apps didn't have a single compilation failure, but that leaves ~8 which need fixes, and I don't think I've been granted access to half of those.

**Comment by andrsd** [comment]
I will take care of bighorn and RELAP-7 (as usual)...

**Comment by jwpeterson** [comment]
I'll fix BISON, Rattlesnake, Wolverine. 
@aeslaughter can look at Mastodon. 
@dscwhen can you please fix Magpie?

**Comment by andrsd** [comment]
I think wolverine gets fixed when I fix bighorn, it might need just a bighorn submodule update.

**Comment by jwpeterson** [comment]
For anyone who's updating an app: this branch is already from a slightly older version of MOOSE, so you may need to merge current devel into it (or vice versa) before fixing headers...

**Comment by andrsd** [comment]
bighorn is patched up

**Comment by jwpeterson** [comment]
> bighorn is patched up

Got it, see/update my checklist above as necessary.

**Comment by YaqiWang** [comment]
@jwpeterson Will you also take care of MAMMOTH? Rattlesnake has been patched up.

**Review by jwpeterson — APPROVED** [review]
Crossing my fingers that this passes all the app tests now.

**Comment by jwpeterson** [comment]
Adding tutorial and examples as suggested by @brianmoose.

**Pull request merged**
