### PR TITLE
New Warehouse design

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #5680)

### CODE REVIEW

**Comment by aeslaughter** [comment]
FYI, this does add quite a few lines, but most of that is tests. If you look at the commits when the warehouses are replaced the are a net decrease (git log --shortstat). For example,

```
commit 229e8c1d72cd7e83b9db426c9f079a7aa632ed6c
Author: Andrew E Slaughter <andrew.slaughter@inl.gov>
Date:   Tue Dec 8 12:39:32 2015 -0700

    Kernel storage update to new objects
    
    (refs #5680)

 16 files changed, 283 insertions(+), 419 deletions(-)

commit 29dc868f46dcdd8fab917bd2d8a191556514e0a9
Author: Andrew E Slaughter <andrew.slaughter@inl.gov>
Date:   Tue Nov 24 09:51:46 2015 -0700

    Migrates PresetNodalBC objects to a unique warehouse
    
    (refs #5680)

 4 files changed, 46 insertions(+), 240 deletions(-)

commit 41713157104910f8ebea392a185d35fee9d10363
Author: Andrew E Slaughter <andrew.slaughter@inl.gov>
Date:   Mon Nov 23 17:17:05 2015 -0700

    Migrates NodalBC objects to a unique warehouse
    
    (refs #5680)

 4 files changed, 54 insertions(+), 99 deletions(-)

commit 06540282268a50f8a29c8550e760b73fd8427e90
Author: Andrew E Slaughter <andrew.slaughter@inl.gov>
Date:   Mon Nov 23 16:28:29 2015 -0700

    Migrated Integrated BCs to a unique warehouse
    
    (refs #5680)

 11 files changed, 78 insertions(+), 126 deletions(-)
```

**Comment by aeslaughter** [comment]
This is ready and so is my YAK patch.

**Comment by permcody** [comment]
Actually it was a small net increase:

**BEFORE (framework)**
``` 
$ find. -name ".[hC]" | wc
   1241    1241   47209
$ find . -name "*.[hC]" | xargs wc
  158158  528382 5387632 total
```

**AFTER (framework)**
```
$ find. -name ".[hC]" | wc
    1251    1251   47592
$ find . -name "*.[hC]" | xargs wc
  158113  528639 5387496 total
```

I also ran a few speed tests and noticed that some tests are faster and some are slower so I can't really draw any conclusions about any degradations or improvements due to this change without a further more involved study.

\begin{Soapbox}
So why am I doing this? Well I think it's important to look objectively at our code base before diving into any sort of long term project. I have no doubt that your intentions are good but at the end of the day it's sometimes hard to say we've improved the code after a long haul change like this. This change was meant to refactor the warehouses to reduce a number of duplicate methods and possibly consolidate a few common warehouses. However at the end of the day, the actual file and line counts have both *increased* marginally not *decreased*. I realize that I'm counting lines, not semicolons or blocks so it may in fact be down a bit if I consider that you've improved the documentation but it's safe to say this didn't reduce the code base by a significant amount.

There are also certainly increase hidden costs. We now have several "different" lines of code that now need to be used and debugged for awhile to know if things are better. There will almost certainly be new bugs and new problems but I have no doubt that they will be resolved in time. Also, other developers will have to invest time to understand the new unfamiliar layout and get to know the system.

I guess what I'm trying to get at is that we really need to be careful about changing things for the sake of improvement. Sometimes old familiar debugged code with warts can be just as good as new cleaner but unproven code. 
\end{SoapBox}

Thanks Andrew for your efforts on this change. After my soapbox speech I do agree that the new design is better and hopefully allows us to extend the framework even more in the future. I will review this change set and get back to you.

**Comment by aeslaughter** [comment]
A few comments:
- I still have about 12 warehouse to convert, I have done 8 so far and need to remove the old code, so in the end I am hopeful that the code will be reduced.
- Regardless of the lines, the new systems adds uniformity across the object storage containers.
- I am not sure what will happen with speed, but there still is the deprecated isActive calls that will go away.

**Comment by aeslaughter** [comment]
Moved to #6061

**Pull request closed without merging**
