### PR TITLE
Update HIT to merge content from blocks that have same name

### LINKED ISSUE #25928: Allow object parameters to be split between files
## Reason
In some situations where the majority of input is the same between two or more runs, it's useful to factor out some parameters. However, the parser currently does not merge blocks of the same name. For example,
`fileA.i`:
```
[Mesh]
  type = GeneratedMesh
  dim = 1
[]

[Problem]
  solve = false
[]

[Postprocessors]
  [test_pp]
    type = ConstantPostprocessor
  []
[]

!include fileB.i

[Executioner]
  type = Steady
[]
```
with `fileB.i`:
```
[Postprocessors]
  [test_pp]
    value = 5.0
  []
[]
```
gets an error
```
A UserObject with the name "test_pp" already exists.  You may not add a Postprocessor by the same name.
```

## Design
This would have some kind of "merge" happen before processing the input file so that input file blocks with the same name do not get treated as two objects with the same name.

## Impact
More flexible input capability.

### PR DESCRIPTION
**Pull request by brandonlangley**
closes #25928

### CODE REVIEW

**Comment by brandonlangley** [comment]
@joshuahansel -

This implements your request https://github.com/idaholab/moose/issues/25928 to merge content from blocks that have same name.

It's not ready to merge due to the expected failure mentioned below, and I want to see if any downstream app tests fail.

I'm copying my Slack comment to here for reference and to get @permcody's thoughts on how this should be handled:

> After this update, `auxkernels/time_integration.time_integration_aux` fails running this (abridged version) input:
>
> ```
> [Mesh]
>   # . . .
> []
>
> [Functions]
>   [dts]
>     type = PiecewiseLinear
>     x = '0.01 0.1'
>     y = '0.005 0.05'
>   []
> []
>
> [Variables]
>   # . . .
> []
>
> [Kernels]
>   # . . .
> []
>
> [AuxVariables]
>   # . . .
> []
>
> [AuxKernels]
>   # . . .
> []
>
> [BCs]
>   # . . .
> []
>
> [Functions]
>
>   active = 'Soln Source TopBC BottomBC RightBC LeftBC'
>
>   [Soln]
>     type = ParsedFunction
>     expression = 't*(x*x+y*y)'
>   []
>   [Source]
>     type = ParsedFunction
>     expression = '(x*x + y*y) - 4*t'
>   []
>   [TopBC]
>     type = ParsedFunction
>     expression = 't*(x*x+1)'
>   []
>   [BottomBC]
>     type = ParsedFunction
>     expression = 't*x*x'
>   []
>   [RightBC]
>    type = ParsedFunction
>    expression = 't*(y*y+1)'
>   []
>   [LeftBC]
>     type = ParsedFunction
>     expression = 't*y*y'
>   []
> []
>
> [Postprocessors]
>   # . . .
> []
>
> [Executioner]
>   type = Transient
>   [TimeStepper]
>      type = FunctionDT
>      function = dts
>   []
> []
>
> [Outputs]
>   # . . .
> []
> ```
>
> The contents from the two `[Functions]` blocks above get merged into one block which effectively looks like this:
>
> ```
> [Functions]
>
>   [dts]
>     type = PiecewiseLinear
>     x = '0.01 0.1'
>     y = '0.005 0.05'
>   []
>
>   active = 'Soln Source TopBC BottomBC RightBC LeftBC'
>
>   [Soln]
>     type = ParsedFunction
>     expression = 't*(x*x+y*y)'
>   []
>   [Source]
>     type = ParsedFunction
>     expression = '(x*x + y*y) - 4*t'
>   []
>   [TopBC]
>     type = ParsedFunction
>     expression = 't*(x*x+1)'
>   []
>   [BottomBC]
>     type = ParsedFunction
>     expression = 't*x*x'
>   []
>   [RightBC]
>    type = ParsedFunction
>    expression = 't*(y*y+1)'
>   []
>   [LeftBC]
>     type = ParsedFunction
>     expression = 't*y*y'
>   []
> []
> ```
>
> It's obvious looking at this merged block why the run ends up failing with an `Unable to find function dts` error.
>
> The first `[Functions]` block did not specify an `active` or `inactive` block list, so `[dts]` is regarded active there.
>
> But the second `[Functions]` block did specify an `active` block list, so anything not in the list is deemed inactive.
>
> Merging these two blocks turned `[dts]` from active to inactive due to it being absent from the `active` block list.
>
> Even if the first block did specify `active = 'dts'`, parameter values are not merged so what should happen then?
>
> This scenario with `active` / `inactive` lists presents the same problem regardless of if an `!include` input is used.

**Comment by brandonlangley** [comment]
@joshuahansel @permcody -

In addition to the `time_integration.time_integration_aux` failure described above, there's also a Python test failing.

The `TestHarness/tests.duplicate_test_names` test checks for the condition of duplicate test sections using this file:

```
[Tests]
  [./duplicate_test_name]
    type = RunApp
    input = good.i
  [../]
  [./duplicate_test_name]
    type = RunApp
    input = good.i
  [../]
[]
```

The parse tree for this has one merged `duplicate_test_name` section after this update rather than separate sections.

The [Controlled app tests](https://civet.inl.gov/job/1863464/) job is also failing, but I don't have permission to see the results so I'm unsure of the damage.

**Comment by loganharbour** [comment]
The controlled app failure is related. 

Tag me once the moose tests are passing and I'll take a deeper dive into it.

**Comment by joshuahansel** [comment]
> Tag me once the moose tests are passing and I'll take a deeper dive into it.

Tag me once the moose tests are passing and I'll take a deeper dive into it. @brandonlangley I'm looking into the SAM failures. I think it's likely that tests can be fixed before this PR goes in (avoid any "breakage").

**Comment by joshuahansel** [comment]
All SAM tests were easily avoidable and unnecessary, probably copy/paste errors. I'll put up a SAM PR soon, but @loganharbour I think you're clear to review. @brandonlangley I'll put a commit on your branch to fix the failing MOOSE test.

Interestingly, this was one of the failing SAM input files:
```
[Functions]
  [flow_secondary]
    type = PiecewiseLinear
    x ='-1.000E+03  0          1       1e5'
    y = '-1259     -1259     0       0'
    scale_factor = 0.002216 # 1/rhoA
  []
  [flow_dhx]
    type = PiecewiseLinear
    x ='-1.000E+03   0     1      1e5'
    y = '-6.478  -6.478  -6.478    -6.478'
    scale_factor = 0.046 # 1/rhoA
  []

  [./flow_secondary]
    type = PiecewiseLinear
	x ='-1.000E+03	0	        1	     1e5'
	y = '-1259   	-1259   	0  		 0'
	scale_factor = 0.002216 # 1/rhoA
  [../]

  [./flow_dhx]
    type = PiecewiseLinear
	x ='-1.000E+03 	0	   1	    1e5'
	y = '0  0	-6.478 	 -6.478'
	scale_factor = 0.046 # 1/rhoA
  [../]
[]
```
I don't know why the current parser was ok with this. Note this was in the 4th input file in a multi-input setup: `app-opt -i input1.i input2.i input3.i input4.i`. So maybe this sort of thing gets by in this situation because the multi-input setup overrides previous input files?

**Comment by brandonlangley** [comment]
@joshuahansel -

> Interestingly, this was one of the failing SAM input files: ...

Yeah, it definitely doesn't make sense to me how the parser would have ever been okay with that example.

I tried to replicate to see if it would somehow successfully parse with MOOSE and it fails with these errors:

```
*** Info ***
Merging inputs input1.i, input2.i, input3.i, input4.i


*** ERROR ***
/path/to/input4.i:3.5: parameter 'Functions/flow_secondary/type' supplied multiple times
/path/to/input4.i:16.5: parameter 'Functions/flow_secondary/type' supplied multiple times
/path/to/input4.i:4.5: parameter 'Functions/flow_secondary/x' supplied multiple times
/path/to/input4.i:17.2: parameter 'Functions/flow_secondary/x' supplied multiple times
/path/to/input4.i:5.5: parameter 'Functions/flow_secondary/y' supplied multiple times
/path/to/input4.i:18.2: parameter 'Functions/flow_secondary/y' supplied multiple times
/path/to/input4.i:6.5: parameter 'Functions/flow_secondary/scale_factor' supplied multiple times
/path/to/input4.i:19.2: parameter 'Functions/flow_secondary/scale_factor' supplied multiple times
/path/to/input4.i:9.5: parameter 'Functions/flow_dhx/type' supplied multiple times
/path/to/input4.i:23.5: parameter 'Functions/flow_dhx/type' supplied multiple times
/path/to/input4.i:10.5: parameter 'Functions/flow_dhx/x' supplied multiple times
/path/to/input4.i:24.2: parameter 'Functions/flow_dhx/x' supplied multiple times
/path/to/input4.i:11.5: parameter 'Functions/flow_dhx/y' supplied multiple times
/path/to/input4.i:25.2: parameter 'Functions/flow_dhx/y' supplied multiple times
/path/to/input4.i:12.5: parameter 'Functions/flow_dhx/scale_factor' supplied multiple times
/path/to/input4.i:26.2: parameter 'Functions/flow_dhx/scale_factor' supplied multiple times
```

**Comment by permcody** [comment]
> @joshuahansel @permcody -
> 
> In addition to the `time_integration.time_integration_aux` failure described above, there's also a Python test failing.
> 
> The `TestHarness/tests.duplicate_test_names` test checks for the condition of duplicate test sections using this file:
> 
> ```
> [Tests]
>   [./duplicate_test_name]
>     type = RunApp
>     input = good.i
>   [../]
>   [./duplicate_test_name]
>     type = RunApp
>     input = good.i
>   [../]
> []
> ```
> 
> The parse tree for this has one merged `duplicate_test_name` section after this update rather than separate sections.
> 
> The [Controlled app tests](https://civet.inl.gov/job/1863464/) job is also failing, but I don't have permission to see the results so I'm unsure of the damage.

Don't worry about keeping the current behavior here. I'm not even sure exactly what I would want to happen here since we don't have a conflict in the parameter names. Part of me wants to error if there's a duplicate section name for the testing system, but that's not consistent with the MOOSE input parser and the other part of me thinks consistent behavior is even more important. Let's go with consistent behavior even if that means modifying this test.

**Comment by brandonlangley** [comment]
> Don't worry about keeping the current behavior here. I'm not even sure exactly what I would want to happen here since we don't have a conflict in the parameter names. Part of me wants to error if there's a duplicate section name for the testing system, but that's not consistent with the MOOSE input parser and the other part of me thinks consistent behavior is even more important. Let's go with consistent behavior even if that means modifying this test.

@permcody -

Note this file being tested **_does_** fail processing with a `FATAL PARSER ERROR` due to the conflict in parameter names.

```
[Tests]
  [./duplicate_test_name]
    type = RunApp
    input = good.i
  [../]
  [./duplicate_test_name]
    type = RunApp
    input = good.i
  [../]
[]
```

It's just that the currently expected failure (before these changes) looks like this:

```
tests/test_harness.duplicate_test_name ................................................. [DUPLICATE TEST] SKIP
tests/test_harness.duplicate_test_name .................................................................... OK


Parser Errors:
--------------------------------------------------------------------------------------------------------------
/data/civet1/build/moose/test/tests/test_harness/duplicate_test_names:6: duplicate section "/Tests/duplicate_test_name"
/data/civet1/build/moose/test/tests/test_harness/duplicate_test_names:7: duplicate parameter "/Tests/duplicate_test_name/type"
/data/civet1/build/moose/test/tests/test_harness/duplicate_test_names:8: duplicate parameter "/Tests/duplicate_test_name/input"
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 1.0 seconds. Average test time 0.7 seconds, maximum test time 0.7 seconds.
1 passed, 1 skipped, 0 pending, 0 failed, FATAL PARSER ERROR
```

And now (after these changes), that failure instead looks like this:

```
tests/test_harness.duplicate_test_name .................................................................... OK


Parser Errors:
--------------------------------------------------------------------------------------------------------------
/data/civet1/build/moose/test/tests/test_harness/duplicate_test_names:3: duplicate parameter "/Tests/duplicate_test_name/type"
/data/civet1/build/moose/test/tests/test_harness/duplicate_test_names:4: duplicate parameter "/Tests/duplicate_test_name/input"
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 0.9 seconds. Average test time 0.7 seconds, maximum test time 0.7 seconds.
1 passed, 0 skipped, 0 pending, 0 failed, FATAL PARSER ERROR
```

These two lines are what the regular expressions in the test are checking for:

```
tests/test_harness.duplicate_test_name ................................................. [DUPLICATE TEST] SKIP
tests/test_harness.duplicate_test_name .................................................................... OK
```

However that top `[DUPLICATE TEST] SKIP` line is no longer present, so that regular expression check fails.

There is actually already a separate Test Harness unit test that is checking for the `duplicate parameter` errors.

The `python/TestHarness/tests/test_ParserErrors.py` test already checks this same condition using this file:

```
[Tests]
  [./syntax]
    type = RunApp
    input = good.i
    check_input = true
    check_input = true
  [../]
[]
```

So should the `duplicate_test_name` test be removed instead of modified as duplicate names are no longer an error?

**Comment by permcody** [comment]
I’m happy we are catching this already. We don’t need two tests for the
same behavior. Please feel free to remove.

**Comment by brandonlangley** [comment]
@joshuahansel -

I [removed](https://github.com/idaholab/moose/pull/25964/commits/a868aa409639dd58490333a21f498dfbb1b6acc4) the `duplicate_test_names` failure test since duplicate test names are no longer an error condition.

I'm not sure if the SAM tests that were failing have been updated/fixed downstream or if they will still fail here.

I don't know that there are any changes left here, so I'm moving this out of draft and ready to merge if wanted.

**Review by loganharbour — APPROVED** [review]
I'm going to check this again with the new changes coming and and will merge after.

**Comment by loganharbour** [comment]
There are a few tests that are cancelled - they can be ignored. They're older recipes that existed on the previous push that no longer exist.

**Pull request merged**
