### PR TITLE
Allow spaces in petsc_version and slepc_version

### LINKED ISSUE #13232: Fixed issues with PETSc-3.9.{0,1,2,3}
## Bug Description

PETSc-3.9.{0,1,2,3} have incompatible APIs on Jacobian tests.  We are going to skip some tests if necessary for these particular petsc versions.

## Steps to Reproduce

Compile PETSc-3.9.0, and run framework tests

## Impact

Not much.

### PR DESCRIPTION
**Pull request by fdkong**
Closes #13232

### CODE REVIEW

**Comment by fdkong** [comment]
@tophmatthews  Could you check if this patch works for you?

Thanks

**Comment by tophmatthews** [comment]
Yup, works for me! Thanks @fdkong

**Comment by fdkong** [comment]
@permcody  Could take a look at this?

**Review by permcody — CHANGES_REQUESTED** [review]
Nope - This is super wrong. I'll see if i can fix this up for you.

**Comment by permcody** [comment]
Superseded by #13273.

**Pull request closed without merging**
