### PR TITLE
Bug fix solid mechanics volumetric locking

### LINKED ISSUE #8026: Fix bug in solid mechanics AxiSymmetricRZ
### Description of the enhancement or error report
There is a bug in the volumetric locking calculation in axisymmetricRZ which shows up in creep tests. In the volumetric locking correction, the volumetric part of the strain tensor is averaged over the element and there was a mistake in this calculation. 

### Rationale for the enhancement or information for reproducing the error
fixes bug in strain calculation

### Identified impact
This issue affects 2 tests in combined directory and a few tests in Bison.

### PR DESCRIPTION
**Pull request by sveerara**
AxisymmetricRZ.C, Linear.C and Planestrain.C has been changed and two tests in combined directory have been regolded. 

The volumetric averaging of the strain over all qp points belonging to an element occurs in a for loop with index qp_loop. In some of the terms, the current quadrature index (qp) was used instead of qp_loop. 

This PR will fail a few bison tests. A bison patch is ready.

Closes  #8026

@bwspenc, @sapitts

### CODE REVIEW

**Comment by bwspenc** [comment]
This looks good to me.

Does this have anything to do with the issue with small strain axisymmetric models of thick shells, or is that an unrelated issue?

**Comment by sveerara** [comment]
I don't think this has anything to do with the small strain axisymmetric models of thick shells. Although, I ran the problem only after I fixed this bug so I cant say for sure. 

The thick cylinder problem had a pressure applied to the inner surface. The stress at the element closest to the inner edge was a little different from the analytical solution. But the stress given by moose is an element averaged quantity. When I extrapolated the element averaged stress to get the stress at the edge, it matched the analytical solution. I have verified that it matches the analytical solution for no b-bar + axisymmetricRZ, b-bar + axisymmetric RZ, no b-bar + nonlinear RZ and b-bar + nonlinear RZ.

**Comment by sapitts** [comment]
What about the axisymmetricRZ + large_strain= true + b-bar / no b-bar combinations?  Do those also match the analytical solution?

**Comment by sveerara** [comment]
I have not checked that. I will check that now.

**Comment by sveerara** [comment]
axisymmetricRZ + large_strain  = true +b-bar /no b-bar gives the same results as the other cases. I did not try it without the bug fix.  This probably would have been affected quite a bit by the bug. Thanks @sapitts

**Review by dschwen — APPROVED** [review]

**Comment by bwspenc** [comment]
@gardnerru

**Comment by bwspenc** [comment]
@sveerara has a commit ready for the failing BISON app tests, so I'm merging this now.

**Pull request merged**
