### PR TITLE
Fixing up generated header dependencies for submodules

### LINKED ISSUE #16637: Improve `-v` version output
## Reason
```
(moose) [schwd][~/Programs/blackbear]> ./blackbear-opt -v

Application Version: 3877bd279e
```

Thats a lie! What's shown here is the framework version. Both need to be shown and labeled correctly.
Furthermore there is a Makefile issue where going back to an older commit will not re-generate the `*Revision.h` file. This has the potential to drive developers (@recuero) mad, as they see a hash not matching their checkout in the app's version output.

## Design
Just show the right stuff and make sure its updated.

## Impact
Better transparency.

### PR DESCRIPTION
**Pull request by permcody**
closes #16637

I believe this fixes the nasty header problem. I tested this in a few of the umbrella repos and saw the expected behaviors after touching all and subsets of the submodules:

```
Submodule path 'foo': checked out '5a162d0e8a9e79b45f1368eecfba6d0f284af3bd'
Submodule path 'bar': checked out '3ee502f39743356d2bfb235cf7eacfb809f8ed5c'
Submodule path 'baz': checked out '8674d2f57c34ea77ff9a7cf2d03b98a48c903506'
Submodule path 'biz': checked out '11e6336f3a6d072e33c1fdce2a5c7fa15d4d8ab4'
Submodule path 'moose': checked out '00f391953c6b81ced1db217a613316bfe4aed4f3'
Submodule path 'jazz': checked out '62cf88bf22cbbb1aabd223320769895464e080fd'
Submodule path 'junk': checked out 'f4ad60e26d2ae2a1c31171c85009f07e95f1c76c'
permcj@thearchitect{~/projects/purple_slug}[update_submodules]$ make -j45                                                                                (moose)
Using HIT from /Users/permcj/projects/moose/moosetools/contrib/hit
Checking if header needs updating: /Users/permcj/projects/purple_slug/foo/include/base/FooRevision.h...
Checking if header needs updating: /Users/permcj/projects/purple_slug/bar/include/base/BarRevision.h...
Checking if header needs updating: /Users/permcj/projects/purple_slug/baz/include/base/BazRevision.h...
Checking if header needs updating: /Users/permcj/projects/purple_slug/biz/include/base/BizRevision.h...
Checking if header needs updating: /Users/permcj/projects/purple_slug/jazz/include/base/JazzRevision.h...
Checking if header needs updating: /Users/permcj/projects/purple_slug/junk/include/base/JunkRevision.h...
```

For this test, I set $MOOSE_DIR and didn't change it even though the (unused) submodule was updated. As expected, it picked up MOOSE from the MOOSE_DIR and correctly picked up the dependencies for all the submodules updating only those submodules' headers. Additionally, I didn't update one of the other submodules and it isn't reflected in this output at all. This might be it guys!

### CODE REVIEW

**Comment by lindsayad** [comment]
Who is this guy??

**Review by loganharbour — APPROVED** [review]
What a fun mess :-) even correct on the first go!

I tested this locally touching files in dependent apps and it looks like we're good

**Comment by permcody** [comment]
> What a fun mess :-) even correct on the first go!
> 
> I tested this locally touching files in dependent apps and it looks like we're good


image

**Comment by loganharbour** [comment]
> > What a fun mess :-) even correct on the first go!
> > I tested this locally touching files in dependent apps and it looks like we're good
> 
> image

Don't even have faith in yourself? A true MOOSE developer!

**Comment by permcody** [comment]
Trying to show a little humility since I nailed it. Hedging my bets you know...

**Pull request merged**
