### PR TITLE
Start using apptainer builds for civet testing

### PR DESCRIPTION
**Pull request by loganharbour**
Reduces coverage as required for the change from gcc 9 -> 8

### CODE REVIEW

**Comment by loganharbour** [comment]
@lindsayad would you mind looking through these diffs to make sure nothing looks egregious?

Reminder that modules aren't built with `-O0`, so almost all of these are likely differences in optimization strategies between GCC 9 and 8

**Comment by lindsayad** [comment]
We're configured with PNG output now?

**Comment by lindsayad** [comment]
seems like some difference in treatment of static functions, e.g. a lot of coverage "lost" in `NavierStokesApp`

**Comment by loganharbour** [comment]
> seems like some difference in treatment of static functions, e.g. a lot of coverage "lost" in `NavierStokesApp`

Is this a concern to you? I don't really care about the numbers. Just that coverage for important things is actually reliable and diffable.

**Comment by lindsayad** [comment]
No it was just an observation. Overall this looks fine to me

**Review by lindsayad — DISMISSED** [review]

**Review by lindsayad — DISMISSED** [review]

**Review by milljm — APPROVED** [review]

**Pull request merged**
