### PR TITLE
use auto when casting for thread joining UOs PPs VPPs

### PR DESCRIPTION
**Pull request by GiudGiud**
pretty sure I wont do it wrong anymore if I cant copy paste it wrong from anywhere

### CODE REVIEW

**Comment by GiudGiud** [comment]
Any preference for the issue to use?
Could do 
#14513
#7829 
#6993

**Comment by loganharbour** [comment]
why

**Comment by GiudGiud** [comment]
beautiful code

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
> why

haha. why why?

**Pull request merged**
