### PR TITLE
Add more `coupled*Values*` functions

### LINKED ISSUE #21989: enhancement of "coupledNeighborValueOld" or "coupledNeighborValueOlder" to "coupledNeighborValuesOld" or "coupledNeighborValuesOlder" for vector case
## Reason

Moose has coupledNeighborValues for vector case but doesn't have for _old or order cases. 
## Design

   _disp_old(coupledValuesOld("displacements")),
    _disp_neighbor_old(coupledNeighborValuesOld("displacements")),
that are similar to 
   _disp(coupledValues("displacements")),
    _disp_neighbor(coupledNeighborValues("displacements")),

## Impact

Add a new feature.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #21989

@RLiu2020

still needs tests

### CODE REVIEW

**Comment by dschwen** [comment]
Needs tests

**Comment by dschwen** [comment]
I'll add tests

**Comment by dschwen** [comment]
Turns out I still need this

**Comment by GiudGiud** [comment]
@dschwen can you please approve my changes

**Review by GiudGiud — APPROVED** [review]
approving Daniel's work

**Comment by GiudGiud** [comment]
should be ready (passed last set of tests, changed up a commit a tad)

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
