### PR TITLE
Restricted convergence test to 4 processes

### PR DESCRIPTION
**Pull request by joshuahansel**
This fixes the sweep testing failures caused by https://github.com/idaholab/moose/pull/28848.

### CODE REVIEW

**Comment by joshuahansel** [comment]
Enabled parallel sweep testing on this PR

**Review by lindsayad — CHANGES_REQUESTED** [review]
I should have caught this on review. Is there any way to test this other than iteration counting? The fact that this fails in parallel means it's likely not future proof against slight changes in PETSc implementation, etc.

**Comment by joshuahansel** [comment]
I think that iteration counting is the right way to test a convergence object because this is ultimately the impact a convergence has. I don't see that not testing at high process counts will be a detriment. At low counts, I think it should be stable enough.

**Review by lindsayad — APPROVED** [review]

**Comment by loganharbour** [comment]
Looks like this is now failing SQA, not sure how it didn't fail before

```

ERRORS:
/Convergence/AugmentedLagrangianContactFEProblemConvergence is missing a markdown file.
  The page should be located at modules/contact/doc/content/source/convergence/AugmentedLagrangianContactConvergence.md
  A stub page can be created using using the './moosedocs.py generate' command
Control this message using: 'log_missing_markdown'

/Convergence/AugmentedLagrangianContactReferenceConvergence is missing a markdown file.
  The page should be located at modules/contact/doc/content/source/convergence/AugmentedLagrangianContactConvergence.md
  A stub page can be created using using the './moosedocs.py generate' command
Control this message using: 'log_missing_markdown' 
```

https://civet.inl.gov/job/2540128/

**Comment by joshuahansel** [comment]
Ok I'll fix now. And then try to find why this didn't show up before.

**Comment by joshuahansel** [comment]
Fix: https://github.com/idaholab/moose/pull/29046

**Pull request merged**
