### PR TITLE
Fix error in mean thermal expansion coefficient calculation in SolidMechanics

### LINKED ISSUE #8375: Fix error in mean thermal expansion coefficient calculation in Solid Mechanics
### Description of the enhancement or error report
When transitioning a few BISON thermal expansion models to Tensor Mechanics (TM) that use the mean thermal expansion calculation it was found that TM and SM version exodiffed when soft linking to the SM gold file.  As is the results for timestep 1 are identical between TM and SM and then the diff grows as time progresses. The small error was found in the SM thermal expansion coefficient calculation in Solid Mechanics (in both SolidModel.C and ConstitutiveModel.C).

Update the solid mechanics models and regold the tests.

Fix up comments in the TensorMechanics formulation. 

### Rationale for the enhancement or information for reproducing the error
Ensure consistency between both TM and SM methodologies as the migration continues. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Impacts BISON and Grizzly.

### PR DESCRIPTION
**Pull request by gambka**
Closes #8375

@bwspenc

### CODE REVIEW

**Review by bwspenc — COMMENTED** [review]
Looks great, and this is a big improvement!  Let's see what the carnage is on the BISON and Grizzly tests now.

**Comment by bwspenc** [comment]
OK, I see why Grizzly is not diffing.  Let's investigate why the BISON tests aren't diffing like we expected before we merge this.

**Comment by permcody** [comment]
DO NOT MERGE! We have a critical error in the TestHarness. We are in the process of reverting - we will retest your PR as soon as it's in.

**Review by bwspenc — APPROVED** [review]
This all looks good.  We'll merge this early tomorrow and put in a BISON commit to update those diffing tests.

**Comment by bwspenc** [comment]
The failing BISON tests are expected.  We're ready to patch BISON, so I'm going to merge this now.

**Pull request merged**
