### PR TITLE
Do not use serialization when using PBS

### LINKED ISSUE #14955: --pbs options broken due to pedantic behavior
## Bug Description
When using PBS, the QueueManager asks for all jobs preparing to run within the test spec file group, so that it may compute the total run time needed for that group. -This is how we used to run jobs in general. As a group. We now serialize all jobs.

Due to the serialization of jobs, and the fact that the QueueManager is still assuming it will launch these jobs as a group using one qsub script, we run into some problems. First, the walltime is way off, as it only computed max_time for one test. Second, and this is a bit more bizarre and will require investigation; The QueueManager is building multiple qsub launch scripts (one for each test in the group). And each consecutive qsub launch script beyond the first, has their walltime set to zero.

We need to basically not do serialization when performing PBS options. We can only have one .previous_test_results.json file sitting in the test spec file location upon group completion. Remember; the TestHarness, when doing PBS work, launches additional TestHarnesses in that test spec file directory (as a qsub launch script), to perform ./run_tests **once**. Right now, we are running into a scenario like the following:

```bash
cd some/test/specfile/location
./run_tests --re=testA  # contents of testA.qsub
./run_tests --re=testB  # contents of testB.qsub
./run_tests --re=testC  # contents of testC.qsub
```
...executed all at once. The result, is that the initial TestHarness, will only see results for which test took the longest to complete, and therefor completed last (.previous_test_results.json is clobbered). The other tests, will have no results at all. Leaving the TestHarness explaining to the user that those tests are LAUNCHING.

## Steps to Reproduce
Create a test spec file with multiple tests, and a max_time set. The resulting qsubs walltime will not be a concatenation of all test's max_time. And only the last test has results. A failure in fact, because the walltime is zero (PBS Killed your job due to exceeding walltime).

## Impact
PBS is failing for any test spec file with multiple tests

### PR DESCRIPTION
**Pull request by milljm**
Attempt to fix PBS by avoiding serialization behavior, while using PBS features.

Closes #14955

### CODE REVIEW

**Comment by milljm** [comment]
I just ran a test in moose/tests... and I do not get the same results as I do in another app... more testing is needed.

**Comment by dylanjm** [comment]
@milljm Hi Jason, does this need a reviewer or are there still changes to be made for this PR?

**Comment by milljm** [comment]
There are still some changes that need to happen. Things got busy with GitLab being upgraded and all. I'll hopefully get some time to get back into this PR.

**Comment by bwspenc** [comment]
@milljm Just chiming in to pester you about this. We haven't been getting usable reports from our assessment testing for a long time now because of this, so we would love to get this taken care of. This isn't an emergency, but it is a high priority for us to get that fixed.

**Comment by milljm** [comment]
Have you guys tried to use my branch? This seems to work for moose/tests.

**Comment by bwspenc** [comment]
I haven't.  @dylanjm may have.

**Comment by milljm** [comment]
I received a report where this has solved their issue.

**Comment by dylanjm** [comment]
This branch is working for the nightly runs now as well.

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
