### PR TITLE
3D versions added to coal mining example.

### LINKED ISSUE #10279: Add 3D example to TensorMechanics coal-mining example
## Rationale

Mostly to show that we can do realistic 3D models!

## Description

A 3D version of the existing 2D models.

## Impact

Advertising(?)

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #10279

### CODE REVIEW

**Comment by WilkAndy** [comment]
7MB of that is an input mesh.  Help!

**Comment by WilkAndy** [comment]
The test associated with this PR is
```
  [./coarse]
    type = RunApp
    input = 'coarse.i'
    check_input = True
  [../]
```
I thought "RunApp" + "check_input=True" was always super fast - just basically checking the input file parses ok.  Yes?  No?

**Comment by permcody** [comment]
Unfortunately no, we only parsed the input file the first time around but found that we had a lot of false negatives that way. Input files almost always parse, unless there are silly syntax errors. What we want to do with check only is see if we can actually instantiate the objects you need to run the problem. That means that we have to do things like read the mesh. It's quite a bit more than just reading the mesh.

Question, is your mesh 7MB because it captures some fine geometry or did you already pre-refine it? I ask because you could check in a course mesh then refine it after you read it which would really help here.

**Comment by WilkAndy** [comment]
Removing various things now....

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for the merge, @permcody ,

a

**Pull request merged**
