### PR TITLE
[WIP] Tensor mechanics geometric scaling

### PR DESCRIPTION
**Pull request by tophmatthews**
#14119

### CODE REVIEW

**Comment by tophmatthews** [comment]
@bwspenc we talked a while back about doing mesh scaling for thermo-mechanical problems so that we can get away from extreme axial mesh refinement in long in skinny meshes. You thought (correctly) that the anisotropy would lead to bad convergence. However, I'm super stoked about the capabilities with automatic scaling, and the new avenues it's opened up (thanks @lindsayad).  I've implemented this for thermal solves, really just through modifying `ADHeatConduction`
```
  ADRealVectorValue v = ADDiffusion<compute_stage>::precomputeQpResidual();
  v(0) *= _scaling_vector(0);
  v(1) *= _scaling_vector(1);
  v(2) *= _scaling_vector(2);

  return _thermal_conductivity[_qp] * v;
```
Without scaling, you were right, convergence was terrible. However, with automatic scaling, convergence is just as good with an un-scaled mesh.

I've done extensive testing in `heat_conduction` module, and the next step is `tensor_mechanics`. I can get it to work for a 3D problem by scaling `ADStressDivergenceTensors`
```
ADReal residual = _stress[_qp].row(_component) * _grad_test[_i][_qp] * _scaling_vector(_component);
```
Unfortunately, I'm struggling to get this working for axisymmetric or r-spherical. I think it has to do with the strain calculation...but I'm not sure. Can @bwspenc or @sapitts help me out with the implementation? I think this can really be a game-changer, but I could be missing something.

The other pieces that (I think) have to be updated are integrated BC's, and integral postprocessors.

**Comment by tophmatthews** [comment]
This works already for thermo solves @dschwen, it's just the mechanical pieces. help!

**Comment by lindsayad** [comment]
Have you taken into account that in non-cartesian coordinate systems your integral contains e.g. the r-coordinate? For your formulation do you need to make sure that that is scaled too?

**Comment by tophmatthews** [comment]
No, that is what I'm missing. I was hoping to get some tensor mechanics experts to help with those pieces so I don't miss something.

**Comment by tophmatthews** [comment]
Thermal pieces have been spun off to #14125

**Comment by sapitts** [comment]
@tophmatthews since it's going to take me a while to get up to speed with the AD world and where we handle the different coordinate assumptions, here's the relevant docs on the residual calculation in the stress material in case you've haven't seen it already: https://mooseframework.inl.gov/source/kernels/StressDivergenceRZTensors.html

**Pull request closed without merging**
