### PR TITLE
Upgrade submodule to petsc-3.11.2

### LINKED ISSUE #13471: Upgrade PETSc submodule to PETSc-3.11.2
## Reason

PETSc-3.11.x is released a couple of week ago. Some users already require to use this new release. It is good idea to update submodule support to this when 3.10.5 is our Default PETSc.
 
## Design

Update PETSc submodule

## Impact

Everyone who wants this new feature.

### PR DESCRIPTION
**Pull request by fdkong**
Closes #13471

This requires libmesh PR in https://github.com/libMesh/libmesh/pull/2147

### CODE REVIEW

**Comment by tophmatthews** [comment]
@fdkong @permcody There was a lot of talk with @acasagran @novasr and others this past week about different results from different petsc versions across different installations on clusters. It seems that using petsc as a submodule may help ensure everyone is on the same petsc version at the same time. What is the suggested usage of submodule vs self-install?

**Review by lindsayad — APPROVED** [review]

**Comment by fdkong** [comment]
> @fdkong @permcody There was a lot of talk with @acasagran @novasr and others this past week about different results from different petsc versions across different installations on clusters. It seems that using petsc as a submodule may help ensure everyone is on the same petsc version at the same time. What is the suggested usage of submodule vs self-install?

`PETSc submodule` is a cutting-edge version of PETSc (we are moving to PETSc-3.11.x right now) that mostly intends being used by MOOSE developers or advanced users. One of the reasons having `PETSc submodule ` at this point is gradually patching MOOSE/libMesh/PETSc during  the transition period. We do have discussed this topic a while ago; whether we are going to have everybody to use the same PETSc submodule. However, I do not think we are going to do this in the near future. The reason is that it is too much to require regular MOOSE users install their own PETSc when you consider PETSc itself needs to carry a ton of external packages such as parmetis, Metis, etc. 

OK,.., now let me back to your original questions now:  

What do you mean by "different results"? Different convergence histories? Different physics solutions?

Possibly reasons:

(1) Some changes of default solver parameters in PETSc.  We did not see this much from PETSc-3.8.x, PETSc-3.9.x, to PETSc-3.10.x so far.   You could check the log of  PETSc changes here https://www.mcs.anl.gov/petsc/documentation/changes/index.html.

(2) External package changes. For example, you could get a different mesh partitions using different versions of PETSc since PETSc has different external packages  from version to version. We carefully check this when upgrade PETSc in MOOSE. Civet will check all tests.  We did not see noticeable changes so far (upgraded to PETSc-3.10.5 one week).

(3) Unstable discretization of your equations. We have seen a lot before. At some point (a year ago), one moose-based application has troubles on superlu_dist. Different runs (with exactly the same everything),  give different results. We spent so much energy on that to dig in to the heart of super_dist. It turned out that the system from the physics was super ill-conditioned and unstable  (caused by large element aspect ratios).  The differences come from the machine truncation errors. The machine truncation errors should not cause any problems if the physic is stable. After that, we start testing two versions of PETSc against all moose tests and moose-based application tests in order to guarantee  no unstable tests will be added into the moose ecosystem.  Here is some discussion in PETSc as well https://www.mcs.anl.gov/petsc/documentation/faq.html#different. 

My personal suggestion right now is that try to figure out why you have different answers on different PETSc versions (even worse different installations). Using one particular version of PETSc is not a right solution since you will have troubles again in a future version of  PETSc.  If I have to guess, most likely your formula or discretization is unstable since you get different results on different installations (with the same PETSc). There are definitely other possibilities.  We are happy to help you out on this issue if you need anything.

**Comment by lindsayad** [comment]
I would be curious to know what the convergence checks are for the inputs that give different results with different PETSc versions and/or different architectures. I wonder perhaps whether most of those are using the convergence checks of `FEProblem` vs `RefereceResidualProblem`. My guess/hope would be that most of the inputs that have things like csv or exodus differences are using `FEProblem` since a lot of BISON type problems don't use variable scaling and hence you may very well converge one variable without converging the other. A fix would for this would be to use variable scaling or to catch the golden snitch of automatic scaling which is not trivial but should be explored.

For inputs in which the non-linear solve converges with one petsc version/architecture and doesn't in another, then this is likely due to the poor linear conditioning that @fdkong referenced. The antidote for this may also largely be based on variable/automatic scaling.

**Comment by tophmatthews** [comment]
> `PETSc submodule` is a cutting-edge version of PETSc

Thanks for the response @fdkong. It's hard to know what the best petsc version to use is, so I guess the getting starting instructions which use 3.9.4 should be followed for now.

> The reason is that it is too much to require regular MOOSE users install their own PETSc when you consider PETSc itself needs to carry a ton of external packages such as parmetis, Metis, etc.

I recently did a cluster install, and using the petsc module was cleaner than using an external package installation location. Having a submodule almost seems easier?

> What do you mean by "different results"? Different convergence histories? Different physics solutions?

These are good questions, and maybe motivate some off-line discussions with @acasagran once he determines exactly where the problem lies, eg is it timestep sensitivity.

> (1) Some changes of default solver parameters in PETSc. We did not see this much from PETSc-3.8.x, PETSc-3.9.x, to PETSc-3.10.x so far. You could check the log of PETSc changes here https://www.mcs.anl.gov/petsc/documentation/changes/index.html.

This is very helpful information, and sounds like we should be using >= 3.8? @acasagran was comparing to 3.6.3, which if I remember correctly, had some serious issues that were fixed in 3.8.3

> (3) Unstable discretization of your equations.

This is still a primary issue I would guess, and motivates @lindsayad comments, ie "The golden snitch"!

**Comment by fdkong** [comment]
> Thanks for the response @fdkong. It's hard to know what the best petsc version to use is, so I guess the getting starting instructions which use 3.9.4 should be followed for now.

The easiest way is to check what civet is using.  We actually should put this on our website. Right now, PETSc-3.10.5 is default. However, other versions such PETSc-3.8.x, PETSc-3.9.x  work as well.

**Comment by lindsayad** [comment]
> It's hard to know what the best petsc version to use is

In terms of robustness/consistency of a user solve, there should be no "best". They should all work the same from the user perspective (while perhaps better using cpu/memory resources behind the scenes as you update/upgrade PETSc). The fact that we're not seeing this means there is work for us as PETSc users to do; the problem really does not lie with PETSc.

**Comment by tophmatthews** [comment]
> The fact that we're not seeing this means there is work for us as PETSc users to do; the problem really does not lie with PETSc.

I agree. It seems to me that differing values from different petsc packages hints at something fundamentally wrong with the problem setup, or timestep sensitivity, etc, much like you have both pointed out.

**Pull request merged**
