### PR TITLE
Add base_name to generate_output tensor mechanics master action

### LINKED ISSUE #13860: Allow the tensor mechanics master action to use base_name when generating output
## Reason
The tensor mechanics master action automatically generates useful aux kernels for outputting parameters during mechanics simulations. `base_name` is sometimes used to separate different regions, or mechanics. `generate_output` should use `base_name` to generate the respective output.

## Design
Make `generate_output` use `base_name`

## Impact
Better enhancement of the tensor mechanics action

### PR DESCRIPTION
**Pull request by tophmatthews**
Adds the capability to use a base name in the master action output generation
Closes #13860

### CODE REVIEW

**Comment by dschwen** [comment]
Missing gold file

**Comment by tophmatthews** [comment]
whoops...

**Comment by tophmatthews** [comment]
Want to take a look now @dschwen or @bwspenc ?

**Review by dschwen — APPROVED** [review]
LGTM

**Pull request merged**
