### PR TITLE
Emit an error when using a private parameter in an input file.

### PR DESCRIPTION
**Pull request by brianmoose**
Output parameter group name in --dump

refs #7655

### CODE REVIEW

**Comment by permcody** [comment]
I'd prefer that we don't allow this at all. We should turn this into an error! Do that and let's see what breaks. If it's just Yak/Rattlesnake, we'll force them to fix it. I think BISON may already be fixed.

**Comment by friedmud** [comment]
Yeah.

I've abused this myself in the past... but I agree: it shouldn't be allowed.  Private _means_ private.

**Comment by brianmoose** [comment]
BISON, YAK, and MAMMOTH all have problems when that turns into an error.

**Comment by YaqiWang** [comment]
That is expected...I can work on a fix. Can you give me a full report on the error?

**Comment by brianmoose** [comment]
The errors are on the job page https://www.moosebuild.org/job/57359/
Note that it just shows the first access to a private parameter. I looked at one of the test `.i` files and it had quite a few accesses.

**Comment by sapitts** [comment]
I'll take a look at the failing BISON tests and see if I can get away with just changing the parameter types from private to in an advanced group for now later this week.

**Comment by permcody** [comment]
Thanks @sapitts and @YaqiWang. This is important to fix up.

**Comment by YaqiWang** [comment]
FYI, Yak MR #693 will fix Yak for this PR. I will be working on MAMMOTH fix.

**Comment by YaqiWang** [comment]
Fix in MAMMOTH is simple and ready, but we will need a yak submodule update first with that fix. Will let you know when all done.

**Review by permcody — APPROVED** [review]
Looks good @brianmoose!

**Comment by brianmoose** [comment]
Thanks @YaqiWang both Yak and MAMMOTH passed. That just leaves BISON.

**Comment by sapitts** [comment]
Well, Bison passes now but there's a file that failed in Yak now; @YaqiWang  would you take a look at Yak and let me know if I need update something in Bison (mammoth passed though!).  thanks!

**Comment by YaqiWang** [comment]
Ah, sorry, we recently merged in this test.

**Comment by permcody** [comment]
Nice work everyone! Thanks!

**Pull request merged**
