### PR TITLE
Ensure that RestartableTypesChecker::execute is executed  (#5392)

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by friedmud** [comment]
This is a weird diff (not your fault... just that git did an odd job of matching up changes!).

Now that I look at this test... it's weird.  It's using a Steady executioner... WITH RESTART... which is probably not a good idea.  We should really change it to use Transient... but whatever.

This change looks fine to me for now.

**Comment by friedmud** [comment]
Thanks for putting this in!

**Comment by permcody** [comment]
I also vote for changing the Executioner, just so it doesn't get skipped if
we make any further changes to the TestHarness or framework. This one runs
because we actually don't need recover for this test to work.

**Comment by snschune** [comment]
@permcody Are you referring to issue #5398 ?

**Comment by permcody** [comment]
No, I'm talking about just this one test where we are manually running this checker object and making sure the reads and writes are sane. It runs just fine as a `Steady` solve because it's just exercising this object. I'd rather switch the executioner to a Transient solve just because "recover" on a Steady solve doesn't make sense.

**Comment by friedmud** [comment]
Yep

**Pull request merged**
