### PR TITLE
To include natural boundary condition in INSAD

### PR DESCRIPTION
**Pull request by doquang**

### CODE REVIEW

**Comment by lindsayad** [comment]
Hi @doquang. Can you rebase so that only the contents of [a2509dc](https://github.com/idaholab/moose/pull/26827/commits/a2509dc338b153945b9af09d86772122f834dab2) appear on this PR?

**Comment by doquang** [comment]
I am trying. I am not sure that I am doing it right.

**Comment by GiudGiud** [comment]
git fetch origin
git rebase origin/devel

**Comment by doquang** [comment]
Thanks @GiudGiud ,

I do not know why my github also included the commit from you "Add option to avoid reading the file on construction". I tried to revert it. Could you help to verify that it is ok or not.

**Comment by GiudGiud** [comment]
Yeah it s weird. I think maybe you started your pull request from next instead of devel. 

You can go

git rebase -i origin/devel too and delete commits that are not needed by replacing pick with d

**Pull request closed without merging**
