### PR TITLE
Add face gradients to functor material properties

### PR DESCRIPTION
**Pull request by GiudGiud**

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
Would it make sense to have the variable's `adGradSln(const FaceInfo & fi)` method call this new global function? Then when @grmnptr wants to change the way we do non-orthogonal correction, he only has to do it in one place? (I think he wants to change that IIRC)

**Comment by GiudGiud** [comment]
If we do that then we need to merge the caches for functors and the caches for variables.
Note that we cache both the corrected and uncorrected gradients in variables, and dont cache any gradient (and probably would only cache the second) for functors.

at the end of the day the question is:
while we really do not envision functor material properties not being used as functors (and therefore dont need to duplicate utilities), do we envision finite volume variables not being used a functors / being accessed through the initial APIs (like in CNSFV)?

**Comment by lindsayad** [comment]
I think I'd like to see over time less calls on variable objects and see our users using just the functor methods. Currently we do not cache face gradients by default and my last memory of profiling face gradient caching was that it actually led to slower code. So we could start with only implementing caching of the elemental gradients for functors and not bother with caching implementations for the other argument types. One thing that is problematic is that a single cache clearance schedule controls all caching behavior, and we've seen over time that for finite volume we'd like to default to caching cell gradients but not face values. We could add more atomic methods for scheduling cache clearance on a per-method basis.

Anyway as I said over time I don't want to see variable objects being used in user code, but if you don't want to take the time right now to make that change, that's understandable.

**Comment by GiudGiud** [comment]
Well if you dont mind, I d like this one to go in without the gradient caching transition. I worked on this to let Joe use a functor matprop for his porosity. And it's lame but when Peter reworks the gradient orthogonal correction we may know more again about what we need so we can wait for that

**Comment by GiudGiud** [comment]
@lindsayad coverage borked itself but otherwise this is good to go

**Review by lindsayad — APPROVED** [review]
I want to implement https://github.com/idaholab/moose/issues/20629 but that will also involve cleanup in other areas so I'm fine with this going in as is

**Pull request merged**
