### PR TITLE
Postprocessor late bind

### PR DESCRIPTION
**Pull request by permcody**
@YaqiWang - This should work for most applications but not for Yak. Apparently you are inspecting a lot more of the system than you thought you were during the `add_postprocesor` task. Can it be fixed? Maybe, you'll have to work with me. Let me know if you want to pursue getting this in the code base. I think it's a pretty good improvement over what we have an removes the deficiencies you pointed out, but it might still not work for you.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Will take a closer look.

**Comment by permcody** [comment]
Before you take a look, you'll need this patch in Yak:
```
diff --git a/src/base/YakApp.C b/src/base/YakApp.C
index 0403f13..5aeedd5 100644
--- a/src/base/YakApp.C
+++ b/src/base/YakApp.C
@@ -1031,7 +1031,7 @@ YakApp::registerYakActions(Syntax & syntax, ActionFactory & action_factory)
   // add additional aux-materials
   registerTask("add_aux_material", false);
   addTaskDependency("add_aux_material", "add_material");
-  addTaskDependency("add_postprocessor", "add_aux_material");
+  addTaskDependency("instantiate_postprocessors", "add_aux_material");
 
   registerTask("add_transport_system", false);
   addTaskDependency("add_transport_system", "prepare_mesh");
```

**Comment by YaqiWang** [comment]
everything passes with this patch in yak?

**Comment by permcody** [comment]
No, not even close. Maybe half of the tests do. The problem (as I
suspected) is that the add_postprocessor task has been moved way up. Now
you can't inspect all of the same parts of the system that you were able to
before. It's causing problems.

**Comment by YaqiWang** [comment]
Being busy in writing a conference summary due next Monday. Hopefully I will get time to look into the failing tests thursday or friday. I only want the tests pass. Are the failing crashes or exodiff?

**Comment by permcody** [comment]
@YaqiWang - I am closing this PR for now. Even though it works with MOOSE and modules, it just doesn't work for yak.

**Comment by YaqiWang** [comment]
I do not want to make this change at this moment because it causes a quite painful refactoring in yak. Plus I can bypass this issue easily if I keep this issue in mind. If others want this, we can reactivate it.

**Comment by YaqiWang** [comment]
I cannot remember what that painful refactoring would be... But if this is the right thing to do, I will do it. Is this branch still able to be rebased on devel?

**Comment by permcody** [comment]
I'll see what happens. It's pretty old but it should be workable. I'll see if I can get it cleaned up and reopened.

**Pull request closed without merging**
