### PR TITLE
Update logic for finding MOOSE_DIR in moosedocs.py

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
As found by @lindsayad issue discussed in #9108 was still not correct.

**Review by lindsayad — DISMISSED** [review]
Look at this line reduction!

**Review by lindsayad — CHANGES_REQUESTED** [review]
It looks like you missed `navier_stokes` symbolic link editing...?

I don't know if this is tangential to this PR, but the behavior that I would want is if I execute `moosedocs.py check` in `navier_stokes/doc`, I only really want to see the SQA report for `navier_stokes` (and *maybe* the framework). If this is unreasonable, let me know. After cherry-picking your commit, I see the correct reports now...but I see the reports for all modules, even if I am just running `navier_stokes/doc/moosedocs.py check`. I suppose I am not surprised by this given that we are editing all the symlinks to point to `modules/doc/moosedocs.py`.

**Comment by aeslaughter** [comment]
Dang, my logic is flawed. The behavior you desire is what is supposed to happen. I am glad you checked it. I think the loc with the chdir should be the location that you are running. Let me change it.

**Comment by aeslaughter** [comment]
@lindsayad Give this a try please.

**Comment by aeslaughter** [comment]
If this works for you, I will add some tests for this command.

**Comment by lindsayad** [comment]
I’ll give it a whirl tomorrow morning

**Comment by lindsayad** [comment]
Yep, this works beautifully!

**Review by lindsayad — DISMISSED** [review]

**Comment by aeslaughter** [comment]
Cool, let me add some tests for the various methods of running the command

**Comment by lindsayad** [comment]
@aeslaughter Are you done with adding tests?

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
