### PR TITLE
Makefile fix for external FP submodule inclusion

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #27027

### CODE REVIEW

**Comment by GiudGiud** [comment]
ugh commit 2 fixes something but breaks another. 
I ll leave only commit  1 for now

**Comment by loganharbour** [comment]
I think we probably need a sanity check from a few for this one

**Comment by GiudGiud** [comment]
This does not solve the header symlink warnings btw (which are caused by SodiumRevision.h being created in every module when building combined, for some reason)

But it should solve the missing "SinglePhaseFluidProperties.h" include when building the modules inside combined apps we have seen in the apptainer recipes

**Comment by loganharbour** [comment]
Looks like this breaks things: https://civet.inl.gov/job/2442762/

**Comment by GiudGiud** [comment]
Seems to be tied to the revision, the other problem. I invalidated to see if it gets it past
```
In file included from /data/civet1/build/blue_crab/build/unity_src/base_Unity.C:2:
/data/civet1/build/blue_crab/src/base/BlueCrabApp.C: In member function 'virtual std::string BlueCrabApp::header() const':
/data/civet1/build/blue_crab/src/base/BlueCrabApp.C:253:50: error: 'SODIUM_REVISION' was not declared in this scope; did you mean 'HELIUM_REVISION'?
  253 |   os << std::setw(25) << "  Sodium version: " << SODIUM_REVISION << "\n";
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  HELIUM_REVISION
Compiling C++ (in opt mode) /data/civet1/build/blue_crab/build/unity_src/timesteppers_Unity.C...
Compiling C++ (in opt mode) /data/civet1/build/blue_crab/build/unity_src/postprocessors_Unity.C...
make: *** [/data/civet1/build/moose/framework/build.mk:150: /data/civet1/build/blue_crab/build/unity_src/base_Unity.x86_64-pc-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....

ERROR: exiting with code 2
```

**Comment by GiudGiud** [comment]
Trying to fix the other issue too again

**Comment by GiudGiud** [comment]
Ok should be good.

The only fail is Okami, so I'll look to patch Okami most likely

**Comment by GiudGiud** [comment]
Okami patch is up  https://hpcgitlab.hpc.inl.gov/idaholab/okami/-/merge_requests/42

this is good to go

**Comment by loganharbour** [comment]
moosebuild.hpc.inl.gov has been off for a while; need to get that back going

**Comment by milljm** [comment]
https://moosebuild.hpc.inl.gov is back online

**Comment by GiudGiud** [comment]
let's merge? stuff is failing downstream because this is not in
https://civet.inl.gov/job/2462068/

**Review by permcody — APPROVED** [review]

**Comment by GiudGiud** [comment]
Unrelated failure

**Pull request merged**
