### PR TITLE
Move use_displaced_mesh = true to Kernels #10158

### PR DESCRIPTION
**Pull request by ghost**
Hello,

I got an error as I was running the tutorial of the tensor_mechanics module (<http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/BasicTutorial/basics_part_2/>):

    *** ERROR ***
    The parameter 'GlobalParams/use_displaced_mesh' is a private parameter and should not be used in an input file.

I moved the setting to `TensorMechanics` in the `Kernels` block, and it now works.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Some comments:
 - you might have to ```use_displace_mesh=true``` in other places in this input file - i'm not sure without checking
 - this input file might benefit from using the newer TensorMechanics Action.  It more easily includes the AuxVariables like von Mises stress.

Perhaps you'd like to tackle this?  Or ask someone like @sapitts ?

**Comment by brianmoose** [comment]
Also, so we catch things like this in the future, it would probably be a good idea to put a `tests` file in that directory that does at least a
`check_input = True` for each of the input files.

**Comment by sapitts** [comment]
@broncodev you'll need to add a new issue (we don't have one open currently for updating the tensor mechanics tutorial input files) and then reference that issue number in your commit message.  Let me know if you need help with sorting this out.

@WilkAndy I agree, these tutorials could definitely be made more user friendly with the use of the tensor mechanics master action; however, in order to do that, we would also need to update the written tutorial instructions [here](http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/BasicTutorial/basics_part_1/).  These changes are probably much more extensive than @broncodev wants to make in a first commit, so I'll take that on once this commit is merged.

@brianmoose thanks for the tests file reminder; we'll get that in asap.

**Comment by broncodev** [comment]
@sapitts This would be my issue report:

> Title: Update tensor_mechanics tutorial input files
> Contents:
> ## Rationale
> I was asked to create this issue based on #10141 (related to updating tensor_mechanics tutorials)
> 
> ## Description
> Originally, one of the parameters gave an error. There seems to be a need to update the tutorial and possibly create tests for it.
> 
> ## Impact
> - Tests become broader
> - Users get better tutorials

@WilkAndy  Thanks. I am just starting to use the module (and MOOSE as a whole), so I don't know what you mean by TensorMechanics Action, but thanks for letting me know.

**Comment by sapitts** [comment]
@broncodev that issue description looks pretty good to me; you might change the rationale section to 'updating the tensor mechanics tutorial files'. Go ahead an create a new issue with your message.

Once you have the new issue number, you should modify your commit message with that issue number (see the [Contributing Instructions](mooseframework.org/wiki/Contributing/) under Making modifications for formatting the moose guys expect ( I use `git commit --amend` for these sorts of changes).

Thanks for helping us improve MOOSE!

**Comment by broncodev** [comment]
@sapitts Done. For posterity, I think that the link to Contributing should be: http://www.mooseframework.org/wiki/Contributing/

**Comment by sapitts** [comment]
Thanks @broncodev

**Comment by sapitts** [comment]
@broncodev you'll need to update the commit message for your commit on your machine and then repush your branch to rerun the testing system.  The testing scripts don't look at the title of the merge request for the issue number.

**Comment by broncodev** [comment]
@sapitts Finally! I had never done this. I hope it's fine now.

**Comment by broncodev** [comment]
Note to self:
(after creating a new branch to issue a pull request, if the commit message needs to be changed)

1. Stash your local changes, saving un-staged files (on your local branch, e.g. master) [a, c]
2. Checkout remote branch [a, c]
3. Ammend the commit message [b]
4. Push branch
5. Stash pop (to go back to your original branch, e.g. master) [c]

[a] https://stackoverflow.com/a/1304645
[b] https://coderwall.com/p/_thg9a/reword-a-git-commit-message, https://stackoverflow.com/a/10317152
[c] https://stackoverflow.com/questions/1304626/git-switch-branch-and-ignore-any-changes-without-committing#comment9430641_1304645

**Comment by brianmoose** [comment]
Might want to squash those commits, I don't think we need 5 commits for a one line change....

**Comment by permcody** [comment]
@broncodev - You can amend the commit message by typing "git commit --amend". One command, very simple.

**Review by permcody — APPROVED** [review]

**Comment by broncodev** [comment]
> You can amend the commit message by typing "git commit --amend". One command, very simple.
@permcody I appreciate it. I have done that before. It was my first time trying to do it on the web UI.

I had the "wonderful" idea of modifying the file on the website of GitHub (I had never done that). This created a branch called patch-1 (which I never expected to have to modify). One cannot amend the title directly on the web (you can change the title, but at least I don't know how to push again). This led me in the path of self-laceration. I also did not want to bother any of you and went astray looking for the solution myself. Needless to say that I had done changes in my local repo already.

**Comment by permcody** [comment]
Editing on the website has it's limitations. We've all tried it but it doesn't give you enough flexibility. I squashed your commits for you and merged them.

**Pull request merged**
