### PR TITLE
Dependency Comparator (backwards compatible attempt)

### PR DESCRIPTION
**Pull request by roystgnr**
This is another try at resolving #8659, but this time hopefully without triggering broken user code like #8662 (a.k.a. the first commit here) did.  Instead of sorting otherwise-independent objects by name, we keep track of when they're added to the comparator and we sort by addition time.  This ought to come up with the same ordering as the most typical result of sorting-by-shared_ptr, but should do so 100% of the time rather than occasionally switching orderings depending on how malloc feels on any particular day, which fixes a #1500 failure for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
Damn.  I can reproduce that FSP test failure, but I don't yet understand it.  I had been hoping it was just another #1500 failure that wouldn't recur with a non --enable-parmesh libMesh build.

**Comment by permcody** [comment]
It's probably another system that isn't specifying dependencies. I've created a monster...

**Comment by roystgnr** [comment]
Yeah, it looks like the add_preconditioning action is getting called before the add_field_split action.  If I'm right then this is a one-line fix.

You still definitely ought to swap less-than for greater-than in my new comparator at some point and fix the hundred-odd *other* things which break, though.

**Comment by permcody** [comment]
I definitely will but it'll probably be awhile. I actually like what you've done here. You've created a "StableDependencyResolver", that's a really useful utility.

**Review by permcody — APPROVED** [review]
Looks good, Thanks!

**Pull request merged**
