### PR TITLE
Implements makeParamRequired

### LINKED ISSUE #11383: makeParamRequired is defined but never implemented
## Rationale

The public template function `InputParameters::makeParamRequired` is defined but never implemented. This leads to linking error at compilation time when trying to use it.

## Description

The error can be reproduced by any call to `InputParameters::makeParamRequired`. This can be simply fixed by providing the default implementation in InputParameters.h

## Impact

Allows users to actually use `InputParameters::makeParamRequired`, thus improving the flexibility of the `InputParameters` system.

### PR DESCRIPTION
**Pull request by agiorla**
Implements `InputParameters::makeParamRequired`, which fixes the linking error when trying to call that function.

Closes #11383

### CODE REVIEW

**Comment by permcody** [comment]
@agiorla - This looks fine, but we are requiring test cases at a minimum for new functionality. Could you create a test object (one that's part of the moose_test application) or select an existing one and create a test for this?

**Comment by agiorla** [comment]
@permcody Sure I'll see what I can do, no problem.

**Comment by permcody** [comment]
The reason that this doesn't exist is because there's actually a workaround. You can "re-add" the parameter as required as long as the name and type match the original declaration. I'm fine with this enhancement, but just letting you know that there is another way to make MOOSE force a requirement parameter.

**Comment by agiorla** [comment]
@permcody  I didn't know that the parameter could be re-added. If you prefer me to use the work-around, I'm fine with that (but then I believe that the definition of `makeParamRequired` should be removed, just to prevent someone from trying to use it). I would prefer to keep it as it seems to be more intuitive than having to redeclare it, but I can use the work-around as well if needed.

**Comment by permcody** [comment]
You are absolutely right that it should be removed if it's not going to be implemented. Please feel free to do whatever you feel makes the most sense for your case.

**Review by permcody — CHANGES_REQUESTED** [review]
Thanks for the contribution. I left a few minor comments. 

We are starting to enforce documentation and other keywords at the MOOSE level to get new code in. Every single new class has to be documented within MooseDocs: http://mooseframework.org/moose/utilities/MooseDocs/index.html

Also, for something new and simple like this we should be striving to put in all of the new required SQA keywords as well "design, requirements, issues (optional)". 

I realize this is a lot to ask, so I'm happy to have a MOOSE team member finish this up on your behalf unless you want to give it a go. Take a look at the documentation and the test on a recently merged PR here if you'd like: https://github.com/idaholab/moose/commit/db55503b6bd83582ee64b4266d81f2b84c9e4fda

**Comment by agiorla** [comment]
@permcody I'd like to give it a try. I'm interested to know how MOOSE manages all the documentation system. I will try to do that this week.

**Comment by permcody** [comment]
Great! If you need help or want to hand it off, let me know.

**Comment by agiorla** [comment]
@permcody I am not sure where the documentation for these classes would go, given the fact that the doc folder for the test app seems pretty empty. Would that be in test/doc/content/documentation/systems/Kernels ?

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
BadRequiredParamsKernel should be a unit test - not a regression test (i.e. go in [mooserepo]/unit/src)

**Review by rwcarlsen — APPROVED** [review]

**Review by permcody — APPROVED** [review]

**Pull request merged**
