### PR TITLE
Introduce UserObjectInterface API to AD objects

### PR DESCRIPTION
**Pull request by lindsayad**
Refs #5658

### CODE REVIEW

**Comment by lindsayad** [comment]
I was just thinking...and this is kind of unfortunate timing given our training that we just did...but perhaps what should have been done is to rename member template functions (to something like `getUserObjectTempl`) and then to name the macro `getUserObject` so that users experience the exact same interface 😦 The same thing could be done with `getMaterialProperty`, `getParam`, etc. It's getting late to make this change, but if we ***do*** want to make this change we should make it immediately as the AD train continues to pick up steam.

@idaholab/moose-team @dschwen

**Comment by dschwen** [comment]
I think that's a great idea. We could leave the old ad macros in for a while and issue a `#warning` and later an error with a helpful hint

**Review by aeslaughter — APPROVED** [review]

**Comment by permcody** [comment]
I'm definitely in support of renaming things. We need consistency. It'll be worth the temporary pain right now.

**Comment by fdkong** [comment]
Vote for the consistent interface

**Comment by dschwen** [comment]
Would you create a separate `ADUserObjectInterface` class for those (I think that'd be my preference), where getUserObject is a macro? Or would you just change it in `UserObjectInterface`?

**Comment by lindsayad** [comment]
> Would you create a separate `ADUserObjectInterface` class for those (I think that'd be my preference), where getUserObject is a macro? Or would you just change it in `UserObjectInterface`?

I would do it in `UserObjectInterface`. If I created a new class (`ADUserObjectInterface`) and defined a template method `getUserObjectTempl` and then created the macro `#define getUserObject this->template getUserObjectTempl`, then we'd have an issue if someone was inheriting from `UserObjectInterface` and calling `getUserObject` if the `ADUserObjectInterface` header is included somewhere. Right...?

**Pull request merged**
