### PR TITLE
Verification test for phase field model of structural phase transformation with elasticity

### LINKED ISSUE #9079: Add a test for structural phase transformation with elasticity
### Description of the enhancement or error report
We will add a verification test for phase field model of structural phase transformation with elasticity. 

### Rationale for the enhancement or information for reproducing the error
The effects of elastic anisotropy and different types of eigenstrain on the shape of second phase particle can be verified and compared with analytical solution.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
N/A.

### PR DESCRIPTION
**Pull request by yipenggao**
### Complete each of the following items before creating a PR

We add a verification test for phase field model of structural phase transformation with elasticity.

The effects of elastic anisotropy and different types of eigenstrain on the shape of second phase particle can be verified and compared with analytical solution.

Closes #9079

### CODE REVIEW

**Comment by yipenggao** [comment]
Sorry, this is my first time creating a PR. So I just add a new inputfile for simplicity.

The inputfile works well in my local system, but it fails for one of the above test (App tests:linux-gnu). What should I do to get it passed? Or someone will help me solve the problem?

Thanks.

**Comment by permcody** [comment]
@yipenggao - That failure is not your problem. Mammoth is getting patched now.

**Comment by brianmoose** [comment]
@yipenggao I invited you to join the "MOOSE Users" GitHub team. Once you accept the invitation then your PRs will automatically be tested.

**Review by dschwen — CHANGES_REQUESTED** [review]
This should have the changes you made to `LandauPhaseTrans.i` applied, too. (use TensorMechanics/Master action, move `displacements` into `[GlobalParams]`, remove `z` stuff from Mesh params, fix timestepper, etc.)

**Comment by yipenggao** [comment]
All things are fixed, thanks. :)

**Comment by dschwen** [comment]
> All things are fixed, thanks. :)

No... they are not. In fact none of the points I raised are addressed. Did you forget to commit the changes?

**Comment by yipenggao** [comment]
@dschwen 

... You are right.. I commit it this time. Thanks.

**Review by dschwen — APPROVED** [review]
👍

**Pull request merged**
