### PR TITLE
Adds ability to append date to output files

### LINKED ISSUE #6001: Append date to output files
I would like an option to append the date to the outputted file's name from a simulation (ie. input_out_11252010.csv). Im not sure what make more sense, the date completed or the date started.

### PR DESCRIPTION
**Pull request by aeslaughter**
This allows the date/time to be append to the file_base, regardless of dollar bracket support via GetPot, this option was deemed useful by the Bison team, so I did it.

(closes #6001)

### CODE REVIEW

**Comment by permcody** [comment]
I'd rather not have two ways to do the same thing, especially since the existing solution is a one-liner. I haven't had a chance to try it out yet but it should just be something like the following block:

```
[Outputs]
   [./exodux]
     type = exodus
     file_base = name_${time()}
   [../]
[]
```

I believe that you can even change the format right inside of the DBE. I would vote that we discard this change.

**Comment by permcody** [comment]
See: https://github.com/libMesh/libmesh/blob/master/include/base/getpot.h#L3038

**Comment by gardnerru** [comment]
I tried file_base = name_${time()} and received test_<<${ } variable 'time()' undefined>>.e this morning. Do I have a syntax issue?

**Comment by permcody** [comment]
Yes you do - Let me see if I can figure it out... Stay tuned

**Comment by permcody** [comment]
Oh you just need to put an equals sign in front of the word time.  That'll
give you seconds since Epoch, I'm not seeing a method to convert that to a
local time but it could be done one way or another. These DBEs are quite
powerful.

```
   file_base = foo_${=time}
```

See:
https://github.com/libMesh/libmesh/blob/master/include/base/getpot.h#L2823

**Comment by permcody** [comment]
Depending on how you are going to parse these later, you might find that seconds since epoch is actually easier than trying to read a human formatted date. You just read in the numbers and Bam! you have time in the easiest possible format.

**Comment by novasr** [comment]
wait, what? i get some number when i try this, but i don't know what it means. i'd like to have year_month_day or something like that.

**Comment by permcody** [comment]
http://www.epochconverter.com/

I'm sure we can get you something more human friendly though

**Comment by novasr** [comment]
Ah. This might be enough. Thanks!

**Comment by jwpeterson** [comment]
> http://www.epochconverter.com/
> 
> I'm sure we can get you something more human friendly though

I predict the world will end at 9999999999.

**Comment by permcody** [comment]
Well there are no simple formulas for converting epoch to a date without library methods to help because of leap years, months with different days, etc. So writing a little formula in your input file is not reasonable: 
http://howardhinnant.github.io/date_algorithms.html

Personally, I'd like to see std::localtime added to our existing getpot DBE expression list so that we can just ask for the localtime and pass a format string:

```
   file_base = foo_${localtime %y_%m_%d}
```

What do you think @roystgnr?

**Comment by roystgnr** [comment]
The usual standardsy way to do things is three part: std::time() to get the POSIX time, std::localtime() to convert to structure using local time zone, then std::strftime() (or std::put_time(), but we don't want to require C++11) to convert to ASCII.

The structure step doesn't have a good counterpart in GetPot, so I guess it'd be reasonable to reuse the name "localtime" to do both structure-and-formatting.  I don't think we should squeeze it into all three steps, though; it might be useful to be able to get strings with more than just the current time.  So the common syntax would be a little longer:

```
file_base = foo_${= localtime %y_%m_%d ${= time} }
```

**Comment by permcody** [comment]
That's reasonable.

I just thought of one more option. I implemented the ability to pass DBE
variables via the CLI so you can use a normal bash function to produce the
date string you want and supply it on the command line in the form of a
variable that you expand in the input file.

$ ./app-opt -i input.i DATE=`date`

Where you have something like this in the input file:

file_base=foo_${DATE}

If you are scripting all of this you could do it either way.

**Comment by aeslaughter** [comment]
As interesting as it is using GetPot, I think for a casual user a simple
input file flag is a much better option.

Imaging, someone in the hall asks you: Can you append time to the output
file name?

The answer will be, yes:
Set 'append_date = true'

-or-

file_base = foo_${= localtime %y_%m_%d ${= time} }

**Comment by permcody** [comment]
I just don't like have several different ways to do the same thing. We have to stop over-designing. First, we have only one customer for this capability, and they plan to do this in their testing so the outputs will be parsed by scripts (not humans) anyway. Has anyone else asked about dates on their output files? 

I really like the idea of adding the ability to pass a format string directly through getpot regardless of the decision here. If the other MOOSE devs want another switch in the outputs block I'm willing to be overruled. At the very least your patch should allow a format string to be passed instead of just saying "true".

@idaholab/moose-developers please vote

**Comment by permcody** [comment]
@roystgnr - I was just looking at https://github.com/libMesh/libmesh/blob/master/src/utils/timestamp.C#L37

It looks like we considered adding a user-defined data string in that utility. Is there a reason it's not available there now? It'd be nice to re-use this routine one way or another (either in @aeslaughter's PR or in the proposed Getpot change.

**Comment by roystgnr** [comment]
I don't think I've ever futzed with timestamp.C - looks like it may be something @dknez added to help with reduced basis code logging?  Adding a pointer-to-format-string parameter (optional, default NULL) sounds like a reasonable extension.

I'd like to be careful about adding new dependencies (especially non-header-only ones!) to getpot.h - we use that in non-libMesh codes with only one line changed: commenting out USE_LIBMESH so that thread/error/etc methods get switched to dependency-free (albeit less useful) fallbacks.

**Comment by aeslaughter** [comment]
It does allow a format string to be passed: 'append_date_format' is a
companion option. My vote is for having traditional option(s), for the
reason of ease of use. If someone looks at the available options for an
Output object, they will see that there exists a means for adding the date.
The GetPot method, which we should also support for more generic
specialized reasons, is too obscure for general users.

That being said, I don't want too dwell on this since this is such a minor
feature, I will go with the others votes.

**Comment by andrsd** [comment]
I do not like the dollar notation. The `append_time` and `append_date_format` is more human-readable and friendly. Maybe, we can get rid of `append_time` and turn that on when `append_date_format` was specified in the input file.

**Comment by gardnerru** [comment]
I can understand the concern of having too many ways to do something but
let's face it, there are multiple ways to do pretty much everything in real
life and most people will pick the easiest. This feature was asked for to
complete a project that has been dragging on. I believe that we will be
able to use the getpot as is, but the other method is more user friendly
and easier to implement from our project stand. (append_date can be passed
in from the command line to append to the already existing output name.)

On Wed, Dec 2, 2015 at 8:20 AM, David Andrs <notifications@github.com>
wrote:

> I do not like the dollar notation. The append_time and append_date_format
> is more human-readable and friendly. Maybe, we can get rid of append_time
> and turn that on when append_date_format was specified in the input file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/6008#issuecomment-161330149>.
>



-- 
Russell Gardner
Fuels Modeling and Simulation
Idaho National Laboratory
PO Box 1625
Idaho Falls, ID 83415-3840
208-526-2970

**Comment by roystgnr** [comment]
I prefer the DBE notation, but my definition of "user friendly" is idiosyncratic enough that my vote probably shouldn't be counted, or possibly should be counted negatively.

**Comment by jwpeterson** [comment]
> I don't think I've ever futzed with timestamp.C - looks like it may be something @dknez added to help with reduced basis code logging?

I added this, originally for the PerfLog.

As for the vote, my opinion is that this type of syntax:
```
file_base = foo_${= localtime %y_%m_%d ${= time} }
```
is almost ludicrously over-complicated, something that no one will be able to remember how to use without digging up an old input file to copy/paste it from.  Another obvious problem with this approach over the "seconds since epoch approach" is: what if you want to have two saved outputs from the same day for the same problem?

So, I would vote for Andrew's approach where you can simply append time with a flag, however I'd argue for the seconds since epoch format instead of month-day-year.  My other gripe with this PR is that you snuck (yes @permcody, snuck) in the deletion of an otherwise-unrelated deprecated parameter in the same commit...

**Comment by aeslaughter** [comment]
I can remove the deprecated removal, it was a "while you're in there"
moment.

**Comment by roystgnr** [comment]
Disambiguating (and avoiding overwriting of!) files generated on the same day can be critical, but it might be more user friendly to use ISO times rather than Unix epoch times.

2015-12-02T09:56:25-0600

Looks a lot hairier than 

1449071785

but the latter has no interpretation without context whereas the former is obvious at a glance.

**Comment by friedmud** [comment]
I'm a bit late to the party (end of the semester crunch!) but I will actually throw in a vote for a nice simple option like "append_time"... DBE is unnecessarily complicated for such a normal request.

I definitely want a human readable option.

I can actually see myself using this rather a lot...

**Comment by aeslaughter** [comment]
I will fix this up later today, by adding UTC time as default and breaking
up the deprecated stuff.

**Pull request merged**
