### PR TITLE
Add post-processor feature to compute difference over entire transient

### PR DESCRIPTION
**Pull request by joshuahansel**
The post-processor `ChangeOverTimestepPostprocessor` was generalized to be able to measure changes with respect to a post-processor's initial value instead of just to its previous time value. It was renamed to reflect this. See Issue #10327.

### CODE REVIEW

**Comment by joshuahansel** [comment]
This is expected to fail with RELAP-7 due to the rename of the post-processor. Other apps may fail for the same reason, though I'm not sure if any other apps use it.

**Comment by andrsd** [comment]
Our standard practice in cases like this is that we deprecate the old class and give users time to fix their input file. Then we come in and remove the class.  If the differ just in the name, you can make the deprecated one inherit from the new one (to avoid code duplication) - for example.

**Comment by joshuahansel** [comment]
@andrsd Ok, thanks for the info, I'll try your inheritance suggestion.

**Comment by andrsd** [comment]
If the inheritance approach works, then put `mooseDeprecated` in the c-tor with a message how users should update their input file. You can also add a date there when the old class will be removed.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
