### PR TITLE
Please inspect but do not merge

### PR DESCRIPTION
**Pull request by WilkAndy**
This is a small start to the porous_flow module.  Before we contribute an enormous chunk of work, perhaps people would like to inspect and critique this small piece of code.

Refs #6740

### CODE REVIEW

**Comment by WilkAndy** [comment]
Tagging @cpgr

**Comment by aeslaughter** [comment]
I looked at the code quickly, generally it seems to be well-documented. However, I don't really care for "PorFlow" as a prefix. I would prefer something more verbose: "PorousFlow", for me the short-hand isn't worth saving three letters. In my own "level_set" module I plan on using the "LevelSet" prefix instead of "LS" to be complete and avoid all ambiguity.

**Comment by WilkAndy** [comment]
Thanks @aeslaughter .   I think this is related to #6746 .   I think we'll change to PorousFlow.  Our class names are so huge :-(

**Comment by dschwen** [comment]
Thanks to autocomplete long class names are not a big problem. I second
Andrew's comment.

**Comment by jwpeterson** [comment]
I see that the title has already been changed once wrt WIP/not WIP.  @WilkAndy are you wanting the CI to run with every commit or no?

**Comment by dschwen** [comment]
I changes the title. On GitLab adding `[WIP]` disables the merge button, but it didn't work here :-(

**Comment by dschwen** [comment]
There also seems to have been some rebasing foobar...

**Comment by jwpeterson** [comment]
According to @brianmoose, adding WIP on GitHub will disable Civet.  I see that this PR doesn't pass the pre-check, though, so probably not that big of a deal.

**Comment by WilkAndy** [comment]
Yea, this is definitely work in progress.  I'm going to close this PR now as i don't think anyone is reading the code as it gets dribbled in.  Hopefully tomorrow or soon after we'll be creating a very large PR (currently 35 classes and 30 tests, but there will be more today) so brace yourselves!

**Pull request closed without merging**
