### PR TITLE
Adding support for validation into test harness

### PR DESCRIPTION
**Pull request by andrsd**

### CODE REVIEW

**Comment by permcody** [comment]
The BISON team has taken a different approach to this. They use the `-i` flag to tell the TestHarness which files to process (e.g. "assessment" vs "tests). We also use the `-i` flag to run TestHarness test cases that are designed to fail etc. This PR instead adds a new flag that's intended to be used in the existing "tests" files to filter them out. This is somewhat inconsistent. Are you opposed to going the existing route and putting your validation cases in a new file of your choosing like "validation"?

**Comment by andrsd** [comment]
* For our validation needs, there are measurements for tests done by, let's say, facility A and they did several runs and produced different sets of data. So, we want these grouped in one dir. Then, another facility did some other types of measurements, so we want those in one place.  So, we would not have one `tests` file with all tests. If I understand correctly the `-i` flag, it takes just one file, right?

* `Tester.py` already has `validation` and `verification` flag, where the comment says "Set to True to mark test as a validation|verification problem".  But this flag is not used for anything right now. We also have a "heavy" parameter and we run those tests by adding "--heavy", so it made sense to me to add this `--validation` flag that would behave like `--heavy`. If that is not the plan for this flag, fine, but  we would like to be able to execute all tests that have the `validation' parameter set to True. Similarly, for verification in the future.

Those are the ideas behind these changes...

**Comment by permcody** [comment]
> If I understand correctly the -i flag, it takes just one file, right?

Currently yes, but it would be trivial to change that.

> Tester.py already has validation and verification flag, where the comment says "Set to True to mark test as a validation|verification problem"  

😮, I don't remember why/what that's there for

> We also have a "heavy" parameter and we run those tests by adding "--heavy", so it made sense to me to add this --validation flag that would behave like --heavy.

True, and that's a little bit unfortunate. The heavy flag has never worked quite like I want it. When we run with heavy we still run the normal test cases. With the validation flag, would you run the test cases and the validation cases like heavy? 

With the separate file, it's pretty easy to completely partition things. It would be nice to come up with a single system for "filtering" but as you've pointed out we already have a bit of a mess. Perhaps the answer to whether you want it completely partitioned or if you want to add the validation cases can help us decide here. I just really don't like the two very different ways of running validation cases.

**Comment by aeslaughter** [comment]
The documentation for the "verification/validation" parameters in Tester.py is out-of-date, these parameters actually are markdown filenames.

Use:
https://github.com/idaholab/mastodon/blob/devel/test/tests/kernels/time_integration/tests

Result:
https://mooseframework.inl.gov/mastodon/sqa/mastodon_vvr.html

**Comment by aeslaughter** [comment]
We had a discussion about this as a team and we don't want another flag for running subsets of tests. We determined that the TestHarness should include a "tags" or "groups" parameter that has a very specific set of options: i.e., heavy. The important thing is that these flags need to be known and controllable at the moose level, so when running tests without arguments you can see if something is skipped and why. This will avoid having tests that never run without some sort of information.

**Comment by permcody** [comment]
Closing this PR as we plan to work towards a more consistent solution that will yield more information about tests that aren't normally run for all/any project.

**Pull request closed without merging**
