### PR TITLE
Finite Shell Strain - Total Global Strain Fix

### PR DESCRIPTION
**Pull request by Zoophish**
Very small fix in Tensor Mechanics: all I've done is added the total global strain conversion to ADComputeFiniteShellStrain.C.

This was thankfully pointed out by @neuphris [here](https://github.com/idaholab/moose/discussions/22460#discussioncomment-3963151), but doesn't appear to have been added to master yet.

Without the total global strain conversion, the global strains remain at zero, which messes a lot of our work up. The code for the conversion is identical to that in [ADComputeIncrementalShellStrain](https://github.com/idaholab/moose/blob/983b61fc7768602c010e223b8b1fa0c8cc128070/modules/tensor_mechanics/src/materials/ADComputeIncrementalShellStrain.C#L259).

### CODE REVIEW

**Comment by recuero** [comment]
Could you add a test that meaningfully exercises your fix?

**Comment by bwspenc** [comment]
@Zoophish I'm interested to hear that you're using the shell elements, and it sounds like you're having some amount of success. I'm curious -- are you modeling any curved geometries with the shells? We realized that the current shell formulation, which has 2 rotational DOFs, doesn't really work for curved geometries because the rotational DOFs are defined in the local coordinate system, which varies from element to element except for the case of a regular mesh of a flat structure. We spent quite a while this last summer re-working the shell formulations to have 3 global rotational DOFs/node, and then transform those into the local coordinate system. We have gotten decent results from that model, but still have some lingering frustrating issues that have prevented us from merging the code in yet. I have it on a branch on my repository:  https://github.com/bwspenc/moose/tree/shell_new

If you look around there, you'll see that it's still kind of messy (we had 2 or 3 different versions of the model where we were trying out various things). We were only focusing on the incremental version, not the total version you have this proposed fix for.

I'd need to look a little more carefully at your proposed change, but it is likely the right thing to do. We do need test cases for this to demonstrate that it's doing the right thing before we merge it in, though, as @recuero pointed out.

It might be good to find a time to talk about what you're doing with the shells so we can coordinate our efforts.

**Comment by Zoophish** [comment]
@bwspenc Thanks for your reply. We are trying to use shell elements for composite laminate structural simulations using equivalent single layer theory. So far we've just been using flat coupons for validation tests, but we will likely want to use curved geometries in the future. I have been trying to investigate how the local coordinate system works with shell elements since this is particularly important for getting the layups correct, so I'm very interested to see how the new formulation affects this.

I'll also look into adding a test for this and I'm open to any suggestions on how this should be done.

**Comment by j-bowhay** [comment]
@recuero @bwspenc I would be very keen to see a fix for this. To hopefully unblock this I have opened https://github.com/idaholab/moose/pull/25268 which cherry picks these commits and adds a test. I would be grateful if you could take a look.

**Pull request closed without merging**
