### PR TITLE
Various ray_tracing enhancements

### LINKED ISSUE #16320: Change RunApp RayTracingMeshOutput tests to Exodiff
## Reason
Currently some of the tests in `modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output` use `RunApp` instead of `Exodiff` because we cannot enforce partitioning using `MeshGenerators`.

## Design
Use grid partitioning for these tests once it is compatible for these tests.

## Impact
More rigorous testing.

### LINKED ISSUE #16999: Support ray-dependent data in RepeatableRayStudy
## Reason
Currently, the data values passed in to RepeatableRayStudy get assigned to all rays. We should have the capability to supply data to each ray, independently. 

## Design
The parameters `initial_ray_data` and `initial_ray_aux_data` should be of type `std::vector<std::vector<Real>>` to provide data for each ray.

## Impact
Added capability.

@fdkong

### LINKED ISSUE #17001: Do not require definition of "rays" within RayTracingObject
## Reason
The `rays` parameter within the `RayTracingObject` specifies which rays that the object will apply to. If one wants to apply the object to all rays, they have to list all of the possible ray names.

## Design
Allow the `rays` parameter to be optional, and if it is not provided apply to the object to all rays.

## Impact
Can reduce the size of input files when wanting to apply a RayKernel/RayBC to all rays.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #16999, closes #17001, and closes #16320.

### CODE REVIEW

**Comment by loganharbour** [comment]
@fdkong, this allows for ray-dependent data initialization, for example:

```
[study]
  type = RepeatableRayStudy
  names = 'pipe0_ray0 pipe0_ray1'
  start_points = '0 0 0
                  1 0 0`
  end_points = '1 0 0
                1 1 0`
  ray_aux_data_names = 'pipe_id start_distance'
  initial_ray_aux_data = '0 0;
                          0 1'
[]
```

Will be the case where you have a pipe that goes from (0, 0) -> (1, 0) and then (1, 0) -> (1, 1):
- `pipe0_ray0` from (0, 0) -> (1, 0) with initial data `pipe_id` = 0, `start_distance` = 0
- `pipe0_ray1` from (1, 0) -> (1, 1) with initial data `pipe_id` =  0, `start_distance` = 1

**Comment by fdkong** [comment]
It would be great if we could read `start_points` and `end_points` from a file.

When you have many points, you do not want to put all point coordinates in the input file.

**Comment by loganharbour** [comment]
> It would be great if we could read `start_points` and `end_points` from a file.
> 
> When you have many points, you do not want to put all point coordinates in the input file.

I considered that, but I think in that case you would want to just create your own study. If we added that, we would also need to add support for all (or at least some) of the other parameters via file.

**Review by GiudGiud — APPROVED** [review]
i like that you can define different data on each ray now

**Pull request merged**
