### PR TITLE
Porous Flow test documentation.

### PR DESCRIPTION
**Pull request by WilkAndy**
The tests themselves have not yet been added to the repo, but adding these now will mean it's easier for people to add/modify doco while the remainder of the code is being added.

Refs #6845

### CODE REVIEW

**Comment by dschwen** [comment]
Are we going to talk about committing Excel sheets to MOOSE? On one hand I guess whatever tool does the job is fine. On the other hand both Excel sheets are basically graphs that could be done using a python script (or IPython notebook) with matplot lib or a gnuplot input. They would be a more open alternative.

Anyhow. Ignore this comment for now. I'd be interested in what other people think about this. We already have five `*.ipynb` IPython notebooks in MOOSE... and - now that I grepped for it for the first time - almost *50* Excel files. 

Mind blown.

**Comment by WilkAndy** [comment]
I really hate excel - it wastes so much of my time.  however, the problem is that it's kind of like pdf: everyone uses it.

a

**Comment by friedmud** [comment]
I'm definitely against Excel.

ipython (Jupytyr) Notebooks are ok - but they age poorly. I would really
prefer just straight Python with CSV data.

**Comment by WilkAndy** [comment]
What i need is:
 - ability to present data graphically
 - ability to load and display MOOSE CSV data
 - ability to manipulate moose csv data - e.g. answer = column1 + column2.
 - ability to encode formulae from analytical solutions, generate data from them and graphically compare with the moose csv data.  All formulae should be easily visible to readers of the file.
 - as simple and self-contained as possible (e.g., not "load this file, then run this script, then load results into another file, then graph the results with blah blah")

If you can point me to your preferred solution i'd be very happy.  It's a good time to implement a non-excel solution as i suspect we'll have maybe 100 excel files by the end of the year and in this PR we only have a few.

a

**Comment by WilkAndy** [comment]
Hold off on merging this for a while why i learn about python+matplotlib, and python+PandasDataframes - to replace the excel

**Comment by WilkAndy** [comment]
Removed the excel files, yippee, in favour of short python/matplotlib scripts.

**Comment by permcody** [comment]
👍

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Pull request merged**
