### PR TITLE
Update TabulatedFluidProperty tests to use provided csv file

### PR DESCRIPTION
**Pull request by cpgr**
As noted in #9286, an old version of a fluid properties data file would cause the test to fail if present, as TabulatedFluidProperties would read it in rather than generate a new file. This isn't seen in the test boxes as they always use a clean environment with no stale fluid property files, but will be an issue with a personal moose installation where these tests have previously been run.

This PR adds csv data files to the tests to make sure that the tests use the newer csv format introduced in #9275. This should ensure that this type of test failure in a personal moose repository doesn't happen again. I also simplified one of the tests to reduce the size of the csv file.

The default file extension in TabulatedFluidProperties has also been updated to csv. 

Refs #9286

### CODE REVIEW

**Comment by permcody** [comment]
> This isn't seen in the test boxes as they always use a clean environment with no stale fluid property files, but will be an issue with a personal moose installation where these tests have previously been run.

@cpgr - I swore we already had the capability to delete arbitrary user files but I just looked through the various testers and can't see that logic. The normal operation of the TestHarness is to delete generated files that we know about (i.e. the names of files you list to compare against in your test specs). It would be trivial to add another option to the Testers where you could provide a list of extra files to delete. Would that help you here?

**Comment by cpgr** [comment]
Yeah, that was my first thought but I couldn't find an option to do that.

**Comment by permcody** [comment]
Well I'd add that option now, but @milljm is in the process of rewriting the entire TestHarness so I don't dare touch it. I suggest you put in a ticket to revisit putting that option in when it becomes available for improved robustness. I'll add the ticket to put that option in, you can reference my ticket so when it closes you can come back to yours.

**Comment by permcody** [comment]
Related #9304, #9307

**Review by permcody — APPROVED** [review]

**Pull request merged**
