### PR TITLE
Make problem verbose to see through Actions and Components

### LINKED ISSUE #25853: Actions and Components obscure the setup of the problem
## Bug Description
In a regular simulation (kernels & bcs directly in the input file), I can see from Debug/show_actions exactly what is happening during the setup. The name of the kernels appear as they are created.

With Components and Actions, I dont know what's being created. The very least I would need would be:
- name
- type

But I would also like to be able to check:
- block / boundary restriction. This could be done AFTER the setup (and I suggest we do that instead)
- which variables are coupled in. This could also be done after

## Steps to Reproduce
Run any simulation with Debug/show_actions with first kernel/bc syntax then with Actions

## Impact
Lack of clarity can defeat user debugging and force developer intervention.

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #25853 

the alternative could be: 
- make the factory verbose when it creates something. 
- make the warehouse verbose when we add something to them

but the problem is the one in the input file so it makes more sense to me to add the option there

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
would it make sense to trigger this off of the `verbose` parameter from the `Executioner` block?

**Comment by GiudGiud** [comment]
yeah maybe but I dont need it for now. I use that other one for automatic scaling

**Comment by GiudGiud** [comment]
does `verbose` percolate to other verbose options?

**Comment by lindsayad** [comment]
I just don't know what we're doing with a `verbose` flag if you actually have to turn on a bunch of other `verbose_` flags to get verbosity. And then a user has to think about verbose flags in multiple input locations

**Comment by dschwen** [comment]
Wer have a debug top level block. But maybe you want to add a "Verbosity System" 🤣

**Comment by GiudGiud** [comment]
MOOSE probably could use a VerbosityInterface given that we need verbose flag everywhere

**Comment by lindsayad** [comment]
I am fine with the new data member and maybe even the new `Problem` parameter. But I think that we should start doing more of this:

> does `verbose` percolate to other verbose options?

**Comment by lindsayad** [comment]
Or alternatively deprecate that parameter

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
