### PR TITLE
Displaced czm

### PR DESCRIPTION
**Pull request by lindsayad**

### CODE REVIEW

**Comment by lindsayad** [comment]
@arovinelli Please play around with this branch and add tests to tensor_mechanics. I'm going to drum up some dummy problem to put in MOOSE test as well

**Comment by arovinelli** [comment]
@lindsayad give me 24hrs. We are reorganizing to telecommute

**Comment by lindsayad** [comment]
Ugh, this `BreakMeshByBlockGenerator` is a mess. Fail the `node_touched_by*` assertion during cloning of the undisplaced mesh with two procs. Gonna do some digging. Looks like a pretty epic dialogue over on #14456

**Comment by arovinelli** [comment]
It should work for replicates meshes...
@roystgnr did some modification to libmesh that should allow it to work for replicated mesh in debug mode.
However i’m not sure we pushed all relevant changes.

Sent from my iPhone

On Mar 16, 2020, at 8:42 PM, Alex Lindsay <notifications@github.com> wrote:

﻿

Ugh, this BreakMeshByBlockGenerator is a mess. Fail the node_touched_by* assertion during cloning of the undisplaced mesh with two procs. Gonna do some digging. Looks like a pretty epic dialogue over on #14456<https://github.com/idaholab/moose/pull/14456>

**Comment by arovinelli** [comment]
@lindsayad this does the job, however I have a question which grad_phi and grad_test does this return? the on of displaced or the on of _undisplaced_mesh. I don't know how to check this specifically

**Comment by lindsayad** [comment]
All the information you have available to you in the interface kernel when
you  set `use_displaced_mesh = true` should be displaced information

**Review by permcody — APPROVED** [review]
Nice work!

**Comment by arovinelli** [comment]
@permcody I was trying add some tests :(

**Comment by lindsayad** [comment]
@arovinelli It should actually be easier this way. You can create a follow-on PR with physics tests. You wouldn't have been able to push commits to my branch

**Comment by arovinelli** [comment]
@permcody @lindsayad make sense.
I'll prepare them with the the czmkernel for displaced CZM

**Pull request merged**
