### PR TITLE
Allow CSV to output VPPs to unique file per nonlinear iteration

### LINKED ISSUE #14618: CSV cannot output VPPs on nonlinear
## Bug Description
CSV creates VPP file names based on the time step index, even if `execute_on` does not just include "initial" and "timestep_end". For "nonlinear" for example, the same file name would be used for each nonlinear iteration.

## Steps to Reproduce
Create a VPP and a `CSV` with `execute_on = NONLINEAR`.

## Impact
Medium priority - execution/output of VPPs on "nonlinear" is useful for debugging convergence difficulties.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #14618

### CODE REVIEW

**Comment by permcody** [comment]
You can't gold non-converged calculations. They'll never match. You need to create a customer comparison file so that you can ignore the actual values.

**Comment by joshuahansel** [comment]
> You can't gold non-converged calculations. They'll never match. You need to create a customer comparison file so that you can ignore the actual values.

> Will fail miserably...

Test debug disagrees with you :P Why do you say that? The iterative method is deterministic, right? It should recover the same iterates each time. The converged solution is just the iterate we usually choose to compare. The satisfaction of the nonlinear residual equation of a given iterate says nothing of reproducibility here.

The only vulnerability I see is if the numerics of the solvers are changed significantly in the future; but then there will be plenty of other tests diffing. The iteration I compare got to |R| = 5.719791e-07 by the way, so you can think of it as a test with a tolerance of 6e-7 that golded the "converged" solution.

The testing of the iterate values was an intended part of the test design; otherwise we'd just be testing that a file of the correct name is created, not that the file contains that iterate's values.

I'll change the test design if you still want, so just let me know.

**Comment by permcody** [comment]
> Test debug disagrees with you :P Why do you say that? The iterative method is deterministic, right? It should recover the same iterates each time. The converged solution is just the iterate we usually choose to compare. The satisfaction of the nonlinear residual equation of a given iterate says nothing of reproducibility here.

Deterministic only for a given architecture, decomposition, and numeric solver. If any of those change you are likely to run into diffs during the iterates. 

> The only vulnerability I see is if the numerics of the solvers are changed significantly in the future; but then there will be plenty of other tests diffing. The iteration I compare got to |R| = 5.719791e-07 by the way, so you can think of it as a test with a tolerance of 6e-7 that golded the "converged" solution.

This isn't our experience. Even a minor change to PETSc can and has caused diffs in the past on nonlinear outputs. We've had to regold similar tests many times in the past. @fdkong can attest to this.

The testing of the iterate values was an intended part of the test design; otherwise we'd just be testing that a file of the correct name is created, not that the file contains that iterate's values.

With a custom comparison file you can test just about anything or conversely, ignore just about anything. For the purpose of this test, aren't you are in fact just verifying the form of the file? The individual values don't really mean anything do they?

I'll change the test design if you still want, so just let me know.

I'm just trying to avoid checking in a brittle test as we've run into many issues with these in the past. I'm going to tag @fdkong, who is on travel and see if he has a better suggestion for you. If however you really don't need to look at the individual values, but just know they do in fact exist and are coming out, I can help you with that.

**Comment by joshuahansel** [comment]
> This isn't our experience. Even a minor change to PETSc can and has caused diffs in the past on nonlinear outputs. We've had to regold similar tests many times in the past.

Ok, I see where my thinking was flawed - though converged solutions are subject to these differences as well, they are less so, since the solution changes between iterations are larger in the beginning iterations. I'll change the test as you suggested. Thanks for catching/explaining it.

**Comment by fdkong** [comment]
What do we want to test?  The convergence history?

We should not assume we will have the same convergence history since there is almost no way to guarantee that.

**Comment by joshuahansel** [comment]
@fdkong Nevermind, I'm not going to check the solution iterate values anymore.

**Comment by aeslaughter** [comment]
Can we do something similar for timestep as we do for time, see https://github.com/idaholab/moose/blob/f068c6df5b7c4da8b2737889d7807ea9b8e2990d/framework/src/outputs/PetscOutput.C#L143

**Comment by YaqiWang** [comment]
Maybe we should rethink using csv to output vector postprocessors. For example, we can use xml to output data like this
```
<VectorPostprocessor name="vpp">
<Entry time="0" nonlinear_iteration="1" picard_iteration="0">
  <x>...</x>
  <y>...</y>
  <z>...</z>
  <id>...</id>
</Entry>
...
</VectorPostprocessor>
```
or if you do not like xml, use some similar format to accommodate possibly irregular data in one file with more flexibility. We really do not have to use csv for vpp.

**Comment by joshuahansel** [comment]
@aeslaughter I don't understand your suggestion - from what I see from the code you highlighted, that is a method of assigning a time value to a nonlinear/linear iteration, but the VPP CSV files don't know of the time value, just the index, right?

@YaqiWang That is a larger suggestion that I will leave to the core MOOSE team, e.g., @permcody. I see your point about all of the files - I don't like that part either. XML capability seems like it could be a good idea, but I would think that removing the VPP to CSV capability would lead to a lot of work (in fixing tests and such - we'd need XMLDiffer, for example, for those tests that test VPP values in a CSV file).

**Comment by permcody** [comment]
We aren't going to change VPP output to XML by default. If somebody really wants that, I could entertain an option for it, but with XML, we'd probably want to supply a differ like Josh suggested and also tools for processing.

**Comment by YaqiWang** [comment]
We need to promote the lines in `PetscOutput` to maintain a *global output time* flattened from real time, nonlinear iteration number, linear iteration number, picard iteration number and so on, which can be used by Outputs like Exodus, CSV, etc. This will need executioner to inform output system what need to be activated (I have not thought of how output system and executioner interact carefully). The flattening algorithm needs to be carefully documented so that users know what the time in output mean. I think @aeslaughter is suggesting to possibly use this output time in the file name for vpp to make it extensible.

One single format can supporting indexing of the data is preferred, if we can have full control on the format (not like Exodus and CSV, where we can do with only time). Note I am not saying we have to use XML although I think it is a good candidate. Creating a differ is necessary and actually can be done quite quickly. ISOXML in Rattlesnake is using RapidXML and we had a simple differ added in ISOXML.

**Comment by aeslaughter** [comment]
@joshuahansel What I was trying to suggest was perhaps create a timestep() function used by output that could be used to provide fake timesteps to the output objects like it provides a fake time. That way all filenames that used timestep will get this feature.

**Comment by aeslaughter** [comment]
> We aren't going to change VPP output to XML by default. If somebody really wants that, I could entertain an option for it, but with XML, we'd probably want to supply a differ like Josh suggested and also tools for processing.

There is already an XML differ [XMLDiffer](https://github.com/idaholab/moose/blob/5f3097ccc6c3be7961fa79861308c7e4cc1634b0/python/TestHarness/XMLDiffer.py) and we already have tools for reading VPP data.

The multiple files are very annoying, you get one for every VPP object and every time step. So even with CSV output you need a script to processes it. A single XML file would require the same tool requirement without having a million files.

**Comment by joshuahansel** [comment]
@permcody In light of @aeslaughter's comments, it sounds like XML might be a good option for VPPs. I'd be fine with waiting for that capability instead of making these CSV changes - the nonlinear iteration VPP capability is not urgent for me.

**Comment by aeslaughter** [comment]
You can follow #14634; the basic features are there I just need to finish it up. I will hopefully get back to this next week.

**Comment by joshuahansel** [comment]
Closing in favor of #14634.

**Pull request closed without merging**
