### PR TITLE
Translate parsed function output relative to master app. 

### PR DESCRIPTION
**Pull request by aprilnovak**
This offsets the point used to evaluate a `ParsedFunction` according to any output position set for the app. 

## Reason
This is needed in Cardinal to allow us to split out multiple Nek simulations but set ICs based on their position within a master application.

## Design
This adds a `use_app_offset_position` parameter to `MooseParsedFunctionBase` and adds a `getOutputPosition` function that translates a provided point in the app's x,y,z frame to that in the master app. To make as little infrastructure changes as possible, I just used the existing `getOutputPosition` feature in `MooseApp`, which is technically only turned on if `output_in_position` is true in the `MultiApp`. So the current design will _not_ use an offset position if you do

```
[MultiApps]
  [sub]
    ...
    app_type = MooseTestApp
    output_in_position = false
  []
[]
```

(i.e. `output_in_position = false`). If there's a preference to have this parsed function offset even if `output_in_position` is false, this PR just requires a bit more modifications. 

## Impact
Allow greater flexibility in parsed function usage for ICs and BCs in Cardinal simulations.

Closes #18699

### CODE REVIEW

**Review by GiudGiud — COMMENTED** [review]
@fdkong @lindsayad 
we have been talking about a general coordinate mapping like this for multiapp. See issue #12293
It ll be coming next FY. 
How urgent is this @aprilnovak ? And is this the only capability you are looking for here or will there be more PR around this capability?

**Comment by GiudGiud** [comment]
Ok thinking of closing. @fdkong can you double check that we will be covering this need next FY?

**Comment by GiudGiud** [comment]
Ok I m not convinced we will cover this next FY in the end. I think we will focus on mapping subapps to main app locations when transfering, not for functions. 

However, I am reluctant to approve this because:
- seems that this should be a parameter that lives in Function, not just ParsedFunction
- it breaks the multiapp paradigm that subapps do not know they are subapps and behave the exact same as if they are main app
The second point is the bigger one. Do you have to be calling functions from the subapps? Or could you create a field in the main app and transfer the values to the subapps?

**Comment by aprilnovak** [comment]
> Do you have to be calling functions from the subapps? Or could you create a field in the main app and transfer the values to the subapps?

Yes, I suppose this could be done by sending to each multi-app the x, y, z coordinates at which it is centered, with perhaps three `MultiAppVectorPostprocessorTransfer` to send x, y, and z. To me, having this shift in `ParsedFunction` isn't _hugely_ breaking the notion of multi-apps not knowing they are a multi-app - they still don't really know they are a sub-app. This proposed change just exposes the already-available app offset to `ParsedFunction`.

But I realize this may be a rather fringe feature. I really only wanted this feature for testing purposes, and ended up going another route while this PR waited for review. So it doesn't set me back if you think the design isn't right.

**Comment by fdkong** [comment]
How urgent you need this feature?

**Comment by GiudGiud** [comment]
let's say I have a pebble at 0,0,0.1 in the main app.
I represent this pebble with a 0.03 cm spherical mesh. This mesh has to originate at 0,0,0 in the subapp referential, because the spherical coordinates of 0,0,0.1 are 0.1, 0, pi/2 and working the mesh from there is just going to be complicated

**Pull request closed without merging**
