### PR TITLE
Loosen tolerances on DisplacementAboutAxis for Intel

### PR DESCRIPTION
**Pull request by sapitts**
The tests for the DisplacementAboutAxisBC exodiff failed on the Intel compiler when [testing the master branch](https://www.moosebuild.org/job/18573/).  In two tests I loosened the tolerances for exodiff and in the other I removed the offending post processors

No code design changes are included in this commit.

Refs #6484

### CODE REVIEW

**Comment by jwpeterson** [comment]
Your `nl_rel_tol` for this test is already pretty small, but you might be able to push it a bit further.  For example:
```
../../tensor_mechanics-opt -i torque_reaction_cylinder.i
```
prints:
```
Time Step  2, time = 0.5
                dt = 0.25
 0 Nonlinear |R| = 3.860252e+04
      0 Linear |R| = 3.860252e+04
      1 Linear |R| = 2.212771e+04
      2 Linear |R| = 1.123281e+04
 1 Nonlinear |R| = 1.123112e+04
      0 Linear |R| = 1.123112e+04
      1 Linear |R| = 8.001880e+03
      2 Linear |R| = 4.522402e+03
      3 Linear |R| = 2.612839e+03
      4 Linear |R| = 1.253229e+03
 2 Nonlinear |R| = 1.253152e+03
      0 Linear |R| = 1.253152e+03
      1 Linear |R| = 7.982969e+02
      2 Linear |R| = 3.956000e+02
      3 Linear |R| = 2.212434e+02
      4 Linear |R| = 1.653328e+02
      5 Linear |R| = 7.258870e+01
      6 Linear |R| = 2.608064e+01
 3 Nonlinear |R| = 2.607843e+01
      0 Linear |R| = 2.607843e+01
      1 Linear |R| = 1.342605e+01
      2 Linear |R| = 6.391353e+00
      3 Linear |R| = 3.890041e+00
      4 Linear |R| = 2.304706e+00
      5 Linear |R| = 1.431335e+00
      6 Linear |R| = 8.026748e-01
      7 Linear |R| = 3.265160e-01
      8 Linear |R| = 1.459947e-01
      9 Linear |R| = 6.215445e-02
     10 Linear |R| = 3.562990e-02
 4 Nonlinear |R| = 3.565110e-02
      0 Linear |R| = 3.565110e-02
      1 Linear |R| = 2.266862e-02
      2 Linear |R| = 1.331235e-02
      3 Linear |R| = 6.478325e-03
      4 Linear |R| = 3.176772e-03
      5 Linear |R| = 1.646553e-03
      6 Linear |R| = 6.567530e-04
      7 Linear |R| = 3.188298e-04
      8 Linear |R| = 1.785093e-04
      9 Linear |R| = 9.368474e-05
     10 Linear |R| = 6.244103e-05
     11 Linear |R| = 3.419386e-05
     12 Linear |R| = 1.842197e-05
     13 Linear |R| = 7.210813e-06
     14 Linear |R| = 2.340406e-06
     15 Linear |R| = 8.701408e-07
     16 Linear |R| = 4.228941e-07
 5 Nonlinear |R| = 9.468857e-07
 Solve Converged!
```

You might be able to avoid the diffs by making `nl_rel_tol` 1.e-12 or so...

**Comment by sapitts** [comment]
I tightened the tolerances for the 3D case to ```nl_rel_tol = 1.e-12``` and ```nl_rel_tol = 1.e-11``` for the cylinder case because 1e-12 would not converge; thanks for the advice.

**Comment by jwpeterson** [comment]
OK, no guarantees if it will even work, we'll let CIVET tell us...

**Comment by permcody** [comment]
👍

**Pull request merged**
