### PR TITLE
output the number of adjacent grains for each grain

### PR DESCRIPTION
**Pull request by PengWei97**
## Reason

In the evolution of grain growth, output the number of grains adjacent to each grain, that is, the topology information of grain growth simulation.

## Design

1. In `FeatureFloodCount`, add `adjacent_grain_id` in `FeatureData` to store the ID of adjacent grains for each grain, and create `createAdjacentGrainMap` to build `adjacent_grain_id`.
2. In `FeatureFloodCount`, get the number of adjacent grains through `getAdjacentGrainNum`.

## Impact

No effect on related code.

### CODE REVIEW

**Review by permcody — CHANGES_REQUESTED** [review]
See comments on Conversation thread.

**Comment by PengWei97** [comment]
Hi @permcody, Thank you very much for your thoughtful reply. Please forgive me for modifying your code without permission.

> Can you clarify for me which of these you are really after since your code also seems a bit conflicted?

I modified your code for two purposes, the first is to output the number of adjacent grains per grain, which I think is an important piece of information in grain growth simulation, and refer to [Longqing chen's article](https://www.sciencedirect.com/science/article/pii/S1359645402000848?casa_token=dlU_qBPrdw8AAAAA:kH0sYFrKzPza6-wh8d0ZeygOqkr28Evbl401vj6PcQqOOGx7LkTKVCPchNqzNAAV02phB-Joxk9E). 

The second is that I need to construct the anisotropic of grain boundary energy and grain boundary mobility based on the grain boudary misorientation between grains, as said in [the jianbao gao's article](https://www.sciencedirect.com/science/article/pii/S1359645421008697). However, the existing `GBAnisotropy` in moose is based on the order parameter and is not related to the grain orientation (euler angles). This is also why I build adjacent grain ID vectors in FeatureData for each grain or feature, which I thought might be of use.

> The FeatureFloodCount class is not designed to output stable grain (or feature) IDs over time. It's simply designed to be a counter.

Yeah, I also read [your doctoral dissertation](https://ui.adsabs.harvard.edu/abs/2017PhDT........31P/abstract) carefully, but please forgive me that I don't have much basic knowledge, and there are a lot of questions that I don't understand. However, there are two points in your dissertation that I think are more important to me, the first is `All of the global information is maintained and processed on a single rank with all of the remaining ranks having minimal local to global mapping information.` in 3.5 Scalable Parallel Design, the second is `Generally however, it is also useful to maintain unique grain identifiers that are fixed over the lifetime of the simulation, which can be used to query individual grain properties such as orientation.` in 4.4 The GrainTracker Postprocessor. So I think each grain ID (`_id`)is kept constant during the simulation, which is different from the order parameter ID (`_var_index`). 

> If you want a stable topology each time step, your logic will need to be moved down to the GrainTracker class (and associated interfaces).

Nice, I'll try to put the code I'm adding now in `FeatureFloodCount` into `GrainTracker` or create a new class for this purpose.

> Please let me know if you need any further guidance or have other questions regarding your implementation. 

Good, thank you very much for your kind help. I will raise my questions promptly and look forward to your further guidance.

**Comment by permcody** [comment]
> Hi @permcody, Thank you very much for your thoughtful reply. Please forgive me for modifying your code without permission.

No need for permission ahead of time, this is an open source project.

> I modified your code for two purposes, the first is to output the number of adjacent grains per grain, which I think is an important piece of information in grain growth simulation, and refer to [Longqing chen's article](https://www.sciencedirect.com/science/article/pii/S1359645402000848?casa_token=dlU_qBPrdw8AAAAA:kH0sYFrKzPza6-wh8d0ZeygOqkr28Evbl401vj6PcQqOOGx7LkTKVCPchNqzNAAV02phB-Joxk9E).

> The second is that I need to construct the anisotropic of grain boundary energy and grain boundary mobility based on the grain boudary misorientation between grains, as said in [the jianbao gao's article](https://www.sciencedirect.com/science/article/pii/S1359645421008697). However, the existing GBAnisotropy in moose is based on the order parameter and is not related to the grain orientation (euler angles). This is also why I build adjacent grain ID vectors in FeatureData for each grain or feature, which I thought might be of use.

I realize that the objects in the `phase_field` module are rather complex, but we do have the ability to get the Euler angles for every grain in the simulation. There's an entire system devoted just to supplying these angles. We can supply them via a file, or generate them randomly. There's an interface here [GrainTrackerInterface](https://github.com/idaholab/moose/blob/next/modules%2Fphase_field%2Finclude%2Fpostprocessors%2FGrainTrackerInterface.h) that we implement in a few different variations of the GrainTracker object. One of the methods [getVarToFeatureVector](https://github.com/idaholab/moose/blob/643a67e5fb765188d7837257362ea194a26de6c6/modules/phase_field/include/postprocessors/GrainTrackerInterface.h#L43) is probably what you are looking for. This method can be called on every element in the domain and it will return a vector of lenth "num_order_parameters", and be populated with grains IDs that are active at that location and an "invalid ID" for every order parameter that is zero (within tolerance). With those IDs, you can recover the unique grain ID and thus any attributes associated with that grain (such as Euler Angles and several other pieces of information). You should be able to calculate anything you need from that method. 

We use this method in several different materials and user objects to calculate forces and other quantities which are critical to the evolution of your microstructure. Here's an example of how we use that vector in one of of these classes: [Using getVarToFeatureVector](https://github.com/idaholab/moose/blob/cad31de97181316a6f3038a4165f4edb76074558/modules/phase_field/src/userobjects/ComputeExternalGrainForceAndTorque.C#L76).

> Yeah, I also read [your doctoral dissertation](https://ui.adsabs.harvard.edu/abs/2017PhDT........31P/abstract) carefully, but please forgive me that I don't have much basic knowledge, and there are a lot of questions that I don't understand. However, there are two points in your dissertation that I think are more important to me, the first is All of the global information is maintained and processed on a single rank with all of the remaining ranks having minimal local to global mapping information. in 3.5 Scalable Parallel Design, the second is Generally however, it is also useful to maintain unique grain identifiers that are fixed over the lifetime of the simulation, which can be used to query individual grain properties such as orientation. in 4.4 The GrainTracker Postprocessor. So I think each grain ID (_id)is kept constant during the simulation, which is different from the order parameter ID (_var_index).

All correct! I would recommend you take a look at the GrainTracker tests here [grain_tracker_test])https://github.com/idaholab/moose/tree/cad31de97181316a6f3038a4165f4edb76074558/modules/phase_field/test/tests/grain_tracker_test). I've purposely made these all very small so they run quickly on a single processor (or a few processor cores) on a laptop. If you visualize the various fields, you can watch both the order parameters and unique ID fields. You'll see one is stable and the other changes very dynamically. However, you can always recover the stable field with the methods in the `GrainTracker`.

One other object that may be of interest is [FeatureVolumeVectorPostprocessor](https://github.com/idaholab/moose/blob/cad31de97181316a6f3038a4165f4edb76074558/modules/phase_field/src/vectorpostprocessors/FeatureVolumeVectorPostprocessor.C). This object dumps out a lot of vector data about each grain to a CSV file. Such as the volumes of each grain which is usually of interest in many phase field simulations. You can look at the code to see how the methods in `GrainTracker` are used to get this information. 

I will say that we do not currently print out the number of neighboring grains of a grain anywhere. I don't believe this information is important (although one might argue, it's interesting). Instead, what you usually need is just which grains are active at each integration point in your simulation, which we do have. So, I don't think you need to augment any of the code for what you are doing so far. 

I'm tagging @dschwen in case he can point you to other relevant examples or classes for you to take a look at as you learn these systems.

**Comment by PengWei97** [comment]
ok, thank you so much~~

> One of the methods `getVarToFeatureVector` is probably what you are looking for. This method can be called on every element in the domain and it will return a vector of lenth "num_order_parameters", and be populated with grains IDs that are active at that location and an "invalid ID" for every order parameter that is zero (within tolerance). 

Yeah, I also saw the code related to `getVarToFeatureVector` in the `ComputePolycrystalElasticityTensor` object, 
```c++
const auto & op_to_grains = _grain_tracker.getVarToFeatureVector(_current_elem->id());
``` 
If op_to_grains[op_index] is not equal to invalid_id in a FEM element, then op_to_grains[op_index] represents the grain ID, and `*_vals[op_index]` is the corresponding activation order parameter value. In my knowledge, if only one `op_to_grains[op_index] != invalid_id`, only one order paramater is activated, then it means that it is inside a certain grain. If there are multiple [op_index] != invalid_id` (two in most cases), and multiple order parameters are activated, then it is represented on the grain boundary. Afterwards, the misorientation on each element is obtained from the Euler angles of their corresponding grain IDs. 

So I want to write my own materials object to achieve grain boundary anisotropy (grain boundary energy and grain boundary mobility) caused by grain boundary misorientation, following `ComputePolycrystalElasticityTensor` and referring to `GBAnisotropy`.

> I will say that we do not currently print out the number of neighboring grains of a grain anywhere. 

Ok, the adjacent grain ID vector and the number of adjacent grains may not be so important, and it is only necessary to know which grains are activated on each element in simulation.

> grain_tracker_test

Yeah, I have read and simulated the examples under this folder, next I might look at the input-related source code of `GrainTracker`.

> I'm tagging @dschwen in case he can point you to other relevant examples or classes for you to take a look at as you learn these systems.

Nice, I'm also looking forward to some advice from @dschwen.

wei

**Comment by PengWei97** [comment]
Hi @permcody, I'm having some problems trying to construct the grain boundary misorientation anisotropy, and I've also created [my question](https://github.com/idaholab/moose/discussions/20570) in Discussions, looking forward to your help and support.

wei

**Comment by permcody** [comment]
I will take a look tomorrow!

**Comment by PengWei97** [comment]
> I will take a look tomorrow!

**Comment by PengWei97** [comment]
Hi @permcody, I'm having a problem building a model for grain boundary mobility anisotropy determined by misorientation and need your help.

When using the following code to determine grain boundaries,
```c++
  const auto & op_to_grains = _grain_tracker.getVarToFeatureVector(_current_elem->id());  
  std::vector<unsigned int> grainID; // Create a vector of grain IDs
  std::vector<unsigned int> variableIndex; // Create a vector of order parameter indices

  _delta_theta[_qp] = 0;
  for (MooseIndex(op_to_grains) op_index = 0; op_index < op_to_grains.size(); ++op_index)
  {
    auto grain_id = op_to_grains[op_index]; // grain id

    if (grain_id == FeatureFloodCount::invalid_id) // max 4294967295
      continue;    

    grainID.push_back(grain_id); // save the grain id
    variableIndex.push_back(op_index); // the id of the order paramater gr[0-num_op]
  }
```

Only the area shown by the blue double arrow in the figure below can be identified, while the area of the grain boundary is marked by the black double arrow. In other words, in the area marked by the red double arrow, `FeatureFloodCount` only sets a valid grain ID, and the other is invalid, which makes me unable to set the orientation difference on this elem to a valid value .
image

So what I want to ask is, how can I set the second invalid grain ID to be valid, or get another grain ID based on the existing information.

**Comment by dschwen** [comment]
Is there a threshold value for when the grain is considered active? I believe there is.

**Comment by PengWei97** [comment]
Thanks a lot for your answer, I solved it by setting connecting_threshold = 0.02 in `GrainTracker`.

**Pull request closed without merging**
