### PR TITLE
Fix minor issues about empty inputs in HexConCirAdaptBdryMG and exter…

### LINKED ISSUE #19621: HexagonConcentricCircleAdaptiveBoundaryMeshGenerator Cannot Take Empty Inputs/PolygonConcentricCircleMeshGenerator Creates Incorrect External Boundary In A Special Case
## Bug Description
Two minor bugs are identified in the `Reactor` module

- `HexagonConcentricCircleAdaptiveBoundaryMeshGenerator` throws an error if `inputs` and `sides_to_adapt` are not given. This feature is needed in some special cases when this mesh generator is used to generate assembly meshes that do not need to be adaptive to any other meshes.
- In `PolygonConcentricCircleMeshGenerator`, if a background only mesh (i.e., not ring or duct regions) with one single radial element layer is generated, and if a non-trivial `interface_boundary_id_shift` is set, the produced mesh does not have a correct external boundary id.

## Steps to Reproduce

- Using `HexagonConcentricCircleAdaptiveBoundaryMeshGenerator` without `inputs` and `sides_to_adapt` leads to an error because `getMeshes("inputs")` cannot take an invalid `inputs`.
- Using `PolygonConcentricCircleMeshGenerator` without `ring_radii`, `duct_sizes` and with `background_intervals = 1` and a non-trivial (!=0) `interface_boundary_id_shift` leads to incorrect external boundary id (e.g., default correct id = 10000).

## Impact
Cannot make some special reactor meshes straightforwardly.

### PR DESCRIPTION
**Pull request by miaoyinb**
…nal boundary in PolyConCirMG

closes #19621

### CODE REVIEW

**Comment by miaoyinb** [comment]
@eshemon FYI

**Comment by miaoyinb** [comment]
@loganharbour this PR is just to fix two bugs we recently found in the reactor module. The changes are quite minor. Not sure why the internal App test failed. I would appreciate if you could take a look. Thanks in advance.

**Review by GiudGiud — APPROVED** [review]
bison failure is unrelated.

**Comment by miaoyinb** [comment]
Thank you so much @loganharbour @GiudGiud

**Pull request merged**
