### PR TITLE
output: remove confusing templated inheritance from class heirarchy

### PR DESCRIPTION
**Pull request by rwcarlsen**
This removes the strange inheritance relationships between output classes - which allowed the entire removal of the BasicOutput intermediate class.  I plan on doing some more simplifications and cleanups on this coming.  I can do those in this PR if preferred - or another PR if this seems fine in its current state.

Some notes on a few of the changes here:

* Previously, all subclasses of AdvancedOutput needed to specifiy certain
"output types" and an error was thrown if they weren't specified by
subclasses.  But now since there are subclasses that don't use any
special sub "output types", it is okay to not throw an error when this
is the case.  So We remove the error check.

* Previously, the console output timestep information even if the object's
execute_on flags were set to not run on TIMESTEP_BEGIN. This should not
have been happening because the console was coded to only print timestep
information on TIMESTEP_BEGIN.  Which means Console::output was being
called during EXEC_TIMESTEP_BEGIN despite its flags - bad.  This
behavior was fixed, but we might want to provide some sort of legacy
support if other apps/users were relying on this in any significant way.

First step in addressing #9176

### CODE REVIEW

**Comment by rwcarlsen** [comment]
Let's get this in before it becomes outdated - further work can go in follow up PRs.

**Comment by permcody** [comment]
Thanks! I'll review.

**Review by permcody — APPROVED** [review]
This is a nice improvement!

**Comment by permcody** [comment]
@aeslaughter - Any comments?

**Comment by aeslaughter** [comment]
While I don't mind this getting cleaned up, there is a reason behind the madness. Removing the template removes the ability to create general output classes. It is fine to have an output object that uses oversampling, but does not output to file. This and other general situations will not be possible if this is merged.

So while changing the design to remove the template works now, it will limit flexibility in the future. I will leave this up to @permcody, personally the template stuff may be confusing but it adds flexibility and it also works fine and has been for many years. 

For me the real change would be to get rid of the Basic and Advanced stuff alltogether. The entire reason behind the Advanced output was motivated by two things. First, when I started this output project we decided that anything going to the screen should be handled by the Console object. Second, YAK "needed" to have postprocessors print to the screen at different intervals than other parts of the Console, to make this work I did all sorts of crazy crap that needs to change.

Having the first restriction made  implementing the second require a lot of code that is far too confusing and complicated. Given what we have changed with respect to output streams the first assumption is wrong. Mainly, the Console needs to be broken up into multiple objects: PostprocessorConsole, IterationConsole, PerfLogConsole, etc. This will allow people to dial up what they want when the want it.

In an ideal world I would like to fix all this myself, but my time always is pushed elsewhere.

**Comment by rwcarlsen** [comment]
ping @permcody

**Review by aeslaughter — APPROVED** [review]
I an neutral to this change, I made another general comment that explains why.

**Comment by permcody** [comment]
I really don't think removing the templating limits us in any practical way. I can't really see how we were effectively using the templating now as it was pretty straightforward to remove without breaking anything. 

Most of MOOSE's generality comes from inheritance, but the Output system is notably one that does not. I'm for removing the templating as I still believe we can handle all requirements and needed flexibility without it. As you mentioned, time crunches are a practical reason that we may not actually get around to fixing it exactly how we want anyway. Might as well clean up what we don't need for now and revisit when there's a driver for some larger change later.

**Comment by brianmoose** [comment]
FYI, this causes several relap-7 tests to diff. Also breaks building Tiamat.

**Comment by andrsd** [comment]
The RELAP-7 diffs are not related to this PR. There are a few new tests that are not robust enough yet and some of them diffed.

**Comment by permcody** [comment]
@rcarlsen - Will you take a look at the Tiamat failure? It looks like a
simple fix. Go ahead and put in a PR to their project so we can keep it
building. Thanks!

**Comment by rwcarlsen** [comment]
I don't have access to CASL/Tiamat

**Comment by permcody** [comment]
I'm requesting access for you, @jwpeterson and @aeslaughter.

**Pull request merged**
