### PR TITLE
Clarify feature_id vs. grain

### LINKED ISSUE #7385: Clarify difference of "Feature" and "Grain" numbers in EBSD reader and its related classes
### Description of the enhancement or error report
There is a lot of confusion the EBSD reader about the meaning of _grain_ ID. Grain IDs are a MOOSE internal numbering system and should not be confused with EBSD _feature_ IDs. Feature IDs can be arbitrary (unsigned) integers, while grain IDs are contiguously numbered integers (starting at 0). 
I need to rename a bunch of member and local variables to make the distinction clear and add more documentation.

### Rationale for the enhancement or information for reproducing the error
Reduce confusion.

### Identified impact
This will probably break code using EBSD data. I'll fix everything I can.

Ping @tonkmr , @permcody , @frombs

### PR DESCRIPTION
**Pull request by dschwen**
Closes #7385

### CODE REVIEW

**Comment by permcody** [comment]
This looks ok. Let me try it with the EBSD dataset with the grain tracker and make sure it's working

**Comment by permcody** [comment]
Hmm - well this still doesn't help me out with the GrainTracker. I'm not sure what to do, why don't you stop by and we can figure out how to get the info out that I need.

**Comment by dschwen** [comment]
Btw. @tonkmr and @permcody you can use `EBSDReaderAvgDataAux` to output the `feature_id` field!

**Comment by permcody** [comment]
You are missing a few cases in `EBSDReader::getAvgDataAccessFunctor`

**Comment by permcody** [comment]
👍

**Pull request merged**
