### PR TITLE
Write only the last line(s) of a CSV file instead of the whole thing each time.

### PR DESCRIPTION
**Pull request by permcody**
I also refactored and cleaned up FormattedTable quite a bit. I have more cleanup coming that I will probably add as another commit to this PR.

### CODE REVIEW

**Comment by friedmud** [comment]
Nice!

**Comment by jessecarterMOOSE** [comment]
Awesome! FYI this was requested in #6299

**Comment by permcody** [comment]
@andrsd, @jwpeterson, or @aeslaughter - This is ready for review and merge.

**Review by jwpeterson — DISMISSED** [review]
Other than the `emplace_back` thing, looks good to me.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
