### PR TITLE
Add Dockerfile and Jenkinsfile to repo

### LINKED ISSUE #13915: Addition of a Dockerfile and a Jenkinsfile
## Reason
Having a Dockerfile to build MOOSE in the root directory of the repo, along with a Jenkinsfile to prescribe how the build should proceed, is a lot more convenient and maintainable.  From here, our (Kairos Power) CI/CD will be pushing MOOSE images to Docker Hub, where any interested party is free to pull from (easier access).  When these changes trickle down to herd codes, it will be possible to build images by pulling a MOOSE base image based on the herd code's MOOSE submodule commit hash.

## Design
Two files will be added.  The Dockerfile contains what's needed to build a MOOSE image, and the Jenkinsfile prescribes how to build, test, and push the Docker image to a user-defined registry.  

Along with this, to lessen the redundancy of build scripts, scripts/update_and_rebuild_petsc.sh will be modified to allow specification of the configure --prefix flag to be the value of $PETSC_PREFIX as defined by the user or default to no prefix specification.  Also, having --download-ptscotch=1 in the configuration leads to the error "PTScotch needs bison installed."  The instructions for manual installation don't include ptscotch, and MOOSE/BISON seems to run fine without it.  This seems like a safe delete.

## Impact
None of these changes impact the MOOSE source code.  The only extant file being changed is scripts/update_and_rebuild_petsc.sh, and I don't think it sees a lot of use compared to the package and manual install methods.  The net effect of adding a Dockerfile and Jenkinsfile is that Docker images of MOOSE will be publicly available on Docker Hub, and interested parties will be able to pull either the latest image or by commit hash.

### PR DESCRIPTION
**Pull request by herter4171**
Adds a Dockerfile and a Jenkinsfile to be used to build and push images of MOOSE to Docker Hub for general use (specific use-case is at Kairos Power).  No source code as been modified.  The file `scripts/update_and_rebuild_petsc.sh` was modified to allow specification of `--prefix` using `$PETSC_PREFIX`.  

Closes #13915.

### CODE REVIEW

**Comment by herter4171** [comment]
I'm seeing CIVET says "Requests MUST not be direct to the devel branch!"  However, the page for contributing emphasizes that PRs should be made to devel.  Is the actual procedure to make a PR with "next" instead, and should I delete this particular PR?
Screen Shot 2019-08-16 at 8 16 50 AM

**Comment by dschwen** [comment]
Changed the base to `next`.

**Comment by milljm** [comment]
@dschwen a hiccup perhaps? Seems to work this morning...

**Comment by dschwen** [comment]
Yeah, I managed to invalidate, but it occurred to me that I don't understand the error message either. How did this PR even get in a state to trigger that error? I have never seen it before. Is this a new addition to the pre-test recipe?

**Comment by milljm** [comment]
@herter4171 @dschwen It looks like the discrepancy means we need to update the documentation. 

Documentation, documentation,  documentation, documentation, documentation, documentation, documentation, documentation... Its an ongoing process :) Sorry for the confusion!

As for how it got into this state? ¯\\_(ツ)_/¯

**Comment by lindsayad** [comment]
> Is this a new addition to the pre-test recipe?

Yes I believe it is relatively new. People like @aeslaughter kept submitting PRs against next :-)

**Comment by permcody** [comment]
Thanks for letting us know our documentation is out of date. We'll get that fixed.

**Comment by herter4171** [comment]
Thanks for looking into this @dschwen, @milljm, and @lindsayad... Glad to help, @permcody.  I'll submit a new PR against next with these files in a subfolder per our discussion.

**Pull request closed without merging**
