### PR TITLE
Update materialize.min.js

### LINKED ISSUE #23998: Mobile Droid users unable to click menu items on website
## Bug Description
There is a bug in Materialize that prevents users from navigating the menu system on our website.

## Steps to Reproduce
Using a Droid phone, navigate to our website and try to peruse through the menu system.

## Impact
Droid users are unable to use our website at all.

### PR DESCRIPTION
**Pull request by milljm**
A newer version was released. Bump our version to match, try and solve Droid menu click issue.

Closes #23998

### CODE REVIEW

**Comment by milljm** [comment]
I need a public website created (PR), and test using physical devices (instead of emulation)

**Review by roystgnr — APPROVED** [review]
Do these guys get charged by the byte for whitespace?

**Review by GiudGiud — APPROVED** [review]
reviewed every character

**Comment by milljm** [comment]
@roystgnr  Its crazy what removing white space saves...  er, well i was about to prove it, but its actually not much!

```pre
142K Apr  6 09:42 materialize.min.css
vs with white space:
167K Apr 12 08:11 materialize.min.css_w
```

**Pull request merged**
