### PR TITLE
Implementation of Interface UserObject

### LINKED ISSUE #11647: Add InterfaceUserObject Class
## Rationale

This class is similar to InternalSideUserObject, but allow to works on Interfaces

## Description

`InterfaceUserObject` is a new class inheriting from `boundaryRestrictableRequired`.
`loop/ComputeUseroObjectThread` adn `loop/ComputeMateirlasThread` now have an `::onInterface` Method

## Impact
This will help in developing the interface kernel based, cohesive zone model (#11575 #11546 )
No cons, only a new feature users can enjoy.

### PR DESCRIPTION
**Pull request by arovinelli**
- The aim of this new class is to provide an **easy to use** user object to make computation across an interface.

- A new user obejct base class similar to the `InternalSideUserObject`. The noticeable difference is that the `InterfaceUserObject` is boundary restricted but allows to grab material properties and variable across an interface. `ComputeUserObjectsThread` and `ComputeMaterialThread` now override the `onInterface` method.  Some addition has been done to `FEProblemBase` to allow this new class to properly work.

- in general the `InterfaceUserObject` is helpful for all that situations in which a UO is needed to do computation across an Interface where the `InterfaceKernel` is used.
continuation of #11660
 #closes #11647

### CODE REVIEW

**Comment by arovinelli** [comment]
@lindsayad I removed the material update after the UO execution and updated `FEProblemBase::needBoundaryMaterialOnInterface`. 
```
bool
FEProblemBase::needBoundaryMaterialOnInterface(BoundaryID bnd_id, THREAD_ID tid)
{
  if (_bnd_mat_interface_cache[tid].find(bnd_id) == _bnd_mat_interface_cache[tid].end())
  {
    _bnd_mat_interface_cache[tid][bnd_id] = false;

    // if (_nl->needBoundaryMaterialOnInterface(bnd_id, tid))
    //   _bnd_mat_interface_cache[tid][bnd_id] = true;
    // else if (_interface_user_objects.hasActiveBoundaryObjects(bnd_id, tid))
    //   _bnd_mat_interface_cache[tid][bnd_id] = true;
    if (_interface_user_objects.hasActiveBoundaryObjects(bnd_id, tid))
      _bnd_mat_interface_cache[tid][bnd_id] = true;
  }

  return _bnd_mat_interface_cache[tid][bnd_id];
}
```

let's start back from this and tell me what you would like to change.

Thanks for your time
Andrea

**Comment by lindsayad** [comment]
I would like a pull request that looks like [this](https://github.com/idaholab/moose/commit/f326b58e397a7faca55cd51c6b654f533c55abd8), e.g. if I grep through the PR I should not encounter the word `material`

**Comment by arovinelli** [comment]
Ok, so I need to get rid of all the changes to 
`ComputeMaterialsObjectThread` 
and the calls
`FEProblemBase::needBoundaryMaterialOnInterface`...
I'll try to figure out what I'm missing to get the correct material properties value without those

**Comment by lindsayad** [comment]
Isn't that going to require that `InterfaceMaterial` get finished first? And won't `InterfaceMaterial` be able to do the CZM things you wanted to do? E.g. it should allow you to pull face and neighbor material properties and variable values such that you can compute (stateful) interface material properties, right?

**Comment by arovinelli** [comment]
@lindsayad I'm not sure about this. Ideally this UO (at least as I think at it)  should be able to compute something across an interface, doesn't matter if it is variable or a MP. The interface material is necessary only to store stateful interface MP that depends on  othe MP (e.g. damage as function of dispalcement).
So, if I have a stateful diffusion coefficient on both side I should be able to grab it with this UO, because it should be updated when i call 

```
void
ComputeUserObjectsThread::onInterface(const Elem * elem, unsigned int side, BoundaryID bnd_id)
....
  _fe_problem.prepareFace(elem, _tid);
  _fe_problem.reinitNeighbor(elem, side, _tid);
  // Set up Sentinels so that, even if one of the reinitMaterialsXXX() calls throws, we
  // still remember to swap back during stack unwinding.
  SwapBackSentinel face_sentinel(_fe_problem, &FEProblem::swapBackMaterialsFace, _tid);
  _fe_problem.reinitMaterialsFace(elem->subdomain_id(), _tid);
  SwapBackSentinel neighbor_sentinel(_fe_problem, &FEProblem::swapBackMaterialsNeighbor, _tid);
  _fe_problem.reinitMaterialsNeighbor(neighbor->subdomain_id(), _tid);
...
```

Am I missing something?

**Comment by arovinelli** [comment]
@lindsayad Alex, don't get me wrong.  With the introduction of the `InterfaceMaterial` this UO wont be necessary anymore, at least for the CZM model. However if we want to have an Interface UO i think it should be able to grab MP on both side of a generic interface. 
For instance: assume that interface behaviour depends on the mean interface property-jump across all the interface, then I will need to use this object to compute the mean with the InterfaceUO and give it back to the `InterfaceMaterial`. Does this make sense?

**Comment by lindsayad** [comment]
> @lindsayad Alex, don't get me wrong. With the introduction of the InterfaceMaterial this UO wont be necessary anymore, at least for the CZM model. However if we want to have an Interface UO i think it should be able to grab MP on both side of a generic interface.

You're right; I agree with this. So the code that you have in `ComputeMaterialsObjectThread` and the `needBoundaryMaterialOnInterface` methods should absolutely go into MOOSE. However, since we don't yet have the proper material for the interface, I don't think this can go in yet. I would like to see this code either incorporated into @jiangwen84's eventual `InterfaceMaterial` PR or as a follow-on PR.

Unfortunately, this does mean that the `InterfaceUO` won't have all its capability right out of the box...we need to wait just a bit. @arovinelli does this make sense? You have the best idea of what needs to exist for actual use cases.

**Comment by arovinelli** [comment]
@lindsayad I give it some thought and I think it might be better to wait for the `InterfaceMaterial` becuase that would prevent users from using the `InterfaceUO` and getting wrong results for `MP`. 
However, there are a couple of capability I would like to add to the `InterfaceUO` before merging anyway:
getting normals and qp cooridnates on both side of the interface to allow for large deformations computation.
So I can work on this in the meanwhile @jiangwen84 works on the `InterfaceMaterial`
I'm not sure how to get this quantities on the slave side of the interface do you have any suggestion?
Also, in the meanwhile I'll keep the `ComputeMaterialsObjectThread` and `needBoundaryMaterialOnInterface` code in the paper to allow me for development (and take it out later).

**Comment by lindsayad** [comment]
> @lindsayad I give it some thought and I think it might be better to wait for the InterfaceMaterial becuase that would prevent users from using the InterfaceUO and getting wrong results for MP.

Ok, that sounds good to me. If you want to do that, then I think you should close this and then re-open after the `InterfaceMaterial` PR is opened.

> I'm not sure how to get this quantities on the slave side of the interface do you have any suggestion?

Are you referring to the normals and the qps?

**Comment by arovinelli** [comment]
>Ok, that sounds good to me. If you want to do that, then I think you should close this and then re-open after the InterfaceMaterial PR is opened.
Ok I'll close this and keep on a secure branch.

> Are you referring to the normals and the qps?
Yes I do :)

**Comment by jiangwen84** [comment]
@arovinelli For large deformation, I think it makes more sense to pursuit it with FaceFaceConstraint. Particularly, when you have large sliding, the initial element/neighbor pair would no longer be tied to each other. It is more like a Contact problem where geometric search, project, etc needs to be performed.

**Comment by arovinelli** [comment]
>@arovinelli For large deformation, I think it makes more sense to pursuit it with FaceFaceConstraint. Particularly, when you have large sliding, the initial element/neighbor pair would no longer be tied to each other. It is more like a Contact problem where geometric search, project, etc needs to be performed.

@jiangwen84 I agree, contact is a good option for large sliding, however large deformations also include rotations. For cases in which rotations are not small you need to use a large deformation (finite strain) formulation. Furthermore, many CZM model accounts for this. 
Anyway, I think we are diverging from the main point,I would simply like allowing the `InterfaceUO` to get geometric properties on both side of the interface.

**Comment by lindsayad** [comment]
Closing this until #12101 goes through and this is updated to use that capability

**Comment by arovinelli** [comment]
@lindsayad ok I gave up on waiting on this, so I will take out all the material stuff from this and the make another PR. However I'm working on it but I can't make it work with the new wearhouse and I need some help in figureing out what's happening.
basically the `ComputeUserObjectThread::onInterface` never get called. Could help me figure out what is wrong with it?

**Comment by YaqiWang** [comment]
@lindsayad Can we let this go in without #12101? Or we can trim down a little bit to get this in?

**Comment by arovinelli** [comment]
I’ll finish this up in the weekend is ti ok?

On Feb 7, 2019, at 12:42 PM, Yaqi <notifications@github.com<mailto:notifications@github.com>> wrote:


@lindsayad<https://github.com/lindsayad> Can we let this go in without #12101<https://github.com/idaholab/moose/pull/12101>? Or we can trim down a little bit to get this in?

**Comment by YaqiWang** [comment]
Thanks @arovinelli . We have something relying on this but do not want to take over this. Your consideration is appreciated!

**Pull request closed without merging**
