### PR TITLE
Re-factor MooseDocs to remove nested navigation

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by permcody** [comment]
Wow - huge reduction in lines to take this approach.

**Comment by aeslaughter** [comment]
@permcody Not really, this removes the stub markdown files that currently exist. I was planning on adding them back in, but not wanted to see if this was working on the remote server. 

There are some styling things to consider and some broken links, but the navigation stuff seems to be working like I intended. I am curious to what people think of this approach.

http://mooseframework.org/docs/PRs/8133/site/documentation/systems/index.html

**Comment by aeslaughter** [comment]
I also plan on adding the class descriptions along with the names. They will be on the same line and if they go long it will just be a "..."

**Comment by permcody** [comment]
It's a lot faster and feels more modern now!

I wonder whats the best way to show objects from all of the various modules and the framework. Right now you are showing objects from PhaseField and TensorMechanics but since this whole page is arranged by syntax that might be a bit of a problem. For one thing you aren't showing blocks that are added by either of those two modules right now, but if you did the complete list would get really messy. If we do it like we do know (just the framework and then a separate page from framework plus all modules), it's of limited value because most people just don't need everything. 

What if we had a series of checkboxes for each of the modules and we could generate the page based on which boxes were checked? This is getting away from the more immediate mods of what the interface looks like. I definitely like this better!

**Comment by aeslaughter** [comment]
I have a Phase Field systems page: http://mooseframework.org/docs/PRs/8133/site/documentation/modules/phase_field/systems/index.html

**Comment by permcody** [comment]
Should we be seeing all the extra PhaseField syntax on that page? We aren't right now.

**Comment by friedmud** [comment]
It is looking better.  Viewing the site at the above link posted by @moosebuild the site is kind of mangled (missing images, inverted colors).  Is that just a side-effect of the build system?

It's definitely snappier and I like the menus at the top of the screen!

**Comment by aeslaughter** [comment]
I don't have the mangled colors, but there are missing images and a bunch
of missing content. Not sure what is causing that and don't have time to
dig into at the moment.

**Comment by friedmud** [comment]
Just a heads up that the site still doesn't really render right for me.  Is it supposed to at this point?

**Comment by aeslaughter** [comment]
It is supposed to be working, I am believe I am still figuring out the
relative links incorrectly so everything is hosed.

**Comment by friedmud** [comment]
No problem: just checking 😄 

Let me know when it starts working.  I'm eager to see what you've been up to!

**Comment by aeslaughter** [comment]
I haven't been up to much in the past month, I am just trying to get things
cleaned up and rebased.

**Comment by aeslaughter** [comment]
I think this is ready to go, it does the following:
    
* Removes the huge nested menu in favor of a simple top menu.
* Adds the ability to make summary pages of systems and objects, these will be sparse until we get a more complete dump MOOSE and/or we document the objects.
* Adds a `moosedocs.py test` command which will be run by Civet, I need to and a lot more tests but some of the basics are setup.

**Review by brianmoose — APPROVED** [review]
I didn't actually look over all 1687 files. I did go to the website and look things over. Things looked good with the exception of the "copy" button on the moose style markdown page.
Anybody else want to look things over before this gets merged?

**Comment by aeslaughter** [comment]
The copy button is a style issue that I would like someone to help me with,
I don't think it needs to hold this up. Once this gets merged I plan on
opening a new issue for this type of minor tweaks.

**Comment by friedmud** [comment]
It is _way_ better: but still a lot to do (for instance: non of the top bar renders properly on an iPad or iPhone).

Are you just wanting to call this particular PR complete and move on to another one about the remaining issues?

**Comment by aeslaughter** [comment]
On Fri, Jan 13, 2017 at 4:41 PM, Derek Gaston <notifications@github.com>
wrote:

> It is *way* better: but still a lot to do (for instance: non of the top
> bar renders properly on an iPad or iPhone).
>
I will look at this, but I am not sure I will be the right person to fix
it.

> Are you just wanting to call this particular PR complete and move on to
> another one about the remaining issues?
>
Yes, people are wanting to write documentation and this PR is significant
since it changes the locations of markdown files and also improves many
other items that should make their experience better.

**Comment by friedmud** [comment]
Ok - I'm for this getting merged. Let's keep working on it.

Good work so far! Looking really good!

**Pull request merged**
