### PR TITLE
Ensure that PerfGraph section names are static

### LINKED ISSUE #23805: Static registry of timed section used with dynamic / different names does not error
## Reason
If you use a timed section name (registry entry) that changes during the simulation, only the first instance's name will be used, a new section will not be created

## Design
Either a dynamic registry
OR
error if the name changes (assert probably)

## Impact
better usability of the perf graph for downstream application users

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #23805

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]

**Review by GiudGiud — DISMISSED** [review]

**Comment by GiudGiud** [comment]
Let's see if that does it

**Comment by GiudGiud** [comment]
The side effect is that we'll register too often. Doesnt seem ideal :S. Let s see if I can find a better option

**Comment by GiudGiud** [comment]
This will avoid registering too often.

But the big question here:
- if a timed section is in a parent class, do we want each derived class to have their own section (what this does)
OR
- do we want to keep silently merging them under the "first class that registered the timed section"

**Comment by GiudGiud** [comment]
I think this can be merged
```if a timed section is in a parent class, do we want each derived class to have their own section (what this PR does)```
is the right call

**Comment by GiudGiud** [comment]
@lindsayad or @loganharbour mind moving this forward?

**Comment by loganharbour** [comment]
@lindsayad I can't approve of my own PR - but I approve of @GiudGiud's changes; can you please approve mine?

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
