### PR TITLE
Support Lagrangian kernels in axisymmetric RZ coordinates

### PR DESCRIPTION
**Pull request by hugary1995**
This series of PR attempts to add support for axisymmetry in the new Lagrangian mechanics system. It seems that the review time exponentially grows with the PR size, so I try to break the large PR into small ones. This PR only focuses on the case for axisymmetric RZ coordinates.

ref #20712

### CODE REVIEW

**Comment by hugary1995** [comment]
@reverendbedford Can you help me check the equations before I do anything crazy? I'll add the updated Lagrangian ones in a later PR.

**Comment by hugary1995** [comment]
Perhaps the best way to reduce code duplication (without modifying basis functions in libMesh for stabilization), is adding interfaces that defines the basis functions in the tensor mechanics module, and then template Lagrangian kernels and materials on those interfaces. Inside those interfaces, we can handle stabilization as well as coordinate systems.

**Comment by reverendbedford** [comment]
1. I'm transcribing the formulations I have in a notebook to latex, I'll try to finish tomorrow and double check I didn't screw anything up.
2. I'm open to any way of organizing this better than what's in tensor_mechanics now.  The main annoyance is that the stabilized basis functions involve the basis functions for the other displacement components, which gets aggravating the way we do things now with scalar (field) kernels.  I'd have to see or make a mock up to figure out if/how we could reuse the same basic implementation across the two (three once we do spherical) cases.

**Comment by reverendbedford** [comment]
Your definition of the gradient seems okay to me.  I think you're on to the right approach which might be to:

1. Make `ComputeLagrangianStrain::calculateDeformationGradient()` virtual and override in some sort of `ComputeLagrangianAxisymmetricStrain` class.  Actually we should make a new virtual method to calculate the unstabilized deformation gradient as the F_bar stabilization will be the same for both Cartesian and axisymmetric.
2. Inherit from the Cartesian kernels and (for the unstabilized case) just alter `trialGrad` and `testGrad`.  I didn't think about it at the time, but making those return tensors is incredibly convenient, as I think you may be able to just alter those two methods and get the (unstabilized) case working.

That may be it for the total Lagrangian kernel without stabilization.  Stabilization is going to be the annoyance, as I suspect, but have not checked, the derivatives of the average.

I now see your point about modularizing things by templating on the means to calculate the test and trial gradients.  I completely forgot that I changed that completely from the current kernels and return the full RankTwo forms.  That's inefficient for the unstabilized Cartesian kernels but sure nice here.

**Comment by hugary1995** [comment]
> Your definition of the gradient seems okay to me. I think you're on to the right approach which might be to:
> 
> 1. Make `ComputeLagrangianStrain::calculateDeformationGradient()` virtual and override in some sort of `ComputeLagrangianAxisymmetricStrain` class.  Actually we should make a new virtual method to calculate the unstabilized deformation gradient as the F_bar stabilization will be the same for both Cartesian and axisymmetric.
> 2. Inherit from the Cartesian kernels and (for the unstabilized case) and just make virtual/alter `trialGrad` and `testGrad`.  I didn't think about it at the time, but making those return tensors is incredibly convenient, as I think you may be able to just alter those two methods and get the (unstabilized) case working.
> 
> That may be it for the total Lagrangian kernel without stabilization. 

That's exactly what I did here. I also did updated lagrangian and it's pretty much the same thing.

> Stabilization is going to be the annoyance, as I suspect, but have not checked, the derivatives of the average get complicated by the coordinate system.

I haven't derived it yet. I'll plan to try cooks membrane to convince myself that stabilization is really needed in rz. If so I'll implement stabilization. I suspect it's not all that bad.

> I now see your point about modularizing things by templating on the means to calculate the test and trial gradients. I completely forgot that I changed that completely from the current kernels and return the full RankTwo forms. That's inefficient for the unstabilized Cartesian kernels but sure nice here.

I thought you had thought all this through and did it that way on purpose... It's indeed convenient. For Cartesian, we could speed it up by implementing views into a RankTwoTensor -- that's for future reference.

**Comment by reverendbedford** [comment]
> I thought you had thought all this through and did it that way on purpose... It's indeed convenient. For Cartesian, we could speed it up by implementing views into a RankTwoTensor -- that's for future reference.

Nope way dumber than that.  I did it because it was nice for the F_bar modifications not for any grand plan on implementing other coordinate systems.  But it should make things easy now.

**Comment by hugary1995** [comment]
I am closing this PR for now, as I realize that the current Lagrangian kernels need an overhaul to implement other coordinate systems in a clean way.

Currently, most of the heavy lifting of the jacobian calculations are performed in the kernels. Applying stabilization in a `Material` and computing the derivatives of the stabilized defgrad in a `Kernel` make the code difficult to maintain. I propose to move all the jacobian calculations, e.g. `dF/du`, `dpk1/deigenstrain`, `dL/du`, `dstress/deigenstrain`, etc. into the corresponding strain calculator. That way
- the kernels will become agnostic to `_large_kinematics` (except the geometric jacobian in updated Lagrangian);
- the kernels will become agnostic to `_stabilize_strain`;
- the annoying pull back / push forward operations are no longer needed in the jacobian calculation for stabilized strain in updated Lagrangian (as the strain calculators are run on the undisplaced mesh);
- we can get rid of several intermediate material properties like the inverse of the incremental deformation gradient, since we no longer need to first save it as a material property, then retrieve it inside the kernel;
- we can write generic kernels for all coordinate systems templating on different gradient operators.

**Comment by dschwen** [comment]
Guys, a while back (2-3 years) we were discussing transitioning TM to vector kernels. I should probably have brought this up earlier. But it would enable calculations that involve all components more easily.

**Comment by reverendbedford** [comment]
I took a poll last year and it seemed the consensus was to keep things as
is with scalar kernels.  But ya I think one of the lessons here is that
using a vector kernel would be better for everything except the unstablized
Cartesian case.

**Comment by hugary1995** [comment]
I need more time to think about this. It's a little difficult for me to wrap my head around the difference here. If we consider [the residual and jacobian using total Lagrangian](https://mooseframework.inl.gov/source/kernels/lagrangian/TotalLagrangianStressDivergence.html), even with vector kernels, we still need to populate `\phi^\alpha_{i, K}` and `G^\beta_{kL}` for each of the displacement component `\alpha` and `\beta`, which still means a `RankTwoTensor` for each component. Did I miss anything or the vector kernel brings us some other benefit?

Anyways, if there's going to be a transition, it's now or practically never. The new Lagrangian mechanics system is a good chance to make the transition -- before it grows larger.

**Pull request closed without merging**
