### PR TITLE
Fixed clamp template call

### LINKED ISSUE #13244: Clamp<T> template usage in MathUtils::smootherStep
## Bug Description
Forgot template `<T>` in clamp call in `MathUtils::smootherStep`

## Steps to Reproduce
`x = clamp<T>((x - start) / (end - start), 0.0, 1.0);`

## Impact
Better usage of `smootherStep`

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #13244

### CODE REVIEW

**Comment by permcody** [comment]
Do you need the explicit template parameter here for something? It can be inferred from the function arguments for this case. Just curious.

**Comment by tophmatthews** [comment]
Yeah, I was getting a compile error in an AD object when I was calling smootherStep
```
/opt/civet/build_0/bison/moose/framework/build/header_symlinks/MathUtils.h:151:7: error: no matching function for call to 'clamp'
  x = clamp((x - start) / (end - start), 0.0, 1.0);
```
The call is
```
const ADReal mixing = MathUtils::smootherStep<ADReal>(_temperature[_qp], start, end);
```

**Comment by tophmatthews** [comment]
Here's the full error @permcody ,
```
/opt/civet/build_0/bison/moose/framework/build/header_symlinks/MathUtils.h:151:7: error: no matching function for call to 'clamp'
  x = clamp((x - start) / (end - start), 0.0, 1.0);
      ^~~~~
/opt/civet/build_0/bison/src/materials/tensor_mechanics/ADUPuZrCreepUpdate.C:117:18: note: in instantiation of function template specialization 'MathUtils::smootherStep<MetaPhysicL::DualNumber<double, MetaPhysicL::NumberArray<50, double> > >' requested here
      MathUtils::smootherStep<typename Moose::RealType<compute_stage>::type>(_temperature[_qp], _alpha_start, _alpha_end);
                 ^
/opt/civet/build_0/bison/build/header_symlinks/ADUPuZrCreepUpdate.h:27:3: note: in instantiation of member function 'ADUPuZrCreepUpdate<JACOBIAN>::computeResidual' requested here
  ADUPuZrCreepUpdate<compute_stage>(const InputParameters & parameters);
  ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/ext/new_allocator.h:136:23: note: in instantiation of member function 'ADUPuZrCreepUpdate<JACOBIAN>::ADUPuZrCreepUpdate' requested here
 { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
                      ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/alloc_traits.h:475:8: note: in instantiation of function template specialization '__gnu_cxx::new_allocator<ADUPuZrCreepUpdate<JACOBIAN> >::construct<ADUPuZrCreepUpdate<JACOBIAN>, const InputParameters &>' requested here
 { __a.construct(__p, std::forward<_Args>(__args)...); }
       ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/shared_ptr_base.h:526:30: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<ADUPuZrCreepUpdate<JACOBIAN> > >::construct<ADUPuZrCreepUpdate<JACOBIAN>, const InputParameters &>' requested here
   allocator_traits<_Alloc>::construct(__a, _M_ptr(),
                             ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/shared_ptr_base.h:637:18: note: (skipping 3 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
   ::new (__mem) _Sp_cp_type(std::move(__a),
                 ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/shared_ptr.h:690:14: note: in instantiation of function template specialization 'std::shared_ptr<ADUPuZrCreepUpdate<JACOBIAN> >::shared_ptr<std::allocator<ADUPuZrCreepUpdate<JACOBIAN> >, const InputParameters &>' requested here
      return shared_ptr<_Tp>(_Sp_make_shared_tag(), __a,
             ^
/opt/moose/gcc-7.3.1/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/shared_ptr.h:706:19: note: in instantiation of function template specialization 'std::allocate_shared<ADUPuZrCreepUpdate<JACOBIAN>, std::allocator<ADUPuZrCreepUpdate<JACOBIAN> >, const InputParameters &>' requested here
      return std::allocate_shared<_Tp>(std::allocator<_Tp_nc>(),
                  ^
/opt/civet/build_0/bison/moose/framework/build/header_symlinks/Registry.h:177:15: note: in instantiation of function template specialization 'std::make_shared<ADUPuZrCreepUpdate<JACOBIAN>, const InputParameters &>' requested here
  return std::make_shared<T>(parameters);
              ^
/opt/civet/build_0/bison/moose/framework/build/header_symlinks/Registry.h:206:24: note: in instantiation of function template specialization 'buildObj<ADUPuZrCreepUpdate<JACOBIAN> >' requested here
    copy._build_ptr = &buildObj<T>;
                       ^
/opt/civet/build_0/bison/src/materials/tensor_mechanics/ADUPuZrCreepUpdate.C:15:384: note: in instantiation of function template specialization 'Registry::add<ADUPuZrCreepUpdate<JACOBIAN> >' requested here
static char dummyvar_for_registering_obj_ADUPuZrCreepUpdate_residual15 = Registry::add<ADUPuZrCreepUpdate<RESIDUAL>>({"BisonApp", "ADUPuZrCreepUpdate" "<RESIDUAL>", "", "", nullptr, nullptr, nullptr, "/opt/civet/build_0/bison/src/materials/tensor_mechanics/ADUPuZrCreepUpdate.C", 15, "", "", true}); static char dummyvar_for_registering_obj_ADUPuZrCreepUpdate_jacobian15 = Registry::add<ADUPuZrCreepUpdate<JACOBIAN>>({"BisonApp", "ADUPuZrCreepUpdate" "<JACOBIAN>", "", "", nullptr, nullptr, nullptr, "/opt/civet/build_0/bison/src/materials/tensor_mechanics/ADUPuZrCreepUpdate.C", 15, "", "", true});
                                                                                                                                                                                                                                                                                                                                                                                               ^
/opt/civet/build_0/bison/moose/framework/build/header_symlinks/MathUtils.h:136:1: note: candidate template ignored: deduced conflicting types for parameter 'T' ('MetaPhysicL::DualNumber<double, MetaPhysicL::NumberArray<50, double> >' vs. 'double')
clamp(T x, T lowerlimit, T upperlimit)
^
1 error generated.
```
Looks like the last line shows it's conflicting when using the ADReal
`note: candidate template ignored: deduced conflicting types for parameter 'T'`

**Comment by permcody** [comment]
Haha - Thanks for checking!

**Review by permcody — APPROVED** [review]

**Comment by dschwen** [comment]
Hm, I think the right solution would be to change the signature of clamp to

```
T clamp(T x, Real lowerlimit, Real upperlimit);
```

Then you do not get conflicting deduced types! I don't see how the limits could contribute to the derivative.

**Comment by tophmatthews** [comment]
Ohhh...I see...It was conflicting since `x` was different than `lowerlimit`. Yeah, that would be better, I can change it again...

**Comment by dschwen** [comment]
It is not a big deal, but the limits are currently upcast to DualNumbers which adds a few operations.
Alternatively you can add a second template parameter:

```
T clamp(T x, T2 lowerlimit, T2 upperlimit);
```

**Pull request merged**
