### PR TITLE
Update libmesh

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:

  - Make Elem::interior_parent always safe to call
  - Support shell preconditioning matrix in eigen system
  - Add dual shape functions
  - Add hash specialization for FEType
  - Added an API to retrieve eigenvalue
  - Fix an overzealous assertion in unpack_indexing
  - Update to MetaPhysicL 1.0.2
  - Make "NumericVector localize()" scalable if possible
  - Try appending to a VariableGroup in add_variables
  - Revert "Use push_parallel_packed_range in scatter_constraints"
  - Fixes for "make distcheck"
  - Don't undef or define MPI_REAL
  - Use push_parallel_packed_range in scatter_constraints
  - Use common m4 files from a submodule
  - Let user control sorting method used by BoundaryInfo::build_side_list()
  - Adding number of threads option to LibMeshInit.
  - QGaussLobatto: add fallback on regular Gauss quadrature
  - Add Tri::quality(SHAPE) metric.
  - Fixed valgrind issue with VecSetDM
  - Fix node unique_id in xda for libMesh 0.9.2
  - Use terser make_range() in place of IntRange<T> where possible.
  - Add templated make_range() helper functions.
  - Don't renumber with parallel and non-contiguous numbering
  - AbaqusIO: Add support for "MASS" elements and "NODE" sidesets.
  - Respect empty variables in Nemesis_IO::write_nodal_data
  - More robust Partitioner::set_node_processor_ids
  - Introduce std::reference_wrapper for more examples
  - Use numerically stable Edge3::volume() algorithm
  - RB fix: fix to RBEIMConstruction
  - Multiple file support in meshtool
  - Small fix to RBConstruction
  - Introduce std::reference_wrapper in fem_system_ex1
  - Make Edge3::volume() calculation more robust.
  - Don't swap LIBS and CPPFLAGS
  - RBConstruction update to store an untransformed basis.
  - Smooth libmesh for PETSc-3.13
  - Fix flux error estimates when flux weights not in approximation space
  - Introduce std::reference_wrapper in fem_system_ex3
  - RBConstruction change: Small change to train_reduced_basis().
  - Update to post_process_elem_matrix_and_vector in RBConstruction
  - Bugfix in rb_construction_base.C
  - DofMap::add_constraint_row(): assert there is no diagonal entry
  - RBConstruction change to element post-processing
  - macrofice second-derivative quantities
  - Fixes for build_sphere(DistributedMesh)
  - Fix adjoint Dirichlet constraints with AMR
  - The 'extra_checks' parameter should match 'secure' for backwards comp…
  - FEMSystem assert should work with new casts
  - PetscSolverException: use specific error message if available
  - Add 'extra_checks' parameter to FEMap::inverse_map()
  - Add DirichletBoundary copy assignment operator.
  - FileSolutionHistory class
  - Testing unique_id uniqueness

Also, for conda, make sure we build libmesh without the gdb command.
Then I don't have to pass --without-gdb-backtrace every time.
Trying to spawn a gdb process takes forever. Nobody got time
for that.

Finally, in conda test and make sure we created a TIMPI library

Refs #14922

### CODE REVIEW

**Comment by lindsayad** [comment]
@milljm I think that's all I need to do with conda right?

**Comment by milljm** [comment]
Correct!

**Comment by lindsayad** [comment]
This https://civet.inl.gov/job/514885/ looks like a real failure. It seems that the current TIMPI hash checked into libMesh is on an orphaned branch (@roystgnr ), so the unreachable error makes sense. I actually don't understand why this only shows up in the non-conda builds.

**Comment by roystgnr** [comment]
That TIMPI hash came in via https://github.com/libMesh/libmesh/pull/2515 ...

Damn, this looks like my fault.  I was futzing with TIMPI, was trying to push temporary tags to experiment with before submitting https://github.com/libMesh/libmesh/pull/2534 , and must have unintentionally overwritten the previous tag and branch.  Let me see what I can do.

**Comment by roystgnr** [comment]
Give it a try now?

**Comment by lindsayad** [comment]
[These failures](https://civet.inl.gov/job/514828/) look like they're caused by libmesh/libmesh#2491. Perhaps they need a fix like that in #15012?

**Comment by lindsayad** [comment]
Wow  the valgrind memory errors in https://civet.inl.gov/job/514877/ are unreadable. Is this a conda artifact?

**Comment by lindsayad** [comment]
> Give it a try now?

This failed again. If I run `git fetch; git fetch --tag` in TIMPI I still don't see a corresponding branch or tag:

```
* acb414b 2020-04-30 Roy Stogner (tag: v1.1.1_bootstrapped) Add bootstrap output
* e9ef8f6 2020-04-30 Roy Stogner Don't ignore bootstrap output
* 8a09dd6 2020-04-30 Roy Stogner (tag: v1.1.1) Update NEWS
* b391e69 2020-04-30 Roy Stogner Bump up release number for autoconf refactoring
| * a27bd7e 2020-04-29 Roy Stogner (tag: v1.1.0_bootstrapped, up/branch_1.1.0) Add bootstrap output
| * a46b021 2020-04-29 Roy Stogner Don't ignore bootstrap output
|/  
*   64f6826 2020-04-29 roystgnr (tag: v1.1.0, up/master, up/HEAD) Merge pull request #30 from roystgnr/relative_submodule_path
|\  
| * 316ab2b 2020-04-29 Roy Stogner Use a relative path for submodules
|/  
*   7fb9089 2020-04-27 Alex Lindsay Merge pull request #29 from roystgnr/common_m4
|\  
| | * 9e59828 2020-04-24 Roy Stogner (up/branch_1.1.0_acsm) Add bootstrap output
| | * 85e2b62 2020-04-24 Roy Stogner Don't ignore bootstrap output
| |/  
| * 2e9e882 2020-04-24 Roy Stogner Remove obsolete macro
| * e683273 2020-04-24 Roy Stogner Use autoconf-submodule for ACSM+AX macros
|/  
| * 4054808 2020-04-21 Roy Stogner (HEAD) Add bootstrap output
| * 858381b 2020-04-21 Roy Stogner Don't ignore bootstrap output
|/  
* 157450a 2020-04-21 Roy Stogner Add missing header
```

**Comment by roystgnr** [comment]
You might need ```git fetch --tag --force```?  Just look at [the releases page](https://github.com/libMesh/TIMPI/releases) - at least on Github, https://github.com/libMesh/TIMPI/commit/4054808355ba2511247b83ac0a8aa0ce2a404e8b is again the hash associated with v1.1.0_bootstrapped.

**Comment by roystgnr** [comment]
> These failures look like they're caused by libMesh/libmesh#2491. Perhaps they need a fix like that in #15012?

Let me see if I can replicate any of those.

**Comment by lindsayad** [comment]
You have to have a branch pointer in order for the commit to be reachable:
```
(moose-boost) lindad@pop-os:~/projects/moose/libmesh/contrib/timpi(master)$ git fsck --unreachable up | grep commit.*4054808
Checking object directories: 100% (256/256), done.
Checking objects: 100% (465/465), done.
unreachable commit 4054808355ba2511247b83ac0a8aa0ce2a404e8b
```

**Comment by roystgnr** [comment]
Okay; branch_1.1.0 is now force pushed to connect to the tag too.

**Comment by roystgnr** [comment]
https://github.com/libMesh/libmesh/pull/2542 is merged now and should fix that unique_id test.  No idea what's going on with those valgrind failures though.

**Comment by fdkong** [comment]
> [libMesh/libmesh#2542](https://github.com/libMesh/libmesh/pull/2542) is merged now and should fix that unique_id test. No idea what's going on with those valgrind failures though.

https://github.com/idaholab/moose/pull/15202

**Comment by lindsayad** [comment]
Yes, see now this will include the libmesh changes in all the conda targets :+1:

**Comment by lindsayad** [comment]
This failure is because @fdkong's commit isn't in the libmesh/libmesh git tree. https://civet.inl.gov/job/517142/

**Comment by lindsayad** [comment]
Honestly, I have no idea how the conda builds are picking up @fdkong's libmesh commit. I also don't understand why [this target](https://civet.inl.gov/job/516977/) picked up his commit either. I don't know who might be able to answer my question? @milljm @jwpeterson ? I understand that github stores some info about pull requests with the upstream repository, but if for instance I do a fresh clone from `libmesh/libmesh` and I try to checkout @fdkong's commit, it no worky:
```
(moose-petsc) lindad@pop-os:~$ git clone git@github.com:libmesh/libmesh libmesh2
Cloning into 'libmesh2'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 201793 (delta 25), reused 15 (delta 3), pack-reused 201665
Receiving objects: 100% (201793/201793), 133.01 MiB | 10.51 MiB/s, done.
Resolving deltas: 100% (149968/149968), done.
(moose-petsc) lindad@pop-os:~$ cd libmesh2
(moose-petsc) lindad@pop-os:~/libmesh2(master)$ git co 61aef8 
error: pathspec '61aef8' did not match any file(s) known to git
```

**Comment by fdkong** [comment]
> Honestly, I have no idea how the conda builds are picking up @fdkong's libmesh commit. I also don't understand why [this target](https://civet.inl.gov/job/516977/) picked up his commit either.

This always works for me :-)

**Comment by dschwen** [comment]
> change to boost m4 file to ignore pedantic warnings from boost

That was reverted

**Comment by fdkong** [comment]
Do not understand the `Valgrind` target fails here. Conda package builder just ignore my `libmesh` update commit.

I think we need to get https://github.com/libMesh/libmesh/pull/2543 in

**Comment by fdkong** [comment]
https://github.com/idaholab/moose/pull/15200 is required to make the rest targets  green

**Comment by lindsayad** [comment]
> #15200 is required to make the rest targets green

I'll rebase this onto next to get @roystgnr changes, since it may be a little bit until we get a next to devel merge (64 dof id and distributed-recover testing currently broken on next). @fdkong let's hold off on pushing anymore to this. There are some things I want to understand first

**Comment by lindsayad** [comment]
> This always works for me :-) But I do not understand why either. I could do a similar thing for PETSc as well.

Ok, conda shouldn't be in the equation here, since it's just using the local hash. I believe all that matters is how `fetch` on the build boxes is configured. My best guess is that on almost all build boxes `fetch` has this configuration:
```
git config --global --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"
```
but the test timings box does not...? If `fetch` does have that configuration, then a `git fetch` or a `git submodule update` would fetch pull ref heads in addition to branch ref heads, which would make it so that those commits can be checked out.

@permcody @milljm @brianmoose can anyone confirm or deny this hypothesis? I of course have forgotten how to log onto the test boxes...

**Comment by lindsayad** [comment]
> Do not understand the `Valgrind` target fails here. Conda package builder just ignore my `libmesh` update commit?

My above hypothesis, if correct, makes these failures a mystery. We were able to checkout your fork's commit in `Fetch and Branch`, so I don't understand why we wouldn't have seen the results of your fixes.

@milljm for my sanity would it be possible to explicitly print out the libmesh commit being used by the conda environment (making sure not to print the one that has your `.gitmodules` patch) in `Initialize Conda Environment`? I know it should be the commit from the submodule hash, but I would just love to be able to see and confirm. I feel like I'm on crazy pills

**Comment by milljm** [comment]
I've tried to read this thread and answer your question about three times (and deleted my response).

I'm going to hold off trying to answer this until you're online. I am a bit confused what everyone is asking for.

**Comment by brianmoose** [comment]
I am also confused, but mainly why @lindsayad tagged me :smile:

**Comment by lindsayad** [comment]
> I am also confused, but mainly why @lindsayad tagged me smile

Hahaha because you're the testing/CIVET master! And I can't believe I got a response! :smile:  We're talking about this on our slack team, but I'll repost here for the general public. Hopefully what I don't understand is made more clear below (how about that for a sentence!):

What I don't understand is this: the other day @fdkong pushed a commit to my libmesh update PR which did not exist on any libmesh branches. It only existed as a pull request. With a standard `git fetch` configuration, CIVET should not have been able to retrieve his commit. For a standard configuration I would expect the error that we saw on the [test timings box](https://civet.inl.gov/job/517142/)
```
BUILD_ROOT/moose/: git submodule update --init
fatal: reference is not a tree: 61aef80a6e24f2ab1f3d7ec8668ca07eabd33fd4
Unable to checkout '61aef80a6e24f2ab1f3d7ec8668ca07eabd33fd4' in submodule path 'libmesh'
```
However, we didn't see that error on any other box. This really shouldn't be a conda issue; it should appear in our `Fetch And Branch` sections

**Comment by brianmoose** [comment]
Hmm, if I had to make a wild guess, maybe the libmesh PR from @fdkong ran on those boxes previously so the hash was already in `.git/modules/libmesh` when doing your PR. But the timing box didn't have it so it failed. Not sure if that sounds plausible or not...

**Comment by lindsayad** [comment]
It's a good attempt but I think that's probably not it. For one thing the libMesh PR only fires up about 6 recipes whereas on the MOOSE Libmesh update PR there's over 20. Moreover, I believe that for testing PRs into  libmesh we use a proper stand-alone libmesh repo as opposed to using a libmesh that is a submodule of moose (e.g. for libmesh PR testing we're in something like `/opt/civet/build_0/libmesh`

**Comment by brianmoose** [comment]
Haha, ahh, missed the libmesh PR part. Yeah, best I could do without access to the test boxes and being out of the loop for so long!  :smile:

**Comment by lindsayad** [comment]
Just let us know when you're ready to come back! :-) hope you're doing
well!

**Comment by lindsayad** [comment]
Ok @fdkong don't touch this PR!!! I'm trying to reproduce the failure seen before...

**Comment by fdkong** [comment]
@lindsayad What is the plan on this? It would be great if we could take the lastest libmesh hash, and do a libmesh update.

I need this for a PR https://github.com/idaholab/moose/pull/14406

**Comment by lindsayad** [comment]
I've been waiting on some libMesh PRs to go through. @recuero is about to submit a libMesh PR that I also want through for mortar purposes

**Comment by lindsayad** [comment]
Note to self for all the things to unset:
```
unset CPPFLAGS CFLAGS LDFLAGS DEBUG_CPPFLAGS DEBUG_CFLAGS CXXFLAGS DEBUG_CXXFLAGS FFLAGS FORTRANFLAGS DEBUG_FFLAGS DEBUG_FORTRANFLAGS
```

**Comment by fdkong** [comment]
Why all the tests are pending forever?

**Comment by permcody** [comment]
Priorities can be set for each recipe and multiple priorities depending on whether a recipe is triggered due to PR or merge. We've set priorities so that PRs get tested first and longer running recipes get more priority. The amount of activity going on among all the projects is accelerating but our build farm is only getting older! I'm thinking about this and trying to find ways of funding a build farm that can keep up!

**Comment by roystgnr** [comment]
Do we have any metrics regarding how much build farm time gets spent on each CI recipe?  Right now the only thing limiting me on libMesh testing is a mix of "how annoying is it when my personal tests take too long" and "how much would I rather be writing something other than more tests", and I barely even think about optimization of test cases or dbg mode code paths, but if there's anything that's hitting the build farm too hard then we could tweak the recipes or the tests as a short term fix.

**Comment by lindsayad** [comment]
Oh yea beautiful pass

**Comment by fdkong** [comment]
@lindsayad Do you want me to merge it right now?

**Comment by lindsayad** [comment]
Yea

**Review by fdkong — APPROVED** [review]

**Comment by fdkong** [comment]
@milljm It is safe to get this in?

**Review by fdkong — DISMISSED** [review]
Let us hold on for a moment

**Comment by fdkong** [comment]
I will let @milljm hit button on this one!

**Comment by milljm** [comment]
Lets make this change to the conda_build_config.cfg:

```diff
moose_petsc:
 - 3.12.5 build_2
```

**Comment by milljm** [comment]
This should be merged anyway, as the are is due to PETSc 3.12.5 @ build_2 does not yet exist publicly (it exists in Next).

Or. We wait until Next, devel, master passes. Invalidate this, and then it will pass.

**Review by milljm — APPROVED** [review]
I am merging this now, because libMesh passed, and Fande's PR passed (updating PETSc which this PR now includes). We don't want to create _another_ PR with both updates.

**Pull request merged**
