### PR TITLE
Add ParsedMaterial

### LINKED ISSUE #4549: Factor out a ParsedMaterial from DerivativeParsedMaterial
We have usecases for building a single material property from a parsed function, in which we need to couple to moose variables. ```DerivativeParsedMaterial``` can already be used for this purpose, but if the derivatives are not needed a ```ParsedMaterial``` may reduce overhead.

### PR DESCRIPTION
**Pull request by dschwen**
Refactor the Derivative Material system completely. Add `ParsedMaterial` (a `DerivativeParsedMaterial` without derivatives).

This PR effectively renames `DerivativeBaseMaterial` to `DerivativeFunctionMaterialBase` and introduces the need to explicitly initialize `FunctionMaterialBase` due to virtual inheritance. Thus it **may require application patches**.

Closes #4549.

### CODE REVIEW

**Comment by dschwen** [comment]
I've added a commit that makes as many classes in the hierarchy abstract. This seems cleaner to me, as the user is not supposed to instantiate them directly, and I can avoid the unnecessary explicit initialization of ```FunctionBaseMaterial``` in them.

The classes are made abstract by declaring a _pure virtual_ destructor. Additionally an implementation of the destructor _has_ to be supplied (according to the standard). The destructor does not have to be implemented in the derived classes.

**Comment by dschwen** [comment]
```
class VirtualBase {
public:
  VirtualBase(int);
};

VirtualBase::VirtualBase(int)
{
}

class Intermediate : public virtual VirtualBase {
public:
  Intermediate(int);
  virtual ~Intermediate() = 0;
};

Intermediate::Intermediate(int)
{
}

Intermediate::~Intermediate()
{
}


class Derived : public Intermediate
{
public:
  Derived(int);
};


Derived::Derived(int i) :
  VirtualBase(i),
  Intermediate(i)
{
}

int main()
{
}
```

compiles fine with ```clang++``` but not with ```g++ -std=c++11 virtualinherit.cc```. Grrr, despite _"An abstract class (10.4) is never a most derived class, thus its 
constructors never initialize virtual base classes, therefore the 
corresponding mem-initializers may be omitted"_

**Comment by dschwen** [comment]
If anyone cares: 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=19249 (open bug from 2005! One guy argues that the gcc interpretation of the standard is correct. No progress on the bug at all.)

http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#257 (The standards committee finds that the gcc interpretation is _not_ what the standard intends and is not intuitive/logical and ammends the standard)

**Comment by dschwen** [comment]
Note to self: there might be a better way using templated inheritance

```
FunctionBaseMaterial <--- DerivativeFunctionBaseMaterial

ParsedMaterialHelper<FunctionBaseMaterial> <--- ParsedMaterial

ParsedMaterialHelper<DerivativeFunctionBaseMaterial> <--- DerivativeParsedMaterialHelper <--- DerivativeParsedMaterial
```

No diamond, because the two ```ParsedMaterialHelper``` templates are different.

**Comment by permcody** [comment]
The fact that your intermediate base classes are abstract also tells me
that you can come up with alternative designs. Take a look at what we did
with the UserObject, PostProcessor inheritance to break the diamond. The
casting gets a little weird (requires a downcast in addition to the normal
upcasting) but the user remains blissfully ignorant.

**Comment by dschwen** [comment]
I've implemented the templated inheritance solution sketched above. It looks a bit cleaner to me. Of course the ```ParsedMaterialHelper``` now contains crazy constructs like ```this->template getMaterialProperty``` but that is hidden from the user. And now the ```FunctionMaterialBase``` class is not virtual anymore and does not require explicit initialization (making the application patches smaller and the interface cleaner).

**Pull request merged**
