### PR TITLE
Remove MooseGhostPointNeighbors src and header

### LINKED ISSUE #24573: Remove MooseGhostPointNeighbors
## Reason
ElementPointNeighborLayers is older and does the same thing

## Design
`git rm`

## Impact
Should be none

### PR DESCRIPTION
**Pull request by brandall25**
closes #24573

## Reason

Deleting redundant/useless code.

## Design

Removed MooseGhostPointNeighbors.C and MooseGhostPointNeighbors.h

## Impact

Should have no impact on APIs.

### CODE REVIEW

**Comment by brandall25** [comment]
@lindsayad This failed some checks when I simply removed the `MoosePointNeighborLayers` files. So, I replaced a the instances of `MoosePointNeighborLayers` in the code with `ElementPointNeighborLayers`.

**Comment by lindsayad** [comment]
sounds good, let's see how CI looks!

**Review by lindsayad — DISMISSED** [review]
Thank you so much for your contribution @brandall25 !

**Comment by brandall25** [comment]
@lindsayad No problem!

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Ok the Griffin failure is real. I can fix it, and then I'll come back here and re-invalidate

**Review by lindsayad — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
