### PR TITLE
Avoid use of libmesh_deprecated() APIs

### LINKED ISSUE #13921: Fix compatibility with libMesh --disable-deprecated builds
## Bug Description
MOOSE still uses deprecated libMesh methods in a few files.

## Steps to Reproduce
Configure libMesh with --disable-deprecated, try to build MOOSE

## Impact
Minor performance and compilation time issues in a few cases, mostly just an annoyance.  I'll put up a fix shortly.

### PR DESCRIPTION
**Pull request by roystgnr**
This (re) closes #13921

One of the changes incidentally should offer a nice memory scalability improvement in the interaction of FeatureFloodCount with distributed meshes.

### CODE REVIEW

**Comment by roystgnr** [comment]
I can replicate this (after switching the test to manually use replicated parallel_type even with my --enable-parmesh libMesh build), but I don't yet understand it.  The failing test passes if I revert just the ConcentricCircleMeshGenerator.C edits, but those look completely innocuous.

**Comment by roystgnr** [comment]
Okay, I get it now.  Those changes *look* completely innocuous, but they're not, because https://github.com/libMesh/libmesh/pull/2473 didn't actually preserve backwards compatibility: the old API arguments now set a *permanent* change in the Mesh behavior, they don't just affect a single prepare_for_use call anymore, and it looks like some MOOSE code started to inadvertently rely on that.  That bug's going to need to be fixed in libMesh, and it looks like some code here is going to need to become a bit more complicated to fix cases that inadvertently started to rely on the new behavior.

**Comment by lindsayad** [comment]
I want to make sure that we get https://github.com/libMesh/libmesh/pull/2584 merged before updating libmesh again (you may just be testing). 

Also note that libmesh updates now need to be accompanied by changing the date [here](https://github.com/idaholab/moose/blob/next/conda/libmesh/meta.yaml#L3) in order to trigger changes to our conda libmesh environment. (Of course we can wait to make that change until this is close to ready to merge and we've settled on the libmesh has we'll be updating to)

**Comment by roystgnr** [comment]
> I want to make sure that we get libMesh/libmesh#2584 merged before updating libmesh again

It would be better to kill two birds with one stone, yeah.  How close is that to being ready?  Looks like you just kicked off new tests 45 minutes ago?

> (you may just be testing).

Yeah; my first crack at this passed for me locally (because I was using a --enable-parmesh libMesh and the bug was only triggered by a REPLICATED-only test).  I don't want to delay finding out if there are are any more surprises.

But I also want to get the libMesh fixes downstream ASAP.  This is a really frightening sort of bug - we only caught it in *one* CI test, despite it being bad enough to seriously trash the mesh in that test, and it was only caught by the exodiff rather than by any internal assertion failures?  We need to get that snuffed out before some application *without* thousands of exodiff tests gets bitten by it.

> Also note that libmesh updates now need to be accompanied by changing the date here in order to trigger changes to our conda libmesh environment.

Thanks!  So much for these tests, then...

**Comment by roystgnr** [comment]
This particular PR isn't urgent - I just tried to build MOOSE against a --disable-deprecated libMesh build and noticed we'd slipped out of date.

Getting a libMesh submodule update in with https://github.com/libMesh/libmesh/pull/2594 ASAP would be good, but that should probably be a separate PR.  Want to start one?  Sounds like the procedure has changed since last time I needed a libMesh submodule update.

**Comment by lindsayad** [comment]
I'll throw one up in not too long

**Comment by roystgnr** [comment]
> I'll throw one up in not too long

I don't see a libMesh PR yet?

Which might be for the better.  I'm seeing a hard-to-trigger regression in adaptive hp refinement.  At the moment I'm knee-jerk blaming @jwpeterson because some of his recent changes are suspiciously related, but I haven't yet figured out exactly what the new bug is, so I'm not even sure if the libMesh/libmesh#2594 merge commit is safe to use or if the regression went in first via  libMesh/libmesh#2593. I also haven't yet figured out how extensive the bug is; if my suspicions are right then adaptive p refinement or even uniform p refinement might break in some cases too.

**Comment by lindsayad** [comment]
Ok, I was gonna put one up tomorrow but I’ll wait until you say go.

**Comment by jwpeterson** [comment]
> I'm seeing a hard-to-trigger regression in adaptive hp refinement.

What are the steps to reproduce this? By "hard-to-trigger" I guess you mean that it doesn't fail every time/fails randomly? Let me know so I can help bisect.

**Comment by roystgnr** [comment]
> By "hard-to-trigger" I guess you mean that it doesn't fail every time/fails randomly?

Not that bad, fortunately; I just meant it's not failing in CI, even though we're now doing "make check" with a hybrid parallel run by default.

Simple ```LIBMESH_RUN="mpirun -np 2" make check -C examples/adaptivity/adaptivity_ex3/``` is enough to hit it for me, and I caught it on higher processor counts, so I think anything but serial is broken for me.  Not sure what aspect of my configuration (```../configure --enable-everything --disable-strict-lgpl --enable-paranoid-warnings --enable-werror --enable-parmesh --disable-deprecated```) is the trigger; the most extreme difference from our typical CI is the default DistributedMesh, but that shouldn't have much if anything to do with the types of errors I'm seeing.

With HEAD, I get
```
Assertion `!elem->active() || fe_type.family == LAGRANGE || elem->refinement_flag() == Elem::JUST_COARSENED' failed.
```
From dof_map.C:2738

Then while trying to bisect I see a *different* error, this time even in serial, e.g. at https://github.com/libMesh/libmesh/commit/5b1b2d76f
```
ERROR: Invalid Order FOURTH selected for LAGRANGE FE family!
```

**Comment by jwpeterson** [comment]
> ERROR: Invalid Order FOURTH selected for LAGRANGE FE family!

Yeah, you can't bisect before 

cf96c76da Merge branch 'bugfix_2592'

otherwise you will get that error.

**Comment by roystgnr** [comment]
Anything I can cherry pick to avoid that?

**Comment by jwpeterson** [comment]
I think you'll need to cherry-pick the commits

libMesh/libmesh@952104b41 Revert to FEInterface::shape() calls taking ElemType.
libMesh/libmesh@9977714e7 compute_node_constraints(): ignore elem->p_level() inherited by sides.

to test any commit in between when libMesh/libmesh#2592 was merged and those fixes... this is a bit annoying, sorry.

**Comment by roystgnr** [comment]
> this is a bit annoying, sorry.

Yeah, but I was looking over every one of those PRs too, and so was CI.  These are sweeping huge changes to low level APIs, I know, but I'm still dumbfounded that two bugs this bad didn't get caught *somehow* before merging.  adaptivity_ex3 gets run with p refinement on every "make check", regardless of configuration, right???

**Comment by jwpeterson** [comment]
Yeah, last we talked about this you said you'd seen the issue before on a different PR. I think something about the `ENABLE_NODE_CONSTRAINTS` code path not being tested by CIVET?

**Comment by roystgnr** [comment]
Yeah, that's definitely something I need to fix in the recipes.  This isn't getting hit from those code paths, though.

**Comment by jwpeterson** [comment]
OK, well I just double-checked and the config summary in CIVET says:
```
  node constraints................. : no
```
so it would be good to figure out why that's disabled (I assume it's explicitly disabled?) and see whether we can get it turned back on at some point.

**Comment by lindsayad** [comment]
Node constraints are disabled by default in configure

**Comment by roystgnr** [comment]
Yeah, we have had problems with that before and we do need to start enabling node constraints in at least one test recipe, but (after a bit of waffling) I'm still failing to see how that could be what's giving me failures where CI sees passes.  The stack trace just isn't going anywhere near the node constraints code, and this is a non-moving mesh where the node constraints code should basically be a complicated no-op in the end anyway.

**Comment by roystgnr** [comment]
Got this figured out now.  There's some very old weird behavior in our side_ptr code that's interacting with some weird-but-more-justifiable newer behavior in set_p_level, which can corrupt p_level values when we combine adaptive p refinement with (any kind of) h refinement.  The Correct(TM) fix shouldn't be hard, as long as nobody's depending on the old weird behavior, so I'll try that first.

**Comment by roystgnr** [comment]
Not **100%** certain, but I'm betting a failure that only affects Mac+Python+Peacock wasn't my fault...  :smile:  I'll kick it after (if) the remaining tests come back green.

**Comment by roystgnr** [comment]
@lindsayad - this should be okay to merge at any time now.

I'm getting happier and happier about the --disable-deprecated libMesh option; 3 of the 7 commits here turned out to be performance or bug fixes that simply got caught because they were also libmesh_deprecated() code paths.

**Review by lindsayad — APPROVED** [review]
Thanks @roystgnr !

**Pull request merged**
