### PR TITLE
Update seacas to 2024-03-11

### PR DESCRIPTION
**Pull request by cticenhour**
See https://github.com/sandialabs/seacas/releases/tag/v2024-03-11 for details

Refs #21665

### CODE REVIEW

**Comment by milljm** [comment]
We should probably just drop Intel...

**Comment by cticenhour** [comment]
The error message looks like it is missing an ARM-specific header, but in an Intel machine. Maybe there wasn't Mac Intel testing for this release? I'll have to peek at the source later.

**Review by milljm — APPROVED** [review]
👍

**Review by loganharbour — APPROVED** [review]

**Comment by cticenhour** [comment]
GCC min debug failures are concerning two modules tests:

- `solid_mechanics/test:ad_smeared_cracking.rz_exponential`, and 
- `contact/test:pdass_problems.cylinder_friction_penalty_al_frictional_action_amg`

the former of which is also [currently intermittently failing](https://civet.inl.gov/job/2148607/) on `next` testing. Both failures are timeouts and neither use `moose-seacas`. Therefore they are unrelated to the present PR, and this can be merged.

**Pull request merged**
