### PR TITLE
Changed location where residual vector is initialized to allow userob…

### PR DESCRIPTION
**Pull request by sveerara**
…jects to edit residual vector #6057

### CODE REVIEW

**Comment by YaqiWang** [comment]
This fails Yak because there are cases in Yak where `NonlinearSystem::computeResidual()` is called separately without calling `FEProblem::computeResidual()`.

**Comment by sveerara** [comment]
I will try moving the computation of post-aux user objects to after NonlinearSystem::computeResidual() and see if that resolves the issue with user objects. That way no changes would have to be made to Yak.

**Comment by YaqiWang** [comment]
Nope, I do not think that is right move. There are chances kernels depending the post-aux user objects... Patching yak is extremely simple, actually only one place needs to be changes. If we decide this change is good with Moose developers, I can patch Yak for you.

**Comment by sveerara** [comment]
If I move the computation of post aux user objects to after NonlinearSystem::computeResidual(), some of the moose tests are failing. 

I can use dirackernels to apply Nodal forces instead of NodalUserObjects if it is too much effort to patch the Yak.

**Comment by sveerara** [comment]
I have moved the initialization of residual vector to the beginning of FEProblem::computeResidualType(). Thanks!

**Comment by YaqiWang** [comment]
I should let you know that we changed that piece of code in yak because we think calling nonlinear system residual evaluation may not be proper although it is more efficient. We'd rather sacrifice a little on efficiency to gain the generality. You could restart the test and possibly this time the test will pass ;-)

**Comment by sveerara** [comment]
Thanks for making the changes to Yak. I have restarted the tests. I hope they will pass now.

**Comment by YaqiWang** [comment]
ha, now it is mamot failing, hehe.

**Comment by sveerara** [comment]
Ah ok. I guess I will just use Dirac kernels to apply the nodal forces instead of using nodal user objects. Thanks for your help.

**Comment by dschwen** [comment]
Are you sure the marmot failure was not due to my PR?

**Comment by sveerara** [comment]
I do not have access to marmot or yak so I am not sure why the tests failed.

**Comment by dschwen** [comment]
I invalidated the app tests. The MARMOT fail was not caused by this PR.

**Comment by sveerara** [comment]
Thanks for looking into the app tests and figuring out the problem.

**Comment by permcody** [comment]
I wouldn't mind having @andrsd or @friedmud look at this. Basically she wants to zero out the Residual vector a little earlier so that she can possibly contribute to it from a UserObject. That seems ok to me, but I'd like a second opinion.

**Comment by andrsd** [comment]
Zeroing out `residual`, `residual(KT_TIME)` and `residual(KT_NONTIME)` earlier is fine.

Just keep in mind that whatever your user objects are doing with the residual, they should probably go via `Assembly` interface. Accessing `residual` directly is wrong, because that vector is build up by time integrators, so whatever you put into it is going to be overwritten. Also you should not be messing with `KT_TIME`, since those are time derivatives and will be destroyed by `TimeIntegrator` as well. If you use the `Assembly` interface properly it will modify KT_NONTIME correctly. Just a comment on your issue you are trying to solve where you refer to residual, but it does not say which one you have in mind...

Another thing is that user objects were not designed to contribute to residual. You may want to look at `NodalKernels` system and if that does what you need, then you do not need this patch at all...

**Comment by sveerara** [comment]
I will be adding to the KT_NONTIME residual vector. I will make sure to go through the assembly instead of accessing the residual vector directly. But this user object would be executed during the residual calculation phase. So I am not sure if why it would be overwritten by the time integrators as this is probably the innermost iteration. 

I need to edit the residual of nodes lying on a boundary and I don't think Nodal Kernels can be restricted to a boundary.

I was able to use DiracKernels to apply forces at the nodes. But I feel editing the residual at the node using a nodaluserobject would be more efficient than finding the element the node belongs to and then splitting the force among the quadrature points belonging to that element.

**Comment by andrsd** [comment]
> So I am not sure if why it would be overwritten by the time integrators as this is probably the innermost iteration.

Because time derivatives and the final residual are computed and build every linear iteration (in JFNK solve).

> I need to edit the residual of nodes lying on a boundary and I don't think Nodal Kernels can be restricted to a boundary.

Then we should make that change, it makes more sense then to allow system that was not design to modify residual to modify residual. Just my 2 cents on the subject...

**Comment by sveerara** [comment]
Thanks for the comment. I will try to make that change to Nodal kernels. Then UserForcingFunctionNodalKernel can be used to solve my problem.

**Comment by andrsd** [comment]
> I will try to make that change to Nodal kernels.

In that case, here is a few pointers to get you started:
1) go look at `AuxWarehouse` how we store nodal auxes restricted to blocks and boundaries and mimic that in `NodalKernelWarehouse`.
2) You will need something similar to what `ComputeNodalAuxBcsThread` is doing, but modified for `NodalKernels`.
3) `NonlinearSystem::addNodalKernel` will need to check if the nodal kernel is block/boundary restricted and do the right thing.
4) `NonlinearSystem::computeResidualInternal` needs to be modified so that boundary restricted nodal kernel are evaluated. Probably after the block ones are done.

**Comment by friedmud** [comment]
Firstly...

> But I feel editing the residual at the node using a nodaluserobject would be more efficient than finding the element the node belongs to and then splitting the force among the quadrature points belonging to that element.

This is not a valid reason to do anything.  You're optimizing before you know that there is an issue.  You're abusing a system for a purpose it wasn't intended for... that ALWAYS has consequences and in this case I am firmly against this PR.

Did you actually try this with DiracKernels?  And I presume that you've done detailed time profiling to show that doing it that way makes DiracKernels take up a large percentage of your runtime (it would need to be 20-30% before it makes sense to even start optimizing it).

In the long run, using systems as they were intended will yield stabler, cleaner and more effective code.  Going outside the bounds of any system has consequences for us all... making MOOSE harder to maintain (because there are little dependencies throughout the code on ordering, etc that aren't clear... so it makes it difficult to evolve the code base).

I'm glad to hear that you're thinking of switching to NodalKernels... if those map well to your problem then that seems like a fix.

Can we close this PR?

**Comment by sveerara** [comment]
Thanks for the comment. I will try to edit the Nodal Kernels and submit it as a separate PR. If I am not able to get it to work with Nodal Kernels then I will use Dirac Kernels. I will close this PR.

**Comment by friedmud** [comment]
@sveerara do you need NodalKernels restricted to boundaries / blocks like @andrsd was talking about?  If so, take a look at it... and if it seems like it's too much trouble for you, let me know.  I may be able to do it for you within the next few days (probably not today though).

**Comment by sveerara** [comment]
I will be working on the Nodal Kernels part today. If I am not able to get
that to work, I will let you know. Thanks!

**Comment by friedmud** [comment]
Great - just let me know if you run into any trouble.  I'll actually be working in NodalKernels today as well... I'm going to finish off: #5951

**Pull request closed without merging**
