### PR TITLE
Various Dockerfile improvements

### LINKED ISSUE #18658: Enable testing of the Dockerfile
## Reason
Currently, we don't test the Dockerfile. We need to make some improvements to it so that it's capable of well-rounded testing.

## Design
- Add an option to build the modules within the container
- Add options for libmesh and PETSc compiles
- Add python packages that will enable the testing of Python.

## Impact
A more feature-full MOOSE docker container and testing of said container.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #18658

### CODE REVIEW

**Review by herter4171 — DISMISSED** [review]
I can't speak to the failing checks, but I've been able to reproduce a working result using the head of this branch.

**Comment by loganharbour** [comment]
Alright @herter4171... think I'm ready for another look.

Ignore the cancelled tests, I'll fix them up once https://civet.inl.gov/job/800282/ works.

**Review by herter4171 — DISMISSED** [review]
Looks good to me.  Built functional images for Ubuntu 20.04 and CentOS 8 from the most recent commit that wasn't dealing with comments and whitespace, so I approve.

**Review by milljm — APPROVED** [review]

**Comment by loganharbour** [comment]
One last fix to the civet recipe... need to grab large_media when testing python.

**Pull request merged**
