### PR TITLE
Heavy valgrind for mortar thermomech tests

### PR DESCRIPTION
**Pull request by recuero**
(#22596)

### CODE REVIEW

**Comment by loganharbour** [comment]
You made six tests heavy but only three run in heavy on https://civet.inl.gov/job/1232385/

Do not all of these run in valgrind?

**Comment by recuero** [comment]
Is CIVET identifying the labels properly?

``` [0.000s]     SKIP test:mortar_tm/2drz/ad_frictionless_second.stiff/soft_stiff [Valgrind==NORMAL, HEAVY]
[0.000s]     SKIP test:mortar_tm/2drz/ad_frictionless_second.stiff/stiff_stiff [Valgrind==NORMAL, HEAVY]
[0.000s]     SKIP test:mortar_tm/2drz/ad_frictionless_second.soft/finite_rr [Valgrind==NORMAL, HEAVY]
[0.000s]     SKIP test:mortar_tm/2drz/ad_frictionless_second.soft/finite_scaling [Valgrind==NORMAL, HEAVY]

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Those tests won't run unless `--heavy` is passed to the test harness. But the valgrind heavy recipe just passes `--valgrind-heavy`

**Comment by loganharbour** [comment]
Still failing: https://civet.inl.gov/job/1232982/

**Comment by loganharbour** [comment]
You forgot to start on `next` and set heavy to the ones that were actually failing

**Comment by recuero** [comment]
https://github.com/idaholab/moose/pull/22672

**Pull request merged**
