### PR TITLE
Fix SLEPc include guard in the .C file

### PR DESCRIPTION
**Pull request by permcody**
refs #13292

### CODE REVIEW

**Review by fdkong — APPROVED** [review]

**Comment by YaqiWang** [comment]
Is MOOSE currently broken without this?

**Comment by permcody** [comment]
The next branch is, but that's OK - the next branch is frequently broken, which is why you branch from devel.

**Comment by YaqiWang** [comment]
Oh, so a PR should be branch off from `devel`? If I have a PR already from next, how should I fix it?

**Comment by permcody** [comment]
Well in the special case where you are trying to fix something that was
merged into next but is broken. You have no choice but to branch from next.
Most of the time you should be using devel.

**Pull request merged**
