### PR TITLE
Add mean-zero pressure approach for INS

### PR DESCRIPTION
**Pull request by jiangwen84**
closes ref #15549

### CODE REVIEW

**Comment by jiangwen84** [comment]
@lindsayad  could you review it? Thanks.

**Comment by jiangwen84** [comment]
@jwpeterson FYI.. Any suggestions?

**Comment by jwpeterson** [comment]
:+1: looks good to me assuming you checked the solution and it seems reasonable :) 

I vaguely remember writing that PDF documentation at some point, so, good to see that it is still there. I also have the original LaTeX file laying around in case that should be checked in somewhere.

**Comment by jiangwen84** [comment]
Yes, the velocities solution seems to be reasonable. The left is with mean-zero pressure and the right is with pinning pressure. 

solution

**Comment by jwpeterson** [comment]
One minor point is that the name `PostprocessorCED` I always found a bit confusing since it is not a Postprocessor but rather a ScalarKernel that uses a Postprocessor. Also I think "CED" stands for "constrained" but that's also not immediately obvious. So, something like AverageValueConstraint and putting it in the constraints/ directory might make more sense.

**Comment by jiangwen84** [comment]
@jwpeterson Very good suggestions. I did not change the name before because I want to code be consistent with the pdf where it refers to the `PostprocessorCED`. Since you have the LaTex file, I am happy to change the name and update the document.

**Comment by jwpeterson** [comment]
> Since you have the LaTex file, I am happy to change the name and update the document.

Sounds good, I will just email it to you directly.

**Review by jwpeterson — DISMISSED** [review]

**Review by lindsayad — COMMENTED** [review]
Why did the gold files in test have to get touched?

**Comment by jiangwen84** [comment]
I thought exdous would store some input file information. Since I rename one class,  I feel it might be good to update them as well.

**Comment by lindsayad** [comment]
I never like regolding if it can be avoided. However, if you can assure me
that an exodiff with the old gold file is clean, then I can live with it.

**Comment by jiangwen84** [comment]
Reverted them.

**Review by lindsayad — APPROVED** [review]
Thanks @jiangwen84 !

**Comment by lindsayad** [comment]
This is really slick stuff @jiangwen84. I just implemented the corresponding version for finite volume where we cannot even pressure pin a node!

**Pull request merged**
