### PR TITLE
Make discrete nucleation recoverable

### LINKED ISSUE #6729: Make discrete nucleation restartable
### Description of the enhancement or error report
Add a few `declareRestartable`s in the discrete nucleation system.

### Rationale for the enhancement or information for reproducing the error
Will allow correct restart of simulations involving nucleation.

### Identified impact
see above

### PR DESCRIPTION
**Pull request by dschwen**
Closes #6729

### CODE REVIEW

**Comment by aeslaughter** [comment]
Since we don't run modules with --recover, do you want add a targeted test to make sure that this works?

**Comment by dschwen** [comment]
How?

**Comment by dschwen** [comment]
How about we run modules with recover but default to `recover = false` (so it needs to be explicitly enables)

**Comment by aeslaughter** [comment]
see /moose/test/tests/output/recover/tests

**Comment by dschwen** [comment]
Ok, done @aeslaughter, check it out.

**Pull request merged**
