### PR TITLE
Pass old strain into UMAT

### LINKED ISSUE #18843: Pass old total strain into UMAT
## Bug Description
We are passing the current total strain into Abaqus UMAT plugins, where the plugin expects the "strain at the beginning of the increment", which in MOOSE terms is the _old_ strain.

## Steps to Reproduce
Read the code and compare to the Abaqus manual. Run any model that uses the total strain value.

## Impact
Enable MOOSE to reproduce Abaqus results with custom UMATs (for example for creep modeling)

tagging @recuero

### PR DESCRIPTION
**Pull request by dschwen**
Closes #18843

### CODE REVIEW

**Comment by dschwen** [comment]
Pinging UMAT user @edwardXZ06.

**Review by bwspenc — CHANGES_REQUESTED** [review]
The code changes look reasonable, but can we add a test that is affected by this?

**Comment by dschwen** [comment]
Test added. Can we be friends again?

**Comment by dschwen** [comment]
Ugh, I'll have to create a new PR for this tomorrow as Civet will go down tonight and we've been asked not to open new PRs.

**Pull request closed without merging**
