### PR TITLE
renamed unit/data to unit/database in geochemistry

### LINKED ISSUE #15109: Geochemistry: rename data directory to database in unit tests
## Reason

Consistency with the other parts of geochemistry

## Design

Something like `mv unit/data/*.* unit/database/.`    and update unit tests accordingly

## Impact

Just consistency in the naming structure

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #15109

### CODE REVIEW

**Comment by WilkAndy** [comment]
Here's a super easy one for you @loganharbour !   Or maybe you want to stay away from geochemistry for a while?  If so, i'll hassle someone else.

**Review by loganharbour — APPROVED** [review]
👍 will merge when the box turns green

**Comment by loganharbour** [comment]
I'll keep my eye on this. There's a few other passes that should have been failures (although not due to this PR). We should have a fix in for it tomorrow.

**Comment by WilkAndy** [comment]
Thanks @loganharbour

**Comment by fdkong** [comment]
We take care of the PR once I fix that crappy test. Thanks

**Comment by WilkAndy** [comment]
Thanks @fdkong

**Comment by WilkAndy** [comment]
Cool, thanks @loganharbour and @fdkong

**Pull request merged**
