### PR TITLE
First stab at removing deprecated content

### PR DESCRIPTION
**Pull request by loganharbour**
refs #0

Another side task... looking to see what we can actually remove.

### CODE REVIEW

**Review by dschwen — COMMENTED** [review]
Decisive move! Over 2000 lines removed. So much red. Love it!

**Comment by loganharbour** [comment]
>Decisive move! Over 2000 lines removed. So much red. Love it!

Testing still looks like an xmas tree.... working on it

**Comment by GiudGiud** [comment]
@loganharbour taking a similar stab in modules tests. Just so we dont duplicate effort

**Comment by loganharbour** [comment]
Sounds good. This is pretty stale. I'm going to break it up into smaller PRs.

**Pull request closed without merging**
