### PR TITLE
Help!  Code duplication.  Sad.

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #19072

Here you see a MeshModifier that defines SubdomainID using a Function.  **Almost all the code is more-or-less directly copied from PiecewiseConstant and its subclasses.  Oh dear.**

1. What i'd like: to define SubdomainID using a MOOSE Function.  I can't get this to work because _fe_problem is not defined when creating the mesh, so i can't use `getFunction`.
2. Alternatively, i could define SubdomainID using the same user interface as a Piecewise Function.  PiecewiseConstant is probably least prone to user errors.  That's what this PR essentially does.  But ideally, i'd like to use `PiecewiseConstant::value` to define subdomainID without all this code duplication, so perhaps i'd like to inherit from PiecewiseConstant, but the best i could get was MOOSE exiting with error "add_mesh_generator is not registered to build Function derived objects".

It'd be great if someone could suggest a way around my problems, or suggest a different approach.

Don't focus on the details of the current code - i'll tidy and test it later if no one can think of a better approach.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Notifying @cpgr

**Comment by WilkAndy** [comment]
> You can change subdomain IDs later in the simulation. This means a user object that runs on initial could do the ID assignment. We're doing that in the element death system.

Yea, that's an idea.  I reckon out workflow would work with that, agreed @cpgr ?

**Comment by cpgr** [comment]
> > You can change subdomain IDs later in the simulation. This means a user object that runs on initial could do the ID assignment. We're doing that in the element death system.
> 
> Yea, that's an idea. I reckon out workflow would work with that, agreed @cpgr ?

When in doubt go to the user object! Sounds great. Are you happy to try it @WilkAndy or do you want me to have a go (I'm hoping you have already done it in the hour it's taken me to reply, hehehe)?

**Comment by WilkAndy** [comment]
> > > You can change subdomain IDs later in the simulation. This means a user object that runs on initial could do the ID assignment. We're doing that in the element death system.
> > 
> > 
> > Yea, that's an idea. I reckon out workflow would work with that, agreed @cpgr ?
> 
> When in doubt go to the user object! Sounds great. Are you happy to try it @WilkAndy or do you want me to have a go (I'm hoping you have already done it in the hour it's taken me to reply, hehehe)?

I haven't done it, but will do it.

**Comment by WilkAndy** [comment]
Hi @dschwen , do you think you could help with this?  You'll see i've added a CoupledVarSubdomainModifier UserObject that does what i want.  However, it does not work with `execute_on = INITIAL` because MOOSE complains as below.  On `TIMESTEP_END` everything works fine.

From
```
cd moose/test/tests/userobjects/coupled_var_subdomain
../../../moose_test-opt -i coupled_var_subdomain.i
```
the error is:
```
*** ERROR ***
The following error occurred in the object "MOOSE Problem", of type "FEProblem".

Requested subdomain 1 does not exist.

Stack frames: 23
0: 0   libmesh_opt.0.dylib                 0x000000010d945274 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1252
1: 1   libmoose-opt.0.dylib                0x000000010cde7fac moose::internal::mooseErrorRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 988
2: 2   libmoose-opt.0.dylib                0x000000010cd4944f callMooseErrorRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, MooseApp*) + 111
3: 3   libmoose-opt.0.dylib                0x000000010c63225f void MooseObject::mooseError<char const (&) [21], unsigned short&, char const (&) [17]>(char const (&) [21], unsigned short&, char const (&) [17]) const + 447
4: 4   libmoose-opt.0.dylib                0x000000010c632091 FEProblemBase::getCoordSystem(unsigned short) const + 113
5: 5   libmoose-opt.0.dylib                0x000000010cd8b808 void Assembly::setCoordinateTransformation<MooseArray<libMesh::Point>, MooseArray<double> >(libMesh::QBase const*, MooseArray<libMesh::Point> const&, MooseArray<double>&, unsigned short) + 72
6: 6   libmoose-opt.0.dylib                0x000000010cd8b94c Assembly::computeCurrentElemVolume() + 60
7: 7   libmoose-opt.0.dylib                0x000000010cd8c3c8 Assembly::reinit(libMesh::Elem const*) + 408
8: 8   libmoose-opt.0.dylib                0x000000010c63f1d7 FEProblemBase::prepare(libMesh::Elem const*, unsigned int) + 39
9: 9   libmoose-opt.0.dylib                0x000000010c9b7e29 ComputeInitialConditionThread::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&) + 1401
10: 10  libmoose-opt.0.dylib                0x000000010c64e81b void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeInitialConditionThread>(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, ComputeInitialConditionThread&) + 59
11: 11  libmoose-opt.0.dylib                0x000000010c64f4b4 FEProblemBase::projectInitialConditionOnCustomRange(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>&, libMesh::StoredRange<MooseMesh::const_bnd_node_iterator, BndNode const*>&) + 52
12: 12  libmoose-opt.0.dylib                0x000000010c840746 ElementSubdomainModifier::finalize() + 694
13: 13  libmoose-opt.0.dylib                0x000000010c65714f FEProblemBase::joinAndFinalize(TheWarehouse::QueryCache<>, bool) + 271
14: 14  libmoose-opt.0.dylib                0x000000010c658129 FEProblemBase::computeUserObjectsInternal(MooseEnumItem const&, Moose::AuxGroup const&, TheWarehouse::QueryCache<>&) + 2889
15: 15  libmoose-opt.0.dylib                0x000000010c659aca FEProblemBase::computeUserObjects(MooseEnumItem const&, Moose::AuxGroup const&) + 250
16: 16  libmoose-opt.0.dylib                0x000000010c62b03d FEProblemBase::execute(MooseEnumItem const&) + 173
17: 17  libmoose-opt.0.dylib                0x000000010c634b6a FEProblemBase::initialSetup() + 6074
18: 18  libmoose-opt.0.dylib                0x000000010cdbac1d MooseApp::executeExecutioner() + 93
19: 19  libmoose_test-opt.0.dylib           0x000000010bf385a3 MooseTestApp::executeExecutioner() + 195
20: 20  libmoose-opt.0.dylib                0x000000010cdbc040 MooseApp::run() + 3344
21: 21  moose_test-opt                      0x000000010bcb6bb5 main + 133
22: 22  libdyld.dylib                       0x00007fff68a1ecc9 start + 1
```

**Comment by WilkAndy** [comment]
@dschwen  - any thoughts on this "initial" problem?

**Comment by dschwen** [comment]
Stupid question: would it work on `TIMESTEP_BEGIN`? And then doing it only on step 0?

Otherwise @hugary1995 might have a better idea.

**Comment by hugary1995** [comment]
It seems to me that `setCoordSystem` is the only missing call. Did you try it?

**Pull request closed without merging**
