### PR TITLE
An approach for controlling MaterialProperties

### PR DESCRIPTION
**Pull request by aeslaughter**
Here is just a prototype of how we could control material properties: make the Control object a Material and let it change material properties.

There is work to done to make this be proper, but I think that this is a valid approach and will not be difficult to implement. Sure it suffers from efficiency because things are being recomputed, but it works...

### CODE REVIEW

**Comment by aeslaughter** [comment]
@friedmud @andrsd @permcody @jwpeterson you may want to comment on this.

**Comment by mangerij** [comment]
So just some input here..

When I heard the developers were planning this I was excited because you will be able to control the elasticity tensor which can change during the simulation. Typically many maaterials have different allowed phases under ertain conditions. One such simple example is a cubic to tetrgonal phase transition so if you are using symmetric9 then you can just do that but perhaps you could have a situation where fillMethod needs to be controlled as well.

**Comment by dschwen** [comment]
Changing an elasticity tensor can be done already, with the property
material. Check out CompiuteVariableElasticityTensor

**Comment by friedmud** [comment]
Yes, @dschwen is right.  The Control logic capability is NOT for implementing physics.  Physics should be implemented in Kernels / Materials, etc.

Control logic is for modifying the behavior of a simulation.  Like turning on a BC at a specific time or activating a forcing term or making decisions (like shutting down a reactor simulation because it reached an unsafe operating condition).

I'm sure it will be used for much more than that... but when you're talking about serious physics (like computing elasticity tensors) that should be implemented in your code...

**Comment by permcody** [comment]
Is there any reason that you can't accomplish this with the existing systems as they are? Material properties are very powerful. Instead we should think about how to couple CL objects into the existing systems instead of having CL do everything.

**Comment by aeslaughter** [comment]
@permcody There is nothing you can do in control logic that you can't do with the other systems in MOOSE. The point is to provide an simple access point to make scrip-table changes to a simulation.

I would be happy to explore other means for controlling materials, this was just a simple idea that I think would serve our needs.

**Comment by permcody** [comment]
The point is that we don't want to encourage the use of the CL system for controlling things like material values. In fact, I'd almost like to disallow it if possible. Why not create an example more in line with what the system is designed for? (e.g. changing a boundary condition or turning a kernel on/off based on some other function or state)

**Comment by aeslaughter** [comment]
Those other things will come, but I was under the impression from @andrsd
that changing material properties is something that will be needed.

**Comment by andrsd** [comment]
Yes, that's one of the requirements for RAVEN...

**Comment by permcody** [comment]
OK - changing material properties per quadrature point or changing "state" so that properties are calculated differently. This is an important distinction and one we should be very careful about.

**Comment by aeslaughter** [comment]
Agreed. I think it would be possible to create a MaterialBase that is inherited by both Materials and Controls w/o diamond inheritance or by using virtual inheritance. Then a `Control` would have two methods for required by the user to implement:

- "execute()" which does parameter stuff at the simulation level
- computeQpProperties which does the materials stuff

If people are on board with this I will start down this approach. I will first get the Control in MOOSE that does just parameter stuff, I will then start with the material stuff.

**Comment by aeslaughter** [comment]
What I implement is that a ControlLogic can be a material (w/o declaring)
so it can set qp values.

**Comment by aeslaughter** [comment]
We agreed not to control materials in this fashion.

**Pull request closed without merging**
