### PR TITLE
Reference list

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
https://mooseframework.inl.gov/docs/PRs/15312/site/publications.html

**Comment by aeslaughter** [comment]
I am not sold on this organization. It might be better to organize by peer-reviewed, conferences, reports, etc. @permcody Could this be an intern task?

**Comment by lindsayad** [comment]
What's the difference between "cited by" and "research using"?

**Comment by aeslaughter** [comment]
That is a question for @jwpeterson

**Comment by jwpeterson** [comment]
> What's the difference between "cited by" and "research using"?

Pretty much what it says. For the former, a paper can have a sentence like: "The following are examples of multiphysics solver frameworks [6-12]" and MOOSE is one of those, but isn't used for the simulations in the paper. For the latter, the authors actually ran MOOSE and are presenting those results in the paper.

**Review by lindsayad — APPROVED** [review]
Seems like the organization bit can be revamped at a later time. This looks nice. Thanks @aeslaughter @jwpeterson

**Pull request merged**
