### PR TITLE
Fix sign inconsistency in GeneratedMesh

### LINKED ISSUE #7197: Fix sign issue in GeneratedMesh
### Description of the enhancement or error report

_nx, _ny, _nz are all signed but should be unsigned

### Rationale for the enhancement or information for reproducing the error

I plan to do some comparing of these values against vector lengths and don't really want to cast those values to avoid warnings.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None

### PR DESCRIPTION
**Pull request by permcody**
closes #7197

### CODE REVIEW

**Comment by permcody** [comment]
Well now I know why this wasn't done before. It requires several changes, also at least Yak will need a patch. We'll see if there are other apps.

**Comment by permcody** [comment]
I have a Yak patch ready.

**Comment by jwpeterson** [comment]
@permcody swears his Yak patch is one line.

**Comment by permcody** [comment]
Proof can be found here:
https://hpcgitlab.inl.gov/idaholab/yak/merge_requests/564/diffs

**Pull request merged**
