### PR TITLE
Enable executioners setting user indicated controls

### LINKED ISSUE #14361: Enable executioners setting controls
## Reason
The reason for this is that: in neutronics calculations, we often have something called criticality search, during which we basically adjust a parameter in the input so that the eigenvalue reaches a certain value. If we can make a parameter controllable and add a function in `Executioner` like
```
  ControllableParameter getControllableParameter(const std::string & param_name) const
  {
    return _app.getInputParameterWarehouse().getControllableParameter(getParam<std::string>(param_name));
  }
```
we can let executioner accept a controllable parameter and change the parameter during the calculation.

## Design
Using `Control` in the input file will be really difficult not only for developers but also for users. I personally think this is a reasonable feature. If you agree, I can send in a PR. 

## Impact
New feature.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #14361. Simple yet powerful new capability!

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody Ready for review. Of course the test is just a toy.

**Comment by permcody** [comment]
I'm having second thoughts about this design. The original design of the Control system was to only allow controls the ability to change parameters. Now we are explicitly breaking that design for convenience. 

Let's take a step back for a second. Even if it's more difficult, is it possible to just add a Control to the Executioner to do this work for you? Maybe even as a member to your Executioner? One of the things that caused me pause we seeing the introduction of that new "friend" member to give Executioners the same access to Controllable parameters as the Control system. From a frameworks perspective, I'd really prefer to avoid that. Let's brainstorm for a minute and see if we can delegate this task to a Control somehow.

**Comment by YaqiWang** [comment]
The problem with `Control` is that it sets parameter only at certain execution time. This design allows executioner to set parameters for its own purpose, like search a parameter to make the system critical. Unless Executioner can forcely execute Controls, it is not going to satisfy the requirement in this issue. In this MR, basically I am granting executioner to use the machinery `Control`s are using, which seems reasonable to me.

**Comment by YaqiWang** [comment]
Even we can create a special Control for executioner, I do not think it is necessary and complicates the design. I do not like `friend` either. One solution is to simply make `InputParameterWarehouse::getControllableParameter` public.

**Comment by YaqiWang** [comment]
Oh one question: is the `friend` inheritable by derived executioners? If not, I do not think we should bother much since `Executioner` is inside MOOSE framework and we can make sure it is not being abused.

**Comment by permcody** [comment]
> The problem with Control is that it sets parameter only at certain execution time. This design allows executioner to set parameters for its own purpose, like search a parameter to make the system critical. 

Sure but this is exactly what gives me the chills from a frameworks maintainable standpoint. Executioners can now change any parameter in the system at any time. All of the power of the Control system and much more.

> Unless Executioner can forcely execute Controls, it is not going to satisfy the requirement in this issue.

This might be the right idea. We already have the ability to register new `execute_on` flags and this is the design for the Executioner. To execute things. Then you don't need to do anything different here, you just create a new control and execute it on your custom tag. It might not be as convenient as this simple change but it's completely within line of the current design of both the Executioner and Control systems.  

> In this MR, basically I am granting executioner to use the machinery Controls are using, which seems reasonable to me.

Perhaps, but then why do we need Controls, what's the difference between an Executioner and a Control. Should Executioners just inherit from the Control system now? Why are they special? What kinds of holes do we open up by having Executioners behave like Controls without being Controls? It is a small change but it could have big implications because of how general and powerful the ability to change any simulation parameter is. 

> Even we can create a special Control for executioner, I do not think it is necessary and complicates the design. I do not like friend either. One solution is to simply make InputParameterWarehouse::getControllableParameter public.

You aren't thinking like a designer now. If that method is made public, then any object in any system can change any parameter. That means we can drop the Control system altogether. It's private for a reason.

> Oh one question: is the `friend` inheritable by derived executioners? If not, I do not think we should bother much since Executioner is inside MOOSE framework and we can make sure it is not being abused. Note: this function only provides a very limited access for the derived executioners.

`friend` is not inherited - but that's another problem with this PR. It doesn't need to be since you are exposing the Control interface through a new public member. Again, With this PR as it sits, any object could control any parameter at any time. For sure, this method should be `protected` but that still gives any Executioner full control over the parameters system. 

Can we look at making this work by just executing controls (like Executioners do) and just having the desired control added to the simulation, either explicitly, or through an Action? You realize that you probably won't even need a MOOSE PR if you do it that way.

**Comment by YaqiWang** [comment]
`gives any Executioner full control over the parameters system` is not right. It is users' decision to let Executioner to control something. Note the executioner is not setting any control parameter but the one specified in the input. Did I open a hole to the framework? I do not think so.

You realized how miserable my life will be if I do not have this function, do you? We currently have something already. We derived a special function that has a mutable member function, which can be called by Executioner. It is difficult to use for users and hard to extend. Using controls and custom executioner makes things even worse. The simpler code design is, the better.

**Comment by permcody** [comment]
I'm not trying to make your life miserable.

> Did I open a hole to the framework? I do not think so.

Yes you did. You add a new **public** member function to Executioner, which can change a controllable value. At the very least that must be moved to `protected`.

I want to get @aeslaughter's take on this before we merge it in. I can probably live with Executioners being able to control but I still don't see why you can't just trigger a Control to be a proxy for you, then nothing has to change. I'll be on travel next week.

**Comment by YaqiWang** [comment]
Yes, that member function is intended to be protected. I was not paying attention.

**Comment by YaqiWang** [comment]
@aeslaughter What is your opinion? Note that I proposed this because of a need for an custom executioner. I am as well wanting the framework to be bullet proof. ;-)

**Comment by aeslaughter** [comment]
Here is my view. You should use the Control system with the ability to add a custom execution flag. 

1. In your application create a new execution flag
2. Create your control and add the new flag to the list of execution flags
3. Create your Executioner that calls FEProblemBase::executeControls(MY_NEW_FLAG);

**Comment by aeslaughter** [comment]
I guess I will add that if we support the ability of the Executioner to change a parameter, it is the same as allowing every object that ability, because the Executioner is available everywhere (which is a whole different problem). And once we do that, the Control system is not needed and our ability to actually control parameters for stochastic simulations becomes much harder, if not impossible because any object anywhere can change it, even if it is changed by a Control.

As MOOSE evolves the systems will become more restricted so that we can dictate the 
program flow. If you are worried about the amount of input syntax then a custom action is needed for the general user.

**Comment by YaqiWang** [comment]
I will try this approach, that sounds reasonable to me. I will report back if I am going to still need this PR or not.

**Comment by YaqiWang** [comment]
My preliminary implementation in Rattlesnake shows this is is a reasonable approach. It requires some setup but ok. I will tag your guys on my MR in Rattlesnake later. The custom execution is pretty powerful. Thanks for the comments.

**Pull request closed without merging**
