### PR TITLE
Add October 2021 news

### PR DESCRIPTION
**Pull request by cticenhour**
@idaholab/moose-ccb Now that September 2021 is merged into next, I'm opening October early so that people can be pinged for updates. Please add your contributions for October 2021. 

Refs #11447

### CODE REVIEW

**Comment by loganharbour** [comment]
@lindsayad functor material property and 3D mortar content please

@eshemon it would be great to have someone add some content (a summary) about the new reactor meshing capability - what all is in it and what all is to come. Would you mind delegating to someone?

**Comment by eshemon** [comment]
@miaoyinb and I will work on getting a summary together.

**Comment by eshemon** [comment]
@miaoyinb  and I will work on getting a summary together.

**Comment by cticenhour** [comment]
Thank you! When your addition is ready, you can point me to the branch and I can add the commit to this directly.

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
