### PR TITLE
Improve links to module examples

### LINKED ISSUE #22923: Improve links to module tutorials
## Reason
Several of the modules have tutorial pages, but finding them is difficult on the MOOSE website. The main MOOSE page on tutorials is missing links to some of the module tutorials/examples, and doesn't really convey what they are.

## Design
Provide links to other tutorials and improve the wording.

## Impact
No impact on code behavior, only webpage organization.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #22923

### CODE REVIEW

**Review by friedmud — COMMENTED** [review]
This looks good - but I want to see what the website looks like before approving it.

**Review by cticenhour — COMMENTED** [review]
Thanks for your comment @friedmud. @bwspenc this is consistent with what we talked about earlier, so I am happy with it. Want to see how it looks when rendered as well before approving.

**Comment by bwspenc** [comment]
@friedmud @cticenhour FYI, the documentation build is done now

**Review by cticenhour — APPROVED** [review]
LGTM - thank you!

**Comment by bwspenc** [comment]
I would add here that the flow of the page is still a little weird with those framework tutorials in the green boxes. The last one on that list should probably be linked to from a landing page for the porous flow module. My opinion is that we should drop the green boxes to make everything look more consistent. We also need to think about the blurry distinction between tutorials and examples.

**Comment by bwspenc** [comment]
The stuff I noted above is for future work, though. This at least meets my immediate need.

**Comment by cticenhour** [comment]
I also liked the previous dropdowns (and some of the remaining links work better as dropdowns and not as much as individual pages). But I think this is OK for the current need. More work needs to be done on this page, for sure.

**Comment by bwspenc** [comment]
I got rid of the dropdowns because they actually embed a page from within the modules, which only works if the page only has a bullet list. Some of the pages I wanted to link to, however, had text in addition to simple bullet lists, which wouldn't fit with the look of the other dropdowns.

**Comment by cticenhour** [comment]
I have some ideas about how to organize this - possibly leveraging more of the markdown include capabilities. Will put in a follow-up PR.

**Pull request merged**
