### PR TITLE
Another parallel transfer bug

### PR DESCRIPTION
**Pull request by smharper**
I was using `processor_id()` which gives the rank on the master communicator when what I really wanted was the rank on the subapp communicator.  `sub_app's_mesh.comm().rank()` seems to give me what I want.  Is there a better way I should be getting to that communicator?

There's a minus sign switch to make `_from_positions` more intuitive and consistent with `_to_positions`.

Small typo that can cause crashes: `i_from` -> `i_proc`

I also added a test that has 5 subapps which is important because it is odd (its easy to make parallel logic that fails with a load imbalance) and generally larger than the number of processors you test with.  This test is actually how I found the `i_from` typo.  I expect it would have also caught the rank thing.

### CODE REVIEW

**Comment by smharper** [comment]
Hey, @friedmud.  Is there any particular reason why `MultiApp::comm()` returns an `MPI_Comm` rather than a `LibMesh::Communicator`?  I'm thinking about changing that in the near future...

**Comment by friedmud** [comment]
Probably because it was used in the swap communicator stuff?  I honestly don't know.  I suppose: try to change it and then you might find out why ;-)

**Comment by friedmud** [comment]
Do you want to merge this as it is... or wait until you change that?  I think it's a good idea to be able to get the `libMesh::Communicator` for a sub app...

**Comment by smharper** [comment]
I'd like to get this one merged in as is.  Some of the simulations we're trying to run now might fail without it.  I'll return to the communicator issue in a separate PR

**Pull request merged**
