### PR TITLE
Diagonal matrix fixups

### PR DESCRIPTION
**Pull request by lindsayad**
This required some changes in the tensor mechanics `rom_stress_update` tests:

- The creep_rate_diff postprocessor seems to be a very sensitive quantity. I'm kind of a firm believer in not doing diffs on anything except non-linear variables and/or their aggregate quantities because those are the dofs that the non-linear solver is trying to crank on. The change in method for calculating scaling factors seems to have very slightly changed the scaling factors. However, if I do exodiffs on the non-linear variables they come out clean, so I think I trust the change. So I've switched they heavy verification test to be an Exodiff and the only quantity it doesn't test is creep_rate_diff. So creep_rate itself is fine. 
- The change in scaling factors calculation in #14204 appears to have slightly changed the 3D user Jacobian, requiring a bump in the ratio tol. I'm honestly not sure that the user Jacobian is 100% accurate because 5e-4 or 7e-4 with proper scaling of the matrix seems pretty high. But perhaps the function is non-smooth

### CODE REVIEW

**Comment by tophmatthews** [comment]
I noticed this too, but what was the change that caused this?

The primal variables mean nothing in this test. This is testing the output from the material property directly only. I wonder if there is a better way to treat the variables, e.g. use small strain instead of finite, with a unity youngs modulus.

I would agree that the creep_rate_diff can probably be ignored. The creep_rate, rhoi, and rhom are really the only things that need to be tested.

**Comment by tophmatthews** [comment]
I can take a look at this again tomorrow, but really I think you may be able to just add `outputs = console` to every postprocessor except `creep_rate`, `rhoi`, and `rhom`.

**Comment by tophmatthews** [comment]
but keep it as a csvdiff

**Comment by lindsayad** [comment]
Exodiff is a superset of CSVDiff...is your concern robustness because you don’t want to potentially cause us hardship in the future? ;-)

**Comment by tophmatthews** [comment]
I like CSVDiff: human readable, it's painfully obvious what your are testing, human readable, lighter/smaller, human readable, can be scooped into excel easy, human readable....

Here for example, I the primal variables do not do anything. It's just the values from the material property that mean something.

Obviously, it was short-sighted to CSVDiff on the diff postprocessor. #14188 should take care of it for ya.

**Comment by tophmatthews** [comment]
I still don't get why #14204 changed things though since the primal variables shouldn't be changing  changing the creep_rate_diff...

**Review by permcody — APPROVED** [review]

**Comment by tophmatthews** [comment]
Oh no! This was solved by #14188! I don't think this is the right way fix the tests.

**Comment by lindsayad** [comment]
Yea didn't get around to closing this in time...

**Pull request merged**
