### PR TITLE
Ability to continue main app if sub app's solve does not converge in FullSolveMultiApp

### LINKED ISSUE #15624: Continue stochastic runs and output when subapp fails
## Reason
Currently, when performing stochastic runs using SamplerFullSolveMultiApp, all the simulations are killed and none of the previous results are outputted. This causes a lot of headache when executing many runs and the completed simulation results are still valid.

## Design
SamplerFullSolveMultiApp needs to continue running the subapps, even if one or more fail. For the runs that fail the SamplerPostprocessorTransfer should be able to either transfer NaN value to VPP output.

## Impact
This will significantly affect the statistics and surrogate modeling objects, as they will need to know how to deal with samples that failed.

### PR DESCRIPTION
**Pull request by zachmprince**
This PR adds a parameter in FullSolveMultiApp to allow main app to continue fun if a sub app's solve does not converge. This is mainly for when running many samples using STM and the a difficult set of parameters makes sum of the samples fail to converge. With this option, the main app will still transfer values. I would not say this implementation is perfect, so I am very open to suggestions.

Tagging @rwcarlsen @aeslaughter 

Closes #15624

### CODE REVIEW

**Comment by rwcarlsen** [comment]
I think the param-sweep/sampler docs could use some (brief) discussion of how errors are generally handled and how these new options affect things.

**Comment by zachmprince** [comment]
I completely agree, I will start adding some documentation on these in the MultiApp and Transfers. There is one thing I don't like about this implementation that maybe you and/or @aeslaughter could give some suggestions. If a user wants to omit the transfer if a solve fails, the resulting vector of outputs will mismatch the samples in the sampler. This will cause errors whenever there is another loop over samples to analyze the results, like for surrogate training, for instance. I'm not sure how best to resolve this issue.

**Comment by rwcarlsen** [comment]
My first thought is that maybe we never want to omit the transfer.  Because if we do, then any samplers that don't generate independent sample batches will generated (even more) biased/skewed results.  It's like giving people an extra foot-gun.  And I have a hard time seeing the benefit of throwing out the entire batch ever.

**Comment by zachmprince** [comment]
Just to get on the same page. The entire batch will not be thrown out, only the samples that did not converge. I agree this could cause skewed results, though. But wouldn't that skewness be worse if an unconverged value is transferred, as it could result in erroneous outliers?

**Comment by rwcarlsen** [comment]
Okay - you meant omit the transfer from the failed subapps - not the transfers for the entire batch.  In that case, I still think we want to not "omit" them - preferring to mark them NaN or something so users are alerted to the fact that there were failed samples. rather than them silently not being there.

**Comment by rwcarlsen** [comment]
The details are going to be in how this affects stats/aggregated quantities calculated over sample results - one NaN could ruin everything.  The stats need to skip/ignore failed samples, but the actual sample results should have them still there.

**Comment by zachmprince** [comment]
Right, that detail made be move away from using a NaN. But you're right that it a little too sneaky to have the failed subapps go unnoticed by omitting the transfer. I need to figure out a general way to ignore NaN values when processing the results. I think it is pretty clunky to have `std::isnan` everywhere.

I will change this PR so there is an option to output NaN when there is a failed solve. I will leave this detail for the next PR. Thanks for your help!

**Comment by zachmprince** [comment]
@aeslaughter I believe I made all the suggestions you mentioned.

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
