### PR TITLE
ALL YOUR BASE ARE BELONG TO US

### LINKED ISSUE #10838: Reorganize framework/base
## Rationale
framework/base is a bloated mess.  We need to move stuff out into logical directories.

## Description
At least:

 - problems
 - systems
 - Move interfaces to be with the objects they interface to
 - compute_loops

## Impact
Better organization... better Unity builds

### PR DESCRIPTION
**Pull request by friedmud**
YOU HAVE NO CHANCE TO SURVIVE MAKE YOUR _TIME_

Building on my laptop with `-j 8`:
No Unity: 15.5m
Unity: 4m
This: 3m

Building on my workstation with `-j 150`
This: 1m

Less build time + better organization = win

I no longer support splitting `FEProblemBase.C`.  Building `FEProblemBase.C` takes ~43 seconds.  Unity building _all_ problem classes together takes ~47 seconds.  This is a big win on laptops - and do we really need all of MOOSE and moose_test to compile in under 1m on our workstations?

The very best we would ever be able to do is ~30 seconds: `systems_unity`, `parser_unity`, `actions_unity` and `outputs_unity` all take about that amount of time.  I think I'm fine with 1m on my workstation since unity building helps out so much on laptops / Falcon.

closes #10838

### CODE REVIEW

**Comment by mangerij** [comment]
Excellent stuff Derek. I like to see these types of improvements. I wonder how much collective build time this saves.... tens of thousands of hours!

**Comment by permcody** [comment]
Well that's nice except @rwcarlsen's history is not useful and needs to be squashed anyway. We should do that before we merge this in.

**Comment by rwcarlsen** [comment]
I'll should have things ready on the other PR by around lunch time today.

**Comment by permcody** [comment]
This looks pretty reasonable to me. I don't have any issues with the new organization.

**Review by permcody — APPROVED** [review]

**Pull request merged**
