### PR TITLE
Execute face materials after lower-d var reinit for mortar

### PR DESCRIPTION
**Pull request by lindsayad**
@recuero wants to pull a lower-dimensional variable into what
I can only presume is a face material and use it for computing
a material property. Hence we must reinit the lower-d variable
before computing the face material.

Refs #14821

### CODE REVIEW

**Comment by lindsayad** [comment]
@recuero I don't have a lot of time to spend on anything other than finite volumes for the next six weeks unfortunately, so if you could check and see whether this works for you, and if you could devise a test that we can put into `moose/test` that would be fantastic

**Comment by recuero** [comment]
@lindsayad Thanks for putting this together so quickly. The `ADMaterial` needs to pull mechanical contact information to compute a `MaterialProperty` that will be used by thermomechanical contact --I believe that is the recommended way to do that. Unfortunately, it looks like I still have the same issue with a seg fault happening in the material. Basically, after pulling the contact pressure:

```   
 _contact_pressure_var(isParamValid("contact_pressure")
? &this->_subproblem.getStandardVariable(
_tid, parameters.getMooseType("contact_pressure"))
 : nullptr)
{
  if (_contact_pressure_var)
    _contact_pressure = &_contact_pressure_var->adSlnLower();
```
I get a seg fault in `ComputeQpProperties()` :

```
void
ADGapConductanceMaterial::computeQpProperties()
{
  if (_contact_pressure_var)
      Moose::out << "ADMaterial Contact pressure: " <<(*_contact_pressure)[_qp] << "\n";
```

**Comment by lindsayad** [comment]
Is this still on your BISON MR? If your remote branch is current with your
local changes, I can try and reproduce

**Comment by recuero** [comment]
> Is this still on your BISON MR? If your remote branch is current with your local changes, I can try and reproduce

I just pushed it to my MR. Please use this file to test `gap_heat_transfer_mortar_transient_action_tm.i`

**Comment by lindsayad** [comment]
This is the backtrace:
```
(gdb) bt
#0  0x00007fffe326ebf0 in PMPI_Abort () from /home/lindad/miniconda3/envs/moose-boost/lib/libmpi.so.12
#1  0x00007ffff7772e48 in MooseArray<MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned int, MetaPhysicL::NWrapper<50ul> >, true> >::operator[] (
    this=0x555555e4d5f0, i=0) at /home/lindad/projects/moose/framework/build/header_symlinks/MooseArray.h:276
#2  0x00007ffff7694710 in ADGapConductanceMaterial::computeQpProperties (this=0x555556096530) at /home/lindad/projects/bison/src/materials/ADGapConductanceMaterial.C:83
#3  0x00007ffff502caf3 in Material::computeProperties (this=0x555556096530) at /home/lindad/projects/moose/framework/src/materials/Material.C:106
#4  0x00007ffff5033558 in MaterialData::reinit (this=0x5555557c3f80, mats=std::__debug::vector of length 1, capacity 1 = {...})
    at /home/lindad/projects/moose/framework/src/materials/MaterialData.C:73
#5  0x00007ffff4b65b46 in FEProblemBase::reinitMaterialsBoundary (this=0x555555d2a9d0, boundary_id=100, tid=0, swap_stateful=true)
    at /home/lindad/projects/moose/framework/src/problems/FEProblemBase.C:3056
#6  0x00007ffff4776d0c in ComputeElemAuxBcsThread<AuxKernelTempl<double> >::operator() (this=0x7fffffffb680, range=...)
    at /home/lindad/projects/moose/framework/src/loops/ComputeElemAuxBcsThread.C:102
#7  0x00007ffff54f719d in libMesh::Threads::parallel_reduce<libMesh::StoredRange<MooseMesh::const_bnd_elem_iterator, BndElement const*>, ComputeElemAuxBcsThread<AuxKernelTempl<double> > > (
    range=..., body=...) at /home/lindad/miniconda3/envs/moose-boost/libmesh/include/libmesh/threads_pthread.h:380
#8  0x00007ffff549f93a in AuxiliarySystem::computeElementalVarsHelper<AuxKernelTempl<double> > (this=0x555555d5fe40, warehouse=..., 
    vars=std::__debug::vector of length 1, capacity 1 = {...}, timer=200) at /home/lindad/projects/moose/framework/src/systems/AuxiliarySystem.C:684
#9  0x00007ffff549f302 in AuxiliarySystem::computeElementalVars (this=0x555555d5fe40, type=...) at /home/lindad/projects/moose/framework/src/systems/AuxiliarySystem.C:590
#10 0x00007ffff549d736 in AuxiliarySystem::compute (this=0x555555d5fe40, type=...) at /home/lindad/projects/moose/framework/src/systems/AuxiliarySystem.C:376
#11 0x00007ffff4b68571 in FEProblemBase::computeAuxiliaryKernels (this=0x555555d2a9d0, type=...) at /home/lindad/projects/moose/framework/src/problems/FEProblemBase.C:3481
#12 0x00007ffff4b68433 in FEProblemBase::execute (this=0x555555d2a9d0, exec_type=...) at /home/lindad/projects/moose/framework/src/problems/FEProblemBase.C:3462
#13 0x00007ffff4b52f8e in FEProblemBase::initialSetup (this=0x555555d2a9d0) at /home/lindad/projects/moose/framework/src/problems/FEProblemBase.C:970
#14 0x00007ffff52fc0e5 in Transient::init (this=0x555555da5350) at /home/lindad/projects/moose/framework/src/executioners/Transient.C:229
#15 0x00007ffff5c69fa8 in MooseApp::executeExecutioner (this=0x5555557adbe0) at /home/lindad/projects/moose/framework/src/base/MooseApp.C:931
#16 0x00007ffff5c6aa73 in MooseApp::run (this=0x5555557adbe0) at /home/lindad/projects/moose/framework/src/base/MooseApp.C:1060
#17 0x00005555555684ce in main (argc=3, argv=0x7fffffffc118) at /home/lindad/projects/bison/src/main.C:50
```
Resolving this is definitely going to take substantially more work because essentially we're going to have to make sure that the lower-d variable has been reinited before any reinit of the boundary material, which as we see can happen just during auxiliary variable computation. This will probably require implementing #14804 such that when reinit'ing on a boundary face which also has a corresponding lower  dimensional block, we calculate variables that live on the latter.

**Comment by lindsayad** [comment]
Ok @recuero @bwspenc what I propose is this. Forget the boundary to lower-d subdomain map idea. What I think we need is this data member on `MooseMesh`:
```c++
std::unordered_map<std::pair<const Elem *, unsigned short int>, const Elem *> higher_d_elem_side_to_lower_d_elem;
```
You'd have to be smart about how you did it in order to reduce computational expense, but you could loop over higher/lower dimensional elements and then use `higher_d_elem->which_side_am_i(lower_d_elem)` to figure out a side. If the `lower_d_elem` is not actually a side of the `higher_d_elem`, then the return value is `libMesh::invalid_uint`. You *could* assume in the beginning that whoever is generating your mesh is going to set interior parents; if you make that assumption, then you could vastly reduce the computational expense of your looping.

Anyway once you had that map constructed, you could do the following in `ThreadedElementLoopBase::operator()`:
<pre>
        onElement(elem);

        for (unsigned int side = 0; side < elem->n_sides(); side++)
        {
          std::vector<BoundaryID> boundary_ids = _mesh.getBoundaryIDs(elem, side);
          <b>const Elem * lower_d_elem = _mesh.getLowerDElem(elem, side);</b>

          if (boundary_ids.size() > 0)
            for (std::vector<BoundaryID>::iterator it = boundary_ids.begin();
                 it != boundary_ids.end();
                 ++it)
            {
              <b>preBoundary(elem, side, *it, lower_d_elem);
              onBoundary(elem, side, *it, lower_d_elem);</b>
            }
</pre>

And then in stuff like `ComputeResidualThread::onBoundary`:
<pre>
void
ComputeResidualThread::onBoundary(const Elem * elem,
                                  unsigned int side,
                                  BoundaryID bnd_id,
                                  <b>const Elem * lower_d_elem/*=nullptr*/</b>)
{
  if (_ibc_warehouse->hasActiveBoundaryObjects(bnd_id, _tid))
  {
    const auto & bcs = _ibc_warehouse->getActiveBoundaryObjects(bnd_id, _tid);

    _fe_problem.reinitElemFace(elem, side, bnd_id, _tid);
  <b>if (lower_d_elem)
      _fe_problem.reinitLowerDElem(lower_d_elem, _tid);</b>

    // Set up Sentinel class so that, even if reinitMaterialsFace() throws, we
    // still remember to swap back during stack unwinding.
    SwapBackSentinel sentinel(_fe_problem, &FEProblem::swapBackMaterialsFace, _tid);

    _fe_problem.reinitMaterialsFace(elem->subdomain_id(), _tid);
    _fe_problem.reinitMaterialsBoundary(bnd_id, _tid);

    for (const auto & bc : bcs)
    {
      if (bc->shouldApply())
        bc->computeResidual();
    }
  }
}
</pre>
This would also require writing `SubProblem::reinitLowerDElem`. We already have `SubProblem::reinitLowerDElemRef`. The only difference between the two is that the former would use the default quadrature rule.

**Comment by lindsayad** [comment]
Incorporated into #15259

**Pull request closed without merging**
