### PR TITLE
Move CoefTimeDerivative from misc to framework

### LINKED ISSUE #11047: Create CoefTimeDerivative in framework
## Rationale

Really frequently i have to use combined-opt just because i have a coefficient in front of \dot{u}.  Super annoying.

## Description

I don't want to divide by the coefficient (and use AnisotropicDiffusion, for example) because the coefficient is different in different blocks, and the division mucks around with the relative sizes of my residuals in those blocks and the "heat content" of the nodes.  The division is actually impossible in my current situation, where the blocks are both 2D and 3D.  The 2D blocks represent super thin 3D elements and we've deliberately scaled the coefficients of all terms in the DE (relative to the 3D-block coefficients) to ensure the residuals on the 2D blocks do correctly represent thin-3D physics.

I suggest just moving CoefTimeDerivative from combined to framework.

## Impact

Ability to easily model the heat equation (etc) without having to compile and use all of "modules".

### PR DESCRIPTION
**Pull request by philippschaedle**
Move CoefTimeDerivative from misc to framework
CoefTimeDerivative calculates the time derivative of a variable and multiply by a coef

closes #11047

### CODE REVIEW

**Comment by YaqiWang** [comment]
Any reason this cannot be merged into TimeDerivative?

**Comment by philippschaedle** [comment]
Coeftimederivative inherents from timederivative and allows to multiply by a coefficient

**Comment by andrsd** [comment]
@YaqiWang is saying that `TimeDerivative` is a special case of `CoefTimeDerivative` where `Coefficient = 1`. So, he was suggesting moving the `Coefficient` parameter into `TimeDerivative` and possibly deprecate `CoefTimeDerivative` (I am assuming).  

However, I am expecting some pushback here. Similarly we have `Diffusion` with no coefficient in the framework and `CoefDiffusion` in the `misc` modules. If we move one kernel, it would make sense to move the other one as well. Consistency will be the key point here...

**Comment by philippschaedle** [comment]
Sure @andrsd this totally makes sense. The coefficient could certainly just be moved to the TimeDerivative Kernel.  

Regarding the CoefDiffusion there is also the AnisotropicDiffusion Kernel in the framework which is quite similar to the CoefDiffusion. Maybe those could be combined too. 

What do you guys think?

**Comment by aeslaughter** [comment]
I don't think we should be moving things into the framework, I would actually love for items to be moved out into the modules. I would like to see the framework as end-user object free as possible. 

My reasoning is that it because a slippery slope, now we have a coefficient, but I need a material property coefficient, a postprocessor coefficient, etc. Where does it end?

I would not mind adding to the "misc" module or better yet rename it to something better where these type of objects can be added. I am thinking "core", "foundation", "basic", "general", ...

**Comment by permcody** [comment]
This is what @andrsd was talking about. A debate about which objects should be in the framework and which should not. I'll voice my opinion. I think adding constants to the basic objects is fine. I'd personally like to just have a coefficient added to the main `Diffusion` kernel instead of having `CoefDiffusion` and `Diffusion`. The same goes for the other basic kernels. I really don't buy into the argument that it's too complicated or muddies the water when we are trying to teach this stuff. I think most people understand that a default of 1.0 is fine for multiplication.

**Comment by friedmud** [comment]
You guys know what I'm going to say about this before I even say it... so why even propose it? 😁 

`Diffusion` and `TimeDerivative` must be left alone.  The reason is not that they shouldn't be complicated for people to look at (although I agree with that as well)... it's that they're _foundational_ objects that MANY other things inherit from.

Every single object throughout the entire MOOSE system that inherits from Diffusion for implementing Laplacian type operators would gain both an unwanted/unused parameter _and_ an unnecessary multiplication by `1.0`.  That's ridiculous when it's easily handled by having `CoefDiffusion`.

The exact same thing goes for `TimeDerivative`... it's the foundation for every time derivative in the MOOSE ecosystem and should be as plain as possible.

Base classes should be as plain and _fundamental_ as possible.  They should have _very_ little reason to ever change as they are depended on / used by so many other objects throughout the system.  They should do one thing - and only that one thing.

This is one of those issues where I even wonder why we're talking about this.  Why does having `CoefDiffusion` or `CoefTimeDerivative` chafe you guys so much?  We have hundreds of other objects in the system that are more questionable than they are!

Ok - now that I've weighed in with my dependable answer about the base classes: I'll also weigh in on this PR itself.

To me the `Coef*` Kernels are general enough that they can exist in MOOSE itself.  It's a judgement call... but the utility gained by having them trumps any increase in "bloat" or "maintenance".  They are not "end-user" Kernels and don't specify any particular physics at all.  In my view they are very simple and fundamental.  Not only that: but with Unity build it doesn't take any longer to build them within the framework.

**Comment by permcody** [comment]
OK, I'm fine with this PR. @philippschaedle - the only other thing that may need to be done here is the movement of the associated test. There's probably a test (or two) in "misc" where this object came from. Those tests should be moved if possible to the MOOSE test suite.

**Comment by philippschaedle** [comment]
That's great. Thanks for the good discussion.

**Comment by friedmud** [comment]
@philippschaedle I fixed up your branch.  It looked like you had rebased on the wrong branch somehow (always rebase on `devel`).  You had also committed an output file in your test by accident.  In case you're wondering here are the steps I took to fix it (there are other ways of dealing with this, but I thought this was the most straightforward):

```bash
# Added a remote and fetched your branch then:
git fetch upstream # Update my upstream/devel branch
git co -tb fixup_philip upstream/devel # Checkout a new branch based on upstream/devel
git cherry-pick 4b5ad6 # Move over one of your commits to this branch
git cherry-pick 9a26cac8 # Move over the other commit
git rebase -i HEAD~4 # Interactive rebase to set the second commit as "s" to squash it into the first one
git rm -f tests/kernels/coefficient_time_derivative/coupled_time_derivative_diffusion_out.e # Remove the output file that shouldn't be in the repository
git commit --amend # Amend your commit to remove that file
git push -f philippschaedle HEAD:feature_issue_11047 # Force push the result back to your branch on GitHub
```

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like `kernels/coefficient_time_derivative.test` diffs when running with higher -p.
See #11231

**Pull request merged**
