### PR TITLE
Enhance SubdomainBoundingBox a little 

### LINKED ISSUE #12279: A small enhancement of SubdomainBoundingBox mesh modifier
## Rationale

The enhancement will be restricting the subdomain ID assignment within a bounding box only for a selected set of existing subdomains.

## Description

If no subdomains are specified, assigning subdomain ID will happen for all elements within the bounding box.

## Impact
New feature.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #12279.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Call for help on fixing the doc failure.

**Comment by permcody** [comment]
We now require that the SQA tags on all tests in a touched "tests" file are there. So you touched a test, therefore you have to add the appropriate tags to the other tests!

**Comment by YaqiWang** [comment]
Ok, I will close this and the issue since it is too specific then.

**Comment by permcody** [comment]
Hang on - There's nothing wrong with your issue or the PR. Just that we are requiring a little work to start getting the test specs up to date. Are you not interested?

**Comment by YaqiWang** [comment]
No, I might just wait for the test specs up to data.

**Pull request closed without merging**
