### PR TITLE
MooseDocs presentations and AD for minitutorial

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
AFAICT, there are no tests hitting the new `ADKernel` members? :crying_cat_face:

**Comment by aeslaughter** [comment]
@lindsayad I just removed the changes to ADKernel, I am not using it anymore.

**Review by lindsayad — APPROVED** [review]
These 10k lines look fine. I looked at all of them

**Comment by milljm** [comment]
@lindsayad @aeslaughter... something is wrong with this... the menu system loads... unpacked? not squashed? some-other-word-to-describe what it is doing.

If it is not doing it for you, refresh the page. If the site is cached, it looks ok.

**Comment by lindsayad** [comment]
Does it look like this?
screen shot 2019-02-26 at 9 29 29 am

**Comment by milljm** [comment]
Indeed. The menu does not start collapsed.

**Comment by sapitts** [comment]
I'm not sure if it is related, but we can't get the alerts and parameter drop-down list arrows to render properly in the apps (I don't remember the path to any of the module pages and I can't manage to click anything from the drop down menu in MOOSE to check if this issue is showing up in MOOSE too or if it is localized to apps)

**Pull request merged**
