### PR TITLE
Adds ability to have arbitrary execute flags

### LINKED ISSUE #7489: Arbitrary execute_on
### Description of the enhancement or error report

I want the ability to add my own options to `execute_on`... so I can add as many as I want and execute them arbitrarily.
### Rationale for the enhancement or information for reproducing the error

It would be useful for complex custom Executioners / Systems
### Identified impact

Storage for all objects will need to change.  Some amount of engineering required... probably associated with `MooseApp`.

### LINKED ISSUE #8893: Execute on flags need some work
### Description of the enhancement or error report

We have an enum of `execute_on` flags in MooseTypes.h with flag values assigned. However there are a a few files in the framework that build a list manual with flag types for constructing the strings in a MOOSE enum. If you try to mess with these flags at all MOOSE breaks in bad ways. We need to use MooseTypes.h for everything and avoid constructing these lists manually. Also, we now have a utility in MOOSE that make it easy to assign flag values to enum types. We should use that here. It's currently being used in the FeatureFloodCount object successfully without static casts all over the place.

### Rationale for the enhancement or information for reproducing the error

Try adding a new flag somewhere not at the end and watch all hell break loose.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Improving code robustness

### PR DESCRIPTION
**Pull request by aeslaughter**
closes #7489 
closes #8893

### CODE REVIEW

**Comment by aeslaughter** [comment]
One question which I am sure will come up. Why didn't I make a new class that inherits from MultiMooseEnum? 

I started down that road, but unfortunately you have to add template specializations, like we have for MultiMooseEnum, to the InputParameters and Parser objects, which I didn't really feel was worth it.

**Comment by rwcarlsen** [comment]
This will also need to update the stork app files **inside** moose.

**Comment by aeslaughter** [comment]
@permcody Was asking why this is needed, I have two reasons, but other should comment with more.

1. The level_set module has a transfer that uses "CUSTOM" to perform a transfer after each refinenment level, allowing for the subapps to have the same refinement pattern as the master, but it would be cleaner to use a name that has some sort of meaning: EXEC_MESH_REFINED.
2. Mastodon would like to have a Postprocessor that executes on FINAL. As ticket #8893 explains, this wasn't as easy as it should of been, even with the flag already existing. So, rather than hacking up the broken system I made it more flexible.
3. Applications such as Rattlesnake currently re-execute things all with the same execution flags, which is evident in the Eigen related changes in this PR. Having the ability to add new flags should enable re-execution to be performed in a more flexible and understandable manner.

**Comment by permcody** [comment]
@friedmud - This work spun out of a request you made at the last tiger team. You may want to look over this and see if this is what you were after.

**Comment by mangerij** [comment]
Ferret is going to diff but unrelated -- working on regolding those tests at the moment.

**Comment by aeslaughter** [comment]
I also started to document the SetupInterface, it still needs some more content, but I wanted to start the testing. I will keep working on it.

http://mooseframework.org/docs/PRs/8946/site/documentation/interfaces/SetupInterface/index.html

**Comment by aeslaughter** [comment]
Currently, I have the registration of the flags to mimic the registration of objects. But doing this will require the addition of "Moose::registerExecFlags" to all the apps. This is something that I can do, but it is labor intensive and the reason for doing it is not technical, but simply for consistency. 

Technically, speaking the registerExecFlag function could be called from anywhere at anytime. But, practically it should be called prior to creating objects (i.e., before validParams calls). 

For ease of implementation, what about just having any custom flags be registered in the app constructor.

```
MyApp::MyApp(...)
{
  Moose::registerObjects(...);
  MyApp::registerObjects(...);

 registerExecFlag(MY_NEW_FLAG, "NEW_FLAG");
}
```

**Comment by permcody** [comment]
Creating a new method to call for each application will require an extern declaration as well so that this doesn't break dynamic loading of Multiapps. We already have to call the register objects and register syntax methods. Now we'll have to call this too. Seems like a lot of work to dynamically turn on a new application.

**Comment by rwcarlsen** [comment]
Is there any reason they can't just register their custom exec flags in their app constructor (instead of adding yet another static function)?

**Comment by aeslaughter** [comment]
@rwcarlsen See my editted comment above on github, which you probably didn't see in the mail.

> EDIT
> Nevermind, this doesn't work when compiling apps together because we don't call the constructors of the apps. The way I have it might be correct, but I am open to ideas.

**Comment by aeslaughter** [comment]
We could have a non-static virtual method in MooseApp that can be overridden, the only catch is that the overridden virtual will need to call the base class method, which isn't that big a deal. I think this is the solution I like, at least so far.

**Comment by aeslaughter** [comment]
I am moving this to a branch on upstream so I can test integration branch for Marmot and Mammoth.

**Pull request closed without merging**
