### PR TITLE
Delete unnecessary vector closes

### LINKED ISSUE #10669: Delete unnecessary vector  closes
## Rationale

`Vector close ` is not free, and even worse, it is actually not scalable with increasing the number of processor cores. It may be a good idea to delete unnecessary ones.

### PR DESCRIPTION
**Pull request by fdkong**
Vector close is not free, and even worse, it is actually not scalable
with increasing the number of processor cores.
It may be a good idea to delete unnecessary ones.

Closes #10669

### CODE REVIEW

**Comment by fdkong** [comment]
@permcody, @friedmud Could you take a look? The fail is not introduced by this PR. I did not do anything related the failed tests:)

**Comment by permcody** [comment]
Seems like a lot of deletes, but it also looks like it's a reduction of just one or two for normal problems. How can you be sure that these are all safe to delete?

**Comment by YaqiWang** [comment]
`mooseAssert(xxx.closed(), "")`?

**Comment by permcody** [comment]
Hmm, that's not a bad idea @YaqiWang. However, if we are actually deleting them, the really means that we _never_ needed them? They may not always be closed where these calls are being deleted, but they are being closed eventually before they are used. 

Asserting that they are closed is a really good idea right before you attempt to do an operation that requires that they are closed (not necessarily at the bottom of the loop). @fdkong - maybe you should continue your hunt for unecessary closes, but also consider adding new asserts as @YaqiWang is suggesting.

**Comment by fdkong** [comment]
No routine  to check if a vector is closed or not, and it is not necessary. Because the check will also involve a global communication to make sure  all processor on the same page.  This is almost equivalent  to close an empty close which just sends zero-length messages.

**Comment by permcody** [comment]
So much for that idea ;)

**Comment by friedmud** [comment]
Closing for now because a lot more work needs to be done and @fdkong is working on something else.

**Pull request closed without merging**
