### PR TITLE
Make MOOSE work with debug PETSc (Warning: includes libmesh update!)

### PR DESCRIPTION
**Pull request by jwpeterson**
I haven't yet tried this with all the apps, and there is one modules test still failing that I need to work with @WilkAndy to fix, but this has been in progress for a while and would be good to get merged.

Refs #5235.

### CODE REVIEW

**Comment by friedmud** [comment]
This is really good stuff @jwpeterson !

As soon as this works with app_tests we should immediately add this as part of moose_build...

**Comment by jwpeterson** [comment]
I think I've fixed the only app issues (one in BISON, one in MARMOT), so this should be good to merge whenever we are ready to do a libmesh update.

**Comment by dschwen** [comment]
876d653e0967a crashes all test in dbg on rod (PETSc 3.4). Opt testing passes cleanly.

**Comment by jwpeterson** [comment]
On Tue, Aug 18, 2015 at 4:40 PM, Daniel Schwen <notifications@github.com>
wrote:

> 876d653
> <https://github.com/idaholab/moose/commit/876d653e0967a1abb71239f2e249dd0fe63e0e61>
> crashes all test in dbg on rod (PETSc 3.4). Opt testing passes cleanly.
>

What is the crash?

I'm pretty sure I tested this, but only in opt mode.

-- 
John

**Comment by dschwen** [comment]
Segfault

```
#0  0x00007ffff0694ba5 in SNESGetKSP () from /opt/moose/petsc/openmpi_petsc-3.4.3/gcc-opt/lib/libpetsc.so
#1  0x00007ffff6444e74 in Moose::PetscSupport::petscSetDefaults (problem=...) at /ssd/schwd/moose/framework/src/utils/PetscSupport.C:431
#2  0x00007ffff68e5cb7 in Moose::setSolverDefaults (problem=...) at /ssd/schwd/moose/framework/src/base/Moose.C:1027
#3  0x00007ffff67a6c41 in FEProblem::solve (this=0xef4bc0) at /ssd/schwd/moose/framework/src/base/FEProblem.C:3090
#4  0x00007ffff6981d85 in TimeStepper::step (this=0xff39b0) at /ssd/schwd/moose/framework/src/timesteppers/TimeStepper.C:188
#5  0x00007ffff661e606 in Transient::solveStep (this=0xface60, input_dt=-1) at /ssd/schwd/moose/framework/src/executioners/Transient.C:400
#6  0x00007ffff661e0fd in Transient::takeStep (this=0xface60, input_dt=-1) at /ssd/schwd/moose/framework/src/executioners/Transient.C:328
#7  0x00007ffff661dd55 in Transient::execute (this=0xface60) at /ssd/schwd/moose/framework/src/executioners/Transient.C:253
#8  0x00007ffff674b47a in MooseApp::executeExecutioner (this=0x90eb50) at /ssd/schwd/moose/framework/src/base/MooseApp.C:421
#9  0x00007ffff674bef5 in MooseApp::run (this=0x90eb50) at /ssd/schwd/moose/framework/src/base/MooseApp.C:537
#10 0x0000000000422a96 in main (argc=3, argv=0x7fffffffe1c8) at /ssd/schwd/moose/modules/phase_field/src/main.C:32
```

**Comment by jwpeterson** [comment]
Works fine for me, you might need to make clobber and rebuild.

**Comment by jwpeterson** [comment]
(moose tests anyway)

**Comment by dschwen** [comment]
Yeah, already doing that. Forgot I had to patch moose.mk for clobebr to work on Linux (this should be fixed sometime). So I thought I had already clobbered, but it was a no-op.

**Comment by dschwen** [comment]
Ok, yes, it was the broken clobber. Works now.

**Pull request merged**
