### PR TITLE
Loosen partitioning tolerance

### PR DESCRIPTION
**Pull request by lindsayad**
Refs 32 bit failure from #27691

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]
see my PR :D

**Review by GiudGiud — APPROVED** [review]
my only concern is that these parMETIS tests now use ptscotch. hence my other PR. The two PRs are compatible though

**Comment by lindsayad** [comment]
I agree. I saw this as a quick fix independent of the partitioner used

**Comment by lindsayad** [comment]
@GiudGiud's associated PR: https://github.com/idaholab/moose/pull/28355

**Pull request merged**
