### PR TITLE
make EigenProblem consistent with FEProblem when solve=false

### LINKED ISSUE #27084: Make EigenProblem respect the "solve" parameter in the same way as FEProblem
### Motivation

If the `solve` parameter is set to false, when using FEProblem, `FEProblemBase::nlConverged` will return true. But `EigenProblem::nlConverged` has a different behavior and does not consider that the `solve=false`

### Design

Make `EigenProblem::nlConverged` consistent with `FEProblemBase::nlConverged` to get the expected behavior when `solve=false` 

### Impact

No impact to most users. Only something likely noticed by people writing custom executioners

### PR DESCRIPTION
**Pull request by jthano**
closes #27084

### CODE REVIEW

**Comment by jthano** [comment]
I didn't think this change needed a test. But I could try to add a test if a reviewer thinks it's needed

**Review by loganharbour — CHANGES_REQUESTED** [review]
Yeah, please add a test. You should be able to just do a `RunApp` and search for some output that shows it was skipped

**Comment by jthano** [comment]
I found it hard to add a test based only on screen output. In the old code, an erroneous message will be printed to console because of these lines from Eigenvalue::execute()
```c++
    if (!lastSolveConverged())
    {
      _console << "Aborting as solve did not converge" << std::endl;
      break;
    }

```
But I didn't want to rely on not finding that message in the output since the message itself could change in the future. So I added a very small CSV diff test. In the new code, the correct value is output by the constant postprocessor in the input file which executes on `FINAL`. In the old code, the output value is wrong because the system never executed on `FINAL` since the solve aborts due to the code pasted above.

**Comment by jthano** [comment]
> I found it hard to add a test based only on screen output. In the old code, an erroneous message will be printed to console because of these lines from Eigenvalue::execute()
> 
> ```c++
>     if (!lastSolveConverged())
>     {
>       _console << "Aborting as solve did not converge" << std::endl;
>       break;
>     }
> ```
> 
> But I didn't want to rely on not finding that message in the output since the message itself could change in the future. So I added a very small CSV diff test. In the new code, the correct value is output by the constant postprocessor in the input file which executes on `FINAL`. In the old code, the output value is wrong because the system never executed on `FINAL` since the solve aborts due to the code pasted above.

Nevermind, there is an execute on FINAL still even in the old code. The only difference is the `_time_step`. In the old code it was outputting `time=1` and in this new code it outputs `time=2`. But I guess this relies on the `#ifdef LIBMESH_ENABLE_AMR` otherwise the `break` in the code pasted above does nothing. Let me think about this a bit more.

**Comment by jthano** [comment]
I think the tests are good to go now. I added a two dependent tests, one checking that `Aborting as solve did not converge` is printed when a solve fails with `solve=true` and another one changing `solve=true` and making sure the output is just `Solve Skipped!`

**Review by loganharbour — APPROVED** [review]
Perfect, thanks for getting the tests in

**Pull request merged**
