### PR TITLE
Remove MeshModifiers

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
Enough has seem to changed between the MeshGenerator and MeshModifier test directories that I found it easier to just update the tests/mesh_modifiers than to figure out if the test was the same as something else.

**Comment by lindsayad** [comment]
So what's your plan for dealing with the apps? Are you going to go convert them over to `MeshGenerators` first or make their app developers do that before we merge this into next?

**Comment by aeslaughter** [comment]
> So what's your plan for dealing with the apps? Are you going to go convert them over to `MeshGenerators` first or make their app developers do that before we merge this into next?

Not sure. It depends how bad things are. We shall see, I think I have moose and modules are updated.

**Comment by aeslaughter** [comment]
I don't have access to Ferret of SaintBernard, but both are failing (https://civet.inl.gov/job/598622/).

@mangerij Ferret is using MeshModifiers, can you update it?
@danielvogler SaintBernard is still using MeshModifers, can you get it updated?

 Let me know if you need assistance.

**Comment by lindsayad** [comment]
I have changes that depend on this, so I've got real skin the game now... Waddya know, I have access to Ferret and SaintBenard

**Comment by danielvogler** [comment]
Hi Alex,

But we merged mesh modifiers into moose a while ago? Is there anything
different?

Cheers.
Daniel

**Comment by mangerij** [comment]
@aeslaughter Hi all, I can't actually see which Ferret tests are failing because we made the app Private. ...And I actually only stumbled on this by chance of clicking a random email notification from the moose traffic. I will fix it tomorrow or if possible you can submit the PR to Ferret directly.

**Comment by lindsayad** [comment]
> @aeslaughter Hi all, I can't actually see which Ferret tests are failing because we made the app Private. ...And I actually only stumbled on this by chance of clicking a random email notification from the moose traffic. I will fix it tomorrow or if possible you can submit the PR to Ferret directly after I give you access.

@mangerij have you seen https://github.com/mangerij/ferret/pull/70 ?

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
