### PR TITLE
Fix AssignElementSubdomainID on distributed meshes

### PR DESCRIPTION
**Pull request by roystgnr**
This corrects another #1500 regression for me:
mesh_modifiers/assign_element_subdomain_id.quad_elementid_test
previously failed on 5 processors with --distributed-mesh, and now
works on 1 through 24 processors.

The algorithm here is awful.  I *feel* like we ought to be able to do
this in the distributed case in O(N_elem/N_proc), like most
DistributedMesh operations, but I can't figure out exactly how.  The
code for replicated meshes here is O(N_elem), just as fast as before,
but the DistributedMesh code path is now O(N_elem log(N_elem)), plus
another O(N_elem) term with an ugly constant in front if the mesh is
actually distributed.

If that shows up in anybody's profiling then open an issue and we can
at least shave it down to O(N_elem) at the cost of code legibility.

### CODE REVIEW

**Comment by roystgnr** [comment]
Hmm... this also seems to have fixed some tests I didn't expect, like userobjects/internal_side_user_object.get_neighbor_test, and a quick grep shows that there are other tests currently restricted to ReplicatedMesh because of a dependency on AssignElementSubdomainID.  Let me see if those can have their restrictions removed.

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Hmm, it looks like this causes an exodiff in `pressure_bc.2d_pressure_displaced_mesh` on the Clang target: https://www.moosebuild.org/job/101673/

**Comment by roystgnr** [comment]
Is that test even *using* AssignElementSubdomainID?

**Comment by permcody** [comment]
Hmm, I can't see where that object is used anywhere by the XFEM module. This is a little odd.

**Comment by brianmoose** [comment]
I actually didn't even check what this PR does, just saw the test start failing after this PR and one of mine went in at the same time. Shouldn't have jumped to conclusions, it looks like my PR is causing this :) Still need to figure out why....

**Pull request merged**
