### PR TITLE
Add a transient test for laplacian jump

### LINKED ISSUE #2190: Fix LaplacianJumpIndicator test with Parallel Mesh
It is giving incorrect values for the second derivatives with Parallel Mesh - I can't see why so for now it's been marked as distribution=serial

### PR DESCRIPTION
**Pull request by permcody**
Make sure it works for recover and distributed mesh.
closes #2190

### CODE REVIEW

**Comment by jwpeterson** [comment]
I'm not sure where the `DivergenceBC` comes from in this weak form? You wouldn't have that for Lagrange elements, and I don't see why you would have it for Hermites either but I might be missing something. If I remove that the problem still solves fine (actually it takes fewer linear iterations) so I'd like to think about this one a bit more. If the goal is to test Laplacian jumps it seems like we should solve a 4th-order problem...

**Comment by jwpeterson** [comment]
I tried to figure out how there would be an extra boundary term for the convection-diffusion equation simply due to using Hermite elements, but I still don't see it. I have a feeling @roystgnr might be able to shed some light on the situation since he has used C1 elements quite a bit in the past?

**Review by jwpeterson — APPROVED** [review]
I'm going to merge this as-is but I still think that `DivergenceBC` thing is unnecessary. See, for example, other input files like `examples/ex14_pps/ex14_compare_solutions_1.i` and `test/tests/ics/hermite_ic/hermite_ic.i` which also solve the Diffusion Kernel but *don't* use this BC.

I think I will also put up a new PR to change these tests a bit. This is not an H2-problem, so I don't know if the LaplacianJump error estimator is even appropriate/should be expected to give a good result for it...

**Comment by roystgnr** [comment]
> I still think that DivergenceBC thing is unnecessary.

Agreed.

> This is not an H2-problem, so I don't know if the LaplacianJump error estimator is even appropriate/should be expected to give a good result for it...

The derivation for the Laplacian jump estimator is only really valid for low order C1 elements on the biharmonic problem.  For C1 elements on H1 problems I'm pretty sure what you would want is an element-wise integral of the strong form residual.

But to be fair, libMesh users have quite a history of successfully taking "a good error estimator on problem X" and proving it to be "a decent error indicator on problem X+Y-Z", so I wouldn't be completely stunned if the LaplacianJump actually gave decent refinement patterns just because it worked as a feature indicator.

On the gripping hand, there is a horrible failure mode possible when you try to use a higher-Hilbert-order error indicator on a lower-Hilbert-order problem: if the higher-order Hilbert norm diverges, you can get runaway refinement into the parts of the domain where the norm isn't bounded, because each successive refinement causes the local error estimate to (correctly!) run off to infinity instead of converge to zero.  I saw that when trying to use an H1 norm on an L2 problem, but you could probably get it in the H2->H1 case too, if you applied a H^-1 forcing function.

**Comment by jwpeterson** [comment]
> Agreed.

Hmm... I did a convergence study for this problem both with and without the mysterious BC active, and it works *much* better (essentially optimal convergence rate) when you have the `DivergenceBC` present:

plot

So I'm a bit stumped by this. One idea is that only the value DOFs are constrained by the `DirichletBC` class in MOOSE, and therefore you have to do something "extra" for the gradient DOFs, which in this case is just computing the usual boundary term residual contribution?

**Comment by roystgnr** [comment]
That's dumbfounding.

You're just computing the usual ```du/dt = u'' + alpha u'``` here, right?

**Comment by jwpeterson** [comment]
No time derivative, just steady 1D convection-diffusion with Dirichlet BCs.

**Comment by roystgnr** [comment]
And you're running with low enough convection that stabilization shouldn't be an issue... I seriously would not have expected that 1.85 line...

**Pull request merged**
