### PR TITLE
Finite Volume Flow over sphere

### PR DESCRIPTION
**Pull request by AlbertJP7**
## Reason
3D computation of Flow over a sphere

## Design
finite volume version of finite element flow over sphere

## Impact
finite volume flow results

### CODE REVIEW

**Comment by GiudGiud** [comment]
@grmnptr can we close this ? 
You moved it over to another PR that is merged now right?

**Comment by grmnptr** [comment]
No, I merged the flow over cylinder, the sphere is something that Albert worked on till his last day at INL, I have no idea how far he got. I suppose I can finish this at some point.

**Comment by GiudGiud** [comment]
@AlbertJP7 could you please give us a quick update on this. Did you see the vortex shedding on that case / everything you and @lindsayad  expected?

**Comment by lindsayad** [comment]
I think the plan was for the flow here to be slow enough that we wouldn't get shedding in order to match some results from the module's FE publication. But it would be good if @AlbertJP7 could weigh-in on where he got to

**Pull request closed without merging**
