### PR TITLE
Adds mesh adaptivity group in performance log

### LINKED ISSUE #9766: Group mesh adaptivity related taks in performance log
### Description of the enhancement or error report
It would be nice to group mesh adaptivity related tasks together in the performance log. My App spends a lot of time on mesh adaptivity (for better or worse) and it would be nice to see all that in one place.

### Rationale for the enhancement or information for reproducing the error
Easier to see related tasks

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Better performance logging

I will submit a PR for this shortly.

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
Just a simple change to the performance logging. I made a "Mesh Adaptivity" group and moved the `adaptMesh()`, `computeIndicators()`, and `computeMarkers()` functions in `FEProblemBase` to it. Should anything else be included?

I left the initial adaptivity stuff alone because that only runs once so it should probably stay in the "Setup" group. I'm more interested in the mesh adaptivity that is occurring over and over again.

This is certainly open for discussion. Feel free to make any suggestions.

closes #9766

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Here is some sample output from tests/adaptivity/cycles_per_step/cycles_per_step.i
```
 -------------------------------------------------------------------------------------------------------------------------
| Moose Test Performance: Alive time=2.12587, Active time=2.10764                                                         |
 -------------------------------------------------------------------------------------------------------------------------
| Event                                      nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                                       w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|-------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                         |
|                                                                                                                         |
| Application                                                                                                             |
|   Full Runtime                             1          0.0054      0.005372    2.1077      2.107686    0.25     100.00   |
|                                                                                                                         |
| Execution                                                                                                               |
|   computeKernels()                         73         0.4400      0.006028    0.4400      0.006028    20.88    20.88    |
|   computeNodalBCs()                        73         0.0028      0.000039    0.0028      0.000039    0.13     0.13     |
|   compute_jacobian()                       10         0.0891      0.008914    0.0891      0.008914    4.23     4.23     |
|   compute_residual()                       73         0.0038      0.000052    0.4466      0.006118    0.18     21.19    |
|   solve()                                  5          0.0475      0.009496    0.5833      0.116651    2.25     27.67    |
|                                                                                                                         |
| Mesh Adaptivity                                                                                                         |
|   adaptMesh()                              5          1.1076      0.221511    1.1076      0.221511    52.55    52.55    |
|   computeIndicators()                      6          0.2639      0.043988    0.2639      0.043988    12.52    12.52    |
|   computeMarkers()                         6          0.0247      0.004112    0.0247      0.004112    1.17     1.17     |
|                                                                                                                         |
| Output                                                                                                                  |
|   Exodus::output()                         6          0.0482      0.008031    0.0482      0.008031    2.29     2.29     |
|                                                                                                                         |
| Setup                                                                                                                   |
|   Application Setup                        1          0.0699      0.069901    0.0728      0.072825    3.32     3.46     |
|   FEProblemBase::init::meshChanged()       1          0.0002      0.000234    0.0002      0.000234    0.01     0.01     |
|   Initial updateActiveSemiLocalNodeRange() 1          0.0001      0.000060    0.0001      0.000060    0.00     0.00     |
|   Initial updateGeomSearch()               2          0.0000      0.000002    0.0000      0.000002    0.00     0.00     |
|   NonlinearSystem::update()                1          0.0001      0.000083    0.0001      0.000083    0.00     0.00     |
|   eq.init()                                1          0.0026      0.002606    0.0026      0.002606    0.12     0.12     |
|   execMultiApps()                          1          0.0000      0.000007    0.0000      0.000007    0.00     0.00     |
|   execTransfers()                          1          0.0000      0.000004    0.0000      0.000004    0.00     0.00     |
|   initial adaptivity                       1          0.0003      0.000286    0.0066      0.006601    0.01     0.31     |
|   initialSetup()                           1          0.0011      0.001085    0.0082      0.008199    0.05     0.39     |
|   reinit() after updateGeomSearch()        1          0.0000      0.000002    0.0000      0.000002    0.00     0.00     |
|                                                                                                                         |
| Utility                                                                                                                 |
|   projectSolution()                        1          0.0004      0.000434    0.0004      0.000434    0.02     0.02     |
 -------------------------------------------------------------------------------------------------------------------------
| Totals:                                    271        2.1076                                          100.00            |
 -------------------------------------------------------------------------------------------------------------------------
```

**Comment by jessecarterMOOSE** [comment]
Hmm, I thought this was going to be easy... Any help @permcody?

**Comment by permcody** [comment]
In debug mode the performance logger checks to make sure that the thing you are popping matches what you said it should in your "pop()" call. If not - CRASH! This should be easily reproducible in debug mode on your system. It's possible you just missed a call or two somewhere.

On another note, is this really helpful to you? As you can see the log doesn't actually sum by subsection. Also, we do adaptivity during the setup phase that can take a lot of time that wouldn't be tallied in your new location. It's hard to get this right because we don't really have a way to tag an activity in multiple locations (i.e. setup and adaptivity).

**Comment by jessecarterMOOSE** [comment]
@permcody Sorry, just noticed I had a typo in there. Oops. I tried to correct it in the Github editor...

And it is fairly useful right now as I have been studying the tradeoff between runtime and mesh adaptivity and related routines and it's nice to have the information I'm looking for right in the same section. My app is doing lots (and lots!) of adaptivity at the moment so the initial adaptivity and/or uniform refinement that occurs at setup is just a drop in the bucket for me.

You know more about the user base as a whole so I'll leave it up to you as to whether this change is appropriate. I have no problem abandoning this PR if necessary. I can pull out the data I need with a Postprocessor anyway.

**Comment by jessecarterMOOSE** [comment]
@permcody I tried a few different things, and could probably come up with more. See anything you like?
```
 -------------------------------------------------------------------------------------------------------------------------
| Moose Test Performance: Alive time=2.19063, Active time=2.17146                                                         |
 -------------------------------------------------------------------------------------------------------------------------
| Event                                      nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                                       w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|-------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                         |
|                                                                                                                         |
| Application                                                                                                             |
|   Full Runtime                             1          0.0055      0.005471    2.1715      2.171500    0.25     100.00   |
|                                                                                                                         |
| Execution                                                                                                               |
|   Adaptivity: adaptMesh()                  5          1.1553      0.231068    1.1553      0.231068    53.21    53.21    |
|   adaptivity_computeIndicators()           6          0.2629      0.043811    0.2629      0.043811    12.11    12.11    |
|   adaptivity_compute_markers               6          0.0239      0.003991    0.0239      0.003991    1.10     1.10     |
|   computeKernels()                         73         0.4139      0.005669    0.4139      0.005669    19.06    19.06    |
|   computeNodalBCs()                        73         0.0028      0.000039    0.0028      0.000039    0.13     0.13     |
|   compute_jacobian()                       10         0.1101      0.011013    0.1101      0.011013    5.07     5.07     |
|   compute_residual()                       73         0.0036      0.000050    0.4204      0.005758    0.17     19.36    |
|   solve()                                  5          0.0477      0.009546    0.5782      0.115646    2.20     26.63    |
|                                                                                                                         |
| Output                                                                                                                  |
|   Exodus::output()                         6          0.0477      0.007952    0.0477      0.007952    2.20     2.20     |
|                                                                                                                         |
| Setup                                                                                                                   |
|   Application Setup                        1          0.0810      0.080978    0.0840      0.083960    3.73     3.87     |
|   FEProblemBase::init::meshChanged()       1          0.0003      0.000262    0.0003      0.000262    0.01     0.01     |
|   Initial updateActiveSemiLocalNodeRange() 1          0.0001      0.000060    0.0001      0.000060    0.00     0.00     |
|   Initial updateGeomSearch()               2          0.0000      0.000002    0.0000      0.000002    0.00     0.00     |
|   NonlinearSystem::update()                1          0.0001      0.000083    0.0001      0.000083    0.00     0.00     |
|   eq.init()                                1          0.0026      0.002636    0.0026      0.002636    0.12     0.12     |
|   execMultiApps()                          1          0.0000      0.000008    0.0000      0.000008    0.00     0.00     |
|   execTransfers()                          1          0.0000      0.000005    0.0000      0.000005    0.00     0.00     |
|   initial adaptivity                       1          0.0125      0.012469    0.0187      0.018698    0.57     0.86     |
|   initialSetup()                           1          0.0010      0.001001    0.0202      0.020200    0.05     0.93     |
|   reinit() after updateGeomSearch()        1          0.0000      0.000003    0.0000      0.000003    0.00     0.00     |
|                                                                                                                         |
| Utility                                                                                                                 |
|   projectSolution()                        1          0.0004      0.000421    0.0004      0.000421    0.02     0.02     |
 -------------------------------------------------------------------------------------------------------------------------
| Totals:                                    271        2.1715                                          100.00            |
 -------------------------------------------------------------------------------------------------------------------------
```

**Comment by permcody** [comment]
I like the colon syntax because it stands out to me as a sub category. Also, it's clear that it's not a method name (not that we use underscores anyway).

**Comment by jessecarterMOOSE** [comment]
Something else to consider is the fact that now there's a long-winded string you have to match when using the PerformanceData Postprocessor (e.g.: `event = "Adaptivity: adaptMesh()"`). It might be nice to be able to do some sort of substring match such that `event = adaptMesh()` is sufficient. That would also help maintain backwards-compatibility.

**Comment by permcody** [comment]
That's not a bad idea. I'd open a separate ticket though so it doesn't get lost. We are really trying to clean up tickets so we can get through the enormous backlog.

**Review by permcody — APPROVED** [review]

**Pull request merged**
