### PR TITLE
Adds step 11 that creates action for building velocity aux variables.

### LINKED ISSUE #9259: Tutorial Step11: Action to create vel_x, vel_y, vel_z AuxVariable and kernels.
### Description of the enhancement or error report
We talk about actions, but don't give an example w/r/t to the tutorial.

### Rationale for the enhancement or information for reproducing the error
This would give us a place to point people who want to create actions that has a bit more meaning then the current example in the examples directory.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Make tutorial more complete.

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #9259)

### CODE REVIEW

**Comment by aeslaughter** [comment]
Running the `git clang-format` command seems to remove the new symlinks by putting the content into the actual file rather than keeping it a link.

**Comment by aeslaughter** [comment]
```
slauae@localhost:~/projects/moose-docs/tutorials/darcy_thermo_mech (tutorial-action-9259)$ git clang-format cd1f4e4caac9853eeae5251de8d516f256a8522f
changed files:
    tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h
    tutorials/darcy_thermo_mech/step11_action/include/auxkernels/RandomCorrosion.h
    tutorials/darcy_thermo_mech/step11_action/include/base/DarcyThermoMechApp.h
    tutorials/darcy_thermo_mech/step11_action/include/bcs/HeatConductionOutflow.h
    tutorials/darcy_thermo_mech/step11_action/include/kernels/DarcyConvection.h
    tutorials/darcy_thermo_mech/step11_action/include/kernels/DarcyPressure.h
    tutorials/darcy_thermo_mech/step11_action/include/materials/PackedColumn.h
    tutorials/darcy_thermo_mech/step11_action/src/actions/DarcyVelocityAction.C
    tutorials/darcy_thermo_mech/step11_action/src/auxkernels/DarcyVelocity.C
    tutorials/darcy_thermo_mech/step11_action/src/auxkernels/RandomCorrosion.C
    tutorials/darcy_thermo_mech/step11_action/src/bcs/HeatConductionOutflow.C
    tutorials/darcy_thermo_mech/step11_action/src/kernels/DarcyConvection.C
    tutorials/darcy_thermo_mech/step11_action/src/kernels/DarcyPressure.C
    tutorials/darcy_thermo_mech/step11_action/src/main.C
    tutorials/darcy_thermo_mech/step11_action/src/materials/PackedColumn.C
    tutorials/darcy_thermo_mech/step11_action/unit/src/main.C
slauae@localhost:~/projects/moose-docs/tutorials/darcy_thermo_mech (tutorial-action-9259)$ 
slauae@localhost:~/projects/moose-docs/tutorials/darcy_thermo_mech (tutorial-action-9259)$ git diff
diff --git a/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h b/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h
deleted file mode 120000
index 232f916cf..000000000
--- a/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h
+++ /dev/null
@@ -1 +0,0 @@
-../../../step10_multiapps/include/auxkernels/DarcyVelocity.h
\ No newline at end of file
diff --git a/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h b/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h
new file mode 100644
index 000000000..4103177ab
--- /dev/null
+++ b/tutorials/darcy_thermo_mech/step11_action/include/auxkernels/DarcyVelocity.h
@@ -0,0 +1,54 @@
+/****************************************************************/
+/*               DO NOT MODIFY THIS HEADER                      */
+/* MOOSE - Multiphysics Object Oriented Simulation Environment  */
+/*                                                              */
+/*           (c) 2010 Battelle Energy Alliance, LLC             */
+/*                   ALL RIGHTS RESERVED                        */
+/*                                                              */
+/*          Prepared by Battelle Energy Alliance, LLC           */
+/*            Under Contract No. DE-AC07-05ID14517              */
+/*            With the U. S. Department of Energy               */
+/*                                                              */
+/*            See COPYRIGHT for full restrictions               */
+/****************************************************************/
+
+#ifndef DARCYVELOCITY_H
+#define DARCYVELOCITY_H
+
+#include "AuxKernel.h"
+
+// Forward Declarations
+class DarcyVelocity;
+
+template <>
+InputParameters validParams<DarcyVelocity>();
+
+/**
+ * Auxiliary kernel responsible for computing the Darcy velocity given
+ * several fluid properties and the pressure gradient.
+ */
+class DarcyVelocity : public AuxKernel
+{
+public:
+  DarcyVelocity(const InputParameters & parameters);
+
+protected:
+  /**
+   * AuxKernels MUST override computeValue.  computeValue() is called on
+   * every quadrature point.  For Nodal Auxiliary variables those quadrature
+   * points coincide with the nodes.
+   */
+  virtual Real computeValue() override;
+
```

**Comment by aeslaughter** [comment]
@permcody This won't pass because of the clang-format problems with symbolic links, when you have time just take a look to see if this is something we want to add. If not, we can just drop it and forget about it all together.

**Comment by permcody** [comment]
Custom Actions are one of those systems which we probably don't really want to spend time covering. My thoughts are that it would be fine to have this in the source tree, but I'd probably not include it in the slides. We could mention that it's there and even change the current custom Action slides to point to it, but I probably wouldn't cover it.

**Comment by aeslaughter** [comment]
I agree, this PR doesn't change slides or mention that this exists. Just wanted here to point to people in the future and possible add to the actions documentation that does not exist.

**Pull request closed without merging**
