### PR TITLE
Get rid of Exodiff build warnings

### LINKED ISSUE #1777: Fix compiler warnings (MOOSE)
None

### PR DESCRIPTION
**Pull request by permcody**
closes #1777

### CODE REVIEW

**Comment by andrsd** [comment]
Are you expecting to do more work on this?  There is one warning in modules:
```
contact/src/MechanicalContactConstraint.C:1587:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
             return 0.0;
                       ^
contact/src/MechanicalContactConstraint.C:1590:9: note: here
         case CM_GLUED:
         ^~~~
```

**Comment by permcody** [comment]
I wasn't planning on any more additions to this PR. It should clean up all warnings in MOOSE. Feel free to merge and we can take a look at modules later. @friedmud suggested that we add checks to CIVET to disallow new warnings from being introduced. I kind of like that idea but am a little worried it might be too heavy handed. Maybe it's worth a shot so we don't have to keep fixing these up.

**Review by andrsd — APPROVED** [review]

**Comment by brianmoose** [comment]
I am seeing 2 warnings in modules, the one that David showed and this:

```
porous_flow/src/auxkernels/PorousFlowPropertyAux.C: In constructor 'PorousFlowPropertyAux::PorousFlowPropertyAux(const InputParameters&)':
porous_flow/src/auxkernels/PorousFlowPropertyAux.C:84:95: warning: this statement may fall through [-Wimplicit-fallthrough=]
       _enthalpy = &getMaterialProperty<std::vector<Real>>("PorousFlow_fluid_phase_enthalpy_qp");
                                                                                               ^
porous_flow/src/auxkernels/PorousFlowPropertyAux.C:86:5: note: here
     case PropertyEnum::INTERNAL_ENERGY:
     ^~~~
```

In `MechanicalContactConstraint.C` it looks like they didn't expect to fall through.
In `PorousFlowPropertyAux.C` it looks like they forgot to break.
Somebody more knowledgeable than me about the code should take a look at it.

@friedmud I will enable `-Werror` on the framework until these get fixed.

**Comment by permcody** [comment]
@brianmoose - I suggest that you look at git blame for the specific line and just tag the author.

**Pull request merged**
