### PR TITLE
Show info for additional subdomains and sidesets

### LINKED ISSUE #28077: Show info for additional subdomains and sidesets
### Motivation

With `add_subdomain_names` the user can add "empty" subdomains to be used later. When the user skips `add_subdomain_ids` the ids are auto-assiged. But the ids choosen by Moose are not directly visible to the user. The same with sidesets.

### Design

In the spirit of the parameter `show_info` in [MeshGenerator.C](https://github.com/idaholab/moose/blob/6349167f4073a10e927fc73d403dd65fd370db6c/framework/src/meshgenerators/MeshGenerator.C) Moose could add a parameter `add_subdomain_show_info` so the user can request the ids to be shown. For sidesets it would be `add_sideset_show_info`.

### Impact

Just adds some console output on demand of the user.

### PR DESCRIPTION
**Pull request by jmeier**
With `add_subdomain_names` the user can add "empty" subdomains to be used later. If the user skips `add_subdomain_ids` the ids are auto-assiged. But the ids choosen by Moose are not directly visible to the user. The same with sidesets.
I'd like to propose to add the parameters `add_subdomain_show_info` and `add_sideset_show_info`.
#closes #28077

### CODE REVIEW

**Comment by grunerjmeier** [comment]
This PR currently does not contain a test. Is a test needed for this kind of PR? If yes, how to test console output?

**Comment by GiudGiud** [comment]
In terms of testing, you have to a do a RunApp test with "expect_out" to test console output.

This overlaps too much with the mesh info output. If you want empty subdomains and sidesets to show up there, you'll need to modify libMesh to print empty subdomains and sidesets

**Comment by grunerjmeier** [comment]
> This overlaps too much with the mesh info output. If you want empty subdomains and sidesets to show up there, you'll need to modify libMesh to print empty subdomains and sidesets
I'll stay away from libMesh for now. I close the PR?

**Comment by GiudGiud** [comment]
Yes I think it's best

**Pull request closed without merging**
