### PR TITLE
WIP: Frictional mortar contact with tensor mechanics tests

### PR DESCRIPTION
**Pull request by tophmatthews**
Added frictional mortar contact with tensor mechanics.

Ref #13080

### CODE REVIEW

**Comment by tophmatthews** [comment]
@lindsayad Your going to hate me while I'm getting all these tests up ... but you'll be thanking me down the line (hopefully :)

These include frictional contact only for first order 2d meshes for now. Right now, I am having issues with ping-ponging...

<details>
<summary>
check this input out
</summary>

```
E_block = 1e9
E_plank = 1e9
elem = QUAD4
order = FIRST
name = 'stiff_stiff'

[Mesh]
  patch_size = 80
  patch_update_strategy = auto
  [./plank]
    type = GeneratedMeshGenerator
    dim = 2
    xmin = -0.3
    xmax = 0.3
    ymin = -10
    ymax = 10
    nx = 2
    ny = 67
    elem_type = ${elem}
  [../]
  [./plank_sidesets]
    type = RenameBoundaryGenerator
    input = plank
    old_boundary_id = '0 1 2 3'
    new_boundary_name = 'plank_bottom plank_right plank_top plank_left'
  [../]
  [./plank_id]
    type = SubdomainIDGenerator
    input = plank_sidesets
    subdomain_id = 1
  [../]

  [./block]
    type = GeneratedMeshGenerator
    dim = 2
    xmin = 0.31
    xmax = 0.91
    ymin = 9.2
    ymax = 10.0
    nx = 3
    ny = 4
    elem_type = ${elem}
  [../]
  [./block_id]
    type = SubdomainIDGenerator
    input = block
    subdomain_id = 2
  [../]

  [./combined]
    type = MeshCollectionGenerator
    inputs = 'plank_id block_id'
  [../]
  [./block_rename]
    type = RenameBlockGenerator
    input = combined
    old_block_id = '1 2'
    new_block_name = 'plank block'
  [../]
  [./block_sidesets]
    type = SideSetsFromPointsGenerator
    input = block_rename
    points = '0.6  9.2  0
              0.91 9.5  0
              0.6  10.0 0
              0.31 9.5  0'
    new_boundary = 'block_bottom block_right block_top block_left'
  [../]
[]

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Variables]
  [./disp_x]
    order = ${order}
    block = 'plank block'
    scaling = ${fparse 2.0 / (E_plank + E_block)}
  [../]
  [./disp_y]
    order = ${order}
    block = 'plank block'
    scaling = ${fparse 2.0 / (E_plank + E_block)}
  [../]
[]

[Modules/TensorMechanics/Master]
  [./action]
    decomposition_method = EigenSolution
    strain = FINITE
    generate_output = 'stress_xx stress_yy stress_zz vonmises_stress hydrostatic_stress strain_xx strain_yy strain_zz'
    block = 'plank block'
  [../]
[]

[Contact]
  [./frictional]
    mesh = block_sidesets
    master = plank_right
    slave = block_left
    formulation = mortar
    system = constraint
    model = coulomb
    friction_coefficient = 0.1
  [../]
[]

[BCs]
  [./left_x]
    type = DirichletBC
    variable = disp_x
    boundary = plank_left
    value = 0.0
  [../]
  [./left_y]
    type = DirichletBC
    variable = disp_y
    boundary = plank_bottom
    value = 0.0
  [../]
  [./right_x]
    type = FunctionDirichletBC
    variable = disp_x
    boundary = block_right
    function = '-0.04*sin(4*t)+0.02'
  [../]
  [./right_y]
    type = FunctionDirichletBC
    variable = disp_y
    boundary = block_right
    function = '-t'
  [../]
[]

[Materials]
  [./plank]
    type = ComputeIsotropicElasticityTensor
    block = 'plank'
    poissons_ratio = 0.3
    youngs_modulus = ${E_plank}
  [../]
  [./block]
    type = ComputeIsotropicElasticityTensor
    block = 'block'
    poissons_ratio = 0.3
    youngs_modulus = ${E_block}
  [../]
  [./stress]
    type = ComputeFiniteStrainElasticStress
    block = 'plank block'
  [../]
[]

[Dampers]
  [./disp_x]
    type = MaxIncrement
    variable = disp_x
    max_increment = 0.1
  [../]
  [./disp_y]
    type = MaxIncrement
    variable = disp_y
    max_increment = 0.1
  [../]
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  type = Transient
  solve_type = 'PJFNK'
  petsc_options = '-snes_converged_reason -ksp_converged_reason'
  petsc_options_iname = '-pc_type -mat_mffd_err -pc_factor_shift_type -pc_factor_shift_amount'
  petsc_options_value = 'lu       1e-5          NONZERO               1e-15'
  end_time = 15
  dt = 0.1
  dtmin = 0.1
  timestep_tolerance = 1e-6
  line_search = 'contact'
  l_max_its = 30
[]

[Postprocessors]
  [./nl_its]
    type = NumNonlinearIterations
  [../]
  [./total_nl_its]
    type = CumulativeValuePostprocessor
    postprocessor = nl_its
  [../]
  [./l_its]
    type = NumLinearIterations
  [../]
  [./total_l_its]
    type = CumulativeValuePostprocessor
    postprocessor = l_its
  [../]
  [./contact]
    type = ContactDOFSetSize
    variable = frictional_normal_lm
    subdomain = frictional_slave_subdomain
  [../]
  [./avg_hydro]
    type = ElementAverageValue
    variable = hydrostatic_stress
    block = 'block'
  [../]
  [./max_hydro]
    type = ElementExtremeValue
    variable = hydrostatic_stress
    block = 'block'
  [../]
  [./min_hydro]
    type = ElementExtremeValue
    variable = hydrostatic_stress
    block = 'block'
    value_type = min
  [../]
  [./avg_vonmises]
    type = ElementAverageValue
    variable = vonmises_stress
    block = 'block'
  [../]
  [./max_vonmises]
    type = ElementExtremeValue
    variable = vonmises_stress
    block = 'block'
  [../]
  [./min_vonmises]
    type = ElementExtremeValue
    variable = vonmises_stress
    block = 'block'
    value_type = min
  [../]
[]

[Outputs]
  file_base = ${name}
  [./exodus_out]
    type = Exodus
    execute_on = 'nonlinear'
  [../]
  [./comp]
    type = CSV
    show = 'contact'
  [../]
  [./out]
    type = CSV
    file_base = '${name}_out'
  [../]
[]

[Debug]
  show_var_residual_norms = true
[]
```
</details>

Looking at the nonlinear iterations on the exodus, you can see the ping-ponging:

asdf

I think you had some techniques to help reduce this. Any ideas?

**Comment by lindsayad** [comment]
> Looking at the nonlinear iterations on the exodus, you can see the ping-ponging:

Your new favorite thing! 😄 Yes I would really like to try #14167 on this kind of thing. I hope to get that done first, and then I can try these inputs out

**Comment by tophmatthews** [comment]
> Your new favorite thing! 😄

Nope! not even close to my favorite thing...but necessary I suppose.

**Comment by tophmatthews** [comment]
I wonder if there is some sort of clever damper that could help overcome this... @fdkong do you have anything in your bag of tricks that helps this? I'm already using your contact line search.

**Comment by lindsayad** [comment]
Reducing lambda in the line search is reasonable, and that's what the contact line search does. And we've seen that that doesn't work super well. @tophmatthews try to be a little patient and let's wait and see whether #14167 can help out. Jamming is a well-known phenomenon in the contact literature, and easy fixes have never been the solution.

**Comment by tophmatthews** [comment]
> @tophmatthews try to be a little patient

Patience? Ain't nobody got time for that :)

**Comment by lindsayad** [comment]
Improving contact convergence has been the primary impetus for me developing automatic differentiation, non-linear complementarity, automatic scaling, mortar, and now grid sequencing. Trust me, I want to solve this problem as much as anyone. It's been the golden snitch for me since I started at INL!

**Comment by lindsayad** [comment]
Also since this is already a pretty coarse grid, I want to figure out how to apply a reduced active set method to the contact constraints, as opposed to the current MOOSE-implemented semi-smooth method. That's something I might want to brainstorm with @fdkong

**Comment by tophmatthews** [comment]
Keeping in mind some of the geometric scaling I proposed, do you see problems with long skinny elements that would motivate geometrically scaled square elements? I received pushback on the necessity of geometric scaling.

**Comment by lindsayad** [comment]
Intuitively I don't see much of a problem insofar as the condition number of the problem remains reasonable

**Comment by lindsayad** [comment]
BTW reduced active set method does do some line-search modification/restriction such that constraints are never violated...the restriction can be thought of as some "damping."

**Comment by lindsayad** [comment]
@tophmatthews You can checkout my `topher-frictional-contact` branch. I've gotten much better convergence than what your input file had originally, but I still get poor convergence on time-step 147 as it tries to come out of contact for the last time. My current plan is to try and get reduced-space active set going to try and ensure monotonic convergence behavior...

**Comment by tophmatthews** [comment]
> My current plan is to try and get reduced-space active set going to try and ensure monotonic convergence behavior...

Awesome, glad you always have ideas!

I'm trying to look through and see what you changed:
- You coarsened like crazy...down to one element bouncing block? I assume this was just for your testing to speed things up, but it still works the same with refined blocks?
- You scaled the normal and tangential lms by 1e-7 and 1e-6, which is close to the disp variable scaling which is 1e-9. I wonder what the reason was there? Automatic scaling should take care of that though I imagine.
- You changed the `c` value to 1e8. I've seen that parameter and read the description `Parameter for balancing the size of the gap and contact pressure`, but generally have no idea what it means.

**Comment by lindsayad** [comment]
>     * You coarsened like crazy...down to one element bouncing block? I assume this was just for your testing to speed things up, but it still works the same with refined blocks?

Look at `Problem/num_grid_sequences=2`. This means that your final mesh will have two levels of refinement, so it should actually be a little finer than your original problem.

>     * You scaled the normal and tangential lms by 1e-7 and 1e-6, which is close to the disp variable scaling which is 1e-9. I wonder what the reason was there? Automatic scaling should take care of that though I imagine.

Automatic scaling will do nothing:
- For normal contact when the gap is zero
- For tangential contact when a node is sticking

because in those cases the residual is not a function of the lagrange multipliers themselves, e.g. there is no on-diagonal dependence.

>     * You changed the `c` value to 1e8. I've seen that parameter and read the description `Parameter for balancing the size of the gap and contact pressure`, but generally have no idea what it means.

For normal contact for example, the residual is `std::min(gap, u)`. If `u` is on the order of 1e7 while `gap` is on the order of 1e-1, then this residual contribution will be poorly behaved, especially when using PJFNK. This can lead to ping-ponging between residual values of ~1e7 and ~1e-1 because the Jacobian-free approximation is having a hard time dealing with transitions between Jacobian entries that should alternately be of order 1e7 and 1e-1. It's much better if they're on the same order.

**Comment by lindsayad** [comment]
One thing I'll note is that without grid sequencing, e.g. if I comment out `num_grid_sequences` and put `uniform_refine = 2` in the mesh block, then this simulation fails on time step 100 as opposed to time step 147, so definitely getting some robustness from the sequencing.

**Comment by tophmatthews** [comment]
nope...hopefully

**Comment by lindsayad** [comment]
Let’s keep this on the radar

**Comment by dewenyushu** [comment]
Happy late New Year guys! This is Dewen Yushu, a new postdoc who will be working on the contact module. Cheers!

**Comment by lindsayad** [comment]
Ok @dewenyushu you can look at the `stiff_stiff.i` input file in this PR for an illustration of a frictional mortar case that struggles with convergence. The simulation does better using `NEWTON` and the PETSc option `-snes_fd` indicating that a better Jacobian would help here. I hope to enable better mortar Jacobians through libmesh/libMesh#2396

**Pull request closed without merging**
