### PR TITLE
Test for non-unicode characters in output

### LINKED ISSUE #14370: TestHarness might crash when reading bad characters
## Bug Description

It appears that it's possible for the TestHarness to crash when reading test output.

## Steps to Reproduce

Unknown, but it happened here:
https://moosebuild.inl.gov/job/220497/

## Impact

Moderate: The TestHarness shouldn't crash when reading output.

### PR DESCRIPTION
**Pull request by milljm**
Fail the test properly when non-unicode characters are present in
stdout/stderr output.

Create unittest to verify functionality.

Closes #14370

### CODE REVIEW

**Review by permcody — DISMISSED** [review]

**Comment by permcody** [comment]
Tag @YaqiWang - Fix is going in already...

**Comment by YaqiWang** [comment]
Thanks! This makes feel sane again.

**Comment by permcody** [comment]
@YaqiWang - I don't think we should merge this until Mammoth tests have been fixed up. This PR just failed on Mammoth on some of the test we identified yesterday as containing race conditions.

**Comment by YaqiWang** [comment]
I will be on it soon today.

**Comment by YaqiWang** [comment]
What is the status of this one?

**Comment by milljm** [comment]
@YaqiWang It looks like its passing for Mammoth now... I am invalidating one last target due to a strange MPI intermittent issue. If that passes, I'll ask someone to merge this.

**Comment by milljm** [comment]
@YaqiWang Would you kindly review this PR. I'll merge if you approve.

**Review by YaqiWang — APPROVED** [review]

**Comment by YaqiWang** [comment]
Looks good to me.

**Comment by milljm** [comment]
@permcody I thought maybe Yaqi had merge rights... I guess not, can you merge this? Things are passing now (aside from zapdos due to other issues).

**Review by permcody — APPROVED** [review]

**Pull request merged**
