### PR TITLE
Evenly distribute the boundary nodes to avoid bad shaped elements

### LINKED ISSUE #14533: ConcentricCircleMeshGenerator is not smoothing nodes on outer square
## Reason
`ConcentricCircleMeshGenerator` is not smoothing nodes on outer square thus can create some strange looking mesh when smoothing is turned on. It does not look good and also can generate less accurate solutions.

The issue can be see with the following input:
```
[Mesh]
  [./ccmg]
    type = ConcentricCircleMeshGenerator
    num_sectors = 12
    radii = '0.248036411 0.328121329 0.350776456 0.372054616 0.382249781 0.39218'
    rings = '8 8 2 2 1 1 12'
    inner_mesh_fraction = 0.60
    has_outer_square = on
    pitch = 1.25984
    portion = top_right
    preserve_volumes = off
    smoothing_max_it = 1
  []
[]

[Outputs]
  exodus = true
[]
```
quarter-pin

## Design
Looks to me this can be fixed by changing the order of adding side sets on outer boundaries and smoothing.

## Impact
Make this generator generate a better mesh.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #14533.

A parameter `inner_mesh_fraction`  is removed because it is no longer needed after this change. The generated mesh with this change is:

mesh2

### CODE REVIEW

**Comment by YaqiWang** [comment]
MAMMOTH has one test using this generator. It can be regolded easily.

**Comment by permcody** [comment]
@YaqiWang - This can probably be merged. If you are around respond to this thread and we can get it in. I don't want to merge unless you are ready to deal with the Mammoth regold.

**Review by permcody — APPROVED** [review]

**Comment by YaqiWang** [comment]
Yes, @cody. I am ready. Sorry for the delayed response. Just back on track from the holiday and travel.

**Comment by permcody** [comment]
Merged

**Comment by YaqiWang** [comment]
Cannot send in MR in mammoth at this moment. Will fix it asap later. Thanks.

**Pull request merged**
