### PR TITLE
Better Nemesis repartitioning test

### PR DESCRIPTION
**Pull request by roystgnr**
This should provide better coverage of the new capabilities discussed in #5563.

It's already been invaluable in bug hunting; it turned out that there were a whole class of bugs related to repartitioning a Nemesis file which just didn't get triggered by repartitioning a from-scratch ParallelMesh.

This PR ought to fail with the first MooseBuild, then work after we merge libMesh/libmesh#625 and update the libMesh module in a subsequent commit here.

### CODE REVIEW

**Comment by permcody** [comment]
Looks like we have another test in modules for @aeslaughter's image mapper work. Do you have any time to look at that test as well?

**Comment by roystgnr** [comment]
I'll give it a look.  Just "make test" in the modules subdirectory?

**Comment by permcody** [comment]
Yes

**Comment by roystgnr** [comment]
I can see the problem, I think.

It's not MOOSE-specific; *anyone* trying to output a repartitioned AMR mesh via Nemesis could hit this.

In the un-repartitioned case, all elements' descendants belong to the same processor.  So we can build Nemesis_IO_Helper::subdomain_map while iterating over active local elements, then build libmesh_elem_num_to_exodus while iterating over the subdomain_map, and then we query that while iterating over active descendants of local boundary elements and we're always guaranteed to get a result.

But once we repartition, active descendants of local elements aren't necessarily local, we've got empty slots in the libmesh_elem_num_to_exodus map, and so we scream and die.

We can't increase the size of the subdomain_maps, or the exodus numbering will be wrong.  But it looks like bndry_elem_list already includes non-local elements, so perhaps instead of testing locality of each boundary element we can test locality of each descendant?  I'll try that.

**Comment by roystgnr** [comment]
IMHO this should finally be ready to merge.

**Comment by permcody** [comment]
Thanks, We'll probably hold off on merging this for a few weeks since we just did a libmesh update and like to spread the rebuild pain out a bit for our users.

**Comment by permcody** [comment]
@roystgnr We have the version of libMesh you need to run this test but when I tried to rebase it and rerun the tests it failed (EXODIFF) on the new nemesis partitioning test. It looks like the split is off (nodes and elements). Do you have time to rebase and take a look at this?

**Comment by roystgnr** [comment]
I'll at least see if I can replicate it on my systems, definitely.  Not sure if/when I'll find time to fix the problem.  My suspicion is that there may be some system-dependent ParMETIS behavior, in which case the workaround would be to generate new gold standards on your systems and use those to guard against regressions until we have time to dig into what's causing the differences.

**Comment by permcody** [comment]
Hmm, well at the very least you can rebase and re-push since it needs to happen anyway (empty merge conflict in the module). If it passes again (which it did before), we can just disable the tests on our OS X systems. I'll be satisfied with that as an interim solution.

**Comment by roystgnr** [comment]
Still passes for me after the rebasing.  However, outputs/vtk.diff_parallel_mesh fails for me (this isn't a new thing, just an oddity I'd forgotten to mention and haven't had time to investigate in the past), so there's definitely *something* system-dependent going on that I don't understand yet..

**Comment by permcody** [comment]
Adding one more commit before merging #5644

**Pull request closed without merging**
