### PR TITLE
speed up ad mortar contact tests a little bit more

### PR DESCRIPTION
**Pull request by lynnmunday**
The blocks still go in and out of contact 2 times.  These tests originally ran for 10 then were reduced to 5 and now 3.  

ref #15141

### CODE REVIEW

**Comment by lynnmunday** [comment]
@bwspenc @lindsayad could you review.

**Review by lindsayad — APPROVED** [review]
It still goes in-and-out three times with the reduction to `end_time = 3`?

**Comment by lynnmunday** [comment]
I was wrong, It goes into contact 2 times, based on csv file.   The test time can be extended.  I didn't realize the jacobian tests were the ones that were taking the most time.  The cli_args you put in the test file was being ignored/overridden by the end_time parameter in the input file so the jacobian tests were never being shortened.

**Comment by lindsayad** [comment]
Ok yea if we get three in and outs with an `end_time` of 5, I would prefer
that. Thanks for doing this!

**Pull request closed without merging**
