### PR TITLE
Execute controls before aux kernels

### PR DESCRIPTION
**Pull request by andrsd**
Controls have to be execute before auxes are, becuase if the aux has a
controlled value, it needs to use the one that the control is
prescribing at that time. Otherwise, the values are lagged in time.
This is observable is the aux has execute_on = timestep_begin.

Refs #5680

### CODE REVIEW

**Comment by aeslaughter** [comment]
This opens a huge can of worms for all systems, depending on if you are controlling something or using something in the control, when you want it to execute can change.

Is it possible, to set the Control to "execute_on=INITIAL TIMESTEP_END" such that that control will change the value used in the Aux on the previous timestep. Otherwise, we probably need to go down the PRE_AUX/POST_AUX route that we do for Postprocessors, except that we will need this for every system in MOOSE.

**Comment by andrsd** [comment]
I was worried you would say something like this.

I cannot change the value in the previous time step, because I am setting my values based on simulation time. That's why I need to do it at the beginning of time step before anything else happens.

Let me try if I can do something else to achieve this, so we do not need to go PRE/POST route.

It __really__ is time for MOOSE 3.0 :-)

**Comment by aeslaughter** [comment]
When I can get my arbitrary execute on stuff finished up, which is very close, you could just create a custom call to Controls in custom FEProblem

**Comment by andrsd** [comment]
Ok. I can work around this in a meantime by setting `execute_on = linear`. So let's close this...

**Pull request closed without merging**
