### PR TITLE
Update libMesh to latest master

### PR DESCRIPTION
**Pull request by roystgnr**
The fixes in https://github.com/libMesh/libmesh/pull/1358 solve
failures in multiple #1500 AMR test cases (on higher processor counts;
they were already working with -np 2) for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
Huh.  The output/position failure was already on my todo list, since it had been failing on higher numbers of processors for a while, so I didn't realize we'd shaken things up hard enough to get a failure on 2 processors.  Looks like I can replicate it more easily now and I'm starting to understand it, though, so (cross our fingers) I think can fix it and this might fix some harder-to-debug cases too.

**Comment by permcody** [comment]
@roystgnr - what's your priority on getting this in? I usually like to have @jwpeterson here when we do these updates but he's on vacation in Europe! I'm fine merging this today if you'd like it to go in, otherwise, it'll be later in the week (possibly the end of the week).

**Comment by roystgnr** [comment]
I'm hammered with non-INL stuff from now until Thursday, then I'm on vacation in California from Friday until June 27th, so I'd been hoping to merge this today so I could deal with any fallout ASAP.

However, the only thing I *really* wanted to do right away is test #9201 against the new libMesh, and I hadn't wanted to do that by pulling a new libMesh update into a commit there, because I wanted to first test the libMesh update separately, but now that that's done I'll add it to #9201 too.

**Comment by permcody** [comment]
Sounds good, we'll get this merged today. I think we'll throw a few more tests at this PR before we hit the button.

**Comment by permcody** [comment]
Sigh...  New regression in 64-bit build. Since I have icecream, I'll reconfigure really quick and make sure we don't have any more and submit a patch.

**Comment by roystgnr** [comment]
Patched and included.

**Review by permcody — APPROVED** [review]

**Pull request merged**
