### PR TITLE
Gap heat transfer radiation energy balance

### LINKED ISSUE #18585: GapHeatTransfer creates heat in the gap for CYLINDER and SPHERE
## Bug Description

In `GapHeatTransfer`, the heat flux across the gap at a given node/qp is computed and then identically applied to both sides of the gap. This is not correct in non-plate geometries because both sides do not have the same length.

Something like this in could be done in `GapHeatTransfer::computeQpResidual()`:

```
% for cylinders:
if (_inner_surface)
  _edge_multiplier *= 2*r1/(r1+r2)
else
  _edge_multiplier *= 2*r2/(r1+r2)

% for spheres:
if (_inner_surface)
  _edge_multiplier *= (2*r1/(r1+r2))^2
else
  _edge_multiplier *= (2*r2/(r1+r2))^2
```

As @jiangwen84 pointed out, r1 and r2 designate the __local__ inner and outer radii of the gap, respectively (local in case there is deformation).

## Steps to Reproduce

[This branch](https://github.com/vincentlaboure/moose/tree/gapheattransfer_heat_balance) contains two examples showing 10% discrepancy with `r2/r1 = 1.1`. 

## Impact

If the ratio of outer to inner radii is close to 1, the impact should be limited.

However, even for a standard BISON case with cylinders `r2 = 4.18 mm`,  `r1 = 4.1 mm`, that's already a 2% discrepancy.
For cases with much larger gaps (e.g. in HTRs where radiation happens through the cooling channel), it can reach 20% or more.

In any case, this prevents from achieving global heat balance.

Tag @jortensi

### PR DESCRIPTION
**Pull request by recuero**
This PR intends to close #18585.

## Reason
It implements a fix, suggested by @vincentlaboure, who identified an energy balance mismatch for radiation problems when the gap length between the bodies is not negligible with respect to cylinder/sphere's main dimensions. This fix  introduces an assumed middle plane that is used as a reference to factor in the influence of area differences in the energy balance, which was neglected in the existing implementation.

## Design
Minor additions to add a scale factor based on _current_ geometry in `GapHeatTransfer`. Fixes affect cylinder and sphere geometries.

## Impact
Simulations that preserve energy balance when radiation heat transfer is used.

@novasr

### CODE REVIEW

**Comment by recuero** [comment]
@bwspenc @dschwen Input?

**Review by vincentlaboure — COMMENTED** [review]
As suggested by @novasr, is there a reason not to have:

```
_gap_conductance_dT[_qp] = dh_conduction() + dh_radiation();
```

in `GapConductance::computeQpConductance()`?

**Comment by recuero** [comment]
Yeah, that makes sense to me. I'll play with it and see it consistently improves convergence. We'll need to make a number of changes in the apps to get this PR checked in.

**Review by dschwen — APPROVED** [review]
Looks good to me

**Review by loganharbour — APPROVED** [review]
Good to go for breaking next

**Pull request merged**
