### PR TITLE
Clarify how PorousFlowPiecewiseLinearSink can specify BCs

### PR DESCRIPTION
**Pull request by permcody**
Putting https://github.com/idaholab/moose/pull/12795 on next

### CODE REVIEW

**Comment by permcody** [comment]
Sorry @danielbi-ETHZ - Your PR was against the wrong branch ("devel" instead of "next"). Here's your PR once more testing against "next".

**Comment by permcody** [comment]
@lindsayad - This PR has already been reviewed and approved here: https://github.com/idaholab/moose/pull/12795, but it was against the devel branch. Could you please merge?

**Review by lindsayad — APPROVED** [review]

**Comment by permcody** [comment]
@danielbi-ETHZ - New problem... The "!pthreads" restriction is something we don't test a whole lot but porous-flow relies on that configuration. It turns out your test never ran during our whole PR process, and now that it finally made it into next, it failed:
https://civet.inl.gov/job/285620/

I'll look into testing the "!pthreads" configuration on PRs. I'm not sure if you'll have a chance to look at this or not, but it's definitely not correct as it stands.

**Comment by cpgr** [comment]
I can see what has happened. I didn't see that @danielbi-ETHZ had put a new test in here, so didn't see that my recently merged PR would break it. 

I'll put in a PR shortly to fix it as it is easy - I'm just waiting for libmesh to update on my computer.

**Pull request merged**
