### PR TITLE
Add SamplerInterface to UserObject

### LINKED ISSUE #15913: User objects should have sampler interface
## Reason
Many of the user objects (vpps and pps) in stochastic tools use SamplerInterface. 

## Design
Would help clean things up if we just have UserObject derive from SamplerInterface.

## Impact
Cleaning up a lot of the STM user objects.

### PR DESCRIPTION
**Pull request by aeslaughter**
closes #15913

### CODE REVIEW

**Review by zachmprince — APPROVED** [review]
Do we need an issue for this?

**Comment by zachmprince** [comment]
Just created one.

**Comment by aeslaughter** [comment]
I have a fix for Grizzly waiting. If Grizzly is the only thing that fails then this can be merged and I will update the submodule in Grizzly.

**Comment by zachmprince** [comment]
Okay, I will look through the testing in the morning and merge if everything checks out

**Pull request merged**
