### PR TITLE
Deprecated all MeshModifiers

### PR DESCRIPTION
**Pull request by permcody**
I started converting tests over. We have several dozen. It's a time consuming task that I don't have time for right now. Since we can't remove all tests (since we have several that are testing the MeshModifiers themselves, I'll leave it for now - bye bye green deprecated badge).

### CODE REVIEW

**Comment by YaqiWang** [comment]
It will be nice if we can start supporting the following syntax:
```
[Mesh]
  [skewedcube]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 3
    ny = 3
    nz = 4
    bias_x = 2
    bias_z = 0.5
  []
[]
```
instead of
```
[MeshGenerators]
  [skewedcube]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 3
    ny = 3
    nz = 4
    bias_x = 2
    bias_z = 0.5
  []
[]
[Mesh]
  type = MeshGeneratorMesh
[]
```
I guess we can provide a script to convert all input files.

**Comment by permcody** [comment]
Yes, The syntax will evolve. I agree that we should support `MeshGenerators` in the `Mesh` block.

**Comment by friedmud** [comment]
I don't see any need for `[MeshGenerators]` to be in the `[Mesh]` block... I think the `[Mesh]` block can just be omitted when using generators (we should just automatically use `MeshGeneratorMesh`).

The current way it's set up is because I haven't had time to do anything beyond getting it all working.

**Review by friedmud — APPROVED** [review]
👍

**Comment by YaqiWang** [comment]
Another thing is that when we remove `BlockDeleter` mesh modifier, it could be better to rename `BlockDeleterGenerator` to `BlockDeleter`. I think it is better to use `[Mesh]` instead of `[MeshGenerators]`. Of course, I am talking about the end goal.

**Comment by permcody** [comment]
Renaming some of the Generators is a good idea. One thing at a time though!

**Pull request merged**
