### PR TITLE
New turbine

### PR DESCRIPTION
**Pull request by freytp**
Create TurbinePressureRatioEfficiency1Phase component for the thermal_hydraulics module

### CODE REVIEW

**Comment by joshuahansel** [comment]
@freytp So it looks like you've basically copied and pasted `ShaftConnectedCompressor1Phase` and removed that `treat_as_turbine` parameter, right? If so, this is definitely ripe for some refactoring with inheritance. There should be a common base class for the two components, maybe called `PressureRatioEfficiency1PhaseBase` with a virtual method that gets overridden by the base classes that does the `treat_as_turbine` thing. Let me know if you need further help with it - I'm not sure on your experience with this kind of stuff.

**Comment by freytp** [comment]
@joshuahansel Yeah that's what happened, Lise had me do this as an exercise to see first hand everything involved with making a component in THM. I would appreciate a discussion on how to move forward with the base class since this is my first time doing this

**Comment by joshuahansel** [comment]
@freytp I remember having a discussion with you offline, but it probably wasn't enough to help you. If you want to finish this, I can help. Otherwise Lise and I could finish it.

**Comment by joshuahansel** [comment]
I'm guessing we still want this... 🪄  UNSTALE-IOSO!

**Pull request closed without merging**
