### PR TITLE
Delete ParsedFreeEnergyInterface 

### LINKED ISSUE #4714: ParsedFreeEnergyInterface is deprecated
should be removed. This is replaced by the DerivativeFunctionMaterial system.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #4714.

### CODE REVIEW

**Comment by permcody** [comment]
I wonder how many bugs you just fixed? :smiley:

**Comment by permcody** [comment]
BTW - You'll have to rebase this commit before it can be merged.

**Comment by dschwen** [comment]
Rebased.

> I wonder how many bugs you just fixed? :smiley:

Go and look at #4742 rather than make snide comments!!

**Comment by jwpeterson** [comment]
> I wonder how many bugs you just fixed?

:sick: :fire:

**Pull request merged**
