### PR TITLE
Cross-plattform compatibility improvements

### PR DESCRIPTION
**Pull request by dschwen**
This is still work in progress, but I'd like to see how its <s>passing</s> failing the tests.

Refs. #14591

### CODE REVIEW

**Comment by dschwen** [comment]
```
Building and linking hit...
failed to import pyhit - try running "make hit" in the $MOOSE_DIR/test directory.
```

Would it be possible to bet more output at this stage @milljm ?

**Comment by milljm** [comment]
You mean, like "you can try running make, but that seems to never work" sort of stuff? =D

**Comment by dschwen** [comment]
@milljm , it shows that it's building pyhit but the import fails. So something must have gone wrong along the way. I believe I figured it out. Let's see. But I suspected that you hide the hit make output to avoid cluttering up the log.

**Comment by permcody** [comment]
image

**Comment by dschwen** [comment]
The pythit native module is now finally building on *nix and Windows. This unfortunately requires another if statement in the makefile. I'm working on getting the testharness to actually run now. Which I thought should be easy - it's python after all - but has some nasty pitfalls, like running shell commands with pipes from python...

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
So what now, do we need to do Windows testing?

**Comment by dschwen** [comment]
At some point we might want to do that. But we're not there yet. Since we don't officially support Windows I fully expect regressions to happen, but overall this is a big step forward already.

**Pull request merged**
