### PR TITLE
Update libmesh

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:

  - Add a new functor for sync element integers
  - Some cleanup for RB EIM code
  - edgeset/nodeset/sideset unit test refactor
  - More contains_vertex_of optimization
  - Fix distributed p coarsening assertion

@roystgnr wanted to get these in

### CODE REVIEW

**Review by roystgnr — DISMISSED** [review]
We're certain those app failures were unrelated?

**Comment by loganharbour** [comment]
I bet the `contains_vertex_of` changes could have caused a failure in mockingbird... I'll look into it.

**Comment by lindsayad** [comment]
I'm glad somebody expanded the checks 😅

**Comment by YaqiWang** [comment]
If we can bring this small change https://github.com/libMesh/libmesh/pull/2960 in this update, it will be great.

**Comment by roystgnr** [comment]
Yeah, we should update to that point.  We're being delayed by the Mockingbird regression anyway, which looks to be something real and which is going to take longer to investigate.

**Comment by lindsayad** [comment]
converting this to draft to ensure no merging until we've figured out Mockingbird

**Comment by roystgnr** [comment]
Let's update to the latest master while we're at it?  libMesh/libmesh#2960 is merged now.

**Comment by lindsayad** [comment]
I will definitely update but I figured I would wait for the conclusion of the Mockingbird investigation to avoid triggering 65 recipes potentially unnecessarily

**Comment by loganharbour** [comment]
Go for it. I think the issue is frustratingly unrelated.

**Review by loganharbour — DISMISSED** [review]

**Comment by lindsayad** [comment]
@roystgnr anything else crop up that you want to wait for?

**Comment by milljm** [comment]
@lindsayad I broke the dependencies with moose-libmesh and moose-tools with an old libnetcdf requirement... Please hold (unfortunately)

**Comment by roystgnr** [comment]
Nothing else going into libMesh soon enough and urgently enough to delay this further, no.

**Review by milljm — DISMISSED** [review]
Aside from Python 3.9 failures for a few python unit tests, and mastodon install failures. This is ready to go as far as Conda packaging is concerned.

**Review by milljm — DISMISSED** [review]
👍

**Comment by loganharbour** [comment]
Good now. Hopefully we can get this in ASAP.

**Comment by lindsayad** [comment]
Are these End User Experience failures to be expected?

**Comment by loganharbour** [comment]
Nope... working on it

**Review by milljm — APPROVED** [review]
👍 
hurry up and pass...

**Comment by YaqiWang** [comment]
Strange, why we did not see the compiling error here like in here: https://moosebuild.hpc.inl.gov/job/348553/.

**Comment by roystgnr** [comment]
Assuming it's not too revealing, can you copy the compilation error here?  I get "You are not allowed to see results. Please sign in to an appropiate user." while logged in via my INL HPC account, so I guess I'm not whitelisted for Griffin.

**Comment by loganharbour** [comment]
Yaqi and I discussed this last night - I believe there was indeed an issue and PR successfully made for it.

**Comment by YaqiWang** [comment]
That link is the test results for a MR in Griffin. Looks like we have been failing Griffin devel branch for a while, the code having the compiling error did not make to master branch, which is what this libMesh update test against. I will fix it and bring Griffin master up to date. The compiling error is due to the functor I added in libMesh but I have the exact same one in Griffin as well.

**Pull request merged**
