### PR TITLE
Add a clear_extremes option to ErrorFractionMarker

### LINKED ISSUE #9914: ErrorFractionMarker Enhancement
## Rationale
Currently, ErrorFractionMarker always computes a new `max` and `min` error every iteration.  It would be good to be able to have these be "static" for some problems... especially for steady state.

If doing a steady state calculation the current formulation for ErrorFractionMarker will essentially always find _something_ to refine... because the max error is a moving target.  As you refine the mesh the max error gets smaller which means that there are always some elements within the tolerance of the max error.

## Description
I propose adding a `clear_extremes` option to ErrorFractionMarker that will default to `true` (the current behavior).  In the case where it is `false` the extremes will be the running extremes ever encountered in the solve.

## Impact
No impact (the default will stay the same)

### PR DESCRIPTION
**Pull request by friedmud**
Just adding an option to EFM.

closes #9914

### CODE REVIEW

**Comment by friedmud** [comment]
Why am I failing a clang-format here?  I have all the hooks setup... clang-format on my machine reformatted that line already.

Is this the case where you have to run clang-format multiple times?

**Comment by permcody** [comment]
I doubt it. We rarely encounter that. Possibly a different version of the
compiler? Make sure your clang format file is correct and being picked up.

**Comment by friedmud** [comment]
My stuff is all new (just installed during tiger team):

```
[gastdr][~]> clang-format --version
clang-format version 3.9.0 (tags/RELEASE_390/final)
[gastdr][~]> which clang-format
/opt/moose/llvm-3.9.0/bin/clang-format
```

It's definitely picking up the style file - because everything is getting reformatted all the time.

**Comment by friedmud** [comment]
Running `git clang-format a4c8e36d4a46ed27d5c2cba5afc5dc7d67851270` _does_ change it to what Civet wants... it looks like it really is that case where you have to run it twice...

Original:
```
  params.addParam<bool>("clear_extremes", true, "Whether or not to clear the extremes during each error calculation. Changing this to `false` will result in the global extremes ever encountered during the run to be used as the min and max error.");
```

After saving:
```
  params.addParam<bool>(
      "clear_extremes", true, "Whether or not to clear the extremes during each error calculation. "
                              "Changing this to `false` will result in the global extremes ever "
                              "encountered during the run to be used as the min and max error.");
```

After manual clang-format:
```
  params.addParam<bool>("clear_extremes",
                        true,
                        "Whether or not to clear the extremes during each error calculation. "
                        "Changing this to `false` will result in the global extremes ever "
                        "encountered during the run to be used as the min and max error.");
```

Bummer

**Comment by friedmud** [comment]
Just a question: why is this "Failed But Allowed"?

All tests have passed perfectly... and this is a tiny change that doesn't change any defaults.  I can't see how this caused any "failure".

**Comment by permcody** [comment]
Right, which is why you need to look at the test result details. GitHub
only has pass and fail but we have a few targets that are "allowed to
fail". Until we added that label we missed that case 99% of the time
because the Github status has to be all green.

Redback is failing. It's not valgrind clean and it doesn't seem to be high
enough on Thomas's list to fix it. We've skipped several tests but they
continue to fail randomly with the current state of that app. I think I
will have Brian remove it from the "tested apps" list on Monday until it
has been rewritten and cleaned up. You might check to make sure there
aren't any other failures.

**Review by permcody — APPROVED** [review]

**Pull request merged**
