### PR TITLE
Geochemistry: tests now pass in parallel

### LINKED ISSUE #16337: Prepare geochemistry module for parallel testing
## Reason
@WilkAndy requested geochemistry to be tested in parallel and with threads. 

## Design
@WilkAndy please create a PR that allows the parallel tests to pass. I've created a temp recipe `(meowbuild) Partial Modules Parallel Test` that you can add to your PR to test. Once you get it passing, I'll replace the default parallel modules test with said recipe. See https://civet.inl.gov/job/635970/ for the failure.

## Impact
More test coverage.

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #16337

### CODE REVIEW

**Comment by loganharbour** [comment]
@WilkAndy I went ahead and added the new modules test with geochem.

Once this turns green, I will switch around the recipe so that it runs on all tests and then merge this.

**Comment by WilkAndy** [comment]
> @WilkAndy I went ahead and added the new modules test with geochem.
> 
> Once this turns green, I will switch around the recipe so that it runs on all tests and then merge this.

Thanks @loganharbour

**Comment by loganharbour** [comment]
Parallel test looks great @WilkAndy. Thanks for doing this - we should really be getting all the modules tested in parallel if possible.

Will merge once it's all green and I get the new recipe moved over.

**Comment by WilkAndy** [comment]
> Parallel test looks great @WilkAndy. Thanks for doing this - we should really be getting all the modules tested in parallel if possible.
> 
> Will merge once it's all green and I get the new recipe moved over.

Yea, i'm glad to get this done.  I had forgotten that this threads+parallel recipe even existed.  Perhaps there are a lot of other recipes i should be testing against.  Perhaps it'd be good to publish a list of what module is tested against which recipe, so modules developers can aim for 100% recipe coverage.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
