### PR TITLE
Merging Solid and Tensor Mechanics #5624

### PR DESCRIPTION
**Pull request by permcody**
Rebasing the PR from @sveerara for merging #5625

### CODE REVIEW

**Comment by jwpeterson** [comment]
@permcody, this branch failed the devel_to_master app tests in BISON and is now holding up other devel-to-master merges.  This seems like a really big change, was this sufficiently tested by someone other than @sveerara?  @bwspenc, can you or someone else take a look at what's up with BISON on MOOSE devel?

**Comment by permcody** [comment]
Yes it failed and the patch was already put into Bison and merged. There
was a large discussion about this action involving several people including
bisoners and marmoters so I think it's fine. There is no holdup the next
thing to be merged should be successful.

**Comment by jwpeterson** [comment]
Marmot also failed because of this, although @dschwen claims to be fixing it.

**Comment by dschwen** [comment]
_"Claim"_ to be fixing it! Cannot trust these germans...

**Pull request merged**
