### PR TITLE
Add new solver options for the moose adaptive input file

### PR DESCRIPTION
**Pull request by lindsayad**
Refs libMesh/libmesh#1986

@friedmud @aeslaughter

### CODE REVIEW

**Comment by lindsayad** [comment]
So talking with @fdkong one way to solve the non-symmetric constraint issue could be in the solver. E.g. a naive way to solve the problem would be to create a P = (A + A^T) / 2. Note that non-symmetric constraints from AMR is an issue encountered by others as well. See this PETSc [thread](https://lists.mcs.anl.gov/pipermail/petsc-users/2016-February/028598.html).

Or we can still consider reverting libMesh/libmesh#1986. If we're more of that mind, then it might be better perhaps to add an option like `force_symmetric`.

**Comment by aeslaughter** [comment]
Requiring a change in solver options when enabling AMR seems wrong to me, we already have problems with how long it takes to perform refinement loops, now we need to have special preconditioning.

For the short-term adding a flag of some sort should be fine, but we will need a good explanation in the slides of why all of a sudden we enable this option.

**Comment by aeslaughter** [comment]
Just something else to consider that might be involved, for this problem the initial condition is set to 300, but the BC on the left is 350. So, there is a huge jump at the first timestep and in my current AD version there is some solution oscillation in the first few timesteps that get corrected as time progresses. 

If I have time next week I was going to add a ramping function BC to see if I can get rid of this behavior.

**Comment by fdkong** [comment]
I am actually surprised that a small symmetric  change made BoomerAMG fail, and it has to be related something we do not completely understand yet. 

Alex's old changes in libmesh are definitely right (in my opinion) since the residual function and the Jacobian function are consistent.  A short-term fix  is to let libmesh support both Jacobian matrix and preconditioning matrix. For a long-term fix, we should look into BoomerAMG to figure out why this small change makes the solver fail. 

@lindsayad

**Comment by lindsayad** [comment]
So we know that algebraic multi-grid should be able to tackle asymmetries, so we hypothesized that the problem must be elsewhere. And indeed decreasing the uniform refine to 1 and running with `-pc_type svd -pc_svd_monitor -ksp_view_pmat` we get this output:
```
Time Step 1, time = 0.1, dt = 0.1

 0 Nonlinear |R| = 1.058383e+04
      SVD: condition number 5.549818770971e+11, 0 of 854 singular values are (nearly) zero
      SVD: smallest singular values: 1.691378326413e-10 6.676454725932e-10 1.467227192042e-09 2.515781490780e-09 3.732254422574e-09
      SVD: largest singular values : 9.293896253354e+01 9.328633619846e+01 9.355749175262e+01 9.375169816516e+01 9.386843184740e+01
      0 Linear |R| = 1.058383e+04
      1 Linear |R| = 2.702731e-01
      2 Linear |R| = 1.433114e-06
Mat Object: () 1 MPI processes
  type: seqaij
row 0: (0, 1.)  (2, 0.)  (4, 0.)  (6, 0.) 
row 1: (1, 1.)  (3, 0.)  (5, 0.)  (7, 0.) 
row 2: (0, 8.01567e-10)  (2, 1.52538e-08)  (4, -7.2221e-09)  (6, -4.8174e-09)  (8, 8.01567e-10)  (10, -4.8174e-09) 
row 3: (1, 0.321786)  (3, 1.44054)  (5, 1.15436)  (7, 0.25024)  (9, 0.321786)  (11, 0.25024) 
```
So we have a large condition number (1e11) and if we look at the pressure variable (rows 0 and 2) we can see that while we are putting unity on the diagonal for dirichlet boundary conditions, the magnitude of our other residuals (coming from the physics) is order 1e-9 because of material properties. If we scale the physics residuals of the pressure variable by 1e9 then boomeramg runs beautifully.

So we can safely close this.

**Pull request closed without merging**
