### PR TITLE
Limit peacock/chigger tests to linux (for now)

### PR DESCRIPTION
**Pull request by aeslaughter**
There is currently a bug in VTK on conda when writing PNG files: https://github.com/conda-forge/vtk-feedstock/issues/109.

Eventually, part of restoring this should be to use offscreen, software rendering with osmesa. But, for now we need to get things working so conda work can continue.

### CODE REVIEW

**Comment by aeslaughter** [comment]
@rwcarlsen Can you help be put a new line at the end of the hit files? I can't find the correct place.

**Comment by aeslaughter** [comment]
@milljm 

If I use vtk=8.1.2 with python=3.7, then I don't get the libpng error.

**Comment by aeslaughter** [comment]
vtk=8.2 also works with python=3.7

**Comment by rwcarlsen** [comment]
Just saw this - are you still trying to figure out newlines or did you get it fixed?

**Comment by aeslaughter** [comment]
@rwcarlsen I moved it to another PR: https://github.com/idaholab/moose/pull/14966/commits/cc051110c0e0ab56a6ceb0fd273318b803d9774f

**Comment by aeslaughter** [comment]
This is getting close to cleaning up peacock/chigger stuff. There is an image size problem on linux that I am working to figure out.

**Review by milljm — APPROVED** [review]
Looks fine to me!

**Pull request merged**
