### PR TITLE
Full Makefile control of disabling/enabling modules!

### PR DESCRIPTION
**Pull request by permcody**
Dynamic modules. You can turn them on/off through the Makefile without code changes. This should be compatible with all apps but I'll want to patch them to use this dynamic approach (using the module_loader).

### CODE REVIEW

**Comment by friedmud** [comment]
Noted

**Comment by friedmud** [comment]
@permcody can you detail the changes that would be needed in an end-user's application?

I'd like to modify my own to see how it works...

**Comment by permcody** [comment]
Just make sure your application looks like the original stork file:
https://github.com/idaholab/stork/blob/master/src/base/StorkApp.C.app#L22-L28

If you've dumped the `ModulesApp` calls and registered individual modules, you need to undo that. That's it!

Once you've done that, you should be able to use the normal MOOSE Makefile syntax to enable/disable modules:

```
SOME_MODULE    := yes
OTHER_MODULE  := yes
```

The way it works is I dynamically generate a new suffix for your particular combination of modules. If you compile several different apps you could potentially have several different object file names built from the same source file (located in the new "module_loader" directory).

**Comment by friedmud** [comment]
Is there any chance of those generated files colliding?

The generated files are one of the things bothering me here.  One thing
that it means is that MOOSE can't ever be put anywhere that the user
doesn't have write permission (i.e. "installed").  I know that we currently
discourage that... but I know that several places do it anyway...

I'm ok with disallowing that... but we should be clear about the
consequences.

Derek

**Comment by friedmud** [comment]
The generated files also just feel a bit brittle.  Will they automatically be updated if they get out of date?

**Comment by permcody** [comment]
Maybe I'm not being clear. It's not a generated source file. It's just an object file with a special suffix. Compile your app and then look in the `modules/module_loader/src` directory and you'll see one. Compile BISON or some other app and you may see another. They won't collide.

modules_with_tm_hc_misc.o 
modules_with_tm_pf.o

Each one names exactly which modules are turned on. Since the app.mk file generates that dependency like any other dependency, they won't go out of date. If you need a combination that isn't there. That name is "generated", then the file is compiled with that name and is linked in like any other object file.

**Comment by friedmud** [comment]
Right - what if `modules/module_loader/src` is not writeable by the user...

**Comment by permcody** [comment]
Then MOOSE wouldn't compile? I guess you are talking about a multi-user cluster installation. Hmm, we could probably come up with a solution for that. It's already a special rule so I suppose the destination for the object file, *.d, and *.lo files could be in some user defined location. That would be easy to add.

**Comment by permcody** [comment]
BTW - We (you included) actively discourage that model for development all the time.

**Comment by friedmud** [comment]
Absolutely!  I definitely discourage it!

It's just something that came to mind when I saw the generated files.

Is there any possibility of generating it within the App's directory that you're compiling?  That would make me feel better about it.

**Comment by permcody** [comment]
Anything is possible, but that would require additional lines in the app.mk file. The cool part about this is that the module_loader basically just looks like any other app right now so it uses all of the existing rules. To move the generated files, we'd have to add new variables or new rules for that case.

BTW - The existing method doesn't break with this. If BISON wants to leave their application alone and just have it register modules directly, that will always work, and is probably better anyway for stable applications. This capability is more for new users or those that just want to play around without the core team help.

I'd suggest that we don't worry about generating those files elsewhere for now. If by chance some user contacts us, and really wants to use a pre-installed MOOSE and can't change that, we can either add this capability then or just convert their app to the existing registration method.

**Comment by friedmud** [comment]
Sounds good.

That was essentially my only issue... do you think this is mergeable at this point?

**Comment by permcody** [comment]
Yeah it's mergable. My only potential issues are all the nasty edge cases with `make clean` and `make clobber`. I'll have to run it through the paces and may have a few tweaks to getting that all right, but I'm confident that it works for the normal cases. I compiled several applications on my system and had about a half dozen different variations on my system. I probably won't switch over BISON, or MARMOT to the new system so really we won't see much impact but it'll really help out new stork users. I'll write up some information about how to turn modules on/off.

**Review by friedmud — APPROVED** [review]
I like it - with a small reservation about the generated object files.

**Pull request merged**
