### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by dschwen**
Refs #8233

### CODE REVIEW

**Comment by WilkAndy** [comment]
Thanks for the changes to the plastic tensor_mechanics stuff.

**Comment by jwpeterson** [comment]
Two things:
* Your commit metadata is messed up: "Daniel Schwen <Daniel Schwen>"
* I don't think your commit triggered this error, but would you mind also fixing the "thh" typo in it:
```
materials/types.except1: *** ERRR ***
materials/types.except1: MaterialStdVectorAux.  selected_qp specified as 10 but there are only 4 quadpoints in thh element
```

**Comment by jwpeterson** [comment]
> That typo... does not exist! WTF?!

Maybe someone already fixed it... maybe it's two threads writing at the same time?

**Comment by dschwen** [comment]
Must be a threading output issue. I checked the blame and the error was never there.

**Comment by dschwen** [comment]
Oh, come on!!!

Mammoth fail:

```
godiva.test: *** ERROR ***
godiva.test: ***** Invalid Object: ComputeThermalExpansionEigenStrain *****
godiva.test: Expired on Mon Dec 19 01:00:00 2016
godiva.test: Update your application using the 'ComputeThermalExpansionEigenstrain' object
```

Ping @YaqiWang

**Comment by YaqiWang** [comment]
That has been fixed by @brianmoose . The new test will probably pass.

**Comment by YaqiWang** [comment]
Yes, we noticed this and a fix has been sent in Rattlesnake requiring Sebastian's review. But Sebastian is on PL... Let me ask another developer to review and merge it. Sorry about this.

**Comment by dschwen** [comment]
Yeah, the Rattlesnake test timed out again. I suggest ignoring it for now. Can somebody review this PR?

**Comment by YaqiWang** [comment]
That time-out can be ignored. It will take a hour or two to make that MR into Rattlesnake master. Or we can try testing again to see if you get lucky this time.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
