### PR TITLE
Re-enable ElementsAlongPlane with DistributedMesh

### PR DESCRIPTION
**Pull request by roystgnr**
This restores more #1500 test cases.

The code here actually works with any number of processors; we just need to turn of mesh renumbering to make sure CSV results from unit tests match.

### CODE REVIEW

**Comment by roystgnr** [comment]
That's baffling.  I can't replicate those failures myself.

Maybe there's some unexpectedly-relevant bugfix in my version of libMesh that hasn't been merged into the MOOSE version yet?  We can try kicking these tests again after the next libMesh update.

**Comment by permcody** [comment]
No need to wait, update the libMesh hash in your PR and CIVET will check it out and build it. At lot of times we wait to do libMesh updates until there is a reason, you may give us one.

**Comment by roystgnr** [comment]
Wait, wait - the tests are passing in debug mode?  That's actually all I've been running locally.  Let me see if this is a heisenbug I can replicate.

**Comment by roystgnr** [comment]
No, everything works for me in opt mode too.  Maybe there's something intel-specific wrong?

**Comment by permcody** [comment]
Highly likely, Intel is the bane of our existence. Anything we can do to help? If you have a token, we can always get you a login. 

It's just the element IDs that change but maybe since you are working on DistributedMesh that is the field of interest?

**Comment by roystgnr** [comment]
Rebased and cherry-picked #9276.  We should merge the latter first, and then drop that commit from here.

**Comment by roystgnr** [comment]
It looks like the earlier failures were probably red herrings fixed by https://github.com/libMesh/libmesh/pull/1360 - not an Intel compiler problem, just an undefined-code-happening-to-work-sometimes problem.  This should be good to merge.

**Review by permcody — APPROVED** [review]

**Pull request merged**
