### PR TITLE
Only do Material related setup activities if there are Materials

### LINKED ISSUE #7221: Only do Material setup tasks when Materials exist
### Description of the enhancement or error report
`FEProblem::initialSetup()` currently does quite a few Material setup related tasks (including a whole element loop!) even when there are no Materials present in the system.  This should be rectified.

### Identified impact
If done properly there should be zero impact (other than faster startup times).

### PR DESCRIPTION
**Pull request by friedmud**
closes #7221

### CODE REVIEW

**Comment by friedmud** [comment]
@YaqiWang can you comment on why Yak would fail with this change?

**Comment by YaqiWang** [comment]
The failing does not make sense. Logically the change is simple and nothing related with the failing test. It seems something can be easily fixed. Can you generate a backtrace for that segfault really quick?

**Comment by YaqiWang** [comment]
@snschune might have some better idea because that is his test.

**Comment by snschune** [comment]
@friedmud Looking at the test and the code, I don't see it right away; would have to compile in debug.  
I won't get to it till tomorrow morning European time though, which is probably still earlier than you.

**Comment by permcody** [comment]
Wait! Are you on vacation?

**Comment by snschune** [comment]
No, I am resolving Visa issues...so I am _not_ on vacation.

**Comment by friedmud** [comment]
Yikes!  Well - if you could take a look I would appreciate it!  I couldn't
see a connection myself... so I'm suspecting that there is a side-effect
that's being relied on...

**Comment by snschune** [comment]
Yeah, will do.

**Comment by snschune** [comment]
I tracked it to `fe_boundary::reinit` and it appears that `this->qrule` is `NULL`. It would trip this assert:
`libmesh_assert (this->qrule != libmesh_nullptr || pts != libmesh_nullptr);`

I am still looking into it, but if you know right away where this is usually initialized, please chime in.

**Comment by snschune** [comment]
A temporary fix is in under Yak MR #569.

**Comment by friedmud** [comment]
Thanks so much @snschune !  Does that mean that this PR is mergeable... or should we wait for that MR to get merged into Yak?

**Comment by snschune** [comment]
Well, it's being tested right now (but not against this particular branch). If the yak MR doesn't come through quick enough, there might be issues. What would happen in that case? I guess the Moose submodule wouldn't be updated automatically when the devel branches are tested against each other? 

It depends on how urgent this is for you.

**Comment by friedmud** [comment]
Nah - not urgent - just checking.

Just let me know when it gets merged, please.

Thanks again!

**Comment by YaqiWang** [comment]
Patch in Yak by @snschune has been merged. I invalidated the failing test. After it passes, this should be ready.

**Comment by friedmud** [comment]
Great!  Thank you both!

**Pull request merged**
