### PR TITLE
Feb. News

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #11446)

@idaholab/moose-ccb Please add your work.

### CODE REVIEW

**Comment by permcody** [comment]
I don't have anything unless we want to announce our NQA-1 audit findings. That was technically done in February though.

**Comment by lindsayad** [comment]
I'm curious about those...

**Comment by permcody** [comment]
@aeslaughter - Go ahead and give this another look. You can merge it if you think it's ready.

**Review by permcody — DISMISSED** [review]

**Review by cticenhour — APPROVED** [review]

**Comment by permcody** [comment]
Hmm - we probably should have proof read this one more time. There are several grammar errors in the last section.

**Pull request merged**
