### PR TITLE
Add AD version of radiative heat flux bcs

### PR DESCRIPTION
**Pull request by andrsd**
Refs #13053

### CODE REVIEW

**Comment by dschwen** [comment]
No `template <bool is_ad>`? That's a lot of code duplication.

**Comment by andrsd** [comment]
I changed the API in `ADRadiativeHeatFluxBCBase ` from `virtual Real coefficient() const = 0;` to `virtual ADReal coefficient() const = 0;`, but I guess I could template that.

**Comment by dschwen** [comment]
In case no Generic (base) class exists you can use `std:: conditional``.

**Comment by andrsd** [comment]
The generic class does not exist, but it seems it should, so I will build one. I seems to be a cleaner approach than the conditional.

**Comment by andrsd** [comment]
@dschwen I asked for your review since you made the initial comment on templating.

**Review by dschwen — APPROVED** [review]
Looks good to me

**Comment by andrsd** [comment]
Thanks!

**Pull request merged**
