### PR TITLE
TimedPrint Enhancements

### PR DESCRIPTION
**Pull request by permcody**
In addition to only printing on the first rank this PR "enhances" the screen output of TimedPrint.
Namely, we now get wrapping for very long timers so that they don't go off the screen indefinitely.
Next, when activated, timing information is printed out to the right when the task is finished (column aligned)
Finally, color is added to highlight the time (can't see that in this sample, but it's there)
```

Uniformly refining mesh ....................................................               [ 53.18 s]
Initializing equation system .............................................................
.............................................                                              [107.88 s]
Caching mesh information .........                                                         [ 10.36 s]

Framework Information:
MOOSE Version:           git commit eb31e4bc56 on 2019-06-24
LibMesh Version:         82a1cfa7e84f28c361a0ee7b59dcc99c67e11425
PETSc Version:           3.10.5
Current Time:            Mon Jun 24 16:19:45 2019
Executable Timestamp:    Mon Jun 24 12:52:30 2019

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   
    Total:                 6558721
    Local:                 6558721
  Elems:                   
    Total:                 6553600
    Local:                 6553600
  Num Subdomains:          1
  Num Partitions:          1

Nonlinear System:
  Num DOFs:                6558721
  Num Local DOFs:          6558721
  Variables:               "u" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 

Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    hypre boomeramg 

Caching mesh information ......                                                            [  7.18 s]
Projecting initial condition .........                                                     [ 10.20 s]
Outputing exodus ....................                                                      [ 21.36 s]
Computing initial residual ............................                                    [ 29.24 s]
 0 Nonlinear |R| = 5.060632e+01
      0 Linear |R| = 5.060632e+01
      1 Linear |R| = 2.119692e+00
      2 Linear |R| = 1.200934e-01
```

### CODE REVIEW

**Comment by permcody** [comment]
@friedmud - any comments on this? Should be ready..

**Comment by friedmud** [comment]
I like all the enhancements (especially the time).

I'm not in a place to try this out right now - but I'll check it out tomorrow when I'm in the office.

**Comment by permcody** [comment]
> (7 days ago) but I'll check it out tomorrow when I'm in the office.

Haha - the comment of death from Derek...

**Comment by permcody** [comment]
@fdkong - Care to review and merge?

**Review by fdkong — APPROVED** [review]

**Comment by fdkong** [comment]
Looks good for me

**Pull request merged**
