### PR TITLE
Destroy the mesh only after the problem using it

### PR DESCRIPTION
**Pull request by roystgnr**
The FEProblem class contains System, DofMap, etc. objects which may
try to perform cleanup on their underlying MeshBase during their own
destructors, so the mesh should continue exist until that destruction
is done.

This should fix the bug noticed in
https://github.com/libMesh/libmesh/pull/1064 and resolve the issue
reported in https://github.com/idaholab/moose/issues/7562

"make test" appears to be working again for me even with the modified libMesh.

### CODE REVIEW

**Comment by roystgnr** [comment]
Hmm... I'm actually still getting some test failures with the modified libMesh.  I'll look into those further.

**Comment by roystgnr** [comment]
At least now it's a handful instead of every single test...

**Comment by roystgnr** [comment]
If we're getting a failure in a Bison unit test with the current Moose libMesh version then that's much more serious, but I can't see any way this patch could cause that exodiff...

**Comment by roystgnr** [comment]
Okay.  I've hunted down the source of other libmesh-branch-based failures, and that'll be another "delete pointers in a different order" fix in Moose that I'd like to merge along with this branch, but I'll wait until the Bison tests repeat before I push.

**Comment by permcody** [comment]
👍

**Pull request merged**
