### PR TITLE
Removing name and making parameters const in a variety of classes

### PR DESCRIPTION
**Pull request by aeslaughter**
This is some work in preparation for #4604 and #4606.
- changes `InputParameters &` to `const` and removes 'name' from some, not all interface classes 
- adds a MooseObjectID that we will need for #4606

### CODE REVIEW

**Comment by permcody** [comment]
I don't like this. Communication between related interfaces could be handled via a common object pointer for which they are instantiated. However, if two interfaces really need to exchange information then perhaps they really shouldn't be independent. We should consider a new design instead of adding a shim class. What are the implications of combining block/boundary restrictable? Is there ever a case when we are allowed to restrict by both block and boundary? Aren't they always exclusive for a given object? If it is OK to combine those two interfaces and you still need to get information to a 3rd interface (MaterialPropertyIO), you should simply be able to do accommodate that directly through the `*this` pointer.

**Comment by aeslaughter** [comment]
I don't want to combine Block and Boundary restrictable, since objects can be one or the other, or both. If then where combined there would be a whole slew `if` statements and a bunch of hasBoundary type stuff that doesn't mean anything to a class that can not be boundary restricted.

**Comment by aeslaughter** [comment]
Are you saying to do casting of `this` to the various objects and store the data in the objects? If so, I didn't think of trying that.

**Comment by permcody** [comment]
Right, you'd pass `*this` in the construction of those two objects so that they could reference the `MooseObject` that they are attached to and also each other if needed.

**Comment by aeslaughter** [comment]
Implemented a better block/boundary material interface communication scheme, just pass the std::set they need.

**Comment by permcody** [comment]
:+1:

**Pull request merged**
