### PR TITLE
Remove spaces from phase_field docs

### PR DESCRIPTION
**Pull request by permcody**
refs #7409

### CODE REVIEW

**Comment by dschwen** [comment]
Whywouldyouremoveallthosespacesfrommyphasefielddocs?

**Comment by sapitts** [comment]
Have you checked this against Bison to make sure that the Bison docs will build successfully with this change? Please?

**Comment by permcody** [comment]
Oh wow - look at you two! Immediately jumping all over this PR. I did this so that it would render. Right now, most of the phase-field docs don't render. Yes, I'll try BISON out as soon as I figure that out.

**Comment by brianmoose** [comment]
FYI, I added an optional Civet recipe for MOOSE called "Application Documentation" that builds Bison and Mastodon documentation against the MOOSE PR.

**Comment by sapitts** [comment]
Thank you @brianmoose!

**Comment by aeslaughter** [comment]
I will fix this up.

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
