### PR TITLE
Remove RealPropertyOutput

### LINKED ISSUE #5347: Remove RealPropertyOutput

### PR DESCRIPTION
**Pull request by aeslaughter**
We don't need this anymore
(closes #5347)

### CODE REVIEW

**Comment by friedmud** [comment]
Cool that you didn't need to regold!

However, in the long-run... do you think it would be better to go ahead regold these now?  One thing I worry about is people using these as examples... and the bits about outputting elemental as nodal are going to get copied everywhere....

**Comment by aeslaughter** [comment]
I don't think it is necessary to re-gold, but also wouldn't mind changing
the them either. I do like that it exercises the elemental to nodal
projection a bit more. I am particularly intrigued by the example that
required second order monomials, I didn't even know that worked for aux
variables.

**Comment by permcody** [comment]
There are open issues with higher order monomials but Yaqi uses them quite a bit. Something isn't quite working right with the projection but nobody has had anytime to dig into it yet.

**Comment by friedmud** [comment]
Really?  I tried them a while ago and everything seemed to be fine.  Is there an open ticket somewhere?

As for why one "required" second order monomials it's because the material property isn't constant on the element.  The function used for the material property value is `t * x * y` which can be perfectly represented by a second order monomial.

**Comment by permcody** [comment]
I believe the monomials themselves are fine. It's just the projections for
output purposes. Last time I tried projecting a higher order monomial I
couldn't get libMesh to _not_ change the basis to nodal for higher
monomials. No, it wasn't the output as nodal parameter, I also tried
messing with the code in our project solution directly but still received
the same result. I only had about 30 mins at the time so it might still be
something simple, just haven't figure it out yet.

https://github.com/idaholab/moose/pull/4996

Projecting to a nodal basis can be arbitrarily bad. It's fairly easy to
build a problem where sampling at the nodes can completely miss the
intended feature you're trying to capture.

**Comment by friedmud** [comment]
Ah yes - You are quite right about that.  I forgot about that issue.

Is there anything else we want to discuss on this PR?

:+1:

**Pull request merged**
