### PR TITLE
move porousFlow dirac kernel setup out of constructor and into initialSetup

### LINKED ISSUE #20506: PorousFlowLineGeometry does not work with transferred reporters
## Reason
The set-up for PorousFlowLineGeometry is done in the constructor so coordinates being transferred in from reporters won't be available.  This is mostly a problem when the data is coming from a multiapp transfer. 

## Design
Move the setup into intialSetup.  Add error check that data is being transferred.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #20506

### CODE REVIEW

**Review by WilkAndy — CHANGES_REQUESTED** [review]
I think we need an exception test that triggers that "no points" error

**Comment by lynnmunday** [comment]
> I think we need an exception test that triggers that "no points" error

@WilkAndy I was hitting this no points exception in falcon where we have a reporter that projects a point onto the closest node with in some tolerance.  When it doesn't find a node within that tolerance, it is empty and the porousFlowLIneSource that was getting data from that reporter was segfaulting. I've added a test for this error and one that I put in previously without testing.

**Review by WilkAndy — CHANGES_REQUESTED** [review]
This all looks great, thank you.  But i'm confused: i thought the PorousFlow Diracs could already accept a reporter?   I'm running late for an appointment - maybe you can answer before i figure it out myself!

**Comment by lynnmunday** [comment]
I made the change to allow these dirac kernels to take reporter values about 2 weeks ago.  I am using those reporter dirac kernels in the loosely coupled DFN-matrix simulations that are using Monte Carlo sampling to place the production location.  In this case, the location of the production well has to be transferred in from another multi-app so the location isn't known during construction of the dirac kernel on the DFN sub-app.  I'm using a reporter that searches for a closest node and it initially empty which leads to a segfault here:
```
  198 	PorousFlowLineGeometry::calcLineLengths()
   199 	{
   200 	  const int num_pts = _zs.size();
-> 201 	  _bottom_point(0) = _xs[num_pts - 1];
   202 	  _bottom_point(1) = _ys[num_pts - 1];
   203 	  _bottom_point(2) = _zs[num_pts - 1];
```

**Comment by WilkAndy** [comment]
> I made the change to allow these dirac kernels to take reporter values about 2 weeks ago. I am using those reporter dirac kernels in the loosely coupled DFN-matrix simulations that are using Monte Carlo sampling to place the production location. In this case, the location of the production well has to be transferred to the DFN sub-app from a main-app so the reporter containing the location is empty during construction. I'm using a reporter that searches for a closest node and it is initially empty which leads to a segfault in these dirac kernel's constructor here:
> 
> ```
>   198 	PorousFlowLineGeometry::calcLineLengths()
>    199 	{
>    200 	  const int num_pts = _zs.size();
> -> 201 	  _bottom_point(0) = _xs[num_pts - 1];
>    202 	  _bottom_point(1) = _ys[num_pts - 1];
>    203 	  _bottom_point(2) = _zs[num_pts - 1];
> ```
> 
> These vectors are empty but will have values once the reporters are executed in initialSetup.

Great, thanks @lynnmunday - for the explanation and the code

**Review by WilkAndy — APPROVED** [review]

**Comment by lynnmunday** [comment]
@loganharbour Andy approved the changes, will you merge it?

**Review by dschwen — APPROVED** [review]

**Review by recuero — APPROVED** [review]

**Pull request merged**
