### PR TITLE
Parallel thermal contact bugfix

### PR DESCRIPTION
**Pull request by bwspenc**

### CODE REVIEW

**Comment by friedmud** [comment]
So, it was a regression after all.  How was this not caught when it was first introduced?

**Comment by bwspenc** [comment]
There was only one test with this non-standard combination of options, and it was set up to be serial-only.

**Comment by bwspenc** [comment]
I should add that the test was set up to be serial-only because it needs to use a direct solve to converge robustly, and at the time, we couldn't use superlu with the testing system.

**Comment by permcody** [comment]
Hmm - we are really starting to get these extended PETSc options embedded in our test suite. We really need a way to figure out if PETSc has been configured with the right combination of options for people who build it themselves or whatever. @WilkAndy reported the other day that all of the superlu tests are failing on his system.

**Comment by bwspenc** [comment]
@permcody Yeah, I was thinking the same thing. Stuff like this shows why it's critical that we test with these options.  We're running almost everything in BISON with superlu or mumps these days, so it's critical that we test with those options, but I agree that it would be good to have a way to turn those tests off.

**Comment by permcody** [comment]
Opened a ticket to capture testing for SuperLU: #6172

**Pull request merged**
