### PR TITLE
FiniteStrainMohrCoulomb removed

### PR DESCRIPTION
**Pull request by WilkAndy**
Also FiniteStrainPlasticBase removed
One test removed

Let's see whether this causes app failures!

Refs #6973

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hi @brianmoose  .  Originally this PR failed because i activated the heavy  tests.  One of them failed due to a reason unrelated to this PR.  I've fixed that test in #7037 , but could we have heavy tests automatically on?

**Comment by permcody** [comment]
I'm not sure we can accommodate this or not. We routinely saturate the
machines during the day with regular jobs. I know it's a different story
during your work day. Maybe we could come up with something...

**Comment by WilkAndy** [comment]
OK, i'll let you all think about it.  the heavy tests are important to me so i regularly activate them but obviously other people don't.  could you schedule period runs or would that even be too intensive?

**Comment by permcody** [comment]
👍

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Pull request merged**
