### PR TITLE
Remove one unnecessary mesh adaptation

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #6925.

Three output tests rely on the old behavior. Do you want me just regold them? Tag @permcody .

### CODE REVIEW

**Comment by permcody** [comment]
I haven't seen the failures, but if they are just simple tests (not physics) and they rely on the old "incorrect" behavior then yes, regolding is the right solution.

**Comment by YaqiWang** [comment]
These are the three tests:
```
outputs/system_info.nonlinear ............................................... FAILED (EXPECTED OUTPUT MISSING)
outputs/system_info.mesh .................................................... FAILED (EXPECTED OUTPUT MISSING)
outputs/system_info.aux ..................................................... FAILED (EXPECTED OUTPUT MISSING)
```

**Comment by permcody** [comment]
All of those tests can definitely be updated. BTW - They don't dump Exodus files so they actually don't need to be "regolded". They just need their respective RegExs updated.

**Comment by YaqiWang** [comment]
Right. I will add one more commit to fix them.

**Comment by YaqiWang** [comment]
BTW, rattlesnake can be easily patched. It has an executioner overriding `preExecute` to inject some evaluations before output on initial.

**Comment by YaqiWang** [comment]
@permcody I think this is ready.

**Comment by permcody** [comment]
OK - waiting on next to be fixed before I review and merge.

**Comment by permcody** [comment]
@YaqiWang - I assume you have patches ready for Rattlesnake?

**Comment by YaqiWang** [comment]
Yes.

**Comment by permcody** [comment]
I'll plan on getting this in after lunch. I need my PR to go in so we can use it in Redcrab today. Thanks for the improvement.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
@YaqiWang - This is in.

**Comment by YaqiWang** [comment]
ok, will send the rattlesnake patch in. Thanks.

**Comment by YaqiWang** [comment]
FYI, rattlesnake has been patched. The patch has got into master branch.

**Pull request merged**
