### PR TITLE
Exodus IsoGeometric Analysis prerequisites

### PR DESCRIPTION
**Pull request by roystgnr**
## Reason

Testing Moose with the upcoming IGA support in ExodusII revealed a few incompatibilities that need to be fixed for that feature to work.

## Design

We now make sure to skip side reinits on 0-D NodeElem elements (which have no sides, but which are critical in C1+ IGA simulations as libMesh uses NodeElem to represent spline nodes and store unconstrained degrees of freedom there).

We now have `RATIONAL_BERNSTEIN` as a selectable nonlinear variable type, so we can actually use IGA basis functions on IGA elements.

We now have the ability to set a restricted `exodus_version` on new Moose tests, so upcoming IGA tests, which require a very recent version of ExodusII to be enabled in libMesh, will be skipped when Moose has been compiled against an older incompatible ExodusII library.

## Impact

New features, no impact to existing use cases.

Refs #18768

### CODE REVIEW

**Review by GiudGiud — COMMENTED** [review]
I'm excited for the new capability!

**Review by GiudGiud — DISMISSED** [review]

**Comment by roystgnr** [comment]
Rebasing for Pronghorn compatibility

**Review by lindsayad — COMMENTED** [review]
This title says prereq ... so this is probably not the space in which we might want to modify mapping related things in `Assembly`?

**Comment by roystgnr** [comment]
I ... actually missed those.  Why do you have those, again?  You don't need a LAGRANGE FE to give you physical xyz points; if you call get_xyz() on any FE you'll get the right physical xyz points, using the right map, regardless of differences between map type and FE type.  Likewise for JxW points.  You're not recomputing those things redundantly?

**Comment by lindsayad** [comment]
> but it doesn't look like we're actually duplicating Lagrange mapping calculations here?

no

> We'll be doing Lagrange shape function initialization only to throw it away unused, in cases where we only use Rational-Bezier FE for our variables, but that's a problem with efficiency, not with correctness.

Exactly

**Comment by lindsayad** [comment]
All the code in `FEMap::compute_single_point_map` is agnostic of LAGRANGE vs. RATIONAL_BERNSTEIN right? I'm just trying to be sure that my `Assembly::computeSinglePointMapAD` method is fine un-modified. I think so...

**Comment by roystgnr** [comment]
`FEMap::compute_single_point_map` is mapping shape function independent, using pre-filled arrays - `FEMap::init_reference_to_physical_map` is where we choose between different FE types for different mapping shape functions.

However, I'm not sure how much of the code *using* `Assembly::computeSinglePointMapAD` is going to work with rational basis functions.  The non-vertex nodes for a Rational Bernstein element are really control points, and might not even lie on the element for curved geometries, and in the case where we haven't deleted our spline nodes the FEM node locations aren't even independent, they're constrained!  Doing deformation of displaced IGA meshes is a huge use case, and we ought to be able to get it working eventually, but it's not going to be plug-and-play the way physics on a fixed domain can be.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
