### PR TITLE
Fix PointValue postprocessor on distributed mesh

### PR DESCRIPTION
**Pull request by roystgnr**
We have to prepare for some ranks to be unable to find an element
containing the requested point; they won't be the ones evaluating it
anyway.

Why are we using all this code instead of System::point_value()?

This fixes another #1500 regression for me, in
postprocessors/point_value.test

Hmm... that question in the commit message sounds rude and snarky, but it's not rhetorical.  If the answer is just that @friedmud wrote the first version of PointValue before System::point_value() existed, then we should consolidate code and save a few lines.  If the reason is that PointValue handles variables which aren't raw libMesh::System variables, or some such, then I'd be honestly curious about the details.

### CODE REVIEW

**Comment by permcody** [comment]
Good question. PointValue in Moose is quite old but I just looked at `System::point_value()` and it looks like it's a drop in replacement for this object. I'm 100% supportive of replacing it if you'd like. If not, just open a ticket and somebody on my team can do it later. Thanks for fixing this! (and everything else you've been cleaning up lately)

**Comment by roystgnr** [comment]
> Thanks for fixing this! (and everything else you've been cleaning up lately)

Eh, let's just hope @friedmud forgives me for my choice of priorities.  I *want* to get CheckpointIO upgraded, I swear, I just fear I'm not going to be able to know whether I'm actually improving or worsening the code so long as there's dozens of DistributedMesh-failing regression tests muddying the issue.

**Comment by permcody** [comment]
These are both high (or the same) priorities in my book. Neither is super useful without the other on larger problems.

**Review by permcody — APPROVED** [review]

**Comment by friedmud** [comment]
If you can replace it with `System::point_value()` I don't see why not.

**Pull request merged**
