### PR TITLE
Updates to VolumetricModel 

### PR DESCRIPTION
**Pull request by jasondhales**
Refs #5053

### CODE REVIEW

**Comment by jwpeterson** [comment]
Looks like this requires an app update.  We can push an integration branch to upstream if you want to use that to update your app first...

**Comment by jasondhales** [comment]
I'm rusty on this.  Can I point to ad4418e?

**Comment by jwpeterson** [comment]
Hmm... because of the way github works, you might actually be able to.  In the MOOSE module within your app, can you do:
```
git fetch origin pull/5081
```
successfully?  That should pull down ad4418e, which will allow you to update the submodule and fix the app.

**Comment by jasondhales** [comment]
No, that didn't work.

**Comment by jwpeterson** [comment]
OK, how about:
```
git fetch origin pull/5081/head
```
That worked for me in a quick test.

**Comment by jasondhales** [comment]
Yep, that worked.  I'm rebuilding now to double check things.  I'll push my app change shortly.  Thanks.

**Comment by jasondhales** [comment]
I was able to build the code and check things locally, but when I submitted the merge request on gitlab, I get the following error from the build test:

fatal: reference is not a tree: ad4418ea93f0b70214417406422404d26f3ddfdd
Unable to checkout 'ad4418ea93f0b70214417406422404d26f3ddfdd' in submodule path 'moose'

**Comment by jwpeterson** [comment]
Darn, probably because the refspec does not include "refs/pull/*/head" as described [here](https://gist.github.com/piscisaureus/3342247).  We'll just do it the old-fashioned way by pushing your branch to upstream, and then using that for the submodule update... I can do it tomorrow, or perhaps we can just give you write access, @permcody?

**Comment by jasondhales** [comment]
Great, thanks.  Let me know when it is ready.

**Comment by jasondhales** [comment]
Also, it seems like last time the PR was merged into devel and then I checked it out from there into my app.

**Comment by jwpeterson** [comment]
OK, your branch is in upstream as `vstrain_5053`

> Also, it seems like last time the PR was merged into devel and then I checked it out from there into my app.

Yeah, that's another option.

**Comment by jasondhales** [comment]
I haven't been able to get hpcgitlab to fire off the testing again.  I tried closing and reopening the merge request, and I pushed a slightly changed branch.  Neither seem to have triggered another attempt.  Any ideas?

**Comment by jwpeterson** [comment]
It may be due to the outage.  Have you tried editing the MR description?

**Comment by jasondhales** [comment]
Just tried it.  Nothing new.  The message "Checking for ability to automatically merge…" and the spinning circle are sticking around longer than they should.  Is that stage somehow stuck?

**Comment by jwpeterson** [comment]
> Is that stage somehow stuck?

That's kind of what it feels like...  I think other jobs have fired off since gitlab came back online, though, so I'm not sure what's special about this one.

**Pull request merged**
