### PR TITLE
[WIP] Update element data for transforms

### PR DESCRIPTION
**Pull request by lindsayad**
@joshuahansel try this out

### CODE REVIEW

**Comment by roystgnr** [comment]
IMHO this is just the use case `set_isnt_prepared()` was for.

**Comment by roystgnr** [comment]
Hmm.. not quite, actually.

**Comment by roystgnr** [comment]
This is just the use case our *future* `set_specifically_what_isnt_prepared()` ideas were aimed at - allowing code to do things like updating caches of geometric data without redundantly recomputing caches of topological data, in this case.  But we haven't figured out the right APIs for that, and until then, either solution is probably equally reasonable here.

**Comment by lindsayad** [comment]
Ok I've decided to go with `set_isnt_prepared` instead. Overall safer I think and also maybe in some cases avoids redundant work (e.g. some other generator calls `set_isnt_prepared` and then we end up doing the element data caching twice) ... although may also impose unnecessary work in some cases too (e.g. no other mesh generators). So ... I'll say performance is a wash and so I'll go with added safety (maybe we add some new data to the mesh that is invalidated by transforms but isn't fixed by calls to `cache_elem_data`)

**Comment by lindsayad** [comment]
I expect this to fail modules testing. Instead of trying to "fix" all the places where we stitch meshes in MOOSE, I'm proposing https://github.com/libMesh/libmesh/pull/3509 instead

**Comment by lindsayad** [comment]
will need to wait on libmesh/libmesh#3510

**Comment by lindsayad** [comment]
closing in favor of #24018

**Pull request closed without merging**
