### PR TITLE
Move communicateGaps method into .C

### PR DESCRIPTION
**Pull request by lindsayad**
We are seeing a problematic instantiation in libmesh/libmesh#3467 that instantiates TIMPI StandardType and Packing outer template wrapping of MetaPhysicL types before we've had a chance to include our headers with partial specializations. Hopefully this will help

### CODE REVIEW

**Review by roystgnr — DISMISSED** [review]
Not sure if this will help, but it couldn't hurt.

**Comment by recuero** [comment]
Dumb comment... why not also `communicateVelocities`?

**Comment by lindsayad** [comment]
Because it's a template function

**Review by roystgnr — APPROVED** [review]
I'm a little more hopeful about that `MooseConfig.h` include turning out to be helpful...

**Comment by lindsayad** [comment]
intel mac failures unrelated

**Pull request merged**
