### PR TITLE
Modify some comments to clarify mean thermal expansion function

### LINKED ISSUE #9251: Refactor ComputeMeanThermalExpansionFunctionEigenstrain
### Description of the enhancement or error report
We have multiple material models where we want to hard-code a relationship for the mean thermal expansion as a function of temperature. We want to re-used the functionality of ComputeMeanThermalExpansionFunctionEigenstrain for that purpose, but don't want the constraint that this relationship be defined through a user-supplied Function in the derived classes. 

### Rationale for the enhancement or information for reproducing the error
Break ComputeMeanThermalExpansionFunctionEigenstrain into a base class that other similar models can derive from, and a derived class that gets the thermal expansion relationship through a Function.

### Identified impact
Changes are limited to ComputeMeanThermalExpansionFunctionEigenstrain.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #9251

### CODE REVIEW

**Review by dschwen — CHANGES_REQUESTED** [review]
That's great, but a better place would be the Markdown file for this clas.. which does not exist yet. You can add the reference to the TM bib file.

**Comment by bwspenc** [comment]
Hold on, don't merge this!  It's still wrong.

**Comment by bwspenc** [comment]
OK, I think I have this right now.  @gambka, would you mind taking a look at this to verify?  Also, @dschwen, there actually is already a Markdown file for the one class that currently derives from this base class, which I edited slightly because there was a minor error.

**Review by gambka — APPROVED** [review]
Looks good to me.

**Review by dschwen — APPROVED** [review]

**Pull request merged**
