### PR TITLE
PorousFlow JOSS improvements to documentation

### PR DESCRIPTION
**Pull request by cpgr**
Addresses documentation improvements suggested.

Refs #15268

### CODE REVIEW

**Comment by cpgr** [comment]
Wow - I might push to next instead so there aren't so many commits!

**Comment by WilkAndy** [comment]
Hey MooseDevels: are you expecting me to review, or will you do it?

**Comment by loganharbour** [comment]
@WilkAndy please do a run through and then I'll review.

**Comment by WilkAndy** [comment]
Sorry, i didn't get to this today.  I will do this early next week.

**Comment by WilkAndy** [comment]
This looks good to be merged, @loganharbour .   @cpgr, do you want to do an extra commit with "Schaedle" instead of "Sch{a-umlauts}dle" in the paper.md ?

**Comment by cpgr** [comment]
OK, I'll do it now. I couldn't manage to get the umlaut working properly when I first did this so will go with the non-umlaut spelling.

**Comment by WilkAndy** [comment]
Cool, thanks @cpgr.  Yea, i couldn't get the umlaut working either - seems to work find in bib files but not JOSS markdown.

**Comment by WilkAndy** [comment]
Hi @loganharbour , as far as i'm concerned this is perfect to merge.

**Comment by loganharbour** [comment]
We really should start making some standard, general documentation for getting started that appears in all of the modules. Until then, linking to the general getting started is a good choice.

Side note - other two PRs will come together. This one's just the easier weekend choice :-)

**Review by loganharbour — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for everything @loganharbour

**Comment by cpgr** [comment]
Thanks @loganharbour. Andy and I definitely need to shout you a drink!

@WilkAndy. I can't really remember the JOSS process, but I think that the last commit (removing the umlaut that wasn't rendered) should have gone to the `joss_porous_flow` branch instead of `next`? If so, I'll make a new PR to that branch too.

**Comment by WilkAndy** [comment]
I think you're right about the `joss_porous_flow` branch and the umlaut.  Thanks Chris,

a

**Comment by cpgr** [comment]
Looks like there was no umlaut in the version in the `joss_porous_flow` branch. Weird? I think we can get the paper to rebuild in JOSS. I'll take a look

**Comment by WilkAndy** [comment]
OK, strange.  Maybe you or i already did it?

**Pull request merged**
