### PR TITLE
Adding truss model, postprocessor, and visco-elastic single element model

### PR DESCRIPTION
**Pull request by jain651**
This PR is for 
 - a truss model which is developed in line with the existing beam model. The truss model can take care of multiple eigenstrains too.
 - a processor that calculates average diaplacement between a set of points.
 - a single element model for visco-elastic modeling.

Closes #15826

### CODE REVIEW

**Comment by loganharbour** [comment]
Please push a change to this to forcefully re-trigger testing (full testing is now available).

You can do the following:
```
git commit --amend
```
and save the amend message that comes up without changing it (by typing `:wq` if in vim). This will forcefully change the commit hash of the last commit, which will trigger a change. Then forcefully push:
```
git push --force
```

**Comment by jain651** [comment]
When I try to run 
```
git clang-format 993719694528eec103be499d263e274696ff58d9
```
It gives the following error:
```
(moose) amitjain@fn604209 moose (trussModel_2) $ git clang-format 993719694528eec103be499d263e274696ff58d9
clang-format did not modify any files
```

**Comment by loganharbour** [comment]
Can you apply the patch instead?
```
curl -s https://mooseframework.inl.gov/docs/PRs/15841/style.patch | git apply -v
```

**Comment by jain651** [comment]
Yes, I applied the patch.
What do I need to do next? This is the first time I am doing this, so please bear with me.

**Comment by loganharbour** [comment]
No problem!

That patch adds another commit to your branch. Now, you need to simply push the changes to github with:
```
git push
```

**Comment by jain651** [comment]
Could you please help me in understanding the further process to make the check completely successful?

**Comment by cticenhour** [comment]
If you click on "Details" to the right of each check, it will take you to the test output, so you can figure out what is wrong. In this case, it looks like you have some errors in your test input files. 

It looks like you've set a command line parameter that is conflicting with another in the input file, `truss_plastic.i`. The fix here is to remove the `hardening_constant` you added to the file, since the test also sets a `hardening_function`. 

```
tensor_mechanics/test:truss.compressive_hardeningfn: *** ERROR ***
tensor_mechanics/test:truss.compressive_hardeningfn: PlasticTruss: Only the hardening_constant or only the hardening_function can be defined but not both
```

**Comment by jain651** [comment]
@bwspenc Could you please review this PR?

Thanks,
Amit Jain

**Comment by gridley** [comment]
This is pretty nice. I was just recently wondering if MOOSE could do trusses...

**Comment by bwspenc** [comment]
Looking at this now.

**Comment by bwspenc** [comment]
@jain651 Since this has been out there for a while, could you please re-base and push an update to this?

**Pull request closed without merging**
