### PR TITLE
Revert "Refactor RunApp and FileTester"

### PR DESCRIPTION
**Pull request by milljm**
Reverts idaholab/moose#18988

Re-open #18974

### CODE REVIEW

**Review by loganharbour — DISMISSED** [review]

**Comment by YaqiWang** [comment]
Looks messy............ I am looking into Griffin.

**Review by loganharbour — APPROVED** [review]
This is being merged with failing and incomplete tests. It will fail on next. Merge will allow application developers to use the fixes for correcting their applications.

**Comment by lindsayad** [comment]
I'm glad we moved hell and high-water to get this fixed. I have a long standing development branch that I rebased onto a point in between this and #18988. I had a bunch of merge conflicts, but I thought I had fixed them appropriately because when I ran my test suite, all the new tests passed. But now rebasing after this point they fail, and going back to the in-between point (I had a old temporary branch at that point), if I run with `-v` I see that it should have failed then too. Now what I don't have is a branch pointing to my development point *before* #18988 ... so I'm going to see just how good I am with `git reflog` now

**Comment by lindsayad** [comment]
Well sorting through `git reflog` was pretty easy ... and the conclusion was that the test actually never passed 😆 I thought I had fixed a problem I had banged my head against the wall for for weeks about ... and it was only because the test harness playing a mean trick on me 😆 😭

**Pull request merged**
