### PR TITLE
Subdomain setup fix in ComputeElemAuxBcsThread 

### LINKED ISSUE #21018: `subdomainSetup()` with threads is not being called when expected/needed
## Bug Description
In [ComputeThermalExpansionEigenstrainBase](https://github.com/idaholab/moose/blob/next/modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C#L49-L79) I'm using `subdomainSetup()` to resize a vector to `_fe_problem.getMaxQps()` elements. In threaded execution this vector has size zero in some threads (leading to [this _Test threads_ failure](https://moosebuild.hpc.inl.gov/job/453600/)) .

## Steps to Reproduce
Run any input that uses an object based on `ComputeThermalExpansionEigenstrainBaseTempl<is_ad>` threaded. 

Note: we are _not_ testing the tensor mechanics module with threads on PRs! Why?

## Impact
This will prolong the current `next` breakage.

### PR DESCRIPTION
**Pull request by dschwen**
Fixes a threading failure exposed by the recent thermal expansion eigentrain PR (#20982).

Closes #21018

### CODE REVIEW

**Review by loganharbour — APPROVED** [review]
Not really sure `did` makes any sense, but that's ok

**Review by bwspenc — APPROVED** [review]

**Comment by dschwen** [comment]
> Not really sure `did` makes any sense, but that's ok

https://github.com/idaholab/moose/blob/c3fe9a4bae677a53ec5355564566014c9a47211c/framework/src/problems/FEProblemBase.C#L1348-L1356

**Comment by loganharbour** [comment]
Ahh yeah doesn't make sense elsewhere, best to use it here too 🍻

**Comment by dschwen** [comment]
Uhm... Domain ID?

**Comment by dschwen** [comment]
> Ahh yeah doesn't make sense elsewhere, best to use it here too 🍻

I naively thoutht this was MOOSE team sanctioned nomenclature, but now that I did a git blame I know better :-D https://github.com/idaholab/moose/commit/90516437a5874dcd6d8f5a3ef40688e26cdca411

**Review by recuero — APPROVED** [review]

**Pull request merged**
