### PR TITLE
Resizing bug in PorousFlowMaterial fixed

### LINKED ISSUE #11335: PorousFlow example coarse_3D.i asserts in debug
## Rationale

The PorousFlow example `examples/flow_through_fractured_media/coarse_3D.i` asserts in debug mode
```
Assertion `i < _size' failed
Access out of bounds in MooseArray (i: 3 size: 3)
at /Users/gre462/Documents/MOOSE/projects/moose/framework/build/header_symlinks/MooseArray.h, line 263
```

## Description

Can be seen by running this example using a debug executable.

## Impact

Perhaps a subtle issue that is triggered by the combination of objects in this example?

### PR DESCRIPTION
**Pull request by WilkAndy**
For nodal materials, the data should be of size max(number_of_nodes, number_of_quadpoints).  Although only number_of_nodes elements in this vector are ever computed and used, PorousFlow now handles the case where number_of_quadpoints > number_of_nodes.

Fortunately, this rather major bug would never be seen by users running optimized code, and their results will be unchanged by this PR, even if they had number_of_quadpoint > number_of_nodes in their mesh.  This is because we only use number_of_nodes information, so even though MOOSE would be std::copying junk information, it would never be used.

Fixes #11335

### CODE REVIEW

**Comment by cpgr** [comment]
I'm glad the fix wasn't too hard!

**Comment by WilkAndy** [comment]
I hope the fix is a fix! :-)

**Comment by permcody** [comment]
FYI - @friedmud or @andrsd - This doesn't look like the kind of behavior a user should need to implement, but it's a reality that @WilkAndy is facing.

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
You are correct, @permcody .   A Material that works at the nodes is what's required.  Mostly these Material properties are basically nodal Aux Variables.  (Not always, because there is also the unusual case of nodal Material Properties depending on the element too, viz, we use elemental information together with nodal information to say "the value at the node in so-and-so element is such-and-such".)

Why didn't we just use nodal Aux Variables everywhere (apart from the unusual case just mentioned)?   It was completely because we want: (1) vectors of information (our Material Properties are std::vectors, std::vector<std::vector<Real>>, etc); (2) derivative information: d(property)/d(variable) (which are also vectors).   Here we could really nicely utilize the DerivativeMaterial, where we can, but don't need to, specify derivatives.  So for us, an Aux Variable that had those features of DerivativeMaterial would be basically perfect.

a

**Comment by andrsd** [comment]
> I'm not sure if we have materials for DG kernels but that's another place (interior faces).

We do. Pretty much since the beginning of DG. The three instances of a material we have are: volumetric, side, neighbor (that being along the side of a neighboring element).

The nodal materials I mentioned above would not work like `AuxKernel`s do. There are obvious problems like: no gradient values for C0 elements, different materials sharing a single node, etc. The nodal materials would work like normal materials, but instead of qpoints they would have values at nodes. Obvious disadvantage is that if you had 4 elements sharing 1 node, the value at that node would be computed 4 times. But if you had 4 different materials sharing a single node, you would have to do 4 evaluations any way.  In the end, this nodal material would be just a solution for storing things. Indexing into it by local node idx rather then qpoint idx. There would not really be any other purpose. And it would only fix the code where @WilkAndy has to mess with `_material_data`. 

Also, this is just a proposed way how we could fix the above-mentioned problem.

**Pull request merged**
