### PR TITLE
Silence excessive log after reading unique file

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #25955

Turns out modifying syntax lists affects SQA too
EDIT
that commit on syntax is removed

### CODE REVIEW

**Comment by GiudGiud** [comment]
Re-drafting until I m sure this passes and fixes the syntax as expected

**Comment by GiudGiud** [comment]
syntax page is trimmed as expected
https://mooseframework.inl.gov/docs/PRs/26528/site/modules/chemical_reactions/index.html

**Comment by cticenhour** [comment]
Not seeing any trimming in the syntax portion of that linked page. The sections for `ReactionNetwork/AqueousEquilibriumReactions` and `ReactionNetwork/SolidKineticReactions` still exist. Should I be looking at something else?

**Comment by GiudGiud** [comment]
umm. Yes I dont actually want them gone, just want Variables to stop showing up under them. But they dont on that page, only on that page:
https://mooseframework.inl.gov/syntax/index.html#fbcd317d-d6ea-402b-a932-8ad9c5fd872d

**Comment by cticenhour** [comment]
Still seeing Variables show up on https://mooseframework.inl.gov/docs/PRs/26528/site/syntax/index.html#4babf0fa-e3d9-48db-b5d6-a80740275aac

**Comment by GiudGiud** [comment]
yup I dont know what to do :S

**Comment by cticenhour** [comment]
Hmm. Instead of `unregister.yml` did you try a `remove.yml`? In this case I imagine you would put in:

```
- ReactionNetwork/AqueousEquilibriumReactions/Variables
- ReactionNetwork/SolidKineticReactions/Variables
```

Since this is only popping up in the complete syntax, it should probably go in `framework/doc/remove.yml`

**Comment by GiudGiud** [comment]
I dont think remove.yml fits?
`ReactionNetwork/SolidKineticReactions/Variables` does not exist as a syntax.

the way I understand it
what exists is that ReactionNetwork/SolidKineticReactions is registered to the same tasks as AddVariableAction, and the task is associated to this Variables/* syntax. What we need to do is unregister the variables/* objects associates with that syntax from the ReactionNetwork/SolidKineticReactions

**Comment by GiudGiud** [comment]
dropping the commit. Cannot figure out those variables can be de-registered. 
The file I added is not being ignored, I checked (the reason for the error now).

**Comment by GiudGiud** [comment]
It s a trivial one now @cticenhour

**Review by cticenhour — COMMENTED** [review]
Had to invalidate a couple things before we got to green. All good now.

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
