### PR TITLE
add solution comparison example 

### LINKED ISSUE #5766: Solution Comparison Example
We really should have an example that shows how to compare solutions using `SolutionUserObject`, `SolutionFunction` and `ElementL2Error`

I'm working on this

### PR DESCRIPTION
**Pull request by friedmud**
Use `SolutionUserObject`, `SolutionFunction` and `L2ErrorPostprocessor` to compute the difference between two solutions.

I know that documentation needs to get added to the Wiki for this... but I have to run to class so I'll do that later tonight...

closes #5766

### CODE REVIEW

**Comment by permcody** [comment]
If I merge this are you still going to add documentation or is that just a ploy to get me to merge? hmm

**Comment by friedmud** [comment]
lol - I'll add documentation right now.  Go ahead and merge it so I can reference it in the documentation ;-)

I double promise ;-)

**Comment by permcody** [comment]
OK... I'm giving a probability of seeing documentation a "2".  Yes, a POSITIVE 2, which is higher than most of our probabilities ;)

**Comment by friedmud** [comment]
That high probability was justified!

Look at the bottom here:

http://mooseframework.org/wiki/MooseExamples/Example_14/

And the bottom of here:

http://mooseframework.org/wiki/MooseSystems/UserObjects/SolutionUserObject/

**Pull request merged**
