### PR TITLE
Cleanup and add ChainedReal support

### LINKED ISSUE #24888: `BilinearInterpolation` should support additional derivative types
## Reason
For thermal expansion materials the support of `ValueAndDerivative` (or `ChainedReal`) is required.

## Design
Mixing virtual functions and templating is a bit tricky. I will add a templated implementation function and a set of overloaded virtuals for the polymorphic interface.

## Impact
Added capability

### PR DESCRIPTION
**Pull request by dschwen**
Closes #24888

### CODE REVIEW

**Review by lindsayad — DISMISSED** [review]
You're not adding any new functional code, but it would be nice to see some testing of `ChainedReal`

**Comment by elementx54** [comment]
If it helps, there will eventually be a test in Bison that also uses this new capability.

**Comment by lindsayad** [comment]
> If it helps, there will eventually be a test in Bison that also uses this new capability

That's nice, but not ideal

**Comment by elementx54** [comment]
> > If it helps, there will eventually be a test in Bison that also uses this new capability
> 
> That's nice, but not ideal

@dschwen Do you want me to create a test in MOOSE? I will need this in BISON early next week.

**Comment by elementx54** [comment]
I gave it a shot and not easy for me, but I just don't know how to get the tests to work for the `ChainedReal` and `ADReal`. I think my problem is creating the derivative part and checking that. I'm not familiar with how those are treated behind the scenes.

I'll just grab dschwen's branch in the meantime and compile BISON with it while he is gone.

**Comment by dschwen** [comment]
We could merge this and I'll add a test tomorrow. I'm on pl today, driving home.

**Review by lindsayad — APPROVED** [review]

**Comment by loganharbour** [comment]
> a-u-t-o m-e-r-g-e...

Wouldn't because of https://civet.inl.gov/job/1652987/

**Comment by dschwen** [comment]
> > a-u-t-o m-e-r-g-e...
> 
> Wouldn't because of https://civet.inl.gov/job/1652987/

Yeah, pretty much never works when I try it.

**Pull request merged**
