### PR TITLE
Move xfem tests

### LINKED ISSUE #6757: Move XFEM tests
### Description of the enhancement or error report
We originally put a number of XFEM tests that depend on solid_mechanics in the combined module. Since the xfem module depends on solid_mechanics, we can move them back into xfem.

### Rationale for the enhancement or information for reproducing the error
Better to have tests in the appropriate module if possible.

### Identified impact
Move modules/combined/tests/solid_mechanics/xfem directory to xfem/tests.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #6757 

If you all think this is a reasonable solution, I'll modify stork as well to add these checks in new modules that get created with the script there.

### CODE REVIEW

**Comment by dschwen** [comment]
You could use dynamic object registration for your tests to pull in the objects from the other modules. This would be a little less heavy handed in my opinion.

**Comment by bwspenc** [comment]
@dschwen We have a huge number of tests in the combined module that are there just because of this issue. That would require putting ugly syntax in every one of those tests.
It looks like this breaks a phase field test that uses MultiApp so this might not be the solution.

**Comment by dschwen** [comment]
Ugly syntax?! @permcody, are you reading this? Shots fired! ;-)

**Comment by bwspenc** [comment]
I have to admit that I don't even know what the syntax is. Any solution where we would have to modify the input files to tell it where to find the library would be ugly regardless of how lovely the syntax is.

**Comment by dschwen** [comment]
It really is not ugly at all:

```
[Problem]
  register_objects_from = 'PhaseFieldApp'
  library_path = '../../../../phase_field/lib'
[]
```

The paths are well defined (relative).

**Comment by friedmud** [comment]
This PR is definitely not the answer (any `static` usually isn't!).  This will directly break any time an app is a sub-app of itself or if you have two sub-apps of the same type...

**Comment by bwspenc** [comment]
@friedmud I'm not a fan of `static` either, but since these are `static` methods, we're kind of stuck doing something like that to control their behavior if we want to handle this on the module side.

The options here are:
1. Do something on the side of the module like what I did.  That would probably have to involve some use of `static` variables. We could work around this multi-app issue with an even uglier use of `static` variables if we really wanted to.
2. Handle this on the framework side somehow.  The framework could simply ignore a second registration, which isn't great because we wouldn't get error checking. Alternatively, maybe it could store something to let it know that it already registered the objects for a module so that it could skip them the second time through.
3. Do this with dynamic linking, as @dschwen suggested. With the current scheme, we would have to modify the input files to point to the library, so you'd have to modify the input file depending on whether it was run with a module's executable or with the executable of an app that pulled in that module. That seems messy. However, since the module knows what other modules it depends on, couldn't we hard-code in a relative path to that other module where it would automatically look?  That way we wouldn't have to modify the input files.  If we could do something like that, I think that would be an ideal solution.
4. Do nothing and just have the tests that use objects from multiple modules live in the `combined` module.  It's already kind of a mess, and we will add many more tests like this in the future, so I'm not really crazy about that, but it does work.

**Pull request closed without merging**
