### PR TITLE
IC scalar var from mesh file var

### LINKED ISSUE #13040: Scalar variable initial_from_file_var?
## Rationale

Should moose be able to read IC from file for scalar variables? If so, this is a bug report, if not this is a feature request. 

## Description

If this feature is thought to be possible, this patch in moose tests shows `test/tests/kernels/ode/ode_expl_test.i` fail if the coupled aux scalar variable uses `initial_from_file_var`.

[ode_expl_test_patch.txt](https://github.com/idaholab/moose/files/2958449/ode_expl_test_patch.txt)

## Impact

It would allow me to use IC from file when scalar kernels are involved in my sims. At the least, this is an unhandled error since MPI_Abort is called w/o a useful message.

It looks like if I used checkpoints I could get around this, however I prefer the IC from file approach since I'm not looking for a "restart"

### PR DESCRIPTION
**Pull request by veeshy**
Added logic to check if variable is scalar, if it is then set the var ic accordingly. Two tests added to show loading of scalar var and auxvar.

Closes #13040.

### CODE REVIEW

**Comment by permcody** [comment]
This is close.... However, as you can see it's failing to run in parallel. 
@andrsd - Can you see what the issue is here? He's trying to set a scalar dof. I've never dug into the parallel rules for this operation.

**Comment by andrsd** [comment]
Scalar DOFs only live on proc 0 IIRC. That's most likely the problem. Tag @roystgnr

**Comment by veeshy** [comment]
Ah! I wrapped a check for proc 0 around the code and it passes tests with `-p 2` locally now

**Comment by roystgnr** [comment]
Actually, at the moment we store all SCALAR dofs on processor N-1.  (IIRC we figured that proc 0 was already the most overloaded and proc N-1 the least due to typical node imbalance)  You can set any value from any processor, of course, but it might save a wisp of communication to do the read on the last processor rather than the first.

Except... You got a signal 11 from the previous code?  That looks like a problem with the ```global_values[0]``` lookup; does ExodusII_IO::read_global_variable() only operate on proc 0 perhaps?

**Comment by veeshy** [comment]
Looks like the exodus helper class only does reads on the 0th proc, I added a comment into why the read is on the 0th proc, otherwise I got nothing extra to add to this one.

**Comment by permcody** [comment]
OK - we can probably finish it up then. I think what needs to be done based on Roy's comment is that we need to send what we read on rank 0 to rank (size-1) via MPI.

**Comment by permcody** [comment]
Superseded  #13112

**Pull request closed without merging**
