### PR TITLE
Update petsc to 3.22.1-ish (includes some 3.23 features)

### PR DESCRIPTION
**Pull request by lindsayad**
For even more beautiful code

### CODE REVIEW

**Comment by lindsayad** [comment]
will need to wait on https://gitlab.com/petsc/petsc/-/merge_requests/7945

**Comment by milljm** [comment]
This is also happening: https://github.com/idaholab/moose/pull/28847
Historically though, changes to the entire stack take time...

**Comment by lindsayad** [comment]
Marking this as draft because I want to wait for https://gitlab.com/petsc/petsc/-/merge_requests/7988 to get merged

**Comment by lindsayad** [comment]
Yea none of the failures are related to this PR

**Comment by lindsayad** [comment]
failures are unrelated. This should be ready for review again

**Review by milljm — APPROVED** [review]
For my part, the Conda stuff looks good.

**Pull request merged**
