### PR TITLE
Allow executioners to do setups before problem init

### LINKED ISSUE #18004: Give executioner a chance to do something before init_problem task
## Reason
Currently an executioner can do something either in its constructor or its `init()`, one is often too early (before adding variables) while another is often too late (after `FEProblem::initialSetup`). Some work done by executioner need to be done during executing actions, often as late as possible but before `init_problem` task.

## Design
So I propose to add a call back function in `Executioner` like `virtual void preInit()`, which can be called inside at the beginning of `FEProblem::init`.

## Impact
This is a new capability that can simply some executioner design significantly.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #18004.

### CODE REVIEW

**Comment by GiudGiud** [comment]
Would you say this is preProblemInit?
preInit does say it's before Init, but doesnt locate it exactly in the timeline.

**Comment by loganharbour** [comment]
@YaqiWang out of curiosity - what are you trying to do during this phase?

**Comment by YaqiWang** [comment]
We want to let executioner to build the sweeper instead of the transport system. The executioner needs to get information from transport system for building the sweeper thus cannot do the build in its constructor. We do not want to build the sweeper in its init function because otherwise initialSetup of sweeper (although it could be empty) will not be called by MOOSE. There could be other use cases I believe if we have more custom executioners in the future.

**Comment by YaqiWang** [comment]
Any objections or further comments on this?

**Review by GiudGiud — APPROVED** [review]
Looks good to me

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
