### PR TITLE
Variable time integration aux kernel issue5737

### PR DESCRIPTION
**Pull request by gleicher27**
changes...

### CODE REVIEW

**Comment by andrsd** [comment]
You want to start your branch from `devel` not `master`. Try `git rebase devel`

**Comment by gleicher27** [comment]
ok it should be rebased up to devel.

**Comment by permcody** [comment]
Now you need to push once more. Git will reject it since it will now be in conflict with this old branch so you'll need to add the "-f" flag for force. Always be careful with that flag but that's how you override outdated (rebased, amended, and so on) branches.

Before you do that though, it would be nice if you clean up your commits. Generally we want to see only working commits in the final push, not all of the intermediates that you might produce during your normal development cycle. You need to squash them through an interactive rebase (`git rebase -i HEAD~<number of commits>`). If you need help with these steps let me know.

**Comment by permcody** [comment]
The fact that you just pushed another commit tells me that it is NOT rebased on devel. You wouldn't have been able to push without changing the entire history.

**Comment by permcody** [comment]
Moved to #5773

**Pull request closed without merging**
