### PR TITLE
Add JUnit XML output support for TestHarness

### LINKED ISSUE #25284: Add support for writing TestHarness results to a JUnit XML file.
## Reason
Currently, results saved to a file are only saved in a JSON with a custom structure. For testing in downstream production applications, the ability to have industry-standard tests is beneficial for running more complex/custom testing pipelines, especially since JUnit is native to most pipelines, especially gitlab runners

## Design
TestHarness will, in addition to JSON output, output a junit xml file upon request

## Impact
Will add a new arg to the testharness and new functionality but won't impact anything else

### PR DESCRIPTION
**Pull request by nietzscheanmonkey**
Closes #25284

### CODE REVIEW

**Comment by loganharbour** [comment]
Thanks for the contribution.

Is there a standard here that you're following?

**Comment by nietzscheanmonkey** [comment]
Aside from the basic JUnit XML structure, not particularly, it just takes the testharness' internal structure and outputs it in a readable way in the XML. It is currently tested and working on Gitlab Runner, but should be working on other pipelines that use JUnit as well.

**Comment by loganharbour** [comment]
This looks fine to me. Is there an easy way to check the output instead of a test that just runs with the option?

**Comment by nietzscheanmonkey** [comment]
The simplest and most resilient solution is probably twofold:
1. Make a gold of the output of `always_ok`, then use XMLDiff to compare the two. 
2. Using the xsd from https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd, read the xml file outputted by the TestHarness under a try catch, where you basically read the whole output file in using the JUnit schema definition. If the try catch triggers, then the schema is invalid. 

Then you basically have a test that checks that the TestHarness is outputting the file, then a test that checks its properly formatted. 

Note that I don't know if the XSD solution will play nice out of the box. The output from this xml definitely works in Gitlab Runner, though, so it is valid, but it's possible that the JUnit XSD might be particularly strict or work in a weird way.

I'm also not 100% on the behavior of where the output file goes if output_dir is manually set. That is something to verify/modify.

**Comment by loganharbour** [comment]
I think that for the sake of simplicity, storing the output and diffing should be sufficient. I don't think #2 is necessary.

**Comment by GiudGiud** [comment]
What's the status here?
Do you need commit number 2? @nietzscheanmonkey

**Comment by nietzscheanmonkey** [comment]
Haven't a lot of time to work on this and the development environment I'm stuck with makes writing for this very time-consuming. If someone wants to finish it off I have no objections, otherwise I hope to get to it soon. 

The failures don't seem related, but I am unable to invalidate them. If someone could verify and invalidate it would be appreciated.

**Pull request closed without merging**
