### PR TITLE
Fixing minor bugs in hfem diffusion kernel

### LINKED ISSUE #19561: Fix minor bug in `HFEMDiffusion` Kernel
## Bug Description

In `debug` mode, the `HFEM Diffusion` kernel generates an error in the off-diagonal jacobian evaluation when the more one variables were defined (see attached input below):

```bash
execution Information:
  Executioner:             Steady
  Solver Mode:             NEWTON
  MOOSE Preconditioner:    SMP (auto)

 0 Nonlinear |R| = 3.685139e-01
Assertion `i*j < _val.size()' failed.
i*j = 0
_val.size() = 0


Stack frames: 35
0: 0   libmesh_dbg.0.dylib                 0x000000010faa2232 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 626
1: 1   libmesh_dbg.0.dylib                 0x000000010fa96f2a libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 218
2: 2   libmoose-dbg.0.dylib                0x000000011733946d libMesh::DenseMatrix<double>::operator()(unsigned int, unsigned int) + 445
3: 3   libmoose-dbg.0.dylib                0x0000000118089203 DGKernel::computeOffDiagElemNeighJacobian(Moose::DGJacobianType, MooseVariableFieldBase const&) + 691
4: 4   libmoose-dbg.0.dylib                0x000000011808bb30 DGLowerDKernel::computeOffDiagJacobian(unsigned int) + 208
5: 5   libmoose-dbg.0.dylib                0x000000011808bfda HFEMDiffusion::computeOffDiagJacobian(unsigned int) + 90
6: 6   libmoose-dbg.0.dylib                0x000000011845d4dc ComputeFullJacobianThread::computeInternalFaceJacobian(libMesh::Elem const*) + 748
7: 7   libmoose-dbg.0.dylib                0x000000011845b49e ComputeJacobianThread::onInternalSide(libMesh::Elem const*, unsigned int) + 702
8: 8   libmoose-dbg.0.dylib                0x0000000117a9dd24 ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) + 1412
9: 9   libmoose-dbg.0.dylib                0x00000001186eaed2 void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeFullJacobianThread>(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, ComputeFullJacobianThread&) + 114
```

In the investigation of this issue, it was found that the method `computeOffDiagJacobian` should be overrided as shown below because we don't need to evaluate jacobian contribution from other variables that are not used in the HFEM Diffusion kernel.

```
void
HFEMDiffusion::computeOffDiagJacobian(const unsigned int jvar_num)
{
  if (jvar_num == _var.number())
    DGLowerDKernel::computeOffDiagJacobian(jvar_num);
}
```

## Steps to Reproduce

The error can be reproduced by executing the attached input file in debug mode.

[hfem_diff_error.i.txt](https://github.com/idaholab/moose/files/7664639/hfem_diff_error.i.txt)

```
[Mesh]
  [square]
    type = GeneratedMeshGenerator
    nx = 3
    ny = 3
    dim = 2
  []
  build_all_side_lowerd_mesh = true
[]

[Variables]
  [u1]
    order = THIRD
    family = MONOMIAL
    block = 0
  []
  [u2]
    order = THIRD
    family = MONOMIAL
    block = 0
  []
  [lambda1]
    order = CONSTANT
    family = MONOMIAL
    block = INTERNAL_SIDE_LOWERD_SUBDOMAIN
  []
  [lambda2]
    order = CONSTANT
    family = MONOMIAL
    block = INTERNAL_SIDE_LOWERD_SUBDOMAIN
  []
[]

[Kernels]
  [diff1]
    type = MatDiffusion
    variable = u1
    diffusivity = '1'
    block = 0
  []
  [reaction1]
    type = Reaction
    variable = u1
    rate = '1'
    block = 0
  []
  [source1]
    type = BodyForce
    variable = u1
    value = '1'
    block = 0
  []
  [diff2]
    type = MatDiffusion
    variable = u2
    diffusivity = '2'
    block = 0
  []
  [reaction2]
    type = Reaction
    variable = u2
    rate = '2'
    block = 0
  []
  [source2]
    type = CoupledForce
    variable = u2
    v = u1
    block = 0
  []
[]

[DGKernels]
  [surface1]
    type = HFEMDiffusion
    variable = u1
    lowerd_variable = lambda1
  []
  [surface2]
    type = HFEMDiffusion
    variable = u2
    lowerd_variable = lambda2
  []
[]

[BCs]
  [u1_bc]
    type = NeumannBC
    boundary = 'left right top bottom'
    variable = u1
  []
  [u2_b2]
    type = NeumannBC
    boundary = 'left right top bottom'
    variable = u1
  []
[]

[Executioner]
  type = Steady
  solve_type = 'NEWTON'
  petsc_options_iname = '-pc_type -snes_linesearch_type -pc_factor_mat_solver_type'
  petsc_options_value = 'lu       basic                 mumps'
[]
```
## Impact

The error described here can be resolved.

### PR DESCRIPTION
**Pull request by yjung-anl**
closes #19561

### CODE REVIEW

**Comment by yjung-anl** [comment]
@YaqiWang 
Can you take a look this PR?

**Comment by YaqiWang** [comment]
Can we just add
```
  if (_local_ke.n() == 0 || _local_ke.m() == 0)
    return;
```
in `DGKernel::computeOffDiagElemNeighJacobian` before the quadrature point loop?

**Comment by yjung-anl** [comment]
@YaqiWang 
I originally did that way. But I modified this way because I don't want to update `DGKernel` kernel.
Which one would be better? (Or updating both?)

**Comment by yjung-anl** [comment]
Updated `DGKernel ` and `ArrayDGKernel` as well.

**Comment by YaqiWang** [comment]
> @YaqiWang I originally did that way. But I modified this way because I don't want to update `DGKernel` kernel. Which one would be better? (Or updating both?)

The logic in
```
void
ArrayHFEMDiffusion::computeOffDiagJacobian(const unsigned int jvar_num)
{
  if (jvar_num == _var.number())
    ArrayDGLowerDKernel::computeOffDiagJacobian(jvar_num);
}
```
does look strange: typically `jvar_num` is not equal to `_var.number()` and we skip completely in such a case. Basically in such a case `ArrayDGLowerDKernel::computeOffDiagJacobian(jvar_num)` is just doing `computeJacobian`. At least you want to call `computeJacobian` directly? Skipping the calculation completely is reasonable for optimization purpose.

I think changing DGKernel as well can possibly make things safer. I have to admit the code here is quite complex, which is also related with the logic in `ComputeJacobianThread` if I recall.

**Comment by yjung-anl** [comment]
@YaqiWang 
I updated the commit as you suggested.

**Comment by loganharbour** [comment]
I think this is the right call; I'll let @YaqiWang give a 👍🏼 first

**Comment by YaqiWang** [comment]
Looks good to me. Even though we could override `ArrayHFEMDiffusion::computeOffDiagJacobian` for a faster evaluation, but that is minor to me.

**Review by YaqiWang — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
