### PR TITLE
Demonstrates an exodus output bug

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
This demonstrates an Exodus output bug I've been getting. I wrote a simple marker that marks two overlapping circles in 2D. After a specified time, one of the circles is ignored. I'm hoping someone can inspect this and figure out why it is failing.

I made a test using the marker that will pass when run normally, but will diff when run with --recover. In the test, the interior of the circles are marked to refine, while the outside is set to coarsen. At some time, one of the circles is turned off, so the area inside it gets coarsened, but there's still some refinement left over due to the other circle. In addition, there's some solution being solved for that is initially localized and deliberately placed off-center. I think the combination of all these things is something that isn't currently tested.

I explicitly put the half transient and recover pair of tests in the test file so I could just run the test suite once to see this. If this gets fixed and merged I can change that.

Help!

More discussion: https://groups.google.com/forum/?hl=en#!topic/moose-users/CcmODePrA7o

ref #8890

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Oh, and I know "TwoCircleMarker" is a dumb name. Suggestions welcome.

**Comment by jessecarterMOOSE** [comment]
Well this is weird. When I test my branch locally I only get one failing test, but CIVET shows two. The second is the same test I expect to fail with recovery, but it's failing with no recovery!

**Comment by jessecarterMOOSE** [comment]
Oh, I see, the two tests that are using the same gold file are probably colliding.

**Comment by jessecarterMOOSE** [comment]
OK, this is now working (failing) like I expect - the test with coarsening and a solve passes but fails when recovered.

Not sure if it's related, but the test segfaults with distributed mesh.

**Comment by permcody** [comment]
Thanks for the test case! We can definitely work this this. 

We run all the of the MOOSE tests automatically in recover mode so you shouldn't need to build the separate tests manually to trigger this error. If you just submit a regular test making sure that it diffs both the intermediate result AND the final result, the recover testing should trigger this error. That would have also saved the problem where you had competing tests. BTW - If you have competing tests where the outputs are explicitly named, the TestHarness actually does detect that case. I was wondering why it didn't detect that here but then I realized that your first test was a "RunApp" test which doesn't name any outputs. No big deal, this is still awesome that you've boiled it down to a simple case.

**Comment by jessecarterMOOSE** [comment]
I understand that now. Really the reason why I did the explicit recover test was just so I could run the test suite once and see both the pass and fail and be done with it. Now I realize that by only putting the test in there once, it's more obvious that recovery is the problem here because those tests fail while basic tests all pass. Otherwise you have to drill down more to see what's going on, as you had to. So with that in mind, I'm removing the explicit recovery test from this PR. Should this be merged, I can squash all these commits.

And as a reminder, I think the _solution_ is fine here, because when I put a LineValueSampler VPPS through all the noise, it came out smooth. That leads me to believe it's something going on with the output. It might not be confined to Exodus.

Anyways, I'm happy to help, but I don't think I'll be able to do much to find a fix. Good luck!

**Comment by permcody** [comment]
One thought that came to my mind is the extra adaptivity step that we do after the simulation is finished. This is a long standing issue that I attempted to fix but it's rather tricky. I'm not immediately seeing why that would cause this to fail but perhaps it's related. I have an old branch on my system that actually fixes that bug but it caused on other diff that I really didn't want to track down. I don't have time to look at this right away but whoever looks at this ticket should be aware that this _might_ be the issue.

**Comment by jessecarterMOOSE** [comment]
I'm curious if this issue still persists after the latest libmesh update, but some other commits have creeped into this PR. How can I clean this up and then re-test with the new libmesh?

**Comment by permcody** [comment]
Just rebase the PR. When you do that, don't forget to run "submodule update" so that you don't accidentally leave a libmesh "un-update" in there.

**Comment by jessecarterMOOSE** [comment]
Oh well. The tests fail with recovery and segfault with distributed mesh (without recovery!) so I thought the libmesh update might help since it involves CheckpointIO and distributed mesh (not I know what the actual updates are).

**Comment by jessecarterMOOSE** [comment]
I rebased this PR after today's libmesh submodule update and still no luck. I thought there might be some improvement because I've seen some work going on in libmesh and DistributedMesh. FYI, the tests I made for this PR flat-out fail (segfault) with --distributed-mesh. With ReplicatedMesh, it only fails with --recover.

Tagging @permcody @roystgnr

**Comment by roystgnr** [comment]
At least the DistributedMesh failures look like my bailiwick.  I can replicate the failures; they're failing assertions in dbg mode.

**Comment by roystgnr** [comment]
Although, the DistributedMesh asserts look like a red herring, as far as restarts are concerned.  ```MeshCommunication::delete_remote_elements()``` is shrieking because it was specifically asked to retain certain elements but is discovering that those elements were already coarsened away.  That could probably be fixed either by fully updating the MOOSE Periodic BCs code to rely on ghosting functors instead of explicit id requests, or by updating the MeshCommunication code to handle explicitly ghosted subactive elements.  Or both, belt-and-suspenders.

Only two_circle_marker_gaussian_ic fails with me using ReplicatedMesh and --recover on 2 processors, but that might be enough to work from.

Don't expect much soon, though; I'm busy this week and on vacation next week.

**Comment by jessecarterMOOSE** [comment]
Thanks @roystgnr . This isn't a crucial issue. I can bug you about it later.

**Comment by dschwen** [comment]
Looks like this should be closed and an Issue opened (linking to jessecarterMOOSE:demo_exodus_bug)

**Comment by jessecarterMOOSE** [comment]
Sounds good @dschwen

**Comment by jessecarterMOOSE** [comment]
hmmm, I can't seem to re-open this. I'll just try to open a new one.

**Pull request closed without merging**
