### PR TITLE
Put Piecewise class back in

### LINKED ISSUE #15833: Put Piecewise back in
## Reason
`PiecewiseBase` was originally put in to provide a base class for custom piecewise functions that could be read by `IterationAdaptiveDT`. `Piecewise` was used to hold all of the typical Piecewise function input parameters, with the base class holding some of the more basic implementation details. Along the way, `Piecewise` and `PiecewiseBase` were combined, taking away that ability.

## Design
Put `Piecewise` back in!

## Impact
This will allow internal apps to work again...

### PR DESCRIPTION
**Pull request by tophmatthews**
closes #15833

### CODE REVIEW

**Comment by tophmatthews** [comment]
Well, ping @dschwen, but it doesn't matter so much until testing is back up...

**Comment by dschwen** [comment]
Maybe we can find a better name than `Piecewise` then?

**Comment by tophmatthews** [comment]
Sure, it needs to be between PiecewiseBase and all others.

**Comment by dschwen** [comment]
Maybe `PiecewiseTabularBase`. that indicates it is more specific and handles gathering the tabular data for the underlying interpolations. `Piecewise` is too clean of a name and suggests it being a user facing instantiable object... if that makes sense.

**Comment by tophmatthews** [comment]
Yeah, that sounds fine

**Comment by dschwen** [comment]
So in retrospect this seems to be a case where a bit of design documentation would be useful. The old `Piecewise` seemed like a superfluous step and since I introduced `PiecewiseLinearBase` I decided to prune it out. Your use case of programmatically created data tables did not occur to me back then. But it sure makes sense.

**Comment by tophmatthews** [comment]
Yes, that's fair enough. That info is in the issues and PR's, but it's buried for sure. Really, what would be the best, is to have had my external app tested so it was obvious. I'm going through that process now, after it's been sitting around for some time.

**Comment by tophmatthews** [comment]
Where would that doco go, in the header of the base class?

**Comment by dschwen** [comment]
I'd argue it would be best placed in the header as that's what you will look at when you refactor code. Our SQA guys might disagree though, as we link to design docs as .md from the `tests` files. But still, I'd put a comment in the class doco in the header.

**Comment by tophmatthews** [comment]
ping @dschwen

**Review by dschwen — APPROVED** [review]
Looks ok to me

**Pull request merged**
