### PR TITLE
Get time derivatives correct on timestep end output, even for linear solve types

### PR DESCRIPTION
**Pull request by lindsayad**
A different design from #27197. Will be cherry-picking some of the other commits from there soon

### CODE REVIEW

**Comment by lindsayad** [comment]
@chandanaj and @recuero if you have a moment ... I'm trying to make a change so that we compute time derivatives on `TIMESTEP_END` to try and fix a bug that @nmnobre observed (bad time derivatives) when doing an *implicit* linear solve. This caused diffs with @recuero's explicit dynamics contact tests that use `CentralDifference`.

Up until now I feel like `CentralDifference` has computed its time derivatives in a pretty odd way. Instead of using the current solution as $u_{n+1)$ it has used `u_old` as $u_{n+1}$. I've changed that now. A nice benefit of this is that we no longer need three older states for $u$. Instead we just need `u`, `u_old`, and `u_older` which feels right to me for a central difference time integrator.

What this means for result files: for simple tests like those for the framework, if you look at the regolding of the csvdiffs, the time derivatives have essentially been moved up one line, indicating that we are able to get time derivative data a step earlier now.

I would love it if you guys could look at the new gold files and tell me if they still make sense or, perhaps, even more sense than they used to

**Comment by nmnobre** [comment]
> What this means for result files: for simple tests like those for the framework, if you look at the regolding of the csvdiffs, the time derivatives have essentially been moved up one line, indicating that we are able to get time derivative data a step earlier now.

Phew, I'm glad we're still seeing this. As I mentioned in #27197 this was making me feel a bit uncomfortable, so I'm happy we'll still get to discuss this, thanks Alex!

**Comment by recuero** [comment]
Great improvement. This is one of those things I found odd about explicit integration.

The explicit dynamic contact tests appear to be hitting an assertion. I'm not sure about the cause, but those tests heavily rely on the timing and ways the derivatives were obtained. It makes complete sense they fail. Maybe the material reinitialization isn't now using the right state? 

Unrelated to this PR. Another thing I would change is the fact that old/older displacements are used to compute derivatives. That's counterintuitive to me with dynamics. Despite dynamics being based on momentum equations, you could overwrite velocities as the code stands and it'll have no effect since a new one will be computed based on old displacement states -which shouldn't be changed.

**Comment by lindsayad** [comment]
lol I'm pretty sure these failures are because of the auto-checkpointing

**Comment by lindsayad** [comment]
Oh damn I actually checked-in my change to try and prevent auto-checkpointing

**Comment by cbolisetti** [comment]
This is great, thank you @lindsayad!

**Comment by hugary1995** [comment]
Are the solutions of the regolded tests diffing?

**Comment by hugary1995** [comment]
I'll look at the gold files myself.

**Review by hugary1995 — APPROVED** [review]
The source code changes look reasonable to me. The regolded tests under the solid_mechanics directory all look more correct to me. I didn't check the regolded contact explicit dynamics tests.

**Comment by lindsayad** [comment]
failures are unrelated

**Pull request merged**
