### PR TITLE
Fixed compiler warnings: variable tiny_pivot_found set but not used

### LINKED ISSUE #11379: PetscSupport unused parameter
## Rationale

Remove unused parameter

## Description

```
/apps/geomodel/moose/projects_andy/moose/framework/src/utils/PetscSupport.C: In function âvoid Moose::PetscSupport::storePetscOptions(FEProblemBase&, const InputParameters&)â:
/apps/geomodel/moose/projects_andy/moose/framework/src/utils/PetscSupport.C:681:8: warning: variable âtiny_pivot_foundâ set but not used [-Wunused-but-set-variable]
   bool tiny_pivot_found = false;
        ^
```

## Impact

@fdkong  ?

### PR DESCRIPTION
**Pull request by fdkong**
Closes #11379

### CODE REVIEW

**Comment by fdkong** [comment]
@WilkAndy, could you check if the patch fixes your issue. Are you using an old PETSc version?

**Comment by fdkong** [comment]
It looks right for me. `tiny_pivot_found` is always under `!PETSC_VERSION_LESS_THAN(3, 7, 0)` in this patch. I actually checked this with PETSc-3.7.1.

**Comment by permcody** [comment]
NVM - you are correct. I had to look at it in split view to see it. Lots of messing CPP defines interleaved.

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Just confirming that the unused param is now fixed on my system.

**Pull request merged**
