### PR TITLE
Added scale factor parameter to PiecewiseLinearInterpolationMaterial

### LINKED ISSUE #8752: Add scale factor parameter to PiecewiseLinearInterpolationMaterial
### Description of the enhancement or error report

I will add a scale factor parameter to PiecewiseLinearInterpolationMaterial.

### Rationale for the enhancement or information for reproducing the error

Allow easier scaling of material values

### Identified impact

No impact

ping @bwspenc

### PR DESCRIPTION
**Pull request by backmari**
closes #8752

### CODE REVIEW

**Review by bwspenc — CHANGES_REQUESTED** [review]
I'm good with this.  It does need to be tested, though.  You could just add another version of one of the existing tests that scales the properties.  You wouldn't even need to add any new input or gold files.  Just use cli_args to add the scale_factor parameter, and also use it to pass in a scaled-down version of the y data, so that in the end you get the same result.

**Comment by backmari** [comment]
@bwspenc That's a good idea. Unfortunately the test harness throws an error about duplicate output files since the scale factor test outputs an Exodus file with the same name as the original test. If I change the name of the output file using cli_args, then Exodiff of course won't compare it to the original gold file. It seems inefficient to add a copy of the original gold file with a different name, but unless there are better ideas...

**Comment by bwspenc** [comment]
@backmari Sorry, I forgot to tell you one detail: If you use the 'prereq' option to make the other test that writes to that gold file a prerequisite of the second test, the testing system won't start the second one before the first one is done, and you won't have any problems.

**Comment by permcody** [comment]
Sweet! Looks like that feature I added just saved you @backmari! Figuring out those spurious failures due to race conditions are nasty, hence the smart output file checks.

**Comment by backmari** [comment]
@bwspenc @permcody Oh cool! I was wondering what was up with all those 'prereq' statements in the test. Thanks!

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
