### PR TITLE
HPC Docs

### PR DESCRIPTION
**Pull request by brandon-biggs**
## Reason
Adding additional documentation for accessing moose on HPC clusters per Refs #20071 

## Design
An updated documentation page for access MOOSE in HPC.

## Impact
Better documentation hopefully provides for less issues.

This includes all of @GiudGiud 's additions from https://github.com/GiudGiud/moose/commit/b11e25aa6971c46dc414b29ddc66eb3578a83bbd with a few modifications, mostly around altering one's `~/.bashrc` and the possible implications of that with other HPC services.

Refs #20071

### CODE REVIEW

**Comment by GiudGiud** [comment]
@brandon-biggs I ll move your commit over to my PR
you re welcome to edit my PRs anytime

**Comment by loganharbour** [comment]
> you re welcome to edit my PRs anytime

He won't be able to edit your PR by default (he doesn't have write); you'll have to add him to your fork

**Comment by GiudGiud** [comment]
Ok I just added him. Good catch.

**Comment by cticenhour** [comment]
>@brandon-biggs I ll move your commit over to my PR

@GiudGiud is this still happening? If so, should this PR be closed?

**Comment by GiudGiud** [comment]
I was going to close it once my PR is merged.

**Comment by cticenhour** [comment]
Sounds good - just checking in!

**Comment by GiudGiud** [comment]
Other HPC doc PR got merged

**Pull request closed without merging**
