### PR TITLE
Added TriangulatedMeshGenerator meshgenerator

### LINKED ISSUE #19372: Adding Triangulation Mesh Generator
## Reason
`TriangulatedMeshGenerator` creates a meshgenreator functionality for triangulating an outer boundary region surrounding an existing meshgenerator mesh.

## Design
This meshgenerator provides an interface to the 3rd party triangulation library poly2tri (https://github.com/jhasse/poly2tri). The outer boundary nodes of an input meshgenerator are extracted as the inner boundary of the triangulated region, and input parameters are used to construct a circular outer boundary of the triangulated region. These nodes are provided to the poly2tri library for triangulation, and the resulting triangles are added to the input mesh.

## Impact
This enhancement will add meshgenerator triangulation functionality. The 3rd party poly2tri library will be added as contrib.

### PR DESCRIPTION
**Pull request by aaronoaks**
Added TriangulatedMeshGenerator meshgenerator interface to the poly2tri triangulation library.

closes #19372

### CODE REVIEW

**Comment by aaronoaks** [comment]
@eshemon @shikhar413

**Comment by eshemon** [comment]
@aaronoaks  @loganharbour , just checking on the status of this, were you checking on where to put the poly2tri source code still?

**Comment by roystgnr** [comment]
Sorry for the delay; my foot-dragging more than Logan's.  We definitely don't want third-party source code dropped into a meshgenerators (even in a module) rather than somewhere we can easily keep in sync with upstream, but Logan's talked me out of my first "just stuff it in framework/contrib/p2t" impulse - we want to put it in libMesh contrib/p2t instead, so:

- We can see about creating an intermediate interface to it that matches the Triangle interface there (libMesh contrib/triangle can't be linked to by Moose binary distributions thanks to licensing incompatibility, but in stand-alone libMesh builds and non-redistributable personal Moose builds being able to do some code-to-code comparisons might be invaluable).
- We can make it an optional external dependency via libMesh configure (we went through enough hell with the diamond-dependency problem with Parmetis that we really never want to add new third-party software again without making `configure --with-that_software=/some/external/install` an option)

The trouble, though, is that I was hoping to do that in a way backed by CI ... and yet CI won't even run here because the poly2tri files aren't close to meeting Moose lint standards.  We may have to mutilate the versions here quite a bit before doing anything else, just so we can get some green checks out of Civet, so that when we do move some of the foundational bits elsewhere we can easily see if the move itself causes any regressions.

**Comment by eshemon** [comment]
Thanks @roystgnr. Is there an action item on our side?

**Comment by roystgnr** [comment]
Not unless anyone can think of objections to our current plan.  I'm just about done for the week, but I ought to be able to start hacking at this Monday morning.

**Comment by roystgnr** [comment]
I probably should have asked about this earlier, but: does anybody know much about the poly2tri developers?  I've been hoping that we could simply include their code as a submodule rather than outright forking it, but that would be a lot easier if they turn out to be amenable to us sending patches upstream.  I'd really love to have their include paths prefixed with poly2tri, in particular, not just dump them into the top level libMesh install dir.

I guess we'll find out via experiment: I put in a PR with some hopefully-less-controversial suggestions.

**Comment by loganharbour** [comment]
> we could simply include their code as a submodule rather than outright forking it

hmm.... entry-level moose users aren't used to ever having to update/init submodules to use moose. Just FYI. So this will be a significant change for some. Obviously not really for those that deal with applications.

**Pull request closed without merging**
