### PR TITLE
Ignoring boost warnings with pragma system_header

### LINKED ISSUE #15157: Suppress clang boost -wpedantic warning in stochastic_tools
## Reason
boost is creating 5mb of warnings for the debug build, this might be why grizzly tests are failing.

## Design
Add pragma around boost include to ignore -wpedantic
This is already in #include "libmesh/ignore_warnings.h" for gcc but not clang
once it is added to ignore_warnings.h, this pragma can be removed from 
stochastic_tools/include/distributions/BoostDistribution.h

# Impact
clean up debug warnings

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #15157

### CODE REVIEW

**Comment by lynnmunday** [comment]
@dschwen is this what you meant by putting the boost include into its own file with the pragma system_header?

**Comment by lynnmunday** [comment]
@bwspenc this one will ignore the warnings

**Comment by lindsayad** [comment]
So you don't need the libmesh update anymore?

**Comment by bwspenc** [comment]
@lindsayad Assuming this passes the tests, no we won't need the libmesh update.

**Comment by bwspenc** [comment]
In fact, we probably do not want the libmesh version right after we put that commit in because it broke stuff and they had to revert it.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
