### PR TITLE
Remove old deprecated methods in FluidProperties

### LINKED ISSUE #13758: Remove some deprecated methods in FluidProperties
## Reason
There are a lot of deprecated methods in the FluidProperties module that have been deprecated for a long time (up to a year). These should be removed to clean up the module.

## Design
Delete these deprecated methods from the classes.

## Impact
These have been throwing warnings for a long time, so hopefully no-one is using them

### PR DESCRIPTION
**Pull request by cpgr**
Clean up the base classes by removing deprecated methods and other bits that aren't necessary.

Most of these methods were from the PT version of SinglePhaseFluidProperties, which I've also deleted. I think PorousFlow was the only thing originally using these, but it was changed a long time ago to use the newer method names, so these shouldn't be in use anymore.

Closes #13758

### CODE REVIEW

**Comment by andrsd** [comment]
Patch for SAM was submitted.

**Review by andrsd — DISMISSED** [review]

**Comment by cpgr** [comment]
Thanks @andrsd 

There are still some other old method names there
```
rho(p, T)
h(p, T)
mu(p, T)
```
etc that I wasn't sure about removing. Do you want me to delete them as well and see if anything breaks? They have been giving `mooseDeprecated` warnings for ages as well,

**Comment by permcody** [comment]
I'd say definitely try removing them in a PR - we'll see what breaks in the resulting testing and can push on other projects accordingly.

**Comment by cpgr** [comment]
I removed the other deprecated methods and the unused `IdealGasFluidPropertiesPT` and broke SAM again 👍

**Comment by andrsd** [comment]
And I fixed SAM again 🙃, so we should be good merging these changes.

**Review by andrsd — APPROVED** [review]

**Comment by cpgr** [comment]
Thanks @andrsd

**Pull request merged**
