### PR TITLE
Made THM test more robust for parallel sweep testing

### LINKED ISSUE #24830: CIVET: 'Modules parallel sweep' failure
Testing 8d1dab4

[Modules parallel sweep](https://civet.inl.gov/job/1633017/) : **Failed**

View the results [here](https://civet.inl.gov/job/1633017/).

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #24830

### CODE REVIEW

**Comment by joshuahansel** [comment]
I need to enable the sweep testing, but I don't see a pipeline in CIVET yet.

**Comment by loganharbour** [comment]
> I need to enable the sweep testing, but I don't see a pipeline in CIVET yet.

Pushed the hook again and added the testing

**Comment by joshuahansel** [comment]
@loganharbour The failing test is because the parallel sweep apparently changes the AD container size to 250. The test is an error-reporting test about the AD container size not being large enough (assuming configured with the default size, around 50). Anything that can be done about this here? I see that `Tester` has a param `min_ad_size`, but I guess what's needed is `max_ad_size` here.

**Comment by joshuahansel** [comment]
@loganharbour I went ahead and added a `max_ad_size` parameter.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
