### PR TITLE
Restore linux testing for chigger/peacock

### PR DESCRIPTION
**Pull request by aeslaughter**
@milljm Just here for when you get to this.

### CODE REVIEW

**Comment by milljm** [comment]
Tagging to conda-moose VTK issue: https://github.com/idaholab/conda-moose/issues/66

**Review by milljm — DISMISSED** [review]

**Comment by milljm** [comment]
Pesky Mac. I wonder if that has to do with PETSc 3.12.5 being introduced.

**Comment by aeslaughter** [comment]
Well at least the linux tests pass, now I will disable the peacock/chigger tests that are failing on Mac, there have always been some.

**Review by milljm — APPROVED** [review]
👍

**Comment by permcody** [comment]
Looks like one test failed here. Not bad considering how many were unrestricted.

**Pull request merged**
