### PR TITLE
dependsOn methods added to DependencyResolver

### PR DESCRIPTION
**Pull request by WilkAndy**
I'd like feedback on this, but even if the idea and code are perfect (haha) i don't want it merged yet as i haven't yet included all the zillion dependencies.  I don't think i can use Moose's DependencyResolver for my purposes.  My Actions need to ask the question: "does Kernel K depend on Material property M?"

Refs #8870

Informing @cpgr .

### CODE REVIEW

**Comment by permcody** [comment]
Hey Andy, That class looks pretty good but the existing DependencyResolver can pretty much do exactly what you've coded up here. The only thing thing that's missing from our class is the ability to just get a Boolean response back for a given key/value pair but we could easily add that for (or you can add it yourself) and we could all continue using this one utility.

Take a look at the little test case I created for the dependency resolver:
https://github.com/idaholab/moose/blob/devel/unit/src/DependencyResolverTest.C#L19-L42

You can put in several items (it's templated, so items can be strings, integers, or even objects for a given instance) then get them out in the "correct" order. We just need to add the Boolean interface so you can ask the resolver if something depends on something else.

Now the second part of the pipe dream is populating this data structure. For now, you are going to do it with static lists which is a good start. Later, we'd like to use MOOSE to build these lists for you. When a kernel calls "getMaterialProperty", or "getPostprocessorValue" we should capture that. I've thought about this a lot and even changed every interface in MOOSE a year or so ago so that we'd at least be able to figure that part out. Then it's all about reporting and using that information in the simulation. 

For now, I suggest you start with the dependency resolver and just add your Boolean API that gives you what you need.

**Comment by WilkAndy** [comment]
OK, i'll give that all a try.  Thanks for your guidance, @permcody ,

a

**Comment by WilkAndy** [comment]
Hi @permcody .  If this is OK, could you merge it so i can use this stuff today?

a

**Review by permcody — APPROVED** [review]
Looks good! Thanks

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Comment by WilkAndy** [comment]
@permcody, i could have added a "dependsOn" check inside insertDependency to prevent cyclic dependency.  Cyclic dependency could make the recursion inside dependsOn go forever.  I'll let you add the check if you want to.  For me, i'll make sure i never construct a cyclic graph!

**Comment by permcody** [comment]
Right. Please reopen that ticket and note this observation so we can take
care of it. Thanks!

**Pull request merged**
