### PR TITLE
Use just short name for naming objects in mortar heat transfer action…

### PR DESCRIPTION
**Pull request by recuero**
Refs #23869

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
I wasn't trying to make you do more work. I was mostly trying to understand the static counter design. If you make this change, should we do an error check to ensure that someone doesn't try to add multiple UOs of the same `MortarGapHeatTransfer::UserObjectToBuild`?

**Comment by recuero** [comment]
Yeah, that's in order.

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Review by lindsayad — APPROVED** [review]

**Comment by recuero** [comment]
@loganharbour This inconsistent tag business appears to prevent getting a coverage number: Should we just invalidate coverage? (Doing so)

**Comment by lindsayad** [comment]
great success

**Pull request merged**
