### PR TITLE
Updated syntax of example problem for elasticity driven grain growth with an EBSD reconstructed IC

### LINKED ISSUE #7190: Fixup EBSD example in the combined module
### Description of the enhancement or error report

This example is out of date. It prints a warning and may not run properly

### Rationale for the enhancement or information for reproducing the error

Run the EBSD example.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Localized to this input file.

### PR DESCRIPTION
**Pull request by tonkmr**
I updated the syntax of EBSD_reconstructoin_grain_growth_mech.i so it runs again. Closes #7190.

### CODE REVIEW

**Comment by tonkmr** [comment]
@permcody in this example, the ebsd grain numbers don't match the GrainTracker unique IDs

**Comment by permcody** [comment]
True - but the problem is with the centers not the GrainTracker itself:

```
EBSD Grain 0 (x,y,z)=( 1.27155, 0.762931,        0)
EBSD Grain 1 (x,y,z)=( 4.65709,   1.3242,        0)
EBSD Grain 2 (x,y,z)=( 1.78716,  3.85087,        0)
EBSD Grain 3 (x,y,z)=(     6.7,    2.025,        0)
EBSD Grain 4 (x,y,z)=(  6.5125,   3.1125,        0)
EBSD Grain 5 (x,y,z)=( 4.20833,  3.20833,        0)
EBSD Grain 6 (x,y,z)=( 5.30599,  5.23047,        0)
EBSD Grain 7 (x,y,z)=( 2.61806,  6.47222,        0)
EBSD Grain 8 (x,y,z)=(0.717105,  6.59868,        0)
Assigning center 0 (x,y,z)=( 1.27155, 0.762931,        0) absolute distance: 0.706791
Assigning center 1 (x,y,z)=( 4.65709,   1.3242,        0) absolute distance: 0.788941
Assigning center 2 (x,y,z)=( 1.78716,  3.85087,        0) absolute distance: 0.719939
Assigning center 3 (x,y,z)=(     6.7,    2.025,        0) absolute distance: 0.474342
Assigning center 4 (x,y,z)=(  6.5125,   3.1125,        0) absolute distance: 0.530625
Assigning center 5 (x,y,z)=( 4.20833,  3.20833,        0) absolute distance: 0.0589256
Assigning center 6 (x,y,z)=( 5.30599,  5.23047,        0) absolute distance: 0.82202
Assigning center 7 (x,y,z)=( 2.61806,  6.47222,        0) absolute distance: 0.472273
Assigning center 8 (x,y,z)=(0.717105,  6.59868,        0) absolute distance: 0.625104
```

Grains 2 and 4 are swapped. The centers here exactly match the actual grain centers...

**Comment by tonkmr** [comment]
This isn't the same as the file I emailed to you earlier. This is a much larger problem with 111 grains and the differences are fairly substantial. It might be that something is just set up wrong, but can you run it and see what you think?

**Comment by tonkmr** [comment]
Note that the EBSD numbering is a separate issue from the one addressed in the merge request. It can be merged even before we figure out the numbering issue.

**Pull request merged**
