### PR TITLE
Illustrates the Impossible problem of cutting dt from Materials

### PR DESCRIPTION
**Pull request by WilkAndy**
This illustrates the Impossible error experienced by myself and others.  A Material calls

throw MooseExcecption("Something happened, dt needs to be reduced")

and MOOSE responds with Impossible.  Could someone take the time to fix this bug, please?

In this case, the material is ComputeLinearElasticStress_CUT_DT, that attempts to cut the timestep if stress(1, 1) > 1.
The test file that may be used to obtain the 'Impossible' error is push.i

Refs #3789

### CODE REVIEW

**Comment by permcody** [comment]
Excellent - Thanks! We'll definitely take a look at this. 

@jwpeterson any change you can get to this?

**Comment by jwpeterson** [comment]
Yes, I will take a look.

**Comment by jwpeterson** [comment]
If I comment out the try/catch block around `computeResidualType` in `FEProblem::computeResidual()`, we can get a better stack trace for your error (so we can see where it's coming from) which in this case appears to be from `AuxiliarySystem::computeElementalVars(ExecFlagType)`.  I'll have to see about wrapping all calls to this function in try/catch blocks and whether or not we can recover from them. 

```
Stack frames: 26
0: 0   libmesh_opt.0.dylib                 0x000000010174a51d libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1533
1: 1   libmesh_opt.0.dylib                 0x000000010174b07e libMesh::write_traceout() + 670
2: 2   libmesh_opt.0.dylib                 0x000000010173536b libMesh::libmesh_terminate_handler() + 11
3: 3   libc++abi.dylib                     0x00007fffa0c3219e _ZSt11__terminatePFvvE + 8
4: 4   libc++abi.dylib                     0x00007fffa0c31c12 _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
5: 5   libmoose-opt.0.dylib                0x0000000100d72818 FEProblem::checkExceptionAndStopSolve() + 344
6: 6   libmoose-opt.0.dylib                0x0000000100d1778e AuxiliarySystem::computeElementalVars(ExecFlagType) + 702
7: 7   libmoose-opt.0.dylib                0x0000000100d17022 AuxiliarySystem::compute(ExecFlagType) + 226
8: 8   libmoose-opt.0.dylib                0x0000000100d73290 FEProblem::computeResidualType(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, Moose::KernelType) + 512
9: 9   libmoose-opt.0.dylib                0x0000000100e83a59 Moose::compute_residual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, libMesh::NonlinearImplicitSystem&) + 121
10: 10  libmesh_opt.0.dylib                 0x0000000101b9a1a3 __libmesh_petsc_snes_residual + 659
11: 11  libpetsc.3.6.dylib                  0x0000000104d642d4 SNESComputeFunction + 324
12: 12  libpetsc.3.6.dylib                  0x0000000104d97db6 SNESSolve_NEWTONLS + 422
13: 13  libpetsc.3.6.dylib                  0x0000000104d693b3 SNESSolve + 851
14: 14  libmesh_opt.0.dylib                 0x0000000101b9bb0a libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int) + 634
15: 15  libmesh_opt.0.dylib                 0x0000000101bdc861 libMesh::NonlinearImplicitSystem::solve() + 353
16: 16  libmoose-opt.0.dylib                0x0000000100e84ef3 NonlinearSystem::solve() + 355
17: 17  libmoose-opt.0.dylib                0x0000000100d72625 FEProblem::solve() + 117
18: 18  libmoose-opt.0.dylib                0x000000010116f6c6 TimeStepper::step() + 22
19: 19  libmoose-opt.0.dylib                0x0000000100f12ad2 Transient::solveStep(double) + 626
20: 20  libmoose-opt.0.dylib                0x0000000100f1283e Transient::takeStep(double) + 174
21: 21  libmoose-opt.0.dylib                0x0000000100f125d9 Transient::execute() + 89
22: 22  libmoose-opt.0.dylib                0x0000000100e5d676 MooseApp::run() + 118
23: 23  tensor_mechanics-opt                0x00000001008e2507 main + 135
24: 24  libdyld.dylib                       0x00007fffa15015ad start + 1
25: 25  ???                                 0x0000000000000003 0x0 + 3
traceout_0_83961.txt (END)
```

**Comment by permcody** [comment]
It's slightly more involved than that. This is happening in the PETSc callback so we need to widen the net to properly terminate the solve. Take a look at `Nonlinear::computeResidual`. I think @friedmud put this in and probably thought this was good enough to catch all the exceptions from the `compute_residual` callback but clearly it is not. 😄 

I think some of the real try/catch logic in NonlinearSystem needs to be backed out to the callback entry point to make sure we get all the extra junk that gets computed (and could potentially throw).

**Comment by jwpeterson** [comment]
Closing this, I think it has been fixed (and the test code included) in #7751.

**Pull request closed without merging**
