### PR TITLE
Allow DiracKernels to work in non-cartesian coordinate systems

### LINKED ISSUE #20107: Allow DiracKernels to work in non-cartesian coordinate systems
## Reason

Currently the DiracKernel residual is only valid in cartesian. However, we may want to add "point" sources in rz or spherical coords as well.

## Design

Multiply the residual in DiracKernel by the coordinate transformation factor.

## Impact

New capability.

### PR DESCRIPTION
**Pull request by hugary1995**
close #20107

### CODE REVIEW

**Comment by hugary1995** [comment]
These are the diffs:
```
    DIFF porous_flow/test:recover.theis_full FAILED (CSVDIFF)
    DIFF porous_flow/test:fluidstate.theis FAILED (CSVDIFF)
    DIFF heat_conduction/test:gap_heat_transfer_htonly.RZ FAILED (EXODIFF)
    DIFF porous_flow/test:dirackernels.theis_rz FAILED (CSVDIFF)
    DIFF porous_flow/test:fluidstate.theis_tabulated FAILED (CSVDIFF)
    DIFF heat_conduction/test:gap_heat_transfer_htonly.ZR FAILED (EXODIFF)
    DIFF heat_conduction/test:gap_heat_transfer_htonly.RSpherical FAILED (EXODIFF)
    DIFF porous_flow/test:dirackernels.theis3 FAILED (CSVDIFF)
    DIFF porous_flow/test:energy_conservation.heat04_rz FAILED (CSVDIFF)
    DIFF heat_conduction/test:gap_heat_transfer_mortar.large_gap_heat_transfer_test_sphere FAILED (CSVDIFF)
```

I looked at the heat conduction diffs, for the three of them that have analytical solutions, the postprocessor values are slightly better than before.

I am not sure about the porous flow ones. Can @cpgr or @WilkAndy take a look to see if the failing tests give better or worse results?

**Comment by cpgr** [comment]
It looks like the Dirac kernel in the failing porous flow tests isn't injecting anything anymore. I think they are all RZ meshes with the point source at the origin like so

````
[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 20
  xmax = 100
  bias_x = 1.05
[]

[Problem]
  coord_type = RZ
[]

[DiracKernels]
  [sink]
    type = PorousFlowSquarePulsePointSource
    point = '0 0 0'
    mass_flux = -0.16E-3
    variable = pp
  []
[]

etc
```

So this doesn't work anymore following these changes?

**Review by loganharbour — CHANGES_REQUESTED** [review]
Yeah, I was thinking about this over the weekend. if we're in either rz or rspherical with `r = 0`, we should not multiply by the coordinate transformation. And we need docs to describe this.

**Comment by hugary1995** [comment]
@cpgr Thank for looking into this! Yeah, this was an issue I was expecting. I think there is nothing wrong with your test input, I'll have to think about it.

@loganharbour I completely agree. I'll try to address this and add docs.

**Comment by bwspenc** [comment]
Doesn't the node/face (`quadrature=false`) version of thermal contact use DiracKernels? It seems like those results would be totally off if we weren't doing something to handle this already.

**Comment by bwspenc** [comment]
> 

It looks like

**Comment by hugary1995** [comment]
@bwspenc How do you want to move this forward? I would prefer someone with access to internal apps to take over.

**Comment by loganharbour** [comment]
@hugary1995 can you make the change I suggested? I think then we can find someone to take care of the internal apps

**Comment by bwspenc** [comment]
@hugary1995 Yeah, we can take this over. We'll talk with the team about the consequences of this.

**Comment by dschwen** [comment]
We've talked about this in standup. Consensus is that we do not like dealing with the `r=0` case in the above way. We should rather have a special DiracKernel class that is specifically for source terms at the origin or axis of rotation. Furthermore this needs an explicit opt-in from users. I would feel very uncomfortable changing such a basic behavior without making sure potential users are aware of the change.

**Comment by YaqiWang** [comment]
Sounds to me just needing to add a boolean parameter like `coordinate_transformation_included` and default it to true, i.e. the current behavior. Users can use this parameter to include the transformation if they want.

**Pull request closed without merging**
