### PR TITLE
Update PETSc submodule to 3.12

### LINKED ISSUE #14108: Upgrade PETSc submodule to 3.12
## Reason

PETSc 3.12 was released a couple of hours ago.  It contain some new features we are quite interested in. 

## Design

Update PETSc submodule to support this release so that MOOSE users can try these cutting-edge features.

## Impact

Advanced MOOSE users

### PR DESCRIPTION
**Pull request by fdkong**
Let's see how many tests will fail 

Closes #14108

### CODE REVIEW

**Comment by fdkong** [comment]
Check 64bit tests as well because partitioning results are likely different.

**Comment by lindsayad** [comment]
I like the upgrade!

**Comment by fdkong** [comment]
> I like the upgrade!

Yes. We want to try the cutting-edge PETSc

**Comment by fdkong** [comment]
@lindsayad  Ready for review

**Review by lindsayad — APPROVED** [review]
LGTM!

**Pull request merged**
