### PR TITLE
Added error checking to mesh stitching

### LINKED ISSUE #23366: Error checking for mesh stitching
## Reason
Libmesh's stitch_meshes and stitch_surfaces functions have an optional parameter 'enforce_all_nodes_match_on_boundaries' that, if true, throws an error if the number of nodes on the specified boundaries don't match the number of nodes that were merged. This parameter is false by default, meaning that even if two meshes are not stitched together properly, the program will continue to run without error.

## Design
The suggestion is to change the value of 'enforce_all_nodes_match_on_boundaries' to 'true' in all stitch_meshes and stitch_surfaces calls.

## Impact
This change will result in more understandable errors regarding mesh stitching.

### PR DESCRIPTION
**Pull request by pbehne**
Libmesh's stitch_meshes and stitch_surfaces functions have an optional parameter 'enforce_all_nodes_match_on_boundaries' that, if true, throws an error if the number of nodes on the specified boundaries don't match the number of nodes that were merged.
This parameter is false by default.
This commit changes this parameter to true for all instances of stitch_meshes and stitch_surfaces used in the framework.

Closes #23366

### CODE REVIEW

**Comment by joshuahansel** [comment]
Hm, looks like some recent commits by @GiudGiud made it onto your PR somehow.

**Comment by pbehne** [comment]
@loganharbour

**Comment by GiudGiud** [comment]
Just cherry-pick your commit on top of upstream/devel
whatever rebase you did must have gone wrong

**Comment by miaoyinb** [comment]
Does it throw an error now if only a fraction of the boundary needs to be stitched? I think this is the reason why a number of reactor module tests fail.

**Comment by GiudGiud** [comment]
Yeah that part was happening. Patrick has got a fix for this now

**Pull request closed without merging**
