### PR TITLE
Print longest running DAGs along with Jobs

### LINKED ISSUE #20916: Display longest running groups
## Reason
While we have a list of longest running individual jobs, a user was interested in longest running groups (the length an entire test spec file took). This may help folks 'break up' their test spec files if they believe they should.

## Design
Using information already being stored in the job DAG, it shouldn't be difficult to sum up the total time that DAG spent running its jobs.

## Impact
Civet test results will display longest running DAGs

### PR DESCRIPTION
**Pull request by milljm**
When using the --longest-jobs option, append also the longest running DAGs

Closes #20916

### CODE REVIEW

**Comment by milljm** [comment]
Example output:
```pre
Ran 159 tests in 17.7 seconds. Average test time 0.6 seconds, maximum test time 1.6 seconds.
159 passed, 2 skipped, 0 pending, 0 failed

10 longest running jobs:
--------------------------------------------------------------------------------
kernels/ad_vector_couple.ad_vector_couple .......................... OK [1.616s]
kernels/ad_jacobians.testbodyforce-adfunction-jac .................. OK [1.594s]
kernels/ad_vector_couple.ad_grad_vector_couple ..................... OK [1.533s]
kernels/vector_fe.lagrange_vec ..................................... OK [1.530s]
kernels/ad_mat_diffusion.1D/ad_1D_transient ........................ OK [1.442s]
kernels/ad_mat_diffusion.1D/ad_1D_transient_jacobian ............... OK [1.278s]
kernels/jxw_grad_test_dep_on_displacements.jxw_jacobian_cylindrical  OK [1.242s]
kernels/ode.test_sys_impl .......................................... OK [1.231s]
kernels/simple_diffusion.diffusion_200x200 ......................... OK [1.188s]
kernels/ad_mat_diffusion.1D/1D_transient ........................... OK [1.103s]

10 longest running spec files:
--------------------------------------------------------------------------------
kernels/vector_fe                                                       [8.845s]
kernels/hfem                                                            [7.983s]
kernels/simple_transient_diffusion                                      [6.531s]
kernels/ad_mat_diffusion                                                [5.574s]
kernels/ode                                                             [4.966s]
kernels/jxw_grad_test_dep_on_displacements                              [4.300s]
kernels/conservative_advection                                          [4.253s]
kernels/ad_vector_couple                                                [3.962s]
kernels/array_kernels                                                   [3.943s]
kernels/ad_coupled_value                                                [3.638s]
```

**Comment by YaqiWang** [comment]
`longest running spec files` => `longest running spec folders` and `longest running jobs` => `longest running tests`?

**Comment by loganharbour** [comment]
> `longest running spec files` => `longest running spec folders` and `longest running jobs` => `longest running tests`?

- Longest running jobs
- Longest running specs

Seems sufficient to me

**Comment by milljm** [comment]
The TestHarness searches for, and uses `tests` by default. Since you can't have two files of the same name exist in the same directory... this should suffice. If you have a test spec file located in a child directory, it should print that extra path.

Actually I am glad this was brought up. I arbitrary decided to include two parent directories when printing the location of where the test spec file lies. So if you have like named directories, it would be difficult to determine what is what:

```pre
/path/to/foo/tests
/path/to/foo/to/foo/tests
```
would end up printing `to/foo` twice. I don't have good way around this.

**Comment by milljm** [comment]
@loganharbour brought up a good point about how displaying a group run is a bit meaningless when/if the group was run in parallel. The idea behind this PR, is to make the user aware of what spec files are taking up the most 'time'. But is 'time' the right word?

Consider a test spec file with 100 tests in it, and each test theoretically takes 1 second to complete. If I ran this on a machine with 100 available cores, then in reality I should see this test spec file taking 1 second to complete.

I am asking for some input on how to proceed. In its current state the print out isn't very accurate, while still offers helpful insights into possible problem spec files.

**Comment by permcody** [comment]
I believe that you should label your longest running "folders" as "user-time". That means something specific in Linux-land (wall time). Two other minor suggestions:

- Consider putting the "spec" file in the name 
```
outputs/format/tests                                                 [1699.700s]
mortar/continuity-3d-non-conforming/tests                            [415.617s]
```

- Consider renaming that section to "longest running folders"

This has a little more flexible meaning if you were to run with `-i assessments` or some other TestHarness input file.

**Comment by loganharbour** [comment]
I'm fine with the latter.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
