### PR TITLE
Fluid-structure interaction capabilities using acoustics

### LINKED ISSUE #15712: Fluid-structure interaction capabilities using acoustics
## Reason
Currently, capabilities to simulate fluid-structure interaction do not exist.

## Design
Fluid-structure interaction is implemented using the acoustics formulation, which ignores the nonlinear term in the Navier-Stokes equation and performs an Eulerian analysis. The following kernels/bcs are implemented:

* Acoustic inertia kernel to simulate the double time derivative of the fluid pressure
* An interface kernel between fluid and structure to enforce displacement and pressure/stress continuity
* Free surface fluid BC to simulate gravity waves over the fluid

## Impact
These capabilities are needed to simulate the dynamic response of advanced reactors with molten fuel, among other applications.

### PR DESCRIPTION
**Pull request by somu15**
Currently, capabilities to simulate fluid-structure interaction do not exist. Fluid-structure interaction is implemented using the acoustics formulation, which ignores the nonlinear term in the Navier-Stokes equation and performs an Eulerian analysis. The following kernels/bcs are implemented:

* Acoustic inertia kernel to simulate the double time derivative of the fluid pressure
* An interface kernel between fluid and structure to enforce displacement and pressure/stress continuity
* Free surface fluid BC to simulate gravity waves over the fluid

These capabilities are needed to simulate the dynamic response of advanced reactors with molten fuel, among other applications.

Closes #15712

### CODE REVIEW

**Comment by somu15** [comment]
@cbolisetti @lynnmunday @fdkong @lindsayad Can you please review this PR?

**Review by lindsayad — CHANGES_REQUESTED** [review]
@fdkong I am going to push your FSI module creation to this PR. Then @somu15 I'm going to ask that you migrate anything that has to do with interfacing between fluid and structure into that module.

**Comment by somu15** [comment]
@lindsayad Sounds good.

**Comment by lindsayad** [comment]
Ok I just rebased this branch onto next and cherry-picked @fdkong 's FSI commits, so @somu15 make sure to reset your local branch to match your remote (e.g this). Should be good to start migrating things over to the FSI module now.

**Comment by lindsayad** [comment]
Are you guys waiting on a review? I would assume so. @somu15 can you resolve the merge conflict please?

**Comment by somu15** [comment]
> Are you guys waiting on a review? I would assume so. @somu15 can you resolve the merge conflict please?

I resolved this conflict by removing large_media which accidentally got in. I think civet should be back online for the merge conflict to be removed.

**Comment by somu15** [comment]
@lindsayad @cbolisetti I have removed the merge conflict.

**Comment by lindsayad** [comment]
No

**Pull request closed without merging**
