### PR TITLE
Add conda instructions

### PR DESCRIPTION
**Pull request by milljm**
Begin adding instructions for using MOOSE with Anaconda.

The resulting link will be:
```pre
-site address-/getting_started/installation/conda.html
```
_At this time, we do not want a link to these instructions._

Refs #14515

### CODE REVIEW

**Comment by permcody** [comment]
This is a good start but we probably should include a little detail on what to do if you have a package_builder package already installed.

**Comment by milljm** [comment]
Site link with the actual document I need scrutinized:
[Anaconda MOOSE Environment](https://mooseframework.inl.gov/docs/PRs/14516/site/getting_started/installation/conda.html)

**Comment by permcody** [comment]
I followed these instructions and they worked for me. I definitely miss icecream and autojump though! Will have to try to install the former myself and see if I can get it working. The latter was easy to get back. You might want to mention a few more details on the miniconda install (e.g. should they avoid anaconda? Does it matter where they install it, single user or multi-user?). Maybe you don't know the answers to all those questions yet, that's fine, these will evolve. Good start!

**Comment by milljm** [comment]
I have not had any success building a payload containing Conda compilers that Icecream was able to redistribute. I _can_ build the actual Icecream binaries however, and will make that package available for you guys: `conda install -c idaholab icecream`.

**Comment by milljm** [comment]
@permcody Autojump has been added. You have to install it separately:

```
conda install -c idaholab autojump
```

Do we want this to be automatically installed via moose-env?

**Review by permcody — APPROVED** [review]

**Pull request merged**
