### PR TITLE
Modify app.mk for compilation in Bash on Ubuntu on Windows

### PR DESCRIPTION
**Pull request by hillyuan**
Compilation of all modules in Bash On Ubuntu On Windows fails due to 
----
undefined reference to 'XXXXApp::XXXXApp(InputParameters const&)'
......
----
which are supposed to be included in library libXXX-opt.so. This problem is solved by changing the sequence of the list of linking libraries defined in app.mk.

By the way, compilation in MSYS2/Mingw in also confirmed while above modification is needed.

### CODE REVIEW

**Comment by permcody** [comment]
Why did you close this? This should be reviewed and possibly merged.

**Comment by permcody** [comment]
Looks like you may have converted this to Windows line endings. The actual diff looks fine and I wouldn't mind testing this. In fact, I think your change is correct!

**Comment by permcody** [comment]
@brianmoose - Perhaps you can take this PR over if the original poster doesn't resubmit. I think that the test app probably should come first since it depends on the main app. If this links properly on Mac and Linux AND fixes the Windows build, why not?

**Comment by brianmoose** [comment]
@hillyuan Could you put something like "refs #000" in one of your commit messages? This will allow our testing to get started.

**Comment by brianmoose** [comment]
I agree with @permcody that this looks correct.
@hillyuan You can do something like `git commit --amend` then add "refs #000" in the commit message. You then force push (`--force`) the branch back up to github. Our testing system requires a ticket reference (ie #<some number>) in a commit message. This PR doesn't have one which is why we use #000.

**Comment by permcody** [comment]
Superseded by #10127.

**Pull request closed without merging**
