### PR TITLE
Add the Physics system in support of a multiphysics component definition

### PR DESCRIPTION
**Pull request by GiudGiud**
**What is a Physics?**
A Physics object will define nearly everything we need to solve an equation on a given mesh. Essentially kernels and BCs for traditional cases, but we also have a bunch of UOs, helper materials, etc, for some equations that we dont want to burden the user with. This is what we do in our current Action-based workflows. We may even want to set the executioner for the user, and a Physics should let us do that.
The new things are
- providing a consistent set of APIs for interacting with components, and for parameter checking, ghosting, anything that is relevant for every equation and implemented only once at the PhysicsBase class
- a persistent object that we can interact with in a meaningful and general manner (unlike an action)  and has a global view of the physics. I know this is pretty abstract, but in the context of more dynamic simulations where physics change / react to external inputs, I think it can help. 
An example of a meaningful interaction could be getting two components to interact though a new 'ValueJunction' component that sets up Dirichlet BCs between the two component's Physics' variables. Same idea for exchanging fluxes. We can query from the Physics what functor 'fluxes' are and how to set its BCs.
- It helps us organize physics that are related. For example, we have very many flow types for NS, and we dont want to implement them all in a single action file, or implement the same routines in multiple actions (for NSFE-CG, NSFV, NSFV-CGDG etc).

**In this PR:**
- a base class for Physics that defines the APIs you need for defining physics working on a mesh and on components
- a heat conduction physics class that is able to add its kernels and bcs
- a tree of classes for NSFV physics that makes it clear how we would want to add the NSFE part if we want to
- a full implementation of WCNSFV flow, energy, turbulence and scalar equations, working on both meshes & file mesh components

**What is good about this PR**
- much shorter action code for NSFV, also not a header
- potential for any physics on multiphysics components, instead of what we have which hardcodes a Physics
- for such components, potentially reduced number of objects, components forward their needs down to Physics objects, which can define less objects to solve the simulation
- still potential for hardcoded physics-component, which are kind of easier to create imo

**What's left:**
- [ ] reduce code duplication
  - in the routine definitions with the NSFV action
  not sure how possible that will be since they rely on class attributes
  - please suggest
- [x] Figure out junction between (file) mesh components to show it s still possible with Physics
- [x] Figure out junction between a NSFV and a THM component
- [ ] Make a decision on momentum BC parameters. they are used by advection physics, which is why they are at the base class level. But they could be moved down to the FlowPhysics class, in which case energy/advection would always NEED to be created in tandem with a (potentially inactive) FlowPhysics
- [ ] Add documentation

**Check that it works:**
- multi-component case
- multi-physics multi-component case

**Other checks**
- parameter groups

**Areas for future expansion:**
More physics?
1D flow into a Physics?
Grow outside of the file mesh component and do any kind of mesh?

Early PR so @joshuahansel and @grmnptr can take a look at where I went building on their work

Reminder of the previous syntax for classical Mesh-based (as opposed to Component-based) solves
```
[Modules]
  [NavierStokesFV]
    compressibility = 'weakly-compressible'
    add_energy_equation = true

    density = 'rho'
    dynamic_viscosity = 'mu'

    initial_velocity = '${inlet_v} 1e-15 0'
    initial_pressure = '${outlet_pressure}'

    inlet_boundaries = 'left'
    momentum_inlet_types = 'fixed-velocity'
    momentum_inlet_function = '${inlet_v} 0'

    wall_boundaries = 'top bottom'
    momentum_wall_types = 'noslip noslip'

    outlet_boundaries = 'right'
    momentum_outlet_types = 'fixed-pressure'
    pressure_function = '${outlet_pressure}'

    mass_advection_interpolation = 'average'
    momentum_advection_interpolation = 'average'
  []
[]
```
New syntax for Mesh-based
```
[Physics]
  [flow]
    type = WCNSFVFlowPhysics
    # velocity_names = 'vel_x vel_y'

    density = 'rho'
    dynamic_viscosity = 'mu'

    initial_velocity = '${inlet_v} 1e-15 0'
    initial_pressure = '${outlet_pressure}'

    inlet_boundaries = 'left'
    momentum_inlet_types = 'fixed-velocity'
    momentum_inlet_function = '${inlet_v} 0'

    wall_boundaries = 'top bottom'
    momentum_wall_types = 'noslip noslip'

    outlet_boundaries = 'right'
    momentum_outlet_types = 'fixed-pressure'
    pressure_function = '${outlet_pressure}'

    mass_advection_interpolation = 'average'
    momentum_advection_interpolation = 'average'
  []
[]

```

Josh lays out the syntaxes possible for the Components in this reply:
https://github.com/idaholab/moose/pull/25704#issuecomment-1762022144

### CODE REVIEW

**Comment by loganharbour** [comment]
I think this is already a lot to review, I would advise working on another task until a few eyes get to this

**Comment by GiudGiud** [comment]
I kind of want to prove it works and it's useful, then cut it up in as many pieces I can manage for the review. I m trying hard to be careful with cleanly separated commits which will help the split.

I needed to make a PR to get CIVET to run valgrind on it. Valgrind is hard to get going on macs

**Comment by joshuahansel** [comment]
The basic idea is certainly something we've considered before. We've just struggled in deciding where to draw the lines of what a "Physics" is.

So for what you have, would this basically replace the NSFV action?

**Comment by GiudGiud** [comment]
Essentially. We would deprecate it and keep further developments in that system instead

**Comment by joshuahansel** [comment]
I think at the least, this is on the right track. I say we start by agreeing on a precise definition of what we think a Physics object should be. Here's my thoughts:

- spatially discretized PDE(s) themselves, with no mesh
- optional specification of ICs and BCs

When using with components, I think we could use the "pass a Physics" approach in the generic mesh components (`Component1D`, `Component2D`, and `FileMeshComponent`) and use the hard-coded "build a Physics" approach in our existing components like `FlowChannel1Phase`, which would build a Physics like `FlowModel1Phase`.

**Comment by GiudGiud** [comment]
> - spatially discretized PDE(s) themselves, with no mesh

Yes. In an ideal world we would have 'Physics' just be the equation, then a 'Discretization' block that does the discretization for us. It's unrealistic in MOOSE. I tried having a nested discretization block, but ran into basic problems like 'you need to know the physics to know what discretization parameters make sense, you need to know the discretization to know which physics object should be created (so you can then query the parameters, dependency issue!)'

> - optional specification of ICs and BCs

agree. I think for NS, if you dont handle BCs you only do half the work so it has to be there

> When using with components, I think we could use the "pass a Physics" approach in the generic mesh components (Component1D, Component2D, and FileMeshComponent) and use the hard-coded "build a Physics" approach in our existing components like FlowChannel1Phase, which would build a Physics like FlowModel1Phase.

This is where I ended up. I have a FileMeshPhysicsComponent that can take any Physics, but then the user has to specify all the relations between the component and the physics in the Physics block (e.g. which boundaries are the inlet, etc)
And I made a physics-hardcoded FileMeshWCNSFVComponent where the Physics parameters live on the component, which lets you put the parameters nearest to where they are used.

**Comment by joshuahansel** [comment]
Yeah I know the challenge with having a Discretization block. I think it's possible, but you are usually going to end up with Physics-specific Discretizations, e.g., `WCNSFlowPhysicsFV`, which is ok, but I don't see much advantage to making the split.

**Comment by joshuahansel** [comment]
> The big downside with the latter is that you end up writing almost an entire input file on every component, and also you create way more objects than you would need with the former

Yeah this is why I like having both options. You lose some flexibility with the "pass the Physics" approach. For instance, if you want to have different ICs on your different pipes, you need the "build the Physics" approach.

**Comment by GiudGiud** [comment]
> Yeah this is why I like having both options. You lose some flexibility with the "pass the Physics" approach. For instance, if you want to have different ICs on your different pipes, you need the "build the Physics" approach, or at least just creating multiple copies of your Physics object, with different ICs.

So for initialization I was thinking either:
- we programmatically initialize the simulations rather than let the user do it. It s not hard to conserve mass by making the velocity inversely proportional to the area of the pipe for a first guess
- we specify the physics, but let the user override the physics on some parameters. This might be tricky to make not-confusing but I d be open for someone to try

**Comment by joshuahansel** [comment]
> we programmatically initialize the simulations rather than let the user do it. It s not hard to conserve mass at first order by making the velocity inversely proportional to the area of the pipe for a first guess (can even take density(T) into account)

Not sure what you mean by this, but I'd guess this doesn't sound too practical.

> we specify the physics, but let the user override the physics on some parameters. This might be tricky to make not-confusing but I d be open for someone to try

This does sound like it'd get messy/confusing. I'd prefer to stick with just having the two options like you have.

**Comment by joshuahansel** [comment]
@loganharbour You were asking for an example. Here's one in the context of THM. Note that I'm proposing to have both component options ("pass a physics" and "build a physics").

A current input file (same input file for "build a physics"):
```
[Components]
  [pipe1]
    type = FlowChannel1Phase
    # some mesh params
    position = '0 0 0'
    orientation = '1 0 0'
    length = 1.0
    n_elems = 100

    # some "physics" params
    A = 1.0
    f = 0.1
    initial_p = 1e5
    initial_T = 500
    initial_vel = 1
  []
  [pipe2]
    type = FlowChannel1Phase
    position = '5 0 0'
    orientation = '0 1 0'
    length = 5.0
    n_elems = 50

    # pipe2 has same physics params as pipe1
    A = 1.0
    f = 0.1
    initial_p = 1e5
    initial_T = 500
    initial_vel = 1
  []
  [pipe3]
    type = FlowChannel1Phase
    position = '1 0 0'
    orientation = '1 0 0'
    length = 0.2
    n_elems = 200

    # pipe3 has different physics params than pipe1 and pipe2
    A = 0.5
    f = 0.0
    initial_p = 2e5
    initial_T = 300
    initial_vel = -2
  []
[]
```

A "pass a physics" input file:
```
[Physics]
  [flow_modelA]
    type = FlowModel1Phase
    A = 1.0
    f = 0.1
    initial_p = 1e5
    initial_T = 500
    initial_vel = 1
  []
  [flow_modelB]
    type = FlowModel1Phase
    A = 0.5
    f = 0.0
    initial_p = 2e5
    initial_T = 300
    initial_vel = -2
  []
[]

[Components]
  [pipe1]
    type = Component1D
    position = '0 0 0'
    orientation = '1 0 0'
    length = 1.0
    n_elems = 100

    physics = 'flow_modelA'
  []
  [pipe2]
    type = Component1D
    position = '5 0 0'
    orientation = '0 1 0'
    length = 5.0
    n_elems = 50

    physics = 'flow_modelA'
  []
  [pipe3]
    type = Component1D
    position = '1 0 0'
    orientation = '1 0 0'
    length = 0.2
    n_elems = 200

    physics = 'flow_modelB'
  []
[]
```

So you can *sometimes* re-use some physics on different components, if you happen to have all of the same "physics" parameters. In a large system, you're typically going to have different physics parameters, like cross-sectional area and friction factor, for example, and also possibly different IC. So I'd say that THM is not the primary motivator for this capability.

I see this as mostly being a different way to approach Actions that bundle together physics (like in NS), but which allow usage in the Component system. For example, we have a somewhat ugly solution right now for re-using NS code between an Action and a Component. Physics can improve this a bit. And Guillaume also demonstrated with heat conduction, for example.

**Comment by joshuahansel** [comment]
So it's like you package up some physics and then you apply it to some selection of blocks.

**Comment by dschwen** [comment]
I have questions. Who wants this? Is silicon valley inventing the bus again? I.e. how is this not just actions again.

> a persistent object (unlike an action)
Actions are persistent objects, what's new here?

Honestly this looks like a shot from the hip. I'm happy you are talking to TH folks, but I think this could benefit from a bigger discussion with mesoscale, mechanics, fuel performance, etc. teams.

**Comment by GiudGiud** [comment]
> Who wants this?

I want this. Actions dont work with components, and the amount of code re-use in Actions is appallingly low. TM looks nothing like Griffin TransportSystems for example. 

> Is silicon valley inventing the bus again?

Just read the rest, it's a better bus.

> a persistent object (unlike an action)

There s no APIs on the action base class that make the fact that is indeed persistent a useful object to retrieve

> mesoscale, mechanics, fuel performance, etc. teams.

Mechanics is relevant for sure. I dont conceptualize a system-based approach being that relevant for mesoscale. Are you unhappy with what you have right now?

**Comment by GiudGiud** [comment]
There you go I amended from 

> - a persistent object (unlike an action) that we can interact with 
to
> - a persistent object that we can interact with (unlike an action) 

to avoid the very selective quotes

**Comment by dschwen** [comment]
> > a persistent object (unlike an action)
> 
> There s no APIs on the action base class that make the fact that is indeed persistent a useful object to retrieve

You can easily add APIs to an action derived class and fetch that from the warehouse. I'd urge to be careful with adding a new system for something that could be a simple action (why can't components be made to work with actions?!). While there might be upsides there also are downsides. More code to maintain, more "systems" to understand, more options to do the same thing. This is potentially adding confusion for users and developers. Bison for example already has an action system to set up materials (adding required objects to simulate the necessary physics in cladding and fuel materials for example). Springing a completely new approach on us without any regard for the existing solutions is not great. I also wonder how useful this system can ultimately be when it comes to practical simulations. For example contact. How would that fit into this new physics "system"?

**Comment by GiudGiud** [comment]
> You can easily add APIs to an action derived class and fetch that from the warehouse. And we are doing that already.

You may have done it in TM but because Action.h was so general none of it made its way up. And every other action reimplemented your stuff. 

> More code to maintain, more "systems" to understand, more options to do the same thing. 

Coming from the current situation which is insanely duplicative between applications, I dont think this applies. 
More systems is actually a good thing, systems should be focused. Action is not focused, it creates litterally everything and does whatever one wants. Physics is a subset. The 'action' name is also more MOOSE-speak. It's great when you have bathed in it forever, when you are introduced it's another obscure term to process. 

> Springing a completely new approach on us without any regard for the existing solutions is not great.

You are not really the customer here. Simulating a fuel and a clad doesnt take thousands of lines. The hundreds of channels inputs in SAM and THM are thousands of lines long because the Physics is spelled out so many times. They also currently require total duplication for each flow model, which we're hoping to solve by separating the Physics

> For example contact. How would that fit into this new physics "system"?

We'll have to figure it out. But unless someone proves me wrong I dont see two Components being able to spring a contact action. But if we code a SolidMechanics Physics and we code that the way two of these objects interact on a non-conformal mesh in close proximity is through few contact kernels, then we can realistically have the component create those

**Comment by joshuahansel** [comment]
> Springing a completely new approach on us without any regard for the existing solutions is not great

The introduction of a new system doesn't require everyone to adopt it. You can use it if it makes sense for your application. If there's no advantage, you can stick with what you're already doing and ignore the system. I don't think a new system necessarily brings a lot more confusion, so long as it is easy to understand (I haven't considered it here yet, just the high-level concept). The main concept I see here is to re-use physics action-like code in and out of the component system.

> Actions dont work with components

What exactly is meant by this? Do you mean a component cannot create actions, or interact with actions, or are not actions themselves? @lindsayad was interested in having components actually be actions. I've been doubtful so far because I'm unable to make all of the connections, but I'm open. The action system may not have been very mature at the time of the original component design. Should we explore this question first? If components were actions, would that eliminate the benefits of this?

Lots to think about here. Could be a full-blown discussion of the component system.

**Comment by GiudGiud** [comment]
>  If components were actions, would that eliminate the benefits of this?

The main benefits are clean hierarchies of classes creating equations, with base classes describing the physics and derived classes implementing the equations with a discretization. See the top post for the full list of benefits (consistent APIs to interact with, etc)
I m not sure what turning components into action bring tbh. It would just mean that instead of having the simulation initialize them, it would be a bunch of actions. Make us drift further from SAM for sure though. 

> Actions dont work with components

I think anything can create and interact with actions. You can get a writable reference to the action factory and warehouse from the app. Those APIs are all completely open.
I dont think Actions work well with components because there s no APIs to modify their content from other objects. There's no APIs to connect them. Action.h is too general, and TM, NSFV, TransportSystems started from there. 

The base class of physicsBase is not set in stone btw. I picked GeneralUO randomly. I could maybe pick Action.h. It does not matter (except having me re-write code to get the Physics from the action warehouse instead of the Problem).
What matters is the `[Physics]` block and the APIs. and you will not get either of those without refactoring your action a lot, to the point you may as well code a Physics object.

**Comment by GiudGiud** [comment]
It would be worth discussing though. We could converge on a better design.
For example if we could have (dubious) a Physics create an existing Action to create the kernels/BCs, while still retaining enough information to be able to handle interactions with Components/between physics, that could be a way to build on top of existing code. I dont think it s possible in a general manner (but people can try on their case) because of the utter generality of Actions

**Comment by joshuahansel** [comment]
> I dont think Actions work well with components because there s no API to modify their content from other objects. There's no API to connect them.

Yes, this was one of my main concerns about Components being Actions. There's also some timing concerns and the dependency resolution of its "tasks": the various component setup steps need to be executed in an order depending on the coupling of components. We'd need build tasks after these "actions" were created, which seems screwy, like a task `heat_transfer1_setup` depending on `pipe1_setup`.

**Comment by GiudGiud** [comment]
> We'd need build tasks after these "actions" were created, which seems screwy, like a task heat_transfer1_setup depending on pipe1_setup.

You can register tasks dynamically btw. I think Actions already do that. It will be a lot of tasks though if we use 3/4 tasks for each component

**Comment by lindsayad** [comment]
If you stored things in the action warehouse you could actually run geometric relationship managers on time… the problem is created after the mesh has been setup

**Comment by lindsayad** [comment]
The best conceptual argument I see for components/physics not being actions is if they are required to exist after the action setup phase

**Comment by GiudGiud** [comment]
What happens to the Action after the setup phase?
Does it go out of scope?

**Comment by lindsayad** [comment]
And then if they’re required to exist after the setup phase we’d have to explore why that is

**Comment by dschwen** [comment]
> What happens to the Action after the setup phase? Does it go out of scope?

The actions are stored in the action warehouse. Unless they are explicitly destroyed after initialization they will hang around there.

**Comment by GiudGiud** [comment]
If it can still be accessed anytime that matches a lot of the needs for interacting with components and plans to be a dynamic object rather than just a setup thing. The lack of threading will just mean we use locks instead of memory duplication.

What may be more concerning is that we want to determine the type of the Physics from the [Physics/type], not from the syntax name directly. And this is very much unlike what we do for actions.

**Comment by joshuahansel** [comment]
Sorry if I derailed the conversation - it sounds like the idea has potential merit regardless of component design. And it sounds like it might be possible to make physics/components into actions (and I have more thoughts/questions on this), but I guess we should answer first whether we want some kind of Physics entity with this kind of syntax:
```
[Physics]
  [myphysics]
    type = BlahPhysics
    ...
  []
[]
```
whether it be a MOOSE object or an action. I would vote yes, but we need to get some more opinions.

**Comment by joshuahansel** [comment]
> What may be more concerning is that we want to determine the type of the Physics from the [Physics/type], not from the syntax name directly. And this is very much unlike what we do for actions.

I was wondering about this too but was second-guessing myself. Can Actions even do the syntax in my previous comment? If not, that seems like definitely a no-go.

**Comment by GiudGiud** [comment]
It wont be a mooseObjectAction (unless Physics is a mooseObject like now). And the way regular Action get recognized from their syntax then the corresponding tasks get registered wont work either.
So it will have to be custom code in the interaction between parser and actions

**Comment by GiudGiud** [comment]
still needs to be pretty

**Comment by GiudGiud** [comment]
Note that this is not to solve the length of input file problem. This is to enable a Component-based approach to multiphysics, where we load components one by one then assign physics to each

**Comment by hugary1995** [comment]
It's not clear to me how a component is different from an action. I guess I'll just unsubscribe from the discussion since I'm not familiar with the component system at all...

**Comment by GiudGiud** [comment]
Components have some similarities with Action but they dont derive from them. 
They set up meshes, kernels etc and also perform these steps in order. It's as if there were sub-tasks being ordered within a task

**Comment by joshuahansel** [comment]
@hugary1995 I agree that solving the lengthy input file problem isn't the aim here - I think it was just a potential bonus. Your suggestion of the `!include` with parameters is interesting though. I suspect that the parser people would not like it because it make things a bit more complex. My thinking is that when your input files are getting to that point, it's time to write a python script with the hit stuff.

**Comment by lindsayad** [comment]
With the results from the meeting today about the subjects in this PR being positive, should we start reviewing?

**Comment by GiudGiud** [comment]
no, this PR will be cut in 5+ pieces. I ll leave it open for discussions and running valgrind though (until IM fixes leaks on mac at least)

**Pull request closed without merging**
