### PR TITLE
PorousFlowDictator illustrated

### LINKED ISSUE #10169: Illustrate the Dictator
## Rationale

Amusement

## Description

Ascii art

## Impact

Smiles all round

### PR DESCRIPTION
**Pull request by WilkAndy**
Finally i have done this after thinking about it for about a year.

Fixes #10169

### CODE REVIEW

**Comment by WilkAndy** [comment]
@cpgr .   Depends a bit on the line-spacing and font layout of your terminal.

**Comment by permcody** [comment]
How did you generate this?
http://picascii.com/

**Comment by WilkAndy** [comment]
Yea, i tried various online things, and searches, etc, and picascii was the best.  Initially i wanted a picture of a dictator, but they were all too obviously a particular dictator - gaddafi, fidel, et al.

**Comment by andrsd** [comment]
You should have gone with: `диктатор` :-)

**Comment by WilkAndy** [comment]
The problem is, @andrsd , there are just too many dictators in the world at the moment, and then of course there are all the historical ones too.  I wouldn't want to choose a particular one.  The others would feel really sad.

**Comment by andrsd** [comment]
`диктатор` was a computer game for ZX-80 in 80s...

**Comment by WilkAndy** [comment]
Yep, the illustration on the cover of the dictator looks mean alright!   Even meaner - he comes on a cassette tape and consists of about 1000 lines of BASIC code!

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
oh yea!  Thanks for the merge @permcody!    It took me about 10 hours to create that ASCII eye, so i'm glad you didn't reject it :-)   Obviously my skills don't lie in any artistic field.

a

**Comment by cpgr** [comment]
He's not joking about the amount of time it took!

**Pull request merged**
