### PR TITLE
Loosen jacobian tolerances

### PR DESCRIPTION
**Pull request by lindsayad**
Refs #12650

### CODE REVIEW

**Comment by permcody** [comment]
Adding the distributed sweep targets ('cause they were the ones that failed).

**Comment by lindsayad** [comment]
Yea I have max_parallel for these set to 2, so our distributed mesh target in pthreads testing in the PR stage skipped these new tests because it runs with `p = 4`. On my local machine, the Jacobian test is actually better with p = 2 than when run in serial with `--distributed-mesh`

**Comment by permcody** [comment]
Oh interesting... I wonder if we should lower the distributed-mesh testing to "p 2" for PRs then... I assume there must be other tests that we miss for this same reason.

**Comment by lindsayad** [comment]
That seems like a good idea to me

**Review by permcody — APPROVED** [review]

**Pull request merged**
