### PR TITLE
Update .gitignore

### LINKED ISSUE #6945: Update .gitignore
### Description of the enhancement or error report

.jitdir is showing up due to changes in the function parser from the last libMesh update

### Rationale for the enhancement or information for reproducing the error

No errors or problems, just clutter

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact

### PR DESCRIPTION
**Pull request by permcody**
Ignore .gitdir contents

closes #6945

### CODE REVIEW

**Comment by dschwen** [comment]
In .jitignore?

**Comment by dschwen** [comment]
I bet you pronounce GIF jiff as well...

**Comment by permcody** [comment]
I do not:
http://i.imgur.com/VMX15YT.gifv

**Comment by jwpeterson** [comment]
Merging without waiting for testing.  What could go wrong?

**Pull request merged**
