### PR TITLE
python: remove old getpot parser

### PR DESCRIPTION
**Pull request by rwcarlsen**
This should go in *after* #10077 and #10106 are merged.

### CODE REVIEW

**Comment by permcody** [comment]
@rwcarlsen - correct me if I'm wrong, but even though the other two referenced PRs have been merged, we still have to hang onto this for as long as we keep old peacock around, correct?

**Comment by rwcarlsen** [comment]
Correct.

**Comment by permcody** [comment]
Closing per the 30-day inactivity policy. I still support this but I think it'll be several more months before we are able to remove.

**Comment by rwcarlsen** [comment]
This can go in now that old peacock is gone.  Will need to invalidate after moose-docs issues get resolved on devel.

**Review by permcody — APPROVED** [review]

**Pull request merged**
