### PR TITLE
Enabling coupling of elemental variable values

### LINKED ISSUE #6818: Coupling values in `InitialCondition`s does not work for elemental variables
### Description of the enhancement or error report

If I take an input file that coupled nodal variables in an input file and I change the variable type to elemental (like monomials), I get a segfault.

### Rationale for the enhancement or information for reproducing the error

This input file demonstrates the problem (work fine with nodal variables):
```
[GlobalParams]
  family = MONOMIAL
  order = CONSTANT
[]

[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  nx = 2
  ny = 2
[]

[AuxVariables]
  [./a]
  [../]

  [./b]
  [../]
[]

[Variables]
  [./u]
  [../]

  [./v]
  [../]
[]

[ICs]
  [./u_ic]
    type = ConstantIC
    variable = u
    value = -1
  [../]

  [./v_ic]
    type = MTICSum
    variable = v
    var1 = u
    var2 = a
  [../]

  [./a_ic]
    type = ConstantIC
    variable = a
    value = 10
  [../]

  [./b_ic]
    type = MTICMult
    variable = b
    var1 = v
    factor = 2
  [../]
[]

[AuxKernels]
  [./a_ak]
    type = ConstantAux
    variable = a
    value = 256
  [../]

  [./b_ak]
    type = ConstantAux
    variable = b
    value = 42
  [../]
[]

[Kernels]
  [./diff_u]
    type = Diffusion
    variable = u
  [../]

  [./diff_v]
    type = Diffusion
    variable = v
  [../]
[]

[BCs]
  [./left_u]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  [../]

  [./right_u]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1
  [../]


  [./left_v]
    type = DirichletBC
    variable = v
    boundary = left
    value = 2
  [../]

  [./right_v]
    type = DirichletBC
    variable = v
    boundary = right
    value = 1
  [../]
[]

[Problem]
  solve = false
[]

[Executioner]
  type = Steady

  solve_type = 'NEWTON'
  nl_rel_tol = 1e-10
[]

[Outputs]
  exodus = true
[]
```

### Identified impact

People doing DG cannot do the same IC values coupling as people doing CG.

### PR DESCRIPTION
**Pull request by andrsd**
Enables elemental variable values coupling in `InitialCondition`s

Closes #6818

### CODE REVIEW

**Comment by YaqiWang** [comment]
@andrsd Is the nodal value the average of the values at the point on all its surrounding elements?

**Comment by andrsd** [comment]
@YaqiWang I am not sure I understand your question. Nodal values in general are just given by the solution vector. The final elemental value we compute in AuxKernel (for first order monomials) is the average value.

In `MooseVariable`, `_nodal_u` holds either nodal values for nodal variables, but also elemental for elemental variables (i.e. the values extracted from the solution vector), and `_u` are the values at q-points.

**Comment by permcody** [comment]
👍

**Comment by friedmud** [comment]
I'm confused here about a few things:

1.  Can initial conditions for nodal variables access elemental variables?  (This is what @YaqiWang was talking about)
2.  How does the test test this?  It looks like it's using all nodal variables to me

**Comment by friedmud** [comment]
Ok - for (2) I see the `GlobalParams` block now.  I gotta say: I don't like that very much!  Makes it much harder to see what's going on... but "we allow it" ;-)

**Comment by andrsd** [comment]
for (1), I have not tried, but I would expect problems like segfaults. There might still be a gap in the initial condition system, since we just work with the nodal value and I do not think we do anything special for elemental variables.

for (2), it is the way used by people doing DG, so they do not have to repeat CONSTANT, MONOMIAL everywhere. I got confused by it for the first time as well, but it makes sense to use `GlobalParams`.  And it is good to exercise different ways of syntax in the test harness as well...

**Pull request merged**
