### PR TITLE
DistributedMesh test workarounds

### PR DESCRIPTION
**Pull request by roystgnr**
This disables a few more of the remaining failing tests in #1500, and adds comments about why specifically each is disabled.

We're down to about 20 as-yet-unexplained failures, but I expect them to be slow going.  I do want to *understand* each failure before just marking it as "doesn't work yet", to make sure that they correspond to unsupported features rather than to features-we-incorrectly-think-are-supported.

### CODE REVIEW

**Comment by friedmud** [comment]
@roystgnr Would you mind going into the code for each of these and throwing an error for DistributedMesh?  Then we should change the test to actually check for that error (that part is optional... but highly recommended).

It would be best if people don't accidentally run into seg-faults / bad behavior.

**Comment by roystgnr** [comment]
@friedmud - sounds like a good idea.  I'm ashamed to admit that I thought of it but decided to be lazy instead.

If this was libMesh I'd be using a ```libmesh_not_implemented()``` (or if I was feeling kind, ```libmesh_not_implemented_msg("some explanation")``` to mark off the offending cases.  What would the preferred MOOSE idiom be?  ```mooseError("some explanation")```?

**Comment by permcody** [comment]
Yeah. mooseError is fine. Thanks

**Comment by permcody** [comment]
Superseded by #9180.

**Pull request closed without merging**
