### PR TITLE
Remove the default parmetis partitioner when using distributed mesh

### PR DESCRIPTION
**Pull request by YaqiWang**
Supposedly any partitioner should be fine. Let's see how much the damage is.

### CODE REVIEW

**Comment by friedmud** [comment]
"any" partitioner won't be fine... especially with adaptivity where you need to repartition after the mesh changes.  Any of the "serial" partitioners won't handle that.

**Comment by friedmud** [comment]
What problem are you trying to solve here?  You can always override the choice of parmetis by using the Partitioner block.

**Comment by YaqiWang** [comment]
I have a test that I want to run with and without distributed mesh in parallel. Because there could be randomness in parmetis partitioning, I put `partitioner = linear` in the `Mesh` block. But then with `--distributed-mesh`, the partitioner is forced to be parmetis while without distributed mesh it is not. `parmetis` partitioner produces different partitioning of `linear` thus changes the solution. I thought `Mesh/partitioner` is equivalent with `Partitioner` block, right?

**Comment by fdkong** [comment]
> thought `Mesh/partitioner` is equivalent with `Partitioner` block, right?

`Paritioner` block is considered as a `custom` partitioner, and you should be able to use `linear` there

**Comment by friedmud** [comment]
BTW: I'm not against changing this particular piece of MOOSE - it is a little heavy handed.  But it's like that to prevent someone from using a serial partitioner with distributed mesh which will can fail for many reasons (the main one is adaptivity).

I wouldn't mind just turning this into a `mooseError()` and then allowing an override in the `[Problem]` block or something.

**Comment by permcody** [comment]
> "any" partitioner won't be fine... especially with adaptivity where you need to repartition after the mesh changes. Any of the "serial" partitioners won't handle that.

I guess we need a test case for this combination. Interestingly removing these lines didn't trigger a single failure anywhere in moose or the apps so clearly it's a pretty rare case. Why don't you add a test with an explicit serial partitioner + adaptivity? We already have parallel distributed mesh testing turned on by default so if Derek is correct that should fail.

**Comment by YaqiWang** [comment]
Wow, all tests pass. I will keep working on this later, not urgent to me, unless @fdkong want to pick this up.

**Pull request closed without merging**
