### PR TITLE
Fix and test local range toggle

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Review by friedmud — APPROVED** [review]

**Review by friedmud — APPROVED** [review]
👍

**Review by friedmud — DISMISSED** [review]
👍

**Comment by permcody** [comment]
You're like Hammy the Hamster: First you clicked the comment button 4 times on a libMesh PR comment, then approved this PR 3 times! Haha!

**Comment by friedmud** [comment]
@permcody It was all because of a GitHub glitch... happened two days in a row... I blame Microsoft!

**Comment by friedmud** [comment]
Trying this now

**Review by friedmud — APPROVED** [review]
👍

**Pull request merged**
