### PR TITLE
Manage stateful data in contact to correctly recover from a failed step

### PR DESCRIPTION
**Pull request by bwspenc**
ref #7544

### CODE REVIEW

**Comment by bwspenc** [comment]
@acasagran 

We have done extensive testing of this code, but it requires code that forces the solver to fail to converge under certain cases to test the behavior after a failed solve, and I'm hesitant to check that in to a non-testing area. See #7347.

**Comment by bwspenc** [comment]
@friedmud That's basically what I'm doing, but that lives in `moose/test`, so I can't link it in from the modules.

**Comment by friedmud** [comment]
I'm with you... hmmm.

**Comment by permcody** [comment]
Ben and I (and others) talked about having testing code available to the modules through another "testing" folder where we could just link to test objects (i.e. moose/test/src). That way we could reuse some of these objects without polluting the modules or framework. Id' like to do that in the future, but it's not going to happen right now.

**Comment by permcody** [comment]
👍

**Pull request merged**
