### PR TITLE
Changed Euler2RGB to output a vector and added actions to create auxvariables and auxkernels

### PR DESCRIPTION
**Pull request by tonkmr**
I changed Euler2RGB to output a vector rather than a scalar. I also changed the names of the current auxkernels to be more clear. They can output a scalar value like to previous behavior or either the red, green, or blue value. I also added an action that creates the auxvariables and auxkernels.

This makes it so it now only requires one step to plot the RGB values in paraview.

### CODE REVIEW

**Comment by dschwen** [comment]
Forgot to check in a file?

**Comment by dschwen** [comment]
One test is under reconstruction and another one has its separate subdirectory. I'd rather see both tests in the same sub dir.

**Comment by tonkmr** [comment]
The one with its own subdirectory is in combined because it uses "EulerAngleProvider." The other test is in phase_field. Do you want me to move both into combined?

**Comment by dschwen** [comment]
how about we move the one in combined into `grain_texture`?

**Pull request merged**
