### PR TITLE
fluidproperties: add AD support to SinglePhase objects

### PR DESCRIPTION
**Pull request by rwcarlsen**
ref #12898

### CODE REVIEW

**Comment by joshuahansel** [comment]
This all looks good to me. Do you have any tests for the AD derivatives? For instance, maybe a test kernel that calls one of the interfaces with PetscJacobianTester?

**Comment by rwcarlsen** [comment]
This currently disables -Woveroaded-virtual because some of the singlephasefluidproperties subclasses don't implement the derivative-versions of the virtual x_from_y_z functions.  I'm not sure how to best deal with this.  The disabling only is in effect for files that `#include "SinglePhaseFluidProperties.h"` but that could potentially cause missed errors in user code.  The problem is that we actually want the behavior that is being warned about - we want implementations to be able to have the derivative functions called without terminating the simulation to allow for AD support to work "as good as possible" even if only some derivatives are available - so I need the base class to have derivative versions of the functions implemented that the AD functions can call.

**Comment by rwcarlsen** [comment]
No tests yet.  I wanted to get some feedback before I try to polish this up.

**Comment by andrsd** [comment]
We want the doco back in some form. Not every body denotes these quantities like we do. For example, we use `e` for internal energy, but the TD community is using `u`.  Units are also important, some packages are assuming `MPa` for pressure - we are assuming `Pa`, some uses `kJ`, we use `J`.  We do not necessarily have to have a doxy comment in front of each `propfunc`, we could just list all of them once like so:
```
/**
 * p - pressure [Pa]
 * T - temperature [K]
 ...
  */
```
or something like this.

The following did not seems to make your list: 
- `beta_from_p_T`
- `v_from_p, T`
- `e_from_p_T`

We do not want to forget them.

Other than that, looks good.

**Comment by rwcarlsen** [comment]
@andrsd - My list is only for functions that have empty/no implementation.  The "missing" ones you cited are actually left their unchanged - since the macro wouldn't have their customized implementations.  I'll see what I can do for doco

**Comment by cpgr** [comment]
Can we also do something similar for the other way around? Like implement only an AD version
```
DualReal prop_from_var1_var2(DualReal var1, DualReal var2)
```
and then provide
```
Real prop_from_var1_var2(Real var1, Real var2)
void prop_from_var1_var2(Real var1, Real var2, Real & prop, Real & dprop_dvar1,  Real & dprop_dvar2)
```
automatically for apps that expect these versions?

Or is that what this does, and I have just totally misunderstood it?

**Comment by rwcarlsen** [comment]
Writing the AD version requires knowing the regular derivatives plus some very AD-specific code that is identical for every property.  So it doesn't make much sense to require fluid properties implementers to write that AD-specific code every time in addition to the vanilla partial derivative calculation.  Rather, if implementers provide a way for us to calc the partials, we provide AD automatically for free.

**Comment by rwcarlsen** [comment]
This should be good - pragma error supression is only done per fluidprops class. doc comments added.  And a unit test for the AD stuff was added.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
