### PR TITLE
 Specializations of MooseADWrapper for std::array and MooseUtils::SemiDynamicVector

### PR DESCRIPTION
**Pull request by matthiasneuner**
refs #20364

## Reason
Reestablish compatibility with Fastor

## Design
Specializations of MooseADWrapper for std::array and MooseUtils::SemiDynamicVector

## Impact
no

### CODE REVIEW

**Review by dschwen — DISMISSED** [review]
Yeah, this looks like the right thing to do here. It removes the more general specialization which - I presume - interfered with Fastor, and adds a more narrow specialization for array and Semidynamicvector. 

@matthiasneuner is the underlying issue that Fastor tensors cannot be instantiated with dual numbers?

**Review by loganharbour — DISMISSED** [review]
Need to drop the merge commits from history

**Comment by matthiasneuner** [comment]
> Need to drop the merge commits from history

Please can you give me some quick instructions what I should do? Thank you!

**Comment by matthiasneuner** [comment]
> Yeah, this looks like the right thing to do here. It removes the more general specialization which - I presume - interfered with Fastor, and adds a more narrow specialization for array and Semidynamicvector.
> 
> @matthiasneuner is the underlying issue that Fastor tensors cannot be instantiated with dual numbers?

@dschwen I just tried, I can instantiate a Fastor::Tensor with ADReal (at least it compiles). I don't use MOOSE's ADReal at all in my projects, but I will test it more in detail once I have some more time.

**Comment by dschwen** [comment]
Do
```
got fetch origin
git reset --hard origin/devel
git cherry-pick 67212ce0
```

**Review by dschwen — APPROVED** [review]

**Pull request merged**
