### PR TITLE
Template RankThreeTensor for AD

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #12599)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@lindsayad I can't figure out my compile problem, can you take a look?

```
undefined reference to `RankThreeTensorTempl<double>::RankThreeTensorTempl()'
undefined reference to `RankThreeTensorTempl<double>::doubleContraction(RankTwoTensorTempl<double> const&) const'
```

**Comment by lindsayad** [comment]
At the end of `RankThreeTensor.C` put these lines:

```c++
template class RankThreeTensorTempl<Real>;
template class RankThreeTensorTempl<DualReal>;
```

**Comment by aeslaughter** [comment]
FYI. I have a fix for ferret waiting.

**Comment by aeslaughter** [comment]
@lindsayad I can't get it too work, maybe you can finish it off?

**Comment by lindsayad** [comment]
I think we're gonna add some unit tests for this...

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
