### PR TITLE
Fixing ICEUpdater Parallel Bugs

### PR DESCRIPTION
**Pull request by amccaskey**
This PR attempts to fix the following ICEUpdater issues: 
1. failure to run correctly in parallel
2. reports an inconsistent number of posts.

### CODE REVIEW

**Comment by amccaskey** [comment]
How do we make this test the ICEUpdater correctly in the CI? I just checked the test output and it skipped the tests because Libmesh didn't build with CURL support. Any way to turn that on?

**Comment by permcody** [comment]
Oh, this will be a good test of turning curl back on. Linking against curl
caused a lot of people in the libMesh community headaches so we disabled it
by default. John has since cleaned up the way we add library link paths in
configure so it should be safer now. To turn it on, you'll need to add the
"--enable-curl" flag to our "update_and_rebuild_libmesh.sh" script in
moose/scripts. It'll be fine for you to modify that in your PR because
it'll actually use that flag on our test systems.

While you are at it, please squash down your commits before pushing another
branch. We don't want that merge in there, or other spurious fixes.

**Comment by amccaskey** [comment]
Looks like CURL didn't get picked up in the Libmesh configure... It couldn't find /usr/include/curl/curl.h.

**Comment by permcody** [comment]
Looks like we don't have curl-dev installed on the build boxes...  We'll do
that then invalidate that target so it can rerun.

**Comment by permcody** [comment]
Looks like libMesh found the dev package (after invalidating).

**Comment by permcody** [comment]
libCurl is causing new problems in libMesh. We are investigating and will keep you posted.

**Comment by friedmud** [comment]
I still vote for keeping Curl off by default for now. Only once we have
more people asking for ICE integration than not should we consider making
it the default

On the test machines we can pass the extra flags to add curl support at
compile time.

**Comment by amccaskey** [comment]
I've run into problems in my Moose App development when I try to enable curl. Turned out linking to the default libcurl on my system fails because its not built with the same compilers and standard c++ libs I was using for Moose development. I added a new build of libcurl to /opt/moose/curl built with the compilers in the environment package and things work fine. May be that Moose should package curl with its environment package going forward and have the script point to that.

**Comment by jwpeterson** [comment]
On Thu, Nov 5, 2015 at 7:32 AM, Alex McCaskey <notifications@github.com>
wrote:

> I've run into problems in my Moose App development when I try to enable
> curl. Turned out linking to the default libcurl on my system fails because
> its not built with the same compilers and standard c++ libs I was using for
> Moose development. I added a new build of libcurl to /opt/moose/curl built
> with the compilers in the environment package and things work fine. May be
> that Moose should package curl with its environment package going forward
> and have the script point to that.
>

That may be the right solution going forward.  Would you mind posting the
particular version of curl you built and the flags you used?  Jason Miller
might be able to use them if we decide to add curl to the redistributable
package.


-- 
John

**Comment by amccaskey** [comment]
It was pretty simple. I just cloned https://github.com/bagder/curl.git, but you can also download the latest release at http://curl.haxx.se/download.html. Run ./configure --prefix=/opt/moose/curl from the top-level, make, then make install.

**Comment by permcody** [comment]
It is simple indeed but it is also a sizable project. Why the heck is a network communication tool so big!? I'm starting to wonder if it's worthwhile looking for other small libraries for communication testing. You are simply opening a socket and sending a few well understood bytes...

**Comment by friedmud** [comment]
@permcody : I still believe that this Curl stuff is unnecessary.  It was
useful for getting going... but we should investigate something _tiny_ that
we can just put in contrib.

**Comment by aeslaughter** [comment]
http://stackoverflow.com/questions/118945/best-c-c-network-library

**Comment by friedmud** [comment]
This one looks nice!  Header only (and a variant is what they use in Boost).

http://think-async.com/Asio/

For instance, check out the Client example:

https://github.com/chriskohlhoff/asio/blob/master/asio/src/examples/cpp03/http/client/async_client.cpp

Derek

**Comment by permcody** [comment]
Totally on board with this. I'd like to drop curl after all the problems it
has caused.

**Comment by amccaskey** [comment]
Sorry for the late response here, was offline for a few days. 

I'm on board with this too. I'll create a new Issue for this, and work on configuring the Updater to use Asio.

**Comment by permcody** [comment]
@amccaskey - Just pinging you on this. Any progress on switching away from curl? I'd like to get the ICE stuff all in there if possible before the NEAMS meeting.

**Comment by amccaskey** [comment]
Yea I would too. I've started on it, I ran into issues trying to put asio into contrib. So I this is a good time to ask: 

How does MOOSE/Libmesh work with Boost? It seems to me (and I may be totally wrong) that the Libmesh build includes Boost and Moose leverages that for things like shared pointers. However, if you were to build with --enable-cxx11, would Libmesh not be bundled with Boost, and Moose would use std::shared_ptr, etc? 

I ask because it seems like asio requires a few Boost headers (unless you set ASIO_STANDALONE, which I'm not sure how to set in the MOOSE build). Any advice on how to proceed?

**Comment by amccaskey** [comment]
... and when I try to build with asio it fails to find those Boost headers...

**Comment by permcody** [comment]
libMesh contains a small subset of BOOST headers because we don't actually require BOOST to run libMesh or MOOSE. The libMesh developers are fine with adding new headers if it doesn't explode the size of our paired down BOOST headers. BOOST is notorious for requiring hundreds of headers for a single method so it just depends on which methods you are using and are they header only, etc.

Everything in libMesh is carefully wrapped to work with C++03 and C++11 where possible. Compiling with or without switches implementations under the hood so we can use native C++11 features where possible and supplement those features with C++03 + BOOST equivalents.

So to answer your question, if you need a BOOST header, look into adding that header to the contrib folder in libMesh. As long as it's only a few, they'll accept your PR. If you try adding a thousand new headers, they probably won't. If you need C++11 you can use that as well as long as things fail gracefully when it's not available. I'd entertain having ICE requiring C++11 since many of our users are turning it on now. Those who aren't would simply not be able to use ICE. Ideally it would be awesome if it worked either way but things don't always work out that way.

**Comment by friedmud** [comment]
We definitely want to use the standalone version of ASIO (otherwise we will
need pretty much all of BOOST)

However: I think it requires C++11...

**Comment by permcody** [comment]
Superseded by #6037

**Pull request closed without merging**
