### PR TITLE
Misc. enhancements to TimeIntegrators

### PR DESCRIPTION
**Pull request by jwpeterson**
While looking at @andrsd's `RungeKutta2` implementation, I realized we could actually have three methods for the price of one if we just generalized it a bit.  The old `RungeKutta2` functionality is now available as the `ExplicitMidpoint` method, and the original name has been deprecated.  The `Heun` and `Ralston` explicit time integration methods have also been added.

The branch also adds tests for the new methods, and a small python script that can be used to make [convergence plots](https://drive.google.com/file/d/0B9BK7pg8se_iMFFzSFo5eThKMG8/view?usp=sharing) that confirm the order of the new methods.

This branch also adds the `ImplicitMidpoint` method (implemented as a two-stage implicit RK method) which has the same order of accuracy and stability as Crank-Nicolson.  I may decide to not keep it in the long run, but wanted to at least have it in the history.

### CODE REVIEW

**Comment by permcody** [comment]
:+1: 

@andrsd do you care to review?

**Comment by andrsd** [comment]
Yeah, I'll look at it...

**Comment by andrsd** [comment]
One comment, it is more a cosmetic deal: Do we want to print the method's name in each stage? I thought we were printing the time integrator name in the simulation header...

**Comment by friedmud** [comment]
I haven't looked at the code yet... but I'm happy to see more advancements along these lines.

@jwpeterson this is probably worth an announcement/blog post/twitter post and an update to some of the documentation on mooseframework.org

**Comment by jwpeterson** [comment]
> One comment, it is more a cosmetic deal: Do we want to print the method's name in each stage? I thought we were printing the time integrator name in the simulation header...

You are right, looks like I picked this up from Dirk.  I'll remove that.

**Comment by jwpeterson** [comment]
> @jwpeterson this is probably worth an announcement/blog post/twitter post and an update to some of the documentation on mooseframework.org

OK.

**Comment by jwpeterson** [comment]
> Should this really use AMG?

Sure, it still has to solve the mass matrix.  Is AMG not the best PC for that one?

**Comment by andrsd** [comment]
> Is AMG not the best PC for that one?

I thought AMG was good for Laplacian-like operators.

**Comment by jwpeterson** [comment]
> The same fix should go in ImplicitMidpoint as well...

Thanks, also fixed the Dirks.

**Comment by jwpeterson** [comment]
> I thought AMG was good for Laplacian-like operators.

Well, I tried the Jacobi preconditioner and it was marginally faster (timed with "/usr/bin/time -p", end_time = 1.0, dt = 0.000244140625, and console = false):
* Jacobi: 9.21
* AMG: 10.40

so I will switch to that.

**Comment by andrsd** [comment]
@jwpeterson We can merge as is unless you plan on polishing up the patches...
@friedmud Are you done looking at the code or you need more time before merging?

**Comment by jwpeterson** [comment]
I'm all done, merge when ready.

**Comment by jwpeterson** [comment]
BTW, [blog post](http://www.mooseframework.org/blog/new-timeintegrators-added/) was added.

**Comment by friedmud** [comment]
I'm not qualified to review this :smile: 

That said, I AM qualified to trust @andrsd enough to merge it ;-)

**Pull request merged**
