### PR TITLE
Mtwist update

### PR DESCRIPTION
**Pull request by andrsd**
1) Update mtwist
2) Improve unit tests for `MooseRandom`
3) Regolding tests that were affected by mtwist update (i.e. were using MooseRandom)

### CODE REVIEW

**Comment by permcody** [comment]
@andrsd are you proposing that we run modules in parallel now? If we don't, we'll likely see regressions - if we do, we'll probably feel the pain a bit from poorly designed tests....  Still might be the right thing to do though

**Comment by andrsd** [comment]
> are you proposing that we run modules in parallel now?

I am not proposing anything. I ran the tests in parallel and had t make sure that I did not cause any problems. I did not, but quite a bit of tests either failed (because `-pc_type lu` does not run in parallel) or diffed (sometimes because of a too tight tolerance, sometimes because people did not realize that parallel and serial runs will have different convergence history, some even seems there might be a parallel bug in people's code - when the doff was too big).

So while I was investigating the problems I just fixed them as I went.

**Comment by andrsd** [comment]
I do not understand how this could break `line_value_sampler` in parallel...

**Comment by permcody** [comment]
That test is unstable. We probably need to skip it

**Comment by permcody** [comment]
No need to retest this unless you want. We can merge whenever you are ready.

**Comment by andrsd** [comment]
While this builds fine on linux, I see
```
duplicate symbol _mts_lrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mts_llrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mts_drand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mts_ldrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mt_lrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mt_llrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mt_drand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
duplicate symbol _mt_ldrand in:
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/mtwist.x86_64-apple-darwin14.0.0.devel.o
    /Users/andrsd/workspace/moose/framework/contrib/mtwist/src/.libs/randistrs.x86_64-apple-darwin14.0.0.devel.o
ld: 8 duplicate symbols for architecture x86_64
```
on Mac OS X, so this PR still needs some work.

**Comment by andrsd** [comment]
I have patched all apps, so we should be ready to merge...

**Pull request merged**
