### PR TITLE
Adding thermal properties of UC

### PR DESCRIPTION
**Pull request by AyaHegazy22**
Issue #23207

### CODE REVIEW

**Comment by dschwen** [comment]
5550 commits, looks like you accidentally rebased on master. You need to do a `git reset --hard upstream/devel` and then `git cherry-pick 0e168ac 69c04bd 8b20668 30918ea b735459 3f69e43`

**Comment by novasr** [comment]
In addition to @dschwen comments, do we want UC material models here?

**Comment by dschwen** [comment]
> In addition to @dschwen comments, do we want UC material models here?

Are those published in the open literature? If so then it goes back to our recent open-sourcing discussion, and I would say yes. This contribution already comes form the outside. If the university thinks it should be open source why should we reject it?

**Comment by novasr** [comment]
I wasn't suggesting we reject, just wondering where it ought to go.

**Comment by novasr** [comment]
Also, there are UC models in BISON. Perhaps these efforts should be coordinated?

**Comment by dschwen** [comment]
> Also, there are UC models in BISON. Perhaps these efforts should be coordinated?

I see. One problem with the solid properties module is that it does not cover all bison usecases. It's almost as if someone designed the APIs in this model without talking to application developers...

Anyways, I'd suggest that since this PR is aimed at the solid properties module, it should go in here. However, we should have a design discussion in the near future on how we can consolidate app material models and the solid properties module.

**Comment by lindsayad** [comment]
> model

Did you mean to say module?

**Comment by lindsayad** [comment]
It looks like quite a few BISON application developers were pinged on the solid properties module PR: https://github.com/idaholab/moose/pull/21231#issuecomment-1150325040

**Comment by dschwen** [comment]
> It looks like quite a few BISON application developers were pinged on the solid properties module PR: [#21231 (comment)](https://github.com/idaholab/moose/pull/21231#issuecomment-1150325040)

Indeed. I missed that. It looks like Kyle voiced his concerns about the module not being very useful for Bison. At that point the module developers basically agreed that the "solid properties" module should effectively just be a "solid thermal properties" or "solid properties that are just a function of temperature" module, and that Bison should just keep doing its thing. After that I don't see any further engagement from Bison developers (can't blame them).

So I suppose the bottom line is that this PR is a PR for the solid properties module and has absolutely nothing to do with Bison?

On a more constructive note, we could probably look into using whatever we can from SPM from the Bison material objects. At least from within the nuclear material action system, which could keep the extra input file complication from having additional UOs hidden from the user.

**Comment by dschwen** [comment]
Anyhow, not to derail this PR discussion too much, I suspect part of my frustration comes from a lack of understanding of the design goals of this module. I suppose one reason to move to the General User Object based design, away from the material based design with the fairly established derivative properties system, comes from the introduction of the of the (still somewhat obscure to me) functor system. All of this is likely mainly my own fault.

**Comment by dschwen** [comment]
Back on topic: @AyaHegazy22 let us know if you need help fixing this PR. Try the git commands I posted above first. If things blow up I can help recover the PR.

**Comment by AyaHegazy22** [comment]
> Back on topic: @AyaHegazy22 let us know if you need help fixing this PR. Try the git commands I posted above first (I tried them locally on my machine for this branch and it worked fine). If things blow up I can help recover the PR.

**Comment by joshuahansel** [comment]
@dschwen As for the design of the solid properties module, I see the goal as this: if the model is ok to be open-source, put it in the solid properties module *somehow*. It doesn't need to be in the `ThermalSolidProperties` format - that's just the first hierarchy to exist in the module because multiple applications expressed interest in it. For example, you can just have namespaces that you put functions in, and the applications can leverage those functions however they like. Nothing is to stop Bison from putting their material models in the module as well - I just think anybody has been motivated to do that yet. As for the design of `ThermalSolidProperties`, the UO-design was desirable because it was flexible as far as what MOOSE system the relationships could be used in.

**Comment by lindsayad** [comment]
@joshuahansel see my most recent comment on https://github.com/idaholab/moose/issues/12284. I think it makes sense to have continued discussion over on the issue

**Pull request closed without merging**
