### PR TITLE
Attempting to fix an old bug...

### LINKED ISSUE #2345: _second_phi_zero is never resized!
second_phi_zero is currently broken - needs to be resized

### PR DESCRIPTION
**Pull request by permcody**
closes #2345

Maybe I need to dream up a test but it seems like this should be a simple fix either way. @andrsd does this look right to you?

### CODE REVIEW

**Comment by andrsd** [comment]
> @andrsd does this look right to you?

:+1:

**Comment by jwpeterson** [comment]
I think we decided after some discussion that `LIBMESH_DIM` should be replaced by the max (over all the elements) of the number of element shape functions (or dofs).

**Comment by permcody** [comment]
@andrsd - we appear to be resizing zeros in each of the reinit methods. Why not just size them once to the max and leave the alone?

**Comment by andrsd** [comment]
We can certainly do that now that we have `_max_qp` available.

**Comment by permcody** [comment]
OK - I'll make the appropriate changes

**Pull request closed without merging**
