### PR TITLE
PorousFlow Dirac kernel and tests

### PR DESCRIPTION
**Pull request by cpgr**
Adds a DiracKernel to the PorousFlow modules, as well as some tests
Refs #6990

### CODE REVIEW

**Comment by cpgr** [comment]
Now that the bug fix in #6989 has been merged the failing modules tests should work

**Comment by WilkAndy** [comment]
Hi @cpgr, do you have to pull from devel and push -f up here to get these tests to work?

**Comment by cpgr** [comment]
I'll try that

**Comment by permcody** [comment]
👍

**Pull request merged**
