### PR TITLE
Checkpoint input test coverage

### PR DESCRIPTION
**Pull request by roystgnr**
This turns out to be much less impressive than I thought it would be, because we still have some libMesh bugs preventing N->M DistributedMesh reads of CheckpointIO files...  but we can read N->N pre-split checkpoint files via FileMesh just fine now, which ought to be all we need for #7752.

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like this doesn't work on Mac: https://www.moosebuild.org/job/110576/

**Comment by roystgnr** [comment]
Gah.  I don't have a Mac to replicate with.  Can anyone try this in dbg mode and tell me what happens?

**Comment by brianmoose** [comment]
```
mesh/checkpoint.test_8: Working Directory: /Users/algebk/projects/moose2/test/tests/mesh/checkpoint
mesh/checkpoint.test_8: Running command: mpiexec -n 8 /Users/algebk/projects/moose2/test/moose_test-dbg --n-threads=1 -i checkpoint_split.i Outputs/file_base=test_8  Mesh/file=checkpoint_split_in.8.cpr --error --no-gdb-backtrace
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 25769803781
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 5
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: [0] ./include/libmesh/libmesh_common.h, line 554Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 51539607552
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 0
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 158913789952
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 0
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 304942678018
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 2
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 94489280517
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 5
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 244813135876
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 4
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: , compiled nodate at notime
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: [1] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: [2] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: [3] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: [4] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: [6] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 4591870180066957722
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 2576980378
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: [5] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_8: oldvar = 236223201284
mesh/checkpoint.test_8: static_cast<Told>(static_cast<Tnew>(oldvar)) = 4
mesh/checkpoint.test_8:
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: [7] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
mesh/checkpoint.test_8: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7
mesh/checkpoint.test_8:
mesh/checkpoint.test_8: ################################################################################
mesh/checkpoint.test_8: Tester failed, reason: CRASH
mesh/checkpoint.test_8:
mesh/checkpoint.test_8........................................................................ FAILED (CRASH)
mesh/checkpoint.test_2: Working Directory: /Users/algebk/projects/moose2/test/tests/mesh/checkpoint
mesh/checkpoint.test_2: Running command: mpiexec -n 2 /Users/algebk/projects/moose2/test/moose_test-dbg --n-threads=1 -i checkpoint_split.i Outputs/file_base=test_2  Mesh/file=checkpoint_split_in.2.cpr --error --no-gdb-backtrace
mesh/checkpoint.test_2:
mesh/checkpoint.test_2: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_2: oldvar = 25769803777
mesh/checkpoint.test_2: static_cast<Told>(static_cast<Tnew>(oldvar)) = 1
mesh/checkpoint.test_2:
mesh/checkpoint.test_2:
mesh/checkpoint.test_2: [0] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_2: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_2: oldvar = 4591870180066957722
mesh/checkpoint.test_2: static_cast<Told>(static_cast<Tnew>(oldvar)) = 2576980378
mesh/checkpoint.test_2:
mesh/checkpoint.test_2:
mesh/checkpoint.test_2: [1] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_2: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
mesh/checkpoint.test_2:
mesh/checkpoint.test_2: ################################################################################
mesh/checkpoint.test_2: Tester failed, reason: CRASH
mesh/checkpoint.test_2:
mesh/checkpoint.test_2........................................................................ FAILED (CRASH)
mesh/checkpoint.test_4: Working Directory: /Users/algebk/projects/moose2/test/tests/mesh/checkpoint
mesh/checkpoint.test_4: Running command: mpiexec -n 4 /Users/algebk/projects/moose2/test/moose_test-dbg --n-threads=1 -i checkpoint_split.i Outputs/file_base=test_4  Mesh/file=checkpoint_split_in.4.cpr --error --no-gdb-backtrace
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_4: oldvar = 25769803779
mesh/checkpoint.test_4: static_cast<Told>(static_cast<Tnew>(oldvar)) = 3
mesh/checkpoint.test_4:
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: [0] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_4: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_4: oldvar = 158913789952
mesh/checkpoint.test_4: static_cast<Told>(static_cast<Tnew>(oldvar)) = Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_4: oldvar = 188978561027
mesh/checkpoint.test_4: static_cast<Told>(static_cast<Tnew>(oldvar)) = 3
mesh/checkpoint.test_4: 0
mesh/checkpoint.test_4:
mesh/checkpoint.test_4:
mesh/checkpoint.test_4:
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: [2[1] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_4: ] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notime
mesh/checkpoint.test_4: Assertion `oldvar == static_cast<Told>(static_cast<Tnew>(oldvar))' failed.
mesh/checkpoint.test_4: oldvar = 4591870180066957722
mesh/checkpoint.test_4: static_cast<Told>(static_cast<Tnew>(oldvar)) = 2576980378
mesh/checkpoint.test_4:
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: [3] ./include/libmesh/libmesh_common.h, line 554, compiled nodate at notimeapplication called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
mesh/checkpoint.test_4: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
mesh/checkpoint.test_4: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
mesh/checkpoint.test_4:
mesh/checkpoint.test_4: ################################################################################
mesh/checkpoint.test_4: Tester failed, reason: CRASH
mesh/checkpoint.test_4:
mesh/checkpoint.test_4........................................................................ FAILED (CRASH)
```

**Comment by roystgnr** [comment]
Ah!  That's a cast_int failure!  I generated those files with one set of id sizes, and presumably the Mac build has a different set.

There's no way to fix this without a libMesh update.  Can we selectively disable that test on Mac for now somehow, or do we need to disable it altogether until we can update?

**Comment by permcody** [comment]
You can make a test run only on selected "platform"s. Check that out in the
test specs. Options are listed when you type "run_tests --dump".

**Pull request merged**
