### PR TITLE
Some assembly refactors

### LINKED ISSUE #26328: ADParsedFunctorMaterial evaluation attempting to access invalid qt elements
## Bug Description
Feeding an AuxVariable into an ADParsedFunctorMaterial results in `Error Bad qt=(large number)`. 

## Steps to Reproduce
Create an `AuxVariable` and attempt mathematical operations on it in an `ADParsedFunctorMaterial`

## Impact
Prevents one user solution for data-fitting, there may be a way around it, but it's a major inconvenience. 

This issue is solved by PR #26269.

### PR DESCRIPTION
**Pull request by lindsayad**
Work done in support of issue #25666 and its PR #26073

### CODE REVIEW

**Comment by lindsayad** [comment]
@rui-hu @lingzou @lingzou-anl the tests that are exodiffing were previously using an incorrect calculation of JxW. Could someone check and see what you think of the new results?

**Comment by loganharbour** [comment]
Let me know if you need a review

**Comment by lindsayad** [comment]
I do need one 😄

**Comment by lingzou** [comment]
@lindsayad it is great that @loganharbour can help with the review. this MR is a bit beyond my capabilities.

**Comment by lindsayad** [comment]
It would be good for a SAM dev to consider the SAM failures though and whether what you are now getting for output files reflect better solutions

**Comment by ke7kto** [comment]
This PR fixes issue #26328

**Comment by lingzou** [comment]
> It would be good for a SAM dev to consider the SAM failures though and whether what you are now getting for output files reflect better solutions

@lindsayad I am trying to understand what needs to be done on SAM side, like what has been changed in this MR, and what are needed in SAM; or maybe there is nothing needed in SAM, but just to make sure the failed cases should be updated and to accept the changes.

**Comment by lingzou** [comment]
@lindsayad It seems to me that this MR may have introduced a bug somewhere. Please refer to one of the failed SAM test case: tests/components/SurfaceCoupling/GapHT.i

Note that this problem has analytical solutions (please see the test head of that problem). This MR produced results very far away from the analytical solutions, so this makes me think maybe 
1. there was a bug in this MR; **or** 
2. SAM should be updated following this MR;

unless I was completely wrong about the analytical solutions.

**Comment by lindsayad** [comment]
It did not introduce a bug. It fixed a bug. I think that previously the JxW returned by the `Assembly` API was half of what it should have been. When `FE::reinit` is called with a point argument but not a weights argument, then dummy weights of 1 are used. However, for one Gauss point for integration, the weight should be 2.

**Comment by lindsayad** [comment]
If this caused a diff from an analytical or reference solution, then it seems like maybe SAM was working around the bug

**Comment by lindsayad** [comment]
On line 81 of `SAMNodeFaceConstraint.C` you multiply JxW by 2. Perhaps this was SAM working around the bug

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
