### PR TITLE
Add debugging and fix KKS test for PETSc >= 3.6.0

### PR DESCRIPTION
**Pull request by dschwen**
The outcome solve/fail of a test in the phase field module depends on the order two nonlinear variables are declared in the `[Variables]` block. The previous order worked. I have switched it to the failing order to see what moose build makes of it.

### CODE REVIEW

**Comment by dschwen** [comment]
Ok, this can be merged now IMO. The debug statements are generally useful to figure out what the default material property system is doing, so I vote to let those in there. This PR fixes a Jacobian bug and a few bugs in getMaterialPropertyDerivative calls.

**Comment by friedmud** [comment]
Really?  We're going to merge print statements that always come out like this?

If we did this everywhere then we would have so much output that everyone would just ignore it.

I vote for a `verbose` flag for this particular thing... so if someone is interested specifically in why their properties are jacked up they can turn that on.

**Comment by dschwen** [comment]
Yeah we can do that. But it only prints in debug mode anyways, which is
what people resort to if they think something is broken.

**Comment by dschwen** [comment]
I can do a PR when I'm back from travel. If we make this a parameter the
output should be cleaned up more.

**Comment by friedmud** [comment]
But they might be in Debug mode looking for something else... And then they're bombarded with output from this system.

I think we're eventually going to need "logging levels" to help deal with this stuff....

**Comment by andrsd** [comment]
:+1: for the flag

**Comment by dschwen** [comment]
I'm removing the debug statements. I don't want to add a flag just now, as this interface does not have a ```validParams``` function yet, and adding one would complicate the use of the interface.

**Pull request merged**
