### PR TITLE
Initial ArrayKernel Capability

### PR DESCRIPTION
**Pull request by friedmud**
Ok - I know this is pretty rough... but I've taken it about as far as I can at the moment and I need to move on to other things.  I don't want to let this rot in a branch so I'd like to get it into the framework and then we can work on it over time.

Let's consider this as a "Technology Preview"...

The basic idea here is to create a new `MooseVariable` called `ArrayMooseVariable`.  One `ArrayMooseVariable` object actually stands for multiple libMesh variables that are all in the same variable group (i.e. they have the same `FEType`).

The "value" of an `ArrayMooseVariable` at a quadrature point is a vector (an `Eigen::VectorXd` to be precise).  The entries are the value of each variable in the variable group.

Similarly, the "gradient" is a matrix.  It has `n_vars` rows and `LIBMESH_DIM` columns.

The really great thing about these definitions is that libMesh stores all of the coefficients of all of the variables in a group right next to each other for each dof object.  That means that no copying has to take place to get to the values... instead, the raw PETSc vector can be operated on.  For convenience, this raw data can be wrapped in an `Eigen::Map` which makes it act just like any other `Eigen::VectorXd` (so you can do things like mat-vecs with it).

Also, since all of the data for each dof object is contiguous only _one_ `dof_indices()` call needs to be made... and all of the rest are inferred.  This allows for just one single `global_to_local_map()` call as well.

In addition, using Eigen facilitates really nice looking syntax in both the `ArrayKernel` and the `ArrayNodalBC` derived classes.  Here is what `computeQpResidual()` looks like for `ArrayDiffusion`:

``` C++
void
ArrayDiffusion::computeQpResidual()
{
  _residual.noalias() = _grad_u[_qp] * _grad_test[_i][_qp];
}
```

Other than this being an assignment instead of returning a value it looks JUST like normal MOOSE syntax.  The assignment is regrettable (especially the `noalias()` part which tells Eigen that the stuff on the right side is different from the stuff on the left so it can remove temporaries in the calculation) but there is no way around it.  I think it will become natural.

Similarly, `computeQpResidual()` in `ArrayDirichletBC` looks like this:

``` C++
void
ArrayDirichletBC::computeQpResidual()
{
  _residual.noalias() = _u[_qp] - _value;
}
```

So, again, it looks like normal MOOSE syntax.  Now, to get this one to work out I actually made `_value` a vector instead of a scalar.  That can be worked around in other ways with Eigen... but I chose this for now because it gives REALLY nice looking syntax ;-)

Now... what do we gain out of this 4,000 lines of code?  Well... speed of course!  Especially when you have lots of variables!  Here is a link to some timing runs I've done comparing a simple diffusion problem in 2D and 3D both with and without `ArrayKernel` (note: the `Optimized ArrayKernel` is the one represented in this pull request... the old one was an intermediate state): https://docs.google.com/spreadsheets/d/1if49FiqkBWSsZvdwBLV4lnfmZE1gXkKKZvJBybYoyvo/edit?usp=sharing

To summarize the link... in 2D you can expect this kind of speedup as you add more variables:

| # Vars | Speedup |
| --- | --- |
| 2 | 0.785 |
| 3 | 0.9 |
| 6 | 1.36 |
| 10 | 1.8 |
| 30 | 3.26 |
| 50 | 4.08 |
| 100 | 4.9 |
| 1000 | 6.54 |

6.5x at 1000 variables is nice.  That means something that used to run in an hour now runs in 10 minutes...

Ok... but there is still a TON left to do.
1.  Jacobians aren't implemented yet
2.  Doesn't work with threading yet!  (The way I interact with the PetscVector is not thread safe... the raw vector access needs to be done _around_ the `computeResidual()` threaded call)
3.  A ton of work needs to be done to allow coupling to these variables
4.  I'm sure that a mixed problem (normal vars and array vars) is not going to work yet (never tried)
5.  Only shape functions with one degree of freedom per dof object are supported.
   - This is because of a limitation in the way libMesh stores dof indices when a variable has more than one degree of freedom per dof-object.
   - I would like to provide a configure time option for changing this and then ArrayKernel should work
   - See my email to the libmesh-devel mailing list here: https://sourceforge.net/p/libmesh/mailman/message/35258936/
6. Decisions need to be made about how to handle sparsity pattern stuff for preconditioning (i.e. what does the "block diagonal" mean?  How do you specify that you want particular, individual couplings between variables in an ArrayVariable?)
7.  One of the big bummers is that I don't have a great answer to how we make every other system work with ArrayMooseVariables.  Like: are we going to have to create a whole copy of Postprocessors/UserObjects for Postprocessing ArrayMooseVariables?  This just remains to be seen.
8.  Tons of other stuff I know I'm forgetting.

Ok - that's enough for now.  Take a look at the code... and let's hammer out (most) of the rough edges for the capability that is currently here.  I know I'll go a few rounds with Civet first....

refs #6881

### CODE REVIEW

**Comment by YaqiWang** [comment]
Only the block diagonal part of the Jacobian is the part matters to our physics. All components of `ArrayMooseVariables` are actually decoupled from each other in our physics. If we can at least have `computeQpJacobian` in this PR, I can start trying it out. It will make the learning easier if there are some testing codes in.

So we cannot use array kernel for DG because of item 5?

**Comment by permcody** [comment]
@YaqiWang - We definitely want a customer for this but I also want to caution you from relying very heavily on the new system since we might up-end it at any time and change it a lot. 

@friedmud - I've looked over this code a bit and I see what you mean by rough... That's ok, it's a huge system and will take some effort to beat into shape. I'd like to hammer in a few new C++11 concepts since this is a new system instead of propagating the old stuff. We don't need to do that before merging this piece though. Let's get it up and running then we can start mod'ing it.

**Comment by permcody** [comment]
@friedmud - I'm going to close this PR since we know it's not going to be completed for quite some time. Just keep it around in your branch. Thanks!

**Comment by friedmud** [comment]
Makes sense :-)

**Comment by lindsayad** [comment]
I'm wondering whether I might be able to pick this branch up...@YaqiWang has identified this as the top priority for Rattlesnake

**Comment by lindsayad** [comment]
And if parts of this may be used for vector valued finite elements, then it would be of great interest to me for electromagnetics

**Comment by permcody** [comment]
The real challenge with ArrayKernels is Jacobians. Coming up with a reasonable interface for filling in the "matrix" of Jacobians when using ArrayKernel is challenging. Aside from that, integrating this into all the other places in MOOSE may not be easy. I love that you are looking for really challenging project, but this one might be too big to tackle right now. We can talk to Derek about this one too when we get on the phone with him.

**Comment by YaqiWang** [comment]
Is there something else in your mind? To me, if a task is important, we need to be right on it no matter how hard it is. This task is on top of the list of things we want to do for Rattlesnake...

**Comment by permcody** [comment]
Well the capability isn't all that important. What you are really hoping
for is speed. If we could give you speed, that would probably make you
happy!

**Comment by YaqiWang** [comment]
Actually that is not mainly for speed, it is more for the memory overhead of lots of kernels. I will be happy if it can also increase the speed ;-)

**Comment by YaqiWang** [comment]
@friedmud I am going to pick this up and push it into framework. I probably will have questions later.

**Pull request closed without merging**
