### PR TITLE
porous_flow: dirackernel.py now works for python3 and python2

### LINKED ISSUE #17558: TypeError: 'map' object is not subscriptable
## Reason

In several python scripts, we get TypeError: 'map' object is not subscriptable as in python3 map returns an iterable object of type map, and not a subscriptible list.

## Design

Converting the iterable object of type map to list. 

## Impact

The test python script will work with python3.

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #17558

Request review from @cpgr

### CODE REVIEW

**Comment by loganharbour** [comment]
Can you cherry-pick the commit from #17557 and then edit the commit message to add the issue reference?

I'd prefer to keep the contributors in the repo correct, more so when it's someone's first contribution :)

**Review by cpgr — APPROVED** [review]
👍

**Comment by WilkAndy** [comment]
> Can you cherry-pick the commit from #17557 and then edit the commit message to add the issue reference?
> 
> I'd prefer to keep the contributors in the repo correct, more so when it's someone's first contribution :)

Possibly!  I've never done that before.   Totally agree about authorship.   I won't be able to do it today - probably tomorrow.

**Comment by WilkAndy** [comment]
Just wanted to say that i *want* to do this, but it'll be easier once i can compile moose (#17582)

**Comment by WilkAndy** [comment]
@loganharbour - i can't get this cherry-picking thing to work.  Can you give a few more details?   This PR isn't urgent, as i suspect @rksin8 has got their own local amendments anyway.

**Comment by loganharbour** [comment]
I'm assuming here that `upstream` is your remote that points to `idaholab/moose`.

Sit on the right local branch
```
git checkout type_error_rksin8_17558
```

Update upstream
```
git fetch upstream
```

Reset current branch to idaholab/moose/devel
```
git reset --hard upstream/devel
```

Grab @rksin8's commit
```
git cherry-pick 215f312fd97f821ffb1fd1dbff1f0718a8dd5e08
```

Do an interactive rebase to reword it as needed
```
git rebase -i HEAD~1
```

At this point, maybe we should just have @rksin8 reword his own commit 😆

**Comment by WilkAndy** [comment]
Thanks @loganharbour, both for the recipe and instructions.  Unfortunately, that cherry-pick didn't work, perhaps because @rksin8 has deleted the repo.  I also tried
```
git remote add rksin8_stuff git@github.com:rksin8/moose.git
git fetch rksin8_stuff
git cherry-pick 215f312fd97f821ffb1fd1dbff1f0718a8dd5e08
```
which returned:
```
fatal: bad object 215f312fd97f821ffb1fd1dbff1f0718a8dd5e08
```
Any further ideas?

**Comment by WilkAndy** [comment]
OK, i'm getting no traction on this from @rksin8 .   Let us thank him and merge this PR, heh?

**Comment by loganharbour** [comment]
Closed in favor of #17971.

**Pull request closed without merging**
