### PR TITLE
Move media files to LFS

### PR DESCRIPTION
**Pull request by dschwen**
The moose repo is in in inconsistent state regarding LFS as the storage typ mandated in `.gitattributes` and the storage actually used for the files in `docs/media/rdg` conflict.
This PR fixes this by moving the two files to LFS.
PRs should be tested to make sure that files that should go in LFS are actually committed correctly.

Refs #8082

### CODE REVIEW

**Comment by dschwen** [comment]
Unfortunately Github is completely transparent to LFS. Maybe we can get this tested in moosetest @brianmoose ?

My local `git log --stat` shows that this commit is effective though:

```
commit 486fef1f340aa29d3f0b469a99652fd0d665474a
Author: Daniel Schwen <daniel.schwen@inl.gov>
Date:   Mon Dec 12 12:56:41 2016 -0700

    Move media files to lfs (#8082)

 docs/media/rdg/anim_1d_aefv_square_wave.gif | Bin 2250820 -> 132 bytes
 docs/media/rdg/fig_1d_aefv_square_wave.png  | Bin 36732 -> 130 bytes
 2 files changed, 0 insertions(+), 0 deletions(-)
```

**Comment by dschwen** [comment]
@andrsd @jwpeterson @permcody Could anyone "review" (it is a trivial change) and merge this please. This is driving me nuts and totally crippling my work.

**Review by andrsd — APPROVED** [review]

**Comment by andrsd** [comment]
How do we prevent this in future?

**Comment by dschwen** [comment]
With a pre-test I'd say.

**Pull request merged**
