### PR TITLE
Make September 2023 news public

### PR DESCRIPTION
**Pull request by cticenhour**
Add October 2023 news template

Refs #11447

### CODE REVIEW

**Comment by roystgnr** [comment]
Somehow I didn't get the libMesh submodule update newsletter entries into the eventual PR that included the submodule update.  That's embarrassing.

**Comment by cticenhour** [comment]
@GiudGiud I just did a quick edit of the contributed text, and I think most of the changes were in your contributions. Please let me know if you'd like more tweaks. 

Tagging @joshuahansel for the full review.

**Review by GiudGiud — DISMISSED** [review]
good for me
@lindsayad last chance

**Review by lindsayad — CHANGES_REQUESTED** [review]
merp. Incoming

**Review by lindsayad — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]
Approving everyone else's but mine

**Pull request merged**
