### PR TITLE
sort glob output in chigger animation

### LINKED ISSUE #16697: images going into chigger gif animation are not sorted
## Bug Description
Gif creation in `chigger.utils.anim` uses `glob` for image search but results from `glob` are [not guaranteed to be sorted](https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered). As a result, gif frames can be rendered out of order.

## Steps to Reproduce
Create a gif from an image stack and see for yourself.

## Impact
Will help with visualization.

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
Sorts glob output so gifs come out in the right order. There probably should be a test for this. What do you think @aeslaughter ?

closes #16697

### CODE REVIEW

**Review by aeslaughter — DISMISSED** [review]

**Comment by aeslaughter** [comment]
Works for me and a test would be great.

**Comment by jessecarterMOOSE** [comment]
ok @aeslaughter I added a test.

**Review by aeslaughter — APPROVED** [review]
You are now an expert for chigger development, I'll start passing things your way. 😏  Thanks!

**Comment by jessecarterMOOSE** [comment]
@aeslaughter any idea why the testing is hung up?

**Comment by aeslaughter** [comment]
No. I restarted it.

**Comment by jessecarterMOOSE** [comment]
That seems to have done the trick :+1:

**Pull request merged**
