### PR TITLE
Fix PR 15216

### PR DESCRIPTION
**Pull request by dewenyushu**
Fix memory problem, remove redundant gold file, amend PR #15216.

### CODE REVIEW

**Comment by dewenyushu** [comment]
@andrsd here is the fix. Thanks for finding the origin of the problem!

**Comment by andrsd** [comment]
Enabled the 2 valgrind targets that failed on `next`, so we are sure this will fix it.

**Review by andrsd — DISMISSED** [review]
Cool that you fixed the other 2 problems :+1:

**Comment by andrsd** [comment]
@dewenyushu Why did you close this?

**Comment by dewenyushu** [comment]
> @dewenyushu Why did you close this?

Ahh, I was rebasing the branch and accidentally pushed it, and now it shows all the files changes in the PR and PR 15216...

This PR met an error in documentation check though which I think should not have been caused by this PR:

`MooseDocs.commands.check (MainProcess): The class description is missing for /Kernels/ADMatHeatSource, it can be added using the 'addClassDescription' method from within the objects validParams function.
MooseDocs.commands.check (MainProcess): The class description is missing for /BCs/CavityPressure/CavityPressureAction, it can be added using the 'addClassDescription' method from within the objects validParams function.
MooseDocs.commands.check (MainProcess): The class description is missing for /BCs/CavityPressure/CavityPressureUOAction, it can be added using the 'addClassDescription' method from within the objects validParams function.
MooseDocs.commands.check (MainProcess): The class description is missing for /Modules/TensorMechanics/Master/CommonTensorMechanicsAction, it can be added using the 'addClassDescription' method from within the objects validParams function.`

**Comment by andrsd** [comment]
The doco fix is already in the next, so don't worry about that. We need clean valgrind targets.

**Comment by andrsd** [comment]
also, should not there be only 1 commit on this branch that fixes the memory leak? why are there 4  commits now?

**Comment by dewenyushu** [comment]
> The doco fix is already in the next, so don't worry about that. We need clean valgrind targets.

Ah okay. Thought my fix caused the issue and trying to debug that... Good to know

**Comment by dewenyushu** [comment]
> also, should not there be only 1 commit on this branch that fixes the memory leak? why are there 4 commits now?

These ones now contain the commit from the merged PR somehow.. I will probably need to open a different PR or something

**Comment by andrsd** [comment]
You can fix that easily:
```
$ git checkout dual_mortar_15215
$ git rebase --onto devel HEAD~1 dual_mortar_15215
```
Then, make sure there really is 1 patch by:
```
$ git log devel..
```
This should show your top-most patch.

Then, force push your branch and reopen this PR.

Don't create more work for yourself then needed...

**Pull request closed without merging**
