### PR TITLE
Revert wasp submodule update

### PR DESCRIPTION
**Pull request by cticenhour**
Refs #25411

### CODE REVIEW

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
you might have to rebase this on next...

**Review by milljm — APPROVED** [review]
👍

**Comment by cticenhour** [comment]
@milljm Had the same thought at the same time 😄

**Comment by loganharbour** [comment]
This probably shouldn't have been merged and needs to be looked into a little more. Triggering a wasp change and not triggering an apptainer moose-dev or conda moose-dev change is concerning

**Comment by dschwen** [comment]
> This probably shouldn't have been merged and needs to be looked into a little more. Triggering a wasp change and not triggering an apptainer moose-dev or conda moose-dev change is concerning

This reverts a change that was missing all of the things you mentioned.

**Comment by loganharbour** [comment]
> > This probably shouldn't have been merged and needs to be looked into a little more. Triggering a wasp change and not triggering an apptainer moose-dev or conda moose-dev change is concerning
> 
> This reverts a change that was missing all of the things you mentioned.

Even more the reason then, no? 🥴 when things aren’t understood, which it seems like they weren’t, better to force a build

**Comment by cticenhour** [comment]
For this specific case, I felt pretty confident that this would work fine to return us to a good state after looking through the python and CIVET scripts, even if I was missing some of the workflow context that you provided this morning (thanks again for that!). I had another version of this branch with a full set of package updates, but I felt it was better to *not* force a build when the triggered container hadn't made it to a master merge (which we got lucky about this time, given the modules failures). If it had gone farther than next, I would have incremented the packages.

**Pull request merged**
