### PR TITLE
Fix NaN in r,theta calculation in CrackFrontDefinition

### LINKED ISSUE #5222: Fix NaN in CrackFrontDefinition
In a calculation of an angle with arcsin(leg/hypotenuse), I ran into a case where the leg was slightly longer (by 1e-13) than the hypotenuse, resulting in a NaN. This is presumably just a roundoff error in the calculation of the leg and hypotenuse, so I'm adding a fuzzy compare and an error check.

### PR DESCRIPTION
**Pull request by backmari**
closes #5222

### CODE REVIEW

**Comment by permcody** [comment]
@backmari - both of these failures are due to the libmesh/petsc update. Just leave it alone and I'll invalidate the builds later. This PR looks fine.

**Comment by backmari** [comment]
Okay, thanks @permcody.

**Comment by bwspenc** [comment]
@backmari This looks good to me.  My only comment is that we shouldn't have two separate tolerances.  I assume that you added a special tolerance of 1e-10 because the existing tolerance of 1e-14 was too small.  I would just change the existing tolerance to 1e-10 and use that.  I don't think it was chosen very scientifically.

**Comment by dschwen** [comment]
Since @backmari does not have code development in her contract she cannot possible have made this PR. Should we just close it? ;-)

**Comment by backmari** [comment]
@bwspenc Great, yes I didn't know if the 1e-14 was chosen based on some specific criterion. I'll change the existing tolerance and use that.

**Comment by backmari** [comment]
@dschwen :-)

**Pull request merged**
