### PR TITLE
Consistent interface for member template functions

### PR DESCRIPTION
**Pull request by lindsayad**
We had added a lot of macros prefixed with ad in order to hide this->template
syntax from users. A more consistent interface is to rename the member template
functions and then give the macros the original name so that users experience
no disruption in the interface when moving from traditional
objects to AD.

### CODE REVIEW

**Comment by tophmatthews** [comment]
Dude...you couldn't have done this before I did all the bison changes?

**Comment by lindsayad** [comment]
Hey I’m the one who’s gonna have to go fix it :-(

**Comment by dschwen** [comment]
This is great. The quicker this goes in the better for me. I have a bunch of PRs in flight and would love to get them fixed.

**Comment by dschwen** [comment]
Uh oh, this might have been a horrible mistake...

**Comment by lindsayad** [comment]
Lol, what is this plundering of my PR?

**Comment by dschwen** [comment]
Yeah, is there a way to lock the GitHub "resolve conflict" functionality. I think I have used that before and got yelled at because it creates a weird topological feature in the git commit graph. I just had forgotten about it.

**Comment by dschwen** [comment]
Ugh, macro substitutions in class declarations and member function headers...

**Review by permcody — APPROVED** [review]

**Pull request merged**
