### PR TITLE
Added ability to use old temperature for thermal expansion

### LINKED ISSUE #16019: Add option to use old temperature in thermal expansion calculations
## Reason
There are times when the temperature is not changing drastically where decoupling the temperature from the thermal expansion strain can help convergence.

## Design
Optionally use the temperature from the previous timestep for thermal expansion calculations.

## Impact
Better simulation flexibility.

### PR DESCRIPTION
**Pull request by tophmatthews**
closes #16019

### CODE REVIEW

**Comment by tophmatthews** [comment]
ping @dschwen for review

**Comment by dschwen** [comment]
@tophmatthews can you demonstrate that this indeed improves convergence in a realistic application?

**Comment by tophmatthews** [comment]
Well...only qualitatively. I've seen better norms, but I don't have a good example on hand @dschwen ...

**Comment by dschwen** [comment]
I'm a little concerned about adding code paths that are "shots in the dark". This should be easily testable using the Bison assessment cases.

**Review by dschwen — APPROVED** [review]
The implementation is fine. If it helps, get it merged.

**Comment by tophmatthews** [comment]
So this has been sitting approved for a week now, whats the next step to get this in?

**Comment by dschwen** [comment]
You nagging

**Comment by dschwen** [comment]
More seriously, I wanted to give other devs the opportunity to chime in. Didn't happen, I forgot about it. Thanks for the reminder!

**Pull request merged**
