### PR TITLE
added error if last entry in point_file is not at the well bottom,

### LINKED ISSUE #24639: porousflow module:  Error if the last point given for a peaceman borehole is not the deepest
## Reason
The function used to activate the peaceman borehole is evaluated based on the well bottom which should be the point with the smallest z-coordinate value.  The well bottom is determined by the last value given in the point_file.  There should be an error if the last value given in the point_file has a higher elevation than the first value given in the point_file.  

## Design
Add an error.  

## Impact
Input files that previously ran will no longer run if the points in the point_file are not ordered from shallowest to deepest.

### PR DESCRIPTION
**Pull request by lynnmunday**
By well bottom, I mean has the lowest z-coordinate.  The last entry is where the function given by bottom_p_or_t is evaluated and this function needs to be evaluated at the well bottom.  closes #24639

### CODE REVIEW

**Comment by lynnmunday** [comment]
@WilkAndy @cpgr Will you review?  I added an error because this took me a while to debug.  I finally came across the answer in sink.md about the csv point_file ordering for the well bottom.  I changed a lot of csv files so maybe they are not always ordered shallowest to deepest but I think they should be.

**Comment by cpgr** [comment]
This looks ok. I guess we never had a test where the bottomhole pressure was given by a function that depended on depth, so never ran into this?

**Review by GiudGiud — APPROVED** [review]

**Comment by lynnmunday** [comment]
> This looks ok. I guess we never had a test where the bottomhole pressure was given by a function that depended on depth, so never ran into this?

@cpgr there wasn't a test for bottomhole pressure being a function of depth.  This change will cause simulations to error out if they are using a bottom_p_or_t function AND they have the csv peaceman file ordered incorrectly.  I also could have resorted the csv file that was read in and not error out.

**Comment by GiudGiud** [comment]
Ping me when I should merge / everyone agrees

**Comment by lynnmunday** [comment]
@GiudGiud This is good, you can merge it.

**Pull request merged**
