### PR TITLE
Merging the (e,v) and (p,T) branch in fluid_properties

### PR DESCRIPTION
**Pull request by andrsd**
1. Class hierarchy is merged into one branch.
2. rho(p, T) is renamed to rho_p_T to follow the naming conventions.

### CODE REVIEW

**Comment by andrsd** [comment]
Tagging @cpgr @WilkAndy

**Comment by andrsd** [comment]
The 2 fails in RELAP-7 and pronghorn are expected:

1. The failing test in RELAP-7 was made invalid by this merge (we guarded against the usage of p,T formulation). That is now allowed.
2. pronghorn fail is caused by `cp`, `cv` name collision. The reason is explained in the first commit.

So this could go in. I will fix RELAP and pronghorn and then the subsequent changes should not break anything else.

**Comment by andrsd** [comment]
Patches for pronghorn and RELAP-7 are ready.

**Comment by andrsd** [comment]
Patch for SAM is ready as well.

**Comment by veeshy** [comment]
Any chance you have a script that made those internal projects work easier? I have PT FP used a bunch throughout my project. I’m sure I can figure out the right sed but if you already did I’d appreciate it! This is a great PR!

**Comment by andrsd** [comment]
I do not have a script, I just use atom and do search and replace. The problem is that not all of the names should be replaced. There are things in `fluid_properties` module that have to stay unchanged for right now. This is probably not an issue in an app. If your app is publicly available, I can send you a PR...

**Comment by veeshy** [comment]
Ah okay I’ll just do the same since my app is private unfortunately.

**Review by permcody — APPROVED** [review]

**Pull request merged**
