### PR TITLE
Add option to specify mean CTE function

### PR DESCRIPTION
**Pull request by bwspenc**
ref #4717

### CODE REVIEW

**Comment by bwspenc** [comment]
@backmari You may want to take a look at this.

**Comment by bwspenc** [comment]
This is failing on the ```utils/random.threads_verification``` test, which shouldn't have anything to do with this.

**Comment by permcody** [comment]
That test is just a little bit unstable. It fails maybe 2-5% of the time.
We can invalidate and run the tests again

**Comment by backmari** [comment]
The CTE calculation looks good to me. Good call to move delta_t from the denominator.

**Pull request merged**
