### PR TITLE
Remove deprecated code in tensor_mechanics

### PR DESCRIPTION
**Pull request by bwspenc**

### CODE REVIEW

**Comment by permcody** [comment]
Looks like you are removing several objects, however it looks like you are only removing registration from one. That might be correct. I just want to make sure.

**Comment by bwspenc** [comment]
Yeah, a few of them were not registered.

On Feb 24, 2017, at 8:35 AM, Cody Permann <notifications@github.com> wrote:

Looks like you are removing several objects, however it looks like you are
only removing registration from one. That might be correct. I just want to
make sure.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_8622-23issuecomment-2D282321071&d=DQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=hn5akMybrkn-1oiQB8nm_y7trT_BOQm9jBgbzQWwxXA&m=b44v7-VU6gpr_JQbUmPrJ2pRyt4GCHj1pIxkszS7J70&s=gkKRclQKIscUhBHkXkXmC8jCjEMolp5Q5WCA6YMDo3A&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGTYdDgGuvyBy1MeE78pT9GU9ZtIN-2Dsaks5rfviZgaJpZM4MKtnB&d=DQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=hn5akMybrkn-1oiQB8nm_y7trT_BOQm9jBgbzQWwxXA&m=b44v7-VU6gpr_JQbUmPrJ2pRyt4GCHj1pIxkszS7J70&s=RqI_J304Hp6cFHB4hlWUibwTzIm-TDbID4GJbKaLj5M&e=>
.

**Comment by rwcarlsen** [comment]
Anything blocking this besides a rebase?

**Comment by bwspenc** [comment]
@rwcarlsen Sorry, this is pretty old.  I think this ended up breaking some stuff in Marmot that I didn't anticipate.  I need to scale this down and not remove as much stuff.  I'll take a look at it.

**Comment by permcody** [comment]
Would really like to remove deprecated code. Maybe we should revisit this?

**Comment by dschwen** [comment]
I can get on this. The materials that fail Marmot can largely be removed.

**Comment by dschwen** [comment]
Let's try this again. The Marmot fail should be fixed now.

**Comment by bwspenc** [comment]
OK, I'll revive this and see if it will work now.

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
The mammoth fix looks easy. Are you doing it @bwspenc ?

**Pull request merged**
