### PR TITLE
Variables explicitly initialized in DistributedGeneratedMesh

### LINKED ISSUE #11878: DistributedGeneratedMesh.C possibly unitialized values
## Rationale

My compiler says there are possibly unitialised values in DistributedGeneratedMesh.C .  Probably just want to set ```i=j=k=0``` but i don't want to go ahead and write this in case there's a better initialization.

## Description

```
/projects/cmrp/projects_wil04q/moose/framework/src/mesh/DistributedGeneratedMesh.C: In function âvoid build_cube(libMesh::UnstructuredMesh&, unsigned int, unsigned int, unsigned int, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::ElemType, bool) [with T = libMesh::Quad4; libMesh::Real = double]â:
/projects/cmrp/projects_wil04q/moose/framework/src/mesh/DistributedGeneratedMesh.C:1244:5: warning: âkâ may be used uninitialized in this function [-Wmaybe-uninitialized]
     add_element<T>(nx, ny, nz, i, j, k, ghost_id, part[ghost_id], type, mesh, verbose);
     ^
/projects/cmrp/projects_wil04q/moose/framework/src/mesh/DistributedGeneratedMesh.C: In function âvoid build_cube(libMesh::UnstructuredMesh&, unsigned int, unsigned int, unsigned int, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::Real, libMesh::ElemType, bool) [with T = libMesh::Edge2; libMesh::Real = double]â:
/projects/cmrp/projects_wil04q/moose/framework/src/mesh/DistributedGeneratedMesh.C:1244:5: warning: âjâ may be used uninitialized in this function [-Wmaybe-uninitialized]
/projects/cmrp/projects_wil04q/moose/framework/src/mesh/DistributedGeneratedMesh.C:1244:5: warning: âkâ may be used uninitialized in this function [-Wmaybe-uninitialized]
```

## Impact

Stronger code.

### PR DESCRIPTION
**Pull request by WilkAndy**
Please check, @friedmud

Fixes #11878

### CODE REVIEW

**Comment by friedmud** [comment]
Ummm - it doesn't matter... i,j,k are set immediately by calling `getIndices()`.  Is this because Valgrind is showing something, or something?  Because it didn't show up in our Valgrind testing.

**Comment by WilkAndy** [comment]
Not valgrind but my compiler produces the warning.  Please just kill this PR if you think it's pointless.

**Comment by friedmud** [comment]
Interesting - always good to squash compiler warnings.  Can you tell us which compiler?  I thought we had `-Wall` and `-Werror` turned on during testing to prevent this kind of thing.

Also: can you copy/paste the error that you're seeing?

I'm not really against this PR - I just want to understand why it's doing what it's doing before we make a decision.

**Comment by WilkAndy** [comment]
I copied the error to #11878 .  Compiler is

> mpicxx -v
Using built-in specs.
COLLECT_GCC=/apps/gcc/4.9.3/bin/g++
COLLECT_LTO_WRAPPER=/apps/gcc/4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --disable-multilib --enable-languages=c,c++,fortran,java,lto,objc,obj-c++,go --prefix=/apps/gcc/4.9.3 --with-isl=/apps/isl/0.14.1 --with-gmp=/apps/gmp/6.1.0 --with-mpc=/apps/mpc/1.0.3 --with-mpfr=/apps/mpfr/3.1.4 --with-cloog=/apps/cloog/0.18.4
Thread model: posix
gcc version 4.9.3 (GCC)

**Comment by permcody** [comment]
I looked into this a bit. The problem is that i,j,k are _not_ always set for lower dimensional cases. Of course they aren't used either in those cases, so it's ultimately not a problem. Still, Andy's GCC complains because I guess it thinks they are "possibly" uninitialized, which is technically true. I tried to replicate on our Linux machines and was unable. I think it's worth merging since this is the second time he's opened up a ticket mentioning this issue.

**Comment by WilkAndy** [comment]
"since this is the second time he's opened up a ticket mentioning this issue"

LMHO !    I had totally forgotten, of course.   Now i'm wondering in how many other instances you guys have been banging your heads on your desks: "geez, why doesn't that Andy just shut up - he keeps repeating the same thing over and over!"

**Comment by permcody** [comment]
The fact that you make an occasional mistake is the only reason I believe you are a human instead of my gut instinct that you might be a highly advanced robot with the amount of code and documentation you produce. 

However, you did out-eat Rich M. once, so there's that (only a robot could do that).

**Comment by permcody** [comment]
I was able to reproduce. This will fix it. Thanks!

**Review by permcody — APPROVED** [review]

**Pull request merged**
