### PR TITLE
fix turbulence channel test input

### LINKED ISSUE #27776: Fix the pressure pinning in the turbulent channel test input
### Bug Description

The input pins the pressure at a point in the domain, which leads to errors when refining the mesh for an inlet-outlet type of problem. 

### Steps to Reproduce

in 'channel_ERCOFTAC.i', refine the mesh y-divisions (e.g. from ny=5 to ny=20) and spot the artifact in the inlet velocity. 

### Impact

It does not prevent work from getting done. 

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by freiler**
Closes #27776

## Reason
-The test input pins the pressure at a point in the domain, which leads to errors when refining the mesh for an inlet-outlet type of problem.

### CODE REVIEW

**Review by grmnptr — CHANGES_REQUESTED** [review]
This will likely need a regold.

**Comment by tanoret** [comment]
Good solution. @grmnptr what are we rebasing on next?

**Comment by grmnptr** [comment]
We merge PRs to next, the PR was set up to merge into devel which is forbidden.

**Review by grmnptr — APPROVED** [review]
Nice catch!

**Pull request merged**
