### PR TITLE
Create SQA Document Inheritence

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
@permcody I will let you know when this is ready for you to look at, there is something weird going on when CIVET is building the site. This is a problem for tomorrow Andrew.

**Comment by aeslaughter** [comment]
@permcody @jasondhales @bwspenc @sapitts 

This is a prototype of the inherited SQA documentation, start from the following link and hopefully you can see what I am doing.

https://mooseframework.inl.gov/docs/PRs/13680/site/sqa/index.html

**Comment by aeslaughter** [comment]
FYI, I will just disable SQA in the apps to avoid the submodule update mess. As I setup the apps to use this new system I will turn it back on.

**Comment by aeslaughter** [comment]
@permcody Check out this link, if you haven't yet: https://mooseframework.inl.gov/docs/PRs/13680/site/sqa/index.html

**Review by permcody — APPROVED** [review]

**Pull request merged**
