### PR TITLE
DistributedMesh restart should skip partitioning and renumbering

### PR DESCRIPTION
**Pull request by roystgnr**
This fixes occasional bugs when parallel restart meshes are hit by
non-idempotent repartitioning.  In particular it fixes the
restart/new_dt.test_restart test with --distributed-mesh --recover
settings.  That test is an example of #5877, mixing recovery with
restarts, and it now works on 1 through 24 processors, so there's a
chance that that capability is working now.

This fixes some but not all of the potential DistributedMesh restart
problems discussed in #8410.  I'll open a new ticket for the remaining
issue.

### CODE REVIEW

**Comment by roystgnr** [comment]
I need to do some more testing of this before I'll be certain it fixes the problem.

**Comment by roystgnr** [comment]
No, this doesn't work.  The "success on 1 through 24 processors" came from a *previous* attempt at this branch, where I inadvertently disabled repartitioning+renumbering regardless of the value of _app.isRestarting(), and thereby broke a bunch of other tests.

Now, I am testing _app.isRestarting()... and that always returns false, regardless of the value of Problem/restart_file_base in the input file.  I guess that SetupMeshAction precedes CreateProblemAction, so by the time the MooseApp knows it's restarting, it's too late and the mesh has already been incorrectly set up?

**Comment by roystgnr** [comment]
I guess the thing to do in the short term is to test the mesh file suffix and only disable repartitioning/renumbering for CheckpointIO files.

**Comment by roystgnr** [comment]
Yes, that fixes the problem for me.

**Review by permcody — APPROVED** [review]

**Pull request merged**
