### PR TITLE
Moose enum error

### PR DESCRIPTION
**Pull request by permcody**
I set out to just add an assertion to MooseEnum for #7141. I did that.
- I also added the capability for mooseAssert to throw so that we can test assertions.
- Fixed a bad comparison in ConsoleUtils

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Awesome. Much cleaner than anything I could have done. I never quite grasped the unit testing system anyway.

**Comment by jessecarterMOOSE** [comment]
BTW @permcody, my testing showed this needs a comma too:

https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/src/utils/MultiPlasticityDebugger.C#L13

**Comment by jwpeterson** [comment]
:+1: Aside from the fact that unit tests are not run in debug mode (and so the assertions are not actually tested).  I think we are planning to add a devel target in the near future, though.

**Comment by jwpeterson** [comment]
> BTW @permcody, my testing showed this needs a comma too:

This is fixed in 283a515

**Pull request merged**
