### PR TITLE
Cache (active) semilocal elements

### LINKED ISSUE #7096: Add cache for semilocal elements to FeatureFloodCount
### Description of the enhancement or error report
Currently FFC uses `ELEM::is_semilocal`, which does a bunch of `find_point` calls. Those are expensive (and apparently a bit dangerous with higher order elements and displaced meshe). I'd like to add a cache (set) containing all semilocal element IDs that is built whenever the mesh changes (or on initialize of the FFC).

### Rationale for the enhancement or information for reproducing the error
Replace the slow and error prone call to `is_semilocal` with a fast std::set::find call.

We observe segfaults and assertions in debug related to `contains_vertex_of` where shared vertices are not correctly detected as mutually contained in the elements.

### Identified impact
Fix use of FFC with Riso AN3 Bison assessment case.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #7096

### CODE REVIEW

**Comment by permcody** [comment]
Well that was easy. I bet it produces a noticable speedup too. I ran several timing cases a few weeks ago. I'll have to rerun some of those cases and see if this helps.

**Comment by friedmud** [comment]
Yikes: I just looked at the implementation of `Elem::is_semilocal()`... that looks _incredibly_ slow... building a temporary `std::set` for every call!?!?  Yikes!

**Comment by dschwen** [comment]
Not to mention the inverse map which means many many Newton solves for each call...

Anyhow, there seems to be a fail related to this PR (`Assertion `start_elem->active()' failed.`). I'll look into it and fix it.

**Comment by permcody** [comment]
Yeah libMesh could probably use a slightly less general, but more useful
neighbor algorithm that just finds neighbors based on connectivity
information.

**Comment by friedmud** [comment]
@permcody this isn't really about finding "neighbors".  The real neighbors are actually stored on the `Elem`.  This is about finding "point" neighbors... two elements that share any point.  This is made MUCH more difficult by the fact that elements of different dimension can be attached to each other at nodes... that's what a lot of the code in there is for.

In the particular case of "semilocal" elements... I really think that a flag needs to be added to `Elem` to indicate "ghosted" elements.

I mentioned a few months ago that I want to "ghost" more layers... but libMesh really doesn't make that easy.  As you can see in this one case the idea of even _being_ "semilocal" means you're either local or connected to a local element through a point.  I really want to mark elements as being "ghosted" and have libMesh automatically manage that.  It would make this kind of thing trivial because the semilocal check would just check to see if it's local or if it's ghosted...

Anyway - that's off-topic.  This PR is a good way to handle things given the current state of the code.

**Comment by permcody** [comment]
Yes, I do understand the distinction of what this lookup is trying to do. I think we all keep running into this. You wanted additional "ghost layers", I want additional "halo" layers. They all keep coming back to needing a better way to track ghost elements instead of discovering them in this expensive fashion. @jwpeterson added a ghost element iterator to libmesh but it is too expensive to for any time sensitive code.

**Comment by dschwen** [comment]
Hmm, I rebased and ran the failed test (`ACGrGrElasticDrivingForce.bicrystal`) on my local machine and it passed. :-/

**Comment by permcody** [comment]
Good News Everyone! This optimization looks really promising:

Before optimization on a medium-small problem (10s of thousands of dofs) :
```
| FeatureFloodCount                                                                                                       |
|   mergeSets()                              11         0.1010      0.009178    0.1010      0.009178    0.06     0.06     |
|                                                                                                                         |
| GrainTracker                                                                                                            |
|   execute()                                11         8.6050      0.782270    8.6050      0.782270    4.96     4.96     |
|   finalize()                               11         8.9513      0.813757    9.0840      0.825818    5.16     5.24     |
|   remapGrains()                            11         0.0040      0.000362    0.0040      0.000362    0.00     0.00     |
|   trackGrains()                            11         0.0277      0.002520    0.0277      0.002520    0.02     0.02     |
```

After Optimization:
```
| FeatureFloodCount                                                                                                       |
|   mergeSets()                              11         0.0976      0.008871    0.0976      0.008871    0.06     0.06     |
|                                                                                                                         |
| GrainTracker                                                                                                            |
|   execute()                                11         3.1068      0.282434    3.1068      0.282434    1.83     1.83     |
|   finalize()                               11         1.0357      0.094151    1.1663      0.106031    0.61     0.69     |
|   remapGrains()                            11         0.0039      0.000355    0.0039      0.000355    0.00     0.00     |
|   trackGrains()                            11         0.0292      0.002655    0.0292      0.002655    0.02     0.02     |
```

Scroll over and look at the GrainTracker "execute" and "finalize". It looks like it may be around a 4x speed up for this problem. I expect it would be even more significant in 3D.

**Comment by dschwen** [comment]
@permcody, I've added `meshChanged` to FFC to only rebuild the set when necessary. I also added some debug output to count the number of calls to is_semilocal in initialize vs. the number of calls avoided in execute.

For ACGrGrElasticDrivingForce.bicrystal I get:

```
84 calls to is_semilocal in initialize
366 calls avoided in execute
```

So even for a small test it seems to be worth it.

**Comment by dschwen** [comment]
This is ready for a final review @permcody

**Comment by friedmud** [comment]
@dschwen do you think this cache should be here... or should it go on `MooseMesh`?

We already have an `MooseMesh::activeSemiLocalNodeRange()`...

**Comment by dschwen** [comment]
I know, I discussed this with Cody last week. We decided to put it in FFC first and move it if we find other applications for it.

**Comment by friedmud** [comment]
Fine with me... just checking!

**Comment by permcody** [comment]
This is awesome! 😄  👍

**Pull request merged**
