### PR TITLE
Improve non-functional requirements

### PR DESCRIPTION
**Pull request by aeslaughter**
The first three commits implement an approach I ended up abandoning because it was a bit too complex, but it did include a feature that I would like to maintain the history on just in case we need to do something more extensive after the next audit.

The approach I settled simple allows a "classification" to be set in the test specs.

### CODE REVIEW

**Comment by aeslaughter** [comment]
This now includes an improved failure analysis that includes documentation regarding what we perform automatically. It also uses the same "collections" mechanism to allow for non-functional requirements to be defined and reported.

**Comment by aeslaughter** [comment]
When the dos are done building again the following links will help:

Failure Analysis Docs
https://mooseframework.inl.gov/docs/PRs/16472/site/sqa/moose_far.html
https://mooseframework.inl.gov/docs/PRs/16472/site/sqa/framework_far.html

Other Docs Added
https://mooseframework.inl.gov/docs/PRs/16472/site/python/MooseDocs/extensions/sqa.html
https://mooseframework.inl.gov/docs/PRs/16472/site/python/moosesqa/index.html

**Comment by loganharbour** [comment]
Wanna take care of the conflict before I review?

**Review by loganharbour — CHANGES_REQUESTED** [review]
All in all looks good to me. I spent quite a while looking through the documentation and it's awesome.

There is an issue here (see last link in bullets):
https://mooseframework.inl.gov/docs/PRs/16472/site/sqa/moose_far.html

I tried to find it, but I'm not familiar with the syntax enough.

Edit: Failures are related. BISON should hopefully be fixed in the near future.

**Comment by aeslaughter** [comment]
The missing link was due to the addition of the Navier Stokes SQA pages added in #16651.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
