### PR TITLE
Restore two term expansion as default for (P)INSFV

### PR DESCRIPTION
**Pull request by lindsayad**
This requires implementing try-catch blocks where we first try gradient computation with the two term boundary expansion and then if we get a singular system when performing the LU decomposition, then we switch to a one term boundary expansion just for the currently failing element.

If we had kept this as the default without reverting the behavior in #17716 then @joe61vette probably would have never sent us that failing input and we wouldn't have spent the last month in a panicked state about how broken our fluids application is (of course there is more work to be done, but things aren't perhaps as bad as we thought).

Refs #16822

### CODE REVIEW

**Comment by lindsayad** [comment]
Ok I think this is ready

**Review by GiudGiud — DISMISSED** [review]

**Comment by lindsayad** [comment]
Another example of why automated coverage is so awesome. I thought I added a test that was specifically targeting `INSFVVelocityVariable::adGradSln` but I totally missed and hit `MooseVariableFV::adGradSln` instead! Wouldn't have caught that without the automated coverage testing

**Comment by GiudGiud** [comment]
Umm so do we need a test to cover the exception case in MooseVariableFV then?

**Comment by lindsayad** [comment]
Nah that was already tested in MOOSE test. With the change to the NS test that now captures both `adGradSln` implementations

**Comment by lindsayad** [comment]
alright ... 100% coverage now. @GiudGiud can I get a re-approval please?

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
