### PR TITLE
Make Picard solve able to output solutions during Picard iteration

### LINKED ISSUE #11934: Request output intervals for picard iterations
## Rationale

Currently picard takes in 3 types of syntax:
picard_max_its
picard_rel_tol
picard_abs_tol

I propose to add a fourth syntax:
picard_output_interval = n

so an output exodus is available every n picard iterations for visualization/debugging purposes.

## Description

It is necessary to solve certain systems using picard iterations. Some of them require a large number of picard iterations to get to steady state. However, there is currently no interface to write an temporary/debugging output from picard iteration, which makes it impossible to understand the status of the system during picard iterations.

## Impact

New capability

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #11934 1934

The output for the transient test is like the following:
```
|   1.800000e+00 |   5.000000e+00 |
|   1.810000e+00 |   1.000000e+00 |
|   1.830000e+00 |   3.000000e+00 |
|   1.900000e+00 |   5.000000e+00 |
|   1.910000e+00 |   1.000000e+00 |
|   1.930000e+00 |   3.000000e+00 |
|   2.000000e+00 |   5.000000e+00 |
+----------------+----------------+
```
where 1.8, 1.9 and 2.0 are the normal outputs on time steps. 1.91, 1.93 for example are the outputs during Picard iteration for time 2 at the first and the third picard iterations (at time 2, there are only 4 picard iterations).

The output for the steady test is:
```
+----------------+----------------+----------------+
| time           | unorm          | vnorm          |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   9.630100e-01 |   5.773503e-01 |
|   2.000000e+00 |   1.049102e+00 |   6.494461e-01 |
|   3.000000e+00 |   1.057824e+00 |   6.570847e-01 |
|   4.000000e+00 |   1.058705e+00 |   6.578590e-01 |
|   5.000000e+00 |   1.058794e+00 |   6.579372e-01 |
|   6.000000e+00 |   1.058803e+00 |   6.579451e-01 |
+----------------+----------------+----------------+
```
Time step 1 to 5 are the outputs on the five Picard iterations.

Note that this PR only enables the outputs for the MAIN app on picard iterations. If we want the similar outputs for multiapps, we possibly will need to do it in `FullSolveMultiApp` and `TransientMultiApp`. I doubt that will be a much needed features.

### CODE REVIEW

**Comment by friedmud** [comment]
This should be done by adding a new execute_on and then specifying one of the outputs in the outputs block to execute on that execute_on

**Review by friedmud — CHANGES_REQUESTED** [review]
This should be done by adding a new execute_on and then specifying one of the outputs in the outputs block to execute on that execute_on

**Comment by YaqiWang** [comment]
Yes. We need to. I will add that execute_on flag when civet is back. It will take more time but I agree we should not delay it anymore.

**Comment by YaqiWang** [comment]
I am aware of this. But this needs a significant redesign (I probably can do but having other tasks) to address @friedmud 's comment if this temporary walkaround is not accepted.

**Pull request closed without merging**
