### PR TITLE
Prevent infinite loop in multiapp.

### LINKED ISSUE #24371: Infinite loop if accidentally pass main app file name to MultiApp
## Reason
I discovered what I think is an infinite loop (hangs indefinitely) if you accidentally put the main app's file as a sub-app, like

```
[MultiApps]
  [nek]
    type = TransientMultiApp
    input_files = 'main.i'
  []
[]
```

inside of `main.i` itself. The program just hangs.

## Design
Ideally, this would error to the user. 

## Impact
Better user experience.

### PR DESCRIPTION
**Pull request by aprilnovak**
Closes #24371

### CODE REVIEW

**Review by GiudGiud — CHANGES_REQUESTED** [review]
Good idea but I use that a lot to make multiapp tests with a single input

you just need to pass a cli_args to the multiapps: cli_args = "MultiApps/active=''"

You would need to check for those cli_args being passed

**Comment by aprilnovak** [comment]
> You would need to check for those cli_args being passed

Good catch, I was not aware of that use case. Is it just cli_args I need to check? Couldn't the user also have the block disabled in the input itself? I'm not sure how to access the "active" attribute, it's not obvious to me on the `MultiApp` doxygen.

**Comment by GiudGiud** [comment]
I think if the input is running itself as a multiapp, then it must be that the multiapps is active.

Another similar one could be turning on/off apps through controls. In main app, active, in sub app, inactive, would prevent an infinite loop. This seems unlikely

I cant find of another likely one (aside from the one I mentioned earlier) though

**Comment by aprilnovak** [comment]
> I think if the input is running itself as a multiapp, then it must be that the multiapps is active.

I guess I don't understand then what you'd like to see changed with this PR? Yes, in theory the user could avoid this with the `active` functionality, but my point is that the user forgets to do that and enters this infinite loop.

**Comment by GiudGiud** [comment]
If you look at the tests that are failing, I m guessing they are those that use the cli_args to turn off a MultiApps block

**Comment by aprilnovak** [comment]
I am not sure on how to proceed - I can search `cliArgs()` for `MultiApps/active=''`, but that seems brittle and not going to catch things like `inactive='sub'` or other equivalent ways to enact the same change. Do you have a suggestion?

**Comment by GiudGiud** [comment]
Look for MultiApps/active and MultiApps/inactive.
If they are there in the cli_args, then do not trigger your error. 

Sure it s not foolproof but it will catch 99% for sure

**Comment by GiudGiud** [comment]
actually

**Pull request closed without merging**
