### PR TITLE
ElementKernel - proof of principle

### PR DESCRIPTION
**Pull request by YaqiWang**
For #9014. DO NOT MERGE.

### CODE REVIEW

**Comment by andrsd** [comment]
Now, let's see the timings...

**Comment by dschwen** [comment]
No timings yet, 👎  from @friedmud, doe we need to keep this open?

**Comment by YaqiWang** [comment]
If any of moose members knows what I am doing here, the purpose of this PR is conveyed and this PR can be closed.

**Comment by permcody** [comment]
We understand what this is doing. I propose we close this but @YaqiWang - keep this branch around. Perhaps we'll discuss this at Tiger team.

**Pull request closed without merging**
