### PR TITLE
Fix dt old usage and predictor mutation in AB2PredictorCorrector

### LINKED ISSUE #7890: AB2PredictorCorrector doesn't actually use dt_old when it should
It actually uses two values _fe_problem.dtOld() and _dt which are always both set to the current dt (same value) at the time estimateTimeError is called.

Also, the error calculation mutates the FEProblem predictor solution state - resulting in it holding the wrong value for later viewers.

### PR DESCRIPTION
**Pull request by rwcarlsen**
Previously, the AB2PredictorCorrector always had/used the same value for
dt and dt_old in its time error calculations rather than the actual
current and previous dt values.  This fixes that - resulting in a
new/different output file for one test - which has been updated here.

The AB2PredictorCorrector also, as a side-effect of error estimation,
mutated the canonical, FEProblem-global Predictor solution - rendering
it impossible for later viewers to see/use the original correct value.
This fixes that by forcing AB2 to copy the predicor solution instead of
capturing it by reference.

Fixes #7890.

### CODE REVIEW

**Comment by permcody** [comment]
Ping @bwspenc

**Comment by friedmud** [comment]
This seems good to me as long as @bwspenc doesn't spot anything.

**Comment by rwcarlsen** [comment]
Can we hold on this for just a second.  I have one more tweak to add

**Comment by rwcarlsen** [comment]
Tweak added.

**Comment by bwspenc** [comment]
This looks good to me, although I actually wasn't involved in writing this code at all. I worked on the predictor that uses an extrapolation from the previous solutions for an initial guess for the nonlinear solution.

**Review by jwpeterson — APPROVED** [review]
I'm surprised no apps broke... guess none are using this predictor?

**Comment by andrsd** [comment]
This stuff was done by John Hutchins during his internship a few years ago and AFAIK it has not been used by anyone else but `moose_test`.

**Pull request merged**
