### PR TITLE
Handles block/boundary restriction of DiscreteMaterial

### LINKED ISSUE #6533: DiscreteMaterial Discussion
### Description of the enhancement or error report
The new `DiscreteMaterial` System has generated a lot of discussion... I would like to capture that _here_ so we can decide if there are any actionable issues...

### PR DESCRIPTION
**Pull request by aeslaughter**
- Generalizes the Newton iteration test objects just to make it easier to add more of these objects, if needed.
- Adds a check for MOOSE to error if a property is declared on the same block by multiple material objects.  As far as I can tell we never had this check before.
- This adds block/boundary restriction to DiscreteMaterial and checks that they are consistent with the calling object.

(closes #6533)

### CODE REVIEW

**Comment by friedmud** [comment]
Definitely good fixes... thanks for taking the feedback and improving the system!

**Comment by aeslaughter** [comment]
@dschwen 

I am trying to add an error if a material property is declared by two different materials on the same block, I am getting this:

```
phase_field:MultiPhase.orderparameterfunctionmaterial: *** ERROR ***
phase_field:MultiPhase.orderparameterfunctionmaterial: The following material properties are declared on block 0 by multiple materials:
phase_field:MultiPhase.orderparameterfunctionmaterial: h
```

**Comment by aeslaughter** [comment]
@friedmud No problem, glad I did. We currently can have ambiguous declaration and computation of material properties.

**Comment by dschwen** [comment]
Hmmm, @aeslaughter, this might be related to the derivative material stuff and the way default material properties are created. Let's talk tomorrow.

**Comment by aeslaughter** [comment]
@idaholab/moose-developers My latest commit makes the material declare conflicts a warning, I vote we get this in first. I will then work on updating the apps to be complaint, then convert to an error.

**Comment by aeslaughter** [comment]
@dschwen Why not?

**Comment by dschwen** [comment]
The redeclaration can be done by arbitrary materials! We may need an additional list here to skip the dependency check for zero material properties. Let me come over real quick.

**Comment by dschwen** [comment]
@aeslaughter I have confirmed that rebasing this PR on #6567 gets rid of the double declaration error in `phase_field:MultiPhase.orderparameterfunctionmaterial`.

**Comment by aeslaughter** [comment]
This is failing on heavy tests, which have been failing for awhile now. It is not related to this PR.

**Comment by aeslaughter** [comment]
@dschwen Are you ok with merging this warning message now?

**Comment by dschwen** [comment]
Yes

**Comment by permcody** [comment]
:+1: 

Closes #2253 as well.

**Pull request merged**
