### PR TITLE
Libmesh submodule update

### LINKED ISSUE #22549: Incompatibility with PETSc 3.18
## Reason
PetscDMMoose.C isn't compatible with a few API changes in PETSc 3.18; compilation of MOOSE against that version of PETSc fails.

## Design
We can use some libMesh macros to handle a few of the warning-triggering API changes, another `PETSC_VERSION_LESS_THAN` macros to add a new case for one of the error-triggering changes, and switch a few member accesses from `->type` to `->type_name`.

## Impact
This should all be invisible to users and other developers.  It's going to be moot until the next libMesh submodule upgrade, though, as the libMesh compatibility with PETSc 3.18 hasn't reached MOOSE yet either.

### PR DESCRIPTION
**Pull request by roystgnr**
* Made output with `ExodusII::write_added_sides()` and discontinuous
  interior variables partitioning-independent, by averaging
  discontinuous values on shared added sides.
* Beginning (Lagrange Finite Element, no mesh refinement) support for
  Prism20 and Prism21 geometric elements
* Fixes for QTRAP and QGRID quadrature on pyramids
* Fixes for various NumericVector subclass misbehaviors leading to
  assertion failures
* Expansions in line, function, and feature coverage for the libMesh
  internal test suite.
* Add compatibility with PETSc 3.18
* Fix for linking to VTK 9.2
* Fixes for errors with Nvidia HPC SDK compilers

This closes #22549 and is needed to get #22324 finally running cleanly.

### CODE REVIEW

**Comment by roystgnr** [comment]
Shoot - I remembered to link the PETSc 3.18 issue, but forgot to mention that in the newsletter notes.  I'll fix and force-push.

**Comment by roystgnr** [comment]
> The following file(s) are unchanged:

> conda/mpich/conda_build_config.yaml

What's this coming from? I thought the required changes here moved to the conda_build_config.yaml conda/moose/ and conda/template/ ... and I thought the move *predated* our October update, which didn't generate these messages.

**Comment by loganharbour** [comment]
Added the additional tests. Does this not include the petsc compatibility changes?

**Comment by roystgnr** [comment]
> Does this not include the petsc compatibility changes?

It includes them.  I force-pushed an update to the newsletter edits and git comment; didn't update the comment above is all.

**Comment by loganharbour** [comment]
@roystgnr - we're gonna pull https://github.com/idaholab/moose/pull/22521 into this as well. otherwise, looks good to me

**Comment by roystgnr** [comment]
>we're gonna pull https://github.com/idaholab/moose/pull/22521 into this as well

Works for me.  Need any help from my end?

**Comment by loganharbour** [comment]
> > we're gonna pull #22521 into this as well
> 
> Works for me. Need any help from my end?

I'll defer to @cticenhour as to how he wants to do that

**Comment by cticenhour** [comment]
@roystgnr I am happy to push directly to this branch if you don't have anything else that needs to be added?

**Comment by roystgnr** [comment]
Nothing else needs to be added.  If anything somehow blocks a merge for days then I'd be tempted to slip in another upcoming libMesh PR or 3 first, but fingers crossed that won't happen; the hash I've upgraded to should be good to go.

**Comment by loganharbour** [comment]
@cticenhour can you please rebase this on devel, and then also push a branch to idaholab? I'd like to do this so that I can start building the build farm packages

**Comment by cticenhour** [comment]
Will do!

**Review by loganharbour — CHANGES_REQUESTED** [review]
Waiting for the build box spack packages to build; good after that

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
