### PR TITLE
Fix error message conditions in XYDelaunayGenerator

### LINKED ISSUE #24538: Bad error testing in XYDelaunayGenerator
## Bug Description

@shikhar413 reported not seeing the expected error when he had holes marked for stitching but not for refinement.  I ran across an unexpected (and incorrect) error when I was bisecting #24474

## Steps to Reproduce

For the missing error: create an input file where XYDelaunayGenerator is given `true` values in a `stitch_holes` vector but given no `refine_holes` vector at all.

For the overzealous error: create a `stitch_holes` vector, but leave one entry `false` and mark the corresponding `refine_holes` entry as `true`

## Impact
The overzealous error prevents correct input files from executing; the missing error can cause incorrect input files to silently create torn meshes.

### PR DESCRIPTION
**Pull request by roystgnr**
## Reason
@shikhar413 reported not seeing the expected error when he had holes marked for stitching but not for refinement.  I ran across an unexpected (and incorrect) error when I was bisecting #24474

## Design
Correct the logic in the if statement preceding paramError()

## Impact
No change to existing APIs, except that input files which could have silently and incorrectly generated non-conforming slit meshes will now exit with an error before trying.

Closes #24538

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Sockeye failure is related. 
@roystgnr do you have access? I could patch

**Comment by roystgnr** [comment]
>  @roystgnr do you have access? I could patch, I think it s an easy one

Would you?  In theory I've got access; in practice I don't have a checkout yet.

**Comment by GiudGiud** [comment]
ok on it

**Comment by GiudGiud** [comment]
Created https://github.inl.gov/ncrc/sockeye/pull/687
@joshuahansel for your consideration

**Pull request merged**
