### PR TITLE
Revert "Make sure weighted gaps are parallel consistent"

### PR DESCRIPTION
**Pull request by lindsayad**
Reverts idaholab/moose#19246

I don't understand what's causing the valgrind errors at https://civet.inl.gov/job/880361/ yet and it might be a little while until I do. valgrind stack traces are like the following
```
==1115445== 1,360 bytes in 34 blocks are definitely lost in loss record 5 of 40
==1115445==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1115445==    by 0xBCD2B06: PMPI_Type_create_resized (in /usr/lib/x86_64-linux-gnu/libmpich.so.12.1.8)
==1115445==    by 0x499C784: TIMPI::StandardType<MetaPhysicL::DynamicStdArrayWrapper<double, MetaPhysicL::NWrapper<300ul> >, void>::StandardType(MetaPhysicL::DynamicStdArrayWrapper<double, MetaPhysicL::NWrapper<300ul> > const*) (parallel_dynamic_std_array_wrapper.h:72)
==1115445==    by 0x499E866: TIMPI::StandardType<MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, void>::StandardType(MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> > const*) (parallel_semidynamicsparsenumberarray.h:53)
==1115445==    by 0x499F5E4: TIMPI::StandardType<MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true>, void>::StandardType(MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true> const*) (parallel_dualnumber.h:68)
==1115445==    by 0x49A1110: void TIMPI::BuildStandardTypeVector<2ul>::build<unsigned long, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true>, double>(std::vector<std::unique_ptr<TIMPI::DataType, std::default_delete<TIMPI::DataType> >, std::allocator<std::unique_ptr<TIMPI::DataType, std::default_delete<TIMPI::DataType> > > >&, std::tuple<unsigned long, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true>, double> const&) (standard_type.h:389)
==1115445==    by 0x49A1BB7: TIMPI::StandardType<std::tuple<unsigned long, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true>, double>, void>::StandardType(std::tuple<unsigned long, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<300ul> >, true>, double> const*) (standard_type.h:465)
==1115445==    by 0x49638FE: build_standard_type<std::tuple<long unsigned int, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, long unsigned int, MetaPhysicL::NWrapper<300> >, true>, double> > (standard_type.h:114)
==1115445==    by 0x49638FE: push_parallel_vector_data<std::unordered_map<unsigned int, std::vector<std::tuple<long unsigned int, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, long unsigned int, MetaPhysicL::NWrapper<300> >, true>, double> > >&, ComputeWeightedGapLMMechanicalContact::communicateGaps()::<lambda(libMesh::processor_id_type, const std::vector<std::tuple<long unsigned int, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, long unsigned int, MetaPhysicL::NWrapper<300> >, true>, double> >&)> > (parallel_sync.h:383)
==1115445==    by 0x49638FE: ComputeWeightedGapLMMechanicalContact::communicateGaps() (ComputeWeightedGapLMMechanicalContact.C:209)
==1115445==    by 0x4964E16: ComputeFrictionalForceLMMechanicalContact::incorrectEdgeDroppingPost(std::unordered_set<libMesh::Node const*, std::hash<libMesh::Node const*>, std::equal_to<libMesh::Node const*>, std::allocator<libMesh::Node const*> > const&) (ComputeFrictionalForceLMMechanicalContact.C:179)
==1115445==    by 0x677A5C6: ComputeMortarFunctor::operator()() (ComputeMortarFunctor.C:259)
==1115445==    by 0x60BE808: NonlinearSystemBase::mortarConstraints() (NonlinearSystemBase.C:3339)
==1115445==    by 0x60ECF79: NonlinearSystemBase::computeJacobianInternal(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) (NonlinearSystemBase.C:2415)
```
I see calls to `free()` for every new `StandardType` I implemented so I don't really know what's going on here. @roystgnr do you have any ideas?

### CODE REVIEW

**Review by loganharbour — CHANGES_REQUESTED** [review]
You need to cherry pick out the conda changes. We can't go back in build number. Keep the conda changes there.

Just remove edits to:
- `conda/libmesh/build.sh`
- `conda/libmesh/meta.yml`
- `conda/mpich/conda_build_config.yaml`

**Comment by roystgnr** [comment]
These are the new StandardType specializations in https://github.com/libMesh/MetaPhysicL/pull/1 being leaked?  I'll take a look.

**Comment by lindsayad** [comment]
> These are the new StandardType specializations in [libMesh/MetaPhysicL#1](https://github.com/libMesh/MetaPhysicL/pull/1) being leaked? I'll take a look.

Yes

**Review by loganharbour — APPROVED** [review]
In the event that you can't fix in a reasonable time and need to merge

**Comment by roystgnr** [comment]
I don't see any obvious errors there ... and I can't reproduce them, either - a MetaPhysicL `--with-timpi=$FOO` build still passes `METAPHYSICL_RUN='mpirun -np 4 valgrind' make check` for me, and I'm not seeing anything suspicious in `run_unit_tests.sh.log` afterward either.

**Comment by lindsayad** [comment]
Yea I just added some push tests to metaphysicl unit testing and valgrind is still giving me nothing :frowning_face:

**Comment by lindsayad** [comment]
Should I just merge this? I don't know what's going on with docker here. I don't see it failing anywhere else

**Comment by lindsayad** [comment]
We will need to make changes down in TIMPI and then propagate them up so reverting is the right thing to do here in the short term

**Pull request merged**
