### PR TITLE
add initialSetup for ComputeIsotropicElasticityTensor

### LINKED ISSUE #15941: isotropic elasticity tensor not initialized
## Bug Description

The ComputeIsotropicElasticityTensors lacks an initialSetup() so computations at EXEC_INITIAL that depend on it get wrong results.

## Steps to Reproduce

Output effective stiffness at EXEC_INITIAL

## Impact

Bug.

### PR DESCRIPTION
**Pull request by hugary1995**
closes #15941

### CODE REVIEW

**Comment by hugary1995** [comment]
@aeslaughter Hi Andrew, I saw some of your discussions in #15481. I have a similar use case as @amjokisaari has mentioned there and I wonder if we could simply set this up at initial?

**Comment by aeslaughter** [comment]
Can you be more specific what you are interested in from the discussions mentioned? How does this fix help?

**Comment by hugary1995** [comment]
The elasticity tensor and effective stiffness calculations used to be in the constructor. Now that they have been moved to residualSetup, their values become uninitialized (or zero-initialized) before any residual calculations. There are calculations that we need to perform before the residualSetup.

For example, the very reason of the effective stiffness calculations are for CFL condition estimates in elastodynamics. We need the CFL condition to estimate the timestep size. There is now no way to calculate the timestep size at EXEC_INITIAL because residualSetup hasn't happened yet.

There are many other calculations we need to do before any residualSetup, e.g. we may want to rotate the elasticity tensor at initialSetup, we may need to initialize an internal state variable based on the elasticity tensor, etc.

There are also calculations we need to do even we have "solve = false". But now we cannot.

**Review by dschwen — APPROVED** [review]
Yes, this is the right thing to do.

**Comment by dschwen** [comment]
@zachmprince , there might be more changes in your controllable params PR that have this issue.

**Pull request merged**
