### PR TITLE
Testing use of LFS for media documentation media directory

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #6699)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@idaholab/moose-team I think we should consider using LFS for all media files. It is very transparent, once it is setup the workflow is the same.

**Comment by friedmud** [comment]
I think it's overkill for PNGs...

Also: can people on the Proxy get to it?

**Comment by aeslaughter** [comment]
What about movies and/or slideshows of dozens of pngs. For reference, the
moose workshop has 22MB in the pics directory.

**Comment by friedmud** [comment]
22 MB isn't a huge deal - but it is headed in the direction where splitting
it out could be beneficial.

I do agree about movies though... I guess that now that our entire website
is in the git repo we're going to have to think more about this...

**Comment by jwpeterson** [comment]
This is pretty slick, and it does work behind the proxy. There are no special commands unless you actually want to pull down the full files (they are represented by small placeholder files otherwise).  The workflow is:
```
(put file.png in docs/media)
git add docs/media/file.png
git commit -am"Adding file."
git push
```
At this point, you see "Git LFS: (1/1 files...)" at the prompt, which shows the big files being pushed to a different server.

When another user later pulls/fetches, they get small placeholder files until they actually run "git lfs pull" at which point the large files are pulled down.

I had a couple of strange errors when I initially tried to pull @aeslaughter's branch but ended up fixing them by simply running "git lfs uninstall" and "git lfs install" again... not sure what the problem was there.  Anyway, I think this may be a reasonable approach to take.

**Pull request closed without merging**
