### PR TITLE
Reorganize examples and tutorials page

### PR DESCRIPTION
**Pull request by cticenhour**
@bwspenc @friedmud I made a few more adjustments to the examples and tutorials page based on prior discussion to make it flow a little better and look more uniform to me. Let me know what you think! 

Refs #22923

### CODE REVIEW

**Comment by friedmud** [comment]
Overall - it's good... but I wonder if we're really recommending the best thing up front?  It seems to me that we should move the Workshop (with a big link to the video) to the top.  To me... that's the best entry point.  The Examples don't explain that much... and walking through the text tutorial yourself doesn't do a ton either.

What do you think?

**Comment by cticenhour** [comment]
Yeah, I see your point. We promote the workshop materials for new users generally, so why not put it up front here too? It's the most comprehensive of the bunch on this page.

I'll move that section up and then rather than a big link, I think we should just embed the youtube video of the last workshop (which can be watched or clicked through).

Thanks for the comment!

**Comment by bwspenc** [comment]
I like how this makes things more uniform. I think I agree with Derek that the workshop videos should be at the top. 

I have to admit that I don't really like those things that expand out the page. They feel kind of gimmicky and require extra clicking to get to what you want. Also, I would think that they should all behave in a similar way, but the various pages that they link to have different formatting. My preference would be to just have everything be a bulleted list of links (like the Framework Examples section).

**Comment by cticenhour** [comment]
@bwspenc I personally like the little dropdown expansions! 😄 I think they keep things from being quite as much of a wall of text, especially with modules whose listings have a bit more content on this page like Porous Flow. 

I'll try out using more traditional subsections and leverage the include functionality a bit more and see how that looks. Thanks!

**Comment by bwspenc** [comment]
Those dropdown expansions just embed the landing page for the individual modules in the main page. It seems to me like if you're interested in a specific module, you'd probably want to go to that landing page and navigate around from there, rather than going back to the main MOOSE tutorials page. There's no obvious way to get to that landing page from this main page when it's just embedded in the dropdown expansion.

**Comment by cticenhour** [comment]
Are you suggesting that we just provide direct links to each module landing page and not these listings? 

The only embedding / includes being done here (whether we're talking subsections or dropdowns) are for markdown pages that already held otherwise unformatted listings of examples. They are only being re-used (except for the small re-org in combined you see in the changeset). Once a user clicks on any of these links, the secondary navigation ribbon allows them to proceed on to the module landing page if they want more from that module only.

**Comment by bwspenc** [comment]
That navigation ribbon doesn't actually provide a link to that module landing page. Maybe if you have a minute, we should just discuss this.

**Comment by cticenhour** [comment]
By "module landing page", I am referring to the module home page (i.e., as in https://mooseframework.inl.gov/modules/geochemistry/), which I thought is what you were referring to. I just sent a meeting invite to your inbox for tomorrow morning.

**Comment by cticenhour** [comment]
@bwspenc I think I addressed your concerns from our discussion before the holiday. Please take a look when you have the chance. Thanks!

**Comment by cticenhour** [comment]
@bwspenc pinging you as a reminder for a review - any more thoughts on this?

**Comment by friedmud** [comment]
This looks good to me :+1:.  Thanks for working on this.

**Review by friedmud — APPROVED** [review]
Looks good!

**Comment by loganharbour** [comment]
FYI these tests were ran more than three weeks ago.

**Pull request merged**
