### PR TITLE
Rework Peacock visualization tab

### LINKED ISSUE #4907: Peacock UI has too much whitespace
Peacock is pretty much unusable on small displays due to the large UI margins and whitespace. The minimum window height is > 900px.

### PR DESCRIPTION
**Pull request by dschwen**
This makes peacock usable on smaller screens, simplifies the layout hierarchy, improves the widget scaling, uses double spinner boxes where appropriate, adds a "White background" option, and adds a draggable splitter between render view and options (this allows the user to collapse the options completely).

Screenshot shows the widget scaling by dragging the options wide.

peacock_scale

Adresses #4907.

### CODE REVIEW

**Comment by permcody** [comment]
@friedmud - do you have any comments on this before we merge?

**Comment by friedmud** [comment]
I'll try it out.

**Comment by dschwen** [comment]
Ugh, I screwed something up. Hold on. The radio buttons for the contour limits are impropperly grouped.

**Comment by friedmud** [comment]
Everything looks good: other than the new tab bar.  I hate it.  Ugly as sin. ;-)

Let's keep the old tab bar.

Everything else looks great!

**Comment by dschwen** [comment]
Haha, I knew you'd not like that. Well, I guess tastes differ. It's all the same to me. I'm already working on the followup PR that cleans up the spacing and makes it look better on Linux systems. But I can add a commit to change the tab bar here.

**Comment by friedmud** [comment]
Those tabs look much better... do they actually take up more room?  Looks about the same to me...

Thanks for changing it back!

**Pull request merged**
