### PR TITLE
Add ADComputeVolumetricEigenstrain

### LINKED ISSUE #26880: Make ADComputeVolumetricEigenstrain
## Reason
An AD version of `ComputeVolumetricEigenstrain` would be helpful for accumulating volumetric strains and applying them as eigenstrains.

## Design
Make something similar to `ComputeVolumetricEigenstrain` without the `DerivativeMaterialInterface` bits. 

## Impact
Added functionality for eigenstrains.

### PR DESCRIPTION
**Pull request by tophmatthews**
closes #26880

### CODE REVIEW

**Comment by tophmatthews** [comment]
Just as a side note, In the non-AD class, there is a lot of good work to get derivatives and second derivatives of the volumetric strains, and then it goes:

```
TODO: Compute derivatives of the elastic strain wrt the variables specified in args
```
😆

**Comment by tophmatthews** [comment]
Huh, it automatically moved everything from `tensor_mechanics` to `solid_mechanics`, but still required a merge conflict resolution. Anyways, should be good to go still.

**Comment by tophmatthews** [comment]
Can I get some eyes on this @dschwen ?

**Comment by tophmatthews** [comment]
Anybody out there?

**Comment by lynnmunday** [comment]
> Just as a side note, In the non-AD class, there is a lot of good work to get derivatives and second derivatives of the volumetric strains using @dschwen 's `DerivativeMaterialInterface`, and then it goes:
> 
> ```
> TODO: Compute derivatives of the elastic strain wrt the variables specified in args
> ```
> 
> 😆
Can you just delete the unsupported features in the nonAD version and template that class?  If those features are added to the nonAD version, the AD and nonAD classes are going to diverge and do completely different things.

@dschwen what do you think

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
> Can you just delete the unsupported features in the nonAD version and template that class? If those features are added to the nonAD version, the AD and nonAD classes are going to diverge and do completely different things.
> 
> @dschwen what do you think

No, let's not delete this. The classes are already diverged. Adding the derivatives will un-diverge them.

**Comment by tophmatthews** [comment]
Thanks @dschwen !

**Pull request merged**
