### PR TITLE
Brackets in delete_trailing_whitespace.sh

### LINKED ISSUE #5963: delete_trailing_whitespace.sh doesn't work for me

### PR DESCRIPTION
**Pull request by WilkAndy**
This works for me, and i hope it works as intended for other people.

Fixes #5963

### CODE REVIEW

**Comment by permcody** [comment]
Interesting, I think I'll have @jwpeterson or @dschwen look at this too. We've changed the way we invoke find a lot due to differences on OS X and Linux. I want to make sure that this change works for everyone.

**Comment by jwpeterson** [comment]
So, what bug does this fix?  I don't see how adding parentheses changes the logic, but that's probably because I don't understand the find command...

**Comment by dschwen** [comment]
Yeah
```
A or B or C == A or (B or C)
```

**Comment by WilkAndy** [comment]
As i understand it, the brackets are needed because of the print0.  i believe the non-parentheses version is actually

find blahblahblah -o \(-name "*.py"  -type f -print0 /)  |  xargs blahblahblah

which does not actually change any .C files on my system.  Eg, look at:

http://unix.stackexchange.com/questions/49477/got-less-output-with-print0-option-on-find

i could have misunderstood this stuff, but do i know the non-parentheses version doesn't work!

a

**Comment by permcody** [comment]
Well that's not entirely right. The print0 option is just for using an
otherwise unused character to separate the output, i.e. the NULL character.
It must be used with the -0 option to xargs to split properly. The grouping
is independent and I know it gets super complicated when the -prune option
is used. What Linux system are you on? Maybe I'll try a few tests out here
to see if we can replicate. Actually, I'll merge this if it works on our
Macs and Linux box even though it seems unnecessary as long as it doesn't
regress.

**Comment by WilkAndy** [comment]
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 1

Here's 3 examples:

No -print0:
wil04q@cemvmc:/apps/geomodel/moose/projects_andy/moose/modules/richards/src/kernels> find . -path ./contrib -prune -o -path ./libmesh -prune -o -name "*.[Chi]" -o -name "*.py" -type f
./Q2PPorepressureFlux.C
./PoroFullSatTimeDerivative.C
./Q2PSaturationDiffusion.C
./RichardsMassChange.C
./RichardsLumpedMassChange.C
./DarcyFlux.C
./Q2PPorepressureDiffusion.C
./Q2PSaturationFlux.C
./Q2PMassChange.C
./RichardsFullyUpwindFlux.C
./RichardsPPenalty.C
./RichardsFlux.C

With -print0:
wil04q@cemvmc:/apps/geomodel/moose/projects_andy/moose/modules/richards/src/kernels> find . -path ./contrib -prune -o -path ./libmesh -prune -o -name "*.[Chi]" -o -name "*.py" -type f -print0

With -print0 and parenthases:
wil04q@cemvmc:/apps/geomodel/moose/projects_andy/moose/modules/richards/src/kernels> find . -path ./contrib -prune -o -path ./libmesh -prune -o \( -name "*.[Chi]" -o -name "*.py" \) -type f -print0
./Q2PPorepressureFlux.C./PoroFullSatTimeDerivative.C./Q2PSaturationDiffusion.C./RichardsMassChange.C./RichardsLumpedMassChange.C./DarcyFlux.C./Q2PPorepressureDiffusion.C./Q2PSaturationFlux.C./Q2PMassChange.C./RichardsFullyUpwindFlux.C./RichardsPPenalty.C./RichardsFlux.C

**Comment by jwpeterson** [comment]
On OSX, I can confirm this:
```
find . -path ./contrib -prune -o -path ./libmesh -prune -o -name "*.[Chi]" -o -name "*.py" -type f -print0
```
doesn't work on OSX. It prints:
```
./doc/doxygen/create_dox.py./scripts/build_coverage.py./scripts/ensight/ensightDR.py./scripts/find_dep_apps.py./scripts/find_hung_process.py./scripts/fixup_headers.py./scripts/get_repo_revision.py./scripts/LikelyOptimzer.py./scripts/mooseExamplesLateX/gen_tex.py./scripts/replace_snes.py./scripts/rm_outdated_deps.py./scripts/syntaxHTML/generate_input_syntax.py./scripts/syntaxHTML/genInputFileSyntaxHTML.py./scripts/timingHTML/timing_utils.py./scripts/updateStable.py./scripts/updateSyntax.py
```
i.e. a big string of Python file names with no spaces.

On the other hand, the version with parens:
```
find . -path ./contrib -prune -o -path ./libmesh -prune -o \( -name "*.[Chi]" -o -name "*.py" \) -type f -print0
```
does work!

So I'm going to merge this.  Also, I hate `find`.

**Comment by WilkAndy** [comment]
Actually, it's suppose to print a big string of python file names with no spaces:  xargs -0 sees the null chars (which you don't see on the terminal evidently) and does the right thing.  I still think the problem is described in the above link - only the last clause has an action: so it finds but doesn't print any .[Chi] files.

You may hate "find", but i bet you use it all the time :-)

a

**Comment by permcody** [comment]
Andy is right. You won't see the NULL characters on the terminal so he
still may be correct about the underlying issue.

**Pull request merged**
