### PR TITLE
Add exponential porosity-permeability function. Closes #7632

### LINKED ISSUE #7632: Add log k permeability-porosity relationship to porous_flow
### Description of the enhancement or error report
Add material to porous_flow to calculate permeability from porosity based on the relationship log k = A phi + B, where k is permeability, phi is porosity and A and B are empirical constants

### Rationale for the enhancement or information for reproducing the error
This is a widely-used porosity-permeability relationship, providing an alternative to the kozeny-carman relationship

### Identified impact
None, new material added to porous_flow

### PR DESCRIPTION
**Pull request by hsheldon**
Adding material to porous_flow module to implement exponential porosity-permeability relationship, k = k_anisotropic \* B \* exp(A \* phi).

### CODE REVIEW

**Comment by permcody** [comment]
I'm trying to understand the commit history here. It looks like you are merging commits from another branch into this one? I can merge this if it keeps your workflow sane but it's not the cleanest looking history.

**Comment by jwpeterson** [comment]
Yes, this needs to be rebased on devel so that there are not duplicate copies of commits as seen in the history above.  Also the whitespace fixes should be squashed down.  In general, running `git pull` while working on two different computers will cause this nonlinear history, but we prefer not to merge such histories into devel.

**Comment by hsheldon** [comment]
Aha, you have discovered my incompetence with git! Its messy because I was trying to update some commit messages after I had pushed to github. So then I ended up with a 1 ahead, 1 behind situation and had to pull and merge (at least that's what git was telling me to do). I did try squashing but got in a muddle with that too. If someone can talk me through what I need to do to squash these commits into one commit that would be great. Or do it for me, but that's less desirable as I will likely end up in the same mess next time.

**Comment by hsheldon** [comment]
Hooray, I fixed it! All squashed and neat and tidy now.

**Comment by permcody** [comment]
@hsheldon - Much better!
The problem is the command `git pull`. It seems like the right command to use (inverse of `git push`) but honestly it's a command that we advise people to avoid completely. The reason is that the MOOSE project follows the "rebase" philosophy instead of the merge philosophy. Neither is wrong, just a team preference. `git pull` is shorthand for `git fetch; get merge FETCH_HEAD` so it's a non-starter right there. There is a flag where you can request that `git pull` does a rebase instead but if you accidentally leave the flag off, you'll get another merge. So the more you switch back and forth between machines and use that command the more and more merge commits you'll see leading to a "cluttered history".

We recommend that you use `git fetch` explicitly followed by `git rebase [branch name]`. In fact if you use "tracking branches" you don't even need the branch name when using the rebase command. 

Take a look at our recommended workflow if you have questions or feel free to ask:
https://mooseframework.org/static/media/uploads/docs/moose_github.pdf

Thanks!

**Pull request merged**
