### PR TITLE
Update libmesh

### LINKED ISSUE #24931: Compute `sln_diff` on the fly
## Reason
`Transient::relativeSolutionDifferenceNorm()` computes a difference with an unnecessary allocation.

## Design
Compute `sln_diff` in `Transient::relativeSolutionDifferenceNorm()` on the fly.

## Impact
Better memory usage.

### PR DESCRIPTION
**Pull request by loganharbour**
Summary of changes:

- Adds hierarchic (and L2_HIERARCHIC) FE prism support
- Adds in-place L2 norm difference method
- Fixes for MeshedHole
- Makes metis and parmetis IGA-aware
- Gives better diagnostics if users mix DEBUG/NDEBUG flags

Closes https://github.com/idaholab/moose/issues/24931

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr or @lindsayad  what else do you want to get in before we do an update?

**Comment by lindsayad** [comment]
I don't have anything I'm working on right now

**Comment by roystgnr** [comment]
I've got some projector stuff I'm working on, but it's not going well enough to wait on.  I'd say if we've got the HIERARCHIC+PRISM stuff in then we're good for an update.

**Comment by loganharbour** [comment]
Sounds good. I'll merge once the rest pass.

**Review by milljm — APPROVED** [review]
Added channel: https://conda.software.inl.gov/moose/pr-25039, installed `moose-dev`. Looks to pull all the right versions. `mamba update --all` also seems to pull the expected packages.

**Review by roystgnr — APPROVED** [review]

**Comment by loganharbour** [comment]
FYI @YaqiWang - this removes one more vector (the one you brought up a few weeks ago in Transient)

**Pull request merged**
