### PR TITLE
Add SinglePhaseFluidProperties::e_from_p_T()

### PR DESCRIPTION
**Pull request by jwpeterson**
Refs #11133.

### CODE REVIEW

**Comment by andrsd** [comment]
* RELAP failed to build, because the base class defines `e_from_p_T` as pure virtual. We do not have to follow [my suggestion](https://github.com/idaholab/moose/issues/11133#issuecomment-376685777) and patch those apps after this is merged, if you want to.

* We unit test fluid properties in `moose/unit/src`, so you do not need that extra code for `PetscJacobianTester`.  Look at `IdealGasFluidPropertiesTest.C` as a starting point.  For the test of derivative, use the `DERIV_TEST` macro - very handy.

**Comment by jwpeterson** [comment]
> RELAP failed to build, because the base class defines e_from_p_T as pure virtual. We do not have to follow my suggestion and patch those apps after this is merged, if you want to.

I think in order to prevent those apps from being "orange" in CIVET for too long, I will temporarily provide a base class implementation in this PR, then go back and remove it later as you suggested.

> We unit test fluid properties in moose/unit/src, so you do not need that extra code for PetscJacobianTester

So I was just copying what was done in the existing `fluid_properties` tests, e.g.
* test/tests/ideal_gas/e_from_v_h_derivatives.i
* test/tests/stiffened_gas/e_from_v_h_derivatives.i

I find the `PetscJacobianTester` approach to be quite nice, but if you prefer the unit test route, I could add some tests for the new function. Do you think we should have both types of tests going forward, or drop the `PetscJacobianTester` ones?

**Comment by andrsd** [comment]
> Do you think we should have both types of tests going forward, or drop the PetscJacobianTester ones?

Just the unit tests. We forgot to convert those `PetscJacobianTester` ones into unit tests, which I will do today.

**Comment by jwpeterson** [comment]
The internal apps should should remain green with this latest push, I have a RELAP-7 PR ready to go once this is one merged that will update RELAP-7 to the new interface. @andrsd

**Review by andrsd — APPROVED** [review]

**Pull request merged**
