### PR TITLE
additional gap conductance tests #6161

### PR DESCRIPTION
**Pull request by novasr**
### Completed each of the following items before creating a PR
- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

Fixes tests that were failing with intel compiler. refs #6161

### CODE REVIEW

**Comment by permcody** [comment]
@novasr - This looks good but you didn't really say why you did any of these things. It's definitely worth noting why we have an `nl_rel_tol = 1e-22` and why we can't execute the postprocessors on `initial`. Six months from now another developer will stumble on this and ask why there are such screwy parameters here. Can we document (right in the input file) what we learned and why these tests are setup this way? Thanks!

**Comment by novasr** [comment]
nl_rel_tol = 1e-_12_, but yeah. What do you mean by noting this? What do you mean by screwy parameters? We can mention that due to the really high thermal conductivity k * grad_u * normals might not be very close to zero, and therefore shouldn't be run with execute_on = initial. Is that what you want said? I've already mentioned why the thermal conductivity is set to high.

**Comment by permcody** [comment]
Oops yes, your value for rel_tol. Yes, that's exactly what I'd like to note here. It's not something we thought about right away and so it's worth writing down. We'd expect the gradient term to be zero, and it is to machine precision but not after we multiply it by a really high coefficient. That's all I'm looking for.

You said you already mentioned why the coefficient was high. I just looked at the input file and didn't see that, but if it's there, great!

**Comment by novasr** [comment]
I added a little write-up to each of the input files. Tell me what you think.

**Comment by permcody** [comment]
:+1:

**Pull request merged**
