### PR TITLE
Adding doco to common MOOSE kernels

### PR DESCRIPTION
**Pull request by permcody**
refs #6636

### CODE REVIEW

**Comment by friedmud** [comment]
:+1:

But if we're going to be doing documentation of basic objects... I would LOVE, LOVE, LOVE to see us finally fill out `InputParams.description()` so we can feed a tooltip description of the objects to Peacock (and it can be in `dump`, etc.).

**Comment by permcody** [comment]
Oh good point! Thanks for the reminder.

**Comment by permcody** [comment]
@aeslaughter - Any chance we can render LaTeX in the tool tip? It might be cool to have descriptions actually contain the mathematical forms.

**Comment by friedmud** [comment]
It's gotta be possible.  Once upon a time my plan was to render using an HTML box in the tooltip and use Mathjax....

**Comment by dschwen** [comment]
What is `InputParams.description()`? Is that like `addClassDescription()`?

**Comment by friedmud** [comment]
@dschwen Yeah - that one

**Comment by aeslaughter** [comment]
I think we might be able to make a tooltip with latex by using matplotlib. When the mouse hovers it would open a small widget with a matplotlib text box, that could could contain latex. Doing this with pure Qt seems more difficult. I will see if I can mock something up quickly.

**Pull request merged**
