### PR TITLE
Fix boundary id offset code with distributed meshes

### LINKED ISSUE #24068: `RenameBoundaryGenerator` fails for a distributed mesh problem
## Bug Description
Using `RenameBoundaryGenerator` in combination with `GeneratedMeshGenerator` when a nonzero `boundary_id_offset` is used, in a distributed mesh, results in a boundary-does-not-exist error (see below).

## Steps to Reproduce
Run the attached input file with 2 processors and `--distributed-mesh`: 
[rename_boundary_failure.txt](https://github.com/idaholab/moose/files/11233477/rename_boundary_failure.txt)
and observe the error
```
The following boundaries were requested to be renamed, but do not exist: left right bottom top 
```

## Impact
This prevents some users from using mesh generators if they need a distributed mesh.

### PR DESCRIPTION
**Pull request by roystgnr**
## Reason
This fixes renaming on distributed mesh cases where some processors
don't have any semilocal elements on some boundary.

This closes #24068 for me.

## Design
Get global boundary ids when we need them instead of just the local set.

## Impact
I have to have seen all those `mesh_mode = 'REPLICATED'` test annotations at some point, and still never bothered finding the one-line fix preemptively, so I can't say the shame here doesn't hurt.

To other developers and users, no negative impact.

### CODE REVIEW

**Comment by roystgnr** [comment]
Hmm... this fix is sufficient for me for all those tests on a handful of processors, and for some of those tests on a lot of processors, but not yet for all of those tests on a lot of processors.  I'll take a crack at the remaining failures after lunch.

**Comment by roystgnr** [comment]
And after a "make clean" and rebuild I'm seeing no remaining failures.  I may have had object files lying around from an earlier libMesh (or an earlier PETSc; I did the update to 3.19 yesterday).  Unless CI sees a problem I don't, this should be good to merge.

**Review by GiudGiud — APPROVED** [review]

**Comment by joshuahansel** [comment]
@roystgnr Thanks for looking into this! That's great that you're able remove some `mesh_mode` restrictions. Who knows how many other tests inherited that restriction because they use `GeneratedMeshGenerator`...

**Comment by roystgnr** [comment]
> Who knows how many other tests inherited that restriction because they use `GeneratedMeshGenerator`...

I didn't even think to look.  Do I have to experience painful shame *every* time I neglect something, or can I just open up a tab and settle up once a year?

Too behind on other things to go through all the (grep says 506?!) framework+modules tests right now, but at first glance I'm seeing a *lot* of tests with no obvious reason they should be restricted.

I wonder if we're going about this the wrong way, when we disable testing of a feature combination by just never running the affected test with that feature.  We should run the affected test with that feature, and assert that we get an appropriate error message.  Then when someone enables more compatibility and removes the error we automatically find out which tests we can add to help cover the newly enabled cases, and when someone accidentally tries to use an incompatible combination they automatically find out what's wrong.

**Comment by joshuahansel** [comment]
> Too behind on other things to go through all the (grep says 506?!) replicated-only framework+modules tests right now, but at first glance I'm seeing a lot of tests with no obvious reason they should be restricted.

Yeah, not worth your time. We need to periodically run all tests and give some kind of `--force-run` to ignore the restrictions, and have it tell us which tests are restricted but don't need to be :)

> I wonder if we're going about this the wrong way, when we disable testing of a feature combination by just never running the affected test with that feature. We should run the affected test with that feature, and assert that we get an appropriate error message. Then when someone enables more compatibility and removes the error we automatically find out which tests we can add to help cover the newly enabled cases, and when someone accidentally tries to use an incompatible combination they automatically find out what's wrong.

Interesting idea. Do you mean 50+ tests that have something like `distributed_mesh_error = 'The boundary could not be found'`? Or just a single test that checks for that error? The former seems like it could get ugly, and some might be diffs instead of errors.

**Comment by roystgnr** [comment]
> Do you mean 50+ tests that have something like `distributed_mesh_error = 'The boundary could not be found'`? 

I'd take all the tests with `parallel_type = replicated` in `foo/bar.i` and turn them into `mesh_mode = REPLICATED` in `foo/tests`, but then I'd start interpreting `mesh_mode = REPLICATED` as something like `expect_err = 'requires replicated'` when running with `--distributed-mesh`.

**Pull request merged**
