### PR TITLE
Skip Reporter types in `JSONDiff` by default

### LINKED ISSUE #23979: Skip reporter types in `JSONDiff` by default
## Reason
Reporter types are a bit fluid, and we're getting diffs quite often with `Reporters/*/values/*/type` in`JSONDiff`. We don't want to diff these in most cases.

## Design
Skip the values in `Reporters/*/values/*/type` by default, but make it an option so that we can still diff type in cases when desired (like the explicit reporter types).

## Impact
Removes some testing, but adds significant convenience.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes https://github.com/idaholab/moose/issues/23979

Ping @zachmprince and @grmnptr; with these changes, I would really like for us to in this PR set this parameter (`JSONDiff/keep_reporter_types`) to true for the tests that we can that test _just_ a reporter object. I've only done this for the framework so far

### CODE REVIEW

**Comment by loganharbour** [comment]
@socratesgorilla seeking your opinion

**Comment by socratesgorilla** [comment]
> @socratesgorilla seeking your opinion

Is this fixing that thing Casey brought up where the diffs are appearing because of weird compiler differences? Or is this a separate issue?

**Review by socratesgorilla — APPROVED** [review]

**Review by zachmprince — APPROVED** [review]

**Review by lindsayad — COMMENTED** [review]
are types only ever output in reporter contexts? E.g. could this problem show up elsewhere?

**Comment by loganharbour** [comment]
> are types only ever output in reporter contexts? E.g. could this problem show up elsewhere?

Not at the moment. The type is only ever inserted with `Reporter::store(nlohmann::json &)`, which is currently only called by `JSONOutput`

**Review by lindsayad — APPROVED** [review]
I think making the default more robust across architectures and configurations is a fantastic idea

**Pull request merged**
