### PR TITLE
set initial conditions and aux kernel values consistently

### PR DESCRIPTION
**Pull request by rwcarlsen**
… for nodes in multiple subdomains.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Choosing which subdomain is kind of arbitrary though. I suggest to do this kind of thing on the application side. If multiple objects are setting the same dof, we can do weighted average, with the weighting as the angle contribution in 2pi in 2D and solid angle contribution in 4pi in 3D. But that is very complicated. I am even not sure if libMesh supports the evaluation of the angles.

**Comment by rwcarlsen** [comment]
@YaqiWang - the purpose of this is to make MOOSE's behavior consistent.  Right now, the value randomly jumps up and down along interfaces between subdomains.  And the jumping up/down is also different depending on your partitioning/#procs.  The purpose of this is to stabilize that behavior.

**Comment by YaqiWang** [comment]
Do you have multiple ICs? Otherwise, the behavior should be fixed, unless you are doing some unusual operations in `value` function (i.e. not just using the coordinate of the nodes). If there are multiple ICs, I'd suggest to add a parameter `excluding_subdomains`, which can be called in `setCZeroVertices` to avoid setting values multiple times. I did not check your changes though, just my thinking. We had a similar situation in Rattlesnake (setting node values based on values on connected subdomains) and have to have some codes in the IC with `if (_current_node)` check.

**Comment by rwcarlsen** [comment]
@YaqiWang - I'm not sure exactly everything you are trying to say, but this is for cases where block restriction causes more than one IC object to compete for setting a node's value on the interface between two or more subdomains.  Your suggestion by itself would not work because then we would not have a complete set of dof values for the current element before moving on to computing values for the next element - due to objects from multiple subdomains being needed to compute the values for an element on the current subdomain.  This PR has to work around this and other constraints (due to variable+object interdependencies among other things).  Again - the primary purpose here is to make the values along block interfaces be consistent for any number of MPI procs.

**Comment by YaqiWang** [comment]
I am sorry. You are right, my suggestion is not accurate. `MooseMesh` has a function `nodeToElemMap()` which can get the connected elements of a node (hopefully that function is reliable in all cases), you can check if the subdomain of currently element is the smallest of all elements to call `value()` function for doing the setting. But calling that function could be a little expensive in term of memory usage (it creates a map).

**Comment by rwcarlsen** [comment]
No need for you to independently discover everything I did to write this PR - if you look at the code, you can see everything being done here - this *does* use the node-element map.

**Comment by YaqiWang** [comment]
Well, it costs me a little. I have thought of this before. Either way works ok. But I do want to remind you that this is not the ultimate fix. I would add some documentation carefully for this behavior.

**Review by permcody — APPROVED** [review]
Looks like a reasonable "improvement" to me.

**Comment by permcody** [comment]
@mangerij - This PR will cause a diff in Ferret. What this PR does is give us a the ability to set a consistent IC whenever you have block-restricted variables. Currently, anytime you have block restriction you might get inconsistent values on the nodes where two or more subdomains butt up against one and other. Please take a look at your existing test after this gets merged. You'll likely need to re-gold because your IC will be different (improved).

**Pull request merged**
