### PR TITLE
Add algebraic ranges (#27135)

### LINKED ISSUE #27135: Compute Jacobian/Residual on a subset of the entire mesh.
### Motivation

For hyper reduced ROM, a subset of jacobian and residual entries need to be computed but the rest are not needed. Need the ability to tell MOOSE to only compute the J/R on those elements and nodes. This includes not computing material properties on these elements either.

### Design

Possible ways: 
1) Mesh Divisions system and block restricting the kernels. 
2) Add ability directly into MooseMesh
For example:
``` 
void
MooseMesh::setActiveLocalElementRange(ConstElemRange * range)
{
  if (!range)
    _active_local_elem_range = nullptr;
  else
    _active_local_elem_range = std::make_unique<ConstElemRange>(*range);
}
void
MooseMesh::setLocalNodeRange(ConstNodeRange * range)
{
  if (!range)
    _local_node_range = nullptr;
  else
    _local_node_range = std::make_unique<ConstNodeRange>(*range);
}
```

### Impact

Increases the speed up of ROM. Using the MooseMesh example, the speed-up of my ROM solve(ignoring mesh generation and outputting) went from 10 -> 670.

### PR DESCRIPTION
**Pull request by maxnezdyur**
closes  #27135

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
I think that almost all the ranges used should remain the same. It would be dangerous to only do `initialSetup` for instance on a subset of elements. I think the new algebraic ranges should only be used when computing things like the residual and Jacobian

**Comment by lindsayad** [comment]
For a test, I would recommend a couple subdomain problem and a custom executioner in which you only set the algebraic range to a subset of the subdomains and then just assign the identity for degrees of freedom not on that subset.

**Comment by maxnezdyur** [comment]
> I think that almost all the ranges used should remain the same. It would be dangerous to only do `initialSetup` for instance on a subset of elements. I think the new algebraic ranges should only be used when computing things like the residual and Jacobian

Confused about this comment. Are you saying to get rid of any changes in `initialSetup` that I have?

**Comment by loganharbour** [comment]
> I think that almost all the ranges used should remain the same. It would be dangerous to only do initialSetup for instance on a subset of elements.

I agree. This should be limited to the solve ranges as much as reasonably possible

**Comment by lindsayad** [comment]
> Are you saying to get rid of any changes in `initialSetup` that I have?

Yes. Basically undo all your changes except for within residual and jacobian computation

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
