### PR TITLE
Close Aux System

### LINKED ISSUE #11525: close aux system vectors in checkExceptionAndStopSolve
## Rationale
The Aux system is not properly closed in some cases when an Exception is thrown during the solve.

## Description
@gardnerru has an input that fails with a  PETSc error complaining about solution vectors not being closed after an exception is thrown in `ComputeMultipleInelasticStress::updateQpState()`. I have tracked this down in a the debugger to a call to `_aux->update();` in `FEProblemBase::outputStep(EXEC_FAIL)`. Breaking on exceptions I was able to follow the trajectory of the exception through `checkExceptionAndStopSolve` where the nonlinear system vectors are all properly closed but the Auxiliary system remains open.

I have a small fix for this, which makes Russel's input deal with the exception gracefully and continue with the run

## Impact

Fix broken simulations.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #11525

### CODE REVIEW

**Review by permcody — CHANGES_REQUESTED** [review]
Simple fix inside of a branch that only gets executed when there's an exception - good!

The problem is that this is ripe for a future regression. We are constantly going through the framework and refactoring close methods since they can be very expensive in a parallel simulation. Can we cook up a test case that will fail without this close? We have ExceptionKernel (https://github.com/idaholab/moose/blob/devel/test/src/kernels/ExceptionKernel.C) that we use to trigger these kinds of difficult to track down exception cases. Perhaps an ExceptionAuxKernel will do the trick?

**Comment by dschwen** [comment]
In Russel's case the exception is thrown in a material. The properties provided by the material are used by a Kernel and an AuxKernel.

**Comment by dschwen** [comment]
I have pushed a test that fails and uncovers a potential additional issue (exodiff depending whether rank 0 or non-zero throws!). Still working on a test for this fix.

**Comment by dschwen** [comment]
Sorry, @permcody, no success in constructing a test case. @bwspenc suggested the use of `save_in` could play a role (for having an open aux solution vector while doing `computeResidualTags`), but I have been unable to make it fail.

**Comment by jwpeterson** [comment]
> I have pushed a test that fails and uncovers a potential additional issue (exodiff depending whether rank zero or non-zero throws!). Still working on a test for this fix.

dont_believe

**Comment by dschwen** [comment]
Alrighty, the way `ThrowMaterial` was designed didn't allow me to simply restrict by rank who throws, as the variable based condition was reached at different timesteps on different processors. The new design consistently throws at the same timestep and now everything looks hunky dory.

**Review by permcody — DISMISSED** [review]

**Comment by bwspenc** [comment]
I'm super stoked that this is working now!

**Comment by dschwen** [comment]
@permcody, fixing a unity build failure invalidated your review and thus blocked the auto merge.

**Review by permcody — APPROVED** [review]

**Pull request merged**
