### PR TITLE
RGMB bug fixes and downstream updates from base mesh generators

### PR DESCRIPTION
**Pull request by shikhar413**
refs #24648

### CODE REVIEW

**Comment by shikhar413** [comment]
@eshemon @miaoyinb FYI

**Comment by shikhar413** [comment]
@GiudGiud this PR simplifies the logic for RGMB mesh generation by calling PatternedCartesianMeshGenerator instead of PatternedMeshGenerator, we would be immensely grateful for your review.

FYI I am hitting exodiff errors with all of my Cartesian assembly and core tests when switching from PatternedMeshGenerator to PatternedCartesianMeshGenerator. These meshes look the same before and after the code changes, and I'm wondering if you have any ideas about what could be causing this exodiff (not sure what element 1 refers to in this case)? Wanted to get your input first before trying to re-gold

image
image

**Comment by GiudGiud** [comment]
For the assembly case, the meshes are translated from one another. So that s probably the issue, it cant match non-matching elements

**Review by GiudGiud — COMMENTED** [review]
looks good. Let's try the diffs again with a translation and if it still doesnt do it I ll have another look or ask for help

**Comment by shikhar413** [comment]
> For the assembly case, the meshes are translated from one another. So that s probably the issue, it cant match non-matching elements

Ah, I totally missed that, thanks for pointing that out. The unit tests should all pass now.

**Comment by GiudGiud** [comment]
Seems one of the deleted files was being used in the docs, that s the doco failure
```
listing modules/reactor/test/tests/meshgenerators/core_mesh_generator/core_periphery_ptmg.i block=Mesh
```

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
looks good

**Pull request merged**
