### PR TITLE
Numerical diffusion doco of PorousFlow includes RDG comparison

### LINKED ISSUE #12346: Compare diffusion in RDG with PorousFlow
## Rationale

We hope that RDG will produce less numerical diffusion than PorousFlow.  Currently the diffusion is quantified in these two pages:

http://mooseframework.org/modules/porous_flow/numerical_diffusion.html
http://mooseframework.org/modules/rdg/index.html

I want to document some experiments with the RDG module and include the results in the PorousFlow documentation, so that people like @hsheldon can see what to expect when RDG is implemented in PorousFlow.

It is possible this may also shed some light on ways to implement RDG in PorousFlow, or possibly alternatives to RDG, which i'm still thinking about.

Tagging @permcody , @yidongxiainl , @andrsd , @joshuahansel , @mrodb , @rpodgorney , @lingzou , @cpgr , @YaqiWang , @philippschaedle , @hsheldon

## Description

```AEFVKernel``` and ```AEFVBC``` will be more convenient to use if they have a "velocity" input, as the aforementioned PorousFlow documentation does not assume v=1.

There is a bug in ```AEFVBC``` in the computeJacobian - it needs to size the result correctly (this isn't picked up in the test)

I'll make PorousFlow depend on the RDG module

I'll include the tests in the PorousFlow test suite, alongside the existing tests and documentation.

## Impact

Clarity on what to expect from RDG.  Probably improve my understanding of RDG.

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #12346

### CODE REVIEW

**Comment by WilkAndy** [comment]
I encourage @hsheldon to offer her "users" perspective on the "numerical diffusion" doco on the webpage

**Review by andrsd — COMMENTED** [review]
@WilkAndy I do not believe this is correct. I think you should modify `AEFVFreeOutflowBoundaryFlux` and `AEFVUpwindInternalSideFlux` so they take the velocity parameter and then use it in those `RealVectorValue uadv1(...)` statements.

@yidongxiainl Can you look at `AEFVUpwindInternalSideFlux.C` lines 47 and 50? They read:
```
RealVectorValue uadv1(1.0, 1.0, 1.0);
RealVectorValue uadv2(1.0, 1.0, 1.0);
```
but since this is 1D, I would expect:
```
RealVectorValue uadv1(1.0, 0.0, 0.0);
RealVectorValue uadv2(1.0, 0.0, 0.0);
```
And then, if @WilkAndy wants to prescribe velocity, these should be:
```
RealVectorValue uadv1(_velocity, 0.0, 0.0);
RealVectorValue uadv2(_velocity, 0.0, 0.0);
```
Correct?

**Comment by hsheldon** [comment]
Thanks Andy, I’ll get to it next week

**Comment by andrsd** [comment]
I fixed some SQA stuff. The code and input files are now ok.
I will wait for a ping from @hsheldon in case we need changes in doco.

**Comment by WilkAndy** [comment]
Thanks for the "SQA" stuff, @andrsd

**Comment by WilkAndy** [comment]
@hsheldon emailed me privately with the following change requests:

1. Maybe give a bit more explanation of numerical diffusion, e.g. "sharp profiles of transported quantities (e.g. heat, tracer concentration) become artificially smoothed". Would be nice to have links to the other pages that you mentioned if possible. 
2. Why does RDG produce stepped profiles?
3. Can you provide some guidance on choosing an appropriate timestep to avoid/minimise numerical diffusion? This would presumably have some relationship to the advection speed.

I want to address these before merging, please.

**Comment by WilkAndy** [comment]
@hsheldon emailed me privately with the following change requests:

1. Maybe give a bit more explanation of numerical diffusion, e.g. "sharp profiles of transported quantities (e.g. heat, tracer concentration) become artificially smoothed". Would be nice to have links to the other pages that you mentioned if possible. 
2. Why does RDG produce stepped profiles?
3. Can you provide some guidance on choosing an appropriate timestep to avoid/minimise numerical diffusion? This would presumably have some relationship to the advection speed.

I want to address these before merging, please.

**Comment by WilkAndy** [comment]
hello

**Comment by WilkAndy** [comment]
hello

**Comment by WilkAndy** [comment]
hello

**Comment by andrsd** [comment]
@WilkAndy, ping me when you are done with your edits.

**Comment by WilkAndy** [comment]
Thanks @hsheldon ,

I’ll address the comments shortly

2. RDG is “stepped” because the Variables (mass fraction, in this case) is a Piecewise Constant, and not our usual linear-lagrange.  Although a seemingly minor thing, it could have major code implications as we’ve assumed linear-lagrange all over the place :-(

Because of this i’ve been considering alternatives that are node-based rather than element-based.

3.  I haven’t really thought about this much.  If you look at Fig7, you’ll see that increasing the number of timesteps by a factor of 100 (1E3 steps to 1E5 steps) makes basically no difference, so you’re sunk if you use mass lumping + full upwinding, no matter what you do.  I can explain this physically, but not on email.

What i find really interesting is that the no lumping + no upwinding does very nicely at reducing numerical diffusion if: (1) the number of timesteps is large enough; (2) you ignore the crappy overshoots.

Because of this, i have been reconsidering the Kuzmin-Turek TVD stuff we talked about previously (#12370)

**Comment by WilkAndy** [comment]
@andrsd , assuming this passes all checks, i think i've addressed @hsheldon 's comments.

**Comment by WilkAndy** [comment]
i think this can be merged now

**Review by andrsd — APPROVED** [review]

**Pull request merged**
