### PR TITLE
Support LAGRANGE_VEC in Coupleable interface for nodal objects

### LINKED ISSUE #16076: LAGRANGE_VEC not supported by nodal aux kernels, even though it should be
## Bug Description
See discussion in #15776 

## Steps to Reproduce
Discussed in #15776

## Impact
Impacts any nodal aux kernel on LAGRANGE_VEC variables. This is not used in the framework at the moment, but it should be able to do this. E.g., taking the magnitude of a LAGRANGE_VEC vector in an aux kernel does not work right now.

### PR DESCRIPTION
**Pull request by lindsayad**
@gridley is trying to use a LAGRANGE_VEC variable in a nodal AuxKernel
and he is hitting the current error message. However, LAGRANGE_VEC
variables are well defined at nodes, so I've modified the error check to
only error out if the family is something other than `LAGRANGE_VEC`.
(Our current other families, `MONOMIAL_VEC` and `NEDELEC_ONE`, are not
nodal)

Refs #13827 and closes #16076

### CODE REVIEW

**Comment by lindsayad** [comment]
No sir

**Comment by gridley** [comment]
Is there anything keeping this from being merged? I know it's not necessary since I could just pull your branch, but just figured that I'd wait until this is merged to get some better results from the new feature #15758.

**Comment by lindsayad** [comment]
> Is there anything keeping this from being merged? I know it's not necessary since I could just pull your branch, but just figured that I'd wait until this is merged to get some better results from the new feature #15758.

Let's see if it passes tests

**Review by rwcarlsen — DISMISSED** [review]

**Comment by rwcarlsen** [comment]
Do any of our tests exercise this - i.e. try to get a vector var with lagrange_vec family?  If not we probably ought to add a test.

**Comment by lindsayad** [comment]
@gridley if you have some time, I'd love for you to add a test for this, since you seem like you're chomping at the bit to get this in. You might get to it before I do

**Comment by gridley** [comment]
Sure thing! It's now on my TODO.

**Comment by gridley** [comment]
Do you want me to push the test to your branch you're trying to merge here? @lindsayad

**Comment by gridley** [comment]
Hm, actually, I am running into something unexpected still. I am working on a problem that has second order lagrange vector elements for the velocity, and am trying to compute a scalar aux variable in the same second order lagrange basis. So, my aux kernel gets the velocity as a `VectorVariableGradient`. The vector variable is being constructed as you'd expect from INSADAction.

My input for this aux kernel then looks like:

```
[AuxVariables]
  [q_criterion]
    family=LAGRANGE
    order=SECOND
  []
[]
[AuxKernels]
  [q_criterion_calc]
    type=INSQCriterionAux
    velocity=velocity
    variable=q_criterion
  []
[]
```

Here is my INS setup:

```
[Modules]
  [IncompressibleNavierStokes]
    equation_type = transient
    velocity_boundary = 'bottom right   top               left    front back'
    velocity_function = '0 0 0  0 0 0   lid_function 0 0  0 0 0   0 0 0 0 0 0'
    pressure_pinned_node = 0
    density_name = rho
    dynamic_viscosity_name = mu
    use_ad = true
    laplace = true
    supg = true
    family = LAGRANGE
    order = SECOND
  []
[]
```

So wait... I read up on the aux kernel and it seems that they behave nodally if we're using a LAGRANGE_VEC as the input to our aux computations. This means that `coupledVectorGradient` can't be used. I need to calculate an auxiliary quantity that depends on the solution gradient though. Am I forced to calculate my aux quantity in a monomial basis to trip evaluations being done at quad points, thus making gradients available? It would be nice to know this aux quantity on the same grid as my velocities.

Here is the error I get right now:

```
*** ERROR ***
q_criterion_calc: nodal variables do not have gradients
```

Why can't i just tell the aux kernel to behave elementally?

**Comment by lindsayad** [comment]
> It would be nice to know this aux quantity on the same grid as my velocities.

I shain't know what you mean by this 😄 You mean that you want the degrees of freedom associated with nodes instead of elements? Why does it matter? If your auxiliary variable is a function of the solution gradient, then isn't it fundamentally going to be discontinuous? It seems like you wouldn't *want* to use a Lagrange variable in this case. Perhaps you want to use `L2_LAGRANGE`?

**Comment by gridley** [comment]
I was hoping to get the projection into the space of continuous second order lagranges, but I suppose in this case, L2_LAGRANGE  would also make sense. Wow, this sure came full circle. I was seeing some strange behavior when doing that though. The quantity I'm computing should vanish at the wall, and it wasn't in my case. I thought surely this is due to the discontinuous quantity not being correctly computed, but maybe it is, and I should just refine my mesh.

**Comment by lindsayad** [comment]
> The quantity I'm computing should vanish at the wall, and it wasn't in my case. I thought surely this is due to the discontinuous quantity not being correctly computed, but maybe it is, and I should just refine my mesh.

Discontinuous adds some trickiness because Exodus at least is incapable of storing information for higher-than-zeroth order MONOMIALs. I actually don't know how we handle output of `L2_LAGRANGE` variables. @YaqiWang may know more. I believe he knows as much about visualizing discontinuous families as anyone.

**Comment by gridley** [comment]
Hey @lindsayad, it looks like there are no good way to test this using the existing vector auxkernels in the framework. There is only one auxkernel that maps vector variables to scalar values at the nodes, which is `VectorVariableComponentAux`. I don't think this one is good for testing, because it seems to use `coupledNodalValue` if the aux kernel is nodal. The error here only arises if calling `coupledVectorValue`.

So, as part of this test, maybe i should add `VectorVariableMagnitude` as an aux kernel that will always use `coupledVectorValue`? So, it seems a workaround for this issue would have just been using `coupledNodalValue<RealVectorValue>` rather than `coupledVectorValue`. Superficially, these sound like the same thing. I imagine this has to do with some interfaces being on one but not another?

**Comment by gridley** [comment]
So, to be more specific, this is the test I had written which I expected to previously fail, but it actually doesn't fail before this PR because `coupledNodalValue<RealVectorValue>` ends up getting used rather than `coupledVectorValue` in `VectorVariableComponentAux`.



```
[Mesh]
  type = GeneratedMesh
  dim = 3
  xmin = -1
  xmax =  1
  ymin = -1
  ymax =  1
  zmin = -1
  zmax =  1
  nx = 2
  ny = 2
  nz = 2
[../]

[Variables]
  [./u]
    family = LAGRANGE_VEC
    order = first
    value = '1 2 3'
  [../]
[]

[Kernels]
  [./none]
    type = VectorDiffusion
    variable = u
  [../]
[]

[BCs]
  [./left]
    type = VectorDirichletBC
    variable = u
    boundary = left
    values = '0 0 0'
  [../]
  [./right]
    type = VectorDirichletBC
    variable = u
    boundary = right
    values = '1 2 3'
  [../]
[]

[AuxVariables]
  [./u_first_component]
    initial_condition = 1
  [../]
[]

[AuxKernels]
  [./vx]
    type = VectorVariableComponentAux
    vector_variable = u
    variable = u_first_component
    component = x
  [../]
[]

[Executioner]
  type = Steady
[]

[Outputs]
  exodus = true
[]

```

**Comment by lindsayad** [comment]
I think that a VectorVariableMagnitude aux sounds great. Yea so
coupledNodalValue<T> returns a single T value. coupled(Vector)Value returns
a MooseArray of Real(VectorValue). In your VectorVariableMagnitude aux, you
should be able to just call coupled(Vector)Valuer regardless of the value
of _nodal, and then index with _qp. It should be right for both _nodal and
not _nodal.

**Comment by gridley** [comment]
@lindsayad Could you edit this to say it closes #16076? Aren't we supposed to make an issue for every PR or something?

**Comment by lindsayad** [comment]
Alright, linked to it in the opening PR message!

**Comment by lindsayad** [comment]
@gridley I'm a little confused. In your gold file it looks like`u_mag` is 2.3 everywhere...which doesn't seem right

**Comment by gridley** [comment]
That is pretty wonky... but I just re-ran that input and obtained a result matching that gold. The moose don't lie, man. Do you get a different result than that uniform value? This is definitely unexpected for a diffusion problem w/ Dirichlet BCs on a 2x2x2 mesh...

**Comment by lindsayad** [comment]
Oh yea it repeatably produces the same wrong result :-) the nonlinear solution is correct if you look at it in paraview. It looks like there’s just a problem with the aux calculations. Your aux kernel looks fine. Wondering if we’re just missing some dependency somewhere. Definitely unexpected. I’ll have to run in the debugger to figure it out.

**Comment by lindsayad** [comment]
@gridley the most recent commit I pushed here appears to fix things

**Comment by gridley** [comment]
Nice!!!

**Comment by lindsayad** [comment]
@rwcarlsen this has a test and is ready for re-review

**Review by rwcarlsen — APPROVED** [review]

**Pull request merged**
