### PR TITLE
Support Exodus/output_dimension when using --mesh-only

### PR DESCRIPTION
**Pull request by permcody**
~This enhancement allows the options in an Exodus Output objects to be in effect. Namely the output_dimension override. The big change though is now the mesh-only option will construct the problem object but not populate or initialize it. This is so that we can add a normal output object, which requires the existence of the problem. I believe this is moving in the right direction as it will allow us to utilize more of the native Output object options in the future.~

The new design is to use a new method in MooseMesh::effectiveSpatialDimension(), which returns a dimension number based on the highest axis in use (e.g. if any coordinates are in z, you'll get a 3). This works because we do a loop over the Mesh after all modifiers have been applied in case the Mesh has been moved, extruded, etc. Since I went through the trouble of making this method, I'm using the same version in the `Exodus` output object so this affects all Exodus output, not just the MeshOnly stuff. The one exception is that we'll continue to output 1D meshes in 3D regardless due to a Paraview bug?

@andrsd - This causes 15 tests to diff in Relap-7, all 2D meshes. Previously they were coming out in 3D, now they will come out in 2D which I think is an improvement (moving them around in the visualizer is certainly easier).

@dschwen - This causes a few diffs in Magpie due to a big fat lie in `MyTrimMesh`. That object erroneously returns non-zero coordinates in the unused dimensions. This could easily be fixed by just deleting the get[Min/Max]InDimension methods.

### CODE REVIEW

**Comment by gambka** [comment]
Thanks for making this work.

**Comment by permcody** [comment]
@andrsd - Any thought on this? Relap-7 is really the only holdup here. Definitely a behavior change, but I think it's a good change.

**Comment by andrsd** [comment]
> @andrsd - Any thought on this? Relap-7 is really the only holdup here. Definitely a behavior change, but I think it's a good change.

Sorry, I totally missed this. Our mesh dimension in RELAP-7 is always 3. Even if you have 1D pipe along x-axis, the dimension is 3. What it is is 1D flow in 3D space. If we had a 2D heat structure, the mesh spatial dimension is again 3, not 2, because again it is a 2D object in 3D space.

We always build our special mesh object with spatial dimension equal to 3. So, as long as I can force the dimension in the Exodus writer to 3, this is ok and a RELAP-7 patch should be trivial.

I am looking at the diff right now, to learn how to patch RELAP-7.

**Comment by andrsd** [comment]
Looks like all I need to do is to override `effectiveSpatialDimension` and all should work fine...

**Review by andrsd — APPROVED** [review]

**Comment by permcody** [comment]
Right, or you could actually go with the new behavior! 2D meshes come out
in 2D space. I'm happy to help you with a patch though. We can merge
tomorrow when you are in.

**Comment by andrsd** [comment]
> I'm happy to help you with a patch though.

Patch is done. Thanks for the offer though!


> We can merge tomorrow when you are in.

I am merging now :-)

**Comment by hchen139** [comment]
This makes the output mesh dimension for all peridynamics simulations to 3D, since we only use 1D edge element to model problems of higher dimension (2D and 3D). Any idea to make this be more consistent with peridynamics???

**Comment by permcody** [comment]
Good question... I'd love to just output the right dimension for everything but outputting 1D for 1D causes hundreds of diffs throughout the framework and modules because we've always output as 3D. Part of the reason that we don't want to switch back is due to visualization bugs in Paraview. However, I can understand not wanting 3D for everything either... Perhaps we could consider an application level setting (that you could also turn on in the peridynamics module) that could choose a global default. You can always override it on a case by case basis. Let me know what you think will work best.

**Comment by hchen139** [comment]
The current coordinate check for the effective spatial dimension in meshbase class should work for peridynamics module. However, the exodus class does not use this effective spatial dimension rather than the mesh dimension for 1D mesh.
I tried to use set_mesh_dimension() in my mesh generator class to set the _elem_dims to a user specified value such as the effective spatial dimension even though the actual element dimension is 1D . I did this for the spatial dimension using set_spatial_dimension() too. These dimensions should be correctly set since I checked their values in the same mesh generator class after being set and the returned values are exactly the user provided values. However, when I check these dimensions in the Exodus.C class, the mesh_dimension is till 1 but the spatial_dimension is changed to the user specified value. I'm wondering why the mesh_dimension is till 1 even after being changed to a user specified value. If we can set the _elem_dims using set_mesh_dimension(), I think this would also be a way to work around the current issue at least for peridynamics module.
Maybe Ben has other good suggestions. @bwspenc

**Comment by permcody** [comment]
You probably shouldn't mess with mesh_dimension. It really should be 1 for your scenario. It's supposed to represent the max elemental type in your mesh format. I think the setter might just be there for historical purposes before libMesh differentiated between mesh and spatial dimensions. As for the ability to have MOOSE honor your desired dimension. That should be possible. Ideally, I'd like to change the default for 1D but that breaks so many things in MOOSE right now. I'm open to suggestions. It might be possible to change a default per application or something along those lines.

**Comment by hchen139** [comment]
I couldn't agree with you more. I think the default should be 1D in MOOSE. And this default can be reset per application.

**Pull request merged**
