### PR TITLE
PiecewiseBilinear Extension to Relax CSV File Requirement

### PR DESCRIPTION
**Pull request by stimpsonsg**
Modifying PiecewiseBilinear function to allow x, y, and z to be specified in the function instead of requiring a data_file (with corresponding addition of a 2d_linear_interpolation test).

### CODE REVIEW

**Comment by aeslaughter** [comment]
You don't need to close when they fail, you can just push your fixes on top of this same PR and the testing system will re-test.

**Comment by aeslaughter** [comment]
Nevermind, I see what happened you put the PR to the wrong branch, which you can't change. Sorry.

**Comment by stimpsonsg** [comment]
Yeah, after looking at the rest pushing to devel, I figured that was my error.

**Comment by stimpsonsg** [comment]
When you do a pull request, does it pull the commits off of the branch?  It's saying that branch is even with devel now, when it did have the one commit I was requesting here.

**Comment by aeslaughter** [comment]
When submitting PR's to MOOSE you need to use the devel branch: http://mooseframework.org/wiki/Contributing/

Let us know if you have any trouble and thanks for this contribution, at first glance this looks like a well thought out change and your tests are making the developers look bad.

**Comment by stimpsonsg** [comment]
Ah, nevermind, I see now.

**Comment by aeslaughter** [comment]
I checked out your code, I am going to make a few formatting changes and
add a few tests for the error message and then submit a PR back to you.

**Comment by stimpsonsg** [comment]
Okay, that sounds good.  I opened a new pull request, but I think something is more off with that one.  I'm merging into devel, but it says it's a ton of commits.

**Pull request closed without merging**
