### PR TITLE
Add debugging information for showing the progress of initial setup

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #15444.

### CODE REVIEW

**Comment by loganharbour** [comment]
What does this output look like?

I'm hesitant to add more tools for debugging timing when we should just enhance current tools. We should be able to grab this information from the PerfGraph instead and summarize it differently.

**Comment by YaqiWang** [comment]
Looks like this:
```
...
[DBG][ACT] TASK (              add_kernel) TYPE (                 AddKernelAction) NAME (           power) Memory usage 291MB [Time] 4.11s
[DBG][ACT] TASK (              add_kernel) TYPE (             NeutronSAAFSNAction) NAME (            saaf) Memory usage 291MB [Time] 4.11s
[DBG][ACT] TASK (                  add_bc) TYPE (                     AddBCAction) NAME (      convection) Memory usage 546MB [Time] 5.58s
[DBG][ACT] TASK (                  add_bc) TYPE (             NeutronSAAFSNAction) NAME (            saaf) Memory usage 546MB [Time] 5.58s
[DBG][ACT] TASK (          add_aux_kernel) TYPE (          RattlesnakeDebugAction) NAME (           Debug) Memory usage 651MB [Time] 6.27s
...
[DBG][ACT] Finished executing all actions with memory usage 652MB6.29s
[DBG] Memory usage 657MB [Time] 8.53s (Starting FEProblem initial setup) 
[DBG] Memory usage 657MB [Time] 8.53s (Adding extra vectors) 
[DBG] Memory usage 657MB [Time] 8.53s (Computing max dofs per elem/node) 
[DBG] Memory usage 657MB [Time] 8.67s (Setting AD required derrivative size) 
[DBG] Memory usage 657MB [Time] 8.67s (OutputWarehouse initial setup) 

Framework Information:
MOOSE Version:           git commit 21186e0 on 2020-04-28
LibMesh Version:         c6e82b286ef5c2cecede458b5f9c7c1b1daa8e53
PETSc Version:           3.12.5
SLEPc Version:           3.12.1
Current Time:            Thu Jun 11 01:46:27 2020
Executable Timestamp:    Thu Jun 11 01:45:48 2020

Parallelism:
  Num Processors:          192
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   
    Total:                 43809
    Local:                 251
  Elems:                   
    Total:                 87108
    Local:                 447
  Num Subdomains:          7
  Num Partitions:          192
  Partitioner:             metis

Nonlinear System:
  Num DOFs:                19644708
  Num Local DOFs:          112574
  Variables:               "T" { "aflux_g0_d0" "aflux_g0_d1" "aflux_g0_d2" "aflux_g0_d3" "aflux_g0_d4" 
                             ... "aflux_g6_d59" "aflux_g6_d60" "aflux_g6_d61" "aflux_g6_d62" "aflux_g6_d63" 
                             } 
  Finite Element Types:    "LAGRANGE" "LAGRANGE" 
  Approximation Orders:    "FIRST" "FIRST" 

Auxiliary System:
  Num DOFs:                397677
  Num Local DOFs:          2306
  Variables:               { "flux_moment_g0_L0_M0" "flux_moment_g1_L0_M0" "flux_moment_g2_L0_M0" "flux_moment_g3_L0_M0" 
                             "flux_moment_g4_L0_M0" "flux_moment_g5_L0_M0" "flux_moment_g6_L0_M0" } "power_density" 
                             "T1" 
  Finite Element Types:    "LAGRANGE" "L2_LAGRANGE" "LAGRANGE" 
  Approximation Orders:    "FIRST" "FIRST" "FIRST" 

Execution Information:
  Executioner:             NonlinearEigen
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    hypre boomeramg 

[DBG] Memory usage 658MB [Time] 8.68s (Ghosting ghosted boundaries) 
[DBG] Memory usage 658MB [Time] 8.68s (Calling mesh changed) 
[DBG] Memory usage 658MB [Time] 8.80s (Pre IC/aux user objects initial setup) 
[DBG] Memory usage 658MB [Time] 8.80s (Checking nonlocal coupling) 
[DBG] Memory usage 658MB [Time] 8.80s (Functions initial setup) 
[DBG] Memory usage 658MB [Time] 8.80s (Updating seeds for random interface objects) 
[DBG] Memory usage 658MB [Time] 8.80s (Computing pre IC user objects) 
[DBG] Memory usage 658MB [Time] 8.80s (Applying initial conditions) 
[DBG] Memory usage 659MB [Time] 8.90s (Initializing stateful material properties) 
[DBG] Memory usage 659MB [Time] 8.90s (Indicators/markers initial setup) 
[DBG] Memory usage 659MB [Time] 8.90s (Initial mesh adaptation) 
[DBG] Memory usage 659MB [Time] 8.90s (Copying solutions backwards) 
[DBG] Memory usage 659MB [Time] 8.91s (Nonlinear system initial setup) 
[DBG] Memory usage 659MB [Time] 8.91s (Auxiliary system initial setup) 
[DBG] Memory usage 659MB [Time] 8.91s (Updating nearest node geometry search) 
[DBG] Memory usage 659MB [Time] 8.91s (Updating active semi-local node range) 
[DBG] Memory usage 659MB [Time] 8.91s (Updating mesh for mortar) 
[DBG] Memory usage 659MB [Time] 8.91s (Updating geometry search) 
[DBG] Memory usage 659MB [Time] 8.91s (Time integrator initial setup) 
[DBG] Memory usage 659MB [Time] 8.91s (Transfers initial setup) 
[DBG] Memory usage 659MB [Time] 8.91s (Execute initial transfers/multiapps/uos/auxkernels) 
[DBG] Memory usage 660MB [Time] 8.95s (Executing inital controls) 
[DBG] Memory usage 660MB [Time] 8.95s (Initializing scalar variables) 
[DBG] Memory usage 660MB [Time] 8.95s (Flushing console) 
[DBG] Memory usage 660MB [Time] 8.95s (Checking registry lables) 
[DBG] Memory usage 660MB [Time] 8.95s (Finished FEProblem initial setup) 
```

**Comment by YaqiWang** [comment]
PerfGraph is not very intuitive for locating the code, gperftools requires compiling the code differently. This is a simple capability with which developers can pass `Problem/show_initial_setup=true Debug/show_actions=true` in the command-line to quickly see if there are any outstanding performance issues for large simulations quickly.

**Comment by YaqiWang** [comment]
I think this is good to go after the tests pass. Thanks.

**Comment by rwcarlsen** [comment]
I don't think this approach scales well in general.  @YaqiWang - you are very interested in initial setup detail because you run applications that are heavy there.  But someone else might be super interested in detailed logging for some other part of the code.  We already have several parameters users can set to output more/less info on various topics spread all around the framework.  I don't think it is a very good approach to just keep adding more special on-off flags for this stuff.  The perf graph was one attempt to provide a generalized system for logging a bunch of timing info.  And it works well.

The idea of adding more logging to various parts of moose is good.  I think though that it might be worth having a brief discussion on whether we want to hold off on splattering more one-off logging around until we design a proper logging system or not.

gperftools is very good for cpu and memory profiling.  And it is comprehensive - every function, every callstack.  You do have to compile in oprof mode, but I don't think that is particularly onerous.  And inevitably, when doing this sort of profiling work - you end up needing more information than you have printed/logged and need to either add even more one-off logging (yuck) - or just run a proper profiling anyway.

That's my 2 cents anyway.

**Comment by YaqiWang** [comment]
This is just printing our about 25 line messages, nothing about scaling though. The number could grow but will never be a problem affecting performance, plus it is controlled by a parameter that users can turn on. We typically will use this parameter to ask users to report back something quickly for performance issues. It will be quite a burden to ask users recompile the application in gperftools. I believe adding this is helpful and can keep the `initialSetup` well tracked.

**Comment by rwcarlsen** [comment]
I wasn't talking about scaling w.r.t. performance or anything like that.  I meant - scaling - as in we can't keep applying the convention of whenever somebody wants some extra logging for whatever (good) reason, we add a bunch of custom one-off printing and input parameters for them.  I meant "doesn't scale" as in the "not sustainable" sense.

**Comment by YaqiWang** [comment]
I realized that you could mean this during the last reply. My argument in the last sentence still apply though. We indeed want to show this complicated function and ask developers to spend a little more efforts on this when then add new functions there. It will be pretty obvious for them to follow the similar pattern in there. So I do not think that is an issue. This equally applies to other applications than Griffin especially for large-sized simulations.

**Comment by rwcarlsen** [comment]
Did you look in to possibly making some additions to the perfgraph stuff to make this work?  That already tracks/reports timing well.  Perhaps we could work in a way to toggle memory tracking into that.

**Comment by YaqiWang** [comment]
Yes. As I said before, the items in perf_graph do not correspond lines of the code. This new parameter is basically extending what we have with `show_actions`.

**Comment by rwcarlsen** [comment]
Perfgraph tracks whatever blocks of code we want.  You just put the `TIME_SECTION` macro in the scope of interest.

**Comment by YaqiWang** [comment]
You did not listen to me, perf_graph does not show the memory and CPU time increment as this parameter. Plus not all codes are surrounded by TIME_SECTION.

**Comment by rwcarlsen** [comment]
It does show the CPU time.  You are correct, however, that it does not show memory usage.  But maybe we could consider adding memory usage as optionally tracked/displayed info for that.  And adding more timed sections to an existing general system is much preferable to adding additional special case logging.

**Comment by YaqiWang** [comment]
Well, I think this is useful add-on. The only downside I can think of is to manually add the print-out but on the other hand, it forces developers carefully insert new items in the initialSetup. The function is enormous and I am concerned developers introduce performance regression accidentally there. When problem happens, I can inform users to turn `Problem/show_initial_setup=true` and `Debug/show_actions=true` and report back. This is a huge thing for us to communicate with users. I do not see problems for getting this in.

**Comment by rwcarlsen** [comment]
I completely agree that this is useful.  I just think we need to work to unify it's implementation with other patterns/facilities that already exist.  For timing we should definitely use perfgraph macros.  For the memory stats, maybe we could integrate it into perfgraph - or maybe not - but we should at least try/investigate.

**Comment by YaqiWang** [comment]
We can have all of these, in-line print-outs, timed print-outs, perf graph. I think the first one possibly only works for the setup. The problem for using perfgraph macros, timed prints is that it is subjective, i.e. up to developers to decide whether adding it or not. I think integrate memory stats in perfgraph is a good idea.

**Comment by YaqiWang** [comment]
Guys, I want this to be merged so that I can clean up the branches on my local machine. Switching branches is painful...

**Comment by permcody** [comment]
@YaqiWang - Why not build extra capability into `TimedPrint`? This would be at least the third if not the forth different way of printing progress. I very much agree with @rwcarlsen on this. Nobody is against adding things to help you out with monitoring long startups (like you are doing). We are only debating the semantics of how to do it. @friedmud added `TimedPrint` precisely to satisfy the negative feedback he got when we was running large sims. Having a ton of output on something like RELAP-7 just makes things messy. Yeah, I know it makes sense for Griffin. So how do we come together? The solution back then was to conditionally print based on elapsed time which works very nicely and people are more or less happy with that capability. I'm onboard for adding to this capability, but this PR is just adding something completely different.

**Comment by friedmud** [comment]
@permcody TimedPrint won't help here - you need nested capability.

@rwcarlsen Thank you for putting in some good thoughts here.  I agree with you: augmenting the PerfGraph system to allow for memory allocation seems like the best plan to me.

When doing some performance testing last night I was thinking that the "Child" columns are not really useful.  Perhaps we remove all of them and add a column for "Memory Increment".  It would be trivial to do and we could get a lot of information from it.

**Comment by friedmud** [comment]
@permcody Actually - thinking about it again... I don't see why we couldn't have this in both the TimedPrint and PerfGraph.  When TimedPrint is over and it shows the total elapsed time - it could also show the memory increment.  Having that information there certainly wouldn't hurt anything.

**Comment by YaqiWang** [comment]
My baseline argument is that this does not hurt anything. More arguments are: monitoring the complicated initial setup (that everyone can potentially touch) can give us peace of mind on performance; providing an easy way to pinpoint performance problems even users can use. This progressive printing can coexist with TimedPrint, PerfGraph, PETSc logview.

**Comment by friedmud** [comment]
Adding memory capability to `TimedPrint` was pretty successful:

image

**Comment by rwcarlsen** [comment]
@YaqiWang But it does hurt things (while also helping).  It hurts code maintainability.  It is likely to become incorrect over time as stuff moves around in initialSetup.  It also provides a less consistent/unified user experience.  Working within the timed print and perfgraph mechanisms, we should be able to provide all this benefit/info without incurring those costs.

**Comment by YaqiWang** [comment]
The amount of maintenance added by this is negligible than the amount of any capabilities I'd say. No free lunch though. Improving timed print and perf graph is independent. @friedmud that is looks very nice. We should push that in quickly.

**Comment by loganharbour** [comment]
Aside from my disagreements on the additional maintenance requirements for this.. I think that putting it in the TimedPrint (and potentially also the PerfGraph) is superior.

A few of the reasons:
- Having it scoped instead and therefore showing the change within the scope is more specific than the implementation here
- It extends outside of just `FEProblemBase::initialSetup()` in a more general manner, and works with all of the other timed prints we already have
- It doesn't require using yet another method that does on screen output
- It extends a current system instead of adding another

My $0.02.

**Comment by YaqiWang** [comment]
I think I do have strong opinion on getting this in. It helps our users and developers a lot with this simple command line parameter `Problem/show_initial_setup=true`.

**Comment by aeslaughter** [comment]
> I think I do have strong opinion on getting this in. It helps our users and developers a lot with this simple command line parameter `Problem/show_initial_setup=true`.

I am with the other MOOSE developers on this. Putting this with PerfGraph gives one flag to turn on all timing/memory extra info: Outputs/print_perf_graph. TimedPrint doesn't require any flags if I recall. This option already exists, your method requires another flag to get all the information.

Secondly, your flag is adding an output related flag to Problem block.

**Comment by YaqiWang** [comment]
> Secondly, your flag is adding an output related flag to Problem block.
I do not think this is an issue, we have several similar flags in `Debug` block.

I am not against enhancing PerfGraph and TimedPrint and actually very supportive on that. This flag supplements what we have in those. It is unique in sense that we can use it to quickly find offending lines. Note that PerfGraph and TimedPrint is subjective, meaning only works when developers put codes in place.

AGAIN: I am not excessively adding this kind of print-outs. This does not hurt.

**Comment by rwcarlsen** [comment]
We _can_ add perfgraph and/or timed prints to initialsetup if that is important (as you suggest).  I think everyone else here agrees that adding some logging to initialSetup is okay - we just want it to be done via existing systems rather than new one-off parameters.

**Comment by YaqiWang** [comment]
Yes, monitoring `initialSetup` is super important. It will take a lot effort to add TimedPrint and PerfGraph for all items in initial setup, also the problem is that it may not always be necessary. This quick parameter can supplement this. I do not see reasons why it is so concerning. Please be considerate. I need this parameter.

**Comment by loganharbour** [comment]
> It will take a lot effort to add TimedPrint and PerfGraph for all items in initial setup

Doesn't your method require us to do this as well?

**Comment by YaqiWang** [comment]
> > It will take a lot effort to add TimedPrint and PerfGraph for all items in initial setup
> 
> Doesn't your method require us to do this as well?

No, it has been done here.

**Comment by YaqiWang** [comment]
Cannot believe 30 days have passed...

**Pull request closed without merging**
