### PR TITLE
Fixing the MeshSideSetGenerator to make it work in FV

### LINKED ISSUE #16505: MeshSideSetGenerator does not work in FV
## Bug Description
When using the MeshSideSetGenerator to create a LowerDimensional block, a FV simulation does not take it into account.

## Steps to Reproduce
[3d_dirichlet_lowerdim_NOTWORKING.txt](https://github.com/idaholab/moose/files/5700184/3d_dirichlet_lowerdim_NOTWORKING.txt)

## Impact
LowerDimensional blocks cannot be simulated with Finite Volume

### PR DESCRIPTION
**Pull request by mlesueur**
- Fixed erroneous duplication of lowerdim elements on internal boundaries
   - Current solution might not fit MOOSE standards
 - Implemented correct elem-neighbor connections in MeshSideSetGenerator
 - Allowed for taking into account lowerdim intersections (changes implemented in MeshSideSetGenerator, MooseMesh, FaceInfo)
   - Current solution might not fit MOOSE standards
 - Added new fvkernel to solve for diffusion in blocks with or without lowerdim (FVLowerDimDiffusion)
 - Added test benchmarking FV diffusion through intersecting lowerdims

closes #16505

### CODE REVIEW

**Comment by rwcarlsen** [comment]
To make it farther in the automated testing - at least one of your commit messages needs to contain a ticket/issue number (e.g. `#1234`).  Also - if it isn't already - you'll need to make sure your changes/mods are formatted correctly via `clang-format`.  Once those things are sorted, you should be able to get more feedback from the testing here.

**Comment by mlesueur** [comment]
Hi @rwcarlsen,
I have hopefully fixed a bit the commits so that CIVET goes up to the tests. Right now, only the tests of the MeshSideSetGenerator do not pass, but that should be fixed when we agree on a correct solution to prevent the duplication of lowerdim elements on the internal boundary.

**Comment by mlesueur** [comment]
See below the solution currently implemented for taking in account the intersection of lowerdim elements

pr

**Comment by mlesueur** [comment]
In my method, I changed the neighbor of the element adjacent to the lowerdim element to be the newly created lowerdim element. However I cannot do the opposite because the lowerdim element face is of a lower dimensionality.
In debug mode, libmesh spits an error because it does not like that the element-neighbor relationship is not reciprocal. (line 1853 of [elem.C](https://libmesh.github.io/doxygen/elem_8C_source.html))
pr2

**Pull request closed without merging**
