### PR TITLE
Removing IsParamValid usage after intialization in dynamic inertial force computations

### LINKED ISSUE #13290: Remove isParamValid function usage afer initialization
## Bug Description
There are several instances, especially in dynamic inertial force kernels in TensorMechanics where the isParamValid function is used after initialization. After profiling a MASTODON run using Instruments on Mac, we found that the frequent usage of isParamValid at every timestep is slowing down the simulation significantly. 

## Steps to Reproduce
Profile any simulation involving dynamic inertial force kernels. The profile should show a significant contribution from the usage of the isParamValid function.  

## Impact
Preliminary runs in MASTODON showed a 2.5x speedup when these functions were replaced by boolean class variables created during initialization.

### PR DESCRIPTION
**Pull request by cbolisetti**
Changed the usage of isParamValid function to a boolean class variable that is initialized accordingly. This closes #13290

### CODE REVIEW

**Comment by cbolisetti** [comment]
@sveerara please check if this is okay. Also if there are any other places where isParamValid is used in the body of the class, please let me know and I'll change it in this PR. I didn't change lineelementaction since it is only executed at the beginning.

**Review by permcody — DISMISSED** [review]

**Comment by sveerara** [comment]
@cbolisetti, I din't realize that isParamValid could slow down things this much. Thanks for making these changes. ComputeIncrementalBeamStrain also has isParamValid in computeQpStrain.

**Comment by cbolisetti** [comment]
> @cbolisetti, I din't realize that isParamValid could slow down things this much. Thanks for making these changes. ComputeIncrementalBeamStrain also has isParamValid in computeQpStrain.

@sveerara neither did we, until @friedmud looked at the profiling results and pointed out. I will change the other classes too. We'd like to continue this process and see if there are any more obvious bottlenecks that we can remove. I'll keep you posted.

**Comment by dschwen** [comment]
It does a map lookup involving string comparisons. That's a lot of operations. We should probably guard against it being used in tight loops (like we throw an error when gateMaterialProperty is used after construction). We could set a flag in FEProblem at the beginning of an element/node loop (which is cleared when the loop is done) and check for that flag in expensive operations like the Input Parameter stuff. This is not new and I have fixed issues like this a before. Unfortunately it is not really documented anywhere (as in a best practices document).

**Review by permcody — APPROVED** [review]

**Pull request merged**
