### PR TITLE
Loosen exodiff tolerance slightly on problem test

### LINKED ISSUE #9530: Patch for PR #9451
### Description of the enhancement or error report
updated the generalized_plane_strain_tm_contact test input file and regolded the result 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by bwspenc**
closes #9530

### CODE REVIEW

**Comment by bwspenc** [comment]
@roystgnr This should get that test passing with PR #9451.

**Comment by bwspenc** [comment]
@hchen139

**Comment by roystgnr** [comment]
Looks like that should do it.  Testing with a relative tolerance as high as 1e-4 horrifies me... but I guess it's relative to the local element value, which on our failing element is several orders of magnitude less than the peak solution value for that variable, so this probably isn't an actual regression, just a tiny bit of numerical error diffused into a part of the solution where it's noticeable.

If there was an easy exodiff option for "relative error compared to peak solution value" (or compared to average, even), I'd be agitating to switch all the MOOSE tests to that immediately...

**Comment by bwspenc** [comment]
@roystgnr We commonly run into issues like this where we exceed the allowable relative tolerance when the value is low, but not so low that it is approximately zero.  It would be nice to have some option for exodiff that gradually relaxed the relative tolerance when the value dropped down.  Maybe the relative error compared with the peak solution value you suggested would do the trick.  If we had a good proposal, I'm sure we could get that added to exodiff.

We have trouble in general with stresses.  They are noisier than our solution variables (displacements) because they're based on their derivatives.

**Review by jasondhales — APPROVED** [review]

**Comment by permcody** [comment]
You know, we have the source for Exodiff in our repository and I've patched it before (and sent my patch to upstream). Exodiff very stable so the risk of introducing our own changes and having to maintain them outside the code base is very low. We might even be able to submit our additions to upstream. Just a thought.

**Comment by bwspenc** [comment]
Good to know!  I'll keep that in mind the next time I get frustrated dealing with a misbehaving test that is just barely diffing.

**Pull request merged**
