### PR TITLE
Migrate conda-moose recipes into moose

### PR DESCRIPTION
**Pull request by milljm**
Start populating moose with conda recipes.

Refs #14922

### CODE REVIEW

**Comment by milljm** [comment]
If I removed the label, then why is it still there GitHub...

**Comment by permcody** [comment]
So I'm not sure how to review this. Just take your word for it?

**Comment by milljm** [comment]
I am going to commit once more, by adding a readme.

**Comment by milljm** [comment]
The 'do not merge' label was there for the purpose of testing civet recipes.

**Review by loganharbour — APPROVED** [review]

**Review by fdkong — APPROVED** [review]

**Pull request merged**
