### PR TITLE
Test named blocks/sidesets/nodesets with Nemesis mesh

### LINKED ISSUE #23006: Named blocks, sidesets, nodesets and Nemesis
## Bug Description
Can't use a Nemesis mesh and reference a named block, sideset, or nodeset from the input file

See https://github.com/libMesh/libmesh/pull/3462

## Steps to Reproduce
Put names in place of numbers in nemesis_test.i

## Impact
Annoyance

### PR DESCRIPTION
**Pull request by jasondhales**
Closes #23006

Requires https://github.com/libMesh/libmesh/pull/3462

### CODE REVIEW

**Review by roystgnr — DISMISSED** [review]
Looks sufficient to me.  Just need to give CI a kick after the next libMesh submodule update goes in.

**Comment by roystgnr** [comment]
Whoa, that looks like an actual failure.  What'd we get wrong?  Is it not handling the case where a sideset isn't found anywhere among a processor's local elements?

**Comment by jasondhales** [comment]
The last test failure was due to the input file using block_1 for the block name, but the mesh didn't have a name for the block.  I thought it did from looking at it in Paraview, but that was just a default name from Paraview.  I refreshed the mesh to have block_1 as the block name to make the test more complete.  It should pass now.

**Comment by jasondhales** [comment]
@roystgnr will you review this now that the test passes?  Thanks.

**Review by roystgnr — APPROVED** [review]

**Pull request merged**
