### PR TITLE
Expand isParamValid for Vectors of MooseEnum

### LINKED ISSUE #21530: Validity of a MoosEnum Vector Required InputParameter
## Bug Description

When a required input parameter is of type `std::vector<MooseEnum>`, `isParamValid` does not check if the vector entires are valid `MooseEnum`s, `isParamValid` only checks if the parameter name is present. As a result, `applyParameters` does not copy required input parameters that are `std::vector<MooseEnum>` and the required input parameter remains undefined.

## Steps to Reproduce

The following unit test demonstrates the described behavior of `isParamValid` and `applyParameters`.

```
  MooseEnum types("foo bar");

  InputParameters p1 = emptyInputParameters();
  p1.addRequiredParam<std::vector<MooseEnum>>("enum", std::vector<MooseEnum>(1,types), "testing");

  InputParameters p2 = emptyInputParameters();
  p2.addRequiredParam<std::vector<MooseEnum>>("enum", std::vector<MooseEnum>(1,types), "testing");

  MooseEnum set("foo bar", "bar");
  p2.set<std::vector<MooseEnum>>("enum") = std::vector<MooseEnum>(1,set);

  EXPECT_FALSE(p1.isParamValid("enum"));
  EXPECT_TRUE(p2.isParamValid("enum"));

  p1.applyParameters(p2);

  EXPECT_TRUE(p1.get<std::vector<MooseEnum>>("enum")[0]=="bar");
```
## Impact

This prevents SAM from correctly creating sub components based on a template input that utilizes a vector of `MooseEnum`

### PR DESCRIPTION
**Pull request by dogrady2**
This PR expands the logic within `isParamValid` to confirm that all entries within a vector of MooseEnum objects are valid. Confirming that all entries are valid allows `applyParameters` to correctly determine if a required parameter has been defined.

Closes #21530

### CODE REVIEW

**Comment by dogrady2** [comment]
@GiudGiud Can you review this PR, or assign someone more appropriate.

**Comment by GiudGiud** [comment]
@dogrady2 we will invite you soon to the idaholab org on github so the test suite may run for your PRs

**Comment by GiudGiud** [comment]
what is the application for vectors of MooseEnum as opposed to a MultiMooseEnum?

**Comment by GiudGiud** [comment]
I guess you could use different enums

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
