### PR TITLE
Bilinear

### PR DESCRIPTION
**Pull request by JerryLiu2023**
## Reason

There is a misfunction of piecewisebilinear function in reading data table from .csv file.
This piecewisebilinear function is updated to read a slightly changed format of input file. 
## Design

Modify piecewisebilinear function by skipping the first data entry in the data input file
## Impact

Yes.

This fix the issue #19173

### CODE REVIEW

**Review by GiudGiud — CHANGES_REQUESTED** [review]
I dont think we will want to just change CSV reading by this function for everyone (existing tests etc) now (unless there s a bug?). People are using this function everywhere. But we could add an option to switch between an old and a new behavior.

Am I understanding correctly that this PR makes it skip the first column?

**Review by dschwen — CHANGES_REQUESTED** [review]
The only change I can request here is not to make this PR.

**Comment by dschwen** [comment]
Ok, I think some confusion here stems from `PiecewiseBilinear` calling its file format "csv". Technically that's not entirely wrong, but there is a very peculiar layout to the data, namely the first row is are the first coordinate axis ticks, and the first column (excluding the first entry of that column) are the second coordinate axis ticks. All values other than the values in row or column one are values in the product space of the two axes.

The change Jerry proposes only makes all columns equally long by filling the empty space in the top left corner with a dummy value. 

Changing a file format that users probably rely on just like that is a _showstopper_ IMO. At the _very least_ there should be a backwards compatible fall back. But that would complicate the code even further. 

So my question is: "Why?" Or rather "What problem is solved with this PR?"

**Comment by GiudGiud** [comment]
Seems this is no longer a concern.

**Pull request closed without merging**
