### PR TITLE
XFEM cleanup

### PR DESCRIPTION
**Pull request by bwspenc**
Remove the usage of strings of 9s to initialize large values for unsigned ints

### CODE REVIEW

**Comment by bwspenc** [comment]
FYI @austinltam. We'll reapply your stuff on top of this once it goes through, and this should fix the memory leak.

**Comment by lindsayad** [comment]
```
test:moving_interface.moving_interface: ==32459== 33,184 (320 direct, 32,864 indirect) bytes in 1 blocks are definitely lost in loss record 147 of 153
test:moving_interface.moving_interface: ==32459==    at 0x483AE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (new_allocator.h:114)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (alloc_traits.h:444)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<EFAElement2D, std::allocator<EFAElement2D>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_count<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:677)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:1344)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:359)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate_shared<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:702)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: make_shared<EFAElement2D, unsigned int&, unsigned int&> (shared_ptr.h:718)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: ElementFragmentAlgorithm::add2DElement(std::vector<unsigned int, std::allocator<unsigned int> >, unsigned int) (ElementFragmentAlgorithm.C:84)
test:moving_interface.moving_interface: ==32459==    by 0x4A854B9: XFEM::buildEFAMesh() (XFEM.C:331)
test:moving_interface.moving_interface: ==32459==    by 0x4A9892B: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:255)
test:moving_interface.moving_interface: ==32459==    by 0x55210BC: FEProblemBase::updateMeshXFEM() (FEProblemBase.C:6021)
test:moving_interface.moving_interface: ==32459==    by 0x55714F8: FEProblemBase::initialSetup() (FEProblemBase.C:886)
test:moving_interface.moving_interface: ==32459==    by 0x5AC84F0: Transient::init() (Transient.C:229)
test:moving_interface.moving_interface: ==32459==    by 0x61CDFD9: MooseApp::executeExecutioner() (MooseApp.C:938)
test:moving_interface.moving_interface: ==32459==    by 0x61CE08A: MooseApp::run() (MooseApp.C:1067)
test:moving_interface.moving_interface: ==32459==    by 0x116D8D: main (main.C:33)
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== 57,768 (80 direct, 57,688 indirect) bytes in 2 blocks are definitely lost in loss record 150 of 153
test:moving_interface.moving_interface: ==32459==    at 0x483AE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
test:moving_interface.moving_interface: ==32459==    by 0x49DF285: allocate (new_allocator.h:114)
test:moving_interface.moving_interface: ==32459==    by 0x49DF285: allocate (alloc_traits.h:444)
test:moving_interface.moving_interface: ==32459==    by 0x49DF285: _M_allocate (stl_vector.h:343)
test:moving_interface.moving_interface: ==32459==    by 0x49DF285: void std::vector<std::shared_ptr<EFAElement>, std::allocator<std::shared_ptr<EFAElement> > >::_M_realloc_insert<std::shared_ptr<EFAElement> const&>(__gnu_cxx::__normal_iterator<std::shared_ptr<EFAElement>*, std::vector<std::shared_ptr<EFAElement>, std::allocator<std::shared_ptr<EFAElement> > > >, std::shared_ptr<EFAElement> const&) (vector.tcc:440)
test:moving_interface.moving_interface: ==32459==    by 0x49C59AB: push_back (stl_vector.h:1195)
test:moving_interface.moving_interface: ==32459==    by 0x49C59AB: EFAElement::findGeneralNeighbors(std::map<std::shared_ptr<EFANode>, std::set<std::shared_ptr<EFAElement>, std::less<std::shared_ptr<EFAElement> >, std::allocator<std::shared_ptr<EFAElement> > >, std::less<std::shared_ptr<EFANode> >, std::allocator<std::pair<std::shared_ptr<EFANode> const, std::set<std::shared_ptr<EFAElement>, std::less<std::shared_ptr<EFAElement> >, std::allocator<std::shared_ptr<EFAElement> > > > > >&) (EFAElement.C:221)
test:moving_interface.moving_interface: ==32459==    by 0x49CED1E: EFAElement2D::setupNeighbors(std::map<std::shared_ptr<EFANode>, std::set<std::shared_ptr<EFAElement>, std::less<std::shared_ptr<EFAElement> >, std::allocator<std::shared_ptr<EFAElement> > >, std::less<std::shared_ptr<EFANode> >, std::allocator<std::pair<std::shared_ptr<EFANode> const, std::set<std::shared_ptr<EFAElement>, std::less<std::shared_ptr<EFAElement> >, std::allocator<std::shared_ptr<EFAElement> > > > > >&) (EFAElement2D.C:451)
test:moving_interface.moving_interface: ==32459==    by 0x498BBF7: ElementFragmentAlgorithm::updateEdgeNeighbors() (ElementFragmentAlgorithm.C:163)
test:moving_interface.moving_interface: ==32459==    by 0x4A85E6F: XFEM::buildEFAMesh() (XFEM.C:353)
test:moving_interface.moving_interface: ==32459==    by 0x4A9899F: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:266)
test:moving_interface.moving_interface: ==32459==    by 0x55210BC: FEProblemBase::updateMeshXFEM() (FEProblemBase.C:6021)
test:moving_interface.moving_interface: ==32459==    by 0x5AB81C0: PicardSolve::solveStep(double, double&, double, double&, bool, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) (PicardSolve.C:457)
test:moving_interface.moving_interface: ==32459==    by 0x5ABB9F7: PicardSolve::solve() (PicardSolve.C:233)
test:moving_interface.moving_interface: ==32459==    by 0x5BF1D47: TimeStepper::step() (TimeStepper.C:163)
test:moving_interface.moving_interface: ==32459==    by 0x5AB6F22: Transient::takeStep(double) (Transient.C:417)
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== 72,904 (16 direct, 72,888 indirect) bytes in 1 blocks are definitely lost in loss record 151 of 153
test:moving_interface.moving_interface: ==32459==    at 0x483AE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
test:moving_interface.moving_interface: ==32459==    by 0x49E0E35: allocate (new_allocator.h:114)
test:moving_interface.moving_interface: ==32459==    by 0x49E0E35: allocate (alloc_traits.h:444)
test:moving_interface.moving_interface: ==32459==    by 0x49E0E35: _M_allocate (stl_vector.h:343)
test:moving_interface.moving_interface: ==32459==    by 0x49E0E35: void std::vector<std::shared_ptr<EFAFragment2D>, std::allocator<std::shared_ptr<EFAFragment2D> > >::_M_realloc_insert<std::shared_ptr<EFAFragment2D> const&>(__gnu_cxx::__normal_iterator<std::shared_ptr<EFAFragment2D>*, std::vector<std::shared_ptr<EFAFragment2D>, std::allocator<std::shared_ptr<EFAFragment2D> > > >, std::shared_ptr<EFAFragment2D> const&) (vector.tcc:440)
test:moving_interface.moving_interface: ==32459==    by 0x49B79C7: EFAElement2D::createChild(std::set<std::shared_ptr<EFAElement>, std::less<std::shared_ptr<EFAElement> >, std::allocator<std::shared_ptr<EFAElement> > > const&, std::map<unsigned int, std::shared_ptr<EFAElement>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<EFAElement> > > >&, std::map<unsigned int, std::shared_ptr<EFAElement>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<EFAElement> > > >&, std::vector<std::shared_ptr<EFAElement>, std::allocator<std::shared_ptr<EFAElement> > >&, std::vector<std::shared_ptr<EFAElement>, std::allocator<std::shared_ptr<EFAElement> > >&, std::map<unsigned int, std::shared_ptr<EFANode>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<EFANode> > > >&) (EFAElement2D.C:1114)
test:moving_interface.moving_interface: ==32459==    by 0x49C733D: ElementFragmentAlgorithm::createChildElements() (ElementFragmentAlgorithm.C:375)
test:moving_interface.moving_interface: ==32459==    by 0x49C991F: ElementFragmentAlgorithm::updateTopology(bool) (ElementFragmentAlgorithm.C:289)
test:moving_interface.moving_interface: ==32459==    by 0x4A93D70: XFEM::cutMeshWithEFA(NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:1067)
test:moving_interface.moving_interface: ==32459==    by 0x4A9898D: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:262)
test:moving_interface.moving_interface: ==32459==    by 0x55210BC: FEProblemBase::updateMeshXFEM() (FEProblemBase.C:6021)
test:moving_interface.moving_interface: ==32459==    by 0x5AB81C0: PicardSolve::solveStep(double, double&, double, double&, bool, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) (PicardSolve.C:457)
test:moving_interface.moving_interface: ==32459==    by 0x5ABB9F7: PicardSolve::solve() (PicardSolve.C:233)
test:moving_interface.moving_interface: ==32459==    by 0x5BF1D47: TimeStepper::step() (TimeStepper.C:163)
test:moving_interface.moving_interface: ==32459==    by 0x5AB6F22: Transient::takeStep(double) (Transient.C:417)
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== 102,480 (1,280 direct, 101,200 indirect) bytes in 4 blocks are definitely lost in loss record 152 of 153
test:moving_interface.moving_interface: ==32459==    at 0x483AE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (new_allocator.h:114)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (alloc_traits.h:444)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<EFAElement2D, std::allocator<EFAElement2D>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_count<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:677)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:1344)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:359)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate_shared<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:702)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: make_shared<EFAElement2D, unsigned int&, unsigned int&> (shared_ptr.h:718)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: ElementFragmentAlgorithm::add2DElement(std::vector<unsigned int, std::allocator<unsigned int> >, unsigned int) (ElementFragmentAlgorithm.C:84)
test:moving_interface.moving_interface: ==32459==    by 0x4A854B9: XFEM::buildEFAMesh() (XFEM.C:331)
test:moving_interface.moving_interface: ==32459==    by 0x4A9899F: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:266)
test:moving_interface.moving_interface: ==32459==    by 0x55210BC: FEProblemBase::updateMeshXFEM() (FEProblemBase.C:6021)
test:moving_interface.moving_interface: ==32459==    by 0x5AB81C0: PicardSolve::solveStep(double, double&, double, double&, bool, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) (PicardSolve.C:457)
test:moving_interface.moving_interface: ==32459==    by 0x5ABB9F7: PicardSolve::solve() (PicardSolve.C:233)
test:moving_interface.moving_interface: ==32459==    by 0x5BF1D47: TimeStepper::step() (TimeStepper.C:163)
test:moving_interface.moving_interface: ==32459==    by 0x5AB6F22: Transient::takeStep(double) (Transient.C:417)
test:moving_interface.moving_interface: ==32459==    by 0x5AB731E: Transient::execute() (Transient.C:309)
test:moving_interface.moving_interface: ==32459==    by 0x61CDFA3: MooseApp::executeExecutioner() (MooseApp.C:940)
test:moving_interface.moving_interface: ==32459==    by 0x61CE08A: MooseApp::run() (MooseApp.C:1067)
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== 146,600 (640 direct, 145,960 indirect) bytes in 2 blocks are definitely lost in loss record 153 of 153
test:moving_interface.moving_interface: ==32459==    at 0x483AE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (new_allocator.h:114)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate (alloc_traits.h:444)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<EFAElement2D, std::allocator<EFAElement2D>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:97)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_count<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:677)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: __shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr_base.h:1344)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: shared_ptr<std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:359)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: allocate_shared<EFAElement2D, std::allocator<EFAElement2D>, unsigned int&, unsigned int&> (shared_ptr.h:702)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: make_shared<EFAElement2D, unsigned int&, unsigned int&> (shared_ptr.h:718)
test:moving_interface.moving_interface: ==32459==    by 0x49C0571: ElementFragmentAlgorithm::add2DElement(std::vector<unsigned int, std::allocator<unsigned int> >, unsigned int) (ElementFragmentAlgorithm.C:84)
test:moving_interface.moving_interface: ==32459==    by 0x4A854B9: XFEM::buildEFAMesh() (XFEM.C:331)
test:moving_interface.moving_interface: ==32459==    by 0x4A9892B: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&) (XFEM.C:255)
test:moving_interface.moving_interface: ==32459==    by 0x55210BC: FEProblemBase::updateMeshXFEM() (FEProblemBase.C:6021)
test:moving_interface.moving_interface: ==32459==    by 0x5AB81C0: PicardSolve::solveStep(double, double&, double, double&, bool, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) (PicardSolve.C:457)
test:moving_interface.moving_interface: ==32459==    by 0x5ABB9F7: PicardSolve::solve() (PicardSolve.C:233)
test:moving_interface.moving_interface: ==32459==    by 0x5BF1D47: TimeStepper::step() (TimeStepper.C:163)
test:moving_interface.moving_interface: ==32459==    by 0x5AB6F22: Transient::takeStep(double) (Transient.C:417)
test:moving_interface.moving_interface: ==32459==    by 0x5AB731E: Transient::execute() (Transient.C:309)
test:moving_interface.moving_interface: ==32459==    by 0x61CDFA3: MooseApp::executeExecutioner() (MooseApp.C:940)
test:moving_interface.moving_interface: ==32459==    by 0x61CE08A: MooseApp::run() (MooseApp.C:1067)
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== LEAK SUMMARY:
test:moving_interface.moving_interface: ==32459==    definitely lost: 2,379 bytes in 12 blocks
test:moving_interface.moving_interface: ==32459==    indirectly lost: 410,600 bytes in 5,313 blocks
test:moving_interface.moving_interface: ==32459==      possibly lost: 0 bytes in 0 blocks
test:moving_interface.moving_interface: ==32459==    still reachable: 126,863 bytes in 17 blocks
test:moving_interface.moving_interface: ==32459==         suppressed: 2,481 bytes in 54 blocks
test:moving_interface.moving_interface: ==32459== Reachable blocks (those to which a pointer was found) are not shown.
test:moving_interface.moving_interface: ==32459== To see them, rerun with: --leak-check=full --show-leak-kinds=all
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 4 from 4)
test:moving_interface.moving_interface: --32459-- 
test:moving_interface.moving_interface: --32459-- used_suppression:     52 openmpi_mpi_init_leak /home/lindad/projects2/moose/python/TestHarness/suppressions/errors.supp:51 suppressed: 2,481 bytes in 54 blocks
test:moving_interface.moving_interface: ==32459== 
test:moving_interface.moving_interface: ==32459== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 4 from 4)
```

**Comment by bwspenc** [comment]
The scope of this PR has changed. I'm ready to drop the idea of moving xfem over to using shared pointers. I've fixed the original memory leak that motivated me to go down that path, and despite having spent quite a while chasing down the remaining memory leaks, I'm still seeing a lot of memory leaks when I run my code that has been converted to shared pointers with valgrind. It looks like we have to be very disciplined about when to use shared_ptr vs weak_ptr. Getting that straight seems to be more difficult than keeping track of which object should delete which dynamically allocated objects, which we have a good handle on.

Anyway, I removed all of the shared_ptr conversion from this PR, so this is just a small amount of cleanup. It's passed all the valgrind tests, so I think it is good to go.

**Comment by lindsayad** [comment]
Is this rebased on your other xfem changes?

**Comment by bwspenc** [comment]
@lindsayad I guess it wasn't since those were only in devel. I just rebased against next to verify that there weren't any conflicts (there weren't), and pushed an update.

**Review by jiangwen84 — APPROVED** [review]
Looks good.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
