### PR TITLE
Remove auxvars for PenetrationInfo and go back to restartable data

### PR DESCRIPTION
**Pull request by shartibartfast**
Removes the aux variables for the stateful PenetrationInfo variables and reinstates the restartable data in PenetrationLocator. Also simplifies the node capture logic, removes unused member data in PenetrationInfo and PenetrationLocator, and reduces the number of redundant calls to update the contact force in MechanicalContactConstraint.

Fixes several tests that fail recovery in modules/combined.

The sliding block test was re-golded due to minor differences (<1%).

### CODE REVIEW

**Comment by permcody** [comment]
MOOSE test will report a failure in the apps - ignore it. We'll invalidate after yak is all fixed up again.

**Comment by friedmud** [comment]
Wow - what happened?

**Comment by friedmud** [comment]
(Note: I'm not asking to criticize... I'm just out of the loop.  You don't need to explain everything... just a quick thing to satisfy my curiosity ;-)

**Comment by friedmud** [comment]
Nevermind: I found it: #5060

**Comment by shanestafford** [comment]
Closes #5060

**Comment by permcody** [comment]
@shanestafford you may want to stop down in 109 and have a discussion with @friedmud, @bwspenc, and myself about this PR. Derek expressed concern about returning to the PenetrationInfo method over the AuxVariable method. The later may be easier to use if we plan to turn on adaptivity. Let's have a chat and then make a decision about whether this should be merged.

**Comment by permcody** [comment]
I verified that the contact tests are passing with recover using this branch. I still think we should have a discussion about the AuxVariable approach vs PenetrationInfo approach. We may merge this for the current problem but eventually we'll want something better for adaptivity.

**Pull request merged**
