### PR TITLE
Added test for exception with save_in

### LINKED ISSUE #10485: PETSC error if MooseException is used with save_in
## Rationale
`throw MooseException("entering the danger zone...go back!")` is a great way to terminate a timestep during a run. However, if an exception is thrown during a residual solve, and `save_in` is used at the same time, PETSC throws an error. I know that the `save_in` function is going away, but I'm not sure when that'll be. The work around is to use `return std::numeric_limits<Real>::quiet_NaN();` as originally suggested by @andrsd in #10166, and turn the error into a warning. Not a huge priority, but perhaps it'll help others avoid the same problems.

## Description
If `throw MooseException("some reason")` is used at the same time as `save_in`, PETSC returns the error:
```
 Cutting timestep.
 Solve Did NOT Converge!
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Object is in wrong state
[0]PETSC ERROR: Not for unassembled vector
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.7.6, Apr, 24, 2017 
[0]PETSC ERROR: ../../../marmot-opt on a arch-darwin-c-opt named hdl1513265.lanl.gov by topher Tue Jan  9 13:32:47 2018
[0]PETSC ERROR: Configure options --prefix=/opt/moose/petsc-3.7.6/mpich-3.2_clang-5.0.0-opt --download-hypre=1 --with-ssl=0 --with-debugging=no --with-pic=1 --with-shared-libraries=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-fblaslapack=1 --download-metis=1 --download-parmetis=1 --download-superlu_dist=1 --download-mumps=1 --download-scalapack=1 -CC=mpicc -CXX=mpicxx -FC=mpif90 -F77=mpif77 -F90=mpif90 -CFLAGS="-fPIC -fopenmp" -CXXFLAGS="-fPIC -fopenmp" -FFLAGS="-fPIC -fopenmp" -FCFLAGS="-fPIC -fopenmp" -F90FLAGS="-fPIC -fopenmp" -F77FLAGS="-fPIC -fopenmp"
[0]PETSC ERROR: #1 VecCopy() line 1638 in /private/var/folders/hl/r7dqj_2d48s322zhyg_b05z00000gn/T/moose_package_build_temp/petsc-default-mpich-clang-opt/petsc-3.7.6/src/vec/vec/interface/vector.c
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

## Impact
This will make the use of `MooseException` applicable to kernels while using `save_in`.

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #10485

### CODE REVIEW

**Comment by dschwen** [comment]
Have you verified that this fails without the commit from #11526?

**Comment by tophmatthews** [comment]
grrr...it seems to be working before that commit too...let me dig back a little further.

**Comment by dschwen** [comment]
Ha. Yeah, I tried to come up with a good test and tabled that effort for now. Best of luck though. :-)

**Comment by tophmatthews** [comment]
@dschwen yeah...I give up. I distinctly remember getting the error I describe in #10485, but I can't seem to reproduce it here.

**Pull request closed without merging**
