### PR TITLE
Revert "CSVDiff to SchemaDiff"

### PR DESCRIPTION
**Pull request by loganharbour**
Reverts idaholab/moose#24633

See https://github.com/idaholab/moose/issues/24828

### CODE REVIEW

**Review by milljm — APPROVED** [review]

**Comment by loganharbour** [comment]
We will just revert this for now @zachmprince unless you're trying to fix it. @milljm has an idea, will get to it tomorrow

**Comment by loganharbour** [comment]
Merging despite failure as this is a significant bug fix

**Comment by milljm** [comment]
There was a lot wrong with it 😄 

The incoming PR: https://github.com/idaholab/moose/pull/24854

You're welcome to pull that real quick, and verify if _that_ works.

**Comment by dzheng26** [comment]
> There was a lot wrong with it 😄
> 
> The incoming PR: #24854
> 
> You're welcome to pull that real quick, and verify if _that_ works.

I pulled and tested your branch. It works for my case. Great work!

Only thing I noticed is the print out of "Step". Since moose output is from step 0, the CSVDiff "Step 2" is actually Moose step 1. It maybe a little confusing. Maybe using "Step" for Moose step and "Row" for data row in csv file?

```
Relative Error Tolorance:	5.5e-06
Absolute Zero:		1e-10
Column 3, Step 2:		gold: 1.00000050e+00, result: 2.00000050e+00
				CSVDIFF Detected:
relative diff: 9.99999500e-01
```

**Comment by milljm** [comment]
Good call, I'll fix that. Along with the silly looking formatting...

```bash
cd moose/test
./run_tests -i schemadiff --re=schema_csvdiff_relative_override
```

Ideal print out:
```bash
: Running csvdiff
: Gold File: /Users/milljm/projects/moose/test/tests/test_harness/gold/csvdiff_spec_override_specific_floor_out.csv
: Results File: /Users/milljm/projects/moose/test/tests/test_harness/csvdiff_spec_override_specific_floor_out.csv
: Relative Error Tolorance:	0.1
: Absolute Zero:		1e-10
: Column 4, Step 1:		gold: 9.00000000e-02, result: 7.99146692e-02
: DIFF Detected:		relative diff: 1.12059231e-01
```

where results file is:
```pre
time,x_field,y_field,z_field
0,0,0,0
0.1,0.0063860971983041,0.00050710442694632,0.079914669200048
0.2,0.022873266268822,0.0024626580675746,0.18308191355809
0.3,0.047999984682465,0.0066786917783011,0.27374948672607
0.4,0.078210261081996,0.013463269762465,0.34586265131286
0.5,0.11031382785127,0.022622885713097,0.40253012555247
```

**Comment by dzheng26** [comment]
> ```shell
> : Running csvdiff
> : Gold File: /Users/milljm/projects/moose/test/tests/test_harness/gold/csvdiff_spec_override_specific_floor_out.csv
> : Results File: /Users/milljm/projects/moose/test/tests/test_harness/csvdiff_spec_override_specific_floor_out.csv
> : Relative Error Tolorance:	0.1
> : Absolute Zero:		1e-10
> : Column 4, Step 1:		gold: 9.00000000e-02, result: 7.99146692e-02
> : DIFF Detected:		relative diff: 1.12059231e-01
> ```
> 
Looks good!

**Pull request merged**
