### PR TITLE
Avoid stopping the calculation, even in devel mode, on harmonic interpolation issues

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #21923

I m hitting this in the nonlinear convergence process in devel mode.
The opt solution seems correct so my guess is that this is a transient issue happening during the nonlienar iterations

### CODE REVIEW

**Comment by grmnptr** [comment]
Yeah, I am not sure if I like this. The assert is there because the harmonic mean of nonpositive numbers is undefined. Why don't you just use regular mean? What is the problem at hand?

**Comment by grmnptr** [comment]
I suppose I agree with the changes in a sense that if we have negative only, we should still be able to use.

**Comment by GiudGiud** [comment]
I don’t want to be changing the interpolation method because the result is bad for one iteration. 

The problem was the FHR multiphysics but it seems to have stopped presenting itself after a checkpoint update. 

in general we avoid erroring in these situations because it s a transient issue. A mooseException is a little better but a warning would suffice. 

I promise it won’t be “do once” in a couple months when we have that capability

**Comment by GiudGiud** [comment]
We dont but this is not unique to this PR.
I can remove the DoOnce if you prefer to be continually informed

**Review by grmnptr — APPROVED** [review]

**Pull request merged**
