### PR TITLE
Create PorousFlowHeatMassTransfer Kernel

### LINKED ISSUE #11050: Create PorousFlowHeatMassTransfer Kernel
## Rationale

We need a Kernel that transfers heat or mass from one Variable to another.  This is useful for simplified modelling of precipitation/dissolution, where the Variable is the concentration.  It is also useful for transferring heat from a fracture to a surrounding matrix.

## Description

```
Residual = r (u - v)
```
where r is the ```transfer_coefficient``` (Real, not range-checked), u is the variable (typically temperature, porepressure or mass-fraction), and v is a coupledVariable (typically constant-in-time AuxVariable, or a fracture/matrix temperature in the above fracture-matrix example).

This needs to compute the derivatives wrt u and v.

I don't think we have to worry about any lumping-to-the nodes: v is just a ```coupledValue``` (not ```coupledNodalValue```) and we evaluate at ordinary quadpoints.

Later we might want to optionally pre-multiply by mobility in a certain direction, relative permeability, enthalpy, density and/or mass fraction, just like in PorousFlowSink, but let's not do this at the moment because it's not needed right now.

## Impact

Ability to model heat or mass transfer between different components of a simulation.

### PR DESCRIPTION
**Pull request by philippschaedle**
Residual = r (u - v)
Kernel that transfers heat or mass from one Variable to another. This is useful for simplified modelling of precipitation/dissolution, where the Variable is the concentration. It is also useful for transferring heat from a fracture to a surrounding matrix.

closes #11050

### CODE REVIEW

**Comment by philippschaedle** [comment]
This might need to be improved to make the transfer coefficient r depend on an auxvariable. Further this may depend on the element volume.

**Comment by permcody** [comment]
@philippschaedle - This is been sitting idle for awhile. It looks like you may have just forgotten to commit a required file, and of course provide a little bit of documentation. We typically close stale PRs after 30-days. Let us know if you need some help finishing this up.

**Comment by philippschaedle** [comment]
@permcody - Thanks for that hint! I got basically all the files for testing and documentation. However, I am still working on a more detailed documentation which should go to the fracture example of the porous flow module. This documentation should compare the results based on the transfer function in a mixed dimensional domain to an explicit model without the transfer. Unfortunately, the results do not yet agree. 

For now I could also just add a short documentation which says how to use the kernel and add the more detailed one later. I could do that tonight or tomorrow. Do you think that is fine?

Sorry for that delay.

**Comment by permcody** [comment]
There's not problem with the delay. Just wanted to let you know that we close these after 30 days if they sit idle.

**Comment by permcody** [comment]
Closing per the 30-day limit. Please feel free to reopen when you get a chance to work on this more. Thanks!

**Pull request closed without merging**
