### PR TITLE
Fix function symbols in the diffusion kernel docs

### PR DESCRIPTION
**Pull request by nmnobre**
## Bug description
The function symbols in the diff kernel doco are not correct in the equations

## How to reproduce
Look at the Diffusion kernel documentation page

## Impact
Minor, unsightly mistake

Minor typo I spotted while reading the docs.

-N

### CODE REVIEW

**Comment by GiudGiud** [comment]
Dont think it s a typo. You write the Residual as `_grad_u[_qp] _grad_psi[_qp]` from the integration by parts. 
If we write 
u as sum u_j phi_j with phi being the shape functions 
then
```
grad_u = sum u_j grad_phi_j
```
Then we want to get the Jacobian so we compute:
```
J_ij = partial R_i / partial u_j = sum [ partial  (u_j  grad_phi_j ) / partial u_j ]  _grad_psi
J_ij = grad_phi_j   _grad_psi. (did not write i index in)
```

If you agree on all that, then are you making the point that Diffusion is for the CG method so it s the same basis for shape and trial functions? Diffusion.C could be used for DG with an extra DGkernel for the internal sides I think

**Comment by nmnobre** [comment]
I agree with everything you've written. :) 

But if you notice I changed the symbol for the test function, indexed by i, not the symbol for the trial function, indexed by j. So, if anything, we could also change the symbol for the trial function (to phi_j) to underline the fact that they need not match? But I wasn't particularly bothered by that. :)

**Comment by GiudGiud** [comment]
oh you're saying it should be
```
(\nabla \phi_j, \nabla \psi_i).
```

**Comment by nmnobre** [comment]
> oh you're saying it should be
> 
> ```
> 
> (\nabla \phi_j, \nabla \psi_i).
> 
> ```

I'm saying it should definitely be psi_i, as I've suggested in the committed changes, i.e. the test functions are named psi.

I'm happy with keeping psi_j, unless you want to reiterate they may be different sets of functions, in which case we can change it to phi_j.

**Comment by GiudGiud** [comment]
Let's go with that then:
```
(\nabla \psi_i, \nabla \phi_j)
```
it keeps the "expected" ordering of the term (from the equation above) and the same notation consistent. 
Good catch!

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thanks for the fix!

**Pull request merged**
