### PR TITLE
Removing PrintAction and tests

### LINKED ISSUE #6822: Fix PrintMaterials test
### Description of the enhancement or error report

The actions/meta_action/print_materials test fails occasionally. After looking at the source code it becomes apparent as to why. The order in which the information is written to the output file is based on the set order of the pointers! This is very wrong. This test seems like a bad idea.

```
    for (std::set<const AddMaterialAction *>::iterator it = actions.begin();
         it != actions.end(); ++it)
      os << i++ << "," << map_type[(*it)->getMooseObjectType()] << std::endl;
    os.close();
```

### Rationale for the enhancement or information for reproducing the error

Run it thousands of times and it _might_ fail.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Just this test

### PR DESCRIPTION
**Pull request by permcody**
closes #6822

I'm proposing that we remove this Action and associated tests. I really don't understand the purpose of this test and we've established that it's unreliable anyway. The test centers around these lines:

```
    std::set<const AddMaterialAction *> actions = _awh.getActions<AddMaterialAction>();

    std::map<std::string, unsigned int> map_type;
    map_type["GenericConstantMaterial"] = 100;
    map_type["CoupledMaterial"] = 888;

    std::ofstream os(getParam<FileName>("csv_file").c_str());
    os << "name_id,type_id" << std::endl;
    unsigned int i=0;
    for (std::set<const AddMaterialAction *>::iterator it = actions.begin();
         it != actions.end(); ++it)
      os << i++ << "," << map_type[(*it)->getMooseObjectType()] << std::endl;
    os.close();
```

It's not clear what those constants mean or why they are there. The interfaces used in this section of code are used elsewhere so I just don't understand the purpose of this test. I suggest that we implement something else if there is a need.

### CODE REVIEW

**Comment by permcody** [comment]
Also self-nominating for PR of the Day (PROTD)

**Comment by permcody** [comment]
@YaqiWang - Please comment if you feel this test needs to stay or there's some functionality here we need to keep.

**Comment by YaqiWang** [comment]
I do not mind that It goes away. Its purpose is to test `ActionWarehouse::getActions<T>()`. The only issue is that somebody could break the function without knowing it without testing moose against all applications (Rattlesnake is using the function).

**Comment by permcody** [comment]
I propose we merge this. I opened a new ticket #6921.

**Pull request merged**
