### PR TITLE
Allow libmesh to condense all variables into one group if possible

### LINKED ISSUE #15231: Allow libmesh to put all variables into a single group if possible
## Reason

Minimizing the number of groups can help libmesh indexing, and also enables
some preconditioning optimization.

## Design

Remove `system().identify_variable_groups(false);`.

Try to fix whatever issues we may have faster this deletion of this line of code.

## Impact
None.

### PR DESCRIPTION
**Pull request by fdkong**
Closes #15231 

Let us check how many tests will fail with this deletion. And work a right way to fix the issues.

### CODE REVIEW

**Comment by roystgnr** [comment]
Well, those test failures aren't related to this PR, but they're still pretty dumbfounding.  I swear I tested those!  #15200 fixed them!

**Comment by fdkong** [comment]
> Well, those test failures aren't related to this PR, but they're still pretty dumbfounding. I swear I tested those! #15200 fixed them!

Sorry, Roy. Your fix might not be in moose-devel before I added this PR. It should be in moose-devel right now, and let me validate if it works.

**Comment by fdkong** [comment]
@roystgnr Looks like we are fine?

**Comment by fdkong** [comment]
What else we need to check?

**Comment by roystgnr** [comment]
Looks like we're good to go.  I'd actually be happy seeing this PR merged as-is, though since it's including a libMesh update it should probably get a closer look by others first.  At the very least though you could take out the libMesh update, leave the first commit, and then have MOOSE in a state where it still works fine with the official libMesh hash but it's also easy to get block_size working the way you want it by using a newer libMesh.

**Comment by fdkong** [comment]
> Looks like we're good to go. I'd actually be happy seeing this PR merged as-is, though since it's including a libMesh update it should probably get a closer look by others first. At the very least though you could take out the libMesh update, leave the first commit, and then have MOOSE in a state where it still works fine with the official libMesh hash but it's also easy to get block_size working the way you want it by using a newer libMesh.

libmesh update is here https://github.com/idaholab/moose/pull/15182

I will take out of libmesh update

**Review by lindsayad — APPROVED** [review]
I  didn't pay a whole lot of attention to the chatter on slack, but I'm assuming @friedmud and @YaqiWang are good with this

**Comment by fdkong** [comment]
@YaqiWang will be excited about this PR since he wants to see this picture:


MicrosoftTeams-image

**Comment by lindsayad** [comment]
Oh yes, Horrible Mult-Grid!! :-)

**Pull request merged**
