### PR TITLE
OversampleOutput fixes

### PR DESCRIPTION
**Pull request by roystgnr**
This solves the correctness issues that were causing OversampleOutput to fail with DistributedMesh, which as a side benefit allows us to strip out a chunk of code and avoid an unnecessary solution serialization.

This fixes --distributed-mesh test failures with ics/function_ic.spline_function for me.

We're not done with #1500 yet but so far these bugs are turning out to be easier to fix than I'd feared.

### CODE REVIEW

**Comment by roystgnr** [comment]
Hmm... or maybe I spoke too soon.  I still believe this fix is correct, but it must not be sufficient; it doesn't resolve the outputs/oversample.adapt --distributed-mesh failures yet.

**Comment by roystgnr** [comment]
Yeah, this isn't going to work as-is.  Apparently the policy is to *not* reconstruct or adapt the oversample mesh when the original mesh adapts?  In that case we'll completely lose any partitioning synchronization as soon as the original mesh gets repartitioned.  That's fixable in theory, but not nearly this easily.

**Comment by friedmud** [comment]
We can change the way oversample works.  I would definitely be for making
it follow the partitioning of the original mesh... so as the partitioning
of the original mesh changes we change the partitioning of the oversample
mesh to match.

**Comment by permcody** [comment]
Agreed, we'll rethink this capability. We'll just mark it as "replicated
only" in the meantime.

**Comment by roystgnr** [comment]
Oh, "follow the partitioning of the original mesh" is definitely the way to go.  I can actually set up a GhostingFunctor that would do that on the fly, but not easily, and I can't think of any other way to sync the partitioning that doesn't rely on either making the oversampling grid replicated or on all-to-all communication.

**Comment by friedmud** [comment]
The easiest way to sync the partitioning is just to hijack the
partitioner.  Just create a partitioner that has a reference to the other
mesh and whenever the oversample mesh needs to be repartitioned what it
does is it goes and grabs the partitioning for the top level (most parent)
elements in the original mesh and applies it to the oversample mesh.

**Comment by permcody** [comment]
Yes. We do something very similar for the reference and displaced meshes
that moose already has. I wonder though, how many meshes should we have? It
seems like we could eventually engineer a system where all these various
systems can share a single mesh where we apply displacements, over
sampling, and other transforms to the main mesh on demand. Could save us
more memory.

**Pull request closed without merging**
