### PR TITLE
A VI example

### LINKED ISSUE #12041: An example to demonstrate how to use VI
## Rationale
There is a VI solver in PETSc, but we do not have a correct example demonstrating how to use it.

## Description

Add a simple example to show users how to use VI solver which can bound a variable. 

## Impact
People who is interested in constrained nonlinear problems.

### PR DESCRIPTION
**Pull request by fdkong**
The original one did not use VI at all. We made this example actually use
a VI nonlinear solver for constrained nonlinear problems

Closes #12041

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
Needs documentation

**Comment by hugary1995** [comment]
@fdkong so is it by design that you want to demonstrate the case that the vi solver overrides the DirichletBC?

**Comment by andrsd** [comment]
That's a good point. If users set their BCs outside of permissible range (which is determined by the limits), does it mean they are solving an incorrect problem? 

How about using this instead? Solve diffusion with left and right BC = 0, but so that the exact solution has some minimum and maximum, let's say -1 and 1 (the function could be sin-like).  Then, impose the upper and lower bounds to be -0.5 and +0.5 and we should get some sin with some cut-off values...

**Comment by fdkong** [comment]
Good points.

It is a bad example and misleading, and I should redesign an example.  At the current implementation, users are responsible  to set consistent boundary conditions. Users can also set a right Aux to reserve whatever they want.

**Comment by fdkong** [comment]
> How about using this instead? Solve diffusion with left and right BC = 0, but so that the exact solution has some minimum and maximum, let's say -1 and 1 (the function could be sin-like). Then, impose the upper and lower bounds to be -0.5 and +0.5 and we should get some sin with some cut-off values...

I am thinking about some real constrained problems. I will try to search some example

**Comment by friedmud** [comment]
I like @andrsd 's idea...

**Comment by andfranklin** [comment]
I've created an example problem per @andrsd suggestion:

```
###############################################################################
# This is a constrained diffusion problem with a known solution.
#
# The method of manufactured solutions was used to derive the
# unconstrained solution:
#
# u(x) = sin(2 pi x)
#
# The solution variable should be constrained to be between -0.5 and 0.5.
###############################################################################

[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 4
  boundary_id = '1 2'
  boundary_name = 'left right'
  second_order = true
  elem_type = EDGE3
[]

[Variables]
  [./u]
    order = SECOND
    family = LAGRANGE
  [../]
[]

[AuxVariables]
  [./u_unconstrained]
    order = SECOND
    family = LAGRANGE
  [../]

  [./u_bound]
    order = SECOND
    family = LAGRANGE
  [../]
[]

[Functions]
  [./u_unconstrained]
    type = ParsedFunction
    value = 'sin(2.0*pi*x)'
  [../]
[]

[Kernels]
  [./diff]
    type = Diffusion
    variable = u
  [../]

  [./rhs]
    type = BodyForce
    function = '4.0*pi*pi*sin(2.0*pi*x)'
    variable = 'u'
  [../]
[]

[AuxKernels]
  [./u_unconstrained_kernel]
    type = FunctionAux
    function = 'u_unconstrained'
    variable = 'u_unconstrained'
  [../]
[]

[Bounds]
  [./u_bounds]
    type = BoundsAux
    variable = u_bound
    bounded_variable = u
    upper = 0.5
    lower = -0.5
  [../]
[]

[BCs]
  active = 'left right'

  [./left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0.0
  [../]

  [./right]
    type = DirichletBC
    variable = u
    boundary = right
    value = 0.0
  [../]
[]

[Executioner]
  type = Steady
  solve_type = 'NEWTON'
  petsc_options_iname = '-snes_type'
  petsc_options_value = 'vinewtonrsls'
[]

[Outputs]
  [./exodus_oversample]
     type = Exodus
     refinements = 4
     file_base = 'constrained'
  [../]
[]
```

Here is the output:

constraint_problem

The function over/under-shoots the constraint because the constrains are applied directly to the nodal values and not the function. This results in [Runge's Phenomena](https://en.wikipedia.org/wiki/Runge%27s_phenomenon).

**Comment by hugary1995** [comment]
I am afraid that this example is not a well-posed one. You are essentially solving for a constraint ode:
u,xx + b = 0
-0.5 < u < 0.5
and I don't think there exist a solution to this system, also the solution you got from the input file does not satisfy the underlying ode.

**Comment by andfranklin** [comment]
Can you explain more what you mean by not well-posed? Or better yet, could you propose a well-posed problem?

**Comment by hugary1995** [comment]
How about this one:
u,x - ux = 0
which has two solutions
u = 0
u = exp(0.5*x^2)
Therefore, by defining different bounds we can obtain different solutions.

**Comment by hugary1995** [comment]
Sorry, I take back my words -- there is a solution to this constraint ode in weak sense. It might be better to just manufacture a second order solution, i.e.

> -u,xx + 2 = 0
> u(0) = 0
> s.t. -1<u<0

which has no Gibbs phenomenon.

then if you impose 

> -0.5<u<0

 you will get a different solution.

I'm commenting on this PR because I am using this VI solver and I just want to make sure it will be continuously supported by MOOSE. Thanks.

**Comment by andfranklin** [comment]
Unless I'm missing something I don't think this problem is well-posed because it does not have a unique solution. Without loss of generality let's assume `0 < x < 1`. Then any function `u(x) = x * (x + c)` satisfies this problem for `-1 > c > -2`. [Plots](https://www.wolframalpha.com/input/?i=plot+x+*+(x+-+1)+and++x+*+(x+-+1.25)+and++x+*+(x+-+1.5)+and++x+*+(x+-+1.75)+and++x+*+(x+-+2)++for+x%3D0+to+1).

**Comment by hugary1995** [comment]
You are right. My question is is the VI solver variational or does it simply project the solution onto the bounds?

On Oct 20, 2018 6:48 PM, Andrew Franklin <notifications@github.com> wrote:

Unless I'm missing something I don't think this problem is well-posed because it does not have a unique solution. Without loss of generality let's assume 0 < x < 1. Then any function u(x) = x * (x + c) satisfies this problem for -1 > c > -2. Plots<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.wolframalpha.com_input_-3Fi-3Dplot-2Bx-2B-2A-2B-28x-2B-2D-2B1-29-2Band-2B-2Bx-2B-2A-2B-28x-2B-2D-2B1.25-29-2Band-2B-2Bx-2B-2A-2B-28x-2B-2D-2B1.5-29-2Band-2B-2Bx-2B-2A-2B-28x-2B-2D-2B1.75-29-2Band-2B-2Bx-2B-2A-2B-28x-2B-2D-2B2-29-2B-2Bfor-2Bx-253D0-2Bto-2B1&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=qXkGFNeMh3vJqsspu4VMkw&m=yK0xmbsi1imW65uVSdndx1GdZOG2qY0SzHEz2_KE0e4&s=w1ZGOFcAarYAfX2HH_Gx4YF96zicBwRhtzsed_m9gCU&e=>.

**Comment by andfranklin** [comment]
As I understand it, the the Active-Set Semismooth Method is being used to solve the finite-dimensional, nonlinear complementarity problem. This does **not** project the solution onto the bounds. In fact, it does not guarantee that the iterate remains within the [[ref](https://www.mcs.anl.gov/~tmunson/papers/semismooth.pdf)].

When running the test case with 32 elements instead of 4 moose produces the following:

image

It appears that the Active-Set Semismooth Method perturbs the physics if the solution is within bounds in order to satisfy the bounds. I suspect that the physics perturbation is likely a function of the NCP function. PETSc is hard wired to use the Fisher-Burmeister NCP function. Maybe different NCP functions would be less disruptive?

To simply project the solution onto the bounds I believe that the Reduced-Space Method would need to be used. Maybe @fdkong could comment.

**Comment by andfranklin** [comment]
Just had a discussion with @fdkong. The above results were produced using  Reduced-Space Method.  The Active-Set Semismooth Method can be used by setting:

```
petsc_options_value = 'vinewtonssls'
```

in the Executioner block. The solutions of each method are identical in the eyeball-norm. The perceived physics distortion is **not** a result of the NCP function.

**Comment by friedmud** [comment]
The results look "correct" to me.  My conjecture is that the solution that
has come out gives the smallest residual to the unconstrained problem while
still meeting the constraints.  I'm hoping that @Fande Kong
<fdkong.jd@gmail.com> can actually prove this...

Derek

**Comment by fdkong** [comment]
perfect_solution

`Residual norm:  10.1335`

visolution

`Residual norm:   2.47974`

**Comment by friedmud** [comment]
Yep - so the "curvier" one that looks further away from the analytical
solution... is actually better...

**Comment by hugary1995** [comment]
How do I interpret the residual norm output from MOOSE then? Is it the residual norm of the inactive set where the constraint isn't enforced?  For example, if I set a residual tolerance of 10e-6 in my input file, after the solve converges the actual residual could be higher than 10e-6 -- if this is the case I'll have to be more cautious when I use this solver.

**Comment by friedmud** [comment]
With VI it solves a modified set of equations: so when you hit '0' you've
satisfied both the PDE and the constraint.  Obviously, the solution that is
found is not the solution to the PDE alone... and therefore there will be
some "residual" if you were to take that solution and run it through the
residual calculation with just the PDE.  The size of that "nonfit" is
representative of impact the constraint had on the solution.  If the
constraint didn't change things much then that "unconstrained" residual
will still be small... if it had a large impact then the unconstrained
residual will be larger.

Note: Fande has done extra work here to get to the "unconstrained
residual": what's output by MOOSE by default is the "constrained"
residual... ie the one you're trying to force to zero that includes the
effects of the constraints.

You say "actual residual" in your post... but what do you mean by that?
What is the "actual" residual to you?

Derek

**Comment by hugary1995** [comment]
Thanks Derek that makes sense. I was referring to unconstrained residual. Now I get that the residual output by MOOSE is with respect to the modified problem, i.e.
`modified residual = original residual + FB functional`
where `FB function = a + b - sqrt(a^2+b^2)`
what confused me is that I thought when modified residual -> 0, FB functional has to vanish... then the modified residual -> original residual. Now it seems that I misunderstood.

**Comment by fdkong** [comment]
The VI is designed, again, for complementary problems that are described as:

F(x)>=0, x>=0 and xF(x) = 0. (1)

VI is simply to reformulate this problem and then use a regular Newton to solve the reformed function. One example to reformulate the problem is:

F(x) + x - \sqrt(x^2 + F(x)^2) = 0. (2)

You can easily see that (2) is equivalent to (1). If x is active, then F(x) could be an arbitrary number. If F(x) is active, then x could be an arbitrary number, however we always project the solution onto bounds so that this situation is actually avoided.  x is simply composed of an active part x_a and an inactive x_i, that is,  x = {x_a, x_i}. F(x) corresponding to x_a is denoted as F_a(x), and we have a similar definition for F_i(x) as well.

The residual used during solving process is ||F_i(x)||_2 because we can not do anything to F_a(x) that is already satisfied (2), that is, x=0 and F(x) can be arbitrary. The actual residual for PDE is ||F_i(x)+F_a(x)||_2, so that it is can be arbitrarily large even though ||F_i(x)|| is zero.  

If PDE has an unique solution within the constrained domain, then you simply should not use VI, instead, a regular Newton with a good initial guess should give you what you want. 

Therefore, @hugary1995  If you have set residual (that is defined as ||F_i(x)||_2) in Executioner block as 1e-6, the actual  residual (defined as ||F(x)||_2) can be anything, e.g. 1e+100, 1e+10, or 1e-10. I still do not understand why you think ||F(x)||_2 should be something small when using VI.   You may tell us what are you doing? And then you may need a different solver?

**Comment by fdkong** [comment]
> Thanks Derek that makes sense. I was referring to unconstrained residual. Now I get that the residual output by MOOSE is with respect to the modified problem, i.e.
> `modified residual = original residual + FB functional`

The moose output residual is ||F_i(x)||_2. 


> where `FB function = a + b - sqrt(a^2+b^2)`
> what confused me is that I thought when modified residual -> 0, FB functional has to vanish... then the modified residual -> original residual. Now it seems that I misunderstood.

**Comment by fdkong** [comment]
Another simple way to understand this is that: 

The output residual is that of (2). (2) becomes small does not imply that F(x) will be small.

**Comment by hugary1995** [comment]
Ok I understand now. Thanks @fdkong @friedmud

**Pull request closed without merging**
