### PR TITLE
Addressing issue #4656

### PR DESCRIPTION
**Pull request by YaqiWang**
This is a simple but also a temporary fix. Calling those init functions is costly.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@andrsd Will you do this?

**Comment by YaqiWang** [comment]
BTW, I do not know why dbg test is failing. The error happens in initial condition evaluation, which does not make sense to me...

**Comment by andrsd** [comment]
> Will you do this?

I might get to it next week. How urgent is it for you?

**Comment by YaqiWang** [comment]
Next week is fine to me. I checked in my test in yak but currently disabled it. Thanks!

**Comment by andrsd** [comment]
I am closing this in favor of #4960 which addresses my comments from 10453521f75284aa6ca0b08c2dfcd98cae935538

**Pull request closed without merging**
