### PR TITLE
PorousFlow theory updated

### LINKED ISSUE #8239: PorousFlow Task: Document the upwinding, lumping, and nodal Materials
In doc/theory/theory.tex .  Some of the doco/ideas from the Richards module can be copied over.

### PR DESCRIPTION
**Pull request by WilkAndy**
Now includes discussion of
  - lumping
  - full upwinding
  - linear solvers and preconditioners

Fixes #8239
Refs #8139

### CODE REVIEW

**Comment by WilkAndy** [comment]
Unrelated test failure:

DiffuseCreep.stress_based_chem_pot

This is a test of @cpritam , but it hasn't been touched for the last 8 months, and must have passed testing recently.  I'm going to invalidate and see what happens.

**Comment by dschwen** [comment]
That test is failing in my PR as well.

**Comment by WilkAndy** [comment]
Aha, thanks @dschwen

**Review by jwpeterson — APPROVED** [review]
Thanks for always having great documentation.

**Comment by WilkAndy** [comment]
Thanks for the review+merge, @jwpeterson , and the nice comment about my doco!

a

**Pull request merged**
