### PR TITLE
check unused petsc options 

### PR DESCRIPTION
**Pull request by fdkong**
Implement a petsc option checker. This could be carried out right after the first nonlinear iteration or the first time step. We are actually going to support execute_on = 'linear nonlinear timestep_end timestep_begin'.

This require API changes in PETSc, and so please do not review right now. NOT REVIEW!

### CODE REVIEW

**Comment by permcody** [comment]
I don't want to implement this as a user object. It should just be an integral part of the framework and occur automatically at the right time. That's the way I had it on my branch in #727.

**Comment by permcody** [comment]
Also I'm fairly certain that this doesn't really accomplish what we need it to do but I'd have to test to find out. We actually need to report any unused option. Not just those unused by Petsc. This includes input file overrides which are tricky to handle. This was all handled in my version #727. I think mine would work fine if we just fired it after the first solve.

**Comment by permcody** [comment]
@fdkong - Will you take another look at this PR? It'd be nice to get it in and perhaps it could go in now. If not, just close per our policy and revisit later.

**Comment by fdkong** [comment]
Close, and will open if necessary.

**Pull request closed without merging**
