### PR TITLE
Use the app name from executable for MooseDocs check command

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #11337)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@andrsd This should fix the problem you are having with MooseDocs check.

**Comment by aeslaughter** [comment]
@bwspenc This should fix the problem you are seeing with Grizzly.

**Review by andrsd — APPROVED** [review]

**Comment by bwspenc** [comment]
Are you aware that this PR causes hundreds of errors when building the apps?  Stuff like this:
```
MooseDocs.base.readers:
ERROR: Multiple files located with matching name 'modules/tensor_mechanics/test/tests/material_limit_time_step/creep/nafems_test5a_lim.i':
    /Users/spenbw/gitproj/githerd/blackbear/doc/../../moose/modules/tensor_mechanics/test/tests/material_limit_time_step/creep/nafems_test5a_lim.i
    /Users/spenbw/gitproj/githerd/moose/modules/tensor_mechanics/test/tests/material_limit_time_step/creep/nafems_test5a_lim.i
```

**Comment by andrsd** [comment]
I observed the same thing on my laptop, but it does not show up on the build boxes. Just another data point

**Comment by bwspenc** [comment]
@aeslaughter FYI I just tried setting MOOSE_DIR to the absolute path, and it works fine.

**Comment by bwspenc** [comment]
Also, this does also fix the issue I was having with the Grizzly documentation not finding the .i files from an app it was including. Thanks!

**Pull request merged**
