### PR TITLE
Creates basics for building SQA documents from a markdown template

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #9466)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@brianmoose I have MooseDocs related testing in moose/test/docs, this should probably added to the list of directories that only trigger documentation builds.

**Comment by aeslaughter** [comment]
@permcody I fixed the failing tests, this should be ready.

**Comment by permcody** [comment]
This looks good. Can you add the template for the SDD (Software Design Description) too? That's the one that Lorielle is trying to get done for Mastodon.

**Review by permcody — APPROVED** [review]
This looks ok to me.

**Pull request merged**
