### PR TITLE
Make Dirac kernels with use_mobility=true to work with PF actions

### LINKED ISSUE #17025: PorousFlow: at_nodes parameter needed in specialized situations
## Reason

In recent PR #16995, i found that the `at_nodes` parameter was needed in `modules/combined/examples/geochem-porous_flow/forge/porous_flow.i`, viz:

```
  [./relperm] # this is necessary because of the use_mobility = true used in the PorousFlowPeacemanBorehole objects
    type = PorousFlowRelativePermeabilityConst
    at_nodes = true
    phase = 0
  [../]
```

The `at_nodes` parameter is supposed to be invisible to users, but this is a special situation where it is currently necessary.  It'd be nice to make it invisible.

## Design

It would be nice if the `at_nodes` parameter didn't need to be specified.   Hopefully @cpgr can do something magical with his Actions.

## Impact

Ease of use of PorousFlow, since `at_nodes` is a complication that we had hoped to hide from users.

### PR DESCRIPTION
**Pull request by cpgr**
This change ensures that the required materials are added when a
combination of PorousFlowBasicTHM or PorousFlowFullySaturated with
Dirac kernels that have use_mobility=true, removing the need for users
to manually include at_nodes=true materials.

Fixes #17025

### CODE REVIEW

**Comment by cpgr** [comment]
Hey @WilkAndy - turns out this actually wasn't as hard as I had originally thought and I didn't need the elaborate solution I was trying to implement!

**Comment by WilkAndy** [comment]
Cool, thanks.  This stuff is sometimes mind-boggling.  i'll review today....

**Review by WilkAndy — APPROVED** [review]
Sorry for forgetting about this!

**Comment by cpgr** [comment]
Oh, wow. I forgot this was here too

**Review by loganharbour — APPROVED** [review]

**Comment by cpgr** [comment]
Thanks @loganharbour

**Pull request merged**
