### PR TITLE
Rename _ad_grad_zero helper variable to something more generic

### LINKED ISSUE #17985: Add a helper variable for zero AD vector variables
## Reason
When setting coupled non-AD vector variable zero defaults using an `isCoupled()` guard scenario, one can use `_vector_zero`. But this does not work with AD vector variables, though a helper exists for AD scalar variables (`_ad_zero`).  An `_ad_vector_zero` helper variable (or something like it) should be added to the framework for developer convenience.

## Design
~~Add an `_ad_vector_zero` member variable to Coupleable and FEProblemBase.~~
Based on discussion in #17986 a generic rename of `_ad_grad_zero` will likely be a better route due to memory usage concerns.

## Impact
Easy access to a zero default for AD vector variables.

### PR DESCRIPTION
**Pull request by cticenhour**
Closes #17985

### CODE REVIEW

**Comment by cticenhour** [comment]
@lindsayad requesting you for a review. Though this is just a packaging of "zero" like the others, let me know if I should make a test.

**Review by lindsayad — CHANGES_REQUESTED** [review]
I'm hesitant about this. You should be able to use the preexisting `_ad_grad_zero` member to achieve the same functionality although the name is somewhat undesirable. We recently had a memory snafu addressed in https://github.com/idaholab/moose/pull/16831 related to default values and AD. Basically this is adding 153 Reals worth of memory per quadrature point. These AD default values have shown up as the single largest memory consumer in some problems (one is referred to in the title post of #16831). Would it be possible to use the existing `_ad_grad_zero` member? I would also be open to renaming the member to something more generic that would fit conceptually in both gradient and vector value cases

**Comment by cticenhour** [comment]
Ah I see - I had forgotten those memory issues from January. I am happy to abandon this in favor of `_ad_grad_zero` - that was in my original implementation in some pending Zapdos code, but my goal here was mostly improved code readability for the developer/end-user. 

A rename might be something like `_ad_vector_type_zero`? I still think that muddies the readability waters in the framework at least, since the bulk of the usage I see (in tensor mechanics) is for only grad displacement member variables. I guess that's just preference though. What would you prefer?

**Comment by lindsayad** [comment]
`_ad_vector_of_zeroes`? :laughing: I think something like `_ad_vector_of_zeroes` or `_ad_vector_type_zero` is a better name. I think it's more clear that you can use a `_ad_vector_of_zeroes` for a `_ad_grad_zero` t than the reverse: I think it's less clear that you can use a `_ad_grad_zero` for a `_ad_vector_of_zeroes`. I would try a name change. I don't see BISON using `_ad_grad_zero` which would be the principal app I would worry about for compatibility. If another app is using it, I would probably just give up since it's nearly impossible to do backwards compatibility with a data member :frowning_face:

**Comment by cticenhour** [comment]
Looks like we have multiple failures in Pronghorn, bluecrab, contact (which I'm a little surprised by...), so I think it's safe to say that `_ad_grad_zero` is enough for me. :)

Thanks for your input here Alex!

**Pull request closed without merging**
