### PR TITLE
Apply top-block-level parameters to bottom-level MooseObjects

### LINKED ISSUE #13783: Allow MooseObjectAction to extract parameter from its corresponding parent folder
## Reason
This small (one-line change) but possible controversial feature can be done really easily in `Parser` as
```
diff --git a/framework/src/parser/Parser.C b/framework/src/parser/Parser.C
index b267ce9711..b9010312a7 100644
--- a/framework/src/parser/Parser.C
+++ b/framework/src/parser/Parser.C
@@ -367,6 +367,7 @@ Parser::walkRaw(std::string /*fullpath*/, std::string /*nodepath*/, hit::Node *
       {
         object_action->getObjectParams().blockLocation() = params.blockLocation();
         object_action->getObjectParams().blockFullpath() = params.blockFullpath();
+        extractParams(MooseUtils::baseName(curr_identifier), object_action->getObjectParams());
         extractParams(curr_identifier, object_action->getObjectParams());
         object_action->getObjectParams()
             .set<std::vector<std::string>>("control_tags")
``` 
This basically allows users to put common parameters shared by for example materials under `[Materials]` block instead of repeatedly under their own sub-blocks. The feature is better than `[GlobalParams]` because those params within `[Materials]` can only been seen by materials. This limited scope can reduce the possibility of naming conflict among different types of objects.

Lots of neutronics models can benefit from this feature because of a number of materials could exist with some common parameters.

## Design
This is a completely new feature in the input file and there could be some implications. But conceptually I think this feature is good.

## Impact
A new feature.

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #13783

### CODE REVIEW

**Comment by dschwen** [comment]
Have you run the tests locally @lindsayad? Is this breaking anything? How do root level variables behave with this?

**Comment by lindsayad** [comment]
```
relationship_managers/evaluable.evaluable_neighbors_replicated .................. [min_cpus=3] FAILED (ERRMSG)
relationship_managers/geometric_neighbors.geometric_edge_neighbor ............... [min_cpus=3] FAILED (ERRMSG)
partitioners/grid_partitioner.test .............................................. [min_cpus=4] FAILED (ERRMSG)
vectorpostprocessors/parallel_consistency.test .................................. [min_cpus=2] FAILED (ERRMSG)
outputs/debug.show_var_residual_norms ....................................... FAILED (EXPECTED OUTPUT MISSING)
vectorpostprocessors/parallel_consistency.broadcast ............................. [min_cpus=2] FAILED (ERRMSG)
outputs/debug.show_material_props ........................................... FAILED (EXPECTED OUTPUT MISSING)
bcs/periodic.auto_wrap_3d_test ............................................................... FAILED (ERRMSG)
relationship_managers/evaluable.edge_neighbor ................................... [min_cpus=3] FAILED (ERRMSG)
relationship_managers/evaluable.edge_neighbor_3D ................................ [min_cpus=3] FAILED (ERRMSG)
relationship_managers/geometric_neighbors.geometric_edge_neighbor_3D ............ [min_cpus=3] FAILED (ERRMSG)
auxkernels/ghosting_aux.show_ghosting ........................................... [min_cpus=4] FAILED (ERRMSG)
auxkernels/ghosting_aux.show_ghosting_with_local ................................ [min_cpus=4] FAILED (ERRMSG)
auxkernels/ghosting_aux.no_algebraic_ghosting ................................... [min_cpus=4] FAILED (ERRMSG)
```
All failures are because of a use case I personally touted in #13783 :rofl:
```
auxkernels/ghosting_aux.show_ghosting: *** ERROR ***
auxkernels/ghosting_aux.show_ghosting: The parameter 'Mesh/dim' is a private parameter and should not be used in an input file.
```
Child blocks of the `Mesh` block which suppress the `dim` parameter

**Comment by lindsayad** [comment]
Wow this passed all modules tests straightaway

**Comment by rwcarlsen** [comment]
I don't like this.  The opaque pushing of parameters down into unknown sets of objects config makes input files harder to understand and debug.  If I see `foo=bar` inside a materials block that has 8 materials, how do I know which materials are using it?  I prefer a pull approach.  Objects should use substitution expressions where they can pull in parameters from parent scopes.  This already works and has the cascading parent scope traversal with inner scope overriding.  It also supports referencing params outside the enclosing scopes via `foo/bar/baz` syntax which this PR does not support.

Also - does this ensure we preserve unused parameter errors for these intermediate/parent-scoped params?

**Comment by lindsayad** [comment]
I'm going to close this per the discussion in #13783

**Pull request closed without merging**
