### PR TITLE
Organized contact module

### LINKED ISSUE #14205: Organize contact module
## Reason
The contact module *.h and *.C files are only partially organized...not too sure why. This will prevent unity building, and add confusion about what objects really are.

## Design
Reorganize the contact module based on object type.

## Impact
Better readability, organization, unity build, etc.

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #14205

### CODE REVIEW

**Comment by tophmatthews** [comment]
This is ready for review for whoever would be appropriate

**Comment by sapitts** [comment]
This seems like something that @acasagran might like to weigh in on?

**Review by dschwen — APPROVED** [review]
Lovely. Thanks!

**Comment by bwspenc** [comment]
@dschwen Any reason this isn't merged in?  It looks like we should merge it to me.

**Comment by bwspenc** [comment]
I'm going ahead and merging it.

**Pull request merged**
