### PR TITLE
Fix memory issue for the test, generalized_plane_strain_tm_contact

### LINKED ISSUE #8140: Test fails on PETSc 3.7
### Description of the enhancement or error report
The `modules/combined/tests/generalized_plane_strain_tm_contact` test fails on PETSc 3.7.

### Rationale for the enhancement or information for reproducing the error
It gives warnings from the inverse_map, and eventually segfaults.

### Identified impact
Modify the test.

### PR DESCRIPTION
**Pull request by fdkong**
Added a petsc option to fix memory issue for the
    
    test, generalized_plane_strain_tm_contact.
    
    -mat_superlu_dist_fact SamePattern_SameRowPerm
    
    Closes #8140 #8141

### CODE REVIEW

**Comment by permcody** [comment]
@fdkong - That's great that this can be fixed by an extra option but why is it seg faulting in the first place? Can we do something in MOOSE to prevent this issue?

**Comment by fdkong** [comment]
> @fdkong - That's great that this can be fixed by an extra option but why is it seg faulting in the first place? Can we do something in MOOSE to prevent this issue?

I am still working on this, and still puzzled. It is complicated. I would do something in moose or petsc, if I could figure out the reason.

The petsc option I added makes this example pass, but does not make sense for me mathematically.

**Comment by permcody** [comment]
Did you forget to carry the one? 😄

**Review by bwspenc — COMMENTED** [review]
I'm OK with this change, but I'm hoping that we can come up with a solution so we don't need to use these options on every model like this.  Since this has one of my commits in it, someone else should probably merge it.

**Comment by fdkong** [comment]
> I'm OK with this change, but I'm hoping that we can come up with a solution so we don't need to use these options on every model like this. Since this has one of my commits in it, someone else should probably merge it.

A short answer would be  to add this option in MOOSE as a default option, and the long term is to fix this thing in PETSc or superlu_dist. I have been debugging for a while, and not get yet. Even through we could fix the thing in PETSc, we have to wait for a new release.  The short term may be better, and how do you think, @permcody ?

Fande,

**Comment by permcody** [comment]
I definitely do **not** want users to set this option. It'll get copied all over the place and show up in input files forever. @fdkong - let's set this option automatically based on the specific version of PETSc we using when SuperLU is used.

**Comment by bwspenc** [comment]
I agree with @permcody.  I'm assuming that this is something that can be used with any model (assuming you're using the right version of PETSc). If that's the case, let's definitely set this behind the scenes.

**Comment by fdkong** [comment]
> I agree with @permcody. I'm assuming that this is something that can be used with any model (assuming you're using the right version of PETSc). If that's the case, let's definitely set this behind the scenes.

Added

**Review by bwspenc — APPROVED** [review]
This looks like a better solution to me.  I guess we'll see whether this breaks something else in the testing.

**Review by permcody — APPROVED** [review]
I think I'd like it if we only needed one CPP define but this is acceptable.

**Pull request merged**
