### PR TITLE
Total flux 4798

### PR DESCRIPTION
**Pull request by WilkAndy**

### CODE REVIEW

**Comment by dschwen** [comment]
This is a bit off-topic, but I've been seeing quite a few PRs that had the issue number in the title. As far as I know our current practice it to have it in the PR description (Such as "Closes #XXX"). Sorry, I don't mean to single you out Andy, there was definitely another offender as well. Thought I mention it before it catches on ;-)

**Comment by WilkAndy** [comment]
No problems, @dschwen .  I suspect that github automatically put that title and i accepted it.

a

**Comment by permcody** [comment]
GitHub creates a title from the first line in your commit message. If you
put the reference after a newline than you are good to go. If you are
typing a message on the command line like many of us do just don't close
the quote before hitting newline. You can type several lines before closing
your quote if you wish. It just looks cleaner.

**Comment by WilkAndy** [comment]
Thanks @tonkmr ,

a

**Pull request merged**
