### PR TITLE
Add mortar frictional contact ironing animation

### PR DESCRIPTION
**Pull request by recuero**
Refs. #17495

## Reason
Capability demonstration on website

## Design
Follow existing design, just addition

## Impact
Easier grasp of MOOSE's capabilities

### CODE REVIEW

**Comment by recuero** [comment]
@dewenyushu @lindsayad just adding a frictional ironing problem animation using mortar. Merge if it looks okay.

**Review by lindsayad — DISMISSED** [review]
lgtm!

**Comment by recuero** [comment]
Oops, didn't capitalize the title. Let me fix it

**Comment by dewenyushu** [comment]
@recuero this is exciting! Several minor comments about the animation: 

I assume the horizontal velocity is constant. However, in the animation it looks like the block is slowing down while moving to the right. I guess there are time steps being cut towards the end of the simulation. This caused Paraview to output extra image frames for you. To improve this, in Paraview maybe try: `view->Animation view` and then choose the `Mode` as `sequence` and set the `No. Frames` as the actual number of image you would like.

Also, do you think it would be better to make the legends clearer, e.g., something like `Tangent Contact Pressure of the Intruder/Indenter/Tool` and the `Displacement (x) of the Substrate`?

**Comment by recuero** [comment]
@dewenyushu done!

**Comment by lindsayad** [comment]
When @dewenyushu approves I will merge

**Review by dewenyushu — APPROVED** [review]
Thanks @recuero !

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
