### PR TITLE
Added input file examples for basic tensor mechanics tutorial

### LINKED ISSUE #7014: Create basic tutorial for the tensor mechanics kernel
### Description of the enhancement or error report
We need a basic tutorial for the tensor mechanics kernel. It will cover

- The basic elements of a tensor mechanics input file
- Visualizing tensor fields
- 2D axisymmetric RZ problems
- Small strain elasticity, finite strain elasticity, and finite strain J2 plasticity
- Extruding a 2D mesh to be a 3D mesh
- Running 3D tensor mechanics problems in cartesian coordinates

### Rationale for the enhancement or information for reproducing the error
New users need a clear demonstration of how to use the basic parts of the tensor mechanics kernel

### Identified impact
The tutorial will help new users quickly become familiar with the tensor mechanics module

### PR DESCRIPTION
**Pull request by tonkmr**
The tutorial walks the user through the construction of various input files. For each case, an example input file is provided for reference. 
The tutorial can be found at:
http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/BasicTutorial/

Closes #7014

### CODE REVIEW

**Comment by permcody** [comment]
Will invalidate BISON after they update.

**Comment by tonkmr** [comment]
I only checked in example input files here, and didn't make any changes to the code or tests. I'm not sure how it would invalidate BISON.

**Comment by dschwen** [comment]
👍

**Comment by jessecarterMOOSE** [comment]
A dumb question, but is this linked anywhere on the Tensor Mechanics page? I don't see it.

**Comment by tonkmr** [comment]
It isn't linked yet. I was waiting for this to be merged. I will link it soon.

**Pull request merged**
