### PR TITLE
Attempt at fixing failing heavy tests 

### PR DESCRIPTION
**Pull request by recuero**
from #14462. Refs. #6978

Fix for failing heavy tests from the migration of regression tests from Solid Mechanics to Tensor Mechanics.

### CODE REVIEW

**Comment by recuero** [comment]
@bwspenc Please take a look.

**Review by bwspenc — DISMISSED** [review]

**Comment by bwspenc** [comment]
@permcody This should fix the breakage issue.  Note that it says that this PR will change the repo size by 13 MB, but it just has some minor changes to a few text files and adds a couple of symlinks to .e files. I'm not sure what's up with that.

**Comment by permcody** [comment]
Yeah - I'm not sure about the size diff check either. The only thing I can think of is that it might not be rebased on current devel? You can see the command that gets run. Git "sees" lots of changes, but they might not all be necessary.

**Comment by recuero** [comment]
@bwspenc @permcody There were still a few tests diffing. Updated some settings to fix it.

**Comment by permcody** [comment]
Looks like you still have 2 to go!

**Comment by recuero** [comment]
@permcody @bwspenc Removed SM tests can't fail. Hopefully.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
