### PR TITLE
Make MOOSE converged test more consistent with PETSc's default one

### PR DESCRIPTION
**Pull request by fdkong**
There is an option, "-snes_force_iteration", in PETSc, that forces the nonlinear solver take at least one iteration. 

MOOSE did not honor this option because it uses a different converged test from PETSc. This PR fixes this by making the MOOSE converged test function to take the option into account. 

This requires an API update at the PETSc side. Once the API is added into PETSc, I will retest this PR against PETSc-master. 

Close #10599

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
This looks good. However, contact has a class called ReferenceResidualProblem which reimplements `checkNonlinearConvergence`. Additionally they don't have it marked override so you had no idea it existed after you changed the method signature in `FEProblemBase`. That should be marked override and you need to change its signature

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
@bwspenc Forcing a minimum number of iterations is something that would have to be added on the Petsc side. Perhaps @fdkong can comment on how difficult that would be. If we did acquire the ability to specify a minimum number of nonlinear iterations, then I definitely think that should be an input file option. For now, this forcing of a single nonlinear iteration seems like it may not be used very much, so I like the current fix. However, if you think it will receive enough use to warrant being an input file option, then we can open a ticket.

**Comment by fdkong** [comment]
@bwspenc, What applications require you have a minimum number of iterations? Use this info, I could talk to PETSc team and propose a patch.

**Comment by fdkong** [comment]
@bwspenc, What applications require you have a minimum number of iterations? Use this info, I could talk to PETSc team and propose a patch.

**Comment by bwspenc** [comment]
It mostly comes up for debugging purposes, and is not something you would generally need to use in practice.  A good example of that would be the work Alex was just doing to resolve the issue with the contact set update. We were pretty sure we could get correct solutions with the old algorithm if we forced it to take more iterations, and that could have been tested really easily if we had that option.

**Pull request merged**
