### PR TITLE
change bottom_p_or_t to be a function 

### LINKED ISSUE #20452: allow PorousFlowPeacemanBorehole to take a function for bottom_p_or_t parameter
## Reason
For the case where this diracKernel is a function_of=pressure, it would be nice to compute the bottom_p_or_t pressure in a function that can account for the z-coordinate location of the bottom of the borehole.  

## Impact
This change will make the borehole source easier to use with monte carlo sampling of the borehole placement using reporter input.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #20452

### CODE REVIEW

**Comment by lynnmunday** [comment]
@WilkAndy or @cpgr  Would one of you comment on this change?  Nothing breaks and it is backward compatable with just supplying a value.  I made it a function so that as we move the production well location around using the monte carlo sampler, we can easily adjust the bottom pressure.

**Review by cpgr — DISMISSED** [review]
It all looks ok to me. Only question is why is the `insitu_pp` function value written as `2*0.5e7` instead of just `1e7`?

**Comment by lynnmunday** [comment]
@cpgr   I wanted to show that it was evaluating a function.... I don't know if that is a very good reason.  I wanted to use the coordinate value in the function but the borehole is always located at the origin.

**Comment by lynnmunday** [comment]
don't push this, I'll add a function that uses a coordinate.

**Comment by lynnmunday** [comment]
@cpgr would you take another look at this?   I made the function use a coordinate, this would be closer to how we would actually want to use it.

**Review by cpgr — APPROVED** [review]
Look's good to me

**Comment by WilkAndy** [comment]
Thanks for doing this, @cpgr .   I was traveling or preparing to travel most of this week.

a

**Comment by lynnmunday** [comment]
@loganharbour Would you merge this?  @cpgr is ok with the changes.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
