### PR TITLE
Penalty Dirichlet BC for nodesets

### LINKED ISSUE #14092: Penalty Dirichlet BC for nodesets
## Reason
Similar to the PenaltyDirichletBC for sidesets, sometimes it is desired to have this capability for nodesets.

## Design
Nodal kernel was used to implement penalty method for Dirichlet BC for nodesets.

## Impact
New capability. No impact on existing codes or tests.

### PR DESCRIPTION
**Pull request by hchen139**
close #14092

### CODE REVIEW

**Comment by permcody** [comment]
@lindsayad - Can you review this please. You might want to look at the huge array of comments I had over here: https://github.com/idaholab/moose/issues/14092

Now that I understand that this is an _integrated_ BC it makes more sense. Is this how you'd implement it though?

**Comment by hchen139** [comment]
> @lindsayad - Can you review this please. You might want to look at the huge array of comments I had over here: #14092
> 
> Now that I understand that this is an _integrated_ BC it makes more sense. Is this how you'd implement it though?

No, it is a _nodal_ BC but should be implemented without zeroing out the rest components of the corresponding row and column. This can be achieve by using either integrated BC for sidesets (already available as _PenaltyDirichletBC_) and nodal kernel for nodesets (this PR).

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
This seems fine to me. It seems like you must have an actual use case for this. I personally like to avoid penalties since it destroys the matrix condition number, but I understand there may be times you need to use it.

**Comment by bwspenc** [comment]
@lindsayad We do indeed have use cases for this. I agree that we don't usually want to use penalties, but it's the right thing to do here.

**Pull request merged**
