### PR TITLE
Fix doco warnings

### PR DESCRIPTION
**Pull request by andrsd**
Fixing warnings in documentation generation

### CODE REVIEW

**Comment by andrsd** [comment]
Could we possibly make the doco target into a hard fail so we don't have to fix things like this again?

**Comment by aeslaughter** [comment]
I will promote MooseDocs warning to errors. Can I add my changes to this PR?

**Comment by andrsd** [comment]
Absolutely!

**Comment by andrsd** [comment]
I used your patch against on the "broken" `devel` branch and these warnings are still warnings:
```
MooseDocs.extensions.appsyntax (Process-4): The class description is missing for /FVBCs/FVConstantScalarOutflowBC, it can be added using the 'addClassDescription' method from within the objects validParams function
```

The other ones are errors as we would expect. Is there a reason why you kept these as warnings?

**Comment by aeslaughter** [comment]
I only change warnings in the "check" command which performs checks if the files exist. It doesn't do anything with the markdown. The warning you are posting comes from the build command when trying to parse the `!syntax description ...` markdown syntax. I will see what it will take to get the class description to be tested with "check".

**Comment by andrsd** [comment]
@aeslaughter Beautiful! Your patch discovered some more missing `addClassDescription` calls 👍

**Review by aeslaughter — APPROVED** [review]

**Comment by andrsd** [comment]
Thanks!

**Pull request merged**
