### PR TITLE
Consolidate ideal gas classes in fluid properties module

### LINKED ISSUE #12970: Consolidate ideal gas fluid property classes
## Rationale

There are two ideal gas formulations: `IdealGasFluidProperties` and `IdealGasFluidPropertiesPT` but both now share the same base class, so could be consolidated into a single class.

## Description

Move the pressure and temperature methods from `IdealGasFluidPropertiesPT` to `IdealGasFluidProperties` and deprecate `IdealGasFluidPropertiesPT`.

## Impact

Eventually have only one ideal gas class with full functionality of existing classes.

### PR DESCRIPTION
**Pull request by cpgr**
Implement all functionality in IdealGasFluidProperties and
deprecate IdealGasFluidPropertiesPT

Closes #12970

### CODE REVIEW

**Comment by cpgr** [comment]
Hi @andrsd,

The molar mass in IdealGasFluidProperties was
```
Real
IdealGasFluidProperties::molarMass() const
{
  return _R / R_universal;
}
```
but molar mass is actually the inverse of this (universal gas constant / specific gas constant).

I changed it and had to redo some unit tests (that used IdealRealGasMixtureFluidProperties), but I assume that this will break Relap7 or some other app that uses it.

Was this supposed to be the inverse of molar mass (mol/kg)?

**Review by andrsd — DISMISSED** [review]

**Comment by andrsd** [comment]
> Was this supposed to be the inverse of molar mass (mol/kg)?

Nope. I just screwed up the `molarMass` method in ideal gas :-) . Thanks for fixing this!

**Comment by andrsd** [comment]
I will fix the internal apps - no worries...

**Comment by andrsd** [comment]
Looks like `porous_flow` has some input files still using `viscosity` instead of `mu`. Also, you may want change the `IdealGasFluidPropertiesPT` to `IdealGasFluidProperties` there as well.

**Comment by andrsd** [comment]
I have patches for bighorn, pronghorn and RELAP-7 ready.

**Comment by cpgr** [comment]
I missed those tests! I've fixed them up as well.

It did remind me that I had just removed some input parameters (like viscosity), so I have added a deprecated message if using them, as well as range checking some others to avoid any possibility of  division by zero by an input file error.

**Review by andrsd — APPROVED** [review]

**Comment by cpgr** [comment]
Thanks again @andrsd

**Pull request merged**
