### PR TITLE
Fix deprecated required coupled variable

### LINKED ISSUE #16175: Make addDeprecatedCoupledVar work with required parameters
## Reason
When using `InputParameters::addDeprecatedCoupledVar` with a required parameter, you get the deprecated message followed by an immediate failure for a missing required parameter _new_name_.

## Design
Per the original design deprecated aliases should work for all couple variable types. (Tag @lindsayad)

## Impact
Make it easier to deprecate old coupled variable names.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #16175

### CODE REVIEW

**Comment by lindsayad** [comment]
Looks like that indenter example Antonio added uses the `master_variable` syntax

**Comment by dschwen** [comment]
Whoops, and we do not fail on deprecations... Ok, I'll fix it.

**Comment by dschwen** [comment]
Ok, welp. Apparently I'm removing all the deprecated master/slave parameters now...

**Comment by dschwen** [comment]
Pinging @cbolisetti (Mastodon is using expired deprecated objects) and whoever is in charge of Pronghorn (@rwcarlsen ?).

**Comment by dschwen** [comment]
I removed the master/slave deprecation and will put it in a separate PR.

**Comment by dschwen** [comment]
Why is that Documentation target not running?!

**Comment by lindsayad** [comment]
I don't know. I bet if you do `git commit --amend` and then push again it will trigger correctly. I know the firewall BS has been "fixed" for another 24 hours

**Comment by dschwen** [comment]
It is so convenient that I cannot access the public civet when I'm on the VPN. Gosh, I feel so safe.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
