### PR TITLE
Checking issue #12908

### PR DESCRIPTION
**Pull request by arovinelli**
I and @YaqiWang  might have found a possible issue while revising #12896. The possible issue is related to the use of block restricted auxkernels when using a distributed mesh.
I opened this PR to test simple cases and see if the problem is related to #12896 or is a defect.

checking issue #12908

### CODE REVIEW

**Comment by arovinelli** [comment]
@YaqiWang I'm adding tests regarding the strange behavior of #12896 here. This branch is clean so we can sort out what is causing the issue

**Comment by arovinelli** [comment]
@YaqiWang you were right, it is the `AssignElementSubdomainID ` that make things going wrong. The test with `SubdomainBoundingBox` box works fine. I'll change the input deck for #12896

**Comment by YaqiWang** [comment]
I checked `AssignElementSubdomainID`, looks like it has a large amount of code to make it work with distributed mesh. I remember @roystgnr made lots of effort to make this work. He might have comments on this.

**Comment by permcody** [comment]
We don't know for sure that `AssignElementSubdomainID` is the problem here. The diff is in the solution variable, not the subdomains.

**Comment by YaqiWang** [comment]
Note: @arovinelli said that changing `AssignElementSubdomainID` to `SubdomainBoundingBox` make the problem go away.

**Comment by roystgnr** [comment]
Is SubdomainBoundingBox being used to create the exact same subdomains as AssignElementSubdomainID was?  If not then it's possible that it's just failing to trigger a corner case.

Am I correct in observing that the failure is occurring with block-restricted kernels even *without* block-restricted variables?  In other words, there's no chance that https://github.com/libMesh/libmesh/issues/1919 might be hitting you here?

**Comment by arovinelli** [comment]
@permcody you can check the log of **Pthreads Test **. Of the four test I did only the one with `AssignElementSubdomainID` fails, this is sure.It might also be a strange combination of  interaction between block restricted variables and subdomain id. However is my personal believe that results are correct but the mesh is somehow rotated. Can we dump the exodus of the tests somehow?

**Comment by roystgnr** [comment]
There are a half dozen test case input decks, mostly in test/tests/mesh_modifiers/assign_element_subdomain_id/, that started working in parallel after I made those fixes to AssignElementSubdomainID... and they are using exodiffs, so at least the written Exodus file had subdomains correct... subdomain ids on ghost elements wouldn't be properly tested by that procedure, so maybe that's something to be suspicious of, but the code certainly looks like it *should* be getting ghost element subdomain ids correct too.

**Comment by YaqiWang** [comment]
The two tests have the following diff in their input files:
```
14,17c14,18
<     [./subdomain_id]
<       type = AssignElementSubdomainID
<       subdomain_ids = '0 1
<                        1 1'
---
>     [./bounding_box]
>       type = SubdomainBoundingBox
>       bottom_left = '-1 -1 0'
>       top_right = '0 0 0'
>       block_id = 1
22c23
<       depends_on = subdomain_id
---
>       depends_on = bounding_box
```
One is failing but another is not.

@roystgnr I think you are right, aux kernels are block restricted but the aux variables are not.

**Comment by YaqiWang** [comment]
@arovinelli do the two tests have exact gold exodus file? If not, you may want to. Also are you able to produce the failure on mac?

**Comment by roystgnr** [comment]
> One is failing but another is not.

I forget exactly what our ID conventions are for build_square, but regardless it looks like the AssignElementSubdomainID case is putting 3 elements in subdomain 1 but the SubdomainBoundingBox case is putting 1 element in subdomain 1?  It might be a good idea if they matched completely; that would differentiate between "AssignElementSubdomainID is actually failing" vs "that particular subdomain configuration is triggering a different problem" diagnoses.

**Comment by arovinelli** [comment]
@roystgnr @YaqiWang @permcody 
I was able to replicate this on my linux machine (centos).
I added other tests:

-  one exactly comparable to the bounding box, the assigneID still fails
- one assigneID only mesh, it works.
- one assigneID with unrestricted auxvars, it fails
- one assigneID with no aux var/kernel, it pass

Also when it fails, it's simply because the mesh is rotated as I suspected (I can't add an image here) but basically you can think that in the gold file the element with id 1 is at (x,y)=0,0 in the outcoming file form distributed mesh it goes to (x,y)=1,0 however variable and material property are ok (but rotated of corse).

**Comment by arovinelli** [comment]
I forgot to mention, element ID also results rotated.

**Pull request closed without merging**
