### PR TITLE
Add back secondary-primary coupling for penalty mortar

### LINKED ISSUE #21569: PenaltyEqualValueConstraint allocates nonzeros
## Bug Description

`PenaltyEqualValueConstraint` allocates non-zeros. I am not sure if this is generally the case for Mortar, or just this object.

## Steps to Reproduce

Set `Problem/error_on_jacobian_nonzero_reallocation = true` in `test/tests/mortar/continuity-3d-non-conforming/continuity_penalty_sphere_hex8.i`.

## Impact

Slow initial Jacobian computation which eventually becomes a real problem when the mesh becomes large.

### PR DESCRIPTION
**Pull request by lindsayad**
At one point we removed the secondary-primary (and vice versa)
coupling because all of our constraints were LM based. But with
penalty we need that coupling restored in order to avoid
new-nonzero reallocations

Closes #21569

### CODE REVIEW

**Comment by hugary1995** [comment]
It seems to be working for my toy problem now. But the regression tests suggest I might just be lucky with the number of processors I chose. @albiedahal is trying this on a larger problem, and he'll let us know how it goes.

**Comment by albiedahal** [comment]
@hugary1995 The larger mesh problem still hangs at initial jacobian computation

**Comment by hugary1995** [comment]
> @hugary1995 The larger mesh problem still hangs at initial jacobian computation

Can you try setting `error_on_jacobian_nonzero_reallocation` to true in the Problem block? I want to confirm this is caused by nonzero allocation.

**Comment by lindsayad** [comment]
> Would it be straightforward to add some smarts to pick the coupling depending on whether we have LMs?

I think it's not a big deal to over-preallocate. PETSc will shrink the unused entries upon the first `MatAssemblyBegin/MatAssemblyEnd` (which is one of the reasons we can later get new nonzeros as the mesh moves and new coupling entries form ... this case is what we would want a hash table for in PETSc)

**Comment by albiedahal** [comment]
> > @hugary1995 The larger mesh problem still hangs at initial jacobian computation
> 
> Can you try setting `error_on_jacobian_nonzero_reallocation` to true in the Problem block? I want to confirm this is caused by nonzero allocation.

I get a PETSC ERROR
image

**Comment by lindsayad** [comment]
Decided it would be prudent to do some performance checking. I ran the non-conforming gap conductance test with boomeramg with 9 refinements with 64 procs. It doesn't appear that there's really anything embarrassing out of mortar; runtime is actually dominated by the refinement process (so arguably this is not the best performance test case)

prof-mortar0

**Comment by lindsayad** [comment]
@albiedahal if you could try your problem again, that would be appreciated. Are you using a displaced mesh?

**Comment by lindsayad** [comment]
this should be ready for review

**Comment by albiedahal** [comment]
> @albiedahal if you could try your problem again, that would be appreciated. Are you using a displaced mesh?

I tried running the problem again with `error_on_jacobian_nonzero_reallocation = true` on the problem block and it executes without an error. However, the initial jacobian computation is still slow. I am using homogenized total lagrangian kernels with `large_kinematics = true` and `use_displaced_mesh` is set to `false` by default.

**Comment by lindsayad** [comment]
Ok well that sounds like a separate issue, potentially unique to mechanics. You could profile it to check

**Review by recuero — COMMENTED** [review]
The move from `multimap` to `map` does not seem to affect the coupling contents, does it?

**Comment by lindsayad** [comment]
no

**Comment by recuero** [comment]
For an 8-way simulation of the continuity penalty sphere problem (`uniform_refine = 3`), the first computation of the Jacobian takes 19.9 s, as opposed to 42.1 s which was taking without the modifications in this PR.

**Review by recuero — APPROVED** [review]
Looks good to me. It shows performance improvement for problems of moderate size.

**Pull request merged**
