### PR TITLE
Enable MatPartitioning

### PR DESCRIPTION
**Pull request by fdkong**
This allows us have more partitioning options.

`parmetis ptscotch chaco party hierarch`

### CODE REVIEW

**Comment by permcody** [comment]
You go stale bot!
Tag @brianmoose

**Comment by permcody** [comment]
Oh damn...

**Comment by brianmoose** [comment]
@permcody  stale bot would have closed this if you hadn't commented....so I will go ahead and close. Somebody can reopen if they want to revive it.

**Comment by permcody** [comment]
Oh man! You are even more draconian than stale bot!

**Pull request closed without merging**
