### PR TITLE
New Perf Graph timers in FeatureFlood/GrainTrackers

### PR DESCRIPTION
**Pull request by permcody**

### CODE REVIEW

**Comment by permcody** [comment]
Tag @friedmud - Here is my change set that produces the error I posted here: https://github.com/idaholab/moose/pull/11552#issuecomment-406270948

**Comment by dschwen** [comment]
Don't you need to inherit from PerfGraphInterface or is that higher up in the hierarchy (I did not see that in the original PR)

**Comment by permcody** [comment]
Hmm. I certainly didn’t do that. If that’s the case we should improve the
error messaging. I’m not sure how it could even approach working without
it, but maybe...

**Comment by dschwen** [comment]
Is this a joke ticket and I'm just not getting it?

**Comment by dschwen** [comment]
I now see `UserObject` inherits form `PerfGraphInterface` already (this is how it should be). You heisenbug comes from not initializing the IDs.

**Comment by permcody** [comment]
Not a joke ticket. I honestly just missed that very important detail. It’s
the kind of thing a first time user might do. We should probably check for
unregistered Ids!

**Comment by friedmud** [comment]
@permcody You can't just check for it (at least not in opt) - that would slow it down.  You hit the correct assert for this case.

Feel free to add another assert if you want though.

**Comment by permcody** [comment]
`PerfID` is just an `unsigned int` so there's not much we can do. It's good to see what can happen if registration is forgotten. We could probably get it to fail reliably on Mac by just not ever using ID 0 (zero). On Linux, you will hit the assert since you'll have garbage IDs. I'm not inclined to change anything though, we'll just have to watch for that in review. Valgrind will definitely catch it so it can't sneak through.

**Comment by permcody** [comment]
Going to combine timers and several enhancements into a single PR.

**Pull request closed without merging**
