### PR TITLE
Disambiguate object path in document to accomodate for new SAM object

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #29543

### CODE REVIEW

**Comment by loganharbour** [comment]
SAM is fixing this. I reached out to them, should be in soon

**Comment by GiudGiud** [comment]
It's probably easier on our side this time. As you want.

**Comment by loganharbour** [comment]
They put in quite a few objects that register to MooseApp, which is a pretty significant issue. I think I'd rather see those problems instead of hiding them

**Comment by GiudGiud** [comment]
That might be a separate issue then? What I am addressing here is the listing finding two source files with the very close names

**Comment by GiudGiud** [comment]
see this
https://civet.inl.gov/job/2600478/

**Comment by loganharbour** [comment]
Same issue I believe. syntax plugin mishap

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
Now that I think about it. We really shouldn't be doing partial matches on files

**Pull request merged**
