### PR TITLE
Sub-block support for Thermochimica calculations

### LINKED ISSUE #26376: Sub-block definition of chemical composition for Thermochimica API
## Reason
In order to set up multiple materials via the chemical composition setup of Thermochimica (i.e. Fuel salt in liquid blocks, and alloy in solid blocks)

## Design
Being able to define Temperature, Pressure, and Elements specific to certain blocks - fluid and solid specifically to allow for multiple variable inputs.

## Impact
This will change the Thermochimica API.

### PR DESCRIPTION
**Pull request by parikshitbajpai**
Closes #26376

### CODE REVIEW

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
```
ERRORS:
Duplicate requirements found:
The system shall throw an error if the temperature unit is not specified
/data/civet1/build/moose/modules/chemical_reactions/test/tests/thermochimica/tests:op_munit_error:144
/data/civet1/build/moose/modules/chemical_reactions/test/tests/thermochimica/tests:tunit_error:111
/data/civet1/build/moose/modules/chemical_reactions/test/tests/thermochimica/tests:munit_error:133
/data/civet1/build/moose/modules/chemical_reactions/test/tests/thermochimica/tests:punit_error:122
Control this message using: 'log_duplicate_requirement'
```

**Review by dschwen — CHANGES_REQUESTED** [review]
Fix requirements

**Comment by parikshitbajpai** [comment]
> Fix requirements

I need to learn how to copy paste without breaking things. Fixed it

**Comment by parikshitbajpai** [comment]
Need to handle common elements when multiple databases are specified. Will do that in #26607.

**Review by dschwen — APPROVED** [review]

**Pull request merged**
