### PR TITLE
Give explicit path for where to bootstrap netcdf

### PR DESCRIPTION
**Pull request by lindsayad**
Refs failure on libmesh/libmesh#3617

### CODE REVIEW

**Review by loganharbour — CHANGES_REQUESTED** [review]
Reminder that you'll need to bump libmesh versions for conda to trigger this change there

**Comment by lindsayad** [comment]
Are we still supposed to change `conda/mpich/conda_build_config.yaml`?

**Review by loganharbour — CHANGES_REQUESTED** [review]
Added all of the next tests because this is still a package change. This is good

If you want to merge this this weekend, let me know because I do need to rebuild some other packages at the same time.

**Review by loganharbour — DISMISSED** [review]
Oops. Approve, not request changes...

**Review by roystgnr — DISMISSED** [review]

**Comment by roystgnr** [comment]
I'm good with this as-is, but would it be more flexible to make this a for loop?  Then if we want to drop in multiple netcdf options we just hit them all.

**Comment by lindsayad** [comment]
> We should also include a change to moose/scripts/tests/versioner_hashes.yaml to keep in line with that process

So I need to do that?

> I'm good with this as-is, but would it be more flexible to make this a for loop? Then if we want to drop in multiple netcdf options we just hit them all.

The thing is that right now there is not a need to bootstrap the newer netcdf releases as their checked-in bootstrapped files used a newer autotools version that works with Mac arm64

**Review by loganharbour — APPROVED** [review]

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
