### PR TITLE
Fix 'map' object is not subscriptable error

### PR DESCRIPTION
**Pull request by rksin8**
Fixed 'map' object is not subscriptable error in python3 by converting map output to list

refs #17558

### CODE REVIEW

**Comment by WilkAndy** [comment]
Thanks for doing this, @rksin8 .

**Review by WilkAndy — APPROVED** [review]
Only two housekeeping things - usually we open an "issue" and refer to the issue number in the pull request. Currently this contribution also contains commits from updating your next to the current idaholab next branch, which is not really optimal.

Are you able to fix these things, @rksin8 ?   Sometimes git can be rather difficult to work with, so please don't spend hours trying to get it all fixed.

Apart from that, the actual code changes are good, thanks.

**Comment by rksin8** [comment]
> Only two housekeeping things - usually we open an "issue" and refer to the issue number in the pull request. Currently this contribution also contains commits from updating your next to the current idaholab next branch, which is not really optimal.
> 
> Are you able to fix these things, @rksin8 ? Sometimes git can be rather difficult to work with, so please don't spend hours trying to get it all fixed.
> 
> Apart from that, the actual code changes are good, thanks.



> Only two housekeeping things - usually we open an "issue" and refer to the issue number in the pull request. Currently this contribution also contains commits from updating your next to the current idaholab next branch, which is not really optimal.
> 
> Are you able to fix these things, @rksin8 ? Sometimes git can be rather difficult to work with, so please don't spend hours trying to get it all fixed.
> 
> Apart from that, the actual code changes are good, thanks

Thanks for the reply.  I don't know to fix this. So to create a pull request, first I need to open an issue then use that reference number in the pull request.  I will follow this and other guidlines in the future requests.

**Comment by WilkAndy** [comment]
@loganharbour - could you please close this PR?  I have created another one with the same content but using the usual contributing workflow at #17573

**Comment by WilkAndy** [comment]
@rksin8 - i've created another PR at #17573 with your content, but using the standard moose-contributing workflow.  You may close this PR now as it won't be accepted by the MOOSE team without the correct workflow.   Thanks for your contribution :-)

**Comment by WilkAndy** [comment]
> @rksin8 - i've created another PR at #17573 with your content, but using the standard moose-contributing workflow. You may close this PR now as it won't be accepted by the MOOSE team without the correct workflow. Thanks for your contribution :-)

Don't close this quite yet, @rksin8 .   I'm trying to make you the author of these changes, rather than me.

**Pull request closed without merging**
