### PR TITLE
Minor change to reduce total number of set insertions

### PR DESCRIPTION
**Pull request by olinwc**
Eliminates first set insertion by instead assigning the set directly, resulting in a minor runtime improvement. Closes Issue #14628

### CODE REVIEW

**Comment by permcody** [comment]
Did you find this by looking at timing? I'm not convinced that this would help at all because assignment still causes a copy operation. If you did want to avoid the first copy you'd actually use the std::set::swap() method instead. In general we usually don't look for micro-optimizations like this unless we can prove (through timing) that they matter.

If you are interested in working on optimization, we can walk you through the process of finding slow chunks of code through profiling and how to go about fixing them.

**Comment by olinwc** [comment]
I'll have to rerun my time profiling to verify my original claim, I will attach them here once I have. But I do believe I was experiencing a 4-5% runtime improvement (which for the cases I've been testing can add up to over an hour of saved runtime)

**Comment by YaqiWang** [comment]
It is not about micro optimization but rather good practice of using STL. If the code is changing nothing but reduces operations, I'd say we should go for it.

**Comment by permcody** [comment]
BTW - `swap` won't work here because it's a reference into the container.

**Comment by permcody** [comment]
I'm fine with optimization - I just want to make sure it's actually improving something. On inspection it's difficult to see where we are avoiding anything. I would expect the new code to be equivalent in terms of operations.

**Comment by YaqiWang** [comment]
Yes, @olinwc has to explain this.

**Pull request closed without merging**
