### PR TITLE
Testing and fixing parallel issue with reporters that operate on data collected from samplers

### LINKED ISSUE #26530: Get optimization reporter reductions working in parallel
## Bug Description
ParsedVectorVectorRealReduction does not have the correct data in parallel and sometimes segfaults.

## Steps to Reproduce

The following test will segfault if run in parallel:
/moose/modules/combined/test/tests/optimization/invOpt_multiExperiment

## Impact
This can be fixed by changing the reporter_mode_context from REPORTER_MODE_REPLICATED to REPORTER_MODE_ROOT and by performing a check on the data.  By using REPORTER_MODE_ROOT, the reporter can also be gotten in the constructor instead of finalize which fixes reporter dependency issues.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #26530

### CODE REVIEW

**Comment by lynnmunday** [comment]
@dschwen @loganharbour This fixes the issue with the reporters not be executed in the proper order that I talked you about on Wednesday.  Could you review and merge this?  This also has testing that fails without this fix.

**Comment by loganharbour** [comment]
Can you not add more than one test?

**Comment by lynnmunday** [comment]
@loganharbour  The input file tests all of the reporters I created.  I changed the test to make it run in parallel.  I'm not sure how else to test these.  The current test will fail without this fix.

**Review by loganharbour — APPROVED** [review]
Looks good.

I added two valgrind tests for sanity checks.

**Comment by lynnmunday** [comment]
Thanks @loganharbour

**Comment by lynnmunday** [comment]
@loganharbour or @dschwen would you merge this if the reviews are done?

**Pull request merged**
