### PR TITLE
A veritable feast of changes to PorousFlow

### LINKED ISSUE #8196: PorousFlow Task: Complete refactor of Materials
Notifying @cpgr .  I know you're away, but this is a major refactor, so i want to record here my rationale and what i've done.  I've still got a niggling feeling this is not a perfectly wonderful refactor - that there must be a better thing to do!  Also i'm not sure my actual implementation is the best.  It looks nice because generally it splits our Material classes into smaller chunks, but that makes the number of lines of code increase.  Also, the number of Materials is now almost double in most input file - we really need to write some Actions i think!

The general idea is that we now have two types of Material: a standard MOOSE Material that evaluates stuff at the quadpoints; and a new type of Material that evaluates stuff at the nodes.

To enable this, i've created a new PorousFlowMaterial from which all our Materials derive.  It is simple: it just has a parameter _nodal_material that may be set by derived classes.  If this is false then the derived Material behave as normal, otherwise a resizing of the Material Properties to the number of nodes occurs, and a loop over the number of nodes is performed (rather than a loop over the number of qps).

Why do this?

As you know, we have to lump and upwind, so these "nodal Materials" are necessary.  However, DiracKernels reinitialise Materials every time they do a residual or jacobian calculation, and the number of quadpoints in an element is equal to the number of Dirac points in that element.  Oh dear, that means that the standard Materials won't be sized correctly!  These new "nodal Materials" will be sized correctly, however.

It also allows us to remove PorousFlowNodeNumber.

### PR DESCRIPTION
**Pull request by WilkAndy**
Reviewers, enjoy yourselves!  Tagging @cpgr , @yidongxiainl , @huangh-inl .

This is a major refactor of PorousFlow's Material system.  Most classes and all test files are affected.

All PorousFlow Materials now derive from PorousFlowMaterial that has a bool _nodal_material that gets set by all derived classes.
If the derived class sets _nodal_material to false then the class is a standard MOOSE Material, with Properties computed at the quadpoints.
If the derived class sets _nodal_material to true then the Properties are sized to _current_elem->n_nodes(), and the Properties may therefore be computed at the nodes of the element.

As explained in #8196, these new "nodal" Materials are necessary in PorousFlow because we lump and upwind in the Kernels.

The current implementation is quite pleasing because it means most of our Material classes actually REDUCE in size.  This is because we were previously computing Properties at both the quadpoints and the nodes using copy-and-pasted bits of code, but now we simply compute the Properties at "_qp" which stands for a quadpoint if _nodal_material=false, and node_number if _nodal_material=true

Also, for certain simulations this implementation will be faster because some Material Properties (either quadpoint or nodal) don't need to be computed, and for all simulations this implementation will not be slower than previous.

The nearest-node stuff is now almost always unnecessary and PorousFlowNodeNumber has been eliminated.  Only in non constant-strain finite elements when porosity is dependent on volumetric strain is the nearest-node stuff needed, and I've added an appropriate flag in those Materials and related Kernels for users to set in this unusual case.

The downside is that the number of Materials in input files can double compared with before, because both quadpoint and nodal versions of the Material Properties are needed.  This will eventually be invisible to users through the use of Actions.

Along the way I have fixed up numerous errors where we accidently used quadpoint or nodal versions of Properties, but should have used the opposite one.  That's another nice feature of this implementation - everything is much clearer.  In a similar vein, Porosity is now much more robust.  Because porosity-at-the-nodes depends on volumetric strain, which depends upon gradients of displacements, which are evaluated at quadpoints, the derivatives are quite complicated, and I've fixed this up in the Materials and Kernels.

I've also added some more tests as i saw fit, and have made resizing of Material Properties consistent (and hopefully correct!) to avoid segfaults.

Fixes #8196
Refs #8046

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]
I agree with the concept and have no complaints about coding convention stuff, but it would be good for someone else more familiar with the physics to also sign off on this.

**Comment by WilkAndy** [comment]
That's really good news, thank you @jwpeterson .  I was dreading you saying the whole thing was crazy for some reason.

Regarding someone looking at the physics: unfortunately @cpgr (the other main contributor to PorousFlow) is away until sometime in January.  Perhaps to encourage a merge from you I can say that prior to this contribution PorousFlow only worked for situations with number_nodes = number_quadpoints, but this generalisation allows things like DiracKernels to work (finally!).

**Comment by cpgr** [comment]
I think these changes are great @WilkAndy - remembering whether to use a `_qp` or `_nodal` property was a real pain. Thanks for this.

**Comment by friedmud** [comment]
I'm also for these changes.  There is a long history of using _qp to mean
"current point"... just look at nodal AuxKernels and DiracKernels.

**Comment by WilkAndy** [comment]
Thanks guys,

a

**Comment by WilkAndy** [comment]
Thanks @jwpeterson , @friedmud , @cpgr for your review and merge of this enormous commit.  Have a happy Christmas!

a

**Pull request merged**
