### PR TITLE
Adding offset vector to mortar constraints

### PR DESCRIPTION
**Pull request by ttruster**
Add capability for vector offset between primary and secondary sides of mortar surface. References https://github.com/idaholab/moose/discussions/25802

## Reason
Current automatic mortar generation only searches for intersections along the secondary unit normal. Adding an offset vector lets the same system work for other cases where the search is not along the unit normal by internally shifting the coordinates of the primary side before the search.
Example use case: for weakly enforcing periodic boundary conditions for homogenization problems where the domain boundary is not rectangular, such that pairs of faces are not directly opposite each other in the normal direction.

## Design
Add a parameter `boundary_offset` into the `MortarConsumerInterface` which defaults to the zero vector. Add this vector at all appropriate places internally for computing the mortar segments and their quadrature point locations.

## Impact
Adds a new parameter to `MortarConstraint` objects.

### CODE REVIEW

**Comment by ttruster** [comment]
I plan to modify the Mortar Constraint documentation page about this parameter, and to include a warning of the potential unintended uses of this feature. In particular: for tensor mechanics, using this to couple two bodies that are not separated by their normal direction will violate conservation of angular momentum...

@hugary1995, I haven't done profiling for anything except Matlab; can you point me to a link for that in C++?

**Comment by lindsayad** [comment]
You can see our our profiling doc page [here](https://mooseframework.inl.gov/application_development/profiling.html)

**Comment by hugary1995** [comment]
I'd first pick a representative example (maybe a mortar constraint problem of a decent size) and run it with and without your changes. If there is a noticeable difference in the overall wall time, we can discuss how to proceed. There are two ways to optimize as I see it:
1. Profile the example and look at the cost of the lines of the code that you added, and see which one is the "bottleneck". Then we can think about how to make it faster, if possible. The page that @lindsayad referenced is a good starting point. I can help if you have trouble building moose with gperftools.
2. As I mentioned in the discussion thread, we could add an option in the configure script, e.g. `--with-mortar-offset`, and guard your code with something like
```cpp
#ifdef MORTAR_OFFSET_ENABLED
  v = v + offset;
#endif
```
which will completely remove the additional costs if the user choose not to use this feature.

**Comment by lindsayad** [comment]
What I suspect is that this cost will be small compared to other costs

**Comment by hugary1995** [comment]
Yep, I agree.

**Comment by lindsayad** [comment]
@ttruster it seems like this PR was pretty close to a mergeable state. The only issue I see in testing is the distributed mesh failure on the Framework 2 recipe. Did you want to try and finish this?

**Comment by ttruster** [comment]
I got the email notification for this yesterday. Yes my intention would be to finish. One thought I had though was to allow a computed offset, instead of requiring values typed in the input file. I was going to base it on the Periodic BC transformation input.

Thoughts about that? I will do something over the weekend to keep it active. I know I also need to modify the doc files about it to mention the offset.

**Comment by ttruster** [comment]
To elaborate, I'm thinking of letting the offset be a "function" or "functor" so that it can be computed by the mesh geometry in MOOSE rather than needing to be typed in the input file.
I'm looking at the notes here: 
https://mooseframework.inl.gov/syntax/Functions/index.html
Do you think that is viable, or are functions only computed after the mesh generation stage is done? Namely, I think the offset needs to be computed before the automatic mortar surfaces are generated.

**Comment by lindsayad** [comment]
Functions are evaluated on-the-fly. `Function` classes are constructed before the mortar mesh is generated so that shouldn't be a concern

**Comment by ttruster** [comment]
I'll attempt to modify some things in the next few days to keep this active; we're in our exam week now.
@lindsayad, are there any good source code examples of calling Functors within a Kernel or Constraint, which I could emulate?
https://mooseframework.inl.gov/syntax/Functors/index.html

**Comment by lindsayad** [comment]
One framework finite element example is the integrated bc `FunctorNeumannBC`. There's also the aux kernel `FunctorAux`. There's quite a few examples in postprocessors like `ElementIntegralFunctorPostprocessor`. If you need some more examples let me know

**Pull request closed without merging**
