### PR TITLE
Update libmesh

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:

- Exodus improvements
- Update metaphysicl
- ExodusII_IO: Fix indexing issue in read_elemental_var_values().
- Add member function sub_matrix in DenseMatrix
- Assert consistent ErrorVector values for flagging
- Remove deprecated Elem API calls.
- shared_ptr<GhostingFunctor> support
- The 'node' variable is now used independently of setting unique ids.
- DofMap::local_variable_indices() bugfix
- Overzealous warnings in distributed corner case
- CheckpointIO support for extra DofObject integers
- Forward declare DualNumber in order to use DenseMatrix<DualNumber>
- Drop long-deprecated Elem APIs.
- Two updates to PR #2103.
- Add FEMContext::interior_rate_gradient
- Mesh stitching fixes for NodeElems
- MeshBase::add_elem_integer() API
- GenericProjector rewrite
- Subdomain-restricted variables hanging nodes fix
- Fix 2006 bug with refinement within ES::reinit()
- DofMap::reinit_send_list(), Overlapping Coupling Test
- Fix remote_elem copying in UnstructuredMesh
- Only skip noncritical partitioning in BoundaryMesh
- Add outer product for TypeVectors
- Remove redundant (and shadowing) fe
- Factor out a DenseMatrixBase implementation header
- Re-implement parallel sync using the NBX algorithm
- Drop VecScatterCreateWithData() workaround.
- Revert changes from #2078 to rb_construction.C.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Can we wait a little on @roystgnr 's PR https://github.com/libMesh/libmesh/pull/2108? With that the extra integer support would be complete.

**Comment by lindsayad** [comment]
> Can we wait a little on @roystgnr 's PR [libMesh/libmesh#2108](https://github.com/libMesh/libmesh/pull/2108)?

Sure

**Comment by roystgnr** [comment]
Sorry for the delay!  It's in now.

**Comment by andrsd** [comment]
Could we wait with this until my libMesh/libmesh#2123 is merged? It is a small change, so hopefully it will be merged soonish...

**Review by permcody — APPROVED** [review]

**Pull request merged**
