### PR TITLE
Fix problem with lost output after patch update

### LINKED ISSUE #4613: PETSc output gets lost on steps when the contact patch is updated
If the 'patch_update_strategy = auto' option is set, all output about solver progress gets lost on that step.

I have a patch for this that I'll submit shortly.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #4613

### CODE REVIEW

**Comment by permcody** [comment]
I'm not sure I understand. What exactly is getting lost? Are you losing output due to a crash? Are you sure this is the right location? Generally we want std::endl to appear at the end of some message not at the beginning of some other message. While it might seem like it doesn't matter, if we change the order of something than it starts to matter, or if it becomes part of a multiapp it might matter. Can we dig in a bit more to understand what's getting lost? I'd be willing to help.

**Comment by bwspenc** [comment]
@permcody When the patch gets updated, we are losing all output that was coming from PETSc and from PETSc callback functions for the current step.  It came back in the following step because the initialization stuff for the PETSc output console gets done every step.

I'm not sure what you mean about std::endl.  I did put it at the end of that message.  Without that change, that message that I added std::endl to shows up at the end of all of the iterations for that step, rather than at the beginning of the step, when the patch update happens.

**Comment by permcody** [comment]
To clarify, what I mean is that you are flushing that message to force output that was buffered from something else that just happened and is still in the buffer. My thought is that the flush belongs on that something else, not this message.

**Comment by permcody** [comment]
@bwspenc we might hold onto this as @aeslaughter wants to try flushing the buffers before doing the linear and nonlinear steps. If his patch works, this patch should no longer be necessary.

**Comment by bwspenc** [comment]
@permcody I don't think that would fix the problem with losing the PETSc output, though.  Also, I'd like to have the buffer flushed after that message and before the solver reinit happens anyway.

**Comment by aeslaughter** [comment]
I think this should be good to merge, provided #4619 does its job.

**Comment by jwpeterson** [comment]
@permcody are we voting on whether or not to have a `std::end`?

**Comment by aeslaughter** [comment]
My vote, merge with the std::endl;. As @bwspenc states, it prints sooner if the following steps are slow.

**Comment by permcody** [comment]
This is fine to merge. I didn't want it merged if it was a hack to fix output (flush something in the buffer that should be flushed by the code putting the information in the buffer). In general we need to clean MOOSE output up as much as possible. The issue here is that this code is printing to the console buffer while PETSc is not so if it's not flushed it comes out in the wrong order! 

A better solution would be to get PETSc printing to the same buffer that _console holds onto so that whether it is flushed or not doesn't change the output order.

**Pull request merged**
