### PR TITLE
Enable building c++ opt without -O2 optimization

### LINKED ISSUE #18777: Honor ADDITIONAL_CPPFLAGS last in building
## Reason
We can't currently override `-O2` set in libmesh_CPPFLAGS within moose.mk because all of our insertion points are inserted before `libmesh_CPPFLAGS`. We would like to use `-O0` when building for coverage.

## Design
Evaluate `ADDITIONAL_CPPFLAGS` after `libmesh_CPPFLAGS` in build.mk.

## Impact
With the options that we currently supply in `ADDITIONAL_CPPFLAGS` in CI, this shouldn't change anything that is currently running in production but will allow us to compile with `-O2` when desired.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #18777

### CODE REVIEW

**Comment by lindsayad** [comment]
I'm not necessarily against this change but a change that I would really like to see is to move `CXXFLAGS` behind `libmesh_CXXFLAGS`. This would be much more consistent for users who are familiar with other C++ projects. User requested `CXXFLAGS` should always win and right now they don't

**Comment by lindsayad** [comment]
Belay that ... @loganharbour verified that conda `CXXFLAGS` adds `-O2` so to prevent conda users from running into surprises when they run a dbg build through a debugger we need to make sure that `libmesh_CXXFLAGS` is behind `CXXFLAGS`.

**Review by lindsayad — DISMISSED** [review]

**Comment by loganharbour** [comment]
Should be good now. I suspect that we will need to change some tests that timeout now due to be ran with -O0 and opt.

**Review by lindsayad — CHANGES_REQUESTED** [review]
Because of conda I don't think we can do the CXXFLAGS switch-a-roo that I initially pulled for

**Review by lindsayad — DISMISSED** [review]

**Comment by loganharbour** [comment]
@lindsayad I just need corrections for:

```
10 longest running jobs:
--------------------------------------------------------------------------------------------------------------
[300.0s]  TIMEOUT kernels/ad_mat_diffusion.2D/ad_2D_steady_state_jacobian FAILED (TIMEOUT) [FINISHED]
[249.7s]       OK bcs/ad_function_dirichlet_bc.ad/test-jac
```

ran with `--n-threads 2` and `-O0`.

Push directly here; the tests are ready.

**Comment by loganharbour** [comment]
Once this passes and _before_ merging, we will add the new recipes in https://github.com/idaholab/civet_recipes/pull/88.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
