### PR TITLE
Plug some FV leaks

### PR DESCRIPTION
**Pull request by lindsayad**
Only buildFaceInfo and construct FVFluxThreads when we have FV

Refs #15049

### CODE REVIEW

**Comment by lindsayad** [comment]
@loganharbour @rwcarlsen @fdkong starting to look at some of these things...

**Review by rwcarlsen — APPROVED** [review]

**Comment by rwcarlsen** [comment]
FWIW the flux thread loop already checks for fv objects and aborts if there are none.  So the only thing that matters is we don't call faceInfo and trigger the lazy construction of faces.

**Comment by lindsayad** [comment]
> FWIW the flux thread loop already checks for fv objects and aborts if there are none. So the only thing that matters is we don't call faceInfo and trigger the lazy construction of faces.

I figured that was probably the case

**Comment by roystgnr** [comment]
@lindsayad, you're 100% sure about https://github.com/libMesh/libmesh/pull/2552#issuecomment-624994113 ?  I'm just saying, all the Test-with-threads CI runs *before* you merged an FV change *weren't* dying with a failed FV test...  :raised_eyebrow:

**Comment by lindsayad** [comment]
Ah yes, I thought about appending that the failure wasn't my fault in libMesh, but it may still have been my fault! Hahaha

**Pull request merged**
