### PR TITLE
Filter out valid non-petsc options

### LINKED ISSUE #25577: Need to remove moose app command-line options from the list of petsc options
## Reason
If we add `-options_view` option on command line, which will print PETSc option table entries at the end of simulation when `PetscFinalize` is called, we will see `-i foo.i` in the list, which is not one of petsc options. If we add `-options_left` on command-line, this will generate a false warning saying that `there are options you set that were not used` from PETsc.

## Design
When passing command-line to PETSc, we possibly should remove those options from MOOSE application, i.e. options declared in `MooseApp`. Otherwise, we may see this false warning if the `-options_left` is turned on programmatically. (I do not know how this option is turned on in MOOSE.) Tag @lindsayad 

## Impact
No impact to calculations but rather a possible false warning that annoys users.

### PR DESCRIPTION
**Pull request by pbehne**
This PR uses functionality in libmesh to add valid MOOSE command line parameters to a "safe list" so they are not interpreted by petsc as unused parameters. This implementation has the added benefit that any invalid command line parameters are still passed to petsc, which then warns the user.

Closes #25577

### CODE REVIEW

**Comment by lindsayad** [comment]
Hey @pbehne, I pulled this down to test and noticed when I removed `-options_left` from the input that we weren't seeing the unused option printed, which is what I expected remembering that @cticenhour had put his `-options_left` removal in some file other than `MooseApp`. And then grepping I found the occurrence in `PetscSupport`. So I've removed that. I decided to keep the removal of `-options_left` from that input file as now the input tests multiple things:
1. the default in PETSc since 3.19 is to warn users about unused options, e.g. the user doesn't have to manually supply `-options_left` to get that information
2. your change here: to *not* warn about MOOSE command line options

Let me know if you're ok with https://github.com/idaholab/moose/pull/27477/commits/7064d1a4455fc7542f441046dd66e906325ef5dc

**Comment by pbehne** [comment]
@roystgnr, when I run the MOOSE test suite, I get the following unused warning with each test:

`Option left: name:--no-gdb-backtrace (no value) source: command line`

Since `--no-gdb-backtrace` is a libmesh option not used by MOOSE, I think we need to add it to the safe list within libmesh. Could you check why this is not already happening and add it?

**Comment by lindsayad** [comment]
If I had to wager a guess, it is because we no longer configure libmesh with gdb backtraces enabled. We configure libmesh with `--without-gdb-command`. Presumably libmesh would add that command line option if we did have a gdb command. probably the right thing to do is to stop passing `--no-gdb-backtrace` in the test harness

**Review by lindsayad — APPROVED** [review]

**Comment by pbehne** [comment]
@lindsayad NEAMS MP project

**Pull request merged**
