### PR TITLE
No comment

### PR DESCRIPTION
**Pull request by andrsd**
Refs #000

### CODE REVIEW

**Comment by friedmud** [comment]
LOL - WTH is this stuff??

**Comment by permcody** [comment]
I think we'll leave the responsible party's name off this PR to avoid any potential humiliation. We should probably just delete simple diffusion altogether from contact.

**Comment by dschwen** [comment]
Yeah, fortunately there is [no way](https://github.com/idaholab/moose/blob/2bf9a13ed667d62aae44f4410ba7d689855c04af/modules/contact/tests/kernels/simple_diffusion/simple_diffusion.i~HEAD_0) of finding out who the responsible party might be...

**Comment by andrsd** [comment]
@dschwen The author and the committer are two different people...

**Pull request merged**
