### PR TITLE
Add slave slide Jacobian contribution from displacements

### LINKED ISSUE #14626: Add master/slave coupling terms in GapHeatTransfer
## Reason
In the current (not mortar) system that we use for thermal contact enforcement, we are using integrated BCs (GapHeatTransfer) to apply the flux on the two sides of the interface.

It's well established that most of the convergence issues that we are having in thermo-mechanical problems with contact come down to GapHeatTransfer. We had always assumed that they were because the conductance is a highly nonlinear function of the displacement, and we're not getting those terms right in the Jacobian.

However, we were looking at a very simple small problem that has convergence issues, and realized that the problem here is that we're not including the coupling terms between the master and slave surface for the temperature variable. That problem has a constant conductance, no coupling between thermal and mechanics, and still experienced very poor convergence. The on-diagonal terms in the Jacobian are spot-on, and the off-diagonal terms are wrong because they're missing this contribution.

## Design
Since we are developing the mortar-based system that will ultimately replace this, I don't think it makes sense to do a major re-design of this system. If we can access the needed off-diagonal Jacobian entries from the existing IntegratedBC, I think it's worthwhile to patch that code to fix this.

## Impact
This would not change any code interface or usage, but it is expected to vastly improve convergence of this class of problems.

### PR DESCRIPTION
**Pull request by lindsayad**
@bwspenc I'm going to need you to come up with a test case for this. I can tell you that this change appears to not affect the Jacobian in @jiangwen84's problem. The Jacobian ratio for the first Jacobian evaluation is 1.44 both before and after this PR. This is an awful ratio; ideally it would be on the order of 1e-8. I can see clear culprits for the bad Jacobian are the derivatives of the temperature with respect to the displacements. But these missing off-diagonal entries are not due to `ThermalContact` in @jiangwen84's input file. Indeed if I comment out the `ThermalContact` block the Jacobian ratio actually gets worse! It goes to 205.

I've verified that we at least go through the new off-diagonal computing path, but for this problem for the first jacobian eval, grad_t at the interface is zero, and it is still quite small for the second jacobian eval, so the off-diagonal Jacobians should be small for thermal contact. Hence it would be great if you guys can drum up a new good test.

Will close #14626

### CODE REVIEW

**Comment by bwspenc** [comment]
@lindsayad Thanks for putting this together.  Yes, I can work on a test case.

In the case of @jiangwen84's problem, we know the thermal part of the Jacobian is spot-on because if we turn off the displaced mesh, we have a relative error of 1e-8 or so. It's somewhat off as you noted when we include mechanical deformation, which is a little odd because the conductance is constant in that case.  I think it is due to the fact that the thermal strains change the cross-sectional area that the BC is applied on (it looks like the ThermalContact action sets use_displaced_mesh=true for that). 

The term that you just implemented accounts for the dependence of the conductance on the gap size, which I think is a far more important effect.

**Comment by bwspenc** [comment]
The test case for this is going to have to use a non-constant conductance.

**Comment by lindsayad** [comment]
I wanted to suggest that I think the temperature kernels (I guess actually only `HeatConduction` here) have bad Jacobians with respect to the displacements. I see that `use_displaced_mesh = true` is the default for `HeatConduction` (which makes sense to me!) but there is nothing for `computeQpOffDiagJacobian` there.

**Comment by lindsayad** [comment]
Indeed if I change from using `HeatConduction` to `ADHeatConduction`, the (initial) Jacobian ratio goes from 1.44 to 5.32e-7. The second Jacobian eval ratio is still a little higher than I would like: 9e-2

**Comment by lindsayad** [comment]
> The second Jacobian eval ratio is still a little higher than I would like: 9e-2

This highish Jacobian ratio is coming from some still imperfect piece of the ThermalContact Jacobian, perhaps because of the cross-sectional dependence you mentioned. If I turn off `ThermalContact` and use `ADHeatConduction`, the Jacobian is perfect for both non-linear iterations.

**Comment by bwspenc** [comment]
I just tried this out on the LWR fuel example problem that I was testing your previous fix on.  It was not set up to use the full Jacobian matrix for preconditioning (because we've had spotty success using that before). I set it to use the full Jacobian because you need that to show the effect of this fix.  Here's what I get:
Before this fix: 173 s, 3009 residual evaluations
After this fix: 94 s, 1395 residual evaluations

Needless to say, I'm pretty stoked! I'm sure there's more performance/robustness to be squeezed out of this by switching to AD and mortar, but this is going to have an immediate major positive impact on every fuel problem out there.

**Comment by lindsayad** [comment]
Ok, so for both runs you had the full Jacobian? And when you say before/after this fix, you mean just this PR right, e.g. both your runs had the previous fix? (#14645) Just want to make sure that this big gain came from this PR alone. (I know you said there was a (relatively small) gain from #14645 for LWR)

**Comment by bwspenc** [comment]
Yes, both runs used the full Jacobian.  Prior to this current change, the run time was not affected that much by whether we used the full Jacobian because it wasn't very helpful.

The "before this fix" case had your prior fix in it, so this difference is only due to adding the term coupling with displacement. There was a modest improvement with your other fix as well, but the numbers are just looking at the isolated effect of this fix.

**Comment by lindsayad** [comment]
@bwspenc https://github.com/idaholab/moose/pull/14659/commits/e1e763ff5610279d3c4b168c0cfd4c1a5aca63d2 should resolve the BISON test failure in debug mode

**Comment by lindsayad** [comment]
> Before this fix: 173 s, 3009 residual evaluations
> After this fix: 94 s, 1395 residual evaluations

This is awesome!

**Comment by permcody** [comment]
@lindsayad - Are we still working on a test case for this?

**Comment by lindsayad** [comment]
Yes, @bwspenc is working on that

**Comment by bwspenc** [comment]
@bwspenc really wants to work on it -- as soon as he finishes pushing proposal paperwork...

**Comment by permcody** [comment]
> @bwspenc really wants to work on it.

Wow you are referring to yourself in the third person. Hope you aren't going too crazy with that effort!

**Comment by bwspenc** [comment]
@lindsayad Sorry it took me so long -- I finally put together a test for this and added it to this PR.  I took the test you had previously to test the master/slave thermal coupling terms, and made it have more coupling with mechanics by adding thermal expansion.  I also added mechanical contact to it because the surfaces were penetrating.  It converges in about 10 NL iterations.  I think we can do better than that if we further improve the Jacobian, but we're light years ahead of where we were before your code changes in this PR -- it really struggles without those changes.

**Comment by bwspenc** [comment]
@permcody I'm good with all of the code changes here, but since I'm adding a test here, we should have someone else review this.  If you could review this, I'd appreciate it.

**Review by bwspenc — APPROVED** [review]

**Review by permcody — APPROVED** [review]

**Pull request merged**
