### PR TITLE
Properly restore MultiApps when only some failed

### LINKED ISSUE #12477: Problem with restoring MultiApps when only some failed
## Rationale

If a master has two sub apps and only the first one fails, the time step of the master app is not cut, as it is if only the first one was used by the master app.

## Description

This error can be reproduced by adding a second non-failing subapp to `moose/test/tests/multiapps/picard_failure/picard_master.i`.

It seems that the culprit is: https://github.com/idaholab/moose/blob/devel/framework/src/problems/FEProblemBase.C#L3542

I believe it should be:

```
for (const auto & multi_app : multi_apps)
  success = multi_app->solveStep(_dt, _time, auto_advance) && success;
```

and not:

```
for (const auto & multi_app : multi_apps)
   success = multi_app->solveStep(_dt, _time, auto_advance);
```

I will send in a PR shortly.

## Impact

Fixing this bug will allow to recover properly when only one subapp failed.

### PR DESCRIPTION
**Pull request by vincentlaboure**
Closes #12477

### CODE REVIEW

**Comment by vincentlaboure** [comment]
It would be good to have a test in parallel but `NanAtCountKernel` does not seem to work in parallel and I do not know any other (easy) way to make a subapp fail.

**Comment by vincentlaboure** [comment]
On another note, I tried to not add another master input file but it looks that if I use `cli_args='Outputs/file_base=something'`, the names of the output files created by the subapps are unchanged. Is that intended?

**Comment by permcody** [comment]
Tag @friedmud

**Comment by permcody** [comment]
Thanks Vincent! This looks good.

To answer your question about CLI overrides. We have special syntax where you can override just a single app on the command line. If you use the "normal" syntax it gets applied to all apps. Take a look at the examples of how to just override one app:
https://github.com/idaholab/moose/tree/next/test/tests/parser

**Comment by vincentlaboure** [comment]
Sounds good. I did follow that syntax to remove the extra input file.

Is there an easy way to add parallel testing?

**Comment by permcody** [comment]
In MOOSE - Everything is tested in serial, parallel, with threads, etc. We hit those tests hard. It's a much different story in the modules and applications. So you don't need to do anything else to run these tests in several configurations, that'll just happen.

**Comment by vincentlaboure** [comment]
But in that case, the tests have `max_parallel = 1`, `max_threads = 1` because `NanAtCountKernel` would behave differently in parallel. So really we cannot test in parallel with that kernel.

**Review by friedmud — APPROVED** [review]
This looks good to me.  Thanks!

**Pull request merged**
