### PR TITLE
rm yaqi hacky 7126

### PR DESCRIPTION
**Pull request by WilkAndy**
Finally i can remove this.

Lots of tests re-jigged - explanation is in the commit message if anyone is super interested.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Oh yea, let's thrash those testing computers!

**Comment by permcody** [comment]
Umm, No... 
We don't guarantee evaluation based on ordering in the input file. If there's a bug here we need to deal with that too. I'll take a look at that before we merge. This might be something else @aeslaughter can look at quickly too. It looks like your PourousFlowTempurature consumes "PourousFlow_node_number" and "PourousFlowNodeNumber" produces that property. We have tests for that case so perhaps it's just a "sorting" issue that's only rearing it's head due to these both being stateful properties?

**Comment by aeslaughter** [comment]
I am working on this.

**Comment by WilkAndy** [comment]
You are correct, @permcody.  PorousFlowTemperature uses PorousFlowNodeNumber, and currently all the tests work if NodeNumber comes first in the input file.  It would be great if MOOSE didn't need the ordering to be correct.

**Comment by WilkAndy** [comment]
Cool, thanks @aeslaughter .   You've done lots of things for me lately - thanks.

**Comment by aeslaughter** [comment]
@idaholab/moose-team 
This has un-covered a problem with Material object execution. We have them setup to accept the "execute_on" flag, but we don't honor it, even with the patch I put in the other day. 

We need to be passing the proper execution flag to reinitMaterial, etc. so only the materials with the given flag are recomputed. Of course, this idea of execute_on only really makes sense for stateful properties. I am not sure what the proper solution is here: perhaps a stateful/non-stateful storage of materials, where the stateful honor the execute flag and the non-stateful do not. We could produce a warning that the execute flags are being ignored in the later.

**Comment by permcody** [comment]
OK - several separate issues here:

First there's @friedmud's `ConstantMaterial` idea which is one small vector that's just available everywhere and you can't change it: #6979. That's a separate idea from `execute_on` materials which is much trickier.

If you *really* want to support `execute_on`on materials we'll need lots of extra help from the framework to make sure they work right. 
 * Only stateful materials could support execute_on (Some sort of run_time check)
 * They'd have to be restricted to `'initial timestep_begin nonlinear'`
 * MOOSE would have to detect this and manage these properties separately (i.e. not moving them backwards in time)

Nothing short of handling all that will makes any sense.

**Comment by WilkAndy** [comment]
I don't think i need execute_on in Materials.  I know i have a flag "on_initial_only" in PorousFlowNodeNumber, but that works well as it is, and it's just pre-emptive optimisation really, as i have no idea if computing NodeNumber is very expensive (i'm guess it's very inexpensive).

**Comment by aeslaughter** [comment]
I am working on this in a separate PR: #7717.

**Pull request closed without merging**
