### PR TITLE
Fix getMaterialPropertyDerivative in multiapps

### LINKED ISSUE #9557: getMaterialPropertyDerivative fails with constant props in MultiApp setting
### Description of the enhancement or error report

If `getMaterialPropertyDerivative` is called in different dimension applications in a `MultiApp` and the property is constant in both apps (e.g. the derivative property is zero in both apps), then you will get an assertion error when running in `dbg` mode. From some preliminary investigation, I believe this is because a 'zero property' is created with size equal to the number of quadrature points of the app that is initialized first, and then this property is never resized.

### Rationale for the enhancement or information for reproducing the error

This error can be reproduced by running the following input files with `PhaseFieldApp` compiled in dbg mode.

Master:
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 1
  ny = 1
[]

[Variables]
  [./diffused]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./diff]
    type = MatDiffusion
    variable = diffused
    D_name = diffusivity
  [../]
[]

[BCs]
  [./bottom]
    type = DirichletBC
    variable = diffused
    boundary = 'bottom'
    value = 1
  [../]

  [./top]
    type = DirichletBC
    variable = diffused
    boundary = 'top'
    value = 0
  [../]
  [./left]
    type = DirichletBC
    variable = diffused
    boundary = 'left'
    value = 1
  [../]
  [./right]
    type = DirichletBC
    variable = diffused
    boundary = 'right'
    value = 0
  [../]
[]

[Materials]
  [./blockDiffusivity]
    type = DerivativeParsedMaterial
    f_name = diffusivity
    function  = '1.0'
    args = diffused
    derivative_order = 1
  [../]
[]

# [Materials]
#   [./blockDiffusivity]
#     type = GenericConstantMaterial
#     prop_names = 'D'
#     prop_values = '1'
#   [../]
# []

[Executioner]
  type = Transient
  num_steps = 1
  solve_type = 'PJFNK'
[]

[Outputs]
  execute_on = 'timestep_end'
  exodus = true
[]

[MultiApps]
  [./loopApp]
    type = TransientMultiApp
    app_type = PhaseFieldApp
    execute_on = timestep_begin
    positions = '0 0 0.0'
    input_files = 'sub_simple.i'
  [../]
[]
```
Sub:
```
[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 1
[]

[Variables]
  [./diffused]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./diff]
    type = MatDiffusion
    variable = diffused
    D_name = diffusivity_sub
  [../]
[]

[BCs]
  [./left]
    type = DirichletBC
    variable = diffused
    boundary = 'left'
    value = 1
  [../]
  [./right]
    type = DirichletBC
    variable = diffused
    boundary = 'right'
    value = 0
  [../]
[]

[Materials]
  [./blockDiffusivity]
    type = DerivativeParsedMaterial
    f_name = diffusivity_sub
    function  = '1.0'
    args = diffused
    derivative_order = 1
  [../]
[]

# [Materials]
#   [./blockDiffusivity]
#     type = GenericConstantMaterial
#     prop_names = 'D'
#     prop_values = '1'
#   [../]
# []

[Executioner]
  type = Transient
  num_steps = 1
  solve_type = 'PJFNK'
[]

[Outputs]
  execute_on = 'timestep_end'
  exodus = true
[]
```
### Identified impact

This is a bit of a corner case, so not high priority; I'm a bit surprised we ever ran into it. But if it happened once, it can happen again. There are easy hacks to get around this, e.g. specify a function like `1.0 + 1e-16*diffused`, but it would be nice for this to work as expected.

### PR DESCRIPTION
**Pull request by dschwen**
@lindsayad confirmed this closes #9557

### CODE REVIEW

**Review by andrsd — COMMENTED** [review]
This fixes the problem, but the real problem is actually in having `static MaterialProperty<T> zero;` part of `MaterialPropertyInterface`.  There should be one instance per `FEProblem` and then `getMaxQps` without resizing would just work. Similarly like we have it with _zero, _grad_zero, etc.

The zero material properties could live in `MaterialData` (not necessarily in `FEProblem`), but the trick would be to get all the templated versions there and then get the right references back in `getZeroMaterialProperty`.

I am assuming @dschwen does not want to do this, right?

**Comment by dschwen** [comment]
No, I don't want to do this. This is a bit more complicated than `_zero`, because I rely on templating here! The static property can have an arbitrary type.

**Comment by dschwen** [comment]
I guess it would be possible if there was a templated function in FEProblem(Base) that would then insert the zero property for a given type into MaterialData (where it is held as a base class pointer).
I'm not sure though it even belongs in MaterialData

**Comment by andrsd** [comment]
> I'm not sure though it even belongs in MaterialData

May be there is a better place.

Yes, it should be possible, but it won't be a small patch...

**Comment by andrsd** [comment]
So, I think we will go with this for right now...

**Review by andrsd — APPROVED** [review]

**Comment by andrsd** [comment]
I opened #9561 for fixing the design and assigned it for the upcoming tiger team. Hopefully, I will get to fix it then.

**Pull request merged**
