### PR TITLE
Addfreundlich

### LINKED ISSUE #22382: Add support for Freundlich isotherms as an InterfaceKernel
## Reason
The Freundlich isotherm is a commonly accepted model representing sorptivity at an interface which empirical data has been fit to. This is necessary to model solid-vapor interface equilibrium. A henrian regime is also included for low concentration calculations, with a transition region determined by material properties.

## Design
Add an interfacekernel, FreundlichPenaltyInterface, which accepts material properties relevant to the interface (these are properties relevant in the solid phase defaulting to As, Bs, Cs, Ds, Es, d1s, d2s). I have a current implementation, but it does not seem to work well with changes in temperature over time across the interface.

## Impact
Will allow Freundlich isotherms to be modeled.

### PR DESCRIPTION
**Pull request by ke7kto**
Closes #22382

Not sure which module would be most appropriate to add this functionality to.

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
So it sounds like this is for mass transfer? If so, this seems like it could be a good fit for the upcoming scalar transport module. You will need to rebase your work on top of the `next` or `devel` branches. It looks like you're currently based on top of `master`, which is why your PR introduces 5,446 commits. You'll also need to add some documentation of the new object as well as a test

**Comment by ke7kto** [comment]
Yes. This is for mass transfer. I will rebase, sorry about that. I'm not sure how to make a test for an interfacekernel. How does that work?

**Comment by lindsayad** [comment]
> Yes. This is for mass transfer. I will rebase, sorry about that. I'm not sure how to make a test for an interfacekernel. How does that work?

Use it in an input file that gets run by the test harness. I might suggest weighting a week or two for us to submit the pull request that creates the scalar transport module (we are waiting on final export control approval), because I think this object fits the best in that module

**Comment by lindsayad** [comment]
https://github.com/idaholab/moose/pull/22392 will introduce the `scalar_transport` module which would be a good place for your code

**Pull request closed without merging**
