### PR TITLE
Add stationary ray capability

### LINKED ISSUE #26591: Allow stationary rays
## Reason
It could be useful for testing and for running point objects in the ray tracing system to allow stationary rays.

## Design
Add a way to generate rays that are stationary (max distance = 0).

## Impact
New capability.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #26591

### CODE REVIEW

**Comment by loganharbour** [comment]
FYI @gsgall

**Comment by loganharbour** [comment]
@gsgall I gave an attempt to get the ray exodus output to work with this, and failed a tad. There's some libmesh issues we're going to have to resolve. Eventually, we'll get these output as well.

**Comment by gsgall** [comment]
> @gsgall I gave an attempt to get the ray exodus output to work with this, and failed a tad. There's some libmesh issues we're going to have to resolve. Eventually, we'll get these output as well.

I that should be fine for the purposes of the sort of verification problems I am planning on doing with this. but we should probably open this as a new issue if the plan is to resolve this outside of this PR.

**Comment by loganharbour** [comment]
Great idea, thanks @gsgall. Created #26604.

@cticenhour this is good to go.

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
