### PR TITLE
Removing DTK tests as a first step

### PR DESCRIPTION
**Pull request by permcody**
refs #7123

### CODE REVIEW

**Comment by friedmud** [comment]
Odd - I would think you would want to leave them in there and redo how they work... i.e. a "test first" kind of deal

**Comment by permcody** [comment]
Well these answers are so far off and @rppawlo didn't think they were very robust anyway. They've been broken for months and I'm just going to turn them off for now, not delete them.

**Comment by friedmud** [comment]
K

**Comment by rppawlo** [comment]
Just to follow up on @permcody 's comment - last summer/fall @sslattery and I tried to repair these tests for the DTK refactor. I don't remember all the details but I think we came to the conclusion that these tests had an implicit assumption in them about how DTK worked that was incorrect (the DTK interface code was correct but just something in the test was off). However all our acceptance tests for CASL coupling do pass. We concluded that a better thing to do was put in our exact CASL use cases as tests rather than spending more time on these.

**Pull request merged**
