### PR TITLE
Point locator fixes

### PR DESCRIPTION
**Pull request by roystgnr**
Set out_of_mesh_mode in more use cases; hopefully these are the last fixes required for forwards compatibility with https://github.com/libMesh/libmesh/pull/1240

Properly handle the out-of-mesh NULL return value when we're on a DistributedMesh and we're querying for data which might not be semilocal on each processor's part of the mesh; this fixes a #1500 regression failure in postprocessors/findvalueonline.line_out_of_bound for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
Ah.  This won't work without a libMesh update to a version incorporating https://github.com/libMesh/libmesh/pull/1249

**Comment by roystgnr** [comment]
Looks like the new PointLocatorTree code is missing some curved elements after all?  I'll see if I can reproduce.

**Comment by roystgnr** [comment]
Wait, I can't just invalidate; I need to bump the submodule hash...

**Comment by permcody** [comment]
Looks like many of those seg faults are using the GrainTracker...  I'm pretty busy today but I might be able to dig into this a little later.

**Comment by roystgnr** [comment]
Oh finally it all works again.

**Review by jwpeterson — APPROVED** [review]
👍 Assuming the latest round of testing works.  Both @bwspenc and @YaqiWang are waiting for new capabilities in this update.

**Comment by jwpeterson** [comment]
Hmm... I will push a fix for Yak, I guess it was relying on `mesh_base.h` to include `partitioner.h` somewhere.

Not sure about Marmot, @dschwen can you take a look and see if this is already being addressed somehow?

**Comment by jwpeterson** [comment]
Mammoth needs to have its Rattlesnake submodule updated... otherwise this should be good to go, other than the RELAP-7 issues which I will work on with @andrsd.

**Comment by jwpeterson** [comment]
Just barely missed getting the mammoth master update in time, but it should be working fine.

**Comment by brianmoose** [comment]
In case you didn't notice, the intel target has an exodiff in parallel: https://www.moosebuild.org/job/75002/
Also, this seems to be broken when building libmesh with `--with-dof-id-bytes=8` : https://www.moosebuild.org/job/75089/

**Comment by jwpeterson** [comment]
> Also, this seems to be broken when building libmesh with --with-dof-id-bytes=8

Crap, this one is a real type mismatch error:
```
../src/mesh/unv_io.C:1338:62: note:   ‘std::map<unsigned int, libMesh::Node*>::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const unsigned int, libMesh::Node*> >}’ is not derived from ‘const std::pair<_T1, _T2>’
               if (it == _unv_node_id_to_libmesh_node_ptr.end())
```

Do we only have 64-bit indices builds on the master merges?

**Comment by brianmoose** [comment]
Yes, that is only done on the master branch, although it can be added to a PR.

**Comment by jwpeterson** [comment]
OK, would it be difficult to manually enable 64-bit testing for libmesh PRs too?  I just opened libMesh/libmesh#1283, but I don't think it's possible to add 64-bit as an additional recipe to run.

**Comment by jwpeterson** [comment]
> In case you didn't notice, the intel target has an exodiff in parallel: 

I'm not too worried about this one:
```
==============================================================
NOTE: All node and element ids are reported as global ids.

  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
  --------- Time step 2, 1.0000000e+00 ~ 1.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
   u  rel diff:  9.7656296e-04 ~  9.7655743e-04 = 5.65487e-06 (node 513)
```
we might be able to fix it by using absolute tolerances or a custom comparison file...

**Comment by brianmoose** [comment]
The libmesh 64bit testing seems to be running now : https://www.moosebuild.org/job/75134/

**Comment by jwpeterson** [comment]
> The libmesh 64bit testing seems to be running now

Awesome, thanks!  And it looks like it built so there was only the one regression.

**Pull request merged**
