### PR TITLE
Updating PorousFlow theory.tex to include recently added materials

### LINKED ISSUE #9104: Document recent additions to PorousFlow
### Description of the enhancement or error report

@hsheldon has recently made two additions to PorousFlow.  Could she please add a line or two to doc/theory/theory.{tex,pdf} to document the new functionality?

### Rationale for the enhancement or information for reproducing the error

Keeping doco up to date.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Documentation

### PR DESCRIPTION
**Pull request by hsheldon**
Closes #9104

### CODE REVIEW

**Comment by hsheldon** [comment]
@WilkAndy

**Review by WilkAndy — APPROVED** [review]
This is just updating doco.  It's a bum that git doesn't understand you've just changed a few lines of the tex file.  Chris also found this.  Might have something to do with carriage-returns vs newlines, or something similar.

Anyway, the changes look perfect - thanks @hsheldon

**Comment by permcody** [comment]
I believe it does know. @brianmoose?

**Comment by brianmoose** [comment]
Currently the only check is for changes in the `docs` directory. Then it will only run the documentation. These files are in `modules` so it triggers everything.
I'll see about adding `.tex` and `.pdf` files to the documentation check.

**Review by permcody — APPROVED** [review]

**Pull request merged**
