### PR TITLE
Merging Solid and Tensor Mechanics

### LINKED ISSUE #5624: Merging Solid and Tensor mechanics
1. Moved files common to both tensor and solid mechanics (like pressure, pressure action, gravity, inertial force, NewmarkVelAux and NewmarkAccelAux) to tensor mechanics and made solid mechanics depend on tensor mechanics. 
2. Solid mechanics tests depending on any of the common files are moved to combined/tests/solid_mechanics
3. Renamed PressureTM to Pressure, PressureActionTM to PressureAction and GravityTM to Gravity

### PR DESCRIPTION
**Pull request by sveerara**
Closes  #5624

### CODE REVIEW

**Comment by dschwen** [comment]
Why are all the solid mechanics tests moved into the combined folder?

**Comment by sveerara** [comment]
When an external application includes SolidMechanicsApp, then all the
functions in TensorMechanicsApp is automatically included. However, when
SolidMechanicsApp cannot call any of the functions in TensorMechanicsApp by
itself. So if the tests are in Solid mechanics, then it will give an error
saying object is not registered.

**Comment by permcody** [comment]
@dschwen - turns out that this is the way the phasefield module works too. Even though the phasefield _module_ requires the tensor mechanics module. the phasefield _app_ doesn't register tensor mechanics objects. This should probably be rectified so that we can organize these tests a little better.

**Comment by dschwen** [comment]
Yeah, you only did the part of the module-module dependency where solid mechanics classes can include tensor mechanics headers, but you didn't do the object registration. @permcody mentioned that in the email. We _should_ register objects to avoid having to move tests around.

**Comment by permcody** [comment]
Part of the issue here is that we cannot currently call register on the
same object twice or we get duplicate registration errors. Again, this can
be worked around, but just isn't done yet. I'm willing to help out here
since there may be some new trail to blaze.

**Comment by bwspenc** [comment]
If we make a change to MOOSE to allow objects to be registered twice to permit the solid mechanics app to register the tensor mechanics, then it seems like we shouldn't even do this in the first place.  We could just leave the common stuff in misc, have both solid_mechanics and tensor_mechanics register them, and it would all work. I think what Swetha has here is a reasonable solution, and we should go with this unless the needed changes to allow for double registration can be done quickly.

By the way, the app tests are failing because BISON needs to add the line to register tensor_mechanics.  I haven't ever gone through the incompatible API process, but as I understand it, we go ahead and merge this, and then make a commit to BISON that contains the needed code change and changes the MOOSE version.  Is that right?

**Comment by permcody** [comment]
Bison should't need to register TM. I want the dependency to be handled
automatically. I'll take a look eat fixing that up. Yes, we'll merge this
then put the update with the submodule update into Bison.

**Comment by permcody** [comment]
After looking at this some more, it's clear we need more work on the MOOSE side to make all of this work properly. For now, I think we should register TM in Bison until I've come up with a better solution.

I'll merge this and put in a PR for Bison.

**Comment by permcody** [comment]
Unable to merge automatically - rebasing and opening a new PR - #5641

**Pull request closed without merging**
