### PR TITLE
Modified THM tests to pass parallel sweep testing

### PR DESCRIPTION
**Pull request by joshuahansel**
Refs #16857

### CODE REVIEW

**Comment by loganharbour** [comment]
failing :(

**Comment by joshuahansel** [comment]
Not getting "output too large" to show in CIVET anymore though! :D I'll keep iterating

**Comment by joshuahansel** [comment]
@loganharbour I'll probably end up making an issue with a bunch of failing tests and skip them so that I can get this off my plate for the time being.

**Comment by joshuahansel** [comment]
@loganharbour reminder (not urgent though)

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
LU ALL THE THINGS!

**Pull request merged**
