### PR TITLE
Create directory recursively when making dir for profiling files

### PR DESCRIPTION
**Pull request by YaqiWang**
This is the patch for #16277. Tag @fdkong and @lindsayad

### CODE REVIEW

**Comment by YaqiWang** [comment]
I did try this function with
```
diff --git a/test/src/main.C b/test/src/main.C
index 73a1525e2a..9587b57a61 100644
--- a/test/src/main.C
+++ b/test/src/main.C
@@ -14,12 +14,18 @@
 
 #include <iostream>
 
+#include "MooseUtils.h"
+
 // Create a performance log
 PerfLog Moose::perf_log("Moose Test");
 
 int
 main(int argc, char * argv[])
 {
+  std::string a(argv[1]);
+  MooseUtils::mkdirRecursively(a);
+  return 0;
+
   // Initialize MPI, solvers and MOOSE
   MooseInit init(argc, argv);
```
Things work as expected now. Let me try on HPC.

**Comment by aeslaughter** [comment]
This should include a unit test

**Comment by YaqiWang** [comment]
Will do. I saw `MooseUtilsTest.C` now.

**Comment by aeslaughter** [comment]
What about changing the name to "makedirs" and "removedirs"? That is what these functions are called in python.

**Comment by YaqiWang** [comment]
Remove the `recursively` word in the names? If it has been a convention in python, we definitely need to make it consistent.

**Comment by YaqiWang** [comment]
Function names changed. Any more comments?

**Review by lindsayad — APPROVED** [review]

**Comment by fdkong** [comment]
The failing test is related to this PR? It seems not for me

**Comment by lindsayad** [comment]
> The failing test is related to this PR? It seems not for me

No, not related

**Review by fdkong — APPROVED** [review]

**Comment by YaqiWang** [comment]
Thanks!

**Pull request merged**
