### PR TITLE
Adds ability to set subdomain ID on based on Image data

### LINKED ISSUE #5927: Using Image to assign Subdomains

### PR DESCRIPTION
**Pull request by aeslaughter**
This also moves the ImageMesh and ImageFunction into MOOSE, it seems like this is useful beyond phase-field.

(closes #5927)

### CODE REVIEW

**Comment by jwpeterson** [comment]
Seems reasonable to factor things out this way.  Not sure this will currently do exactly what Martin Lesueur wants to do (I think he wants to completely drop elements that have a certain value in the ImageFunction) but it could probably be made to do so.

**Comment by YaqiWang** [comment]
He will need a mesh modifier for remove certain blocks in the mesh, which is also what I want. Can I create an issue for it?

**Comment by permcody** [comment]
There's already an existing issue for element "deletion". I implemented a
working version of this MeshModifier years ago. In fact it was the first
MeshModifier. It was never used and eventually it was deleted. The old code
is still in the repository and can be resurrected. I can tell you from
working on this before that there are a few gotchas. For instance elements
have to be deleted in a specific order.

**Comment by permcody** [comment]
I like the new class but I have doubts about it seeing a whole lot of use in the framework. We've seen several cases where having several explicit subdomains can be costly which is why we don't use them for neutronics applications anymore. Instead we use a member variable in a material class to track which "virtual" subdomain we are one for the purpose of producing a material property. I'm ok with putting this in the framework but I think you may have jumped the gun here.

**Comment by YaqiWang** [comment]
I'd like to have `SubdomainRemoval` mesh modifier because there are some famous neutronics benchmark problems which have regular Cartesian geometry except some of elements are missing. If we can have this modifier, I can just use the generated mesh and do not need to create a mesh with cubit. Can we resurrect it? We also need to create a new side set which is surrounding the blocks to be removed.

**Comment by YaqiWang** [comment]
If we use a vector of real values to control spin the elements into subdomains with the image data, and the size of this vector is not big, we are good.

**Comment by aeslaughter** [comment]
Creating images from an image of a pink kitty could create a whole bunch of domains, but the ImageSampler has functionality to perform thresholding so you only get two. Considering most people are using this for some of "binary" micro-structure type data, they will only ever get two values.

I am not super hung up on having this in framework or phase_field, it seems like this is more generic than phase_field, especially when I get the levelset module merged.

Finally, it would be cool to delete elements, but if you really want to just model one portion of an image it is possible to do this stuff in Cubit and CGAL, I have done it. I don't know if we want to worry about that type of feature when these tools already have the capability.

**Comment by permcody** [comment]
Please check in your pink kitty example...

**Comment by permcody** [comment]
@YaqiWang - see https://github.com/idaholab/moose/issues/3080

**Comment by aeslaughter** [comment]
kitty_mesh

**Pull request merged**
