### PR TITLE
Add macro for doing things once per execution flag call in MooseObject

### LINKED ISSUE #17896: Add mooseDoOncePerTimestep
## Reason
For reactor fluids simulations, notably with Pronghorn, it's very important to check that the reactor is operating within the validity domain of each correlation, for friction coefficients, for heat transfer coefficients etc. 
We would like to output a mooseWarning when it is not. However, because this can lead to an overwhelming amount of warnings when the simulation is not yet converged, we add a mooseDoOnce to this warning, thus effectively disabling the warnings when we need them the most, at convergence. 

## Design
Reset the mooseDoOnce object every timestep as a boolean option to mooseDoOnce
Or
Add a mooseDoOncePerTimestep

## Impact
Better advanced reactor simulations

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #17896

@rwcarlsen not really the biggest fan just yet... I may close this

### CODE REVIEW

**Comment by GiudGiud** [comment]
What are you concerned with?
I'm very supportive of this, it's very much needed for examining the validity range of models and correlations for nuclear reactor analysis.

**Comment by loganharbour** [comment]
This is failing because the test is dependent on linear and nonlinear iteration counts, which are poorly consistent. Waiting to get some more feedback before I get around to fixing it.

Knock knock @rwcarlsen

**Comment by rwcarlsen** [comment]
Can't you just write the test to check for `num_warnings == nonlinear_iteration_count`.  My mild opinion is still that mooseDoOnce or just making the warnings an error is a better solution.  But if others really feel like this will be helpful then I won't hold it back.  The issue is that warnings get ignored.  So if users are annoyed that a warning is printing out a bunch it seems like making it easier to ignore is not the best approach.  Maybe a better solution would be something like an error suppression file with patterns of errors/warnings to ignore - maybe it could even be integrated into input files.  Seems more general, flexible and useful.  (Also more likely to be abused - maybe we don't let it work for errors - just warnings).

**Comment by rwcarlsen** [comment]
Actually - I'm not sure I really like my suggestion.  Seems like it could hide real problems - which goes back to why I'm not a huge fan of this PR - it hides the extent of an issue that probably should be resolved rather than ignored.

**Comment by GiudGiud** [comment]
In the context of Pronghorn, we need to be able to ignore warnings while the simulation is converging, as the flow regime might not match at that point the domain of validity of the correlations used. 
Then at convergence, the good reactor physicist will make sure to understand what is happening if there are still warnings. 

But it may also be the case that we are purposefully using a correlation outside of its validity domain, for lack of another option for example.

Either way, we can't be swarmed with warnings, or do them once on the first time the materials are evaluated.

**Comment by rwcarlsen** [comment]
A lot of these sorts of issues crop up with fluid properties and various correlations - sometimes the solver jumps to a slightly negative temperature or something and then wonky values get propogated through until somebody throws an error/warning or until the solver goes off the rails and fails to converge.  In my experience - usually the right solution is to fix the issue (better jacobians, different line search, constraining solver search region, etc.)  so you don't see the warnings any more.  If it shouldn't be ignored, then it's actually good for it to be obnoxious.  In general - it's a lot easier/better for convergence if we aren't searching invalid ranges where our correlations and such are broken.

**Comment by GiudGiud** [comment]
The generation of wonky values by being out of range can be treated as a separate issue though. People can add limiters, can change the inputs when they are out of range etc. 

In fact I am pushing for Pronghorn to reset negative pressures and temperatures in the variable materials. 

But the current status quo, DoOnce warnings, is really problematic.

**Comment by GiudGiud** [comment]
Pronghorn needs this so badly, no way this is going away on stale

**Pull request closed without merging**
