### PR TITLE
Add algebraic ghosting to all EquationSystems

### LINKED ISSUE #14536: Allow addition of algebraic relationship managers to arbitrary Systems/DofMaps
## Reason
@loganharbour has additional `Systems` on the `EquationSystems` object that can require algebraic ghosting.

## Design
A paranoid solution is to loop over the `Systems` in `EquationSystems` and add the algebraic ghosting functors to each.

## Impact
Allow @loganharbour and folks using additional `Systems` to operate in parallel

### PR DESCRIPTION
**Pull request by lindsayad**
If an algebraic ghosting functor is requested by an object, we
add that functor to all Systems held by EquationSystems instead
of manually adding to the nonlinear System and auxiliary System.
This covers cases where users have more than the two traditional
Systems.

Closes #14536

### CODE REVIEW

**Comment by lindsayad** [comment]
@loganharbour Can you see if this works for you? Do you want to add a test or should I?

**Comment by loganharbour** [comment]
I'll give this a try right now. Looks good and simple enough.

I'm not really sure what an appropriate test is or if there are any objects in the framework that add additional Systems. Are there?

**Comment by lindsayad** [comment]
> I'm not really sure what an appropriate test is or if there are any objects in the framework that add additional Systems. Are there?

Not to my knowledge. I'll think up a test. Don't worry about it.

**Review by permcody — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]
Is also working for my use case 👍

**Pull request merged**
