### PR TITLE
Update `get_repo_revision.py` to get rid of `diskutils` deprecation

### LINKED ISSUE #19966: Update get_repo_revision.py, deprecated distutils.version
## Reason
Deprecated distutils.version

## Design
`from packaging import version` instead of `from distutils.version import LooseVersion` 

`if version.parse(gitVersion) >= version.parse("2.9"):` instead of `if LooseVersion(gitVersion) >= LooseVersion("2.9"):`

## Impact
Getting rid of the deprecation warning

### PR DESCRIPTION
**Pull request by atoptann**
Closes #19966

### CODE REVIEW

**Comment by atoptann** [comment]
@loganharbour

**Comment by loganharbour** [comment]
> @loganharbour

🍻 thanks for getting to it quickly

**Review by loganharbour — APPROVED** [review]

**Review by loganharbour — CHANGES_REQUESTED** [review]
You'll need to do:

```
if sys.version_info[0] == 3 and sys.version_info[1] < 7:
  from packaging import version
else:
  from distutils.version import LooseVersion
```

and something similar for the other commands (this change is for python > 3.6)

**Comment by atoptann** [comment]
> You'll need to do:
> 
> ```
> if sys.version_info[0] == 3 and sys.version_info[1] < 7:
>   from packaging import version
> else:
>   from distutils.version import LooseVersion
> ```
> 
> and something similar for the other commands (this change is for python > 3.6)

**Comment by loganharbour** [comment]
Darn. We're gonna have to add `packaging` to python on the build boxes. Ping @milljm...

**Comment by cticenhour** [comment]
@loganharbour @milljm did `packaging` get added to the build boxes? Was pinged about this deprecation message the other day, and saw this has been sitting here.

**Comment by milljm** [comment]
Okay, sorry for the delay. py-packaging is now available and loadable on our build machines...

**Comment by cticenhour** [comment]
@milljm Looks like we have some issues with recipes looking for CentOS-8 or rocky and not finding them, since this PR was started before we dropped the former. What needs to be done here?

**Comment by milljm** [comment]
@cticenhour A new push needs to occur... Invalidations will re-use old recipes

**Comment by cticenhour** [comment]
@atoptann Can you do a rebase of this on the current devel branch?

**Comment by hugary1995** [comment]
Pinged by the deprecation warning just now.

**Pull request closed without merging**
