### PR TITLE
Add SIDE_HIERARCHIC support

### PR DESCRIPTION
**Pull request by roystgnr**
## Reason
To enable storage of flux or other per-side variables, support for Discontinuous Petrov-Galerkin or other fancy mixed methods, etc.

## Design
libMesh supports a SIDE_HIERARCHIC FE class; the changes here merely make it possible for Moose users to request that variable type, and add a regression test with a couple such variables.

## Impact
This adds new options, no impact on users who don't specifically request a SIDE_HIERARCHIC variable.

We may have some future behavior changes in store for such users, as we try to figure out what the best way to visualize these things is, or if we discover any bugs that the libMesh unit test coverage didn't trigger.  Derek tells me @YaqiWang is ready to try these out, so best to get this PR enabled ASAP before getting bogged down in the question of what proper Exodus output would look like.

Refs #20191

### CODE REVIEW

**Comment by YaqiWang** [comment]
@roystgnr few quick questions:

1. Can we block restrict or side-set restrict the side variables?
2. Can we couple a side variable in objects operating on sides, such as DGKernel, InterfaceKernel, InternalSideUserObject, InterfaceUserObject, BoundaryCondition, SideUserObject, etc.?
3. How is a side built? Is it build always based on upwinding element and its local side ID?  I guess this affect how DoFs on sides are interpreted.
4. Are we supporting distributed mesh with side variables?

**Comment by roystgnr** [comment]
Can't believe I'd done a "commit -a" without thinking.

**Comment by YaqiWang** [comment]
I should have been more specific on the second question: will `coupledValue(var_name)`,`coupledDofValues(var_name)` and `coupledNeighborValue(var_name)`,`coupledNeighborDofValues(var_name)`  work for side variables?

So the dofs on an element is like `normal var dofs; side var dofs on side 0; side var dofs on side 1; ...`? On the boundary, we want the dofs seen on element and also dofs just for the boundary, how do we store the dofs just for the boundary?

**Comment by roystgnr** [comment]
Your question was specific enough; I'm afraid that doesn't make the answer any more specific.  I don't know of any reason why any of those methods should fail, but until we have test coverage for them there may be some reasons I don't know.

> So the dofs on an element is like normal var dofs; side var dofs on side 0; side var dofs on side 1; ...?

If the side vars are the last variables added to the system, then yes; if not, then no; if the answer is important than that's some fragile user code, because it would be much safer to use the lookup APIs that take a variable index (or at least to query the DofObject on each side, if trying to optimize?), rather than to hard-code any belief about what they would return.

> On the boundary, we want the dofs seen on element and also dofs just for the boundary, how do we store the dofs just for the boundary?

Right now the only way to do that is still to create boundary elements with their own subdomain (or a boundary mesh, if you don't need it tightly coupled) and add a (subdomain-restricted, in the former case) variable to that.  The side variable type here assigns DoFs to element sides, not boundary sides.  The way libMesh FE variables work would make a boundary-side-only variable much harder to implement.

> If we want to do a trace operation for a normal variable to populate a side variable, does libMesh provide a quick way of doing that or we will have to loop through sides to do the projection on our own?

The latter.  That'd be a reasonable thing to add to libMesh, though.

> If we have a C1 variable and do a trace operation, will the dofs stored on an element and its neighbor for a side variable are the same?

Even if you have a discontinuous variable, any operation you do will leave the side DoFs stored on an element equal to the side dofs stored on its neighbor, because they're the same DoFs.  We don't keep redundant duplicates, any more than we keep 8 copies of every vertex DoF on a hex mesh.  If you want something that stores different DoFs on each side-of-a-side, go ahead and let me know since that wouldn't actually be hard to add on top of this work, but this work isn't it.

**Comment by roystgnr** [comment]
> If the side vars are the last variables added to the system, then yes; if not, then no

My apologies; I spoke too hastily about this.  If there's *one* side var and it's the last variable in the system then its DoFs will be last, and they will be in increasing side order; but if there's multiple side vars, they won't be interleaved "side var A side 0, side var B side 0, side var A side 1, side var B side 1, ...", they'll be blocked "side var A side 0, side var A side 1, ... side var B side 0, side var B side 1, ..."

**Review by lindsayad — APPROVED** [review]
LGTM

**Pull request merged**
