### PR TITLE
Lava lamp 13239

### PR DESCRIPTION
**Pull request by WilkAndy**

### CODE REVIEW

**Review by permcody — APPROVED** [review]
I've been asking for a lava lamp simulation for 10 years! This is the most useful piece of science done with MOOSE yet! Now I need somebody to build a lava lamp mesh and run it in 3D. What better way to show off a computational framework than to showcase a lava lamp on the front page? Who needs reactor simulations anyway.

**Comment by cpgr** [comment]
@WilkAndy - something has gone wrong with some rendering on `lavalamp.md` - part of the third sentence is in math font and perhaps part of the subscript?

Also the `{\tt ppgas}` and {\tt zi}` haven't rendered correctly.

**Comment by cpgr** [comment]
Oh, and thanks for finishing this off

**Comment by WilkAndy** [comment]
Bum, thanks for checking @cprg.  I didn't have my laptop so couldn't preview what the markdown looked like.  I'll fix it tomorrow, unless you get to it first.

**Pull request merged**
