### PR TITLE
Constrain python to <3.11, enable rocky9 apptainer, improve versioner, add cuda and clang to apptainer

### LINKED ISSUE #23944: Create another Conda package for Python pinning
## Reason
Python 3.12 is out, and it would seem Python 3.11 is now default on Conda. When one installs our `moose-libmesh` package without also installing a Python pinning `moose-tools` package, we now get an environment unable to build MOOSE, as described in Discussion: https://github.com/idaholab/moose/discussions/23831 

## Design
Investigate creating yet-another-package that depends on a version of Python we support. There's _gotta_ be a way. I am envisioning a very loose dependency. Something like:

```pre
moose-libmesh --> moose-python
```

Where `moose-python` will only contain `python <3.11` and perhaps `packaging`. This should still allow for combination install of `moose-libmesh` and `moose-tools`.

The reason for "yet another package" is to break away from the pinning that is created when building other packages (like `moose-libmesh`). e.g if we attempted to solve this issue _in_ `moose-libmesh`, we would need to build `moose-libmesh` as many times as we support versions of Python (x4).

We also do not want to force folks to install `moose-tools`. It was never meant as a requirement (but it certainly is becoming one). We might discuss this further. A simple fix would be throw a dependency of `moose-tools` in our `moose-libmesh` package.

## Impact
Folks who _only_ install `moose-libmesh` should be able to build / develop-in MOOSE.

### PR DESCRIPTION
**Pull request by milljm**
When installing moose-mpich and Python, constrain Python to below version 3.11.

Closes #23944

### CODE REVIEW

**Review by cticenhour — DISMISSED** [review]

**Comment by cticenhour** [comment]
Looks like we've got conflicts here....is this from when we failed to increment `moose-libmesh` correctly?

**Comment by loganharbour** [comment]
We'll need to keep https://github.com/idaholab/moose/pull/23963 in mind

**Review by loganharbour — CHANGES_REQUESTED** [review]
We likely need to add a `moose-wasp` (via `conda/wasp`) dependency to `moose-test-tools` in the versioner. Plus maybe other libraries. This would probably require that we pin a version of `moose-wasp` in `moose-test-tools`, but I think that's okay.

**Review by loganharbour — DISMISSED** [review]
Approving content that is not my own

@milljm please review my content. Approve if you see fit, remove the do not merge if you’re content

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — DISMISSED** [review]

**Comment by milljm** [comment]
I approve Logan works.

**Review by loganharbour — APPROVED** [review]

**Comment by milljm** [comment]
I still approve of Logan's work.

**Comment by loganharbour** [comment]
The only failing tests are all WIP

**Pull request merged**
