### PR TITLE
Removing static to make test work with threads

### PR DESCRIPTION
**Pull request by permcody**
refs #6159

### CODE REVIEW

**Comment by jwpeterson** [comment]
:+1: I can't remember why I used a static here.  Laziness is a possibility.

**Comment by friedmud** [comment]
Wait... how does threading work with DiracKernels?  Does every threaded copy need to add the same points?  What happens if they don't?

**Comment by jwpeterson** [comment]
DiracKernels aren't threaded, right?

**Comment by aeslaughter** [comment]
https://github.com/idaholab/moose/blob/devel/framework/src/base/ComputeDiracThread.C

**Comment by friedmud** [comment]
How does any of this stuff ever work? ;-)

Seriously though, I don't understand how threading is currently working
with DiracKernels.

Derek

**Comment by permcody** [comment]
I suspect that there is a problem as well after thinking about this. We may
be getting lucky and the threads adding points are also the ones applying
the residuals. We need to either make sure that's engineered into the
system or every thread needs to add every point or we need to add the
points to a shared area of memory.

In any case, that static needs to go!

**Comment by friedmud** [comment]
Ok - created a new Issue for the DiracKernel threading stuff: #6200 .

I'll merge this as it is because it definitely fixes one thing ;-)

**Pull request merged**
