### PR TITLE
Add missing SQA items in THM testing

### PR DESCRIPTION
**Pull request by GiudGiud**
well, this was a nightmare.
There were a few findings though

should be merged only after the other one, as I built from the other one

### CODE REVIEW

**Comment by joshuahansel** [comment]
> should be merged only after the other one

@GiudGiud The "other one" has been merged, right?

**Comment by GiudGiud** [comment]
Yup

**Review by joshuahansel — APPROVED** [review]
Thanks for doing this! It's up there in my most boring reviews, and I'm sure it was much worse actually doing it.

**Comment by GiudGiud** [comment]
Thanks for the review!

**Pull request merged**
