### PR TITLE
Patch for generalized_plane_strain_tm_contact test

### LINKED ISSUE #9530: Patch for PR #9451
### Description of the enhancement or error report
updated the generalized_plane_strain_tm_contact test input file and regolded the result 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by hchen139**
Patch for test failure in PR #9451

closes #9530

### CODE REVIEW

**Comment by roystgnr** [comment]
Thanks!

How many time steps does this test typically take now, with the num_steps=5000 cap removed?

**Comment by hchen139** [comment]
@roystgnr the actual number of time steps is determined by the end_time, dt and dtmin, which is 10 for this test. The num_steps=5000 cap is not useful in this test.

**Comment by roystgnr** [comment]
So that was an unrelated atavism?  Thanks for clarifying.  I saw it and just assumed some kind of adaptive time stepping was going on.

**Comment by hchen139** [comment]
@bwspenc Hi, Ben, could you have a look at this PR whenever you have time. Thanks.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
