### PR TITLE
Added some more documentation from BISON user's manual

### PR DESCRIPTION
**Pull request by tolman42**
refs #9638

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

### CODE REVIEW

**Review by aeslaughter — COMMENTED** [review]
Please remove these items from the hidden.yml file in MOOSE.

**Comment by sapitts** [comment]
@aeslaughter I'll pick this up since Malachi has left.  Besides removing the items from the hidden.yml file, are there any other changes you'd like to see made to this commit while I'm picking it up?

**Comment by aeslaughter** [comment]
@sapitts Just need the items from the hidden file.

**Comment by sapitts** [comment]
Commit included in PR #10045; please close this pull request

**Pull request closed without merging**
