### PR TITLE
Fix transfer initial setup 4498

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by permcody** [comment]
:+1: This looks fine to me. If this works for you we'll merge it.

**Comment by snschune** [comment]
It's the behavior Yaqi and I want (and I suppose that MultiAppTransfer::initialSetup is generally expected to be executed), but it breaks a bunch of things in YAK, i.e. Yak tests will fail but it will compile. I am working to resolve the issue. If I cannot in a timely manner I can always just skip the failing tests until I can fix the problem.

**Comment by permcody** [comment]
That's important! We need to know that because we won't roll this patch to
master if yak fails. We DO test against yak now in the
devel_to_master_app_tests target. I'll mark this PR with the appropriate
tag.

**Comment by permcody** [comment]
We won't merge this until you tell us Yak is passing. Let us know.

**Comment by snschune** [comment]
Alright.

**Comment by snschune** [comment]
The new commit avoids transfers to be executed twice. However, when ```initialSetup()``` is executed 
for my ```EmbeddedMeshTransfers```, I call ```execute()``` once. This is important because it saves us one expensive transport update at the beginning of the solve. 
However, it still messes up the order in which materials are stored in the ```MaterialWarehouse```, hence I will still get a segmentation fault. 

I need to understand how executing a ```MultiAppTransfer``` can revert the ordering of the Materials.
I verified that after ```MaterialWarehouse::initialSetup``` is called, the materials are sorted correctly,
but something messes up this ordering.

**Comment by snschune** [comment]
@permcody The branch that sits in Yak merge request #36 should work with these changes. Yak
is ready for this to be merged.

**Comment by YaqiWang** [comment]
This fixes the transfer initialSetup and should be merge asap imo.

**Comment by permcody** [comment]
Thanks, @snschune I'll get back to MOOSE work tomorrow and will get this merged.

**Pull request merged**
