### PR TITLE
Changed the point equality test in LineSegment::contains_point

### LINKED ISSUE #9500: Line sampler in 1-D not robust
### Description of the enhancement or error report
At least for 1-D (and possibly higher D as well), the line sampler vector post-processors are sensitive to floating point precision error. For example, if one has a 1-D mesh and wants to sample a material property along this line using `LineMaterialRealSampler`, then depending on the end coordinates, number of elements, etc., one may only intersect the first few elements along the line, even though the lines should be exactly coincident.

### Rationale for the enhancement or information for reproducing the error
The issue has been verified using the following file, where one can see in the CSV output that only the first few elements were found to intersect the sampling line:
[point_intersection_equals.txt](https://github.com/idaholab/moose/files/1149021/point_intersection_equals.txt)

### Identified impact
This should now include points that were not found to intersect to floating point error, ~1e-15.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #9500

### CODE REVIEW

**Comment by joshuahansel** [comment]
@andrsd This is the pull request I told you I'd make.

**Review by andrsd — CHANGES_REQUESTED** [review]
Let's add a test that triggered this change, so we know this works as it is supposed to.

**Comment by joshuahansel** [comment]
I have been pretty ineffective at the debugging of the failing test so far. All I can say so far is

- This happens only for distributed mesh.
- This error occurs with this input file with or without my changes.
- This error only occurs if that vector post-processor is created.
- The error occurs in `RayTracing::elementsIntersectedByLine()`, in the `operator()` call of point locator to find the first element. It apparently fails to find the point (0,0,0) in any element for some processes. It looks like the error happens for P-1 processes.

Since this is a distributed mesh issue, is the mesh partition containing the first element only available to one process, and yet all processes are looking for the first element?

**Comment by joshuahansel** [comment]
As discussed offline, last line of my previous comment explains the issue. `RayTracing` is not yet ready for distributed meshes, so the fix was to use a replicated mesh.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
