### PR TITLE
Fix memory leak created in stateful property + recover fix

### PR DESCRIPTION
**Pull request by permcody**
refs #13987

### CODE REVIEW

**Comment by permcody** [comment]
@cpgr - Minor problem with your patch. This should fix it.

**Comment by cpgr** [comment]
Thanks @permcody. I didn't even think about releasing the memory!

**Comment by permcody** [comment]
Well there aren't many places left in MOOSE that don't use smart pointers to manage memory. This is one of those places and it really should be modernized.

**Comment by permcody** [comment]
@lindsayad - This needs to go in to unclog the next branch. Then I can merge in your libMesh update + AD PR.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
