### PR TITLE
Test added illustrating SideSetsAroundSubdomain bug

### PR DESCRIPTION
**Pull request by WilkAndy**
The test is called around_created_subdomain.i   It crashes.
An almost identical test, which creates sidesets around a subdomain using the SideSetsBetweenSubdomains MeshModifier instead, is also included.  It does not crash.

Refs #9447

### CODE REVIEW

**Comment by WilkAndy** [comment]
Please could someone else fix this?  I currently don't have the time/skill to address this issue.

**Comment by WilkAndy** [comment]
Oh, i should have explained how i got a "gold" exodus file for a input file that crashed!  I used SideSetsBetweenSubdomains, which should produce exactly the same mesh in this particular case.

**Comment by dschwen** [comment]
Discussion should happen on the linked issue. The test harness ran this. I'm assuming the PR can be closed now (let me know if you need me to re-open).

**Comment by WilkAndy** [comment]
Yep, good, thanks for closing.

**Pull request closed without merging**
