### PR TITLE
Migration of the 1D Rspherical kernel, small, and finite strain materials 

### PR DESCRIPTION
**Pull request by sapitts**
with tests that compare to analytical solutions (a solid sphere under external pressure, center pinned, for small strain, and a hollow sphere under external pressure and pinned at inner radius for finite strain). Refs #6256. Equations and expected results for radial stress are given in the test input files. 

An action is not included in this commit because it makes sense to combine the cylindrical and spherical actions into a single file, and I would like to talk through this process with a few folks before committing an Action.

This commit also includes a spelling correction in the Compute2DSmallStrain header file.

### CODE REVIEW

**Comment by permcody** [comment]
@dschwen - can you please review?

**Comment by WilkAndy** [comment]
I'm curious as to whether you INL guys+gals are planning to generalise all tensor_mechanics to arbitrary dimensions.

I think everything i've written in tensor_mechanics is for 3D.  There are a lot of "3"s hanging around in my code.  Lots of plastic models are really only defined for 3D.  If there is a push from you for the generalisation, i can code with this in mind.  Generalising to arbitrary dimensions is quite a big job, but it'll only get worse and worse as we keep writing "3" in our code everywhere!

**Comment by dschwen** [comment]
The 3 should probably at least be LIBMESH_DIM anyways.

**Comment by sapitts** [comment]
The RSpherical and Axisymmetric materials + kernels are the only non 3D
'strain calculators' which need to be moved over from solid mechanics.

--

Stephanie Pitts
Graduate Student, Mechanical Engineering, and Instructor
Computational Mechanics & Materials Science Laboratory
Washington State University, sapitts@wsu.edu

**Comment by permcody** [comment]
OK on the comment, but that doesn't really apply to this PR. If you have any further comments on the review let us know.

**Pull request merged**
