### PR TITLE
Create subdirectories from file_base

### LINKED ISSUE #3249: Output to directory that doesn't exist doesn't work
If I put something like this in my Outputs block:
```
[./CSV]
  type=CSV
  file_base = csv/mybase
[../]
```
the code dies with an error because the 'csv' directory doesn't exist.  Any chance we could have MOOSE make that directory for the user if it doesn't exist?

### PR DESCRIPTION
**Pull request by permcody**
Adds the capability to create directories if the `file_base` has slashes.

A corresponding capability is added to the TestHarness to remove those directories so that we can verify functionality. The TestHarness capability is small and can be found at the bottom of `RunApp.py`. The remaining changes are just refactoring to remove duplicate code.

closes #3249

### CODE REVIEW

**Comment by friedmud** [comment]
@permcody what about the case where two tests in the same directory are outputting files into the same subdirectory... but the files have different names?

Would this accidentally delete the directory of one test while the other was running (if they are running in parallel)?

**Comment by permcody** [comment]
Well first, I really hope nobody puts an input file in an output directory in any testing scenario... That would be terrible.

However, the answer is no even in that case. I'm using `os.rmdir()` which only removes non empty directory so the destruction order is very important. I am handling the case where a user is outputting multiple files to the same output directory. Each of the files is removed before any of the directories are moved.

Honestly, this is probably all over engineered since we normally don't delete any files for real runs. This is just a TestHarness option to make sure we don't break this going forward.

**Comment by friedmud** [comment]
What I'm saying is that there could be a race condition between two tests in the same directory that are outputting to the same directory.

Even in the case of only removing if it's empty it's possible for a process to create the output directory... then another process to remove it (before any files have been put in it by the first process) and then the first process will bomb out when it actually tries to put a file in it.

This is the kind of crazy race condition that's a bitch to track down in the testing system...

**Comment by permcody** [comment]
There's not much the TestHarness could do to handle that case. I think the only robust way to deal with it would be to serialize those tests.

On another note, this PR failed to work in parallel just now... I'm not sure why as I though that FileOutput only happened on rank 0.

**Comment by friedmud** [comment]
@permcody not with `DistributedMesh`... every process outputs

**Comment by friedmud** [comment]
Actually - this code is in the constructor of `FileOutput`... that will get called on every processor.  I suppose this needs to be guarded with `if (processor_id() == 0)`

**Comment by friedmud** [comment]
@permcody Re: the race condition.

Can the test harness not see the other tests in the same `tests` file?  It could determine that there are two tests that are outputting to the same subdirectory and that it needs to try to remove that subdirectory and then it could throw an error...

**Comment by permcody** [comment]
That could certainly be done by inspecting the various "diff" file locations. However, I really don't see much use in engineering all of this. We'll probably have this one test, maybe one more that actually uses the subdirectory output feature. I'd really rather not see a lot of this in the test suite even though it might be used a lot in real runs.

Once I start looking at files, I could probably determine other useful things like missing prereqs to some extent!

**Comment by friedmud** [comment]
Ok - I'm down with keeping it simple for now.

In the future I would like to do a lot more with subdirectory output... like have the name of the subdirectory be dependent on the input file run (like the name of files is today).

Because with the way this capability is now... if you copy the input file and run it the new output files will go in the _same_ directory (but they will have different names).  It would be nice to have the option to get different directory names.

But anyway - that's for the future.

**Comment by permcody** [comment]
Well this should be ready to merge now. If'll be some work decide how to remove directories robustly and safely in the future should we decide we want that feature. This was printing out several "Unable to delete folder" messages yesterday on the test systems but not on my box. I was really confused about this until I realized it was because we also run `--recover` tests which turns on checkpointing all over the place which adds even more information to the output area.

**Pull request merged**
