### PR TITLE
Consolidate and clean mesh-modifer/generator tests

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #13814
Here's what happened to each test folder. Duplicates are exact save for object names and at times comments in input files.

- [x] add_all_side_sets : duplicates of add_all_side_sets_generators, deleted
- [x] break_boundary : duplicates of break_boundary_on_subdomain, deleted
- [x] parsed_subdomain : duplicate of parsed_subdomain_generator, deleted
- [x] add_extra_nodeset: similar test intent but different tests, consolidated with extra_nodeset_generator. Turned from diffusion problem to mesh-only exodus
- [x] break_mesh_by_blocks
Files renamed with this convention:
TestBreakMesh_3D_Polycristal -> break_mesh_3D_polycrystal.i
TestBreakMesh_3D_3Block_Auto.i -> break_mesh_3D_auto.i
More tests in mesh generator folder
- [x] sidesets_around_subdomain
All 4 inputs for all 4 tests are in the new MG folder
convention roughly for renaming: around_multi_created_subdomain.i <- sidesets_around_subdomain/around_multi_created_subdomain.i 
- [x] add_side_sets: 2 tests were duplicates with sidesets_from_normals_generator, deleted. Last one duplicated in sidesets_from_points_generator, deleted
- [x] sidesets_between_subdomains
all input files and tests are in the new MG folder. same names
- [x] add_side_sets_from_bounding_box
tests are duplicates of tests in meshgenerators/sidesets_bounding_box_generator
- [x] lower_d_block
The new tests are testing name/id input of sidesets. The old test were about first/second order meshes. The mesh modifier tests were moved to the mesh generators
- [x] smooth_mesh
duplicate of smooth_mesh_generator
same mesh is used, the only difference is 2 less smoothing runs (out of 5) in the new test, and the old test was diffusion. The new test is mesh-only. Testing is equivalent overall
- [x] assign_element_subdomain_id
moved to MG folder
- [x] mesh_extruder
all duplicates except the tri test which was only in mesh modifier folder and got moved over to the mesh generator folder
- [x] subdomain_bounding_box
duplicate of subdomain_bounding_box_generator Tests
the only difference is the 2-level refine in the mesh modifier test. This doesnt really affect anything, it just made the original test more expensive.
- [x] assign_subdomain_id
duplicate of subdomain_id_generator
original test was a diffusion solve, replaced by mesh-only
- [x] mesh_side_set
Total duplicate of mesh_side_set_generator test
- [x] transform
total duplicate of transform_mesh_generator
- [x] block_deleter
The mesh modifier tests covered 12 different cases. The new mesh generator tests covered the 1st one then a 13th and 14th additional case. While input
files (and gold files) were checked in for the 12 cases in the mesh_generator folder, the test specs were not written. The mesh modifier folder was deleted
and the mesh generator test specs are now written for those 11 cases.
- [x] modifier_depend_order
The depend_with_force_prepare test is testing a parameter that no longer exists (force_prepare), so it's not really doing much. It's removed now
The other test tests ordering of mesh generators. It has no direct equivalent in the new tests but it does overall gets tested a lot.
I moved the folder over to meshgenerators/order_of_generation
- [x] boundingbox_nodeset
duplicate of boundingbox_nodeset_generator folder. The mesh modifier tests were diffusion solves, mesh generator tests are --mesh-only. Same testing power
- [x] parsed_sideset
test is part of the parsed_generate_sideset suite (which includes more)
- [x] image_subdomain
The mesh modifier tests were testing stacks of images and 3D images, while the tests in image_mesh_generator/ only had a single image test. The mesh_modifier folder tests were moved to the mesh generator corresponding folder

### CODE REVIEW

**Comment by lindsayad** [comment]
(not that it is much)

**Comment by GiudGiud** [comment]
no we shouldnt. Seems the exception checking was more thorough for mesh modifiers than for mesh generators

**Comment by GiudGiud** [comment]
I ll go grab these tests

**Comment by GiudGiud** [comment]
let s see if that fixed it

**Comment by GiudGiud** [comment]
ok there's actual differences in the tests, despite the matching names and descriptions. I ll try to find out what they are. I m thinking 3 tests are involved based on the diff

**Comment by lindsayad** [comment]
Huh? It looks like all tests are passing to me

**Comment by lindsayad** [comment]
well other than the doc

**Comment by GiudGiud** [comment]
I m talking about the diff in coverage.

**Comment by lindsayad** [comment]
ah, got ya

**Comment by lindsayad** [comment]
So what are we doing about this vs. #22267? It seems like you think this one is superior ... and I definitely agree that feature coverage is more important than line coverage

**Comment by GiudGiud** [comment]
I'm fixing this one to get the coverage right. The missing lines might tell us something about differences in the tests. 

The other one has modified tests, a muddled commit history, deleted tests we do not want to delete, checks in the repository a duplicate of a picture of a kitten, pick your reason but imo it's not mergeable as is.

**Comment by GiudGiud** [comment]
so the final word on the missing lines is that you needed to run at least 3 processes in distributed mode to hit the missing lines. 

however, while this configuration is part of our test suite (we sweep from 1-16 at least with distributed), it is not part of the recipes used to compute coverage

The new test will force this

**Comment by GiudGiud** [comment]
wouhou coverage increased now lolol

@lindsayad any other concerns?

**Review by lindsayad — APPROVED** [review]
Nice. It would almost be nice to create `#ifdef MOOSE_ENABLE_DEPRECATED` guards like we have for libMesh that could be used to remove deprecated code from coverage testing for example. What would you think about that @loganharbour ? Probably would make the code more ugly than it's worth to make coverage appear (a little bit) better

**Comment by GiudGiud** [comment]
thanks!

**Comment by loganharbour** [comment]
> It would almost be nice to create #ifdef MOOSE_ENABLE_DEPRECATED guards like we have for libMesh that could be used to remove deprecated code from coverage testing for example.

I think I'm on board with this. I think it would make maintenance easier as well by just doing a quick grep for that guard

**Comment by loganharbour** [comment]
We would probably need to add functionality for what to do with deprecated parameters, though

**Comment by GiudGiud** [comment]
On the doc side,
- We dont have anything on the PLN-4005 for what to do with deprecated features.
- We should have docs in "how_to_contribute_to_moose" to explain the few details about what to do when transforming an object, especially changing its parameters
all I can think of for now

**Comment by friedmud** [comment]
Locking this until we have time to have a proper meeting about testing so we can have a better discussion.

**Pull request merged**
