### PR TITLE
Array kernel

### PR DESCRIPTION
**Pull request by permcody**
Rebasing and superseding #13314

### CODE REVIEW

**Comment by permcody** [comment]
@friedmud - Do you have time to look at this?

**Review by lindsayad — APPROVED** [review]
I had reviewed this in its previous edition, and @YaqiWang addressed my comments, so I am good with this.

**Comment by YaqiWang** [comment]
@cody I will recreate the PR with conflicts being resolved. Can we close this?

**Comment by permcody** [comment]
Absolutely - just reference the new ticket when you close this in case
people are following the trail.

**Comment by permcody** [comment]
superseded by #13528.

**Pull request closed without merging**
