### PR TITLE
Throw an error if negative value occurs where unsigned int values are…

### PR DESCRIPTION
**Pull request by andrsd**
… expected

Refs #17334

### CODE REVIEW

**Comment by loganharbour** [comment]
Tests?

Ping @aeslaughter may want to do this in moosetools instead

**Comment by andrsd** [comment]
No tests yet, because I wanted to see what is going to break before I dive into this.

I can set this to draft (which this totally is a draft), but I was not sure if CIVET would run the tests.

**Comment by loganharbour** [comment]
Can you go put this in idaholab/moosetools instead? We're planning the transition within the next few days.

**Comment by andrsd** [comment]
> Can you go put this in idaholab/moosetools instead? We're planning the transition within the next few days.

Yeah, no problem.

**Comment by andrsd** [comment]
Moved [here](https://github.com/idaholab/moosetools/pull/39)

**Pull request closed without merging**
