### PR TITLE
Add AssignSubdomainID

### LINKED ISSUE #8287: AssignSubdomainID MeshModifier
### Description of the enhancement or error report
We just need the dead simple capability to assign a subdomain ID to all elements.

### Rationale for the enhancement or information for reproducing the error
Basic functionality that should exist.

### Identified impact
Just adding another tiny class

### PR DESCRIPTION
**Pull request by friedmud**
Just adding a really simple MeshModifier.

closes #8287

### CODE REVIEW

**Comment by permcody** [comment]
How do we not already have this? I guess we have the libMesh utility that does this for us but never has it been added to MOOSE?

**Comment by friedmud** [comment]
I guess so!  I was surprised to.

We have others, that are crazy complicated, but if all you want to do is re-assign all of the IDs there isn't anything there...

**Comment by YaqiWang** [comment]
Looks like we already had this? https://github.com/idaholab/moose/blob/devel/framework/src/meshmodifiers/AssignElementSubdomainID.C

**Comment by friedmud** [comment]
@YaqiWang Nope: I want to assign _all_ of the elements to a single ID.  As far as I can tell that can't be done with `AssignElementSubdomainID`.  I think you could technically do it with `SubdomainBoundingBox` if you just encompassed the whole mesh.... but that's fairly obtuse for something that should be easy.

**Comment by YaqiWang** [comment]
Why cannot with `AssignElementSubdomainID `? We just need to repeat the same number the number of elements times. I agree it is complicated than this modifier but it also contains checks like assigning the same ID to blocks with different element types. I think we want to control the number of necessary source files in the framework. How about move this into misc modules?

**Comment by friedmud** [comment]
@YaqiWang Are you serious?  This is extremely basic capability that should be in the framework.  If anything, `AssignElementSubdomainID` should go into misc.

Personally: I think both are fine in MOOSE: they are both useful and both applicable to a wide range of problems.

**Comment by YaqiWang** [comment]
Well, there are too many basic capabilities... If each one is requiring one source file, our compiling time will be intolerable. To me it is already on the edge of intolerable. Compiling MAMMOTH takes forever!

**Comment by friedmud** [comment]
@YaqiWang I agree that we need to be careful about what goes into MOOSE... but _this_ is basic functionality that should be in the framework (should have always been in the framework).  Fight against bloat somewhere else... this is not it.

**Review by permcody — APPROVED** [review]

**Pull request merged**
