### PR TITLE
Add new beginIndex() macro to MOOSE

### LINKED ISSUE #7580: Add beginIndex() to MOOSE
### Description of the enhancement or error report

Give us a consistent way of looping with an index

### Rationale for the enhancement or information for reproducing the error

Stop using `unsigned int` for every loop index, for one thing it's wrong, also it _may_ interfere with vectorizing.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Enhancment

### PR DESCRIPTION
**Pull request by permcody**
closes #7580

We'll move these clang diagnostics to libMesh in the future.

### CODE REVIEW

**Comment by permcody** [comment]
Ping @idaholab/moose-team

**Comment by friedmud** [comment]
It gets a 👍 from me.

**Comment by friedmud** [comment]
Can we use `static_assert` now instead of just causing a compile error?

**Comment by permcody** [comment]
> Can we use static_assert now instead of just causing a compile error?
Good question, I honestly don't know since this is a macro... I'd have to play with it.

**Comment by friedmud** [comment]
I would think that the macro would expand to `static_assert` which would trigger the compiler to error out... but I've never tried.

**Pull request merged**
