### PR TITLE
Rename a few objects based on issues created

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #26615 #22055 #26755

### CODE REVIEW

**Comment by GiudGiud** [comment]
Should be ready for review now.

**Review by joshuahansel — CHANGES_REQUESTED** [review]
The renames seem good other than maybe `ExamplePatchMeshGenerator` - that one does sound like it needs to be moved to `test` (as suggested in the issue) if it has a name like that. And I would usually do "Test" instead of "Example", but this is an optional change.

**Comment by GiudGiud** [comment]
It's heavily relied on in Bison so we cant move it to test.
We could move it to Bison

**Comment by joshuahansel** [comment]
It's relied upon in Bison? For actual usage or just testing? If actual usage, then I guess "Example" is inappropriate. If just testing, we just need to have Bison add moose test objects in its test executable, right?

**Comment by GiudGiud** [comment]
Just testing. That's not really Makefile work I would like to do.
The renaming is necessary even if we move it to test and do the Makefile work btw

**Comment by joshuahansel** [comment]
Makefile work? I thought would just be a one-liner in `BisonTestApp`. For example, in `SockeyeTestApp::registerAll()` we do
```
ThermalHydraulicsTestApp::registerAll(f, af, s, true);
```
to get THM test objects. If that's not the case, then nevermind.

**Review by joshuahansel — APPROVED** [review]
The suggested move of `ExamplePatchMeshGenerator` to `test/` is an optional follow-up change (after Bison changes).

**Comment by GiudGiud** [comment]
Thanks! 
Ah yes it could be just that. That would be fine as long as Bison folks are fine with it

**Pull request merged**
