### PR TITLE
Writing/reading size of DenseMatrix to/from Checkpoint files  (#5380)

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by permcody** [comment]
Were you able to test this in Yak?

**Comment by snschune** [comment]
@permcody It works with the problem @gleicher27 gave me. Ran in RSN though.

**Comment by friedmud** [comment]
This should have had a test with it.  @snschune can you please add a small test to moose_test that uses a stateful DenseMatrix and needs this capability?  Make sure that it fails without your changes here... and works with them.

**Comment by snschune** [comment]
@friedmud Agreed. Problem is that a quick search showed me that MOOSE currently has no classes that declare any restartable DenseMatrix.
I can set up a userobject wrapping a stateful DenseMatrix. Any better ideas?

**Comment by YaqiWang** [comment]
Honestly we should let a moose developer do this. And chances that there are other data types are not tested for restart. What Sebastian did is just a fix to the bug in the existing code.

**Comment by friedmud** [comment]
Add it to the `RestartableTypes` object in MooseTest: https://github.com/idaholab/moose/blob/devel/test/src/userobjects/RestartableTypes.C

And check the values of it in `RestartableTypesChecker`: https://github.com/idaholab/moose/blob/devel/test/src/userobjects/RestartableTypesChecker.C

That will make it get checked by the `restartable_types` test: https://github.com/idaholab/moose/tree/devel/test/tests/restart/restartable_types

@YaqiWang No: the person adding the capability is responsible for testing it.

The existing capability was NOT a bug... nor was it wrong.  It was created for a different use-case... when the DenseMatrix size is set in its constructor (then the one getting passed in already has the right size).

**Comment by YaqiWang** [comment]
I can hardly agree this is not a bug. Sizing the DenseMatrix should come along with assignment always.

**Comment by YaqiWang** [comment]
@snschune checked the code and think it should not take him much time doing it. So he will just do it. I think we should thank Sebastian for fixing this.

**Comment by permcody** [comment]
Thanks @YaqiWang and @snschune. We get the best work done when we all work together. We appreciate your contributions and are more than happy to return the favor with fixes to Yak and Rattlesnake.

**Pull request merged**
