### PR TITLE
Disable non-sparse testing for some mortar continuity convergence tests

### PR DESCRIPTION
**Pull request by recuero**
These tests are failing with PETSc errors when running with the non-sparse recipe. Here, I am proposing disabling non-sparse testing for these tests. These should have been failing originally in #19092.

See https://civet.inl.gov/job/868045/

Refs. #13080

### CODE REVIEW

**Comment by recuero** [comment]
@jbadger95 just wondering what you'd recommend here. Were these originally run with the non-sparse option?

**Comment by jbadger95** [comment]
Hmmm so looks like the initial sparsity pattern is wrong, I mean technically we could remove this from the input file:

```
[Problem]
  error_on_jacobian_nonzero_reallocation = true
[]
```

That's interesting that the sparsity pattern is wrong on a non-deforming mesh in 2D though. We shouldn't have any edge dropping, I'll admit I'm not quite sure what's going on here. @lindsayad any thoughts?

**Comment by jbadger95** [comment]
I think the intention was to put 

```
[Problem]
  error_on_jacobian_nonzero_reallocation = true
[]
```

in all non-deforming problems so that we can be sure we're getting sparsity right. That's interesting there's no failure for sparse AD. Was this test disabled before or how did the mortar PR get through with this failure?

**Comment by jbadger95** [comment]
> Were these originally run with the non-sparse option?

I'll admit I've actually never used the non-sparse option, I'm not really familiar with it

**Comment by recuero** [comment]
Thanks, @jbadger95!

> Was this test disabled before or how did the mortar PR get through with this failure?

We had some technical difficulties in our testing, it should have been failing from the beginning

**Comment by lindsayad** [comment]
I don't know. The `AugmentSparsityOnInterface` object hasn't been modified in quite a while

**Comment by lindsayad** [comment]
Oh it was this change I think:
```
-      // SecondaryPrimary
-      mortar_interface_coupling.insert(std::make_pair(secondary_elem->interior_parent()->id(),
-                                                      primary_elem->interior_parent()->id()));
-      // PrimarySecondary
-      mortar_interface_coupling.insert(std::make_pair(primary_elem->interior_parent()->id(),
-                                                      secondary_elem->interior_parent()->id()));
```
I remember us talking about this @jbadger95 and I said let's give it a whirl and see whether anything breaks ... and at the time it didn't! So the sparse container is telling us that indeed these couplings do not exist because we never fill those spots in the AD indices container ... but I have some dumb code somewhere that manually iterates over `PrimarySecondary` and `SecondaryPrimary` and fills it

**Comment by lindsayad** [comment]
@recuero I'm going to look for this dumb code (I think I know where it is). I'm going to push to your PR. And then let's try not disabling the nonsparse testing

**Comment by recuero** [comment]
Great!

**Comment by jbadger95** [comment]
@lindsayad It might actually be coming from the structure of GapConductance (it's not really a mortar constraint, it's kind of hacking mortar to use the flux). For example on `GapConductanceConstraint:74`:

```
case Moose::MortarType::Lower:
    {
      // we are creating an AD version of phys points primary and secondary here...
      ADRealVectorValue ad_phys_points_primary = _phys_points_primary[_qp];
      ADRealVectorValue ad_phys_points_secondary = _phys_points_secondary[_qp];

      // ...which uses the derivative vector of the primary and secondary displacements as
      // an approximation of the true phys points derivatives when the mesh is displacing
      if (_displaced)
        for (unsigned int i = 0; i < _n_disp; ++i)
        {
          ad_phys_points_primary(i).derivatives() = (*_disp_primary[i])[_qp].derivatives();
          ad_phys_points_secondary(i).derivatives() = (*_disp_secondary[i])[_qp].derivatives();
        }

      auto l =
          std::max((ad_phys_points_primary - ad_phys_points_secondary) * _normals[_qp], _min_gap);
      return (_lambda[_qp] - _k * (_u_primary[_qp] - _u_secondary[_qp]) / l) * _test[_i][_qp];
    }
```

Looks like `l` is an AD value (would depend on displacements but we aren't displacing here). Anyway is it happening because we're dividing u_primary and u_secondary by this AD guy? I'm not sure, there's not displacement variables so I don't see what it would be adding to the sparsity structure but as you note this extra sparsity doesn't really exist and maybe this the culprit?

**Comment by lindsayad** [comment]
@recuero I just pushed. Can you try turning those tests back to being tested with nonsparse?

@jbadger95 I don't think that should be affecting those tests because they are undisplaced

**Comment by jbadger95** [comment]
@lindsayad Ah yeah it's not only gap conductance that's failing, you're right

**Comment by jbadger95** [comment]
I like the fix, I guess it wasn't allocating the extra guys for sparseAD because in that case 0 is cast to an ADReal with no indices where when you have non-sparse AD it was cast to a full vector of 0's that were then being added to the Jacobian?

**Comment by recuero** [comment]
@lindsayad I am getting similar PETSc messages after removing my commit and leaving yours locally.

**Comment by lindsayad** [comment]
ruh roh

**Comment by lindsayad** [comment]
I'll do some local testing as well

**Comment by lindsayad** [comment]
everything is passing for me locally...

**Comment by recuero** [comment]
Wow that's fast compilation! Not sure what the difference would be. I'll push force to eliminate my commit.

**Comment by lindsayad** [comment]
No I wouldn't do that yet. I'm really confused ... if I just go to `next`, then stuff is passing for me too

**Comment by lindsayad** [comment]
PYTHONPATH user error for those following at home... 😆

**Review by loganharbour — APPROVED** [review]
Failures are unrelated. Merging with failures as this resolves the nonsparse test failures in https://civet.inl.gov/event/78326/

**Pull request merged**
