### PR TITLE
Back away magic subdomain ids from UINT16_MAX

### PR DESCRIPTION
**Pull request by roystgnr**
In the long run we need to be using subdomain names here, from the nice big ~50^32 sized namespace available there, not picking from 2^16 ids and hoping to avoid conflicts.

In the short run, this at least gives us a little breathing room in between the hard-coded ids and the default maximum subdomain_id_type value, so we can autogenerate subsequent ids safely.

I regenerated the gold exodus files by manually search-and-replacing saved ids in ncdump output, then ncgen'ing the result, to make sure there weren't any unwanted changes inadvertently slipped in.

Refs #19950

This isn't quite enough to make MOOSE compatible with https://github.com/libMesh/libmesh/pull/3613 but it fixes most of the conflicts for me.

Pinging @shikhar413 for his opinion on whether this is a reasonable short-term fix.  I'll start up a separate issue for the remaining problem, which seems to be unrelated to the id choice here.

### CODE REVIEW

**Comment by shikhar413** [comment]
Works for me, I'll defer to @GiudGiud to decide whether this change is acceptable. In the long run, I have some ideas on how we can possibly move away from these magic number subdomain ids for this particular application, but this won't be done any time soon.

**Comment by GiudGiud** [comment]
I ll look at this soon. Dont worry about unrelated failures, CI failures dont stop me from reviewing.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
> I regenerated the gold exodus files by manually search-and-replacing saved ids in ncdump output, then ncgen'ing the result, to make sure there weren't any unwanted changes inadvertently slipped in.

this is awesome. we need to do this more often

**Comment by loganharbour** [comment]
> this is awesome. we need to do this more often

I think that we should leverage the reporter system more for a lot of this if we can. being able to more clearly see the data is wonderful

**Comment by roystgnr** [comment]
IMHO the test suite in https://grinsfem.github.io/ does things the Right Way for many problems.  Don't try to assert that l ᪲  error norms against a gold solution are below some tolerance, compute L² norms and H¹ seminorms against a gold or manufactured or analytic solution and assert that *those* are low enough.  Fewer false positives, fewer false negatives, the analytic and manufactured solution cases give you actual verification rather than just regression testing, and with the right tolerances you can even test cases where an adaptive mesh refinement pattern is sensitive to solver noise.

**Pull request merged**
