### PR TITLE
Reorganized Transient, Added NestedTransient, Changed XFEM tests #9588

### PR DESCRIPTION
**Pull request by yingjie1989**
### @bwspenc  @permcody 

- Include any relevant design information for your change
   Reorganized Transient.C, developed NestedTransient.C and modified the tests of XFE. All tests of XFEM have passed
   
- Test cases: All the tests in xfem module: moose/module/xfem/tests/
- closes issue # 9588

### CODE REVIEW

**Comment by YaqiWang** [comment]
Looks to me this new executioner should be in XFEM module.

**Comment by bwspenc** [comment]
@YaqiWang We have a need for nested solves for several applications: contact, XFEM, and fracture are just a few examples.  This is a general capability that I think belongs in some form in the framework.  @permcody and I discussed doing something like this a while back, and this is a starting point for discussion.  I still need to review this code myself.

**Comment by YaqiWang** [comment]
Actually I am very happy to see xfem word is removed from Transient, which is a monster and hard to read and extend. But the derived class has still xfem words everywhere, which makes me wonder if it should be in xfem module. Maybe it's just a minor naming issue.

**Comment by permcody** [comment]
@yingjie1989, I second @YaqiWang's comment. Looking at the NestedSolver, it really should live in the XFEM module. Make sure that "NestedSolver" is really the name we want as well. I'm not sure that name is necessarily clear. The Transient changes look acceptable on the surface.

**Review by permcody — CHANGES_REQUESTED** [review]
Please move this new Executioner to the XFEM module.

**Comment by agiorla** [comment]
I will second @bwspenc  comment, nested solver may be used in other context than XFEM, so I would prefer to have a generic architecture directly in the framework for this kind of capabilities.

**Comment by bwspenc** [comment]
There are two goals of these changes:
1) Remove XFEM-specific code from the Transient Executioner.
2) Start down the path of creating a generic system that we can use for other things like XFEM that need this.
I agree that the code in NestedTransient is currently very XFEM-specific, and in the current state, this does look like it belongs in the XFEM module.  I'd like to come up with some general system that follows this flow, but offers pluggable interfaces for other things to get done after a nested solve happens.
@yingjie1989 has some code sitting in the wings right now that we want to get integrated into MOOSE for Augmented Lagrange contact enforcement that needs to do updates at these same times.  I'll come by sometime today to discuss what our needs are in this area.

**Comment by friedmud** [comment]
This looks like a good topic for the tiger team...

**Comment by permcody** [comment]
Closing due to inactivity.

**Pull request closed without merging**
