### PR TITLE
Fix ComputeLinearElasticPFFractureStress.C when using snes solver with barrier

### PR DESCRIPTION
**Pull request by ghost**
closes #26536

## Reason
Cannot have a barrier function with the use of snes solver

## Design
Put the barrier out of the snes if scope

## Impact
It will allow the use of the barrier function with snes solver

### CODE REVIEW

**Comment by jiangwen84** [comment]
In your commit message, you just need to add "ref #26536", NOT "closes ref #26536".

**Comment by jiangwen84** [comment]
And these two commits should be merged into one.

**Comment by dschwen** [comment]
Is there a regression test for this?

**Comment by jiangwen84** [comment]
> Is there a regression test for this?

I do not see it. @nshabib could you quickly add one that use both VI and barrier? thanks.

**Comment by nshabib** [comment]
> > Is there a regression test for this?
> 
> I do not see it. @nshabib could you quickly add one that use both VI and barrier? thanks.

Hi, i will close this pr as we've encountered another issue actually as per the newest comment in https://github.com/idaholab/moose/discussions/26534. Best regards.

**Pull request closed without merging**
