### PR TITLE
Add LeastSquaresFitHistory VectorPostprocessor

### LINKED ISSUE #11709: Version of LeastSquaresFit VPP that outputs full history
## Rationale

I'm using the LeastSquaresFit VPP to output a set of files containing the coefficients -- a separate file for each time step. This is a big pain, because I really want them all in one file, so I have been using a script to combine them. Now that we have the `contains_complete_history` option in the VPPs, we don't have to do that.

## Description

Add a new LeastSquresFitHistory VPP that stores the coefficients in a set of vectors that grow over time. This significantly changes the code, so I don't think it makes sense to just have this be an option in the current LeastSquaresFit VPP. There may not really be a need to still keep around the current LeastSquaresFit VPP, but I'd say we should keep it for the time being, at least until I migrate my usage of it over to the new one. I'm not sure whether anyone else is using it.

## Impact

Add a new VectorPostprocessor object. This will not impact other parts of the code.

### PR DESCRIPTION
**Pull request by bwspenc**
Adds code, test, and documentation
closes #11709

### CODE REVIEW

**Comment by permcody** [comment]
Those are really bizarre errors... It feels like the `--half-transient` part isn't working or something. I see that you aren't setting `n_steps`, which is supported but not something we use a lot in the regression test suite. You also designed this test to take only two steps (again should be fine), but if there's a floating point issue. I suspect something else is going wrong here that's not related to the recover part of the problem. Perhaps you've uncovered a new bug. Try supplying `n_steps` explicitly or making it last until time = 3.0 or something to make sure it takes that first step.

**Comment by bwspenc** [comment]
Thanks for the help, @permcody. I tried setting both `num_steps` and `end_time`, and it passes on my machine when I run with `--recover`, but it doesn't work unless I have both of them specified. I just pushed an update that has both of those set (which feels a little ugly since just one or the other should be sufficient). I'll see if that passes on those platforms that were giving me trouble.

**Comment by permcody** [comment]
Here's the code that `--half-transient` triggers:
https://github.com/idaholab/moose/blob/devel/framework/src/executioners/Transient.C#L245-L252

I can't see what would be wrong with this, but it seems like it's not taking even one step.

**Comment by bwspenc** [comment]
@permcody I finally got it to pass by moving this test into a different directory from the one that was originally there (which I assume using `prereq` would have also accomplished). It may have been some kind of issue with the two tests (least_squares_fit_history.i and least_squares_fit.i) writing to the same file, but that doesn't really make any sense to me because they had different file names and write to different output files (only csv files in this case).

**Review by permcody — APPROVED** [review]

**Pull request merged**
