### PR TITLE
Move InterfaceDiffusion and PenaltyInterfaceDiffusion to framework

### PR DESCRIPTION
**Pull request by fdkong**
Closes #19059

### CODE REVIEW

**Review by lindsayad — DISMISSED** [review]
Assuming this shows close-to 100% covered for new framework lines (it should, unless these test objects weren't actually being used), then this looks good to go to me!

**Comment by fdkong** [comment]
OK, I need to fix docs. We are missing docs for these kernels.

**Comment by fdkong** [comment]
@lindsayad  It is ready for review again.

I added docs for the kernels

**Review by loganharbour — APPROVED** [review]
👍🏼

**Review by loganharbour — CHANGES_REQUESTED** [review]
Sorry - didn't see the new docs

**Review by loganharbour — DISMISSED** [review]

**Comment by fdkong** [comment]
I think this is ready.

**Review by lindsayad — APPROVED** [review]

**Comment by fdkong** [comment]
I might merge it soon if you do not have additional comments

**Review by jiangwen84 — APPROVED** [review]

**Pull request merged**
