### PR TITLE
Updating the mailmap for MOOSE

### PR DESCRIPTION
**Pull request by permcody**
refs #12160

### CODE REVIEW

**Comment by lindsayad** [comment]
Is this supposed to include all MOOSE contributors? I don’t see you, Robert, Fande, or me...?

**Comment by permcody** [comment]
Only people that have lots of “aliases”!

Try running “git short log -sn”. Then add the “e” option.

**Review by lindsayad — APPROVED** [review]

**Comment by tophmatthews** [comment]
581  Benjamin Spencer
   174  Ben Spencer

**Comment by tophmatthews** [comment]
Stephanie Pitts

**Comment by tophmatthews** [comment]
52  Andrew E. Slaughter <slaughter98@gmail.com>

**Comment by tophmatthews** [comment]
(can you tell I'm procrastinating writing milestones?)

**Comment by tophmatthews** [comment]
Stephanie and Andrew are listed twice:
```
  2528  Andrew E. Slaughter <andrew.slaughter@inl.gov>
    52  Andrew E. Slaughter <slaughter98@gmail.com>

    53  Stephanie Pitts <pitts.stephanie@gmail.com>
    49  Stephanie Pitts <stephanie.pitts@inl.gov>
```
even you?
```
  1927  Cody Permann <cody.permann@inl.gov>
    76  Cody Permann <Cody.Permann@inl.gov>
```

**Comment by permcody** [comment]
Try `git shortlog -sn`. Drop the 'e'. That's what I was using. I know it's possible to remap email addresses too, but I wasn't worried about that.

**Comment by tophmatthews** [comment]
OH! I see. I thought it only added email addresses, but still had the same ordering.

**Comment by permcody** [comment]
It's an overloaded file. It does arguably too much. I just wanted to get to a single list of names even if those people used multiple email addresses. Maybe I'll go back later and try to remap email addresses, but that'll take more work to stay on top of.

**Comment by tophmatthews** [comment]
~190 ain't bad!

**Comment by permcody** [comment]
No - but I was hoping to report 200+ users - Doh!

**Pull request merged**
