### PR TITLE
Rename a material property from density to current_density

### LINKED ISSUE #7811: Density material in misc module is evaluating the current density
### Description of the enhancement or error report
This density material property is required by my problem for the thermal conduction kernel. However, I also need the `InertialForce` kernel under tensor mechanics module, which should be using the original density but currently getting a property in name of `density`. This property in name of `density` declared by Density.C is indeed the current density.

### Rationale for the enhancement or information for reproducing the error
Miss match could be created with Density.C.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

 I am suggesting to change the property name in Density to `current_density`. This change will impact several files in modules

```
	modified:   heat_conduction/src/kernels/HeatConductionTimeDerivative.C
	modified:   heat_conduction/src/kernels/SpecificHeatConductionTimeDerivative.C
	modified:   misc/src/Density.C
	modified:   solid_mechanics/src/kernels/SolidMechImplicitEuler.C
	modified:   tensor_mechanics/src/kernels/Gravity.C
	modified:   tensor_mechanics/src/postprocessors/Mass.C
```

which looks to me all are using the current density anyway. The changes in module is pretty minimal. Not sure about the applications. I am also not so sure about `solid_mechanics/src/kernels/SolidMechImplicitEuler.C`, but if it is an issue, it can be fixed later. This will fix my issue. I am also suggesting to keep the `density` material property in Density.C but make it as the original density.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #7811.

### CODE REVIEW

**Comment by YaqiWang** [comment]
This PR fails BISON, RELAP-7 and MAMMOTH as expected. If @bwspenc and/or anybody are OK with this change, I can send in patches.

**Comment by dschwen** [comment]
We actually wanted to rename the parameter of the Density Material `initial_density` rather than density. I guess this change is somewhat orthogonal though.

Actually I'd much rather have the density be called `density` rather than overqualify this common material property. `density` conveys exactly what it is. I'd rather see that thing that apparently needs the density of the undeformed mesh (or whatever the heck _initial density_ is supposed to be) renamed.

**Review by bwspenc — COMMENTED** [review]
I was just going to say the same thing as @dschwen .  I'd rename the property that sets the initial density to initial_density.

**Comment by YaqiWang** [comment]
It is orthogonal. I picked the easier route. This at least will differentiate the current density and the original density. We can change the hardcoded density names elsewhere into `original_density`. We will be asking users to use `original_density` when they add the density material through `GenericConstantMaterial`. BTW, it seems `original` is preferred than `initial`, do you agree?

**Comment by dschwen** [comment]
Original? Just because you start your simulation at some arbitrary temperature that does not make that density _original_.

**Comment by YaqiWang** [comment]
I think original means a density with stress-free at a reference temperature. Changing temperature will create displacement, which will result into the current density.

**Comment by bwspenc** [comment]
I think initial is preferred.  We have other parameters name initial_something in BISON.

**Comment by YaqiWang** [comment]
I should add that I am using the name from Ted Belytschko's book. Also the developer of `Density.C` is also using `_orig_density`. I do think that it makes more sense.

**Comment by YaqiWang** [comment]
I am going to close this but leave the issue open because the issue appears real but this fix is not satisfactory.

**Pull request closed without merging**
