### PR TITLE
Remove old hit syntax for easier copy pasting of tests

### PR DESCRIPTION
**Pull request by GiudGiud**
Refs #9845

Not the most useful PR, but would save me a few seconds every time I go fish an existing test, and that adds up.

Sorry for whoever will review this if we go forward. Maybe we should build a script to review it? It's not SQA though

### CODE REVIEW

**Comment by loganharbour** [comment]
I would really rather not do this until we can do this systematically with pyhit and can also enforce formatting on PRs. @dschwen can weigh in on this - I believe we're still waiting on #15797 and maybe others?

In addition, we should really do this on a bot user to make the change more clear like was done with the clang format switch.

**Comment by friedmud** [comment]
I somewhat agree with @loganharbour  - but how far out are those capabilities?  If we're still a year or so out - might as well do this first.

**Comment by GiudGiud** [comment]
Let's just do it now.
Had to delete more dots today, pissed me off for like a whole thirsty seconds

**Comment by loganharbour** [comment]
I still prefer to do this on a system account

**Comment by WilkAndy** [comment]
Just out of interest, how did you ensure the documentation `listing` stuff still displays correctly when you remove all those dots?  when i did this for porous_flow and geochemistry, i had to check all the markdown by hand, i think because `end=[]` wasn't always correct any more.

**Comment by GiudGiud** [comment]
I didn't. I ll have a look now

**Comment by loganharbour** [comment]
If we do want to go through with this, we do need to produce some sort of diff for the produced websites to make sure that we don't mess up any of the input listings that are defined by start/end like @WilkAndy described.

Any ideas on how to quickly do this @aeslaughter?

**Comment by dschwen** [comment]
Agree with @loganharbour 

- Do it once multiline strings don't get messed up by `hit format`
- Do it with a system account
- Enforce hit formatting in PRs

**Comment by loganharbour** [comment]
> Do it once multiline strings don't get messed up by hit format

ETA?

**Comment by dschwen** [comment]
Besides, it really isn't a huge hurdle to press `Shift+Cmd+H` in Atom to hit format your current file, so the copy/paste argument seem weak to me.

**Comment by dschwen** [comment]
Tagging @rwcarlsen . A quick fix to not touch ML strings should not take long at all. Later we could worry about heuristics for consistent indentation etc.

**Comment by rwcarlsen** [comment]
Like others have said - there is more preparation/work required before we can do something like this. We need to

* decide solidly on the actual/exact format we want for the files - so we don't have to do this again.
* prevent things from regressing - i.e. have CIVET recipes for checking things like with clang format.
* make it easy for users to comply - have easy automatic formatting tools users can run (e.g. something in their path, editor plugins, etc.).
* If we are also going to format everything in one go, also possible provide a script to help/fix in-flight PRs people have - because this kind of PR causes massive conflict headaches for every PR that touches tests.

Without addressing at least the first 3 bullets, we shouldn't be doing this.

**Comment by GiudGiud** [comment]
@dschwen 
- not everyone uses Atom or your plugins. 
- it seems to me multiline strings have nothing to do with [../]
- enforcing the hit format in PRs is super low impact work, so no one will tackle this.

@rwcarlsen 
- I see no issue with doing this thing again. Syntax evolves, we adapt. NQA does not prevent us from doing this. Goal of MOOSE is not to have the least amount of commits
- The conflicts from this PR will be trivial to deal with. People don't need python scripts to remove dots and slashes in the few folders they have.
- compliance and regression are not real concerns either. Once the [] syntax is everywhere, no one will introduce [../] on purpose. People copy what they see, they don't make up new inputs from scratch. Changing the syntax everywhere fixes the problem. 

You can however look at the growing list of conflicting files to see that people are adding the old syntax in tests file, where they are finding it.

**Comment by rwcarlsen** [comment]
But it's disruptive both in in-flight PR conflicts - breaking git blame and history tracking on files, etc.  It takes time for the submitter and reviewers, etc.  Plus - as you note - regressions will be continual - it would be much more desirable to prevent/disallow regressions.  Nobody is saying this isn't a good idea - just that a bit more preparation and work is desirable to make things more permanently better.

**Comment by GiudGiud** [comment]
git blame will still work for the core of the tests. It will only be 'broken' for the [] lines (I argue it works as expected). And these don't really matter.

It's disruptive now, it'll be disruptive later too. I don't see the difference. 

I note that regressions are happening now because people are seeing the old syntax. Regressions will be exceedingly rare once the new syntax is in. We have to worry about like the next two batches of PRs.

**Comment by rwcarlsen** [comment]
I really think we still need my first three bullets addressed above.  They are completely doable in a reasonable amount of time, but it will take more work than just a reformatting PR.

**Comment by GiudGiud** [comment]
nah I ll get to it

**Pull request closed without merging**
