### PR TITLE
Report a module name instead if we can

### LINKED ISSUE #28571: Share module information within `PreMake`
### Motivation

If using the `moose-dev-*` modules, as in:

```
module load use.moose moose-dev-openmpi
```

on HPC, we should report a version mismatch using the modules in the URI for a better user experience.

The current error looks like:

```
WARNING: Container moose-dev-openmpi-x86_64 is currently at version 0416bb4 and the required version is 561161b.
Before updating the container, make sure that your version of MOOSE is up to date.

You can obtain the correct container at oras://harbor.hpc.inl.gov/moose-dev/moose-dev-openmpi-x86_64:561161b.
```

but should look something like:

```
WARNING: Container moose-dev-openmpi-x86_64 is currently at version 0416bb4 and the required version is 561161b.
Before updating the container, make sure that your version of MOOSE is up to date.

You can obtain the correct container by using the module moose-dev-openmpi/561161b
```

### Design

Change the `PreMake` to support the new error instead when it is detected that a module is being used.

### Impact

Improved user experience.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #28571

When using:

```
> module load use.moose moose-dev-openmpi
> moose-dev-shell
```

with an invalid version, the error used to be:

```
WARNING: Container moose-dev-openmpi-x86_64 is currently at version 561161b and the required version is 0416bb4.
Before updating the container, make sure that your version of MOOSE is up to date.

You can obtain the correct container at oras://harbor.hpc.inl.gov/moose-dev/moose-dev-openmpi-x86_64:0416bb4.
```

and it is now:

```
WARNING: Container moose-dev-openmpi-x86_64 is currently at version 561161b and the required version is 0416bb4.
Before updating the container, make sure that your version of MOOSE is up to date.

You can obtain the correct container via the module moose-dev-openmpi/0416bb4.
```

### CODE REVIEW

**Comment by GiudGiud** [comment]
> Closes #561161b

what is #561161b

**Comment by loganharbour** [comment]
> > Closes #561161b
> 
> what is #561161b

Thanks, fixed. Lazy copy pasta failure.

**Review by milljm — APPROVED** [review]
👍

**Comment by loganharbour** [comment]
Failure is unrelated.

**Pull request merged**
