### PR TITLE
Add IGA example and documentation

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
https://github.com/idaholab/large_media/pull/29 is required for this to work

**Comment by lindsayad** [comment]
who's this crazy guy?

**Comment by loganharbour** [comment]
Looks like we need to upgrade VTK on the test boxes to test this. At least the conda runs grab it.

**Comment by aeslaughter** [comment]
@lindsayad Need to get a few commits to hold you back for a bit longer.

**Review by loganharbour — APPROVED** [review]
I'm upgrading vtk to 9 on the build boxes. I'd like to test it here before we merge. Should be ready soon.

**Review by loganharbour — CHANGES_REQUESTED** [review]
Minor change while I'm waiting

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
