### PR TITLE
Stitch with verbose=false for patterns stitching to avoid slurry of console output

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #23336

Only doing patterns for now since they are the most problematic. 
We could do all stitching once we have a verbosity interface

### CODE REVIEW

**Comment by GiudGiud** [comment]
Failures are unrelated.

**Comment by GiudGiud** [comment]
Down to have this to debug the VTB btw

**Comment by lindsayad** [comment]
Need to resolve the merge conflict

**Comment by GiudGiud** [comment]
done

**Review by lindsayad — APPROVED** [review]
I think this change is the more sensical default, but I do think the verbosity can be useful in cases. I would ideally like to see a parameter to control this

**Comment by GiudGiud** [comment]
I will add it when I do the MooseVerbosityInterface

**Pull request merged**
