### PR TITLE
Disallow by default ICs on restart for restarted variables

### LINKED ISSUE #21423: Checkpoint: no log or warning on conflict between restart and initial conditions
## Bug Description
When using the checkpoint restart system, the initial conditions are likely not to be used. There is nothing telling the user that they are used anyway

## Steps to Reproduce
Do a restart from checkpoint simulation, forget to delete your ICs

## Impact
Wasted time on code coupling work

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #21423

Status of app patches:
- [x] BISON https://github.inl.gov/ncrc/bison/pull/5593
- [x] Griffin https://github.inl.gov/ncrc/griffin/pull/1496
- [x] Pronghorn https://github.inl.gov/ncrc/pronghorn/pull/1223
- [x] RELAP7 https://github.inl.gov/ncrc/relap-7/pull/2547
- [x] SAM https://git-nse.egs.anl.gov/ac.giudicelli/SAM/-/commits/PR_ics
- [x] Sockeye https://github.inl.gov/ncrc/sockeye/pull/725
- [x] Subchannel https://github.inl.gov/ncrc/subchannel/pull/292
- [x] BlueCrab https://github.inl.gov/ncrc/blue_crab/pull/221

### CODE REVIEW

**Comment by GiudGiud** [comment]
All patches have been merged, good to go

**Review by lindsayad — APPROVED** [review]
as long as subchannel passes

**Comment by GiudGiud** [comment]
Passes now. Thanks for the review!

**Comment by YaqiWang** [comment]
@GiudGiud heavy tests in Griffin: https://civet.inl.gov/job/1790464/ need to be fixed for this change. There is also one VTB griffin test.

**Comment by GiudGiud** [comment]
Patches are up

**Pull request merged**
