### PR TITLE
Feature 12769

### PR DESCRIPTION
**Pull request by danielbi-ETHZ**

### CODE REVIEW

**Comment by permcody** [comment]
Welcome to the community! If you have any questions about your test failures, don't hesitate to ask. It looks like you have a few formatting issues. You should be able to find the exact errors inside of the failed precheck target linked above.

**Comment by danielbi-ETHZ** [comment]
Dear Cody,

I initiated a pull request for MOOSE, but the automated checks seem to have failed. When I click on the details of why they failed, I get the following error message:

You are not allowed to see results. Please sign in to an appropiate user.

Please let me know what the next steps are.

Thanks,
Daniel Birdsell

----------------------------------------------
Daniel Birdsell

PostDoc at
Geothermal Energy and Geofluids
Institute of Geophysics
ETH Zurich
Sonneggstrasse 5, NO F61
CH-8092 Zurich
SWITZERLAND

Office: +41 44 632 47 10
Cell: +1 505 690 3741
----------------------------------------------

**Comment by permcody** [comment]
You only need elevated permissions to look at some of the internal apps. You should be able to click on the "Precheck" box without logging in.

**Comment by permcody** [comment]
Superseded by #12795.

**Pull request closed without merging**
