### PR TITLE
Rename interpolation transfers, docstring fixups

### PR DESCRIPTION
**Pull request by GiudGiud**
early PR for awareness

### CODE REVIEW

**Comment by GiudGiud** [comment]
seems everyone hates my new names. Will change it up

**Comment by lindsayad** [comment]
Was this hate from within the office? I kind of liked Geometric and Algebraic (or at least I didn't hate it)

**Comment by GiudGiud** [comment]
Algebraic is a pretty good one. We had FEInterpolation

**Comment by GiudGiud** [comment]
ok got to wait on a next merge to handle the conflicts, but still ready for review imo

**Comment by GiudGiud** [comment]
ready for review

**Comment by GiudGiud** [comment]
@lindsayad should be good now

**Comment by lindsayad** [comment]
@joshuahansel the failure here makes me think you may get non-deterministic error messages for that test with distributed mesh. Can we look into that?

**Review by lindsayad — APPROVED** [review]
:+1:

**Pull request merged**
