### PR TITLE
Tweak the documentation

### PR DESCRIPTION
**Pull request by nmnobre**
## Motivation
Typos and spelling mistakes in the documentation

## Design
Fix the mistakes using a spell checker and check afte rthat it's correct

## Impact
Helps robots reading our code spell properly

Hi @GiudGiud,

This escalated quickly, again... 😇

The only thing of note is that I changed the order of the time and space coordinates in the docs for the functions system to match the implementation of that class's methods. Then, well, then I fixed a few typos. I gave up for now, I'll come back to it another day.

Cheers,
-N

### CODE REVIEW

**Review by joshuahansel — APPROVED** [review]
Thanks a lot! I'm guessing you ran a spell checker on all of the md files? Was it a pain, with a bunch of false positives? Apparently we're terrible at spelling/typos.

**Comment by nmnobre** [comment]
> Thanks a lot! I'm guessing you ran a spell checker on all of the md files? Was it a pain, with a bunch of false positives? 

Indeed. I ran aspell with a standard English dictionary and wrote all the hits onto the same file.
Then, I opened this file in Visual Studio Code, loads of false positives. But then Code will also run its own spell checker, which both underlines in red all the typos it sees but also tries to be clever about camel case (you'll see I fixed some typos in class names, it's cool). So this excludes some of the false positives. The caveat is it stops at 1000 errors, so next time I might split the file in multiple smaller ones. I noticed it gets confused if you start deleting rows, the file is just too big for it to manage reasonably (I started with ~12,000 lines). Then, I just look in the MOOSE source for each typo and try to amend each of its occurrences. I try to read at least the sentence that word pertains to, for context. It's rare, but it has happened the first suggested correction isn't the right one.

**Comment by nmnobre** [comment]
I'm doing a couple more before bed, so let me push those and then once the tests finish you can merge. :)

**Comment by nmnobre** [comment]
Hi @joshuahansel, thanks for waiting. I think I'm done now! :)
I'm sure I missed a ton of other small mistakes, but those you can only spot by reading things thoroughly.
I'll create PRs as I spot them.

Two things I couldn't decide what to do with:

1) Is this on purpose? Referring to u_{i} while using u_{di}?
https://github.com/idaholab/moose/blob/aab76d5271d84a92d1d1e0b4e17aa757a1f4a612/modules/navier_stokes/doc/content/source/fvkernels/PINSFVMomentumAdvection.md?plain=1#L10-L11

2) It reads weird to me that the electron is transferred _between_ the two iron oxidation states. I'd expect the transfer to happen between the iron and the oxygen. I'd also move the acceptor/receptor sentence to the end, _after_ explaining the half-reaction. That's because it's not uncommon to use the same acceptor/receptor terminology for the two completely different species involved in the full redox reaction.
https://github.com/idaholab/moose/blob/aab76d5271d84a92d1d1e0b4e17aa757a1f4a612/modules/geochemistry/doc/content/modules/geochemistry/geochemistry_nomenclature.md?plain=1#L99

**Comment by joshuahansel** [comment]
Thanks @nmnobre. I think 1 is fine as-is. I think you should make the changes for 2 that you suggested.

**Comment by nmnobre** [comment]
> Thanks @nmnobre. I think 1 is fine as-is. I think you should make the changes for 2 that you suggested.

All done. Fixed 2) as suggested and agreed on a fix to 1) with @GiudGiud.

**Comment by lindsayad** [comment]
@joshuahansel please merge as you see fit

**Pull request merged**
