### PR TITLE
Remove legacy params specializations in modules

### PR DESCRIPTION
**Pull request by dschwen**
Only 2737 files now ! :-D

Refs #14135

### CODE REVIEW

**Comment by loganharbour** [comment]
All this work for immediate failure 😬

**Comment by dschwen** [comment]
> All this work for immediate failure

You do realize _that_ failure was Civet's fault, though, right? (That's not to say some other crap isn't going to fail once I invalidate...)

**Comment by loganharbour** [comment]
> > All this work for immediate failure
> 
> You do realize _that_ failure was Civet's fault, though, right? (That's not to say some other crap isn't going to fail once I invalidate...)

Absolutely. Still got a kick out of it, though.

**Comment by dschwen** [comment]
And of course there is a ton more to fix for me...

**Review by loganharbour — APPROVED** [review]
Forward declarations too? Beautiful.

**Comment by permcody** [comment]
Nice work!

**Pull request merged**
