### PR TITLE
Revise clobber target

### LINKED ISSUE #6258: make clobber doesn't work for me
I get:

find: The -delete action atomatically turns on -depth, but -prune does nothing when -depth is in effect.  If you want to carry on anyway, just explicitly use the -depth option.

I think make clobber has to start with

        $(shell find $(CURDIR) -depth

a

### PR DESCRIPTION
**Pull request by dschwen**
This should work. It goes back to using xargs. I'm using a two stage approach to clean out the bulk of object files in the .libs folders first. I haven't timed it yet though.

Closes #6258

### CODE REVIEW

**Comment by jwpeterson** [comment]
I'm curious why you decided to remove the `$(shell ...)` directives that were there.  I'm pretty sure that is the most portable way to call the shell from a Makefile.

**Comment by dschwen** [comment]
Ha, yeah, I thought so, too. Turns out it was totally retarded. $() executes the shell command and tries to execute the return value again. So if the command produces any output whatsoever it tries to execute it.

**Comment by jwpeterson** [comment]
> $() executes the shell command and tries to execute the return value again. So if the command produces any output whatsoever it tries to execute it.

Pretty sure it doesn't do that.

https://www.gnu.org/software/make/manual/html_node/Shell-Function.html

"The shell function performs the same function that backquotes (‘`’) perform in most shells: it does command expansion. This means that it takes as an argument a shell command and evaluates to the output of the command. The only processing make does on the result is to convert each newline (or carriage-return / newline pair) to a single space. If there is a trailing (carriage-return and) newline it will simply be removed."

So it ensures that newlines are converted to spaces in whatever is returned by the shell.  I think we need to keep it.

**Comment by dschwen** [comment]
Backticks does that as well

**Comment by jwpeterson** [comment]
I think I incorrectly extrapolated the examples where `$(shell)` appears on the right-hand side of an assignment to cases where you just need to call a program in the shell... FML.

**Pull request merged**
