### PR TITLE
Moves Python code to 4 spaces and maintain ownership

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #8454)

### CODE REVIEW

**Comment by permcody** [comment]
I'm supportive of this change since it is more inline with PEP 8: https://www.python.org/dev/peps/pep-0008/ and does indeed make the code more readable. The fact that we can preserve ownership is very helpful. 

@friedmud - we have talked this over in the cube quite a bit and everyone is in favor of changing the Python standard. We have no plans to modify the C++ standard. I know you are an outspoken dissenting opinion but I'm willing to move if all the guys writing Python really want this change. We'll update the standard once this is merged. Please record your comments if you still stand in opposition.

**Comment by dschwen** [comment]
@aeslaughter please change the `.editorconfig` file accordingly. Add this section:

```
[*.py]
indent_size = 4
```

**Comment by permcody** [comment]
Needs rebase before merge.

**Review by permcody — CHANGES_REQUESTED** [review]
Needs rebase

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Well here we go...
@aeslaughter please update the Python style guide!

**Comment by aeslaughter** [comment]
Thanks, I will update the guide. I will also work on the "pylint" or other
tool for enforcing the standard.

**Pull request merged**
