### PR TITLE
Adding missing calls to set current subdomain

### PR DESCRIPTION
**Pull request by andrsd**
This is fixing missing calls to set current subdomain ID and improves `PointValue` test, so the new asserts in `Assembly` are tripped when things are not right.

### CODE REVIEW

**Review by rwcarlsen — APPROVED** [review]
LGTM

**Comment by YaqiWang** [comment]
Can we re-merge? I was going to suggest to fix MooseMesh in this PR...

**Comment by andrsd** [comment]
> Can we re-merge?

Not merged yet.



> I was going to suggest to fix MooseMesh in this PR...

Like in 2b437bc ?

**Comment by YaqiWang** [comment]
yes

**Pull request merged**
