### PR TITLE
Added Postprocessor to display a MooseFunction value

### PR DESCRIPTION
**Pull request by j2bradley**

### CODE REVIEW

**Comment by dschwen** [comment]
Append ```(#5197)``` to your commit messages. Use
```
git rebase -i HEAD~2
```
to edit the messages.

**Comment by jhbradley** [comment]
ok. will do.

On Thu, Jun 11, 2015 at 5:36 PM, Daniel Schwen <notifications@github.com>
wrote:

> Append (#5197) to your commit messages. Use
>
> git rebase -i HEAD~2
>
> to edit the messages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5240#issuecomment-111307035>.
>



-- 
John-Michael H. Bradley
Intern - BYU-Idaho
*Fuel Modeling & Simulation*

**Comment by jhbradley** [comment]
Afterwards I'm assuming I need to initiate another pull request. Do I need to rewrite history when I push the modified commit messages?

**Comment by dschwen** [comment]
You rewrite history and force push to your branch. This PR will automatically update. No need to do a new one.

**Comment by jhbradley** [comment]
Will do.

On Thu, Jun 11, 2015 at 6:30 PM, Daniel Schwen <notifications@github.com>
wrote:

> You rewrite history and force push to your branch. This PR will
> automatically update. No need to do a new one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/pull/5240#issuecomment-111314216>.
>



-- 
John-Michael H. Bradley
Intern - BYU-Idaho
*Fuel Modeling & Simulation*

**Comment by jhbradley** [comment]
Done

On Thu, Jun 11, 2015 at 6:38 PM, Bradley, John-Michael H <
john-michael.bradley@inl.gov> wrote:

> Will do.
>
> On Thu, Jun 11, 2015 at 6:30 PM, Daniel Schwen <notifications@github.com>
> wrote:
>
>> You rewrite history and force push to your branch. This PR will
>> automatically update. No need to do a new one.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/idaholab/moose/pull/5240#issuecomment-111314216>.
>>
>
>
>
> --
> John-Michael H. Bradley
> Intern - BYU-Idaho
> *Fuel Modeling & Simulation*
>



-- 
John-Michael H. Bradley
Intern - BYU-Idaho
*Fuel Modeling & Simulation*

**Comment by dschwen** [comment]
:+1:

**Comment by friedmud** [comment]
@jhbradley Thanks for the contribution!

**Comment by jhbradley** [comment]
No problem. Hopefully I can make several more before my internship ends.

**Pull request merged**
