### PR TITLE
An attempt to start cleaning up object execution.

### PR DESCRIPTION
**Pull request by aeslaughter**
This is the start of creating a unified method for executing systems via a single method `FEProblem::execute`. If you look at this function, I encapsulated calls to `UserObject` and `AuxKernel` objects compute methods as well as outlined what I think this function should do.

Also, this **should not** be squashed as I am sure that there will be problems with code changing behavior and the individual commits should make bisecting easier (each commit should compile, run, and pass the tests as is).

### CODE REVIEW

**Comment by aeslaughter** [comment]
@permcody I will make it a member variable.

**Comment by friedmud** [comment]
Ummmm... where was the review on this?  ~700 lines changed and it was merged within 6 hours with no comments?

**Comment by friedmud** [comment]
I don't see how this idea is going to work in general... there are too many dependencies in the execution order.  Why execute Controls last?  Maybe you want to control something before Transferring it.  Why execute Indicators and Markers before Transfers?  Maybe you want to transfer a field in then adapt based on that.

Having it all gummed up in one `execute()` function makes it difficult for anyone that wants to specialize how this stuff happens.  With the current (I guess "old" now, since this got merged) I could create a custom Executioner to execute stuff in whatever order I wanted...

**Comment by aeslaughter** [comment]
The current (or old) system offers no consistency, there where calls to
computeUserObjects(PRE_AUX) then computeUserObjects(POST_AUX) w/o compute
aux kernels in between. There were calls to computeUserObjects(ALL)
followed by computeUserObjects(POST_AUX). Sometimes, markers and indicators
are computed, sometimes they are not (I haven't messed with this yet).

I think 95% of our users just want to know when stuff operates, and as is
this is very difficult to determine.

I was motivated when I was working on a ControlWarehouse and had to put
computeControls in about 20 locations in just the framework, I didn't even
know where to start with YAK.

I feel we need some sort of calling structure, that lack of the consistency
is dangerous. We still have legacy modes enabled after how many months
because we were arbitrarily calling execute methods.

I also don't understand your change in position on Executioners, for years
I heard you state "don't create executioners", but now you want people too.
If this really bothers you, we can keep the underlying compute methods
('computeUserObjects, computeAuxiliary, ...) public, but there should be
one function that the framework relies upon.

Also, I am also open to expanding the execute method to offer more
flexibility: perhaps a call list that the user can set from an input file:
`execute_order='controls user_objects_pre aux markers user_objects_post aux
indicators transfers multiapps'`, for example.


FYI, There were comments on other PRs that I closed (notice the v3 on the
branch name).

**Comment by friedmud** [comment]
Cool - I like the overall goal of centralizing and codifying logic.  And I agree that we shouldn't be actively encouraging Executioner creation... but it _is_ a System and it needs to remain one.  Some users _will_ really need to have really specialized Executioners.

I think that a lot of what you have going on here could be fixed by changing stuff on the Executioner side instead.  For instance, look at my `computeUserObjectsAndAuxiliaryKernels()` function in my Executioner refactor branch: https://github.com/friedmud/moose/blob/executioner_refactor_5229/framework/src/executioners/Executioner.C#L351

That reflects the same thing that you are seeing... so I definitely agree that there needs to be some work done in this area.

As for review... we should make sure to link to outdated PRs if there was prior discussion.  I just looked back through the PR history, and although I see a little bit of discussion about particular code things... I don't see any larger discussion on design direction.

Mostly, I was just reacting to seeing so many different things all being jammed into the same function... so many things that aren't even normally executed together (for instance, MultiApps and adaptivity).

I didn't want this to become yet another `FEProblem::initialSetup()`.  @permcody has been trying to go to the _opposite_ of what you're doing here by breaking that one up (and rightfully so... even if we haven't figured out how to do it yet...).  I could see this becoming another quagmire that we dare not modify for fear of hundreds of seemingly unrelated tests failing (you even mention that possibility right here in this PR!).

If this stuff is mostly called in Executioners and there needs to be some consolidation there... then let's put it there.  FEProblem should remain blissfully ignorant of this kind of stuff...

**Comment by aeslaughter** [comment]
How long before you can get the Executioner re-factor completed? Your
Executioner::execute() that is wrapped with well defined loops is what I am
after, what can I do to help get this done?

Feel free to de-deprecate the "compute..." calls, nothing needs to change
with your patch then. When it is in we can remove the FEProblem::execute
method.

**Comment by friedmud** [comment]
God - I don't know.  I went too big with it... THOUSANDS of tests failing.  Fix one issue and a different set of 1000 tests fail... ugh.

I'm actually going to start over(*)... and create a new set of Executioners and leave the existing ones in place while I get everything working.  It's too much to do all at once.

Unfortunately, this is just isn't going to happen really soon.  Maybe not until middle of December...

BTW: Please don't attempt to go from what I've put on GitHub... I have even more on my laptop and workstation in various states of not working... ugh.

* Note: I don't actually mean chuck everything... I mean use what I've done but go down a different development path.

**Comment by YaqiWang** [comment]
Has Yak been fixed with this change? I am a little worrying about that calling FEProblem execute is too much and we lose the flexibility (possibly too much) that the old way provides us.

**Comment by aeslaughter** [comment]
YAK was not updated, it is still using the old method and the old method
will live on for now. I am removing the deprecated message stuff now.

**Pull request merged**
