### PR TITLE
Allow flexibility in how cli_args for MultiApps are handled 

### PR DESCRIPTION
**Pull request by snschune**
## Reason

This MR allows to provide different command line parameters to subapps in classes
inheriting from `MultiApp`.

## Design

Virtual function that returns `_cli_args` by default.

## Impact

No impact is anticipated.

### CODE REVIEW

**Comment by loganharbour** [comment]
@snschune give us a shout when you're ready for input

**Comment by snschune** [comment]
@loganharbour it's ready.

**Review by loganharbour — COMMENTED** [review]
Can you provide an example situation of where you're overriding this?

**Comment by snschune** [comment]
> Can you provide an example situation of where you're overriding this?

As in a test object that overrides it and is tested in the test harness? 
Yes, I'll cook something up.

**Comment by loganharbour** [comment]
Long story short: I need you to rebase on current devel and then regold that exodus file you added. Exodus writing at the time of you creating this was a bit borked.

We can do this if need be.

**Comment by snschune** [comment]
@loganharbour this is still open, shouldn't be a lot of work to get it in.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
