### PR TITLE
Remove unnecessary rpath patching on linux

### PR DESCRIPTION
**Pull request by loganharbour**
Refs https://github.com/idaholab/moose/issues/14553

### CODE REVIEW

**Comment by loganharbour** [comment]
Well @permcody  and @dschwen  what do you folks think?

I did find out that the rpath fixing is required for the binary, just not the libs. And it's needed for both on mac. Not really a clean solution, but...

**Comment by permcody** [comment]
I’m happy if it works. None of this install code is perfect or pretty.

**Review by permcody — APPROVED** [review]
I don’t think this is any worse than bidding the definitions of these commands in a completely different file.

**Comment by loganharbour** [comment]
Failure is unrelated.

**Pull request merged**
