### PR TITLE
Always compute single point map when computing Jacobian with disps

### PR DESCRIPTION
**Pull request by lindsayad**
As described in libmesh/libmesh#2997, if elements
are affine, then the previous Jacobian evaluation routine would treat them
as such, but a slight perturbation to the displacement field, as is done
in finite difference testing of the Jacobian, will make the element
non-affine and consequently proceed down a different code path in
function evaluation. The solution is to make sure that when performing
Jacobian evaluations and our affine map determination is a function of
nonlinear degrees of freedom (e.g. the displacement variables) that we
always compute the single point map

### CODE REVIEW

**Comment by roystgnr** [comment]
> If we had AD in libMesh we would be experiencing the exact same Jacobian errors we are seeing with the MOOSE re-implementation.

And then we'd need to change it in libMesh.  Just because the map is the same at every quadrature point doesn't mean the map's derivatives with respect to nodal position variables are the same at every quadrature point; some nodes are closer than others to each quadrature point.  If I write code assuming `x * x >= 0` after declaring `Real x`, I would expect to have to change that code, not just the variable type, if I wanted it to work for `Number x;` similarly the assumption that mapping calculations are the same on all quadrature points on an affine element depends on us only calculating map values, not including derivative calculations w.r.t. values that vary from quadrature point to quadrature point.

> Should we only do the affine optimization during residual evaluations, knowing that any perturbation to a displacement dof will make the element non-affine and hence we should always call the single-point map method during jacobian evaluation?

Shouldn't we, in specifically those cases where we're also treating nodal positions as functions of solution variables?  It's not a matter of "we're evaluating a jacobian, can't use the affine map optimization", it's a matter of "we're evaluating a jacobian including derivatives with respect to mapping variables, can't use the affine map optimization".

> If we ever get around to doing AD in libMesh, allowing removal of these MOOSE re-implementations, would we check a computing_jacobian flag in FEMap::compute_map that we consider when deciding whether to go down the affine or single-point map computation?

Something like `computing_variable_mapping`, maybe?  It wouldn't apply to every Jacobian, only to those where the shape of the Elem changes when the terms you're differentiating against change.

**Comment by lindsayad** [comment]
> Something like `computing_variable_mapping`, maybe? It wouldn't apply to every Jacobian, only to those where the shape of the Elem changes when the terms you're differentiating against change.

Yea even now we do not do this derivative addition/computation if we are not doing a displaced map calculation, so you're right that just because we are computing a (SNES) Jacobian doesn't necessarily mean that we cannot do do the optimization if our mapping has no dependence on our degrees of freedom. Ok I will not modify the current test but instead change the code

**Comment by lindsayad** [comment]
Alright with this change, the displacement jacobian tests pass for me locally in serial and in parallel with libmesh/libmesh#2997

**Review by roystgnr — DISMISSED** [review]
~~You're manually testing this against the reduced tolerances libMesh PR?~~

Comments crossed in transit; thanks!

**Comment by lindsayad** [comment]
Lol. Now I think with the affine tolerance in its current state our perturbations in the finite difference Jacobian are not large enough to change it from affine to non-affine so hence the current errors. I think I'm going to *always* compute the single point map for now and then once libmesh/libmesh#2997 is merged and we've updated libmesh then I will restore the optimization during residual evaluation

**Comment by lindsayad** [comment]
Yikes I guess we are seeing the AD versions of the failures that are showing up in the hand-coded calculations in the libmesh update. This will require regolding some tests in BISON and in BlackBear

**Comment by roystgnr** [comment]
> Now I think with the affine tolerance in its current state our perturbations in the finite difference Jacobian are not large enough to change it from affine to non-affine so hence the current errors.

That sounds likely.

> I think I'm going to always compute the single point map for now and then once libMesh/libmesh#2997 is merged and we've updated libmesh then I will restore the optimization during residual evaluation

This is getting more and more horrifying but that seems like the most straightforward way to progress.

There's basically no way to avoid ruining "git bisect" here, is there?

**Comment by lindsayad** [comment]
> There's basically no way to avoid ruining "git bisect" here, is there?

I guess I don't know what you mean. Since it seems like we were using inaccurate computations in the past but registering those computations as good nonetheless, that a "pass" with a git bisect as in "run_tests returned everything as passing" is a false positive anyways.

**Comment by roystgnr** [comment]
> a "pass" with a git bisect as in "run_tests returned everything as passing" is a false positive anyways.

Good point.  I'm just afraid of what happens when we find regressions that were caused by past errors but aren't uncovered until we hit them with future tests.  I guess at that point we just make sure the future tests don't use any slightly-perturbed meshes; we'd want to use only the new tests when bisecting such a case anyway, for speed's sake.

**Comment by lindsayad** [comment]
@roystgnr could you re-approve this? I have patches for BISON and BlackBear prepared

**Review by roystgnr — APPROVED** [review]

**Pull request merged**
