### PR TITLE
Make sure PorousFlow actions add all versions of materials as needed

### LINKED ISSUE #12762: Check materials needed for BC's in PorousFlow actions
## Rationale

We try and automatically include the correct version of materials needed in PorousFlow models, but a recent report on the mailing list demonstrated that we are missing a case with a specific combination of actions and boundary conditions.

## Description

The issue is the combination of `PorousFlowBasicTHM` action and `PorousFlowPiecewiseLinearSink` BC, see 
https://groups.google.com/d/msgid/moose-users/b7e157ae-e730-4152-8d65-198835070b12%40googlegroups.com?utm_medium=email&utm_source=footer

## Impact

Simpler input files for users

### PR DESCRIPTION
**Pull request by cpgr**
The `act()` method in these actions were pretty complicated to follow, so I have separated them into several sub methods that do only a single thing (like add kernels, add materials, etc) to make it easier to fix this issue.

Includes a number of new tests to make sure that the problem identified in this issue is correctly addressed.

Closes #12762

### CODE REVIEW

**Comment by WilkAndy** [comment]
This is cool, thanks Chris.  I've often wondered whether we dug ourselves a hole by building all this Action stuff, but i think this PR helps the problem, and also most input files people send me use the Actions so i think they're truly useful.

**Comment by cpgr** [comment]
Yeah, I do think they are easy for the users, but they are complicated to get right from our side!

**Comment by cpgr** [comment]
Hi @danielbi-ETHZ,

This PR should mean that you don't have to add a `PorousFlow1PhaseFullySaturated` material when using a `PorousFlowPiecewiseLinearSink` and `PorousFlowBasicTHM` like you had to in the input file you added in the mailing list discussion [here](https://groups.google.com/d/msgid/moose-users/b7e157ae-e730-4152-8d65-198835070b12%40googlegroups.com?utm_medium=email&utm_source=footer).

After this has been merged, you should be able to remove that material entirely.

**Comment by danielbi-ETHZ** [comment]
Hi @cpgr,

Thank you very much for fixing this. I really appreciate it.

Best,
Daniel

**Review by permcody — APPROVED** [review]
Thanks! This looks like a nice improvement.

**Comment by cpgr** [comment]
Thanks @permcody

**Pull request merged**
