### PR TITLE
Reinit with *displaced* elem for DisplacedProblem::reinitNeighbor

### LINKED ISSUE #14876: JxW wrong for DG/InterfaceKernels on displaced mesh
## Bug Description

JxW (and other things) are wrong for DG/InterfaceKernels on displaced mesh

## Steps to Reproduce
Take a reference mesh with square QUAD4 elements. Apply displacements only in one direction. The JxW in a DG/InterfaceKernel will be the same for all sides even though it should be different

## Impact

Anyone doing DG/InterfaceKernel computation on the displaced mesh are getting wrong results.

### PR DESCRIPTION
**Pull request by lindsayad**
We've been using a reference element for displaced problem
calculations involving anything with neighbors, e.g. at least
DGKernels and InterfaceKernels. This would lead to wrong values
for JxW, grad_test, grad_phi. Not great

Closes #14876

### CODE REVIEW

**Comment by lindsayad** [comment]
I'm going to add test(s), but @arovinelli you can play around with this

**Comment by arovinelli** [comment]
> I'm going to add test(s), but @arovinelli you can play around with this

@lindsay thanks a lot for taking care of this so quickly. I played with my examples and numbers are now correct.
Also, the test that is failing should either be regolded or removed because it's wrong.

**Comment by lindsayad** [comment]
> Also, the test that is failing should either be regolded or removed because it's wrong.

Right

**Review by fdkong — APPROVED** [review]

**Comment by lindsayad** [comment]
Yea, don't worry about that!

**Pull request merged**
