### PR TITLE
Add perf_log for each action

### LINKED ISSUE #11474: Add perf_log for each action
## Rationale
For scaling and performance study, we would like to where our time is spent. It is better to know how much we spend on each action.

## Description
Add perf_log for each action.

## Impact
Impact everyone if you turn on `show_actions`

### PR DESCRIPTION
**Pull request by fdkong**
Closes #11474

### CODE REVIEW

**Review by permcody — CHANGES_REQUESTED** [review]
I don't want this on by default. It's way too much data. Please add an option that will turn this on when requested.

**Comment by fdkong** [comment]
It happens only when we have "`show_actions=true`". Is it not enough? We want to have one extra option inside the option of `show_actions=true`.

**Comment by permcody** [comment]
Oh... Right that's ok...

**Review by permcody — APPROVED** [review]

**Comment by friedmud** [comment]
The one thing missing from this PR is documentation.  It would be nice to know that `show_actions = true` will output the performance of each action in the perf_log.

Even if it's just changing the parameter documentation for that parameter... that should get captured somewhere... although it would be even better if you created a new `md` document to start talking about perf_log

**Pull request merged**
