### PR TITLE
Moved THM source and syntax doc location

### LINKED ISSUE #22852: THM pages do not show in source documentation
## Bug Description
THM classes do not show in https://mooseframework.inl.gov/source/index.html. It appears that THM has source files in `doc/content/modules/thermal_hydraulics/source` instead of `doc/content/source`, as the other modules do, so this is assumed to be the cause.

## Steps to Reproduce
View the above link and see no THM classes.

## Impact
Missing THM documentation links.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #22852

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]
the one downside of this is that very general names such as AddComponent or AddClosure
now point to undocumented pages :S 

https://mooseframework.inl.gov/docs/PRs/22902/site/source/actions/AddComponentAction.html
https://mooseframework.inl.gov/docs/PRs/22902/site/source/actions/AddClosuresAction.html

**Comment by joshuahansel** [comment]
@GiudGiud Just to be clear, I didn't break anything, right? You're just saying that it's now more apparent that there are undocumented pages?

**Comment by GiudGiud** [comment]
Yes you did not break anythig.

But every engineer clicking through this source menu will get confused because of the items with general names and missing docs

**Comment by joshuahansel** [comment]
Ok, I've repurposed https://github.com/idaholab/moose/issues/19737 for this. I'll do some of this soon. It's mostly going to be actions.

**Pull request merged**
