### PR TITLE
A debug assertion with extra element IDs

### PR DESCRIPTION
**Pull request by YaqiWang**
Just for @roystgnr to take a look.

The error can be produced by
```
cd test/tests/meshgenerators/generated_mesh_generator
mpiexec -n 5 ../../../moose_test-dbg -i generated_id_mesh.i --distributed-mesh
```

### CODE REVIEW

**Comment by YaqiWang** [comment]
Please DO NOT MERGE.

**Comment by loganharbour** [comment]
@YaqiWang FYI: you can now set your own PR's as a "draft" which removes the merge option.

**Comment by roystgnr** [comment]
I can reproduce it, so that's a plus.  And I can get at it in the debugger.  You say "the opt mode runs fine and can produce the right exodus file"?  I wouldn't trust that by itself (the whole point of assertions is to catch bugs before they have ruinous consequences), but it first glance it looks like the problem here really is a bug in the assertions rather than corruption in the data they're trying to double-check.  I'll put up a libMesh PR if that turns out to be correct.

What's still puzzling me, though, is that if I'm understanding the bug correctly then I'd expect it to be a huge risk with *any* code that uses all three of DistributedMesh, extra_integers, and mesh redistribution in debug mode, so I'm surprised this is the first time it's triggered.  I know we have a little DistributedMesh+extra_integers test coverage, and a ton of DistributedMesh + mesh redistribution test coverage, do we just not have any test that uses all three and that gets run with METHOD=dbg?

**Comment by YaqiWang** [comment]
I guess we do not have distributed mesh + debug tests in MOOSE. Same in my application.

**Comment by YaqiWang** [comment]
Thanks @loganharbour .

**Comment by YaqiWang** [comment]
Thanks @roystgnr for this quick fix.

**Pull request closed without merging**
