### PR TITLE
Change MooseVariableFEImpl to MooseVariableFE

### PR DESCRIPTION
**Pull request by lindsayad**
Part 2 of clean-up.

Step 1 was renaming `MooseVariableFE` to `MooseVariableFEBase`

Refs #11203

### CODE REVIEW

**Review by friedmud — DISMISSED** [review]
This looks good

**Comment by friedmud** [comment]
Let's hold off on merging this until after #10111 gets merged so we don't have to rebase that one again...

**Comment by permcody** [comment]
@lindsayad - You can rebase this now and we should be able to get it merged.

**Review by friedmud — APPROVED** [review]
👍

**Pull request merged**
