### PR TITLE
Test to demonstrate desired MeshMetaData behavior

### PR DESCRIPTION
**Pull request by aeslaughter**
@arovinelli Is this valid representation of what you are trying to accomplish in #15972?

(refs #15972)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@permcody Here is my test PR.

**Comment by arovinelli** [comment]
> @arovinelli Is this valid representation of what you are trying to accomplish in #15972?
> 
> (refs #15972)

Yes for save, no for reload.
My reload is somehow special, I need to know if the mesh property called `data` is present, before calling the prepare for use in FileMeshGenerator. If the property is present, then I load the data, do my modifications to the mesh (this my responsibility) and then call prepare for use. If I do as in your example, I'll already be in trouble as my ghosted element will already be deleted.
Still, I appreciate this PR as it demonstrates how do you do it in a case where your ghosting is not a function of your mesh data

**Comment by aeslaughter** [comment]
@lindsayad It seems like this ghosting problem should be handled with a RelationshipManager rather than via the MeshMetaData. Can you help out?

**Comment by aeslaughter** [comment]
@arovinelli This PR shows that the MeshMetaData is not being loaded on restart and it was not intended to work in that fashion. This system was designed to mimic materials within a single input, where data is both consumed and produced within the generators.

If we expand the behavior to work across restart then the generator can check if the meta data exists and do something special.

**Comment by lindsayad** [comment]
Geometric relationship managers/ghosting functors are now added before `MeshGenerators` are executed so it should be theoretically possible to avoid deleting the required remote elements when `prepare_for_use` is called @arovinelli's `MeshGenerator`. It seems like if @arovinelli created a relationship manager that geometrically ghosted all the elements on either side of his interface, then he would be set to go

**Comment by aeslaughter** [comment]
This demonstration is no longer needed a different approach using RelationshipManagers is being explored.

**Pull request closed without merging**
