### PR TITLE
Jacob's 3d mortar

### PR DESCRIPTION
**Pull request by recuero**
The intent of this PR is to take the work from @jbadger95's https://github.com/idaholab/moose/pull/18203 and make some final changes to pass CIVET testing and corresponding reviews.

Refs #13080

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Comment by loganharbour** [comment]
> I just verified that the tet10 and hex27 tests definitely touch the TRI6 and QUAD9 code respectively. So @loganharbour are we not gathering in the increased sparsity coverage yet or is the diff coverage comment not updating correctly?

Oops. Good catch. In generate I only grab from framework1 and framework2 tags. Forgot to actually switch this to grab all that start with framework.

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Review by dschwen — CHANGES_REQUESTED** [review]
I need a break. Here are comments on the first bit.

**Review by dschwen — CHANGES_REQUESTED** [review]
Done for now

**Review by dschwen — DISMISSED** [review]

**Review by lindsayad — CHANGES_REQUESTED** [review]
I'd love to see one test that sets the `debug` option. I want to make sure the world won't explode if a user sets that option. I think that's all I have left ... and maybe deletion of the quad8 code in the Lagrange helpers if everyone's on-board with sticking with HEX27/QUAD9 for second order 3D mortar

**Comment by jbadger95** [comment]
> @jbadger95 is there any reason to keep around the `QUAD8` portion of the Lagrange helper code? Do you think we should support HEX20/QUAD8 meshes? I kind of think we should just keep the code compact and stick with HEX27/QUAD9 (which you have).

I'd ask @bwspenc, it sounded like they like using serendipity elements for Bison applications. it does reduce node count and would also help reduce the required AD sizes a bit. Just to be clear you're talking about QUAD8 interfaces in 3D mortar right (like you wouldn't be removing it from 2D mortar)? 

Supporting serendipity elements would be super easy (I think we would just need to add an entry to the subdivision functor in `AutomaticMortarGeneration` and `ComputeMortarFunctor` and implement the quadrature point transformations in the `transform_qp` functor), the harder part would be enabling dual shape functions. Enabling dual shape functions on QUAD8 interfaces would require a change similar to what's needed to enable dual shape functions on TRI6 elements (the required change has to do with integral positivity like we discussed with @dewenyushu and @recuero a while ago). I'm not sure we need to support dual shape functions on TRI6 elements either since triangle interfaces are already risky business with 3D mortar (actually it might be a good idea to put an assertion in that dual shape functions shouldn't be used with TRI6 right now, the weighted gap will signal false contact). I guess if we're supporting TRI6 elements without supporting dual shape functions why not just do the same thing for QUAD8 though? Up to you, if you do want to support it I can write out the quadrature transformations quick.

(sorry this is all over the place, my opinion developed as I was typing it out)

**Review by jbadger95 — COMMENTED** [review]
These are just to outline the changes for enabling HEX20/QUAD8 with 3D mortar

**Review by lindsayad — DISMISSED** [review]
Amazing work @jbadger95 . And great follow-on @recuero; thank you for getting this across the finish line. Thank you for good review @dschwen . this is exciting stuff!

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
I should have caught this on review ... We are failing debug checks roughly 1/10 times with the `continuity_mixed` test when running in parallel and I'm pretty much certain this is because we have a mortar mesh that is totally distributed ... e.g. only *local* elements are looped over when constructing the mortar mesh ... but it's typed as a `ReplicatedMesh`. I'm surprised we don't have more failures frankly

**Comment by lindsayad** [comment]
And then some jumbled parallel printing showing that we have two nodes with the same id but different unique id
```
Node id()=14, processor_id()=0, Point=(x,y,z)=(    0.25, 0.269796, 0.230204), unique_id()=322
    DoFs=

Node id()=14, processor_id()=1, Point=(x,y,z)=(    0.25,      0.5,     0.25), unique_id()=320
  DoFs=
```

**Comment by lindsayad** [comment]
In `ReplicatedMesh::renumber_nodes_and_elements`, when nodes are renumbered the new numbers will be a function of the element-node connectivity. So if on one process, the element-node connectivity is different for a given element id, then you are doomed

**Comment by lindsayad** [comment]
It ensures that our nodes container is compact with size exactly equal to the number of non-null Nodes on the process. In *our* case, does it matter? Probably not, but I feel like I am close to figuring out what's going on, and if I can figure it out and it's not hard to fix, we might as well allow it. My neurotic brain is just very troubled by random behavior

**Comment by jbadger95** [comment]
If you change the node_id's to use a counter instead of `mortar_segment_mesh->max_node_id()` does it fix the non-deterministic behavior?

**Comment by lindsayad** [comment]
See #19159

**Pull request merged**
