### PR TITLE
Allow to skip partitioning for file mesh generator

### PR DESCRIPTION
**Pull request by GiudGiud**
This is a big deal for split meshes. We already partitioned them at the split, no need to repartition right after loading. 

So this is a boolean. I'm on the fence about changing the behavior for split meshes only. People may want to avoid partitioning at this point with regular meshes as well. And changing the behavior when introducing split meshes could be a little surprising (especially if a bug creeps in or if there s issues with not having partitioned at this mesh generator down the line)

### CODE REVIEW

**Comment by loganharbour** [comment]
Can we not store whether or not a mesh is pre-split as some metadata so that we don't need an input flag here?

**Comment by GiudGiud** [comment]
You could want this behavior for non-pre split meshes as well. Early partitioning can be an issue for mesh generation.

more mesh metadata is where we are headed here overall (need to remember when we computed neighbors for example), but I think the knobs are inevitable

**Comment by YaqiWang** [comment]
This looks like the old `prepare_for_use()` headache. We discussed this before: can we have to separate inheritance path for serial mesh generators and parallel mesh generators? To load the pre-split mesh with `FileMeshGenerator`, I feel we should have another one like `ParallelFileMeshGenerator`.

**Comment by GiudGiud** [comment]
It is indeed related, prepare_for_use calls the partitioning. 

I dont see why we should separate mesh generators if it's pretty much working already with FileMeshGenerator. With that boolean I'm loading a pre-split BEAVRS mesh, repartitioning it at the end of mesh generation, then running it on HPC. There could be some interest in changing the default behavior, but I am not a fan of then having a different behavior on partititioning when switching to split meshes. I feel like users would be surprised.

**Comment by loganharbour** [comment]
Status?

**Comment by GiudGiud** [comment]
I'd be down for a merge. 
When someone has time, we should add the extra meta data needed in MeshBase and separate each bit of prepare for use. 
I think this is still relevant on its own

**Review by friedmud — DISMISSED** [review]
👍

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
