### PR TITLE
June MOOSE newsletter

### PR DESCRIPTION
**Pull request by aeslaughter**
@idaholab/moose-team Please add to the MOOSE newsletter for June. You can just push your changes to this branch directly.

(refs #11446)

### CODE REVIEW

**Comment by SudiptaBiswas** [comment]
Is this only for Framework updates or can Module updates be included as well?

**Comment by lindsayad** [comment]
I would think that it should also include module updates...they're part of
the repo!

**Comment by jwpeterson** [comment]
> I would think that it should also include module updates

Agreed

**Comment by cpgr** [comment]
I've added a few lines about a big change that is being made (#11652) in the porous flow module, but I'm not sure how to add them to this PR.

**Comment by jwpeterson** [comment]
Make a PR to Andrew’s fork on this branch and we’ll fast forward merge it so there’s no merge commit.

**Comment by aeslaughter** [comment]
@sapitts @bwspenc Can you add a few words about all the documentation changes to TM?
@friedmud Can you add a few words about VPP parallel consistency (#11428) 
@permcody Can you add something about `ElementValueSampler`
@SudiptaBiswas Are you still planning on adding something?

**Comment by permcody** [comment]
I think you mean @joshuahansel for ElementValueSampler.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
