### PR TITLE
Check temperature coupling in RZ

### LINKED ISSUE #20879: Detect missing temperature coupling in tensor mechanics
## Reason
When using temperature dependent eigenstrains the temperature variable should get coupled to populate the off-diagonal Jacobian entry to improve convergence.

## Design
Use validateCoupling to detect temperature dependent eigenstrains.

## Impact
Helps the user get better converging runs.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #20879

### CODE REVIEW

**Comment by dschwen** [comment]
The failures indicate that the check is working. I'll fix those inputs.

**Comment by dschwen** [comment]
> This is great, thanks! Unfortunately, there's probably no easy way to have the error message tell you to add the appropriate parameter to the Action, but this is certainly an improvement. I'll approve it once the tests are fixed.

Maybe there is a hard way though. We could run an action task after the materials are set up, but before the kernels are added and output an action specific message there.

**Review by bwspenc — DISMISSED** [review]

**Comment by bwspenc** [comment]
I imagine that there are quite a few things like this where the kernels or materials throw errors that might not make a whole lot of sense to someone who set them up with an Action. Definitely a bigger issue than this PR! I approved it assuming the tests will pass. Let me know if you need me to re-approve it.

**Comment by dschwen** [comment]
Failure is unrelated

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
