### PR TITLE
Remove INSFVMomentumFriction

### LINKED ISSUE #20857: Remove INSFVMomentumFriction
## Reason
We originally added the object to fake a representation of a heat exchanger. Now that we have `PINSFVMomentumFriction`, we can use that instead

## Design
Delete `INSFVMomentumFriction`

## Impact
Should be little impact on users because they can replace with `PINSFVMomentumFriction`. Positive impact for us as maintainers because we can just focus on `PINSFVMomentumFriction`

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #20857, should not be merged yet

### CODE REVIEW

**Review by lindsayad — CHANGES_REQUESTED** [review]
I'm hoping that we can make this removal without having to regold any of the tests. Let me know if you want any help with this. Thanks for taking this on!

**Comment by socratesgorilla** [comment]
@grmnptr did all the stuff involving the tests, so I would absolutely need help rewriting the tests to not regold files whenever you or him have time

**Comment by grmnptr** [comment]
I'll take a look later today!

**Comment by GiudGiud** [comment]
For Darcy making the two match is easy
In PINSFV you have coef * rho / eps
in INSFV you had coef
so just use a coef of old_coef / rho and have eps of 1

For Forchheimer you ll need a little more trickery but it s already doable
In PINSFV you have coef * rho / eps
in INSFV you had coef * abs(u)
So just use a functor coefficient of old_coef / rho * abs(u)

You can make that with https://mooseframework.inl.gov/source/materials/VectorMagnitudeFunctorMaterial.html
add a factor parameter to it like in https://mooseframework.inl.gov/source/auxkernels/FunctorElementalAux.html
this is always useful

**Comment by socratesgorilla** [comment]
> For Darcy making the two match is easy In PINSFV you have coef * rho / eps in INSFV you had coef so just use a coef of old_coef / rho and have eps of 1
> 
> For Forchheimer you ll need a little more trickery but it s already doable In PINSFV you have coef * rho / eps in INSFV you had coef * abs(u) So just use a functor coefficient of old_coef / rho * abs(u)
> 
> You can make that with https://mooseframework.inl.gov/source/materials/VectorMagnitudeFunctorMaterial.html add a factor by using the https://mooseframework.inl.gov/source/auxkernels/FunctorElementalAux.html (factor = 1/rho)

What is meant by u in the abs(u)? Not sure what to reference there.

**Comment by GiudGiud** [comment]
u is the velocity vector for me. 
so u = (vel_x, vel_y)

this is kind of a specialized ticket btw. Not really the easiest for someone working framework-wise. 
I m taken rn but mid-next week if you need help with this we can do it together

**Comment by GiudGiud** [comment]
I ll take this over to completion
Thanks for the head start

**Comment by lindsayad** [comment]
@GiudGiud you still want to take this over? This would fit in common layer budget IMO (as it is in the common layer :smile: )

**Comment by socratesgorilla** [comment]
As far as I remember all this PR needed to get merged is changing some tests. I don't think it would be very much work to finish if you know what you're doing in regards to the math on the tests.

**Comment by GiudGiud** [comment]
I dont recall tests passing. Maybe we ended up removing most INSFVMomFriction anyway.
I wanted to lump this in with other work I never got to
- removing CRTP
- changing convention for friction factor definition across the board

I can push a rebase and at least get this in

**Comment by socratesgorilla** [comment]
Did these fixes get merged in the mentioned pull request?

**Comment by GiudGiud** [comment]
no there's no progress on this.

**Comment by socratesgorilla** [comment]
It's still as almost ready as it was a year ago

**Pull request closed without merging**
