### PR TITLE
Add a 2d interface kernel test

### PR DESCRIPTION
**Pull request by YaqiWang**
Refer #000. I just want to see if this test breaks in parallel on the test box.

### CODE REVIEW

**Comment by permcody** [comment]
@YaqiWang - What do you want me to do with this PR? It looks like you just wanted to test. Should it be closed?

**Comment by YaqiWang** [comment]
Yes, I was hoping to reproduce the madness we saw the other day. But I cannot get it with this PR.

**Comment by YaqiWang** [comment]
Actually it does not hurt to add a 2D test. The only problem is that I need to push that mesh modifier in to split the boundary. If you think breaking boundaries based on the block all sides are attached to is a useful mesh modifier, I can change this PR a little and repush.

**Comment by YaqiWang** [comment]
@permcody I will create this mesh modifier and the 2d test case for interface kernel, because this interface kernel is going to be important to us. We want it to be tested thoroughly.

**Comment by YaqiWang** [comment]
Close in favor of #7889.

**Pull request closed without merging**
