### PR TITLE
Automatically declare a preprocessor symbol for each enabled app 

### LINKED ISSUE #7327: Have apps (and modules?) declare a preprocessor symbol to indicate their availability
### Description of the enhancement or error report
We have started working with optional dependencies quite a bit lately (Mammoth, Marmot, Magpie). It would be beneficial if each app defined a `-DAPPNAME_ENABLED` compiler option to enable conditional compilation of app features that depend on other apps.

### Rationale for the enhancement or information for reproducing the error
Reduce the amount of hard dependencies. This allows for faster builds if not all features are required

### Identified impact
Resolving issue would be impact neutral but would enable soft (optional) dependencies in a more general way.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #7327

### CODE REVIEW

**Comment by permcody** [comment]
This looks OK, have you been able to test whether this is going to be enough for you?

**Comment by YaqiWang** [comment]
@dschwen MAMMOTH Makefile contains this line for each depending app, which can be removed after this patch. But application_name might be in lower case, is that a problem?

**Comment by dschwen** [comment]
The case is a good point. And yes the lines will be removed (except the
RELAP-7 vs. RELAP7 issue).

**Comment by dschwen** [comment]
This latest commit enables `app.mk` recursion!

**Comment by permcody** [comment]
This is insane by the way, recursion in Makefiles? I can't see any possibility of this going badly. I'll just merge this and remain blissfully ignorant of the voodoo within.
👍

**Pull request merged**
