### PR TITLE
Make MooseEnum able to deprecate some of its enums

### LINKED ISSUE #5368: Make name change in MooseEnum easier
There could be cases where developers want to change the name of one of the enumerations of a `MooseEnum` to another name. To do this, we need to make a name deprecated and add a new one. When we convert a string from a string with the old name, we issue a warning and convert it to the new enum. 

What we need is possibly just a new function in `MooseEnum`, which change a deprecated name to a new one. I will submit a PR for this.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #5368.

### CODE REVIEW

**Comment by permcody** [comment]
I don't think this design will work all that well. Consider this case:

```
MooseEnum enum("value1 value2", "value1");

enum = value2;

/// Now deprecate
enum.deprecate("value1")

```

When do we print our warnings? These enums are stateful and can get copied around. If you allow deprecation as a separate public API there are additional cases to consider about printing messages later.

I think it would be a mistake to allow deprecation anywhere besides the constructor. The designer of these enums will know ahead of time if they want to deprecate a value and it'll be clear to see it at the point when the object is created. At any point during the execution if an a value is assigned that is deprecated we can trigger a warning at that point instead of trying to do it both when it's assigned and later if deprecated is called sometime other than before an assignment.

The big problem with this idea is that we already have multiple default argument parameters in `MooseEnum` and `MultiMooseEnum` so adding another default string argument isn't going to work due to ambiguity. Let me think about it for a bit and see if there's a good way to deprecate values on construction.

**Comment by YaqiWang** [comment]
Yes, calling `deprecate` should right after the construction of a `MooseEnum`, and the default enum should not be deprecated. I assume the developer knows how it can be used. It is better to make it as a part of constructor.

**Comment by permcody** [comment]
Perhaps, but these utility classes are the ones that can get abused the worst. I'd really like to make sure that they are fool-proof since they are small and have very clear easy to understand purposes. They could even be used outside of MOOSE if we wanted so it's worth getting them right.

**Comment by friedmud** [comment]
I just wanted to come in and say that I like the idea of being able to deprecate enums.

As for HOW to do it.  I don't know.  The method here isn't bad.  For one thing, it could allow an inherited class to deprecate options specified in the parent... which might be useful...

**Comment by permcody** [comment]
I'm not sure I understand what the purpose of `formalize()` is in this PR. You probably don't want users to be responsible for calling a method in order to see the warning. If they fail to call the method, they fail to see the warning which isn't very robust.

At the very least calling the deprecated method should recheck the current state of the enum and warn immediately plus make sure that any future assignment automatically warns.

As far as having a separate deprecate method, I guess I'm OK with that since I can't think of an elegant way of doing it in the constructor with all of our existing empty default param constructors. I suggest dropping `formalize()` method and doing the checks on all assignment operations.

Make sure that you add additional tests to moose/unit for these cases as well if you work on this PR. There's already several unit tests for MooseEnum already in there so you can just follow the pattern to test for deprecated items.

**Comment by friedmud** [comment]
:+1: for @permcody 's comments

**Comment by YaqiWang** [comment]
I am on something else. Will back to this maybe tomorrow. Checking the current deprecated names has to be done in the derived classes, which makes things a little messy. I am creating a pure virtual function in base class for this.

**Comment by friedmud** [comment]
I'm not sure what you mean by this.  @permcody was suggesting that every time the enum is assigned a value it checks to see if you are currently assigning a deprecated value.  If you are then it will print a warning/error at that point.

**Comment by YaqiWang** [comment]
Because `deprecate()` is separated from constructor, there is a chance that when it is called the current enum is to be deprecated. In such a case, we need to check the current enum in `deprecate()` and issue a warning as well.

**Comment by permcody** [comment]
I wouldn't spend a lot of time worrying about inheritance cases for this class. This is one of those classes that's probably "done" and unlikely to be extended within the MOOSE framework and if it were to be extended we'd probably add whatever feature we missed right back into the existing implementation (like you are doing right now).

**Comment by permcody** [comment]
@YaqiWang - you're right. All of the assignment logic should already be consolidated into a single method. Just add your deprecated check there and make sure you can also call it when `deprecate` is called to handle all cases.

**Comment by YaqiWang** [comment]
After talking with @permcody, I decided to push what I am currently having and let Cody take it over. He has some better idea on the implementation and doing moose unit test. Hopefully what I did so far is useful. Thanks Cody.

**Comment by dschwen** [comment]
Yaqi, commenting from my phone, did you take care to have the copy constructors support this, and the cast between MultiMooseEnum and MooseEnum?

**Comment by YaqiWang** [comment]
Nope. I did not think about it. The old way should be ok and we do not need to warn because the source enum should have warned.

**Pull request closed without merging**
