### PR TITLE
Modification to logic checking for t_step 0 or 1 to allow restart

### PR DESCRIPTION
**Pull request by sapitts**
### Relevant design changes

A flag check (`!_app.isRestarting()`) is added to each case of the logical check `if (_t_step == 0)` and `if (_t_step == 1)` to guard against problems with restart functionality, as identified by @mll36 .  Corrections to spacing and bool variable names made by some unnamed intern earlier this summer in `ComputeThermalExpansionEigenStrain` are also corrected in this PR.

@WilkAndy please review the proposed change to the porous flow material `PorousFlowMassFraction` and to the tensor mechanics material `ComputeMultiPlasticityStress`; @permcody or @dschwen please review the other materials.

The `isRestarting` check was not added to the heat conduction postprocessor `ThermalConductivity`, but I can easily include that change in this PR if the check makes sense in that postprocessor. 
### Test Cases

A new pair of test cases, using the tensor mechanics thermal expansion eigenstrain class, is included to test for restart capabilities.  The test is simply thermal expansion; no displacement or force loads are applied.

Refs #7457

### CODE REVIEW

**Comment by WilkAndy** [comment]
PorousFlowMassFraction - what you've done @sapitts looks like it'll work and you have no other option.  In relation to #6774 and the yaqi_hacky stuff, the uninitialised variable stuff is getting really tenuous in MOOSE.  Your current change to PorousFlowMassFraction is a bandaid over a bandaid!  (Do you guys have bandaids in the US?  They're little adhesive strips that cover wounds - kids like to use copious amounts of them to cover microscopic scratches!).

**Comment by WilkAndy** [comment]
I partially retract what i said about the PorousFlowMassFraction "looks like it'll work" since i have no idea if it'll work!!  If it compiles and runs the tests that's all i can ask for at present, until #6774 is addressed.

**Comment by WilkAndy** [comment]
ComputeMultiPlasticityStress is perfect, thank you @sapitts .

**Comment by permcody** [comment]
Thanks for fixing these. I'll say that I'm not crazy that these materials have to inspect things like `_t_step` or need to ask the app about whether things are restarting but this is the right fix for the immediate problem. I encourage the Solid Mechanics developers to interact with the MOOSE team so that we can improve these systems. Ideally the material shouldn't need to dig for this information. Perhaps we need additional callbacks that get called at the right time to make these calculations work better. I'm open to new ideas.

**Comment by permcody** [comment]
👍

**Comment by sapitts** [comment]
Thank you gentlement.   @permcody would it work for me to talk with you about better ways to execute certain lines only on the first or zeroth timestep next week, after Tiger Team is finished?  If we can work out a better way to handle these special cases, it makes an awful lot of sense to make that code change when migrating these tests to tensor mechanics.  @bwspenc and @jasondhales do you have suggestions on how we could get around using the ```if (_t_step == 0)``` logic?  Perhaps by querying total strain and / or stress?

**Comment by mll36** [comment]
I wonder if these initial strains/stresses could be moved to an initialization class at the beginning of simulations? It would remove those if statements in the materials increasing performance.

**Comment by permcody** [comment]
Yes @mil36, I was thinking along those lines. Not new classes though, just additional initialization methods for Materials. @sapitts, Feel free to stop down in 109 to talk about this. It's important and this is as good of time as any to work these issue out with the whole team present.

**Pull request merged**
