### PR TITLE
Modify PETSc configure script to look for, or download, HDF5 by default

### PR DESCRIPTION
**Pull request by cticenhour**
This PR adds a first draft of logic to `scripts/configure_petsc.sh` so that HDF5 can be found locally on a user system. The changes do the following:

1. The first attempt to locate HDF5 uses the user-set environment variables `HDF5_DIR`, `HDF5DIR`, and `HDF5_ROOT` in that order of priority. 
2. If these variables are not defined, HDF5 is then searched for using common locations:
    - `/usr/lib/hdf5`
    - `/usr/local/hdf5`
    - `/usr/share/hdf5`
    - `/usr/local/hdf5/share`
    - `$HOME/.local`
    - ~~`$PATH`~~ EDIT: On second thought, we don't want to do this (see comments below). Removed as of [4882e3c](https://github.com/idaholab/moose/pull/20358/commits/4882e3c05535aa718c00a7c94bc8733d220b4471)

    when the first instance of `hdf5.h` is discovered, this location is used in PETSc configure and reported to the console for user reference. The user is also notified that `HDF5_DIR` is an option to specify the installation if this discovered HDF5 isn't suitable. 
3. If HDF5 is still not found, then it is downloaded via PETSc on Linux. On macOS, due to the [following gfortran bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102992) we cannot yet enable the PETSc HDF5 as a true fallback option. In that instance, the user is notified via the console that `HDF5_DIR` is available if they happen to have an installed alternative. 

Refs #20033

### CODE REVIEW

**Comment by roystgnr** [comment]
Ooh - is (2) going to start an argument?  I was under the impression that current Moose policy was something like "avoid adding system paths to our include/link lines except by specific user request", on the theory that we have too many users with /some/weird/module/path/libStuff.so.new and /usr/lib/libStuff.so.ancient and we don't want ancient system builds conflicting with up-to-date module builds.

I wasn't thrilled with that philosophy when I first heard it; I like e.g. Ubuntu users to just get as many dependencies as are installed automatically working, but I've since become a convert.  On my TODO list is a `--enable-lib-search` (exact name TBD) configure option for libMesh to search `/lib` and `/usr/` and such, such that when it's disabled (including by default) we consider any automatic inclusion of those paths in our search lists to be a bug, whereas when it's enabled we consider that a request to search those paths (and /usr/lib64, and subdirectories, and whatever else typically sees preinstalled packages) for anything and everything that they might have that we might be able to use.

**Comment by cticenhour** [comment]
I'm not wedded to it.....I went back and forth about keeping it in there earlier for exactly your reasons. I personally like allowing users to tailor what is searched using their defined `PATH`, but this only really works well for those users who keep a tight watch on what they have on their system. It's risky, to be sure. I'll remove it during the next round of updates, as I have another small change to make to the `find` command flags anyway.

**Comment by cticenhour** [comment]
@roystgnr a follow up here - do you think I should also have the script look in `/opt`?  I based the currently used locations in `/usr` and `$HOME` on those I saw in libmesh contrib cmake files for netCDF and exodus.

**Comment by roystgnr** [comment]
Nah; /opt is still "someone other than me installed this" in general and has the same caveats - even if the stuff there is a lot less likely to be ancient, it's only a little less likely to get the user in trouble with conflicts.

Although, when I do add an `--enable-autodetect` or whatever for libMesh, I should definitely remember to have it check /opt too.

**Comment by roystgnr** [comment]
Sorry about the fakeout Close; I should be more careful when using a mouse while on a treadmill.

**Comment by loganharbour** [comment]
@roystgnr aggressively pushing his opinions with the close

**Comment by cticenhour** [comment]
One thing here that I wanted to note in case it causes us some trouble.....conda is issuing clobber warnings about possible conflicts between the `hdf5` package we keep around for `moose-tools` and the PETSc HDF5. This is occurring in the Linux end user experience targets. See a sample below:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::hdf5-1.10.6-nompi_h6a2412b_1114, https://conda.software.inl.gov/moose/pr-20358/linux-64::moose-petsc-3.15.1-build_7
  path: 'bin/gif2h5'
```
I am concerned HDF5 from `moose-petsc` might get overwritten by HDF5 from `moose-tools` (or vice versa). I don't exactly see a way around that except to remove HDF5 from `moose-tools`......which definitely isn't ideal for those cases when someone is only running `moose-mpich` and `moose-tools`. @milljm do you have some thoughts about this?

**Comment by loganharbour** [comment]
> I am concerned HDF5 from `moose-petsc` might get overwritten by HDF5 from `moose-tools` (or vice versa).

I don't think we care as long as libmesh picks up the one that petsc used.

**Comment by cticenhour** [comment]
Right. I'm just envisioning a scenario when the pre-compiled libmesh is using HDF5 libraries in that shared path that are subtly (or not subtly) different than those it expects and compiled with. Sounds like something we wouldn't be able to control. That's why I wanted some other opinions.

**Comment by loganharbour** [comment]
I mean if it’s compiled with them at a specific path it should just work? You either have works or not, not sure about subtly different

**Comment by cticenhour** [comment]
> I mean if it’s compiled with them at a specific path it should just work? You either have works or not, not sure about subtly different

I could very well be overthinking here, given all the beautiful green on CIVET. When I was considering this yesterday, it reminded me of MOOSE build failures with libmesh regarding previously built libraries that no longer correspond to the source code being compiled. We provide serial HDF5 1.10.6 right now, but want to *also* provide parallel 1.12.0. Even if libmesh was originally built using 1.12.0 as we wanted, would it fail when looking for a `.dylib` corresponding to 1.12.0 but finding one for 1.10.6 due to an overwrite (since all libs are put in `~/miniconda3/envs/moose/libs`)? Might not be an issue, but I just wanted to bring it up.

**Comment by cticenhour** [comment]
@roystgnr one more question before I mark this ready for review. Would you want me to turn on HDF5 in the current libmesh package, or wait until your changes in libmesh/libmesh#3145 make it to the submodule?

**Comment by dschwen** [comment]
> 3. If HDF5 is still not found, then it is downloaded via PETSc on Linux. On macOS, due to the [following gfortran bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102992) we cannot yet enable the PETSc HDF5 as a true fallback option.

Whoa, that's why I suddenly had to add calls to FLUSH. Here 4f4c1309ec11bd4d4fbfc7e4acd43d3903ee00993e10732664ac22878e10d7bcR66

**Comment by roystgnr** [comment]
> Would you want me to turn on HDF5 in the current libmesh package, or wait until your changes in https://github.com/libMesh/libmesh/pull/3145 make it to the submodule?

I'd be thrilled to have it turned on if you can make sure that it fails gracefully ... which I guess is as simple as not using --enable-hdf5-required?

In the long-term I want all our binary distributions and most of our CI runs to be built with --enable-hdf5-required but that'll be a little user-unfriendly if we do it before the PETSc HDF5 autodetection is in place.

**Comment by loganharbour** [comment]
> @milljm `moose-mpich` doesn't appear to have updated on these build boxes (getting C++17 errors). See https://civet.inl.gov/job/976307/ with conda environment list output:
> 
> ```
> moose-mpich                      3.4.2  build_2
> ```

We cache old builds. This is what happens when you start a conda build, but then another conda build happens (actual update gets pushed), and then you build again. I'll go nuke it.

**Comment by cticenhour** [comment]
@YaqiWang @zachmprince any idea why adding HDF5 might be causing the single failure in Griffin we're seeing? Or have we tripped something unrelated?

**Comment by YaqiWang** [comment]
@zachmprince and I talked. It is a bug in `AdvancedOutput::initAvailableLists()`. I assume Zach is working on a fix. Glad this bug was caught by this PR.

**Comment by cticenhour** [comment]
@YaqiWang thanks for the update! I appreciate you and @zachmprince taking a look. Let me know if I can be of assistance with the fix.

**Comment by loganharbour** [comment]
Is this almost good?

**Comment by cticenhour** [comment]
Yeah - going to rebase and push with the MOOSE fix in next once Griffin update makes it to master (almost there).

**Comment by cticenhour** [comment]
Closing in favor of #20580

**Pull request closed without merging**
