### PR TITLE
Adding basic structure for fluid properties module

### PR DESCRIPTION
**Pull request by andrsd**
There is a base class FluidProperties that inherits from a
GeneralUserObject. The next child class belwo it is
SinglePhaseFluidProperties than defines fluid properties for a single
phase like pressure, temperature, cp, cv, k, mu, c, etc.

Two basic equations of state are alos provided:
- stiffened gas
- ideal gas

There is a basic material that computes the properties:
FluidPropertiesMaterial.

The syntax to use this is:

```
[FluidProperties]
  [./air]
    type = IdealGasFluidProperties
    ...
  [../]
  [./water]
    type = StiffenedGasFluidProperties
    ...
  [../]
[]
```

Refs #6972

### CODE REVIEW

**Comment by friedmud** [comment]
This looks good to me.  I'll leave it up for a few hours this morning in case others want to comment on the design... but I'll merge it here in a little while...

**Comment by jwpeterson** [comment]
:+1:

**Comment by friedmud** [comment]
This commit reminds me that our current way of doing custom Module input file syntax (like the input file block you're adding here) is bad.  It is really cluttering up the "top level"... especially for people new to MOOSE.

I REALLY think it's time for us to put Module syntax blocks underneath a `[Modules]` block in the input file.  I have an open ticket for it here: https://github.com/idaholab/moose/issues/5585

This is the perfect candidate to start it with.  VERY few people are going to need this new block... but every new MOOSE-based application (and any old ones that use ALL modules are going to have this cluttering up the top level).

What do you say about starting the trend and putting this new input file block under `[Modules]`?

**Comment by dschwen** [comment]
Totally agree. I have already started using `[Modules]` [in phase field](https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/base/PhaseFieldApp.C#L439).

**Comment by friedmud** [comment]
@dschwen cool!  I didn't know that.  Glad to see some movement on this front... it will really clean up our syntax tree...

**Comment by andrsd** [comment]
@friedmud This is a top level block in RELAP-7 and pretty important one. So, I'd like to keep that if possible, so I do not have to change every single input file in RELAP-7.

Any chance that app could decide how to register additional syntax?

**Comment by friedmud** [comment]
The App can certainly register the block as a top-level block if it wants
to.  Just do it in the App::registerSyntax() function.

**Comment by andrsd** [comment]
So yes, I do not have to call `FluidPropertiesApp::associateSyntax(_syntax, _action_factory);` and put its body in RELAP-7's register stuff, but I thought we do not recommend to do so... maintenance, etc.

**Comment by friedmud** [comment]
For now, I think that's the best option (to register it the way you want it in RELAP-7).  That's one of the reasons we have the flexibility built in to register objects / syntax separately (so an App can present Module/MOOSE/other objects they way they want with their own syntax).

I do agree that it creates a strong dependency though... so maybe in the future we can engineer a better solution.

Maybe we can pass in a "Prefix" to Modules to tell them where to register their syntax.  Most applications will just leave it at the default of `"Modules/fluid_properties"` and others can just pass in `""` (to signify that they want the Module to register syntax at the outermost level.

If you like that idea - let's create a ticket and we can talk about it during the tiger team...

**Comment by andrsd** [comment]
I was thinking along similar lines. I will be glad to work on this during the tiger team week.

I'll make the change and let's merge this, some other app is waiting on this...

**Comment by friedmud** [comment]
Cool - sounds good

**Comment by dschwen** [comment]
This PR introduced a bunch of compiler warnings in dbg:
<details>
<summary>Compiler output excerpt</summary>
```
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:154:41: warning: unused parameter 'pressure' [-Wunused-parameter]
StiffenedGasFluidProperties::e_dpT(Real pressure, Real temperature, Real & e, Real & de_dp, Real & de_dT) const
                                        ^
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:154:56: warning: unused parameter 'temperature' [-Wunused-parameter]
StiffenedGasFluidProperties::e_dpT(Real pressure, Real temperature, Real & e, Real & de_dp, Real & de_dT) const
                                                       ^
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:154:76: warning: unused parameter 'e' [-Wunused-parameter]
StiffenedGasFluidProperties::e_dpT(Real pressure, Real temperature, Real & e, Real & de_dp, Real & de_dT) const
                                                                           ^
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:154:86: warning: unused parameter 'de_dp' [-Wunused-parameter]
StiffenedGasFluidProperties::e_dpT(Real pressure, Real temperature, Real & e, Real & de_dp, Real & de_dT) const
                                                                                     ^
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:154:100: warning: unused parameter 'de_dT' [-Wunused-parameter]
StiffenedGasFluidProperties::e_dpT(Real pressure, Real temperature, Real & e, Real & de_dp, Real & de_dT) const
                                                                                                   ^
/Users/schwd/Programs/moose/modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C:182:41: warning: unused parameter 'pressure' [-Wunused-parameter]
StiffenedGasFluidProperties::h_dpT(Real pressure, Real temperature, Real & h, Real & dh_dp, Real & dh_dT) const
                                        ^
```
</details>

**Comment by YaqiWang** [comment]
Just a reminder: if this is a new module, we might need to fix the MAMMOTH make file to indicate R7 is going to need it.

**Comment by andrsd** [comment]
> This PR introduced a bunch of compiler warnings in dbg:

I'll fix that...

> we might need to fix the MAMMOTH make file to indicate

RELAP-7 does not use that module yet, so as long as you do not have that module active in the MAMMOTH makefile, you do not have to do anything...

**Pull request merged**
