### PR TITLE
Cleanup of InteractionIntegral in solid mechanics #9559

### PR DESCRIPTION
**Pull request by sveerara**
- Move the aux_stress and aux_grad_displacement from InteractionIntegralAuxFields.C to InteractionIntegralSM.C

- Removed InteractionIntegralAuxFields.C material model

- Edited DomainIntegralAction so that it passes the required additional parameters to InteractionIntegralSM.C and does not add the InteractionIntegralAuxFields.C material model

@bwspenc, can you please take a look at this PR. Thanks!
ref #9559

### CODE REVIEW

**Comment by bwspenc** [comment]
@sveerara To fix the documentation build, you just need to remove the markdown file (which I just added the other day!) for that Material that you removed.

**Review by bwspenc — APPROVED** [review]
Looks good!  Thanks a lot for doing this.

**Comment by sapitts** [comment]
I think this might help address some of the documentation failures that we're seeing in Bison as of yesterday too. Thanks for the fix @sveerara

**Comment by bwspenc** [comment]
@sapitts I have a hunch I know what's causing those problems.  I'll come by.

**Comment by bwspenc** [comment]
@sveerara I just did a timing study, and one of my models took 24 minutes to run one step before, and now it takes 17 minutes.  There was a bunch of other expensive initialization in that model, so chances are that the speedup is even more significant in a model with many time steps.

**Comment by sveerara** [comment]
@bwspenc, that's great. I am glad this change is reducing the computation time.

**Pull request merged**
