### PR TITLE
More efficient correct PolycrystalICs

### PR DESCRIPTION
**Pull request by permcody**
I still have a ways to go on this but the syntax is starting to take shape. I've updated several of the existing input files to get them to run and I want to make sure I have buy-in from @tonkmr and @dschwen.

The idea is that you have to create a UserObject for "Polycrystal IC". Right now you can do this for Voronoi and Hex. Eventually, I'll want to make sure we can do it for Reconstruction as well. It may be overkill for things like Bicrystals. Then you link the userobject to the ICs block. What I haven't changed yet is the name of that block. It's currently incorrectly called `PolycrystalVoronoiIC` because I hijacked the existing "reduced" IC action to make this work.

I need input, what shall we call the IC that links to the UserObject? Should we have a new block name here? Maybe `PolycrystalReducedIC`? That's what you'd use this for, any time you need to assign a reduced number of OPs to a larger number of grains. Even though we currently have a reduced IC (that will go away) we don't have a block with that name. However, Maybe users don't care about that and just want to set up a polycrystal structure without thinking about whether or not the number of grains and ops match or not. I was originally thinking about deleting the whole inner block but after looking at the plethora of actions we have, I'm not sure we want to do that. For instance the Bicrystal stuff should probably stay. 

This PR is working and looks very promising as far as scalability goes. I might take it as is and try running the large 3D problem over the weekend. 

If all of this is too intrusive, I can just back off on all of it and create a new Action and new IC that just does the right stuff and leave all of the existing ICs alone.

### CODE REVIEW

**Comment by permcody** [comment]
Nevermind on this. I thought about it a lot last night and decided it's too disruptive as is. I'm going to create one new IC and leave the existing ones alone for now. We can talk about transitioning some of the existing ones over after this is merged.

**Comment by dschwen** [comment]
Reduced op models will always be run with `GrainTracker`, right? So why not call this `GrainTrackerIC`. It will look more familiar to users.

**Comment by permcody** [comment]
I'm going to say "no" for two reasons:
First, you may not need the GrainTracker on some simulations even though you want to use a reduced OP assignment. The example that comes to mind are just about any hexagonal grain structure that is static or moves very little. Also, we might use this one IC to handle most of our polycrystal structures. The jury is still out on that one.
Second, You don't actually couple to the GrainTracker with this IC so that name might really be confusing.

I just about how a non-destructive PR ready to go and I'm calling it `PolycrystalColoringIC`. If you think that's bad, let me know. We could actually call it PolycrystalReducedIC since that name doesn't actually appear in the input file to date despite having an IC by that name. That IC will very quickly be deprecated (in a followup PR).

**Comment by permcody** [comment]
BTW - I got the Elder force Hex example running properly with three OPs yesterday. I don't think the greedy algorithm assigns that correctly right now. You don't need the grain tracker on that simulation.

**Comment by dschwen** [comment]
`Elder force Hex`... Is that the new Skyrim?

**Comment by permcody** [comment]
🤣

**Pull request closed without merging**
