### PR TITLE
Update tensor mechanics tutorial inputs

### PR DESCRIPTION
**Pull request by sapitts**
No design change nor code change in this commit. 

The commit does introduce the use of a tests file for the tensor mechanics input files as suggested by @brianmoose ; for short running tutorials I've set the full test to run and for the longer tutorial files I've set the tests file to only perform a syntax check.

The commit also changes the input files to use the tensor mechanics master action as suggested by @WilkAndy.  I've added comments to help identify and explain changes from one input file to the next in the series progression.

These changes to the input files should be accompanied by an update to the tutorial pages on the mooseframework.org page. @permcody would you help me get editor access to the tutorial pages or help me identify a moose team member to work with to update the tutorial pages?

Refs #10158

### CODE REVIEW

**Comment by sapitts** [comment]
Thank you @milljm for the help with the tutorial website pages editing.  I'll update those pages right away when this merge request goes through (to avoid describing changes to files that don't yet exist in the repo).

**Comment by dschwen** [comment]
It would be sweet if we could bring this tutorial into the presentation blaster format.

**Comment by sapitts** [comment]
> It would be sweet if we could bring this tutorial into the presentation blaster format.

Hmm, I'm feeling more inclined towards a savory approach at the moment. But I'll look into this format. Pretty sure I won't have it all sorted by the time you have to give training next week, unfortunately

**Comment by permcody** [comment]
@sapitts - I believe you can just go edit the old wiki. If you have a few small edits, that's probably fine. At some point we need to bring it over to the new site, but that's going to take some time.

**Review by dschwen — DISMISSED** [review]

**Comment by sapitts** [comment]
@permcody The master action changes are fairly significant, so I will be changing the tutorials on the old wiki more than a little (albeit removing more existing information than adding new information).  Would it be best to hold off on the master action changes to the tutorial files until I've added the appropriate documentation to the new site?  I've got the changes separated into two commits so that it's easy to drop the changes that would require updating the older wiki pages

**Comment by permcody** [comment]
I don't see us getting to the tutorial anytime soon so we need to update the old site independently of the new site so that the training makes sense. I'm fine with you making those changes there even if the information isn't on the new site. It'll take some time to get that moved over and working like it does today.

**Comment by sapitts** [comment]
I've updated the older wiki to reflect the use of the tensor mechanics master action.  Repushed because I found a couple of typos in my input files when writing the documentation.

I think I've got an idea about how to get this information into the presentation blaster format, in a separate commit to the presentations repo, but I'd welcome suggestions on the best place for this tutorial information in the presentations folder.

**Review by dschwen — APPROVED** [review]

**Pull request merged**
