### PR TITLE
fixed uninitialized iterators in ComputeNodalKernelJacobiansThread.C and ComputeNodalKernelBCJacobiansThread.C

### LINKED ISSUE #6294: uninitialized iterator in (ComputeNodalKernelJacobiansThread.C) causes seg faults
find uninitialized iterator in ComputeNodalKernelJacobiansThread.C and ComputeNodalKernelBCJacobiansThread.C, can cause segmentation fault.

### PR DESCRIPTION
**Pull request by jiangwen84**
Fixed the uninitialized iterators

Closes #6294

### CODE REVIEW

**Comment by jwpeterson** [comment]
Wow, code review fail.

**Comment by dschwen** [comment]
I'm surprised this is not detected by the Valgrind tests.

**Comment by jwpeterson** [comment]
> I'm surprised this is not detected by the Valgrind tests.

According to the code coverage statistics, the entire loop is never hit.

**Comment by friedmud** [comment]
Yep... no tests yet doing off-diagonal jacobian building with NodalKernels.

**Comment by dschwen** [comment]
Off diagonals are premium DLC

**Comment by friedmud** [comment]
@dschwen lol

**Comment by friedmud** [comment]
Thanks so much @jiangwen84 !

**Pull request merged**
