### PR TITLE
Do not evaluate nodal BCs for non-nodal variables

### LINKED ISSUE #14019: Nodal BCs are executed when they act on a non-nodal variable
## Bug Description

When nodal BCs are active on a non-nodal variables, the code goes and tries to evaluate them. This is wrong, nodal BCs should not be evaluated on non-nodal variables.

## Steps to Reproduce

This input file:
```
[GlobalParams]
  family = MONOMIAL
  order = CONSTANT
[]

[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 1
 []

[Variables]
  [u]
  []
[]

[Kernels]
  [diff]
    type = Diffusion
    variable = u
  []
[]

[BCs]
  [bcs]
    type = DirichletBC
    variable = u
    boundary = 'left right'
    value = 1
  []
[]

[Executioner]
  type = Transient
  dt = 1
  num_steps = 1
  abort_on_solve_fail = true
[]
```

## Impact

If users are lucky, this will produce an answer, but in a small fraction of cases this will cause the code to crash.

### PR DESCRIPTION
**Pull request by andrsd**
In SystemBase::reinitNode{Face}(), we checked if the variable was nodal
and if it was we called reinitNode() and then computed values.  This caused
that the internal state of MooseVariable was not updated, so when we got
into a nodal system and asked the variable if it was defined at nodes via
isNodalDefined() call, the answer was incorrect.

The SystemBase::reinitNode{Face}() needs to update the internal state of
MooseVariable first and then if the variable is defined at the node, we
compute its values and possibly evaluate the objects associated with the
variable.

Closes #14019

### CODE REVIEW

**Comment by andrsd** [comment]
I am going to suggest to myself that this should actually throw an error :-)

**Review by lindsayad — COMMENTED** [review]
I'm admittedly a little baffled at how this code compiles without complaining about an undefined reference for `isNodalDefined`. So what is the difference between `isNodal` and `isNodalDefined`?

**Comment by andrsd** [comment]
`isNodal` tells you if the variable in nodal or not in general. `isNodalDefined` tells you if the variable has a nodal DoF at a location it was previously reinited.

**Comment by andrsd** [comment]
> I'm admittedly a little baffled at how this code compiles without complaining about an undefined reference for `isNodalDefined`

Look at the changes in `framework/include/variables/MooseVariableFEBase.h`. Is that what you are missing?

**Comment by lindsayad** [comment]
> Is that what you are missing?

I see a pure virtual in `MooseVariableFEBase` and then an `override` in `MooseVariableFE` with no apparent definition...

**Comment by andrsd** [comment]
> I see a pure virtual in `MooseVariableFEBase` and then an `override` in `MooseVariableFE` with no apparent definition...

That was only changed to be virtual, the body was already there.

**Comment by lindsayad** [comment]
> That was only changed to be virtual, the body was already there.

Lol. 🤦‍♂ 

Do you have any idea about why Numbat is failing with this?

**Review by lindsayad — APPROVED** [review]

**Comment by andrsd** [comment]
> Do you have any idea about why Numbat is failing with this?

Not yet...

**Comment by andrsd** [comment]
Ok, here is why. Numbat uses 2nd order mesh, then it uses `NodalValueSampler` to put those values into a CSV file. The mesh has 63 nodes, but the gold file has only 23 entries. So it looks like the tests rely on an incorrect behavior, where the `NodalValueSampler` produced only values from "1st order" nodes.

I will send them a PR.

Tagging @cpgr

**Pull request merged**
