### PR TITLE
Regold Test for libMesh#2584

### LINKED ISSUE #15351: Enforce Ordering of Nodal Variables in Nemesis Output Files
## Bug Description
When nodal solutions are written to Nemesis output files the ordering of the vector pairs created by libMesh `EquationSystems::find_variable_numbers` is not preserved. This causes nodal variable values to be written to the wrong variable name within the Nemesis output files.  Please note that this is a libMesh bug ([ref libMesh#2581](https://github.com/libMesh/libmesh/issues/2581)) and no framework changes are needed in MOOSE.  However, the `nemesis_hide.i` test in MOOSE needs to be regolded in order for the PR ([libMesh #2584](https://github.com/libMesh/libmesh/pull/2584)) to pass testing.

## Steps to Reproduce
Run the `nemesis_hide.i `test and view the nodal variable values from the Nemesis output file  in Paraview.

## Impact
The `nemesis_hide.i `test needs to be regolded.

### PR DESCRIPTION
**Pull request by frombs**
closes idaholab#15351
refs [libMesh#2584](https://github.com/libMesh/libmesh/pull/2584) & [libMesh#2581](https://github.com/libMesh/libmesh/issues/2584)

### CODE REVIEW

**Comment by frombs** [comment]
@permcody, one test timed out and the other three appear to have failed because "moose-libmesh 2020.05.13" from Conda was used instead of the updated version of libMesh.

**Comment by loganharbour** [comment]
@frombs our testing suite has changed some.

The majority of the tests now use conda, which only creates a new libmesh package if changes are found in the conda configuration. What this should be the majority of the time is simply a build date change [here](https://github.com/idaholab/moose/blob/next/conda/libmesh/meta.yaml#L3). On initial testing a PR, CIVET will note the config change and the conda stack will be then recompiled using the available libmesh submodule. This recompiled stack will then be used by all the recipes in that PR.

Even more... you will not be able to change this content in this PR, because once a PR is created, we guarantee that it will always use the same conda stack.

Therefore: if you want to really test this, you will need to create a new PR with the same content, and also trigger a new conda libMesh build by changing the build date I linked to above. 

@milljm is there a writeup about this somewhere?
@lindsayad are you ready for a libMesh update?

**Comment by milljm** [comment]
No there is no writeup about this. The behavior is exactly the same as it was before we switched to Conda.

Your PR began with moose-environment package 70, it will stay with 70.
New Conda method:
Your PR began with Conda environment 70, it will stay with 70.

**Comment by loganharbour** [comment]
> The behavior is exactly the same as it was before we switched to Conda.

The update libMesh behavior isn't the same.
Before: update submodule
After: update submodule and update libmesh conda config

**Comment by milljm** [comment]
This is the second time this has 'hit' us. I am re-thinking the reason behind supplying libMesh at all in our Civet tests. Perhaps every target should go back to building submodule libMesh.

**Comment by lindsayad** [comment]
We just updated libmesh in #15331 but we could do it again. But there's no way we're going to merge this with a libmesh commit that isn't in upstream libmesh

**Review by lindsayad — CHANGES_REQUESTED** [review]
This will wait at least until the libmesh hash is actually in upstream libmesh

**Comment by frombs** [comment]
@milljm, John pushed my libMesh branch to upstream so I should be able to proceed with a new PR now.  However, I am not sure how to proceed about the conda moose-libmesh version.  Do I wait until the next big libMesh update so I can get a new hash that contains my libMesh changes?

**Comment by lindsayad** [comment]
Update the version string in moose/conda/libmesh/meta.yaml. However, @milljm and @loganharbour can correct me if I'm wrong but I believe that build boxes which have already run your PR will not consider your meta.yaml change. If you pushed a change to the meta.yaml now, any new boxes that start testing would see and use your updated conda libmesh, but boxes which have already run testing on this PR would not.

**Comment by frombs** [comment]
@lindsayad, thanks for responding .  I plan to create a new PR as you and Logan have suggested.  I changed the meta.yaml hash to "2020.5.29" in my branch to see what would happen on my local workstation.  I wanted to run with the updated `conda moose-libmesh `package instead of my custom compiled libMesh build to find any errors that would show up on Civit when I create the new PR.  

However, when I tried to update the conda package using `conda install moose-libmesh=2020.5.29` on my workstation it gave me an error.  I then typed `conda search -f moose-libmesh` and found that the most current available version was "2020.5.13."  I naively thought that a new version was automatically generated each day and reached out to Jason to see how the process works.

**Comment by lindsayad** [comment]
We only publish packages for build versions that make it into moose master. There is a way to retrieve packages generated from build versions in PRs but I believe you will need an INL HPC account to do that...

**Comment by frombs** [comment]
I have an HPC account so would like to try if the instructions are available.

**Comment by lindsayad** [comment]
Ok let's say you wanted to test a conda package generated by this PR. First, make sure you have a config that looks like what is [here](https://www.mooseframework.org/help/inl/hpc_remote.html) You would then do:
```
conda config --add channels https://rod.inl.gov/conda/moose/pr-15352
```
Then make sure you add this to your shell environment:
```
export http_proxy=socks5h://localhost:5555
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
```
and then try
```
conda update moose-libmesh
```

**Comment by milljm** [comment]
To be clear, Conda environments available on Rod were not deleted. Only on the build machines themselves (forcing them to re-create and thus use anything new found on Rod).

**Comment by frombs** [comment]
> To be clear, Conda environments available on Rod were not deleted. Only on the build machines themselves (forcing them to re-create and thus use anything new found on Rod).

@milljm, thanks for making the change.  All of the test are passing now.  Going forward, do you need to do that manually each time for this situation or will conda automatically recognize the newer libMesh hash?

**Comment by frombs** [comment]
@lindsayad, thanks for the instructions.  I was able to get conda to download the correct libMesh version with one small change.  I initially received the error "CondaHTTPError: HTTP 000 CONNECTION FAILED".  Typing "config --set ssl_verify no" resolved the issue.

**Comment by lindsayad** [comment]
Oh yea forgot to share that one. Good detective work!

**Comment by milljm** [comment]
@frombs going forwards, Civet is building libMesh every time, the way it used to. It will not be using the Conda moose-libmesh package.

**Comment by frombs** [comment]
@lindsayad, I noticed you merged a new libMesh update.  Is this PR safe to merge now?

**Comment by loganharbour** [comment]
@frombs can you please remove the submodule update and the update to `conda/libmesh/meta.yaml`?

Should be good to test shortly and good to go after that.

**Comment by milljm** [comment]
@frombs  The changes made to the meta.yaml file must be removed... Otherwise this PR would revert what would look like a previous version of libMesh... (we updated to 2020.06.03)

**Comment by frombs** [comment]
How do I remove the libmesh submodule update?

**Comment by loganharbour** [comment]
Oh man, there's so many ways to go about doing this. Seeing that you only have two simple commits, I would go about it like this:

```
git reset HEAD~2
```

This will reset the state to before your two commits, and should just leave you with modified and not staged files (2 exodus files, libmesh, and the meta.yaml). Then, you can just go about adding only the files you need (the 2 exodus files) with `git add` per usual and a commit with `git commit -m` per usual.

You'll then need to do a force push (you're rewriting history) with:

```
git push --force
```

**Comment by loganharbour** [comment]
Looks good 👍 should be good to go when everything passes.

**Comment by frombs** [comment]
> Looks good 👍 should be good to go when everything passes.

Logan, thanks for your help!

**Comment by frombs** [comment]
I'm going in circles...tests are failing again. I thought that 2020.6.2 would include my libmesh changes from 2020.5.29.  Was that a bad assumption?

**Comment by loganharbour** [comment]
GAH. I forgot that now, we are actually using the libMesh submodule for testing PRs, and not conda. This should not be a problem in the future, sorry about that!

I'm going to have you pull in the latest libMesh submodule, by grabbing all the changes that are currently in devel. Can you do this (assuming that the idaholab remote is called upstream):

```
git fetch upstream
git rebase upstream/devel
git push --force
```

This will take current idaholab/moose/devel and put your commit on top. By that, you'll get the new libMesh that we have right now and your tests will run with this.

Again - sorry about the mixup here!

**Comment by lindsayad** [comment]
> I'm going in circles...tests are failing again. I thought that 2020.6.2 would include my libmesh changes from 2020.5.29. Was that a bad assumption?

It does not include it because the master branch of libMesh does not contain your PR commits. I can rebase your libMesh PR on top of libMesh master and again push to upstream libmesh as @jwpeterson did before. Then you can update your libMesh hash here and we can run testing again. Note that I will not merge this PR unless I know your libMesh PR is going to be approved and merged. Otherwise we will end up with all kinds of problems because we'll have a libMesh hash in our MOOSE repo doesn't exist in the libMesh upstream repository

**Comment by lindsayad** [comment]
@frombs sit tight and I'm going to update both your libmesh and MOOSE PRs

**Comment by milljm** [comment]
@lindsayad @frombs Thanks for your patience. Removing the need for Conda's moose-libmesh _after_ asking you to update it, _half_ way through your PR is something we just don't have a procedure for.

**Comment by lindsayad** [comment]
Ok, my fingers are crossed...I think this should test green! (or at least orange!)

**Comment by lindsayad** [comment]
We're going to set a record for libmesh updates in a month. I don't even send out emails anymore it's so ridiculous

**Comment by lindsayad** [comment]
@loganharbour can you review? I have half the commits on the PR (ok yea so it's only one commit), so I'd prefer someone else reviews

**Review by lindsayad — APPROVED** [review]
You know it's probably fine

**Comment by loganharbour** [comment]
For SQA - I do indeed approve, after the fact. 😬

**Pull request merged**
