### PR TITLE
Update validParams

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by aeslaughter** [comment]
I still need to do functional_expansion_tools and the framework directory.

**Review by rwcarlsen — APPROVED** [review]
marmot failures are not related.

**Comment by lindsayad** [comment]
I can see how @aeslaughter  plans to overtake @permcody for commit leader

**Comment by permcody** [comment]
Yeah - he claims it doesn't matter, but he's working hard 😉

**Pull request merged**
