### PR TITLE
Skip tensor rotations for isotropic plasticity models 

### LINKED ISSUE #14495: Finite strain rotation in multiple inelastic stress
## Reason
@WilkAndy , why is it required to rotate a guaranteed isotropic elasticity tensor if a tangent operator other than the elastic approximation is used? I'd think isotropic is isotropic and stays the same no matter how you rotate it?!

Elasticity tensor rotations make up a substantial chunk of run time for some cases (up to 15%!!).

## Design
Skip elasticity tensor rotation even if elastic tangent operator approximation is _not_ used.

## Impact
Faster simulations.

### PR DESCRIPTION
**Pull request by dschwen**
This should save a significant amount of compute time for all radial return based models that do not use an elastic approximation to the tangent operator.

Closes #14495

### CODE REVIEW

**Review by WilkAndy — APPROVED** [review]
Thanks @dschwen

**Review by bwspenc — APPROVED** [review]
Thanks for fixing this!  I'm sure it sped things up, but I'm curious, did you have a chance to do any timing studies?

**Comment by dschwen** [comment]
@bwspenc I did runs some short (4 timesteps) profiler runs on the PK13 example. After the change the total time dropped to 72%(!).

**Comment by dschwen** [comment]
[PK23 before this PR](https://github.com/idaholab/moose/files/3945617/PK23_before.pdf)
[PK23 after this PR](https://github.com/idaholab/moose/files/3945618/PK23_after.pdf)

**Comment by bwspenc** [comment]
Nice!  I guess that's about what we should have expected, given that it was spending 21% of its time rotating the rank 4 tensor.

**Comment by permcody** [comment]
@bwspenc and @dschwen - This is causing a failure in THM. Is anybody patching or looking at that?

FYI - @andrsd

**Comment by permcody** [comment]
> @bwspenc and @dschwen - This is causing a failure in THM. Is anybody patching or looking at that?

Scratch that - looks like THM has been broken for awhile.

**Pull request merged**
