### PR TITLE
MUMPS not needed to run PorousFlow examples

### LINKED ISSUE #16951: Don't use MUMPS in a couple of PorousFlow examples
## Reason

MUMPS is great, but some people don't have MUMPS installed.  I don't need to use it in 
```
examples/tutorial.13 ...................................................................... [MUMPS!=TRUE] SKIP
examples/thm_example.2D ................................................................... [MUMPS!=TRUE] SKIP
```

## Design

Just remove the "skip" in the `tests` file and modify the input files accordingly

## Impact

1. More thorough testing (these two tests will run on machines without mumps after this issue is fixed)
2. Ability to run these examples for users who don't have mumps

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #16951

### CODE REVIEW

**Comment by WilkAndy** [comment]
When convenient, could someone please invalidate the "Internal App tests"?

**Comment by WilkAndy** [comment]
Hey @loganharbour - just wondering if you could invalidate the Internal App tests on this PR?

**Comment by WilkAndy** [comment]
Hi @GiudGiud , just wondering if you could invalidate the "Internal App tests" on this PR, and hopefully merge?

**Comment by loganharbour** [comment]
@WilkAndy there's a failure that won't be fixed until the work week. Should be able to merge on monday.

**Review by loganharbour — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for the notification @loganharbour - no probs about waiting till next week

**Pull request merged**
