### PR TITLE
Disallow initial MultiApp failure

### LINKED ISSUE #7213: Initial MultiApp failures should not be allowed
### Description of the enhancement or error report
Currently we have a TODO at line 575 of `FEProblem.C`. It is basically allowing the multiapp on initial to fail to converge. When this does happen, transfer from multiapp to master will be skipped. This is pretty bad decision IMO.

### Rationale for the enhancement or information for reproducing the error
Users could see some really odd behavior because of this if he or she set the tolerance of his or her initial full solve multiapp too tight.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Should not have impact otherwise make bugs in the inputs show up.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #7213.

### CODE REVIEW

**Comment by friedmud** [comment]
My only issue here is that this PR is technically doing two different things... can you slim it down to just the one relevant commit?

**Comment by YaqiWang** [comment]
I did. Sorry, you need to refresh this page ;-)

**Comment by friedmud** [comment]
Cool - I'll merge this once it passes

**Comment by friedmud** [comment]
I think we need a test for this.  The sub-app could use `FailingProblem` ( https://github.com/idaholab/moose/blob/devel/test/include/problems/FailingProblem.h ) to make sure it fails and then we can test for the error message using `RunException`.

**Comment by YaqiWang** [comment]
ok, will add one.

**Comment by YaqiWang** [comment]
@friedmud test is added. Looks like all apps are happy with this change...

**Comment by friedmud** [comment]
Cool - when this passes I will merge it.

**Pull request merged**
