### PR TITLE
This adds a j2_plasticity_vs_LSH directory to modules/combined/tests/…

### PR DESCRIPTION
**Pull request by waxmanr**
…, which contains two input files: one for SM LinearStrainHardening, and one for TM j2 plasticity. The setup for the two tests is the same. I added a gold directory, and a tests file for combined/run_tests, but I marked the j2 test as heavy. It passes, but takes quite awhile (as expected).

(I do have plots for the info below, but they didn't get pushed with the rest of the files. Does git ignore images?)

The error with a 4x4x4 mesh is on the order of 1.5e-10 for all normal stress and strain, except stress_zz (which is the direction of applied load). The error for stress_zz is on the order of -3e-5.  (The error here is just a difference, not a percent. stress_zz max at end of run is 240.)

With a 4x4x4 genmesh, alive time for SM LSH is 5.571s, and for TM j2 is 34.213s.

Refs issue #5628.

### CODE REVIEW

**Comment by dschwen** [comment]
Since both tests are more or less a copy of existing tests I'd suggest we set them both to disabled. The purpose of these is to have a common problem for profiling anyways.

**Comment by dschwen** [comment]
@waxmanr you have accidentrally slipped in a libmesh update in your PR now. Can you please remove that.

**Comment by waxmanr** [comment]
Yes, I saw that, sorry. I updated libmesh yesterday. If I force push again, will that go away?

**Comment by dschwen** [comment]
If you ammend your commit. It should (assuming 51d8fff was a downgrade in the first place).

**Comment by permcody** [comment]
Well it won't just go away without you taking some action, perhaps just
rebasing. Take a look at the "stats" for you local commit and if it shows a
"file" in there called "libmesh" (the submodule), then it'll be in your PR
when you push.

$ git log --stat

**Comment by dschwen** [comment]
@waxmanr go ahead and and do

```git reset --hard HEAD^```  to remove c276ff4
Then do
```git reset HEAD^``` (no hard!!!!) to remove 3dbd32b but keep your changes. 
Then do
```git submodule update```
And then add all your changes using ```git add``` (specifying the file names)
Then commit again and push (with -f)

**Comment by waxmanr** [comment]
Thank you, will do. I am rebuilding libmesh again to make sure nothing strange happened. What git was saying didn't make sense to me (probably my misinterpretation). I think `--hard` was the part I was missing. Will fix as soon as the rebuild is done.

**Comment by waxmanr** [comment]
Looks like that fixed it. Thanks @dschwen for the instructions.

**Comment by dschwen** [comment]
Your commit message should be changed. As it stands alone it makes no sense whatsoever. The commit as is adds the comparative tests. There is no trace of either anything libmesh related or of any previous attempts.

**Comment by dschwen** [comment]
Ok, on my desktop in serial I get 4.33s vs. 14.76s. I'll take a closer look at what is going on here.

**Comment by dschwen** [comment]
A large fraction of the cost 10-20% is object creation and destruction due to local std::vector variables.

**Comment by friedmud** [comment]
Has anyone checked that they are taking exactly the same number of iterations?  All of linear iterations, nonlinear iterations, plasticity iterations.

I suspect that TM is simply taking more iterations somewhere...

**Comment by dschwen** [comment]
No significant difference between linear and non linear iterations. Must be
the return map algorithm.

**Comment by dschwen** [comment]
At time 0.06 the system undergoes some kind of transition and the TM solve (return map) starts taking dramatically longer than SM. Before that TM is actually faster than SM. 
Something is definitely fishy.

**Comment by friedmud** [comment]
That's what I suspected.  I knew that TM wouldn't just be 3-7 times slower just due to coding differences.  Had to be something more going on.

Glad you're on the trail!

**Comment by dschwen** [comment]
Dang, ```ComputeMultiPlasticityStress::plasticStep``` isn't even called prior to step 5 (which is when the slowdown starts). So basically TM is only faster when we are in the _elastic_ regime. However the profiling indicates that tensor inverts are _not_ a significant cost here @cpritam (that seems to be good news). I guess we'll have to take a look at how SM does the plasticity step. They must be doing something right where TM does something... well, less optimal.

**Comment by dschwen** [comment]
I've opened an issue at #5667 to discuss there rather than on a closed PR.

**Pull request merged**
