### PR TITLE
final clang format style adjustments

### PR DESCRIPTION
**Pull request by rwcarlsen**
* reflow comments
* set column limit to 100
* allow short funcs on a single line
* align trailing comments

These are some final changes agreed on after much deliberation in the hypercube.

### CODE REVIEW

**Comment by permcody** [comment]
Alright, now to figure out a plan for integration. 

@rwcarlsen, can you at least look on the web and see if anyone has any ideas for preserving line ownership? I thought about it for awhile last night and came up empty. It's a hard problem. I don't love the idea of having a massive maintenance commit but it might be our only option. If you come up with anything let me know. I think we really need a majority buy-in on the path forward here. 

tag @idaholab/moose-team

**Comment by dschwen** [comment]
It might be worth noting that the Chromium project went through the same exercise a few months back: https://bugs.chromium.org/p/chromium/issues/detail?id=563793
Their answer was [`git hyper-blame`](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html). I should probably just get the f$%& over it ;-)

**Comment by permcody** [comment]
Oh, I like that solution! There is at least one other commit way back in the history that I made to delete trailing whitespace. We could add that particular commit to the list as well.

**Comment by rwcarlsen** [comment]
We should choose a bot name and email for the reformat commit - I think an all-at-once update is probably best.  Authorship preservation, as @dschwen intimates, is probably just going to have to depend on tools for looking back past the reformatting.  I'll prepare a PR to CIVET for a clang-format pre-check that fails CI and prints a patch of for style issues.

**Comment by friedmud** [comment]
Saving the authorship history is pretty important to me too... it's always
useful to know who to go to to ask questions as the code gets bigger...

**Comment by jwpeterson** [comment]
> Their answer was git hyper-blame.

I initially thought that was going to be a link to [this](https://git-man-page-generator.lokaltog.net).

**Comment by permcody** [comment]
> I initially thought that was going to be a link to this.

:rofl: Yeah, me too. I actually checked. Can't trust any link from @dschwen 

@friedmud - hyper blame looks pretty good and sounds even more awesome! I really don't think there's a way to preserve authorship because of the way clang-format works. You can't just read the source line by line and reassign because clang-format builds the AST and just rewrites the document completely. The diffs can be all over the place so it's difficult to figure out how to break up the commit into pieces by author like we did for the python reformat.

**Comment by YaqiWang** [comment]
Once the code is formatted, we can let the bot spit out a patch while failing the pre-test, so that the PR writers can apply it on their own. That is basically what we are doing for the banned keywords, trailing spaces, etc. anyway.

**Comment by rwcarlsen** [comment]
So clang ships with a `` clang-format`` subcommand plugin that can print clang-format diffs of the changed parts of a file (e.g. in a PR).  We could try this sort of approach where we have a CIVET check that runs ``git clang-format --diff $(git merge-base HEAD devel)`` and checks for an empty string vs. a printed patch/diff.  This would allow a basically incremental conversion while sort of preserving authorship.  Worth a shot?  I've got a civet pre-check coded up for it already.

**Comment by permcody** [comment]
While I appreciate the effort to reduce churn, our code would look pretty ugly for months being in this weird half-way state. It also wouldn't allow us to just run clang-format on files which is natural. I think I'd rather just "Go Nuts"

**Comment by rwcarlsen** [comment]
I've pushed up some tools for helping rebase/merge across the clang-format everything commit (tweaked version of scripts used in the chromium project migration @dschwen mentioned).  You basically need to run a git hook install script, make sure a special merge driver script is in your PATH and then run the rebase/merge as normal.  The merge driver will clang-format the files in the 3-way merges in every patch being applied to generate the rebase.  I tested it out and it seems to work fairly well.

**Comment by mangerij** [comment]
test fail from ferret unrelated

**Comment by rwcarlsen** [comment]
This needs to be merged so we can make final preparations for the reformat.

**Review by aeslaughter — APPROVED** [review]

**Comment by dschwen** [comment]
Final, really?! This now formats whole initializer lists onto a single line if they fit. Do we want this?

**Comment by rwcarlsen** [comment]
FINAL - it will never ever ever change ever again :-P.  Actually - there is no way (that I am aware of) to put initializer list items always on separate lines.  The only relevant clang option is ``ConstructorInitializerAllOnOneLineOrOnePerLine: true/false``.  So you can either have them "all on one line or one per line" (whichever clang can manage for each particular case) OR you can have them not "all on one line or one per line" - which means clang will always try to pack them on as few lines as possible.

**Comment by permcody** [comment]
@dschwen - I doubt that we'll every have an automatic tool that works exactly like we'd want. Feel free to take this format file and play with it some more. Let's make sure people are on-board with this change as much as possible. I think it'll make code maintenance much easier moving forward.

**Comment by friedmud** [comment]
Sigh: I'm pretty super against anything that requires pre-hooks and
scripts.  The barrier to entry here is going to be high.  Not too mention
the fact that I work across _many_ different machines... and several
different clones of MOOSE... having to get my environment right on each one
sounds like a huge pain.

I don't really know what to do about it though.

The only other option I can see is that CIVET could automatically cough up
a patch that you could download and apply on your fork that would fix your
formatting...

Derek

**Comment by permcody** [comment]
Well nobody says you are going to have to use a pre-commit hook script.
However, it's unlikely that your code will be properly formatted without
it. Having a script in the MOOSE directory that you can just run at any
time that does it for you should remove that burden. We have one of those
now, in fact and people do use it. It's a one time thing and then you never
have to go back and forth with the developers over a ton of incorrect
spacing issues. More seasoned developers will use the editor plugins which
will really remove the burden of managing formats.

I admit I've been dreading this for awhile too. I honestly think it'll make
our workflow better once we rip the bandaid off.

**Comment by rwcarlsen** [comment]
All you have to do is run ``git clang-format upstream/devel`` in the repo to format everything.  Or you can just create a PR and CIVET will print out the diff/patch for changes you need to make.

**Pull request merged**
