### PR TITLE
Set MooseApp level and number during construction

### LINKED ISSUE #9058: MooseApp level should be set during construction
### Description of the enhancement or error report
And should remain constant during the calculations.

### Rationale for the enhancement or information for reproducing the error
Derived `MooseApp` construction could be depending on the level.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Better code structuring. I will send in a small PR shortly.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close  #9058.

### CODE REVIEW

**Comment by YaqiWang** [comment]
I also removed the unnecessary function `setMultiAppLevel`. It will break Rattlesnake, the patch in Rattlesnake is ready.

**Review by permcody — APPROVED** [review]

**Comment by YaqiWang** [comment]
Because this will fail Rattlesnake, and on the other hand, Rattlesnake patch requires this, how should we proceed? Do we need an integration branch?

**Comment by permcody** [comment]
Ugh... I always love these.

We don't need an integration branch but it does require a little
coordination. I merge MOOSE, you fix rattlesnake (with updated submodule).
Then we invalidate app_tests.

Cody

**Comment by YaqiWang** [comment]
Oh, I see. Devel can be temporarily broken.

**Comment by permcody** [comment]
Yes, I will merge when the tests have completed. Then you will update with the new MOOSE submodule (in devel).

**Comment by YaqiWang** [comment]
Should I do the same for MAMMOTH?

**Comment by permcody** [comment]
Yes! I'm merging now.

**Comment by permcody** [comment]
Merging change, requires application patches in Rattlesnake and Mammoth. @YaqiWang - please update.

**Pull request merged**
