### PR TITLE
Remove unused temperature parameter for TensorMechanics action. 

### LINKED ISSUE #17186: Remove unused temperature from TensorMechanics action
## Reason
I'm _fairly_ certain that the `temperature` input parameter for the `TensorMechanicsActionBase` isn't actually used anywhere in that class or its derived classes. As a very new users, this is somewhat confusing as to its purpose (since all the tests still pass a `temperature` in to avoid `--no-warning` failures).

## Design
Remove the `temperature` parameter from `TensorMechanicsActionBase` and update any tests to remove the extraneous info.

## Impact
More straightforward understanding of the action system.

### PR DESCRIPTION
**Pull request by aprilnovak**
Removes the unused `temperature` input parameter for the `TensorMechanicsActionBase`.

Closes #17186

### CODE REVIEW

**Comment by aprilnovak** [comment]
I have the VPN running, but can't seem to actually see the internal app failures (clicking "sign in" via gitlab takes me to ANL's xgitlab, which doesn't accept my INL credentials obviously). 

In any case, I might not have access to all the internal apps that this breaks - but the changes are really simple, just delete the `temperature` line in the `TensorMechanics` action syntax. Help would be appreciated! 

```
[TensorMechanics]
  [Master/all]
      temperature = <temp variable name>
      # ...
  []
[]
```

**Comment by loganharbour** [comment]
@aprilnovak accept the invitation and then give it a try again.

**Comment by aprilnovak** [comment]
I didn't get any kind of invitation - something via email?

**Comment by loganharbour** [comment]
Looks like you auto accepted then. You should be able to see the results if you're logged in using github

**Comment by aprilnovak** [comment]
That works, thanks! So I have access to BISON and can fix that one, but I don't have access to Grizzly.

**Comment by loganharbour** [comment]
I went ahead and just made one. Will ping when it's in

**Comment by loganharbour** [comment]
I think it'll be easier to not remove the parameter yet in the action. Fix the apps first, get this PR in, and then create a separate PR removing the parameter.

**Comment by aprilnovak** [comment]
Ok that works for me - I'll get the BISON PR in tonight

**Comment by loganharbour** [comment]
Actually - I take that back. I wasn't thinking when I posted that previous comment.

Definitely good as is, seeing that we can pre-patch the applications.

**Pull request closed without merging**
