### PR TITLE
speed up jacobian test 

### PR DESCRIPTION
**Pull request by lynnmunday**
-Trying to speed up the test by reducing the number of elements of the plank block by half.  Since the end time was reduced to 5, only half the plank comes into contact with the brick.  The gold files were not changed so the mesh change does not have an effect on the contact.
-Increased num_steps from 2 to 3 for the jacobian test.  The top brick doesn't come into contact with the plank until the 3rd step.... this will make the jacobian test which was failing for time even slower but maybe it will overall be faster with the smaller mesh

ref #15141

### CODE REVIEW

**Comment by lynnmunday** [comment]
@lindsayad @bwspenc Could you review?  I'm not sure how else to make the test faster.

**Review by lindsayad — DISMISSED** [review]

**Comment by lindsayad** [comment]
Hmm @lynnmunday I actually led you astray. Looking more closely at the `PetscContactLineSearch`, the line search will actually be doing stuff even for mortar (hence this new failure you're seeing), but it won't be reading the contact set correctly, resulting in the bad "no nodes in contact" output you've been seeing in the console. Really, the `ContactLineSearchBase` object should get something like a `verbose` param that allows you to turn console printing off.

**Comment by lynnmunday** [comment]
This is back to the original commit.

**Comment by lindsayad** [comment]
Ok the `small-jac` test is still timing out. I'd say put `num_steps=2` on that one. It's ok if it doesn't come into contact. Honestly that's not a great test anyway because of the looseness of the tolerance.

Also, the non-jac test (the `small` test) is on the edge of timing out. If we could coarsen the `small.i` input file like you did with these others, that would be great.

**Review by lindsayad — COMMENTED** [review]
Thank you for this!

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
