### PR TITLE
Remove dirackernels under contact

### PR DESCRIPTION
**Pull request by dewenyushu**
Refs #19391

### CODE REVIEW

**Review by loganharbour — COMMENTED** [review]
I wouldn't suggest taking up time trying to remove lines in `<SomeApp>App`. Missing lines there is okay; you should focus on adding/removing coverage in the application's objects.

While moving something from a source file to a header file technically improves coverage from a numbers standpoint, it isn't improving coverage from a human standpoint of making the app's coverage better.

**Comment by dewenyushu** [comment]
> I wouldn't suggest taking up time trying to remove lines in `<SomeApp>App`. Missing lines there is okay; you should focus on adding/removing coverage in the application's objects.

Thanks! I was simply looking at the coverage report and trying to remove things that are marked as deprecated. But it seems this needs to be done in a more systematic way together with other modules so I reverted that.

It's probably better change the name of this PR as this will mostly be removing the dirackernels under contact.

**Comment by loganharbour** [comment]
> > I wouldn't suggest taking up time trying to remove lines in `<SomeApp>App`. Missing lines there is okay; you should focus on adding/removing coverage in the application's objects.
> 
> Thanks! I was simply looking at the coverage report and trying to remove things that are marked as deprecated. But it seems this needs to be done in a more systematic way together with other modules so I reverted that.
> 
> It's probably better change the name of this PR as this will mostly be removing the dirackernels under contact.

Great, sounds good 👍🏼. In general, you're good to ignore any coverage failures in `src/base` and `include/base` for all apps

**Review by loganharbour — CHANGES_REQUESTED** [review]
Modify the `.coverage` file in the root of the repo to change the required coverage for `contact` to 87%:

```
[contact]
require_total = 87
```

in https://github.com/idaholab/moose/blob/next/.coverage

**Review by bwspenc — APPROVED** [review]
Looks good!  I went back to figure out why these were left behind. It looks like when the deprecated options were removed in the Contact action, the DiracKernels that were set up were not removed. This is good cleanup.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
