### PR TITLE
Add mesh biasing parameters to GeneratedMesh

### PR DESCRIPTION
**Pull request by jwpeterson**
This isn't exactly what we originally were going to do in #6129, but I believe it's the simplest and fastest way for @jasondhales, @RichWilliamson, and @stimpsonsg to get the capability they are after.

I think the idea of implementing a `MeshModifier` that is a wrapper around the more general `MeshTools::redistribute()` function is still a good idea, I just need to think more about what the user interface for that should be...

### CODE REVIEW

**Comment by jasondhales** [comment]
@jwpeterson, will we be able to restrict this to a single block of the mesh?  If so, this looks like it will work great.

**Comment by jwpeterson** [comment]
Well, this only works with GeneratedMesh at the moment, which doesn't normally have multiple blocks... so I guess the answer is no.  

But it would be possible to block-restrict where this MeshModifier runs, e.g. by only moving nodes of Elems which have a particular subdomain id?

**Comment by jwpeterson** [comment]
This won't work yet with quadratic elements... it won't move the mid-edge nodes correctly.  I'll revise it a bit tomorrow to fix that...

**Comment by jwpeterson** [comment]
quadratic_withbias

This shows the mesh biasing working with quadratic elements in the x and y-directions, while the z-direction remains unbiased.

**Comment by friedmud** [comment]
Super cool!

**Comment by permcody** [comment]
:+1:

**Pull request merged**
