### PR TITLE
mooseError changed to mooseWarning in ComputeLinearElasticStress.

### LINKED ISSUE #6782: ComputeLinearElasticStress able to be used with Materials containing strain_increment
### Description of the enhancement or error report

Currently ComputeLinearElasticStress produces an error if it's used with a Material that supplies strain_increment:

mooseError("This linear elastic stress calculation only works for small strains");

### Rationale for the enhancement or information for reproducing the error

However, i do want to use it with ComputeIncrementalSmallStrain, which is a small-strain class that does calculate strain_increment.  So i propose changing from mooseError to mooseWarning

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

I don't think this is a big deal.  Perhaps @dschwen can think of some dramatic impact?

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #6782

### CODE REVIEW

**Comment by dschwen** [comment]
Well... it could get people in hot water if they get an unexpectedly wrong stress based on a wrong strain.

**Comment by dschwen** [comment]
@tonkmr and/or @cpritam should maybe chime in.

**Comment by WilkAndy** [comment]
Somehow we've got to remove this restriction, however we do it.  Just because we calculate incremental strain should preclude using small strain.

**Comment by dschwen** [comment]
Yes, I agree. If the small strain is not valid its material property should simply not exist.

**Comment by permcody** [comment]
Hmm, so what are we doing here? Is somebody changing something? It's a little unclear from the resulting discussion.

**Comment by dschwen** [comment]
Lets hold off on this change until we get more input.

**Comment by cpritam** [comment]
Isn't the error check doing what it should do, i.e., not allowing the use of computefinitestrain with computelinearelasticstress?

**Comment by WilkAndy** [comment]
Yep, the error - checking is doing the correct thing.  However, there is another strain class:

ComputeIncrementalSmallStrain

that calculates small-strain stuff, but ALSO calculates incremental strains, so you cannot currently use that strain calculator with this ComputeLinearElasticStress.

**Comment by permcody** [comment]
Poking all y'all with my stick. This PR is just sitting here like a giant mole.

**Comment by WilkAndy** [comment]
OK, well we don't have to make this change if people don't like it.  @cpritam - please just "close" if you think it's a dumb idea - it's no big deal.

**Comment by WilkAndy** [comment]
What's happening to this GIANT MOLE ?   Just merge or close - i'm not going to get stressed over either!

**Comment by cpritam** [comment]
I thought we decided to close it.

**Pull request closed without merging**
