### PR TITLE
Allow generalized plane strain plane problems to use Abaqus UMAT

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
## Reason
Generalized plane strain problems do not currently work with an Abaqus UMAT material model. Attempting to do so gives an error about missing material properties.

## Design
Jacobian contribution in `GeneralizedPlaneStrainUserObject` requests an elasticity tensor, which does not exist outside UMAT. Using the Jacobian directly seems to work? Does not appear to affect results.

## Impact
Adds capability

Not saying this is the right solution, but it is a solution. Some discussion [here](https://github.com/idaholab/moose/discussions/20867). Also added some tests.

Refs #19249

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
tagging @dschwen @recuero since they worked on the UMAT interface

**Comment by recuero** [comment]
Thanks for the contribution!

It'd be nice to have these tests compare their output to MOOSE's results.

**Comment by jessecarterMOOSE** [comment]
@recuero I've been doing this along the way and I'm happy to report that results compare very well with Abaqus. This is for both 3D and 2D plane strain models. The only thing is that the kinematic formulations are different in MOOSE and Abaqus. I have a branch where I implemented the Hughes-Winget kinematic formulation in MOOSE and when I enable that, the results are dead on! (at least for simple, single-element models)

**Comment by recuero** [comment]
>  Hughes-Winget kinematic formulation in MOOSE and when I enable that, the results are dead on! 

That's great to hear! I'd hope differences are only noticeable for very large deformation or large time steps with respect to rotation increments?

**Review by dschwen — DISMISSED** [review]
👍

**Comment by recuero** [comment]
One recipe is failing. We should probably hold on until we have a fix for that test.

**Comment by jessecarterMOOSE** [comment]
Don't seem to have permission to view the failing tests. 😢

**Comment by dschwen** [comment]
A single layered 1D bison creep test exodiffs a bit. And it has a failed timestep (which it may have anyways). Chances are the test is just not well posed...

**Comment by recuero** [comment]
> And it has a failed timestep (which it may have anyways)

Have you seen that one fail before? It uses generalized plain strain

**Comment by recuero** [comment]
`Jacobian_mult` isn't available at the right time, at least, for some applications using `ComputeMultipleInelasticStress`. This causes time step failures and, for cases that run, can cause an overall slowdown on the order of 20%-25%.

**Comment by recuero** [comment]
The time step gets cut because there are NaNs in the stress tensor.

**Comment by jessecarterMOOSE** [comment]
Is the elasticity tensor available? There are several `Compute*Stress` materials in Tensor Mechanics that do something like `_Jacobian_mult[_qp] = _elasticity_tensor[_qp]`

**Comment by recuero** [comment]
@jessecarterMOOSE when we get #21780 in, after invalidating it, that test should pass. 

That statement (`_Jacobian_mult[_qp] = _elasticity_tensor[_qp]`)  only takes place at nonlinear, but the GPS UO wasn't executed at that stage.

**Comment by recuero** [comment]
@jessecarterMOOSE can you please rebase off next and push again?

**Comment by jessecarterMOOSE** [comment]
ok done

**Comment by recuero** [comment]
Internal apps already passed. We should be good to go.

**Review by dschwen — APPROVED** [review]

**Comment by jessecarterMOOSE** [comment]
:+1:

**Pull request merged**
