### PR TITLE
Implementing rho_e_dps() in stiffened gas EOS

### PR DESCRIPTION
**Pull request by andrsd**
Refs #7934

### CODE REVIEW

**Comment by permcody** [comment]
Test case?

**Comment by andrsd** [comment]
All this SGEOS stuff started in RELAP and there are tests for it in form of unit tests. Then we moved the code into a module, but the tests stay in RELAP. If we can we do unit testing on module basis, I'd move the tests here as well.

**Comment by permcody** [comment]
moose_unit does compile in the modules so you should be able to move them now. We currently don't have the capability to split them up per module but at least we have a "combined" unit test.

**Comment by andrsd** [comment]
Ok, thanks. I will move the unit tests in another patch within this PR.

**Comment by andrsd** [comment]
@cpgr I added some unit tests for fluid properties in this PR. You may want to look at the code. It might be useful for your fluid properties classes if you want to drop those test materials but still tests the object by itself...

**Comment by andrsd** [comment]
I saw some warnings in the `fluid_properties`, so let me fix those as well ;-)

**Comment by permcody** [comment]
Already did:
https://github.com/idaholab/moose/pull/7969

**Comment by andrsd** [comment]
> Already did:

Ok, thanks.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
