### PR TITLE
Fix Doxygen errors, update Doxyfiles, repair Mathjax equation display

### LINKED ISSUE #5726: LaTeX formulae don't render in Doxygen docs on mooseframework.org
The Mathjax path is set wrong.

### PR DESCRIPTION
**Pull request by dschwen**
This updates the doxy comments to remove the `name` parameter that was removed in the constructor update, fixes a few other parameter name types, properly escapes LaTeX in some comments, updates the Doxyfiles to get rid of deprecation warnings, and removes a warning about redundancy in including tabs.css.

Closes #5726

### CODE REVIEW

**Comment by dschwen** [comment]
This passed before I fixed the commit message of the last commit. Should be ready to merge.

**Comment by permcody** [comment]
Sure..., We've all heard that one before...

**Comment by dschwen** [comment]
> All checks have passed
> 5 successful checks

In your face @permcody !

**Comment by dschwen** [comment]
There are some problems in modules left that I should fix, too.

**Comment by dschwen** [comment]
Ping @WilkAndy. 64edf6d adds the use of ```@param[in]```, ```@param[out]```, and ```@param[in,out]``` to your plasticity documentation. You used plain text comments for that, but Doxygen has a syntax for this, and it seems important for that particular system with the function taking gazillions of arguments by reference.

**Comment by WilkAndy** [comment]
Thanks heaps @dschwen , what a lot of work you've kindly done on my behalf.  Those doxygen comments are super useful in such an ugly piece of code.

**Comment by dschwen** [comment]
Ok, I'm done with this. I've eliminated almost every single Doxygen argument warning.

**Comment by jwpeterson** [comment]
Wow, looks like the Doxygen was only errors.

**Comment by WilkAndy** [comment]
Will doxygen tests be part of the automatic test suite now?

a

**Comment by permcody** [comment]
Doxyfiles are normally committed they are generated from Doxygen, but then they are intended to be customized for your project and committed. Like Daniel said, somebody could make a new python project to customize the generated files as a step in building the Doxygen pages... Yay! more Python projects!!

**Comment by dschwen** [comment]
We could also just use ```patch``` to change the generated Doxyfiles, _but_ that entails the risk of failing inf Doxygen again changes the contents of the autogenerated Doxyfiles.

**Comment by jwpeterson** [comment]
> Doxyfiles are normally committed they are generated from Doxygen, but then they are intended to be customized for your project and committed.

True, but we don't necessarily need to have N copies of it, where N is the number of MOOSE modules...

**Pull request merged**
