### PR TITLE
Reworked internal variables in LinearViscoelasticityBase

### LINKED ISSUE #11496: Access to LinearViscoelasticityBase internal variables
## Rationale

Several material properties in LinearViscoelasticityBase are defined as `MaterialProperty<std::vector<RankTwoTensor>>` or `MaterialProperty<std::vector<RankFourTensor>>` which makes it impossible to access them for post-processing purposes. This makes validation or testing of new viscoelastic models particularly difficult.

## Description

These properties should be defined as `std::vector<std::reference_wrapper<MaterialProperty<T>>>` instead, with each element in the vector being given a separate name. This would allow the use of `RankTwoAux` and `RankFourAux` to extract values from these properties.

## Impact

Improved output capabilities for viscoelastic materials. Some internal changes in `LinearViscoelasticityBase` and derived classes.

### PR DESCRIPTION
**Pull request by agiorla**
- Material properties that were defined as `MaterialProperty<std::vector<T>>` are now `std::vector<std::reference_wrapper<MaterialProperty<T>>>` and can therefore now be accessed via `RankTwoAux` or `RankFourAux`
- One `MaterialProperty` that was a duplicate from `ComputeElasticityTensorBase` has been removed.

closes #11496

### CODE REVIEW

**Comment by agiorla** [comment]
That's forced by the use of the `std::reference_wrapper`. There are other ways to do it: using pointers (but I think having references makes more sense), having internal access methods (but in the end, that would be similar has having that get() in the middle), or having a specialized container with appropriate overloaded operators (but that is quite some work and I'm not sure it makes sense to do that just for this set of classes).

**Comment by agiorla** [comment]
Tagging @bwspenc @saklaninaman

**Comment by bwspenc** [comment]
Overall, I think it looks good. We just need to resolve the issue that @friedmud raised.

We typically vectors of pointers to material properties, rather than vectors of references in situations like this. See for example `_eigenstrains` in `ComputeStrainBase`:
https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/include/materials/ComputeStrainBase.h
The syntax for accessing those is also a little ugly:
```
(*_eigenstrains[i])[_qp]
```
vs
```
_eigenstrains[i].get()[_qp]
```
if we were to use `std::reference_wrapper`, as @agiorla is proposing. I don't see any use of `std::reference_wrapper` in MOOSE. Storing them as pointers would follow our current precedent. 
@friedmud -- would you prefer we use pointers instead?  @permcody --thoughts? I don't have a strong preference either way.

**Comment by friedmud** [comment]
I would vote for pointers... that's how we do this all over the framework.

Not sure this is worth introducing a new C++ concept to the framework.

**Comment by bwspenc** [comment]
@agiorla I think the consensus here is to go with pointers. If you just go through and swap those all out for pointers, this should be good to go.

**Comment by agiorla** [comment]
Sure we can use pointers, no problem. I'll change that and prepare the patch for BlackBear in the process. Thanks all.

**Review by bwspenc — APPROVED** [review]

**Comment by bwspenc** [comment]
This makes an API change that breaks BlackBear (and Grizzly). The changes on the BlackBear side are ready, so I'm merging this.

**Comment by agiorla** [comment]
Thanks @bwspenc

**Pull request merged**
