### PR TITLE
suppress clang -wpedantic warning in from boost 

### PR DESCRIPTION
**Pull request by lynnmunday**

### CODE REVIEW

**Comment by lynnmunday** [comment]
@aeslaughter @dschwen      Will you review this?   Do you add reviewers by putting their name in a comment?

**Comment by lynnmunday** [comment]
if this passes, it closes ref #15157

**Comment by permcody** [comment]
@lynnmunday - which target are/were you seeing the warnings? With all this conda stuff, I'm not sure were to look now.

**Comment by dschwen** [comment]
Does `-Wall` ignore pedantic warnings? @lynnmunday suggested changing `-I` to `-isystem` for the boost includes to more naturally drop all warnings. Another option would be to investigate if newer boost versions are cleaned up to remove these warnings.

**Comment by lynnmunday** [comment]
@permcody Ben noticed that the Grizzly debug compile output was full of boost warnings that are created from stochastic_tools where it includes boost.  We get warnings like this:

275:2: warning: non-standard suffix on floating constant [-Wpedantic]
  275 |   BOOST_DEFINE_MATH_CONSTANT(ln_ln_two, -3.665129205816643270124391582326694694e-01, "-3.66512920581664327012439158232669469454263447837105263053677713670561615319352738549455822856698908358302523045e-01")
      |  ^

**Comment by lynnmunday** [comment]
I tried -Wall because Ben and Google said -Wpedantic doesn't suppress the warnings but I don't know if it works or not because I'm not building grizzly debug here.  @bwspenc is going to try changing -I to -isystem to see if that works

**Comment by permcody** [comment]
@dschwen - if we get BOOST through package managers, which we do with Conda and cluster systems, we may not be able to tightly control versions. I'm fine with blanket ignoring warnings for BOOST in general. I just want to make sure we have the right syntax and that it's working before we merge.

**Comment by lynnmunday** [comment]
I'm closing this because it is fixed by the libmesh.

**Comment by lynnmunday** [comment]
This wasn't really fixed through libmesh so I made a new pr.

**Pull request closed without merging**
