### PR TITLE
Postprocessor MassTensors and tests Refs 

### PR DESCRIPTION
**Pull request by sapitts**
This commit replicates the solid mechanics post processor Mass in tensor mechanics as MassTensors.  Tests in both the solid mechanics and tensor mechanics are retained during this transition process, and a new set of tests for tensor mechanics was created in the combined module.  To mitigate the test duplication, additional test specifications are introduced with the cli_args option to complete the full variation of tests in the x, y, and z directions where appropriate.

Additional post processors exist in solid mechanics and will need to be migrated to tensor mechanics, but I wanted to run the formatting and the test file cli_args modifications past folks in a smaller commit.

Refs #6484

### CODE REVIEW

**Comment by dschwen** [comment]
Wait a minute, I think we had a case where we added the `*Tensors` variant before: `GravityTensors`. And we ended up reverting this. Let me check what happened there before we merge this.

**Comment by dschwen** [comment]
Yep, that was undone in (#5624). Please let's not go down the duplication path again.

**Comment by sapitts** [comment]
I think I see what Swetha and Cody did to avoid duplicating the boundary conditions by having solid mechanics depend on tensor mechanics--since the Mass code is exactly the same, this change shouldn't upset apps, fingers crossed.

@dschwen would you be in favor of eliminating the solid mechanics tests entirely for the new tensor mechanics tests after moving these post processors into tensor mechanics?  @friedmud mentioned in the issue that having tests for all code is key, but if we have only a single version of the [post processors ](https://github.com/idaholab/moose/tree/devel/modules/solid_mechanics/src/postprocessors)(Mass, ect), then having a single set of tests ought to not create any problems.

In either case, these post processors will need to be moved from solid mechanics to tensor mechanics, and I appreciate your advice on how best to accomplish the migration without disrupting the apps.

**Comment by dschwen** [comment]
Yes, a single set of tests should be fine. There should not be a disruption to apps at all.

**Comment by sapitts** [comment]
Okay, I'll close this PR and make a new one.  I'm leaving the issue open for now.  Thank you for the help.

**Pull request closed without merging**
