### PR TITLE
[WIP] supporting scalar variables in miscellaneous objects

### PR DESCRIPTION
**Pull request by lindsayad**
We'll start by focusing on mortar constraints and then we can move to other objects as @ttruster desires

### CODE REVIEW

**Comment by lindsayad** [comment]
@ttruster this is a PR where I'll be working on trying to help you out. We can collaborate on this

**Comment by lindsayad** [comment]
So I've restored the scalar-field Jacobian terms ... but they are wrong. I can work on making sure the terms get added but you'll need to make sure they're being computed correctly. Going to work on the field-scalar terms now.

**Comment by lindsayad** [comment]
Ok @ttruster I now have all the coupling entries in the Jacobian. It looks like the only Jacobian rows that are incorrect now are the scalar Jacobian rows (although all the entries are there). Can you take a look and see if you can fix up those computations? If so, I feel like we have a good indication that we make all this coupling work with our standard assembly APIs

**Comment by ttruster** [comment]
Thanks @lindsayad, I was out on business travel yesterday and today. I'll pull down the changes tomorrow/Friday and check through the Jacobian terms in my constraint routines.

**Comment by ttruster** [comment]
@lindsayad, sorry for my ignorance, but this is my first time working on a PR. I have my forked repo cloned on a Ubuntu 18.04 Linux box where I coding and have the main INL repo as a remote called 'upstream'. I use SmartGit for my git actions, though sometimes I use the termina as well; I compile from the terminal.

When I "Fetch" with Smartgit, I'm only seeing eight branches from upstream: devel, master, next, and some older ones. How do I also fetch the code from your PR commits?

10 minutes searching didn't give me the protocol. Should I install 'gh' desktop for Linux? Or are there some references you can point me toward? GitHub only describes the creating/viewing for their Desktop GUI.

**Comment by lindsayad** [comment]
In the terminal, I would do
```
git remote add lindsayad git@github.com:lindsayad/moose.git
git fetch lindsayad
```
And then you should be able to see the commits I've put on top of your `non-working-scalar-in-mortar` branch. This also assumes you've added ssh keys on github. If you haven't, then change the first command to
```
git remote add lindsayad https://github.com/lindsayad/moose
```

**Comment by ttruster** [comment]
I was able to link your remote, fast forward the changes into my repo local branch, compile and run it. Then I shortened my constraint routines to remove the 'Stab' wrapping functions, and confirm I still get the same answers.

That makes it easier to look at, and I'm rather confident in the expressions for R and J; I looked at the signs a few times for secondary/primary.

What I think the issue is, is about how I hacked the residual assembly. Namely, _fe_problem.addResidualScalar();

When I print out the residual vector, on a 2x2 mesh (I changed the file to 3x3 in the commit because I'm trying to compare with my Matlab FEA code and having trouble since I only have this formulation in elasticity and not diffusion in my other code), then the initial values for the 2 scalar variable residuals are:

1.4000000000000000e+01
6.0000000000000000e+00
];
Since the same value is prescribed in kappa-aux for both components (x and y), then the values should be the same because the domain is square, and I am integrating `r -= dx(_h) * (kappa_aux_vec * _normals[_qp])` which should be 2.0 on horizontal edge and 2.0 on the vertical edge.

Instead, this difference makes me think that some value is being stored/cached multiple times into the scalar residual. Think about it: if I'm integrating the vertical edge first (normal = [1 0 0] and boundary = primary_right; yep, the input file lists this constraint first), then the 2 vertical elements could somehow add `2 + 2*2 = 6` first, and then the same value gets added 2 more times `2*2 + 2*2 + 6 = 1.4e+01`. Meanwhile, the horizontal edge is processed second and just sees `2 + 2*2 = 6.0e+00`.

That is my rational explanation for the odd initial residuals. Meanwhile, the "exact" solution of macro gradient kappa = kappa-aux still falls out of the solution process since the other part of the residual is `dx(_h) * (_pen_scale * _tau_s) * (kappa_vec * dx);`, where dx happens to be parallel to normals[qp], and the SAME extra additions of the residual would happen to that term too, so they cancel each other out.
Meanwhile, if the Jacobian is cached correctly and only happens once, then It won't be 'right'.

Well, I tried hacking the residual with some factors, and it didn't work.
So you'll see these couple ideas within the commits in my repo (is that the place to put them?). Let me know your thoughts on how to get the residual assembly to be proper as well.

**Comment by lindsayad** [comment]
Putting commits on your branch is great as I can easily pull them. I'll take a look into the residuals now!

**Comment by lindsayad** [comment]
When I monitor the residual using `-snes_monitor_residual`, the scalar residuals look like they are 2
```
 0 Nonlinear |R| = 2.828427e+00
Vec Object: 1 MPI processes
  type: seq
0.
0.
0.
0.
0.
0.
0.
0.
0.
2.
2.
```

**Comment by lindsayad** [comment]
All this Jacobian debugging stuff is exactly the reason we added the AD system...

**Comment by lindsayad** [comment]
Ok my most recent commit shows an accurate Jacobian leveraging some AD. You should be able to leverage similar `Assembly` API calls when you move back to hand-coded

**Comment by ttruster** [comment]
The hand-coded Jacobian version now works. I didn't have to change any formulas, just had to remove the 'hack' factors that I put in to try and adjust the residual assembly issue. Copying the `Assembly` API resulted in the proper convergence.

I renamed the files to have a regular and an AD version, and made a separate input file for each one. I get convergence in one iteration for both of those. It was quick to know that the old Jacobian terms were okay because I had dumps from the -mat-view for the previous commits, and I could get the -mat-view of the AD global matrix and all the values were identical.

Now I goofed up with commit histories in Smartgit because I first committed onto your branch locally, which won't push to mine. I messed around deleting branches and ended up renaming the branch to 'not-working-scalar-mortar' accidentally. That is where the current tip/head is for my changes.

**Comment by ttruster** [comment]
Do you want me to quickly make a Lagrange Multiplier version of the PBC and add it to the `EqualValueConstraint` in an input file? I would use the AD again to hopefully get it easily. That way we can check Lower assembly also.

**Comment by ttruster** [comment]
Sorry, forgot one other idea. I noticed that we are getting `MortarConstraint` and base class cleaned up also, removing some of the other stub calls. I could create a wrapping class, similar to the one for Kernel (in test folders, i.e. `KernelScalarBase`), that provides the integration and assembly routines for the scalar variables. Then the mortar-with-scalar objects could derive from that, while the existing mortar objects could derive from a clean `MortarConstraint`.

The way we've got it written currently, the only real change is to remove the `_compute_scalar_residuals` flag (defaults to false) from the base class and all the void function calls. What would go in the new `MortarConstraintScalar` class is an override of the `computeResidual` and `computeJacobian` methods to add expanded methods that first call the base one as well as routines for  scalar quadrature loop and assembly. (Pure) virtual classes for Qp computations are provided which are then implemented in the derived class, for which this `TestPeriodic` could be renamed to `PenaltyPeriodicMortarConstraint` or whatever we want to call it and have it added to the framework as a sample of how to couple mortar and scalar variables.

**Comment by lindsayad** [comment]
> Do you want me to quickly make a Lagrange Multiplier version of the PBC and add it to the `EqualValueConstraint` in an input file? I would use the AD again to hopefully get it easily. That way we can check Lower assembly also.

That sounds good.

> What would go in the new `MortarConstraintScalar` class is an override of the `computeResidual` and `computeJacobian` methods to add expanded methods that first call the base one as well as routines for scalar quadrature loop and assembly. (Pure) virtual classes for Qp computations are provided which are then implemented in the derived class, for which this `TestPeriodic` could be renamed to `PenaltyPeriodicMortarConstraint` or whatever we want to call it and have it added to the framework as a sample of how to couple mortar and scalar variables.

This all sounds great to me. Once you do that, why I don't you submit your own pull request to MOOSE and then I will close this one. The advantage of you submitting the pull request is that as a maintainer I can push directly to your pull request if need be.

**Comment by ttruster** [comment]
I finished making the source for the wrapper class for scalar assembly of mortar constraints in my forked repository on a new branch, `mortar-scalar-assembly`. So I guess that one is ready to try opening a pull request to continue working on some of the other components.

Should I just follow the GitHub steps for opening a pull request, or should I do some preparation first? I had attempted to run a git fetch and git rebase upstream/devel, but then the code no longer compiled and gave some errors in the utils/tensors classes. I have never used rebase before (I'm self-taught on version control and used hg until that got phased out to git), so I might have done it wrong. Also, I haven't run the scripts yet that are supposed to format the file, like removing spaces at ends of lines. I'm using VSCode.

**Comment by lindsayad** [comment]
We have a Contributing page [here](https://mooseframework.inl.gov/framework/contributing.html). The compilation errors you mention could be due to having an old libMesh copy. You may just need to update your libmesh

**Comment by ttruster** [comment]
@lindsayad: I have figured out with help of @reverendbedford how to open a PR. The issue was, I had first forked into my personal account, then opened a group/lab account and moved the repo over to the group. That broke the fork linkage. So, with a new fork in the lab, and a couple more commits to make the Precheck pass, the new PR is now open at https://github.com/idaholab/moose/pull/22376.

**Comment by lindsayad** [comment]
Great! Closing in favor of #22376

**Pull request closed without merging**
