### PR TITLE
Re-enable multiple mortar contact action blocks capability 

### PR DESCRIPTION
**Pull request by recuero**
Refs #21329

This issue was reported separately by @sapitts and @tophmatthews.

### CODE REVIEW

**Comment by recuero** [comment]
This PR should be ready for a review.

**Review by dschwen — APPROVED** [review]
Do you use `contact_userobject_counter` after this PR?

**Comment by recuero** [comment]
For NodalArea. But we may be able to use the name() to disambiguate since it's already passed the vector of boundaries of the particular contact action object.

**Comment by tophmatthews** [comment]
Awesome, thanks for the quick fix!

**Pull request merged**
