### PR TITLE
Some cleanups in MooseVariableFE for ArrayKernel

### PR DESCRIPTION
**Pull request by YaqiWang**
I think this cleanups can stand by themselves. I push this before I even finish a compilable re-implementation of ArrayKernel (#6881) of @friedmud 's #7586 because I want to reduce the later burden of reviewing and do not want to resolve potential conflict later on. This should be relevant with @lindsayad.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Note: I have `+417 −671` in the PR.

**Comment by YaqiWang** [comment]
The last commit is an attempt to fix errors in grain tracker stuff in phase field module but not successful so far. @permcody do you have any thoughts on the error? What I changed in this PR is that fetching the DoF values based on request. The last commit can avoid crashes but give errors like
```
Error: New grain detected and "error_on_new_grain_creation" is set to true
```
and exodiffs. Need more time to look into it.

**Comment by permcody** [comment]
Well the GrainTracker definitely changes solution values between solves. The error you are getting is likely because whatever you are doing there just isn't working yet! Maybe some of the values got rewritten, or perhaps none of them did. If the solution gets messed up, all bets are off as to what the GT will see the next time it gets executed. The "new grain" thing just means that something went wrong. That particular method is where everything is bottled up. You should be able to "swap values" or more generally just change values of coupled variables.

**Comment by YaqiWang** [comment]
The last commit should have fixed the grain tracker. But I do not quite understand why my first attempt did not...

**Comment by YaqiWang** [comment]
This is ready for review.

**Review by lindsayad — APPROVED** [review]
This looks good to me. I appreciate the code reduction

**Pull request merged**
