### PR TITLE
Convert NS kernels to use default coupling system

### LINKED ISSUE #5959: Segmentation fault when using displaced mesh with NS kernels
Hi,
I'm working on a Navier-Stokes simulation in a granular rock matrix that looks at the effects of grain's dilation on permeability (calculated with Darcy's Law).

I use the variables disp_x and disp_y to make my grains swell but Navier Stokes flow is not affected by the swelling!
undisplaced_simulation
displaced_simulation
Although the velocity should increase in the channels that are tightening.

I figured out that I have to put in my Mesh block: displacements = 'disp_x disp_y'
and put in everything that operates spatially: use_displaced_mesh = true
In my input file, it means BC, Kernels and Postprocessors.

But when I turn everything on, I got a segmentation fault.
So I tried to localise the problem and realise that the only things that are not working with use_displaced_mesh = true are the Navier Stokes kernels.

For an example of usage, you can follow my post on the mailing list:
https://groups.google.com/forum/#!topic/moose-users/KvJZvdritew

Cheers,

Martin Lesueur

### PR DESCRIPTION
**Pull request by aeslaughter**
Without this change these kerenls seg. fault in 2D, the _grad_w_vel is not size properly with _qp (_grad_w_vel.size() = 0). I am not sure why this happens, but using the default system fixes the problem.

(closes #5959)

### CODE REVIEW

**Comment by andrsd** [comment]
Using `_mesh.dimension()` is wrong when we'd use the kernels on lower-dimensional elements in higher dimensional space.
In 2D, `_grad_w_vel` should be using `_grad_zero`. If that is not sized properly, it means MOOSE does not size `_grad_zero` when it should. This fix would just hide the problem you just discovered/fixed.

**Comment by aeslaughter** [comment]
@andrsd agreed this does just put a band-aid on the problem. FYI, for this problem `_mesh.dimension()` was reporting 2. I will investigate why _grad_zero is not being sized.

**Comment by jwpeterson** [comment]
So, is this still the band-aid solution or did you figure out there was a real bug?

**Comment by aeslaughter** [comment]
This fixes the real bug. The _zero stuff was stored on SubProblem so both
FEProblem and DisplacedProblem had zero storage; however, only the one on
FEProblem was properly initialize. So, when using _zero with displacements
things went bad. This moves the zero storage to FEProblem only.

**Comment by jwpeterson** [comment]
Sounds good to me.

**Pull request merged**
