### PR TITLE
Adding reserve op capability to grain tracker

### PR DESCRIPTION
**Pull request by permcody**
A new flag allows users to reserve an op that will not
be used as a destination variable during remapping. This
variable is intended to be used for nucleation events.

refs #7367

@karim86, @dschwen, This is all it takes to stop the grain tracker from mapping to a variable. It's not quite finished because I believe that the goal is to force grain tracker to move grains out of that variable on demand, or perhaps as soon as we can. I'm just putting this up so you can see where this is at. If this looks good, I'll work on forcing the grain tracker to move grains away too.

### CODE REVIEW

**Comment by permcody** [comment]
@dschwen what would you like the API to be for getting the information we discussed (ops to grains)?

**Comment by dschwen** [comment]
For a given element I'd like to obtain a vector _num_op_ long that contains the grain number associated with each OP.

**Comment by permcody** [comment]
@dschwen - this PR is already done. I think I'll open a different ticket to handle your new API request. It's independent of this reserve op capability.

**Comment by permcody** [comment]
See #7373

**Pull request merged**
