### PR TITLE
PETSc env variable treatment disambiguation

### LINKED ISSUE #27798: Confusion around compiler environment variables and petsc configure in offline instructions
### Motivation

We need to make clear that our petsc build script (and petsc configure) itself does not honor compiler environment variables

### Design

Clarify documentation

### Impact

More clarity for users

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #27798

### CODE REVIEW

**Comment by lindsayad** [comment]
FYI @prj-

**Review by cticenhour — APPROVED** [review]

**Comment by jessecarterMOOSE** [comment]
@lindsayad I'm going through this now and saw you added compiler options (--CC, etc.) to the petsc build and configure script, but you only did it for the _first_ call to the script where it just prints out the external packages and quits. Do those compiler options also need to be supplied when you actually configure and build on the offline machine?

**Comment by lindsayad** [comment]
Yes they do. That PR missed the later `update_and_rebuild_petsc.sh` invocation

**Comment by lindsayad** [comment]
Do you want to make a PR fixing that or do you want me to?

**Comment by jessecarterMOOSE** [comment]
I'll take a look. I'm going through the process now and may have other suggestions

**Pull request merged**
