### PR TITLE
Improve NearestNodeTransfer fixed_mesh test

### PR DESCRIPTION
**Pull request by smharper**
The test for `fixed_meshes` with `MultiAppNearestNodeTransfer` currently only checks for runtime errors; it doesn't ensure that `fixed_meshes` actually produces the expected results.  In other words, you can completely remove the `fixed_meshes` code and still pass the test.

This PR modifies the subapp in the test so that it moves with time.  This version of the test will fail if the transfer actually recomputes the nearest neighbors at every time step.

### CODE REVIEW

**Comment by friedmud** [comment]
Sneaky idea - I do like it.

My only issue is that this means that this test is NOT a very good example for people to follow - because it is doing something really weird by saying `displaced_source_mesh = true` AND `fixed_meshes = true`.  In fact, I personally feel like that combination should be an error!

Would you mind adding some comments for the `displaced_source_mesh = true` lines to explain the situation?

**Comment by smharper** [comment]
I've added the comment as requested.

I'm not sure that `displaced_source_mesh = true` and `fixed_meshes = true` should cause an error.  I can imagine a situation where we have displacements but they are so small that the user would prefer the speed of `fixed_meshes = true` over a small accuracy gain.  For example, transferring clad temperature to a flow channel with thermal expansion on the clad.  Maybe we should rename `fixed_meshes` to `small_displacements`.

Actually, now that I'm thinking about it, do you think we should always set `fixed_meshes = true` internally when `displaced_source_mesh = false` and `displaced_target_mesh = false`?  The only downside would be memory for the nearest node cache, and that's probably small.

**Comment by permcody** [comment]
Another case is Relap-7. We may want to use `fixed_meshes = true` but we
are also forced to use displaced mesh depending on the direction of the
transfer.

**Comment by smharper** [comment]
Actually I guess in the example I mentioned you just wouldn't use `displaced_*_mesh`.  But there is also the case where you have a significant displacement at timestep 0 that then doesn't change much.  Then maybe you'd want both `displaced_*_mesh = true` and `fixed_meshes = true`.

**Comment by friedmud** [comment]
Yeah: I wasn't actually suggesting that we make it an error... just saying that it feels wrong ;-)

The comments you added are good... so :+1:

**Pull request merged**
