### PR TITLE
Cache property name and return by reference

### LINKED ISSUE #13570: DerivativeParsedMaterial start-up performance issues
## Bug Description
 I have identified two bottle necks in the startup (differentiation phase) if DerivativeParsedMaterials. One takes 26.6% of the entire derivation time, and one takes 68.3%. Both involve an unnecessary amount of string operations that I may be able to trim
down considerably.

## Steps to Reproduce
Run a simulation with DerivativeParsedMaterials that use lots of material properties that are provided by DerivativeParsedMaterials themselves (chain rule).

## Impact
Performance improvement.

### PR DESCRIPTION
**Pull request by dschwen**
...instead of rebuilding the name each time and returning as a copy. Please hold off on merging until I can confirm the performance impact in a profiler.

Closes #13570

### CODE REVIEW

**Comment by dschwen** [comment]
Pre-test failure:

```
//: Using moose-environment release: 
cat: /home/moosetest/singularity/bind_paths/release_binds/Ubuntu-16/PR-_Ubuntu-16/moose/build: No such file or directory
//: Release:  opt/moose bind points not available
//: rm -rf /home/moosetest/singularity/civet_map_path/Ubuntu-16_13572_3e42002e406d0213ebd3326bc0ee489121824088
```

**Comment by permcody** [comment]
So moosebuild swears? Bad MOOSE, Bad MOOSE!

**Comment by dschwen** [comment]
I'm pretty sure the failure to build teh *workshop* materials

```
/tmp/tmpzzZIBP: line 52: ./moosedocs.py: No such file or directory
```

has nothing to do with my PR.

**Comment by permcody** [comment]
Correct - blame @aeslaughter. Invalidating it will fix it!

**Comment by dschwen** [comment]
Ok, this is good to go. It reduced one offender from 26% of startup time to below the noise level.

**Review by permcody — APPROVED** [review]

**Pull request merged**
