### PR TITLE
(AD/nonAD)-ified NeumannBC & MatNeumannBC

### LINKED ISSUE #18442: add ADMatNeumannBC
## Reason
There is a non-AD version of `MatNeumannBC` exists. Sometimes an AD version is needed.

## Design
Duplicate `MatNeumannBC` as an AD version.

## Impact
More options for BCs.

### PR DESCRIPTION
**Pull request by tophmatthews**
Closes #18442

### CODE REVIEW

**Comment by dschwen** [comment]
We just merged https://github.com/idaholab/moose/pull/18248 which provides `GenericIntegratedBC<is_ad>`. It would be really nice if you could just change the existing MatNeumannBC to use that instead...

**Comment by tophmatthews** [comment]
Ah! I was looking for an example, but couldn't find one, that's why I separated it. I'll take a look at that pr.

**Comment by tophmatthews** [comment]
Does a second AD*.md file need to be put in?

**Comment by tophmatthews** [comment]
Thanks for pointing out #18248 @dschwen, ready for review.

**Review by dschwen — APPROVED** [review]
Beautiful

**Pull request merged**
