### PR TITLE
Replace the mooseError with MooseException in FiniteStrainUObasedCP

### PR DESCRIPTION
**Pull request by jiangwen84**
In Crystal plasticity material class, mooseError is called to stop the simulation when the constitutive law is not satisfied. Replacing the mooseError with mooseException will allow moose to cut the time step and continue the run.

close ref #10132

### CODE REVIEW

**Review by permcody — COMMENTED** [review]
Any chance you can come up with a test? It'd be nice but I know they are difficult to come up with.

**Comment by jiangwen84** [comment]
@permcody I added one test for this PR. I increased the initial dt and the loading to fail the material solve. Then dt will be cut and the simulation will continue till the end.

**Comment by jiangwen84** [comment]
@permcody I was not sure why the test failed in debug mode. On my local machine, it will have *** warning *** but, on civet, it becomes ***error ***? any suggestions? thanks.

**Comment by permcody** [comment]
That's because we run individual modules on CIVET, which have the "--error" flag turned on. When you run on your desktop you probably use the top-level .run_tests in the modules directory which allows warnings (maybe it shouldn't). The fix is simple, if you really do have a desired warning in your test. Simply add "allow_warnings = true" to the test spec file and it'll allow them.

**Review by permcody — APPROVED** [review]

**Pull request merged**
