### PR TITLE
Use -Wall -Wextra by default

### PR DESCRIPTION
**Pull request by brianmoose**
Just added the flags to all the Makefiles so they are used when doing moose development.

Note that the flags won't get set if someone builds moose within their app. If this is the desired behavior then I will have to figure out how to add the flags for just the moose objects.

refs #10733

### CODE REVIEW

**Comment by brianmoose** [comment]
Looks like 3 problems:
1. Trilinos: Turning on `-Wall -Wextra` produces some extra warnings in the DTK headers (comparison between signed and unsigned and an inheritance warning). The DTK headers are already guarded with `libmesh/ignore_warnings.h` and `libmesh/restore_warnings.h`. `ignore_warnings.h` only turns off some warnings, I guess these could be added to the list.
2. Minimum clang version testing:  Looks like `ignore_warnings.h` turns on `-Winconsistent-missing-override` which isn't a valid warning on the older clang. It usually warns about it but now they are errors. Probably just need a clang version check in `ignore_warnings.h`
3. Minimum gcc version testing: Looks like the older gcc warns about unused variables when defining global constant variables (in `utils/MooseTypes.h`)

**Comment by brianmoose** [comment]
1. The Trilinos problem will be fixed by updating to a new moose environment package that uses `-isystem` on the trilinos include dir. Seems to remove all the warnings
2. Minimum clang version warnings are fixed by #10934
3. Minimum gcc version warnings were fixed by #10892

**Comment by brianmoose** [comment]
The last remaining error is in trilinos. We updated the package so that most of the trilinos warnings went away (by using -isystem for trilinos directories) but it appears that both libmesh and dtk both define `NANOFLANN_VERSION`. They define it to different values so I am not sure what a good fix would be. They are in different namespaces but that doesn't matter for `#define`

Anyway, I don't really think having `-Werror` turned on by default is a good idea since we don't know what compilers people will be using and it can be incredibly annoying.
Leaving `-Wall -Wextra` turned on might be fine though.

**Comment by permcody** [comment]
Hmm, I can agree that we don't want -Werror on for everyone, but we also DO
want to error for MOOSE and the framework where things are more controlled.
Maybe we could consider turning it on for just specific compilers and/or
specific locations such as MOOSE and perhaps the modules eventually. Even
starting with the build system compiler version and our Mac compilers
combined with the MOOSE directories would be a huge improvement.

**Comment by brianmoose** [comment]
I was just thinking that civet would turn on `-Werror` but it wouldn't be on by default in the moose Makefiles but `-Wall -Wextra` would be. Then people would at least be able to see the warnings and fix them easily but it would never stop people from building.
These flags are already limited to framework/test/modules. My concern is things like trilinos, boost, etc that people might use with moose and they suddenly can't build moose due to `-Werror`

**Comment by friedmud** [comment]
Right: definitely don't want -Werror while developing.  But we definitely
do want it on Civet.  I like the idea of adding -Wall and -Wextra to the
MOOSE makefiles though.

**Comment by brianmoose** [comment]
I removed the `-Werror` and left it so that `-Wall -Wextra` is on by default.
The civet recipes have `-Werror` on them so we should prevent further warnings getting merged.

**Review by permcody — APPROVED** [review]

**Pull request merged**
