### PR TITLE
Make AugmentSparsityOnInterface thread-safe

### PR DESCRIPTION
**Pull request by lindsayad**
Refs test failures with threads from #22376

### CODE REVIEW

**Review by loganharbour — DISMISSED** [review]

**Comment by lindsayad** [comment]
Yea so my hypothesis is that superlu dist, which supports threading via openmp, no worky with the Mac openmp implementation, at least not for Mac intel. So we'll just not use superlu dist for these tests

**Review by GiudGiud — APPROVED** [review]
basically you're moving partially away from class attributes because they are not all initialized at the same time?

**Review by loganharbour — APPROVED** [review]

**Comment by lindsayad** [comment]
> basically you're moving partially away from class attributes because they are not all initialized at the same time?

Yea `SparsityPatttern::Build::operator()` is threaded and so `AugmentSparsityOnInterface::operator()` will be called threaded. So there would be races to write the class data members. By going to all local variables we avoid the issue

**Comment by lindsayad** [comment]
Thread timings:

Simple diffusion with 6 refinements performed in a `--mesh-only` run and then loaded with a `FileMeshGenerator`. 410881 dofs and 409600 elements

| num threads | time |
| --- | --- |
| 1 | 21 |
| 2 | 14 |
| 4 |  10 |
| 8 |  8 |
| 16 |  8 |
| 32 |  9 |

**Comment by GiudGiud** [comment]
How is this chip again? Is it single socket or dual? Any NUMA issue?
To get good/better threading performance, the NUMA needs to be hardcoded in the OpenMP parameters quite often

**Comment by lindsayad** [comment]
> How is this chip again?

?

**Comment by GiudGiud** [comment]
> Run on my System76 Linux box which has 64 physical cpu, 128 logical cpu

what is the CPU ? AMD ? Single socket?

**Comment by lindsayad** [comment]
```
lindad@pop-os:~$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  128
  On-line CPU(s) list:   0-127
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen Threadripper 3990X 64-Core Processor
    CPU family:          23
    Model:               49
    Thread(s) per core:  2
    Core(s) per socket:  64
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU max MHz:         4375.4878
    CPU min MHz:         2200.0000
    BogoMIPS:            5789.02
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse 
                         sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc c
                         puid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe pop
                         cnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse
                          3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwai
                         tx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm r
                         dt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_
                         llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbr
                         v svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold a
                         vic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   2 MiB (64 instances)
  L1i:                   2 MiB (64 instances)
  L2:                    32 MiB (64 instances)
  L3:                    256 MiB (16 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-127
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, STIBP conditional, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by GiudGiud** [comment]
ok not much non-uniformity except maybe the L3, which is likely shared by groups of 4. In this case we would want to make sure all threads are bound to cores that are sharing
`  L3:                    256 MiB (16 instances)`

**Pull request merged**
