### PR TITLE
Richards UserObjects more fully tested

### PR DESCRIPTION
**Pull request by WilkAndy**
Various minor unnecessary things removed from some userobjects

Refs #6402

### CODE REVIEW

**Comment by WilkAndy** [comment]
I can't get that combined test to pass on CIVET - it passes on my computer and has nothing to do with the current PR as far as i can tell.

**Comment by permcody** [comment]
Just leave it open. We are investigating the current failing test.

**Comment by permcody** [comment]
:+1: - This failed due to an unrelated patch which has since been reverted here: https://github.com/idaholab/moose/commit/175e1d14594aff8b25f3cc79548db01684c33dab

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Pull request merged**
