### PR TITLE
Fix some peacock Python3 incompatibilities

### PR DESCRIPTION
**Pull request by smharper**
Python3 is the primary Python that I use in my workflow so I figured I would take a crack at adding Py3 compatibility to peacock.  This PR doesn't give full Py3 compatibility, but it gets a lot of the grunt work out of the way.  Mostly this just switches to the new formats for relative imports and print functions.

Beyond this, some more detailed work is needed.  In particular, some Qt objects are used as dictionary keys, but they aren't hashable in Py3.  Not sure if I'm motivated enough to tackle that stuff so I'll PR this work to give the next person a good start.

Refs #11100

### CODE REVIEW

**Comment by permcody** [comment]
I'd really like to see this taken over by someone. @milljm? @aeslaughter? new intern??

**Review by aeslaughter — APPROVED** [review]

**Comment by aeslaughter** [comment]
I think this is great. I do however think that we should add python3 testing to CIVET before we merge this so we don't let things creep back in. Thanks for this work.

**Comment by aeslaughter** [comment]
@milljm Could you create a python3 version of our python testing, please.

**Comment by smharper** [comment]
@aeslaughter, unfortunately this will still fail Python3 tests.  There's more work to do before it's Py3 ready.

**Comment by aeslaughter** [comment]
I am going to start getting this working as I work on documentation. The new package stuff @milljm is working on as well as Peacock stuff that @andrsd is doing has bumped the priority on this for me.

**Pull request closed without merging**
