### PR TITLE
Enhance `hit find` command with wildcard and value matching support

### LINKED ISSUE #19001: Add `hit grep` subcommand
## Reason
It is often useful to find input files that set a certain parameter. Vanilla `grep` is not helpful here, as it has no concept of hit blocks and context. Just searching a parameter by its name alone is unproductive, as many objects share parameter names.

## Design
The most straight forward implementation would utilize wildcard matches to match full parameter paths

```
hit grep '/Contact/*/mesh' *
```

or (with parameter value matching)

```
hit grep '/Constraints/*/secondary_subdomain=*primary' *
```

this would be very straight forward to implement, but I'd like to be able to specify constraints on the type of a block matched with a `*` as well e.g.

```
hit grep '/Constraints/*/[secondary_subdomain=*primary',type='GapConductanceConstraint]' *
```

or some other more intuitive syntax.

## Impact
A useful tool for people changing APIs around or looking for examples of parameter usage in a large set of input files.

### PR DESCRIPTION
**Pull request by dschwen**
Example output for 

```
hit find 'Kernels/*/type=*Diff*' test/tests/*/*.i
```

```
test/tests/coord_type/coord_type_rz.i:15 Kernels/diff/type = Diffusion
test/tests/coord_type/coord_type_rz_integrated.i:36 Kernels/diff_u/type = Diffusion
test/tests/performance/input.i:15 Kernels/diff/type = Diffusion
test/tests/phi_zero/simple_transient_diffusion.i:22 Kernels/diff/type = CoefDiffusion
test/tests/system_interfaces/input.i:15 Kernels/diff/type = Diffusion
test/tests/tag/2d_diffusion_dg_tag.i:71 Kernels/diff/type = Diffusion
test/tests/tag/2d_diffusion_matrix_tag_test.i:27 Kernels/diff/type = Diffusion
test/tests/tag/2d_diffusion_matrix_tag_test.i:33 Kernels/diff1/type = Diffusion
test/tests/tag/2d_diffusion_matrix_tag_test.i:40 Kernels/diff2/type = Diffusion
test/tests/tag/2d_diffusion_matrix_tag_test.i:46 Kernels/diff3/type = Diffusion
test/tests/tag/2d_diffusion_tag_matrix.i:31 Kernels/diff/type = Diffusion
test/tests/tag/2d_diffusion_tag_vector.i:31 Kernels/diff/type = Diffusion
test/tests/tag/controls-tagging.i:25 Kernels/diff/type = Diffusion
test/tests/tag/eigen_tag.i:32 Kernels/diff/type = Diffusion
test/tests/tag/tag_ad_kernels.i:15 Kernels/diff/type = ADDiffusion
test/tests/tag/tag_dirac_kernels.i:35 Kernels/diff_u/type = Diffusion
test/tests/tag/tag_dirac_kernels.i:49 Kernels/diff_v/type = Diffusion
test/tests/tag/tag_interface_kernels.i:48 Kernels/diff_u/type = CoeffParamDiffusion
test/tests/tag/tag_interface_kernels.i:56 Kernels/diff_v/type = CoeffParamDiffusion
test/tests/tag/tag_neumann.i:15 Kernels/diff/type = Diffusion
test/tests/tag/tag_nodal_kernels.i:17 Kernels/diff/type = Diffusion
test/tests/test_harness/500_num_steps.i:14 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csv_validation_tester_01.i:37 Kernels/diff/type = Diffusion
test/tests/test_harness/csvdiff.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_floor.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_global_floor.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_global_relative.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_not_logic.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_relative.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_comparison_removed_field.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_diff_gold.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_missing_field_comparison.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_spec_override_global_floor.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_spec_override_global_relative.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_spec_override_specific_floor.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/csvdiff_spec_override_specific_relative.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/exception_transient.i:25 Kernels/diff/type = Diffusion
test/tests/test_harness/exodiff.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/exodiff_diff_gold.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/good.i:15 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/long_running.i:16 Kernels/diff/type = CoefDiffusion
test/tests/test_harness/output_csv_and_exodus.i:15 Kernels/diff/type = CoefDiffusion
test/tests/thewarehouse/test1.i:21 Kernels/diff/type = CoefDiffusion
test/tests/usability/bad.i:13: missing closing '[]' for section
test/tests/usability/input.i:15 Kernels/diff/type = Diffusion
45 matches found.
```

Closes #19001

### CODE REVIEW

**Comment by dschwen** [comment]
Probably time to start adding tests for the `hit` executable...

**Review by GiudGiud — COMMENTED** [review]
this is really cool stuff. You are going to replace my usage of grep at this point
you could add unit tests to lower() and globCompare()

**Comment by dschwen** [comment]
I'd still like to ad a `!=` operator for negtive matches.

**Comment by dschwen** [comment]
@loganharbour could we run `make` in `framework/contrib/hit` in the Civet recipes? Or have the hit tool built by default in our build system?

**Review by GiudGiud — CHANGES_REQUESTED** [review]

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
