### PR TITLE
Add an inheritance layer shared by Action and MooseObject

### LINKED ISSUE #28239: Create another inheritance layer shared by Action and MooseObject
### Motivation

We have a lengthy construction requiring parameters, communicator, error message handling in both an Action and user objects. It is needed to have a function for this construction to accept either an Action or a user object to avoid code duplications. To simplify the interface of the function, I want another inheritance layer shared by `Action` and `MooseObject` to group `MooseBase`, `MooseBaseParameterInterface`, `MooseBaseErrorInterface` and `ParallelObject` together which can be passed to the construction function.

### Design

Add a new class that inherits the four base classes and make both `Action` and `MooseObject` which both use the same four base classes derived from the new class.

### Impact

An internal code structure change that should not affect existing capabilities. The new inheritance highlights the similarity of `Action` and `MooseObject` and makes the desired feature in Motivation possible.

### PR DESCRIPTION
**Pull request by YaqiWang**
Closes #28239.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@yjung-anl This change may impact your PR, but hopefully conflict if there is any should be pretty minor.

**Comment by dschwen** [comment]
Why did you not simply push the common inheritances into `MooseBase`¿?

**Comment by YaqiWang** [comment]
`MooseBase` is also directly used by `MooseApp`, which does not use the other two except `ParallelObject`.

**Comment by dschwen** [comment]
I see. Would it hurt though?

**Comment by YaqiWang** [comment]
I think that is a good question. Functions in `MooseBaseParameterInterface` and `MooseBaseErrorInterface` are possible useful to `MooseApp`. Not sure whether there could be some implications. @GiudGiud possibly has an answer.

I cannot come up a good name for this new class, it is likely there is a better name than this `ParallelMooseBase`.

**Comment by YaqiWang** [comment]
@lindsayad brought in `DataFileInterface` and it makes the template of `DataFileInterface` unnecessary. Name is also changed to the one you suggested.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
