### PR TITLE
Vector interface kernel

### LINKED ISSUE #13354: Support for Vector FE in InterfaceKernel
## Reason
Discontinuous interface conditions arise naturally from Maxwell's Equations for electromagnetics simulation. Thus, I would like InterfaceKernels to have Vector FE support. 

## Design
After discussing with @lindsayad, I propose:
1. Splitting the current class into `InterfaceKernelBase` and `InterfaceKernel` classes
2. Making a templated class, `InterfaceKernelTempl`, that will provide `InterfaceKernel` for scalar FE and `VectorInterfaceKernel` for vector FE.

## Impact
This should not break existing APIs, and it will add new capability. It also sets up the base structure for proceeding to AD with InterfaceKernels.

### PR DESCRIPTION
**Pull request by cticenhour**
Summary of changes:

1. `InterfaceKernel` separated into `InterfaceKernelBase` and `InterfaceKernelTempl`. The latter is a templated class which provides `InterfaceKernel` for scalar FE and `VectorInterfaceKernel` for vector FE. 
2. Added 2D and 3D tests for the new `VectorInterfaceKernel`

Closes #13354

### CODE REVIEW

**Comment by cticenhour** [comment]
This PR requires a libmesh submodule update to libmesh/libmesh@4a4afd3. @lindsayad Should this update go in this PR, or in a separate one?

**Comment by lindsayad** [comment]
I'll make an independent libmesh update PR

**Comment by cticenhour** [comment]
For some reason, GitHub is not correctly updating and showing the output of the remaining CIVET tests - they are all green. @lindsayad This should be ready for review whenever you're able to get to it.

**Review by lindsayad — APPROVED** [review]
This looks like a great refactor to me! Nice work @cticenhour. Thanks for the cool new capabiliy.

**Comment by lindsayad** [comment]
The okami build failure appears totally unrelated to me, so going ahead and merging.

**Pull request merged**
