### PR TITLE
FunctionSideIntegral added.  Fixes #4799

### LINKED ISSUE #4799: deprecate or enhance AreaPostprocessor
I want to calculate the integral of a function over a sideset.  Therefore i want to either deprecate AreaPostprocessor and create a new FunctionIntegral, or to enhance AreaPostprocessor so that it takes an optional Function argument:

params.addParam<FunctionName>("function", 1.0, "doco")

FunctionIntegral::computeQpIntegral()
{
  return _func.value(_t, _q_point[_qp]);
}

Comments?

### PR DESCRIPTION
**Pull request by WilkAndy**

### CODE REVIEW

**Comment by WilkAndy** [comment]
Thanks @permcody .

a

**Comment by permcody** [comment]
I didn't see the loose tolerance that @friedmud pointed out. Is that
necessary here?

**Comment by WilkAndy** [comment]
No, @permcody , the loose tolerances are not necessary.  i just opened a new issue, and am about to issue a new PR that tightens the tolerances.  On the architectures i've tried, the tolerances can be around 1E-13.  They can't be zero, because one of the FunctionSideIntegrals is subject to small precision loss

**Comment by permcody** [comment]
Moose has a default rel tol of 1e-8. That's a reasonable number for cross
platform convergence.

**Comment by WilkAndy** [comment]
Hmmm, well i changed it to 1E-12

a

**Pull request merged**
