### PR TITLE
PiecewiseBilinear Extension to Relax CSV File Requirement 

### LINKED ISSUE #5991: PiecewiseBilinear Extension to Relax CSV File
In some applications, it would be useful to allow for PiecewiseBilinear functions to be used without requiring an external data_file.  This issue address that by proposing that x, y, and z can be entered, where x and y are simple vectors and z is a flattened vector from a matrix and size(z) = size(x)*size(y).

### PR DESCRIPTION
**Pull request by stimpsonsg**
Modifying PiecewiseBilinear function to allow x, y, and z to be specified in the function instead of requiring a data_file (with corresponding addition of a 2d_linear_interpolation test).

Closes #5991

### CODE REVIEW

**Comment by stimpsonsg** [comment]
I was hopeful that third time was the charm...but you need a ticket reference?

**Comment by permcody** [comment]
For now. That will change. Since you already have a pr just reference that
number

**Comment by stimpsonsg** [comment]
I created an issue, and have added it to the first comment/description.  How do I tell it to rerun the PR pre check?

Thanks again.

**Comment by permcody** [comment]
If you push again it will retest.

**Comment by friedmud** [comment]
To be clear: you have to add the ticket number in your commit message (I recommend using `git commit --amend` to modify your commit message and then a `git push --force` to update this branch with the modified commit).

You can find all of our development cycle guidelines here: http://mooseframework.org/wiki/Contributing/

**Comment by stimpsonsg** [comment]
Got it.  Thanks to you and Andrew for passing along the Contributing guidelines.  It was clearly my first go at this, but I won't make the same mistakes again.

**Comment by friedmud** [comment]
No problem at all!  Thank _you_ for your contributions!

**Comment by stimpsonsg** [comment]
Great, looks like everything passed.  Let me know if there is anything else you need from me to accept this.

**Comment by permcody** [comment]
Pinging @jasondhales, @novasr and @WilkAndy  - Would one of you mind reviewing this PR? I believe these utilities are used mostly by BISON and Richards.

**Comment by jasondhales** [comment]
Looks good to me.  That test input file is the best documented test I've seen.

**Comment by stimpsonsg** [comment]
To be perfectly honest, I just copied that test file from the pre-existing one and changed the Bilinear arguments.  My understanding is that @novasr is responsible for it's thoroughness.

**Pull request merged**
