### PR TITLE
Adding truss model and AveragePointSeparation

### LINKED ISSUE #16957: Add truss model and AveragePointSeparation postprocessor
## Reason
- Newer method is required to handle truss elements just like already existing beam elements. For instance, it will provide a tool to study a model with prestressing strain, thermal strain in a better way.
- To evaluate the distance between to points in a model, point displacements are calculated in each direction. In this way, there is a need to do some postprocessing to find the displacement between any two points in a model, which is cumbersome.  

## Design
- The design is based on the existing model for the beam elements. 
- The `AveragePointSeparation` calculate displacement in each direction for first point and second point and then calculate the distance between those two points.

## Impact
- Prestressing strain and thermal strain can be applied to a structure without any manipulation. 
- Average distance between two points can be easily calculated using the newly developed `AveragePointSeparation` postprocessor

### PR DESCRIPTION
**Pull request by jain651**
This PR is for
a truss model which is developed in line with the existing beam model. The truss model can take care of multiple eigenstrains too.
AveragePointSeparation postprocessor is also added that calculates average displacement between two points.

closes #16957

### CODE REVIEW

**Comment by loganharbour** [comment]
@jain651 - just got your e-mail. Figured it would be more appropriate to respond here.

The failures that you're experiencing on the controlled and internal app tests are unrelated to your PR. The issue should be fixed some time today, I will keep an eye on them and invalidate when they should pass.

**Comment by loganharbour** [comment]
The documentation errors are valid, however. I suggest you take a look and work on fixing those first while we resolve the other issues internally.

**Comment by jain651** [comment]
> The documentation errors are valid, however. I suggest you take a look and work on fixing those first while we resolve the other issues internally.
Yes, I will work on that. I wanted to address all failure together.  I will do my part. Thanks!

**Comment by bwspenc** [comment]
@jain651 Can you please rebase and update this?

**Comment by bwspenc** [comment]
Did you mean to close this?  I think we still want this, right?  Maybe some of it is a better fit in BlackBear, though?

**Comment by jain651** [comment]
Hi @bwspenc ,
I was facing some problem with updating. So I closed this one but opened it here: #18269.

**Pull request closed without merging**
