### PR TITLE
Add requirements for a set of thermal contact tests 

### PR DESCRIPTION
**Pull request by bwspenc**
ref #13634

### CODE REVIEW

**Comment by bwspenc** [comment]
@hchen139 Hopefully this covers what you need for #14090

**Comment by hchen139** [comment]
still waiting for this PR get merged before addressing comments for #14090

**Comment by permcody** [comment]
@bwspenc - I'm not going to reject this but I received guidance from Nancy that we should avoid using "MOOSE shall" instead we should be writing the "The system shall".

**Review by permcody — APPROVED** [review]

**Comment by bwspenc** [comment]
@permcody Good to know. I think I knew that, but I was copying some strings that said MOOSE instead. I just found the page on how to write a good requirement -- maybe we should link to that from the code standards page or something.

**Pull request merged**
