### PR TITLE
handle stateful properties in xfem moving interface

### LINKED ISSUE #15437: Add AD capability for existing BiMaterial XFEM classes
## Reason
Moving interface problems using XFEM and level set capabilities cannot currently be used with material classes using AD.

## Design
Duplicate the BiMaterial classes with AD counterparts

## Impact
Extends the use of XFEM-level set simulations to material models coded only in AD

ping @jiangwen84

### PR DESCRIPTION
**Pull request by hugary1995**
store stateful properties before healing, and set them back after re-cut.

close #15437

### CODE REVIEW

**Comment by hugary1995** [comment]
@bwspenc could you help me review the xfem changes? We also need to ask someone from the moose team to review the framework changes.

@sapitts FYI.

**Comment by loganharbour** [comment]
Please push a change to this to forcefully re-trigger testing (full testing is now available).

You can do the following:
```
git commit --amend
```
and save the amend message that comes up without changing it (by typing `:wq` if in vim). This will forcefully change the commit hash of the last commit, which will trigger a change. Then forcefully push:
```
git push --force
```

**Comment by hugary1995** [comment]
@bwspenc How do I reopen this PR?

**Comment by dschwen** [comment]
This cannot be reopened, you need to make a new PR

**Comment by hugary1995** [comment]
Whoa how did you see this message when I mentioned Ben? Is Ben automatic forwarding all mentions to you?

**Pull request closed without merging**
