### PR TITLE
ColumnMajorMatrix

### LINKED ISSUE #12254: doubleContraction for ColumnMajorMatrix
## Rationale

Assertions for matrices having the same shape fail in `doubleContraction` and `kronecker` functions in ColumnMajorMatrix, when being used with non-square matrices. 

## Description

The `doubleContraction` function contains the following assertion 
```
  mooseAssert(_n_rows == rhs._n_cols && _n_cols == rhs._n_rows,
              "Matrices must be the same shape for a double contraction!");
```
Which basically asserts that the n_rows of LHS is equal to n_cols of RHS and vice versa, while the assertion is meant to check that the LHS and RHS are of the same shape. Currently, if `doubleContraction` is used with a matrix A(2x3) and a matrix B(3x2), there will not be any error. This needs to be changed to 
```
  mooseAssert(_n_rows == rhs._n_rows && _n_cols == rhs._n_cols,
              "Matrices must be the same shape for a double contraction!");
```

Same issue with `kronecker`.
## Impact

If anything, this might throw some more assertions for cases where these functions were being used in with non-square matrices in the wrong way. If it was being used with square matrices, there will be no change.

### PR DESCRIPTION
**Pull request by cbolisetti**
Removed errors in assertions of ColumnMajorMatrix and changed corresponding unit tests. Closes #12254

### CODE REVIEW

**Review by jwpeterson — CHANGES_REQUESTED** [review]
The fix for the `doubleContraction()` looks ok, the formula for this is 
```latex
doubleContraction(a,b) = \sum_i \sum_j a_{ij} b_{ij}
```
Assuming `kronecker()` is supposed to implement [this formula](https://en.wikipedia.org/wiki/Kronecker_product) then the change also looks reasonable. Would you mind adding a link to the Wikipedia documentation for `kronecker()`? It appears to be undocumented currently.

**Comment by cbolisetti** [comment]
> Please also add some unit tests that throw exceptions (see, e.g. the EXPECT_THROW tests in MatrixToolsTest.C) when incorrect arguments are passed - we currently don't have any test coverage for that.

It looks like a lot of these mooseAsserts actually need to be mooseErrors. Shall I change them to errors? For instance `operator =` should fail when the sizes are different. mooseAssert only fails in debug mode.

**Comment by permcody** [comment]
I'd say feel free. This is a very old class and probably doesn't see a lot of use. If you want to clean it up a bit that's fine.

**Comment by jwpeterson** [comment]
@cbolisetti Unfortunately your changes won't be tested (and we can't merge them) until you follow the instructions posted above by moosebuild regarding running clang-format.

**Comment by cbolisetti** [comment]
@jwpeterson The checks all pass now. Can you please review this when you get a chance?

**Review by jwpeterson — APPROVED** [review]
Thanks for updating the error checks and adding unit tests.

**Pull request merged**
