### PR TITLE
Setup Point and LineSegment specializations to enable use with Reporters

### LINKED ISSUE #23736: Line Segment and Point Reporters
## Reason

Simplifies creating and using reporters that deal with points and line segments. For example, `ReporterPointSource` requests three reporters for x,y, and z coordinates for creating points. 
## Design

Create necessary specializations for Point and LineSegment classes.
## Impact

Cleaner code and simpler input files.

### PR DESCRIPTION
**Pull request by maxnezdyur**
closes #23736 
## Reason

Simplifies creating and using reporters that deal with points and line segments. For example, ReporterPointSource requests three reporters for x,y, and z coordinates for creating points.
## Design

Create necessary specializations for Point and LineSegment classes.
## Impact

Cleaner code and simpler input files.

### CODE REVIEW

**Comment by maxnezdyur** [comment]
@loganharbour I will add some tests soon. But let me know if this is how the `dataLoad` and `dataStore` and `to_json` should look.

**Comment by maxnezdyur** [comment]
How do I go about creating tests for the `dataStore` and `dataLoad`? If you could point me to where it is tested for `Point` then I could recreate them.

**Comment by maxnezdyur** [comment]
@loganharbour I need some help on this. I am trying to add Point to the constant reporter. I am getting the compiler error below 
`  note: candidate template ignored: substitution failure [with BasicJsonType = nlohmann::basic_json<>, T = const std::vector<libMesh::Point> &]: no matching function for call to 'to_json'
  auto operator()(BasicJsonType & j, T && val) const`
Let me know if I am missing something simple, and I can fix it, thanks!

**Comment by loganharbour** [comment]
I'm working on this. I know the issue, not the solution just yet.

**Comment by maxnezdyur** [comment]
Ok, so testing this, I am hitting this error. This is in `ReporterContext.h`
```
*** ERROR ***
Can only broadcast fundamental types.
```

**Comment by loganharbour** [comment]
@maxnezdyur wanna ping me on slack when you have a second. I'm looking into this

**Comment by GiudGiud** [comment]
How's the timeline on this? I m needing std::vector<Point> for reporters.

**Comment by loganharbour** [comment]
It’s done. @maxnezdyur let’s chat tomorrow. I think I have one cleanup commit to add and we’re good 

thanks for the reminder @GiudGiud

**Comment by GiudGiud** [comment]
Ready for review?

**Comment by maxnezdyur** [comment]
I'll add a test case today, but after should be good for a review.

**Comment by loganharbour** [comment]
> Ready for review?

There's two of us on here @GiudGiud - not needed, thanks though.

**Review by GiudGiud — APPROVED** [review]
approving Logan's commit

**Comment by GiudGiud** [comment]
What is the status here? Is this still needed?

**Pull request closed without merging**
