### PR TITLE
Implementation of line sources

### PR DESCRIPTION
**Pull request by snschune**
### Complete each of the following items before creating a PR
A first draft of a line source implementation. 

Most of the work is done in the constructor when distributing the point sources. I use
bisection to find the parameter `s` on the curve such that the length measured from `smin`
corresponds to the Gaussian integration points usually defined `[-1,1]`.

I added a corresponding file with multiple point sources which gives similar results. I also 
tried verifying it using the Green's function of Laplace's equation but that does not agree at all.
So there might still be something wrong with this.

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
Interesting. I could see myself using this as a line _sink_. Would a more appropriate name be DiracLineKernel?

**Comment by friedmud** [comment]
I'm not really liking this too much.

My plan has been to use the new Ray tracing stuff to do line sources...
reiniting a qrule for every segment and integrating against the basis
functions.

**Comment by snschune** [comment]
For straight line sources that is a better solution, because my implementation is only an approximation of a real line source up to how many point sources you pick on the _whole_ line. You may need many to get a good approximation close to the sources. 

I don't see how you can handle sources on curves with significant curvature within each element, though. That's what I am interested in.

**Comment by friedmud** [comment]
Fair enough - still not a fan of this code going into MOOSE. Maybe just
keep it in your own application for now?

**Comment by snschune** [comment]
That'd work for me obviously. If this is not useful for at least a number of people, I'd concur with having it somewhere else. Let's see if there are other opinions....then wrap it up accordingly.

**Comment by friedmud** [comment]
If this is voted to go in... it needs some _serious_ verification.

Line sources are an important thing... and if this goes into the framework it will get used by many other people.  It needs to be shown to be very correct.

**Comment by snschune** [comment]
Lack of responses == lack of interest? If it's only useful for me _and_ a new better capability 
for straight line sources is coming from @friedmud, I'll move this to a specialized app.

**Comment by permcody** [comment]
Very few people watch the tickets. Most of the MOOSE team unfortunately doesn't, so you have to tag them if you want attention. I figured @friedmud handled this fairly well so I think that starting with this capability in your own app is the best bet until it's needed elsewhere.

**Pull request closed without merging**
