### PR TITLE
LeastSquaresFit postprocessor

### PR DESCRIPTION
**Pull request by bwspenc**
refs #4464

### CODE REVIEW

**Comment by jwpeterson** [comment]
@bwspenc looks like this just needs a quick whitespace fix.

**Comment by bwspenc** [comment]
@permcody Per our discussion, I fixed the whitespace error and modified the test so that the vectorpostprocessors are run in the wrong order.  It fails with an error that says there's no data for the least squares fit.  Once the order resolution gets fixed, it should pass.  If you move the line_sample vectorpostprocessor to the top of the list in the input file, it passes.  Thanks for looking into the order dependence!

**Comment by permcody** [comment]
I put in a PR onto your branch. Go ahead and merge that so it'll test again.

**Comment by bwspenc** [comment]
@permcody I think this is ready to go now.  I removed that print statement from your commit, reordered the commits so that the tests would always pass through the whole history, and revised one of your commit messages to reference the issue.  Thanks for the cleanup of my commit -- that's how I had it originally before I started messing around trying to resolve the order dependence.  I can either leave the commit history as is or squash them, whatever you like.

**Comment by permcody** [comment]
This looks good un-squashed. Thanks

**Comment by permcody** [comment]
@jwpeterson will you review this since I have a patch in here as well?

**Comment by jwpeterson** [comment]
No need to wait for the CI on my comments.  Also if you don't have time to fix those little formatting things I am OK with merging this as-is.

**Pull request merged**
