### PR TITLE
Update scripts to python 3

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Review by permcody — DISMISSED** [review]

**Comment by permcody** [comment]
Testing failed.

**Comment by aeslaughter** [comment]
I can't reproduce the errors locally. I have tried to try on a linux machine but the github problems prevented that. I will get it working soonish.

**Comment by aeslaughter** [comment]
I can't reproduce this error, it works on my mac, rod, and moosebuild on rod

**Review by milljm — APPROVED** [review]
👍

**Pull request merged**
