### PR TITLE
PerfGraph Live Tweaks

### LINKED ISSUE #18818: Make live print section activated with a given time delay
## Reason
I am having a user object whose `finalize` function calls an external Fortran function that can be quite heavy. The function also can be verbose with some line print-outs about its progress with a control parameter. When the verbose is off and the function is heavy, MOOSE live-print will be activated with this
```
  TIME_SECTION("computeUserObjects", 1, "Computing User Objects");
```
in `FEProblemBase::computeUserObjectsInternal`, which shows the cpu-time, memory usage at the end nicely with the dots showing the dynamics.

But when the verbose is on and the function is heavy, the dots are mingled with the line print-outs in the Fortran function and mess up the screen. I can add a new section in `finalize` like
```
  TIME_SECTION("FortranCall", 3, "Calling Fortran", false);
```
which creates a new section with dots turned off. The only drawback of this is that when the function is heavy, some line print-outs from Fortran come out before the header of the section. When the function is light, all line print-outs will come out properly because the live section will not be activated.

## Design
So I suggest that we have a capability to control how long to activate a live print. Currently all live print sections use five seconds. If this capability is in place, I can activate the section based on the verbose parameter with 0 time delay. This looks to me a useful feature.

## Impact
A new feature for the live print.

### PR DESCRIPTION
**Pull request by friedmud**
@YaqiWang noticed some undesireable behavior from Perf Graph Live... this is some tweaks to address that.

Main things:
- If something is set not to print dots - it won't ever print the message (only the "Finished" message could possibly be shown)
- If something has printed to the Console since the last time Live woke up - Live won't print anything (the idea being that if they are seeing any progress at all - then there is no reason for Live to do anything.
- "Context" (scopes above the one being printed) are no longer printed.
closes #18818

### CODE REVIEW

**Comment by YaqiWang** [comment]
After adding 
```
  TIME_SECTION("CSAPIFinalize", 4, "Finalizing CSAPI", false);
```
in the `finalize` function of my user object, the screen output is:
```
[CSAPI]...Solving CSAPI FSP.............................................................................................
[CSAPI]...Group    10...................................................................................................

    Computing User Objects[CSAPI]...Group    11...................................................................................................
[CSAPI]...Group    12...................................................................................................
[CSAPI]...Group    13...................................................................................................
[CSAPI]...Group    14...................................................................................................
[CSAPI]...Group    15...................................................................................................
[CSAPI]...Group    16...................................................................................................
```
Looks like the live-print prints `\n Computing User Objects`, which should be turned off in `finalize` function, right?

**Review by YaqiWang — CHANGES_REQUESTED** [review]
Just one comment.

**Comment by friedmud** [comment]
@YaqiWang - thanks for testing.  I think I see what's going on.  Let me fix it.

**Comment by friedmud** [comment]
@YaqiWang ok - I can reproduce this.  Working on a fix.

**Comment by friedmud** [comment]
@YaqiWang - ok, I think I have a fix in

**Comment by YaqiWang** [comment]
This fixed the issue I saw previously.

**Comment by friedmud** [comment]
Thanks for checking @YaqiWang!

**Review by loganharbour — DISMISSED** [review]

**Comment by friedmud** [comment]
@YaqiWang - can you provide an example?  It shouldn't print `Still` if anything has been printed to the screen during the last time period.

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
We've decided to hold off on @YaqiWang's comments to be added at a later date.

@aprilnovak after your question in regards to avoiding printing within your application, please give it a try with these updates to see if the output is as you would like it.

**Pull request merged**
