### PR TITLE
Fixup geochemistry tests on M1

### PR DESCRIPTION
**Pull request by cticenhour**
Refs #18954

### CODE REVIEW

**Comment by WilkAndy** [comment]
I don't understand why you need to much around with precision like this, but if it passes then this PR is fine by me.

**Comment by cticenhour** [comment]
Hi @WilkAndy! I want to write my thoughts on this down here as a bit of a log and also an explanation, since I'm unsure we've done it in full anywhere else. In our experience with prior test fixups, differences between x86 and M1 (ARM64) end up being not only the normal software platform differences, but also how each architecture handles floating point precision.

For example, `long double` is double precision IEEE floating point on ARM64 instead of quad precision (see Apple developer documentation [here](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms) about some ARM64 differences if you're curious). `long long double` is also identical to `long double` on this architecture. The `long double` precision loss actually caused issues with string-to-int conversions being performed in the `convert` method in MooseUtils (see #20088 for more info on that one).

I am assuming here that the same precision differences are feeding into how some values are represented when being passed through standard output. `seawater_no_precip.i` had two lines in the compared output that were different, and I'll highlight one of them here. On x86 machines, we see:

```
CO3--;  molality = 4.596e-05mol/kg(solvent water);  free_conc = 2.661mg/kg(soln);  act_coeff = 0.1891;  log10(a) = -5.061;  CO3-- = -1*H2O - 1*CO2(g) + 2*HCO3-;  log10K = 2.525
```

but with the same `precision` parameter on ARM64, we see:

```
CO3--;  molality = 4.596e-05mol/kg(solvent water);  free_conc = 2.661mg/kg(soln);  act_coeff = 0.1891;  log10(a) = -5.061;  CO3-- = -1*H2O - 1*CO2(g) + 2*HCO3-;  log10K = 2.526
```

Note the `log10K` value. Increasing to `precision = 7` was the minimum required before the numerical representation on all lines of output were an exact match as required by the test. Unlike our "-diff" tests, we don't have a test-spec-level tolerance we can adjust here. Before messing with the precision, I did adjust tolerances for the solve without any real impact.

I do have one outstanding failure (see [the CIVET output here](https://civet.inl.gov/job/1210808/) under the modules testing) for the `ph_constraint` test that I need your assistance with. In the ARM64 output, we have the basis species `Ca++`:

```
Ca++;  bulk_moles = -5.551e-16mol;  bulk_conc = -2.218e-11mg/kg(soln);  molality = 0.01918mol/kg(solvent water);  free_conc = 766.1mg/kg(soln);  act_coeff = 0.4633;  log10(a) = -2.051
```

compared to the same line on x86:

```
Ca++;  bulk_moles = -2.22e-16mol;  bulk_conc = -8.871e-12mg/kg(soln);  molality = 0.01918mol/kg(solvent water);  free_conc = 766.1mg/kg(soln);  act_coeff = 0.4633;  log10(a) = -2.051
```

where our bulk moles and bulk concentration values are both very small numbers and different enough that I am concerned about precision differences here as well. However, considering bulk moles seems to be set via relatively simple re-assignment (without, seemingly, a type change or other conversion) during each iteration in the module, it's unclear to me where the fix needs to be. It's like we're simply adding noise and magnifying tiny precision losses on already small numbers during multiplication/division. Again, making tolerance and output adjustments don't seem to impact these bulk quantities, and unlike a "-diff" test, I can't simply adjust our test comparison tolerance. Do you have suggestions for me on how to address this last test? Thanks!

**Comment by WilkAndy** [comment]
Hi @cticenhour , thanks for the explanation.

Regarding the `ph_constraint` test...   You're right that this is just precision loss - the `bulk_moles` of Ca++ (basically zero) is tied in with the `bulk_moles` of Calcite (=1).   The test is just a string comparison - is it possible to ignore `bulk_moles` bit of the line
```
Ca++;  bulk_moles = -2.22e-16mol;  bulk_conc = -8.871e-12mg/kg(soln);  molality = 0.01918mol/kg(solvent water);  free_conc = 766.1mg/kg(soln);  act_coeff = 0.4633;  log10(a) = -2.051
```
?

**Comment by loganharbour** [comment]
@WilkAndy I think that long term we should really develop `Reporter` output for geochemistry. Long term it will be much better for maintenance to be able to use diffs with tolerances vs very complex and long regex strings.

**Review by loganharbour — APPROVED** [review]
Waiting for a 👍🏼 from @WilkAndy

**Comment by WilkAndy** [comment]
Yep, this looks good.  Rather lucky that the string before the `H+` is actually trivial and needn't be tested in this case!

**Comment by loganharbour** [comment]
Failures are optional recipes not in production yet

**Pull request merged**
