### PR TITLE
Removing non-const get() method in RestartableData

### LINKED ISSUE #16035: Deprecation message when calling non-const ReporterState.value()
## Bug Description
Whenever a postprocessor value is declared, deprection message appears

## Steps to Reproduce
`./moose_test-opt -i tests/postprocessors/area_pp/area_pp.i`

## Impact
Troublesome when trying to go through and remove deprecation.

### PR DESCRIPTION
**Pull request by zachmprince**
Closes  #16035

### CODE REVIEW

**Comment by loganharbour** [comment]
Bold move there, Cotton.

**Comment by aeslaughter** [comment]
> Bold move there, Cotton.

I agree. But, not that you started it means you need to finish it...I think that is a new rule. 😄

**Comment by zachmprince** [comment]
@loganharbour @aeslaughter is this not the right thing to do?

**Comment by loganharbour** [comment]
> @loganharbour @aeslaughter is this not the right thing to do?

It is definitely the right thing to do!

**Comment by loganharbour** [comment]
However, if you see any methods that currently call `.get()` that can be made `const`: that should be the preferred method.

**Comment by zachmprince** [comment]
Whoa! Good to go?

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
