### PR TITLE
Adding new layer remapping capaiblity to MeshExtruder

### LINKED ISSUE #3554: Enhance mesh extruder
We need to enhance the mesh extruder so that it can reassign block IDs for each extruded individual layer. We want to do this enhancement because directly generating a 3D mesh is currently too inefficient to be done.

### PR DESCRIPTION
**Pull request by permcody**
closes #3554

### CODE REVIEW

**Comment by YaqiWang** [comment]
Thanks Cody! This will be really useful to us. A question, can we assign the size of each individual layer?

**Comment by permcody** [comment]
no, that would require another modification at the libmesh level.

**Comment by YaqiWang** [comment]
Oh. Will that be too complicated? That will be a useful feature as well. Sorry for not mentioning it earlier.

**Comment by permcody** [comment]
Not complicated but you won't get it until at least the next update. You can always subdivide your regions and create more elements/layers to make your mesh...  Maybe that's not feasible for what you want to do.

**Comment by YaqiWang** [comment]
Yes, we need it more general and can wait for the next libmesh update. This is already very good for us to try out. We can make `num_layers` parameter as a vector of real numbers. How do we control the size currently? I did not see a parameter doing it.

**Comment by permcody** [comment]
The element size is always "length" of extrusion vector divided by num
layers currently.

**Comment by YaqiWang** [comment]
I see. I thought that is a unit vector.

**Pull request merged**
