### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by arfon**

### CODE REVIEW

**Comment by permcody** [comment]
I thought about adding *.eps but it's probably only the tip of the iceberg. Our "docs" and "tests" files contain several other non code files that we'd like to ignore. Thankfully the binary ones are being ignored now but there are other ASCII files. If your PR is the accepted solution, then that's fine, we'll manage that list. I saw another thread on linguist that said you could weed out specific paths thought too. (i.e. any path containing "tests" or "docs" should be ignored).

**Comment by arfon** [comment]
> I saw another thread on linguist that said you could weed out specific paths thought too. (i.e. any path containing "tests" or "docs" should be ignored).

To be honest I would have expected this to work too. I'm not exactly sure what's going on here and why things like `docs/*` aren't matching.

**Comment by permcody** [comment]
@arfon Do you want to troubleshoot the path matching issue at all? If so I'll leave this alone for the time being. If not, I'll probably add several other suffixes to ignore before merging this.

Thanks

**Comment by arfon** [comment]
> @arfon Do you want to troubleshoot the path matching issue at all? If so I'll leave this alone for the time being. If not, I'll probably add several other suffixes to ignore before merging this.

@permcody - I've had a quick play around now but to no avail. I'm working on some fairly involved changes to Linguist right now so probably don't have time to debug this properly anytime soon sorry. I'd suggest adding some additional suffixes in the short term.

**Comment by permcody** [comment]
Thanks, I updated our .gitattributes file with a few ascii types that we'd like to skip. I'll continue to monitor linguist for additional updates and features.

**Pull request closed without merging**
