### PR TITLE
Postprocessor late binding

### LINKED ISSUE #5507: Late bonding postprocessor with a default value will not be bonded correctly
If a user object call getPostprocessorValue with a parameter name of a postprocessor name who has a default real value, even we set a valid postprocessor name for it, this UO will not bond the pp even it is added later.

### PR DESCRIPTION
**Pull request by permcody**
closes #5507

### CODE REVIEW

**Comment by YaqiWang** [comment]
@permcody Just let me know when this is ready for me to look into rattlesnake.

**Comment by permcody** [comment]
You can anytime. This PR is passing most of the other apps (as it did before).

**Comment by permcody** [comment]
Hmm... Looking at this PR again this morning. I don't think I've changed anything about the order of operations. I guess at some point in the last two years my original fix got implemented in a slightly different but equivalent way. Basically we are declaring postprocessor data early, but not adding the postprocessors until much later. I don't think this PR will fix anything in your case.

Do you have a test case I can look at that illustrates your latest problem? There must be something else going on there.

**Comment by YaqiWang** [comment]
My case is in a custom fairly complicated executioner. But you can for example, add a postprocessor in Transient constructor and print the value at every time step end. Can be easily reproduced. We possibly can test if the pointer obtained in constructor the same as another one obtained in `init()`.

**Comment by permcody** [comment]
> My case is in a custom fairly complicated executioner. But you can for example, add a postprocessor in Transient constructor 

Ah! So this is a new requirement. I'm fairly certain that this PR isn't needed and definitely won't fix your case. Postprocessors have at some point (between when you originally reported this ticket) and when I attempted to merge my fix into HEAD have already been updated to bind late. There are two passes through the Postprocessors block. One to simply setup the data storage area for Postprocessors (since we'll can know the names of every Postprocessor ahead of time), but not actually instantiate those Postprocessors at that time. After most other objects have been created, we go through and instantiate the Postprocessors, which means they can access and query many more parts of the system.

If you take a look at Moose.C, the creation of the Executioner is pretty early (before even the first pass for setting up Postprocessors). As a first try, just discard my changes here and see if you can move the existing "setup_postprocessor_data" task up above the "setup_executioner" tasks. I don't see any issues with moving that task around since it does very little. That's probably all that's needed. It would be nice to create a custom executioner (or simply add an optional postprocessor) to one of the ones in the test suite to ensure that this continues to work for you going forward.

**Comment by YaqiWang** [comment]
@permcody Moving up `setup_postprocessor_data` task does fix the binding issue for executioners. I did not check fully but it passes all moose framework and Rattlesnake tests. It is worthwhile to put in a small PR I think.

**Comment by permcody** [comment]
Sounds good! Please put in a PR

**Comment by permcody** [comment]
Changes unneeded...

**Pull request closed without merging**
