### PR TITLE
Test that illustrates segfault when attempting to cut dt

### PR DESCRIPTION
**Pull request by WilkAndy**
I'm hoping that one of the moose developers can fix this for me.  I throw a MooseException to attempt to cut dt, but then MOOSE segfaults.

The SEGFAULT.i test illustrates the problem.

Refs #7783

### CODE REVIEW

**Comment by permcody** [comment]
Thanks Andy

**Comment by jwpeterson** [comment]
I thought we had fixed this... is this example doing something materially different from the test in #7668?

**Comment by WilkAndy** [comment]
Yes, @jwpeterson , this Material is more complex.  The "Impossible" error does not arise, because you have indeed fixed it.  Moose cuts the timestep, but then upon calculating the new residual (i assume) it crashes.  I *think* that the problem is that my Material has std::vector stateful variables that aren't getting properly carried over to the new timestep.

**Comment by jwpeterson** [comment]
FYI, here's the stack trace with line numbers:
```
* thread #1: tid = 0x1a54b91, 0x00000001002a8d4d libtensor_mechanics-dbg.0.dylib`ComputeCappedWeakPlaneStress::returnMap(this=0x000000010e004000) + 317 at ComputeCappedWeakPlaneStress.C:130, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001002a8d4d libtensor_mechanics-dbg.0.dylib`ComputeCappedWeakPlaneStress::returnMap(this=0x000000010e004000) + 317 at ComputeCappedWeakPlaneStress.C:130
    frame #1: 0x00000001002a889b libtensor_mechanics-dbg.0.dylib`ComputeCappedWeakPlaneStress::computeQpStress(this=0x000000010e004000) + 75 at ComputeCappedWeakPlaneStress.C:110
    frame #2: 0x000000010033a7ba libtensor_mechanics-dbg.0.dylib`ComputeStressBase::computeQpProperties(this=0x000000010e004000) + 26 at ComputeStressBase.C:65
    frame #3: 0x000000010142dee2 libmoose-dbg.0.dylib`Material::computeProperties(this=0x000000010e004000) + 82 at Material.C:163
    frame #4: 0x0000000101439aed libmoose-dbg.0.dylib`MaterialData::reinit(this=0x000000010bd4c160, mats=size=3) + 413 at MaterialData.C:80
    frame #5: 0x0000000100c0db3e libmoose-dbg.0.dylib`FEProblem::reinitMaterials(this=0x000000010d804e00, blk_id=0, tid=0, swap_stateful=true) + 798 at FEProblem.C:2020
    frame #6: 0x0000000100ba53be libmoose-dbg.0.dylib`ComputeResidualThread::onElement(this=0x00007fff5fbfd408, elem=0x000000010bd01af0) + 190 at ComputeResidualThread.C:84
    frame #7: 0x0000000100a56969 libmoose-dbg.0.dylib`ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator(this=0x00007fff5fbfd408, range=0x000000010c63b5c0, bypass_threading=false)(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) + 665 at ThreadedElementLoopBase.h:165
    frame #8: 0x00000001010e7bd6 libmoose-dbg.0.dylib`void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeResidualThread>(range=0x000000010c63b5c0, body=0x00007fff5fbfd408) + 230 at threads_tbb.h:160
    frame #9: 0x00000001010b9237 libmoose-dbg.0.dylib`NonlinearSystem::computeResidualInternal(this=0x000000010d806e00, type=KT_ALL) + 631 at NonlinearSystem.C:1270
    frame #10: 0x00000001010b8d2d libmoose-dbg.0.dylib`NonlinearSystem::computeResidual(this=0x000000010d806e00, residual=0x000000010c6252f0, type=KT_ALL) + 813 at NonlinearSystem.C:762
    frame #11: 0x0000000100c2024c libmoose-dbg.0.dylib`FEProblem::computeResidualType(this=0x000000010d804e00, soln=0x000000010bd2a780, residual=0x000000010c6252f0, type=KT_ALL) + 1692 at FEProblem.C:3553
    frame #12: 0x0000000100c1f2ef libmoose-dbg.0.dylib`FEProblem::computeResidual(this=0x000000010d804e00, (null)=0x000000010bd2a330, soln=0x000000010bd2a780, residual=0x000000010c6252f0) + 111 at FEProblem.C:3470
    frame #13: 0x00000001010b059d libmoose-dbg.0.dylib`NonlinearSystem::solve(this=0x000000010d806e00) + 301 at NonlinearSystem.C:256
    frame #14: 0x0000000100c1e25a libmoose-dbg.0.dylib`FEProblem::solve(this=0x000000010d804e00) + 138 at FEProblem.C:3249
    frame #15: 0x0000000101925324 libmoose-dbg.0.dylib`TimeStepper::step(this=0x000000010c649a80) + 36 at TimeStepper.C:188
    frame #16: 0x00000001012b675e libmoose-dbg.0.dylib`Transient::solveStep(this=0x000000010bd56330, input_dt=-1) + 974 at Transient.C:392
    frame #17: 0x00000001012b634d libmoose-dbg.0.dylib`Transient::takeStep(this=0x000000010bd56330, input_dt=-1) + 253 at Transient.C:327
    frame #18: 0x00000001012b5ff3 libmoose-dbg.0.dylib`Transient::execute(this=0x000000010bd56330) + 211 at Transient.C:251
    frame #19: 0x0000000101032edd libmoose-dbg.0.dylib`MooseApp::executeExecutioner(this=0x000000010a019200) + 285 at MooseApp.C:428
    frame #20: 0x00000001010355dc libmoose-dbg.0.dylib`MooseApp::run(this=0x000000010a019200) + 140 at MooseApp.C:578
    frame #21: 0x00000001000020c9 tensor_mechanics-dbg`main(argc=3, argv=0x00007fff5fbfe6e0) + 345 at main.C:32
    frame #22: 0x00007fff9aaf55ad libdyld.dylib`start + 1
```

Line 130 is where the assignment happens in the code snippet below:
```
  // initially assume an elastic deformation
  _stress[_qp] = _stress_old[_qp] + _elasticity_tensor[_qp] * _strain_increment[_qp];
  for (unsigned i = 0; i < _num_intnl; ++i)
    _intnl[_qp][i] = _intnl_old[_qp][i];
```

**Comment by jwpeterson** [comment]
In this frame, `_qp==0`, and both the left- and right-hand side operands are zero-length vectors:
```
(lldb) p _intnl[0]
(std::__1::vector<double, std::__1::allocator<double> >) $2 = size=0 {}
(lldb) p _intnl_old[0]
(std::__1::vector<double, std::__1::allocator<double> >) $4 = size=0 {}
```
So, I don't know whether this is specifically related to stateful properties, but it's definitely a stateful property vector that's not being resized.

**Comment by WilkAndy** [comment]
Yep, i agree about the stateful problem with cutting dt, @jwpeterson .   Are you able to fix it?

**Comment by permcody** [comment]
I don't have time to dive in right now but remember that when we are
working with stateful materials we have this "swap in/swap out" mechanism
going on under the hood as we compute material properties. I wonder if in
the case of an exception we are missing the "swap out" step as we start
unwinding the stack.

**Comment by jwpeterson** [comment]
> Yep, i agree about the stateful problem with cutting dt, @jwpeterson . Are you able to fix it?

I don't really know what the problem is yet, but I'm taking a look at it.

> I wonder if in the case of an exception we are missing the "swap out" step as we start
> unwinding the stack.

Are you talking about `FEProblem::swapBackMaterials()`? Any idea how to call this automatically during stack unwinding?  Maybe a little "Sentinel" object that would call it in its destructor?

**Comment by jwpeterson** [comment]
Yeah, I'm thinking that the call to `_fe_problem.swapBackMaterials(_tid);` at the end of `ComputeResidualThread::onElement()` is not happening when we throw from down in `_fe_problem.reinitMaterials()`, so this may be why things get out of sync if Cody's theory is correct.  If we create a Sentinel object right before this call, then throw from `reinitMaterials()`, the Sentinel object's destructor should be called, which would then call `_fe_problem.swapBackMaterials(_tid)`.  I'll see if this does anything.

**Comment by jwpeterson** [comment]
I pushed this very simple [commit](https://github.com/jwpeterson/moose/commit/cfe0155a890ff819c9c37d2d0661490c0a94f639) and it seems to get rid of the segfault.  @WilkAndy in this example the MooseException is thrown every time and the timestep is just cut repeatedly.  I assume that's the intent of the test, but just wanted to be sure...

@permcody and @andrsd this is currently only used in one place, but would probably be handy in others.  What do you think of the idea overall; should we try to generalize it somehow, etc?

**Comment by WilkAndy** [comment]
Thanks @jwpeteron .   Yes, this SEGFAULT.i test is very contrived: it will repeatedly try to cut the timestep until it finally crashes at dt=1E-14.  It shouldn't be added to the test suite!

**Comment by jwpeterson** [comment]
> It shouldn't be added to the test suite!

That's fine, but if you could also test my patch on a "real" problem where you need to throw from `reinitMaterials()` and make sure it works, that would be appreciated...

**Comment by WilkAndy** [comment]
Unfortunately i still get the segfault, at the same place as before.  Perhaps my SEGFAULT.i test file is too simplistic.  However, there are other more realistic cases already in the test suite that you can play with:

tensor_mechanics/tests/capped_weak_plane/pull_and_shear.i

If you add the following line to the [./stress] Material:

max_NR_iterations = 1

you will experience the same segfault as above.

**Comment by jwpeterson** [comment]
> Unfortunately i still get the segfault, at the same place as before.

That's a bummer, if it's really at the same place as before, it means that swapping back materials actually had nothing to do the problem...?  I will take a look at the other example you mention.

**Comment by WilkAndy** [comment]
yea, it really is the same place as before (that std::vector _intnl variable).  Thanks for looking at this @jwpeterson

**Comment by jwpeterson** [comment]
I had a chance to look into this again, and it turns out the segfault was *not* coming from the same place as before, in the second test it was coming from `ComputeElemAuxVarsThread::onElement()` and using a similar "Sentinel" class there also fixes the issue.  @WilkAndy if you'd like to try it yourself you can pull the `cut_dt_segfault_7783` branch from my fork or look at the [commits](https://github.com/jwpeterson/moose/commits/cut_dt_segfault_7783).

In my mind, the remaining checklist for this Issue is:
- [ ] Apply the fix anywhere that `_fe_problem.reinitMaterials` is called.
- [ ] Come up with a generalized `SwapBackSentinel` utility base class, which can be customized for use in different places
- [ ] Add tests ensuring that this continues to work.

**Comment by jwpeterson** [comment]
This should be fixed over in #8059, we can continue the discussion over there if necessary.

**Comment by WilkAndy** [comment]
Thank you for fixing this "cut dt" problem, @jwpeterson .    It is a really important addition for me: now our long-running and large simulations won't just crash upon failure in the Material computations - they can cut the timestep instead.  Great!

**Pull request closed without merging**
