### PR TITLE
Change qp from private to protected in VolumetricModel

### LINKED ISSUE #7230: Move _qp from private to protected in VolumetricModel.h
### Description of the enhancement or error report
In `VolumetricModel.h`, replace 
```
private:
  using Material::_qp;
```

with
```
protected:
  using Material::_qp;
```

### Rationale for the enhancement or information for reproducing the error
This will allow the `Qp` methods such as `computeQpProperties` to be utilized in `VolumetricModel` which are already inherited from `Material`. This can replace looping over qp in `computeProperties`.

### Identified impact

None?

### PR DESCRIPTION
**Pull request by tophmatthews**
Changes `qp` from private to protected in `VolumetricModel`

Closes #7230

### CODE REVIEW

**Comment by friedmud** [comment]
Need to get some solid mechanics related eyeballs on this...

@dscwen
@jdhales
@bwspenc

**Comment by jasondhales** [comment]
I'm not sure why this would be needed.  It was set as private to prevent child classes from using it.  The way the VolumetricModel classes are called, _qp is not set to something useful.  That is why qp is sent into modifyStrain.

This will go away once we move from solid_mechanics to tensor_mechanics.

**Comment by tophmatthews** [comment]
I wasn't sure if there was a reason to have it as private or not or if it was just set and forgotten. There are materials in bison such as `VSwellingUPuZr` that loop over qp in `computeProperties` and `initStatefulProperties` which work fine, but are clunky. The `Qp` methods that are inherited are in place but unusable due to qp being private. Perhaps these materials should only be doing modifyStrain?

**Comment by jasondhales** [comment]
Yes, they are really meant only to modify the strain.  If you look at
SolidModel, you will see how they are used.  They perform a calculation at
a particular point in the larger algorithm that computes stress.  The
SolidModel calls them with its _qp.  They shouldn't be used is other ways.

This will be obsolete once we switch to tensor_mechanics.

On Wed, Jun 22, 2016 at 11:04 AM, Topher Matthews <notifications@github.com>
wrote:

> I wasn't sure if there was a reason to have it as private or not or if it
> was just set and forgotten. There are materials in bison such as
> VSwellingUPuZr that loop over qp in computeProperties and
> initStatefulProperties which work fine, but are clunky. The Qp methods
> that are inherited are in place but unusable due to qp being private.
> Perhaps these materials should only be doing modifyStrain?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_7232-23issuecomment-2D227792546&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=7D2q3wzFLegaqhNwgGCre_36SQzjt7FaETNbxhIXga4&s=IinPKcgIlej6eCWFp4VNTglI4RpMa4-WSNsECSUKWDE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe_AGTY3u6-5FadsB9G08bNNNgM2H7tMCyay9ks5qOV0cgaJpZM4I75k3&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=7D2q3wzFLegaqhNwgGCre_36SQzjt7FaETNbxhIXga4&s=p-pF_PJUS8T6maTlQTdyMVFYHOBYqyVzi8LRz87OZPE&e=>
> .
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Pull request closed without merging**
