### PR TITLE
shorten names of tests in distributed_rectilinear_mesh_generator

### LINKED ISSUE #15492: shorten names of tests in distributed_rectilinear_mesh_generator
## Reason

The name is, just so long, it ends up going beyond the max terminal width length.

## Design

Just remove redundancy letters 

## Impact
None

### PR DESCRIPTION
**Pull request by fdkong**
The name is, just so long, it ends up going beyond the max terminal width length.

Closes #15492

### CODE REVIEW

**Comment by fdkong** [comment]
@milljm Does it work now?

**Review by milljm — APPROVED** [review]
This works for me. Thanks!

Please know, that what we talked about earlier (about fixing the TestHarness), should also occur (and not just this PR). Something I will work on in due time.

**Comment by fdkong** [comment]
> Please know, that what we talked about earlier (about fixing the TestHarness), should also occur (and not just this PR). Something I will work on in due time.

Good to know! Thanks

**Comment by milljm** [comment]
Ref: #15494

**Pull request merged**
