### PR TITLE
Documents Markers

### PR DESCRIPTION
**Pull request by aeslaughter**
This is the what we need to do for all the systems in MOOSE, I need help with this.

The first step might be to add class descriptions to all objects in MOOSE. When this is completed the "build" step of the documentation generations should be green and we can start enforcing this function be defined.

The second step is to add real content to all the systems and objects.

The third step is to make new training slides.

The fourth step is to move all the other content from the old site into the new.

The fifth step is profit. 💰

### CODE REVIEW

**Comment by permcody** [comment]
As much as we like to enforce things I think this documentation system should be a little more forgiving. I'm supportive of requiring class descriptions for MOOSE and probably eventually the modules. I'm not so crazy about putting in empty stubs though the further away from MOOSE you get. I'd like this system to be flexible so people can either use it or not. We will enforce it in MOOSE but maybe not even in all the modules (for instance, what about modules which we don't create like Richards and Porous flow)? Can we make this system flexible so it can support partial documentation?

**Comment by aeslaughter** [comment]
Currently only MOOSE and tensor_mechanics are plugged into the system, we can incrementally add the others. I do think that in the end that everything in MOOSE and modules be plugged into the system, if is coming with MOOSE it should be documented completly. It will avoid the problem we are having now: a massive amount of undocumented code.

I would like to see MOOSE (and probably tensor_mechancis since they are working on it) be completely documented first. We then can enforce documentation (i.e., have a green "master"). Then we can figure out how to add the rest.

**Comment by aeslaughter** [comment]
The marker pages are "complete": http://mooseframework.org/docs/PRs/46534/site/content/framework/systems/Adaptivity/Markers/Overview/

**Review by permcody — CHANGES_REQUESTED** [review]
This PR now conflicts probably due to spacing issues. Let's get the rest of the MooseDocs stuff setup up with the standard spacing.

Thanks

**Comment by aeslaughter** [comment]
http://mooseframework.org/docs/PRs/46883/site/content/framework/systems/Adaptivity/Markers/Overview/

**Review by permcody — APPROVED** [review]

**Pull request merged**
