### PR TITLE
Decrease coverage requirement for scalar_transport

### PR DESCRIPTION
**Pull request by loganharbour**
Unity build config from #28588 changed this somehow. Still trying to figure out the root cause

### CODE REVIEW

**Comment by GiudGiud** [comment]
I ll add some tests for the new Physics. I think that was what did it

**Comment by hugary1995** [comment]
In theory #28588 should not have changed anything in modules other than solid_mechanics. At least that was my intent. It is weird that the coverage report in #28588 stated that modules coverage did not change.

**Review by grmnptr — APPROVED** [review]
Let's unbreak next!

**Comment by loganharbour** [comment]
Failures are unrelated.

**Pull request merged**
