### PR TITLE
Reinitialize geometric search when mesh changes, test with XFEM

### PR DESCRIPTION
**Pull request by bwspenc**
ref #6799

### CODE REVIEW

**Comment by bwspenc** [comment]
This makes the same small code change as was made in #6801, but in the interest of getting the code change that I really need in, this commit does not test adaptivity, but tests that this reinit works using XFEM, which we can do now that the recent material copy commit by @jiangwen84 got merged. I'd still like work out the issue with contact and adaptivity, but it's less urgent.

**Comment by bwspenc** [comment]
The test is failing in debug because of libmesh issue [#938](https://github.com/libMesh/libmesh/issues/938).

**Comment by dschwen** [comment]
Is this still needed?

**Comment by bwspenc** [comment]
Yes, this is very much needed.  The code works fine in opt, but I would love to get this checked in so we don't have to use a one-off modified version of MOOSE on these problems.  It fails in dbg because the deformed and undeformed meshes get out of sync during the process of reinitialization.

**Comment by permcody** [comment]
I'm going to close this PR despite it being needed. Keep the branch around and resurrect as needed. Just tidying up ahead of the assessment.

**Pull request closed without merging**
