### PR TITLE
Modification to error test because of stringify change

### PR DESCRIPTION
**Pull request by zachmprince**
Refs #23708

Should fix [https://civet.inl.gov/event/117135/](https://civet.inl.gov/event/117135/)

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Guess it was my fault then!

**Comment by GiudGiud** [comment]
Thanks for the fix

**Review by permcody — COMMENTED** [review]
Just a comment: in general you can protect yourself from whitespace changes by using RegExs in your patterns.
`... on the fine mesh:\s+2,\s*foo`

**Comment by GiudGiud** [comment]
I wouldnt recommend adding too much of these regex in the outputs. It s not fun to maintain

**Comment by GiudGiud** [comment]
if you do, make sure to include some text describing the regex a bit

**Pull request merged**
