### PR TITLE
let timestepper call the outermost solve

### PR DESCRIPTION
**Pull request by hugary1995**
ref #14486

### CODE REVIEW

**Comment by hugary1995** [comment]
@YaqiWang @permcody  I'm not sure if this is in alignment with your original design.

**Comment by YaqiWang** [comment]
Does a function in TimeStepper like setInnerSolve solve your problem? That way we treat TimeStepper more like a solve object.

**Comment by hugary1995** [comment]
@YaqiWang I understand that is your plan, but I don't completely see how to do that though. For now I think people need this change otherwise TimeStepper is always only calling PicardSolve's solve() method.

**Comment by YaqiWang** [comment]
If you make TimeStepper able to call setInnerSolve, Transient can use it to set PicardSolve as inner and you owe executioner can use it to set whatever solve object as the inner. We don’t want to hardcode this in solve object.

**Comment by hugary1995** [comment]
@YaqiWang Does this look better?

**Comment by YaqiWang** [comment]
Nah. You did not answer if adding `TimeStepper::setInnerSolve(SolveObject & solve)` and then calling it in `Transient::init` as `_time_stepper->setInnerSolve(_picard_solve)` can solve you problem or not. That is my preferred way. We want executioner to set the solve object. Here the solve object (time stepper) is grabbing something.

**Comment by hugary1995** [comment]
Okay I did not understand what you meant at first... I made the changes per your suggestions. I didn't guard against uninitialized solver in TimeStepper -- just let me know if that is necessary.

**Pull request closed without merging**
