### PR TITLE
Rayleigh damping and HHT time integration added to Solid Mechanics mo…

### PR DESCRIPTION
**Pull request by sveerara**
…dules StressDivergence.C and SolidMechInertialForce.C (#5537)

### CODE REVIEW

**Comment by jwpeterson** [comment]
Looks like your patch contains trailing whitespace, tabs, and `if(` statements that need spaces between the keyword and the parenthesis:
```
##########################################################################
ERROR: The following files contain trailing whitespace after applying your patch:
	./modules/solid_mechanics/tests/Rayleigh_damping/HHT_time_integration/rayleigh_HHT.i
	./modules/solid_mechanics/tests/Rayleigh_damping/Newmark_time_integration/rayleigh_newmark.i
	./modules/solid_mechanics/tests/Time_integration/HHT_time_integration/HHT_test.i
	./modules/solid_mechanics/tests/Time_integration/Newmark_time_integration/Newmark_test.i

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.

ERROR: MOOSE prefers two spaces instead of tabs. The following files contain tab characters:
	./modules/solid_mechanics/src/kernels/StressDivergence.C

ERROR: The following files contain control keywords without proper spacing (for, if, while, or switch)
http://mooseframework.org/wiki/CodeStandards:
	./modules/solid_mechanics/src/kernels/StressDivergence.C
##########################################################################
```

**Comment by jasondhales** [comment]
Swetha, do you need to commit the csv files?

**Comment by jwpeterson** [comment]
> Swetha, do you need to commit the csv files?

Looks like the new tests are Exodiff tests, so the CSV files shouldn't be necessary unless you plan to change them over to CSVDiff tests at some point.

**Comment by sveerara** [comment]
I have formatted the files to remove trailing white spaces and tabs and I
have also removed the .CSV files. Please let me know if I need to edit any
other files. Thanks!

**Comment by jwpeterson** [comment]
Looks good to me.  Unless @jasondhales has further comments, I will squash these commits down and merge them by hand.

**Comment by jwpeterson** [comment]
I'll also fix the deprecated constructors that got added...

**Comment by jwpeterson** [comment]
@sveerara, It looks like you have two copies of each of your tests.  The files:
```
Time_integration/HHT_time_integration/HHT_test.i
Rayleigh_damping/HHT_time_integration/Rayleigh_HHT.i 
```
are basically identical, as are:
```
Time_integration/Newmark_time_integration/Newmark_test.i
Rayleigh_damping/Newmark_time_integration/Rayleigh_Newmark.i
```
which version would you like to keep, the ones in Time_integration or the ones in Rayleigh_damping?

**Comment by sveerara** [comment]
The tests in Time Integration test only the two different time integration
schemes.

The tests in Rayleigh damping have two additional parameters zeta and eta
through which Rayleigh damping can be added along with the different time
integration schemes. So there is a minor different in the input files
between the tests in the Time integration and Rayleigh damping folder.

**Comment by jwpeterson** [comment]
I see.  OK, then I will keep both.

**Comment by jwpeterson** [comment]
Merged by hand in 6e04a1e

**Pull request closed without merging**
