### PR TITLE
Return mapping solver

### PR DESCRIPTION
**Pull request by bwspenc**
#6873

### CODE REVIEW

**Comment by bwspenc** [comment]
Pinging @jasondhales: I took what you had and added to it a bit.

**Comment by jasondhales** [comment]
It looks like CLSHPlasticModel needs exactly the same change as HyperbolicViscoplasticityStressUpdate.

**Comment by bwspenc** [comment]
@jasondhales Oh, I see -- I'll make that change.

**Comment by bwspenc** [comment]
I ran the assessment problems with this over the weekend, and am getting a few failures, so don't merge this yet.

**Comment by bwspenc** [comment]
This passes the BISON example that was giving us trouble.  I think I have the issues with the assessment problems resolved, but I'm waiting for those to finish running to verify.

**Comment by bwspenc** [comment]
I've run the BISON assessment problems with these changes, and there are no issues, so this is ready to go as far as that is concerned.

**Review by dschwen — COMMENTED** [review]
Looks good. My only comment would be to drop the references for const primitive data types and have them passed by value.

**Comment by bwspenc** [comment]
@dschwen I just added a commit to this PR that converts all passing primitives by reference to passing by value in that class.

**Review by dschwen — APPROVED** [review]

**Pull request merged**
