### PR TITLE
Do not compute residual before PresetBC

### LINKED ISSUE #13264: Residual gets computed before PresetBCs are applied even if `_compute_initial_residual_before_preset_bcs == false`
## Bug Description
A residual gets computed before PresetBCs are applied even if the bool flag _compute_initial_residual_before_preset_bcs` is `false`. This flag currently only toggles output of this residual to the screen. Later on the value of `_initial_residual_before_preset_bcs` is not uses though.

## Steps to Reproduce
Look at `NonLinearSystem.C:194`

## Impact
Reducing the number of residual evaluation (in the limited cases where  `_compute_initial_residual_before_preset_bcs == false`)

### PR DESCRIPTION
**Pull request by dschwen**
Let's see if this breaks anything.

Closes #13264

### CODE REVIEW

**Comment by dschwen** [comment]
Sigh `Executioner/compute_initial_residual_before_preset_bcs` defaults to `false`.

**Comment by dschwen** [comment]
Some tests simply exodiff because they CSV diff the number of residual evaluations. I'll regold those.

**Comment by permcody** [comment]
It seems like this option shouldn't even exist? Can somebody give us a good reason why we'd ever want to do this? Doesn't this just allow us to "cheat" on our convergence criteria?

**Comment by permcody** [comment]
Maybe @bwspenc has some insight?

**Comment by dschwen** [comment]
This isn't over, stale bot! @bwspenc , can you comment?

**Comment by lindsayad** [comment]
Yea this has always seemed stupid to me

**Pull request closed without merging**
