### PR TITLE
Add 2D FE example for laser welding.

### LINKED ISSUE #26909: Add 2D finite element-based laser welding example.
## Reason
We only have a 3D finite element example whose execution can be computationally demanding.
The 2D hybrid finite volume and element example is not realistic at this point.

## Design
Simplify 3D example into 2D.

## Impact
Simpler model for parameter studies.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #26909

### CODE REVIEW

**Review by lindsayad — APPROVED** [review]
this looks good to me, do you have any pretty pictures for the PR?

**Comment by hugary1995** [comment]
lol, I opened a PR #26926 before realizing the existence of this one. Even though we both mention the word "welding", we are solving for different physics... Just clarifying that #26926 is not related to @lindsayad 's suggestion above.

**Comment by GiudGiud** [comment]
@grmnptr I cant assign you to the PR smh
can you assign yourself?

**Comment by grmnptr** [comment]
Screenshot 2024-02-22 at 9 02 06 PM

**Comment by GiudGiud** [comment]
is pressure interesting for this? just curious. I dont expect so

**Comment by grmnptr** [comment]
Yeah not too much, but I am not an expert.

**Comment by lindsayad** [comment]
merge when ready

**Pull request merged**
