### PR TITLE
Changed aux kernel default 'execute_on' to include 'TIMESTEP_END'

### LINKED ISSUE #11798: Aux variables are now lagged in output for solve_type=LINEAR
## Rationale
As of PR #11768, aux variables are lagged in output by a time step for `solve_type=LINEAR`. The default `execute_on` for aux kernels is `LINEAR`, but before removing the SNES monitor residual evaluation, we were effectively adding `TIMESTEP_END` to the aux kernel.

## Description
See the attached input file, modified from `test/tests/dgkernels/1d_advection_dg/1d_advection_dg.i`:

[1d_advection_dg.txt](https://github.com/idaholab/moose/files/2160941/1d_advection_dg.txt)

I simply added an aux that copies the solution variable. It should be in sync, but you'll find it's not. Note that I also changed the time integrator, but explicit Euler is not necessary to produce the issue. I just did this to make the lagging clear since with the 2-stage time integrator that was there before, you'd actually be seeing the intermediate stage solution, not the previous time step solution, so the issue was less apparent.

## Impact

Fix.

### PR DESCRIPTION
**Pull request by joshuahansel**
A number of exodiff tests failed:
- ics/dependency/monomial: Gold file was confirmed wrong; aux output was lagged.
- utils/random/random: Results were shifted because the random auxes would output
  twice at the end of time step, altering the random-number generator.
- modules/porous_flow/examples/tutorial/11_2D: Confirmed output was incorrect before and re-golded.
- modules/tensor_mechanics/weak_plane_shear/small_deform.*: Confirmed output was incorrect before and re-golded.

Closes #11798

### CODE REVIEW

**Comment by joshuahansel** [comment]
I would not be surprised to see multiple application failures due to this change. This should typically indicate that aux variables were golded incorrectly, but I would be interested to see if there are additional failures.

Tests that I expect to fail are:
- tests using `solve_type = LINEAR` that output aux variables
- tests using `solve = false` that output aux variables
- tests using random number generators for auxes

For all other tests, I do not expect them to fail here, but maybe I'm missing something. Auxes currently have a default `execute_on` of `linear`, which means that they get executed at the end of time step already if a solve evaluates the nonlinear residual at the end of the time step (due to SNES monitor). `solve_type = LINEAR` no longer has this monitor, and `solve = false` does not have this monitor, hence the potential diffs for these options. Otherwise, if an aux's values change due to back-to-back evaluations, then I suspect this indicates a bug (perhaps there is some faulty dependency resolution or some data being abused in the aux kernel).

2 tests in the framework failed, and their failure is understood.

Multiple tests in modules failed as well, but these are not understood, and their failure is suspicious; it could indicate something wrong in those tests. These tests are in `porous_flow` and `tensor_mechanics` (see changed files/commit message for which ones). @WilkAndy I saw your name in the logs for these files - could you investigate? The failures could indicate bug(s). Otherwise, it'd be helpful to know how they aren't bugs.

**Comment by joshuahansel** [comment]
@bwspenc Any idea why the Bison tests might be failing?

**Comment by WilkAndy** [comment]
Heavy tests:

modules/porous_flow/examples/tutorial/gold/11_out.e needs to be re-golded.  The result from this PR is correct.  I actually never realised the old version was wrong!

porous_flow/test/tests/broadbridge_white/rd02.i timed out.  Actually MOOSE appeared to complete (the final time step reported "Solve Converged!") so perhaps the Exodiff caused the timeout.  The nonlinear residuals at each timestep are identical to what i have on my computer, suggesting there will be no problems with this test if the timeout problem is rectified.

**Comment by WilkAndy** [comment]
OK good, there are no modules failures now: green tick :-)

**Comment by WilkAndy** [comment]
I don't know how to see the failures of the porousflow/tensormech tests without downloading this branch and recompiling, which i don't really have time to do at present.  i'm not convinced you need to include the "execute_on = linear" stuff in those tests.  It could be simply that the old gold files were wrong (like that porousflow heavy test mentioned above).  Could you somehow show me the failures that you encountered before making the changes to the tests?

**Comment by joshuahansel** [comment]
Just to be clear, you didn't see any failures in modules because I manually inserted `execute_on = linear` for those tests to produce the old behavior (so see which tests I did this for). I probably should have just let them fail - in the end, we need to decide for each whether their output is wrong or if there are bug(s). For some rare cases such as the `RandomAux`, it's fine not to re-gold but just keep the old defaults. Anyway, I'll remove the `execute_on = linear` so that you can see the failures.

**Comment by joshuahansel** [comment]
For the Bison tests, `MaterialRealAux` seems to be common to the 3 failing tests. In each test, this aux kernel is the only one taking a default `execute_on`, so it appears there is some kind of dependency resolution issue to blame.

For the modules tests, I noticed that `RankTwoAux` and `MaterialRealAux`/`MaterialStdVectorAux` seem to be common to the failed tests.

**Comment by joshuahansel** [comment]
Ok, I'll re-gold those tests. Thanks for your help!

**Comment by joshuahansel** [comment]
The Bison tests should now be fixed.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
