### PR TITLE
Fixed valgrind VecSetDM

### PR DESCRIPTION
**Pull request by fdkong**
https://github.com/libMesh/libmesh/pull/2543

I need to check if `VecSetDM` is Valgrind clean with both `PETSc-3.12` and `PETSc-3.13`

### CODE REVIEW

**Comment by lindsayad** [comment]
This is going to hit very few test targets unless you also change the conda recipes

**Comment by lindsayad** [comment]
Moreover, the valgrind targets use conda

**Comment by fdkong** [comment]
It should test `valgrind` with PETSc-3.12.5.

And now I am going to add a recipe (optional) to `valgrind` petsc submodule

**Comment by lindsayad** [comment]
You could let me do this in the libmesh update PR...if you need more chagnes you can push to that

**Comment by fdkong** [comment]
> You could let me do this in the libmesh update PR...if you need more chagnes you can push to that

Do what?

**Comment by fdkong** [comment]
We have to use conda when we want to use valgrind?

**Comment by fdkong** [comment]
see https://github.com/idaholab/moose/pull/15182

**Pull request closed without merging**
