### PR TITLE
Use std::upper_bound to improve bracket searching efficiency; 

### LINKED ISSUE #24254: LinearInterpolation O(N) to O(log2(N)) improvement
## Reason

The current `LinearInterpolation::sample` function uses loops the x-vector from begin to end to find the correct bracket for interpolation. This is a O(N) algorithm and can be improved to O(log2(N)) using standard C++ features/functionalities.

## Design

Standard C++ features/functionalities, such as `std::lower_bound`, can be used to bump up the algorithm efficiency to O(log2(N)).

## Impact

Performance improvement, especially when the x-vector size is large.

### PR DESCRIPTION
**Pull request by lingzou**
This PR Closes #24254.

## Design

Between `std::upper_bound` and `std::lower_bound`, the former matches the best with the original code implementation.

### CODE REVIEW

**Comment by lingzou** [comment]
@lindsayad Seems to me the failed test cases are unrelated and random(?).

One failed test (exodiff):
modules/heat_conduction/test/tests/truss_heat_conduction/block_w_line.i
does not seem to use linear interpolation at all.

Another failed test:
test/tests/misc/signal_handler/simple_transient_diffusion_scaled.i
is similar, not using linear interpolation.
The error message is:
```
*** ERROR ***
The following error occurred in the object "Executioner", of type "Transient".
Internal error in Transient executioner: _t_step is equal to 0 while recovering in init().
```

Should I send an empty commit let them rerun?

**Comment by lindsayad** [comment]
Once we get a next to devel merge I will invalidate these targets and most of them should pass (the block with line one may still fail, we will see)

**Review by lindsayad — APPROVED** [review]
Thank you for the algorithm improvement @lingzou !

**Comment by lingzou** [comment]
> Thank you for the algorithm improvement @lingzou !

Glad to contribute, and thanks for the review.

**Pull request merged**
