### PR TITLE
Inverse logic

### LINKED ISSUE #7359: Inverse logic for checks in TestHarness
### Description of the enhancement or error report

It'd be nice to be able to specify inverse logic for some of the tests in the TestHarness instead of enumerating all of the allowed targets.

```
method = 'OPT OPROF DEVEL ...'
method = ''!DBG'
```

### Rationale for the enhancement or information for reproducing the error

More options, better maintainability for tests over time

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

All test suites

### PR DESCRIPTION
**Pull request by permcody**
Adds new capability to the TestHarness for inverse logic in checks.

Let's make sure this works for everything and we aren't just skipping every test before merging mkay?

closes #7359

### CODE REVIEW

**Comment by andrsd** [comment]
I was thinking about this once, but abandoned it because of multiple negation. The solution? Let's not allow it! 😃

**Comment by dschwen** [comment]
I wouldn't be true to myself if I didn't say let's not prohibit not doing
it.

**Comment by andrsd** [comment]
When people say:
```
method = '!DBG OPT'
```
They will get:
```
Multiple Negation Unsupported
```

This is misleading, it is not really multiple negation...

**Comment by permcody** [comment]
Agreed, but that expression is also just unnecessary. I'll improve the
error message.

**Comment by andrsd** [comment]
Yes, but people make mistakes. Theoretically, it should not error out for that expression at all.

**Comment by jwpeterson** [comment]
> I wouldn't be ~~true~~ not false to myself if I didn't say let's not prohibit not doing it.

**Comment by permcody** [comment]
Comments addressed

**Pull request merged**
