### PR TITLE
Make MOOSE error when duplicate Scalar variables are added

### LINKED ISSUE #9313: Adding a scalar variable explicitly and through an action should not be allowed
### Description of the enhancement or error report
It is currently possible to add the same scalar variable explicitly and through an action.  This triggers an assertion failure (at least in one case) with dbg but will run in opt.  Should catch this and report an error.

### Rationale for the enhancement or information for reproducing the error
Improved user experience.  I have  Bison input file that demonstrates this.

### Identified impact
Improved user experience.

### PR DESCRIPTION
**Pull request by permcody**
Also error when duplicates have conflicting type
closes #9313

### CODE REVIEW

**Review by andrsd — COMMENTED** [review]
I thought you wanted to throw an error message when a variable of the same type was added twice.

**Comment by permcody** [comment]
Yeah I said that. However, I realized when I got in there that the existing
code allowed that by just returning early which is fine. It was already
doing that for both nonlinear and aux variables. The problem was that that
same logic wasn't in place for the scalars. I'm fine with not throwing and
error as long as we don't do something just plain wrong.

**Comment by andrsd** [comment]
Maybe we should throw a warning for this case. If an action is adding a variable "A" and people have the same variable name in their input file, they should be notified about it. It can potentially be a problem.

**Comment by permcody** [comment]
Sounds good. It'll be interesting to see if we have any existing
regressions.

**Comment by permcody** [comment]
@andrsd - Did you see the number of failures? It's astronomical. Apparently we routinely add the same variable multiple times when using Actions. I don't feel strongly about fixing this right now. I'm going to pull the waning out so we can at least merge in the fix for the reported problem.

**Comment by andrsd** [comment]
> Did you see the number of failures?

Yeah, I saw it. I even looked what caused it. For example, tensor mechanics uses an action that can add displacement variables. It was a new feature, the original one was not doing it. So when they turned that on, they did not remove the `[Variables]` block from an input file. 👎

**Comment by dschwen** [comment]
Where can I see the failures?

**Review by andrsd — APPROVED** [review]

**Comment by andrsd** [comment]
> Where can I see the failures?

https://www.moosebuild.org/job/95003/

**Comment by andrsd** [comment]
BTW: @permcody is opening an issue to fix the input files

**Pull request merged**
