### PR TITLE
New warehouse base class and Controls are a first-class system

### PR DESCRIPTION
**Pull request by aeslaughter**
Implements a new warehouse base class for wrapping
threaded and execute based storage including the ability
to toggle objects as inactive via Controls.

(refs #5680)

### CODE REVIEW

**Comment by permcody** [comment]
As a first pass I have to say that there's too much in this PR. You are basically proposing new classes to replace both `ExecStore` and `Warehouse` along with a bunch of new Control Logic stuff. I guess I'd like to see this split into two because the former is a huge chance to MOOSE and we need to talk it over and make sure we are all on the same page. I can see the advantage of combining or improving the design of the `ExecStore` and the `Warehouse` base class but we should probably chat about the current shortcomings a bit.

**Comment by aeslaughter** [comment]
@permcody While I would love to break this up, that is not an easy task. (I tried and failed). The driving factor behind all of this was to be able to have a Control object that can disable/enable any object. In order to do this, there needs a uniform warehouse design and all the systems need to use it. I started with the simplest and most unused system (Dampers) to demonstrate the concept. 

I am open to discuss the design further, but breaking this up will take more time than it is worth, in my opinion. This only took me a few days to put together, so I am fine with re-tooling it and changing it to meet our needs, but don't want to spend days trying to break this up to just re-combine them in the future.

**Comment by permcody** [comment]
I really don't want to merge this as is since it creates duplicate classes with similar functionality
`Warehouse` <=> `WarehouseBase`
`ExecStore` <=> `ExecuteOnStorage`

In fact, I kind of want to put the brakes on a bit on this whole Control Logic activity. I suggest making sure we have the pieces we need to support the Relap-7 efforts and pause there for now.

**Comment by aeslaughter** [comment]
I am working on this, so closing for now.

**Pull request closed without merging**
