### PR TITLE
Add an accessor to console system info flags

### LINKED ISSUE #6102: Need to access Console::_system_info_flags
so that application can turn on/off some screen print-out pragmatically instead of always doing it through input. This will be an one line accessor.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close  #6102.

### CODE REVIEW

**Comment by permcody** [comment]
I just want to note that this change is not quite as innocuous as it looks. Giving the user a writable reference to the `MultiMooseEnum` can certainly cause breakage if the users overwrites the value. If it is set too late during the setup (which is quite early in this case), the result may be more maddening as nothing will happen at all...

If you want to prevent the later case from occurring, you might use set a Boolean to indicate when the data has been used so that a call to retrieve the reference would fail with a useful error message.

**Comment by YaqiWang** [comment]
Actually `_system_info_flags` is fully constructed in the constructor. So mutating it should be always ok. It will have not effect if the application is trying to change it after system info has been written. Am I understanding correctly?

**Comment by permcody** [comment]
I was worried more about changing the value too late. You might wonder why
nothing happens. It wouldn't create a bug, just an annoyance.

**Comment by YaqiWang** [comment]
Only advanced developers will use this accessor, so I am not so worried about the late changing. But I will add a Boolean as your wish. BTW, do you want me add a const accessor for this as well?

**Comment by permcody** [comment]
While I agree it's not a big deal, we are in the business of building a framework and the more ways we can protect users from themselves, the better. In this case, the opportunity to set those flags is very brief so almost any user that just tries to play with it, will likely fail to accomplish what they think should happen. I know that you aren't that user. :smile:

**Comment by permcody** [comment]
:+1:

**Pull request merged**
