### PR TITLE
Adding a mooseException macro

### LINKED ISSUE #3777: Proper Exception Handling
Ok - time to finally get this right.

Here's what we're going to do:

1.  Users will throw Exceptions when something goes wrong in their models.
2.  Those Exceptions will be caught _locally_ within the threaded loops (propagating exceptions across threads is ridiculous).
3.  When caught in a thread (in `ThreadedElementLoopBase`) it should call something like `_fe_problem.setException()` or whatever to set a flag that there has been an exception.
4.  Threaded element loop will check that flag and `break` if it's set.
5.  Outside the `ThreadedElementLoop` we will do an MPI "max" or whatever to get the flag across processors (note: We do not care that other processes will have kept running _their_ threaded element loops while the one processor that had an exception is hanging around waiting on them).
6.  If the MPI max comes back showing that a processor had an exception then the MOOSE code itself will throw a _new_ exception (to unwind out of some place a few levels down in `computeResidual()`).
7.  `computeResidual()` will have a try/catch wrapped around it.
8.  When `computeResidual()` catches an exception it will call `SNESSetFunctionDomainError()` (to end the iterations)
9.  Profit??

Once this is finished we should be able to close these (And maybe more):
#2049
#2225
#2269

### PR DESCRIPTION
**Pull request by permcody**
closes #3777

### CODE REVIEW

**Comment by permcody** [comment]
@cpritam - Take a look at this PR. I'm adding a macro "mooseException" that works just like "mooseError" except it throws and exception which causes the solve to stop and a reduction to the timestep size. After this is merged, see if it works in your "random matrix" case.

**Comment by friedmud** [comment]
:+1:

**Comment by friedmud** [comment]
Actually... should we automatically color the messages of MooseException Red as well?

**Comment by permcody** [comment]
Oh yes we should... We have more work to do here to debug a few things but
we'll look at that after all this writing is done!

**Pull request merged**
