### PR TITLE
Update openmpi container, container cleanup

### LINKED ISSUE #28356: Use openmpi for app containers
### Motivation

We've shown many issues with mvapich on HPC and have had greater success using openmpi instead.

### Design

Use moose-dev-openmpi as the base for application containers, and update openmpi.

### Impact

Improves HPC application containers.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes https://github.com/idaholab/moose/issues/28356

- Updates base container for moose-dev-mpich and moose-dev-openmpi to rocky 8.9
- Updates moose-dev-openmpi to openmpi 5.0.5
- Cleans up profile prompt

### CODE REVIEW

**Review by milljm — APPROVED** [review]
This looks good to me

**Review by milljm — APPROVED** [review]

**Comment by loganharbour** [comment]
Failure is an additional recipe that was just for testing.

**Comment by lindsayad** [comment]
How did this not break the versioner testing? The influentials for mpi definitely changed which I'm seeing as I prepare https://github.com/idaholab/moose/pull/28411

**Comment by loganharbour** [comment]
> How did this not break the versioner testing? The influentials for mpi definitely changed which I'm seeing as I prepare #28411

Because I failed to add it to versioner testing

**Comment by lindsayad** [comment]
so the only way to fail that test is to update it and update it incorrectly 😄

**Pull request merged**
