### PR TITLE
Almost ready to start parallel distributed mesh testing

### PR DESCRIPTION
**Pull request by permcody**
Just finishing up @roystgnr's PR. We should be able to turn on parallel distributed mesh testing after this PR goes in to avoid more regressions.

### CODE REVIEW

**Comment by roystgnr** [comment]
Wait, we should?  I've still got a dozen or so tests failing on 12 processors, my "just force those all to replicated and figure them out later" plan got stymied by Derek's (quite reasonable!) request for corresponding assertions in the code to protect users of the same features, and trying to find *where* to put those assertions has been taking me forever.

**Comment by permcody** [comment]
Yeah. Let's just turn it on for 2 procs. That get us baselined and prevent
backwards "progress". There are still several objects that will need work
to go to distributed mesh but we'll deal with them as we need them.

**Comment by roystgnr** [comment]
That's a very good idea.  We'll just have to be wary about false positives in that case: we may see PRs which don't actually revert any DistributedMesh support, but which change a common case to a corner case and thereby expose one of the remaining bugs elsewhere.

**Comment by roystgnr** [comment]
And needless to say I'll want to crank up the processor count on those tests as soon as can I can support doing so... false negatives are a huge concern at only 2 procs.

**Review by roystgnr — APPROVED** [review]

**Comment by permcody** [comment]
Agreed, this is going to be an ongoing process. I suspect that several
tests (especially in the modules suite) aren't very reliable on more than 2
processors, let alone distributed mesh.

**Comment by permcody** [comment]
@brianmoose - It's time to turn on distributed mesh testing with 2 procs. After this merges in, let's do that for MOOSE/test.

**Comment by brianmoose** [comment]
To be clear, you want to change the current args from
`--distributed-mesh` to `--distributed-mesh -p 2` on all the different recipes that currently have distributed mesh. Right?

**Comment by permcody** [comment]
Yes

**Pull request merged**
