### PR TITLE
Redesign the attribute reporter in executioners

### LINKED ISSUE #14293: Redesign Executioner::addAttributeReporter
## Reason
`Executioner::addAttributeReporter` is used to push a variable owned by `Executioner` into postprocessors, thus outputted automatically in `Output` system. However, the `execute_on` makes it a little hard to use. Even we change the value of the variable in `Executioner`, the value is not immediately transferred to postprocessor values and possibly not updated in outputs.

## Design
I propose to change the design a little here. We use `Receiver` to add a postprocessor and return the postprocessor value reference to `Executioner`. `Executioner` is adding the postprocessor and responsible for evaluating the value. This will make the other systems directly see the up-to-date values. This is the class doc of `Receiver`
```
 * A class for storing data, it allows the user to change the value of the
 * postprocessor by altering the _my_value reference
```
which is exactly what we want. We did not go this route in the past because we do not want to have a writable reference, but since we are doing it anyway, I think we should change the design here.

## Impact
Give Executioner a little more power and should not impact current capabilities.

### PR DESCRIPTION
**Pull request by YaqiWang**
Refer to #14293.

### CODE REVIEW

**Comment by YaqiWang** [comment]
The only failing is of course Rattlesnake, MAMMOTH. I have patches ready for them. I think this is a better design. It reduces the amount of codes quite a bit. I do not think any sane users will abuse this simple capability.

**Comment by YaqiWang** [comment]
@permcody as you suggested, I added back the original function so this PR won't break applications. Once moose submodule update is pushed to applications, I will patch applications and then submit a following PR in MOOSE to finally remove the original function.

**Comment by YaqiWang** [comment]
@permcody The approach of keeping the original function is not going to work because it is how to use the new interface function that is breaking the applications... We will have to merge this first and go through the painful manual update.

**Comment by permcody** [comment]
Why not give the function a new temporary name then? That way it's just a new API that is unused and will pass all testing. Then you can go through and update each application at will to use the new API. After everyone is using the new API, you can put in another PR to change the name of the original API to match the new one if you want, or you can just remove it. Are you absolutely sure that you can't get this through? This is really bad timing as we are trying to roll out the new package today/tomorrow.

**Comment by YaqiWang** [comment]
I tried and realized we cannot get this through without breaking Rattlesnake. I will explain to you in person.

**Comment by permcody** [comment]
Well try to merge this tomorrow... (on 11/6)

**Comment by YaqiWang** [comment]
Let me give one more try, maybe I can patch MAMMOTH first so that I can push the changes in MOOSE.

**Comment by YaqiWang** [comment]
Sorry, impossible. I will need this being merged first and patch applications.

**Comment by permcody** [comment]
OK - will get to it later today.

**Comment by permcody** [comment]
Let me know when you are in and we can start the painful process of getting this in. Hopefully you've set aside your whole day for pain and suffering - cheers 😄

**Comment by YaqiWang** [comment]
I am ready.

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
1. Put up your patch to Rattlesnake with the MOOSE submodule update (to "next"), let it test and make sure the Rattlesnake testing works. The downstream apps will fail.
 2. Merge Rattlesnake 
 3. Patch Mammoth, Sabertooth, BlueCrab and Direwolf updating all of their submodules but make sure that Rattlesnake is pointing to "devel" and MOOSE is pointing to "next" in each of these applications.
 4. Merge all four of these and let them test and merge through to master
 5. Go back and invalidate the Rattlesnake downstream target and let it merge through to master.
 6. Go back and invalidate the MOOSE internal apps target.

**Comment by YaqiWang** [comment]
Got it. On Rattlesnake MR to devel now, then will be on MAMMOTH MR to devel, then on Sabertooth, BlueCrab, Direwolf simultaneously from MR to master, then back to MAMMOTH, Rattlesnake simultaneously from devel to master, then back to MOOSE from next to devel.

**Comment by permcody** [comment]
Let me know when Rattlesnake is merged (or if you need me to merge it).
Then I can help you update Direwolf or anything else you need.

**Comment by YaqiWang** [comment]
... Rattlesnake devel is currently broken.

**Pull request merged**
