### PR TITLE
Update libmesh.

### PR DESCRIPTION
**Pull request by jwpeterson**
~~This tests the recent changes on @roystgnr's rereoptimize_projections branch, to see if it will allow us to get back on libmesh master in MOOSE.~~

This is now an attempt to update to a newer version of libmesh in MOOSE, but still with _all_ of the various the system_projection stuff reverted, dating back to October, 2015.  Making this revert has gotten progressively more difficult as more and more changes have been piled on top of each other; I'm not even really sure I'm doing it correctly at this point.  It would be great if we could get the one test that is still failing in `--recover` mode (see discussion in this ticket) working with libmesh master again...

Summary of changes in this libmesh update:
- Fix dimension==0 bug in MeshGeneration::build_sphere()
- Removed pthread_unique_id() from Threads.
- Add libmesh_nullptr, wraps C++11 std::nullptr.
- Introduce and mark several classes as libmesh_final, a wrapper for C++11 "final" keyword.
- Misc. fixes to code which touches unique_ids.
- Add various unit tests for slit meshes, also relevant to overlapped meshes.
- Optimize various Elem::volume() routines.  Some are over 100x faster than before.

Refs #000.

### CODE REVIEW

**Comment by jwpeterson** [comment]
@roystgnr Nice! The modules dbg target now passes whereas it did not before.

Looks like the issues with Yak remain but IIRC they are due to something with changes to elem_dims in Mesh and `prepare_for_use` possibly not being called.  We are not at work today, but I will get together with @YaqiWang next week and nail this down with him.

The PR TBB test failure is a new one for me and might be unrelated, I'm going to try invalidating it...

**Comment by roystgnr** [comment]
The TBB failure was in geomsearch/nearest_node_locator.adapt (which appears to be using UniformMarker, so not actually AMR)?  So it is technically possible that there's a regression here in the projection step, although I can't see how.

**Comment by jwpeterson** [comment]
Looks like the same test (and only that one test) failed again so I'd say it's not random.  Note that it failed while attempting to recover (moose_test-opt -i adapt.i --recover) and somehow the solution file is completely different from the gold, not sure how changes to the projection system would cause that...
```
Reading first file ... 
Reading second file ... 
  FILE 1: /home/moosetest/civet/client_root_1/moose/test/tests/geomsearch/nearest_node_locator/gold/adapt_out.e-s003
   Title: adapt_out.e-s003
          Dim = 2, Blocks = 2, Nodes = 1554, Elements = 1424, Nodesets = 4, Sidesets = 4
          Vars: Global = 0, Nodal = 2, Element = 1, Nodeset = 0, Sideset = 0, Times = 1

  FILE 2: /home/moosetest/civet/client_root_1/moose/test/tests/geomsearch/nearest_node_locator/adapt_out.e-s003
   Title: adapt_out.e-s003
          Dim = 2, Blocks = 2, Nodes = 1354, Elements = 1196, Nodesets = 4, Sidesets = 4
          Vars: Global = 0, Nodal = 2, Element = 1, Nodeset = 0, Sideset = 0, Times = 1
```

**Comment by roystgnr** [comment]
I can't see how *any* changes should cause that.  Am I misinterpreting UniformMarker?

**Comment by jwpeterson** [comment]
> I can't see how any changes should cause that. Am I misinterpreting UniformMarker?

No, I think you're interpreting it incorrectly, it should just do uniform refinement.  The special things about this test are that the initial grid has two subdomians that partially overlap one another, and we are testing recovering (hence reading in a solution from file).  So I suppose it's also possible that some of the recent unique_id change could be the cause?  The most recent round of unique_id changes (merged in libMesh/libmesh@53edc4c) are not yet in the version of libmesh used by MOOSE -- they are being brought in by this update.

**Comment by roystgnr** [comment]
Reading in is unthreaded, though, and it's only the TBB runs that are dying here, right?

**Comment by jwpeterson** [comment]
TBB is a red herring.  The failing test is not running threaded, we are just calling it that now to differentiate it from the pthreads testing.

**Comment by roystgnr** [comment]
So what differentiates the failure from the "make test" that works for me and in the libMesh PR?  Just the --recover option?

**Comment by roystgnr** [comment]
Just the --recover option.  And very easy to replicate.

**Comment by roystgnr** [comment]
But very hard to bisect.  The "good" news is that https://github.com/libMesh/libmesh/commit/fe4edd569634ef972494070c14cfccdb75083f5a fails too, so the unique_id PR isn't at fault.

**Comment by roystgnr** [comment]
Hmm.. and that also implies the rereoptimization isn't at fault.  I'll merge that now, and see if I can spare more time to hunt down this failure this weekend.

**Comment by roystgnr** [comment]
libMesh/libmesh@214974a fails too

**Comment by roystgnr** [comment]
libMesh/libmesh@7de27db fails

**Comment by roystgnr** [comment]
libMesh/libmesh@6d190d2 fails

**Comment by roystgnr** [comment]
And libMesh/libmesh@62fdf8c works.  In other words, the original projection refactor is the regression.

Annoying.  I was actually expecting (and surprised by the lack of) possible LAGRANGE regressions at that time, since interpolation vs L2 projection aren't equivalent.  But now that we're wholly back to interpolation we should be getting identical results with master again.  I think it may be printf debugging time.

**Comment by jwpeterson** [comment]
> Looks like the issues with Yak remain but IIRC they are due to something with changes to elem_dims in Mesh and prepare_for_use possibly not being called. We are not at work today, but I will get together with @YaqiWang next week and nail this down with him.

FYI @roystgnr, @snschune and I nailed this down to a `MeshModifier` in Yak that added lower-dimensional elements.  Throwing a `prepare_for_use()` in fixed the issue.  So if we can just get that last `--recover` test case fixed up, we'll be golden.

**Comment by permcody** [comment]
Why are you always preparing? Just go!

**Comment by jwpeterson** [comment]
> Why are you always preparing? Just go!

I'd love to but it causes a segfault.

**Comment by permcody** [comment]
:+1: - This contains the packed range code so I'm happy with this.

**Comment by permcody** [comment]
Hold onto your :horse:!

**Pull request merged**
