### PR TITLE
Add hover capabilities to MooseServer for input documentation

### PR DESCRIPTION
**Pull request by brandonlangley**
refs #22766

https://github.com/idaholab/moose/assets/21372118/ca5f85c6-1b1d-4a16-b447-a7ca495c5690

### CODE REVIEW

**Comment by brandonlangley** [comment]
@dschwen -

This adds MooseServer hover support for all available input documentation types:

- hovering on valid keys presents their parameter documentation strings

- hovering on registered object type values presents class descriptions

- hovering on values that are any enum type presents item documentation

I have tested all these scenarios in MooseServerTest and your VS Code extension.

https://github.com/idaholab/moose/assets/21372118/55809021-3a4a-4140-8e1d-9bbe3203d11e

Would you do a review for this small change set and then merge it if you approve?

Also pinging @loganharbour - I cannot see the failing test, can you see what it is?

**Comment by loganharbour** [comment]
@brandonlangley can you rebase this on devel please. You need to pick up some changes, which will also result in needing to change the hash in the versioner test (because your commit history would change)

**Comment by brandonlangley** [comment]
> @brandonlangley can you rebase this on devel please. You need to pick up some changes, which will also result in needing to change the hash in the versioner test (because your commit history would change)

@loganharbour -

I just rebased on devel, updated the hash in the versioner test commit, and force-pushed back.

The complete [pipeline](https://civet.inl.gov/event/169683/) of CIVET jobs did seem to pass prior to pulling in these changes though.

**Comment by milljm** [comment]
> > @brandonlangley can you rebase this on devel please. You need to pick up some changes, which will also result in needing to change the hash in the versioner test (because your commit history would change)
> 
> @loganharbour -
> 
> I just rebased on devel, updated the hash in the versioner test commit, and force-pushed back.
> 
> The complete [pipeline](https://civet.inl.gov/event/169683/) of CIVET jobs did seem to pass prior to pulling in these changes though.

Sometimes both of these targets can be finicky. I am invalidating them now...

**Review by dschwen — APPROVED** [review]

**Comment by brandonlangley** [comment]
@milljm @loganharbour -

This PR (approved by @dschwen and ready to merge) makes this update to `framework/doc/packages_config.yml`:

```diff
- moose_dev: 2024.01.23
+ moose_dev: 2024.03.01
```

which supersedes this soon-outdated change in https://github.com/idaholab/moose/pull/26958 from @milljm to `framework/doc/packages_config.yml`:

```diff
- moose_dev: 2024.01.23
+ moose_dev: 2024.02.19
```

Since this PR is ready to go, I just wanted to check if you'd rather just merge this and drop https://github.com/idaholab/moose/pull/26958.

That way we wouldn't first merge https://github.com/idaholab/moose/pull/26958, then need to rebase this PR to fix the new conflict, before merging this.

Apologies for not updating the `moose_dev` version in `framework/doc/packages_config.yml` previously in https://github.com/idaholab/moose/pull/26797.

But if the Conda changes look good here, would you want to go ahead and merge this one?

**Review by milljm — APPROVED** [review]
The Conda package changes look good to me 👍

**Pull request merged**
