### PR TITLE
Implement RestoringInterface

### LINKED ISSUE #26347: SolveFailedInterface
## Reason

If an object modifies the "state" of the problem other than stateful properties and adaptivity, there is currently no interface to notify an object about a solve failure event.

## Design

Mimic the `MeshChangedInterface` and add a `SolveFailedInterface`.

## Impact

This will add new API for objects that want to restore the problem state in a solve failure event.

### PR DESCRIPTION
**Pull request by hugary1995**
This interface allows objects to customize the behavior during a problem restore event.

close #26347

### CODE REVIEW

**Review by loganharbour — COMMENTED** [review]
Fundamentally I don't think that I agree with this. Restart is when things are allowed to change. There should be minimal conditional logic in restore.

Regardless, please use `MooseApp::registerInterfaceObject()` and `MooseApp::getInterfaceObjects()` instead of creating a new variable.

**Comment by hugary1995** [comment]
> Fundamentally I don't think that I agree with this. Restart is when things are allowed to change. There should be minimal conditional logic in restore.

Can you take a quick look at the test object I added in this PR? I'd like to know how to deal with cases like that without something like a RestoringInterface.

**Comment by hugary1995** [comment]
Idk if I'm understanding this correctly now...

I expect the "correct" behavior for the new regression test I added to be
```
+----------------+----------------+----------------+----------------+
| time           | add_one        | dt             | t              |
+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.000000e+00 |   1.000000e+00 |   1.000000e+00 |
|   2.000000e+00 |   2.000000e+00 |   1.000000e+00 |   2.000000e+00 |
|   3.000000e+00 |   3.000000e+00 |   1.000000e+00 |   3.000000e+00 |
|   4.000000e+00 |   4.000000e+00 |   1.000000e+00 |   4.000000e+00 |
|   4.500000e+00 |   5.000000e+00 |   5.000000e-01 |   4.500000e+00 |
|   5.500000e+00 |   6.000000e+00 |   1.000000e+00 |   5.500000e+00 |
|   6.500000e+00 |   7.000000e+00 |   1.000000e+00 |   6.500000e+00 |
|   7.500000e+00 |   8.000000e+00 |   1.000000e+00 |   7.500000e+00 |
|   8.500000e+00 |   9.000000e+00 |   1.000000e+00 |   8.500000e+00 |
|   9.500000e+00 |   1.000000e+01 |   1.000000e+00 |   9.500000e+00 |
+----------------+----------------+----------------+----------------+
```

But if I comment out the `restoringProblem` method it gives me "incorrect" results
```
+----------------+----------------+----------------+----------------+
| time           | add_one        | dt             | t              |
+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.000000e+00 |   1.000000e+00 |   1.000000e+00 |
|   2.000000e+00 |   2.000000e+00 |   1.000000e+00 |   2.000000e+00 |
|   3.000000e+00 |   3.000000e+00 |   1.000000e+00 |   3.000000e+00 |
|   4.000000e+00 |   4.000000e+00 |   1.000000e+00 |   4.000000e+00 |
|   4.500000e+00 |   6.000000e+00 |   5.000000e-01 |   4.500000e+00 |
|   5.500000e+00 |   7.000000e+00 |   1.000000e+00 |   5.500000e+00 |
|   6.500000e+00 |   8.000000e+00 |   1.000000e+00 |   6.500000e+00 |
|   7.500000e+00 |   9.000000e+00 |   1.000000e+00 |   7.500000e+00 |
|   8.500000e+00 |   1.000000e+01 |   1.000000e+00 |   8.500000e+00 |
|   9.500000e+00 |   1.100000e+01 |   1.000000e+00 |   9.500000e+00 |
+----------------+----------------+----------------+----------------+
```

So it seems to me that the restartable data is not being rolled back to its previous value? or maybe I am missing something here.

**Comment by lindsayad** [comment]
The reason I suggested a `SolveFailedInterface` for https://github.com/idaholab/moose/issues/26347 was because I didn't want it to clash conceptually with our `restore` concept

**Comment by hugary1995** [comment]
It seems like there has been a fair amount of work related to restartable which has fixed this "issue". Closing this now.

**Pull request closed without merging**
