### PR TITLE
Fixed PR #18731

### PR DESCRIPTION
**Pull request by fdkong**
MultiAppNearestNodeTransfer: Expand bounding box

Refs  #18731

### CODE REVIEW

**Comment by lindsayad** [comment]
Did this result in a failure somewhere?

**Comment by fdkong** [comment]
> Did this result in a failure somewhere?

https://civet.inl.gov/job/807224/

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Review by lindsayad — DISMISSED** [review]

**Comment by fdkong** [comment]
Fixed one test but made four more tests failed. 

It was not productive

**Comment by fdkong** [comment]
@lindsayad Could you  re-approve for me ?

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
