### PR TITLE
Add ability to hide nodal variables from Nemesis output

### PR DESCRIPTION
**Pull request by jwpeterson**
This PR includes a libmesh update ~and therefore probably shouldn't be merged yet (because there are some other libmesh changes currently in progress) but~ and it adds a new test that demonstrates the ability to hide variables from Nemesis output (the new test will not pass without the changes to libmesh) that was not working previously. 

Brief summary of changes in this update:
* Fix copy/paste bug in DofMap::add_neighbors_to_send_list().
* Fixed bug in discontinuous plotting with Exodus format.
* threads.m4: Only error if user requested TBB and it wasn't available.
* Misc. m4 file standardization updates/fixes.
* Allow linear transformations between boundaries for periodic BCs with vector variables.
* Add new example, systems_of_equations_ex9, demonstrating linear elasticity with periodic constraints.
* Support adjacent/overlapping periodic boundary conditions.
* Run examples in the order: "dbg, devel, oprof, opt"
* Factor out Node::choose_processor_id heuristic.
* Tweaks to the way that newly created nodes are partitioned.
* Define USE_GKRAND when building Metis. This is consistent with PETSc's METIS.
* Don't use LIBMESH_TLS in contrib/metis. This is consistent with PETSc's METIS.
* Add asserts to various MeshTools utilities for DistributedMesh use cases.
* Fix Exodus solution writing for meshes with node numbering gaps.
* XdrIO::write meshes with discontiguous node ids.
* Fix adaptivity bug in which Elements w/o neighbors were treated as unrefined islands.
* ExodusII_IO: skip writing elemental variables on inactive blocks.
* Split include/parallel headers into several files.
* Remove --enable-default-comm-world configure option.
* Drop (attempted) MPI-1 support that was apparently long broken anyway.
* Optimizations/fixes to SparsityPattern::Build::parallel_sync().
* Improve/generalize configure test for XDR headers.

Refs #2518.

### CODE REVIEW

**Comment by jwpeterson** [comment]
@roystgnr and @bwspenc, did we somehow pick up a bunch more XFEM failures with the combination of #11502 and the current libmesh master, as well as the original timeout which led us down this path in the first place?
```
[0.097s]     FAIL test:moment_fitting.solid_mechanics_moment_fitting FAILED (ERRMSG)
[0.145s]     FAIL test:mechanical_constraint.glued_penalty FAILED (ERRMSG)
[0.295s]     FAIL test:bimaterials.glued_bimaterial FAILED (ERRMSG)
[0.346s]     FAIL test:second_order_elements.square_branch_quad8_2d FAILED (ERRMSG)
[0.068s]     FAIL test:corner_nodes_cut.corner_node_cut FAILED (ERRMSG)
[0.108s]     FAIL test:corner_nodes_cut.corner_node_cut_twice FAILED (ERRMSG)
[0.061s]     FAIL test:corner_nodes_cut.edge_cut FAILED (ERRMSG)
[0.102s]     FAIL test:corner_nodes_cut.corner_edge_cut FAILED (ERRMSG)
[0.078s]     FAIL test:corner_nodes_cut.notch FAILED (ERRMSG)
[0.590s]     FAIL test:second_order_elements.square_branch_quad9_2d FAILED (ERRMSG)
[0.712s]     FAIL test:bimaterials.inclusion_bimaterial FAILED (ERRMSG)
[0.132s]     FAIL test:solid_mechanics_basic.square_branch_quad_2d FAILED (ERRMSG)
[0.093s]     FAIL test:solid_mechanics_basic.crack_propagation_single_point FAILED (ERRMSG)
[0.767s]     FAIL test:second_order_elements.square_branch_tri6_2d FAILED (ERRMSG)
[0.106s]     FAIL test:solid_mechanics_basic.crack_propagation_sm FAILED (ERRMSG)
[0.191s]     FAIL test:solid_mechanics_basic.edge_crack_3d FAILED (ERRMSG)
[0.236s]     FAIL test:solid_mechanics_basic.elliptical_crack FAILED (ERRMSG)
[0.158s]     FAIL test:solid_mechanics_basic.edge_crack_3d_mesh FAILED (ERRMSG)
[0.180s]     FAIL test:solid_mechanics_basic.penny_crack FAILED (ERRMSG)
[0.264s]     FAIL test:solid_mechanics_basic.square_branch_tri_2d FAILED (ERRMSG)
[0.082s]     FAIL test:pressure_bc.2d_pressure_displaced_mesh FAILED (ERRMSG)
[0.142s]     FAIL test:pressure_bc.edge_2d_pressure FAILED (ERRMSG)
[0.130s]     FAIL test:pressure_bc.inclined_edge_2d_pressure FAILED (ERRMSG)
[0.238s]     FAIL test:pressure_bc.edge_3d_pressure FAILED (ERRMSG)
[0.266s]     FAIL test:moving_interface.moving_bimaterials FAILED (ERRMSG)
[300.0s]     FAIL test:init_solution_propagation.init_solution_propagation FAILED (TIMEOUT) [min_cpus=4]
```

**Comment by roystgnr** [comment]
I don't see how, but it certainly looks like it, doesn't it??

**Comment by roystgnr** [comment]
Rebuilding libMesh master now; I'll see if I can reproduce it.

**Comment by roystgnr** [comment]
Last time I saw *that* error it was from the attempt to restore cached coarse vectors in AdjointRefinementErrorEstimator and UniformRefinementErrorEstimator, when my first crack at changes to node partitioning had caused the refine-then-recoarsen process to no longer restore the exact same partitioning.

**Comment by roystgnr** [comment]
My devel-mode tests are still running, but none are failing for me so far, including a few that died on Civet.  Is it possible that the XFEM tests use the default Mesh, and #11502 was a fix for my default-DistributedMesh configuration but not for ReplicatedMesh?

**Comment by roystgnr** [comment]
Even with ```parallel_type = replicated``` in glued_bimaterials_2d.i, that test still passes for me.  I can't figure out how to replicate the test failures yet...

**Comment by brianmoose** [comment]
Looking at the [modules debug](https://civet.inl.gov/job/190348/) civet check, the crashes all have:
```
Assertion `node.processor_id() == node.choose_processor_id(node.processor_id(), elem->processor_id())' failed.
node.processor_id() = 65535
node.choose_processor_id(node.processor_id(), elem->processor_id()) = 0
 
 
Stack frames: 15
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::MeshTools::libmesh_assert_canonical_node_procids(libMesh::MeshBase const&)
3: libMesh::MeshTools::correct_node_proc_ids(libMesh::MeshBase&)
4: libMesh::MeshCommunication::make_nodes_parallel_consistent(libMesh::MeshBase&)
5: XFEM::update(double, NonlinearSystemBase&, AuxiliarySystem&)
6: FEProblemBase::updateMeshXFEM()
...
```

**Comment by jwpeterson** [comment]
That's certainly possible. My default is `ReplicatedMesh`, and I definitely see the same failures on my system that show up on the test box.

**Comment by roystgnr** [comment]
Let me try a ReplicatedMesh build and see what happens.  Perhaps there's some internal Mesh being built regardless of the parallel_type setting?

**Comment by roystgnr** [comment]
Wait, it looks like I just didn't git pull MOOSE devel after the XFEM change was merged.

**Comment by roystgnr** [comment]
AFK but I'll try to get back to this late tonight.

**Comment by bwspenc** [comment]
We discussed this a bit, and it sounds like I might not even need these calls around line 290 in XFEM.C (or their equivalents on the displaced mesh a few lines later:
```
    _mesh->update_parallel_id_counts();
    MeshCommunication().make_elems_parallel_consistent(*_mesh);
    MeshCommunication().make_nodes_parallel_consistent(*_mesh);
```
I'm modifying the mesh in exactly the same way on all processors, so all of the new elements and nodes should be created with the same `id`, `processor_id`, etc.

**Comment by bwspenc** [comment]
I just tried making that change, and with the libMesh version we are currently using, all of the XFEM tests pass in serial and 4-way parallel.  I haven't tried it on the current libMesh master version yet.

**Comment by bwspenc** [comment]
Well, that didn't help, although now I'm getting an error at a slightly later stage (in debug)
```
test:moment_fitting.solid_mechanics_moment_fitting: Assertion `proc < _first_df.size()' failed.
test:moment_fitting.solid_mechanics_moment_fitting: proc = 65535
test:moment_fitting.solid_mechanics_moment_fitting: _first_df.size() = 1
test:moment_fitting.solid_mechanics_moment_fitting:
test:moment_fitting.solid_mechanics_moment_fitting:
test:moment_fitting.solid_mechanics_moment_fitting: Stack frames: 16
test:moment_fitting.solid_mechanics_moment_fitting: 0: 0   libmesh_dbg.0.dylib                 0x000000010db562a0 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 2192
test:moment_fitting.solid_mechanics_moment_fitting: 1: 1   libmesh_dbg.0.dylib                 0x000000010db4159e libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 622
test:moment_fitting.solid_mechanics_moment_fitting: 2: 2   libmoose-dbg.0.dylib                0x000000010af7906f libMesh::DofMap::first_dof(unsigned short) const + 1631
test:moment_fitting.solid_mechanics_moment_fitting: 3: 3   libmesh_dbg.0.dylib                 0x000000010d959f6f libMesh::DofMap::distribute_dofs(libMesh::MeshBase&) + 16095
test:moment_fitting.solid_mechanics_moment_fitting: 4: 4   libmesh_dbg.0.dylib                 0x000000010f2d63f2 libMesh::EquationSystems::reinit_solutions() + 10258
test:moment_fitting.solid_mechanics_moment_fitting: 5: 5   libmesh_dbg.0.dylib                 0x000000010f2d3bb9 libMesh::EquationSystems::reinit() + 25
test:moment_fitting.solid_mechanics_moment_fitting: 6: 6   libmoose-dbg.0.dylib                0x000000010b68b0d5 DisplacedProblem::meshChanged() + 37
test:moment_fitting.solid_mechanics_moment_fitting: 7: 7   libmoose-dbg.0.dylib                0x000000010b716ffc FEProblemBase::meshChangedHelper(bool) + 460
test:moment_fitting.solid_mechanics_moment_fitting: 8: 8   libmoose-dbg.0.dylib                0x000000010b717ed7 FEProblemBase::meshChanged() + 23
test:moment_fitting.solid_mechanics_moment_fitting: 9: 9   libmoose-dbg.0.dylib                0x000000010b717e4c FEProblemBase::updateMeshXFEM() + 220
test:moment_fitting.solid_mechanics_moment_fitting: 10: 10  libmoose-dbg.0.dylib                0x000000010b6b5a92 FEProblemBase::initialSetup() + 4482
test:moment_fitting.solid_mechanics_moment_fitting: 11: 11  libmoose-dbg.0.dylib                0x000000010acd99a7 Transient::init() + 5255
test:moment_fitting.solid_mechanics_moment_fitting: 12: 12  libmoose-dbg.0.dylib                0x000000010bea0e73 MooseApp::executeExecutioner() + 131
test:moment_fitting.solid_mechanics_moment_fitting: 13: 13  libmoose-dbg.0.dylib                0x000000010bea169b MooseApp::run() + 283
test:moment_fitting.solid_mechanics_moment_fitting: 14: 14  xfem-dbg                            0x000000010661d343 main + 275
test:moment_fitting.solid_mechanics_moment_fitting: 15: 15  libdyld.dylib                       0x0000000109c87235 start + 1
test:moment_fitting.solid_mechanics_moment_fitting: [0] /Users/spenbw/gitproj/githerd/moose/scripts/../libmesh/installed/include/libmesh/dof_map.h, line 545, compiled nodate at notime

**Comment by jwpeterson** [comment]
You really need to be using libmesh master, there aren’t any issues with the version of libmesh currently in MOOSE...

**Comment by jwpeterson** [comment]
@permcody I think this is good to go now.  Also @lindsayad is doing training right now so probably it's a good time for libmesh update??

**Comment by jwpeterson** [comment]
There appears to have been a major regression introduced by libMesh/libmesh@a555464, which is included in this update, so this PR should not be merged in its current state. I've also attached some parallel sweep testing to see if that turns up anything else useful.

**Comment by jwpeterson** [comment]
Once libMesh/libmesh#1699 and libMesh/libmesh#1700 are merged, I will update this PR with those fixes and drop the "Do Not Merge" label.

**Review by permcody — APPROVED** [review]

**Pull request merged**
