### PR TITLE
Moving StiffenedGasTwoPhaseFluidProperties into fluid_properties module

### LINKED ISSUE #15280: Add a concrete TwoPhaseFluidProperties class
## Reason
The fluid properties module has the abstract base class `TwoPhaseFluidProperties` but no concrete child classes. Users of the module should have an example, and this is also needed for unit-testing.

## Design
THM can move `StiffenedGasTwoPhaseFluidProperties` to the fluid properties module, which has default values for water, but is general enough to be customized for other fluids.

## Impact
New class.

### PR DESCRIPTION
**Pull request by andrsd**
Closes #15280

### CODE REVIEW

**Comment by andrsd** [comment]
This will break THM and all downstream apps depending on it. Fixing MRs are ready to go in...

**Review by joshuahansel — DISMISSED** [review]
Looks good, thanks for doing this so that I didn't have to.

**Comment by joshuahansel** [comment]
> Fixing MRs are ready to go in
Do you just mean that you have those locally? I don't see a THM PR up, for example.

**Comment by andrsd** [comment]
Yes, locally. All this really needs is a patch in THM and MOOSE submodule updates downstream. And I cannot test my THM patch in CIVET until this is merged...

**Review by joshuahansel — APPROVED** [review]
Apparently I need to approve this again. I approve again. The Mac failure is unrelated, and the Pronghorn build failure is expected, since it uses THM.

**Pull request merged**
