### PR TITLE
libMesh update.

### PR DESCRIPTION
**Pull request by jwpeterson**
Brief summary of changes in this update:
- Add lock in PetscVector::_get_array for thread safety.
- Fix two logic issues in threads.h
- Fix issue with system_projection and SCALAR variables.
- Add misc_ex12 demonstrating "MITC4" element.
- Expand C++11 <type_traits> configure test (#6495).
- Complete overhaul of threads.h, add --with-thread-model flag.
- Fix for ParallelMesh::max_foo_id().
- Make --disable-maintainer-mode the default.
- Fix issue with FEMContext and quadrature rules for SCALAR variables.

Refs #000.

### CODE REVIEW

**Comment by jwpeterson** [comment]
image1

**Comment by jwpeterson** [comment]
"TBB Test moose tests threads" score card so far: 1/1

**Comment by smharper** [comment]
FWIW, this fixes the segfaults on our cluster

**Comment by jwpeterson** [comment]
> FWIW, this fixes the segfaults on our cluster

Great, thanks for letting us know.  I think we are going to wait for one more threading fix from Derek before this gets merged.

**Comment by jwpeterson** [comment]
Looks like the only thing that failed was BISON, but it was unrelated -- possibly due to some Python updates on the build machines.  Anyway, I think we can probably merge this whenever everyone's ready...and sooner is better than later.

**Comment by dschwen** [comment]
I have a threading fix for FParser almost ready. If you can wait a few hours I would suggest including this.

**Comment by permcody** [comment]
We have two bets over here. I'm all in for your first attempt doesn't
compile. Brian's in for your first two attempts don't compile. Anyone else?

**Comment by jwpeterson** [comment]
> I have a threading fix for FParser almost ready. If you can wait a few hours I would suggest including this.

We can wait, but I'd rather not rush something that has other hidden/subtle new bugs in it... I'd rather wait until we have time to test it extensively with threads in MOOSE, *with the ParsedFunction mutex removed*, before we call it good.  If I've learned anything over the last few weeks, it's that threading is ridiculous.

**Comment by dschwen** [comment]
Well, if your most complex code construct is a for-loop it is easy to sit on a high horse...

**Comment by permcody** [comment]
I'm sure we can settle this like adults, right mister :hankey: :jeans:?

**Comment by dschwen** [comment]
It passes the libmesh unit tests. I'm building MOOSE with it right now. https://github.com/libMesh/libmesh/pull/859

**Comment by jwpeterson** [comment]
OK, the mutex you need to remove is [here](https://github.com/idaholab/moose/blob/devel/framework/src/bcs/FunctionPeriodicBoundary.C#L24) to test that it's actually working with threads.  I recommend running the "testwedge" test in an infinite loop with different numbers of threads to make sure that it works...

**Pull request merged**
