### PR TITLE
Don't run new porous_flow injection_production test with pthreads

### PR DESCRIPTION
**Pull request by brianmoose**
#11969 introduced a new test that can't run with pthreads: https://civet.inl.gov/job/219154/

### CODE REVIEW

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
I'd like to know why this test can't be run using pthreads.  Who knows, it could indicate a major bug in PorousFlow!  As far as i know, the test itself doesn't really activate any super weird parts of MOOSE any more than any other PorousFlow input file.

**Comment by brianmoose** [comment]
#11834 introduced threaded GeneralUserObjects and this test seems to use that. These shouldn't be run with pthreads (see also #11961).
@andrsd Would probably have more details on the why.

**Comment by dschwen** [comment]
You will get n_threads^2 threads?

**Comment by WilkAndy** [comment]
OK, at least it doesn't seem to be my problem.  What happens when a user just tries to use pthreads, by the way?

**Comment by andrsd** [comment]
> What happens when a user just tries to use pthreads, by the way?

Hopefully [helpful error message](https://github.com/idaholab/moose/blob/devel/framework/src/userobject/ThreadedGeneralUserObject.C#L16-L18
)


> You will get n_threads^2 threads?

That is my understanding

**Comment by WilkAndy** [comment]
Ha ha.  That message was obviously written by a computer dude.  It should say something like "run update_and_rebuild_libmesh --use_tbb" or something similarly prescriptive.

**Comment by lindsayad** [comment]
> You will get n_threads^2 threads?

Echo @dschwen 's question

**Pull request merged**
