### PR TITLE
Refactor phase field fracture models as damage models

### LINKED ISSUE #17620: Refactor phase field fracture models as damage models
## Reason

The existing phase field fracture stress calculators work fine -- not questioning that at all. But its currently implementation prevents users from using them in conjunction with other inelastic models.

## Design

Refactor the phase field fracture stress calculators by deriving from DamageBase, such that it can be directly used in stress calculators like `ComputeMultipleInelasticStress`.

## Impact

New capability.

### PR DESCRIPTION
**Pull request by hugary1995**
Refactor the phase field fracture stress calculators by deriving from DamageBase.

close #17620

Implementation:

- [x] No split
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split
- [x] Add an option to enable hybrid formulation

Documentations:

- [x] Summary of phase-field fracture. Extend ComputeLinearPFFractureStress.md
- [x] Talk about how the examples are setup
- [x] No split
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split

Testing:

Brittle fracture mode-I
- [x] No split
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split

Brittle fracture mode-II
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split

Cohesive fracture mode-I
- [x] No split
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split

Cohesive fracture mode-II
- [x] Strain spectral split
- [x] Strain vol-dev split
- [x] Stress spectral split

### CODE REVIEW

**Comment by hugary1995** [comment]
@jiangwen84 This is almost ready except for some testings (see the to-do list above). Feel free to give me some suggestions before I go too far...

**Comment by jiangwen84** [comment]
@hugary1995 Your code looks great so far. Do you want me to review now or until you finish remaining tasks? 

Just two minor comments:
1. Is it possible to reuse the golden files generated by the old PFF version?  
2. Have you thought how to implement PFF with multiple damage variables? Have a different `Scalar` and `Arrary` version?

**Comment by hugary1995** [comment]
> @hugary1995 Your code looks great so far. Do you want me to review now or until you finish remaining tasks?

You can review it now. I just have some documentation to add.

> Just two minor comments:
> 
> 1. Is it possible to reuse the golden files generated by the old PFF version?

I don't think so because the old gold files do not use incremental formulation, so results will diff.

> 2. Have you thought how to implement PFF with multiple damage variables? Have a different `Scalar` and `Arrary` version?

No, I haven't. Is the literature established on that? e.g. the motivation, formulation, and application.

**Comment by jiangwen84** [comment]
> > @hugary1995 Your code looks great so far. Do you want me to review now or until you finish remaining tasks?
> 
> You can review it now. I just have some documentation to add.
> 
> > Just two minor comments:
> > 
> > 1. Is it possible to reuse the golden files generated by the old PFF version?
> 
> I don't think so because the old gold files do not use incremental formulation, so results will diff.
> 
> > 1. Have you thought how to implement PFF with multiple damage variables? Have a different `Scalar` and `Arrary` version?
> 
> No, I haven't. Is the literature established on that? e.g. the motivation, formulation, and application.

We need do some literature review on that. The applications for that would be composites materials and polycrystals with different cleavage fracture planes.

**Comment by hugary1995** [comment]
I think this is reasonably complete now. I'll have to work on other stuff in the next few weeks and won't be able to come back on this. Take your time reviewing this.

**Comment by jiangwen84** [comment]
do not close this PR.

**Comment by hugary1995** [comment]
I am closing this because this PR requires #18725 which won't be fixed in the near future.

**Pull request closed without merging**
