### PR TITLE
Update HIT input processing to enable parameter overrides

### LINKED ISSUE #27564: Add ability to override parameters when using included files
### Motivation

It is desirable to specify collections of default settings common to many problems with a shared input file.

And then include those default settings while also overriding some values in problem-specific inputs, e.g.,

`problem_specific_values.i`:
```
!include common_default_settings.i

[Functions]
  [heat-input-ref]
    expression = '${fparse new_expression}'
  []
[]
```

`common_default_settings.i`
```
[Functions]
  [heat-input-ref]
    type = ParsedFunction
    expression = '0.'
  []
[]
```

But this is not possible and fails with the following error due to the same parameter being specified twice:

```
*** ERROR ***
common_default_settings.i:4.5: parameter 'Functions/heat-input-ref/expression' supplied multiple times
problem_specific_values.i:5.5: parameter 'Functions/heat-input-ref/expression' supplied multiple times
```

### Design

Allow choosing which parameter setting takes precedence with conflicting specifications in included files.

### Impact

Improved flexibility in including files of common default settings and overriding specific values as needed.

### PR DESCRIPTION
**Pull request by brandonlangley**
closes #27564

### CODE REVIEW

**Review by milljm — APPROVED** [review]
Conda looks good!

**Comment by loganharbour** [comment]
This should probably be tested

**Comment by brandonlangley** [comment]
> This should probably be tested

@loganharbour -

I have not yet added the actual update to `hit::buildHITTree()` that uses the override syntax while building the tree.

So far this just includes the WASP update that allows the syntax to be parsed.

I am working on the change that uses the overrides and unit tests now, sorry I forgot to put this in Draft for a second.

**Comment by loganharbour** [comment]
Okay, I think it's best that we include that together with this, then

**Comment by brandonlangley** [comment]
> Okay, I think it's best that we include that together with this, then

@loganharbour -

Yes, 100%, it will all be together. I didn't intend for this to go in without the bit that uses it.

I just had to create the PR in order to get the PR number to add to my `versioner_hashes.yaml` update.

That is the only reason this PR is here now.

I am will be pushing the commit which actually enables the overrides as well as the tests in the next bit.

**Comment by loganharbour** [comment]
Sounds good. If you open the PRs as drafts instead of converting them to drafts later, we don't get notified early

**Comment by brandonlangley** [comment]
@loganharbour -

This is ready for review now with the overrides enabled and tested so that this, for example,

`file_a.i`:
```
!include file_b.i
[Block]
  param_01 :=         value_01_from_file_a
  param_02 :override= value_02_from_file_a
  param_03 =          value_03_from_file_a
  param_04 =          value_04_from_file_a
[]
```

`file_b.i`:
```
[Block]
  param_01 =          value_01_from_file_b
  param_02 =          value_02_from_file_b
  param_03 :=         value_03_from_file_b
  param_04 :override= value_04_from_file_b
[]
```

effectively results in this.

```
[Block]
  param_01 = value_01_from_file_a
  param_02 = value_02_from_file_a
  param_03 = value_03_from_file_b
  param_04 = value_04_from_file_b
[]
```

Note that the short `param := value` and longer `param :override= value` are both allowed.

**Review by loganharbour — CHANGES_REQUESTED** [review]
All looks good to me, so do the tests.

Can you please add a new section to https://mooseframework.inl.gov/application_usage/input_syntax.html for this, and reference that section in a new newsletter entry for may

**Comment by brandonlangley** [comment]
@loganharbour -

I just added a new section to the input syntax documentation and a May newsletter entry for the override syntax.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
