### PR TITLE
Update python headers

### PR DESCRIPTION
**Pull request by permcody**
Put the copyright on all of our python files.

### CODE REVIEW

**Comment by permcody** [comment]
ugh... This is changing the execute bit on several of the scripts. I'll have to workup a fix for that too. I think this is close.

**Comment by agiorla** [comment]
Hi! I'm not sure why this PR has been assigned to me. I can review it for sure, but I want to check it's not an error first...

**Comment by permcody** [comment]
Sorry @agiorla - that was an error. I'll remove

**Comment by permcody** [comment]
@aeslaughter - One more test failing, this time on Mac. I think it has to do with the header change. There has got to be a better way to gold these outputs. I don't see how to fix.

**Comment by aeslaughter** [comment]
The failure is for a test that writes a python script from peacock. You probably added a header to the gold file, which now differs from the script generated by peacock, which does not have a header.

**Comment by permcody** [comment]
Finally passed! @aeslaughter or @brianmoose - please merge and then we'll try to keep up on the changes with new scripts over the coming days.

**Review by brianmoose — APPROVED** [review]

**Comment by aeslaughter** [comment]
👍 Thanks @permcody

**Pull request merged**
