### PR TITLE
TheWarehouse: add support for cached, parametrized queries

### LINKED ISSUE #14260: Improve TheWarehouse performance
## Reason
@friedmud has use cases that stress warehouse querying hard.  We need to be able to cache/run parametrized queries efficiently

## Design
Provide a convenient way for TheWarehouse users to build parametrized queries where they can quickly retrieve results if the set of parameters have been used before.  Avoid lots of memory thrashing from Attribute creation using templating magic.

## Impact
Should not affect existing APIs.

### PR DESCRIPTION
**Pull request by rwcarlsen**
To have a parametrized query cache do this:

```c++
class YourClass
{
    // base_query might include query conditions for a particular system, etc.
    Foo(TheWarehouse::Query& base_query) : _cache(base_query) { }

    void aFunction()
    {
      auto curr_subdomain = ...;
      auto curr_thread = ...;
      _cache.queryInto(_results, curr_thread, curr_subdomain);
    }

    std::vector<FooObjects *> _results;
    TheWarehouse::QueryCache<AttribThread, AttribSubdomain> _cache;
    ...
```

@friedmud - see how this works for you performance-wise.  fixes #14260

### CODE REVIEW

**Review by friedmud — CHANGES_REQUESTED** [review]
This set of changes is looking good... but `Attrib` (which is everywhere) really needs to be `Attribute`... we don't typically shorten things like that.

**Comment by friedmud** [comment]
Actually - I would personally prefer if all of the "Attribute" classes were named the other way around: `SubdomainAttribute`, `ThreadAttribute`, etc.  That's usually how things are done (i.e. with Generators and Postprocessors...)

**Comment by rwcarlsen** [comment]
Sure - but this PR doesn't introduce or rename any of those things.  That seems like a functionally different change that belongs in its own PR - which will make reviewing both changes (esp this one) much better.

**Comment by loganharbour** [comment]
@rwcarlsen Added support for creating a `QueryCache` via copy-constructor from another `Query`. Also required supplying the system when updating an object in `TheWarehouse` - we discussed this previously.

@friedmud Can you take a look at this and hopefully approve? It's being used in the RT module.

**Review by friedmud — APPROVED** [review]
👍

**Comment by rwcarlsen** [comment]
@loganharbour - have you guys looked at the performance using this for raytracing in the way that was showing too much slowness before? - i.e. can you confirm this speeds things up to the degree you need?

**Pull request merged**
