### PR TITLE
Change legacy defaults

### PR DESCRIPTION
**Pull request by permcody**
refs #8106

### CODE REVIEW

**Comment by mangerij** [comment]
Ferret might fail here.

**Comment by permcody** [comment]
It may, but it's an easy fix. I'll send you a patch if it does.

**Comment by mangerij** [comment]
Odd, only exodiffs on the postprocessors.

**Comment by permcody** [comment]
That's not odd at all. That's the kind of behavior that would be affected by this change. 

The way to fix that is to change the effected tests so that their Postprocessors have `execute_on = "initial timestep_end"`.

**Comment by permcody** [comment]
@aeslaughter - Pika is the only app that needs to be fixed now. All others have been patched.

**Comment by permcody** [comment]
After this is merged, Stork should be patched.

**Review by andrsd — APPROVED** [review]

**Pull request merged**
