### PR TITLE
Ensure the correctness of multi-entry of FullSolveMultiApp

### LINKED ISSUE #12772: Issue of reentering Transient::execute
## Rationale

`Steady::execute` can be reentered without changing the final solution even the solution before entering (or initial guess) changes. `Transient::execute` is different. If the solution before entering changes, it means the initial condition is different, thus all the sequential solution changes. However, if we only care the solution reaching the steady-state during transient like in pseudo-transient calculations, we are in a kind of situation like `Steady::execute`. But the current code does not allow reentering correctly. For example, time integrator init is in `Transient::init`, which will be skipped. Time or time step counter may not be setting correctly.

## Description

I propose to move some of the code in `Transient::init` into `Transient::preExecute` to make the reentering more solid. This will make the calculation where mater steady-state calculation drives a Picard iteration involve a pseudo-transient multiapp calculation correctly.

## Impact
A better design enables more functionality without impact.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #12772.

A note: `keep_solution_during_restore` does not work well with the current way of doing `initialSetup`. After restoration, the solution and postprocessors could lost synchronization because the initial evaluation is currently in `FEProblem::initialSetup` but not in `Executioner::preExecute`. So we are still using `no_backup_and_restore` and consequently providing another parameter `keep_full_output_history`.

All the changes in `OutputWarehouse` are removed. System time in `Steady` is added as a short-term solution. This should be ready.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Any comments? This is ready. The test failures are irrelevant.

**Comment by YaqiWang** [comment]
A dummy force push to re-invoke all the tests.

**Review by friedmud — APPROVED** [review]
👍

**Comment by YaqiWang** [comment]
Thanks!

**Comment by permcody** [comment]
This appears to have added a real bug that only showed up in Pika. It looks like we have a steady MMS test that also has an AuxVariable field. That's a test case that we don't appear to have anywhere in the MOOSE suite. The one or two MMS tests that we do have don't have AuxVariables. @aeslaughter - says that he's not getting the Aux output.

**Comment by YaqiWang** [comment]
I will stop by. I have a patch in Pika.

**Pull request merged**
