### PR TITLE
Fixup CSV data reading, when data is organized in Voronoi partittions, to make it clearer

### PR DESCRIPTION
**Pull request by GiudGiud**
to both devs (no need to code an offset) and users of the function (just look at the column in the file)

I m also freezing the number of columns for the coordinates of the centers to Moose::dim (3 for all intents and purposes)
This is probably also reducing the risk of errors

refs #19109

### CODE REVIEW

**Comment by dschwen** [comment]
A while ago I added https://github.com/idaholab/moose/pull/21208 . That would be my preferred way over column indices.

**Comment by GiudGiud** [comment]
that's a larger rework than I want to do for this maintenance action. But I ll keep it in mind next time I use the reader

**Comment by GiudGiud** [comment]
Looks like Grizzly hardcoded the reading of centers to another file. This wont be ready until I find a clean way to reconcile this

**Comment by GiudGiud** [comment]
@dschwen 

adding the offset goes directly against having titles for columns (of the coordinates)
so I removed that from the PR
I tried having titles. I did not finish, there's some painful work to do in the DFR to handle headers in now both rows and columns.

the PR now only hardcodes the dimension 3, which will still be good for porting simulations between dimensions. It s very limited but I trust it can be merged.

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
