### PR TITLE
Fixes for adaptive mesh refinement with contact

### PR DESCRIPTION
**Pull request by roystgnr**
This PR updates the AMR+contact test that @bwspenc put together to demonstrate #6799.

We start with his fix for the immediate problem, updated for compatibility with MOOSE changes since it was written.  There's also fixes for inactive elements that were sneaking into the MooseMesh _node_to_elem_map in some adaptive cases, and a reordering of MooseMesh and EquationSystems reinitialization to make sure that geometric search code wasn't using atavistic MooseMesh cached data.

There is a new gold standard for the test, which is 1% to 5% off from the original solution on various variables.  @bwspenc believes this is due to model changes postdating the creation of the original regression solution, not to anything wrong with the new code.

The new test works fine in parallel, but not yet with --distributed-mesh (which is specifically disabled due to #4532, I presume).  The test also fails in recovery, with a segmentation fault when a null PropertyValue pointer gets dereferenced.  I'll add a new issue for that.

### CODE REVIEW

**Comment by roystgnr** [comment]
The failures here appear to be caused by the change in order in 2647f28, but I don't yet understand how.

**Comment by roystgnr** [comment]
So now I'm starting to understand what's happening.  MOOSE code for contact problems, which gets called via functors and/or callbacks in EquationSystems::reinit(), uses the cached ranges in MooseMesh to loop over all elements, so we have to call _mesh.meshChanged() and update those ranges before the reinit or we miss newly created elements.

However, the reinit() then invalidates those ranges in adaptive problems, because that's where we're newly marking active elements and possibly repartitioning.  So we have to call _mesh.meshChanged() *after* the reinit() too, or the next system assembly can try to walk over newly inactive elements (and/or dangling pointers to newly remote elements!) and then die when it can't find dofs everywhere it looks.

So the current solution, two meshChanged() calls, satisfies correctness, passes all our tests, and is good to merge... but it's a redundant call in some sense: 6 extra loops over elements or nodes, which is ironic in code whose very existence is an attempt to avoid iterating over elements or nodes.  My inclination is to merge now and then come back to it if this shows up in profiling (there's some obvious ways to optimize meshChanged() at a slight cost to modularity).  But I'm open to other ideas too.

**Comment by bwspenc** [comment]
@roystgnr Thanks for looking into this! It looks like the tests passed in debug, so that indicates that you must have done something right!  The redundant `_mesh.meshChanged()` call wouldn't be a performance problem since this happens pretty rarely. Someone other than me should review this, but it looks good to me. I'm pretty excited to have this sorted out!

**Comment by bwspenc** [comment]
@jwpeterson Would you mind taking a look at this?

**Review by jwpeterson — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like your `contact_initial_adaptivity` test is now reliably failing in debug mode: https://www.moosebuild.org/job/111228/
Not sure why this didn't get caught on the PR testing, perhaps due to another PR that has been merged since this was tested?

**Comment by brianmoose** [comment]
@andrsd thinks the failure is due to @YaqiWang 's merged PR #9456 which could have an over zealous assert.

**Comment by roystgnr** [comment]
That assert is baffling me.  Shouldn't reinit() be what sets the current subdomain id, to keep things consistent?  It looks like it's asserting that the new element has the same subdomain id as the previous element, but that can't be because that would fail all over the place.

I don't understand why you'd want to cache a subdomain id anyway.  The CPU time saved over just calling Elem::subdomain_id() ought to be tiny-to-negative, and the programmer time used keeping the cache correct could be significant, especially as the mechanism for doing so doesn't appear to be "change them in sync internally so we can prove they stay correct".

**Comment by andrsd** [comment]
So the assert tripped by RELAP-7 is coming from `PointValue`. We get a point and find the element in displaced space and sample some variable there. So we have to call `reinitElemPhys`, but subdomain_id does not really matter in this case. So, definitely the assert is overzealous for this case.

As for the value of current subdomain, @roystgnr . The reinit happens in `onElement` in our ThreadedLoop-derived class. However, before that we call `subdomainChanged` if subdomain changed. And there @YaqiWang wanted to know the current subdomain id.  That's why we are setting the subdomain id before `onElement`, which is also before reinit.

**Comment by YaqiWang** [comment]
I am guessing your guys are referring https://github.com/idaholab/moose/blob/devel/framework/src/base/Assembly.C#L653.

Let me explain this. To support the `SetupInterface::subdomainSetup()` of almost all moose objects, I changed this part of the code in PR #9456:
https://github.com/idaholab/moose/blob/devel/framework/include/base/ThreadedElementLoopBase.h#L195-L202

`preElement()` is a virtual function which is override by https://github.com/idaholab/moose/blob/devel/framework/include/base/ThreadedElementLoop.h#L94
which calls `Assembly::setCurrentSubdomainID()` to set the current subdomain ID.

Now because subdomain ID is set before `onElement()`, which is calling `Assembly::reinit()`, we want to make sure the previously set subdomain ID is consistent with the current element subdomain ID. In moose, setting current element should be just after setting the current subdomain ID. We could reset the current subdomain ID to replace the mooseAssert, but it will remove a protection offerred by the mooseAssert. @permcody suggested to have that assert and I agree it is a good idea to have it.

If now we see the failure, you are probably missing a function call to set the subdomain ID some where like what I added in https://github.com/idaholab/moose/pull/9456/commits/90516437a5874dcd6d8f5a3ef40688e26cdca411.

**Comment by YaqiWang** [comment]
To answer @andrsd , somewhere, you need to have something similar as the following:
```
        _subproblem.setCurrentSubdomainID(elem, 0);
        _subproblem.reinitElemPhys(elem, point_vec, 0);
```
The location can be easily found with the message thrown by the failing tests. That is actually how I found all locations in 9051643.

**Comment by andrsd** [comment]
Another problem is that this only bombs out in debug, so your PR showed all is good (we test against apps in opt mode), but then debug tests in apps failed.

**Comment by andrsd** [comment]
@YaqiWang `PointValue` is in MOOSE, so you forgot to do it in your PR :-) RELAP just uncovered that...

**Comment by YaqiWang** [comment]
Oh, which means no test for `PointValue` in MOOSE...

**Comment by andrsd** [comment]
There is one, but there is only 1 subdomain id there, so the old value matched the new value and that's why it did not trip your assert. I submitted a fix for this in #9738

**Comment by YaqiWang** [comment]
Oh, I see. Thanks!

**Comment by bwspenc** [comment]
@andrsd Is this all taken care of now with your recent PR (#9738)?

**Comment by andrsd** [comment]
@bwspenc MOOSE and modules should be fine.

**Pull request merged**
