### PR TITLE
MOOSEletter

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #11446)

### CODE REVIEW

**Comment by aeslaughter** [comment]
@idaholab/moose-team We talked about creating a monthly "newsletter", so this is the start of doing that.

I am not sure how detailed we want this to be, I am open do whatever the team wants. My vision is that this will replace our current blog system. We will do something once a month, but we can also do special announcements.

For the monthly post, it would be create if we all just spend a 20 minutes and explain what we did and are doing.

**Review by permcody — COMMENTED** [review]
This is fine, but I don't think it captures very much of what the team is doing. This looks like work you are doing ;)

**Comment by aeslaughter** [comment]
@permcody 

> For the monthly post, it would be great if we all just spend 20 minutes and explain what we did and are doing.

**Comment by tophmatthews** [comment]
We (me, @naveen-pr, @bwspenc) just implemented a tangent operator calculation that greatly speeds up tensor mechanics simulations that involve creep. I can add a few lines now or in later months if you're looking for contributions.

I think this is an excellent idea btw...don't let it die off like the blog posts!!

**Comment by friedmud** [comment]
I like the idea.  We need to pick a day every month that we put one out.
And no matter what we write it up and publish it that day.

Derek

**Comment by aeslaughter** [comment]
@tophmatthews Yes, please contribute to this PR.
@friedmud I have a reminder set for the first Monday of the month.

**Comment by aeslaughter** [comment]
I will start the PR on the first Monday and set the date for Tuesday.

**Comment by friedmud** [comment]
Ok - added my bits to the MOOSELetter!  Let's really work to keep this going...

**Comment by permcody** [comment]
Let's get @rwcarlsen's work in here before we merge:

- `paramError()` and `paramWarning()`
- Not setting non-existent parameters

Both of these are very developer facing changes that need to be communicated.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
