### PR TITLE
Print better TestHarness stack traces

### LINKED ISSUE #10607: TestHarness suppresses errors
## Rationale

When working on a new Tester subclass using the Python test harness framework, if an instance of the subclass throws a Python exception, minimal information is provided, and often insufficient to quickly debug the reason for the exception.  Additionally, this can result in a false positive for passing tests.

### Observed Behavior
When a Tester subclass instance being used in a `runWorker()` call results in a run-time Python exception being thrown, it is caught generically by the `TestHarness.schedulers.Scheduler.runWorker()` method, which is wrapped entirely in a try-catch.  The resulting information to the user is `runWorker Exception:` followed by a printout of the exception message, without any additional information.

Furthermore, this exception does not result in the overall tests reported as crashed or failing; instead, if tests have passed up to when the exception was raised, the test harness reports an "all passed" state, which is misleading at best.  See for example:
```
[...]
framework.external_xml.................................................................................... OK
framework.custom1D........................................................................................ OK
framework.LHSVariables.................................................................................... OK
framework.SimulationTags.................................................................................. OK
framework.testExternalModelReseed......................................................................... OK
runWorker Exception: Error tokenizing data. C error: Expected 4 fields in line 3, saw 5

-------------------------------------------------------------------------------------------------------------
Ran 27 tests in 117.1 seconds
27 passed, 13 skipped, 0 pending, 0 failed

Successfully tested raven.
```
Even though the application from this example has over 400 regression tests, after the runWorker exception is printed, the harness exits with a "success" status on the 27 tests run, while the result of the remaining tests is unknown.

### Desired Behavior
What is missing in the crash report is the test in which the exception occurred, the module and method that raised the exception, and the line number at which the exception was raised, which is typically provided by the Python traceback.

Additionally, a non-passing state passed to CIVET would prevent faulty assumptions about tests passing when run automatically.

## Impact

Changing the lines of code after the `except Exception` at the end of `runWorker` to call `self.killRemaining()` and then _raise_ the exception (`raise e`) might provide the missing details that would be useful.

I don't know immediately how the reporting of pass-fail can be changed, but would be happy to investigate it further.

Both these changes seem straightforward initially, and I'd be happy to prepare a PR with them.

This would have positive impact on developers of MOOSE-based apps that use custom testers, by increasing the accuracy and transparency of the test harness performance.

### PR DESCRIPTION
**Pull request by milljm**
While in the runworker thread, print the actual stack trace
that occurred, if one occurred.

Closes #10607

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
If I'm correct, this will still (misleadingly) claim the tests passed if none failed before the exception, right?

**Comment by milljm** [comment]
It will, because the parent thread was busy dealing with other _passing_ child threads that didn't error... But by the time the parent thread gets around to dealing with the problem thread, the error will eventually show its ugly head.

**Comment by milljm** [comment]
Oh wait, I think I see what you are getting at... the final exit code is still a zero. Yeah that need to be fixed.

We won't be able to tally these as failures. The right solution is to simple die with a non-zero exit code.

**Comment by PaulTalbot-INL** [comment]
Ha, yes, thank, you saved me a lengthy comment.  I agree, nonzero exit to CIVET is exactly what I'm looking for.

**Comment by milljm** [comment]
Okay! I'll figure out how to do that =D 👍

**Review by brianmoose — APPROVED** [review]

**Comment by PaulTalbot-INL** [comment]
Thank you!

**Pull request merged**
