### PR TITLE
Fix unreleased MooseArray deep copy

### PR DESCRIPTION
**Pull request by dschwen**
Fixes Valgrind error introduced in #8978
Refs #8977

### CODE REVIEW

**Comment by dschwen** [comment]
Well, that valgrind test takes 4 hours...

**Comment by dschwen** [comment]
@brianmoose, for doing optional Valgrind testing on PRs it would be super nise if we could specify the `--re` parameter in Civet and only test a few select tests.

**Comment by brianmoose** [comment]
Where would you like to specify that? When adding an optional recipe, have a form for specifying command line arguments?

**Comment by dschwen** [comment]
Or have a form for specifying select environment variables (that way you could inject user specified stuff anywhere in a recipe, not just the run_tests command)

**Review by permcody — APPROVED** [review]
Oh dang... I should have seen that. Thanks

**Pull request merged**
