### PR TITLE
Small documentation fixes

### PR DESCRIPTION
**Pull request by GiudGiud**

### CODE REVIEW

**Comment by grmnptr** [comment]
I think you need to modify the inlet-related BC checks too. I am bit confused. Also, I think we could rename it to simply `velocity-inlet-function`. I think this can stil lbe used if we add compressible too.

**Comment by GiudGiud** [comment]
@grmnptr I've gutted this PR since we re keeping the parameter. Users will just have to read the docs

**Comment by lindsayad** [comment]
Maybe rename this PR? I don't know what the thesis of this PR is any more

**Comment by GiudGiud** [comment]
oh didnt gut it enough

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
