### PR TITLE
initialisation of porosity corrected

### LINKED ISSUE #10054: Correct initQpStatefulProperties in PorousFlowPorosityExponentialBase
## Rationale

At present porosity is initialised to a value appropriate to T=0, P=0, volumetric_strain=0.  That is incorrect when those conditions don't hold for the initial state.  Initialise it appropriately.

## Description

The Old value of Porosity is used in the time-derivative kernels, so an incorrect initialisation produces craziness in the first timestep.  None of our tests currently demonstrate this behaviour, but a real-life model i'm running does.  So I'll have to include a regression test.

## Impact

Better initialisation.  Tagging @cpgr - any comments?

### PR DESCRIPTION
**Pull request by WilkAndy**
PorousFlowPorosityExponentialBase now correctly initialises porosity in cases where porepressure!=0 or temperature!=0 or volumetric_strain!=0 initially.

Fixes #10054

@cpgr , could you review at some stage (only 15 lines of code) as it'd be good to know if you see any problem here.   It's not incredibly urgent.

### CODE REVIEW

**Comment by cpgr** [comment]
Looks good @WilkAndy, although the tests aren't running for some reason.

I wonder whether it would be better to make `atNegInfinityQp()` and `atZeroQp()` pure virtual functions, as the default values of 1 in this base class will throw an assert if they are not overridden?

**Comment by WilkAndy** [comment]
pure virtual - good idea, i'll check to see if it breaks anything

**Comment by WilkAndy** [comment]
Pure virtual caused no problems and just made the code cleaner.  Thanks @cpgr

**Comment by cpgr** [comment]
Yeah, looks great!

**Comment by cpgr** [comment]
Wow, how slow is the testing running. Might need to turn the computers off and then back on...

**Comment by mangerij** [comment]
I think there is maintenance this week.

**Comment by WilkAndy** [comment]
Failed tests appear to be unrelated to this PR, see, #10085

**Review by permcody — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for the review and merge @permcody 

a

**Pull request merged**
