### PR TITLE
Added source files, header files, and test files of IsolatedBoundingB…

### LINKED ISSUE #14050: Adding interfacial width for multiple bounding boxes initial condition
## Reason
In the current MultiBoundingBoxIC of phase field module, there is no option to create diffused interface. The variable value is sharp at the box boundary, and it affects the convergence performance. We would need to be able to specify interfacial width for multi bounding box just like in single BoundingBoxIC. 

## Design
Either adding an int_width to the existing MultiBoundingBoxIC, or making other source files that categorize different types of bounding boxes and define the diffused interfaces accordingly will do the job.  

## Impact
Nothing will be removed from the current initial condition. New feature of interfacial width will be added when the initial condition is multi bounding box. @tonkmr

### PR DESCRIPTION
**Pull request by xueyang94**
…oxIC and NestedBoundingBoxIC.       closes #14050

(Combined the two commits in the previous pull request into one commit, to see if it will pass the checks this time.)

Two new initial conditions: IsolatedBoundingBoxIC and NestedBoundingBoxIC are added into phase field module to enable assigning interfacial width when creating multiple bounding boxes. Five test files are also added: 2D and 3D conditions for these two initial conditions, and one error test file which will throw an error if users make overlapping boxes using IsolatedBoundingBoxIC. refs #14050

### CODE REVIEW

**Comment by permcody** [comment]
Thanks for your contribution - Please let me know if you have questions about passing the pre-checks.

**Comment by tonkmr** [comment]
@xueyang94 is one of my newer students and is learning how to commit to MOOSE. However, she isn't able to see the details on the checks, so she can't see why they are failing. Is there a way for her to see the details of the failed checks?

**Comment by permcody** [comment]
The open source apps' statuses don't require a login to view. This includes the pre-check. I just signed out and I can still open the recheck here: https://civet.inl.gov/job/404011/

The issue is that this PR is against the wrong branch (i.e. "devel" instead of "next").

**Comment by xueyang94** [comment]
@permcody Thanks. I will then try to merge the commit into idaholab:next

**Comment by xueyang94** [comment]
@permcody But in this MOOSE Contributing web [https://mooseframework.inl.gov/old/wiki/Contributing/](url), it uses `git rebase upstream/devel`, not next branch, and also in the PR slides it says Your pull request must made to idaholab:devel.

**Comment by permcody** [comment]
>  it uses git rebase upstream/devel, not next

Yes I am aware. I plan to develop new documentation very soon that's easier to maintain. We have changed our process since that document was originally developed several years ago. Sorry about the misleading information.

**Comment by permcody** [comment]
I don't think you can change your destination branch unfortunately. You'll have to close this PR and open a new one against "next".

**Pull request closed without merging**
