### PR TITLE
Add an initial condition for multiple box shaped variable value variations

### LINKED ISSUE #6858: Add `MultiBoundingBoxIC` to the phase field module
### Description of the enhancement or error report
Add `MultiBoundingBoxIC` to the phase field module

### Rationale for the enhancement or information for reproducing the error
People are asking for it. It is useful and general enough.

### Identified impact
Added capability

### PR DESCRIPTION
**Pull request by dschwen**
Adds the `MultiBoundingBoxIC` initial condition. Boxes are axis-aligned and are specified through a list of opposing corners. The IC is smart enough to deal with _arbitrary_ corners. No lower-left-front / bottom-right-back nonsense.

Closes #6858

### CODE REVIEW

**Comment by dschwen** [comment]
This replaces an IC with the same name in Marmot. I rewrote this completely however.

**Comment by friedmud** [comment]
Is this sufficiently general enough to go into MOOSE?

**Comment by dschwen** [comment]
IDK, it is more specific than any of the other ICs in framework. It has a similar flavor to `MultiSmoothCircleIC` and `RndBoundingBoxIC`, which are both in phase field.

**Comment by laagesen** [comment]
Looks good.

**Comment by friedmud** [comment]
Then maybe name it a but more specifically?

By default, new MOOSE-based applications link in PF.... and this name seems
to suggest that it's just multiple bounding boxes.... if it's actually
smoothed bounding boxes ,or whatever, the name needs to reflect that.

**Comment by permcody** [comment]
I second Derek's comment. Let's name this a little more appropriately.

**Comment by dschwen** [comment]
Those are not smooth, but I have thought of this as a future extension. It would make sense for smooth interface methods.

**Comment by permcody** [comment]
OK - We'll merge as-is and expand later.
👍

**Pull request merged**
