### PR TITLE
Check and Prepare Input Mesh in ElementDeletionGeneratorBase

### LINKED ISSUE #21071: Check and Prepare Input Mesh in ElementDeletionGeneratorBase
## Bug Description
`ElementDeletionGeneratorBase` can optionally assign `new_boundary` to the new surface created by the deletion. This functionality requires that the input mesh to be "prepared". However, the "is_prepared" status of the input mesh is not checked. As a results, if a "not_prepared" mesh is used as the input mesh, this `new_boundary` functionality does not work without throwing any warning or error message.

## Steps to Reproduce
Use a "not_prepared" mesh (e.g., output of `FancyExtruderGenerator`) as the input for "BlockDeletionGenerator" (a derived class of `ElementDeletionGeneratorBase`) and provide `new_boundary`. The `new_boundary` will not be generated.

## Impact
The needed new boundary is not generated without a warning/error message.

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #21071

### CODE REVIEW

**Comment by lindsayad** [comment]
@miaoyinb if you didn't prepare the mesh and you ran your test, what would happen? An error?

**Comment by miaoyinb** [comment]
> @miaoyinb if you didn't prepare the mesh and you ran your test, what would happen? An error?

Yes, without the new lines in `ElementDeletionGeneratorBase.C`, the new Exodiff test will fail.

**Review by lindsayad — DISMISSED** [review]

**Comment by miaoyinb** [comment]
Not sure why. But just use `find_neighbors()` instead of `prepare_for_use()` is enough for this case and seems to fix the failed distributed mesh test.

**Review by lindsayad — CHANGES_REQUESTED** [review]
I want to look into the seg fault real quick

**Comment by lindsayad** [comment]
@miaoyinb I hope you don't mind; I push a commit to your branch here. The issue was that we were preparing for use in-between building our set of delete-able elements and then later calling methods on those delete-able elements. In distributed mesh mode, `prepare_for_use` will remove remote elements, and this resulted in attempting to call methods on elements that had already been free'd

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Since I have a commit on here now, I'd like to get another CCB member's approval before merging

**Comment by miaoyinb** [comment]
Thank you for fixing this.

**Review by loganharbour — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Review by roystgnr — APPROVED** [review]

**Pull request merged**
