### PR TITLE
Exception testing of RichardsMultiphaseProblem.

### PR DESCRIPTION
**Pull request by WilkAndy**
I just want to get 100% test coverage.

Refs #6402

### CODE REVIEW

**Comment by dschwen** [comment]
I propose not merging any of his PRs until @willandy adds tests for his interested classes in tensor mechanics ;-). You're leaving us on the dust coverage wise.

**Comment by WilkAndy** [comment]
Heheheh.  On a serious side - i've used moose for a couple of rather contentious projects and if some "opponent" sees Richards is only 99% tested they'll rubbish everything based on that measly 1%.

**Comment by dschwen** [comment]
Sounds like stiff opposition. Your test coverage is awesome.

**Comment by WilkAndy** [comment]
Thanks @dschwen 

a

**Comment by permcody** [comment]
:+1:

**Comment by WilkAndy** [comment]
Thanks @permcody,

a

**Pull request merged**
