### PR TITLE
Get unit tests running in dbg mode.

### PR DESCRIPTION
**Pull request by jwpeterson**
Fixed all the warnings and removed some invalid tests.

Refs #6055.

### CODE REVIEW

**Comment by jwpeterson** [comment]
@brianmoose if this works, we can add unit test to the PR test debug target.

**Comment by permcody** [comment]
:+1: Let's add the mooseunit-dbg step

**Comment by brianmoose** [comment]
I added the debug unit test for the "PR test debug" and the "devel->master test debug"

**Comment by jwpeterson** [comment]
I can definitely reproduce the segfault on rod:

```
#0  0x00007ffff5507360 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff5507514 in __gnu_debug::_Safe_sequence_base::_M_detach_all() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000000000042c4d4 in __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base (this=0x7fffffffd478, __in_chrg=<optimized out>) at /usr/include/c++/4.6/debug/safe_base.h:199
#3  0x00007ffff7a2caf2 in __gnu_debug::_Safe_sequence<std::__debug::deque<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::~_Safe_sequence (this=0x7fffffffd478, __in_chrg=<optimized out>) at /usr/include/c++/4.6/debug/safe_sequence.h:112
#4  0x00007ffff7a2cb11 in std::__debug::deque<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~deque (this=0x7fffffffd428, __in_chrg=<optimized out>) at /usr/include/c++/4.6/debug/deque:116
#5  0x00007ffff7a27da9 in CppUnit::Message::~Message (this=0x7fffffffd420, __in_chrg=<optimized out>) at /usr/include/cppunit/Message.h:38
```

We have seen this before on Linux, it is caused by the `GLIBCXX_DEBUG` flags we use to compile MOOSE/libmesh in dbg mode being different from the dbg flags we use to compile cppunit.  I recall now why we didn't turn on moose-unit testing in dbg mode... 

However, I still think it's worth merging this PR as it allows us to run the unit tests in dbg mode on OSX, but I don't think we can turn on unit testing on the CI boxes until we possibly change the way we build cppunit in the MOOSE package.

**Comment by jwpeterson** [comment]
I guess I'm buying beer this year, #410.

**Pull request merged**
