### PR TITLE
Added a -depth argument to the "find" in make clobber.

### LINKED ISSUE #6258: make clobber doesn't work for me
I get:

find: The -delete action atomatically turns on -depth, but -prune does nothing when -depth is in effect.  If you want to carry on anyway, just explicitly use the -depth option.

I think make clobber has to start with

        $(shell find $(CURDIR) -depth

a

### PR DESCRIPTION
**Pull request by WilkAndy**
**Please check this works for you as well as me!!"

Fixes #6258

### CODE REVIEW

**Comment by dschwen** [comment]
I remember there was a specific reason we choose to **not** add that option. I'll try to remember what that was.

**Comment by WilkAndy** [comment]
OK, that's no problem - the different versions of "find" are so annoying.  But could you suggest a good way for me to perform "make clobber"?  At the present i just copy-and-paste moose.mk stuff to the command-line and add the "-depth" argument.

**Comment by dschwen** [comment]
yeah, this had been bugging me for a while, too. I'll think about it.

**Comment by dschwen** [comment]
This:

> `-prune` is basically useless in combination with `-depth`, since it's only applied after you've already visited all of the children

I'll go ahead and close this and try to come up with a better `clobber` solution

**Comment by dschwen** [comment]
So, `-delete` implies `-depth` and `-prune` and `-depth` do _not_ work together (your fix would still clobber the libmesh submodule, which is not what we want). We probably will have to move away from `-delete` and back to `xargs`, which was slower, but at least worked.

**Pull request closed without merging**
