### PR TITLE
Moose docs style and macros

### PR DESCRIPTION
**Pull request by aeslaughter**
@WilkAndy and @joshuahansel This PR adds the features you wanted, I will be adding some doco to this PR as well.

### CODE REVIEW

**Comment by WilkAndy** [comment]
So what feature did i request? (!)

**Comment by aeslaughter** [comment]
@WilkAndy The "style" extension, when this is merged, should now be used to color text: https://mooseframework.inl.gov/docs/PRs/13114/site/python/MooseDocs/extensions/style.html

**Comment by aeslaughter** [comment]
@joshuahansel https://mooseframework.inl.gov/docs/PRs/13114/site/python/MooseDocs/extensions/katex.html

**Review by joshuahansel — APPROVED** [review]

**Comment by WilkAndy** [comment]
Aha, i get it, thanks @aeslaughter

**Pull request merged**
