### PR TITLE
Standardise implementation of vapour pressure in FluidProperties

### LINKED ISSUE #9146: Fluidproperties: make implementation of vapour pressure consistent
### Description of the enhancement or error report
At the moment, vapour pressure is implemented in a haphazard fashion - `pSat(temperature)` for water & brine, `vaporPressure(temperature)` for CO2, etc. 

### Rationale for the enhancement or information for reproducing the error
Giving this method the same name for all fluids makes use easier.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Mostly internal changes

### PR DESCRIPTION
**Pull request by cpgr**
Basically `pSat() -> vaporPressure()` in `fluid_propertis` and `porous_flow`.

Also changed `TSat() -> vaporTemperature()` in `Water97FluidProperties` for consistency.

Closes #9146

### CODE REVIEW

**Comment by WilkAndy** [comment]
I wonder whether it's appropriate to add some doco to porous_flow/doc/theory/theory.tex ?  I can't really remember this vapour-pressure stuff and how it impacts upon porous flow, so maybe a few lines of doco is useful?  I really don't know!

**Comment by cpgr** [comment]
I think that the only place it is used at the moment is in the water-gas persistent variable material. I haven't quite finished the documentation for that yet.

One day it might end up being used if we add vapour pressure lowering, but I can't see me really needing that at the moment.

**Comment by WilkAndy** [comment]
OK, that's good, the doco isn't needed yet.  I can't remember what that "vapour pressure lowering" stuff is!

**Review by permcody — APPROVED** [review]
Much better names!

**Pull request merged**
