### PR TITLE
This adds a module that creates a python control logic.

### LINKED ISSUE #9281: Provide a Python control logic
### Description of the enhancement or error report
it would be useful if there was a python control logic that applications could just use to be able to extend themselves with the Python programming language.

### Rationale for the enhancement or information for reproducing the error
Python is already used by MOOSE, so it is more or less available.  Allowing Python to be used to extend MOOSE applications provides additional flexibility for some applications.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This effectively adds another API to the modules directory.  Also python-config would need to be available and usable for compiling the module.

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
This adds a class PythonControl that uses Python to control the MOOSE control logic system and can be used to create control logics in MOOSE applications.

It also makes CoefDiffusion controllable.

Closes #9281

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
This provides a Control Logic that uses Python to allow a Python function that access PostProcessors and change Controllables.

- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
Three testcases in the merge.

- Reference or close a specific issue (refs # or closes #)
Refs #9281

### CODE REVIEW

**Comment by permcody** [comment]
I've had discussions with David, Ben, and Justin and we don't have a driver for the Python Control logic at this time. To the best of my knowledge there are no customers including Relap-7 that need this capability. We don't plan to include this in the modules at this time.

This PR doesn't make any modifications to the framework so this capability could be housed in a MOOSE-based animal if you really need this capability for research reasons. You could then use the "dynamic loading" capability to use it with other modules if you want to drive MOOSE-based applications with Python. If we have a customer for this, we'll revisit this at a later date.

**Comment by alfoa** [comment]
I think we should discuss about this on Friday as well.

I will schedule a meeting with all the people mentioned in this PR.

Thank you.

**Comment by permcody** [comment]
Friday may be bad for me, CASL review meeting all day that I may be in and out of. Are you available at all tomorrow to talk? We could probably meet briefly and decide if we need a full meeting.

**Comment by alfoa** [comment]
I am at the ANS meeting.. I will be back in IF at 9.30pm on Thursday.

**Pull request closed without merging**
