### PR TITLE
Update Atom documentation

### LINKED ISSUE #12089: Update rtags / Atom documentation
## Rationale

The documentation for setting up rtags to index MOOSE is outdated.

## Description

Describe the correct way to generate a `compile_commands.json` file

## Impact

Fix outdated docs

### PR DESCRIPTION
**Pull request by dschwen**
Update the rtags database initialization. Rename page.

Closes #12089

### CODE REVIEW

**Review by aeslaughter — CHANGES_REQUESTED** [review]
please don't put spaces in filenames

**Comment by dschwen** [comment]
Why not?

**Review by aeslaughter — APPROVED** [review]

**Comment by andrsd** [comment]
> Why not?

If the reason was discussed offline, I would like to know as well. Somebody will do that in RELAP, so it would be nice to know why. Is that a limitation of MOOSEDocs?

**Comment by aeslaughter** [comment]
@andrsd I just don't like them, I would also love to keep all paths lower case, but I didn't want to fight it. You can do what they want in RELAP, there is no technical reason why it would not work in MooseDocs.

**Comment by permcody** [comment]
Well let’s take a step back and look at the reason why some want them.
Because they want the spaces rendered, correct? Why not make Moose docs
just do that? We already have a pretty well hardened RE that does all of
the proper camel casing to break out words. We should be able to make
everyone happy here.

**Comment by dschwen** [comment]
I wouldn't want camel case to be broken up (after all that would render MooseObject names the wrong way). We could simply do `s/_/ /g` though (in the search results list for example).

**Comment by dschwen** [comment]
f7f66e940f

**Pull request merged**
