### PR TITLE
Deprecate DiracKernel contact

### PR DESCRIPTION
**Pull request by bwspenc**
ref #7283

### CODE REVIEW

**Comment by dschwen** [comment]
Deprecation warnings cause tests to fail! You need to fix the tests before this will pass (or add the _allow deprecated_ parameter in the tests files).

**Comment by bwspenc** [comment]
@dschwen Yeah, I'm working on them.  I'm curious why I'm only hitting that on linux/debug.

**Comment by bwspenc** [comment]
I looked into why the tests are failing, and the two that are timing out run way slower after I converted them to run with Constraint contact.  I though it might be something to do with having more entries in the matrix, but I did some profiling, and found that almost all of the extra time is spent in the `fe.reinit()` that gets called from `NonlinearSystem::constraintResiduals()`.  The cases I looked at use HEX20 elements and are really contact-heavy (not many other elements relative to the number of contact interactions).  I'm not sure whether this is something specific to those element types, and I also suspect that this is not such a big problem on more realistic models.

Thoughts on this @permcody or @friedmud?  Does that surprise you that `fe.reinit()` is so slow?

**Comment by permcody** [comment]
Element reinit comes up a lot. There are probably places to optimize but
it's an expensive part of the computation. As you pointed out, it might not
be so bad when your physics are more complicated.

**Comment by friedmud** [comment]
Not surprising to me, see here: https://github.com/libMesh/libmesh/issues/890

What is surprising is that we must be doing a lot more of it in the new contact system vs the old.  Can you explain the differences between the two systems?

**Comment by dschwen** [comment]
@bwspenc, this should probably be closed and reopened once we get serious about that deprecation. It's been sitting here for almost a year now (and has accumulated a whole bunch of conflicts by now).

**Comment by permcody** [comment]
Closing due to inactivity.

**Pull request closed without merging**
