### PR TITLE
Mortar with tensor mechanics test shortening

### PR DESCRIPTION
**Pull request by tophmatthews**
Starts simulations after first "bounce" for 2d.
Increases dt for 2drz meshes from 0.1 to 0.25.
Ref #13080

### CODE REVIEW

**Comment by tophmatthews** [comment]
ping @lindsayad

**Comment by lindsayad** [comment]
Looks like there’s some failures in heavy still :-(

One thing I could do is time/profile these tests that were timing out with sparse and a larger container non-sparse and check and see whether the latter would be faster. I know I showed you that one input that ran the same but I don’t know a priori whether that would be the same for all the inputs here.

**Comment by tophmatthews** [comment]
ay, chihuahua. It's failing legit this time.

**Comment by tophmatthews** [comment]
Give that a try @lindsayad . What would be really nice is a "soft" limit on some of these tests so I know when things are close to the "hard" limit...but that's another conversation

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
