### PR TITLE
Added new documentation for the new phase field module actions

### LINKED ISSUE #9814: Add documentation for the new phase field actions
### Description of the enhancement or error report
The new phase field module actions need documentation.

### Rationale for the enhancement or information for reproducing the error
The new phase field module actions were not documented.

### Identified impact
This will only add documentation and change some examples to use the new syntax.

### PR DESCRIPTION
**Pull request by tonkmr**
I added documentation for the new phase field actions. I also changed some of the examples to use it. Closes #9814.

### CODE REVIEW

**Comment by tonkmr** [comment]
These are the first documented actions, and I'm not sure if there is anything else I need to add to other files.

**Comment by permcody** [comment]
Tag @aeslaughter - I'm not very good at identifying the syntax problems in Docs yet. Can you take a look at this PR and let Mike know how to fix?

**Comment by aeslaughter** [comment]
There are a few things that need to change with respect to where the files are being stored. I will fix it up for you.

**Comment by tonkmr** [comment]
@aeslaughter are you handling all the changes or do I need to change something?

**Comment by aeslaughter** [comment]
@tonkmr I submitted a PR to your branch: https://github.com/tonkmr/moose/pull/1

**Comment by aeslaughter** [comment]
@tonkmr I will take care of the failure.

**Comment by permcody** [comment]
Ping @aeslaughter - This is right at the 30 day limit. Looks like you were going to fix something here?

**Comment by aeslaughter** [comment]
@permcody I forgot about this, I will get back to it next week.

**Comment by aeslaughter** [comment]
Closed in favor of #10137

**Pull request closed without merging**
