### PR TITLE
Add --enable-march to libmesh build script

### PR DESCRIPTION
**Pull request by brianmoose**
Just to see how this affects timing

### CODE REVIEW

**Comment by brianmoose** [comment]
@jwpeterson and @permcody

**Review by jwpeterson — DISMISSED** [review]

**Comment by jwpeterson** [comment]
@permcody the timings with `-march` auto-detected and `-march=native` weren't much different. ```
```
http://mooseframework.inl.gov/docs/PRs/11771/timing/
```
The relevant hashes in the plots are 9b3af27 and b2c1e21814

**Comment by permcody** [comment]
Well that's a bummer. Maybe @friedmud has some input here.

**Comment by permcody** [comment]
Ping @friedmud - Looking for a few suggestions. It looks like adding the march flag hasn't done any good on our benchmark tests..

**Pull request closed without merging**
