### PR TITLE
Contact Verification: Overclosure Problem

### LINKED ISSUE #9021: Overclosure Removal Test
### Description of the enhancement or error report
Regression test to demonstrate that MechanicalContactConstraint is capable of removing the initial overclosure.

### Rationale for the enhancement or information for reproducing the error
Expand code's testing

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by zahom**
Closes #9021

### CODE REVIEW

**Comment by dschwen** [comment]
Could you please give this a meaningful title (look at the other PRs we have open for guidance).

**Comment by dschwen** [comment]
I don't know which instructions you've read (please link them so they can be fixed), but http://mooseframework.org/wiki/Contributing/ states

> ## 3. Make Modifications
> Make your modifications and commit them to a branch (be sure to reference an Issue # in your commit messages.)
> ```
> git add your_file.h your_file.C
> git commit -m "A message about the commit
>
> closes #12345"
> ```

Note the _A message about the commit_. 

You should put the issue number you are referencing in the _body_ of the PR (as opposed to the title). That way GitHub links the issue and the PR and people can click through from one to the other. Also the issue will be closed automatically.

**Comment by bwspenc** [comment]
Something's going very wrong with that test on Intel Linux.  Everything looks OK initially, but then the residual starts getting very large, and then it's saying it's converged with a residual of something like 1e+35.  I'm not sure what's going on there...

**Comment by bwspenc** [comment]
@zahom I looked at the test diffs, and they are very small, and all involve components of stress.  I think I recall that you said that you were going to not even output stresses.  You could either turn off the output of stress, or adjust your tolerances so that these differences don't cause a diff.

**Review by bwspenc — APPROVED** [review]

**Pull request merged**
