### PR TITLE
geochemistry JOSS paper first draft.

### PR DESCRIPTION
**Pull request by WilkAndy**
Refs #16667

Hi @cpgr , @loganharbour  and @rpodgorney , this is the first draft of a JOSS paper.  It is MUCH TOO LONG (usually JOSS papers are about 3 pages long) but i wanted to get everything down before trimming

How to look at the paper:

1. goto https://whedon.theoj.org/
2. enter my repo https://github.com/WilkAndy/moose and branch  joss_geochem_16667
3. Hit "Compile Paper" and wait for a minute or so

TODO:

- [ ] various small TODO things marked in the document - Logan's ORCID, Rob's ORCID, Acknowledgement of funding
- [x] check bib items (probably lots of mistakes here)
- [x] check that paper contains all necessary ingredients: see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
- [x] intro overview for non-specialists
- [x] compare and contrast with other software
- [x] an example of a nice benchmark with GWB
- [x] a reactive-transport example - probably Weber Tensleep

a

### CODE REVIEW

**Comment by cpgr** [comment]
Hey @WilkAndy, did you want me to have a go at some of this. Perhaps the intro and some editing to reduce the length?

**Comment by WilkAndy** [comment]
> Hey @WilkAndy, did you want me to have a go at some of this. Perhaps the intro and some editing to reduce the length?

Thanks @cpgr.  Let me work on it for another day then you can take over.

**Comment by WilkAndy** [comment]
Hi @cpgr , @loganharbour and @rpodgorney , the first draft of the geochemistry JOSS paper is now ready for your review.  To see how it looks:

1. goto https://whedon.theoj.org/
2. enter my repo https://github.com/WilkAndy/moose and branch joss_geochem_16667
3. Hit "Compile Paper" and wait for a minute or so

Even if you haven't got time to review it thoroughly at this stage, please:

- @loganharbour - you must provide your ORCID
- @rpodgorney - you must check your ORCID and check the wording in the Acknowledgements section

**Comment by cpgr** [comment]
I'll take a look today Andy.

**Comment by WilkAndy** [comment]
Thanks @cpgr - i've incorporated all your changes with some minor mods.  Now it's up to you, @loganharbour and @rpodgorney (see above).

**Comment by loganharbour** [comment]
Great. This is on my list for Monday!

**Review by loganharbour — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks @loganharbour

**Pull request merged**
