### PR TITLE
Test recovery in PorousFlow

### PR DESCRIPTION
**Pull request by cpgr**
Recovery in PorousFlow was fixed in #13992 but it is not automatically tested. This test makes sure that it works for the problematic combination discussed in #12927.

Also add note to documentation about recovery

Refs #12927

### CODE REVIEW

**Review by permcody — APPROVED** [review]

**Comment by permcody** [comment]
Looks like your new recovery test gets a different answer on 2 proc. You may want to take another look at this. The porous-flow parallel targets are preventing things from merging into devel.

**Comment by cpgr** [comment]
I can't replicate this error on my mac running the tests in parallel. Any ideas to troubleshoot this?

**Comment by permcody** [comment]
Yeah - me neither. The error message from our CSV diff tool leaves a lot to be desired. It should be printing out specific differences, or at least a count. I'll login to a build system and see what the file looks like. I'll post it here when I have it.

**Comment by permcody** [comment]
@cpgr I ran an "sdiff" with the gold file on the left. Looks like there are a few missing nodes in the parallel run:

```
x,y,z,id,tracer							x,y,z,id,tracer
0,0,0,0,0							0,0,0,0,0
0.04,0,0,1,0							0.04,0,0,1,0
0.06,0,0,33,0							0.06,0,0,33,0
0.08,0,0,2,0							0.08,0,0,2,0
0.1,0,0,26,0.041090722809403				      |	0.1,0,0,26,0.041090722761608
0.11,0,0,35,0.11747123151709				      |	0.11,0,0,35,0.11747123137239
0.12,0,0,3,0.25337924122481				      |	0.12,0,0,3,0.25337924096608
0.13,0,0,36,0.39752285935256				      |	0.13,0,0,36,0.3975228590368
0.14,0,0,27,0.53643207630451				      |	0.14,0,0,27,0.53643207595679
0.15,0,0,37,0.66164743331333				      |	0.15,0,0,37,0.66164743296578
0.16,0,0,4,0.77073079758198				      |	0.16,0,0,4,0.77073079725791
0.17,0,0,38,0.85727042666044				      |	0.17,0,0,38,0.85727042638042
0.18,0,0,28,0.92035161638155				      |	0.18,0,0,28,0.92035161615794
0.19,0,0,39,0.96134144353413				      |	0.19,0,0,39,0.96134144334965
0.2,0,0,5,0.98500882802944				      |	0.2,0,0,5,0.98790300163242
0.21,0,0,40,0.99684567462473				      <
0.22,0,0,29,1							0.22,0,0,29,1
0.23,0,0,41,1						      <
0.24,0,0,6,1							0.24,0,0,6,1
0.25,0,0,42,1						      |	0.25,0,0,40,1
0.26,0,0,30,1							0.26,0,0,30,1
0.27,0,0,43,1						      |	0.27,0,0,41,1
0.28,0,0,7,1							0.28,0,0,7,1
0.29,0,0,44,0.98955829449576				      |	0.29,0,0,42,0.98955829451307
0.3,0,0,31,0.95824361388878				      |	0.3,0,0,31,0.95824361394384
0.31,0,0,45,0.88617980986808				      |	0.31,0,0,43,0.88617981000908
0.32,0,0,8,0.74808015388865				      |	0.32,0,0,8,0.74808015414572
0.33,0,0,46,0.60320647375815				      |	0.33,0,0,44,0.60320647407323
0.34,0,0,32,0.46385939475575				      |	0.34,0,0,32,0.4638593951034
0.35,0,0,47,0.34143150416031				      |	0.35,0,0,45,0.34143150453126
0.36,0,0,9,0.1994332634391				      |	0.36,0,0,9,0.1994332637511
0.38,0,0,34,0.086451484555185				      |	0.38,0,0,34,0.086451484769513
0.4,0,0,10,0.011130626723334				      |	0.4,0,0,10,0.011130626822749
0.44,0,0,11,6.8277337547867e-16				      |	0.44,0,0,11,3.9756733572781e-16
0.48,0,0,12,1.8433950127572e-16				      |	0.48,0,0,12,1.0693127416734e-16
0.52,0,0,13,8.7037121539588e-22				      |	0.52,0,0,13,7.4797477942872e-22
0.56,0,0,14,9.2342929345112e-23				      |	0.56,0,0,14,8.3956119596502e-23
0.6,0,0,15,-5.9103226065816e-24				      |	0.6,0,0,15,-5.9918132879721e-24
0.64,0,0,16,-3.6785857368551e-24			      |	0.64,0,0,16,-4.0375220824853e-24
0.68,0,0,17,-8.8525700931033e-25			      |	0.68,0,0,17,-5.9214298523332e-25
0.72,0,0,18,1.3208736300432e-27				      |	0.72,0,0,18,-3.2455534873521e-27
0.76,0,0,19,8.1999887185799e-28				      |	0.76,0,0,19,-7.4033161229878e-29
0.8,0,0,20,1.9467154900232e-28				      |	0.8,0,0,20,3.1684289927431e-28
0.84,0,0,21,2.0417530181838e-31				      |	0.84,0,0,21,7.9264078246973e-29
0.88,0,0,22,1.274002351587e-32				      |	0.88,0,0,22,1.1015424339154e-32
0.92,0,0,23,7.6891371551122e-34				      |	0.92,0,0,23,6.6480022508654e-34
0.96,0,0,24,6.2289005572036e-35				      |	0.96,0,0,24,5.3879206376143e-35
1,0,0,25,3.2880767814885e-40				      |	1,0,0,25,2.7208732021673e-40
```

**Comment by permcody** [comment]
I opened up the tilmestep before "0003" and noticed a few odd values when running in parallel (note these values did not appear in serial):

```
x,y,z,id,tracer
0,0,0,0,0
0.04,0,0,1,0
0.06,0,0,33,0
0.08,0,0,2,0
0.09,0,0,35,0.031304253939768
0.1,0,0,26,0.093891906268191
0.11,0,0,36,0.22350945221229
0.12,0,0,3,0.39326516881727
0.13,0,0,37,0.54152247743658
0.14,0,0,27,0.67258793639195
0.15,0,0,38,0.77989760980103
0.16,0,0,4,0.87164724870583
0.17,0,0,39,0.93246299532432
0.18,0,0,28,0.97165228557706
0.19,0,0,40,0.99125567500748
0.2,0,0,5,1.0000000000001
0.21,0,0,41,1.0000000000001
0.22,0,0,29,1
0.23,0,0,42,1.0000000000001
0.24,0,0,6,0.99999999999999
0.25,0,0,43,0.99999999999999
0.26,0,0,30,1
0.27,0,0,44,1
0.28,0,0,7,1
0.29,0,0,45,0.9686957460919
0.3,0,0,31,0.90610809382264
0.31,0,0,46,0.77649054799538
0.32,0,0,8,0.60673483152586
0.33,0,0,47,0.4584775229757
0.34,0,0,32,0.32741206403782
0.35,0,0,48,0.2178016629148
0.36,0,0,9,0.10486234083334
0.38,0,0,34,0.037263898320744
0.4,0,0,10,0.0011537386191372
0.44,0,0,11,3.2502477349791e-16
0.48,0,0,12,8.0225348546426e-17
0.52,0,0,13,5.8213595329696e-22
0.56,0,0,14,6.1491600893192e-23
0.6,0,0,15,-5.9918132880318e-24
0.64,0,0,16,-3.1191952206692e-24
0.68,0,0,17,-1.482355945367e-26
0.72,0,0,18,-2.453465493657e-27
0.76,0,0,19,2.3588232525827e-29
0.8,0,0,20,3.1684289927748e-28
0.84,0,0,21,1.3523609815566e-31
0.88,0,0,22,8.4303533806637e-33
0.92,0,0,23,5.12222548025e-34
0.96,0,0,24,4.042292907532e-35
1,0,0,25,2.7208732021975e-40
```

With that in mind your Marker isn't going to mark those values that are > 1.0. I was able to work around this issue by changing the upper_bound in the file to 1.01. Then all the tests pass.

There's some sort of tolerance issue with the Marker. I tried putting in an "upper_bound" of 1.01 and the test passed in parallel. In fact even in

**Comment by permcody** [comment]
One final note: The solver history is pretty bad in parallel, you can see how much the solver struggles to reach your tolerance versus the serial case for the third time step. Hopefully that's enough info to make the adjustments you need to make to get this passing!

**Comment by cpgr** [comment]
I'll try and fix this up. I won't be able to get to it today or tomorrow though, so you might want to revert this until I can fix it properly. Thanks for the diagnositics!

**Comment by permcody** [comment]
Ok - I'll revert.

**Pull request merged**
