### PR TITLE
Renamed warn_unused to allow_unused #22052

### LINKED ISSUE #22052: More command line allow options
## Reason
--allow-unused (I dont even want a warning, let me comment out my things in peace)
--allow-warnings to override an app setting

## Design
More command line options

## Impact
Quality of life improvement

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #22052

### CODE REVIEW

**Comment by GiudGiud** [comment]
no objection @loganharbour @permcody ?

**Review by permcody — COMMENTED** [review]
This seems fine to me. De we still have `--error-unused` though? I realize that's the default, but in the case it's not, what do we do to explicitly turn it on?

**Comment by GiudGiud** [comment]
yes we have really good conversions into errors in my mind. It s the opposite, the --allow that are lacking
```
  --error                                           Turn all warnings into errors
  --error-deprecated                                Turn deprecated code messages into Errors
  -o --error-override                               Error when encountering overridden or parameters supplied multiple times
  -e --error-unused                                 Error when encountering unused input file options
```

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
thx for the PR!

**Pull request merged**
