### PR TITLE
Training fixes

### LINKED ISSUE #27282: Several typos exist in the standard MOOSE workshop
### Bug Description

While at the Oregon State training, several typos were discovered. This PR should serve as a catch-all to fix those typos. 

### Steps to Reproduce

View the training, see the typos. 

### Impact

An annoyance, and a confusion to new users. 

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by cticenhour**
Closes #27282

Tag @permcody

### CODE REVIEW

**Comment by roystgnr** [comment]
Turning this into a catchall thread, at the request of @cticenhour on Slack:

Issues in the C++ section:

- In "Scope" we should omit mention of dynamic memory allocation; nobody who needs to be told about new should be using new - we should be teaching them about smart pointers (and also mentioning heap-using containers) in "Dynamic Memory in C++" instead.  Likewise we should update "Variable Initialization" later.

- "References are Safe" is an evil lie - references are safe when they're first made but they can become unsafe at any time the referenced memory is lost to free/delete/stack-shrinkage.

- In the "Object Oriented Design" page I'd specify "*run-time* polymorphism", though we do make the distinction clear in the summary later.

My own disagreements:

- "Do not use auto in any kind of function or method declaration" is IMHO outdated; C++ return type deduction started to get good in C++14, got better in 17, and is a great idea when limited to templated code ... though personally I'd attach that same caveat to all other uses of auto; if you can determine the type of a variable when writing the code IMHO you're doing future readers a favor by spelling it out.

Opportunities for more-modern-C++ updates:

- Talking about range-for (and the libMesh helpers for it) in the Control Statements page would be good, since we use that a lot.  So would putting an initializer in an if(), since we (at least I) don't use that improved scoping opportunity nearly enough yet.

- "Const" should be updated to mention constexpr, maybe with an `if constexpr` example too.

- The bit on lambdas should have a generic-lambda (with auto input/output types) example.

- We might mention rvalue and universal references, not to encourage people new-to-C++ to write them but to make sure they're not flabbergasted when they read them.

- "Variable Initialization" should have some initializer-list and uniform-initialization examples, as well as a structured binding.

- We could put explicitly-deleted and explicitly-defaulted constructors and assignment operators on the page for one of those.

- The STL page should be renamed to "standard library containers" or something; the old STL has been folded into the standard library since 1998.  And it should be updated to mention tuple, pair, unordered_map...

I'll leave this comment here for a while, to let people express any disagreements (or add anything I missed), before I start tweaking any Markdown pages.

**Comment by cticenhour** [comment]
Tagging @permcody, @loganharbour, and @dschwen for comment on any C++ fundamentals changes. See @roystgnr's comment previously in this thread.

**Comment by roystgnr** [comment]
> a while, to let people express any disagreements (or add anything I missed)

That should be enough time to establish that there are no disagreements and I haven't missed anything; I'll start pushing draft changes shortly.

More seriously, I'll break them up into several commits, just in case the actual edits get more pushback than hand-wavy critique did.

**Comment by permcody** [comment]
@roystgnr, I agree with all of your comments. I don't believe we've made any substantial changes to the C++ content for at least 10 years. We only made minor changes when we moved to C++11 and we should have made more sweeping changes then. Even your comments on `auto` are fine. I think most of us have evolved our thinking on that since it was first introduced. In fact, I'll admit that I've done a complete 180 on the subject. When `auto` was first introduced, I remember discussing an outright ban on the keyword with the team. Of course we didn't go with that, but we did recommend heavily against using it. Now after fixing many bugs related to implicit conversions over the years (usually because programmers don't really know the types they receive from various methods - especially library methods, or they don't really think it matters all that much). `auto` solves a lot of those kinds of issues.

**Comment by permcody** [comment]
> if you can determine the type of a variable when writing the code IMHO you're doing future readers a favor by spelling it out.

Actually, I might disagree with this even though I know your intent is good. The problem is that many programmers (or should I say "programming engineers") don't really give as much consideration to things like overflow as I'd like. We've had to fix more than a few bugs with 32-bit integer overflows when used in large data structures over the years just due to carelessness and implicit conversion issues. If your programmers don't know a type (or won't look it up). I'd much rather see `auto` than spend hours tracking down some bug at scale.

**Comment by roystgnr** [comment]
> If your programmers don't know a type (or won't look it up). I'd much rather see auto than spend hours tracking down some bug at scale.

Ha!  This is remarkably close [to what I ended up writing](https://github.com/idaholab/moose/pull/27283/commits/f35206092c21594321e5891d75fada74490974c5#diff-31af1a7ac6215f518bc1a5b5104ee5ac5972eb58f1cc0f106df1abfc51b019feR129-R134).  After some thought, while I still agree with the "if you can determine the type of a variable, don't use auto" philosophy, adding the caveat that "if you're calling a non-`std` library function returning a non-class type then they might upgrade the type in the future" makes its applicability a lot more niche.

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
