### PR TITLE
Replace NodalMaxValue by NodalExtremeValue. 

### LINKED ISSUE #18937: NodalMaxValue duplicates NodalExtremeValue
## Reason
`NodalMaxValue` is exactly the same as `NodalExtremeValue` (but less general). The available postprocessors can be simplified by removing `NodalMaxValue`.

## Design
Remove `NodalMaxValue` and replace by `NodalExtremeValue`.

## Impact
Applications will eventually need to update to use `NodalExtremeValue`.

### PR DESCRIPTION
**Pull request by aprilnovak**
This PR replaces `NodalMaxValue` by `NodalExtremeValue` in the tests and adds a deprecation tag for `NodalMaxValue`.

## Reason
Clean up code base.

## Design
I didn't want to delete any tests, so I just moved the tests that were in the `nodal_max_value` directory into the `nodal_extreme_value` directory. I also deleted two input files in `nodal_extreme_value` directory that weren't used in the tests at all - I assume their existence is an oversight?

## Impact
Applications will now get a warning message that they should update to `NodalExtremeValue`.

Closes #18937

### CODE REVIEW

**Comment by GiudGiud** [comment]
One day we will have NodalParsedValue

**Comment by GiudGiud** [comment]
This is great though thanks for cleaning that up

**Review by loganharbour — CHANGES_REQUESTED** [review]
We should probably retain the old testing until the object is removed

**Comment by loganharbour** [comment]
> Good point - I put `NodalMaxValue` back into the postprocessor tests (but kept the other changes in miscellaneous tests that weren't explicitly testing `NodalMaxValue`). If you'd prefer I just entirely undo any changes related to tests I can do that instead.

As long as we have one test sitting around testing the old behavior with some coverage that should be sufficient!

**Comment by aprilnovak** [comment]
Great, thanks for the feedback! This should be good now.

**Comment by loganharbour** [comment]
Looks like you need to rebase

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
