### PR TITLE
Update libMesh ... yes, again

### LINKED ISSUE #17240: Add support for writing constant elemental vectors to elements in exofiles
## Reason
There is currently no support for writing `CONSTANT MONOMIAL_VEC` variables to the elements in ExodusII files in neither LibMesh nor the framework. They are always written out to the nodes, which, to an unwitting user, may seem contradictory to MOOSE documentation about how constant monomials are treated as elemental variables. 

## Design
This feature must be developed in libMesh `ExodusII_IO::write_element_data`. In MOOSE, we currently do not call this function for CONTANT, MONOMIAL_VECs. Instead, we call its nodal variable counterpart. Thus, compatibility can be added retroactively pending a LibMesh update with libMesh/libmesh#2873, assuming that it doesn't cause any regression. I think the only source code that will need to be modified will be `AdvancedOutput`.

## Impact
Exodus files output from MOOSE will show constant elemental vector variables on elements by default.

(refs #14542)

### PR DESCRIPTION
**Pull request by roystgnr**
Summary of changes:

  - Add elem_num_map and node_num_map accessors to ExodusII_IO
  - Make FEMap::map_fe_type usable outside library
  - Set next unique id in copy_nodes_and_elements
  - Disable HDF5 file locking unless the user insists
  - Error if trying to build ambiguous variable names

Refs #0

Yes, this is a very frequent follow up after the last update.  We didn't
want to tack more commits onto what was already a very tricky update,
but we also ran across a few serious bugs whose fixes are listed above.

Closes #18833
Closes #17240

### CODE REVIEW

**Review by milljm — DISMISSED** [review]
Conda recipe changes look good.

As soon as this is merged in to next, please inform me (especially if you need this version available to fix other applications that may depend on it)

**Comment by lindsayad** [comment]
Haha it looks like your duplicate variable check is doing its job!!

**Comment by roystgnr** [comment]
> Haha it looks like your duplicate variable check is doing its job!!

I'll want to look into things before being proud of myself.  My first crack at the check had a bug and tripped some false positives.

**Comment by roystgnr** [comment]
> My first crack at the check had a bug and tripped some false positives.

And yet these definitely don't look like false positives, they're straight-up "`velocity` as a vector variable, `velocity_x` etc. as scalars".  Nice!  I'll start tacking on fixes here.

**Comment by lindsayad** [comment]
@roystgnr maybe you can cherry-pick what @crswong888 has done in #18833 ? Maybe we can then just close #18833 ?

**Comment by roystgnr** [comment]
:-P

I just finished testing my fix, and it works, but his fix is better.  Yeah, I'll cherry-pick that.

**Comment by crswong888** [comment]
can we add a (closes #18833) somewhere in here?

**Comment by roystgnr** [comment]
Adding "closes" tags to the PR description should be good enough, right?

On an unrelated note, what the heck is
```
Could not write out repodata file '/opt/civet/build_1/conda_builds/conda_envs/pr-18831/.pkgs/cache/8e770d10.json': No such file or directory
```
coming from?  @milljm?

**Comment by crswong888** [comment]
> Adding "closes" tags to the PR description should be good enough, right?

@roystgnr actually it looks like it only works for issues, so I guess #18833 has to be closed manually (which I’ll handle). You can delete that tag if you want.

**Comment by roystgnr** [comment]
Looks like we're good to go, whenever someone has time to review?

**Comment by roystgnr** [comment]
Except ... where is that "Failed but Allowed" coming from?  I'm seeing 32 checks passed, none failed.

**Comment by roystgnr** [comment]
This is because some random thread reordering led me to miss 4 lines of code coverage, isn't it?

**Comment by cticenhour** [comment]
@roystgnr Submodule update fails but is allowed in Precheck.

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
@roystgnr please merge at your leisure

**Review by loganharbour — APPROVED** [review]

**Comment by milljm** [comment]
Let me know if any of you believe this package should be placed in the 'next' Conda channel (will a third party app require this before being available in public).

**Pull request merged**
