### PR TITLE
Using executioner to determine if multiapp converged in STM transfer

### PR DESCRIPTION
**Pull request by zachmprince**
Refs #22512

### CODE REVIEW

**Comment by grmnptr** [comment]
Why is this change necessary? Does the old implementation cause unexpected behavior?

**Comment by YaqiWang** [comment]
> Why is this change necessary? Does the old implementation cause unexpected behavior?

The old one only works with PJFNK solver. Even if we have fixed point iteration, checking problem converged is not enough.

**Comment by zachmprince** [comment]
> Why is this change necessary? Does the old implementation cause unexpected behavior?

The short answer is that we should match the check done [here](https://github.com/idaholab/moose/blob/2bdd493a71c37b4de92863d13e40d70b1e48a8da/framework/src/multiapps/FullSolveMultiApp.C#L131). The long answer is that before these changes, we used [SubProblem::converged()](https://github.com/idaholab/moose/blob/2bdd493a71c37b4de92863d13e40d70b1e48a8da/framework/include/problems/SubProblem.h#L98), which calls [NonlinearSystem::converged()](https://github.com/idaholab/moose/blob/2bdd493a71c37b4de92863d13e40d70b1e48a8da/framework/src/systems/NonlinearSystem.C#L339). However, some executioners, like those in Griffin, do not ever call `NonlinearSystem::solve()` so this check will return `false`. Therefore, it is a more comprehensive check to get it from the executioner.

**Review by GiudGiud — APPROVED** [review]

**Review by grmnptr — APPROVED** [review]

**Comment by YaqiWang** [comment]
@GiudGiud I guess we can merge this now?

**Comment by GiudGiud** [comment]
Merging is blocked right now due to deployment issues
@zachmprince is the assignee, he s in charge of merging once the necessary reviews have been performed (and they have)

**Pull request merged**
