### PR TITLE
Rank 2 tensor scalar auxkernel as a namespace and thermal expansion strains

### LINKED ISSUE #6484: Migrate Solid Mechanics postprocessors into Tensor Mechanics module
### Description of the enhancement
Several post processors exist in solid mechanics but not in tensor mechanics;  these post processors will be replicated in tensor mechanics.

### Rationale for the enhancement
As part of the migration to a single continuum mechanics module, these postprocessors need to be moved into tensor mechanics.

### Identified impact
Tests within modules will be updated (combined) / duplicated (solid mechanics) to use the Tensor Mechanics version of the postprocessors.  The postprocessors in solid mechanics will be left to avoid breaking apps; however, perhaps a deprecated flag ought to be added to the solid mechanics postprocessors?

### PR DESCRIPTION
**Pull request by sapitts**
### Relevant Design Changes

Namespaces are introduced to calculate scalar quantities for rank-2 tensors in both solid mechanics and in tensor mechanics, e.g. von Mises stress, and the auxkernels are updated to use these namespaces.  The namespace is necessary to allow these scalar quantities to be computed as materials, and these materials will be used in a later commit.   Refs #6787

The postprocessor `MaterialTensorIntegral` is migrated to tensor mechanics in this commit, yet the solid mechanics version is retained with the suffix SM because the `solid_mechanics/generalized_plane_strain` cases rely on another set of strain and stress calculators; this commit is already rather monstrous without including the generalized plane strain stress and strain material classes.  Closes #6484 

The calculation of thermal expansion strains in tensor_mechanics was corrected to align with solid_mechanics and moved to a new material class, `ComputeThermalExpansionEigenStrain`.  Refs #6848
### Test Cases

All of these changes were necessary to migrate the single `generalized_plane_strain/planestrain.i` test to tensor_mechanics.   The tests in `combined/solid_mechanics/hoop_stress` were also updated to use the new Tensor Mechanics namespace.  The `cavity_pressure` tests were changed to remove the zero thermal expansion coefficient used in the input file; the non-zero thermal expansion coefficient in the test `CylindricalRankTwoAux` was updated to use the `ComputeThermalExpansionEigenStrain`.

The new thermal expansion eigen strain changes the input syntax in a few applications.  I've attempted to maintain 'backward compatibility' in the new code through the use of a deprecated warning, and in doing so have demonstrated the downside of flagging deprecated as an error; this code will require an application patch for marmot. Refs #6923

### CODE REVIEW

**Comment by permcody** [comment]
I'm still thinking about how best to handle deprecating code during API changes now that some of our applications are using the `--error` flag permanently in their test suite. 

Potential ideas:
1. New targets to CIVET for just testing for deprecation with "failed but allowed" status 
2. @dschwen thinks that we should just not have deprecated code in tests and follow the "incompatible API change" update. 
3. Perhaps add a flag to the test harness called "allow deprecated" which we could toggle. If I added such a flag I would propose that it be a date, not a Boolean. I really don't want deprecated tests to stick around in the test suite for very long. Thoughts @idaholab/moose-developers?

**Comment by permcody** [comment]
Hmm, no comments from @idaholab/moose-developers...

I'm leaning towards option 3 above. We should allow deprecated code in our test suite but only for a short period of time. I think forcing the incompatible API change process for deprecating code kind of defeats the purpose. We might as well just not deprecate code and update the Apps and MOOSE simultaneously if we go that route.

**Comment by dschwen** [comment]
Does that mean we have **two** deprecation dates now? One where tests are passing and one where it ceases to function? Deprecated params don't take a deprecation date yet at all, do they?

**Comment by dschwen** [comment]
Actually we could make this a deprecated _on_ this date and have a fixed time window (3months?) after which the register call or addParam call becomes inactive, and a shorter time window (1week?) after which a warning is generated. This would give us one week where the merge would pass tests and apps could be updated.

**Comment by sapitts** [comment]
Is there something I can do to help keep the ball rolling on the deprecated parameter decision?  I could also remove the deprecated warning on the old thermal expansion input parameters to get this PR to pass Marmot, submit the required updates to marmot and bison, and then add in the deprecated warning in a separate later PR.  Thanks for the help!

**Comment by permcody** [comment]
@sapitts - I'll work on this right now. I'll implement Solution #3 for you since apparently nobody cares besides Daniel.

**Comment by sapitts** [comment]
Thank you @permcody

**Comment by friedmud** [comment]
I like option 3.

@dschwen has a decent idea... but I think that when we decide to deprecate something it needs to _immediately_ show as deprecated.

I really think that any deprecated code / parameters still need to be tested as long as they are in the code base.  So I think option 3 will allow us the most flexibility...

**Comment by sapitts** [comment]
@jasondhales would you mind reviewing the solid_mechanics changes to MaterialTensorCalculator with the new namespace util despite the tests failure on Intel please?  (Now I'll regret being overly picky about comments in the header file in power law creep...)

**Comment by jasondhales** [comment]
I'd be happy to do it.

On Tue, May 17, 2016 at 2:47 PM, Stephanie Pitts <notifications@github.com>
wrote:

> @jasondhales
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasondhales&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=koEvNDog5Nkfs4hrD-qBcCTrxlhwdng9l-PrqPiXlDo&s=-5TYvhyVe1c7xZAfurFmSbtaA0255TFM4uEOYaWt0vA&e=>
> would you mind reviewing the solid_mechanics changes to
> MaterialTensorCalculator with the new namespace util despite the tests
> failure on Intel please? (Now I'll regret being overly picky about comments
> in the header file in power law creep...)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_6937-23issuecomment-2D219848841&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=koEvNDog5Nkfs4hrD-qBcCTrxlhwdng9l-PrqPiXlDo&s=Klk7_HGaPNBoUcwhVwtL0exZBQetSbn97oktQFXgDY8&e=>
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by WilkAndy** [comment]
Please could someone write a blog or something else on moose framework.org to instruct us how to do the deprecation?  With examples.  I'm planning to deprecate the entire Richards module over the next year, so want to do it all properly.

**Comment by sapitts** [comment]
Finally this commit passes, thanks in large part to help from Cody with the new method of handling deprecation!  @dschwen would you please review the tensor mechanics classes?

@WilkAndy as a start [here](https://github.com/idaholab/moose/pull/7008) are the instructions Cody gave me on using the deprecated flag in this commit.

**Comment by permcody** [comment]
Done: http://mooseframework.org/blog/changing-a-published-api-deprecation/

**Comment by WilkAndy** [comment]
Thanks, i like what you've done re deprecation.

**Comment by permcody** [comment]
Closing this - We've solved this issue:
http://mooseframework.org/blog/changing-a-published-api-deprecation/

**Pull request merged**
