### PR TITLE
PorousFlow: groundwater doco

### PR DESCRIPTION
**Pull request by WilkAndy**
start of groundwater_models.md.   Refs #15921

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hi @milljm - not sure if this is "your thing" or not, but there is a YAML failure in "Python 3.7 Tests" that is unrelated to this PR

**Comment by milljm** [comment]
@WilkAndy I am currently working on Civet... Fixing an odd issue with Conda re-initialization.

**Comment by WilkAndy** [comment]
Aha, no probs, thanks for letting me know @milljm .   If you remember, just invalidate the precheck for this PR when you've finished.

**Comment by WilkAndy** [comment]
Hi @hsheldon , 

I'm wondering whether you'd have time to review this documentation.  If not, please tell me and someone else will do it.

This PR focuses on describing how to do groundwater modelling with PorousFlow.  There are a few example input files and figures, but the main contribution is the single documentation page (which includes those input files and figures):

https://mooseframework.inl.gov/docs/PRs/15924/site/modules/porous_flow/groundwater_models.html

Feel free to read the markdown documentation and input files in detail, but probably your focus should be just on the above link.  It has already been revised many times by Maelle and myself, so is hopefully near perfect.

a

**Comment by WilkAndy** [comment]
Hey @hsheldon , just wondering whether you will have time for this review?  If not, that's fine, someone else will do it.

**Comment by hsheldon** [comment]
> Hey @hsheldon , just wondering whether you will have time for this review? If not, that's fine, someone else will do it.

Sorry I'm a bit bogged down at the moment - prefer if you find someone else please.

**Comment by WilkAndy** [comment]
@aeslaughter , would you like to review this, or nominate someone else?  It's just a fairly long documentation page along with some examples.

**Comment by WilkAndy** [comment]
Hey @aeslaughter - just requesting a review of this doco.  The PR doesn't pass at the moment due to "Private App tests", but i can't invalidate that as i'm not privileged enough.

**Review by aeslaughter — APPROVED** [review]

**Comment by WilkAndy** [comment]
Hi,

Can someone invalidate the Private App tests so that this can be merged?

**Comment by WilkAndy** [comment]
OK, strange.... I don't know how documentation changes should impact "Private App tests".

**Comment by aeslaughter** [comment]
We are in the middle of integrating changes into some applications, the failure is unrelated.

**Comment by WilkAndy** [comment]
Thanks for the review and merge, @aeslaughter

**Pull request merged**
