### PR TITLE
Font proposal

### PR DESCRIPTION
**Pull request by bwspenc**
#9638

- Switches from 16pt to 18pt
- Undoes the setting of the sans-serif font to Roboto and uses the default
  sans-serif font, which I think is always Helevetica or something like it.

### CODE REVIEW

**Comment by bwspenc** [comment]
This may not be the right way to do this in css, but I'd like to get people's take on whether they think this is more readable once the doc page gets built from this PR.
@sapitts @aeslaughter @dschwen @friedmud @permcody

**Comment by bwspenc** [comment]
The idea here is to undo what is done in setting the sans-serif font to Roboto in materialize.min.css.

**Comment by bwspenc** [comment]
I happen to be a big fan of Helvetica.  I even made it most of the way through the movie without falling asleep a few years back.
https://en.wikipedia.org/wiki/Helvetica_(film)

**Comment by friedmud** [comment]
Font is too big.  Here is a screenshot on a 15" MBP comparing this PR to the New York Times...

screen shot 2018-04-20 at 3 26 17 pm

**Comment by aeslaughter** [comment]
You also need to remove roboto from the framework/doc/content/contrib

**Comment by bwspenc** [comment]
@friedmud I could go either way on the size.  I think even at the smaller size, this font face is more readable.

**Comment by friedmud** [comment]
Sure - font doesn't matter to me.  This one looks fine.  Just the size is too big.

**Comment by aeslaughter** [comment]
@bwspenc I will merge if you put the font-size back to 16 and remove Roboto from contrib

**Comment by dschwen** [comment]
How about we let this stew a bit?

**Comment by rwcarlsen** [comment]
w.r.t. the nyt, it doesn't seem way to big - it is nearly the same - just a smidge bigger.

**Comment by bwspenc** [comment]
This latest update only changes the font face, and leaves the size alone. Let's see how this one looks to everyone.  @aeslaughter I removed the roboto font files.  The materialize css does still reference that font, so if someone removes the line that unsets the sans-serif font, that may cause problems if the font they are setting it to isn't available.

**Comment by sapitts** [comment]
I'm in favor of this font size change to 18pt, and I think I like the font type for the paragraph texts (not sure about the headings, but it's not aweful). 

Is it possible to set the column width to a certain number of characters? In the screen shot comparing our documentation to nyt, nyt seems to have shorter text column width compared to our docs.

**Comment by bwspenc** [comment]
@sapitts I like the suggestion of shorter rows. For what it's worth, it looks like the Elsevier journals use Helvetica and shorter rows than what we're using in their HTML versions of journal articles. I also think they're using 18 pt font, but not completely sure on that. Look at this for example:
https://doi.org/10.1016/j.jmps.2018.01.008

**Comment by bwspenc** [comment]
It looks like the link to the doc build with this PR is still using the 18 point font even though I set that back to 16. Not sure what's going on there. Also, on closer inspection, those Elsevier journal articles are using 16 point font.  The box I'm typing this in on GitHub also looks like it's using 16 pt Helvetica, which looks pretty good.

**Comment by dschwen** [comment]
I would argue that Helveticva offers no readability benefit over Roboto. Both types have a very similar weight. Btw. http:://inl/gov uses Roboto for paragraph text.

**Comment by aeslaughter** [comment]
Well, just to throw some fuel on the fire. I would like something more like the [example](https://codepen.io/aeslaughter/pen/GdqyYR), but there are all sorts of good options from [Google Fonts](https://fonts.google.com/).

My reasoning for a serif font for the body is based on how I envision the content of the website. The end goal is to essentially have a book, books use serif font and I believe they are easier to read for large blocks of text. The title in sans serif font just helps set it apart.

**Comment by dschwen** [comment]
@aeslaughter I totally and violently agree with your proposal.

**Comment by andrsd** [comment]
> ...and I believe they are easier to read for large blocks of text.

To stir the pot a little more. This is subjective and depends on a personal taste. Some latest research shows that [there is no significant difference between serif vs sans-serif](https://ux.stackexchange.com/questions/60424/serif-vs-sans-serif).

I personally do not care about this that much. As long as we are __not__ using Times New Roman, which is just horrible 😈

**Comment by friedmud** [comment]
I'm actually completely happy with the way the website currently looks on this PR.  The 16pt, sans-serif looks just about right.

The only thing I see is that code boxes need just a bit more space below them.

**Comment by bwspenc** [comment]
I'm not sure this is needed either.  The small text in the command descriptions is hard to read, but I looked at that a little bit with @dschwen, and it looks like that's just because they're using a really low font weight. I'm closing this PR.

**Pull request closed without merging**
