### PR TITLE
PorousFlow tests added

### PR DESCRIPTION
**Pull request by WilkAndy**
These are all the tests except the ones involving DiracKernels that @cpgr is going to add.
Also a bug-fix in PorousFlowJoiner

Refs #6845

### CODE REVIEW

**Comment by WilkAndy** [comment]
@dschwen - almost 10k lines for you to inspect.  Heheheh, enjoy yourself.

a

**Comment by permcody** [comment]
Only one line of source changed! Actually thanks for breaking this out. It makes it "easy" to review if it's all tests and outputs.

**Comment by permcody** [comment]
👍

**Comment by WilkAndy** [comment]
Thanks @permcody,

a

**Pull request merged**
